### ISSUE TITLE
Touch Events when Mixing XAML (With Project and Video repro)

### ISSUE THREAD

**Issue by jakepoz** [MonoGame/MonoGame#1006]
We found when mixing in XAML controls on a Windows 8 project, ex. for a user to enter in their name for a high score, some touch events are getting lost, and monogame start reporting many unreleased touch events.

It appears as if the Core window is not getting PointerReleased Events that correspond to previously seen PointerPressedEvents.

Sample Project: https://dl.dropbox.com/u/14806845/XamlTouchFailure.zip

Video reproduction: https://skydrive.live.com/redir?resid=B3EDB6535B9680C2!770&authkey=!ADy8odmkyUx7-Tc

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
