### ISSUE TITLE
[Windows 8] Visual flickering on WinRT

### ISSUE THREAD

**Issue by deadlydog** [MonoGame/MonoGame#1039]
Hi, I previously converted DPSF over to support running on Android using DPSF (awesome!) and am now trying to do the same for WinRT.  I have it working and the particles show up, but all of the particles flicker (disappear and reappear quickly) A LOT.  They flicker both when I run the app in the "Simulator" and "Local Machine" mode.  I've tried using the latest dlls from the CodePlex download as well as pulling the latest code from the develop3d branch, both produce the same results.  Any ideas as to what is wrong?  Thanks!

**Comment by tgjones** [comment]
This was fixed by #1354?

**Comment by Shqrdx** [comment]
@tomspilman This issue is outdated, the author of DPSF should recompile his library to MG3.3 and than recreated this issue. I couldnt even compile his demo, because of incorrect MG and SharpDX versions.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
