### ISSUE TITLE
WP8 Template stuck at loading screen

### ISSUE THREAD

**Issue by CodeHelix** [MonoGame/MonoGame#1051]
I was testing out the template for WP8 but it won't get past the loading screen. Is there something else I need to do so it will show the default Cornflower Blue screen? Also how do I get it where the app will show up in the Games hub? Also when I run it stops and says a navigation has failed and when I have it continue I get this exception:

System.Reflection.TargetInvocationException was unhandled
Message: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in System.Windows.ni.dll

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
