### ISSUE TITLE
Windows 8 , MGFX: Textures need to be referenced in order or weird things happen?

### ISSUE THREAD

**Issue by WaaghMan** [MonoGame/MonoGame#1070]
In a shader that has these textures defined:

```
texture BaseTexture: TEXTURE0;

sampler2D Texture0 = sampler_state
{
    Texture = (BaseTexture);
    MipFilter = LINEAR;
    MagFilter = LINEAR;
    MinFilter = Anisotropic;
    MaxAnisotropy = 2;
    AddressU = WRAP;
    AddressV = WRAP;
};

texture LightmapTexture: TEXTURE1;

sampler2D Texture1 = sampler_state
{
    Texture = (LightmapTexture);
    MipFilter = LINEAR;
    MagFilter = LINEAR;
    MinFilter = LINEAR;
    AddressU = CLAMP;
    AddressV = CLAMP;
};
```

And this pixel shader code (and more):

```
...
 float4 LightmapColor = tex2D(Texture1,IN.UV2);
 float4 DiffuseColor = tex2D(Texture0,IN.UV);

 DiffuseColor *= LightmapColor * 2;
...
```

The DiffuseColor texture address mode is incorrectly set to Clamp.
If I switch the order they are referenced in the pixel shader:

```
...
 float4 DiffuseColor = tex2D(Texture0,IN.UV);
 float4 LightmapColor = tex2D(Texture1,IN.UV2);

 DiffuseColor *= LightmapColor * 2;
...
```

The shader works as expected (I think).

So, two possibilities here:
- The addressing mode is set to the value of the first referenced texture in the pixel shader.
- The textures really need to be referenced in order for some reason I didn't know.

**Comment by cra0zy** [comment]
Win 8 is no longer a supported platform so closing this.
