### ISSUE TITLE
RenderTarget2D not working on my Win8 ModernUI app.

### ISSUE THREAD

**Issue by kaosklown** [MonoGame/MonoGame#1096]
I created a simple project with the following code in the Draw() function, which should display a blue square on a Red BackGround, but instead I just get the Red BackGround...

"

GraphicsDevice.SetRenderTarget(_target);

GraphicsDevice.Clear(Color.CornflowerBlue);

GraphicsDevice.SetRenderTarget(null);

GraphicsDevice.Clear(Color.Red);

_spriteBatch.Begin();

_spriteBatch.Draw(_target, Vector2.Zero, Color.White);

_spriteBatch.Begin();

"
By the way, I create the renderTarget like this (placed in the end of the Initialize() function)
"
_target = new RenderTarget2D(GraphicsDevice, 256, 256, false, SurfaceFormat.Color, DepthFormat.None);
"

Thanks,

KaosKlown.

**Comment by cra0zy** [comment]
Win 8 is no longer a supported platform so closing this.
