### ISSUE TITLE
Xna.Framework.GraphicsDeviceInformation.DeviceType is invalid in XNA 4.0

### ISSUE THREAD

**Issue by pzgulyas** [MonoGame/MonoGame#1153]
XNA 4.0 uses Microsoft.Xna.Framework.GraphicsDeviceInformation.GraphicsProfile instead, which is unavailable in MonoGame.

**Comment by tomspilman** [comment]
Moving to the 3.6 release... we should cleanup this area of the code once and for all.

**Comment by cra0zy** [comment]
This got fixed a long time ago it seems XD
