### ISSUE TITLE
Ouya - Gamepad always returns true for isConnected

### ISSUE THREAD

**Issue by chaosnhatred** [MonoGame/MonoGame#1171]
In this issue https://github.com/mono/MonoGame/issues/1170
it was noted that Android will always return true for isConnected for the Gamepad.

As Ouya heavily relies on controllers, this may need to change for that platform as to implement the Gamepad API for its detection.

As i am aware the Gamepad API is not Needed, but for this issue it might need to be implemented anyway.

**Comment by cra0zy** [comment]
@tomspilman Ouya has been removed, this can be closed.

**Comment by tomspilman** [comment]
Thanks @cra0zy !
