### ISSUE TITLE
SpriteBatch Flush Garbge Issue

### ISSUE THREAD

**Issue by RecursiveCall** [MonoGame/MonoGame#1172]
The discussion of garbage generation has already been brought up here, but I would like to call out a specific place. The flushing in SpriteBatch generate significant amount of garbage. Since SpriteBatch flushes every single time a resource (texture) is changed, even inside Begin/End pair, changing a texture contributes to increase in allocations in the heap.

As little as a dozen of textures in a test project already causes the garbage collector to run every 1 - 3 seconds (with latency depending on hardware). On the PC, this doesn't becomes problematic until much much later (perhaps hundreds of textures) when other areas of the code become bottlenecks too. But on the ARM (Surface RT specifically), which is much more sensitive to garbage collection, the effect is devastating.

In my test code, I continued to push the number of textures, that on a PC causes not issues whatsoever, but on the Surface RT, cause spikes (and severe drop in FPS) every second or so.

I haven't investigated far enough to figure out whether this happens somewhere in Flush or deep enough all the way in SharpDX's DrawUserPrimitives.

**Comment by tomspilman** [comment]
@nkast - I think maybe we addressed this in your improvements?

**Comment by nkast** [comment]
It's not clear what this is about. The first post talks about garbage from changing textures but later the .DrawInt32() extension  is about solving the garbage from Int32.ToString(). Without a profiling we can't know. MG/XNA doesn't provide a solution for string garbage, one has to use a third party solution like 
http://xboxforums.create.msdn.com/forums/p/45512/273330.aspx#273330
or
https://github.com/tainicom/XNALibrary/blob/master/Source/Helpers/NKStringBuilder.cs


SpriteBatch generate garbage only when re-sizing the internal arrays and  fix #4348 by @MichaelDePiazzi ensure this doesn't occur often.
