### ISSUE TITLE
Implement FBXImporter

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#1209]
Implement the functional equivalent to the FBXImporter content pipeline class:

http://msdn.microsoft.com/en-us/library/microsoft.xna.framework.content.pipeline.fbximporter.aspx

It should be written to be compatible with the MS stock one to begin with, but we should eventually expose more of the data in the FBX...  cameras, lights, etc.

Consider using this existing managed wrapper for the Autodesk FBX SDK:

https://github.com/returnString/ManagedFBX

**Comment by kvenkateshan** [comment]
Can one of you please pass me a sample skinned model (with skeleton and a sample animation) file that you have working with monogame? We are having issues trying to get a skinned model working without it being massively deformed when applying an animation to it. We are struggling to figure out some form of a starting point to narrow it down to if it's the shader/render side or the export/import side. Email: karthik@v7entertainment.com. Thanks in advance!

**Comment by JamesLupiani** [comment]
I didn't get a chance to verify the model after the above fix, but here's the one I was working with:
https://github.com/JamesLupiani/MGModelPipeline/blob/master/Content/Dude/dude.fbx
It's a converted file from one of the original XNA samples.

**Comment by kvenkateshan** [comment]
Thanks for that James. The fbx imported inserted a fictitious RootNode and was causing the indexing of the skeleton that was being based to the skinned effect all out of order. And therefore the exploded geometry. Everything renders well now :)
