### ISSUE TITLE
sound glitches

### ISSUE THREAD

**Issue by JavierMaura** [MonoGame/MonoGame#1274]
I have an strange behaviour with monogame 2.6 on iOS. My game load a texture2D, and then display it. It loads a new texture from disk every 1/12th second ( i can not load all the textures in memory because of there are a lot of frames)

So, the logic es:
Load frame if necessary
Play sound if necessary
Draw Texture
Draw a button texture ( loaded in memory previously)

Running the game, the sound make 'glitches', and, curiously, slows down!! But the display sow the images perfectly, without problem
If i comment the loading line, the sound is perfect, but nothing is displayed, of course.

But then i tried another scenary: 
Load frame if necessary
Play sound if necessary
 // Draw Texture
Draw a button texture ( loaded in memory previously)

And this work fine too!! So it seems that the problem is that there is not enough 'time' for the sound player to update?

Do you know how to solve this? Thanks!!

Post: i've tried with WAV, mp3 and aac, and ...it performs worst with WAV!!!

**Comment by Jjagg** [comment]
Seems like this is simply a performance issue. The graphics and audio codebases don't interact at all. I'm closing this.
