### ISSUE TITLE
MonoGame/WindowsGL not rendering correctly to multiple GLControls

### ISSUE THREAD

**Issue by jaquadro** [MonoGame/MonoGame#1297]
See (http://monogame.codeplex.com/discussions/431834) for an in-depth description of the problem.

Under XNA, we could render to multiple controls backed by a single GraphicsDevice in WinForms, using this well-known tutorial: (http://xbox.create.msdn.com/en-US/education/catalog/sample/winforms_series_1)

I've attempted to adapt this to OpenTK.GLControl by replacing the call to GraphicsDevice.Present() with a GLControl.MakeCurrent() / GLControl.SwapBuffers() pair at the beginning and ending of drawing.  This works fine for a single GLControl.  When multiple controls are present, basic GL manipulations can be performed on all controls, such as color clearing or GL immediate mode drawing, but MonoGame routines will only have an effect in one of the controls.

I've provided a test case (http://hocuspocus.taloncrossing.com/rii/GLControlTest.zip), which is a slightly modified version of the Winforms Series tutorial.  Both controls render a triangle in XNA, but only the left control renders in MonoGame.  MonoGame/OpenTK assemblies and pdbs included, since it needs a build of OpenTK.GLControl, and GraphicsDevice.cs was modified slightly.  See the codeplex discussion for detail.

**Comment by cra0zy** [comment]
OpenTK related issue, we no longer use OpenTK so closing.
