### ISSUE TITLE
Effect.OnApply() return value

### ISSUE THREAD

**Issue by pzgulyas** [MonoGame/MonoGame#1303]
The function can be overridden in XNA 4.0 by
protected override void OnApply()

but in MonoGame it is
protected override bool OnApply()

**Comment by tomspilman** [comment]
This can likely be fixed now.  We remove the bool... and instead check of the `Effect.CurrentTechnique` changed between calls to `OnApply()`.  So this...

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Effect/EffectPass.cs#L71

... becomes more like:

```
            var current = _effect.CurrentTechnique;
            _effect.OnApply();
            if (_effect.CurrentTechnique != current)
            {
                _effect.CurrentTechnique.Passes[0].Apply();
                return;
            }
```

Maybe a little less efficient, but makes this API compliant with XNA4 finally.
