### ISSUE TITLE
No way to get application arguments

### ISSUE THREAD

**Issue by Oblivion165** [MonoGame/MonoGame#1311]
I've looked all over and it appears there are no way to get the arguments passed to the program. I found LaunchParameters but it was empty.

**Comment by willmotil** [comment]
Do you mean passing arguments to main ? 
That should work as normal.

        static void Main(string[] args)
        {
            // Display the number of command line arguments:
            System.Console.WriteLine(args.Length);
        }

If not maybe try environment
https://msdn.microsoft.com/en-us/library/system.environment.getcommandlineargs.aspx

**Comment by Oblivion165** [comment]
This is from 4 years ago so I no longer have any idea what it was for.

**Comment by willmotil** [comment]
Strange it thought it was on the first page of the recent issues 
Maybe i clicked oldest or surfed to it or something lol.
