### ISSUE TITLE
Microsoft.Xna.Framework.Input.Keyboard not working in Windows Phone 8

### ISSUE THREAD

**Issue by AdamDawes** [MonoGame/MonoGame#1352]
XNA on WP7 allowed full interaction with a hardware keyboard for the handful of devices that had one. MonoGame running on Windows Phone 8 doesn't appear to offer any keyboard support. Of course there aren't any WP8 devices with hardware keyboards AFAIA, so this isn't particularly urgent just at the moment; I'm testing this by running in the emulator with "keyboard" mode activated by pressing Page Down.

The KeyboardState,IsKeyDown always returns false for all keys, and the GetPressedKeys function always returns an empty array.

It would be good to get this fixed up for a future release.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
