### ISSUE TITLE
Windows 8: touch point gets "stuck" after using XAML/SIP on touch screen device

### ISSUE THREAD

**Issue by AdamDawes** [MonoGame/MonoGame#1360]
I've found what appears to be a bug in the public release of MonoGame3 running in Windows 8 on a touch screen device (Surface RT). Attached is a simple example project that can be used to reproduce the problem.

Description of problem:
After displaying a simple piece of XAML which includes a text field, setting focus to the text field so that the SIP appears, and then scrolling the XAML content, a touch point is added to the array returned by each call to TouchPanel.GetState() that remains even after contact is released from the screen and cannot be removed.

Attachment:
http://www.adamdawes.com/private/MonoGameStuckTouchpoint.zip

Example project:
The project is a simple empty MonoGame Windows Store project, inside which a couple of XAML controls have been added to the GamePage. These include a textbox and a button, and are initially collapsed so that they cannot be seen.

In the game's Update function, the code checks to see whether a single touch point with a state of "Pressed" has been encountered. If so, it makes the XAML controls visible and sets the focus to the textbox. This causes the SIP to appear on a touch device. Due to the way Windows handles scrolling, the OK button is hidden behind the SIP.

If the user swipes the main area of the page (above the SIP) upwards to reveal the OK button, a touch point ends up "stuck" in MonoGame and is returned from every call to TouchPanel.GetState(), even though the user has released contact with the screen.

To reproduce:
- Run the attached project on a touch screen device with no hardware keyboard (e.g., Surface)
- Note that the project continually displays the number of items returned from TouchPanel.GetState into the debug window (initially always zero).
- Tap the screen. The XAML controls appear, as does the SIP. Because the textbox has focus, it scrolls upwards so that it is displayed immediately above the SIP.
- The debug output still shows zeros at this point.
- Swipe the "non-SIP" part of the screen upwards to reveal the OK button, and release contact with the screen. The debug output now continually shows "1" instead of "0". An unexpected touch point is constantly present within the Touch Panel and cannot be removed.

I've experienced this a couple of times but only yesterday tracked down what was triggering it. This is causing me some real problems in my games as when I ask the user to enter their name for the high-score table, should they happen to scroll the XAML controls then the game locks up due to this unexpected touch point and has to be closed. A workaround and/or fix would be very much appreciated.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
