### ISSUE TITLE
Add support for using PVRTC textures on OpenGL platforms

### ISSUE THREAD

**Issue by KonajuGames** [MonoGame/MonoGame#1370]
Add a SupportsPvrCompression property to GraphicsCapabilities that returns true if the GL extensions report PVRTC is supported.

Enable loading of PVRTC data into textures.

**Comment by tomspilman** [comment]
@KonajuGames - Is this intended just for mobile devices?  Or is this something for desktops too? 

Same for https://github.com/mono/MonoGame/issues/1371 i guess.

**Comment by Jjagg** [comment]
Fixed in #3991.
