### ISSUE TITLE
Windows installer should check previous versions are uninstalled

### ISSUE THREAD

**Issue by KonajuGames** [MonoGame/MonoGame#1372]
We have had a few issues caused by installing the released version over existing beta installations.  The installer should check that previous versions are uninstalled before allowing to proceed with the installation.  If possible, the installer should launch the uninstaller for the installed version.

**Comment by tomspilman** [comment]
Ok... revisiting this issue.

I see one option is adding this script to the installer...

 http://nsis.sourceforge.net/Auto-uninstall_old_before_installing_new

**Comment by KonajuGames** [comment]
> I see one option is adding this script to the installer...

We would need to use a product name for the registry entry without the version number so that it does not matter which version the user had previously installed and which version that are trying to install.

**Comment by tomspilman** [comment]
> We would need to use a product name for the registry entry without the version number

Yeah...  generally you should.  I think we already do.

**Comment by Halofreak1990** [comment]
Is there any progress on this? I currently have multiple MonoGame installations side by side, and I cannot uninstall the older ones because the uninstaller points to the latest version.

Can I safely remove the folders for the older versions in the mean time?

**Comment by tomspilman** [comment]
So before we move on this...  would it be better to support side-by-side installs of MonoGame?  I know that other game/console SDKs try to support this.  Should we?

@KonajuGames @dellis1972 ?

**Comment by cra0zy** [comment]
> So before we move on this... would it be better to support side-by-side installs of MonoGame?

With nugets this is easily doable, with GAC we'd have to do a lot of hacking up and changing versions would be a nightmare...

**Comment by tomspilman** [comment]
Ok... so no multiple side-by-side installations for MonoGame SDK stuff.  If you need side-by-side installs that is where you work from a GitHub repo directly.

So all i need to do is auto-uninstall the previous installed version.

**Comment by tomspilman** [comment]
@dellis1972  @cra0zy 

What about Mac and Linux?

Do those installs... the .run and the .pkg ... uninstall previous installs?

**Comment by cra0zy** [comment]
Linux one does it: https://github.com/MonoGame/MonoGame/blob/develop/Installers/Linux/RUN/postinstall.sh#L42

**Comment by cra0zy** [comment]
PS. This requires the use of http://nsis.sourceforge.net/Reference/InstallDirRegKey

**Comment by harry-cpp** [comment]
Gonna close this as its not gonna be a problem in 3.8.
