### ISSUE TITLE
Windows Phone 8: Content.Load<SoundEffect> crashes with unhandled TypeInitializationException

### ISSUE THREAD

**Issue by AdamDawes** [MonoGame/MonoGame#1394]
Any attempt to load a SoundEffect from a .xnb file on Windows Phone 8 crashes with an unhandled TypeInitializationException.

In thread http://monogame.codeplex.com/discussions/432974 SlyGamer indicated it may be do with the the compression and suggested setting this to Best in the XNA Content project. However I cannot get the sound effect to load with any of the available compression settings.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
