### ISSUE TITLE
Android ResetClientBounds

### ISSUE THREAD

**Issue by ghost** [MonoGame/MonoGame#1397]
On my Samsung Galaxy Nexus (4.1.1, deploying the app in 2.2) I have a default resolution of 1196x720 in landscape and 720x1184 in portrait. If I hold my phone in landscape and my application is set up to be portrait; the display will start out as landscape, GraphicsDeviceManager.ResetClientBounds method will fire down the line to get to portrait resulting in a view bounds calculation of {X:4, Y:0, Width:712, Height:1184} when really I want {X:0, Y:0, Width:720, Height:1184}

Obviously I can't disable it as suggested in the method's description as Window.ClientBounds.Width/Height have different aspect ratios depending on their orientation which will result in those unwanted viewport offsets.

I imagine most people don't have different resolutions depending on their orientation so the ResetClientBounds will normally just swap width/ height. It looks like the start of decent letterboxing/ pillarboxing code but personally I think that should be handled on a case by case basis.

**Comment by cra0zy** [comment]
This should be fixed.
