### ISSUE TITLE
State of web / NaCL support?

### ISSUE THREAD

**Issue by bonesoul** [MonoGame/MonoGame#1419]
So I've been hearing about it for a while
- http://monogame.codeplex.com/discussions/362178
- http://infinitespace-studios.co.uk/2012/07/10/can-monogame-in-the-browser/
- http://supergiantgames.com/?p=1611

Any lately progress & decisions on this?

@dellis1972 do you have your opentk-based web plugin online anywhere so we can git a try maybe?

**Comment by tomspilman** [comment]
Cross referencing this to https://github.com/mono/MonoGame/issues/3895.
