### ISSUE TITLE
More GamerServices back ends.

### ISSUE THREAD

**Issue by CartBlanche** [MonoGame/MonoGame#1424]
At the moment we have GameCenter support under iOS, with some wrinkles, but basically working.

Who can we partner with, on various platforms, to have the equivalent of leaderboards, achievements and matchmaking?

Gree (formerly OpenFient) maybe one option https://developer.gree.net/en/ as that works on iOs and Android.

I believe Google may be working on one for Android.
There is Xbox Live, if Microsoft will allow us
PSN, if Sony will allow us.
We still have to see what OUYA offers
We should see if Valve will allow use to integrate Steam.

**Comment by tomspilman** [comment]
@dellis1972 - Moving this to 3.7 for now...  but we should consider how this factors into your networking plans.  Maybe this just needs to be closed?

**Comment by harry-cpp** [comment]
MonoGame.Framework.Net is no longer a part of the main repo.
