### ISSUE TITLE
[WinDX] Cannot change IsMouseVisible at runtime.

### ISSUE THREAD

**Issue by helmut-g** [MonoGame/MonoGame#1454]
On Windows/DirectX, changing IsMouseVisible at runtime has no effect. In our application, we can dynamically show/hide a GUI and therefore we also want to change IsMouseVisible at runtime.

As far as I can see, the problem is that WindowsGamePlatform.OnIsMouseVisibleChanged was removed in this commit: https://github.com/mono/MonoGame/commit/f5c3a68f36f1246d6a53b91df4d7885e806dd678

Further, this commit https://github.com/mono/MonoGame/commit/ee60155053cd3fdec20a5ac9f2f057c37b2548f6 added code to show/hide the cursor when the it leaves the window. In my experience, this is the Windows default behavior, so the code is unnecessary.

@xanather 
Could you please comment why this WindowsGamePlatform.OnIsMouseVisibleChanged() was removed?
Could you please comment why showing/hiding the cursor in MouseEnter/MouseLeave is necessary?

Proposed solution:
I get the same cursor behavior as in XNA when I do the following:
In the WindowsGamePlatform constructor call Cursor.Hide (because IsMouseVisible defaults to false). 
In WindowsGamePlatform.OnIsMouseVisibleChanged call Cursor.Show/Hide as needed. Do nothing in WinFormsGameWindow.MouseEnter/MouseLeave.

**Comment by auoji** [comment]
Really nothing. Some paste Code thy have 'PlatformGetHandle' - some phantasie - never can work.

IsmouseCVisible not work on Monowork 3.6. Also in doumnation Mouse.Setcoursor - not Exit in 3.6 is doc from 3.7 but this is also fantasie - not exist yet - maybe next year
bullshit
--

'
