### ISSUE TITLE
GraphicsDeviceManager.ApplyChanges() ignore the PreferredBackBuffer size

### ISSUE THREAD

**Issue by angellaa** [MonoGame/MonoGame#1487]
Hello,

I am writing a bug after the following discussions as suggested by Tom Spilman:
http://monogame.codeplex.com/discussions/431594#post1008533
http://monogame.codeplex.com/discussions/433005#post1008532

This is a Windows 8 bug.

The problem is that the ApplyChanges function called after the screen resolution change ignore the PreferredBackBuffer size.

This happens when the user:
- Move the game in the Snapped view state
- Move the game in the Filled view state
- Move the game in a separate screen with a different resolution

Steps to Reproduce:
1. Install MonoGame 3.0 installer on Visual Studio 2012 Update 1
2. Create a "MonoGame Windows Store (XAML) Project"
3. Add a font in the Content folder
4. Add the following code in the Game1.cs class
   
   ```
   public Game1()
   {
       _graphics = new GraphicsDeviceManager(this);
   
       UpdateBackbuffer(ApplicationViewState.FullScreenLandscape);
   
       Content.RootDirectory = "Content";
   
       ApplicationViewChanged += (sender, args) => UpdateBackbuffer(args.ViewState);
   }
   
   private void UpdateBackbuffer(ApplicationViewState viewState)
   {
       if (viewState == ApplicationViewState.Snapped)
       {
           _graphics.PreferredBackBufferWidth = 320;
           _graphics.PreferredBackBufferHeight = 768;
       }
       else
       {
           _graphics.PreferredBackBufferWidth = 1024;
           _graphics.PreferredBackBufferHeight = 768;
       }
   
       _graphics.ApplyChanges();
   }
   
   protected override void Draw(GameTime gameTime)
   {
       GraphicsDevice.Clear(Color.Black);
   
       _spriteBatch.Begin();
   
       for (int x = 0; x < 2048; x += 128)
       {
           for (int y = 0; y < 2048; y += 128)
           {
               _spriteBatch.DrawString(
                   font, 
                   string.Format("({0}, {1})", x, y), 
                   new Vector2(x, y), 
                   Color.White, 
                   0, 
                   Vector2.Zero, 
                   0.3f, 
                   SpriteEffects.None, 
                   0);
           }
       }
   
       _spriteBatch.End();
   
       base.Draw(gameTime);
   }
   ```
5. Run the game in full screen
6. Move the game in Filled View, Snapped View or on a different screen

Expected Result:
In the Filled view state and in any screen the coordinate with the maximum values must be (896, 640) in the bottom right corner. 

Actual Result:
In the Filled view state and in any screen the coordinate with the maximum values depends by the resolution proving that the backbuffer is not set with the resolution requested. For example with a resolution of 1920 \* 1200 the maximum is (1152, 640) that even with this resolution is not what should be. Don't know what this function do but this is not what I expect.

Regression?
A code similar to this worked last year in November/December but I was using a full XNA game project and using CoreWindows events in order to detect screen changes. I was able to move the game in all the windows 8 views and in different screen and the backbuffer was reset correctly after ApplyChanges.

In general, fixing this bug want to provide support for developers (like me) who want to develop a Windows 8 game maintaining a fixed backbuffer across all the screens.

Thanks

First Run - Full Screen

![First Run - Full Screen](https://f.cloud.github.com/assets/641111/212015/f404f5d4-82cb-11e2-8720-a29a6a97ce36.png)

After the user move to Filled view state:

![After move to Filled View](https://f.cloud.github.com/assets/641111/212014/f401ff3c-82cb-11e2-991c-9ca369cf78c7.png)

After the user move to a screen with resolution of 1920x1200:

![After move to a screen with resolution of 1920x1200](https://f.cloud.github.com/assets/641111/212016/f400df8a-82cb-11e2-8d82-d0722759c2d9.png)

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
