### ISSUE TITLE
[Android] No Launchable Activity

### ISSUE THREAD

**Issue by SurvivalistDev** [MonoGame/MonoGame#1491]
Hey there

I'm trying to port a Windows Phone game to Android and have hit a snag that I don't know how to get around.

I've got a custom XNA game class in a library built for Android. I create a new Android Application and set up the MainActivity.cs file as I've seen on various tutorials:

```
namespace Shelter_Android
{
    [Activity (Label = "Shelter_Android", MainLauncher = true)]
    public class Activity1 : AndroidGameActivity
    {
        protected override void OnCreate (Bundle bundle)
        {
            base.OnCreate (bundle);

            ShelterGame_Android.Activity = this;
            var g = new ShelterGame_Android ();
            SetContentView (g.Window);
            g.Run ();
        }
    }
}
```

This builds fine, but when I deploy to the emulator it tells me there is no launchable activity and so it does nothing when I try to run it.

I'm not sure where to start looking for a solution for this. I've searched the GitHub issues and found nothing and I've searched google and found nothing.

Built using Xamarin Studio 4.0 and building MonoGame libraries 3.0.0.0 as part of the solution.

Thanks in advance for any help and suggestions

Chris

**Comment by cra0zy** [comment]
No response, plus pretty old issue, closing.
