### ISSUE TITLE
Call OnExiting From Game.Exit()

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#1499]
Currently when you call `Game.Exit()` on any MonoGame platform the `Game.OnExiting` method is not fired.

We should fix this as well as test to see what other methods/events are triggered from `Game.Exit()`.

Note it should only work on platforms where Game.Exit() is valid...  on platforms where it is not we should throw an exception and not call back any methods/events.

**Comment by xanto** [comment]
Hi, 
I have similar issue with MonoGame.DX package on windows 10 PC. I tested it with 3.4 and 3.5.0.1108 (04 Jan 16 14:27). If I close the Window manually the event is raised, while if I call Exit() in Update method the event is not raised. 

```c#
//Handle Exiting from current game window. Multiple Games can exists
private void HandleGameExiting(object sender, EventArgs e)	{
			var game = sender as GameDevice;
	
			if (game != null) {

				GameDevice gameToRemove;
				games.TryRemove (primaryGameName, out gameToRemove);


				if (gameToRemove == null) {

					return;
				} 

			} 
	}

//in other point of program...
gameDevice.Exiting += HandleGameExiting;


//Inside the Game class

protected override void Update(GameTime gameTime)  {

    if (exit) {
				
       Exit ();
						
   }
   
  base.Update(gameTime);
}
```

**Comment by tomspilman** [comment]
@danzel - Have time to investigate this?

**Comment by Jjagg** [comment]
This is fixed as shown by [this](https://github.com/MonoGame/MonoGame/blob/develop/Test/Framework/GameTest.cs#L175) test. @tomspilman
