### ISSUE TITLE
GraphicsDevice.PresentationParameters.BackBufferWidth incorrect in Game.Initialize

### ISSUE THREAD

**Issue by icefallgames** [MonoGame/MonoGame#1505]
Create a new MonoGame Windows OpenGL Project in VS 2010.

In the Game's constructor, have this:

```
        graphics = new GraphicsDeviceManager(this);
        graphics.PreferredBackBufferWidth = 1000;
```

The Game's Initialize should look like this:

```
    protected override void Initialize()
    {
        System.Diagnostics.Debug.WriteLine(GraphicsDevice.PresentationParameters.BackBufferWidth);
        base.Initialize();
        System.Diagnostics.Debug.WriteLine(GraphicsDevice.PresentationParameters.BackBufferWidth);
    }
```

This will output:
800
1000

In XNA 4.0, it will output:
1000
1000

This is a difference in behavior from XNA 4.0.

I'm using MonoGame 3.0.1.

**Comment by cra0zy** [comment]
This has been fixed with the SDL version.
