### ISSUE TITLE
Finalize Coding Style Guide

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#1512]
We need to finalize the coding style guidelines in this document:

 https://github.com/MonoGame/MonoGame/blob/develop/CODESTYLE.md

This is a required step before we can do #1511.

Lets keep all discussion in this thread before any PRs are submitted to change the guide.

**Comment by tomspilman** [comment]
So... democracy over.

@KonajuGames and i will go thru the existing guide and make the final decisions on the style.

**Comment by cra0zy** [comment]
Just gonna link these 2 helpful links and not gonna say anything:
 - https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md
 - https://github.com/dotnet/codeformatter
