### ISSUE TITLE
Fire and Forget SoundEffect Playback

### ISSUE THREAD

**Issue by totallyeviljake** [MonoGame/MonoGame#1551]
I would like to see a fire-and-forget SoundEffect.Play implementation. The current implementation will playback sound effects immediately, which is not how Microsoft XNA implements sound effect playback.

Marking this for performance because it will improve the reliability of sound effect playback using OpenAL when games attempt to play back sound effects in worker threads. While not a supported feature, this will be a direction for the future of MonoGame.

(milestone MonoGame 3.2)

**Comment by Jjagg** [comment]
I don't understand what this issue is about.

**Comment by harry-cpp** [comment]
Yea, I will close this as the issue has not been properly described.
