### ISSUE TITLE
[UWP] Texture2D.SaveAsPng doesn't save alpha channel

### ISSUE THREAD

**Issue by tomasslavicek** [MonoGame/MonoGame#1593]
Texture2D / RenderTarget2D.SaveAsPng doesn't save an alpha on WinRT. The transparent pixels are saved black.

In internal MonoGame's method Texture2D.SaveAsImage is written:
// TODO: We need to convert from Format to R8G8B8A8!

I want to save my rendertarget to file + load it back to XAML (as Image.Source).

**Comment by JamesC01** [comment]
I believe this has been fixed now. It seems that Texture2D.StbSharp.cs handles the image saving now.
