### ISSUE TITLE
Yet to be implemented

### ISSUE THREAD

**Issue by xanather** [MonoGame/MonoGame#1634]
- RenderTarget3D (https://github.com/mono/MonoGame/pull/1549) - needs implementation on Mac, Linux, WinGL, iOS, Android, Win8, PSMobile, WinPhone
- Multiple Window support (https://github.com/mono/MonoGame/pull/1465) - needs implementation on Mac, Linux, WinGL
- Window.IsBorderless (https://github.com/mono/MonoGame/pull/1389) - needs implementation on Mac
- [DONE] Fullscreen Support - needs implementation on WinDX

Just a idea, might be easier for maintenance. Please edit for anything that's missing.

**Comment by Shqrdx** [comment]
Fullscreen Support - WinDX support - on board, dunno about other... : (

**Comment by tgjones** [comment]
`Window.IsBorderless` on Mac - this is covered separately in #1552.

**Comment by willmotil** [comment]
fullscreen on opengl last i checked is still a bit buggy
