### ISSUE TITLE
Windows 8: Touch Input lag on some devices

### ISSUE THREAD

**Issue by nfurtwangler** [MonoGame/MonoGame#1646]
We got some reports from customers that our MonoGame based game Taptitude had some touch input problems on certain hardware.

We eventually got an Asus Zenbook with touchscreen and the issue reproduces on that hardware.

What happens is if you press your finger down and hold it for a split second then lift up, then the "Release" isn't handled for a very long time (multiple seconds).  This leads to a bad user interface experience and strange "stuck" touch problems.

Looking into it, I think it is very similar to this dicussion which is closed:

https://github.com/mono/MonoGame/issues/770

From debugging our problem we saw that on this particular hardware, leaving your finger down for a short amount of time builds up A LOT of touch "move" events on touch panel.  Given that only one touch event is "popped" from the event queue each time TouchPanel.GetState() is called and we only call GetState() once a frame (to see whats new since last frame) it ends up taking over 100 frames to plow through all the built up "moves" and eventually get to the "release" event.

We ended up making this change to fix the issue for our purposes:

https://github.com/FourBrosStudio/MonoGame/commit/b2407ba45a8ce8c44764e94c8f859e839bf4785d

So basically it works the same as before except it will skip over all "move" events that aren't the last one and ignore "move" if there is a "release" after it.  This is more in line with the way XNA behaves on Windows Phone.  It also means that you _will_ lose information when many moves come in a single frame so an app that wants to do precise line drawing with a finger will need to use the FreeDrag gesture instead of relying on GetState which is more like a snapshot (same as XNA on Windows Phone).

But the benefit is that it doesn't take 3+ seconds to process a finger being lifted.

Has anyone else hit this issue and what are some alternative work arounds?  We are comfortable with this change and are using it going forward but I'm not sure if there was an intentional reason to queue up move events like it was doing before.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
