### ISSUE TITLE
Custom Shaders and SpriteBatch on Windows 8 (RT)

### ISSUE THREAD

**Issue by Axadiw** [MonoGame/MonoGame#1647]
On Windows 8 RT (Metro) there is a problem with rendering sprites from SpriteBatch and using custom shaders with them.

I'm trying to use simple shader changing texture to grayscale:

``` HLSL
sampler TextureSampler : register(s0);


float4 PixelShaderFunction(float4 color : COLOR0, float2 texCoord : TEXCOORD0) : COLOR0
{
    float4 tex = tex2D(TextureSampler, texCoord);
    tex.rgb = dot(tex.rgb, float3(0.3, 0.59, 0.11));
    return tex;
}


technique Technique1
{
    pass Pass1
    {
        PixelShader = compile ps_4_0_level_9_1 PixelShaderFunction();
    }
}
```

Rendering with such effect produces wrong image (examples below). I'm rendering them using such code:

``` C#

//in draw method

_spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
_effectSprite.CurrentTechnique.Passes[0].Apply();
_spriteBatch.Draw(_tex2d, new Vector2(0, 0), Color.White);
_spriteBatch.End();
```

I've created a test project that presents this bug - it allows to render sprite without any shaders, with a shader, and using similar shader file, and by drawing texture on quad, using DrawUserIndexedPrimitives method.

I've tested it on my Geforce 9600GT (Supports 10.0, 9.3, 9.2, 9.1 feature levels) and on Intel HD 3000 (supports the same as GeForce and 10.1), and result is:

without shaders:
![withoutREAL](https://f.cloud.github.com/assets/1938540/370735/03beb8da-a300-11e2-9039-5914c8d00ad0.png)

using DrawUserIndexedPrimitives:
![primitiveREAL](https://f.cloud.github.com/assets/1938540/370737/0aab66ca-a300-11e2-81c8-bbf0e7838dc1.png)

shaders + spriteBatch:
![spriteReal](https://f.cloud.github.com/assets/1938540/370738/0ec24c1a-a300-11e2-8042-ebae78aee68e.png)

The funny this is that I've tested it on my virtual machine (VMWare), and it works perfectly there! Look it looks like this:

without shaders:
![withoutVM](https://f.cloud.github.com/assets/1938540/370743/29a93188-a300-11e2-941b-70c388b10ae7.png)

using DrawUserIndexedPrimitives:
![PrimitivesVM](https://f.cloud.github.com/assets/1938540/370744/2eda2d1a-a300-11e2-8dea-16c1f54b7d9f.png)

shaders + spriteBatch:
![spriteVM](https://f.cloud.github.com/assets/1938540/370745/31fd0e72-a300-11e2-866c-4eb624ec9ca1.png)

I'm compiling content files using Visual Studio 2010 and newest MonoGame sources from GitHub. The WindowsStore app is compiled by VS2012.

Content project:
https://dl.dropboxusercontent.com/u/1334716/monoGame/ContentProject.zip

ShaderTest project:
https://dl.dropboxusercontent.com/u/1334716/monoGame/ShaderTest.zip

Compiled binary:
https://dl.dropboxusercontent.com/u/1334716/monoGame/ShaderTest_1.0.0.3_AnyCPU_Test.zip

I've started quite long conversation about this bug on codeplex, you can see it there:
https://monogame.codeplex.com/discussions/439022

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
