### ISSUE TITLE
Performance issues on Windows Phone

### ISSUE THREAD

**Issue by DDReaper** [MonoGame/MonoGame#1692]
Got stonewalled by some performance issues with the release & code builds on the Windows Phone platform this weekend.

The shocked sample on my blog works fine on pretty much all platforms extremely well except for Windows Phone???

In the release build the app actually crashes with a memory overflow
In the code build it runs but for the first 10 - 20 seconds perf is terrible, it improves after that but is nowhere near as efficient as the other platforms (including native Silver XNA solution on WP7).

Any ideas or suggestions?

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
