### ISSUE TITLE
Monogame not working on Windows with mono

### ISSUE THREAD

**Issue by kunjee17** [MonoGame/MonoGame#1694]
Hi, I am using Xamarin studio to create windows game. I am also using F# as base language. First issue I have faced as I have add manual library of monogame windows but I guess that is Xamarin issue.

Now, main issue I have faced that it is not working with mono 3.0.7, I need to run with .Net runtime only. Now, Xamarin has open issue if I am running with .Net Framework I can't run in debug, I have to run without debug only. 

Please let me know if am missing something here?

Also let me know if more information required.

**Comment by cra0zy** [comment]
This is a mono bug that got fixed, closing...

**Comment by kunjee17** [comment]
@cra0zy Thanks for closing this 5 years old bug... I did totally miss it.
