### ISSUE TITLE
[WinDX] Stretch/missing pixels issue

### ISSUE THREAD

**Issue by xanather** [MonoGame/MonoGame#1696]
So I have two computers
- development machine (desktop - Win7 64-bit)
- other machine (laptop Win8 64-bit)

When I tested my game so far on my laptop the result was concerning. Some pixels rendered differently which started making me worry. (the game is completely 2D).

It seems like if I try to stretch out 1 pixel from a spritesheet and draw it beyond a certain x width/y height, there are a row of pixels that are not drawn and are left out even though the rectangle bounds specified are supposed to cover this left out area. However this does not happen on my desktop which is why it confuses me.

I begin drawing with:

engine.spriteBatch.Begin(SpriteSortMode.Deferred, null, SamplerState.PointClamp, null, null);

Some example of code which creates the issue:

engine.spriteBatch.Draw(engine.textures.interfaceWindow, new Rectangle(0, 0, engine.display.width, engine.display.height), new Rectangle(16, 49, 1, 1), Color.White, 0f, Vector2.Zero, SpriteEffects.None, 0f);
- engine.textures.interfaceWindow - is just the basic texture
- new Rectangle(0, 0, engine.display.width, engine.display.height) - creates the target bounds to draw to be the whole window
- new Rectangle(16, 49, 1, 1) - only gets one source pixel from the interfaceWindow spritesheet (this is just the back color of a window, using it in this way just for the example).

On my desktop, the above code colors the whole screen correctly with one color. On my laptop, it will draw over almost all of the screen but the right and bottom edges, the edges are not touched and nothing is drawn (there is a white outline 1 pixel in width at the edges of the rendering scene). This small "untouched" gap gets larger the bigger I make the target rectangle.

Images:
On my desktop:
![hmmm2](https://f.cloud.github.com/assets/3013922/445288/a24493c8-b1b8-11e2-9a6e-15ebe55fc0f3.png)

On my laptop:
![hmmm](https://f.cloud.github.com/assets/3013922/445304/07632d14-b1b9-11e2-9c56-6396ab8d5d7a.png)

Thats just the top right of the window, the bottom of the window also has the white line. Also notice that the "untouched" gap there is larger than 1 pixel, this is because I had a large render width, making the target Rectangle's width larger.

I had trouble explaining this, I thoroughly looked at my code and I just cannot see how this can be a problem I am making myself.

I'm about to go to sleep so I may not reply for some time, thanks for reading.

**Comment by Jjagg** [comment]
Sounds like a driver bug and no reports of it since 2013, so closing.
