### ISSUE TITLE
Incorrect mouse position in Windows Store project

### ISSUE THREAD

**Issue by MrSoundless** [MonoGame/MonoGame#1712]
Hi guys,
I'm working on a Windows Store game and I noticed something:

When you set the PreferredBackBufferWidth and PreferredBackBufferHeight to something different than the original, the mouse position is incorrect. It keeps returning the position based on the original screen resolution.

In my case, I got a 1680x1050 resolution.

_graphics.PreferredBackBufferWidth = 1280;
_graphics.PreferredBackBufferHeight = 800;
_graphics.ApplyChanges();

Now when I start the game and move the right-bottom of the screen, I expect a position of X:1280, Y:800 but it returns X:1680, Y:1050

**Comment by cra0zy** [comment]
This is not a bug.
