### ISSUE TITLE
Audio.Microphone class missing...

### ISSUE THREAD

**Issue by CartBlanche** [MonoGame/MonoGame#1729]
After a quick poll on twitter, it seems a few people would like to use this class, which we don't have yet.
http://msdn.microsoft.com/en-us/library/microsoft.xna.framework.audio.microphone.default(v=xnagamestudio.40).aspx

Just logging it here so we know it may be needed.

**Comment by cra0zy** [comment]
why was this closed?

**Comment by tomspilman** [comment]
Sorry... my bad.  I was closing old PlayStation Mobile issues and closed this one by mistake.

**Comment by PerikiyoXD** [comment]
No info about the Microphone class?
