### ISSUE TITLE
OpenTK based versions of MonoGame will not allow you to change DepthStencilFormat

### ISSUE THREAD

**Issue by bwfox** [MonoGame/MonoGame#1748]
Setting GraphicsDeviceManager.PreferredDepthStencilFormat seems to have no effect in WindowsGL and OSX versions of MonoGame. The result is that you are stuck with whatever size of Depth and Stencil buffer you are given, even if the graphics hardware supports a larger buffer. 

I tweaked one of the samples to demonstrate the problem here, but it should be fairly easy to reproduce:
https://github.com/bwfox/MonoGameDepthBufferBug

When the DepthFormat is set to 16 bits in the Graphics3DSampleGame() constructor, the rendered models should produce noticeable z-fighting along the seam where they meet. 

I have pull the latest code from the develop branch (including the fix for Issue #1739 ). The state of PresentationParameters on the graphics device reflects the DepthFormat assignment, but the rendered result does not.

**Comment by Jjagg** [comment]
This issue is kind of still present, but closing in favor of duplicate #5441 because the information in this issue is horribly outdated.
