### ISSUE TITLE
Using a Control instead of a form

### ISSUE THREAD

**Issue by nightst4r** [MonoGame/MonoGame#1752]
Do you guys allow code that would extend past XNA? So for example, I wanted my game WPF control to render directly to my WinFormHostControl, rather than to its own window. So I added a static config class to my platform which takes a Control instead of a Form

```
public static class WindowsDeviceConfig
{
    public static bool UseForm = true;
    public static UserControl ControlToUse;
}
```

Then in the game platform I use that class if its configured so. The default values continue to perform as XNA did, but it allows me to set these values before newing up my game and getting different behavior.
# elif WINDOWS && DIRECTX

```
        if (MonoGame.Framework.WindowsDeviceConfig.UseForm)
        {
            return new MonoGame.Framework.WinFormsGamePlatform(game);
        }
        else
        {
            return new MonoGame.Framework.WinControlGamePlatform(game);
        }
```
# elif WINDOWS_PHONE

The only concerning difference I had to do to get coordinates to work was on Mouse.cs, it seems to work fine despite only being a control and not a form, though i believe the XNA version does in fact use a form, this does still work if you pass a form.

 remove:        static System.Windows.Forms.Form Window; 
 add:             static System.Windows.Forms.Control Window;

 remove:        internal static void SetWindows(System.Windows.Forms.Form window) 
 add:             internal static void SetWindows(System.Windows.Forms.Control window)

**Comment by Jjagg** [comment]
Closing in favor of #4730.
