### ISSUE TITLE
[WinDX] Song loading issue

### ISSUE THREAD

**Issue by xanather** [MonoGame/MonoGame#1766]
Loading a song results in the thread becoming locked/blocked after the call to 

resolver.CreateObjectFromURL(FilePath, (int)SourceResolverFlags.MediaSource, null, out otype, out source);

on line 197 of Song.cs.

The game does not load and the window stays frozen (no exceptions are thrown either).

Edit: I am just using the basic Content.Load[Song] with a XNA game studio compiled XNB (with a .wma tied next to it in the physical directory).

**Comment by MichaelDePiazzi** [comment]
From what I can tell, it looks like the only reason this issue is still open is because of some song playback issues? In that case, they may have possibly been resolved by recent PR's #4044 and #4090 and this issue can maybe be closed. Can you confirm @xanather ?
