### ISSUE TITLE
 memory leak when Resume game

### ISSUE THREAD

**Issue by MatriQ** [MonoGame/MonoGame#1771]
I think in method ContentManger.ReloadGraphicsContent memory leak when resume game. every times lost 20M.

**Comment by snaiperskaya96** [comment]
Noticed that @nkast pushed lots of commits which are supposed to fix the leak, is it fixed or?

**Comment by nkast** [comment]
All those commits you see above were rebase/sync with the develop branch.
As for WP8 it's no longer supported, see #5336.

You can find WP8 binaries with all my the fixes & optimizations here:
https://github.com/tainicom/Aether.Extras/tree/master/Samples/Libraries/MonoGame%203.5.1.9000/WindowsPhone8.0

Source code:
https://github.com/tainicom/MonoGame/commits/tnc_3_5_1_9000

**Comment by snaiperskaya96** [comment]
Ah i see! Thanks

**Comment by cra0zy** [comment]
This has been fixed, and the Windows 8.X platform support has also been dropped. Closing...
