### ISSUE TITLE
Weird flickering rectangle (640x480) from 0,0.

### ISSUE THREAD

**Issue by keyle** [MonoGame/MonoGame#1793]
I apologize if this has been posted before. I couldn't find it.

I am having a weird issue where the screen will flicker. A fixed size rectangle from 0,0.

Attached, a screenshot. (It flickers really fast, hence only partially purple).

It's not an issue once the game has loaded and the first GraphicsDevice.Clear() occurs.

But at launch, it will show a white rectangle for about half a second, which is annoying.

The screenshots shows the inside being 640x480. If no GraphicsDevice.Clear() is called, it will be purple flickering black/purple/black/etc. At launch it is white (against black).

I assume it's some odd OpenGL bug. I've used XNA quite a bit and can't reproduce it there. Only with MonoGame.

I am using MonoGameInstaller-3.0.1, on Windows 7 (up to date), with a Radeon 7800 (drivers up to date afaik)

This occurs with a blank project as well. I've also tried to start fullscreen, same deal. 

Let me know if I can provide further information.

![weird flickering](https://f.cloud.github.com/assets/9749/658287/93fc612a-d5cf-11e2-970b-ed01d6a51941.png)

**Comment by Apostolique** [comment]
Good to close this?
