### ISSUE TITLE
No option to clip the cursor to the window bounds in latest development version

### ISSUE THREAD

**Issue by rezich** [MonoGame/MonoGame#1838]
I'm making a game where, during gameplay, moving your cursor to the edges of the window (or screen if fullscreen) scrolls the camera. In MonoGame 3.0.1, this was easy; just set IsCursorVisible to false, and it would properly constrain your cursor to the window (at least, on Windows).

With the latest nightly DLLs in place, a bunch of other problems with 3.0.1 were fixed (resolution changing problems and such), but now the cursor is no longer bound to the window when hidden.

My friend running Linux claims that with the latest Linux DLLs, the cursor is bound to the window like it always was.

Is there some way this could be a toggleable bool or something, just like IsCursorVisible? I'd love for my game to constrain the cursor only during gameplay, but not while paused or in a menu while the game is in windowed mode.

**Comment by cra0zy** [comment]
Mouse should have never been bound to the window by using that property, therefore this is not an issue.
