### ISSUE TITLE
Unable to Capture Screen in iOS

### ISSUE THREAD

**Issue by DVaughan** [MonoGame/MonoGame#1885]
Hi guys,

Thanks for the great work you’re doing on this project.
I have created a Monogame app. I’ve deployed it to an iPad 4 Retina and the iPhone 6.1 simulator. 
My issue is that I’m unable to capture the screen programmatically. I’ve tried numerous approaches.
When I used the Capture method of the UIScreen object, an empty image results (white 768 \* 1024) 
UIImage image = UIScreen.MainScreen.Capture(); 

Texture2D.GetData is not implemented for iOS, so I can’t use that.

How can I capture the screen, or read texture data?

Cheers,
Daniel

**Comment by Jjagg** [comment]
`GetBackBufferData` has been implemented in #5114, but I'm unsure if anyone has tested it on mobile.

**Comment by harry-cpp** [comment]
Yup, works just fine.
