### ISSUE TITLE
MouseState not getting position as expected with current Sources (?)

### ISSUE THREAD

**Issue by SonicTTH** [MonoGame/MonoGame#1901]
Hello,

I'm just trying for learning purposes to port a small game I made on Windows with Visual Studio to run on linux. I get there really well I think and Im absolutely positive that this whole project is just great.

But I seem to dont get the current sorces and rather faulty ones. I followed this tutorial:

https://github.com/mono/MonoGame/wiki/Tutorials:Getting-Started-Guide-Linux#getting-and-building-the-latest-sources-develop3d

And also did a submodule update to get libraries and what else was downloaded from there so that I could also use functions like SoundEffect.FromStream() which weren't there in the normal version of the sources.

Now I got held of a problem with getting the correct screen size to work wich is awesome, but I am newly having a problem with my mouse cursor where its (In a window with the resolution 1280x720) Eiter (0 - 1280 ; 0) or (0 ; 0 - 720).

And I just downloaded and set everything up to have the current sources. But I cant believe that such a weird thing could be in there... can it?

Or did I made a mistake? I'm just getting the cursors position from stuff as easy as:

```
        MouseState mouseState = Mouse.GetState();
        _position = new Vector2(mouseState.X, mouseState.Y);
```

Please help :)

Oh and before I forget, Im using the Linux Mint 15 OS with monoDevelop to do everything on linux.

Greetings,

Ravior

**Comment by cra0zy** [comment]
@tomspilman This has been fixed in the SDL version.
