### ISSUE TITLE
Crash in SharpDX when rendering line strip

### ISSUE THREAD

**Issue by Sabre070** [MonoGame/MonoGame#1908]
We're getting:

```
SharpDXException was unhandled

HRESULT: [0x80070057], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: The parameter is incorrect.
```

on line 2094 of GraphicsDevice.cs when trying to render a dynamic line strip with the following code:

``` csharp
var vertexes = new[]
{
    new VertexPositionColor(new Vector3(40, 20, 0), Color.White),
    new VertexPositionColor(new Vector3(80, 50, 0), Color.White),
    new VertexPositionColor(new Vector3(120, 60, 0), Color.White),
    new VertexPositionColor(new Vector3(160, 100, 0), Color.White),
};
var indicies = new short[] { 0, 1, 2, 3 };

gameContext.Graphics.GraphicsDevice.DrawUserIndexedPrimitives<VertexPositionColor>(
    PrimitiveType.LineStrip,
    vertexes,
    0,
    vertexes.Length,
    indicies,
    0,
    vertexes.Length - 1);
```

This should work fine according to Microsoft's examples on LineStrip, but it doesn't.  Other types of primitives seem to render fine.

What we're actually trying to do is render a graph, with the vertexes generated every frame.  The code above is substituted for the block at https://github.com/hach-que/Tychaia/blob/master/Tychaia/Profiling/TychaiaProfilerEntity.cs#L111, which is being rendered from https://github.com/hach-que/Tychaia/blob/master/Tychaia/TychaiaWorldManager.cs#L73.  Again, according to Microsoft's examples, this should work.

We did at one point manage to get it to run for a few frames, but then it would still crash almost immediately after startup.

**Comment by Apostolique** [comment]
Since the linked issue has been closed, is this one ready to be closed too?
