### ISSUE TITLE
MGCB Building but not creating files

### ISSUE THREAD

**Issue by Mmarzex** [MonoGame/MonoGame#1916]
I built MGCB for MacOSX and then when I try and use the command line tool I try to compile content and it tells me that the build was successful but there is no output. This is what I pass in 

```
mono MGCB.MacOS.exe /outputdir:/Users/maxmarze/Projects/MonoGame/Tools/MGCB/bin/Release/content/bin /intermediatedir:/Users/maxmarze/Projects/MonoGame/Tools/MGCB/bin/Release/content/obj /rebuild /importer:TextureImporter /processor:TextureProcessor /build:/Users/maxmarze/Projects/MGMTest/MGMTest/Content/earth.png /build:/Users/maxmarze/Projects/MGMTest/MGMTest/Content/shuttle.png /build:/Users/maxmarze/Projects/MGMTest/MGMTest/Content/stars.jpg
```

and the output is 

```
Build started 8/8/2013 12:37:22 PM


Build 3 succeeded, 0 failed.
```

Yet nothing is outputted to the directory I set. Is there an error in what I did? Also is it possible to build the content through xamarin yet?

**Comment by cra0zy** [comment]
This has been fixed for quite some time.
