### ISSUE TITLE
ReflectiveReader property/field order

### ISSUE THREAD

**Issue by pruttned** [MonoGame/MonoGame#1956]
ReflectiveReader depends on order of properties and fields returned by GetProperties reflection method. According to MSDN (http://msdn.microsoft.com/en-us/library/kyaxdd3x.aspx) this order may vary.

> “The GetProperties method does not return properties in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which properties are returned, because that order varies.“

Therefore the deserialization may fail in some (random?) circumstances. 
Possible hot-fix is to sort properties/fields by their MetadataToken (http://hoonzis.blogspot.sk/2012/09/reflection-order-of-discovered.html ), but this order is also not guaranteed.
I think that the best way to solve this problem is to use order defined in attribute or to sort properties/fields in alphabetical order. But this is probably going to break compatibility with XNA (which has the same bug).

**Comment by Jjagg** [comment]
Closing in favor of #4792.
