### ISSUE TITLE
Hold gesture not captured on Windows Phone device

### ISSUE THREAD

**Issue by RecursiveCall** [MonoGame/MonoGame#1970]
It seems that GestureType.Hold is not captured. Tested with two Lumia 920's.

It appears that the test elapsed < _maxTicksToProcessHold in TouchPanel always succeeds, preventing the gesture from being added. Placing a breakpoint before the above test, allowing the clock to elapse, causes the test to fail and for the gesture to be added.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
