### ISSUE TITLE
WP8 - Wait.WaitOne() on main thread during game resume

### ISSUE THREAD

**Issue by totallyeviljake** [MonoGame/MonoGame#1971]
on a WP8 device or emulator.
1. Launch your game
2. Click the windows button on the device
3. Click and hold the back button
4. Select your game

in your handler for Game.Activated make a call to MediaPlayer.PlayPosition. Watch your game go black and never return because the Wait.WaitOne in PlayPosition never returns, it just blocks the main thread.

```
            TimeSpan pos = TimeSpan.Zero;
            EventWaitHandle Wait = new AutoResetEvent(false);
            Deployment.Current.Dispatcher.BeginInvoke(() =>
            {
                pos = _mediaElement.Position;
                Wait.Set();
            });
            Wait.WaitOne(); // Never returns in this test
            return (pos);
```

**Comment by cra0zy** [comment]
Support for Win 8.X devices has been dropped.
