### ISSUE TITLE
Game hangs on Windows 8.1 with XAML Controls

### ISSUE THREAD

**Issue by michaelnehls** [MonoGame/MonoGame#2003]
With Windows 8.1, I noticed that something was going wrong when adding XAML controls to a XAML and Monogame project.

When a custom control is added, the game will actually stop getting drawn to the screen. If you resize the app, or move it to another monitor, it starts drawing frames again. 

Example Project: https://dl.dropboxusercontent.com/u/14806845/XAMLError.zip

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
