### ISSUE TITLE
iPad iOS7 missing 40 pixels space at the top.

### ISSUE THREAD

**Issue by eickegao** [MonoGame/MonoGame#2008]
![ios simulator screen shot 2013-09-19 5 12 57 pm](https://f.cloud.github.com/assets/1083864/1177091/efb3cdd4-2177-11e3-85c8-8f12c12c0772.png)
![ios simulator screen shot 2013-09-19 6 05 25 pm](https://f.cloud.github.com/assets/1083864/1177092/f4f8ac60-2177-11e3-893c-a07a33076eee.png)

Please take a look for the screen shots.

**Comment by harry-cpp** [comment]
This is an issue when you are missing a launch screen. We were missing this in the default templates, and this has been resolved.
