### ISSUE TITLE
[Linux]Cursor reappearing

### ISSUE THREAD

**Issue by DrPandemic** [MonoGame/MonoGame#2028]
When I'm on Linux (not on windows) and I hide the mouse cursor, it can't get out of the window frame (that's ok). But if I moved the cursor really fast I'm able to make appear the cursor on the top bar of the window for a split second. But, if I move the window once, it becomes impossible to make the cursor appear on the top. I think the good behavior would be to be impossible to see the cursor reappear even if I didn't move the window. Do you have an idea why it's like that, or an idea for a quick fix in my code?

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
