### ISSUE TITLE
IsFullscreen not setting correctly in GraphicsDeviceManager.Initialize();

### ISSUE THREAD

**Issue by shadow-hunter** [MonoGame/MonoGame#2035]
I'm pretty sure this line:
_graphicsDevice.PresentationParameters.IsFullScreen = false;

in GraphicsDeviceManager.Initialize() should read:
 _graphicsDevice.PresentationParameters.IsFullScreen = _wantFullScreen;

Which is the reason that setting the IsFullScreen property on creation of manager will not actually do anything until calling ToggleFullScreen() after the graphics device is already created.

**Comment by Apostolique** [comment]
This has been fixed. We can close.

In ```GraphicsDeviceManager.Initialize()``` we now call ```PreparePresentationParameters(presentationParameters);```.

In that function, ```presentationParameters.IsFullScreen = _wantFullScreen;``` is present as requested.
