### ISSUE TITLE
Using current codebase, not getting touches when using DrawingSurface

### ISSUE THREAD

**Issue by DDReaper** [MonoGame/MonoGame#2074]
If I run my project using the old DrawingSurfaceBackgroundGrid touches are reported fine without issue but obviously this cannot do Landscape.

However when using the new method with DrawingSurface I not getting touch events, tested with or without gestures enabled

Occasionally one will get through but it usually becomes locked and is never released.

Ideas?

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
