### ISSUE TITLE
EnabledGestures Changes Cause Infinite-Loop in IsGestureAvailable

### ISSUE THREAD

**Issue by dancolasanti** [MonoGame/MonoGame#2076]
In porting my open-source Invasion game from XNA/WP7 to MonoGame/WP8, I noticed that the TouchPanel state occasionally becomes messed up and causes the game to (A) stop responding to gestures and (B) lock-up the UI.

The source code for Invasion is linked from my CodeProject article here: http://www.codeproject.com/Articles/620177/Invasion-Game-in-MonoGame-for-Windows-Phone-8

In the debugger, I found that I could repeat this problem 100% of the time whenever EnabledGestures changed and the IsEnabledGesture is subsequently called.  The easiest way to repeat this is to (A) remove the patch that I put in the code to mask this problem, and (B) keep tapping on the screen once you have cleared all UFOs from it and are waiting for the next level to begin.

In the debugger I have seen that IsGestureAvailable's "while (_gestureEvents.Count > 0)" loop goes infinite because abandoned _gestureEvents get stuck in it.

Somewhere in TouchPanel these stale _gestureEvents must be removed from the list to prevent an infinite-loop from occurring.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
