### ISSUE TITLE
Monogame 3.2 + WP8 - Black screen

### ISSUE THREAD

**Issue by nZeus** [MonoGame/MonoGame#2081]
I have reinstalled Windows, than installed VS2012, WPSDK8, VS2013. 
I've downloaded Monogame 3.2 (Oct 12).

And I've created a new Monogame-WP8 project.
When I run the game, I see only black screen and the SystemTray info.

After some debugging I've seen that LoadContent, Update and Draw methods are not invoked.
This issue exists for 20 days already.

**Comment by DDReaper** [comment]
@nZeus can you restest with the latest dev release?
I've tested this and have been unable to replicate the issue now, so can this be closed?

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
