### ISSUE TITLE
TouchPanel state becomes corrupted and stops correctly processing pinch gestures

### ISSUE THREAD

**Issue by ischyrus** [MonoGame/MonoGame#2083]
I am seeing an issue with TouchPanel when a pinch gesture is performed with more than 2 fingers. In my scenario, and in the referenced repro app, a pinch gesture using 4 or more fingers has the effect of showing a toolbox above the monogame surface. (A xaml control is faded in on top of it).

Pinching together with 4 or 5 fingers shows the xaml control. Pinching apart makes it disappear. You can visually see this happen. The game surface is black, the xaml control is white.

It doesn't happen upon demand, however if you keep pinching and reverse pinching in distinct gestures eventually gesture will stop registering position changes. Additionally PinchComplete is never triggered again.

Pasted below is some debug output that my sample writes. As you can see, it got into a state where the same values for pinch gesture keeps repeating.

Download the example from here: http://sdrv.ms/1bQkJPx

--- Debug.Writeline of gesture values ---
Position - Position2 - Delta - Delta2
{X:993.3276 Y:721.8375} - {X:766.1589 Y:494.4} - {X:4.696655 Y:2.775024} - {X:-3.569519 Y:-5.587494}
{X:998.3624 Y:725.4} - {X:761.9131 Y:489.1875} - {X:5.034851 Y:3.5625} - {X:-4.245789 Y:-5.212494}
{X:1002.533 Y:728.8125} - {X:758.1182 Y:484.725} - {X:4.170654 Y:3.412476} - {X:-3.794861 Y:-4.462494}
{X:1007.079 Y:732.225} - {X:754.4736 Y:480.7125} - {X:4.546387 Y:3.412476} - {X:-3.644653 Y:-4.012512}
{X:1011.4 Y:735.4875} - {X:750.7538 Y:476.8125} - {X:4.320923 Y:3.262512} - {X:-3.719727 Y:-3.899994}
{X:1015.609 Y:739.5} - {X:747.0716 Y:473.325} - {X:4.208191 Y:4.012512} - {X:-3.682251 Y:-3.487488}
{X:1019.742 Y:743.1} - {X:742.7131 Y:469.5} - {X:4.133118 Y:3.599976} - {X:-4.358459 Y:-3.825012}
{X:1023.95 Y:747.0375} - {X:737.8661 Y:465.45} - {X:4.208191 Y:3.9375} - {X:-4.846985 Y:-4.049988}
{X:1028.045 Y:751.0875} - {X:731.7041 Y:461.8125} - {X:4.09552 Y:4.050049} - {X:-6.162048 Y:-3.637512}
{X:1032.366 Y:755.175} - {X:724.9409 Y:457.725} - {X:4.320923 Y:4.087463} - {X:-6.763184 Y:-4.087494}
{X:1036.725 Y:759.3} - {X:718.7037 Y:454.1625} - {X:4.358521 Y:4.125} - {X:-6.237183 Y:-3.5625}
{X:1040.896 Y:763.3125} - {X:712.7296 Y:450.825} - {X:4.170654 Y:4.012512} - {X:-5.974182 Y:-3.337494}
{X:1044.841 Y:767.3625} - {X:706.9808 Y:448.05} - {X:3.94519 Y:4.049988} - {X:-5.748718 Y:-2.775024}
{X:1048.485 Y:771.2625} - {X:706.9808 Y:448.05} - {X:3.644653 Y:3.900024} - {X:0 Y:0}
{X:1051.679 Y:774.825} - {X:706.9808 Y:448.05} - {X:3.193726 Y:3.5625} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:706.9808 Y:448.05} - {X:2.479858 Y:2.700012} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}
{X:1054.159 Y:777.525} - {X:799.8246 Y:402.375} - {X:0 Y:0} - {X:0 Y:0}

**Comment by Jjagg** [comment]
Closing because this is a Windows Phone issue.
