### ISSUE TITLE
Windows 8.1 Monogame+XAML Touch events keep firing

### ISSUE THREAD

**Issue by CAlbers** [MonoGame/MonoGame#2103]
Heey,

We released a game one week back and it all goes well but after upgrading to windows 8.1 we got a small bug which we can't fix.

What changed?

In windows 8.1 they changed a thing that when you activate a XAML textbox with touch and thereby activating the onscreen keyboard they shove now not only the textbox up so it stands above the onscreen keyboard no, they now shove your whole app up so your onscreen keyboard stays on the bottom and your whole game will be partially squeezed out of the frame. You can now swipe up and down in the area above your onscreen keyboard to move your app/game around.

What goes wrong?

If you just insert some input and focus another element it goes fine and nothing strange happens but when you move the game/app up and down while the onscreen keyboard is active and you then exit it by focusing another element it will keep firing a touch event while there isn't anything happening the TouchPanel.GetState() keeps giving old and random touch input.

How to reproduce

I recreated the bug in this project and thereby kinda proved it isn't anything project specific I maybe did wrong. https://www.dropbox.com/s/7rziu3m8l0mk0q9/XAML%20Textinput.rar
1. Touch on the screen so the Textbox and Button will appear
2. Touch the textbox so the onscreen keyboard appears
3. Type a letter and move the screen above the onscreen keyboard up and down
4. Press enter on the keyboard or tap the button on the left side of the screen
5. Set a breakpoint inside the Update() inside the if(touches.Count != 0) and watch the breakpoint being hit.

Hope my explanation is clear enough. This isn't the worst thing but it can be really frustrating when a player gets a sweet highscore then types in his/her name and accidentally swipes the screen and thereby cause the game to jam itself because the touch events are spammed and thereby uncontrollable which may result in low ratings D:

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
