### ISSUE TITLE
Clean install of MonoDevelop .mpack to Xamarin studio uses wrong reference

### ISSUE THREAD

**Issue by theZMan** [MonoGame/MonoGame#2151]
Clean install of Xamarin Studio 4.2.2
Clean install of the MonoDevelop.mpack from the 3.01 release
Create new Mono.Game project
Run 

App fails to run gives errors about MonoGame.Framework

Check references and see that the WindowsGL assembly is referenced by default

Try to disable that and enable the MacOS one and notice that the WindowsGL one gets reselected. Impossible to choose the MacOS version

Only solution appears to be to pull and build the source. Not very user friendly.

Problem also described with pictures here http://jaquadro.com/2013/09/monogame-hello-world-on-mac-os-x-and-xamarin-studio/

I've not tried this with MonoDevelop so not sure if it would repro there or not

**Comment by cra0zy** [comment]
The new monodevelop/xs addon is being worked on: #3361

**Comment by cra0zy** [comment]
@tomspilman This got fixed.
