### ISSUE TITLE
MacOS templates do not bundle the content

### ISSUE THREAD

**Issue by theZMan** [MonoGame/MonoGame#2152]
From http://jaquadro.com/2013/09/monogame-hello-world-on-mac-os-x-and-xamarin-studio/

---

If you pry into the exception, you’ll see that it couldn’t load the “logo” content item because an expected file is missing. In my case, that path is the heinously long “/Users/jaquadro/Projects/DemoGame/DemoGame/bin/Debug/DemoGame.app/Contents/Resources/Content/logo.xnb”.

The Content/logo.xnb in the path corresponds to the Content/logo.png in your project. This file should be getting copied into your built app package (DemoGame.app), but if you manually poke around in Finder, you won’t even find a Resources directory in DemoGame.app/Contents.

If you examine the Build Action of Content/logo.png, you’ll see it’s set to ‘None’. Instead, this should be set to ‘BundleResource’, which will cause it to be copied into the app bundle. I have also found the ‘Content’ build action to do the same thing, but official word is ‘Content’ is obsolete and don’t use it.

---

I'm guessing in the next release we will simply include the content project but if not this should be fixed in the template

**Comment by tomspilman** [comment]
@dellis1972  - Can this be closed now?
