### ISSUE TITLE
openal.dll missing?

### ISSUE THREAD

**Issue by maiorfi** [MonoGame/MonoGame#2156]
In order to work with MonoGame within Xamarin Studio for Windows, you have to install openal.dll from here:

https://code.google.com/p/rallyraid/downloads/detail?name=oalinst.zip&can=2&q=

**Comment by Shqrdx** [comment]
@tomspilman Useless issue, installer for MonoGame already offer OpenAL to install.

**Comment by tomspilman** [comment]
Does it?  Actually I don't think it does.

Maybe I should add it to the download link on the website.

**Comment by tgjones** [comment]
OpenAL is in the (Windows) installer file:
https://github.com/mono/MonoGame/blob/develop/Installers/Windows/MonoGame.nsi#L224

I haven't run the MG installer for a while, so I can't confirm whether it actually gets installed as part of MG.

**Comment by tomspilman** [comment]
Oh... I never noticed that.  If we are certain it is actually run and installed then i'm good to close this.  Can someone go verify?

**Comment by DennisSc** [comment]
I just tested, and can confirm that the Windows installer for mono 4.0.2 does NOT install the required openAL32.dll: If mono runtime is used stand-alone, my app crashes, telling me "System.DllNotFoundException: openal32.dll". 
If I add openAL via the above mentioned openAL installer, everything works smoothly (no crash, proper audio playback).

regards

**Comment by cra0zy** [comment]
@tomspilman This has been fixed, we are now providing the openal in both templates and the NuGet package.
