### ISSUE TITLE
Version 3.1.2.0 and Windows Phone 8 Project

### ISSUE THREAD

**Issue by michael1971** [MonoGame/MonoGame#2231]
I took the installer for version 3.1.2.0. I created a MonoGame Project for Windows Phone 8.
 I run it and recognized that the Draw(GameTime gameTime) function was never called (screen on emulator does not display time). This worked with previous versions.

**Comment by DDReaper** [comment]
@michael1971 can this issue be closed now? Tested with all WindowsPhone projects in the current 3.2 and dev releases without issue

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
