### ISSUE TITLE
Windows GL - Game Deactivate fired during startup

### ISSUE THREAD

**Issue by totallyeviljake** [MonoGame/MonoGame#2236]
In the GL version (maybe others), when the game launches, MG raises the Deactivated event during the first creation of the graphics device. This happens in ResetWindowBounds because of the following line:

```
        bool wasActive = IsActive;
        IsActive = false;
```

The IsActive property goes on to raise the game Deactivated event because the game is falsely marked as Active before initialization is completed.

Microsoft XNA does not do this. I am not sure when the game is considered "active" in the MSFT XNA world.

The full stack trace looks like this:

```
MonoGame.Framework.dll!Microsoft.Xna.Framework.Game.Raise<System.EventArgs>(System.EventHandler<System.EventArgs> handler, System.EventArgs e) Line 845 + 0x11 bytes    C#
MonoGame.Framework.dll!Microsoft.Xna.Framework.Game.OnDeactivated(object sender, System.EventArgs args) Line 652 + 0x1c bytes   C#
MonoGame.Framework.dll!Microsoft.Xna.Framework.GamePlatform.Raise<System.EventArgs>(System.EventHandler<System.EventArgs> handler, System.EventArgs e) Line 239 + 0x11 bytes    C#
```

>   MonoGame.Framework.dll!Microsoft.Xna.Framework.GamePlatform.IsActive.set(bool value) Line 150 + 0x4c bytes  C#
>     MonoGame.Framework.dll!Microsoft.Xna.Framework.OpenTKGamePlatform.ResetWindowBounds(bool toggleFullScreen) Line 202 + 0xa bytes C#
>     MonoGame.Framework.dll!Microsoft.Xna.Framework.Game.ResizeWindow(bool changed) Line 769 + 0x42 bytes    C#
>     MonoGame.Framework.dll!Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() Line 283 + 0xf bytes    C#
>     MonoGame.Framework.dll!Microsoft.Xna.Framework.GraphicsDeviceManager.Initialize() Line 383 + 0x8 bytes  C#
>     MonoGame.Framework.dll!Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() Line 124 + 0x8 bytes    C#
>     MonoGame.Framework.dll!Microsoft.Xna.Framework.GamePlatform.BeforeInitialize() Line 268 + 0x9 bytes C#
>     MonoGame.Framework.dll!Microsoft.Xna.Framework.Game.DoInitialize() Line 739 + 0xe bytes C#
>     MonoGame.Framework.dll!Microsoft.Xna.Framework.Game.Run(Microsoft.Xna.Framework.GameRunBehavior runBehavior) Line 466 + 0x8 bytes   C#
>     MonoGame.Framework.dll!Microsoft.Xna.Framework.Game.Run() Line 456 + 0x22 bytes C#

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
