### ISSUE TITLE
Strange issue loading PNGs under Linux

### ISSUE THREAD

**Issue by hach-que** [MonoGame/MonoGame#2238]
I've got a strange issue where running the same MonoGame game under Linux results in different texture loading results.  This is from loading PNG files:

![test](http://i.imgur.com/VWL1mp7.png)

![test](http://i.imgur.com/1tAFhiX.png)

![test](http://i.imgur.com/kydbLTn.png)

Could this be an issue with MonoGame, or is it more likely an issue with my graphics drivers?

**Comment by SirCmpwn** [comment]
:+1:, would like a fix, this is driving me absolutely up the wall

**Comment by tomspilman** [comment]
We have our own PNG reader code in the code base now...

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Utilities/Png/PngReader.cs#L39

Should be easy to change the call in Texture2D.FromSteam() to use the new reader.

**Comment by KonajuGames** [comment]
I've got a fairly large revamp of the texture content processing in
progress, and as part of that I will see about removing the use of
System.Drawing.Bitmap.​

**Comment by SirCmpwn** [comment]
I just tried putting PngReader in place of Texture2D.FromStream and hit this:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Utilities/Png/PngReader.cs#L173

Since Texture2D.FromStream doesn't bitch about this, it's probably fair to call this a regression and/or bug in PngReader. The image was created with GIMP and I doubt it's really busted.

The image: https://sr.ht/890a.png

**Comment by SirCmpwn** [comment]
Gonna try commenting out and see if it fails later or if we can afford to be tolerant.

**Comment by SirCmpwn** [comment]
That didn't seem to help.

**Comment by SirCmpwn** [comment]
Correction - apparently you can only use a `PngReader` once. Now it works, but the texture that was giving me hell before is now giving me a different kind of hell.

Before PngReader:

![](https://camo.githubusercontent.com/87d20c82aed38203e0fc81f1b7d53c509d583143/68747470733a2f2f73722e68742f636632362e706e67)

After PngReader:

![](https://sr.ht/db46.png)

**Comment by KonajuGames** [comment]
Are the textures being resized in the content processor?​

**Comment by SirCmpwn** [comment]
I'm not using the content processor.

**Comment by SirCmpwn** [comment]
I was able to fix this by reencoding the PNG file, though. I vote for using `PngReader` in `Texture2D.FromStream`.
