### ISSUE TITLE
graphics.isfullscreen = true doesnt work

### ISSUE THREAD

**Issue by Talorthain** [MonoGame/MonoGame#2248]
this.ScreenValue = new Point(1920, 1200);
        graphics.PreferredBackBufferWidth = this.ScreenValue.X;
        graphics.PreferredBackBufferHeight = this.ScreenValue.Y;
        graphics.IsFullScreen = true;
        graphics.ApplyChanges();

This code works perfectly in XNA but in monogame, the viewport always remains windowed. I have tried various resolutions and it incorrectly sets the size of the window

**Comment by Apostolique** [comment]
This can be closed.
