### ISSUE TITLE
Initial Window Position can no longer be set in 3.1.3-alpha Nuget Release

### ISSUE THREAD

**Issue by bootron** [MonoGame/MonoGame#2256]
In the 3.1.3-alpha release on Nuget for the MonoGame.Binaries, it appears to no longer be possible to set the initial window position. 

I used to be able to do something like this:

var screen = Screen.AllScreens.First(e => e.Primary);
Window.IsBorderless = true;
Window.Position = new Point(screen.Bounds.X, screen.Bounds.Y);
graphics.PreferredBackBufferWidth = screen.Bounds.Width;
graphics.PreferredBackBufferHeight = screen.Bounds.Height;

...but now the Window.Position option is no longer available to me. If I set the PreferredBackBufferWidth/Height to anything other than the default, it puts the window into the bottom right corner in an extremely awkward position and I can't find any way to move this programmatically. Any suggestions? By the way, I would obviously prefer to just have an actual FullScreenMode, but this appears to not be working also.

This is a link to a discussion about this original issue:
https://github.com/mono/MonoGame/issues/1672

**Comment by cra0zy** [comment]
This is fixed.
