### ISSUE TITLE
Cannot build MonoGame source on Xaramin for Mac

### ISSUE THREAD

**Issue by DanB91** [MonoGame/MonoGame#2309]
I am trying to set up MonoGame on my Mac.  
I am running:
- OS X 10.9.2
- Xaramin 4.2.3
- MonoMac MDK 3.2.7
- MonoMac MRE 3.2.7

I want to set up MonoGame on my Mac so I start on a project.  However, when I try to run a test project from the MonoGame template, the application just bounces in the dock forever.
Thus, I found on the internet a convoluted process of setting up MonoGame on Mac located here: https://monogame.codeplex.com/discussions/471565

Now I have it another road block.  When I try to build the MonoGame source to generate the needed .dlls, I get 3 build errors (and 67 warnings, but I am not sure if those are intended).

The 3 build errors are: 
- /Users/danb91/Downloads/MonoGame-3.0.1.0/MonoGame.Framework/Graphics/Texture2D.cs(27,27): Error CS1502: The best overloaded method match for 'MonoMac.AppKit.NSImage.AsCGImage(ref System.Drawing.RectangleF, MonoMac.AppKit.NSGraphicsContext, MonoMac.Foundation.NSDictionary)' has some invalid arguments (CS1502) (MonoGame.Framework.MacOS)  for line 623: `var cgImage = nsImage.AsCGImage (RectangleF.Empty, null, null);`
- /Users/danb91/Downloads/MonoGame-3.0.1.0/MonoGame.Framework/Graphics/Texture2D.cs(49,49): Error CS1620: Argument '#1' is missing 'ref' modifier (CS1620) (MonoGame.Framework.MacOS) for line 623: `var cgImage = nsImage.AsCGImage (RectangleF.Empty, null, null);`
- /Users/danb91/Downloads/MonoGame-3.0.1.0/MonoGame.Framework/Graphics/Texture2D.cs(17,17): Error CS0411: The type arguments for method 'Microsoft.Xna.Framework.Graphics.Texture2D.SetData<T>(T[])' cannot be inferred from the usage. Try specifying the type arguments explicitly (CS0411) (MonoGame.Framework.MacOS) for line 641: `texture.SetData(data);`

How do I get past these compilation errors?  Am I missing some sort of dependency?    Instead of compiling the MonoGame source, is there someplace I can just get the prebuilt dll's for Mac?

Also: Why aren't the proper dll's included with the .mpack?  Are there no Mac build servers?  Is there anything I can do to help?

Please excuse any ignorant questions.  Thanks very much for the help!

**Comment by tomspilman** [comment]
@dellis1972 - I think this is moot or irrelevant now... if so go ahead and close it.

**Comment by cra0zy** [comment]
@tomspilman This got fixed a long time ago in a galaxy far far away...
