### ISSUE TITLE
Monogame 3.0.1 => Windows Store App => GCLatencyMode.LowLatency => freezes

### ISSUE THREAD

**Issue by Ziriax** [MonoGame/MonoGame#2325]
When porting my XNA game to MonoGame for running it on Windows 8.1, I noticed that after a minute or so, it was completely freezing (100% CPU), although no exceptions were thrown, and breaking the debugger didn't give any clue what was happening either. 

After a couple of days I found the culprit

To reproduce: 
make a new Windows Store App using the MonoGame 3.0.1 VS template
change the Draw call so it flashes the screen e.g. between black and white.
in the game constructor, add the line GCSettings.LatencyMode = GCLatencyMode.LowLatency;
start the game, and keep tapping with multiple fingers on the screen.
after a couple of seconds, the screen freezes.
My system is a Surface Pro 2 128GB, Windows 8.1 x64, and I also have a Wacom Bamboo Fun tablet attached.

I wonder if other people experience the same issue?

PS: Curiously, setting the latency to SustainedLowLatency (which I guess is the best setting for games?) does NOT freeze the game

**Comment by Shqrdx** [comment]
@tomspilman The current version of MonoGame is 3.2, so if author still think that issue is necessary he could recreate it. I doubt that GC is the thing the standart C# developer should touch(except GC.Collect).

**Comment by Ziriax** [comment]
[A related thread on SO](https://news.ycombinator.com/item?id=4284624)

**Comment by Ziriax** [comment]
I don't know if this issue still occurs in 3.6, but Microsoft actually *recommends* using the `SustainedLowLatency` GC mode, see https://developer.microsoft.com/en-us/windows/mixed-reality/performance_recommendations_for_unity

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
