### ISSUE TITLE
iOS SoundEffect requirements

### ISSUE THREAD

**Issue by igor9silva** [MonoGame/MonoGame#2327]
What does an audio file (.wav) need to be playable on iOS/OS X?
I've tried with a lot of .wav files within all the bitrates possible. Some were signed 16-bit PCM, other ones were unsigned 8-bit PCM.

I've tried processing them to .xnb, but with no success too. (I'm not able to generate .xnb ones for audio files on OS X, I get this error: "Error: Processor 'SoundEffectProcessor' had unexpected failure!").

I know that there is no problem on coding, since it worked with an .xnb file I get from an internet sample.

I tried with a lot files from MonoGame-Samples and MonoGame-StarterKit too.

Thanks in advance.

**Comment by igor9silva** [comment]
@Jjagg was it ever solved?

**Comment by Jjagg** [comment]
@KonajuGames did a lot of work on audio processing. There are still some open issues for audio that are more specific than this one (e.g. #4470), but in general processing sounds works.

**Comment by igor9silva** [comment]
That's great to hear, thanks!
