### ISSUE TITLE
GraphicsProfile is changed upon device reset on Windows Phone 8.1

### ISSUE THREAD

**Issue by Christian24** [MonoGame/MonoGame#2361]
Hi,

I have found out that my game crashes when I suspend and then resume it on Windows Phone 8.1. I have investigated a little and found out that the GraphicsProfile on startup is set to be HiDef and upon device reset it is set to Reach. The change appears to be in UpdateDevice in this exact line:             GraphicsProfile = _d3dDevice.FeatureLevel <= FeatureLevel.Level_9_3 ? GraphicsProfile.Reach : GraphicsProfile.HiDef;

Thanks in advance. I do love MonoGame :)

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
