### ISSUE TITLE
StorageContainer Player folder accuracy

### ISSUE THREAD

**Issue by flibitijibibo** [MonoGame/MonoGame#2363]
I just pushed this fix to MG-SDL2:

https://github.com/flibitijibibo/MonoGame/commit/677b2d499df34ef99dc7b71ae777ce8085d97dd9
https://github.com/flibitijibibo/MonoGame/commit/241b534767c16b1789972f1447617032513df3d3
https://github.com/flibitijibibo/MonoGame/commit/22d8861589889062788fd4a7d964ae4c9244642d

The problem, in summary (pulled from my G+ post https://plus.google.com/102593483001615978126/posts/7qE6nJGcdL2 ):

"Previously, StorageDevice exhibited the following behavior:
- When opening a StorageContainer with a PlayerIndex, the container created a folder Player0 to Player3, depending on the PlayerIndex.
- When opening a StorageContainer without a PlayerIndex, the container did not create any folder, and simply operated on the game save directory's root folder.

As it turns out, NEITHER of these behaviors are correct! From the 'Implementation on Windows' section of the following MSDN article:

http://msdn.microsoft.com/en-us/library/bb200105.aspx

'When no PlayerIndex is specified, content is saved in the AllPlayers folder. When a PlayerIndex is specified, the content is saved in the Player1, Player2, Player3, or Player4 folder, depending on which PlayerIndex was passed to BeginShowSelector.'"

For the most part this isn't too big of a deal, but for Windows titles trying to keep XNA compatibility, this essentially breaks save compatibility entirely. The commit above is pretty small as it is, but the main thing to pull from it is the `if (playerIndex.HasValue)` changes.

**Comment by cra0zy** [comment]
Removed API so closing.
