### ISSUE TITLE
Implement PNG and JPG Reader/Writer

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#2424]
Our current path of using platform provided PNG/JPG readers/writers is unreliable.  Not implemented one some platforms, threading issues on others, and generally different behaviors across all platforms.

We want to remove these platform differences by including our own simple implementations written purely in C#.  Some rules for these readers/writers:
- Requires no extra binary dependencies.
- Single source file.
- Must be safe to read/write PNGs from multiple threads simultaneously.
- No GPL or LGPL licenses.
- Readers should be pretty flexible.
- Writes need little flexibility if any.

For PNG we talked about these for readers...

  http://code.google.com/p/pngcs/
  http://lodev.org/lodepng/
  http://lodev.org/lodepng/picopng.cpp

PicoPNG seems like the best choice being under 500 lines of code, but it needs conversion to C#.

We haven't identified a good PNG writer yet.

For JPEG we have a few suggestions...

  http://keyj.emphy.de/nanojpeg/
  https://github.com/Deathspike/NanoJPEG.NET
  http://code.google.com/p/fjcore/

NanoJPG which already has a C# port seems like the best choice so far.

We haven't identified a good JPG writer yet.

We will put these implementations into the existing utilities folder:

https://github.com/mono/MonoGame/tree/develop/MonoGame.Framework/Utilities

 ... one file for each with names like PngReader, PngWriter, JpgReader, JpgWriter.  We change their namespace to be within `MonoGame.Utilities` and make sure API feels sufficiently C# like and common possibly passing a `Stream` to them directly.  We need to make sure the only things public are the external API to use the library.  We will keep all the original author comments and license info for attribution of the original work.

We would then use these helpers across all platforms removing all platform specific PNG/JPG code within MonoGame.

**Comment by tomspilman** [comment]
I found a fairly simple C# JPEG encoder here...

  http://www.codeproject.com/Articles/83225/A-Simple-JPEG-Encoder-in-C

... could be paired up with C# ported STB code to get a complete PNG/JPEG reader/writer combo.

**Comment by theZMan** [comment]
I talked to some Microsoft folk and got background info.

The PNG/JPG reader writer, resizer is a wrapper around WIC http://msdn.microsoft.com/en-us/library/windows/desktop/ee719902(v=vs.85).aspx 

It uses WIC for all operations including the resize and clipping and uses BiCubic filtering for resize operations.

**Comment by theZMan** [comment]
I found a fully managed JPG reader and Writer here https://github.com/BitMiracle

I note that from stream also supports GIF http://msdn.microsoft.com/en-us/library/ff434103.aspx

Though there's no GIF writer required only PNG and JPG http://msdn.microsoft.com/en-us/library/Microsoft.Xna.Framework.Graphics.Texture2D_methods.aspx

This is one of the last things I need for guncraft so I am going to have to make some choices soon :-)

**Comment by tomspilman** [comment]
I don't want to see us add a dependency on another assembly if we can avoid it.  Unless that assembly is PCL and solves JPEG and PNG reading and writing.

IMO the best path forward still seems to be porting some code from stb_image.c.

**Comment by theZMan** [comment]
BitMiracle is Open source and has a decent license - I was just going to grab the code. I've been testing pngcs and its also a good implementation of the standard.

stb_image doesn't have a JPG writer and nobody should have to write that code ever...

**Comment by tomspilman** [comment]
> stb_image doesn't have a JPG writer 

That is why I linked this a few days ago...

 http://www.codeproject.com/Articles/83225/A-Simple-JPEG-Encoder-in-C

A simple JPG encoder in 2 or 3 source files.

**Comment by theZMan** [comment]
If someone wants to do those ports that's cool... I'm just more comfortable in c# so if you prefer C ports then I will defer to someone else.

We only need PNG anyway so I'll take the fast track in our fork and just use one of the c# PNG implementations.

**Comment by tomspilman** [comment]
> if you prefer C ports then I will defer to someone else.

I don't prefer C ports.    What i prefer is the least amount of code, source files that get the job done.

Note that link I posted was C# code and not C...  the URL is just stupid.

**Comment by disportium** [comment]
I have a basic PNG reader/writer going, implemented from spec and using source from [ZLIB.NET](http://www.componentace.com/zlib_.NET.htm) (which is BSD licensed) for the Deflate compression algorithm.

I'm working on making it a bit more robust; a pull request should be forthcoming later this week.

**Comment by tomspilman** [comment]
@disportium - Cool... i'm looking forward to it.

**Comment by Jjagg** [comment]
We're using StbImageSharp now! :)
