### ISSUE TITLE
Warning Cleanup

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#2433]
We could use a pass cleaning up warnings in the build logs.

You just need to look at the [build log from the last successful build](http://teamcity.monogame.net/viewLog.html?buildTypeId=MonoGame_DevelopWin&buildId=lastSuccessful&buildBranch=%3Cdefault%3E&tab=buildLog&guest=1) and search for "warning".

**Comment by tomspilman** [comment]
Looks like we have around 100 warnings that have built back up in the build.  If someone gets the time to clean these up it would be good to get it solved then enable the build failure on warnings.

**Comment by cra0zy** [comment]
This seems... FUN?!? I'm on it.

**Comment by cra0zy** [comment]
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsMetrics.cs#L19

ulong is not CLS compliant, what should be done about this? disable the warning for it? change to something else?

**Comment by KonajuGames** [comment]
> ulong is not CLS compliant, what should be done about this? disable the warning for it? change to something else?

I would suggest changing them to `long`.  If the metrics ever get so high that they overflow a `long`, we have bigger problems.

**Comment by WardBenjamin** [comment]
I would suggest changing them to long. If the metrics ever get so high that they overflow a long, we have bigger problems.

I agree. However, another possible option for future reference in this case is to mark it non-compliant, aka `[CLSCompliant(false)]` above the method header. Not a suggestion, but just for reference.
