### ISSUE TITLE
Mouse input on destkop platforms

### ISSUE THREAD

**Issue by thefiddler** [MonoGame/MonoGame#2464]
I'm opening this issue to track the status of the `Mouse` implementation in MonoGame.

According to the XNA documentation and my own observations (please correct any mistakes):
1. `Mouse.GetState()` reports the absolute coordinates of the desktop cursor, with the origin set to the window specified by `Mouse.WindowHandle`. A cursor left or above the window has negative coordinates.
2. Mouse coordinates are reported in integer pixels. The resolution of the mouse is limited by the resolution of the monitor (typically 96dpi.)
3. Pointer ballistics are always applied. There is no option to disable mouse acceleration. 
4. The mouse is not restricted to the `GameWindow`. Users can freely move the cursor outside the window and focus different applications. The state of the cursor can be queried even if the `GameWindow` does not have focus.
5. The mouse is restricted by the desktop rectangle. Once the mouse reaches a desktop edge, it will no longer report movement in that direction. Infinite (relative) motion can only be achieved by calling `Mouse.SetPosition` to reset the mouse position.
6. By default, the mouse cursor is invisible inside the `GameWindow`. This can be changed by setting `Game.IsCursorVisible` to true. Using a custom mouse cursor is _not_ supported.
7. `Mouse.SetPosition` does not appear to move the actual cursor, only change its logical position. If the `GameWindow` has focus, `SetPosition` works everywhere on screen. Otherwise, it only works if the cursor lies within the `GameWindow` bounds.

Judging from the above, it appears that `Mouse.GetState` is a thin wrapper around the `GetCursorPos` Windows API. I must admit I find this somewhat surprising, as points 2 and 3 are usually considered a deal-breaker for specific kinds of games, notably first-person shooters.

Point 3 has the additional disadvantage that pointer ballistics differ significantly between operating systems. A mouse control scheme tuned to work on Windows will feel awkward on Mac OS X and vice versa.

Edit: users can set `Mouse.WindowHandle` to a different window in order to change the origin of the coordinate system. It is unlikely that this can be implemented in a cross-platform fashion, so I am ignoring this property in my tests.

**Comment by Apostolique** [comment]
Is there anything left to fix in here or is this good to close?
