### ISSUE TITLE
OpenTKGamePlatform has been updated and calls Net.Session.Exit

### ISSUE THREAD

**Issue by DDReaper** [MonoGame/MonoGame#2511]
Whilst doing the NET separation I came across a reference to the .NET namespace in OpenTKGamePlatform.cs

On line 158/159 it calls:
Net.NetworkSession.Exit();

This wasn't done on any other platform apart from Android and this was added very recently. 

It has been commented out as part of the .NET work, can this be investigated to ensure it is not needed.

**Comment by cra0zy** [comment]
@tomspilman This can be closed since OpenTK is no longer in use.
