### ISSUE TITLE
Design Documentation Outline

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#2520]
We need to come up with a high level outline of what we want to include in the "user manual", the non-reference part of the [MonoGame documentation hub](http://www.monogame.net/documentation/).

My initial rough outline:
- Introduction
  - What is MonoGame
  - System Requirements
  - Setting Up MonoGame
  - MonoGame FAQ
  - Help & Support
- Getting Started
  - The Basics
  - Creating Your First Game
  - Cross-Platform Games
- Coding Your Game
  - The Game Loop
  - Loading Content
  - Rendering The Scene
    - SpriteBatch
    - DrawPrimitive
    - Using Effects
  - Handling User Input
  - Playing Sound Effects
  - Playing Music
- Adding Art, Sounds, Music, Etc.
  - What is Game Content
  - The Pipeline Tool
  - Custom Effects
  - Custom Content Types
- Distributing Your Game
- Tools
  - 2MGFX
  - MGCB
- Credits
- Copyrights

Of course each of these sections would need subsections dealing with platform specific issues along with the common information.

Note the goal here is to replace the need to depend on the Microsoft XNA documentation and hopefully improve upon what they provided.

**Comment by tomspilman** [comment]
We need to kick this off again.

If no one has actual constructive ideas on what the high level doc outline should be, then I'll just make a decision myself and get the structure roughed in over this next weekend.

**Comment by cra0zy** [comment]
I think "Getting Started" and "Coding Your Game" should be moved to under "Tutorials". Also my basic idea of the Tutorials tree would be:
<ul>
<li>
Tutorials
<ul>
<li>
Getting Started
<ul>
<li>
The Basics
</li>
<li>
Creating Your First Game
</li>
<li>
Cross-Platform Games
</li>
</ul>
</li>
<li>
Coding Your Game
<ul>
<li>
The Game Loop
</li>
<li>
Loading Content
</li>
<li>
Rendering The Scene
<ul>
<li>
SpriteBatch
</li>
<li>
DrawPrimitive
</li>
<li>
Using Effects
</li>
</ul>
</li>
<li>
Handling User Input
</li>
<li>
Playing Sound Effects
</li>
<li>
Playing Music
</li>
</ul>
</li>
<li>
Particle Effects
</li>
<li>
Shaders
</li>
<li>
Coding a 3D Game
<ul>
<li>
Matrix Basics
</li>
<li>
Camera
</li>
<li>
3D Collision Detection
</li>
</ul>
</li>
<li>
AI
<ul>
<li>
Pathfinding
</li>
</ul>
</li>
<li>
Multiplayer
<ul>
<li>
Networking Basics
</li>
<li>
Peer to Peer
</li>
<li>
Server Client
</li>
</ul>
</li>
<li>
Stretching and Scaling to Screen
</li>
</ul>
</li>
</ul>

Do tell me what should be added or what should be moved to sub categories.

**Comment by DDReaper** [comment]
Some of those areas are a bit specialised and outside the scope of the MG project it'self, such as Particle Effects, Animation, AI and Multi-player.
There is also the question of supported frameworks / plug-ins which the community should be able to contribute to. For instance SunBurn now have a MG aware version of their engine.

So I would move those sections to a "Other useful tutorials" section or "Game Development links"

Shaders have certainly been a gap for myself, especially with writing them under MGFX.  Reimers tutorials were great and could be used as a template there but targetting MG specific shader building for all platforms.

The primary tutorials should be just about implementing the core of MG itself.

**Comment by cra0zy** [comment]
1) I think that multiplayer is a part of MG project, Microsoft.Xna.Framework.Net....
2) A section for helping with implementing other frameworks would be nice, I agree
3) I think it's important to put in some tutorials like how to setup Particle Effects and Animations, it would help people(and Aliens?) when they are just starting out with Monogame. Organization of everything is also important, and putting it under "Other useful tutorials" doesn't look very nice IMO.

**Comment by tomspilman** [comment]
@cra0zy @DDReaper 

I think we need focus on teaching how MonoGame works and how to best use it for cross platform game development.  Teaching how to use `Microsoft.Xna.Framework.Net` makes sense, but teaching collision detection for example does not.... at least for our first full pass at documentation.

**Comment by cra0zy** [comment]
What are monogames system requirements?

**Comment by tomspilman** [comment]
> What are monogames system requirements?

There are two sets of requirements realty.

First the requirements for developers writing games with MonoGame.

Second the minimum requirements for all the various target platforms MonoGame supports.

Seems like all this would be a good document to add to the outline.

**Comment by cra0zy** [comment]
@tomspilman I had in mind to write both, can you write system requirements for the platforms you know?

**Comment by tomspilman** [comment]
> , can you write system requirements for the platforms you know?

Right now I can't... at work... don't have time to do the research.

Just start the doc, fill out the parts you know, leave TODOs in the ones you don't.

**Comment by benknoble** [comment]
The _Getting Started_ Section currently needs a lot of work--the _Tutorials_ section looks strongly filled out but there's no "One tutorial to rule them all" that would belong in _Getting Started_ that gives a good explanation of how to actually begin understanding MonoGame.
