### ISSUE TITLE
IntermediateOutputPath issues in Xamarin.Android for VS

### ISSUE THREAD

**Issue by KonajuGames** [MonoGame/MonoGame#2551]
Is anyone else using latest stable Xamarin.Android in Visual Studio getting the issue where the specified IntermediateOutputPath in the MonoGame csproj is used for some files and not for others?

In Xamarin Studio the same csproj works fine and places all intermediate files in the specified path.

This is the obj tree as it should be created (as it is by Xamarin Studio).  Everything is under Android\AnyCPU\Debug.

```
\---Android
    \---AnyCPU
        \---Debug
            |   MonoGame.Framework.Android.csproj.FileListAbsolute.txt
            |   MonoGame.Framework.dll
            |   MonoGame.Framework.pdb
            |   __AndroidLibraryProjects__.zip
            |
            +---library_project_imports
            |   +---assets
            |   +---bin
            |   +---java
            |   \---res
            \---res
```

This is the tree produced by Visual Studio.  Some files and directories are under Android\AnyCPU\Debug, but the DLL and PDB are placed in Debug.

```
+---Android
|   \---AnyCPU
|       \---Debug
|           |   DesignTimeResolveAssemblyReferencesInput.cache
|           |   MonoGame.Framework.Android.csproj.FileListAbsolute.txt
|           |   __AndroidLibraryProjects__.zip
|           |
|           +---library_project_imports
|           |   +---assets
|           |   +---bin
|           |   +---java
|           |   \---res
|           \---res
\---Debug
    |   MonoGame.Framework.dll
    |   MonoGame.Framework.pdb
    |
    \---TempPE
```

This causes a build error because it can no longer find the DLL because it put it in the wrong spot and then looks in the right spot and can't find it.

**Comment by theiwaz** [comment]
I've had a problem with XAMLCTASK that the intermediateoutputpath contained a full path. The build target concatenates
    
    Assembly = "$(MSBuildProjectDirectory)\$(IntermediateOutputPath)$(TargetFileName)"

Making the assemblypath invalid
