### ISSUE TITLE
DrawString is 10x slower than xna DrawString

### ISSUE THREAD

**Issue by EnemyArea** [MonoGame/MonoGame#2578]
Hi, 
I was testing my XNA gameengine with Monogame and got some strange peformance issues. I profiled it with the ANTS Performance Profiler and see that the drawString method is the root of all evil. In 550 hit counts the DrawString method needs 0.137 seconds in Monogame but only 0.011 seconds in XNA.

**Comment by nkast** [comment]
The code at https://github.com/danzel/DrawTextTest fires one GC during the test. A temp fix would be to call GC.Collect() at `.LoadContent()`

**Comment by Jjagg** [comment]
SpriteBatch has been optimised a bunch in the past 5 years (mostly by Nikos 😄), so I'm closing this.
