### ISSUE TITLE
GraphicsDevice depends on the Game class

### ISSUE THREAD

**Issue by EugenyN** [MonoGame/MonoGame#2586]
recent changes (b36884c65b4885eb097a1d5455d6ee5f72ab2429) in GraphicsDevice.OpenGL.cs not allow to use custom winforms control for rendering. 

To render to custom winfroms control we in our project do not use Game class. 

But with recent changes we must use the Game and OpenTKGameWindow classes.

example: http://jaquadro.com/2013/04/monogame-winforms-repository/

**Comment by harry-cpp** [comment]
Custom win forms controls and even gtk widgets are possible with the current release so closing this.
