### ISSUE TITLE
Building WindowsGL Content

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#2591]
So currently our `TargetPlatform` enum for the new content pipeline looks like this:

```
    public enum TargetPlatform
    {
        Windows,
        Xbox360,
        WindowsPhone,
        iOS,
        Android,
        Linux,
        MacOSX,
        WindowsStoreApp,
        NativeClient,
        Ouya,
        PlayStationMobile,
        WindowsPhone8,
        RaspberryPi,
        PlayStation4,
    }
```

The problem here is that `Windows` currently builds for DirectX content.  So what do you specify when you need content for the WindowsGL platform?  While most of the content works fine, Effects for DirectX vs OpenGL are completely different.

Should we just make `WindowsGL` a new value in `TargetPlatform`?

**Comment by cra0zy** [comment]
@tomspilman This is fixed.
