### ISSUE TITLE
AccessViolationException windows phone 8 on activation

### ISSUE THREAD

**Issue by thefex** [MonoGame/MonoGame#2612]
I use MonoGame 3.2 for Windows Phone 8.1. Sometimes when my game is deactivated and activated back I get "An unhandled exception of type 'System.AccessViolationException' occurred in SharpDX.Direct3D11.DLL"

call stack:
     SharpDX.Direct3D11.DLL!SharpDX.Direct3D11.DeviceContext.Flush()  
     SharpDX.Direct3D11.DLL!SharpDX.Direct3D11.DeviceContext.Dispose(bool disposing)  
     SharpDX.DLL!SharpDX.DisposeBase.CheckAndDispose(bool disposing)  
     SharpDX.DLL!SharpDX.DisposeBase.Dispose()  
     SharpDX.Direct3D11.DLL!SharpDX.Direct3D11.Device.Dispose(bool disposing)  
     SharpDX.DLL!SharpDX.DisposeBase.CheckAndDispose(bool disposing)  
     SharpDX.DLL!SharpDX.DisposeBase.Dispose()  
     SharpDX.DLL!SharpDX.Utilities.Dispose(ref SharpDX.Direct3D11.Device comObject)  
  MonoGame.Framework.DLL!Microsoft.Xna.Framework.Graphics.GraphicsDevice.UpdateDevice(SharpDX.Direct3D11.Device device, SharpDX.Direct3D11.DeviceContext context)  
    MonoGame.Framework.DLL!Microsoft.Xna.Framework.Graphics.GraphicsDevice.Initialize()  
     MonoGame.Framework.DLL!MonoGame.Framework.WindowsPhone.SurfaceUpdateHandler.Draw(SharpDX.Direct3D11.Device device, SharpDX.Direct3D11.DeviceContext context, SharpDX.Direct3D11.RenderTargetView renderTargetView)  
     MonoGame.Framework.DLL!MonoGame.Framework.WindowsPhone.XamlGame.DrawingSurfaceBackgroundContentProvider.Draw(SharpDX.Direct3D11.Device device, SharpDX.Direct3D11.DeviceContext context, SharpDX.Direct3D11.RenderTargetView renderTargetView)  
     SharpDX.Direct3D11.DLL!SharpDX.Direct3D11.DrawingSurfaceBackgroundContentProviderShadow.DrawingSurfaceBackgroundContentProviderVtbl.Draw(System.IntPtr thisPtr, System.IntPtr hostDevice, System.IntPtr hostDeviceContext, System.IntPtr hostRenderTargetView)

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
