### ISSUE TITLE
Can't access desktop resolution

### ISSUE THREAD

**Issue by DissidentDan** [MonoGame/MonoGame#2619]
In XNA, I was able to use GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width and Height to access the desktop resolution. In Monogame, it always returns 800x600.

This is important for me, as my game defaults to the desktop resolution the first time that you launch it.

**Comment by Dacarnix** [comment]
Im getting the same issue as drenton, using the 3.5 beta built binaries!

**Comment by Dacarnix** [comment]
Incase anyway comes looking here, I have a 1080p monitor, but like drenton, Monogame reported 1536x864. HOWEVER, this was due to the Display settings ZOOM with Windows, I had 125%, which reported a 1080p for 1536x864. So this is something to consider.

**Comment by tomspilman** [comment]
> HOWEVER, this was due to the Display settings ZOOM with Windows

Interesting... looks like the code here...

https://github.com/mono/MonoGame/pull/2738/files#r50624915

... needs to be fixed to account for the desktop zoom.
