### ISSUE TITLE
Able to add a custom cursor.

### ISSUE THREAD

**Issue by kourbou** [MonoGame/MonoGame#2659]
Hello,
I tried to use a spriteBatch as a cursor but it has a short delay. In OpenTK there is an option to set a custom cursor. Maybe it could be possible to implement this directly in MonoGame for both WindowsGL and WindowsDX.

**Comment by cra0zy** [comment]
Base implementation for this has been added with #4755, currently implemented for DesktopGL platform.

**Comment by cra0zy** [comment]
@tomspilman This got implemented in the SDL branch, this should be closed.
