### ISSUE TITLE
Everything is black

### ISSUE THREAD

**Issue by cmllr** [MonoGame/MonoGame#2714]
I've created a new solution and everything is black. I'm using Linux (3.14), MonoDevelop 4.2.2 and MonoGame 3.2. The app does not crash, but it shows nothing at all.

**Comment by cra0zy** [comment]
@tomspilman Considering I have the exact same graphics card I can say that this is fixed.

Fun side info, there was a bug in fglrx driver (aka. AMD proprietary graphics driver for Linux, which I can see was used) that was causing this bug with OpenGL windows.
