### ISSUE TITLE
Memory leak in Windows Desktop Projects

### ISSUE THREAD

**Issue by ChrisSippel** [MonoGame/MonoGame#2717]
First I would like to say I love the new version of MonoGame!

I believe I have found a memory leak in the Windows Desktop projects of MonoGame.

If I create just a blank Windows OpenGL project and just let it run it seems to consume ~4 to ~100 KB of memory every second or so regardless of activity on the screen.

If I create just a blank Windows DirectX project and just let it run, it on occasion consumes ~4 to ~8 KB of memory, but not very often. If I move my mouse on the screen, then I have the memory leaks and it is ~4 to ~100 KB every second.

I have seen the GC come by and collect some garbage but it is typically only  8KB or so, it also doesn't happen very often.

I am using 3.2 of MonoGame in Visual Studio 2012 on a Windows 7 machine.

MonoGames was gotten from the installer on the website.

**Comment by cra0zy** [comment]
@tomspilman Since we dumped OpenTK this can be closed.
