### ISSUE TITLE
Auto-generate link to implementation. [Docs]

### ISSUE THREAD

**Issue by Phrohdoh** [MonoGame/MonoGame#2743]
I've started browsing the monogame.net docs (thank you for something I can use, and not just cloning the beast of MSDN) and many times wish there were a link to the implementation of whatever I was browsing at the moment.

I've not taken a look at documentation generation (if any exist at all) so I do now know how feasible this is.

**Comment by Jjagg** [comment]
DocFX does this, so once we switch over this will be fixed.
