### ISSUE TITLE
Fullscreen mode does not working

### ISSUE THREAD

**Issue by ChazAshley** [MonoGame/MonoGame#2758]
Hey, I'm new in Monogame and just wanted to switch my game window to fullscreen mode using
 `graphics.IsFullScreen = true;`
 why?

**Comment by astynax777** [comment]
I can verify this is not fixed as of 3.2 on.  I'm using Windows 8.1 and attempting to set fullscreen mode using the following lines does not toggle, whereas it works in 3.0 and 3.0.1.
```
graphics.IsFullScreen = true;
graphics.ApplyChanges();
```
Is there a workaround for this?

**Comment by Apostolique** [comment]
I believe this should be fixed.
