### ISSUE TITLE
Native controls being corrupted

### ISSUE THREAD

**Issue by ischyrus** [MonoGame/MonoGame#2759]
My app isn't an actual game, however I am using MonoGame to do some rendering in one of the activities. It works great on iPad and Windows 8, however on Android I am running into an issue where after coming back from a locked screen all of the platform controls like TextView and the ActionBar are all funky.

I have attached some screenshots. One is what it should look like and the other is what it looks like after a locked screen. The app remains responsive and I can navigate between activities ... it's just that everything is wonky. Namely, TextView and the ActionBar.

Has anyone seen this or able to point me in a direction to fix this? It happens nearly 100% of the time on a Nexus 5. It is less frequent on a Nexus 7.

![2014-06-28 18 52 43](https://cloud.githubusercontent.com/assets/41187/3432223/47ce96d2-0072-11e4-8be0-b277ae282ade.png)
![2014-06-28 18 52 47](https://cloud.githubusercontent.com/assets/41187/3432224/49a25598-0072-11e4-9282-924395a7adbc.png)
![2014-06-28 18 51 54](https://cloud.githubusercontent.com/assets/41187/3432225/4b369388-0072-11e4-9fcb-0e91d52dcb42.png)
![2014-06-28 18 52 01](https://cloud.githubusercontent.com/assets/41187/3432226/4cbf5f00-0072-11e4-985b-82f47f67b35e.png)

**Comment by cra0zy** [comment]
Gonna close this as more than likely, this got resolved.
