### ISSUE TITLE
Fix Templates With GamerServices

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#2765]
Some of the VS templates have a `using Microsoft.Xna.Framework.GamerServices`, but we don't reference the new `MonoGame.Framework.Net` assembly.  

Either we add the assembly or need to remove the using.

Probably adding the assembly in is the most useful as it lets people know where GamerServices stuff is now.

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
