### ISSUE TITLE
GetCue from SoundBank for a Cue that contains a Sound with multiple Tracks fails

### ISSUE THREAD

**Issue by wldevries** [MonoGame/MonoGame#2768]
Create a `Sound` and add several `Wave`s to it. This will create `Track`s for that `Sound` that play at the same time when the Sound is played. This fails in MonoGame with a `NotSupportedException`.

**Comment by wldevries** [comment]
I guess a full Xact implementation is a no go for Monogame?

**Comment by tomspilman** [comment]
This was already fixed.
