### ISSUE TITLE
Pipeline error when attempting to clean or build MonoGame.Samples Platformer2D

### ISSUE THREAD

**Issue by swquinn** [MonoGame/MonoGame#2779]
I have successfully built the Pipeline project (both debug and release), but run into an error when attempting to clean or build a project from within the Pipeline.

After importing the [MonoGame.Samples](https://github.com/Mono-Game/MonoGame.Samples) `Platformer2D .contentproj` into `Pipeline.exe` and attempting to Build/Clean the project I receive the following error:

```
Build process failed!

The system cannot find the file specified
  at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
  at MonoGame.Tools.Pipeline.PipelineController.DoBuild(String commands) in > c:\Projects\CSharp\MonoGame\Tools\Pipeline\Common\PipelineController.cs:line 346
```

It is worth noting that even creating a new content builder project, and not adding any assets to it, results in the same error.

The Pipeline I have compiled is based off of the **develop**  branch.

**Comment by cra0zy** [comment]
@tomspilman This can be closed, it's unrelated to the main MG repo.
