### ISSUE TITLE
Content Pipeline Internal Plugin API

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#2781]
Currently the content pipeline has to be built to support specific platforms.  For instance the content pipeline has to know how to do DXT and PVRTC compression.  In this case that is ok as these are public formats on open platforms.

The problem comes in when we have to deal with platforms like PlayStation4 or XBox One where there will be closed source formats that cannot be built into the existing content pipeline.

Currently our solution is sort of lame.  We have a "special" build for these platforms that has the private bits needed for close platforms.  This then requires us to have multiple content pipelines installed on the same system and we have to select the right one based on the target platform.  This is a mess.

Instead we should develop a simple API internal to the content pipeline assembly that abstracts these platform details.  For instance if you just consider texture compression:

```
interface ITextureCompressor
{
  void CompressTexture( GraphicsProfile profile,
                       TextureContent content, 
                       ContentProcessorContext context, 
                       bool generateMipmaps, 
                       bool premultipliedAlpha);
}
```

At startup the pipeline would load all the `Pipeline.Plugin.XXXX.dll` found in the pipeline install path.  Then using attributes we would find the correct `ITextureCompressor` for a particular target platform.

This same technique will be used for other cases like sound effect conversion, song conversion, video conversion, etc.

This sort of design allows us to easily extend an existing MonoGame content pipeline install with platform specific formats.

**Comment by KonajuGames** [comment]
While adding the support ETC1, I've been implementing the compression in a similar manner to the XNA content pipeline.  I've added a `Etc1BitmapContent` that encapsulates everything required to compress the texture.  The `TryCopyFrom` method accepts a `BitmapContent`, will convert it to an intermediate format if required, such as `PixelBitmapContent<Vector4>`, and then call the external library to compress to the ETC1 format.

To extend this in a generic manner, we would need to register a class derived from BitmapContent as supporting a specific TextureProcessorOutputFormat.  We could do this by adding an attribute to the class such as `[BitmapContent(TextureProcessorOutputFormat.EtcCompressed)]`.  The `GraphicsUtil.CompressTexture` method could then do a reflection search for the class that supports the desired output format, create an instance of it and call `BitmapContent.Copy(src, dest)` as required.

**Comment by KonajuGames** [comment]
This also has the advantage that it properly implements the TryCopy methods of BitmapContent-derived classes and would work with existing XNA content pipeline extensions.

**Comment by tomspilman** [comment]
> adding an attribute to the class such as `[BitmapContent(TextureProcessorOutputFormat.EtcCompressed)] `

That is a pretty good idea for texture compression.

Still we need to see about how some of these can be included in separate assemblies and discovered by the pipeline/mgcb tool.

Also need to develop some technique for other platform specific things like videos, songs, sound effects, etc.

**Comment by KonajuGames** [comment]
> Still we need to see about how some of these can be included in separate assemblies and discovered by the pipeline/mgcb tool.

Could they simply be added as references in the .mgcb file like we do now for custom pipeline assemblies?  If you want PS4 content processing support, you add a reference to `MonoGame.Framework.Content.Pipeline.PS4.dll`.  Then we should be able to find the relevant types during processing.

**Comment by tomspilman** [comment]
>Could they simply be added as references in the .mgcb file like we do now for custom pipeline assemblies?

You know it totally could be done that way.  In fact it might force us to make that bit of the Pipeline tool suck less. :)

**Comment by tomspilman** [comment]
So an update on this in 2018.

We've added these "Profile" classed in the Pipeline to help abstract out platform specific content conversions for consoles:

 - [TextureProfile](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Graphics/TextureProfile.cs)
 - [AudioProfile](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Audio/AudioProfile.cs)
 - [ShaderProfile](https://github.com/MonoGame/MonoGame/blob/develop/Tools/2MGFX/ShaderProfile.cs)

These were designed so that we could scan for types derived from these classes in pipeline extension assemblies.

Ideally this system would let a user extend an existing install of the MonoGame Pipeline tool to support console platforms without maintaining multiple copies of the pipeline on their system.

**Comment by Jjagg** [comment]
@tomspilman This can be closed, right?

**Comment by tomspilman** [comment]
Yep!
