### ISSUE TITLE
Android IsFixedTimeStep=true Locks Up On Android 2.x

### ISSUE THREAD

**Issue by JRC-BitBull** [MonoGame/MonoGame#2820]
I am using game.IsFixedTimeStep = true to set a fixed frame rate for my game and have to date encountered no issues with this.

Today I tested on the GenyMotion emulator running 2.3.7 with the latest MG develop build and am getting really strange behaviour. Basically it seems if I set the frame rate to 30fps the game completely locks up, if I set the frame rate to 1000fps or 500fps it runs fine (though unplayably fast obviously).

Android 4.x is not exhibiting this behaviour, the fixed time step operates as expected.

cheers

**Comment by Jjagg** [comment]
[Here](https://bugzilla.xamarin.com/show_bug.cgi?id=20578)'s the related Xamarin bug. It was closed and couldn't be reproduced, so I'm closing this as well.
