### ISSUE TITLE
Monochrome Optimized DXT3 Compression For SpriteFont

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#2853]
The XNA content pipeline produces DXT3 compressed textures for SpriteFont.  Comparing the results from XNA to the Nvidia Texture Compressor we can see significant artifacts using normal DXT3 compression.

In fact I've seen papers talking about monochrome optimizations for DXT.... it could be possible XNA is doing this under the hood.

We need to develop our own monochrome optimized DXT3 compression specifically for SpriteFont.

**Comment by tomspilman** [comment]
So I was right in my suspicions...  the C++ DirectX ToolKit has an example of that sort of specialized compressor for monochrome fonts:

https://github.com/Microsoft/DirectXTK/blob/master/MakeSpriteFont/SpriteFontWriter.cs#L206

The code is MIT licensed... we can port and drop it right into the font processor code with a little note as to the licenses and where it came from.

**Comment by KonajuGames** [comment]
I was playing with this a little in my texture processor fixes.  I'll definitely have a closer look at that link.

**Comment by tomspilman** [comment]
@KonajuGames - So this path only works for platforms were DXT3 is an option.  I suggest on other platforms we skip compression unless we're sure the compressed texture is of acceptable quality.

**Comment by tomspilman** [comment]
FYI.  I got confirmation from a member of the XNA team that the compression code in the C++ DirectX ToolKit for sprite fonts is identical to what XNA did.

**Comment by KonajuGames** [comment]
I noticed while looking through NVTT (comparing it to libsquish) that NVTT appears to support this specialised mode if I'm correct.

If I get libsquish working properly (fixing the couple of artifacts I'd seen), adding this specialised mode shouldn't be difficult. But then we would also have to find a way to support this with the other block compression formats.

**Comment by tomspilman** [comment]
> that NVTT appears to support this specialised mode if I'm correct.

Interesting.


> If I get libsquish working properly 

I think we should start by just adding this into the sprite font processing directly.  We can look to making it a generalized compression feature if it proves useful at a later time.
