### ISSUE TITLE
Font Pipeline Issues

### ISSUE THREAD

**Issue by RayBatts** [MonoGame/MonoGame#2877]
- It looks like the property grid is replacing a single empty character with the default/null-terminating character.
  To reproduce, try to process a SpriteFontTexture, and set its FirstCharacter to ' ' (a single space) via the property grid. Set a breakpoint in the processor and you'll notice that ' ' is replaced with '\0' in the Character/Glyph map.
- FontDescription is missing the Characters field: http://msdn.microsoft.com/en-us/library/microsoft.xna.framework.content.pipeline.graphics.fontdescription.characters.aspx This prevents classes that derive from FontDescritpion from working in MonoGame's pipeline.

**Comment by Jjagg** [comment]
Seems related to #3400.
