### ISSUE TITLE
Touches off on retina iPhone and iPad.

### ISSUE THREAD

**Issue by Clancey** [MonoGame/MonoGame#2973]
Since the fix for iOS 8 rendering, Touch scale is off for iOS with retina displays.  On an iPhone retina its 2x off, and when you go to an iPad retina its 4x off. Not sure what changed with the display rending to fix it for iOS 8, but it has cascaded.

 If you uncomment this line it works.
https://github.com/mono/MonoGame/blob/8d89ad087f296d9e484cd5e3c570d324da08b129/MonoGame.Framework/Input/Touch/TouchPanelState.cs#L231

**Comment by harry-cpp** [comment]
Closing as it could not be reproduced.
