### ISSUE TITLE
Pipeline tool fails if previously open MGCB file is missing

### ISSUE THREAD

**Issue by theZMan** [MonoGame/MonoGame#2994]
When your run pipeline tool 0 it attempts to open the MGCB file that was previously open. If the file is missing the program crashes. I suspect it will also crash if you pass in a bad file name on the command line.

In Pipeline.Windows/commandlineparser.cs
                if (arg.StartsWith("/@"))
                {
                    var file = arg.Substring(3);
                    var commands = File.ReadAllLines(file); <-- crash here FileNotFoundException

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
