### ISSUE TITLE
MGCB must be run from the content directory, or with working directory set

### ISSUE THREAD

**Issue by theZMan** [MonoGame/MonoGame#3016]
Even if you provide a full path to the mgcb file with the /@: parameter you still have to run from the content directory. The pipeline project sets a working directory but you can't do this from VS build events/

The error you get when you are not in the right folder is a random nullref crash - this should be handled better.

It would be preferable when using a .mgcb file for the content folder to be a paramter or be contained in the MCGB file. The pipeline tool seems to make the assumption that the mgcb is in the same folder as the content - this assumption would be fine with me for mgcb too.

**Comment by Jjagg** [comment]
Closing for #4190.
