### ISSUE TITLE
SoundEffect Errors on Application Close - Win 8.1 XAML Project

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#3033]
I posted this on the CodePlex site but realized that this is a better place to put it. Here's the original topic (as well as a sample project that replicates the issue): https://monogame.codeplex.com/workitem/7897

Basically, I'm developing a Windows 8.1 game using XAML and MonoGame 3.2. I have a menu option that the player can click that exits the game using Application.Current.Exit(). If a SoundEffect is loaded through XNA's ContentManager, it causes an error similar to the following:

'MyGame.exe' (CLR v4.0.30319: Immersive Application Domain): Loaded 'C:\Users\me\Documents\Other Projects\Games\MyGame\MyGame\MyGame\bin\Windows8\Debug\AppX\SharpDX.XAudio2.DLL'. Cannot find or open the PDB file.
'MyGame.exe' (CLR v4.0.30319: Immersive Application Domain): Loaded 'C:\Users\me\Documents\Other Projects\Games\MyGame\MyGame\MyGame\bin\Windows8\Debug\AppX\SharpDX.MediaFoundation.DLL'. Cannot find or open the PDB file.

I have narrowed it down to SoundEffects, as when I don't load any the game closes just fine. I suspect there is some memory leak of some sort as this topic mentions: http://community.monogame.net/t/soundeffect-loaded-via-contentmanager-causing-memory-leak-after-resume/1174/2

I hope that this issue is resolved soon. Thank you very much!

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
