### ISSUE TITLE
Windows Phone 8: SoundEffects loaded via ContentManager causing memory leak after resume from suspense

### ISSUE THREAD

**Issue by BDash2014** [MonoGame/MonoGame#3048]
My game is wp8 with latest nuget monogame/sharpdx.
First I though I have some bug in my implementation of libgdx (as game is port from libgdx to monogame), but I end up with ultra simple example:
new empty monogame project where I just load about 30 SoundEffects via ContentManager in LoadContent method and that is. Then after suspend/resume, memory increases by several MB and again and again every suspend/resume until out of memory exception...
Sound effects are waves converted to xnb format. I have no problem with other resources but with SoundEffect only.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
