### ISSUE TITLE
Vector classes are not serializable

### ISSUE THREAD

**Issue by filoe** [MonoGame/MonoGame#3072]
Please mark the Vector2|3|4, Point and the Rectangle class as serializable like XNA did it.

**Comment by kobinis** [comment]
You can use ISerializationSurrogate as a quick solution, for example:

sealed class Vector2SerializationSurrogate : ISerializationSurrogate
    {
        public void GetObjectData(Object obj, SerializationInfo info, StreamingContext context)
        {
            var vec = (Vector2)obj;
            info.AddValue("x", vec.X);
            info.AddValue("y", vec.Y);
        }

        public Object SetObjectData(Object obj, SerializationInfo info, StreamingContext context, ISurrogateSelector selector)
        {
            var vec = (Vector2)obj;
            vec.X = info.GetSingle("x");
            vec.Y = info.GetSingle("y");
            return vec;
        }
    }
