### ISSUE TITLE
MonoGame iOS how to use .acc or .m4a

### ISSUE THREAD

**Issue by RamsayGit** [MonoGame/MonoGame#3104]
I am currently developing an iOS MonoGame app. I dont want to use .mp3 file format for my songs due to the licensing issues. I have read many MonoGame developers say that one can use .acc or .m4a. I personally had zero success loading any of these formats with build action set to Content. I placed them in the Content folder but I keep getting the following exception:

```
System.Exception: Could not initialize an instance of the type 'MonoTouch.AVFoundation.AVAudioPlayer': the native 'initWithContentsOfURL:error:' method returned nil.

It is possible to ignore this condition by setting
```

And the MonoGame content project cant import them for processing, so am not sure what to do here. Any tips would be greatly appreciated.

**Comment by harry-cpp** [comment]
Content loading of non processed file has been disabled from the ContentManager, however the file can still be loaded by using their respective `FromStream` method.
