### ISSUE TITLE
Pipeline Tool feature request: 'open output file location'

### ISSUE THREAD

**Issue by jamesford42** [MonoGame/MonoGame#3123]
Example usage:
Right click on content item
Rebuild
Right click on content item
Open Output-File Location

Note:
There is no need to have an 'Open Output-File' option since the output file is an xnb, and while an xnb visualizer would be cool, there isn't one.

Note:
When right click is on the project itself, this option takes you to the root of the output directory.

**Comment by cra0zy** [comment]
@tomspilman This can be closed now... really need to remember to add `fixed #issue` to my commit messages...
