### ISSUE TITLE
Improving ManagedPVRTC

### ISSUE THREAD

**Issue by prollin** [MonoGame/MonoGame#3170]
I just submited a [PR to the ManagedPVRTC source repository](https://github.com/SickheadGames/ManagedPVRTC/pull/2) and want to make sure it gets enough attention.

ManagedPVRTC is a simple wrapper around the PVRTexLib from Imagination that allows the MonoGame Content Pipeline to compress textures to PVRTC (for iOS). 
PVRTexLib actually supports many formats (including DXT and ETC1) and could be used for scaling textures and/or transcoding from any supported formats (even the non compressed ones).

The submitted PR is a first step in that direction. It most likely need to be improved, built on Linux and MacOSX and added to the MonoGame Dependencies repo.

**Comment by tomspilman** [comment]
Closing this for https://github.com/MonoGame/MonoGame/issues/6276.
