### ISSUE TITLE
TouchCollection Not Clearing

### ISSUE THREAD

**Issue by adeeb1** [MonoGame/MonoGame#3172]
When I tap on the screen with a few fingers and simultaneously click with a mouse, a TouchLocation with the Moved status gets stuck in the TouchCollection and is never cleared out. All subsequent touches are still registered, but index 0 of the TouchCollection continues to return that same TouchLocation with the Moved status, and the time it was registered remains the same.

This was originally reported at the following URL: http://community.monogame.net/t/touchcollection-not-clearing/1425

A test project can be downloaded from the following URL: http://www.mediafire.com/download/lljjv28fi1fo77a/TouchCollection_TestProject.zip

Simply open up the project and run it. Whenever you tap, you will hear a sound. If you swipe, you will hear a different sound.

Reproduction Steps:

Tap and swipe on the screen like a madman with one hand while clicking on the screen using a mouse on the other hand. After a while, you should stop hearing the touch sounds. This means that you have successfully reproduced the issue. Some debug information is displayed in the Output window of Visual Studio.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
