### ISSUE TITLE
Texture2D.FromStream on Android locks the app if called from background thread

### ISSUE THREAD

**Issue by vchelaru** [MonoGame/MonoGame#3174]
The issue was brought up here:

http://community.monogame.net/t/texture2d-fromstream-issue/334/5

This works fine on XNA PC, and I believe on MonoGame W8 (RT), and may be implemented on iOS, but I'm not sure.

**Comment by harry-cpp** [comment]
The issue in the main comment is a reverse of this issue.

I haven't had any issues with loading textures on separate threads in recent time so gonna close this.
