### ISSUE TITLE
SoundEffects Distort or Don't Play After a While

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#3180]
After a certain number of SoundEffects are played, all subsequent SoundEffects are distorted or don't play at all. Here's a link to the original topic: http://community.monogame.net/t/soundeffects-distort-or-dont-play-after-a-while/1459

I'm making a Defense game for the Windows Store in which you kill lots of enemies, and each time an enemy dies it plays a sound. It's not a problem at first, but once the player gets to around Level 38 in a single playthrough the sounds will distort or sometimes stop altogether. I'm playing sounds using SoundEffect.Play() and music with SoundEffectInstance. SoundEffect.Play() is always returning true, so there aren't too many instances being played at once.

An easy way to replicate this issue is to play the same sound 10 times in Update() for around 8-10 seconds. Then, any subsequent sounds will distort or simply not play.

There was a reported memory leak issue for SoundEffects here: http://community.monogame.net/t/soundeffect-loaded-via-contentmanager-causing-memory-leak-after-resume/1174

Unfortunately it seems that the fix is not in place for the current build, and I suspect that either memory leak or failure to properly clean up SoundEffects after they finish playing is the cause of my problem. When the problem occurs and I check Task Manager, the game takes up roughly 30% of my CPU as opposed to 1-2% when the game starts.

EDIT: Based on the comments below, it seems this is an actual issue with MonoGame as this problem doesn't seem to occur with XNA.

**Comment by MGZero** [comment]
After switching from a content project to the content pipeline tool, I am no longer seeing this issue.

**Comment by tdeeb** [comment]
@MGZero Did you just build the XNBs using the MonoGame Pipeline Tool?

**Comment by MGZero** [comment]
Yes

**Comment by tdeeb** [comment]
This is a bit late, but I built my XNBs using MonoGame's Pipeline Tool and I still encounter the issue.

**Comment by templarvii** [comment]
I had the same Problem. But now the bug seams to be fixed.

MonoGame 3.0 --> the sound is well played
MonoGame 3.2 --> the sound is played very crackling after it has been played hundreds of times
MonoGame 3.3 --> i think it's better, but not as good as in version 3.0
MonoGame 3.4 --> i think the sound is well played again (still testing)

Many thanks for your great work!
