### ISSUE TITLE
Implement SkinnedModel importers that work in MGCB

### ISSUE THREAD

**Issue by theZMan** [MonoGame/MonoGame#3187]
This is a placeholder for getting skinned models to work using the Mono content builder

https://github.com/mono/MonoGame/pull/2253 was an initial attempt.
https://github.com/mono/MonoGame/pull/3058 added some fixes for missing bones

For now it appears that processing your models using the XNA CP is the only workaround.

**Comment by Jjagg** [comment]
Closing in favor of #3825.
