### ISSUE TITLE
Installing dev builds in confusing for first timers

### ISSUE THREAD

**Issue by theZMan** [MonoGame/MonoGame#3190]
We recommend people get dev builds since 3.2 is so far behind but its not obvious what to do - high barrier to entry is not good. 

If you start here:
http://www.monogame.net/downloads/

And click through the links the windows option opens a tree with an EXE and an mpack file - which do I choose?

The Mac one opens a closed up tree structure - several of them are full of what appears to be just files. Again not sure what to do here.

Need to provide a direct link or instructions

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
