### ISSUE TITLE
Proposal: Protobuild packages and templates for MonoGame

### ISSUE THREAD

**Issue by hach-que** [MonoGame/MonoGame#3194]
I've been working on package management functionality in Protobuild for the last month or so, and after some previous discussion, I've been developing it further to better suit MonoGame.

Protobuild's package management is designed to support both cross-platform libraries and cross-platform project templates.  For libraries, the binary packages it supports are LZMA compressed, deduplicated and can be swapped in-place for source code (and vice-versa).  For project templates, it provides an easier mechanism to start a Protobuild-based project using cross-platform libraries.

As a demonstration, [download the latest version of Protobuild](https://github.com/hach-que/Protobuild/raw/master/Protobuild.exe) into an empty directory, open a command prompt, and run:

```
Protobuild.exe --start http://protobuild.org/MonoGame/Template.2DPlatformer@develop MyNewPlatformer
```

This works on all desktop platforms (although Mac OS is untested).  For this demonstration you'll need Git in your path because there's no binary package present yet for the project template itself, and if you're running this on Mac OS or Linux, prefix the command with `mono`.  When the command completes, you should be able to open the solution in Visual Studio or Xamarin Studio and run the game.

Protobuild's package management has several advantages over using NuGet:

**Full support for cross-platform projects, in particular those that need to make native calls (such as P/Invoke)**

Protobuild designates library packages by platform; the same platforms that are used for generation, and not framework API.

**Automatic fallback to source code repositories if binary versions are not available for the platform**

Users can swap out binary packages for source versions and vice-versa transparently.  This makes it easier to diagnose issues and bugs.  To try that with the demonstration above, run:

```
Protobuild.exe --swap-to-source http://protobuild.org/MonoGame/MonoGame
Protobuild.exe --generate
```

or try the reverse:

```
Protobuild.exe --swap-to-binary http://protobuild.org/MonoGame/MonoGame
Protobuild.exe --generate
```

**Packages are LZMA compressed and deduplicated to significantly reduce their size**

For reference, the binary packages I've built are:
- Windows + Content Pipeline: 24.4Mb
- Linux + Content Pipeline: 15.7Mb
- WindowsGL: 1.5Mb

The content pipeline includes all external tools and relevant binaries (e.g. ffmpeg + ffprobe for those platforms).

**Support for module templates as packages**

As demonstrated above, this makes it very easy for people to start with MonoGame on any platform (not just Windows).  This requires no installation of MonoGame for developers to start using the engine.

(This doesn't fix some of the issues with running the Content Pipeline on other platforms, but these exist independent on the method of using MonoGame)

**Automatic package configuration**

Partly the reason that #3179 was submitted; Protobuild can automatically package the MonoGame project for any platform after it's built, with no additional configuration required.  The following commands will produce a binary package suitable for uploading:

```
Protobuild.exe --generate Windows
msbuild
Protobuild.exe --pack . package_Windows.tar.lzma Windows
```

To upload it is:

```
Protobuild.exe --push <api_key> package_Windows.tar.lzma http://protobuild.org/MonoGame/MonoGame <git_hash> Windows <optional_branch_to_update>
```
## 

More documentation on the package management feature can be found at [documentation](https://protobuild.readthedocs.org/en/latest/package_management_protobuild.html).  I have pretty much all of this work in a PR (which is not yet submitted, pending discussion on this issue), except for the package push commands which will require some build server configuration.

**Comment by DDReaper** [comment]
Interesting.  Thanks @hach-que will have to check this out

**Comment by DDReaper** [comment]
Kicked off a discussion on the protobuild site on the manager itself https://github.com/hach-que/Protobuild/issues/83

Overall though this would be great for new templates and even the MonoGame samples
Thoughts @tomspilman @dellis1972 @KonajuGames ?

**Comment by hach-que** [comment]
Just an update: The latest version of Protobuild will now cache source packages as well.

This means that when you use MonoGame as a package, even if you are using it in source form (where binaries aren't available), it's only downloaded once.  When you create a second or third project using packages, no downloads are necessary (and you can create new projects based on a previously used template entirely offline).  This caches Git submodules as well (so the "Dependencies", etc. submodules are cached as well).

Protobuild will still attempt to perform "git fetch" before checkout (to make sure it has all the latest commits available), but if it fails or there's no internet connection then it's ignored and continues using what it has available in the cache.

**Comment by hach-que** [comment]
Is there any chance of moving this forward?  I'm currently still publishing packages at http://protobuild.org/monogame/MonoGame but this is tracking my fork of MonoGame so it's not always up-to-date (and has patches applied).

**Comment by jackwilsdon** [comment]
:+1: on this, looking for a nice way to create a cross-platform game.
