### ISSUE TITLE
Implement content pipeline tool as a server

### ISSUE THREAD

**Issue by hach-que** [MonoGame/MonoGame#3198]
The idea here is that the primary content pipeline compilation is done by a Pipeline server tool; this can be run on a desktop machine for individual developers or on a central machine for teams of developers.

Various forms of content compilation (MGCB, Pipeline?) could be centralized to use a running server to perform the actual content compilation, or automatically start the server on the local machine if none can be found on the local network.

In addition, the MonoGame framework could fallback to using the server if the game doesn't have a compiled version of the content present.  This would make developing significantly easier as content wouldn't require recompilation before builds each time.

The Pipeline server could also cache content based on the settings and SHA1 of the incoming content. This would mean that teams of developers wouldn't have to rebuild the content on each of their machines; instead the various pipeline tools and framework could retrieve the results from the server.

Presumably we'd also need a command line tool that pulls built content from the server and writes it out suitable for releasing games.

**Comment by Jjagg** [comment]
Gonna close this because we don't want to maintain something complex like this. Users can wrap MGCB for both use cases mentioned.
