### ISSUE TITLE
Request for Basic requisite content on install

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#3221]
id like to offer a alternate suggestion to #3204 ... (this is basically a modification of that suggestion)
that provides a solution to that
yet at the same time a distinctly separate feature request
that is also highly indie-friendly and makes sense
...
including a default sprite-font class with a default loading method
that will auto load a default installer-included spritefont when called
then return a font reference to that
...
i requested / brought up this point for xna 5 but since that never happened i had forgotten about it

in essence : the reasoning to this is that...
this would allow a template to have only a couple lines to achieve what is desired
my personal desire for this is
i often use xna monogame for a quick console like test app

for example:
then the template would only add something like this in the load method
mySpriteFont = DefaultSpriteFont.Load();
in draw you would then just have
spritebatch.DrawString(myspritefont,"hello world", ect...);

since xna already has a couple lines to delete like
"// load your content here"
you would end up with a comment for each line shown such as
"// load your content here"
"// example load your spritefont"
mySpriteFont = DefaultSpriteFont.Load();
and a similar comment in the draw method

the real benefit :
having this right off the bat would essentially make mono-game on install
"one step away from a graphical replacement to the traditional outdated console application"
of course erasing two lines from game1 and your using mono-game as normal is nothing

in reality :
im suggesting with the installer that a folder is created and adds the most basic starting content
a small image of monogame and a open source sprite font
then the consideration of something like hello world
is simply a choice of adding a line or two to the template or not

**Comment by cra0zy** [comment]
With the new `dotnet templating` engine, we should be able to start providing samples with nuget package.
