### ISSUE TITLE
MonoGameContentBuilderExe should be defined in the project not in the targets file

### ISSUE THREAD

**Issue by jamesford42** [MonoGame/MonoGame#3238]
Concerning this line in MonoGame.Content.Builder.targets

``` xml
<MonoGameContentBuilderExe>$(MSBuildExtensionsPath)\MonoGame\v3.0\Tools\MGCB.exe</MonoGameContentBuilderExe>
```

This variable should really be defined by the csproj not the targets file: allowing different projects to be build by different versions of monogame, if an advanced user wishes to hand edit their csproj.

**Comment by cra0zy** [comment]
MGCB nuget will solve this.
