### ISSUE TITLE
Fix Icon Backgrounds On Windows 8

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#3249]
On Windows 8 the icons for MonoGame URL links end up with a pretty poor background color choice...

![tiles](https://cloud.githubusercontent.com/assets/103522/5363047/20b87da0-7f9e-11e4-87c2-69553221e85e.png)

I came across this article...

 http://msdn.microsoft.com/en-us/library/windows/apps/dn393983.aspx

... but I haven't figured out how to make this apply to .url files.

**Comment by cra0zy** [comment]
Pff, Windows 8
