### ISSUE TITLE
Thoughts on a MG Content Builder NuGet

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#3252]
With the upcoming release of the updated NuGet's, I'm guessing people will want an easier access to the new MGCB tool.

before I commit to putting it together, what are everyone's thoughts about shipping the MGCB tool as a NuGet?

That way it can be updated outside of the main MSI installer.

**Comment by ForNeVeR** [comment]
Hey, guys! Maybe it's time to rethink this?

I think it would be a great advantage to be able to install MGCB through NuGet. Then it'd be accessible to all the great **not MSBuild** tools such as FAKE etc.

I'd like to install only Mono on my build server and get everything else from NuGet, but currently I have to install the whole MonoGame package, and that's inconvenient.

**Comment by tomspilman** [comment]
I have no problem supporting this, but I don't know how to do it properly. 

@DDReaper ?

**Comment by DDReaper** [comment]
I did propose this a while back and had a few ideas on how to make it practical.  Let me do some testing and hopefully get back soon.
Should be similar to what was done to package the MGCB tool separately for Mac

**Comment by cra0zy** [comment]
- Step 1: #5548
 - Step 2: #5528
 - Step 3: Package MGCB inside NuGet
 - Step 4: Profit?

**Comment by DDReaper** [comment]
Those changes certainly look interesting.  As it's a single UI, it'll be mostly about packaging the right dll's with each platform in a single NuGet

**Comment by cra0zy** [comment]
Well I decided to upload an unofficial package: https://www.nuget.org/packages/MonoGame.Content.Builder/

In case someone wants to try it with their project, remember to remove the .targets line for the system content builder from your project, otherwise there will either be conflicts or you will build your content 2 times. Either case it's bad.

Also the NuGet package size is 100 MB, quite large...

**Comment by DDReaper** [comment]
Will give it a go @cra0zy (even though you ignored my gitter conversation, lol)

Do you have a repo link for where the source to the NuGet is to see if we can "trim" it down a little 🗡

**Comment by cra0zy** [comment]
> Will give it a go @cra0zy (even though you ignored my gitter conversation, lol)

I am sorry, I was offline :(

> Do you have a repo link for where the source to the NuGet is to see if we can "trim" it down a little

Just build results from #5528 and a custom nuspec file.

**Comment by DDReaper** [comment]
Shhh, I edited my comment @cra0zy no hard feelings 🗡 
I guess were all allowed to be "offline" every now and again :D

**Comment by cra0zy** [comment]
I'm maintaining my own copy of MGCB nuget at: https://github.com/cra0zy/MonoGame/tree/corebuilder

The nuget is split into 4 packages, this not only makes the download smaller, but also makes it so there are no modifications needed on the content pipeline/mgcb. You only need to reference the main one:
- https://www.nuget.org/packages/MonoGame.Content.Builder/

Per platform ones (do not reference them):
- https://www.nuget.org/packages/MonoGame.Content.Builder.Windows/
- https://www.nuget.org/packages/MonoGame.Content.Builder.Linux/
- https://www.nuget.org/packages/MonoGame.Content.Builder.Mac/

**Comment by harry-cpp** [comment]
MG Content Builder is in the develop branch so closing.
