### ISSUE TITLE
VS .mgcb handling needs extra features

### ISSUE THREAD

**Issue by theZMan** [MonoGame/MonoGame#3259]
1. If you delete the default Content folder from the template you get errors.
2. If you add additional .mgcb files to the project (even in the Content folder) they do not build

We would like an mgcb file to be built no matter where it is in the project but it would be acceptable to require a Content folder if that's a problem.

In addition out content folders are outside the main project directory as they are shared between multiple projects. We add the .mgcb files using 'link'

**Comment by Ragath** [comment]
First issue has been fixed for some time, not having an item with MonoGameContentReference as the build action results in a warning.
Issue 2 stems from not having set the Build Action to MonoGameContentReference. Would be nice if that could be set as the default action of *.mgcb items.

**Comment by cra0zy** [comment]
The 2nd part of this request has been implemented in: #4997 and fixed up in subsequent PRs. Closing...
