### ISSUE TITLE
[Content Pipeline] EffectProcessor not implemented on Mac

### ISSUE THREAD

**Issue by Nezz** [MonoGame/MonoGame#3270]
Any plans to implement it on platforms other than Windows?

**Comment by tomspilman** [comment]
See #2167 for info on this.

**Comment by tomspilman** [comment]
@tgjones - Let's move the rest of the GLSL discussion here...  #2167 has become a mess.

**Comment by tgjones** [comment]
So as a final check before I write some code, the proposal is that you would be able to write GLSL-based MGFX files in this format:

``` c
#include "Macros.glsl"

uniform sampler2D tex1
{
    AddressU = Wrap;
    AddressV = Wrap;
};

uniform mat4 mvp_unif;
attribute vec3 pos_attr;
attribute vec2 uv_attr;
varying vec2 uv;

void vertMain()
{
    gl_Position = mvp_unif * vec4(pos_attr, 1.0);
    uv = uv_attr;
}

void fragMain()
{
    gl_FragColor = texture2D(tex1, uv);
}

technique
{
    pass
    {
        VertexShader = compile glsl_140 vertMain();
        PixelShader = compile glsl_140 fragMain();
    }
}
```

We will detect GLSL by pre-scanning the file for a `compile` directive, and looking at the shader profile.

We will strip out the MGFX-specific stuff - sampler state properties, other states such as rasterizer states, and the `technique` block - from the final GLSL.

**Comment by KonajuGames** [comment]
That looks like a good start to me.

**Comment by tomspilman** [comment]
> the proposal is that you would be able to write GLSL-based MGFX files in this format:

That looks about right to me.  Seems like the first thing one would think of if you said an GLSL FX file... which is a good thing.

Ideally this would only require some slight modifications to the existing MGFX parser and not something entirely new.

> If we need to, we will detect GLSL by pre-scanning the file for a  compile  directive

Yea... I think that is probably the easiest way to do it as all FX files require one.

However... another thought here... we already have to pass the "shader profile" into the system:

https://github.com/mono/MonoGame/blob/develop/Tools/2MGFX/Options.cs#L12

That was me sort of mimicking the "profile" from the FXC.exe command line...

 https://msdn.microsoft.com/en-us/library/windows/desktop/bb509709(v=vs.85).aspx#Profiles

... so to me things seem a little murky now.  What is the relationship between my "shader profile" and the type of FX file we have?  Do we need some change in terminology?  What if for instance someone tries to compile a GLSL FX on PS4?

> We will strip out the MGFX-specific stuff 

I suspect that maybe some of the work the MGFX parser does could help you here.  It already has a sort of map of file positions and lengths of all the tokens it scans for.  I suspect that maybe that can be used to strip the file.

**Comment by tanis2000** [comment]
@tomspilman has there been any progress on this? Any update on a MGFX tool for macOS?

**Comment by Jjagg** [comment]
@tannis2000 Check out #5354

**Comment by tanis2000** [comment]
@Jjagg that's good to see. Any idea when it will be part of an upcoming MG release?

**Comment by Jjagg** [comment]
It's very much a WIP and I'm working on other stuff, so there's not really a set timeline. If we get that pr merged and document how GLFX works a bit, it will be easier to get people to contribute and get it ready for production games.

**Comment by CartBlanche** [comment]
Just wondering if there are any further updates on this?

**Comment by Jjagg** [comment]
Closing. It doesn't help to have 2 open issues for the same thing. See #2167.
