### ISSUE TITLE
Running inside Windows Forms

### ISSUE THREAD

**Issue by Shawak** [MonoGame/MonoGame#3280]
Is there actually any way to run the develop branch inside a windows form?

I found a way to run the latest 3.2 stable version inside a form, but this method doesn't work wiht the develop version throwing me a nullreference exception (using the method linked on the website).

**Comment by tomspilman** [comment]
We have done it ourselves before, so we know it is possible...  it should work just like it does to embed XNA on WinForms.

Can you give us specific info on the exception thrown?  Like what is the class stack?

**Comment by cra0zy** [comment]
@tomspilman This can be closed, plus this is more of a forum question than a bug report/feature request.
