### ISSUE TITLE
Update the MG Installer description on the develop branch to state it's a DEV install

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#3300]
Currently the installer builder still states that it is the MonoGame 3.2 installer

This is terribly confusion for anyone downloading the development release from the develop branch auto creation scripts.

As the MG 3.2 installer is already fixed, can this be updated to either:
- MonoGame Dev release (plus date)
- MonoGame 3.3 Development release
- Something other than MonoGame 3.2

This will help a lot in tutorials and ensure when you are using the dev release you know what on earth you are installing.

Same with the assembly version if this can be configured to automatically increment, with the minor release number updated AFTER each official release, e.g dev should be at lease 3.3.x now.

**Comment by tomspilman** [comment]
Ok... added https://github.com/mono/MonoGame/pull/3408 which fixes up the installer version numbers and stuff.

The next step really is releasing 3.3 next week.

**Comment by Apostolique** [comment]
This can be close.
