### ISSUE TITLE
MediaPlayer.Volume Error

### ISSUE THREAD

**Issue by tattries** [MonoGame/MonoGame#3380]
In windows 8  MediaPlayer.Volumne =0.2 get error

System.TypeInitializationException was unhandled by user code
  HResult=-2146233036
  Message=The type initializer for 'Microsoft.Xna.Framework.Media.MediaPlayer' threw an exception.
  TypeName=Microsoft.Xna.Framework.Media.MediaPlayer
  InnerException: System.NullReferenceException
       HResult=-2147467261
       Message=Object reference not set to an instance of an object.
       Source=MonoGame.Framework
       StackTrace:
            at Microsoft.Xna.Framework.Media.MediaPlayer.PlatformInitialize()
            at Microsoft.Xna.Framework.Media.MediaPlayer..cctor()
       InnerException:

**Comment by tattries** [comment]
Setting anything on MediaPlayer will cause same crash.

**Comment by Nezz** [comment]
The static type constructor fails. Is it Windows desktop or store? If desktop, OpenGL or DirectX?

**Comment by tattries** [comment]
Windows Store and directx






Sent from Windows Mail





From: Adam Kapos
Sent: ‎Monday‎, ‎January‎ ‎12‎, ‎2015 ‎6‎:‎08‎ ‎PM
To: mono/MonoGame
Cc: tattries





The static type constructor fails. Is it Windows desktop or store? If desktop, OpenGL or DirectX?

**Comment by Nezz** [comment]
Then this is the code that fails:
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Media/MediaPlayer.WME.cs#L21-31

It works fine for me, so you will have to debug in your environment.

**Comment by Jjagg** [comment]
Looking at the code I think this can only happen if the window isn't created yet.

Suspected failing [line](https://github.com/MonoGame/MonoGame/blob/ba5c722a399fa4e192859a7dd17377b20ae4d327/MonoGame.Framework/Media/MediaPlayer.WME.cs#L36):
`_dispatcher = CoreApplication.MainView.CoreWindow.Dispatcher;`
