### ISSUE TITLE
ContentPipeline Crashes if it cannot find the default PipelineProcessor for an Importer on Windows

### ISSUE THREAD

**Issue by Eversor** [MonoGame/MonoGame#3398]
ContentPipeline crashes if it cannot find the default PipelineProcessor for an Importer, this is a reproducible issue, in any custom content project simply change a letter of the PipelineProcessor in the ContentImporter attribute to trigger a crash whenever you choose the Importer from the dropdown of an item.

**Comment by cra0zy** [comment]
Pipeline for what, Windows or Mac/Linux?

**Comment by Eversor** [comment]
Windows, sorry for not specifying.

**Comment by njlr** [comment]
I have also had this issue on OSX.

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
