### ISSUE TITLE
Content Pipeline always rebuilds TextureFonts if firstcharacter is set to " "

### ISSUE THREAD

**Issue by Eversor** [MonoGame/MonoGame#3400]
This seems to be due to an issue with Xml Deserialization of the string, as a matter of fact it fails the check in 
AreParametersEqual(cachedEvent.Parameters, Parameters)
because 
cachedEvent.Parameters["FirstCharacter"] = ""
and
Parameters["FirstCharacter"] = " "

**Comment by Eversor** [comment]
this is pretty bad if you use Chineese or Kanji symbols that result in over 20-30 minute compilation times..

**Comment by Eversor** [comment]
This could solve the problem if placed at line 246 of file PipelineBuildEvent.cs

    // There is a bug in xmlserialization where a space character will be read as empty string
    if (value0 is string && value1 is string && string.IsNullOrWhiteSpace((string)value0) == string.IsNullOrWhiteSpace((string)value1))
    continue;

**Comment by Jjagg** [comment]
This is a pipeline caching issue. It thinks parameters are changed when they are not. The check happens [here](https://github.com/MonoGame/MonoGame/blob/ba5c722a399fa4e192859a7dd17377b20ae4d327/MonoGame.Framework.Content.Pipeline/Builder/PipelineBuildEvent.cs#L213).

**Comment by Eversor** [comment]
This still happens in MG 3.8 on Windows. Just tested from the Nuget.
