### ISSUE TITLE
Monogame for Raspberry Pi

### ISSUE THREAD

**Issue by harry-cpp** [MonoGame/MonoGame#3416]
Are there any plans to support this? Would this be useful?

**Comment by tomspilman** [comment]
We had it working already....

  http://youtu.be/zNEVHW6Hwro
  http://youtu.be/jwbYe6eoZgE

@dellis1972 - Do you still have a branch for that?  Could maybe @cra0zy take that work over?

**Comment by dellis1972** [comment]
I think I do...it required some opentk hacks. I'll take a look

-----Original Message-----

**Comment by hach-que** [comment]
Let me know if there are any Protobuild changes required to support this.  I'm pretty sure it'll just be a normal desktop platform though (and so `Protobuild.exe --generate RaspberryPi` + adding the platform to the appropriate `<Platforms>` tags should be enough).

**Comment by DDReaper** [comment]
@dellis1972 did you not try the Platformer Sample on the Pi?

**Comment by dellis1972** [comment]
OK I still have the branch, but its way way out of date. It did required some OpenTK hacks.
Although the original blog post was lost during a hack the archive is at http://web.archive.org/web/20121203091113/http://infinitespace-studios.co.uk/2012/11/14/monogame-on-the-raspberry-pi/

It probably wouldn't take much to get running again since android moved to OpenTK-1.0 it should be fairly compatible. 

The only down side is it required some gles hacks in the native .so to get hardware rendering in X working. not sure if they solved that on the pi (it was 2 years ago)

@DDReaper I didn't just went straight for the 3d tank one :P

**Comment by cra0zy** [comment]
I'll borrow Raspberry Pi from a friend next week and I'll try to setup code for it.

**Comment by WardBenjamin** [comment]
@cra0zy I have one available to me. Could I be of assistance?

**Comment by cra0zy** [comment]
Sorry, for now, no, but maybe later for testing...

**Comment by WardBenjamin** [comment]
No problem. Ping me if you want me to do something!

**Comment by thefiddler** [comment]
Does Raspberry Pi support KMS? If so, OpenTK now has a KMS/DRM backend that should work out of the box. 

I have ordered a RPi 2 for testing that will hopefully arrive soon for testing.

**Comment by chrisgwilliams** [comment]
I'd be interested in seeing this. I played with it a while back but
couldn't past the OpenTK hurdle.

Thanks,

Chris Williams

**Comment by tomspilman** [comment]
Note i'm told there is also the possibility to support RP2 via Windows 10.

**Comment by thefiddler** [comment]
OpenTK also has a SDL2 backend. If SDL2 is available on RPi then that should also work.

Regarding Win10, it appears that this is some sort of cut down version without a graphical user interface. I doubt that DX or GL drivers will be available on that.

**Comment by KonajuGames** [comment]
> Regarding Win10, it appears that this is some sort of cut down version without a graphical user interface. 

True, RPi2 will use Windows 10 for IoT, but there are three versions of Windows 10 for IoT (industry, mobile and small) and all versions can run Universal Apps.  Industry has the full desktop shell.  Mobile has the Modern Shell, and Mobile has no shell but still supports the setting of a Universal App to run at boot.

http://www.anandtech.com/show/9099/microsoft-hints-at-windows-10-iot-skus

**Comment by tomspilman** [comment]
> all versions can run Universal Apps

So almost nothing to do to support RP2 running Windows 10.  We just use our normal Windows 10 Unversal App platform.

**Comment by KonajuGames** [comment]
It would appear so at this stage.

**Comment by thefiddler** [comment]
Awesome I didn't know that. I will give that a spin when my hardware arrives.

**Comment by KonajuGames** [comment]
We won't be able to test it until they release Windows 10 for IoT, which will be around the same time as the general release of Windows 10.  There is no preview release of it.

**Comment by tomspilman** [comment]
@cra0zy - This works now right?  Or should we look at this again?

**Comment by cra0zy** [comment]
It does not work (not on the Linux platforms at least).

**Comment by dellis1972** [comment]
On of the main problems with the Pi was it needed X11 hacks to get it
working. We should revisit this.

**Comment by Jjagg** [comment]
@dellis1972 Do you remember the details? I think those are no longer necessary with the latest version of SDL. From just reading around, it seems to me like we could support RPi by using the following:

- OpenAL for audio (ALSA)
- SDL for windowing and input
- GLES bindings for graphics

So the platform would be much like DesktopGL, but probably with slightly modified graphics setup (similar to Android).

**Comment by tomspilman** [comment]
I wonder if i could setup a TeamCity build agent on a RP3 and run our unit tests on there.  I might order one and set it up just to check it out.

**Comment by WardBenjamin** [comment]
@tomspilman if you order a RPi, I recommend ordering one of the new RPi 3B+ models: 

https://www.raspberrypi.org/blog/raspberry-pi-3-model-bplus-sale-now-35/

The new model has significantly increased CPU performance (mostly from the clock speed bump) and much faster Ethernet (technically a gigabit chip but you won't see that fast).

**Comment by tomspilman** [comment]
@WardBenjamin - Yeah i saw that.  My interest in this is that we've done a few projects for museums and RP3 is a pretty good device to run simple kiosk projects with simple games.  I think it would be pretty nice if we supported it.

Last i check Win10 UWP on RP2 worked well... so we support it that way for sure.  This is more for people wanting to run Linux on there instead of a licensed copy of Win10.

**Comment by mika76** [comment]
This might help you out  http://www.up-board.org/up/ - it's an intel based
board with the same form factor as the raspberry pi

**Comment by galexandreg** [comment]
Is there anything new for Raspberry Pi support? I'm a bit confused by this issue basically saying that it's not compatible yet, and this other one (#6342) where it does seem to work fine with the DesktopGL platform...
If anyone knows and has the time to answer, that would be appreciated 😄 

Thanks

**Comment by Jjagg** [comment]
@galexandreg It should Just Work. DesktopGL used SDL for windowing, OpenGL for graphics and OpenAL-Soft for audio. All of that works on RPi. The discussion in this ticket is massively outdated and is mostly about issues from before we used SDL :)
