### ISSUE TITLE
Unable to read Compressed Texture on Android

### ISSUE THREAD

**Issue by johnn82** [MonoGame/MonoGame#3451]
Hi, I think i've discovered a "strange" bug. When using MG and trying to open a compressed texture (DXT size 1024x1024) in Android it returns an error while reading the stream opened via the AssetsManager. The problem occours only when your texture "ends" with opaque white color (it works with black, haven't tried with other colors) I attach a simple image that cause the error.  This error could be related on how the Pipeline editor creates xnbs OR it is an Android BUG: For eg. If I add .xnb file extension into the "Leave the following resource extensions uncompressed" option, all works fine!

Failing Texture Example with Compression Enabled (DXT)
![back_21112](https://cloud.githubusercontent.com/assets/7510826/5840687/b90f235e-a197-11e4-916d-0c76ff090d57.png)

**Comment by Nezz** [comment]
There is no universal texture compression support on Android.

**Comment by johnHolmes82** [comment]
I don't get it...not a problem of texture compressione I think
Il 21/gen/2015 19:30 "Adam Kapos" <notifications@github.com> ha scritto:

**Comment by prollin** [comment]
@johnHolmes82 can you describe exactly what you are trying to achieve, what is the expected result and what result you are getting; I have a hard time understanding your question above.

Also a code snippet of what you are trying to do would help.

**Comment by johnHolmes82** [comment]
Sorry if I'm unable to explain the problem. The fact is very simple.

1. I've got a texture, PNG file 1024x1024 (i can share an example if you
need) which has in the lower part a big block of same color pixels
2. I create the xnb file from the PNG file using the MG Pipeline tool.
Settings are: color key enabled = false, compressed
3. When I try to load the texture using the content manager I get an error:
"Unable to access asset data: -1" which is raisen when MG is trying to copy
into memory the stream opened by the AssetManager.Open method.

If the problem is still unclear i can share an example

@johnHolmes82 <https://github.com/johnHolmes82> can you describe exactly
what you are trying to achieve, what is the expected result and what result
you are getting; I have a hard time understanding your question above.

Also a code snippet of what you are trying to do would help.

—
Reply to this email directly or view it on GitHub
<https://github.com/mono/MonoGame/issues/3451#issuecomment-70918030>.

**Comment by tomspilman** [comment]
@johnHolmes82 - Does your PNG happen to have data in the alpha channel? Could be we are building a DXT3 or DXT5 texture for Android and not all Android devices support that format.

**Comment by prollin** [comment]
@johnHolmes82, as @tomspilman mentioned, only Tegra devices support DXT compressed texture. I would suggest to try on a Tegra device and see if you still see this issue.

**Comment by tomspilman** [comment]
> Tegra devices support DXT compressed texture

I thought all Android devices supported STC/DXT1 compression...  it was the versions of DXT with alpha that was not supported.  Am I wrong?

**Comment by KonajuGames** [comment]
> I thought all Android devices supported STC/DXT1 compression... it was the versions of DXT with alpha that was not supported.

ETC1 is the common texture compression format on Android.  ETC1 does not support alpha.

**Comment by johnHolmes82** [comment]
The fact is that some files are correctly read by the CM (on same device,
in my case a galaxy tab1) while others are not. Tomorrow i will post an
example project.
Il 22/gen/2015 01:23 "KonajuGames" <notifications@github.com> ha scritto:

**Comment by prollin** [comment]
@tomspilman @KonajuGames, a bit off topic but this issue brings up a good point: MonoGame should default to ETC1 when building content for the Android platform; the way we deal with Alpha is to simply detect it in the TextureProcessor and fallback to no compression (we actually fallback to RGBA4444 in this case). Another solution is to extract the Alpha and encode it separately ... but that requires special handling in the developer's shaders.

I sent a PR a while ago to improve the ManagedPVRTC library to support compressing to ETC formats but I realized that there was too many changes and it was also not fully tested. I ended up creating a [new wrapper around PVRTexLib and just made it public](https://github.com/flyingdevelopmentstudio/PVRTexLibNET) so MonoGame (or anyone interested) can easily fork it and/or contribute.
This is what we use for our content (along with a custom content pipeline for textures) and it has worked great so far.

**Comment by tomspilman** [comment]
> MonoGame should default to ETC1 when building content for the Android platform

I agree.

>  the way we deal with Alpha is to simply detect it in the TextureProcessor and fallback to no compression (we actually fallback to RGBA4444 in this case). 

RGBA4444 is indeed the best path for alpha support.


> Another solution is to extract the Alpha and encode it separately ... but that requires special 
handling in the developer's shaders.

That is the path we cannot support in MonoGame.... or it least it can't be the official path for supporting alpha.

**Comment by KonajuGames** [comment]
> MonoGame should default to ETC1 when building content for the Android platform

I've been using Unity in my day job and it defaults to ETC1 for opaque textures and RGBA4444 for textures with alpha.  This is the path we should take for the default compression for Android platforms.

**Comment by johnHolmes82** [comment]
Here a simple project which shows the issue I'm facing. Don't know exactly where it come from. Don't know if it's a DXT compression problem OR and Android bug problem reading Assets which has been compressed.

Download the example from here!
https://dl.dropboxusercontent.com/u/40411013/Various/MonoGameTest2.zip

Note:
- Add a reference to a valid MG assembly
- Run the project as it is and then try to run it after adding  the ".xnb" into the uncompressed files options as described here ![Uploading commesse.url.changed.PNG . . .]()

**Comment by KonajuGames** [comment]
I haven't been able to replicate the crash on my Nexus 5 by adding .xnb to the compression exclusions.  Because the Galaxy devices do not support DXT, the MonoGame code was decompressing them to 32-bit Color format.  This results in huge textures in memory and is not what you were looking for when you selected texture compression.

I am making some changes now to remove the hidden decompression of DXT textures at load time and to use ETC1 texture compression for opaque textures and RGBA4444 for alpha textures as the default when building data for Android.  @prollin, I'll be using your PVRTexLibNET for this.

**Comment by johnHolmes82** [comment]
@Konaju: Not sure I've understood. In my case the crash is presenting when
the "not working xnb" is compressed by the AAPT (by android). I don't think
it's an issue related to DTX or ETC compression. MG raise an error when
it's trying to read the asset from the physical .xnb file into the
MemoryStream (to perform better). This occours before ANY opengl operation.
Don't think Android cares about "texture compression" at that point of
reading the asset!

2015-01-22 16:04 GMT+01:00 KonajuGames <notifications@github.com>:

> I haven't been able to replicate the crash on my Nexus 5 by adding .xnb to
> the compression exclusions. Because the Galaxy devices do not support DXT,
> the MonoGame code was decompressing them to 32-bit Color format. This
> results in huge textures in memory and is not what you were looking for
> when you selected texture compression.
>
> I am making some changes now to remove the hidden decompression of DXT
> textures at load time and to use ETC1 texture compression for opaque
> textures and RGBA4444 for alpha textures as the default when building data
> for Android. @prollin <https://github.com/prollin>, I'll be using your
> PVRTexLibNET for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/MonoGame/issues/3451#issuecomment-71033267>.
>



-- 
Francesco Colombo
  -- Ad Maiora Studio

-------------------------
The information contained in this message may be privileged and
confidential. If you are NOT the intended recipient, please notify the
sender immediately with a copy to info@admaiorastudio.com and destroy this
message.
Please be aware that email communication can be intercepted in transmission
or misdirected. Your use of email to communicate protected health
information to us indicates that you acknowledge and accept the possible
risks associated with such communication. Please consider communicating any
sensitive information by telephone, fax or mail. If you do not wish to have
your information sent by email, please contact the sender immediately.

**Comment by KonajuGames** [comment]
> MG raise an error when it's trying to read the asset from the physical .xnb file into the MemoryStream (to perform better).

That's the issue that I could not reproduce here.  The rest of it is a follow-on from most of the discussion in this thread, even though it wasn't related to the actual problem.

**Comment by johnHolmes82** [comment]
@Konaju: Ok fine! Maybe the problem occours only on "older" devices like
mine a Galaxy Tab 1

2015-01-22 16:28 GMT+01:00 KonajuGames <notifications@github.com>:

> MG raise an error when it's trying to read the asset from the physical
> .xnb file into the MemoryStream (to perform better).
>
> That's the issue that I could not reproduce here. The rest of it is a
> follow-on from most of the discussion in this thread, even though it wasn't
> related to the actual problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/MonoGame/issues/3451#issuecomment-71037485>.
>



-- 
Francesco Colombo
  -- Ad Maiora Studio

-------------------------
The information contained in this message may be privileged and
confidential. If you are NOT the intended recipient, please notify the
sender immediately with a copy to info@admaiorastudio.com and destroy this
message.
Please be aware that email communication can be intercepted in transmission
or misdirected. Your use of email to communicate protected health
information to us indicates that you acknowledge and accept the possible
risks associated with such communication. Please consider communicating any
sensitive information by telephone, fax or mail. If you do not wish to have
your information sent by email, please contact the sender immediately.

**Comment by johnHolmes82** [comment]
@Konaju: I confirm the issue is related to certain Android version (or
device at least). On my Nexus 5 with Android 5 the texture is loaded fine.
On the Galaxy Tab 1 with Android 4.2 i get the error. Any clue?

2015-01-22 16:30 GMT+01:00 Francesco Colombo <
francesco.colombo@admaiorastudio.com>:

> @Konaju: Ok fine! Maybe the problem occours only on "older" devices like
> mine a Galaxy Tab 1
>
> 2015-01-22 16:28 GMT+01:00 KonajuGames <notifications@github.com>:
>
>> MG raise an error when it's trying to read the asset from the physical
>> .xnb file into the MemoryStream (to perform better).
>>
>> That's the issue that I could not reproduce here. The rest of it is a
>> follow-on from most of the discussion in this thread, even though it wasn't
>> related to the actual problem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mono/MonoGame/issues/3451#issuecomment-71037485>.
>>
>
>
>
> --
> Francesco Colombo
>   -- Ad Maiora Studio
>
> -------------------------
> The information contained in this message may be privileged and
> confidential. If you are NOT the intended recipient, please notify the
> sender immediately with a copy to info@admaiorastudio.com and destroy
> this message.
> Please be aware that email communication can be intercepted in
> transmission or misdirected. Your use of email to communicate protected
> health information to us indicates that you acknowledge and accept the
> possible risks associated with such communication. Please consider
> communicating any sensitive information by telephone, fax or mail. If you
> do not wish to have your information sent by email, please contact the
> sender immediately.
>



-- 
Francesco Colombo
  -- Ad Maiora Studio

-------------------------
The information contained in this message may be privileged and
confidential. If you are NOT the intended recipient, please notify the
sender immediately with a copy to info@admaiorastudio.com and destroy this
message.
Please be aware that email communication can be intercepted in transmission
or misdirected. Your use of email to communicate protected health
information to us indicates that you acknowledge and accept the possible
risks associated with such communication. Please consider communicating any
sensitive information by telephone, fax or mail. If you do not wish to have
your information sent by email, please contact the sender immediately.

**Comment by johnHolmes82** [comment]
@Konaju: Tested also on Kindle Fire HD 7 and Xamarin Simulator either with
Android 4.2. Same issue.

2015-01-26 14:29 GMT+01:00 Francesco Colombo <
francesco.colombo@admaiorastudio.com>:

> @Konaju: I confirm the issue is related to certain Android version (or
> device at least). On my Nexus 5 with Android 5 the texture is loaded fine.
> On the Galaxy Tab 1 with Android 4.2 i get the error. Any clue?
>
> 2015-01-22 16:30 GMT+01:00 Francesco Colombo <
> francesco.colombo@admaiorastudio.com>:
>
>> @Konaju: Ok fine! Maybe the problem occours only on "older" devices like
>> mine a Galaxy Tab 1
>>
>> 2015-01-22 16:28 GMT+01:00 KonajuGames <notifications@github.com>:
>>
>>> MG raise an error when it's trying to read the asset from the physical
>>> .xnb file into the MemoryStream (to perform better).
>>>
>>> That's the issue that I could not reproduce here. The rest of it is a
>>> follow-on from most of the discussion in this thread, even though it wasn't
>>> related to the actual problem.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/mono/MonoGame/issues/3451#issuecomment-71037485>.
>>>
>>
>>
>>
>> --
>> Francesco Colombo
>>   -- Ad Maiora Studio
>>
>> -------------------------
>> The information contained in this message may be privileged and
>> confidential. If you are NOT the intended recipient, please notify the
>> sender immediately with a copy to info@admaiorastudio.com and destroy
>> this message.
>> Please be aware that email communication can be intercepted in
>> transmission or misdirected. Your use of email to communicate protected
>> health information to us indicates that you acknowledge and accept the
>> possible risks associated with such communication. Please consider
>> communicating any sensitive information by telephone, fax or mail. If you
>> do not wish to have your information sent by email, please contact the
>> sender immediately.
>>
>
>
>
> --
> Francesco Colombo
>   -- Ad Maiora Studio
>
> -------------------------
> The information contained in this message may be privileged and
> confidential. If you are NOT the intended recipient, please notify the
> sender immediately with a copy to info@admaiorastudio.com and destroy
> this message.
> Please be aware that email communication can be intercepted in
> transmission or misdirected. Your use of email to communicate protected
> health information to us indicates that you acknowledge and accept the
> possible risks associated with such communication. Please consider
> communicating any sensitive information by telephone, fax or mail. If you
> do not wish to have your information sent by email, please contact the
> sender immediately.
>



-- 
Francesco Colombo
  -- Ad Maiora Studio

-------------------------
The information contained in this message may be privileged and
confidential. If you are NOT the intended recipient, please notify the
sender immediately with a copy to info@admaiorastudio.com and destroy this
message.
Please be aware that email communication can be intercepted in transmission
or misdirected. Your use of email to communicate protected health
information to us indicates that you acknowledge and accept the possible
risks associated with such communication. Please consider communicating any
sensitive information by telephone, fax or mail. If you do not wish to have
your information sent by email, please contact the sender immediately.
