### ISSUE TITLE
Remove code to load non-content files in ContentManager (after v3.3)

### ISSUE THREAD

**Issue by tgjones** [MonoGame/MonoGame#3483]
IMO, this line in ContentManager is fairly unhelpful:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Content/ContentManager.cs#L315

``` csharp
if (string.IsNullOrEmpty(assetName))
{
    throw new ContentLoadException("Could not load " + originalAssetName + " asset as a non-content file!", ex);
}
```

It just covers up the original exception (unless you look at `InnerException`, but not everyone knows to do that).

If the non-content fallback file can't be found, couldn't we just re-throw the original exception?

**Comment by KonajuGames** [comment]
That whole section of ContentManager (loading of raw assets) will disappear
soon as our own content pipeline matures.​

**Comment by tgjones** [comment]
Ah, cool - do you think that will be soon enough to make it pointless making this change?

**Comment by KonajuGames** [comment]
I think we could actually remove it now (after 3.3) since our content pipeline is available and working for all assets that may have been loaded as raw assets.​

**Comment by tomspilman** [comment]
> I think we could actually remove it now (after 3.3) 

I'm all for it.

**Comment by Nezz** [comment]
I agree that the error is unhelpful. I have helped like a hundred peope for whom a simple "file not found" would have been a lot more time useful.

But at least it was a way to make more people come to the communiy forum :)

**Comment by jamesford42** [comment]
+1
Expected to see: "could not load content x because path y does not exist".

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
