### ISSUE TITLE
Suggestion for doc pages

### ISSUE THREAD

**Issue by Chaosus** [MonoGame/MonoGame#3491]
instead of 
![image](https://cloud.githubusercontent.com/assets/3036176/6004529/7d2bd2c0-ab14-11e4-9713-cd1b7142fb64.png)

using something like this 

![image](https://cloud.githubusercontent.com/assets/3036176/6004547/99776c32-ab14-11e4-855e-71d63aa1222e.png)

is more beauty and consistent ?

**Comment by tomspilman** [comment]
I think some for of "all platforms" would be great.

We would need to figure out how to add this feature to SharpDoc.  It is pretty extensible, so will be possible.  Just need someone to do the work.

**Comment by KonajuGames** [comment]
It makes sense.  We don't even include iOS, Android or OS X in that list yet, and since 95% (more?) of the APIs are available on all platforms, adding more platform icons to almost every API in the documentation will get crazy.

**Comment by tomspilman** [comment]
> We don't even include iOS, Android or OS X in that list yet

Note the reason for that is that the SharpDoc tool fails on those assemblies for some reason.  Haven't had time to debug it yet.

**Comment by tomspilman** [comment]
Was thinking we probably want icons for like:

 - All Platforms
 - Desktop Platforms (pipeline stuff)
