### ISSUE TITLE
Android template compability error?

### ISSUE THREAD

**Issue by 9robin3** [MonoGame/MonoGame#3497]
Hi! I installed MonoGame 3.2 for Visual Studio 2013. Does this work for Visual Studio 2013? 
Because when I create a new Project with the Monogame Android Template,
I get the following error:

"The Project file 'location\name.csproj' cannot be opened.

There is a missing Project subtype.
Subtype: '{EFBA0AD7-5A72-4C68-AF49-83D382785DCF}' is unsupported by this installation."

How do I resolve this?

Thanks in advice﻿

**Comment by tomspilman** [comment]
Do you have [Xamarin Studio for Android](http://xamarin.com/platform) installed?  It is required for Android development.

**Comment by 9robin3** [comment]
Do I need Xamarin if I am using Visual Studio too? Or how would I use the
Android on Visual studio?

Thanks

2015-02-06 11:23 GMT+01:00 Tom Spilman <notifications@github.com>:

> Do you have Xamarin Studio for Android <http://xamarin.com/platform>
> installed? It is required for Android development.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/MonoGame/issues/3497#issuecomment-73216168>.
>



-- 

_______________________________________________________





*MY HOMEPAGE:http://www.123minsida.se/9robin3
<http://www.123minsida.se/9robin3> MY YOUTUBE CHANNEL:
http://www.youtube.com/user/9robin3?feature=mhum
<http://www.youtube.com/user/9robin3?feature=mhum>*

*_________________________________________________*

**Comment by tomspilman** [comment]
Xamarin now requires a "Business" license for the VS integration feature.  You can see the details here:

 https://store.xamarin.com/

That said you can still go for their "Indie" license and only use Xamarin Studio for deployment and debugging.  Most of the work in MonoGame titles is common and cross platform, so you can do most of you development in VS in a Windows desktop project.
