### ISSUE TITLE
Remove specific build configs from iOS project files in favor of AnyCPU

### ISSUE THREAD

**Issue by Nezz** [MonoGame/MonoGame#3500]
@hach-que Does Protobuild support AnyCPU for iOS projects?
https://github.com/SongArc/MonoGame/commit/b2c0be2b1f001b52451445824ae78a1ef1b369cc

**Comment by tomspilman** [comment]
I've always seen the `iPhone`, `iPhoneSimulator`, `Ad-hoc`, and `AppStore` stuff in the iOS projects... but never questioned if they needed to be there or not.

Anyone know how all that works and if we need it?

A simple AnyCPU config seems much better.

**Comment by Nezz** [comment]
Xamarin upgraded their build system a while ago and since then the four different build configurations are only used in the main project where the linker will do its magic.

**Comment by hach-que** [comment]
The build configurations for iOS are what was originally contributed (I don't have a Mac or iPhone).  If they're not needed any more, then someone will need to submit a PR.

**Comment by Nezz** [comment]
I looked at what needs to be changed and the required changes are same as what had to be changed going from WindowsPhone to WindowsPhone81.

**Comment by tomspilman** [comment]
https://github.com/MonoGame/MonoGame/issues/6207
