### ISSUE TITLE
[Linux] Clicks shifted to the right

### ISSUE THREAD

**Issue by WardBenjamin** [MonoGame/MonoGame#3502]
Confirmed on Arch Linux: clicks seem to be all consistently shifted to the right of the screen. I will try to add a gif of this occuring to this issue when possible. Note that the same project built against the Windows binaries (built from the source) runs perfectly fine on Windows platforms with no problems.

**Comment by cra0zy** [comment]
I never had that problem, can you post a sample code in which it happens?

**Comment by WardBenjamin** [comment]
Yeah, no problem. I'll try to leave out the irrelevant portions, but there's still going to be quite a bit of code.

**Comment by WardBenjamin** [comment]
if (newMouseState.LeftButton == ButtonState.Pressed && oldMouseState.LeftButton == ButtonState.Released)
	{
	    // Click has just occured
	    Point mousePos = new Point(newMouseState.X, newMouseState.Y);
		//Console.Out.WriteLine("Alert (Game1): Clicked Object. Object Z value: {0}.", Convert.ToString(clickedObject.GetZ()));
		var clickedTile = this.level.tileManager.tiles.Where(e => e.GetRect().Contains(mousePos)).ToList ();
	    if (clickedTile != null && clickedTile.Count () > 0 &&  clickedTile[0] != null)
	    {
			if (this.level.routes == null)
			{
				this.level.routes = new List<TradeRoute> ();
				this.level.routes.Add (new TradeRoute(clickedTile[0], blankTile));
			}
			else
			{
				if (this.level.routes.Count (route => !route.isComplete) > 0)
				{
					var curRoute = this.level.routes.Last (route => !route.isComplete);
					curRoute.Complete (this.level.pathfinder.FindRoute (curRoute.start,clickedTile [0]));
				}
				// If there is not an incomplete route, add one.
				this.level.routes.Add (new TradeRoute (clickedTile[0], blankTile));
			}
	    }
	    else
	    {
	        // Throw Exception
	    }
	}

**Comment by WardBenjamin** [comment]
The pertinent section seems to be the:
    if (newMouseState.LeftButton == ButtonState.Pressed && oldMouseState.LeftButton ==  ButtonState.Released)
    {
        // Click has just occured
        Point mousePos = new Point(newMouseState.X, newMouseState.Y);

**Comment by cra0zy** [comment]
I meant more of a sample Game1.cs class in which it happens, just small code in which the bug can occur....

**Comment by WardBenjamin** [comment]
I'll get that to you as soon as I can, probably tomorrow. I'll have to strip out all of the code specifically related to my game.

**Comment by cra0zy** [comment]
@tomspilman This should be closed since we switched to SDL.
