### ISSUE TITLE
Textures overwritten on Android

### ISSUE THREAD

**Issue by Nezz** [MonoGame/MonoGame#3562]
Here is what happens (`width`x`height`=`glTextureId` on `threadId`):

```
Created texture 1920x135=70001 on 1
Created texture 1920x1080=140002 on 1
Created texture 1920x1080=210003 on 1
Created texture 94x96=280004 on 1
Created texture 96x96=350005 on 1
Created texture 96x92=420006 on 1
[...]
// Resume game
Created texture 1080x1920=140002 on 1
Created texture 1080x1920=210003 on 1
Created texture 1080x1920=280004 on 1
Created texture 1920x1080=350005 on 1
Created texture 1920x1080=420006 on 1
Created texture 1920x1080=490007 on 1
// Textures overwritten, now your textures have gone haywire
// But wait, next one has a correct sequential ID:
Created texture 1920x1080=40110573 on 1 
// Then it goes wrong again
Created texture 1080x1920=560008 on 1
Created texture 1080x1920=630009 on 1
[...]
```

We have been struggling with this bug for a while (see http://community.monogame.net/t/contents-of-rendertarget2d-gets-corrupted/1974). Now I managed to find the root of it. Here it is:

Create a rendertarget in LoadContent, and recreate it if ClientSizeChanged occurs. Also load a couple of textures.

``` C#
        protected override void LoadContent()
        {
            base.LoadContent();

            this.renderTarget = new RenderTarget2D(this.GraphicsDevice, this.GraphicsDevice.Viewport.Width, this.GraphicsDevice.Viewport.Height);
            this.Window.ClientSizeChanged += (sender, e) =>
                {
                    this.renderTarget.Dispose();
                    this.renderTarget = new RenderTarget2D(this.GraphicsDevice, this.GraphicsDevice.Viewport.Width, this.GraphicsDevice.Viewport.Height);
                };

            // Also load a couple of textures
        }
```

Comment out this line so orientation changes will trigger ClientSizeChanged :
https://github.com/mono/MonoGame/blob/893ee3522f67c6725f99ccf2bde5cf33b1276d10/MonoGame.Framework/Android/AndroidGameWindow.cs#L185
Or use builds prior to https://github.com/mono/MonoGame/pull/3560

Turn the screen of the phone on/off -> Rendertarget is sequentially created with already used ID
Rotate phone -> Rendertarget is sequentially created with new ID

**Comment by tomspilman** [comment]
So what is the bug here?  Is this something broken in MonoGame?

Or is this a Android/Mono/Xamarin issue we need to work around?

**Comment by Nezz** [comment]
@dellis1972 @KonajuGames I saw you working with Android and OpenGL. Any tips what might be wrong?

**Comment by Nezz** [comment]
@tomspilman The bug is that creating a new RenderTarget2D overwrites existing textures. Kind of like two processes writing into the same memory space overwriting stuff.

**Comment by tomspilman** [comment]
@Nezz - You mean the GL implementation reuses an old (and invalid?) texture handle on resume?

**Comment by Nezz** [comment]
Yes, but if you wait a little it starts working correctly again. And by little I mean wait until the first draw or update call after resume.
