### ISSUE TITLE
Can't compile anything with Windows 8

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#3570]
Hi!

in the latest repository, I'm getting the following message when compiling a Windows 8 or Universal game:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\AppxPackage\Microsoft.AppXPackage.Targets(1496,9): error APPX0702: Payload file 'D:\utils\coding\monogame\monogame_2015_02_25\MonoGame\MonoGame.Framework\bin\Windows8\AnyCPU\Release\MonoGame.Framework\Themes\generic.xaml' does not exist.

with a 14/02/2015 snapshot, it works

**Comment by KakCAT** [comment]
actually, there was an issue with protobuild.exe, which avast reported as a virus. I copied the protobuild from the 14/02/2015 (I don't know if this could be the cause for the faulty compilation)

**Comment by tomspilman** [comment]
> there was an issue with protobuild.exe, which avast reported as a virus.

Because how protobuild works (it extracts binaries and resources from itself) it can suspected of being a trojan by some antivirus tools.  You just have to ignore it.

**Comment by KakCAT** [comment]
Hi Tom,

I just addded protobuild to the antivirus update list but the problem described in the first post still persists. Is it possible to reopen the issue?

thanks

**Comment by tomspilman** [comment]
Anyone else running into this issue?

**Comment by KakCAT** [comment]
Hi!

the problem also happens in Windows Phone 8.1. I've found the cause of the problem, but no idea about the solution, or if this is a problem of my VS2013CE installation. 

bd4b4ff8f8e8a84005746b3709d0d2134a305748 (I think, git hates me) introduced a modification which causes to WP8.1 and Windows8 .csproj to include the following information:

``` <ItemGroup>
    <Page Include="Themes\generic.xaml">
      <Platforms>Windows8,WindowsPhone81</Platforms>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
```

removing that makes both projects compile again (for me).   

NOTE: to avoid misunderstandings, MonoGame compiles always with or without the change. It's the final Game.exe which does not compile. I don't know if that is checked by the tests.

**Comment by tomspilman** [comment]
> I don't know if that is checked by the tests.

The unit tests do not generate new projects from the templates and compile and run the default game.

It would be interesting to do that, but I don't know where to begin getting VS to generate a project in an automated way.
