### ISSUE TITLE
WP8.1 orientation bug at the start 

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#3589]
Hi!

when running a WP8.1 game, the orientation is not changed until several frames have passed since the start. It is a quite weird bug, because it seems it depends on the CPU load. It looks really bad because my loading screen is in portrait (while it should be in landscape) for the whole process.

The problem can be reproduced very easily with the spinning cube example: Modify the draw function, and loop 1000 times the whole draw (except clear and base.Draw, of course).

Running the example with a single draw makes the orientation turn as soon as it is started, but with the 1000 times loop, the device takes quite a time to turn orientation.

**Comment by KakCAT** [comment]
Hi,

I had to do a video for another bug which also shows this bug. Leaving here as a reference

http://youtu.be/qBe8T9Bptq8

**Comment by tomspilman** [comment]
Fixed in #5520.
