### ISSUE TITLE
Unhandled Exception in Windows 8/8.1 when game begins running after build

### ISSUE THREAD

**Issue by gamepopper** [MonoGame/MonoGame#3621]
# Technical Specs

I'm running Windows 8.1, using Microsoft Visual Studio 2013 Update 4. Microsoft .NET Framework 4.5.1 is installed.
# Steps to Reproduce
1. Create a new Windows Store or Windows Universal 8.1 Project.
2. Build, Deploy and Run the Windows 8/8.1 project.
# What Happens

The sample template builds successfully, and shows the default splash screen for a few seconds. As soon as it finishes, the desktop appears with a Just In Time debugger window saying that a Microsoft .NET Framework exception occurred in the executable.

![exception1](https://cloud.githubusercontent.com/assets/6163825/6697117/592d6354-cce6-11e4-9fb2-00fd3a5fb751.PNG)

However the game still runs perfectly fine, and other platforms build without these issues. If you run a new VS2013 instance to handle the exception, it says that a class is not registered.

![exception2](https://cloud.githubusercontent.com/assets/6163825/6697116/592be074-cce6-11e4-8f07-5cfe119f04b2.PNG)

Here is Windows 8:
![exception3](https://cloud.githubusercontent.com/assets/6163825/6697118/592e41e8-cce6-11e4-8311-c70c49bd6ee7.PNG)

Also if you try to run the build outside Visual Studio, you have to run it twice in order to get past the splash screen.

**Comment by tomspilman** [comment]
Is `MMG.Windows.EXE` the name of your game project?  What did you set the project name to when you created the project from the universal app template?  `MMG.Windows`?

**Comment by gamepopper** [comment]
`MMG`, the `Windows` was added as part of the Universal App template.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
