### ISSUE TITLE
Where to get the MonoGame 3.3 iOS assembly?

### ISSUE THREAD

**Issue by deadlydog** [MonoGame/MonoGame#3657]
I downloaded and installed MonoGame 3.3 for Visual Studio, but looks like the iOS files were not included; "C:\Program Files (x86)\MonoGame\v3.0\Assemblies\iOS" is empty. All of the other platform folders have the MonoGame.Framework.dll and associated files though. Am I missing something?

Before looking in this directory I tried using the NuGet package (since it worked for my Android and Windows 8 projects), but it gives the following error:

```
Installing 'MonoGame.Framework.iOS 3.3.0.0'.
Successfully installed 'MonoGame.Framework.iOS 3.3.0.0'.
Adding 'MonoGame.Framework.iOS 3.3.0.0' to Xamarin.iOS Copy of DPSF.
Uninstalling 'MonoGame.Framework.iOS 3.3.0.0'.
Successfully uninstalled 'MonoGame.Framework.iOS 3.3.0.0'.
Install failed. Rolling back...
Could not install package 'MonoGame.Framework.iOS 3.3.0.0'. You are trying to install this package into a project that targets 'MonoTouch,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Any help is appreciated :)

**Comment by WardBenjamin** [comment]
This could be one of two things. It may be that you don't have an iOS development license, which I believe is required for iOS builds (see [The Xamarin Platform page](http://xamarin.com/platform) for more details). Also, (this is my guess as to the more likely of the two) it may be because you can't build for iOS on Windows, but rather only on Mac (OS X)
.

**Comment by deadlydog** [comment]
Nope, I do have an iOS license through Xamarin, so that shouldn't be the problem (although I might not have had it activated at the time I ran the MonoGame installer).  Also, I'm not actually building an iOS program, just an iOS library, so I don't need a Mac to do that build.  I had this all working with the previous version of MonoGame.  It seems like they just forgot to include the iOS assembly in the MonoGame installer.

**Comment by deadlydog** [comment]
Still no reply from the monogame team. Was this assembly intentionally left out of the installer?  I'm guessing not.

**Comment by danzel** [comment]
@DDReaper handles the nuget packages. Let's bump him in to this issue :)

**Comment by danzel** [comment]
Possibly related #3573

**Comment by DDReaper** [comment]
The iOS dll's are contained in:

* The Windows installer (accessible through Xamarin Enterprise in VS) or MonoDevelop
* the MonoDevelop installer (for Mac)
* the MonoGame.Framework.iOS NuGet

**Comment by deadlydog** [comment]
I have Xamarin Business Edition for VS, but was unable to find where to get the binary.  I also don't have a Mac, so options 1 and 2 did not work for me.  And when I tried to install the NuGet package, that didn't work either.  Since I couldn't install the NuGet package directly via Visual Studio, I had to "hack" the URL to download the assembly.  You can get it from https://www.nuget.org/api/v2/package/MonoGame.Framework.iOS/3.3.0.  This was way harder than it should have been; none of the other platforms gave me problems though, so that's good.

**Comment by DDReaper** [comment]
OK, double checked on the MSI and you are correct, even though an iOS folder is created, it isn't populated.  V.Odd.

However check this GIF for creating a new iOS project on Windows and adding MonoGame via NuGet, worked for me (This is the mode I used for creating the iOS sample on the new sample repo):
![xamarinios](https://cloud.githubusercontent.com/assets/1793042/7003447/753e0b18-dc52-11e4-8f16-277f4af54329.gif)

**Comment by deadlydog** [comment]
Thanks @DDReaper, but I'm not actually creating an iOS project.  I've created a particle system library ([DPSF](http://www.xnaparticles.com)) and was just trying to create an iOS-friendly assembly that other people could use in their iOS projects.  Your solution should work for everyone else though who can actually install the NuGet package in their project :)

**Comment by DDReaper** [comment]
Ahh, right. Didn't get that from your initial inquiry.

To build your library all, you will sadly need a Mac, you can use the PCL or iOS dll's as the reference to build an iOS specific version.

However a better plan would be to build a version in a PCL project that targets all your supported platforms if you can. Use the PCL version of MG as a reference for MG compatibility.
Only issue you may face is unsupported PCL classes, which you'll have to try and work around (although you shouldn't in your case)

If you want help with that, just give me or Deam a shout

**Comment by deadlydog** [comment]
Thanks for the suggestion @DDReaper.  I just setup a PCL project and was able to get DPSF built in it with the PCL version of MonoGame with minimal changes required :)  Would I be able to use this assembly to target ALL of the platforms that MonoGame supports then?  Mac, Linux, OUYA, XBox 360, etc?  When creating the PCL project it did not list these platforms.
![pcl](https://cloud.githubusercontent.com/assets/1187140/7017846/bc500ae8-dcba-11e4-9252-c98545152424.png)
Or would I still need to setup separate projects for those ones and include a reference to the appropriate MonoGame assembly for that platform?

Also, is the MonoGame PCL version fully up-to-date (i.e. on v3.3)?  I notice that the [NuGet package](http://www.nuget.org/packages/MonoGame.Framework.Portable/) is still v3.2 and pre-release.

**Comment by DDReaper** [comment]
Nope, the beauty of a PCL is that it is a single LIB. Setting the Targets means the DLL can be referenced by all of those potential targets.  This is the same for the MG PCL.

The version of the MG PCL (if it's working for you) shouldn't matter as you are building against the promise of a set of functions / methods.  When the dev consumes it, they will be using the actual MG dll, not the PCL version (the PCL version is effectively a fake/mock of MG).
It's only an issue if there are missing methods in the PCL that you require or expect.

Look's like you are ready to fly if you are up and running already :dancer:
