### ISSUE TITLE
Pipeline tool on OSX has incorrect permissions for ffmpeg and ffprobe

### ISSUE THREAD

**Issue by smitcham** [MonoGame/MonoGame#3678]
With the default install, I was getting a FileNotFoundException when trying to build an mp3 asset.  It turns out that the installer is placing the ffmpeg and ffprobe executables down without execute permissions.

**Comment by tomspilman** [comment]
@dellis1972 ?

**Comment by dellis1972** [comment]
This should be being taken care off by 

https://github.com/mono/MonoGame/blob/2d43afcc304bbcc53d45c2f31471192c8b1daa32/MonoGame.Framework.Content.Pipeline/ExternalTool.cs#L151

That said , I'll try and include a post install script to fix that

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
