### ISSUE TITLE
MGCB <output_filename>

### ISSUE THREAD

**Issue by nkast** [MonoGame/MonoGame#3696]
for example I have those assets:
/Menu/ButtonLowRes.png
/Menu/ButtonHighRes.png
...
Lets say we have two .MGCB files "content.mgcb" & "contentHR.mgcb" and I want to specify that both   will generate "button.xnb". That way we have a content file per device (mobile/ desktop) and keep the loading code simple. The only way to do that now is to mirror my /content folder.

All commands in .mgcb (=response file) are treated as command parameters therefore I see two options: 
define a new parameter /outputName:&lt;output_filename&gt;
modify build parameter /build:&lt;content_filepath&gt;=&lt;output_filename&gt; 
where  [=&lt;output_filename&gt;] will be optional.

**Comment by tomspilman** [comment]
So I guess here you are building "content.mgcb" for one project for mobile and then have another project for desktop that builds "contentHR.mgcb"?  The problem being that the generated output content collides?

Note the big plan is to end up with a single content.mgcb file that can generate content for multiple target platforms.  This is why we added the preprocessor features into parsing the .mgcb file.  We just need to find the time to design and implement the UI features needed to define and edit multi-platform content from the Pipeline tool.

**Comment by nkast** [comment]
The opposite, I want the output to collide. To use different assets per platform  that have been prepared by my artist. The big picture here is that I want to edit the 'Name' property from within the Pipeline tool. I found a duplicate here https://github.com/mono/MonoGame/pull/3009 , before closing, here is another example using the pre-proccesor .

we load a texture like:
`var button = content.Load<Texture>("/Menu/Button");`

And the .mgcb would be something like:
``
#if target=phones
/processor:My565TextureProcessor
/build:Menu/ButtonDithered256x32.png;Button;
#elseif target=consoles
/processor:TextureProcessor
/build:Menu/ButtonHDR1024x128.png;Button;
#else
/processor:TextureProcessor
/processorParam:TextureFormat=DxtCompressed
/build:Menu/Button.png;
#endif
``

**Comment by tomspilman** [comment]
> To use different assets per platform that have been prepared by my artist.

That should be doable without our multi-platform support as well.

https://github.com/mono/MonoGame/pull/3009 isn't a duplicate... it is the feature you're looking for.  It is the same feature XNA supports.  I just need to finish some work on it and merge it.
