### ISSUE TITLE
MediaPlayer initialization out of ui thread -> crash 

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#3726]
Hi,

when calling MediaPlayer for the first time when not being on UI thread, the game crashes. CoreWindow.GetForCurrentThread() returns null at MediaPlayer.WME.cs, PlatformInitialize.  

This is probably the same problem as https://github.com/mono/MonoGame/pull/3124

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
