### ISSUE TITLE
Crash when rotating Windows 8 device

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#3727]
Hi,

from time to time, rotating a Windows 8 device crashes the game.

at PlatformClear in GraphicsDevice.DirectX.cs

```
            if (_currentDepthStencilView.Description.Format != SharpDX.DXGI.Format.D24_UNorm_S8_UInt)
                options &= ~ClearOptions.Stencil;
```

_currentDepthStencilView. seems to be null, even when it's been checked a few moments ago (probably being modified asynchronously)

To reproduce, just run a blank sample in the simulator and start rotating it. Sometimes it takes a while, but sometimes crashes at the first run.

I haven't been able to reproduce it in a 2 months old snapshot, but it may be due to crash randomness.

**Comment by KakCAT** [comment]
Hi,

I just noticed that the problem does not happen with the "raw" repository but when applying the fix described in the bottom of https://github.com/mono/MonoGame/issues/3316 (which is needed for WP8.1 releases)

**Comment by nkast** [comment]
@KakCAT Thanks for bringing this to my attention. Maybe the SizeChanged event recreates size-depended resources while concurrently the render thread use the old ones. We need to somehow  dispatching SizeChanged events to the render thread. A solution would be to record the change and wait until next Present to sync the change with next frame. I was thinking about this a while ago for solving another issue.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
