### ISSUE TITLE
Official repo for MonoGame extensions ?

### ISSUE THREAD

**Issue by Chaosus** [MonoGame/MonoGame#3740]
Some people are conservative and dont like new classes or method etc.. but some peoples do not. The good examples of thing to be implemented are PrimitiveBatch,Circle,animation classes for skinned model,BumpMapEffect. I agreed there is too much things for single framework library - So a good variant is to create separate repo for all extensions.
Here is few notes... I suggest

1) (most important)Link it with the official website of MonoGame and mark it visible(it must be official repo by MonoGame creators, otherwise nobody cares about it).
2) It must work on all platforms
3) It must be easy to install and use.
4) No extension methods(because it is messy and could conflicts with other libs). Use static classes with Ex ending.
5) (maybe)Divide it on separate assemblies(for peoples who does not need full functionality).

The main problem could be less developer activity and error checking for the first time. But I think the benefits of this repo will be huge(raw MonoGame couldnt do so much from a box) in the future.

PS. I heard either @dellis1972 or @KonajuGames saying they have some sort of repo - but this is not be completed without regard of 1) rule.

Share your ideas :)

**Comment by dellis1972** [comment]
The repo @KonajuGames has is https://github.com/KonajuGames/MonoGame-Support 
Having a separate extensions repo (or and official fork on the Support one) is a good idea IMHO

**Comment by Shqrdx** [comment]
I see.. its description is "Support assemblies that are not directly related to MonoGame but assist with porting games to platforms supported by MonoGame." - this intended to have complete different description. such as "Extensions support assembles that helps developers to create more complex scenes than raw MonoGame" Joke(something like this).
