### ISSUE TITLE
Video From File.

### ISSUE THREAD

**Issue by jinnin0105** [MonoGame/MonoGame#3743]
Monogame is doesn't support Video FromFile or Stream?
We really need to Video FromFile method... 

video format is mpg ffmpeg.

sorry for developer

**Comment by KonajuGames** [comment]
I don't see any such method in XNA's documentation for the [Video](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.media.video_members(v=xnagamestudio.40).aspx) class.  It should be possible to add it for most platforms.

**Comment by Jjagg** [comment]
I'm closing this because there's a lot of codecs and including a bunch of them will bloat MG lib size. A third-party solution should be used if you want to not use the Content Pipeline.
