### ISSUE TITLE
SharpDX from nuget not working

### ISSUE THREAD

**Issue by Marfusios** [MonoGame/MonoGame#3744]
Hello,

I installed Monogame 3.3 on fresh install of Visual Studio 2013 and I created Monogame Windows Project. After build and start I got an error that dependency is missing (SharpDX). So I used NuGet, it downloads latest version of SharpDX (2.6.3). After start, app throws exception:
Could not load file or assembly 'SharpDX, Version=2.5.1.0

Why monogame strictly dependent on version 2.5.1.0? By the way, there is no package in NuGet with that version and very close version 2.5.0 not working.

Current workaround is to add reference to SharpDX libraries located in "C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows\".

**Comment by hanigan6** [comment]
Any update on this besides the workaround?

**Comment by ramsays** [comment]
Just installed the latest version of MonoGame (3.5), and am still having this problem.

**Comment by tomspilman** [comment]
This should be fixed via https://github.com/MonoGame/MonoGame/pull/5748.

**Comment by DDReaper** [comment]
Max version of SharpDX is 3.0.  The new NuGet's on the dev stream now use the one's off NuGet instead of packaging them separately.
