### ISSUE TITLE
(WP8.1, WP10) Virtual navigation bar hides part of the game screen

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#3752]
When using a device with virtual navigation bar, part of the game is obscured behind the virtual navigation bar.

The virtual bar may or may not be automatically hidden depending on user configuration, so I suppose this should be handled by monogame.

https://msdn.microsoft.com/en-us/library/windows/apps/xaml/dn792127.aspx
"Note that SuppressSystemOverlays only has this effect on the nav bar if Settings > Navigation Bar > Auto Hide is set on the phone."

**Comment by KonajuGames** [comment]
From that MSDN page, it would appear that WP apps will need to handle, in the case of Nokia 630 for example, 800x480 and 854x480 depending on what the user has set the auto-hide setting to.  The `SuppressSystemOverlays` property is set to true by default for all games (anything in the Games category).

Does the `VisibleBoundsChanged` event still work for games when the nav bar is shown or hidden?  We may need to use this to determine the visible area and simply not render to the area underneath the nav bar,

**Comment by KakCAT** [comment]
I think the 'game category' is set at the store, so development builds will not have that value set to true by default until they're published or associated with the store. To avoid release surprises, the value should probably be set to true (or false) always.

In the WP8.1 emulators (720p and up) Pressing ">>", sensors, software buttons allows you to add software buttons to the device, just in case somebody doesn't has 630 or similar phones need to test.

Windows.UI.ViewManagement.ApplicationView.GetForCurrentView().SuppressSystemOverlays=true; indeed removes the navigation bar, as long as the auto-hide setting has been enabled (by default it's not enabled, so most users will always have the bar there)

I tested the VisibleBoundsChanged and yes, it is called after the auto-hidden navigation bar is brought by the user by swipping. However I'm unable to hide it again :)

**Comment by Nezz** [comment]
https://github.com/mono/MonoGame/issues/3457

**Comment by Jjagg** [comment]
Reported fixed in #3457.
