### ISSUE TITLE
[WP8.1] Portrait size not correct

### ISSUE THREAD

**Issue by LightAndrek** [MonoGame/MonoGame#3753]
Using the latest WP8.1 development build if you create a game in portrait mode, setting in Game1.cs and in the manifest

```
graphics.SupportedOrientations = DisplayOrientation.Portrait;
```

sceen width will be the height and viceversa.
Example: on a 800x480 device a normal portrait resolution would be 480x800 but MonoGame leaves width = 800 and height = 480 stretching the content to fit the screen size.

I managed to solve the problem using this:

```
    /// <summary>
    /// Allows the game to perform any initialization it needs to before starting to run.
    /// This is where it can query for any required services and load any non-graphic
    /// related content.  Calling base.Initialize will enumerate through any components
    /// and initialize them as well.
    /// </summary>
    protected override void Initialize()
    {
        // TODO: Add your initialization logic here
        int temp = graphics.PreferredBackBufferWidth;
        graphics.PreferredBackBufferWidth = graphics.PreferredBackBufferHeight;
        graphics.PreferredBackBufferHeight = temp;
        graphics.SupportedOrientations = DisplayOrientation.Portrait;
        graphics.ApplyChanges();
        base.Initialize();
    }
```

In WP8 environment this issues does'nt exist.

**Comment by tomspilman** [comment]
@LightAndrek - Can you try setting the `graphics.SupportedOrientations` in your `Game` constructor instead of `Initialize()`?

**Comment by LightAndrek** [comment]
@tomspilman Tried right now, the issue is still there.

**Comment by cra0zy** [comment]
Closing as this is no longer a supported platform.
