### ISSUE TITLE
OS X mpack leverages 3.3.X assemblies

### ISSUE THREAD

**Issue by thejayjay** [MonoGame/MonoGame#3796]
When leveraging the built in template for MonoDevelop/Xamarin it utilizes the 3.3.X nuget packages which brings down the 3.3 assemblies; was this intentional?

When setting up my recent tests I had to manually leverage 3.4 assemblies from my project directory tree; but it might be useful to correct the 'installer' so its pointing to the correct stuff.

![osx-artificats-3 4 0455-mpack](https://cloud.githubusercontent.com/assets/419952/7413898/37fa3852-ef1d-11e4-8bd5-ecb660117c28.png)

**Comment by tomspilman** [comment]
I think this is because no one has updated the nuget service to have the new assemblies yet.  We're working on automating that ( https://github.com/mono/MonoGame/issues/2843).

@dellis1972 @DDReaper ??

**Comment by dellis1972** [comment]
@thejayjay its a chicken and egg scenario. The nugets are manually built atm, so the addin can't use the 3.4 packages as they don't exist, but we have to ship with something :) 
The plan is to automate the nuget packaging so that will fix that in the future, but we are not quite there yet.

**Comment by thejayjay** [comment]
Thanks so much for the quick response I was curious if it was a chicken and egg type scenario.


Been playing around with MonoGame for awhile. I just began the process to get the OS X version of my project up to parity for testing.

I just wanted to bring up the item to make sure it was on your radar.

Do you folks have a process for closing issues here?  I don't want to clog up the issue queue since it's being worked on in #2843; and the 3.4 bits would show up for someone once you publish to NuGet.

**Comment by tomspilman** [comment]
Naw... lets leave this open.  It is pretty serious issue as we shipped what we called 3.4, but OSX users still get 3.3 how things are now.

I so hate nuget.

**Comment by dellis1972** [comment]
OK, I'm working on installing the built assemblies in the /Library/Frameworks area on a Mac. If that works I "should" be able to update all the msbuild related templates in the XS addin to use the ${MSBuildProgramFiles32} directory as we do in the windows templates. It should work on windows/mac not sure about linux though :/

**Comment by tomspilman** [comment]
@dellis1972 - I think this is fixed now right?

**Comment by cra0zy** [comment]
@tomspilman This got fixed.
