### ISSUE TITLE
Bugs in website docs - "Item" thing

### ISSUE THREAD

**Issue by Chaosus** [MonoGame/MonoGame#3807]
Here is at Matrix struct

![image](https://cloud.githubusercontent.com/assets/3036176/7441140/99c8642e-f0e3-11e4-9b99-01977c09f931.png)

The same exists for http://www.monogame.net/documentation/?page=T_Microsoft_Xna_Framework_Graphics_EffectParameterCollection

Looks like it is the indexers from these classes... we need to investigate and fix this.

**Comment by tomspilman** [comment]
> Looks like it is the indexers from these classes... we need to investigate and fix this.

Yeah... it is the indexers.  The format is quite ugly, but actually this is basically how it looks on XNA's docs:

https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.effectparametercollection_members.aspx

It just lists it as `Item`...  but if you click thru to see the overloads it does look a little nicer with `Item (Int32)` and `Item (String)`.  We could maybe at least fix it to show the indexer type.

This is all fixes in SharpDoc that we could make.

**Comment by Shqrdx** [comment]
In Matrix it has missed description and difference between first item and second overload item. I also think its good idea to create separate subheader such as Constructors, Fields, etc.. just for Indexers.

**Comment by tomspilman** [comment]
> In Matrix it has missed description(however in code it have description) 

That for sure would be a bug then.

>  I also think its good idea to create separate subheader 

I don't think so.  Generally a class has one index maybe two.  Seems like an unnecessary separation when an indexer is just a property like any other.

**Comment by Shqrdx** [comment]
> That for sure would be a bug then.

Damn, I was wrong, Its not have a description.

However 

>difference between first item and second overload item.

Still not exist
