### ISSUE TITLE
Merge WinGL and Linux MonoGame assemblies into one

### ISSUE THREAD

**Issue by cra0zy** [MonoGame/MonoGame#3831]
WindowsGL and Linux use almost the exact same code, except for Song.cs(which will for both be replaced by NVorvis) and few #ifs in OpenTKPlatform.cs.

Advantage would be that this should allow one compilation for a game that can be run from both Windows and Linux.

**Comment by WardBenjamin** [comment]
I personally would be all for this because it would mean I would only need to compile once. The issue that I see with it, however, is that any code written in the future would have to be written around this rather than being platform-dependant, as some of it is at the moment. I know we are working towards less of that, but we are continually introducing more and more of it as we add new features, but before the cross-platform options are found.

**Comment by tomspilman** [comment]
>  The issue that I see with it, however, is that any code written in the future would have to be written around this rather than being platform-dependent

I think that is and acceptable limitation.  Plus there is still the option to execute different code at runtime based on the detected platform we're on.

**Comment by WardBenjamin** [comment]
Yeah, that's true and I was thinking of pointing that out. We just would have to avoid the compile-time dependency differences.

**Comment by tomspilman** [comment]
> We just would have to avoid the compile-time dependency differences.

You also have `DllImport` which lets you late link to some native APIs after platform detection.

**Comment by WardBenjamin** [comment]
Fair enough, I wasn't arguing in the first place. :)

**Comment by tomspilman** [comment]
> I wasn't arguing in the first place. :)

And neither am I.  Just reminding people of the flexibility we do have.

**Comment by Shqrdx** [comment]
I like it, but all #define LINUX should be removed for that ?

**Comment by tomspilman** [comment]
I expect all `#if LINUX` and `#if MONOMAC` stuff would be removed.  It would be replaced by `#if OPENGL` or `#if DESKTOPGL` or something like that I expect.

**Comment by cra0zy** [comment]
So here is the list of stuff that needs to be done, in case someone wants to help, all of these tasks should be in separate PRs:
- get to the same code base for Monogame.Framework.Net
- fix OpenTK bug that's not allowing window to be resized when border is fixed on Linux
- test and make sure that mouse leave behavior is same on Linux and WinGL
- replace all #if LINUX || (WINDOWS && OPENGL) with a new tag, I think OPENTK would look nicely

**Comment by cra0zy** [comment]
> fix OpenTK bug that's not allowing window to be resized when border is fixed on Linux

I am taking this task.

**Comment by cra0zy** [comment]
Question for all, what should the new assembly be called, MonoGame.Framework.xxxx:
- OpenTK
- DesktopGL (suggested by @dellis1972 )
- OpenGL
- something else?

**Comment by KonajuGames** [comment]
Go with DesktopGL.

**Comment by WardBenjamin** [comment]
I agree. Go with DesktopGL, it seems like the most concise and descriptive option.

**Comment by dellis1972** [comment]
Other Tasks (off the top of my head)
* Implement VideoPlayer using Theora (or something similar)
* Make changes to Pipeline tool to remove, Linux, WindowsGL platforms and add "<newplaform>"
* Check the Pipeline to make sure for DesktopGL we produce "sane" outputs (e.g .ogg for songs )
* Test on Linux using MonoKickStarter.

**Comment by cra0zy** [comment]
> Implement VideoPlayer using Theora (or something similar)

This task is to be done later after all the merging.

> Make changes to Pipeline tool to remove, Linux, WindowsGL platforms and add "<newplaform>"

I totally forgot about this good thing you mentioned it.

> Check the Pipeline to make sure for DesktopGL we produce "sane" outputs (e.g .ogg for songs )
> Test on Linux using MonoKickStarter.

With #3832 I already set Pipeline to produce .ogg songs. Also MonoKickStart works without problem on current assemblies, I don't see a reason for it not to work later.

**Comment by cra0zy** [comment]
I couldn't find what is causing the bug in OpenTK, but I did setup a better code for resizing that should be acceptable on all OpenTK platforms: #3834

**Comment by cra0zy** [comment]
> get to the same code base for Monogame.Framework.Net

Taking this task now.

**Comment by tomspilman** [comment]
> I think OPENTK would look nicely

Yeah... `#if OPENTK` would be fine.


> what should the new assembly be called, MonoGame.Framework.xxxx:

Well the assemblies don't include platform names...  if you mean the project name as defined from the Protobuild script.  Yeah... DesktopGL is good.

Still I would suggest not making any change to what projects are generated until after all the code changes are done to unify the platforms.  Focus on making a few PRs that merge together parts of Linux/Windows that are currently separate.

@dellis1972 can then help with unifying the Mac side with your merged Linux+Windows.

After Linux+Windows+Mac is all merged together and all 3 projects use 100% the same code...  then we can fix protobuild to generate a single project.

This causes the least disruption to others using the code base.

> Make changes to Pipeline tool to remove, Linux, WindowsGL platforms and add " <newplaform> "

@dellis1972 - So do we add `DesktopGL` as this new platform?  I guess we can fix the enum so that the `Linux`, `MacOS`, and `WindowsGL` are all depreciated and their values equal the new `DesktopGL` enum value.

**Comment by tomspilman** [comment]
Also we need to avoid breaking the Angle platform:

https://github.com/mono/MonoGame/pull/2377

Which is based on the WindowsGL code path, but will remain a separate platform.

**Comment by Shqrdx** [comment]
Just curious.. PS Vita support is dropped ?

**Comment by tomspilman** [comment]
> PS Vita support is dropped ?

If you mean the PS Mobile stuff... we plan to drop it in July when the store officially closes for it.

**Comment by tomspilman** [comment]
@cra0zy - Note i'm working on this https://github.com/mono/MonoGame/issues/2859 which should help with this process.

**Comment by dellis1972** [comment]
few other tasks

* Remove usage of System.Drawing in the "Desktop" frameworks. 
* Get a Build of OpenTK which does not use System.Drawing.

The reason for this is it simplifies the deployment on Linux and Mac, System.Drawing has a large number of dependencies which we don't really want to deploy with a game. (libgdiplus and all of its dependencies). 

I'll take on the Removal from the Desktop framework.

**Comment by tomspilman** [comment]
> Get a Build of OpenTK which does not use System.Drawing.

That will for sure mean us having our own custom build of OpenTK as I doubt we can convince the OpenTK team to drop `System.Drawing`.

If we need our own build of OpenTK then let me know and i'll fork the official OpenTK repo to our organization https://github.com/Mono-Game .

**Comment by dellis1972** [comment]
Well they have a NOSYS_DRAWING conditional in various places already. It just needs fixing up in a few places :). That said it might be an idea to for to MG and submit PR's back for little things like this. That way we can fix things for us and contribute back.

**Comment by tomspilman** [comment]
> Well they have a NOSYS_DRAWING conditional in various places already

So they support this... then no fork for us which is great!

**Comment by dellis1972** [comment]
One thing to note, I'll get using the PngReader, so we'll only support .pngs when loading from Stream on Linux, windows, mac and Angle. But I don't think that is a bad thing because people should be using the content pipeline anyway :P

**Comment by cra0zy** [comment]
They are actually thinking on removing System.Drawing: https://github.com/opentk/opentk/issues/245

**Comment by KonajuGames** [comment]
It would be a shame to lose JPG support in FromStream as this is often used
when pulling resources from web services.

**Comment by dellis1972** [comment]
We can always use FreeImage to read jpeg's I think. or put together a jpg Reader/writer like the png one

**Comment by dellis1972** [comment]
see #2424

**Comment by tomspilman** [comment]
> It would be a shame to lose JPG support in FromStream

The plan was always to implement a simple JPEG reader/writer in the same style as the PNG one we have now.

**Comment by KonajuGames** [comment]
I'm reading that previous discussion now that had a few options for managed
code jpg reader/writers.

**Comment by cra0zy** [comment]
Next PR I submit will merge WinGL and Linux, finally there :)

**Comment by Frassle** [comment]
> I couldn't find what is causing the bug in OpenTK, but I did setup a better code for resizing that should be acceptable on all OpenTK platforms: #3834

OpenTK now has a fix for the Linux resize issue: https://github.com/opentk/opentk/issues/259
Should get pulled in soon, so you'll be able to clean up your workaround in MonoGame.

> That will for sure mean us having our own custom build of OpenTK as I doubt we can convince the OpenTK team to drop System.Drawing.

It won't be hard, it causes a lot of problems we'd like to drop it but it means breaking backwards compatibility which is never a good thing. We do have a new .NET4.5 branch which would probably be a good place to start stripping legacy stuff from. Would .NET4.5 only cause MonoGame any issues?

> Also we need to avoid breaking the Angle platform:

We'd kinda like to support Angle better in OpenTK. We've already got one pull request to add more Angle support (https://github.com/opentk/opentk/pull/253), but having a hard time reasoning about how best to expose it. MonoGames input on this topic would be very useful!

**Comment by dellis1972** [comment]
@Frassle I submitted a PR to opentk to fix the MINIMAL/NO_SYSDRAWING support which is good enough for the MonoGame so far (I tested it locally). Not sure if it meets your expectations though.

https://github.com/opentk/opentk/pull/262

**Comment by Frassle** [comment]
Haven't had a chance to go through it yet, I'll see if I can merge it in this week though.

**Comment by Frassle** [comment]
Had a look, I think we can drop the NO_SYSDRAWING define and just use MINIMAL everywhere? There's a few changes in your pull request that just comment code out, that needs to be changed to #if and do something sensible when System.Drawing isn't available.

**Comment by dellis1972** [comment]
@Frassle I've updated the PR and fixed the commented out code.

**Comment by cra0zy** [comment]
What should I do with MGCB, MonoGame.Framework.Content.Pipeline and Pipeline Tool projects?

**Comment by dellis1972** [comment]
I think the tooling projects will need to stay platform specific.

**Comment by cra0zy** [comment]
I didn't mean it like that, what I meant is where should I put them since Linux and WindowsGL solutions will be removed, should we maybe setup tool solution generation under Tools folder?

**Comment by tomspilman** [comment]
> should we maybe setup tool solution generation under Tools folder?

We don't want another solution specific to tools.  We want to keep platform specific solutions for tools.

That said...  WindowsGL never needed its own tools.  The regular Windows tools is good enough for GL.

Also could the Linux and Mac tools be merged since they will eventually be using the same DesktopGL assemblies.

**Comment by cra0zy** [comment]
> Also could the Linux and Mac tools be merged since they will eventually be using the same DesktopGL assemblies.

For the Pipeline Tool it needs #3849 done
For the rest I would have to look, but I don't think there is anything major that would need changing.

**Comment by dellis1972** [comment]
DesktopGL runtime *should* work on mac. I'd like to give it a test first before we drop the mac runtime completely.


-----Original Message-----

**Comment by tomspilman** [comment]
> I'd like to give it a test first before we drop the mac runtime completely.

Great...  the sooner we can do that the better things will be for everyone.

**Comment by Frassle** [comment]
OpenTK has now fixed the Linux window resize bug in master (https://github.com/opentk/opentk/commit/e6e8b7a357ddaf4e1e79e83e1ac232f5afe7fa5b) once you update you can probably clean up the workaround you have for that your side.

**Comment by tomspilman** [comment]
Thanks @Frassle !

**Comment by Frassle** [comment]
@dellis1972 PR to fix the Minimal configurations has been merged into OpenTK's develop and net45 branches. If you've got any more OpenTK issues blocking this work let us know.

**Comment by tomspilman** [comment]
Let's get the last of this worked out for 3.6.

**Comment by cra0zy** [comment]
> Let's get the last of this worked out for 3.6.

The only thing that is left is to merge project files in source code, so yea, I agree.

**Comment by mrhelmut** [comment]
@cra0zy Is there anything left to do here?

**Comment by cra0zy** [comment]
My above comment is still valid. We have WindowsGL and Linux solutions, which should get merged into one.

**Comment by Jjagg** [comment]
@cra0zy What exactly needs to happen here? I'm guessing Protobuild definitions, maybe the installers and minor changes to the build server? I'd like to take a stab at this :)

**Comment by cra0zy** [comment]
The only thing left is to modify Protobuild definitions, which will require some minor installer modification, that is you just need to point it to the new assemblies location. The big problem is finding a solution that both @tomspilman and @hach-que agree on...

**Comment by hach-que** [comment]
I don't mind what happens as long as the standard project names (in particular "Linux") are not dropped from the SupportedPlatforms tag, and that MonoGame still builds when you do `--generate Linux`.

**Comment by Jjagg** [comment]
So probably the solutions should stay the same, but WindowsGL and Linux should include the merged DesktopGL csproj instead of the WindowsGL and Linux projects. What about Mac? We can't merge that too?

Currently the WindowGL project still defines 'Windows' and the Linux project defines 'Linux' so I might have to take a look what changes here. Someone posted an issue on the community forum that was caused by a Windows build not working on Mac/Linux. It was related to touch. We can probably do what Tom suggested at the start of this thread and load the right dll at runtime based on the platorm.

**Comment by cra0zy** [comment]
Closing this since I opened a separate issue to discuss about the last problem (#5708).
