### ISSUE TITLE
[W8.1] SwapChainPanel support

### ISSUE THREAD

**Issue by AleksandarDev** [MonoGame/MonoGame#3847]
Discussion over at MonoGame community [link](http://community.monogame.net/t/w8-1-swapchainpanel-support/2433/2)

Basic implementation [here](https://github.com/Sparkiy/MonoGame/commit/125edb2c9170b23d4877c2c723cc9c12173fdef4)

That implementation is missing `Exit()` support as with SwapChainPanel you are not limited to just one instance of panel per application.

**Comment by nkast** [comment]
This is an older branch. GraphicsDevice.DirectX.cs  already have SwapChainPanel for W10 platform. One have to start from the latest source and move those changes from W10 to W8.1 while make  sure not to break W8.0. Mostly by adding the W8.1 platform to #ifs/#endifs.

**Comment by AleksandarDev** [comment]
@nkast I am aware that W10 already has this, but I need W8.1 version for W8.1 store apps (hence modified version from january). I would like for this feature to become part of official release.

**Comment by cra0zy** [comment]
No longer supported platform.
