### ISSUE TITLE
Make OS X Pipeline use Gtk 3 instead of Gtk 2

### ISSUE THREAD

**Issue by cra0zy** [MonoGame/MonoGame#3849]
Linux Pipeline already uses Gtk 3 so there isn't much that has to be done. To be precise only 2 things:
1) Update dependencies, I've setup a PR to update most of them, (https://github.com/Mono-Game/MonoGame.Dependencies/pull/54), the only thing that remains to be updated is libgtk-3-0.dll, which I can't compile since I don't have a Mac
2) Setup #if and OS X constants in: https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Gtk/Gtk3Integration.cs

**Comment by tomspilman** [comment]
@dellis1972 - If you have some time can you help with this?

**Comment by dellis1972** [comment]
I'll add it to my todo list :)

note to self : I need to write up my todo list :P

**Comment by cra0zy** [comment]
> note to self : I need to write up my todo list :P

lol

**Comment by cra0zy** [comment]
Found the Gtk 3 repo for OS X: 

https://wiki.gnome.org/action/show/Projects/GTK+/OSX?action=show&redirect=GTK%2B%2FOSX
https://git.gnome.org/browse/gtk-osx/

@dellis1972 Can you try and compile it?

**Comment by cra0zy** [comment]
With Eto.Forms PR this has been resolved.
