### ISSUE TITLE
Content pipeline VS integration

### ISSUE THREAD

**Issue by Ravendarke8** [MonoGame/MonoGame#3892]
What´s the actual plan, road map, general idea? I´ve noticed you removed inbuilt content compiler one version ago and since then I must say shader development became bit difficult because of slowed down iteration. Is there any chance to be able build whole project including all content in near future? At least shaders, images are not so important as they do not change so often.

**Comment by KonajuGames** [comment]
If you create a project from the current templates, they contain the necessary MSBuild steps to build the content project when the project is built.  It also copies the output files into the correct place in the build output.

**Comment by Ravendarke8** [comment]
Ah, and I was wondering, definitely my bad, thank you for answer.
