### ISSUE TITLE
Unable to create Content Project

### ISSUE THREAD

**Issue by minpav** [MonoGame/MonoGame#3917]
![screenshot 2015-06-05 16 31 07](https://cloud.githubusercontent.com/assets/12015515/8008120/6e27d548-0ba0-11e5-8ab7-f7d262f79893.png)

Always when I try to create content project it only shows error (you can see it on the picture). I tried it with monogame 3.3, 3.4 and a development version after 3.4 (3.5.0.242).

**Comment by KonajuGames** [comment]
That content project will be the XNA content project which is not supported in VS2013.  MonoGame no longer has a dependency on the XNA content project.  If you create a new project using the current project templates, it will create a .mgcb file in the project which is used to manage content.  This file is opened in the MonoGame Pipeline Tool.  The content will be automatically built and included in the output when the VS project is built.

**Comment by minpav** [comment]
Great. But it would be better to remove the not-working template then.

**Comment by cra0zy** [comment]
> Great. But it would be better to remove the not-working template then.

The template doesn't exist in the newest monogame... if you have it it's probably from an older MonoGame installation(Installer doesn't check if the previous version is installed #1372, so it just installs over it).

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
