### ISSUE TITLE
Fullscreen mode not working correctly in Windows10 UAP

### ISSUE THREAD

**Issue by aalmik** [MonoGame/MonoGame#3942]
I am not able to get full screen mode working in Windows 10 UAP in Visual Studio 2015. There is white bar on the screen like here: http://www.robmiles.com/journal/2010/8/25/windows-phone-screen-stealing-status-bar.html

I have tested Monogame 3.4 installed from setup.and also with the latest daily build version 3.5.0.265.

Running Windows Phone Emulator 10.0.1.0 WVGA inch 512MB
graphics.GraphicsDevice.Viewport.Width, graphics.GraphicsDevice.Viewport.Height
method calls returns screen size 734x480!

I have tried combinations of these rows in game constructor and in Initialize method without success.
graphics.IsFullScreen = true;
graphics.ToggleFullScreen();
graphics.ApplyChanges();

I also tried setting IsBorderless property to true but it throws notimplemented exception.
this.Window.IsBorderless = true;

**Comment by jakepoz** [comment]
Hi,

 Does the problem resolve itself with this code:

```C#
if (Windows.Foundation.Metadata.ApiInformation.IsTypePresent("Windows.UI.ViewManagement.StatusBar"))
            {
                StatusBar statusBar = Windows.UI.ViewManagement.StatusBar.GetForCurrentView();
 
                // Hide the status bar
                statusBar.HideAsync();
            }
```

**Comment by tomspilman** [comment]
The white bar is the status bar.  Speaking with MS people it really shouldn't appear if the app is fullscreen...  it is a bug that you manually have to disable it.  We've been waiting for MS to fix this.

**Comment by aalmik** [comment]
@jakepoz it came my mind to try this statusbar hiding also last night when going through MVAs Windows 10 training course http://www.microsoftvirtualacademy.com/training-courses/a-developers-guide-to-windows-10
Hiding of statusbar fixed it for now but it would be nice if MS would fix it. :+1:

**Comment by templarvii** [comment]
Has anybody an idea how to force a Monogame Windows 8.1 App start in full screen under Windows 10. I tried it for days but was not successful.

This code did not work. The game startet still in a window:
```
     graphics.IsFullScreen = true;
     graphics.ApplyChanges();
```

Also in hiding the status bar I was not successful.
I fear Microsoft could take months to solve this and I can't wait for month.

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
