### ISSUE TITLE
MonoGame Project Creation Tool

### ISSUE THREAD

**Issue by cra0zy** [MonoGame/MonoGame#3954]
The idea is as follows: There would still be project templates in Visual Studio, except now when a template is selected we would take selected options, and do:

```
mgpct.exe type=WindowsDX location=/home/name/Documents
```

and open the project generated by the tool afterwards.

The tool should have a --no-gui option, and with that it just generates a default project with the other arguments it got.

Advantages:
- same project templates for Visual Studio and MonoDevelop/Xamarin Studio
- Visual Studio Code support
- Easily have advanced options, like if the person wants to use nuget or not
  - another idea: ability to have templates/samples and downloading them only in case a project creation is started with them as base
- would be able to have Local Copy enabled for MonoDevelop's MonoGame local references without any hacks

@dellis1972 @tomspilman @KonajuGames What do you think?

**Comment by KonajuGames** [comment]
How would that work?  Can Visual Studio run an arbitrary executable when
creating a new project from a template?

I have been giving some thought to how to do something similar to XNA and
it's option to create a new project for Xbox 360 or for Windows Phone from
the Windows project.

**Comment by cra0zy** [comment]
> Can Visual Studio run an arbitrary executable when creating a new project from a template?

It should be able to... we would need to override project creation wizard and run it from there.

> I have been giving some thought to how to do something similar to XNA and it's option to create a new project for Xbox 360 or for Windows Phone from the Windows project.

I've never used that feature, can it also do it in reverse?

**Comment by KonajuGames** [comment]
> It should be able to... we would need to override project creation wizard and run it from there.

That would be a Visual Studio extension rather than just a template.

> I've never used that feature, can it also do it in reverse?

It was a right-click on any XNA project in the Solution Explorer, and it could create a project for another XNA-supported platform in the same directory linked to the same source files, then added that project to the solution.

**Comment by cra0zy** [comment]
> It was a right-click on any XNA project in the Solution Explorer, and it could create a project for another XNA-supported platform in the same directory linked to the same source files, then added that project to the solution.

That sounds so good....also it doesn't sound that hard to create.

**Comment by cra0zy** [comment]
I have decided to work on this instead of trying to help with Protobuild.Manager project... to many conflicts of opinion.

What I have so far(mid video is MD addin): https://youtu.be/vMIixCxcGgQ

@dellis1972 Do you want to join me on this?

**Comment by tomspilman** [comment]
Noting here that this is the same sort of idea as https://github.com/mono/MonoGame/issues/4288.  Once we work out what to do with that we can decide on the fate of this issue.

**Comment by cra0zy** [comment]
Closing this since dotnet templating is a thing.
