### ISSUE TITLE
Changes in 6/11 causes my game to run in shrinked screen

### ISSUE THREAD

**Issue by greyp** [MonoGame/MonoGame#3957]
My game used to display properly in full screen mode. However, after I updated my local MG source to the latest version, the screen is now shrinked. I checked and found that the change in 6/11 by Rami Tabbara was causing this issue:

"
SHA-1: be20099e423eb62193ef2af046c046ae38188bb6
- Android : GraphicsAdapter : Use screen dimensions when getting DisplayMode
- Decouples GraphicsAdapter from Game instance, in-line with other platforms
  "

**Comment by greyp** [comment]
I just updated the MG source to the latest version and this bug is still there... :(

**Comment by greyp** [comment]
I manually reverted it back on my computer. Just not sure if I should push it to the dev branch...

**Comment by rtabbara** [comment]
@greyp I'll setup a PR for this. Checking <code>AndroidGameWindow</code> it does appears that the client bounds are initialised with precisely the same dimensions [here](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Android/AndroidGameWindow.cs#L47), so I'll take a look as to why you're encountering a mismatch.

**Comment by greyp** [comment]
Thanks for your response @rtabbara ! FYI, My dev device is a Nexus 7 (2012 wifi version). :)

**Comment by Apostolique** [comment]
I believe this was fixed in #3996.
