### ISSUE TITLE
Viewport Resolution Changed to iOS Launch Image

### ISSUE THREAD

**Issue by m20tgd** [MonoGame/MonoGame#3963]
I'm creating an iOS game using Monogame and Xamarin Studio. Using an iPhone 6, when I don't have a launch image set, the viewport is the full resolution of the screen (1334 x 750 in landscape). However, when I use a launching image of the required size (1136 x 640 in landscape) this changes the viewport to these dimensions.

Is there a way to change the viewport bounds so the game can be played at full resolution?

**Comment by danzel** [comment]
I just set this up for my game and it worked correctly.

You need a 1334x750 launch image to enable that resolution on iPhone 6 (and a bigger one for iPhone 6+)

http://developer.xamarin.com/guides/ios/application_fundamentals/working_with_images/launch-screens/
Check out the "Managing Launch Screens with Asset Catalogs" section.

**Comment by m20tgd** [comment]
Thanks, I've been uploading the images onto the info.plist. I thought the images had to be the sizes they suggest. I will check out the above and give it a go tomorrow.

**Comment by danzel** [comment]
If you use the Asset Catalog it will check your sizes too :)

**Comment by m20tgd** [comment]
I set up the Asset Catalog, but unfortunately it doesn't support landscape orientation for iPhones except for 6+. You just get a blank screen! Used the storyboard technique though and that did the trick.

**Comment by danzel** [comment]
Cool, close this one off then :)

**Comment by Nezz** [comment]
>I set up the Asset Catalog, but unfortunately it doesn't support landscape orientation for iPhones except for 6+. You just get a blank screen!

This is an iOS bug. This is the workaround:
http://stackoverflow.com/a/25960203
