### ISSUE TITLE
GamePad.GetState(PlayerIndex.One).PacketNumber not Returning Value on Windows

### ISSUE THREAD

**Issue by JackSchaible** [MonoGame/MonoGame#4002]
When developing for Windows, using an Xbox 360 controller, the GamePadState.PacketNumber property doesn't appear to change when buttons, sticks, or triggers on the controller are pressed.

**Comment by tomspilman** [comment]
Interesting... do we know what the exact behavior of that should be?  Seems like it could be easy to replicate in MonoGame if it works the way I think it does.

**Comment by cra0zy** [comment]
Deja Vu... which platform?
 - WindowsDX
 - WindowsGL
 - WindowsUAP

**Comment by SergeantJack** [comment]
Sorry, WindowsDX. And the expected behavior is that the PacketNumber value should change whenever the InputState has changed. https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.input.gamepadstate.packetnumber.aspx

**Comment by Shqrdx** [comment]
@tomspilman I fixed it. Its very easy..

**Comment by SergeantJack** [comment]
@Shqrdx Thanks for the fix...how do I deploy it?

**Comment by Shqrdx** [comment]
@SergeantJack Wait a bit and it will be merged to the MonoGame. Then you can download Development Builds from site.

**Comment by cra0zy** [comment]
Better way, get the build from the MonoGame build server: http://teamcity.monogame.net/

Direct download link: http://teamcity.monogame.net/repository/download/MonoGame_DevelopWin/8775:id/Windows/MonoGameSetup.exe

**Comment by Shqrdx** [comment]
I guess this issue is fixed and should be closed.

**Comment by tomspilman** [comment]
> I guess this issue is fixed and should be closed.

Well I would say this isn't 100% done.

While we're updating `PacketNumber` under XInput controls... we need to have a similar behavior in the other controller implementations.

**Comment by Shqrdx** [comment]
I looked at OpenGL - opentk does not commit to this value at least for XBOX 360 gamepad..

**Comment by KonajuGames** [comment]
For non-XInput we would need to generate a value. It would just need to be
an incrementing value.

**Comment by cra0zy** [comment]
OpenTK should be setting this at: https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/GamePad.OpenTK.cs#L126

If it's not getting set it's probably something that should be fixed in OpenTK.

**Comment by Shqrdx** [comment]
@cra0zy You are on the Linux - create a dummy project - push this code 

    var state = GamePad.GetState(PlayerIndex.One);
    this.Window.Title = state.PacketNumber.ToString();

to Update and see. If title is 0 then its wrong.

**Comment by Shqrdx** [comment]
It is more likely
![image](https://cloud.githubusercontent.com/assets/3036176/8765302/93b73da4-2e0e-11e5-932d-f3108b34e1c2.png)
this API used SetPacketNumber for this

**Comment by cra0zy** [comment]
It's working fine for me... I have xbox 360 wireless controller btw.

**Comment by cra0zy** [comment]
If it doesn't work on Windows, you should probably look in: https://github.com/opentk/opentk/tree/develop/Source/OpenTK/Platform/Windows

**Comment by Shqrdx** [comment]
![image](https://cloud.githubusercontent.com/assets/3036176/8765333/b4d82614-2e0f-11e5-8196-4cf9aa5fdb03.png)
I think this need to be pushed to OpenTK.

**Comment by cra0zy** [comment]
You need to call SetPacketNumber
