### ISSUE TITLE
"Couldn't find a default importer" loading text files with the Content Pipeline

### ISSUE THREAD

**Issue by Heliomance** [MonoGame/MonoGame#4040]
I'm trying to use the Content Pipeline to add a text file to my project (I'm planning on storing my level designs as plain text). When I try and build the project though, I get this error:

`C:/Users/Tamsin/documents/visual studio 2013/Projects/Bambuzle/Game1/Content/Levels/1.txt: error: Couldn't find a default importer for 'C:/Users/Tamsin/documents/visual studio 2013/Projects/Bambuzle/Game1/Content/Levels/1.txt'!`

If it matters for anything, the contents of the text file look like this:

```
########
########
########
########
########
########
01000010
.700007.
.2....2.
.700007.
.307706.
........
```

**Comment by Apostolique** [comment]
For text files, you should use the copy option instead of build.
