### ISSUE TITLE
Strange texture edge bleeding when upgrading a year old game to MonoGame

### ISSUE THREAD

**Issue by hach-que** [MonoGame/MonoGame#4042]
I'm getting this strange texture edge bleeding effect after upgrading a year old game to the latest version of MonoGame:

![image](https://cloud.githubusercontent.com/assets/504826/9023721/19c6ff60-38eb-11e5-93fd-3b1f85a37923.png)

I used to do:

```
this.GraphicsDevice.SamplerStates[0].Filter = TextureFilter.Point;
```

in LoadContent, but that is no longer permitted, so I changed it to:

```
this.GraphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
```

and started performing this before rendering all of the textures.  Everything looks almost correct, but there's 1 pixel of edge where it's off (and it's always one pixel, no matter how close you are to the texture).

Is there something else I need to change or upgrade to get it to look the way it used to:

https://www.youtube.com/watch?v=PIPKPxc1KPI

**Comment by tomspilman** [comment]
I assume that is the pink lines we see there.

The possible sources I can think of:

  - You are seeing thru the edges and that is the clear color.
  - The texture is coming from a texture atlas and the neighboring texture has pink in it.
  - You are using a pink color key in the texture and processing is failing somehow.

Any of these sound possible?

**Comment by hach-que** [comment]
It is a texture atlas and the neighbouring colour is pink. However, this didn't happen originally even with the atlas, as shown in the linked video.

**Comment by tomspilman** [comment]
> It is a texture atlas and the neighbouring colour is pink

That is likely then where it is coming from then.

Did you adding padding the textures in your atlas at all?  Without padding or some other trick (disabled or limited mip filtering) this wouldn't have worked reliably.. even in DX9 (MonoGame is DX11).
