### ISSUE TITLE
Linux installer does not install required files for MGCB build

### ISSUE THREAD

**Issue by WardBenjamin** [MonoGame/MonoGame#4059]
I have recently found that the Linux installer does not install any of the files required to automagically build and copy all of a project's content using a MGCB file. It is missing (at minimum) the `MonoGame.Content.Builder.targets` file, and even now that I have that in a place where xbuild can find it, it does not seem to be building the content or copying it, though MonoDevelop is no longer complaining that it is missing the `.targets` file.

Could I get a fix for this? I don't know what else could be missing.

Note: I wrote a blog post about installing the `.targets` file to the correct place on the system, which you can find here: http://dylanwilson.net/automatic-content-building-on-linux-with-monogame

**Comment by cra0zy** [comment]
I'll look into this once #3953 gets merged.

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
