### ISSUE TITLE
MGCB can't handle malformed Fonts in the Windows Registry

### ISSUE THREAD

**Issue by Flosus** [MonoGame/MonoGame#4061]
I tried to add a simple font to my project and got errors while building it.
I tracked the issue down to the following [line](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Processors/FontDescriptionProcessor.cs#L208)

After analyzing my registry, i saw that some of my entries have invalid data. All of them have completely uppercase Names, as you can see in the image.

The data in these registry entries look like <code>ARIAL.TTF\00\0\0\0\0\0</code> 
As craftworkgames pointed out, these could be some kind of line endings. 

I don't know what made (corrupted?) the data look like this, but i just updated my machine to Windows 10.

Replacing the invalid characters could solve this, because these fonts exist in my Fonts folder and other programs can access it.

![corrupted](https://cloud.githubusercontent.com/assets/4223452/9147856/8d880c6a-3d6d-11e5-8e30-77da796a98ce.png)

Here is the corresponding [Stackoverflow Question](http://stackoverflow.com/questions/31886866/invalid-path-while-processing-font-with-mgcb/31887410)

The stack trace:

<pre><code>
default.spritefont: error: Processor 'FontDescriptionProcessor' had unexpected failure! System.ArgumentException: Illegales Zeichen im Pfad.
bei System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) bei System.IO.Path.IsPathRooted(String path)
bei Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.FindFontFileFromFontName(String fontName, String fontDirectory)
bei Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.Process(FontDescription input, ContentProcessorContext context)
bei Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context)
bei MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)</code></pre>

How to reproduce:
- Look inside your registry at SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts
- Search for a completely uppercase Entry
- Try to build with this font.

I'm sorry for my bad English. When i forgot something, please let me know.

**Comment by mattiascibien** [comment]
@craftworkgames can we just strip out the wrong characters?

**Comment by tomspilman** [comment]
Yes... we should just strip out the trailing bad characters.

**Comment by mattiascibien** [comment]
I guess I will try something Tomorrow though ;)

**Comment by craftworkgames** [comment]
For reference, this issue originated from a [stackoverflow question](http://stackoverflow.com/questions/31886866/invalid-path-while-processing-font-with-mgcb)

**Comment by Flosus** [comment]
Just for curiosity. Does somebody else noticed these Font names? Or does somebody know how they got into this format?

**Comment by mattiascibien** [comment]
@craftworkgames  can Char.MinValue be a good thing to remove those null terminated things?

**Comment by craftworkgames** [comment]
I would consider the first occurrence of \0 as the end if the string. Trim everything else off.

**Comment by mattiascibien** [comment]
Exactly what I was thinking.

**Comment by craftworkgames** [comment]
Oddly enough I ran into a similar bug yesterday in an old VB6 application at my day job. It reminded me of this issue.

[This post](http://blogs.msdn.com/b/oldnewthing/archive/2004/08/24/219444.aspx) was helpful explaining it.

**Comment by DaedalusGame** [comment]
Reminder that this is still an issue two years later.
