### ISSUE TITLE
Implement MeshBuilder

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4070]
We need to implement the `Microsoft.Xna.Framework.Content.Pipeline.Graphics.MeshBuilder` class:

https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.content.pipeline.graphics.meshbuilder.aspx

The implantation should include unit tests to verify it is working correctly.

**Comment by mattiascibien** [comment]
I have started  an implementation in https://github.com/mattiascibien/MonoGame/tree/mesh-builder but I actually need some brainstorming in implementing this (I got the theory by some experience with dynamic mesh building in OpenGL but it seems that I do not know the low levels of MeshContent.
