### ISSUE TITLE
Windows Phone 8 and Monogame

### ISSUE THREAD

**Issue by elu** [MonoGame/MonoGame#4101]
Hi,
i use the actual Monogame with SharpDX 2.6.3 and my App has a problem with the resolution of 1920x1080. When i tap to the right bottom corner i receive a position nearly to (1280,720) in a 720p-Emulator, which is correct. In a (800x480)-Emulator i receive for the same tap a position  nearly to (800,480), which is correct. In a 1080p-Emulator i receive for the same tap a position nearly to (1280,720), which is wrong. Why the touch-position doesn't work for 1920x1080?

**Comment by Nezz** [comment]
WP8.0 apps do not support 1080p. It simply acts as the screen is 720p. You need to build your app using the WP8.1 template to support 1080p.

**Comment by cra0zy** [comment]
@tomspilman This can be closed, we dropped support for WP8.0
