### ISSUE TITLE
Win10 mobile: bug with touch 

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#4105]
The following code draws lots of rectangles to bring W10 to around 1 FPS and prints mouse taps with Red, and prints Pinches with cyan:

http://pastebin.com/B313b9RX

Run the program on Lumia 630 with latest W10mobile version, and tap with several fingers at the same time for a few seconds. Once done that, all subsequent taps are reported as Pinches  (press back on the phone to clear all the taps and see the problem better)

I know this is not a common case (running at 1 FPS with multiple fingers) but may bring evidence of other problems. I was testing #3316 in windows 10 and I randomly found this. Feel free to delete this issue if you feel it's just too picky :)

There's also a huge delay between the tap is done and the tap is notified to the app (even at ~1FPS)

BTW, what is the correct term? Windows 10 mobile? UWP mobile? Windows Phone 10?

**Comment by tomspilman** [comment]
Fixed in #5520.
