### ISSUE TITLE
WP8.1: Viewport outside the render target behaves differently on Device and Simulator

### ISSUE THREAD

**Issue by sophy228** [MonoGame/MonoGame#4113]
http://monogame.codeplex.com/workitem/7798 here is the simular issues

For example: 
render taeget bounds (0, 0, 544 416) (rendertarget2D for example)
viewport bounds ( 416, 288, 544, 128) (Change the GraphicsDevice.Viewport)

Then, we draw something under such viewport: (Sprite.draw)
1. On Windows, WP8.1 Simulator:
   The content ouside the redner tagert will just be clipped ( The first result in below image)
2. On WP8.1 real device:
   All of contents on such viewport can be shown on the target, but  are shrinked even if all the contents are in the render target bound. I guess, the viewport will be shrinked first, and then content on it.. ( The second result in below image)

So it is the issue of Monogame or it is desided by actual GPUs on the devices?

![Figure](https://cloud.githubusercontent.com/assets/10008539/9594761/0639583a-5092-11e5-87b3-ffd374faa37a.png)

**Comment by lupodevelop** [comment]
I have a similar problem either. I will attach the screenshot as soon as possible.

**Comment by sevenstreak** [comment]
Since this is an old issue and Microsoft is dropping support for Windows Phones I propose to close this case since it's only adding to the clutter.

**Comment by Jjagg** [comment]
> Since this is an old issue and Microsoft is dropping support for Windows Phones I propose to close this case since it's only adding to the clutter.

MonoGame has dropped support for Windows Phone as well (#5809), so this is definitely no longer relevant. Thanks @sevenstreak 

cc @tomspilman
