### ISSUE TITLE
MGCB outputDir issue

### ISSUE THREAD

**Issue by CodingMadeEasy** [MonoGame/MonoGame#4139]
When using MGCB.exe, the files aren't being placed in the output directory that I specify. No matter what I put, they are always placed in the same directory I reference when I'm building my asset. 

Here's a sample of the command I'm running: 

MGCB.exe /outputDir:"C:\ContentOutput" /rebuild /platform:Windows /build:"C:\path\to\image.jpg"

I've tried rearranging the order of the commands listed. Nothing seems to work. 

Ps. I'm using the latest stable version (3.4)

**Comment by LoveDuckie** [comment]
Unless someone beats me to it, I can take a look at it later this evening (London GMT).

**Comment by CodingMadeEasy** [comment]
I'm guessing you weren't able to figure it out. If it's too complex or will be fixed in the next stable version then for the time being I can just create a .bat file that will copy the files where I need them to be after building.

**Comment by LoveDuckie** [comment]
I've literally just got round to it now. It's 1AM here, but I can take a look at the code.

**Comment by LoveDuckie** [comment]
I've tested those arguments and the outputdir is being recognised by the commandline parser and is being used by the build pipeline, but I have yet to test building any content. Will do tomorrow.

**Comment by CodingMadeEasy** [comment]
Ok sounds good.

**Comment by whosdatdev** [comment]
Any updates on this? I am on 3.6 and this is still an issue. Also relative paths are broken too :/

**Comment by Jjagg** [comment]
Can't replicate this. Relative paths are tracked in #4190.
