### ISSUE TITLE
UAP App Template needs to be updated to RTM?

### ISSUE THREAD

**Issue by BrainSlugs83** [MonoGame/MonoGame#4205]
Looks like the UAP App Project still creates an RC project?

When the project is being created VS 2015 warns you that you need to install an update, but when you follow the link, it's actually just instructions on how to update the project to RTM.

The link that it sends you to is here:
https://msdn.microsoft.com/en-us/library/windows/apps/xaml/mt188198.aspx

**Comment by cclements1384** [comment]
Are you using the 3.4  release or one of the more recent dev builds?  

This issue is resolved in the dev builds.

-----Original Message-----

**Comment by DDReaper** [comment]
Confirmed the 3.5 dev build does use the new UAP template.
However it does have the issue currently that you need to build and then close / reopen the project for it to work as it's missing the UWP reference initially.  not had time to investigate the issue personally yet.

**Comment by richxbox** [comment]
I also fell over this issue trying to create a UWP with 3.4. Using the 3.5 dev build fixed it but took me a while to get to that solution - be great if the main release could be updated to fix it, thanks.

**Comment by BrainSlugs83** [comment]
Ahh,  that makes sense.   Where can I get a dev. build? Or do I need to build it myself?

**Comment by richxbox** [comment]
I just installed the current development build for Visual Studio from the download page:

http://teamcity.monogame.net/repository/download/MonoGame_DevelopWin/latest.lastSuccessful/Windows/MonoGameSetup.exe?guest=1

Once I upgraded then my new UWP project was created correctly.

**Comment by stonstad** [comment]
Thanks richxbox -- that was a quick solution.
