### ISSUE TITLE
MonoGame 3.5 - "AllowUserResizing/AllowAltF4 = false" has no effect using the UAP template

### ISSUE THREAD

**Issue by dbforge** [MonoGame/MonoGame#4214]
I've implemented my game class and it works so far. Now I want to prevent the user from resizing the game window and closing it using ALT+F4. In the constructor of the game class, I added the following lines:

``` csharp
public Game1()
{
    graphics = new GraphicsDeviceManager(this);
    Content.RootDirectory = "Content";
    graphics.PreferredBackBufferWidth = 600;
    graphics.PreferredBackBufferHeight = 400;
    Window.Title = "BirdAttack";
    Window.AllowAltF4 = false;
    Window.AllowUserResizing = false;
}
```

The game starts and all routines are working but I am still able to resize the window individually and close it using the combination. Putting these lines in the **Initialize**-method hasn't been working, too.
Am I doing something wrong or is this an issue in MonoGame?

**Comment by cra0zy** [comment]
UWP does not support fixed windows(aka. not resizable windows).

**Comment by ProgTrade** [comment]
Okay. Is there at least a way to set a minimum or maximum size?

**Comment by mattiascibien** [comment]
You should use the Windows 10 UWP settings if I recall well. You can set the minimum size from there. Do not remember where ATM.

**Comment by tomspilman** [comment]
> and closing it using ALT+F4

I don't know if we could do this on UWP or not.  @BrianPeek ?

**Comment by BrianPeek** [comment]
No way to stop ALT-F4 that I'm aware of...

**Comment by tomspilman** [comment]
> No way to stop ALT-F4 that I'm aware of...

Yeah... that is what I figured.  Thanks @BrianPeek !

**Comment by BrianPeek** [comment]
...and to avoid the conversation on "What about [KeyboardDeliveryInterceptor](https://msdn.microsoft.com/library/windows/apps/windows.ui.input.keyboarddeliveryinterceptor.aspx) in Win10 10586?"  It works, but requires a restricted capability in the manifest which isn't allowed in "public" UWP apps in the Store.  It would work on sideload builds, partner/internal apps, Enterprise store, or other scenarios, but it will fail WACK and fail ingestion into the public store.

**Comment by tomspilman** [comment]
Yeah...  I think there will just have to be some OS requirements we have to accept.  Disabling Alt+F4 or enforcing fixed window size is not the direction that platforms are heading in the future.

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
