### ISSUE TITLE
Texture2D.GetData<T>(T[], int, int) incorrect behaviour

### ISSUE THREAD

**Issue by Epidal** [MonoGame/MonoGame#4224]
When specifying a start index and element count in Texture2D.GetData, it's checking to see if the data array passed to it is of a length equal to startIndex + elementCount instead of comparing it to just elementCount.  This, of course, means that to get only the last pixel, you would need to pass an array equal to the size of the texture, instead of one with a length of 1.

**Comment by tomspilman** [comment]
Thanks... we could be doing a bad test there.  The best way to fix this would be to add some more unit tests that could expose what limits XNA tests for.

**Comment by Tzenchor** [comment]
I have been testing this. XNA requires that elementCount matches the size of the texture and that the size of the data array equals `startIndex + elementCount`, while Monogame only checks that the array size is big enough to hold the requested data. And in both cases the `startIndex` makes reference to the passed array, and not to the texture.

@tomspilman, do you want to be compliant with the XNA results or keep the improved version?

**Comment by nkast** [comment]
I agree with @Tzenchor,  startIndex is relative to the destination data[].

@Epidal, to read one pixel into an array of size 1, use one of the overloads and specify a source rectangle of 1x1.

@Tzenchor My opinion is that MG does the right thing here even if it affects backward compatibility (moving a MG project to XNA).

**Comment by Tzenchor** [comment]
I was just going to push the tests

**Comment by tomspilman** [comment]
>  while Monogame only checks that the array size is big enough to hold the requested data.

So yeah... lets keep MonoGame's improvement on XNA there.  It would only affect someone trying to port from MonoGame to XNA.
