### ISSUE TITLE
libmojoshader_64.dll not found

### ISSUE THREAD

**Issue by shovonnn** [MonoGame/MonoGame#4263]
When i try to compile effects with monogame pipeline 3.4, it stops with the error saying libmojoshader_64.dll not found. I tried with 2mgfx tool but the result is same. however the version 3.3 works fine. but i cannot use xnb files from 3.3 with my project which uses monogame 3.4.

I tried compiling from source. but i cannot find all the dependancies.

**Comment by mrhelmut** [comment]
If you're compiling from the sources, the dependencies must be grabbed from a sub-repository (https://github.com/MonoGame/MonoGame.Dependencies/tree/86d3c5a9ffc83419f8167ac1289419fac5c4eac2) and placed in the "./Third Party/Dependencies/" folder.
If you're using git, you can do that automatically when cloning the repo: ```git clone --recursive git://github.com/mono/MonoGame.git```
If you already cloned the repo and forget to grab the submodules, you can update them without re-cloning the entire repo: ```git submodule update --init --recursive```

**Comment by hach-que** [comment]
In the shipped versions of MonoGame, those dependencies should already be shipped with the Pipeline tool.  There should be no need to clone repositories and copy files.

What mechanism was used to install MonoGame 3.4?

**Comment by shovonnn** [comment]
I just downloaded it installer from official website. Tried with both 3.3
and 3.4. 3.3 works but 3.4 doesn't.

**Comment by tomspilman** [comment]
All I can think of here is that for some reason `libmojoshader_64.dll` isn't in the current path when it tries to use it.  I've seen this happen some time back when the Pipeline tool is launched from double clicking a .mgcb file.

So how are you launching the pipeline tool in this case?

Also go look at where we install the MonoGame tools....  typically under `C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools`.  Under there you should see `2MGFX.exe`, `MGCB.exe`, as well as `libmojoshader_64.dll`.  Correct?

**Comment by shovonnn** [comment]
Yes libmojoshader_64.dll is there in the tool directory.  I tried both
pipeline tool and 2mgfx.exe from tool directory. But error is same.

**Comment by shovonnn** [comment]
@tomspilman

**Comment by shovonnn** [comment]
@tomspilman i tried with fresh installed windows 10 machine. but no luck. Is it anything with windows 10?

**Comment by tomspilman** [comment]
> Is it anything with windows 10?

I can't say for sure...  but likely not.  Someone else will have to chime in with their experience on Win10 with MonoGame 3.4.

**Comment by KonajuGames** [comment]
You're using 64-bit Windows 10?

**Comment by shovonnn** [comment]
Yes it is 64bit. If it wasn't, I would not even reached that error.

**Comment by shovonnn** [comment]
@tomspilman @KonajuGames any luck with this issue?

**Comment by prime31** [comment]
I can repro this on a fresh install of Windows Server 2012 R2 as well. Same exact ibmojoshader_64.dll error even though the file is present

```
Build started 1/20/2016 11:42:53 PM

C:/Users/Administrator/Desktop/GaussianBlur.fx
C:/Users/Administrator/Desktop/GaussianBlur.fx: error: Processor 'EffectProcessor' had unexpected failure!
System.DllNotFoundException: Unable to load DLL 'libmojoshader_64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at TwoMGFX.MojoShader.NativeMethods.MOJOSHADER_parse(String profile, Byte[] tokenbuf, Int32 bufsize, IntPtr swiz, Int32 swizcount, IntPtr smap, Int32 smapcount, IntPtr m, IntPtr f, IntPtr d)
   at TwoMGFX.ShaderData.CreateGLSL(Byte[] byteCode, Boolean isVertexShader, List`1 cbuffers, Int32 sharedIndex, Dictionary`2 samplerStates, Boolean debug)
   at TwoMGFX.EffectObject.CreateShader(ShaderInfo shaderInfo, String shaderFunction, String shaderProfile, Boolean isVertexShader, String& errorsAndWarnings)
   at TwoMGFX.EffectObject.CompileEffect(ShaderInfo shaderInfo, String& errorsAndWarnings)
   at Microsoft.Xna.Framework.Content.Pipeline.Processors.EffectProcessor.Process(EffectContent input, ContentProcessorContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)
Build 0 succeeded, 1 failed.
```

**Comment by tomspilman** [comment]
@prime31 - Maybe try downloading [Dependancy Walker](http://www.dependencywalker.com/) and opening `libmojoshader_64.dll` with it.   It will tell you if the DLL is truly 64bit and if there are dependency errors loading it.

**Comment by prime31** [comment]
Bingo! Looks like the VSC120 was missing. All fixed up now. Thanks!

**Comment by tomspilman** [comment]
@shovonnn - If you install this...

https://www.microsoft.com/en-us/download/details.aspx?id=40784

... does it fix your issue?

@KonajuGames @dellis1972 - We should be able to rebuild `libmojoshader_64.dll` and have it link the MSVC lib instead of depending on the MSVC dll being installed I think.

**Comment by KonajuGames** [comment]
Was that the VC 2012 runtime?  Yeah, should be easy enough to statically
link.​

**Comment by tomspilman** [comment]
FYI.  I added #4485 specifically for this static linking fix.

**Comment by Jjagg** [comment]
Closing  in favor of #4485.

**Comment by hajimehoshi** [comment]
FYI:

> https://www.microsoft.com/en-us/download/details.aspx?id=40784

This link was missing.

Now the link is https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads , and "Visual Studio 2013 (VC++ 12.0)" is required. The other versions did not work.
