### ISSUE TITLE
Texture2D.GetData buggy for DXT textures

### ISSUE THREAD

**Issue by Skeatwin** [MonoGame/MonoGame#4276]
I use MonoGame 3.4 on Windows (Windows DirectX project) with Visual Studio 2015.
I have this texture into DXT1 format:
![t](https://cloud.githubusercontent.com/assets/5872066/11472683/9848267a-976e-11e5-9f27-6cb796feba33.jpg)

When I use this code:

``` c#
        Texture2D texture;
        SpriteBatch spriteBatch;

        protected override void LoadContent()
        {
            spriteBatch = new SpriteBatch(GraphicsDevice);

            // Load Dxt1 texture (256x256).
            texture = Content.Load<Texture2D>("t");
            byte[] data = new byte[texture.Width * texture.Height / 2]; // Dxt1 correct data size
            texture.GetData(data);
            texture.SetData(data); // Now texture is corrupted.
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);
            spriteBatch.Begin();

            spriteBatch.Draw(texture, Vector2.Zero, Color.White);

            spriteBatch.End();
            base.Draw(gameTime);
        }
```

I get this result:
![t2](https://cloud.githubusercontent.com/assets/5872066/11473677/00818c72-9774-11e5-951a-804b33fefc64.jpg)

But, the same code with the texture into Color format (ARGB8) work fine.
I have also tried with DXT3 and DXT5 format and it's the same result as DXT1: texture is corrupted.

A previous issue thread https://github.com/mono/MonoGame/issues/3590 suggest to change the type of struct to get texture data to avoid troubles, but no changes for DXT textures this time.

**Comment by tomspilman** [comment]
Looks like how we're stepping thru the height.

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.DirectX.cs#L168

My guess is that we should be incrementing the `row` more than we are for DXT surfaces.

**Comment by KonajuGames** [comment]
I had started looking at this. We will need to revise the process for
compressed textures.

**Comment by Skeatwin** [comment]
I would like to help you but I don't think I am at the level... (off topic but great works for the 3.5 !)
