### ISSUE TITLE
(Mac) Changing any GraphicsDeviceManager settings and calling ApplyChanges results in silent crash

### ISSUE THREAD

**Issue by prime31** [MonoGame/MonoGame#4277]
The following code is an example that will trigger the crash:

```
_graphicsManager.PreferredBackBufferWidth = width;
_graphicsManager.PreferredBackBufferHeight = height;
_graphicsManager.IsFullScreen = isFullScreen;
_graphicsManager.ApplyChanges();
```

The ApplyChanges line is what causes it. There is no stack trace at all and no logs that I can find anywhere. Changing anything and calling ApplyChanges is all it takes to repro.

**Comment by flibitijibibo** [comment]
I've not used this in years, but back when I was on MonoMac it appeared to be this right here:

https://github.com/flibitijibibo/FNA/commit/fc33725486a2cc29d52e1dc014f13128676f221b

I have no idea what it was doing there, why it caused silent exits, or what the real solution is. I moved everything to SDL2 before I could find out.

**Comment by prime31** [comment]
Confirmed that the changes linked by @flibitijibibo do indeed fix the issue. It seems a bit odd to me that no one has ever called GraphicsManager.ApplyChanges on Mac. Anyway, simple commenting out the lines making the window invisible fix the issue.
