### ISSUE TITLE
Touch broken with Windows 10 Mobile build 10586

### ISSUE THREAD

**Issue by Nezz** [MonoGame/MonoGame#4281]
Tested using the new emulator from yesterday and actual device too
Works fine on non-mobile
@tomspilman Have you encountered this?

**Comment by tomspilman** [comment]
I haven't done any Win10 work in the last few months, but it was working when Win10 launched.

Nothing has really changed in the touch system in months...

 https://github.com/mono/MonoGame/commits/develop/MonoGame.Framework/Input/Touch

Or in the Windows UAP platform:

 https://github.com/mono/MonoGame/commits/develop/MonoGame.Framework/WindowsUAP

Could be Win10 changed in a way that broke us I guess.

**Comment by Nezz** [comment]
Thanks for the swift answer. I'll dig into it :)

**Comment by Nezz** [comment]
As it turns out GetPointerDevices only returns a mouse pointer, no touch pointers anymore, so it appears to the game that touch panel isn't connected.

**Comment by tomspilman** [comment]
> As it turns out GetPointerDevices only returns a mouse pointer, no touch pointers anymore

Did they not document that change somewhere?  Seems like it could break a lot of apps.

**Comment by Nezz** [comment]
I'm not aware of any documented changes. We just started receiving complaints from people who updated :/

**Comment by tomspilman** [comment]
Weird.

@BrianPeek - Any idea what happened here?  Were we just using the API wrong?

**Comment by DDReaper** [comment]
Are you sure this is an issue.  My FD talk showed it working with touch.
Granted I had to query touch independently, the option flag to use touch as mouse didn't work.

I did note another behaviour when the screen was resized but I need to test more to verify that.

But for me, touch was working if you query the touchscreen manually

**Comment by Nezz** [comment]
This call used to return all devices:
https://github.com/mono/MonoGame/blob/0b25f56e861fb602db884c40267b99ea947bae15/MonoGame.Framework/Input/Touch/TouchPanelCapabilities.cs#L40
But as of build 10586 on mobile it only returns the mouse on emulator. Couldn't check the actual device because I cannot debug there (must be some driver issue). That results in TouchPanelCapabilities.IsConnected being false. But you still receive the touch events.

**Comment by BrianPeek** [comment]
I'll see if I can get an answer as to why behavior changed, but have you tried using the TouchCapabilities class:

https://msdn.microsoft.com/en-us/library/windows/apps/mt414179.aspx#retrieve_touch_properties
https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.input.touchcapabilities.aspx

That should tell you if there are touch devices and the number of contacts, which I think is all you you need in the code above?

**Comment by Jjagg** [comment]
I suspect this got fixed on the UWP side (assuming that's where the issue was). Someone should test this to verify.
