### ISSUE TITLE
Media Foundation (Song playback on DirectX) not working on Vista

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#4287]
Hello,

It appears that `Song` playback doesn't work on Windows Vista. We have several reports of this exception:

```
SharpDX.SharpDXException: HRESULT: [0xC00D36E3], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown
 at SharpDX.Result.CheckError()
 at SharpDX.MediaFoundation.MediaFactory.Startup(Int32 version, Int32 dwFlags)
 at SharpDX.MediaFoundation.MediaManager.Startup(Boolean useLightVersion)
 at Microsoft.Xna.Framework.Media.MediaManagerState.CheckStartup()
 at Microsoft.Xna.Framework.Media.MediaPlayer.PlatformInitialize()
 at Microsoft.Xna.Framework.Media.MediaPlayer..cctor()
```

Since we can't debug on users' machines, I don't have a more precise stack trace with the native debug messages.

According to this [SharpDX discussion](http://sharpdx.org/forum/4-general/3278-mediafoundation-and-windows-vista), Windows Vista runs a different Media Foundation version and may require an update. However, after redirecting users to the mentioned update, nothing changes and most users report that the update won't even install.

At first I thought it was related to #4176 but I can confirm it isn't.

The problem seems very rare, given that Vista users are now very few. There are merely a couple referenced occurrences of that problem on the internet.

My best guess would be that the current version of SharpDX targets a Media Foundation version incompatible with Windows Vista.

This problem, added to #4176 and the recent difficulties to rework DirectX `Song` playback make me wonder if it would be interesting to switch to another API, at least for the Windows Desktop platform (the other Windows platforms are most probably not affected by Media Foundation dependencies).

**Comment by MichaelDePiazzi** [comment]
> This problem, added to #4176 and the recent difficulties to rework DirectX Song playback make me wonder if it would be interesting to switch to another API, at least for the Windows Desktop platform (the other Windows platforms are most probably not affected by Media Foundation dependencies).

I've also been wondering the same thing... Personally, I've been toying with the idea of using NVorbis in my game for song playback (like the OpenGL platforms are currently doing).

**Comment by tomspilman** [comment]
The only downside is loosing the ability to work with existing XNA content for songs.

That said there is something attractive about a single path for Song decoding across lots of platforms.  It could all go thru the same streaming support for SoundEffect.

The performance is the only real big concern.  This would have to be threaded and perform excellent.

**Comment by tomspilman** [comment]
Another thought.

Some platforms (aka consoles) have proprietary formats that are decoded on the hardware.  It is to our benefit not to use Vorbis on those platforms.  So while it could work on all platforms... we likely don't want to use it on some of them.

**Comment by MichaelDePiazzi** [comment]
@tomspilman
Really I think the main platform we need to consider an alternative to is Windows DirectX, as the Media Foundation library has proven to be quite difficult to work with.

Yes, we'd lose the ability to work with existing XNA song content. But DirectX is the only platform this can work with anyway. No other platform (to my knowledge) can use Windows Media (WMA/WMV) formats.

I appreciate that non-desktop platforms would have their own proprietary formats. But for desktop platforms, it would definitely make things simpler to use the same format. I noticed that FNA has opted for using Ogg formats for song and video playback for this reason.

I'm releasing a demo version of my game publicly very soon, and after seeing the issues continuing to pop up with using Windows Media for song playback, I'm going to investigate using an alternative in my game (which will very likely be Ogg Vorbis) to (hopefully) try and avoid some pain.

**Comment by mrhelmut** [comment]
I also think that the problem is only related to desktop platforms. The major problem is Media Foundation being bound to the presence of a specific version of Windows Media Player. And since the WMP EULA doesn't allow us to ship the missing dll's, it raises a lot of scenario not quite funny to deal with.

Speaking of alternatives to play WMA & WMV files, I believe NAudio handles WMA but I wouldn't be surprised that it relies on Media Foundation. As far as I have looked into this, all solutions rely on system components bound to the presence of Windows Media Player. I didn't found external and fully independent libraries to handle these formats.

The main concern is the XNA content compatibility... From my very personal standpoint, I wouldn't mind drifting from that. I'm already considering switching to Desktop GL.

**Comment by mrhelmut** [comment]
Quick bump, 27% of our crash reports are related to Media Foundation issues.

If XNA content compatibility shall be preserved, we'll most probably switch to DesktopGL.

**Comment by mhughson** [comment]
Is there a known work around for the mediaplayer crash on vista?

**Comment by mrhelmut** [comment]
None. If it is critical to you, I would suggest to switch to a DesktopGL project which will use ogg instead of wma and has no dependency with WMP.

**Comment by spunky44** [comment]
Just had this reported by a Vista user as well. Is it really true there is no workaround?

**Comment by KonajuGames** [comment]
I think it may end up being worthwhile to just use Ogg Vorbis for all desktop platforms including DirectX.  Compatibility across all versions of Windows will be better and we'll be in more control of the playback.

**Comment by spunky44** [comment]
What should I tell the Vista user(s). Turn off in-game music and play the soundtrack on YouTube instead..?

**Comment by KonajuGames** [comment]
Given that none of us have a PC with Vista that suffers from this issue, we can't repro the issue and hence I don't know of a work-around that would help right now.  We can only try to work out what we can do moving forward.

Does the user have the European version of Vista (Home Basic N or Business N) that did not have Media Player installed?  There used to be a separate installer available for Media Player 11 on the European versions, but since Media Player 11 is no longer supported by Microsoft, it's not easy to find the installer any more.

Does the user have the latest updates for Windows Media Player 11 on Vista?  Media Player 12 is only supported on Windows 7 or higher.

**Comment by spunky44** [comment]
I'll ask.
I think I am a bit confused that MonoGame still relies on Windows Media Player for playing music, it's something I though had been changed from XNA.

**Comment by KonajuGames** [comment]
We try to do the "right" thing and use the OS-provided media routines to play streaming audio and video.  On mobile platforms, this is essential as it is the only way to get access to the hardware-accelerated audio and video playback.  An advantage of using Media Player on Windows is compatibility with WMA and WMV for audio and video as XNA used.  While more important in the beginning, it is not such a high priority now with our content pipeline more complete.  This will more easily permit a change to the solution for playing streaming audio and video, such as using Vorbis for audio and Theora for video on more platforms.

**Comment by spunky44** [comment]
Does MonoGame music/video work without having WMP installed? Many users had to install it under XNA.

**Comment by KonajuGames** [comment]
For MonoGame using DirectX, yes it currently needs Media Player installed, the same as XNA.  This was only really a problem with the European version of Windows Vista that did not have Media Player pre-installed due to European Union anti-trust restictions against Microsoft.

**Comment by spunky44** [comment]
Under XNA, we had a sticky post that reminded people that they needed WMP. It was pretty common for people to uninstall WMP and so they could not run the game.
I guess that sticky post will have to stay.

**Comment by spunky44** [comment]
The user says he has Windows Media Player version 11.0.6002.19378

**Comment by spunky44** [comment]
The user has agreed to keep the game. He says he will upgrade his OS.
Since a Vista user with WMP installed couldn't execute the game, I think there is something about this issue that does not make sense.

**Comment by mrhelmut** [comment]
FYI, here's the code I used to use in ```Program.cs``` when our game was still running on DirectX (we switched to DesktopGL):

```
#if WINDOWS
            // detect Media Feature Pack presence
            object legacyWMPCheck = Microsoft.Win32.Registry.GetValue(@"HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components\{22d6f312-b0f6-11d0-94ab-0080c74c7e95}", "IsInstalled", null);
            if (legacyWMPCheck == null || legacyWMPCheck.ToString() != "1")
            {
                System.Windows.Forms.MessageBox.Show("It appears that you don't have Windows Media Player installed. This game needs system features bound to Windows Media Player. Please install the Media Feature Pack corresponding to your Windows version to run this game:"
                    + Environment.NewLine
                    + Environment.NewLine
                    + "Windows 7: http://www.microsoft.com/en-US/download/details.aspx?id=16546"
                    + Environment.NewLine
                    + Environment.NewLine
                    + "Windows 8: http://www.microsoft.com/en-US/download/details.aspx?id=30685"
                    + Environment.NewLine
                    + Environment.NewLine
                    + "Windows 8.1: http://www.microsoft.com/en-US/download/details.aspx?id=40744"
                    + Environment.NewLine
                    + Environment.NewLine
                    + "Windows 10: https://www.microsoft.com/en-US/download/details.aspx?id=48231"
                    + Environment.NewLine
                    + Environment.NewLine
                    + "Windows Vista & XP: http://www.microsoft.com/en-US/download/windows-media-player-details.aspx?id=8163",
                    "Missing Windows Media Player", System.Windows.Forms.MessageBoxButtons.OK, System.Windows.Forms.MessageBoxIcon.Error);

                return;
            }
#endif

            using (var game = new NeuroVoiderGame())
                game.Run();
```

It detects the presence of the WMA/WMV codec through registry keys and prompt to download them if need be. That's the best you can do for now...

It checks a legacy WMP keys, which is valid for all Windows versions up to 10. The newest key (```HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components\{6BF52A52-394A-11d3-B153-00C04F79FAA6}```) only works starting from 7.

**Comment by spunky44** [comment]
Great, I'll put that in.

**Comment by mrhelmut** [comment]
Old duplicate of #4176, closing this one.
