### ISSUE TITLE
Mouse input on MonoGame OpenTK with multiple windows

### ISSUE THREAD

**Issue by ala53** [MonoGame/MonoGame#4297]
The issue only occurs on OpenGL (DirectX works fine). 

Steps to reproduce:
- Start the game
- Create a second instance of the game in separate AppDomain (`AppDomain.ExecuteAssemblyByName` on the same MonoGame project/executable).
- Close the newly created instance
- Mouse clicks will no longer be registered on the open window (`Mouse.GetState().LeftButton` always returns `ButtonState.Released`).

I suspect this may be an upstream issue with OpenTK -- especially since AppDomains don't sandbox native objects. Any insights?

**Comment by tomspilman** [comment]
Off the bat I would say app domain support is very low priority for MonoGame.  That said if a fix isn't too complex it would be fine to include it.

Likely you are right that this is an upstream OpenTK issue... but I couldn't exactly say what.

**Comment by ala53** [comment]
AppDomains were just the fastest way for me to explain the issue. If you create 2 `Game`s and run them in tandem via RunOneFrame(), the same issue occurs. Game "B" takes control of the mouse and never lets game "A" see it again.

**Comment by tomspilman** [comment]
This comes back to the case that MonoGame wasn't really design to run 2 Game instances at once.  Still if we fixed this it probably would make the MonoGame code more robust...  less statics and globals and stuff.
