### ISSUE TITLE
MediaPlayer.SetChannelVolume may fail despite null check (WinDX)

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#4298]
Hello,

Despite [the null check](https://github.com/mono/MonoGame/blob/083d88ce8385cf6a454a372e1d5bbafbe83243cb/MonoGame.Framework/Media/MediaPlayer.WMS.cs#L150), it may happen that `MediaPlayer.SetChannelVolumes()` raise an exception because of the async nature of Media Foundation (Windows DirectX projects).

Two different (but related to the same problem) exceptions can occur.

1) [On this line](https://github.com/mono/MonoGame/blob/083d88ce8385cf6a454a372e1d5bbafbe83243cb/MonoGame.Framework/Media/MediaPlayer.WMS.cs#L154)

```
SharpDX.SharpDXException
 at SharpDX.Result.CheckError()
 at SharpDX.MediaFoundation.AudioStreamVolume.GetChannelCount(Int32& dwCountRef)
 at Microsoft.Xna.Framework.Media.MediaPlayer.SetChannelVolumes()
```

2) [On this line](https://github.com/mono/MonoGame/blob/083d88ce8385cf6a454a372e1d5bbafbe83243cb/MonoGame.Framework/Media/MediaPlayer.WMS.cs#L155) or the previous one

```
System.NullReferenceException
 at Microsoft.Xna.Framework.Media.MediaPlayer.SetChannelVolumes()
```

Situation 1 happens when the `_volumeController` is not yet ready.
Situation 2 happens when the `_volumeController` gets reset past the null check (i.e. a new session started but didn't went through the whole initialization yet).
Both are related to the async nature of starting a new session.

This problem rarely occurs, over thousands of sessions, we had 4 of these crashes reported.

@MichaelDePiazzi May I have your thoughts on this one? Every async initializaiton should be fine, I'm quite puzzled.

**Comment by MichaelDePiazzi** [comment]
Ouch... :/

Well... I can think of 2 ways of potentially resolving this... the easy way, or the hard way.

The easy way is to simply put an exception handler around the code in question like so:

```c#
try
{
    for (int i = 0; i < _volumeController.ChannelCount; i++)
        _volumeController.SetChannelVolume(i, volume);
}
catch (SharpDXException)
{
    // The volume service is most likely not quite ready yet
}
catch (NullReferenceException)
{
    // The volume service has been disposed due to a new song being started
}
```

It's not pretty, but it should work.

The hard way is to change `PlatformPlaySong` to be a blocking call (at the moment it's technically async when playing a new song). That way there wouldn't be any async issues like this as we'd be waiting for everything to properly initialise before returning control. I believe this would also be in line with XNA behaviour as I'm fairly sure `MediaPlayer.Play` is a blocking call in XNA.

Off the top of my head, I'm not really sure what would be a nice and reliable way of doing this though.

Personally, this sounds to me like yet another reason to consider an alternative to Media Foundation for Windows DirectX (as you've suggested in #4287).

**Comment by mrhelmut** [comment]
That could be a quick workaround. Not quite clean, but I really don't see what to do besides reworking ```PlatformPlaySong``` like you said. There is also a chance that the ```SharpDXException``` is thrown for other kind of reasons we shouldn't silently catch, but I don't have the exact error code of the error we are looking for... (and also never seen any other kind of errors being raised here, we may just be fine doing this, I'm just not 100% sure).

What would @tomspilman think of this?

I'm not sure if making ```PlatformPlaySong``` a blocking call is a good thing. I've already seen it takes up to 10 seconds to start a new ```Song```. And I believe that how you managed the async initialization already takes care of the ```_volumeController``` being initialized after the media session started, so I'm not even sure that it would get rid of this problem. ```_volumeController``` seems to have an async life cycle on its own.


+1 for an alternative to Media Foundation.

**Comment by MichaelDePiazzi** [comment]
> There is also a chance that the SharpDXException is thrown for other kind of reasons we shouldn't silently catch, but I don't have the exact error code of the error we are looking for... (and also never seen any other kind of errors being raised here, we may just be fine doing this, I'm just not 100% sure).

I had a similar problem with the clock service previously ([see here](https://github.com/mono/MonoGame/blob/083d88ce8385cf6a454a372e1d5bbafbe83243cb/MonoGame.Framework/Media/MediaPlayer.WMS.cs#L125)). From what I remember, SharpDX didn't really provide any further details about the exception and this was the best I could do to handle the situation of the service not being ready yet.

> I'm not sure if making PlatformPlaySong a blocking call is a good thing. I've already seen it takes up to 10 seconds to start a new Song.

I agree. I've observed the same thing.

> And I believe that how you managed the async initialization already takes care of the _volumeController being initialized after the media session started, so I'm not even sure that it would get rid of this problem. _volumeController seems to have an async life cycle on its own.

In regards to the `NullReferenceException`, the only way this could be happening is that a new song was started while the volume was being set. I think the most likely way this could happen is if 2 different songs were played in quick succession. e.g.

1. Song 1 is started
2. Topology for song 1 becomes ready and it gets the volume service and starts setting the volumes
3. While the volume is being set, song 2 is started which sets the volume service to null and causes a `NullReferenceException` exception in `SetChannelVolumes`

**Comment by mrhelmut** [comment]
After some more digging, I'm pretty confident that catching these two exceptions is safe. However, changing volume may have misses, but it's still better than crashing. It's a rare enough problem to tackle it that way, I think.

**Comment by spunky44** [comment]
I have one user who got this crash several times, so it is not as uncommon.

**Comment by MichaelDePiazzi** [comment]
I finally got a chance to look into this. I managed to reproduce it fairly reliably by continually setting the volume and playing a new song every few seconds. The fix was to simply use a lock when dealing with the volume controller. I don't know why I didn't think of that earlier! I've now submitted PR #5376 to resolve this issue.
