### ISSUE TITLE
Windows GL gives Song not a wave file error.

### ISSUE THREAD

**Issue by lionelthomas** [MonoGame/MonoGame#4314]
This code works in Windows version:
 songs = new Dictionary<string, XSong>();
 for (int i = 0; i < soundManagerInit.songs.Count; i++)
 {
         XSong song = new XSong();
         song.InitXSong(soundManagerInit.songs[i]);
         song.Song = game.Content.Load<Song>(@"sounds\songs\" + song.FileName);
         songs.Add(soundManagerInit.songs[i].name, song);
  }
and song plays with
MediaPlayer.Play(songs["Battle March"].Song);
but in Windows GL the Load gives the following error:
 Specified stream is not a wave file.
the only difference is a reference to the appropriate version.

Is there a different way to do this in the GL version.

**Comment by mrhelmut** [comment]
Did you rebuilt your XNB content for WindowsGL ? GL projects use the OGG format (while WindowsDX use WMA), that may be why it fails.

**Comment by lionelthomas** [comment]
No, I tried Mp3 and WMA but not Ogg. What do I use to convert my files from Wma to Ogg?
Thanks.

**Comment by lionelthomas** [comment]
Found a program to convert wma to ogg. Tried 2 qualities and the pipeline hung on both with the following message:
startIndex cannot be larger than length of string
details:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at MonoGame.Tools.Pipeline.MainView.OnDeleteItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Pipeline
    Assembly Version: 3.4.0.456
    Win32 Version: 3.4.0.456
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/Pipeline.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MonoGame.Framework.Content.Pipeline
    Assembly Version: 3.4.0.456
    Win32 Version: 3.4.0.456
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/MonoGame.Framework.Content.Pipeline.DLL
----------------------------------------
MonoGame.Framework
    Assembly Version: 3.4.0.456
    Win32 Version: 3.4.0.456
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/MonoGame.Framework.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data.SqlXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
Nvidia.TextureTools
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/Nvidia.TextureTools.DLL
----------------------------------------
CppNet
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/CppNet.DLL
----------------------------------------
SharpDX
    Assembly Version: 2.5.1.0
    Win32 Version: 2.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/SharpDX.DLL
----------------------------------------
SharpDX.Direct3D11
    Assembly Version: 2.5.1.0
    Win32 Version: 2.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/SharpDX.Direct3D11.DLL
----------------------------------------
SharpDX.MediaFoundation
    Assembly Version: 2.5.1.0
    Win32 Version: 2.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/SharpDX.MediaFoundation.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Wma and Mp3 files work fine and Ogg version can be played by Windows Media Player.
Should I add a Pipeline issue.
Thanks.

**Comment by cra0zy** [comment]
> Did you rebuilt your XNB content for WindowsGL ? GL projects use the OGG format (while WindowsDX use WMA), that may be why it fails.

That's partially correct, WindowsGL in develop version of MG uses OGG, while the stable version uses WAV.

> Found a program to convert wma to ogg. 

Use Pipeline Tool, don't convert manually: http://www.monogame.net/documentation/?page=Using_The_Pipeline_Tool

Set platform to WindowsGL in pipeline tool, add your song(format does not matter, it will convert it to correct format for you), make sure that the song is added as "Song Processor", build, and then use the built files in your project. You need both the ".xnb" and ".wav/ogg" file that the tool will produce.

**Comment by lionelthomas** [comment]
Thank you for the information.
I did as you said, but the pipeline created an xnb file and copied over the wma file. No ogg/wav file was created.
When it tried to load, it gave the error that this was not a wav file.
Don't know where to go from here. This all works in Windows version.

**Comment by cra0zy** [comment]
> Thank you for the information.
> I did as you said, but the pipeline created an xnb file and copied over the wma file. No ogg/wav file was created.
> When it tried to load, it gave the error that this was not a wav file.
> Don't know where to go from here. This all works in Windows version.

You did not set the platform of Pipeline Tool to WindowsGL...

**Comment by lionelthomas** [comment]
Here are the settings:
Build Action Build
Importer Wma Importer - MonoGame
Processor Song - MonoGame

Platform WindowsGL

Error message on load:
Additional information: Specified stream is not a wave file.

Pipeline copied over wma file and created an xnb file

What did I do wrong?
Regards.

**Comment by cra0zy** [comment]
> Pipeline copied over wma file and created an xnb file

You should have gotten either a wav or an ogg file, you didn't set the platform of the Pipeline Tool to WindowsGL.

When the Pipeline Tool is open, click on the first tree node, look at Properties you will find "Platform", and set it to "WindowsGL".

**Comment by lionelthomas** [comment]
I have checked several times and I have the Platform set to WindowsGL. I am using MonoGame Pipeline version 3.4.0.456. Is there a later version that might work?

**Comment by LanceJZ** [comment]
I'm having all the same issue, and nothing fixes it.

**Comment by cra0zy** [comment]
Gonna close this as the original issue got resolved.
