### ISSUE TITLE
Figure out what to do about Xamarin.Mac on the build server

### ISSUE THREAD

**Issue by hach-que** [MonoGame/MonoGame#4351]
Just creating an issue here based on discussion with @tomspilman in #4343.  Basically there was an issue where someone changed something and it broke the Xamarin.Mac implementation but not the MonoMac implementation.  Right now, the MonoGame build server doesn't have the latest version of Xamarin Mac installed.

I think the path forward looks something like this:
- Get an open source license of Xamarin Mac installed on the MonoGame build server
- Add some command line flag like `--force-mac-api-version MonoMac` to Protobuild
- Add build targets to test it
- Only ship one of these implementations in NuGet etc, because the whole API-breaking by Xamarin is a silly mess and we'll end up with 3 NuGet packages for different Mac APIs otherwise

**Comment by tomspilman** [comment]
Idea... isn't this sort of similar to the issue of building solutions/projects for different versions of Visual Studio?

So maybe this is a general way to override what the target development tool?

This could allow someone to force generation of VS2010 projects if needed or force generation for Xamarin.Mac?

**Comment by hach-que** [comment]
Yeah there seems like a bunch of cross-over here, although it is slightly different (targeting different IDEs instead of different APIs) so I'll have to have a think about the best way to approach it.
