### ISSUE TITLE
Monogame using.net4.5 is incompatible with visual studio 2010 express

### ISSUE THREAD

**Issue by stampergames** [MonoGame/MonoGame#4368]
After running "Protobuild", the "TargetFrameworkVersion" property in the generated .csproj files reference "V4.5" which appears incompatible with visual studio 2010 express. On my branch, I changed them to "V4.0" on the ".Windows" projects and the solution now appears workable in visual studio 2010 express. I suspect referencing "V4.5" in the windows versions of the .csproj files was unintentional.

**Comment by hach-que** [comment]
Does it not pick the latest version of Visual Studio by default?

**Comment by stampergames** [comment]
I only have visual studio 2010 on my machine so it is my only choice.  I suppose it will work with a newer ide that supports .net 4.5.  I guess the bigger question is do we want .net (4.0 or 4.5) to be the primary .net version on the windows platform for the next version of monogame.

**Comment by DDReaper** [comment]
The current default on most projects is either .Net 4.5 or 4.6.
I suppose it could still be opened in 2010 if the minimum franework level was lowered, but as 2010 has been out of support for some years now and 2012 is also finished. 2013 will be following quite soon as well.

In my opinion, we should support the latest and 1 previous version really.  Most vendors do the same as far as I'm aware.

**Comment by tomspilman** [comment]
I feel for @stampergames because every once in a while I fire up things in VS2010 just because XNA supports it.

That said supporting 4 versions of Visual Studio is sort of crazy.  It might make sense to stop supporting VS2010 moving forward.  It isn't like there are not newer free versions of VS available to everyone now.

**Comment by tomspilman** [comment]
@hach-que - I guess picking .NET 4.0 for the framework version if only VS2010 is detected isn't a good solution moving forward.

**Comment by hach-que** [comment]
I feel like that would only create more support issues because .NET 4 support would go untested. You can of course change the target profile for platforms using Protobuild properties (it's like FrameworkVersions or something), but I don't want to do any magic for older versions since VS2015 is freely available and superior in every way to the old Express editions.

**Comment by tomspilman** [comment]
> I don't want to do any magic for older versions since VS2015 is freely available and superior in every way to the old Express editions.

Yeah...  there really isn't a great reason to stick to VS2010 other than you just want to.

What is the minimum VS version that supports .NET 4.5?

@dellis1972 @KonajuGames - You guys think we should stop supporting VS2010?

**Comment by hach-que** [comment]
2012 I believe (2013 is 4.5.1 and 2015 is 4.5.2)

**Comment by DDReaper** [comment]
As a small note. In my latest tests for the basic Windows dx project, it wouldn't compile unless I changed the target framework to at least .Net 4.5

Its current default of .net 4 wouldn't compile

**Comment by tomspilman** [comment]
> 2012 I believe 

Great... so we're only talking about dropping VS2010 support which seems reasonable in 2016. ;)

**Comment by nkast** [comment]
Right now we get invalid VS10 solutions. VS Version Selection will open VS10 where none of the projects will load. People with no VS2010 will not see this, Version Selection will open the solution with the next VS version. I have 2013 and 2015 installed as well but it never bothered me that MG open in VS10.
![sln](https://cloud.githubusercontent.com/assets/3018589/12073043/15ba92be-b10f-11e5-96c5-b41a8d06b483.png)

**Comment by hach-que** [comment]
I'm just going to bump up the default Visual Studio version to 2012 for desktop projects, since 4.5 is now the default as well.

**Comment by nkast** [comment]
Setting the framework back to 4.0 would be something like https://github.com/mono/MonoGame/blob/develop/Build/Projects/MonoGame.Framework.definition#L57-L61 , right?

It's not that I want MG to maintain VS210 templates and keep .NET4.0 forever, I am just worried if the move to 4.5  push the next MG release date with all the work and testing required. Why break it if it's not broken?
One idea which I believe would be appreciated by the community is to have a sidenote on the release note and in the roadmap page about the soon to be dropped platforms.

**Comment by hach-que** [comment]
I believe MonoGame is already targeting 4.5 by default (there is some code that now requires 4.5 features as far as I am aware).

It's important to note that Mono is dropping support for anything older than 4.5, and that all previous runtime versions are forced onto 4.5 when running under Mono.  So from a practical standpoint, 4.0 can only ever actually work on Windows going forward because newer Linux distros and Mac will always run at least 4.5.

**Comment by tomspilman** [comment]
> Why break it if it's not broken?

I'd prefer not to change this either, but we've already made the change to support .NET 4.5 by default.  Leaving VS2010 behind was just something we didn't anticipate.

Luckily this is something that the automated build already tests.  It will fail if the generated solutions/projects are not correct after defaulting to VS2012.

**Comment by nkast** [comment]
Fact: Last week I was about to 'complain' about the lack of sync/async and proposing a move to .NET >=4.5! It's the [potentially] breaking changes before a release that makes me a bit worried.

**Comment by hach-que** [comment]
The latest version of Protobuild now generates VS2012 solutions by default.  I haven't submitted a PR here yet though (but updating Protobuild is enough to fix this issue).

**Comment by tomspilman** [comment]
> The latest version of Protobuild now generates VS2012 solutions by default.

Great...  we should get that updated soon.

**Comment by nivan22** [comment]
the generated ,!

**Comment by cra0zy** [comment]
Not a bug anymore.
