### ISSUE TITLE
Update Pipeline Docs

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4384]
We need to update the existing Pipeline tool docs:

https://github.com/mono/MonoGame/blob/develop/Documentation/pipeline.md
https://github.com/mono/MonoGame/blob/develop/Documentation/using_pipeline_tool.md

To reflect the current state of how the Pipeline tool works and is integrated into the VS templates.

For example the tool is no longer new...  it is available on more than just Windows... also we have VS integration now.

**Comment by cra0zy** [comment]
Can I use screenshots from Linux Pipeline?

**Comment by tomspilman** [comment]
> Can I use screenshots from Linux Pipeline? 

Well on this page...

https://github.com/mono/MonoGame/blob/develop/Documentation/pipeline.md

... I don't see a problem adding one screenshot of each platform to give people a look and reinforce that the tool is cross platform.

However on this page...

https://github.com/mono/MonoGame/blob/develop/Documentation/using_pipeline_tool.md

I would prefer we stick to Windows screenshots only as over 90% of our users run the Pipeline tool on Windows.

**Comment by CallumDev** [comment]
Do the documents still need updating? If so I can start working on them and submit a pull request.

**Comment by cra0zy** [comment]
It does, it would be really helpful if you could :+1:

**Comment by mrhelmut** [comment]
That would be very welcome. :)
