### ISSUE TITLE
OpenGL does not implicitly clear the depth buffer like DirectX does, causing random graphics corruption

### ISSUE THREAD

**Issue by hach-que** [MonoGame/MonoGame#4386]
I had a game implemented which just immediately started blitting render targets (using a shader) to the primary back-buffer on each `Draw` run.  This worked absolutely fine under DirectX, but when running under OpenGL (on Mac, Linux or Android), I got seemingly random graphics corruption, like the following (but it could be much worse, with the back-buffer just containing random parts of the desktop):

![image](https://cloud.githubusercontent.com/assets/504826/12111520/1031e684-b3ea-11e5-8c8a-2d9671bd0aa1.png)

This stumped me for ages, before someone suggested that the depth buffer was not being cleared.  In hindsight this makes sense - without the depth buffer being cleared, then OpenGL will leave it containing random garbage until it's written to after the back-buffer is initialized.  But nothing will pass the depth test to write to it because it's never been cleared.

DirectX does this by default and implicitly for you; the original code works fine on Windows.  However, I had to add right at the very start of my Draw loop, code like this:

``` csharp
renderContext.GraphicsDevice.Clear(
    ClearOptions.DepthBuffer, 
    Microsoft.Xna.Framework.Color.Transparent, 
    renderContext.GraphicsDevice.Viewport.MaxDepth,
    0);
```

Once I did that, OpenGL started working across all platforms again:

![image](https://cloud.githubusercontent.com/assets/504826/12111584/8a28e2a8-b3ea-11e5-86eb-606efcd383c9.png)

I believe for correctness sake, and for the purpose of making things work more correctly cross-platform out-of-the-box, MonoGame should implicitly perform this call for the developer.

What I'm not sure yet is whether this is just something we should do after initializing the back-buffer, or whether we need to do every frame.  I'd prefer a solution that was just the former in case the developer does want to preserve the depth buffer across frames (but obviously their game won't work under DirectX in that case).

**Comment by KonajuGames** [comment]
DirectX itself does not implicitly clear any buffers.  And MonoGame should not clear any buffers itself either.  It should always be up to the developer.

With graphics APIs, for efficiency purposes there is no guarantee what is in a buffer at the start of a frame.  Usually it is something from the previous frame or two, but that is simply what happens to be in that memory at that time.

If it is MonoGame code doing a clear of the buffer at the start of a draw in the DirectX builds, it is that code that should be removed.

**Comment by hach-que** [comment]
Yeah that's fine between frames.  What I'm talking about is before the first frame is even rendered.  It seems that when the back buffer is initialized under DirectX, it ensures the depth buffer is in a sane state (set to MaxDepth of the viewport or w/e), whereas under OpenGL it just contains random data.

**Comment by cra0zy** [comment]
I agree with what @hach-que is saying in this. Also I think it should be done on initialization of back buffer.

**Comment by pzgulyas** [comment]
Probably related, but not sure: When porting code from XNA, I had to change the clearing method (at drawing shadowmaps) from
`graphicsDevice.Clear(ClearOptions.DepthBuffer, Color.Transparent, 1, 0)`
to
`graphicsDevice.Clear(ClearOptions.DepthBuffer | ClearOptions.Target, Color.White, 1, 0)`
Seems like the clearing strategy is different in MonoGame to XNA

**Comment by KonajuGames** [comment]
If you're clearing the buffer at the start of each draw, why would you not clear it at the start of the first draw?  That's why the template projects have a call to Clear as the very first thing in the draw.  It is up to the developer to clear the buffer.  You cannot make any assumptions about the contents of the buffer after initialization.

@pzgulyas, what MonoGame platform are you targeting?  Was your code clearing the depth buffer and relying on that to have the color buffer fully rendered (based on depth test passing for all pixels)?

**Comment by pzgulyas** [comment]
@KonajuGames, it is a shadowmap. (Is not my code originally, but) Yes, it seems like it draws into rg channels, and such a clearing was enough. Platform Windows DirectX.

**Comment by tomspilman** [comment]
> Also I think it should be done on initialization of back buffer.

Right...  I think that is reasonable.  While DirectX seems to assure some sane buffer state on first creation I guess OpenGL does not.  

First is there a way that is OpenGL specific to do this initialization?
