### ISSUE TITLE
Screen scaled up on low-end Windows Phone 8.1 devices

### ISSUE THREAD

**Issue by ebatiano** [MonoGame/MonoGame#4402]
On some devices (f.e. Lumia 630) touch positions are scaled up for Y component (portrait) when software button bar is visible.

**Comment by tomspilman** [comment]
@Nezz - You know something about this?

**Comment by ebatiano** [comment]
I should also mention, that on this phone, software buttons never hide, even in fullscreen mode. In portrait mode they cover rendering area (which is also a bug). 

I haven't observed such behavior on other devices.

I checked VisibleBoundsChanged event and unfortunately in portrait mode it still returns 480x800 even if buttons are visible. I guess it all is related...

**Comment by ebatiano** [comment]
After some research there is no problem with touch. There some weird behavior, when buttons are visible, and I've read than on low end phones software buttons are always visible. 
The weird problem is that I have resolution 800x480, and when it is displayed on screen it looks like it was scaled up to 854x480.

**Comment by KakCAT** [comment]
I suppose this is related to https://github.com/mono/MonoGame/issues/3457

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
