### ISSUE TITLE
Crashes on iOS 9 - OpenALSoundController

### ISSUE THREAD

**Issue by ronnycsharp** [MonoGame/MonoGame#4408]
Hi,

my app crashes on iOS 9 devices.
It worked for me after removing a line of code in OpenALSoundController.cs.

```
    private bool OpenSoundController()
    {
```
# if MONOMAC || IOS

```
        //alcMacOSXMixerOutputRate(PREFERRED_MIX_RATE);
```
# endif

...

Regards
Ronny

**Comment by mrhelmut** [comment]
Hi,

This has been fixed in the develop branch (#4103), if can't wait for the next release, I suggest that you switch to the latest development build.
