### ISSUE TITLE
Pipeline tool lists content processors twice

### ISSUE THREAD

**Issue by Helikin** [MonoGame/MonoGame#4424]
I have a .mgcb project that references DLLs with custom content processors. When I load the project in the Pipeline tool the first time, I see one entry for each of my custom processors. When I reload the mgcb project (without closing the Pipeline tool), the custom processors are listed twice:
![image](https://cloud.githubusercontent.com/assets/3626369/12325630/cf414ed8-bacb-11e5-82bb-972723663353.png)

I have found the following cause: [PipelineType.cs](https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Common/PipelineTypes.cs) collects the list of processors in [ResolveAssemblies()](https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Common/PipelineTypes.cs#L398-L438). It first collects all processors of the assemblies which are currently loaded in the AppDomain. Then it collect all processors from the custom content pipeline DLLs referenced in the .mgcb.
This works the first time, but when the project is reloaded, the custom content pipeline DLLs are already loaded in the AppDomain and ResolveAssemblies() will find the same processors in both loops and add them twice.

In my projects this is only a bit irritating but no real problem. But could this be a problem if a user tests several .mgcb projects that use different versions of a custom content processor DLL?

A quick fix would be to just ignore duplicate entries. Ideally, we want to unload custom content processor DLLs before loading the next project. However, I think it is currently not possible in .NET to unload DLLs. I think we can only unload whole AppDomains.

**Comment by tomspilman** [comment]
> A quick fix would be to just ignore duplicate entries.

 I think we should wait and fix it right... we want to allow duplicates to appear so that we can detect issues just like this.

> Ideally, we want to unload custom content processor DLLs before loading the next project.

Right...  this is a known issue.  We intended to eventually address it, so maybe now is the time.

The "right" fix is to only load the pipeline extension assemblies into a separate `AppDomain` which we can unload when the project is closed.  We would then just marshal the property name/value strings across the `AppDomain` boundary.

**Comment by cra0zy** [comment]
This has been fixed.
