### ISSUE TITLE
Reporting issues that are happening in Raining Blobs

### ISSUE THREAD

**Issue by endimilojkoski** [MonoGame/MonoGame#4431]
Hello guys,

here is a list of issues that happened after the Steam release:
1. Game was not working on Arch Linux with MonoGame mono kickstart.
   I got with the player and solved the issue. Since Arch Linux have newer libraries this was the issue:
   libgif.so.4 => not found
   libpng12.so.0 => not found
   And on Arch Linux he had 
   libgif.so.7 and libpng16
   He added the older libs and the game started working!
2. After making it work on Arch Linux, full screen was not working, only very small part of the full screen was showing and the rest was transparent, you could see the desktop. When going in windowed mode it was fine until he reached 1920x1080 window mode resolution.
   Also when playing in windowed mode it is not a real window but a black full screen with the game of the windowed mode resolution size.
3. I have complaint from 2nd player that the game would not start at all on Windows with ATI GPU, still have to investigate this. A while ago one friend could not start the game at all on different ATI GPU PC.
4. Game is not working properly in full screen on 4K monitors and on Mac retina displays. The background is black and the game shows in top left 1/4 of the screen. Switching to windowed mode it works fine. I have added window mode resolutions up to 4K and it works with no issues.

Hope you find this helpful and find a quick solution @cra0zy @mrhelmut @tomspilman 
I will update you as I find more issues or solutions.

Thanks,
Endi

**Comment by cra0zy** [comment]
> Game was not working on Arch Linux with MonoGame mono kickstart.
> I got with the player and solved the issue. Since Arch Linux have newer libraries this was the issue:
> libgif.so.4 => not found
> libpng12.so.0 => not found
> And on Arch Linux he had 
> libgif.so.7 and libpng16
> He added the older libs and the game started working!

Most gdi+ libs for Linux: https://github.com/MonoGame/MonoKickstart/pull/4

@mrhelmut We are missing libpng12.so.0

> After making it work on Arch Linux, full screen was not working, only very small part of the full screen was showing and the rest was transparent, you could see the desktop. When going in windowed mode it was fine until he reached 1920x1080 window mode resolution.
> Also when playing in windowed mode it is not a real window but a black full screen with the game of the windowed mode resolution size.

Ask about what graphics driver and what Desktop Enviorment he is using.

> I have complaint from 2nd player that the game would not start at all on ATI GPU, still have to investigate this. A while ago one friend could not start the game at all on different ATI GPU PC.

Windows, Linux or Mac?

**Comment by endimilojkoski** [comment]
#3: "Windows 7 64-bits and my video board is ATI Radeon HD 7700M Series"

**Comment by mrhelmut** [comment]
I'll add libpng12 to the kickstart PR.

I also have reports of problems with Retina displays. I thought it was #4363 but it seems to still occur. @dellis1972 ?

Don't know what to think about the ATI issue, but my best guess is that the installed driver doesn't support OpenGL 4 (a stack trace would help).

**Comment by mrhelmut** [comment]
libpng12 added.

**Comment by endimilojkoski** [comment]
![macos_retinefullscreen](https://cloud.githubusercontent.com/assets/13436441/12391764/54a68540-bdea-11e5-98da-17f283c91a54.png)

Here is how it looks in full screen on Mac retina.
I am setting full screen size like this:

graphics = new GraphicsDeviceManager(this);
graphics.PreferredBackBufferWidth = GraphicsDevice.DisplayMode.Width;
graphics.PreferredBackBufferHeight = GraphicsDevice.DisplayMode.Height;

How can I help you further on this?
I might get with some of the guys that experience this issue and print the above parameters.

@cra0zy about the Linux question above, he told me he uses Gnome 3 and 1920x1080 display, waiting for more info about his GPU.

**Comment by mrhelmut** [comment]
My best guess is that the Viewport bounds doesn't match the backbuffer size. I have that on my todo but I don't know when exactly I'll be looking at it.

Regarding ATI support, running glxinfo would help knowing if its driver/hardware match the 4.0 requirement.

**Comment by cra0zy** [comment]
> Regarding ATI support, running glxinfo would help knowing if its driver/hardware match the 4.0 requirement.

The error is on Windows, I don't think Windows has glxinfo :P

**Comment by dellis1972** [comment]
MonoGame does not scale stuff automatically for you (unless something changed recently) and XNA never did either afaik. If you design your game to work at 960x540 and then try to run it at 1920x1080 you will need to manage that scaling yourself either with SpriteBatch Scale matrix or via render targets or shaders, a mix of all three. I have a game here that scales using the technique outlined http://www.infinitespace-studios.co.uk/general/monogame-scaling-your-game-using-rendertargets-and-touchpanel/

**Comment by endimilojkoski** [comment]
@mrhelmut  yes, the ATI GPU issue is happening on Windows 7 64-bits, ATI Radeon HD 7700M.

@dellis1972 the game is scaling perfectly fine in all cases and all resolutions. The problem is only with Mac retina and 4K displays.

A friend of mine confirmed that it is working fine on his 2560x1080 monitor. I am taking care of all scaling, centering and black bars.
In windowed mode it runs fine from 480x270 up to 4K!

**Comment by dellis1972** [comment]
@endimilojkoski excellent :) just checking and raising a point incase someone with less experience is reading the thread. 

Can you produce a sample with just the minimum code to replicate the issue? Like @mrhelmut said it might be a Viewport issue.

**Comment by endimilojkoski** [comment]
@dellis1972 it is not a problem for me to send a modified version of the game to someone that is having this issue that will show or log parameters that would benefit to a solution.

What info should I check?
graphics.PreferredBackBufferWidth and GraphicsDevice.DisplayMode.Width ?

**Comment by mrhelmut** [comment]
Check if ```graphics.Viewport``` matches ```graphics.PreferredBackBufferWidth``` / height.

**Comment by endimilojkoski** [comment]
Here are new findings:

#3: I got with the guy with the ATI GPU where the game was crashing. He said he also has issues with emulators that use OpenGL, he can't run games through them. He will try to install some stuff and let me know if it changes anything.
Also worth noting is that his computer also have integrated graphics among the ATI. This is a log file from Steam folders (I am not sure if this was created when I told him to disable ATI GPU):

<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>6.1</WindowsNTVersion>
		<Build>7601 Service Pack 1</Build>
		<Product>(0x30): Windows 7 Professional</Product>
		<Edition>Professional</Edition>
		<BuildString>7601.19110.amd64fre.win7sp1_gdr.151230-0600</BuildString>
		<Revision>1130</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>1046</LCID>
	</OSVersionInformation>
	<ProblemSignatures>
		<EventType>CLR20r3</EventType>
		<Parameter0>RainingBlobs.exe</Parameter0>
		<Parameter1>3.5.0.349</Parameter1>
		<Parameter2>569d724f</Parameter2>
		<Parameter3>OpenTK</Parameter3>
		<Parameter4>1.1.2198.0</Parameter4>
		<Parameter5>568ffc20</Parameter5>
		<Parameter6>34df</Parameter6>
		<Parameter7>e4</Parameter7>
		<Parameter8>OpenTK.Graphics.GraphicsError</Parameter8>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>6.1.7601.2.1.0.256.48</Parameter1>
		<Parameter2>1046</Parameter2>
		<Parameter22>0a9e</Parameter22>
		<Parameter23>0a9e372d3b4ad19135b953a78882e789</Parameter23>
		<Parameter24>0a9e</Parameter24>
		<Parameter25>0a9e372d3b4ad19135b953a78882e789</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>5083C64E-A05C-4C6D-A310-0386D65261DA</MID>
		<SystemManufacturer>Dell Inc.</SystemManufacturer>
		<SystemProductName>Inspiron 7520</SystemProductName>
		<BIOSVersion>A11</BIOSVersion>
	</SystemInformation>
</WERReportMetadata>

**Comment by endimilojkoski** [comment]
Here are new findings:

#3: I got with the guy with the ATI GPU where the game was crashing. He said he also has issues with emulators that use OpenGL, he can't run games through them. He will try to install some stuff and let me know if it changes anything.
Also worth noting is that his computer also have integrated graphics among the ATI. This is a log file from Steam folders (I am not sure if this was created when I told him to disable ATI GPU):

`<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>6.1</WindowsNTVersion>
		<Build>7601 Service Pack 1</Build>
		<Product>(0x30): Windows 7 Professional</Product>
		<Edition>Professional</Edition>
		<BuildString>7601.19110.amd64fre.win7sp1_gdr.151230-0600</BuildString>
		<Revision>1130</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>1046</LCID>
	</OSVersionInformation>
	<ProblemSignatures>
		<EventType>CLR20r3</EventType>
		<Parameter0>RainingBlobs.exe</Parameter0>
		<Parameter1>3.5.0.349</Parameter1>
		<Parameter2>569d724f</Parameter2>
		<Parameter3>OpenTK</Parameter3>
		<Parameter4>1.1.2198.0</Parameter4>
		<Parameter5>568ffc20</Parameter5>
		<Parameter6>34df</Parameter6>
		<Parameter7>e4</Parameter7>
		<Parameter8>OpenTK.Graphics.GraphicsError</Parameter8>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>6.1.7601.2.1.0.256.48</Parameter1>
		<Parameter2>1046</Parameter2>
		<Parameter22>0a9e</Parameter22>
		<Parameter23>0a9e372d3b4ad19135b953a78882e789</Parameter23>
		<Parameter24>0a9e</Parameter24>
		<Parameter25>0a9e372d3b4ad19135b953a78882e789</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>5083C64E-A05C-4C6D-A310-0386D65261DA</MID>
		<SystemManufacturer>Dell Inc.</SystemManufacturer>
		<SystemProductName>Inspiron 7520</SystemProductName>
		<BIOSVersion>A11</BIOSVersion>
	</SystemInformation>
</WERReportMetadata>`

**Comment by endimilojkoski** [comment]
Here is some info on 4K monitor on Win 7 PC:

This is how the game looks like on 4K monitor with resolution of 384x2160:
![rainingblobs_on_4k_win7](https://cloud.githubusercontent.com/assets/13436441/12418222/4f779f9a-beae-11e5-8fd9-767dd6d600ac.jpg)

DM = GraphicsDevice.DisplayMode
VP = GraphicsDevice.Viewport
BB = PreferredBackBuffer{Height/Width}

Note that the actual desktop resolution is 4K and the game is displayed at 2560x1440 in full screen.
Also instead of full screen it shows the taskbar over the game.
Also he said he had strange mouse behaviour where it would go to second monitor even though he was on game monitor.

When he was testing the game in earlier version he had different problem, the game showed up in part of the screen and the rest was black.

**Comment by endimilojkoski** [comment]
Adding one more case from the above testing.
This is how the game looks like when it goes to 4K windowed mode:
![rainingblobs_4k_windowed_win7](https://cloud.githubusercontent.com/assets/13436441/12418462/be1abca6-beaf-11e5-82f1-5ea5fcc2a103.jpg)

And 4K windowed mode was working just fine for him when he tested it a while ago.

I am getting in touch with a guy with Mac retina display and will update you with findings from there.

**Comment by mrhelmut** [comment]
This totally looks to be related to #4398 & #4436.

It's a real mess to get this fixed for all OpenTK backends. It's a bit annoying, but if you would like to go with the safe route, the best workaround is to require a game restart for the resolution / fullscreen state to apply.

**Comment by endimilojkoski** [comment]
I think waiting for the SDL2 version of MonoGame is the safe route! :D

I don't think restart in this case will do any good.
When the game is set to Full Screen and you do a fresh start it detects that the GraphicsDevice.DisplayMode is 2560x1440 and sets the Viewport and Backbuffer to 2560x1440.
But desktop resolution is 3840x2160!

**Comment by mrhelmut** [comment]
You're right about SDL2.

I'm starting to see what's going on. ```GraphicsAdapter.DefaultAdapter.CurrentDisplayMode``` looks off. ```GraphicsAdapter.DefaultAdapter.SupportedDisplayModes```` seems good though.
Most probably related to the retina display issue as well.
I'm also starting to think if this is related to multi-monitor configurations (i.e. ```GraphicsAdapter.DefaultAdapter.CurrentDisplayMode``` is set with values from another monitor).

**Comment by endimilojkoski** [comment]
The values are not coming from the other monitor because the other one is 1920x1080 and the game resolution is set to 2560x1440.

How should I get the value from SupportedDisplayModes?
GraphicsAdapter.DefaultAdapter.SupportedDisplayModes.GetEnumerator().Current returns null fro me.

**Comment by mrhelmut** [comment]
```foreach (DisplayMode displayMode in GraphicsAdapter.DefaultAdapter.SupportedDisplayModes)```

**Comment by endimilojkoski** [comment]
OK, I see there are 20+ items. Do I have to choose the highest resolution form the set?

**Comment by endimilojkoski** [comment]
OK, I got the highest resolution from GraphicsAdapter.DefaultAdapter.SupportedDisplayModes and I got the 4K full screen but the game still acts like it is being displayed on 2560x1440 resolution and actual desktop resolution is 4K:
![rainingblobs_4k_fullscreen_fix_notgood](https://cloud.githubusercontent.com/assets/13436441/12420354/6f13a16a-bebc-11e5-91d9-e1ba222a3ccd.jpg)

**Comment by mrhelmut** [comment]
Could you tell what's in ```graphics.Viewport```?

**Comment by endimilojkoski** [comment]
graphics.Viewport is 2560x1440

**Comment by mrhelmut** [comment]
99% sure it is #4436. But I need to be sure that it works on all backends before resubmitting it.

**Comment by endimilojkoski** [comment]
OK, I am setting the window size in Initialize(), let me try what happens if I do it in Game1().

**Comment by endimilojkoski** [comment]
@mrhelmut thanks for the GraphicsAdapter.DefaultAdapter.SupportedDisplayModes tip, it solved issue on Mac retina displays! :)
Look at it now, same Mac as the above faulty image.
![macretinafixed](https://cloud.githubusercontent.com/assets/13436441/12428945/f07df734-bee7-11e5-8cac-b9f9cc818e09.png)

DM1 is max resolution from GraphicsAdapter.DefaultAdapter.SupportedDisplayModes
DM2 is GraphicsDevice.DisplayMode

**Comment by endimilojkoski** [comment]
About issue #3 with ATI GPU, I got with the guy and solved the problem!

Told him to install this and the game works with no issues:
http://www.guru3d.com/files-details/amd-catalyst-15-11-1-beta-driver-download.html

I am happy to say that all reported issues have been fixed! Thanks guys.

Waiting for SDL2 version to polish last minor inconveniences ;)

**Comment by mrhelmut** [comment]
So you confirm that:
- changing resolution outside of ```Game.ctor``` doesn't work correctly when changing fullscreen as well?
- ```GraphicsDevice.DisplayMode``` doesn't contain the correct desktop resolution?

And you worked around this by iterating through ```GraphicsAdapter.DefaultAdapter.SupportedDisplayModes``` and set the maximum found?

**Comment by endimilojkoski** [comment]
I haven't even tried setting it in Game constructor.
This work whenever you try to change the window resolution or full screen to windowed mode.

This solves Mac retina issue but not Windows 4K issue. For Windows on 4K it makes it worse.

One thing that I have done long time ago that works for me is this:
I noticed that when going from Full screen to Window mode the window size is not correct so I wait 2 frames and set it again and you never notice it has issues :)

I am not sure how I have figured this out but I have no problems changing to full screen and a ton of window mode resolutions in game :)

**Comment by mrhelmut** [comment]
> I noticed that when going from Full screen to Window mode the window size is not correct so I wait 2 frames and set it again and you never notice it has issues :)

Ahah! That's one way to workaround the buggy internal resizing of OpenTK.

**Comment by mrhelmut** [comment]
I took a look at the retina issue. ```GraphicsDeviceManager.Viewport``` is indeed altered by OpenTK, but that's not the only issue. It is related to the HiDPI mode, I need to find out how to disable it in OpenTK, it is apparently a known Cocoa issue with OpenGL viewport.

**Comment by endimilojkoski** [comment]
OK. Just to be clear, the Viewport was not wrong on Mac retina display, DisplayMode was wrong and I was able to make it right by taking it as Max of GraphicsAdapter.DefaultAdapter.SupportedDisplayModes.

Viewport is wrong on WindowsGL on 4K display on Windows 7. I think a while ago the 4K issue in WindowsGL was same as the one on Mac retina but now it is different case.

**Comment by mrhelmut** [comment]
HiDPI can be disabled in the ```OpenTKGamePlatform``` constructor by adding this at the beginning:

```
            Toolkit.Init(new ToolkitOptions
            {
                EnableHighResolution = false
            });
```

Setting the resolution to the max doesn't fix everything in my case, disabling HiDPI does.
4K bug on Windows is another issue which I is too much work considering that OpenTK will be replaced. The best hacky solution I found is to manually recreate Viewport...

**Comment by endimilojkoski** [comment]
I can confirm that "EnableHighResolution = false" does nothing on Windows 7 with 4K monitor and Mac with Retina display, tried both.

One more thing, on Mac retina, when the game is in full screen with the above mentioned fix, if you minimize it, the desktop windows are smaller, like the resolution is higher than it was.

**Comment by Jjagg** [comment]
Closing this because the original issues have been resolved, except some remaining retina issues, but that's tracked in #4802.
