### ISSUE TITLE
Pipeline Tool Issues

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4457]
There are a bunch of issues I noticed when using the MonoGame Pipeline tool on Windows.  Some of this might be Windows specific... some of it might apply the to GTK frontend as well.

 - We should include the open project name in the title bar (see VS).
 - It isn't obvious if a content build is active occurring.
 - We lost the build succeeded/failed message and build time at the end of the output log.
 - The control border around the filter view is different that that around the output view.
 - The output and filter views fights the user set scrollbar position.
 - Text selection in the output view doesn't work correctly.
 - The filter view should have buttons to allow you to filter stuff out... like not showing skipping messages.
 - The 'References' property value should show a `;` separated string of assembly names.
 - Undo/Redo should be visible on the toolbar.
 - Toolbar icons do not update to disabled when a build is triggered.

**Comment by cra0zy** [comment]
> We should include the open project name in the title bar (see VS).

Oh... I totally forgot to implement it for WinForms Pipeline, Gtk had it for half a year... #3912

![title](https://cloud.githubusercontent.com/assets/6773302/12533781/3c742eb8-c23c-11e5-9c68-215065baa77f.png)

> some of it might apply the to GTK frontend as well.

Issues that apply to Gtk:
 - It isn't obvious if a content build is active occurring.
   - In headerbar part it is visible since the last change added changing of build/rebuild, cancel buttons #4418
   - I would like for us to add some sort of progressbar, then for Windows we could also use taskbar progressbar
 - The output and filter views fights the user set scrollbar position.
   - we should add a check to see if it's scrolled to the bottom, if not don't scroll
 - The filter view should have buttons to allow you to filter stuff out... like not showing skipping messages.
   - this should be a separate issue, and we should discuss it in more detail
 - The 'References' property value should show a ; separated string of assembly names.
 - Undo/Redo should be visible on the toolbar.

@nkast Join the fun talk :)

**Comment by cra0zy** [comment]
One more thing, if I could add one more thing to the list, we should add "Open With" option.

**Comment by tomspilman** [comment]
> In headerbar part it is visible since the last change 

Having some buttons change to a disabled state isn't obvious enough.  We really need some sort of explicit animated building graphic.

> I would like for us to add some sort of progressbar

Depends on what we want here.

First thing we can't predict how long a build will take...  one file could take any amount of time and we can't really know how much.  So no matter what the progress bar will be imbalanced.  You could get cases where you shoot up to 99% really quick then sit at 99% for minutes.  Does this make for a good progress information?

The information most people want...  how much longer will this build take... we can't really provide right now.  We would need to gather statistics during processing and use that to make future estimates.  This could be a big feature in itself if we wanted to tackle it.

Really for right now I would settle for some sort of spinner or busy animation while the build is occurring.  Maybe a `1 of X files processed` sort of message could be possible with how the filtering view works now.

This all likely needs its own issue and conversation.

> we should add a check to see if it's scrolled to the bottom, if not don't scroll

Exactly... shouldn't be too hard to make happen, but it is platform specific.

> this should be a separate issue, and we should discuss it in more detail

Done.  https://github.com/mono/MonoGame/issues/4458

**Comment by tomspilman** [comment]
> we should add "Open With" option.

Like on individual content files have an `Open With...` then you select like Photoshop?  As long as on Windows we just shell out to the OS to let the user select.  We shouldn't be building a list ourselves or trying to present our own list.

> we should have separate "Remove" and "Delete" options.

We have to be really careful with that.  One we can undo and the other we can't.  We would have to put a very explicit message and verification before allowing a file to be deleted.

**Comment by cra0zy** [comment]
> Having some buttons change to a disabled state isn't obvious enough. We really need some sort of explicit animated building graphic.

Where would we put it?

**Comment by tomspilman** [comment]
> Where would we put it?

I see a few possibilities:

 - Have the build/rebuild buttons on the toolbar replaced by a build cancel button.
 - Add an animating icon on the empty right side of the toolbar.
 - Add a status bar and place it there... maybe VS like.

**Comment by cra0zy** [comment]
> Have the build/rebuild buttons on the toolbar replaced by a build cancel button.

That is what the headerbar version does. Look at screenshots at: #4418 I though you didn't like that.

Also, just want to show what I've done for the Gtk Pipeline reference property:
![refs](https://cloud.githubusercontent.com/assets/6773302/12534593/28e8e0bc-c261-11e5-9283-5b762ceaf36b.png)

**Comment by tomspilman** [comment]
> I though you didn't like that.

What I don't like is having the Pipeline tool work differently across platforms.  

The docs need to be able to say things like "press the build button on the toolbar" and not have to explain unnecessary platform differences.

> Also, just want to show what I've done for the Gtk Pipeline reference property:

 Looks reasonable.  At least then people will know if it is empty or referencing something.

**Comment by nkast** [comment]
| Text selection in the output view doesn't work correctly.

https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Windows/MainView.cs#L977
That's the problem, 'WordWrapCallback()' is used to wrap text per character, but it's also called upon selection and return wrong results.

**Comment by tomspilman** [comment]
@cra0zy - Another issue that I noticed.

On some games loading the .mgcb file takes a significant time.  It makes the Pipeline tool look frozen for several seconds before the loading completes.

We might want to decide how we want to show that loading is occurring and nothing is locked up.  Not sure how best to do that in a common way across GTK and WinForms.

**Comment by cra0zy** [comment]
> On some games loading the .mgcb file takes a significant time. It makes the Pipeline tool look frozen for several seconds before the loading completes.
> 
> We might want to decide how we want to show that loading is occurring and nothing is locked up. Not sure how best to do that in a common way across GTK and WinForms.

2 things are slowing loading:
1) File Watcher - which I do plan on replacing
2) Load Templates method - this one is more important, look at what it does: https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Common/PipelineController.cs#L942 if the folder is for example "C:\" or "/home/".. that never loads... I think it even crashes?

**Comment by tomspilman** [comment]
> 2 things are slowing loading:

I haven't profiled anything, so I have no clue if the slow loading can be improved or not.

I was opening a .mgcb file with over 2000 content elements in it, so it could be dumb things like the file watcher.  But still I suspect we need some sort of "Loading..." spinner for big content projects.

**Comment by cra0zy** [comment]
> I was opening a .mgcb file with over 2000 content elements in it, so it could be dumb things like the file watcher. But still I suspect we need some sort of "Loading..." spinner for big content projects.

I am fine with adding that. I will submit a separate PR for this.

Can we remove loading templates from .mgcb directory but instead require that templates are placed in "templates/" directory next to .mgcb?

**Comment by tomspilman** [comment]
> Can we remove loading templates from .mgcb directory but instead require that templates are placed in "templates/" directory next to .mgcb?

Not sure I follow what you are asking.

Are you speaking of these templates:

https://github.com/mono/MonoGame/tree/develop/Tools/Pipeline/Templates

?

**Comment by cra0zy** [comment]
@tomspilman I am speaking about https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Common/PipelineController.cs#L934

**Comment by cra0zy** [comment]
> Are you speaking of these templates:
> 
> https://github.com/mono/MonoGame/tree/develop/Tools/Pipeline/Templates

They are those type of templates but not those specific templates.

**Comment by tomspilman** [comment]
> https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Common/PipelineController.cs#L934

Oh... I didn't even know we were doing that.

While it is neat you can put the `.template` file anywhere right now, I don't think it is required to make the feature useful.  I don't have a problem with it looking specifically in some folder.  I am concerned that `templates` is a generic term and it could conflict with something else.

Who ever added that feature will have to chime in here.

**Comment by cra0zy** [comment]
Everything besides the appearance of references in prop grid got fixed.

**Comment by tomspilman** [comment]
@cra0zy - Added a new issue for that and closed this one https://github.com/MonoGame/MonoGame/issues/5210.
