### ISSUE TITLE
Pipeline tool - missing libfreeimage.dylib

### ISSUE THREAD

**Issue by tanis2000** [MonoGame/MonoGame#4473]
The pipeline tool of 3.5 fails at building textures on Mac if you haven't installed freeimage from brew. It would be nice to know which dependencies are needed if they're not delivered with MG.

**Comment by tanis2000** [comment]
As soon as I wrote this it stopped working. I quit the tool, reopened it and now it can't find the libfreeimage.dylib anymore and for some unknown reason the log has turned into the old textual one without the colored icons.. no idea why it's behaving like that.

**Comment by Preprocezzor** [comment]
I have the same problem. I can't import any files via Pipeline.
Did you find out a solution?

**Comment by tanis2000** [comment]
@preprocezzor have you tried installing freeimage through homebrew?

**Comment by Preprocezzor** [comment]
@tanis2000 Yes I did. Still the same error.

**Comment by rvanswieten** [comment]
I am having the same problem in both stable 3.5 as well as development 3.6 versions of Monogame. I have tried the following.

- installing freeimage using homebrew
- changing owner of mgcb command line tool in /usr/local/bin as it is standard installed as root
- running Pipeline.app with root privileges
- copying the libfreeimage files from /usr/local/lib to /Applications/Pipeline.app/Contents/MonoBundle
- copying the libfreeimage files from /usr/local/lib to the Xamarin project directory for my monogame project.
- Plain reinstall of monogame on my mac to make sure it doesn't try to find the proper freeimage libs at install time.

Unfortunately, all this didn't resolve the issue. This wouldn't be much of a problem for me if I would be able to use plain png files for now (setting them as Content, Copy if newer in the file's properties). This used to work in older monogame versions but also does not seem to work anymore.

Does anyone have a workaround. For now, this makes Monogame unusable for my purposes.

**Comment by rvanswieten** [comment]
Update: Installing [the standalone installer for the pipeline tool](http://www.monogame.net/releases/v3.5.1/Pipeline.MacOS.pkg) worked for me.

**Comment by Preprocezzor** [comment]
Worked for me too. Thank you so much @rvanswieten

**Comment by cra0zy** [comment]
This got fixed.
