### ISSUE TITLE
Vsync doesn't work on monogame 3.5 windowed applications [DesktopGL, Mac]

### ISSUE THREAD

**Issue by VinnieH01** [MonoGame/MonoGame#4550]
I started a new DesktopGL project on my mac and I wanted to check fps so I did 
`Console.WriteLine(1 / deltaTime);`

Ive got fixed timestep set to false and Vsync to true : 

`IsFixedTimeStep = false;`
`graphics.SynchronizeWithVerticalRetrace = true;`

This is the result as you can see everything was fine at the start but after a while the vsync just turned off and the fps went from 60 to about 8000.

59,78537
60,89207
58,88935
61,0978
59,49902
59,67548
58,36723
57,99118
64,98697
58,53396
60,98528
55,6796
64,1153
58,10474
59,3789
44,62513
****4345,937
7639,419
7457,122
7407,408
8250,825
8628,128
8968,61
10131,71
9871,668
10298,66...****

**Comment by tomspilman** [comment]
> everything was fine at the start but after a while the vsync just turned off 

So the bug you're reporting is that the vsync turned off without you changing it?

**Comment by VinnieH01** [comment]
@tomspilman Maybe I'm not really sure it was at around 60 fps for a very short period of time so it might just be the application being slow when it's starting. Anyway what I'm trying to say is that vsync dosent work.

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy @mrhelmut - I assume that vsync is implemented under OpenGL....  correct?

**Comment by VinnieH01** [comment]
@tomspilman Something weird happened, after restarting my computer it worked for some reason.

**Comment by VinnieH01** [comment]
@tomspilman forget what I just said it just took a longer while for it to go from 60 to 5000 (probably about 5 sec) so Vsync is defiantly just turning off for some reason.

**Comment by VinnieH01** [comment]
Not sure but it might be some of these scripts https://github.com/mono/MonoGame/tree/develop/MonoGame.Framework/Desktop

**Comment by mrhelmut** [comment]
The default OpenTK behavior regarding that is to use adaptive-vsync (when the OpenGL extension is available), so that irregular framerate may totally be normal.
If you would like to force MonoGame to use the standard vsync, you'll have to set the ```PresentationParameters.PresentInterval``` to ```PresentInterval.One``` instead of ```PresentInterval.Default``` and call ```GraphicsDeviceManager.ApplyChanges()```.

If there are still fluctuations after this, then it's an issue.

**Comment by VinnieH01** [comment]
@mrhelmut so is there a way to fix this?

**Comment by VinnieH01** [comment]
@mrhelmut I still don't understand how getting 10000 fps on a 60hz monitor can be normal?

**Comment by VinnieH01** [comment]
@dellis1972 can you test this on your computer when you have time to see if this happens to all mac users or if its just me?

**Comment by mrhelmut** [comment]
If you happen to have a minimal working example, I'll try to take a look at it.

**Comment by VinnieH01** [comment]
@mrhelmut ok sure wait a second

**Comment by VinnieH01** [comment]
@mrhelmut 
[Test.zip](https://github.com/mono/MonoGame/files/138806/Test.zip)

**Comment by VinnieH01** [comment]
@mrhelmut That one is made for DesktopGL with Xamarin Studio so if you use visual studio I don't know if you can open it

**Comment by mrhelmut** [comment]
Thanks.
I can't reproduce it on any platform. I believe it's simply a problem with how you calculated the framerate. See: https://github.com/CartBlanche/MonoGame-Samples/blob/master/CollisionSample/FrameRateCounter.cs

**Comment by VinnieH01** [comment]
@mrhelmut I'm 100% sure that i dont calculate the framerate wrong if i just print the deltatime I cab clearly see that the fps is way to high. Can you see if @dellis1972 can take a look because he's got a mac.

**Comment by VinnieH01** [comment]
The deltaTime is about 0,000125

**Comment by VinnieH01** [comment]
@mrhelmut if you use a Mac and do Console.Writeline(1/gameTime.elapsedTime.totalSeconds); and the wait a while, are you sure it dosent show a very high number?

**Comment by VinnieH01** [comment]
@mrhelmut (On a DesktopGL project with the newest 3.5 dev build)

**Comment by VinnieH01** [comment]
@mrhelmut If you think it can help I will post my build log when I come home.

**Comment by VinnieH01** [comment]
@dellis1972 Can you please test this, I feel that vsync not working is a pretty serious issue.

**Comment by VinnieH01** [comment]
@dellis1972 @mrhelmut @cra0zy @tomspilman Here's the build log : https://gist.github.com/VinnieH01/823f970f3de3ba87158d

**Comment by VinnieH01** [comment]
@dellis1972 @mrhelmut @cra0zy @tomspilman Ive found the issue Vsync dosent work on windowed applications only on fullscreen!

**Comment by VinnieH01** [comment]
@dellis1972 @mrhelmut @cra0zy @tomspilman When I set the resolution to 1920 * 1080 but still play in windowed vsync works.

**Comment by VinnieH01** [comment]
@dellis1972 @mrhelmut @cra0zy @tomspilman Will this be fixed when you make your own OpenGL binding and remove OpenTK? I think this is a very weird behavior because as long as the window takes up the whole screen (1920 * 1080) it works but if I for example minimize it or have a window that is 500 * 500 the fps is about 10,000. You sure this isn't worth looking into?

**Comment by VinnieH01** [comment]
@dellis1972 @mrhelmut @cra0zy @tomspilman bump

**Comment by dellis1972** [comment]
@VinnieH01 To be honest I would expect Vsync to NOT work on windowed apps.. the reason being there are potentially a load of apps showing at the same time. The GPU is a shared resource, messing around with Vsync might effect other apps. To me is makes sense it only works in full screen. 

See [this search](http://www.bing.com/search?q=VSync+doesn%27t+work+in+windowed+mode&go=Submit&qs=n&form=QBLH&pq=vsync+doesn%27t+work+in+windowed+mode&sc=0-0&sp=-1&sk=&cvid=70056D170DDD4E02B0FE14222A0D7100)

Also you are calculating your FPS wrong. Please look at the FPSComponent linked by @mrhelmut earlier. When using that you will see a consistent 60 fps.
