### ISSUE TITLE
The Xamarin Studio Roslyn Preview makes MonoGame unusable.

### ISSUE THREAD

**Issue by 0916174** [MonoGame/MonoGame#4583]
When downloading the latest development version of MonoGame, it checks for MonoDevelop.Core v5.0 and MonoDevelop.Ide v5.0, but I use the [Preview Release: Xamarin Studio 6.0 with Roslyn Support](https://forums.xamarin.com/discussion/53121/preview-release-xamarin-studio-6-0-with-roslyn-support), which uses MonoDevelop.Core v6.0 and MonoDevelop.Ide v5.0. [This is my Add-in Manager.](http://imgur.com/B3etDsG)
I don't want to install 2 instances of Xamarin Studio just for developing XNA.
Is there a solution to this?

Thanks in advance.

**Comment by KonajuGames** [comment]
You could rebuild the plug-in after modifying the required field in the source (https://github.com/mono/MonoGame/blob/develop/IDE/MonoDevelop/MonoDevelop.MonoGame/MonoDevelop.MonoGame.addin.xml#L77).  We can't feasibly support a preview release and the current stable release simultaneously.

**Comment by 0916174** [comment]
Thanks! I don't have experience with this but I'll think I'll do fine.

**Comment by 0916174** [comment]
Update: I don't know how to move on. I have no experience or knowledge of developing add-ins. Up until now I've only made simple C# and Python applications and games. Can somebody help me out here?

**Comment by KonajuGames** [comment]
@dellis1972 is the plug-in master here.  Any tips?

**Comment by dellis1972** [comment]
@0916174 the Addin needs to be rebuilt against 6.0 

I can probably put a custom build in the Alpha channel of XS at the moment for you. but we cannot officially bump it until 6.0 goes stable.

**Comment by 0916174** [comment]
That would be awesome! Then I would still keep XS 6.0, and a download will be available in the Add-in Manager, right?

**Comment by dellis1972** [comment]
Correct. You will still NEED to install the latest development build from the monogame site. But you should be able to update the Addin via XS afterwards.

I'll post here once its been uploaded. (might take a few hours though)

**Comment by 0916174** [comment]
Already installed the latest MonoGame Development Build from the website.

Thanks a bunch. Awesome support. Looking forward to your reply.

**Comment by cra0zy** [comment]
I started using MD 6 on Linux so this will come in handy to me as well :D

**Comment by dellis1972** [comment]
Just posted it on the Addin's Alpha Channel, should be up in an hour or two. 
Let me know if you have problems on the following PR https://github.com/mono/MonoGame/pull/4584 so we can keep track.

**Comment by cra0zy** [comment]
The addin is not installable :(

MSBuildExtensions, ProjectBindings and ProjectBindings.MonoGame are not extension points / defined.

**Comment by dellis1972** [comment]
Dang.. that means they completely changed the project system on us.
I'll have to chat with the Xamarin Studio team and find out what changed

**Comment by dellis1972** [comment]
Looks like this is going to be a much larger job :(

**Comment by LithiumToast** [comment]
I downloaded and installed the latest Mac package of MonoGame. I'm seeing this in Xamarin Studio 6.0

<img width="1436" alt="screen shot 2016-02-29 at 7 34 06 pm" src="https://cloud.githubusercontent.com/assets/519592/13416932/74ca2cc6-df1b-11e5-9ac7-c01320aeeaee.png">

Looking at Xamarin's website and creating a new empty add in using Xamarin Studio 6.0 it seems that [MonoDevelop.AddinMaker](https://github.com/mhutch/MonoDevelop.AddinMaker) is the recommended way to build addins.

**Comment by cra0zy** [comment]
@LithiumToast You have to use the addin from: #4584, tho it still wont fully load.

**Comment by dellis1972** [comment]
@LithiumToast I'm aware of AddinMaker, I'd rather not take the dependency on it at this time though. Plus the stuff we do in the addin is kinda advanced (Injecting stuff into the csproj), AddinMaker is generally for helping provide basic templates.

**Comment by LithiumToast** [comment]
I made the changes to my local clone from #4584. How do I build the addin for Xamarin Studio? Doesn't Xamarin Studio only accept .mpack files for addins?

**Comment by dellis1972** [comment]
Pushed a few more changes to #4584 and published new build (1574) to Alpha channel.

**Comment by 0916174** [comment]
I have the latest MonoGame installed, but I don't see anything in the alpha repository except for VSBindingsOnMac. Is this correct?

**Comment by cra0zy** [comment]
Get the addin from: http://addins.monodevelop.com/Project/Index/47

**Comment by 0916174** [comment]
Installing the provided addin resulted in a extension point error. [Screenshot.](https://www.dropbox.com/s/j8wxih4xk1ennxo/Schermafdruk%202016-03-06%2022.30.50.png?dl=0)
@dellis1972 @KonajuGames Can you give me any information on what your addin or XS team will be doing with this bug/info? I'll stick to using Visual Studio by dual-booting to Windows for now, but I'd like to be updated whenever progress has been made regarding this bug.

**Comment by cra0zy** [comment]
> Installing the provided addin resulted in an extension point error. Screenshot.
> @dellis1972 @KonajuGames Can you give me any information on what your addin or XS team will be doing with this bug/info? I'll stick to using Visual Studio by dual-booting to Windows for now, but I'd like to be updated whenever progress has been made regarding this issue.

Update Xamarin Studio, you are probably on an older version. The addin works for me on Windows and Linux.

**Comment by dellis1972** [comment]
@0916174 just so you know we CANNOT merge the PR which is dealing with this issue until Xamarin Studio 6 goes into stable. This is because we need to upgrade our build system and if we upgrade to XS6 that will break everyone who is not using the Alpha version. 

For you you need to keep and eye on PR #4584. Changes will be made there, as I rebase on develop I will publish a new addin on addins.monodevelop.com. 

On a side note that error has nothing to do with our Addin as far as I can see, that is the Mac Addin from Xamarin. You will have to expect issues as XS6 is in Alpha, which means it has NOT gone through complete QA testing. If you want a stable experience downgrade to XS 5.10 on the stable channel.

**Comment by dellis1972** [comment]
new addin for Mac available at http://addins.monodevelop.com/Alpha/Mac/6.0.0/MonoDevelop.MonoGame-3.5.0.1610.mpack

**Comment by 0916174** [comment]
@dellis1972 Hi there.
I've just now gone back to programming on Mac and saw that addin (3.5.0.1610) but the link is dead, because nothing happens when I go there. Also, I can't see MonoGame in the Alphachannel of Xamarin 6 yet. Is there a working version yet, or has it been taken down?

Thanks ;)

**Comment by cra0zy** [comment]
http://addins.monodevelop.com/Project/Index/47

**Comment by dellis1972** [comment]
I have no idea why the addin does not appear in the addin channel. I noticed that myself.
In the mean time you can download the mpack from the link @cra0zy provided.

**Comment by 0916174** [comment]
Thank you for the support @cra0zy.
However, I still get an error while trying to install the add-in from the provided website (the MonoGame Alpha Channel add-in for Mac).
<img width="1524" alt="schermafdruk 2016-06-20 14 05 44" src="https://cloud.githubusercontent.com/assets/14292245/16194050/d6e72bb4-36f2-11e6-9583-9dee1c31d149.png">

**Comment by dellis1972** [comment]
Latest working Xamarin Studio 6 Addin for 3.5 

http://addins.monodevelop.com/Beta/Mac/6.1/MonoDevelop.MonoGame-3.5.0.1671.mpack

**Comment by jlandrum** [comment]
The 6.1 plugin loads, but it doesn't seem to want to compile for Mac - it's generating an EXE but no Mac binaries. Possibly because MonoMac vs Xamarin.Mac differences?

**Comment by cra0zy** [comment]
@tomspilman This is fixed.
