### ISSUE TITLE
Add ImageMagick processor so some other image types can be processed

### ISSUE THREAD

**Issue by harry-cpp** [MonoGame/MonoGame#4594]
I wanted to talk about this for a while, but always seemed to forget. How about we start using "ImageMagick" for reading images for content Pipeline.

Why? Supported formats for one, which include both Gimp(XCF) and Photoshop(PSD) formats:
http://www.imagemagick.org/script/formats.php

It also has a .NET wrapper: https://magick.codeplex.com/

Worst case scenario if we can't actually use it as a replacement for our current method, we could still make it convert the file to some known format for us. I've only ever used it as a linux terminal command.

CC. @tomspilman @KonajuGames @dellis1972

**Comment by KonajuGames** [comment]
The beauty of the content pipeline is that it can be easily extended.  There is nothing stopping anyone from adding a third-party content importer that uses ImageMagick to read images into a TextureContent instance (the "known format" that the content pipeline uses).

**Comment by tomspilman** [comment]
Well FreeImage supports PSD as well...   but it doesn't support XCF.

We should stick with FreeImage unless there is some really compelling reason to switch.

**Comment by cra0zy** [comment]
> Well FreeImage supports PSD as well...

Didn't realize that O o.

> but it doesn't support XCF.

Thats what I didn't like, and how this idea came to be.

> We should stick with FreeImage unless there is some really compelling reason to switch.

How about I add another importer specifically for XCF that uses imagemagick?

**Comment by tomspilman** [comment]
I really hate the idea of burdening things with yet another library dependency.

However if it can be done simply and we back up this new XCF/PSD importer with unit tests verifying it works...  I could agree to it.

@dellis1972 @KonajuGames ?

**Comment by KonajuGames** [comment]
There is always a risk in changing something that is currently working.
This would add one source image format that I believe is used very little,
if at all, for direct import to a game asset system.  The value added by
this is quite small I believe.

It would need ImageMagick built as 64-bit dynamic/shared libraries for
Windows, Mac and Linux. The C# bindings would need to be checked on all
three platforms, and the TextureImporter class would need to be rewritten
to use ImageMagick.

I don't know what the license is for ImageMagick, so I can't comment on
anything about that.

**Comment by tomspilman** [comment]
@KonajuGames - Yeah... not suggesting replacement of what we have now. But I meant as a new importer specifically for PSD/XCF only.  So it wouldn't change what we got.

That said...  if we had good unit tests on the importers we could easily swap and see if it is better or not.  At least then we feel like we didn't make anything worse.

So any suggestion of replacing FreeImage with anything else would require we flesh out all the unit tests first before we make any changes.

**Comment by KonajuGames** [comment]
Implemented as an additional importer for those formats would be a
preferred first step. Being a native library it is still a bunch of work
and testing across all three desktop platforms.

**Comment by ambs** [comment]
Although it "would be nice" I think it would be easier to add a plugin to gimp to save as xnb than to add support to most image formats into the pipeline.

**Comment by cra0zy** [comment]
> Although it "would be nice" I think it would be easier to add a plugin to gimp to save as xnb than to add support to most image formats into the pipeline.

No... that would defeat the purpose of this, and would be much much harder to do....

**Comment by tomspilman** [comment]
FYI.   https://github.com/mono/MonoGame/issues/4600

**Comment by cra0zy** [comment]
@tomspilman Can't you leave this open? I still plan on implementing this when I have enough time.
