### ISSUE TITLE
Is there any reason why Buttons doesn't contain Buttons.None?

### ISSUE THREAD

**Issue by BaseCrosser** [MonoGame/MonoGame#4617]
As the title says, is there any reason why there is no Buttons.None in MonoGame?

Greetings,
BaseCrosser

**Comment by tomspilman** [comment]
I suspect because there wasn't a `Buttons.None` in XNA:

https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.input.buttons.aspx

But I don't see harm in adding one.

**Comment by BaseCrosser** [comment]
I created a PR for it.

**Comment by daglundberg** [comment]
The pull request was closed after discussion: https://github.com/MonoGame/MonoGame/pull/4618

Does that mean this can be closed too or no?

Best

**Comment by BaseCrosser** [comment]
I will close this now
