### ISSUE TITLE
Can't load a new MonoGame Windows 10 UAP Project

### ISSUE THREAD

**Issue by wokawaka** [MonoGame/MonoGame#4619]
I have VS 2015 Update 1 on a brand new Windows 10 machine with the latest Monogame 3.4 installed.

When I try to create a new MonoGame Windows 10 UAP Project I get prompted with a message saying that I dont have the right SDK version (this error: https://msdn.microsoft.com/en-us/windows/uwp/porting/update-your-visual-studio-2015-rc-project-to-rtm).

Reading on forums it seems that its these two lines that are wrong in the csproj file:
    TargetPlatformVersion 10.0.10069.0 TargetPlatformVersion
    TargetPlatformMinVersion 10.0.10069.0 TargetPlatformMinVersion

Updating these to 10.0.10586.0 makes me able to load the project but I am then stuck with 197 errors waiting to be fixed.

Is this a bug in monogame, or something I have done wrong? I'm sitting here with a Lumia 950 and want to get coding :)

**Comment by Tzenchor** [comment]
It is solved with the current version. Uninstall your current version, and download the development build for Visual Studio
