### ISSUE TITLE
Windows UAP template is using an outdated SharpDX version

### ISSUE THREAD

**Issue by Tzenchor** [MonoGame/MonoGame#4623]
I have noticed that the SharpDX libraries for Windows UAP are from the alpha release while there's a stable version since Christmas.

Would you like to update them for 3.5, or left that for a later version?

**Comment by tomspilman** [comment]
I think we can wait...  they have been working fine so far.  I worry changing them without getting any testing on it will cause issues with some of the UWP platforms.

**Comment by Jjagg** [comment]
Resolved in #5825, #5949 and #6010.
