### ISSUE TITLE
[Mac][3.5] Mouse events are sent no matter where the mouse is (even if far outside the window)

### ISSUE THREAD

**Issue by prime31** [MonoGame/MonoGame#4644]
Mouse events are registering even when the mouse cursor is hundreds of pixels outside the window. This includes when the mouse is interacting with the window title bar. The expected behavior would be to not pass mouse input to the window if it doesnt occur in the windows bounds.

**Comment by KonajuGames** [comment]
If the game window is active, polling for the mouse state returns the mouse
position wherever it may be, including outside the window bounds. This is
expected behaviour, and we even made a fix for this just before 3.5 was
released for the SDL2 backend.  If your code is not interested in mouse
movement outside the window while your game is active, you can check the
mouse position against the window bounds and ignore any positions that fall
outside the bounds.

**Comment by prime31** [comment]
I suppose that works as long as it is expected. I've personally never seen an SDL using engine pass mouse data when it isnt relevant (inside the games window) but if that was the agreed upon behavior feel free to close.

**Comment by prime31** [comment]
So, as I think about this more I can't come up with a single reason why mouse data should make it back to MonoGame when a click occurs in the titlebar. It's pretty silly that every person that uses MG will have to code the same exact FSM:

- got mouse down lets see where it is
- it's in the title bar. Let's set a flag to ignore the mouse completely until it's done.
- overwrite mouse state every frame waiting for mouse button to be released and title bar drag to be over
- mouse is released so let's under the flag and go back to using mouse input again

Is there a single use case where we would want clicks in the title bar to be handled by the game itself?

Has anyone tried dealing with this whole making a game and enjoyed it better than the previous way? In just a couple hours it's already driving me nuts.
What do you think @tomspilman?

**Comment by KonajuGames** [comment]
I didn't realise you meant mouse button clicks.  Clicks on the menu bar should not be passed through the Mouse.GetState().  I agree with that.  We'll have to work out a way to stop that.  Mouse moves outside the window while the window is active are correct and should be reported.  Mouse button clicks should not, even though the menu bar is likely considered part of the window according to OS X.

**Comment by harry-cpp** [comment]
This is actually normal, its how XNA worked.
