### ISSUE TITLE
[Mac][3.5] Mouse state is not updated if a mouse button is pressed

### ISSUE THREAD

**Issue by prime31** [MonoGame/MonoGame#4646]
Steps to reproduce:
- add the following code to Update
- wiggle your mouse around and notice the logs getting printed
- click the left mouse button and do the same wiggle and notice that their will be no logs until the mouse button is lifted

```
_previousMouseState = _currentMouseState;
_currentMouseState = Microsoft.Xna.Framework.Input.Mouse.GetState();

if( _previousMouseState.X != _currentMouseState.X )
    Debug.WriteLine( "past: {0}, curr: {1}", _previousMouseState.X, _currentMouseState.X );
```

**Comment by prime31** [comment]
I just want to note that this bug does not exist when SDL is used.

**Comment by mrhelmut** [comment]
Happens with SDL2 too (#4529). I thought it was an SDL2-only bug, I haven't investigated it yet, but what I know is that after a click, there are no event coming at all (checked directly on SDL_PumpEvents / SDL_PollEvent) for about 500ms.

**Comment by prime31** [comment]
@mrhelmut I can't repro this when using SDL on a retina Mac. I can click-and-drag and mouse coordinates are updated. When SDL is not used it happens for me. Haven't tested on Windows yet so I can't say what the deal is over there.

**Comment by mgatland** [comment]
I just started using Monogame today and hit this bug. In case any other newbies end up here too, here's how I worked around it in my game:

```C#
// had to add references to System.Windows.Forms and System.Drawing
//Pos mouseCoords = Mouse.GetPosition(window);
var cursorPosition = System.Windows.Forms.Cursor.Position;
Pos windowPos = new Pos(game.Window.ClientBounds.X, game.Window.ClientBounds.Y);
Pos mouseCoords = new Pos(cursorPosition.X - windowPos.X, cursorPosition.Y - windowPos.Y);
```

**Comment by mrhelmut** [comment]
@mgatland Are you working from the latest source? Since the switch to SDL2, I don't have this issue anymore.

If you're considering running your app on OS X or Linux, referencing ```System.Windows.Forms``` and ```System.Drawing``` should be avoided at all cost because you would be running into a total dependency mess due to GDI+.

**Comment by mgatland** [comment]
I'm using the 3.5 release for now. Thanks for the warning

**Comment by Jjagg** [comment]
Fixed with SDL backend.
