### ISSUE TITLE
Project template flag to exclude beginner comments

### ISSUE THREAD

**Issue by InfiniteProductions** [MonoGame/MonoGame#4659]
Or add an option in the installer for:

-templates as they are (beginner)
-templates without all the comments (advanced user)
- or simply remove all comments in template files (may not be good for new user unfortunately)

I usually create a new project and waste time removing all those comments I no longer find helpful.

So if I'm not the only one doing this way, this may save a little time for others, without having to modify templates on each release or after each update from dev snapshot.

**Comment by harry-cpp** [comment]
Templates no longer have any comments by default.
