### ISSUE TITLE
Apple tvOS Support

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4671]
It seems like we added the code support for tvOS in https://github.com/mono/MonoGame/pull/4240.

This issue is to track what else remains to officially declare it as a supported platform.

**Comment by tanis2000** [comment]
Xamarin hasn't yet enabled tvOS support in the stable channel.

**Comment by tomspilman** [comment]
@dellis1972 @CartBlanche - Any clue what the timeline for this is?

**Comment by tomspilman** [comment]
@dellis1972 - Is this working now?

**Comment by Romans-I-XVI** [comment]
Is there a reason tvOS still isn't officially added?

**Comment by paulocoutinhox** [comment]
I'm still looking for a good game framework with official Apple TV support, and it's really disappointing to see that MonoGame had tvOS support in the past but removed it later.

Apple TV is still a valid gaming platform, and modern .NET already provides official tvOS targets, so I think it would be great if MonoGame officially brought tvOS support back.

Please consider restoring and officially supporting tvOS again. I would definitely use MonoGame for my project if Apple TV were an officially supported platform.
