### ISSUE TITLE
SwapChainRenderTarget for UWP

### ISSUE THREAD

**Issue by Helikin** [MonoGame/MonoGame#4674]
MonoGame already has a SwapChainRenderTarget class for Windows (desktop) and DirectX. We have extended this class to support UWP (Windows Universal) as well. 

You can view our changes here: https://github.com/DigitalRune/MonoGame/commit/a156710abf5f7cff070aa59ef601db27f8b77f9d
This commit also adds a SwapChainRenderTarget.Resize method for desktop and UWP.

We use the SwapChainRenderTarget to render graphics into UWP [SwapChainPanel](https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.swapchainpanel) XAML controls in regular UWP apps, for example: [UwpInteropSample (screenshot)](https://www.digitalrune.com/Portals/0/Blog/Files/12/2013/6ac1140b-273a-4157-8c33-193387e41b6a.jpg)
So far I have tested this in 3 UWP projects.

Currently I do not have the time to create pull request, but if there are no objection to these modifications I can create a PR in the next weeks.

**Comment by tomspilman** [comment]
I'll take a closer look at this.

My first impression is we need to work out a common API and partial class this thing...  but it could be that could wait for a OpenGL implementation that requires that cleanup.

**Comment by Helikin** [comment]
If we switch to a newer SharpDX version for desktop, we can merge the DirectX code paths for desktop and UWP. At the moment they diverge because SharpDX 2.6.3 does not contain the SwapChain1 class, which is needed for UWP.

**Comment by tomspilman** [comment]
@Helikin - https://github.com/mono/MonoGame/issues/3794

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
