### ISSUE TITLE
NuGet Cleanup

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4687]
We have a lot of old and maybe obsolete NuGet packages.

Like shouldn't these be depreciated?
- ~~https://www.nuget.org/packages/MonoGame.Framework.Linux/~~
- https://www.nuget.org/packages/MonoGame.Framework.MacOS/
- ~~https://www.nuget.org/packages/MonoGame.Framework.WindowsGL/~~

Also are these projects dead?  They are all for the 3.2 release.
- https://www.nuget.org/packages/MonoGame.Framework.Portable/
- https://www.nuget.org/packages/MonoGame.Framework.Content.Pipeline.Portable/

Finally we replaced this one with `MonoGame.Framework.WindowsUniversal`:
- ~~https://www.nuget.org/packages/MonoGame.Framework.WindowsUAP/~~

What is the best way to fix these and steer users towards the correct new packages?

**Comment by tomspilman** [comment]
@DDReaper - Any suggestions for how to deal with this?

**Comment by tomspilman** [comment]
Ok I unlisted `MonoGame.Framework.WindowsUAP` as it really shouldn't be used anymore.

Waiting to get feedback on the rest of it.

**Comment by dellis1972** [comment]
The PCL/Portable packages should be updated I use those allot for pipeline extensions. 

MacOS is used by MonoMac.. When we kill MonoMac support we can kill that package. People should be using the DesktopGL really now, and the Xam Mac stuff uses DesktopGL since 3.5

**Comment by cra0zy** [comment]
Linux and WindowsGL should get removed.

**Comment by tomspilman** [comment]
@cra0zy - Ok...  i'll hide those packages on the NuGet site immediately.  We will need a separate PR to remove the nuget files for those from the repo.

**Comment by WardBenjamin** [comment]
@tomspilman refer to https://github.com/mono/MonoGame/issues/3405 and https://github.com/mono/MonoGame/issues/3944 for information on the .Portable (PCL) packages. I'd still like to get those updated.

**Comment by tomspilman** [comment]
@WardBenjamin - I've replaced both those issues with https://github.com/mono/MonoGame/issues/4689 which actually calls out what needs to be done.

**Comment by tomspilman** [comment]
So how does anyone know that for example that the DesktopGL nuget...

https://www.nuget.org/packages/MonoGame.Framework.DesktopGL/

... is meant to be used with Windows, Mac, and Linux desktops?  There is nothing in the description or information on that site that says that.

Should we fix the nuget descriptions to include information about what the specific package is and what it is for?

**Comment by DDReaper** [comment]
In the MonoGame.Samples project, that NuGet is predominately for the WIndows desktop GL platform.  This is based off the Windows Desktop GL project in the MG framework source

**Comment by craftworkgames** [comment]
My feeling is that you've got 2 conflicting problems.

1. Having old packages visible could be confusing for new users (i.e which one to choose)
2. There could potentially be lots of projects using those old NuGet packages and upgrading them to DesktopGL is not something the developer wants to do.

The first problem is real, not everyone knows the history of MonoGame and that they shouldn't be using the WindowsDX version anymore (for example). That said, once they learn a little bit about the differences between the packages and how MonoGame is versioned it's easy to figure out which package to use.

The second problem is a pretty good reason to keep old packages on NuGet. That's one of the big benefits of using NuGet packages in the first place. You can be confident your project will still build years down the track.

So, I'm in favor of hiding them, but not removing them.

**Comment by tomspilman** [comment]
> So, I'm in favor of hiding them, but not removing them.

Agreed.  But a little concerned hiding them would break people in some way...  am I just being paranoid?  Is it totally safe to hide a NuGet package?

**Comment by WardBenjamin** [comment]
Yep, it's totally safe to hide it. Old projects that reference it will still see it, but new projects will be forced to the new packages.

**Comment by DDReaper** [comment]
Agreed. Hiding only prevents the  package showing up in searches.
Projects that reference it still  work(and still  show upgrades for the newer version with the same package I'd) or by calling the specific version using the versioned package I'd.

Removing should never be used except in extreme circumstances.

With this clean up,  I guess the monogame.samples project will need a slight refresh

**Comment by tomspilman** [comment]
Thanks @DDReaper & @WardBenjamin .  I've hidden the old WindowsGL and Linux packages.

**Comment by DDReaper** [comment]
+1 @tomspilman 
have you also hidden the (now unsupported) Windows Phone templates as well?  Or do they need more investigation?

**Comment by tomspilman** [comment]
> have you also hidden the (now unsupported) Windows Phone templates as well?

If you mean the project templates in the SDK installer...  you removed that in your PR.

If you mean the Windows Phone NuGet package...  that is still up and visible with the 3.5 version available.  I think I want to leave it up until 3.7 is released in a few months.
