### ISSUE TITLE
NuGet Packages for the Pipeline

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4688]
Can we and should we provide a NuGet package for the `MonoGame.Framework.Content.Pipeline` assemblies?

Could we provide one assembly that works across Windows/Mac/Linux?

**Comment by tomspilman** [comment]
@cra0zy @dellis1972 @DDReaper

**Comment by dellis1972** [comment]
@tomspilman there is already a "alpha" PCL Pipeline package which is what we should really use. That will work on all the platforms. There is no need to "ship" it with the pipeline extension that a user creates as the Pipeline tool provides the platform specific one.  Someone just needs to regenerate it using the Phiraha tool and check it has all the required API entry points.

That said we can "possibly" get away with using the Linux one across all the platforms.. maybe.

**Comment by tomspilman** [comment]
> There is no need to "ship" it with the pipeline extension that a user creates as the Pipeline tool provides the platform specific one.

Oh... interesting.  We sort of designed for PCL in the pipeline and didn't realize it.

But what if someone includes the PCL in their executable and expects things to run.  Does NuGet have features for doing the bait-and-switch?  Or do we also have to provide platform specific builds as separate NuGets too?


> Someone just needs to regenerate it using the Phiraha tool and check it has all the required API entry points.

Is this something we could automate into the build process?


> That said we can "possibly" get away with using the Linux one across all the platforms.. maybe.

Likely not... as we explicitly skip some features (like effect compiling) on non-Windows platforms.

We would need to refactor the `#if`s out of the pipeline and replace with code that takes the right path based on a runtime detection of the platform.

**Comment by dellis1972** [comment]
| But what if someone includes the PCL in their executable and expects things to run. 

Well the pipeline will load its assembly and the .net/mono frameworks will ignore the PCL because an assembly with the same signature is already loaded :)

**Comment by tomspilman** [comment]
> Well the pipeline will load its assembly 

I mean outside of the Pipeline tool.  I can link against ` MonoGame.Framework.Content.Pipeline.dll` in my own non-Pipeline tool EXE.  I've seen people do this specifically for customized build services for use in editors or other development tools.

**Comment by harry-cpp** [comment]
Done in the develop branch.
