### ISSUE TITLE
What are Pipeline.app and MGCB.app?

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4701]
In the output folders for the Pipeline tool and MGCB I see a Pipeline.app folder and a MGCB.app folder.  These folders seem to have a second copy of the entire tool. See...

 http://teamcity.monogame.net/viewLog.html?buildId=8295&tab=artifacts&buildTypeId=MonoGame_DevelopMac#!111hp1,-a1t0qwm07aky,1qtam4d9dpono

The reason I bring this up is we already have 1GB of artifacts on the Mac/Linux build.  If we are storing artifacts we don't actually use or need that is a huge waste of disk space and performance copying this stuff around.

Do we use these .app folders?  If not how do we keep them from being generated in the first place?

If we do use them... then do we need the first copy of the binaries in the root of the Release folder?

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy ?

**Comment by tomspilman** [comment]
FYI.  I fixed the build server to zip up all the artifacts and reduced disk usage by 60%.  The 1GB of artifacts on the Mac/Linux build are now just 371MB.

Still if we can remove junk we don't need it would reduce that even more.

**Comment by cra0zy** [comment]
Pipeline.app contains Pipeline Tool + MGCB, MGCB.app contains only MGCB. They are basically .exe files within an archive.

**Comment by cra0zy** [comment]
The artifacts no longer seem present on the built bot, so closing...
