### ISSUE TITLE
Improve Unit Test Performance

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4704]
Since we [added code coverage](https://github.com/mono/MonoGame/pull/3820) the unit tests take 5 minutes to run where they used to take under 2 minutes.  This sounds trivial, but if we want to add any more tests and run tests for more platforms like DesktopGL then the testing needs to be as fast as possible.

We are currently running tests on a debug build of the framework so that code coverage has PDB files to work with.  Maybe if we used a debug build with optimization enabled it would improve the run time significantly.

This likely would require building the code a second time specifically for unit testing.  But building the code is literally less than 10 seconds.  It also solves to other issues:
- Smaller build artifact sizes.
- Code coverage will be able to find source code again.
- The test build steps can run in parallel with the code build steps.

This sounds like a win across the board.

**Comment by hach-que** [comment]
How feasible is it to run the tests themselves in parallel (if that's not done already, but I assume it is not because it's NUnit which AFAIK doesn't support it)?

**Comment by tomspilman** [comment]
> How feasible is it to run the tests themselves in parallel 

I'll have to research what NUnit supports there.  What worries me is that a lot of the tests pop up a GameWindow and do some rendering.  Having several of these running at once might cause issues.

For sure I can split things so that the Windows and WindowsGL tests run in parallel... still worried about them messing with each other.

**Comment by tomspilman** [comment]
Also we plan to see if we can use something like Xamarin's Test Cloud for mobile testing.  This might involve calling in a bunch of favors at Xamarin and Microsoft to be able to do affordably.  The benefit is we can test thoroughly on difficult devices like Android.
