### ISSUE TITLE
Texture2D GetData returns Transparent colors when called from different thread

### ISSUE THREAD

**Issue by ghost** [MonoGame/MonoGame#4708]
When called from a different thread the GetData returns a transparent colors [0,0,0,0]

I tried from main thread and it returns correct colors

OS: Windows 10
GPU: Nvidia GTX 960

Platform: DesktopGL

**Comment by tomspilman** [comment]
That sounds plausible as a bug in the GL code there.

@cra0zy @dellis1972 ?

**Comment by gms9rc** [comment]
I can confirm that this happens.  Only happened to me on Windows.  On OS X it's not a problem.  I'm also using Desktop GL.

**Comment by tomspilman** [comment]
> On OS X it's not a problem. I'm also using Desktop GL.

Probably because we've got each platform implementing this differently right now.

We now have a pure C# PNG loader in place... we should look to use that on all platforms soon.

**Comment by KonajuGames** [comment]
OpenGL was never designed to work in a multithreaded environment. The shared context idea was added to the OpenGL spec at a much later date, and has never worked perfectly.  This is one reason that Valve has stopped using shared contexts (along with the performance penalty that shared contexts impose).  I would like our desktop platforms to use the same system that we use on Android where all threaded calls to OpenGL are invoked on the render thread and we remove shared context support.
