### ISSUE TITLE
Consistant Package/Installer Naming

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4714]
I noticed that we're using different naming standards across our packages and installers:

![setupwin](https://cloud.githubusercontent.com/assets/103522/14231079/b602912c-f93a-11e5-8b95-427a69157fd4.JPG)

![setupmac](https://cloud.githubusercontent.com/assets/103522/14231080/b825b11e-f93a-11e5-87f1-b4f3bc7e0273.JPG)

Seems like we should decide on a convention for naming these things that is consistent across platforms.

@KonajuGames @cra0zy @dellis1972

**Comment by tomspilman** [comment]
My first thought is `MonoGameSDK` so that would be:

 - MonoGameSDK.exe on Windows
 - MonoGameSDK.run on Linux
 - MonoGameSDK.pkg on Mac

Is there something better?

**Comment by KonajuGames** [comment]
I would like the version number in the filename so it's clear before running it which version it is for.  `MonoGameSDK` as the name is fine.

**Comment by tomspilman** [comment]
> I would like the version number in the filename 

I would too...  but that breaks my ability to have a link on the webserver to the latest development installer.  I guess however I could maybe work out some javascript to build a URL to it by doing a few queries to the web server.

**Comment by KonajuGames** [comment]
A simple way would be to write out a small text file at a fixed address containing the latest filename of the installer including version number.  The Javascript could then load the contents of that file to create the URL and text for the links for all three downloads.

**Comment by tomspilman** [comment]
Ok so this is the naming convention i plan to use.  Assuming 3.7.0.100 is the full version for a build this is what it would look like:
```
MonoGame.SDK.3.7.0.100.exe // Windows
MonoGame.SDK.3.7.0.100.run // Linux
MonoGame.SDK.3.7.0.100.pkg // Mac
```
I can extend this format for console installers in the future if needed as well.

**Comment by cra0zy** [comment]
I like `MonoGameSDK.3.7.0.100.exe` more, no `.` between `MonoGame` and `SDK`.

**Comment by tomspilman** [comment]
> no . between MonoGame and SDK.

Ok....

```
MonoGameSDK.3.7.0.100.exe // Windows
MonoGameSDK.3.7.0.100.run // Linux
MonoGameSDK.3.7.0.100.pkg // Mac
```

**Comment by nkast** [comment]
Is it possible to have the branch name in the name?
Usually I keep a couple of previous installers and rename them: 
`MonoGameSetup 3.7.0.1156 (develop).exe`
`MonoGameSetup 3.7.0.1230 (develop).exe`
and also keep copies of my pull request:
`MonoGameSetup 3.7.0.0733 (develop multithread pipeline).exe`
`MonoGameSetup 3.7.0.0734 (develop VS output).exe`


if we could get something like that it would be great.
`MonoGameSDK.3.7.0.100.develop.exe`
`MonoGameSDK.3.7.0.101.develop.exe`
`MonoGameSDK.3.7.0.102.MouseGetState.exe`

**Comment by tomspilman** [comment]
> Is it possible to have the branch name in the filename?

I'll make sure we mark develop builds with `.develop` in the name.

**Comment by harry-cpp** [comment]
Well this has been "fixed".
