### ISSUE TITLE
Fix Mouse.SetPosition() docs to note platforms where it does not work.

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4718]
We need to add a `<remarks>` section to the docs for `Mouse.SetPosition()` to note which platforms the feature does not work under:

http://www.monogame.net/documentation/?page=M_Microsoft_Xna_Framework_Input_Mouse_SetPosition

I believe this is just the following platforms:
- Web
- Windows 8
- Windows Universal

**Comment by cra0zy** [comment]
Web has it implemented, tho it's missing IsCursorVisible property due to it...

**Comment by FrancescoBonizzi** [comment]
Hi! I didn't see where `Mouse.SetPosition` is not implemented, but I saw that in the `Angle` and `Windows Universal` solutions `PlatformSetCursor` are empty. 

Can I add the `<remarks>` there?

**Comment by Jjagg** [comment]
Only Windows Universal should be mentioned in the comment. The documentation should be added to the shared SetCursor method, otherwise our doc system doesn't pick it up. Thanks!

**Comment by cra0zy** [comment]
Ugh, UWP can be made to work, so instead of adding remarks we should, you know, get it working instead. I think I mentioned this somewhere else.

**Comment by Jjagg** [comment]
Okay, closing for #5000 then.
