### ISSUE TITLE
Xbox 360 GamePadCapabilities.GamePadType is Unknown on UWP

### ISSUE THREAD

**Issue by martyns** [MonoGame/MonoGame#4738]
Using a wired Xbox 360 for windows controller in a MonoGame UWP game, a call to 

`GamePadCapabilities capabilities = GamePad.GetCapabilities(PlayerIndex.One);`
`var g = capabilities.GamePadType; // GamePageType.Unknown`

returns an 'Unknown' GamepadType.

Using the MonoGame Windows project template the controller reports correctly as `Gamepad.Gamepad` using the exact same call.

I'm new to MonoGame so this could be intentional but it caught me out.

**Comment by tomspilman** [comment]
Looks like the UWP GamePad code never sets the `GamePadType`:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/GamePad.UWP.cs#L19

Should be a simple fix.

**Comment by martyns** [comment]
Actually, looking at the source of the other GamePad.*.cs classes it only seems to be 

https://github.com/mono/MonoGame/blob/8a8f21c65c6e40688ed75b64c65bbf5a5790e40f/MonoGame.Framework/Input/GamePad.XInput.cs

that ever sets it. So maybe it's not that important, I only noticed it as I was following a tutorial that checked the type.

I pulled the source down and got it working but it needed a reference adding to `MonoGame.Framework.WindowsUniversal` to `SharpDX` and `SharpDX.XInput` and I'm not sure if there's any issues with adding that.

**Comment by tomspilman** [comment]
Yeah it isn't critical to the gamepad API working, but we should get it right.

So as part of fixing this we should try to make that return a reasonable value for all platforms... not just UWP.

> I'm not sure if there's any issues with adding that.

You shouldn't need SharpDX.XInput on UWP...   it doesn't use XInput.

**Comment by Rhedox** [comment]
UWP doesn't have an equivalent to XInputs device type. SDL at least has the ability to get the name of the controller with SDL_GameControllerNameForIndex which could be compared with the names of common models to find a GamepadType. 

I don't think there's an easy solution to this.
