### ISSUE TITLE
Add Unit Tests for Input Classes

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4744]
We need to add some unit tests which cover the following classes:
- GamePad
- GamePadButtons
- GamePadDpad
- GamePadState
- GamePadThumbSticks
- GamePadTriggers
- Joystick
- Keyboard
- KeyboardState
- Mouse
- MouseState

Here is the coverage report as of this time:

![input](https://cloud.githubusercontent.com/assets/103522/14360776/90f50d20-fcbd-11e5-9f67-211c494f11b5.JPG)

For some of these there isn't much more to do that calling the methods to ensure they don't just outright crash, verifying default values, and method argument limits.

**Comment by WaveFunctionP** [comment]
I am attempting to work on this. (Haven't done much unit testing before.)

Would you prefer separate commits for each class, or in one fell swoop?

**Comment by KonajuGames** [comment]
Take on one type of input at first, say Mouse or Keyboard.  Make a group of tests for that input type and see how big the PR would be.

**Comment by siudeks** [comment]
Q1: What is the status of the issue? in Monogame sources I see GamePadTest, JoystickTest, KeyboardTest, MouseTest so probably code coverage is already increased bu I don't know how much.. 
Q2: could you provide link to the current Monogame code coverage in Teamcity pls?

**Comment by Jjagg** [comment]
I implemented this about as much as we can test it without actual hardware devices in #5142.

**Comment by siudeks** [comment]
:) sounds good, so @Jjagg  could you close the issue? Seems to be already implemented.

**Comment by Jjagg** [comment]
@KonajuGames or @tomspilman?

**Comment by cra0zy** [comment]
@tomspilman This has been implemented? : https://github.com/MonoGame/MonoGame/tree/develop/Test/Framework/Input

**Comment by tomspilman** [comment]
Yes it seems to be good enough... closing.
