### ISSUE TITLE
Import Collada crashes with NaN error

### ISSUE THREAD

**Issue by KrytenCoder** [MonoGame/MonoGame#4769]
Many collada exporters will leave NaNs in the collada file it seems. Version 3.1.1 of assimp has a bug that causes it to crash when importing these dae files. This bug is reported to be fixed in the latest release (v3.2). Any chance of the dlls in MonoGame being updated to this version soon?

Links to Assimp bug reports on this issue:
https://github.com/assimp/assimp/issues/337
https://github.com/assimp/assimp/issues/345

Assimp commit that should have fixed this:
https://github.com/assimp/assimp/pull/338

Thanks :)

**Comment by KonajuGames** [comment]
It shouldn't be difficult to bring that new version in.

**Comment by AliciaRaven** [comment]
There are so many bugs in the AssImp version currently used i can not believe that this issue keeps getting put back, there is the NaN issue, FBX scale issues, also #4967 referenced here. Im sure there are others, i will start to keep a list but AssImp needs updating and it should be a priority for anyone using 3D content.

**Comment by KrytenCoder** [comment]
Please can some one look into this issue. Isn't it just a case of changing the assimp binaries?

**Comment by harry-cpp** [comment]
Assimp has been updated, so closing this.
