### ISSUE TITLE
Addin fails to load in Xamarin Studio 5.10.3

### ISSUE THREAD

**Issue by newky2k** [MonoGame/MonoGame#4773]
After upgrading to the latest  stable version of Xamarin Studio the addin fails to load due to cyclic dependencies.

the addin is the latest version availble, 3.5.0 and xamarin studio on mac is 5.10.3.

<img width="1821" alt="screen shot 2016-04-17 at 17 38 18" src="https://cloud.githubusercontent.com/assets/6675766/14589503/8c6b4474-04db-11e6-8a82-2acfa62b9dc3.png">

[Xamarin Studio info.txt](https://github.com/mono/MonoGame/files/222818/Xamarin.Studio.info.txt)

**Comment by tomspilman** [comment]
@dellis1972 ?

**Comment by dellis1972** [comment]
@newky2k I just got the same thing on startup will investigate

**Comment by dellis1972** [comment]
@newky2k its something to do with the custom MimeType we add. 
This workaround is annoying but works. 

Disable the Addin in the Addin Manager (Disable don't uninstall)
Close XS
Start XS
Enabled the Addin in the Addin Manager
Work as normal.
Disable Addin before closing XS.

I keep looking for a solution.

**Comment by cra0zy** [comment]
This can be closed since with #4584 version 6.0 and up is only supported.
