### ISSUE TITLE
Window.AllowAltF4 and Window.AllowUserResizing

### ISSUE THREAD

**Issue by DuphusDigital** [MonoGame/MonoGame#4774]
Hi, I just updated MonoGame to be the newest version (3.5.1), and noticed a bug was still occuring from version 3.0 (the last version I had installed). Window.AllowUserResizing and Window.AllowAltF4 do absolutely nothing. Here is a quick video: https://youtu.be/mICYTstrxY8

**Comment by cra0zy** [comment]
The reason why it's occurring is because OpenTK is using SDL backend, and SDL doesn't have an option to change resizable param of the window. Add:
```csharp
OpenTK.Toolkit.Init(new OpenTK.ToolkitOptions { Backend = OpenTK.PlatformBackend.PreferNative });
```
in your Program.cs before creating the Game and everything should work fine.

#4755 fixes this as well.

**Comment by DuphusDigital** [comment]
Awesome! Thank you! @cra0zy

**Comment by DuphusDigital** [comment]
That also fixed Alt-F4.

**Comment by cra0zy** [comment]
Gonna close this as OpenTK got removed.
