### ISSUE TITLE
Mouse.GetState() Unhandled Exception.

### ISSUE THREAD

**Issue by DuphusDigital** [MonoGame/MonoGame#4781]
![img](https://cloud.githubusercontent.com/assets/9473767/14655253/4c5effd6-0636-11e6-9381-a71eecb7e8ba.png)
I'm trying to use Mouse.GetState(), and that throws an SDL error from OpenTK.dll. See the image for more infomation.

**Comment by angrywasp** [comment]
Please make sure you have the following 3 files in your output directory and retest
OpenTK.dll.config
MonoGame.Framework.dll.config 
SDL2.dll

Not sure where you get SDL2.dll from (linux user)

**Comment by cra0zy** [comment]
This should work fine now with the newest develop version.

**Comment by cra0zy** [comment]
@tomspilman This got fixed.
