### ISSUE TITLE
If Visual Studio has not set registry keys, Templates still greyed out

### ISSUE THREAD

**Issue by WardBenjamin** [MonoGame/MonoGame#4782]
The missing template options are still greyed out in the above case. I'm running Windows 10 with VS 2015, and for some reason my registry keys were never added. Since the Windows installer relies on these keys to find the template directory, and doesn't have a default, the templates are greyed out. 

I am going to hack around this myself, but this should be fixed.

**Comment by WardBenjamin** [comment]
Relates to #4612.

**Comment by WardBenjamin** [comment]
Looking at another PC, this is still an issue even when VS does correctly install the registry keys. I don't know what the issue is here, though. I'll report back if I can figure it out.

**Comment by tomspilman** [comment]
> If Visual Studio has not set registry keys

Yes...  I noticed this the other day myself.  If you have installed, but never launched VS... then none of the registry keys are set and the installer cannot detect the template install location.

Unless there is a super simple way to fix this... we should just wait for https://github.com/mono/MonoGame/pull/4295 to replace it all.

**Comment by Halofreak1990** [comment]
Another, similar problem occurs when you've installed Visual Studio, and then later decide to move your Documents folder to someplace else, say, to another drive. The installer does not only check the registry keys, but also whether the directory pointed to actually exists, and since it's been moved, the registry key now points to a non-existant directory, and therefore the template options will be grayed out.

**Comment by KonajuGames** [comment]
If the Documents directory was moved after Visual Studio was installed, where would we put the templates?  In the location the registry key points to or in the new Documents directory?  Where does Visual Studio look in this case?

**Comment by Halofreak1990** [comment]
@KonajuGames well, since the registry keys are not modified, and they continue to point to
`%USERPROFILE%\Documents\<Visual Studio version>\Templates` they now point to a non-existing location, which has a similar effect to the OP's problem.

I'd assume Visual Studio reads those registry keys and _also_ now processes a non-existing directory, meaning that any user-installed templates are now missing.

A solution would be that the registry keys are updated, like I did, to point them to the new location, or, even better, a way to refer to the moved Documents folder. Some Windows programs, like IE, somehow detect the move and correctly reference the new directory.

Microsoft really should've made an environment variable that points to the Documents folder, and is automatically updated when the user moves the folder using the designated UI.

**Comment by KonajuGames** [comment]
We can get the Documents special folder, and then use the expected folder structure from there. The issue was that we used that first and the templates wouldn't install or show up if certain conditions had happened. And now there are other conditions that make the new test fail.

**Comment by BabluKumar17** [comment]
Could anyone tell me how to set registry key in Windows 8.1?
Actually, I have same issue with MonoGame installation, it has not been grayed out Microsoft Visual studio 2015.
![image](https://cloud.githubusercontent.com/assets/14871809/19187190/afc530ca-8ca7-11e6-8cf3-19df4201571e.png)

Thank you for your time.

**Comment by Halofreak1990** [comment]
@BabluKumar17 The registry keys are located under `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\<Visual Studio Version>\`

The keys you need to change are "UserItemTemplatesLocation" and "UserProjectTemplatesLocation", though you may also want to change the keys "VisualStudioProjectsLocation" and "VisualStudioLocation" to point to the new location

You can edit them with regedit

**Comment by BabluKumar17** [comment]
I followed these instructions but I have not been able to find the keys you specified above.
![image](https://cloud.githubusercontent.com/assets/14871809/19189001/33109856-8cb3-11e6-93e3-1fb57cd36579.png)

Please see the image. Thank for your time, anyways.

**Comment by Halofreak1990** [comment]
@BabluKumar17 They should be directly under the 14.0 node in the treeview.

**Comment by BabluKumar17** [comment]
Thanks for your help. But I think I do not understand what you want to say. Could you please send me your screen shot?

**Comment by Halofreak1990** [comment]
@BabluKumar17 See the screenshot below
![github_help](https://cloud.githubusercontent.com/assets/3716246/19195368/a7b04a5a-8cb1-11e6-98cd-33387bec90a2.png)

**Comment by tomspilman** [comment]
@BabluKumar17 - Make sure you run Visual Studio at least once before running the MonoGame installation.  The registry key we look for isn't installed until VS is run the first time.

**Comment by BabluKumar17** [comment]
@tomspilman: I have already run it several times. Could it be the problem of not installing it in C: drive? Actually, I have installed it in E: drive.

**Comment by tomspilman** [comment]
@BabluKumar17 - Well we install it based on the registry key...

https://github.com/MonoGame/MonoGame/blob/develop/Installers/Windows/MonoGame.nsi#L270

So I don't see how the install location would have anything to do with it.  Someone that is exhibiting this install issue would just need to debug the installer and see why that path is failing.

**Comment by BabluKumar17** [comment]
@tomspilman: Would you please help with how to debug installer?  I don't know how to do. Or do you mean troubleshooting?
Anyway, the link you have provided me what is it used for?

Thank you

**Comment by tomspilman** [comment]
@BabluKumar17 - Unfortunately I don't have the time to debug this myself.  Maybe someone else has some time will jump in and help here.

**Comment by Ziriax** [comment]
I have the same problem. 

**The solution is to create a folder called "Visual C#" in these template folders.** 

Here's a dump of ProcMon when running the installer, that hinted me in that direction:

```
RegQueryValue	HKCU\Software\Microsoft\VisualStudio\14.0\UserProjectTemplatesLocation	SUCCESS	Type: REG_EXPAND_SZ, Length: 170, Data: d:\user\Peter Verswyvelen\My documents\Visual Studio 2015\Templates\ProjectTemplates
RegCloseKey	HKCU\Software\Microsoft\VisualStudio\14.0	SUCCESS	
CreateFile	D:\user\Peter Verswyvelen\My documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#	NAME NOT FOUND	Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Directory, Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
```

**Comment by Ivaylo-Korakov** [comment]
Hi,
I had the same problem and I was able to fix it.
In my case was a problem with OneDrive on Windows 10.
Apparently, when I was installing VS 2015 it decided to use a new folder called documents in OneDrive. 
What I did. 
I deleted the Documents folder in OneDrive.
I went to the registry and changed all the registry keys which pointed to the OneDrive folder with the folder called documents that is in the user folder.
Hope this helps! Have a nice day!

**Comment by Dani2kn** [comment]
Hi,

I had the same problem with MonoGame on VS2017 on Windows 10.
To fix this problem I downloaded the dev version of MonoGame 3.7.0 http://bit.ly/monogamevsdevsetup
Then on Documents / Visual Studio 2017 / Templates / ProjectTemplates .... I created the directory C#

Hope this helps! Cheers!

**Comment by dougbergman** [comment]
I was able to FIX this problem. It is related to redirecting the my docs folder. It is a pretty simple fix, however. First, go to Visual Studio, under Tools-Options, Project and Solutions. There, it will give you the ITEM and PROJECT folder locations it is using.
You can copy and paste these into the corresponding REGEDIT keys as specfified above(you might need to make them)
![image](https://user-images.githubusercontent.com/6503770/27690544-a1c1feda-5caf-11e7-8dd8-18653e08e3f6.png)

**Comment by Jjagg** [comment]
Installer doesn't use the registry keys anymore because it caused issues with VS2017. Closing in favor of #3808.
