### ISSUE TITLE
Common Bin Folder

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4795]
Currently the structure of our output bin folders is this:
- `MonoGame.Framework/bin`
- `MonoGame.Framework.Content.Pipeline/bin`
- `Tools/2MGFX/bin`
- `Tools/MGCB/bin`
- `Tools/Pipeline/bin`
- `Test/bin`

And once https://github.com/mono/MonoGame/issues/4794 we have yet another.

I've seen other projects invert this to have a common root binary folder:
- `bin\MonoGame.Framework`
- `bin\MonoGame.Framework.Content.Pipeline`
- `bin\Tools\2MGFX`
- `bin\Tools\MGCB`
- `bin\Tools\Pipeline`
- `bin\Test`

This way there is one root when you need to copy/delete/move/archive/etc.

Is this a good idea for MonoGame?  Are there downsides to this?

Should we apply the same technique to the `obj` folder too?

Also should we go further?  For example in that new structure we still end up with multiple copies of `MonoGame.Framework.dll` as each of those assemblies references it and pulls it in.  Should we look to remove this redundancy further by doing:
- `bin\Framework` <- MonoGame.Framework and MonoGame.Framework.Net
- `bin\Pipeline` <- MonoGame.Framework.Content.Pipeline and deps.
- `bin\Tools` <- 2MGFX, MGCB, Pipeline
- `bin\Test`

Thoughts?

**Comment by tomspilman** [comment]
@hach-que - I assume this would this require a new feature in Protobuild to support it.

**Comment by hach-que** [comment]
I don't want to support this, I've seen moving the bin folder to a common place for multiple projects cause subtle compilation, referencing and packaging issues. We had to spend a lot of time at work undoing a common output directory becaused it caused a lot of hard to diagnose issues (this was a solution with 200+ projects and not using Protobuild).

I seriously advise against pursuing any modification of the output or intermediate paths beyond what options Protobuild already provides.

**Comment by tomspilman** [comment]
> I've seen moving the bin folder to a common place for multiple projects cause subtle compilation, referencing and packaging issues.

I suspect you mean putting all output into a single folder for both `bin` and `obj`?  That I agree is not doable.  While you can share a `bin` folder safely if your projects are correctly setup...  the `obj` folder has to be separate in all cases.  But none of that is what I am proposing here.

Changing from `MonoGame.Framework\bin` to `bin\MonoGame.Framework` shouldn't cause any problems like you describe.

**Comment by hach-que** [comment]
I've seen these issues just moving bin, leaving obj in place. It's not safe
to share a bin folder as it impacts where assemblies are resolved from as
subsequent projects are built (as just one example).

**Comment by InfiniteProductions** [comment]
I wonder as pipeline for example include also common dlls (MG, SharpDX + others + MGCB itself, ffmpeg, assimp, ...), MGCB already includes all of these too, shouldn't be "better" to have one single binary for arch, cpu & type (release/debug):
something/bin/windows/cpu/debug/...
                     /windowsGL/cpu/release/
...
with all tools + 3rd party + MG dll mixed up all together ?

BUT: to avoid issue @hach-que shows (as I understand it), projects can still be build as the are, and a little script launched after do the cleanup & "blending".

**Comment by hach-que** [comment]
But that doesn't solve anything because now not only do you still have to
have separate bin folders (if you want to do it post-build), but now you
have to maintain cross-platform build scripts just to move some files.

Given the problems I've seen this cause, I don't think it's worth the
headache.

I definitely won't be supporting this upstream, but you're free to edit the
XSLT. But to be honest I don't know what technical or usability problem
unifying the bin folder ia actually supposed to solve.

**Comment by cra0zy** [comment]
This made me laugh at Protobuild a bit...
