### ISSUE TITLE
System.InvalidOperationException: Shader Compilation Failed

### ISSUE THREAD

**Issue by RecursiveCall** [MonoGame/MonoGame#4800]
A number of shaders were tested to run perfectly on a Windows platform. They were ported to Android (and tested with the emulator) as per the instructions here: http://www.monogame.net/documentation/?page=Custom_Effects. Some of the shaders run fine. Others compile successfully but result in this in runtime:

![capture](https://cloud.githubusercontent.com/assets/2229274/14771697/fc59537c-0a47-11e6-9e71-de8c26d6fa2c.PNG)

**Comment by Jjagg** [comment]
I'm gonna close this because we don't have any information to go on here and it seems @RecursiveCall hasn't used his GitHub account in a long long time, so we won't be able to get the shaders.

**Comment by RecursiveCall** [comment]
@Jjagg, I don't recall the issue, but I did manage to work through it at the time. If I come across this again, I can update the thread.

**Comment by Jjagg** [comment]
Awesome, thanks!
