### ISSUE TITLE
Creating RenderTarget2D with RenderTargetUsage crashes with UWP

### ISSUE THREAD

**Issue by eriksk** [MonoGame/MonoGame#4814]
When using the constructor overload for RenderTarget2D that takes a RenderTargetUsage parameter, it crashes on UWP. 

Error:
`An exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll but was not handled in user code Additional information: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Felaktig parameter.`

Felaktig parameter = "Error parameter" or something like that, it's swedish :)

Code Used:
`new RenderTarget2D(graphicsDevice, 512, 512, false, SurfaceFormat.Color, DepthFormat.None, 0, RenderTargetUsage.DiscardContents);`

It doesn't matter what value the RenderTargetUsage enum has.

**Comment by Tzenchor** [comment]
Running tests on `Texture3D` I run into the same error message, and the cause was that the `GraphicsDevice.GraphicsProfile` was set to `Reach` instead of `hidef`. Also, looking at `RenderTarget2DTest` the `GraphicsDevice.GraphicsProfile` is set to `hidef`

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
