### ISSUE TITLE
Texture2D.FromStream Test

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4820]
This is something I noticed in XNA behavior porting a game to PS4.

If you have a texture that is filled with the color:  `R:255 G:128 B:64 A:0`.  When you load this texture via `Texture2D.FromStream` the resulting texture has the color: `R:0 G:0 B:0 A:0`.

If you have a texture that is filled with the color:  `R:255 G:128 B:64 A:1`...  `Texture2D.FromStream` returns a texture with the color: `R:255 G:128 B:64 A:1`.

So although the XNA docs for `Texture2D.FromStream` explicitly state that it returns non-premultiplied colors... it does however clear the color channels if the alpha channel is 0.

I don't know if MonoGame matches XNA in this regard or not.  We need to implement a specific unit test with a special test texture to verify the results.

Secondarily we should consider adding an overload that lets you disable this color channel clearing as it was unexpected.  I can see how it would be useful to not have it modify the loaded color data.

**Comment by Tzenchor** [comment]
There is a bug. For transparent images works like XNA, but for not semi transparent it is multiplying the color channel by the alpha.
I have used this color for the test: R: 254, G: 128, B: 63, A: 129. But MonoGame is returning this one: R: 129, G: 65, B: 32, A: 129; (There might have been a problem with the test image because paint.net tells one color, and XNA another one)

**Comment by tomspilman** [comment]
> but for semi transparent it is multiplying the color channel by the alpha.

You mean premultiplied alpha?  XNA doesn't do that according to the docs:

> A 2D texture whose format is SurfaceFormat.Color and contains non-premultiplied alpha data.
https://msdn.microsoft.com/en-us/library/ff434103.aspx

**Comment by KonajuGames** [comment]
Our implementations do not zero RGB if A is zero.  I had no idea XNA did that.

Our implementations should not be pre-multiplying alpha.  If so, then that is a bug and should be fixed.

**Comment by Tzenchor** [comment]
> You mean premultiplied alpha? XNA doesn't do that according to the docs:

My fault explaining myself. Monogame is the one premultiplying. `R: 254, G: 128, B: 63, A: 129` Is the result from XNA and `R: 129, G: 65, B: 32, A: 129` the one from Monogame with the same image.

Will do a pull later with the tests or at least i'll publish the branch to my fork.
