### ISSUE TITLE
Add Color(uint) and Color(byte,byte,byte,byte) Constructors

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4824]
When you have to initialize a bunch of colors the current setters and constructors are inefficient.  They all do internal math to scale or clamp values to back to a byte then pack them.  Often this math isn't needed but is there just in case someone passes an out of range value.

I suggest extending the API to support two additional constructors directly taking a packed value and channel bytes:
```
public Color(uint packedValue)
{
...
}

public Color(byte red, byte green, byte blue, byte alpha)
{
...
}
```
These would be the most efficient constructors one could use.

We should also document the packed format in the reference docs on the new ctor and the packed value getter/setter.

**Comment by tomspilman** [comment]
Note in my case we're animating around 40,000 colors per-frame.  Saving 160,000 calls to clamp values that I know don't need any clamping seems like a reasonable thing.

**Comment by UncleThomy** [comment]
was thinking the same thing the other day, good idea

**Comment by KonajuGames** [comment]
There is already a private ctor that takes a packed value.  Simply making that public would solve that one.

XNA 3 had `Color(byte r, byte g, byte b, byte a)`.  It was changed to `int` for XNA 4.  Here's Shawn Hargreaves' [explanation](https://blogs.msdn.microsoft.com/shawnhar/2010/03/31/color-constructors-in-xna-game-studio-4-0/) for the change.

If we can get the `byte` version working nicely alongside the `int` version, this could make a good improvement in performance in some cases.

**Comment by tomspilman** [comment]
> It was changed to  int  for XNA 4.

Maybe then we need something more explicit like `Color.FromBytes(byte,byte,byte,byte)`?  This way you get the optimized construction without any type issues.

**Comment by tomspilman** [comment]
There was an interesting post in there...

> Are you doing if(((r|g|b|a)&0xFFFFFF00)!=0) { clamp }
https://blogs.msdn.microsoft.com/shawnhar/2010/03/31/color-constructors-in-xna-game-studio-4-0/#comment-16733

Maybe we should be doing something similar to avoid the clamp when it isn't needed?

**Comment by trommlbomml** [comment]
I don't understand the performance bottleneck, seems like a premature optimization? I tested creating 1 million colors saving in an array which took with the float constructor in sum about 40ms:

`const int colorCount = 1000000;
var colors = new Color[colorCount];

var sw = Stopwatch.StartNew();
for (var i = 0; i < colorCount; i++)
{
	colors[i] = new Color(i * 0.356f, i * 0.001f, i * 0.00123131f);
}
sw.Stop();

Debug.WriteLine(sw.Elapsed); //~40ms`

I tested on a desktop pc in debug mode, visual studio 2013. But I did not measure performance on mobile, But as this is computation and not memory or garbage collector related I would not expect big impacts. Are there any cases?

Nevertheless: I think the constructor is very useful!

**Comment by tomspilman** [comment]
> I tested on a desktop pc in debug mode

That is the issue...  not all systems are developer desktop PCs.  Consoles, handhelds, mobile.

In my case it was on PS4 that this came up as a bottleneck updating a huge amount of colors per-frame.  This would be slow enough that it hurt the ability for this code to hit 60fps.

**Comment by trommlbomml** [comment]
That is the interesting point for me, thanks!
