### ISSUE TITLE
RasterizerState.DepthBias not working as expected

### ISSUE THREAD

**Issue by SeriousMartin** [MonoGame/MonoGame#4826]
The DepthBias in MonoGame is not working the same way as in XNA.
I'm not 100% sure, but it looks like XNA is applying the DepthBias value set in RasterizerState in a way that matches the depth buffer format.

In XNA I have used a value of -0.0004f (this is quite much) to offset a transparent area border above the landscape.

This didn't work at all in MonoGame and after some investigation I found out that MonoGame just passes the value to DirectX without modification and DirectX applies it as a factor to a very small number that is calculated based on the depth buffer format.

My theory now is that XNA does some math with the DepthBias value to make it easier for the developer to deal with it.

In my case (24bit depth buffer) the following formula gives exactly the same visual result as -0.0004f in XNA:
`state.DepthBias = (float)(-0.0004f / (1 / Math.Pow(2, 24)))`

**Comment by tomspilman** [comment]
Interesting... as long as we can backup this change with a unit test proving identical results to XNA i'm all for this.  @KonajuGames ?

**Comment by KonajuGames** [comment]
Interesting.  The XNA docs state that the value can be between 0 and 16 inclusive.  The [DirectX 11 docs](https://msdn.microsoft.com/en-us/library/windows/desktop/cc308048(v=vs.85).aspx) show that the depth bias is set as an integer, which is why it appeared to do nothing.  The DirectX 11 docs also show that the depth bias is calculated differently based on the type and bit depth of depth buffer used.

How did you come up with that calculation?

I haven't looked at how OpenGL handles depth bias.

Tests should test the full range (0-16).

**Comment by flibitijibibo** [comment]
Here's the GL depth bias work if you want to nab it:

https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/OpenGLDevice.cs#L1566
https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/OpenGLDevice.cs#L4030

**Comment by SeriousMartin** [comment]
By trial and error. 

The formula in the directX doc isn't pretty well explained:
`(float)DepthBias * 2**(exponent(max z in primitive) - r)`
What does the ** notation mean and what is the exponent-function doing to the max depth value of the primitive?

From what I understand the factor should depend on the mantissa bits used by the depth buffer. I couldn't find more info in this so I just tried.
16 is 2^4 so I experimented with an additional factor somewhere in the range of 2^18 and 2^(4+20) did the trick for the visual result.

**Comment by KonajuGames** [comment]
This would also need to work with 16bit depth buffers as they are also commonly used.  We'll need something a bit more general than magic numbers, and backed up by a short description of how and why it is as so.

**Comment by Jjagg** [comment]
The DirectX11 [docs](https://msdn.microsoft.com/en-us/library/windows/desktop/cc308048(v=vs.85).aspx) state:
> If the depth buffer currently bound to the output-merger stage has a UNORM format or no depth buffer is bound, the bias value is calculated like this:
```Bias = (float)DepthBias * r + SlopeScaledDepthBias * MaxDepthSlope;```
where r is the minimum representable value > 0 in the depth-buffer format converted to float32.

The other formula ` (float)DepthBias * 2**(exponent(max z in primitive) - r)` is for non-UNORM formats, but MG [only uses D16_UNORM and D24_UNORM](https://github.com/MonoGame/MonoGame/blob/7c3d6870a38f8a5e479e64d935d692f2610e1cda/MonoGame.Framework/Windows8/SharpDXHelper.cs#L39-L54).

Then on the DirectX [data conversion rules page](https://msdn.microsoft.com/en-us/library/windows/desktop/dd607323(v=vs.85).aspx) it says on UNORM to FLOAT:
> The starting n-bit value is converted to float (0.0f, 1.0f, 2.0f, etc.) and then divided by (2ⁿ-1).

Here n means the number of bits in the UNORM. The minimum representable value > 0 for a UNORM in bits is 000000...001. That means converted to a float we get `1.0f / (2ⁿ-1)`. XNA docs are unclear about this, but I assume they're DepthBias (and therefore also MG's DepthBias) should be interpreted as the DirectX docs 'Bias'. Converting Bias to DepthBias (disregarding SlopeScaledDepthBias) means dividing by 'r' or `DepthBias = Bias * (2ⁿ-1)`. So probably @SeriousMartin's exponent was off by one. XNA docs also state the bias value ranges from 0 to 16 so it should probably be clamped.

**Comment by Jjagg** [comment]
Just tested, it's not clamped. I'll get a PR up in a bit.

**Comment by SeriousMartin** [comment]
Great! Thanks for the clear explanation
