### ISSUE TITLE
Memory consumption FNA vs Monogame

### ISSUE THREAD

**Issue by oldteen** [MonoGame/MonoGame#4834]
I've started this subjet on twitter : https://twitter.com/oldteen_tt/status/729763421240098816

Brief history of my case:
- I am trying to make a game based on FNA
- I want to try android/ios/xbox one support, so I compile my code with monogame 3.6
- And I see these ram conssumption for my game running in debug mode : with FNA +- 100MB and with monogame +-200MB

After make some tests, monogame memory consumption follow the backbuffer size. In 4k my game eat more than 300MB with monogame and stay at 100MB with FNA. (the others values was in 1080p)

I've made a new test with the code output by monogame template, just change the backbuffer size
**4k**
fna : 50MB
MG : 150 MB
**1080p**
fna : 50MB
MG : 93 MB
**640x360**
fna : 50MB
MG : 65 MB

Did I forget something ? a parameter ?
I know that 3.6 is not a finished version, but I am curious, maybe too much ;)

I hope these informations can help or I hope that I've made a mistake.

Edit: I use DesktopGL template

**Comment by mrhelmut** [comment]
Hello,

My branch is not up-to-date, but our game has a stable memory usage. If there's something bound to the backbuffer size, it must have been introduced post-3.5.
Did you tried this against 3.5?

Profiling info would be helpful.

**Comment by oldteen** [comment]
I will re-install 3.5 and test again.

**Comment by oldteen** [comment]
with 3.5 : this issue is in debug mode, in release mode memory is stable.
with 3.6 : this issue is in debug mode **and** release mode

I'm not good enough to use a profiler but I've try with reSharper and I see that the massive memory consumption is "unmanaged memory". I don't know if I can see deeper in unmanaged memory with reSharper memory profiler. I am not enough skilled to analyse more deeply.

I presume 3.6 maybe is always in debug mode, and I make the mistake to consider it like released.

**Comment by mrhelmut** [comment]
@oldteen Does it affect both fullscreen and windowed modes ? If it's only fullscreen, could you try ```graphics.HardwareModeSwitch = false;``` in your game constructor and see if it changes anything?

**Comment by oldteen** [comment]
All previous informations I gave are for windowed mode. This week-end I will try with fullscreen mode.

**Comment by UDXS** [comment]
How about DirectX and Android?

**Comment by oldteen** [comment]
Hi,

Don't know, and these next weeks no time to try more.

**Comment by harry-cpp** [comment]
Gonna close this as its more of a discussion than an actual issue.
