### ISSUE TITLE
referencing pipeline.Windows in a project using windowsGL 

### ISSUE THREAD

**Issue by Blucky87** [MonoGame/MonoGame#4857]
I have a VS solution where I am including all the project files that my game requires.
![solution explorer](http://i.imgur.com/MfA0lv1.png)

When using the `protobuild.exe --generate windowsgl` command, it does not produce pipeline tool projects for the windowsGL vs2015 solution generated. So when if my game is targeting windowsGL I have to type  `protobuild.exe --generate windows` to get the required project files. 

The pipeline tool projects created reference the MonoGame.Framework.Windows. 

I would like a version of the pipeline tools that references MonoGame.Framework.WindowsGL. Is this possible or does the tool require something that WindowsGL does not provide?

**Comment by Jjagg** [comment]
The Pipeline Tool does not depend on a specific MG platform type, only on host OS.
