### ISSUE TITLE
What about Shared Project Template?

### ISSUE THREAD

**Issue by daramkun** [MonoGame/MonoGame#4871]
In the Xamarin Forms, Everybody can make the Shared Project with Android, iOS, UWP. How about like-this template for MonoGame in MonoGame Installer?

This template will have a advantage about Cross-platform Game Development. Shared Code, Shared Content.mgcb, Each Platform Projects.

I tried this manually, It is so annoying works. I want to create projects and settings automatically. And It is reason what want to this template.

P.S. If MonoGame Community are discussing about Portable Class Library, What about Shared Project? Shared Project is more easy to building and using right?

**Comment by mrhelmut** [comment]
You might be interested by browsing through #4288 and continue this discussion.

**Comment by cra0zy** [comment]
Shared project template is already supported, the MonoDevelop/Xamarin Studio already had it in 3.5, for Visual Studio I am not sure if it had it in 3.5, but the template has been added.

**Comment by cra0zy** [comment]
@mrhelmut Wrong link or did you or I misread something?

**Comment by Daramkun** [comment]
I didn't see shared project for monogame 3.5
