### ISSUE TITLE
Use xwt for ProjectControl?

### ISSUE THREAD

**Issue by cra0zy** [MonoGame/MonoGame#4872]
As you might have noticed ProjectControl is really dirty:
 - https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Controls/ProjectControl.win.cs
 - https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Controls/ProjectControl.gtk.cs
 - https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Controls/ProjectControl.mac.cs

This is because Eto.Forms doesn't have a good multiselect treeview control. Now instead of using the one from Eto.Forms we could use the Xwt one. This would allow us to:
 - have same code for this control between platforms
 - gain same drag and drop code, Eto.Forms doesn't support drag and drop, Xwt does

Negative side effects?
 - Pipeline Tool for Windows will need to use WPF since Xwt doesn't support Windows Forms

I really wish that I thought of this idea earlier... at least I didn't start writing the new DnD code yet.

cc. @tomspilman @KonajuGames @dellis1972

**Comment by tomspilman** [comment]
So I am a little concerned about this.

We've taken a big risk in throwing away the UI we already had... ending up with something less functionally useful that we had before...  to move to Eto.  Now we're looking to add some bits of Xwt which we decided was a bad choice before.

We *really* should stick with Eto and help move it forward where we can.  We've been disruptive enough breaking features of the pipeline tool that we shouldn't do that again without an extremely good reason.

So what is the long term plan if we add Xwt specifically for the treeview feature?  Is drag and drop and an improved tree view on the roadmap for Eto?

**Comment by cra0zy** [comment]
Eto.Forms has a multiselect treeview component, which is called TreeGridView. This component however is a bit outdated in design and doesn't allow dynamic updating, which means in order to add/remove just 1 element it needs to refresh all the elements.

> We've taken a big risk in throwing away the UI we already had... ending up with something less functionally useful that we had before... to move to Eto. Now we're looking to add some bits of Xwt which we decided was a bad choice before.

The only lost functionality is drag and drop and multiselect (The propertygrid that is used right now is more advanced than the one Gtk Pipeline had). Also there are more things that are properly synced right now like "Exclude from Project|" (which Win Pipeline was missing) or undoing/redoing property grid changes (which Gtk Pipeline was missing).

> We really should stick with Eto and help move it forward where we can. We've been disruptive enough breaking features of the pipeline tool that we shouldn't do that again without an extremely good reason.

Gaining Multiselect which is not per platform (right now only Linux side has multiselect which works, because I left Win side open when working with replacing WinForms > WPF) and gaining Drag & Drop sound like good reasons.

I wouldn't mind helping with the issues bellow for just Gtk backend, but there are way to many backends for me to do an update on that :/

> Is drag and drop and an improved tree view on the roadmap for Eto?

Drag & Drop: https://github.com/picoe/Eto/pull/437

TreeGridView: https://github.com/picoe/Eto/issues/493 , https://github.com/picoe/Eto/issues/240

**Comment by tomspilman** [comment]
> I wouldn't mind helping with the issues bellow for just Gtk backend, but there are way to many backends for me to do a PR on that :/

Sure...  I don't expect you to solve all the issues in Eto.  Just that we should be sure to keep reminding them to get those resolved and look to remove XWT from the Pipeline tool as soon as we can.

**Comment by cra0zy** [comment]
I just remembered whats wrong with Eto treeviews (both TreeView and TreeGridView) in general: #533

FilterView is really slow when building a lot of stuff because of the above.

**Comment by cra0zy** [comment]
@tomspilman So.... should I start tinkering with a new per platform treeview control or are you fine with using Xwt for it?

**Comment by tomspilman** [comment]
> or are you fine with using Xwt for it?

Yeah i'm fine for using Xwt for now with us helping/pressuring/encouraging the Eto team to getting their own treeview problems fixed.

**Comment by cra0zy** [comment]
Just a reminder about https://github.com/MonoGame/MonoGame.Dependencies/pull/88 , I've kind of been waiting on that to get merged.

On a side note I already did most of the work for this 2 months ago: https://github.com/cra0zy/MonoGame/commits/xwtprojectcontrol , I'll update it to replace the FilterView treeview as well.

**Comment by tomspilman** [comment]
>  I've kind of been waiting on that to get merged.

Just merged it now.

> I'll update it to replace the FilterView treeview as well.

**Comment by cra0zy** [comment]
Fixed with #5149
