### ISSUE TITLE
SetVertexBuffers and DrawInstancedPrimitives for OpenGL

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#4875]
I'm getting into OpenGL a bit, and to get some hands on experience I'm trying to implement SetVertexBuffers and DrawInstancedPrimitives (takes care of #913) and I was wondering if the PR for that should just go here or in @cra0zy's SDL2 branch (because there might be some annoying conflicts?). I got it working with multiple vertex buffers, but I can't test DrawInstancedPrimitives right now because I'm on Linux (shader compilation). I'll try Windows and instanced drawing tomorrow.

I'm also unsure if instanced drawing is available on all platforms that MonoGame supports. I think it works on ES 2.0 only with a certain extension and I'm not sure about Windows Phone either. Should I do some checks for that? Anyways, that's probably easier to discuss when the PR is up, so tl;dr where should the PR go?

**Comment by Jjagg** [comment]
I didn't see #4874 before, awesome! At a glance I think there will only be minor conflicts, if any, so I'll just set up a PR when I checked this on windows and rebase if 4874 gets merged first!

**Comment by Jjagg** [comment]
With the SDL branch merged, I'll try and fix this up in between my exams :) I have a question though. Looks like glDrawInstancedElements has only been around since OpenGL 3.1 and glVertexAttribDivisor since 3.2... How should I go about this? Instanced drawing is not used in many games, so linking the entry points should not fail if it's not supported because the user has an old graphics card or way outdated drivers... Can we load a function that throws a PlatformNotSupported exception that will be delegated to (I'm not sure if this can be done, don't know a lot about delegation in .NET yet) in stead of the GL call? Or maybe there's something better that we can do... I think @dellis1972 and @mrhelmut did the entry point loading?

**Comment by dellis1972** [comment]
I suppose we could catch the "EntryPointNotFoundException" in a similar fashion to [1]. 
And add something to the GraphicsCapabilities class [2] to detect if we managed to get that entry point or not. (it will be null if we didn't get it). Say "SupportsInstancing" which would be true to DX and the platforms that do support it.
The the code in the GraphicsDevice can decide if it needs to throw and error or not. 
It would be nice to see how many PC's still only support GL 2.1 we could then decide if we can up the minimum required version or not.

[1] https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/OpenGL.cs#L1237
[2] https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsCapabilities.cs

**Comment by mrhelmut** [comment]
+1 for the SupportsInstancing approach and silently catching any entry point loading failure.
If games are not using instancing, it would nice that the GL 3.2 requirement is skipped.

A bit of topic, but if we can manage to reach a GL 2.1 minimum, there's an opportunity to make GL projects running on RaspberryPI's. I believe that only the frame buffer object extensions are 3.0+.
