### ISSUE TITLE
Issue in CreatePixelShader

### ISSUE THREAD

**Issue by Christian24** [MonoGame/MonoGame#4898]
Hello everybody,

I am using MonoGame for a long time, but recently after a LONG time I updated my MonoGame sources and recompiled my assets. Everything worked fine before, but now I get an exception in CreatePixelShader in Shader.DirectX.cs.

Here is my PixelShader btw: 

```
`#define ALPHATHRESHOLD 1.0 / 255.0

uniform float3 surfaceOParams; // x - extrusivity, y - specularity, z - emissivity
uniform float3 surfaceEParams; // x - depth, y - gi sensy, z - li sensy

sampler CMap: register(s0) = sampler_state
{
    MinFilter = Point;
    MagFilter = Linear;
    AddressU = Clamp;
    AddressV = Clamp;
};

struct PSOut
{  
    float4 c: SV_Target0;
    float4 sop: SV_Target1;
    float4 sep: SV_Target2;
};  

PSOut PSMain(float4 pos: SV_POSITION, float4 tintColor: COLOR, float2 texCoords: TEXCOORD0)
{
    PSOut output = (PSOut)1.0;

    float4 color = tex2D(CMap, texCoords);
    clip((color.a < ALPHATHRESHOLD)? -1.0: 1.0);

    output.c = color * tintColor;
    output.sop.xyz = surfaceOParams;
    output.sep.xyz = surfaceEParams;
    return(output);
}

technique LightingStage0
{
    pass Pass0
    {
        AlphaBlendEnable = TRUE;
        DestBlend        = INVSRCALPHA;
        SrcBlend         = SRCALPHA;
    ColorWriteEnable = ALPHA|RED|GREEN|BLUE;

        PixelShader = compile ps_5_0 PSMain();
    }
}`
```

Exception: Exception thrown: 'SharpDX.SharpDXException' in SharpDX.dll

Additional information: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Falscher Parameter.

Any help would be greatly apreciated,
Christian

**Comment by Jjagg** [comment]
Not sure how strict this all is, but shouldn't your PSMain function look like this:
    
    float4 PSMain(args...) : COLOR

**Comment by Christian24** [comment]
I don't have much knowledge of HLSL myself, but given this being an effect for multiple render targets I don't think you can change the signature. The thing is it compiles fine, but I get an exception at runtime.

**Comment by Jjagg** [comment]
Ah, is that how you do that! That's good to know :) You could try doing this with shader model 4, I've had (unresolved) issues where only ps_4_0* worked (same exception). Not sure what else this could be, since that "Incorrect Parameter" exception could mean pretty much anything. I'd strip parts of the shader and see if it works then to pinpoint the problem, then find a way around it.

**Comment by Christian24** [comment]
The weird part is that it worked before I updated the MonoGame source code. I tried the ps_4_0 trick, but it doesn't help.

**Comment by Christian24** [comment]
Okay. It seems to be only broken in develop branch. In master branch everything is working fine. Adding ps_4_0_level_9_1 does the trick for some effects, but sadly not for all effects (having too many instructions).

**Comment by Jjagg** [comment]
ps_4_0_level_9_3 will allow for some more instructions, though maybe still not enough in some cases. I hope we can figure this out at some point

**Comment by KonajuGames** [comment]
`ps_5_0` requires a DirectX 11 card when the pixel shader is created at runtime.  `ps_4_0_level_9_1` is required for DirectX 9 level cards.  I'm not sure how it worked before.

Do you have your GraphicsProfile set to `HiDef`?  Leaving it at `Reach` will restrict the supported shader level.

**Comment by tomspilman** [comment]
I don't know what the issue is here, but i'll give it a test later and see.

**Comment by Jjagg** [comment]
I just tried this and can confirm that setting the GraphicsProfile to HiDef fixes the issue @KonajuGames.

**Comment by Jjagg** [comment]
@tomspilman This can be closed too :)
