### ISSUE TITLE
Pipeline Reference Editor Fixes

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4912]
A couple of issues with the Reference Editor in the Pipeline tool.

There should be an empty column header after the "Location" column which stretches to fit the remaining visible area.
![ref](https://cloud.githubusercontent.com/assets/103522/15910914/d322bb42-2d92-11e6-8e0b-436cb07ca25d.PNG)
Look at how the details view works in the Windows file explorer.

The wrong sizer cursor appears on the bottom-left and bottom of the Reference Editor window.

A possible side effect of that wrong sizer cursor is that resizing via the bottom-left and bottom of the window incorrectly moves the right side of the window.

**Comment by tomspilman** [comment]
Note none of this occurs in the WPF version of the tool in PR https://github.com/mono/MonoGame/pull/4885.

**Comment by cra0zy** [comment]
This has been fixed.

**Comment by tomspilman** [comment]
Yep... I can verify this is fixed.
