### ISSUE TITLE
Speed up bindings?

### ISSUE THREAD

**Issue by harry-cpp** [MonoGame/MonoGame#4916]
So by replacing OpenTK we probably lost a bit on speed because OpenTK actually had an afterbuild rewrite action to speed up binding calling: https://github.com/opentk/opentk/blob/develop/Source/Generator.Rewrite/Program.cs

Should we maybe do the same thing?

CC. @dellis1972 @mrhelmut

**Comment by tomspilman** [comment]
It seems that is doing the `calli` optimization.

`calli` is a special IL instruction that just directly calls a function given a function pointer and a stack of arguments.  Internally pinvoke calls use `calli` to call the function, but before that they do some extra work for marshalling.  What i'm confused about is i think `calli` is specifically for virtual methods...  but i could be wrong.

Anyway... our bindings don't use any complex marshalling...  but I expect there is sill some overhead where the pinvoke does some tests and maybe throws some exceptions to "help" you.

It would be interesting to see the cost of our simple non-marshalling pinvokes vs a simple direct calls...  i'm sure it is more expensive, but I don't know how much.

Note this is also the optimization that SharpDX does which makes it the fastest DX wrapper.  You can read about how they use the `calli` optimization far down in this blog post...

  http://xoofx.com/blog/2010/10/19/managed-netc-direct3d-11-api-generated/

We should probably investigate this and other techniques and see what sort of wins we can gain.

**Comment by mrhelmut** [comment]
That's quite interesting.

We moved our game to the latest develop, and I can confirm that there's a small performance hit, nothing significant though.

It's worth investigating.

**Comment by dellis1972** [comment]
I did see OpenTK was using calli and almost went down that route. But decided to "get it working" first. Optimizing later is always good.  

If we do add a rewriter can we make it an MSBuild Task and use Targets rather then run an exe on a post build event. The latter means you have to do platform specific code for Unix/Windows the former means it just works, plus you can correctly detect inputs and outputs.

**Comment by cra0zy** [comment]
You know, I forgot for a moment that we aren't using calli for OpenGL stuff... I just realized it.

**Comment by endimilojkoski** [comment]
Loading is much slower for me now, roughly 5x.
I am loading all the content on startup with System.Threading.Thread.

**Comment by mrhelmut** [comment]
> Loading is much slower for me now, roughly 5x.
>I am loading all the content on startup with System.Threading.Thread.

Nothing to do with the bindings in itself, I think. I believe it's because all texture initializations are blocked on the UI thread now, it's much safer, but may impact load times if you have a lot of individual textures.

**Comment by dellis1972** [comment]
@endimilojkoski probably because we don't have a second GLContext for loading, the loads are done on the main GLContext Thread

**Comment by dellis1972** [comment]
we can probably look at re-implementing that support.

**Comment by prollin** [comment]
@dellis1972 if you do, you should probably get rid of the GL.Finish that appears in Texture2D.PlatformSetData() and move it to replace the GL.Flush() that was called after the action() was called on the BackgroundContext.
GL.Finish() in PlatformSetData is not necessary when running on the UI thread (and can impact performance).

**Comment by harry-cpp** [comment]
Closing this as we went full on dlopen route.
