### ISSUE TITLE
Shader parameter initialization lost after building glsl

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#4919]
I was doing some rendering with a custom shader (built from the pipeline tool) in a DesktopGL project and my models were all black. It all worked in DirectX. After a while of being horribly frustrated I found out my parameters were not initialized, so I checked out the xnb. Turns out the initialization of parameters in a shader gets lost when it's translated to glsl. Is that a MojoShader thing? Can we fix this?

**Comment by tomspilman** [comment]
> Is that a MojoShader thing?

Right.... there was not a way to query the default values from MojoShader.

Still thinking about it further there might be a way.  MojoShader works from the HLSL compiled bytecode... we could maybe get the default values from there.

**Comment by Jjagg** [comment]
I just noticed this is a duplicate of #1314
