### ISSUE TITLE
Couple DesktopGL on MacOS issues with latest 3.6 dev build

### ISSUE THREAD

**Issue by endimilojkoski** [MonoGame/MonoGame#4932]
Found couple issues when testing my DesktopGL game on MacOS:
1. Had to rename "libopenal.1.dylib" to "libopenal.dylib"
2. Had to rename "libSDL2-2.0.0.dylib" to "libSDL2.dylib"
3. Full screen issue on 1440x810 MacBook Pro '08 display. The game shows up in the bottom left corner. I managed to work around it by setting it to full screen again once the Loading finishes. There are no issues if I start the game in windowed mode or if I go to Options and go to windowed mode and back to full screen.
4. If I plug in gamepad while game is running, it is not detected but it does not crash the game like it does on Windows.

*5. The game is still crashing on Windows if I connect a gamepad in game, but this might have been fixed with some of the open PRs?

@mrhelmut @cra0zy

**Comment by mrhelmut** [comment]
1. & 2. are fixed in the dependencies (https://github.com/MonoGame/MonoGame.Dependencies/commit/42e587c60ae6692551da8055a246d4eb554190b8), but I still need to push the update on the main repo.

3. if you have packaged your game in an .app bundle, make sure that there is no ```NSHighResolutionCapable``` or ```NSHighResolutionMagnifyAllowed``` in the info.plist file. These two make MonoGame to not work correctly on Hi-DPI modes.

4. & 5. is something I'll have to take a look at soon.

**Comment by endimilojkoski** [comment]
On my friend's newer MacBook retina model the game crashes if his X360 gamepad is plugged in:

![image](https://cloud.githubusercontent.com/assets/13436441/16090489/dda02fbc-332f-11e6-805c-578072336f11.png)

After unplugging it he can start the game.

**Comment by mrhelmut** [comment]
Could you try the latest develop? I believe it fixes your friend's issue.

I still have to investigate the hot plugging /unplugging support.

**Comment by endimilojkoski** [comment]
I tried with latest develop.

**Comment by mrhelmut** [comment]
That's puzzling, because the related code catches this error... https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/GamePad.SDL.cs#L71

**Comment by endimilojkoski** [comment]
Yes, am building it from source and I have latest version, I checked and those changes are in.

**Comment by mrhelmut** [comment]
Would you be able to debug this problem and know which line fails? I don't have any gamepad exposing this issue.
I suspect that it fails outside the try/catch because of a residual error that hasn't been cleaned from a previous gamepad failure. Probably related to having multiple gamepads.

**Comment by endimilojkoski** [comment]
Unfortunately I can't debug it since it is not happening for me and my friend is in another country.
Will let you know if I find anything else.

I hope this will be fixed soon and other PRs merged before the Steam summer sale :)

**Comment by endimilojkoski** [comment]
I can confirm that the game is working properly now on Mac retina displays.
So 4K and retina displays are working without any issues now on Windows and Mac.
I suppose it is same on Linux but I can't confirm that.

**Comment by cra0zy** [comment]
@tomspilman Everything in here should be fixed.
