### ISSUE TITLE
Fix SpriteEffect half pixel offset

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4939]
Now that we've made `SpriteEffect` public we have to make sure it works.

Currently you can see it is always applying a half pixel offset... even on platforms that don't require it:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Effect/SpriteEffect.cs#L62

It should use the `SpriteBatch.NeedsHalfPixelOffset` flag like `SpriteBatch` does:
 https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/SpriteBatch.cs#L140

While we're at it we should add in a unit test for it since we need to ensure it works now.

**Comment by Verser** [comment]
Just checking, this seems to be complete but is marked as Open and HelpWanted. Should this be closed?

**Comment by tomspilman** [comment]
@Verser - Thanks... we just forgot to close this.
