### ISSUE TITLE
(PipelineTool) Single click on current property value does not start editing.

### ISSUE THREAD

**Issue by jamesford42** [MonoGame/MonoGame#4943]
Double-click seems to be required before you can start editing the value of a property. This is quite odd and non-standard property grid behavior.

**Comment by jamesford42** [comment]
Double-click seems to be required before you can start editing the value of a property. This is quite odd and non-standard property grid behavior.

**Comment by cra0zy** [comment]
I personally like the double click, I left it intentionally. If people complain about this I'll change it.

**Comment by tomspilman** [comment]
It is one of the things I would like to see fixed.

It is not standard behavior for property grids as seen on Windows.

I see no benefit to a double click to activate editing other than being different from standard.

We should fix this.

**Comment by cra0zy** [comment]
> I see no benefit to a double click to activate editing other than being different from standard.

Dialog editing requires double click, that's why it's there. Should dialog editing also be started with one click?

**Comment by tomspilman** [comment]
> Should dialog editing also be started with one click?

No.

Things that are inline editable without a dialog... like a text control or a combo box...  should just be a single click to set focus and allow editing.

If something requires a (or has an optional) dialog box popup for editing...   it should show a `...` button which is clicked to display the dialog.

This is all standard Windows behavior for property grids.  You can see this is more detail if you use like VS2015 and edit some properties on a WPF control.

**Comment by cra0zy** [comment]
> If something requires a (or has an optional) dialog box popup for editing... it should show a ... button which is clicked to display the dialog.

If it's optional, yes, but if it's required, the button is pointless.

**Comment by tomspilman** [comment]
> but if it's required, the button is pointless.

The button is a visual way to indicate you have to do more than click.  Else the user has to guess that maybe a double click does something.

**Comment by griseus** [comment]
I did some research.
Probably there is no quick-and-easy-solution for this. Due to the fact, that the control is created on the mouse up event:
```
        private void Drawable_MouseUp(object sender, MouseEventArgs e)
        {
            _moveSeparator = -_separatorWidth / 2 - 1;

            if (e.Location.X >= _separatorPos && _selectedCell != null && _selectedCell.Editable && !_skipEdit)
            {
                var action = new Action(() => _selectedCell.Edit(pixel1));

#if WINDOWS
                (drawable.ControlObject as System.Windows.Controls.Canvas).Dispatcher.BeginInvoke(action,
                    System.Windows.Threading.DispatcherPriority.ContextIdle, null);
#else
                action.Invoke();
#endif
            }
        }
```
I looked into ETO.FORMS and it seems that there is no support in creating a dropdown and then open it programmatically: https://github.com/picoe/Eto/issues/928

In my opinion this would make refactoring necessary. Would it be okay if the Dropdown property is recognizable as such before clicking? I guess in VS it's the same?

**Comment by cra0zy** [comment]
This has actually been fixed for quite some time now...

Anyway closing...

**Comment by griseus** [comment]
Is the solution Windows only? Because as I tested this on Ubuntu 18.04, I had to double click on the property menu to open a dropdown menu. First one converts the field into a dropdown, the second is for opening.
