### ISSUE TITLE
Xamarin 6.0.1 breaks the MonoGame Add-in

### ISSUE THREAD

**Issue by prime31** [MonoGame/MonoGame#4958]
I can't seem to figure out where in the mpack file the 6.0 restriction is located so I can bump it up to 6.0.1. Any ideas?

**Comment by dellis1972** [comment]
Related https://github.com/mono/MonoGame/pull/4584

Looks like the API's changed again :( I'm working on it but some of the stuff we need no longer exists :(

**Comment by danzel** [comment]
Was it this bug? https://releases.xamarin.com/xamarin-studio-stable-hotfix-for-incompatible-xs-addins/

**Comment by cra0zy** [comment]
@tomspilman This got fixed.
