### ISSUE TITLE
[Content Pipeline Tool] Link to folder issue intended ?

### ISSUE THREAD

**Issue by dylanwijnen1** [MonoGame/MonoGame#4980]
I've linked a folder within the solution it references to _"../../GameAssets"_ from the content.mgcb when run. It will not output as _"Content/bin/****/GameAssets"_ it will output as _"Content/GameAssets"_. Im guessing it has to do with the files being references by _"../../"_. Is this intended or is it me that's using it wrong.

Files were referenced/added through the Content Pipeline Tool.

Edit: Quick mention when building for release it goes into the correct build path.

**Comment by cra0zy** [comment]
Duplicate of #5109
