### ISSUE TITLE
[Mac] Default project Template Hangs on Run

### ISSUE THREAD

**Issue by prime31** [MonoGame/MonoGame#4990]
This is an odd one and I was wondering if anyone has seen it before. I created a fresh DesktopGL project  using the MonoGame project template and get a hard hang on launch. Cant get the debugger connected at all. This only happens one Mac that I have access to. Full logs of mono --trace are below. Any ideas?

[logs.txt](https://github.com/mono/MonoGame/files/351148/logs.txt)

**Comment by Scellow** [comment]
I had this issue, but with Mono application in general, it has something to do with libgdiplus

I'm not sure how i fixed that issue, but i think i had to remove every installed mono versions here /Frameworks/Mono(..)/Versions/

Then just install mono using brew, and move that Mono to the /Frameworks/Mono(..)/Versions/ folder

Then create a simlink to that mono version  to CurrentVersion

I'm not sure about the path / folders name, all by memory

I'll add more info once i can go back to my Hackintosh partition

**Comment by Scellow** [comment]
I put your log on gist for convenience :p 

https://gist.github.com/Scellow/a2acce7e4cbec4490606cf0f8006051f

**Comment by prime31** [comment]
Got it working. What ended up working for me was installing Xamarin.Mac and then setting the project to 64bit. Perhaps it would be a good idea to have 64bit be the default?

**Comment by prime31** [comment]
Adding to this in case anyone else finds it. On another Mac I had the exact same problem. I was able to identity that the issue was that the Mac had one of those cleaner apps run (like Onyx, MacCleaner, etc) and it removed the extra language files from the Mono install (and possibly other files) causing the issue. A Mono reinstall fixed it.

**Comment by mtear** [comment]
I'm having issues with this as well. Does anyone have any more info? I'm just trying to get started with XNA and MonoGame but can't get it to work. I followed the steps from this guide: http://www.gamefromscratch.com/post/2015/06/09/Getting-Started-with-MonoGame-on-MacOS.aspx

**Comment by Jjagg** [comment]
Since this seems to be a Mono installation issue and we didn't get any more reports of this issue I'm closing it.
