### ISSUE TITLE
More Pipeline issues

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4991]
A few issues with the new Eto Pipeline tool:

  - Canceling a build fails on first try...  second try it crashes.
  - Right clicking on a folder and hitting `Rebuild` in the treeview does not rebuild all the items in that folder.
  - Right clicking an item in the treeview does not select it before showing the context menu.
  - Treeview selection seems really slow at times on a project with lots of content items.
  - You can trigger content building from tree view context menu while a build is already in progress.
  - Shift and Ctrl multiselection does not work in treeview.
  - The current cancel build icon looks the same enabled as disabled... needs color to it.

I'd like to see these issues which all worked correctly before Eto addressed before we add any more new features.

**Comment by tomspilman** [comment]
@cra0zy - FYI.

**Comment by cra0zy** [comment]
I have a fix for at least half of them in https://github.com/cra0zy/MonoGame/tree/xwtprojectcontrol tho due to the fact that it has merge conflicts with https://github.com/mono/MonoGame/pull/4904 I didn't submit it.

Also that branch is/was meant for #4872

**Comment by cra0zy** [comment]
Everything on the list should be fixed.
