### ISSUE TITLE
Moving MonoGame Repo

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5033]
We're going to be moving the MonoGame repo from its current location here:

 https://github.com/mono/MonoGame/

... to the MonoGame organization here:

 https://github.com/MonoGame/MonoGame/

We've discuss things with GitHub support staff and the transfer should be 100% transparent as all URLs will redirect to the new location.  Existing clones or forks won't be affected in any way.

All the stars and fork stats for the repo also transfer in the move.

There might be a little issues with the Gitter chat room, but the Gitter staff said they could manually fix things if we have issues.

**Comment by dellis1972** [comment]
nice :)

**Comment by cra0zy** [comment]
Wuhu!!

**Comment by cra0zy** [comment]
Why was MonoGame repo in Mono organization in the first place?

**Comment by tomspilman** [comment]
> Why was MonoGame repo in Mono organization in the first place?

A decision made long ago.... no clue really.  My guess is they needed to put it somewhere after moving from Codeplex and someone thought it would be neat to have it be in the Mono org.

**Comment by CartBlanche** [comment]
Miguel asked us and it made sense at the time, as we were reliant quite heavily on the Mono stack for iOS/Android and Mac. That is no longer the case, as we support lots of other platforms too now. So it makes sense to make is more independent.

**Comment by tomspilman** [comment]
FYI.

We will pull the trigger on the move this week.  It will be totally transparent to everyone and should not interrupt any development here.

**Comment by lozzajp** [comment]
@tomspilman Just browsing the 3.6 milestone release issues, and this one is finished is it?
