### ISSUE TITLE
Very first run takes 2 minutes to open Window on OSX El Capitan

### ISSUE THREAD

**Issue by joao-moraes-petitfabrik** [MonoGame/MonoGame#5037]
When launching the game executable on OSX for the first time, the game window does not open, and everything freezes at the Game constructor.

It stays on that state for about 2 minutes, and then the following messages appear on the console:

Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const: conn 0x24a1f token 0x1ffffffffffe85
Jul 27 17:19:25  mono[13543] <Warning>: Backtrace (at 111526):
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x96b3bdb1 CGSDisableUpdateToken + 228
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  1   AppKit                              0x94701890 ___disable_updates_sync_block_invoke_2 + 19
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  2   libdispatch.dylib                   0x9221683f _dispatch_client_callout + 50
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  3   libdispatch.dylib                   0x92218110 _dispatch_barrier_sync_f_invoke + 61
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  4   libdispatch.dylib                   0x922180cc dispatch_barrier_sync_f + 98
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  5   libdispatch.dylib                   0x92222723 dispatch_barrier_sync + 54
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  6   AppKit                              0x94701772 NSCGSDisableUpdates + 229
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  7   AppKit                              0x947015b8 NSCGSTransactionRunPreCommitActionsForOrder_ + 159
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  8   AppKit                              0x94701507 NSCGSTransactionRunPreCommitActions_ + 26
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  9   AppKit                              0x946e25dc -[_NSCGSTransaction addActionWithOrder:usingBlock:] + 237
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  10  AppKit                              0x946e24d5 NSCGSTransactionAddAction + 115
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  11  AppKit                              0x946e1f2d NSCGSWindowBackingStoreMark_ + 266
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  12  AppKit                              0x946e1e19 -[_NSCGSWindowBackingStore setAttached:] + 43
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  13  AppKit                              0x946e1b3d -[NSCGSWindow(NSCGSWindowBackingStore) setHasBackingStore:] + 89
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  14  AppKit                              0x947bf950 _NSCreateWindowWithOpaqueShape2 + 120
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  15  AppKit                              0x947be3bf -[NSWindow _commonAwake] + 2259
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  16  AppKit                              0x945b87f1 -[NSWindow _commonInitFrame:styleMask:backing:defer:] + 807
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  17  AppKit                              0x945b6dbc -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1789
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  18  AppKit                              0x945b66b5 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 72
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  19  ???                                 0x05e3a6a8 0x0 + 98805416
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  20  ???                                 0x05e36d78 0x0 + 98790776
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  21  ???                                 0x006a0e88 0x0 + 6950536
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  22  ???                                 0x006a0c06 0x0 + 6949894
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  23  ???                                 0x006a00d0 0x0 + 6947024
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  24  ???                                 0x00698114 0x0 + 6914324
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  25  ???                                 0x00697024 0x0 + 6909988
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  26  ???                                 0x00696720 0x0 + 6907680
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  27  ???                                 0x00696528 0x0 + 6907176
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  28  ???                                 0x00695e58 0x0 + 6905432
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  29  ???                                 0x00693b10 0x0 + 6896400
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  30  ???                                 0x006930dc 0x0 + 6893788
Jul 27 17:19:25  mono[13543] <Warning>: void CGSUpdateManager::log() const:  31  ???                                 0x00692fe0 0x0 + 6893536

Immediatelly after this message, the much anticipated CornFlowerBlue window open successfully.

Now I can't reproduce this issue on this machine, but the same behavior happened on my friend's Mac.

Environment:
OS X El Capitan, Version 10.11.5 (15F34)

Mono JIT compiler version 4.4.1 (mono-4.4.0-branch-c7sr0/4747417 Mon Jun 20 15:43:48 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           normal
    SIGSEGV:       altstack
    Notification:  kqueue
    Architecture:  x86
    Disabled:      none
    Misc:          softdebug 
    LLVM:          yes(3.6.0svn-mono-master/a173357)
    GC:            sgen

Monogame assembly version: 3.5.1.1679
From Nuget.

I always thought the Monogame was frozen, and end up killing the process, until I decided to let it run for a long time, and it finally opened, now I can't reproduce this behavior.

Restarting the machine did not fix the issue,
Creating another project did not fix the issue,
Running via command line did not fix the issue,
I don't remember if a Release build also had this behavior.

It could only be solved after waiting the executable fix itself.

Did anyone face this long (2+ minutes) time on opening Monogame for the first time?

**Comment by kennethsuda** [comment]
I have not noticed any extended startup for the MonoGame apps I have been testing with. You might add what yours and your friend's screen resolutions are and what Graphics card each machine has. I am using El Capitan 10.11.6, so one point release later than you. My graphics is NVIDIA GeForce GT 330M 512MB and the native resolution is 1920x1200 of my primary monitor. It appears that several other graphics intensive applications had errors at similar points with a similar description to yours towards the end of last year. You might also try creating a new test app with a different name (new solution) to see if you can make it happen again on your machine. Lastly, you didn't specify which template you use. Perhaps a MG developer can tell, but I can't. I would guess MacOS using xamarin.mac, but it could be one of the others. From the readable part of the stack trace, the default entry point for NSWindow is the one listed.

**Comment by joao-moraes-petitfabrik** [comment]
1 - I can't reproduce this issue by creating another project

2 - The project template I've used was Monogame Cross Platform Desktop Project, but I remember trying with other templates as well (MonoMac).

3 - My mac is a MacBook Pro (Retina, 13-inch, Mid 2014): https://support.apple.com/kb/sp703?locale=en_US

It has an Intel Iris graphics card. My friends mac is the same model.
It says under my Graphics section on About This Mac
Intel Iris 1536 MB

4 - Display resolution is 2560x1600, with the Default scale option selected.

**Comment by Jjagg** [comment]
I'm gonna close this because the OP stated this only happened in MonoMac projects and those are no longer supported.
