### ISSUE TITLE
3.6 Dev Pipeline Tool UX

### ISSUE THREAD

**Issue by lozzajp** [MonoGame/MonoGame#5038]
@cra0zy was told you like the UX issues!

I am using Windows 10 with the latest dev build (28 July 2016). The pipeline has some funny resizing issues as seen below. I did steps 1-5 in order.

1: To get that build action dropdown menu I had to double click (I think before at home on win 7 its just already there).

2: resized the internal window and the dropdown selector part stays where it was. (see 6 for a bad one)

3: Clicking again jumps it back to full size.

4-5: Resizing the internal bit again makes the small window scrollable, you have to scroll to far right to drop down again etc.

6:  a bonus image showing it quite getting in the way.

![pipe](https://cloud.githubusercontent.com/assets/16327815/17216147/5a091708-54d7-11e6-879f-9c519e9be952.png)

**Comment by cra0zy** [comment]
I have 3 PRs which are improving various things in the pipeline tool (#4998 #5005 #5010), I'll look into adding some improvements from this issue once they are merged.

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
