### ISSUE TITLE
3.6 Dev Pipeline Tool can't use new importer/processors without restart

### ISSUE THREAD

**Issue by lozzajp** [MonoGame/MonoGame#5039]
I setup a new project and added MG Extended, opened the pipeline tool and referenced the extended pipeline DLL and then added a tilemap, but the pipeline tool wouldn't let me select any MG Extended processors or importers.

I restarted the pipeline tool and then it allowed me.

Windows 10
Desktop DX Project
MG 3.6 (Dev build 28 July 2016)
Latest stable MG Extended.

**Comment by cra0zy** [comment]
@tomspilman This can be closed, #5154 fixed this.
