### ISSUE TITLE
SharpDX gets wrong resolution causing crash on startup

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#5040]
@tomspilman #5024 caused this issue (the commit before it worked fine). [`monitor.Description.DesktopBounds`](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsAdapter.DirectX.cs#L66) gets incorrect values (1536, 864) which is not a known displaymode for my graphics card, causing adapter._currentDisplayMode not to be set. `GraphicsDevice.DisplayMode` will be null and so [`GraphicsDevice.Setup`](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.cs#L218) will fail with a `NullReferenceException`.

Looks like this is an issue with SharpDX or maybe incorrect use of the API? I couldn't find this in SharpDX source, so maybe this was a bug that is fixed or API changed. I just updated my graphics drivers, but that didn't help.

**Comment by tomspilman** [comment]
> `monitor.Description.DesktopBounds` gets incorrect values (1536, 864) 

Incorrect how?  Is your desktop not 1536x864?  What is your desktop resolution?

Could this maybe be a high DPI issue?

>  or maybe incorrect use of the API?

Most likely that.   While the unit tests I wrote passed and produced the same results as XNA on my system...  it may have issues on other systems.

We just need to make fixes and expand the tests to expose issues we missed.

**Comment by Jjagg** [comment]
Desktop resolution is 1920x1080, I should've mentioned that.

**Comment by Jjagg** [comment]
So I just tried changing the resolution to 1280x800 just to see what values I'd get and SharpDX got the right resolution. Changed it back to 1920x1080 and I get 1536x864 again.

**Comment by tomspilman** [comment]
Do you have a single monitor on this system?  Or is it maybe a multi-monitor setup?

Do you maybe have settings to make fonts/ui larger enabled?  This is under "Control Panel -> Display".

**Comment by Jjagg** [comment]
I'm on my laptop with no additional monitor, but 

> Do you maybe have settings to make fonts/ui larger enabled?

That might be it. I'll try setting the default.

**Comment by Jjagg** [comment]
On Windows 10 under Settings->System->Monitor scale of "fonts, apps and other items" was set to 125%. Changing that to 100% did fix the issue :)

**Comment by tomspilman** [comment]
So this means `DesktopBounds` as returned by SharpDX is scaled and cannot be trusted to be the true desktop bounds for that monitor.

I'll see if I can come up with a more reliable way to get the resolution.

**Comment by Jjagg** [comment]
Thanks for the quick response @tomspilman :+1:

**Comment by tomspilman** [comment]
@Jjagg - Can you give this PR a test...  https://github.com/mono/MonoGame/pull/5043

**Comment by hach-que** [comment]
Just got bit by this... spent about 6 hours today remote debugging a machine to find out why we were getting a null reference exception on startup and this turned out to be the issue.

Is it worth adding a check to see if the current display mode is null, and if so, throwing a more detailed exception, in particular one that mentions that you need to make your game HiDPI aware? (especially since the templates will only assist people starting new projects now)
