### ISSUE TITLE
SoundEffect issue in UWP on Xbox One

### ISSUE THREAD

**Issue by endimilojkoski** [MonoGame/MonoGame#5055]
When testing the game on Xbox One as UWP everything works great except for strange SFX behavior.

When I start it, SFX work with no issues, start a match and everything is OK even with 16 players at once, then I go to menu and SFX completely stop playing but the game runs fine.
And after some time SFX will continue playing with no issues and this repeats while playing.

This is not happening when I test the UWP project on Windows 10, sound is always playing as it should be.

And another thing, if I Deploy the Release version to Xbox One the SFX are not playing at all but there are no issues if I play it on Windows 10.

And I am testing with latest dev build version, got it just before I wrote this.

@tomspilman @cra0zy

**Comment by tomspilman** [comment]
Are you just using `SoundEffect`/`SoundEffectInstance` directly or are you using XACT?

**Comment by cra0zy** [comment]
He is using SoundEffect.Play()

**Comment by cra0zy** [comment]
SoundEffectInstance.Play() radi, bug se dogadja samo u SoundEffeect.Play na Xbox One-u

**Comment by endimilojkoski** [comment]
Yes this fixes the issue but now I have another issue.
When I play with 8 or more players and when a lot of SFXs are played at once the sound breaks and becomes distorted and it stays distorted until I exit and restart the game.

**Comment by endimilojkoski** [comment]
Last issue is also fixed with @cra0zy 's solution added in game code to manually dispose SoundEffectInstances that have stopped running.

Now the game is working as it should on Xbox One as UWP! Thanks guys!

**Comment by tomspilman** [comment]
>Great, this fixes the issue but now I have another issue.

What fixed the issue?  I don't see any solution mentioned here.

> when a lot of SFXs are played at once the sound breaks and becomes distorted 

That can happen if there is too much CPU load as the system tries and fails cannot mix all the sound effects fast enough to not leave gaps and artifacts in the mastering voice.  Likely you have way too many sounds playing at once.

It probably isn't happening on your PC because your PC has more CPU power than the resource limited UWP apps on XB1.

> manually dispose SoundEffectInstances that have stopped running.

Yes you should be disposing `SoundEffectInstances` after they are done playing.

**Comment by cra0zy** [comment]
> What fixed the issue? I don't see any solution mentioned here.

Yup, not a fix, just a workaround.

**Comment by endimilojkoski** [comment]
> What fixed the issue? I don't see any solution mentioned here.

"SoundEffectInstance.Play() works, bug is only happening with SoundEffect.Play() on Xbox One."

I was playing the SFX through SoundEffect.Play() but after I switched to creating SFX instance and playing the instance it was all good.

**Comment by endimilojkoski** [comment]
Since this is working properly when coded like mentioned above I think I can close it.

**Comment by cra0zy** [comment]
It's not working properly, leave it open, it's just that you have a workaround.

**Comment by KonajuGames** [comment]
Reopened. There is a workaround, but we should find the underlying issue.

**Comment by sevenstreak** [comment]
Does this ticket still need to be open?

**Comment by cra0zy** [comment]
Yup, its still a bug...

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
