### ISSUE TITLE
Add IEffect interface, so alternative implementations of Effect can be used

### ISSUE THREAD

**Issue by hach-que** [MonoGame/MonoGame#5057]
I'm currently working on implementing a render batching pipeline for 3D rendering in Protogame, and I need some way of imitiating the "Effect" class without actually having the costs associated with it.  The current render context in the engine has an `Effect` property with the `Effect` type on it.

In particular, a lot of the code currently looks like:

```

// do some setup on effect, like setting parameter values etc.

renderContext.PushEffect(effect);

someOtherApi.DoSomeRenderingWithCurrentEffect();
```

which internally then calls renderContext.Effect or whatever.

I'd like to be able to have a fake Effect, one that the render batcher can provide which tracks all of the state changes made to the effect and it's parameters (like setting of textures and other values) as the game's render loop runs.

Once the render loop is about to finish, the render batcher would then look at all of the render requests that came through, sort them based on the most optimal way to run them (i.e. group requests where the effect and effect parameters are the same) and then push them to the GPU, reducing the number of draw calls to make.  I want to basically take the game render loop, which may render a whole bunch of different things with different effects, and combine them together into very few draw calls, potentially also making use of `DrawInstancedPrimitives` to reduce it even further.

However, so much of the code is coupled to the Effect API, and because this is a concrete class, it makes it hard to use the API without incurring associated costs, or without the render batching having to clone the effect and it's parameters on every request (itself an expensive operation).

I can't just switch out Effect with some other common API either, because it implements no interfaces, and I want render batching to be optional; if you don't want to use render batching, you shouldn't have to, so it's important that the effect setup can actually be a real effect when needed, and not a fake effect supplied by the render batcher for the purposes of tracking changes.

My proposal is to add an `IEffect` interface and potentially an `IEffectParameter` interface, where their signatures would match the current public APIs of the `Effect` and `EffectParameter` classes.  This would allow me to transparently replace effect with a fake tracking version as needed.

**Comment by tomspilman** [comment]
> My proposal is to add an `IEffect` interface 

I don't think we want to do this.

Interfaces in C# are some of the slowest function calls you can make.  Adding interfaces here will only encourage more people to suggest put interfaces into everything.  It is a bad precedent to set and the wrong direction for MonoGame.

http://tips.x-tensive.com/2008/10/method-call-performance.html

@KonajuGames  @dellis1972 ?

**Comment by KonajuGames** [comment]
We have rejected suggestions to add interfaces to other classes before, primarily for the same performance reasons.

**Comment by hach-que** [comment]
So I'm pretty sceptical that that blog post really has any relevance in today's .NET world.  Our entire game engine uses interfaces for everything, and I've never in the past 5 years experienced any issue where using virtual method calls were the source of a performance problem.  Unfortunately the blog post author provides no actual test code, so I've had to construct my own tests based on what was written in the blog post.

The summary: I've run my own tests and they show no significant difference between virtual method calls and interface calls, regardless of whether the interface is explicit or implement (and explicit interfaces have no impact on other method calls).

---

I set up a basic performance test, built in Release mode, which cycles through the same method call 600,000,000 times:

```csharp
var stopwatchnv = Stopwatch.StartNew();
var classnv = new ClassVirtual();
for (var i = 0; i < 600000000; i++)
{
    classnv.Test();
}
Console.WriteLine("Class with non-virtual method: " + stopwatchnv.ElapsedMilliseconds);
```

In each test, `new ClassVirtual();` changes to something else; the following:

- `new ClassVirtual();`
- `new ClassWithExplicitInterface();`
- `(IInterface) new ClassWithExplicitInterface();`
- `(IInterface) new ClassWithImplicitInterface();`

The results on running these tests 10 times, on average is:

```
Summary: Class with virtual method: 1088
Summary: Class with explicit interface, accessed via method: 931.7
Summary: Class with explicit interface, accessed via interface: 1577
Summary: Class with implicit interface, accessed via interface: 1251.3
```

Those numbers might looks significant, but if you consider the per method cost on each iteration, it works out to be:

```
Summary: Class with non-virtual method: 0.0000018333 milliseconds per call
Summary: Class with implicit interface, accessed via interface: 0.0000020855 milliseconds per call
Difference: 0.0000002522 milliseconds per call
```

You could argue that this is still a difference, even though the scenario is almost a spin-wait on the CPU (and not representative of calling say, `Effect.Apply` at all).  So I decided to benchmark this against C, which is arguably the language you should be using if you're caring about **literally a quarter of nanosecond of difference** in a method call:

```
Force variable reference: 6000000000
Milliseconds elapsed: 538
```

The answer is: C wins.

This is trying my hardest to actually get a number on the millisecond count, using `long long`s and printing the variable number at the end.  If you attempt to replicate the exact scenario that C# is running, you just get 0 milliseconds on the clock.

---

As such, I don't believe these performance concerns actually represent a real scenario for the following reasons:

* The measured difference on each method invocation is 0.25 nanoseconds.
* Over 600 million invocations, it's a difference of 200 milliseconds.
* If you're running into performance issues at this level, you should be considering writing your logic in C, and using P/Invoke.
* Of interesting note, just adding an explicit interface to a class makes invocation of the non-interface methods _faster_ by about 120 milliseconds.
* None of this is even remotely relevant when you're considering `EffectPass.Apply`, which has the CPU -> GPU interaction as a bottleneck anyway.

**Comment by tomspilman** [comment]
> which cycles through the same method call 600,000,000 times:

Your test looks to not be well written.

If the compiler/jit knows the object at the call site can only be a specific type... it will avoid calling the interface call because it is slower.  The example you wrote suggests this is what is happening.   You can verify by looking at the disassembly on the call.

If you try this instead: 
```
void DoTest(IInterface iface)
{
   var stopwatchnv = Stopwatch.StartNew();
   for (var i = 0; i < 600000000; i++)
   {
       iface.Test();
   }
   Console.WriteLine("Class with non-virtual method: " + stopwatchnv.ElapsedMilliseconds);
}
```
The compiler can't peek at the type and optimize away the interface call.

Second thing the JIT does is cache the interface method lookup when it sees you are calling the same interface repeatedly.  If you pass a small array of `IInterface` types for the test to run over it has no choice but to avoid the caching and do the lookup on each interface call.

**Comment by KonajuGames** [comment]
I would also suggest trying the same test on mobile devices.

**Comment by hach-que** [comment]
Sorry, no dice on those test modifications.  Here's the new invocation of the test:

```csharp
Test2(new IInterface[]
{
    (IInterface)new ClassWithExplicitInterface(),
    (IInterface)new ClassWithExplicitInterface(),
    (IInterface)new ClassWithExplicitInterface(),
    (IInterface)new ClassWithExplicitInterface(),
    (IInterface)new ClassWithExplicitInterface(),
    (IInterface)new ClassWithExplicitInterface(),
    (IInterface)new ClassWithExplicitInterface(),
    (IInterface)new ClassWithExplicitInterface(),
    (IInterface)new ClassWithExplicitInterface(),
    (IInterface)new ClassWithExplicitInterface(),
}, ref xpims);
```

And here's the test itself:

```csharp
static void Test2(IInterface[] classxpi, ref float xpims)
{
    var i1 = classxpi[0];
    var i2 = classxpi[1];
    var i3 = classxpi[2];
    var i4 = classxpi[3];
    var i5 = classxpi[4];
    var i6 = classxpi[5];
    var i7 = classxpi[6];
    var i8 = classxpi[7];
    var i9 = classxpi[8];
    var i10 = classxpi[9];
    var stopwatchxpi = Stopwatch.StartNew();

    for (var i = 0; i < 60000000; i++)
    {
        i1.Test();
        i2.Test();
        i3.Test();
        i4.Test();
        i5.Test();
        i6.Test();
        i7.Test();
        i8.Test();
        i9.Test();
        i10.Test();
    }
    stopwatchxpi.Stop();
    Console.WriteLine("Class with explicit interface, accessed via interface: " +
                        stopwatchxpi.ElapsedMilliseconds);
    xpims += stopwatchxpi.ElapsedMilliseconds;
}
```

This actually makes it faster:

```
Summary: Class with explicit interface, accessed via interface: 1177
```

If you attempt just a test with a single interface passed through:

```csharp
Test2((IInterface)new ClassWithExplicitInterface(), ref xpims);
```

```csharp
static void Test2(IInterface classxpi, ref float xpims)
{
    var stopwatchxpi = Stopwatch.StartNew();

    for (var i = 0; i < 600000000; i++)
    {
        classxpi.Test();
    }
    stopwatchxpi.Stop();
    Console.WriteLine("Class with explicit interface, accessed via interface: " +
                        stopwatchxpi.ElapsedMilliseconds);
    xpims += stopwatchxpi.ElapsedMilliseconds;
}
```

It's still not a significant deviation from the norm:

```
Summary: Class with explicit interface, accessed via interface: 1614.4
```

**Comment by Jjagg** [comment]
I'm all for this if the performance cost is negligible in actual games, so I hope it is. Using more interfaces will open up options to expand beyond XNA and will make room for useful tools like this one. 

Is the performance cost also the reason #4720 did not get any love? I thought that was a nice PR.

**Comment by KonajuGames** [comment]
> Is the performance cost also the reason #4720 did not get any love? I thought that was a nice PR.

Looking at that one, it wasn't anything about performance.  It was an unexpected big PR (they're always a harder sell), we've been busy with contract work and unfortunately it got lost among the many other PRs.

**Comment by hach-que** [comment]
Since it didn't look like this was going to move anywhere, I ended up writing an intermediate layer in my engine to proxy and cache all modifications to effects.
