### ISSUE TITLE
Track DynamicSoundEffectInstances so they can be disposed

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#5064]
For **XAudio**, when there are voices that are not yet disposed when [MasterVoice is disposed](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffect.XAudio.cs#L351) a crash will occur as noted in [`SoundEffect.Shutdown`](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstancePool.cs#L160). This caused our unit tests to fail in #5042. 

We currently have [`SoundEffectInstancePool`](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstancePool.cs) to manage all SoundEffectInstances (and dispose of them in the Shutdown method) and [`DynamicSoundEffectInstanceManager`](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/DynamicSoundEffectInstanceManager.cs) to manage **playing** DynamicSoundEffectInstances, but not ones that are not currently playing. I suggest we let the DSEIManager handle this by having it keep a WeakReference to all instances that are not playing as well.

**Comment by KonajuGames** [comment]
It makes sense to add it to `DynamicSoundEffectInstanceManager`.

**Comment by KonajuGames** [comment]
Should also rectify the use of WeakReference as described in #5070 while in there.

**Comment by Jjagg** [comment]
Can I do this in #5056 or should I do a seperate PR?

**Comment by KonajuGames** [comment]
Make it a separate PR.  #5056 doesn't touch the manager, so keep those fixes in a new PR.
