### ISSUE TITLE
apply3d soundeffect throws an exception

### ISSUE THREAD

**Issue by tchekjunior** [MonoGame/MonoGame#5066]
hi, 
there is a problem when trying to apply 3d  "SoundEffect".
the code bug with this message: An unhandled exception of type 'System.AccessViolationException' occurred in SharpDX.XAudio2.dll.

I read this discusion on the monogame forum: [http://community.monogame.net/t/solved-accessviolationexception-in-soundeffectinstance-apply3d-l-e/1980/3]

my ".wav" file in stereo. it would be very difficult to change that at the current level of my project.

Please if anyone has an idea to resolve this issue?
ps : I have lastest version on monogame on develop branch.

**Comment by tchekjunior** [comment]
hi,
no body have idea how to fix that issue?

**Comment by tomspilman** [comment]
Generally in most audio systems you cannot appl

**Comment by tomspilman** [comment]
In many audio systems you cannot apply 3D positioning to stereo sounds...  but XNA suggests that it could by discarding the stereo data.

First thing... can you give me the full callstack of the crash?

**Comment by tchekjunior** [comment]
hello Mr Spillman , thank you for your reply.
This is my "full callstack", I hope what help you understand the problem

![screen shot 08-09-16 at 04 50 pm](https://cloud.githubusercontent.com/assets/4943931/17523299/fbd9f70e-5e51-11e6-92f9-d7f08d5f46b3.PNG)

![screen shot 08-09-16 at 04 52 pm](https://cloud.githubusercontent.com/assets/4943931/17523367/3a712c76-5e52-11e6-8c7f-9e082a3a9110.PNG)

This zip contains my stereo sound .wav and .XNB
[sound pack](https://drive.google.com/file/d/0B9IHjQmx0e1fX0lYT0FFTDljblE/view?usp=sharing)

**Comment by tomspilman** [comment]
Looks like a failure to call or within `X3DAudioCalculate`.
 
 https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.x3daudio.x3daudiocalculate(v=vs.85).aspx

This will take someone running this case thru the debugger and seeing specifically where the issue is coming from.  Could be we're just misusing the API here.

**Comment by tchekjunior** [comment]
I do not know if it helps, but when I remove the flag "CalculateFlags.Matrix", the function will run very well, so in my opinion it is the calculated matrix that has a problem.
