### ISSUE TITLE
Wrong usage of weakreferences in DynamicSoundEffectInstanceManager

### ISSUE THREAD

**Issue by trommlbomml** [MonoGame/MonoGame#5070]
I already commented this in the commit, but seems to be ignored or something.

In DynamicSoundEffectInstanceManager.UpdatePlayingInstances() is an iteration over all playingInstances with a check of IsAlive and getting the target of a WeakReference. This can generate in very rare cases NullReferenceExceptions because the GC removes the instance between these lines of code.

The check should - like in all other cases of weak references I found in the source code - check Target directly to null.

**Comment by KonajuGames** [comment]
It's on our radar.  There was some other work going on in there, and I've added this note to it.

**Comment by trommlbomml** [comment]
Thank you very much :) 

Sry for the extra issue, but I had two issues in different libraries where this kind of problems which creates very rare crashes in a commerical software I am working on :)
