### ISSUE TITLE
Pipeline: cannot add file to newly created folder

### ISSUE THREAD

**Issue by InfiniteProductions** [MonoGame/MonoGame#5080]
Don't know if it is linked to #5079 or not:

create new folder "folder1" (name truncated to "older1")
Add an existing file
=> error pop-up: "An error occured while the files were being copied, aborting."

file not added to folder

Adding a file the exact same way using an **existing** folder (also added to the project) works.

as #5079: windows 7 64b latest pipeline dev build
(also: these two issues may happened because a new project is create from pipeline tool itself)

**Comment by cra0zy** [comment]
@tomspilman This and #5079 are fixed.
