### ISSUE TITLE
SharpDX error when using texCUBElod / SampleLevel

### ISSUE THREAD

**Issue by Sizaar** [MonoGame/MonoGame#5094]
Every time when I use `texCUBElod(SamplerName, float4(SampleLocation, MipLevel))` or `TextureName.SampleLevel(SamplerName, SampleLocation, MipLevel)` and try to load an effect with `Content.Load<Effect>("Here/Goes/My/Fancy/Effect");` I get an error:

> An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll
> Additional information: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

Edit: 
Actually the same thing happens when I try to use `texCUBE(SamplerName, SampleLocation)` or `TextureName.Sample(SamplerName, SampleLocation)` under **vs_4_0**/**ps_4_0**. 
It works properly under vs_4_0_level_9_1/ps_4_0_level_9_1 and vs_4_0_level_9_3/ps_4_0_level_9_3.

PS. The effect compiles fine and the error occures during loading time.

**Comment by Jjagg** [comment]
Is your GraphicsProfile set to HiDef? To do this, in your game constructor do `graphics.GraphicsProfile = GraphicsProfile.HiDef` where graphics is your GraphicsDeviceManager. If you don't do this in your constructor you need to call `graphics.ApplyChanges()` afterwards. Let me know if this helped.

**Comment by Sizaar** [comment]
Ah, using `graphics.GraphicsProfile = GraphicsProfile.HiDef;` indeed helps, but MonoGame should check automatically if it is HiDef or Reach. Thanks Jjagg :smiley:!

**Comment by Jjagg** [comment]
> MonoGame should check automatically if it is HiDef or Reach

I think it's good that it's explicit, because you should be aware of the GraphicsProfile your game uses. But a lot of people run into this, maybe we can try to throw more descriptive exception for this...
