### ISSUE TITLE
[WinDX] Opening Steam overlay results in "stuck" keys

### ISSUE THREAD

**Issue by MichaelDePiazzi** [MonoGame/MonoGame#5122]
I'm currently working on Steam integration with my game and I came across an issue when opening the Steam overlay. The Shift and Tab keys (which you press to open the overlay) end up getting "stuck" in the game. I'm assuming this is because the Steam overlay intercepts all the key events, so MonoGame never sees the "release" events for these keys.

I'm having this problem with the WinDX build, but I imagine it also affects other desktop builds. (UPDATE: This actually seems to only affect MonoGame DirectX. Both XNA and MonoGame SDL2 work correctly.)

My current workaround to this issue is to clear MonoGame's internal key buffer (i.e. `Keyboard._keys`) whenever the Steam overlay is opened or closed. However given this is not publicly exposed, the only way to do this is by changing MonoGame to expose it or by using reflection. I am not sure if this is the best way of dealing with this, but it seems to work well.

Has anyone else experienced this particular problem? And if so, how did you solve it?

And if my workaround seems reasonable, would it be acceptable to add this to the MonoGame API (e.g. a `Keyboard.Flush` method which clears the buffer)? If so, I'm more than happy to submit a PR.

**Comment by KonajuGames** [comment]
It makes sense to clear the keys when the overlay is opened. I wouldn't
object to a Flush() method being added, though it probably also applies to
mouse and gamepad as well.

@tomspilman @dellis1972

**Comment by MichaelDePiazzi** [comment]
> it probably also applies to mouse and gamepad as well.

I just tested mouse and gamepad with the Steam overlay and could not get it to "stick"any inputs like it does with the keyboard.

Looking at the code, this is because keyboard input keeps track of key down/up events (so a missed key up event results in a stuck key). Whereas mouse and gamepad only take snapshots of the current state which means they can't get "stuck". So this also means that there's technically nothing to flush for mouse and gamepad since nothing is being buffered.

So based on this, I believe flushing is only required for keyboard.

**Comment by tomspilman** [comment]
Ideally we would solve this internally to MonoGame and not need to add a method like this.

We already clear any key state when the game window has lost focus.  Is there any other type of event like this that occurs when the Steam overlay appears?

@dellis1972 - Did you run into this with Mac/Linux on Steam?

**Comment by MichaelDePiazzi** [comment]
@tomspilman I agree that ideally we should try solve this internally. Although I'm not sure what events we could look at to reliably detect this. I'm currently using the actual game overlay activated event from the Steam API (which we obviously can't use in MonoGame).

I did take a quick look at the windows messages though and I noticed a couple of user messages which only show up when the Steam overlay is loaded. The one that seems to correlate to the overlay opening is 0x14FA. However, I can't find any documentation confirming this so this is only a best guess.

**Comment by tomspilman** [comment]
> The one that seems to correlate to the overlay opening is 0x14FA. However, I can't find any documentation confirming this so this is only a best guess.

Could be an undocumented feature...  we would have to test for it on other systems and games too.  Still hard to say if we can trust it or not.

Does this issue occur with XNA?  If not it is purely a problem because of how we generate keyboard state... which we could fix to avoid the issue entirely.

@mrhelmut - Do you have this issue with the MonoGame SDL2 backend?

**Comment by theZMan** [comment]
We never had any stuck keys with xna and steam in guncraft though that was
a couple of years ago now...

**Comment by mrhelmut** [comment]
No problem with SDL2 in regard to this issue.

**Comment by tomspilman** [comment]
Thanks @theZMan and @mrhelmut .

I think the best fix here is improving our keyboard support in the WinDX version of MonoGame.  It should work like XNA and our SDL2 backend.

I think that is preferable to adding a `Flush()` API here.

**Comment by MichaelDePiazzi** [comment]
Confirmed that XNA and MonoGame SDL2 work correctly. I've updated the issue to clarify this only seems to be a WinDX issue.

A quick look at SDL2 shows that it uses a similar method to WinDX (i.e. keeping track of key down/up events). So the difference must be that SDL2 actually gets the key up events when the overlay is opened, whereas DX doesn't for some reason. I'll try take a closer look into this today and see what can be done.

**Comment by MichaelDePiazzi** [comment]
@tomspilman
I had a good look at this, and had no luck getting the DirectX RawInput key events to work correctly with the Steam overlay. However, I did come across an alternative method using `GetKeyboardState` from the Windows API ([StackOverflow post](http://stackoverflow.com/a/10484282), [MSDN docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646299(v=vs.85).aspx)). I quickly hacked this into MonoGame and confirmed that it does play nicely with the Steam overlay.

This method requires a polling based approach though rather than an event triggered approach. I believe this should be fine from a performance perspective if we only call it when `Keyboard.GetState()` is actually called. It should be a lot more reliable also because it can't miss any key events like the current approach can.

What do you think? If you're ok with this solution, then I'll submit a PR for it.

**Comment by tomspilman** [comment]
> What do you think?

I think this might be the right path.  It is highly likely XNA's `Keyboard.GetKeyboardState()` was designed around that API to begin with.  I wouldn't be surprised if that is what XNA did internally.

@KonajuGames @dellis1972 ?

**Comment by KonajuGames** [comment]
That sounds like a better approach.

**Comment by MichaelDePiazzi** [comment]
I've just submitted PR #5129 which implements this. Let me know what you think.
