### ISSUE TITLE
SoundEffects not playing under linux, causing program to segfault

### ISSUE THREAD

**Issue by define-private-public** [MonoGame/MonoGame#5128]
I'm using MonoGame 3.5 (fresh off of the download pages) in MonoDevelop under Ubuntu Linux (16.04).  I created a new project using the template in the "New Project Wizard."  I tried to add a simple `SoundEffect` and have it play once every two seconds in my `Update()`.  It's loaded properly in my `LoadContent()` function.  It's throwing a `NullReferenceException` when I call `Play()` with the message:

```
Object Reference not set to an instance of an object
```

Someone said it might be related to this here: http://community.monogame.net/t/null-reference-exception-when-calling-play-on-a-soundeffect-or-soundeffectinstance/7319/10

On top of that, the reference `MonoGame.Framework`, `OpenTK` and `NVorbis` are reported missing on the solution explorer, but I can still open a Window and display some sprites.

To add to the weirdness, some older MonoGame apps i've written (in Linux) with older versions of MonoGame are working just fine.

**Comment by mrhelmut** [comment]
DesktopGL platform has been heavily reworked to drop OpenTK in favor to SDL2. Would you mind trying the latest development version? It boasts tons of improvements regarding Linux support.

**Comment by define-private-public** [comment]
Is there a link to build from source?  Or a development PPA?

**Comment by Jjagg** [comment]
You can get the latest development build from the [Downloads](http://www.monogame.net/downloads/) section of MonoGame.net (scroll down a bit) or you can build from source. Instructions for building from source are in the README of this repo.

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
