### ISSUE TITLE
Installer not recognizing Visual Studio Express 2013

### ISSUE THREAD

**Issue by pyorokun7** [MonoGame/MonoGame#5132]
Greetings, for an online course with MonoGame, I downloaded the installer for version 3.5.1.1679 of MonoGame.

At first I thought I could only use Visual Studio 2010 for the assignments, specially because the installer only showed me the option to install the templates for 2010, but later I realized that VS Express 2013 was installed (I'm using a friend's computer) However, when I reran the installer, the option for 2013 was still grayed out, and yes, I ran Visual Studio 2013 at least once before trying.

Checking previous issues like #4612 or #4782, I checked the registry, and I can't see a UserProjectTemplatesLocation key in HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\12.0

However, it does exits in HKEY_CURRENT_USER\Software\Microsoft\VWDExpress\12.0

Is this an issue of the instalation of VS2013 in this computer, not creating the key in the other location? Or the installer is failing to check the key for Express?

Thanks in advance.

**Comment by hach-que** [comment]
You're probably better off using Visual Studio 2015 Community - there's no reason to use VS2013 as far as I'm aware (and the Express editions don't support extensions which is probably your issue).

**Comment by pyorokun7** [comment]
Not sure what do you mean with "don't support extensions", but both Express 2010 and 2013 work well with MonoGame projects (so long as you don't close the project in 2010, when you try to open a MonoGame project with 2010, it does have problems)

I even just created the key in VisualStudio\12.0 and copied the value from VWDExpress\12.0, reran the installer which detected and installed 2013 without issues, and have been working on 2013 since them flawlessly.

**Comment by Jjagg** [comment]
Closing in favor of #3808.
