### ISSUE TITLE
Keyboard pause key is mapping incorrectly

### ISSUE THREAD

**Issue by vcrobe** [MonoGame/MonoGame#5134]
Hi,

I'm building a game using Windows 10/Direct X using the last release of MonoGame 3.5.1 and I'm trying to use the _Pause/Break_ key with this statement

    if (Keyboard.GetState().IsKeyDown(Keys.Pause)) { ... }

but the condition is always false.

Trying to figure out what was happening I wrote this statement in the Update method

    var k = Keyboard.GetState().GetPressedKeys();

When I press the _Pause/Break_ key I get this result

    k[0] = LeftControl

**Comment by Jjagg** [comment]
Hmm, the int value of the Keys.Pause enum value at least matches XNA, there is a test for that [here](https://github.com/MonoGame/MonoGame/blob/develop/Test/Framework/EnumConformingTest.cs#L429), so either it's a hardware thing or something goes wrong earlier when fetching the input. @vcrobe By any chance did you test this in XNA?

**Comment by vcrobe** [comment]
@Jjagg No, I didn't test it in XNA I'll do that tonight but suppose it returns the same result in XNA, is that OK?

Then how can I use the Pause/Break key? Because I want to be able to differentiate the Left Control Key and the Pause/Break key!

PD: I'm using the last release 3.5.1.

**Comment by Jjagg** [comment]
Thanks! I'll look into this. This is definitely a bug and it needs to be fixed.

**Comment by Jjagg** [comment]
Tried this and got the same results as you, so this is a bug.

**Comment by MichaelDePiazzi** [comment]
I tried this also with the current Windows DirectX build and got the same result. However, I tested this with the recent PR (#5129) I did for another DirectX keyboard issue and found that it also resolves this. Give it a try and let me know if this fixes it for you.

**Comment by tomspilman** [comment]
Good call @MichaelDePiazzi ...  I bet your PR fixes this.

**Comment by Jjagg** [comment]
Neat! If it works for you I'm pretty sure you fixed it :)

**Comment by Jjagg** [comment]
@MichaelDePiazzi The mapping is correct with #5129, but when holding down the Pause key it only registers the first frame (or maybe for a few frames, I'm just doing a simple test so I'm not sure). I'm thinking this may be a hardware thing because of the nature of the Pause key?

**Comment by MichaelDePiazzi** [comment]
@Jjagg This works fine for me. If I hold the Pause key down, it stays registered as being pressed. It behaves the same way for me under XNA also. So maybe it is a hardware specific thing... Does it behave the same way for you under XNA also?

**Comment by Jjagg** [comment]
Same in XNA, so this is hardware. I guess this can be closed then? @MichaelDePiazzi

**Comment by vcrobe** [comment]
So there's no way to use the Pause/Break key?

**Comment by Jjagg** [comment]
Did you read this thread? It's working after #5129, so if you grab the develop build or build from source it should work.

**Comment by MichaelDePiazzi** [comment]
@vcrobe As I mentioned earlier, I'm fairly sure PR #5129 also fixed this issue. Please test it and let us know if it works for you or not.

If you are not comfortable compiling this yourself, then you can download the binaries for this PR from here: http://teamcity.monogame.net/repository/download/MonoGame_DevelopWin/23428:id/MonoGame.Framework.zip
Or the installer: http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/23437:id/MonoGameSetup.exe

**Comment by vcrobe** [comment]
@MichaelDePiazzi yesterday I did the test with the assembly located at _Windows_ folder and it works as expected.

**Comment by MichaelDePiazzi** [comment]
@vcrobe Cool, glad to hear it's working! :)
