### ISSUE TITLE
[Pipeline Tool] Resolve Relative Path

### ISSUE THREAD

**Issue by Kwyrky** [MonoGame/MonoGame#5135]
If i have the shader and the include file in the same directory, the pipeline tool is compiling the shader, if i put this line into the shader: #include "ShaderModel.fx"

If the shader is in a directory and the include file relative to the sahder two dirs up and inside the include folder, the shader is not compiling with this line:
```#include "..\..\include\ShaderModel.fx"```

**Comment by tomspilman** [comment]
@Kwyrky 

Flip the slashes:

```
#include "../.../include/ShaderModel.fx"
```

**Comment by Kwyrky** [comment]
Thank you, it worked.
