### ISSUE TITLE
Add Localization  Content Processors and Methods to MG

### ISSUE THREAD

**Issue by dellis1972** [MonoGame/MonoGame#5136]
XNA had a sample for dealing with localised assets [1]. I think it might be a  good idea to add these as default processors to the MG content Pipeline so they are just built in.

So Im proposing we add the  `LocalizedFontDescription` and `LocalizedFontProcessor` code from the sample and then add a new method to the contentManager

`T LoadLocalized<T>(string assetName)`

People can then have the choice of loading using the standard Load method or using the other if that asset has a localized version.

[1] http://xbox.create.msdn.com/en-US/education/catalog/sample/localization

**Comment by tomspilman** [comment]
I don't have a problem with this as long as the localization solution provided was robust and the best way to do things for MonoGame titles.
