### ISSUE TITLE
Select multiple content items in the Content app

### ISSUE THREAD

**Issue by energyuser** [MonoGame/MonoGame#5140]
In the old Content Pipeline tool I could use CTRL + Left Click to select multiple items. Now that's no longer possible and it's a useful feature for projects with a lot of content files, such as mine. Would love to see this feature back. I haven't tested the recent pull requests on the content tool so if that's already fixed feel free to close this issue.

**Comment by dellis1972** [comment]
@cra0zy ?

**Comment by cra0zy** [comment]
Read up: #4872

**Comment by cra0zy** [comment]
#5149 fixes this.
