### ISSUE TITLE
MonoGame MacOS install not appearing in Xamarin Studio

### ISSUE THREAD

**Issue by VaughnGH** [MonoGame/MonoGame#5143]
Just wanted to give a heads up that the current [MonoGame for MacOS](http://www.monogame.net/releases/v3.5.1/MonoGame.pkg) download on the MonoGame website contains an old version of the MonoDevelop plugin for Xamarin Studio. The old plugin doesn't work with current version of Xamarin Studio (6.0.2b73 in my case), making it difficult to actually use MonoGame, or even tell that it was successfully installed. This can be mitigated by updating the install package to use the current 'MonoGame Addin' (version 3.6.0.586 at the time of writing) to Xamarin Studio.

Also, if anyone finds this post via search engine, this issue can be fixed by opening Xamarin Studio (after installing MonoGame), tapping "Xamarin Studio [Community]" > Add-ins... > Updates and updating the MonoGame add-in

**Comment by tomspilman** [comment]
@dellis1972 ?

**Comment by dellis1972** [comment]
@tomspilman has the mac build bot been upgraded? If not then we are still building the old XS5 addin which won't work in XS6. Related PR https://github.com/MonoGame/MonoGame/pull/4584

**Comment by Jjagg** [comment]
Also slightly related because the XS6 branch should set the manifest: #5096 (though that can be done after the branch is merged too)

**Comment by dellis1972** [comment]
We now ship an XS6 and a VSForMac 7.3 Addin with the installer. Please Re-open if these do not work
