### ISSUE TITLE
MonoGame 3.6.0.873 Development Build bug?

### ISSUE THREAD

**Issue by Vusroda** [MonoGame/MonoGame#5145]
I am developing game for Windows, Linux and possibly Mac.
MonoGame 3.5 used OpenTK for cross-platform, and I could make Linux build almost without problems.
OpenTK crashed randomly few times, and once I learned that new Development build doesn't use OpenTK anymore, I downloaded it.

Now, on the Development Build, target CPU is "Any CPU". When I try to build the game, I get following error:

> The Visual Studio 2015 Remove Deubber (MSVSMON.EXE) does not appear to be running on the remote computer. This may be because a firewall is preventing communication to the remote computer. Please see Help for assistance on configuring remote debugging.

I'm not using Remote Debugging.
I can build the project by going to Properties -> Build, and changing Platform target from Any CPU to either x86 or x64.

Am I wrong to use x86 or x64, or is it a bug that it tries to use Any CPU?
I'm using Visual Studio 2015 with Windows 10.

I'm also having problems Loading Content.

> ```
> An unhandled exception of type 'Microsoft.Xna.Framework.Content.ContentLoadException' occurred in MonoGame.Framework.dll
> 
> Additional information: The content file was not found.
> ```

Error pointing to this line: Console.WriteLine("Textures//Misc//testTexture"); It seems that problems is only when trying to access folders, but simple Content.Load< Example>("example") works fine.
    Textures are in correct folded, System.IO.Directory.GetFiles finds that there is content in the folders.

MonoGame PipeLine Tool causes problems when using it to create .ogg content files from files that are already .ogg, but loading .wav works.

**Comment by Jjagg** [comment]
> Now, on the Development Build, target CPU is "Any CPU". When I try to build the game, I get following error:

It says here https://msdn.microsoft.com/en-us/library/ms164726.aspx:

> 
### I got this message while I was debugging locally
If you are getting this message while you are debugging locally, your anti-virus software or a third-party firewall may be to blame. Visual Studio is a 32-bit application, so it uses the 64-bit version of the remote debugger to debug 64-bit applications. The two processes communicate using the local network within the local computer. No traffic leaves the computer, but it is possible that third party security software may block the communication.
The following sections list some other reasons why you might have gotten this message, and what you can do to fix the issue.

____

> I'm also having problems Loading Content.
Console.WriteLine("Textures//Misc//testTexture");

I assume you meant `Content.Load<Texture2D>("Textures//Misc//testTexture")`. What's up with the double slashes here? You'd do that with backslashes but not with forward slashes. I think both back and forward slashes work for the ContentManager, but not like this.

**Comment by energyuser** [comment]
About your `ContentLoadException` exception, did you first `Build` the content from the Pipeline tool? Saving is not the only thing you do; you must also build the content to actually create the `XNB` files that are later loaded when the game runs.

**Comment by Vusroda** [comment]
No, it did point to  Console.WriteLine("Textures//Misc//testTexture"); line in my code. Don't ask me why, I don't know either. Below that, I had those Content.Load< Texture2D>("something") lines. I tried using forward and backslashes and Path.Combine(foldername, assetname) int Content.Load, but no luck.
 
I haven't used Pipeline to build .xnb for textures, because they work fine with 3.5 without them. I'll look into that later today, this is probably the issue.

**Comment by Jjagg** [comment]
> No, it did point to Console.WriteLine("Textures//Misc//testTexture"); line in my code.

This really can't cause that exception. Make sure you build the project before you run it. It may not do this automatically and then it might break on the wrong line because the offending piece of code was there when you last built.

**Comment by energyuser** [comment]
I'm not entirely sure how you load `Texture`s, or rather, any Content file with the `Console`... In fact I don't even know why you would use `Console` with a game app, other than debugging purposes such as current mouse location or current scene, and even that's better displayed with a SpriteFont in the main game `Window`; but it seems you are trying to load `Texture`s with it. My advice is scrap the `System` code you have and use what MonoGame already offers with way less code to write. Usually it's something along these lines:
```c#
yourAsset = this.Content.Load<YourAssetType>("path/to/your/asset") as YourAssetType;
// Regarding the slashes and backslashes that's how you do it with double slash:
yourAsset2 = this.Content.Load<YourAssetType>("path\\to\\your\\assert") as YourAssetType;
// Make sure you don't have an @ before the string parameter or it will disable character escaping and won't work
```

**Comment by cra0zy** [comment]
@tomspilman First part of this is a bug that got fixed, second part is the person trying to load raw assets which we dropped support for. This can be closed.
