### ISSUE TITLE
Trapping mouse in fullscreen modes?

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5148]
Hello :)

I would like to discuss the possibility to trap the mouse inside the window when using any fullscreen modes on desktop platforms.

The reason is that non-trapped mouse can be difficult to use for users with multiple monitors. I know that trapping the mouse on windowed mode is a bad practice, but what about fullscreen?

**Comment by cra0zy** [comment]
Duplicate of #4982
