### ISSUE TITLE
Get added to Microsoft's game dev guide

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5159]
So MS has a guide for game development on Windows 10  here:

 "Windows 10 game development guide"
 https://msdn.microsoft.com/windows/uwp/gaming/e2e

We need to see how we can get MonoGame included on there and what content we need for it.

**Comment by tomspilman** [comment]
@mtoepke - Can you or someone else on your team steer us in the right direction?

**Comment by DDReaper** [comment]
@dellis1972 Has already put his hand up, still the more the merrier.  Considering MG was one of the premier partners and was on stage for the UWP announcement, it is a bit odd it's fallen from the radar.

Even funnier that Unity are their and basically fails to support Windows platforms, they are always the last to be fixed, buggy as hell most of the time and with a massive player overhead. (and no modern C#, lol)

**Comment by tomspilman** [comment]
The content in https://msdn.microsoft.com/windows/uwp/gaming/e2e seems to suggest it is coming out of a GitHub repo somewhere.  Can we submit a PR ourselves to it?

**Comment by BrianPeek** [comment]
I actually work on/near this time now.  I'll see what I can do...

**Comment by tomspilman** [comment]
Thanks @BrianPeek !

**Comment by chrisgwilliams** [comment]
Appears to be up-to-date now.  It's about halfway down the page, between Havok and Cocos2d.

**Comment by DDReaper** [comment]
Well, half way there it seems.
Spotted this while I was doing research for my FD talk:
https://www.visualstudio.com/vs/game-development/
Only lists Unity / Unreal / Cocos and DX.   If Unity is in that list, so should MonoGame in my opinion 🗡

**Comment by tomspilman** [comment]
> Appears to be up-to-date now.

Thanks for reminding me of this issue.


> If Unity is in that list, so should MonoGame in my opinion

Yeah...  but that ship has sailed.  MS is not going to redesign that page to fit us.

**Comment by tomspilman** [comment]
Thanks @BrianPeek !

We're also in the middleware page too:

https://developer.microsoft.com/en-us/windows/app-middleware-partners
