### ISSUE TITLE
Pipeline Tool does not ignore Shader Compiler Warnings

### ISSUE THREAD

**Issue by dellis1972** [MonoGame/MonoGame#5165]
When compiling shaders it is common to have warnings such as 

' warning X3206: 'mul': implicit truncation of vector type;

at the moment, if we get these warnings the pipeline tool flags those as 'failed'.

**Comment by nkast** [comment]
Can you test #5155 ?

**Comment by MarcVador** [comment]
This looks to be solved, warnings are not shown as failures (latest dev build)

**Comment by tomspilman** [comment]
Thanks @MarcVador !
