### ISSUE TITLE
Keys.LeftAlt not detected

### ISSUE THREAD

**Issue by stefv** [MonoGame/MonoGame#5170]
Hello,

I'm trying to catch an Alt+Enter to switch to fullscreen/windowed mode but I don't know why I have the feeling Monogame can't detect if the LeftAlt key is down. I'm using a Surface Pro 4.

I tried just this code to check this problem:
```
foreach(Keys key in Keyboard.GetState().GetPressedKeys())
{
    Debug.WriteLine(key);
}
```

But nothing appended for the left ALT. But if I press the AltGr key I have 2 lines:
```
LeftControl
LeftAlt
```

I'm using Monogame Universal version 3.5.1.1679.

Regards,
Stef

**Comment by nkast** [comment]
The keys you are getting is probably some combination that your system interprets the Alt press as. 
In my system I don't get anything, the keyDown/keyUp event doesn't fire for alt keys.

Unfortunately Store apps can't see Alt keys.  You have to use some other combination.

**Comment by stefv** [comment]
Ok, I understand the problem now. I will use another key.

Thank you.
