### ISSUE TITLE
Missing TextureCube.GetData(...) method

### ISSUE THREAD

**Issue by Sizaar** [MonoGame/MonoGame#5172]
The `TextureCube.GetData(CubeMapFace cubeMapFace, int level, Nullable<Rectangle> rect, T[] data, int startIndex, int elementCount)` method is missing (ref: https://msdn.microsoft.com/en-us/library/bb197085.aspx).

**Comment by Jjagg** [comment]
Fixed in #5121

**Comment by KonajuGames** [comment]
> Fixed in #5121

Ahh, so it is.

**Comment by Jjagg** [comment]
I notice while working on that and quickly did that too. No tests yet though... Haven't worked on that PR in a while because I find the texture format thing so annoying. ..

**Comment by Sizaar** [comment]
Alright, I'll close this issue when your PR is merged @Jjagg. :smiley:

**Comment by Jjagg** [comment]
I edited the PR to autoclose this :)
