### ISSUE TITLE
Missing GraphicsDevice.BlendFactor

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#5175]
XNA has a [BlendFactor](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.graphicsdevice.blendfactor.aspx) property in GraphicsDevice that is currently missing in MonoGame. Note that there is also a [BlendFactor](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.blendstate.blendfactor.aspx) property variable in BlendState. I wrote a quick test to see how it works in XNA:

```
[Test]
public void BlendFactor()
{
    Assert.AreEqual(Color.White, gd.BlendFactor);

    var blend = new BlendState
    {
        BlendFactor = Color.Crimson
    };

    gd.BlendState = blend;
    Assert.AreEqual(Color.Crimson, gd.BlendFactor);

    gd.BlendFactor = Color.CornflowerBlue;
    Assert.AreEqual(Color.Crimson, gd.BlendState.BlendFactor);
    Assert.AreEqual(Color.CornflowerBlue, gd.BlendFactor);

    blend.Dispose();
}
```
This passes, so to get the same behavior in MG we just need to add a `public Color BlendFactor { get; set; }` and then in the BlendState setter set `BlendFactor = value.BlendFactor`. I don't know if this property should just override the BlendFactor from the BlendState, but my guess is that's how it works. XNA docs are ambiguous on this and just say both control blend factor...

**Comment by tomspilman** [comment]
Someone started some work on this before, but was taking the wrong direction on it:

 https://github.com/MonoGame/MonoGame/pull/4141

... and then it got dropped.  Maybe the code and my comments on it in that old PR will help.

> I don't know if this property should just override the BlendFactor from the BlendState,

Yeah that is what it seemed like it did.  We need to move the setting of the `BlendFactor` out of `BlendState` and into `GraphicsDevice.PlatformApplyState`.

**Comment by Jjagg** [comment]
@dellis1972 What's up with all the _last* stuff (_lastBlendState, etc.) to cache applied render state in GraphicsDevice.OpenGL? We have the dirty flags that are already checked in GraphicsDevice so the extra check shouldn't be necessary, right?

**Comment by dellis1972** [comment]
I have no idea. I've not looked at the details of that file for a long long time.

**Comment by tomspilman** [comment]
> What's up with all the _last* stuff (_lastBlendState, etc.) 

That was implemented by @prollin in https://github.com/MonoGame/MonoGame/pull/3510.

It was an effort to reduce the high amount of redundant GL calls that occurred even with the existing state checking done at the state block level in the core `GraphicsDevice`.  Since setting things like blend or depth stencil state involves 5 or 6 GL API calls where in DirectX it is one or two.

We should continue to maintain this in the GL device.
