### ISSUE TITLE
Pipeline Tool - CustomProcessor - Nullables edition

### ISSUE THREAD

**Issue by MarcVador** [MonoGame/MonoGame#5178]
When a custom processor exposes a string property in the pipeline tool, it crashes (it seems this happens only with nullable types, not only String):

```
public string MAP_Normal_Texture
{
    get { return normalMapTexture; }
    set { normalMapTexture = value; }
}
private string normalMapTexture;
```

If a user clicks on the textbox to edit the field of MAP_Normal_Texture, the pipeline tool crashes and no error message available.

But if normalMapTexture is initialized to "", then no crash happens and everything rolls.

**Comment by tomspilman** [comment]
Seems reasonable that the pipeline tool should protect against null properties from processors.

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
