### ISSUE TITLE
Pipeline Tool - CustomProcessor - Attributes ignored 

### ISSUE THREAD

**Issue by MarcVador** [MonoGame/MonoGame#5179]
The PipelineTool ignores the attributes but DefaultValue (only this one, coincidence with String ?) if any are set. 
Instead of reading the attributes DisplayName and Description (if it was intended to be shown in ballons/tooltip ?) it only shows the property name:

```
[DisplayName("Normal Map Texture")]
[Description("blablabla")]
[DefaultValue("")]
public string MAP_Normal_Texture
{
	get { return normalMapTexture; }
	set { normalMapTexture = value; }
}
private string normalMapTexture;
```

Here it shows MAP_Normal_Texture, instead of Normal Map Texture.

**Comment by tomspilman** [comment]
I thought this was working before. @cra0zy ?

**Comment by cra0zy** [comment]
It wasn't working before.. we actually didn't use a single attribute. Anyway #5180 fixes this.

**Comment by tomspilman** [comment]
@MarcVador - This is fixed in the develop branch now.
