### ISSUE TITLE
Content Pipeline Extension project fails to compile - .NET target version

### ISSUE THREAD

**Issue by DDReaper** [MonoGame/MonoGame#5185]
Currently in the 3.5/3.6 build. When creating a new Content Pipeline Extension project is created, it fails to build.

This is due to a .NET version compatibility from the generated template.

Simple workaround is to change the target version from .NET 4.0 to .NET 4.5.  However this should be corrected in the project template.

**Comment by DDReaper** [comment]
Resolved to some degree and covered it in the latest (upcoming) tutorial.  Just have to tell people to check the Target Framework to use when creating the project and/or updating it afterwards.  Not a great experience since the Main templates are all .NET 4.5+

**Comment by tomspilman** [comment]
> change the target version from .NET 4.0 to .NET 4.5.

@DDReaper - Change the target version of what?  The template?  The MonoGame assemblies?

Shouldn't we fix the template if that is the case?

**Comment by DDReaper** [comment]
After recording the video, yes. We should fix the template. 
I'll see if I can submit a PR for it.

**Comment by DDReaper** [comment]
#5225 submitted to resolve this.

**Comment by DDReaper** [comment]
Tested and working fine.

**Comment by tomspilman** [comment]
Merged... thanks @DDReaper !
