### ISSUE TITLE
Sound effects sound like noise or are much too loud

### ISSUE THREAD

**Issue by spunky44** [MonoGame/MonoGame#5190]
Some users report sound effects that sound like noise or are way too loud. 
The issue appears intermittently. I have not reproduced it and don't know what the cause is either.

This is on Windows using the default sound libraries.

I would appreciate any help on this, since I don't even know how to troubleshoot it.

**Comment by spunky44** [comment]
This is being reported by people with headphones, some with surround sound, and some without.

**Comment by spunky44** [comment]
Got his suggestion somewhere else:

> Sounds very much like the sound buffers aren't getting updated often enough and the sound is playing garbage bytes.

**Comment by spunky44** [comment]
The UI sounds which have the problem call `SoundEffect.Play()` which gets a pooled sound effect instance.
The environment sounds which are OK call `SoundEffect.CreateInstance()` which creates a new instance that isn't pooled.

**Comment by MichaelDePiazzi** [comment]
@spunky44 Are you using a DirectX build by any chance? I think this may possibly be related to the same problem causing issue #5054.

**Comment by RefactoredGames** [comment]
The game is on Windows and uses DirectX, yes.
I will look into the linked issue. Unfortunately I cannot test any fixes because I have never experienced the error myself.

**Comment by MichaelDePiazzi** [comment]
I've just submitted PR #5440 which may hopefully help here. I'm not sure about the noise problems, but I think that the problems where things are way too loud should be fixed by this.

**Comment by Ziriax** [comment]
I'm experiencing the same issue, using SoundEffect.Play in a Monogame Windows DX Desktop application. I'm investigating this further.

**Comment by Ziriax** [comment]
When my sound effects sounds like noise, the debug output prints 

`XAUDIO2: WARNING: Spent 13.29ms in OnProcessingPassStart callbacks`

**Comment by Ziriax** [comment]
I'm also experiencing the issue when using `SoundEffect.CreateInstance`, but at first sight less frequently.

**Comment by Ziriax** [comment]
Nevermind, it was my mistake, when refactoring I disposed the sound effect! See #5659

**Comment by Jjagg** [comment]
Fixed in #5440.
