### ISSUE TITLE
Set TeamCity nuget API version to v2 for development feed.

### ISSUE THREAD

**Issue by maelgrove** [MonoGame/MonoGame#5192]
The official MonoGame development feed (http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/) currently only offers nuget protocol v1, which makes it unusable in Visual Studio 2015 Update 1 and later where support for nuget v1 was dropped within the Nuget Package Manager. Support for nuget v2 is available in TeamCity since version 9.0 where as the current installation is 10.0 (http://teamcity.monogame.net/), so this should be only a matter of switching a single configuration (see https://confluence.jetbrains.com/display/TCD9/Configuring+TeamCity+Server+Startup+Properties#ConfiguringTeamCityServerStartupProperties-TeamCityinternalproperties and https://teamcity-support.jetbrains.com/hc/en-us/community/posts/206817105-How-to-enable-NuGet-feed-v2).

**Comment by maelgrove** [comment]
Bump because two years later and the issue is still up. Any updates on this? 
@tomspilman maybe?

**Comment by Jjagg** [comment]
@maelgrove FYI a recent develop build was pushed to nuget.org with the `-develop` pre-release suffix: https://www.nuget.org/packages/MonoGame.Framework.WindowsDX/3.7.0.1681-develop

**Comment by tomspilman** [comment]
We have had the Nuget v2 and v3 feeds for a while:

http://teamcity.monogame.net/guestAuth/app/nuget/feed/_Root/default/v1
http://teamcity.monogame.net/guestAuth/app/nuget/feed/_Root/default/v2
http://teamcity.monogame.net/guestAuth/app/nuget/feed/_Root/default/v3/index.json

I just updated the website to point to the v3 feed by default.
