### ISSUE TITLE
Effects destroying my project

### ISSUE THREAD

**Issue by TheRealVira** [MonoGame/MonoGame#5193]
The problem is, that after a spritebatch begin - end (with shader), will somehow destroy every new drawing attempts (without/default shader). I've created a simple reproduction of the bug:

https://github.com/TheRealVira/BugReproduction

I'm assuming it's because "spritebatch.End()" won't end the job and doesn't clean the shader, so it'll reuse the state after another "sp.Begin()".

**Comment by nkast** [comment]
What would happen if you include a Vetrex Shader in your fx?

**Comment by TheRealVira** [comment]
Updated the reproduction and it seems a bit more as intended, although it now has an offset of half of the screen (at both axis). Did I skip some necessary flags at the initialization of the sampler?

Besides that I'm a bit confused now, because I thought Monogame would automatically add some kind of a default vertex shader...

**Comment by Jjagg** [comment]
>Updated the reproduction and it seems a bit more as intended, although it now has an offset of half of the screen (at both axis).

Possibly because of #4387. Are you expecting SpriteBatcher to set the transform for your vertex shader?

**Comment by nkast** [comment]
> Updated the reproduction and it seems a bit more as intended, although it now has an offset of half of the screen (at both axis). Did I skip some necessary flags at the initialization of the sampler?

So, it works? 
I think the half pixel offset is fixed in 3.6. You can probably find a solution for the half pixel offset and use it as a workaround for now.

>Besides that I'm a bit confused now, because I thought Monogame would automatically add some kind of a default vertex shader...

I believe it uses the default Vertex shader of SpriteBatch's Effect. I suspect that it fails to update the Pixel shader for that reason. I tested your project with MG 3.5.1 and I could see the plane just fine. MG develop 3.6  throws a DLLNotFound (SDL2.dll). So this has to be some issue with the driver and I don't know if it's been addressed in 3.6. Have you tested it on more that one machines/GPUs?

**Comment by TheRealVira** [comment]
> Possibly because of #4387. Are you expecting SpriteBatcher to set the transform for your vertex shader?

Could be... I've expected the SpriteBatcher to create a pass through vertex shader and setting all needed parameters. As it is described in [#4387](https://github.com/MonoGame/MonoGame/issues/4387), the default stuff is a bit cheaty. :smirk:

> So, it works? 
I think the half pixel offset is fixed in 3.6. You can probably find a solution for the half pixel offset and use it as a workaround for now.

Yeah it sort of does. It seems a bit strange though and if the newer version of MG fixed it but is throwing a DLLNotFound it won't help.

> Have you tested it on more that one machines/GPUs?

I sadly don't have much resources to offer there.. :crying_cat_face:

**Comment by nkast** [comment]
> Yeah it sort of does. It seems a bit strange though and if the newer version of MG fixed it but is throwing a DLLNotFound it won't help.

Yes, you need to setup a new project because the GL backend changed. This might also fix the bug.

> I sadly don't have much resources to offer there.. 😿

It might be helpful to know what GPU/driver you have. I don't see the issue with my AMD  R9 270.

**Comment by TheRealVira** [comment]
> It might be helpful to know what GPU/driver you have. I don't see the issue with my AMD R9 270.

I'm currently using the Geforce GTX 760 with the latest drivers (on Windows 10).
