### ISSUE TITLE
Github commit error: "Could not commit submodules: ThirdParty/Dependencies"

### ISSUE THREAD

**Issue by spunky44** [MonoGame/MonoGame#5197]
I got this error after syncing, fixing some conflicts, then attempting to commit to my cloned/forked MonoGame repository.

Github says:
"Add them as submodules from GitShell or remove their .git folders to add them as regular directories instead"

How do I fix it?

**Comment by spunky44** [comment]
Is Dependencies a submodule?

**Comment by Jjagg** [comment]
Yes, Dependencies is a submodule. This is probably the same issue as http://stackoverflow.com/questions/33728070/github-keeps-throwing-could-not-commit-submodules-error-and-i-dont-see-why-t
This is not a MonoGame bug, so it shouldn't really be an issue in this repo.

**Comment by cra0zy** [comment]
> This is not a MonoGame bug, so it shouldn't really be an issue in this repo.

It is a MonoGame bug,  https://github.com/MonoGame/MonoGame/blob/develop/Build/Module.xml#L13

The link should be "MonoGame" not " Mono-Game"... I'll get it fixed.

**Comment by Jjagg** [comment]
Oh, sorry about that

**Comment by cra0zy** [comment]
#5198 Should fix this.
