### ISSUE TITLE
How to get window handle in windows? 

### ISSUE THREAD

**Issue by xaviergonz** [MonoGame/MonoGame#5205]
In order to be able to embed the window in a winforms panel I'd like to run some pinvoke over the window handle after it is created. Is there a way to get it?

**Comment by xaviergonz** [comment]
Nevermind, I found out how.

Basically if anybody needs to put the game in a WinForms panel, all they have to do is this after the game has been created and before it is run:

```
        IntPtr winHandle = game.Window.Handle;
        game.Window.IsBorderless = true;
        game.IsMouseVisible = true;

        Win32.SetWindowPos(
          winHandle,
          IntPtr.Zero,
          40,
          0,
          0,
          0,
          0x0401 // NOSIZE | SHOWWINDOW
        );

        Win32.SetParent(winHandle, winFormsPanel.Handle);
        Win32.ShowWindow(winHandle, 1); // SHOWNORMAL
```

**Comment by cra0zy** [comment]
Issues should be used for Bug tracking / Feature requests. If you have general questions about the framework please use <a href="http://community.monogame.net/">MonoGame Community SIte</a> or <a href="https://gitter.im/MonoGame/MonoGame">Gitter</a>.
