### ISSUE TITLE
Pipeline Tool - UI - Enable build output filtering by output state

### ISSUE THREAD

**Issue by MarcVador** [MonoGame/MonoGame#5206]
Hi !
I just noticed, while my project is growing with more and more data, that the tool does not allow to filter output to show only errors for example. 
Scrolling among 500 items to find the 2 failures is not user-friendly.
Showing only new built items and hiding skipped ones would be nice too.

**Comment by cra0zy** [comment]
Duplicate of #4458

**Comment by MarcVador** [comment]
Hum sorry I did not got so much back in time :/
Then it can be closed.
