### ISSUE TITLE
Improve References display in Pipeline tool

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5210]
Originally mentioned in https://github.com/MonoGame/MonoGame/issues/4457.

![image](https://cloud.githubusercontent.com/assets/103522/19089239/175e08b2-8a3f-11e6-9eb3-6faa5c540c34.png)

The 'Collection' text here is completely unhelpful to the user.

 - The 'References' property value should show a  ;  separated string of assembly names.

This makes it more similar to how VS shows lists of files/folders/macros:

![image](https://cloud.githubusercontent.com/assets/103522/19089180/dc762504-8a3e-11e6-8933-ee6952dbc53a.png)

![image](https://cloud.githubusercontent.com/assets/103522/19089403/c626c4e2-8a3f-11e6-8a3f-6683109e8217.png)

The display could just be the assembly names and not the full path in order to show the most useful information.  The content could be read only and require the use of the editor to make changes to it.

**Comment by cra0zy** [comment]
How about I make it so a cell can have a multiple row height? Or how about I make an expandable row for collection so it can show the values?

**Comment by tomspilman** [comment]
I think it could be worth experimenting with alternate views there.  It isn't like we're trying to save space for anything else under the main project properties.

If you can mock something up quickly lets see what you can come up with.

The only concern is it not behaving like one would expect on Windows.  It will take me trying what you come up with and giving feedback.

**Comment by cra0zy** [comment]
Scratch the multiple rows idea, it looks horrible... time to test the expandable row.

**Comment by tomspilman** [comment]
> Scratch the multiple rows idea, it looks horrible

Yeah I could imagine it would be hard to get something to not look weird like that.

If it was expandable then maybe...  but not always on.

**Comment by nkast** [comment]
A typical solution here is a TypeConverter to convert the collection into a  ';' separated string and vice versa. I don't know if that's supporter by the Eto grid. 
If we were to strip the full paths then editing and conversion back to a colection will not work, we have to somehow make the TypeConverter readonly.

**Comment by cra0zy** [comment]
> A typical solution here is a TypeConverter to convert the collection into a ';' separated string and vice versa. I don't know if that's supporter by the Eto grid. 
> If we were to strip the full paths then editing and conversion back to a collection will not work, we have to somehow make the TypeConverter readonly.

I need to add exactly 3 lines of code to make ';' separated refs display (ie. override the DisplayValue https://github.com/MonoGame/MonoGame/blob/develop/Tools/Pipeline/Controls/PropertyCells/CellRefs.cs#L19), the question here is "Is there a way to make it look nicer?"

**Comment by tomspilman** [comment]
> "Is there a way to make it look nicer?"

I agree...  we can spend a little time to see if we can find something nicer.  

Still the VS team likely lots of experienced UX designers on the team and they still use the simple `;` technique.  I see no issues with following their lead on this.

**Comment by cra0zy** [comment]
> Still the VS team likely lots of experienced UX designers on the team and they still use the simple ; technique.

 - they are not using it in a property grid
 - they are using it for strings that usually have low character numbers
 - their strings are more constant and don't have "." characters

This is how it would look in MG Pipeline PropertyGrid:
![screenshot from 2016-10-08 18-16-30](https://cloud.githubusercontent.com/assets/6773302/19214412/5ffece34-8d83-11e6-92c7-5b303b81e105.png)

It takes eyes quite a lot of time to just figure out where one string ends and another one begins.

**Comment by tomspilman** [comment]
@cra0zy - I agree...  it isn't pretty in most cases, but that is how it is in VS:

![image](https://cloud.githubusercontent.com/assets/103522/19089403/c626c4e2-8a3f-11e6-8a3f-6683109e8217.png)

That is a property grid, in VS, that can have lots of periods, it isn't short.

If you have an idea of how to make it better i'm all for that, but if you don't using the same thing as VS is perfectly fine.  There is always an editor for that property if someone wants to click thru and see things more clearly.

**Comment by tomspilman** [comment]
Ok...  here is my mock-up of what i think we should try to achieve:

![image](https://cloud.githubusercontent.com/assets/103522/19215985/b282b686-8d72-11e6-8709-565a63a418a1.png)

Simple and clean like the rest of the property grid display, but clearly the assemblies are grouped and each is readable.

**Comment by cra0zy** [comment]
The height of the cell is too big IMO, and also it can get crowded if you have to many refs. That was my idea 1, the idea 2 is to make it so References is expandable, like in the screenshot aboves how projectview has "Effects" folder which you can expand.

Side note I just remembered #3688

**Comment by tomspilman** [comment]
> The height of the cell is too big IMO,

That is the entire point...  expand the cell height to allow assembly refs to cleanly wrap and be clearly readable.

> also it can get crowded if you have to many refs

A little adjustment to the line height between assembly refs is all that would be needed.  As long as the vertical space between assembly refs and the vertical space between properties is clearly different... the use can still understand the grouping without ugly horizontal separator lines.

> the idea 2 is to make References expandable

 You could...  but I would keep their vertical spacing tighter than the property vertical spacing.


> Side note I just remembered #3688

The references need to stay in the property grid.
