### ISSUE TITLE
Remove/Rename 'Pads' Menu in Pipeline Tool

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5211]
We should remove or rename the 'Pads' menu item from the Pipeline Tool:

![image](https://cloud.githubusercontent.com/assets/103522/19089658/ea2eb72c-8a40-11e6-9fd8-75718916ad78.png)

It is a duplication of information already available in other areas so it would be fine to remove it.

If we want to keep it we should name it "View" which is more common name for options relating to the different display panels within an application.

**Comment by cra0zy** [comment]
> It is a duplication of information already available in other areas so it would be fine to remove it.

Menubar usually has a duplication of information... take "Edit" menu for example, you have a "New Item" command in it, but it's also available on the toolbar and in the context menu for the folders.

> If we want to keep it we should name it "View" which is more common name for options relating to the different display panels within an application.

My plan was to rename it to the "View" menu later on, once I made it so layouts can be configured... though it might be confusing to name it that immediately.

**Comment by tomspilman** [comment]
> Menubar usually has a duplication of information

 I am aware...  just saying it isn't a hard rule or requirement if we wanted to remove it.


> I thought it might be confusing naming it that immediately.

Quite the opposite...  "Pads" was confusing and meant nothing to me.  "View" is something you find in tons of Windows apps and usually has stuff like this.

We should change it to "View".
