### ISSUE TITLE
Missing XWT When Building Windows Platform

### ISSUE THREAD

**Issue by 06needhamt** [MonoGame/MonoGame#5217]
Various Errors Occur When Building The Windows Platform On Windows All Errors Seem to Relate To Missing XWT 
see [here](https://gist.github.com/06needhamt/52f8ad33c17dd41ea14511dae5e914cd) for build log

**Comment by cra0zy** [comment]
I'm guessing you only pulled the new changes from the repo and forgot to update the submodules, do:
```
git submodule update
```

**Comment by tomspilman** [comment]
@06needhamt - Yeah I expect you didn't update (or maybe even initialize) the submodules.  Reopen this issue if this isn't the case and we'll investigate further.

**Comment by 06needhamt** [comment]
@tomspilman Yes that fixed the problem Thanks
