### ISSUE TITLE
Protobuild OpenGL

### ISSUE THREAD

**Issue by Aeirex** [MonoGame/MonoGame#5219]
Does Protobuild build OpenGL projects? Like, I needed:
`Microsoft.Xna.Framework.GamerServices;`

Although, this is only available if we use the source-code and not the installer/NuGet Package. Can you guys somehow include this in the packages/installer? It is a pretty big break in one of my libraries, that I need resolved.

**Comment by tomspilman** [comment]
Closing this old issue.  We don't support `GamerServices` very well and don't recommend using it as it isn't very portable.
