### ISSUE TITLE
3.6 Pipeline tool - Can't copy NAME of the asset anymore, it's read-only

### ISSUE THREAD

**Issue by DDReaper** [MonoGame/MonoGame#5221]
In XNA days the NAME of the asset in the Content Project was always copyable so you could easily add it to your solution without typo's

The 3.5 tool still let you copy, however it also copied the extension, which wasn't always desirable but it still worked.

In the latest dev branch the NAME is now read-only and you can't copy it unless you right-click and rename it, this promotes a fairly bad experience when you want to copy the name of the asset for use in your project.

Can we enable copying or at least an easy way to copy JUST the name of the asset without the extension?
P.S>
Would submit a PR myself but I'm busy doing tutorials on this stuff and getting ready for FD.

**Comment by cra0zy** [comment]
How about I add a "Copy Asset Relative Path" to the context menu of the Pipeline Tool?

**Comment by DDReaper** [comment]
Yup, that would do it if someone can add it 💃

**Comment by cra0zy** [comment]
PR is done.

**Comment by Tzenchor** [comment]
FYI, in XNA you could change the asset name without renaming the original file

**Comment by cra0zy** [comment]
@tomspilman This has been implemented.
