### ISSUE TITLE
Monogame app not really closing.

### ISSUE THREAD

**Issue by lorencinibrdev** [MonoGame/MonoGame#5223]
Hi all. Ive been doing some game development on C++, but went on to try to use C#, since it would speed up dev time.

Anyways, my issue is the following:

I have a very basic Game.cs class (event the ones from the Monodevelop templates are enough to reproduce the issue), and everything works out fine (Starting, loading textures, handling events, etc...).

The problem starts when i try to close the window.

Be it by using the X button on the window, or by using the Exit() funcion inside, the window does not closes. The events stops being handled, but the screen remains there. I can move the window around, and no message to "Force Close" appears, but i have to click on the Stop Debugging button on Monodevelop, in order for it to go away.

The only strange thing i've noticed is that i have this on my output window:

![capture](https://cloud.githubusercontent.com/assets/4778177/19373996/cac99cfc-919e-11e6-8b68-e03a35452096.png)

Seems like not all the threads oppened by monogame are closing sucessfully. I've used monogame in the past, but never got into this issue...

Here's my setup:
- Linux
- Monodevelop 5.10.1
- Monogame 3.5.1.1679
- OpenTK 1.1.0

I'm sorry for the lack of details, but please, let me know if i can do anything more to help.

**Comment by mrhelmut** [comment]
Hi.
This issue has been fixed in the current develop branch, if you wish to give a try you can download the develop build or build MonoGame from sources. There are a lot of improvements in the latest OpenGL path (OpenTK has been fully replaced by SDL2).

**Comment by lorencinibrdev** [comment]
Oh, wonderfull.

I'll test the development branch when i get home tonight, and let you guys know if it works.

**Comment by lorencinibrdev** [comment]
Hi.

Sorry for the delay, but just confirming that this bug is indeed fixed as of latest development version.

Thanks!
