### ISSUE TITLE
UWP blank texture in shader

### ISSUE THREAD

**Issue by Ziriax** [MonoGame/MonoGame#5231]
I am porting my XNA code to Monogame 3.5.1, to a universal windows app.

Although it is a 2D app, I do not use spritebatches, I draw indexed primitives, with custom shaders.

After installing the latest VS2015 update 3, porting was easy, great job, thanks for making this so easy! 

Unfortunately only the screen was cleared in the correct color, none of my primitives were rendered. If I changed the pixel shader to output a color instead of sampling the texture, I could see the primitives. I launched the graphics debugger, and indeed the result of sampling the texture was all zero. The device state looked correct, the texture was set in slot 0. The UV coordinates were also correct.

However my shader code assigned register(t0) to the texture, but the shader assembly code used register t1... I will now try to assign textures using  the shader parameters instead of calling SetTexture on the device. Nevertheless, if I ask for register t0, I think the compiler should respect that.

I am not sure where to start to fix this issue. I will try to make a small reproducible case.

But just to make sure, are there any known issues with UWP and Monogame regarding this? I tried the latest version of the framework and tools. I had to fix a couple of issues before it ran (multisampling was set to 32, and SV_Position was not matched to POSITION). After these fixes, my app started, but still no textures.

Thanks,
Peter

**Comment by Ziriax** [comment]
Using ```effect.Parameters["MyTexture"].SetValue(myTexture)``` solves the problem. I'm not sure why setting the texture on the device directly does not work. Anyway, it feels cleaner setting it on the effect.

**Comment by DDReaper** [comment]
Note, if you are planning to deploy your UWP to xbox.  Be sure to check out this article:
https://blogs.windows.com/buildingapps/2016/09/09/tailoring-your-app-for-xbox-and-the-tv-app-dev-on-xbox-series/#lPIP0CxHRf64dxyq.97

I've submitted a PR to update the UWP template to include some things, like the cursor removal. But if you have an existing one, you'll need to update manually.

**Comment by Jjagg** [comment]
Closing in favor of #6490.
