### ISSUE TITLE
Pipeline wont open on OSX Sierra

### ISSUE THREAD

**Issue by andrekat** [MonoGame/MonoGame#5235]
Hey guys,

sorry for disturbing .. but im trying since 2 hours getting my pipeline tool on OSX Sierra running - with no success.

when i try to manually open the application i get get following error:

"The application "Pipeline" could not be opened" 

PS: I downloaded latest MonoGame Version - afterwards i installed MonoGame Pipeline, since it wont start, but also with no success :(

Any suggestions ?

Thanks,

**Comment by DuyH** [comment]
I'm on El Capitan and it doesn't seem to open from within Xamarin Studio

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
