### ISSUE TITLE
Fullscreen ignoring PreferredBackBuffer values in developer branch v3.6.0.1011

### ISSUE THREAD

**Issue by vcrobe** [MonoGame/MonoGame#5236]
Yesterday I downloaded the last installer for developer branch (v3.6.0.1011) for Windows.

I'm doing a game using DirectX Desktop project and I was using the last stable release version (3.5.1.1679) and in this version the game work as expected, now when switching to the developer's branch installer I get the following issue:

My game is forced to run with this resolution 1024x768 regardless of the Windows screen resolution. My screen resolution is 1920x1080.

Here's the graphics initialization code

```
graphics = new GraphicsDeviceManager(this)
{
    PreferredBackBufferWidth = 1024,
    PreferredBackBufferHeight = 768,
    IsFullScreen = true,
};
```

When I run the game in full screen it's ignoring the PreferredBackBuffer values and run at 1920x1080. Here's a screenshot

![developbranch](https://cloud.githubusercontent.com/assets/7717678/19619434/39a81d64-9835-11e6-9779-474f8d700764.png)

Note: The vertical lines you see don't appear while playing they appear in the screenshot only.

If I comment the statement _IsFullScreen = true,_  and run the game in a window it works well but if I switch to full screen (while playing the game) I get the same result as the previous screenshot.

This wasn't happening when using the last stable release (master branch) v3.5.1.1679

Here's a screenshot in full screen with the last stable release installer

![master](https://cloud.githubusercontent.com/assets/7717678/19619443/b1e629ce-9835-11e6-9ed5-9ff804f5484c.png)

**Comment by Jjagg** [comment]
I think #5218 should fix this. @MichaelDePiazzi?

**Comment by tomspilman** [comment]
@vcrobe - Do you mind trying out #5218 to see if it solves your issue?

**Comment by vcrobe** [comment]
@tomspilman, @Jjagg  - Sure I'll try it but how can I get an installer with that specific issue fixed?

**Comment by tomspilman** [comment]
@vcrobe - You can grab the installer from the build server for that PR directly:

http://teamcity.monogame.net/viewLog.html?buildId=26039&buildTypeId=MonoGame_PackagingWindows&tab=artifacts&guest=1

**Comment by MichaelDePiazzi** [comment]
Hey guys. Yeah, I'm pretty sure my PR will fix this. Let us know if it solves this issue for you @vcrobe.

**Comment by vcrobe** [comment]
Yes! this PR fixed the issue.

How can I get notified that this PR was merged into the _develop_ branch?

**Comment by Jjagg** [comment]
If you're on desktop you can click the subscribe button on the right on the page of the PR. This should be closed when that PR gets merged so you should get a notification anyway (assuming it does get closed).

**Comment by MichaelDePiazzi** [comment]
Great! Thanks for testing this @vcrobe. I've updated the description of my PR so that it'll automatically close this issue once it's merged.

**Comment by vcrobe** [comment]
@Jjagg Thank you for the exaplanation.
@MichaelDePiazzi You're welcome.

Well... to keep testing the develop branch I've to wait for the merge of this PR. In the meantime I'll use the master branch.

**Comment by MichaelDePiazzi** [comment]
@tomspilman Any chance someone could take a look at getting PR #5218 merged sometime soon? It's been tested now quite a bit (including by players of my game on Steam), so I think it should be good to go. Cheers!
