### ISSUE TITLE
UWP SharpSteer2 XNA port blurry text and slower

### ISSUE THREAD

**Issue by Noemata** [MonoGame/MonoGame#5243]
I've ported SharpSteer2 (https://github.com/martindevans/SharpSteer2) to a monogame UWP app.  The port was trivially easy which is fantastic, but I have noticed that the text is blurry, lines are thicker and appear less sharp, and the performance is about 20% slower.

Any hints on how to close the gap in terms of performance and how to address the quality issue?  I was expecting monogame+UWP to be faster.

Attached are screenshots for comparison.

[ monogame ]

![monosteer2](https://cloud.githubusercontent.com/assets/6632315/19650695/2bceeb4c-99d8-11e6-950e-5f654b5e9da0.png)

[ xna ]

![xnasteer2](https://cloud.githubusercontent.com/assets/6632315/19650709/364d14ea-99d8-11e6-8998-5a578a06302b.png)

Notice how lines are thinner in the XNA version.

**Comment by KonajuGames** [comment]
For the text, issue #5242 mentions that using fractional values in the position when drawing text causes soft edges, which is expected from bilinear filtering.  Not sure about the width of lines though.

**Comment by Noemata** [comment]
This turns out to be more involved than I thought.  One surprisingly big difference occurs when changing the GPU that is being used by UWP.  This did not occur to me initially.  I switched from the Intel GPU to the NVidia GPU and noticed the lines were looking a little bit better.  If you click on the above images to see the image at its actual size, you'll get a better idea of the differences that are in effect for all aspect of line rendering.

This is my first monogame app (having used XNA since the 3.1 days), so I have some catching up to do with respect to how things work.  Adding UWP and its swapchain adds to the range of things to consider.  I'd like to see the "Draw" FPS increase for UWP.  Would appreciate any input from those that have already run into this with UWP.

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
