### ISSUE TITLE
BoundingBox.Contains(Vector3) returns incorrect ContainmentType

### ISSUE THREAD

**Issue by hifi** [MonoGame/MonoGame#5245]
The code of BoundingBox.Contains(Vector3) method checks if any of the points is on the edge of the bounding box and immediately returns `ContainmentType.Interjects` even if the given Vector3 is completely inside it.

The method should return `ContainmentType.Contains` if all of the points are inside and `ContainmentType.Interjects` if any of them are inside.

**Comment by Jjagg** [comment]
When you say point you mean coordinate, right? The implementation looks good to me. Can you give an example of when it returns something unexpected? 

> ContainmentType.Interjects if any of them are inside

This sounds wrong.

**Comment by james0x0A** [comment]
XNA reports `ContainmentType.Contains` if every component of the vector is inside the corresponding axis aligned interval, inclusive of the edges, otherwise it reports `ContainmentType.Interjects`

**Comment by KonajuGames** [comment]
That makes sense.  A point cannot intersect a box.  A point is either inside or outside the box.  It cannot be partially in and partially out.
