### ISSUE TITLE
Extend TextInputEvent to include modifier information

### ISSUE THREAD

**Issue by james0x0A** [MonoGame/MonoGame#5249]
I am in the midst of creating a patch for TextInputEvent to add information about Ctrl, Alt and Win/Gui key presses, in an effort to avoid creating multiple systems for capturing text input.  

If this is something that would be of use to other users of the library, I would be glad to make changes and extend this to all the platforms MonoGame supports where it makes sense.

Current work is available at https://github.com/james0x0A/MonoGame/tree/textinput-modifiers

**Comment by KonajuGames** [comment]
Modifier keys could be handy in text events.

**Comment by tomspilman** [comment]
@james0x0A - You might want to look at https://github.com/MonoGame/MonoGame/pull/4878 to makee sure you're on the same path.

The issue @dellis1972 and i ran into is text events on desktop PCs are so much more complex than one would imagine it could be.  See https://wiki.libsdl.org/Tutorials/TextInput

Still we will accept improvements to what we have now.

**Comment by james0x0A** [comment]
@tomspilman  Ah I see,   I couldn't get  SDL to send a control character on combined keypresses such as Ctrl+V. I think my current changes to SDL might have wiped out backspace.  This is a tricky problem.

I think part of the solution might be to mirror the systems that the data is coming from..   SDL and Winforms have the same model of exposing modifiers on KeyDown events.  It might be worth while to expose platform independent KeyDown/Up  events as an alternative to the provided Keyboard class.

**Comment by james0x0A** [comment]
I am looking at implementing this differently so as not to change the expectations around TextInputEvent.  I'll submit a PR soonish.
