### ISSUE TITLE
monogame.net redirects to bing

### ISSUE THREAD

**Issue by aolko** [MonoGame/MonoGame#5250]
is this intended?

**Comment by KonajuGames** [comment]
No.  It is a temporary issue as domains that were registered by Xamarin are transferred to Microsoft.  We are in the process of getting the domain back.  You can use [monogame.org](http://monogame.org) for now.

**Comment by aolko** [comment]
please put it in the readme or somewhere public

**Comment by tomspilman** [comment]
We're not going to alter any readmes or any other links for now.  This is a temporary issue and should be resolved soon.
