### ISSUE TITLE
Monogame.net redirects to Bing search

### ISSUE THREAD

**Issue by MarcVador** [MonoGame/MonoGame#5251]
I saw an issue about this 2 hours ago and I can't find it now.
Am I the only one experiencing this ?
I tried on my smartphone to confirm it is not coming from my computer and not from my network.

**Comment by KakCAT** [comment]
Same has been happening to me since last night. Community can be accessed from http://107.170.24.209/ meanwhile.

**Comment by MarcVador** [comment]
Ok :)
With this issue, it is impossible to login onto the community with a gmail account (and I think others too)

**Comment by tomspilman** [comment]
> it is impossible to log in to the community with a gmail account

Yeah that is one thing that is really difficult to support with multiple domains.  All these services expect a redirect to a single fixed url.

The good news is this should be fixed in the next 24 hours.

**Comment by MarcVador** [comment]
I think this can be closed :)
