### ISSUE TITLE
ModelMeshPart Effect adding difference between MonoGame and XNA

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#5252]
I have this (very ugly and dirty) piece of code:

```
	
    // backup current effects
	i=0;
	foreach (ModelMeshPart p in mesh.MeshParts)
	{
		originalEffect[i++]=p.Effect;
		
		if (i==2) p.Effect=envEffect2;
		else p.Effect=envEffect1;
	}

	// draw
	mesh.Draw();

	// restore effects
	i=0;
	foreach (ModelMeshPart p in mesh.MeshParts)
	{
		p.Effect=originalEffect[i++];
	}
```

Basically I have a car with basic effect, and I change all the Basic Effects for Environment Effects in the menu screen to show it with environment.
After drawing, I restore the effects.

This works well with XNA, but there's a side effect in MonoGame. The number of effects inside mesh.MeshParts.Effect keeps increasing one each frame when setting p.Effect = something

It seems to me that when setting the effect, in MonoGame the effect is always added to the Effect pool, but in XNA it is only added when that effect is not present in the pool. So, using
``` 
if (!parent.Effects.Contains (_effect)) parent.Effects.Add(value);
```
in ModelMeshPart.Effect setter seems to fix the problem, although I don't know enough of MG to say if this will imply side-effects.

**Comment by KonajuGames** [comment]
That sounds like a reasonable and logical fix.  It makes sense.

**Comment by nkast** [comment]
Mesh.Effects is not a real Collection. 

"ModelMesh.Effects is a shortcut for iterating over the MeshParts property of the ModelMesh and looking up the ModelMeshPart.Effect property of each ModelMeshPart. "
https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.modelmesh.effects.aspx

**Comment by jamesford42** [comment]
That `if not contained, add element` snippet he posted was a change to "ModelMeshPart.Effect setter". Mesh.Effects being a ReadOnlyCollection is not relevant to the discussion as far as I can tell.

**Comment by nkast** [comment]
@jamesford42 I don't get what you mean. Mesh.Effects can be implemented as an Enumerator. Also MeshPart should not have any ref to parent Mesh (if possible).

**Comment by nkast** [comment]
There is abetter way to fix that. No need to maintain a real collection. The effectsenumerator is actually an enumerator of Mesh.MeshParts. Instead of MeshPart it returns its Effect.

I will send a PR later.

**Comment by jamesford42** [comment]
Sure, go for it. This was just the minimal change to fix the issue as it was reported. I don't know where any of this code came from or how long its been there, but it isn't mine, I won't be offended.

**Comment by nkast** [comment]
For the record, I write bad code every day when I want to get things done.

**Comment by nkast** [comment]
Here is what I had in mind.
https://github.com/nkast/MonoGame/commit/899ad499b297e92038f83ca68e2dc4972f9e79d6
On a second though, it's bad in terms of performance. In order to remove Duplicates we have to iterate through the MeshParts in almost every method , and generate some garbage in the process. 

I forgot one of my mottos, 'Fast code is ugly'. The current approach is fine! and so is #5253.
