### ISSUE TITLE
Why don't MonoGame.Tests.Windows work with VS2015 test manager?

### ISSUE THREAD

**Issue by zass30** [MonoGame/MonoGame#5254]
Why don't the unit tests for MonoGame.Tests.Windows work in the VS2015 test manager? Currently, it seems that you have to run a separate MonoGameTests executable found in the output folder of MonoGame.Tests.Windows. Output goes to an HTML page.

Visual Studio has pretty nice test integration and reporting features. It's also very nice to be able to set breakpoints in your unit tests right in VS, and step through code. VS tests are compatible with nunit, but the tests won't compile if you reference the Nuget version of nunit (http://community.monogame.org/t/monogame-tests-windows-not-compiling-in-vs2015-solved/8320)

Is there a historic reason why the test framework isn't compatible with VS? Do people not like the VS test manager? 

I realize that Monogame is a cross platform project, but since the solutions themselves are Visual Studio solutions, it seems logical that the test framework with be compatible with Visual Studio too.

**Comment by tomspilman** [comment]
Hey @zass30 

> Why don't the unit tests for MonoGame.Tests.Windows work in the VS2015 test manager?

Mostly because our test framework was written 5 years ago or so.


> seems that you have to run a separate MonoGameTests executable found in the output folder of MonoGame.Tests.Windows. Output goes to an HTML page.

That is one way you can run them.  The benefit of that method is we can run it on platforms where there isn't another tool...  like mobile devices and consoles.  It is very useful to have a command line runner that writes out its own report.

Still since it uses NUnit for the tests it means it is compatible with NUnit runners like the ones in Resharper which is how I normally run them when developing stuff.


> it seems logical that the test framework with be compatible with Visual Studio too.

If we can make some small fixes that doesn't break the other ways we run unit tests then i'm fine with PRs for that.

**Comment by zass30** [comment]
Thank you for the re ply @tomspilman . VS2015 test manager has an nunit test runner, and normally works with nunit tests. However, it the nunit package referenced with monogame isn't compatible with the one used in the monogame unit tests. Tests won't compile because of the [Ignore] label -- the nunit version from nuget in VS wants Ignore("reason"), and doesn't have a constructor for Ignore().

I'd make the argument that since resharper is a paid product, it would be more accessible for the tests to be runnable within VS natively without having to buy resharper.

In any case, thanks for the response!

**Comment by tomspilman** [comment]
> However, the nunit package referenced with monogame isn't compatible with the one used in the monogame unit tests.

I think we could upgrade the version of NUnit we're currently using and do whatever small API fixes needed to support it.

> Maybe the first thing to do is move to nunit 3?

 Yeah...  i think we can do that.  I just created an issue for that specifically:  https://github.com/MonoGame/MonoGame/issues/5255

**Comment by tomspilman** [comment]
FYI. https://github.com/MonoGame/MonoGame/pull/6252
