### ISSUE TITLE
Upgrade to NUnit 3

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5255]
We should upgrade our current version of NUnit from 2.x to 3.x.  This would involve:
- Updating the assemblies in the dependency repo.
- Fixes to adhere to the new API changes in NUnit 3.x.
- Make sure that running unit tests on the automated build still works.
- Make sure the command line unit test runner still works.
- Make sure running unit tests via Resharper's runner still works.
- Make sure running unit tests via VS2015's test manager works.

This came up as part of a discussion on supporting VS2015 (see https://github.com/MonoGame/MonoGame/issues/5254).

**Comment by zass30** [comment]
I tried my hand at this -- several changes are straightforward like changing Ignore to Ignore("Reason"), but the first stumbling block I've hit is at \MonoGame\Test\Runner\Interface\CommandLineInterface.cs, line 89

			CoreExtensions.Host.InitializeService ();

This is from Nunit.Core.CoreExtensions in nunit 2. In nunit 3, I don't see anything that looks like this in the object browser. I've brought in nunit 3 from VS nuget manager, which auto references nunit.framework. 

![image](https://cloud.githubusercontent.com/assets/2244451/19819171/4d21d15a-9d08-11e6-8e41-94492cfd3bce.png)

Does anyone know what the equivalent of this call is in nunit 3?

**Comment by james0x0A** [comment]
The nunit console runner is probably a good resource for how to set things up.

https://github.com/nunit/nunit-console

**Comment by tomspilman** [comment]
Yeah how the console runner works might need to be totally different when upgrading to 3.x.  The important part is that we still have a way to run the unit tests from the console when needed.

**Comment by james0x0A** [comment]
Looks like the xml format has changed to utilize atributes more heavily, but all the information is there.  Its just a matter of updating the xsl transform.

2.5 result example http://nunit.org/files/testresult_25.txt

3.0 result example http://nunit.org/files/testresult_30.txt

**Comment by tomspilman** [comment]
> Its just a matter of updating the xsl transform.

Sounds good then!

**Comment by Jjagg** [comment]
This can also help speeding up tests (#4704) since NUnit 3 supports running test [in parallel](https://github.com/nunit/docs/wiki/Parallel-Test-Execution#parallel-execution-within-an-assembly)

**Comment by tomspilman** [comment]
> NUnit 3 supports running test in parallel

We can't do this for all tests... as some stuff is not thread safe by design.  Still assuming we can define this on a per-test basis we could use it on some.

**Comment by Jjagg** [comment]
I got things working. I'll see if I can get parallellization in too. I didn't have to change the xsl transform because they have a writer that spits out the same xml as NUnit 2.0 :)

**Comment by zass30** [comment]
@Jjagg did your commit your changes? I'd be interested in seeing if the nunit 3 conversion works with VS2015 built in test manager.

**Comment by Jjagg** [comment]
I did not because I couldn't get Protobuild to handle the dependencies right. Though I tried running the test suite after the conversion with VS test manager and that worked. I did have to install the NUnit Test Adapter https://www.nuget.org/packages/NUnit3TestAdapter/

**Comment by zass30** [comment]
I'd be really interested in playing with what you have. I think being able to run from VS test manager would be a real bonus! Would you be able to share what you have in some form? I'm ok with it not working with protobuild, as long as I know what instructions to follow :)

**Comment by KonajuGames** [comment]
For the Tests to show up in the VS Test Explorer you need the NUnit Test
Adapter Extension to suit the version of NUnit, regardless if it is NUnit 2
or 3. But you don't need the extension just to run all the tests. Just
select the Tests project as the startup project and run it as you would any
other project. You get the same HTML report at the end.

**Comment by Jjagg** [comment]
@zass30 My branch is over at https://github.com/Jjagg/MonoGame/tree/nunit

**Comment by zass30** [comment]
@KonajuGames Thanks, that worked! I had originally been installing the nunit3 test adapter, and that's probably why it was wanting nunit 3. I'm noticing a lot of tests fail in the test manager, but then pass when I select them individually 

For example, the ZeroSizeShouldFailTest fails when I do Run All with the error: " Attempted to read or write protected memory. This is often an indication that other memory is corrupt.". 

I select it and run it individually, it passes.

**Comment by tomspilman** [comment]
FYI. https://github.com/MonoGame/MonoGame/pull/6252
