### ISSUE TITLE
Drag and drop files in the Content Pipeline tool on windows

### ISSUE THREAD

**Issue by simoneddeland** [MonoGame/MonoGame#5256]
I just downloaded the latest development build from http://www.monogame.net/downloads/ to check out how the pipeline is looking now. As I understand it, it now uses WPF instead of whatever was used previously. However, drag and drop support for adding files to a content project does not work anymore, which it used to in Monogame 3.5.

**Comment by DDReaper** [comment]
This has been improved in MG 3.6.  If you check my YT channel, even the first video demonstrates this.
http://bitly.com/darksideofmonogame
So it's already been done

TBH, I thought it was possible in 3.5 already but maybe that is just the mists of time blurring my vision

**Comment by simoneddeland** [comment]
@DDReaper I checked out your youtube-channel and the content pipeline tool you are using in the video https://www.youtube.com/watch?v=OZpW13ERTnQ looks like the pipeline tool from MG 3.5 (where drag and drop worked for me as well). 

The version that does **not** support drag and drop is the newest development build from http://www.monogame.net/downloads/ (which is 3.6.0.1060 now). The pipeline tool looks a bit different and drag and drop is not supported.

**Comment by cra0zy** [comment]
Pipeline Tool has been ported to Eto.Forms so that there can be the same code base for both Windows and Unix. Anyway drag & drop support was lost and I'll try to get it reimplemented sometime soon.

**Comment by DDReaper** [comment]
Right, thanks for the update @cra0zy , good to know I'm not losing my marbles.

Critical through to get that back for 3.6

**Comment by simoneddeland** [comment]
@cra0zy Good to hear, lets hope its easy to implement!

**Comment by cra0zy** [comment]
PR is up.
