### ISSUE TITLE
Rectangle.Contains is probably broken

### ISSUE THREAD

**Issue by elisee** [MonoGame/MonoGame#5270]
Hi!

Just a drive-by report. I saw this PR fixing `Rectangle.Contains` that was merged in FNA recently: https://github.com/FNA-XNA/FNA/pull/56

It looks like MonoGame might have the same bug: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Rectangle.cs#L242

**Comment by tomspilman** [comment]
Thanks.  Just need someone to prove the fix with unit tests and submit a PR.

**Comment by elisee** [comment]
I don't use MonoGame so for anyone that want to do that, note there's a one-line repro in the original PR:

```
Assert.IsFalse(new Rectangle(0, 0, 5, 5).Contains(new Rectangle(1, 1, 5, 5))); // throws
```

**Comment by Jjagg** [comment]
The implementation in MG looks okay to me. You linked the implementation of Rectangle.Contains(Point). 

Rectangle.Contains(Rectangle) is at https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Rectangle.cs#L303
```
public bool Contains(Rectangle value)
{
    return ((((this.X <= value.X) && ((value.X + value.Width) <= (this.X + this.Width))) && (this.Y <= value.Y)) && ((value.Y + value.Height) <= (this.Y + this.Height)));
}
```

I think the method was implemented after FNA got forked from MG.

**Comment by tomspilman** [comment]
> I think the method was implemented after FNA got forked from MG.

The FNA project fairly actively pulls fixes from MonoGame, so that could be true.

**Comment by flibitijibibo** [comment]
I think EnoughTea sent the fix to both projects, so MG should be okay.

**Comment by tomspilman** [comment]
Thanks for the heads up @elisee and @flibitijibibo .

I'm closing this...  our implementation is from 2011 and looks to be correct from our unit tests:

https://github.com/MonoGame/MonoGame/blame/develop/MonoGame.Framework/Rectangle.cs#L303
https://github.com/MonoGame/MonoGame/blob/develop/Test/Framework/RectangleTest.cs#L160

**Comment by elisee** [comment]
Oh, my bad, should have looked closer. I saw similar code and didn't notice it was the (x, y) overload.
