### ISSUE TITLE
Cross Platform Desktop Project doesn't support VideoPlayer

### ISSUE THREAD

**Issue by bangclash** [MonoGame/MonoGame#5277]
Cross Platform Desktop Project doesn't support VideoPlayer object. Same code doesn't have error in DirectX project.

![capture](https://cloud.githubusercontent.com/assets/10566143/20027061/d0f2345c-a2c6-11e6-8aae-f324c864848e.PNG)

**Comment by cra0zy** [comment]
Duplicate of #3983

**Comment by cra0zy** [comment]
@tomspilman This is a duplicate, it can be closed.
