### ISSUE TITLE
MonoGame UWP VB template broken

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#5279]
I just updated the UWP C# template with some fixes for new .NETCore versions and an update for deploying on Xbox.

However I noted there was a VB version as well, but I was unable to get it working in the latest 3.6 dev build.

Any chance the original author could look at that?

**Comment by tomspilman** [comment]
> However I noted there was a VB version as well, but I was unable to get it working in the latest 3.6 dev build.

Yeah it was added by @vogles  earlier this year.

**Comment by Jjagg** [comment]
Gonna close this for #5855.
