### ISSUE TITLE
In Develop Branch v3.6.0.1089 the Content Pipeline Tool don't show the properties of any asset

### ISSUE THREAD

**Issue by vcrobe** [MonoGame/MonoGame#5285]
Yesterday I was testing the develop branch v3.6.0.1089 and when I select any item it doesn't show the properties in the property window.

![untitled](https://cloud.githubusercontent.com/assets/7717678/20100223/8c9e35aa-a58a-11e6-8e0f-d4740c864bca.png)

Note: The screenshot was taken using the master branch

I'm using Window 10 and DirectX.

**Comment by MarcVador** [comment]
It works for me. On both computers.
Have you looked into you .mgcb file to see what properties of the asset it contains ?

**Comment by vcrobe** [comment]
I don't get that issue with the master branch. After the error I've reinstalled the stable version (master branch) recompiled the game and it's working again as expected.

The _.mgcb_ file was created with the Content Pipeline Tool of the master branch and I've never modified it with the tool of any version of the develop branch so I don't think the file has any problem. Anyways if you suspect something about it I can send it to you.

**Comment by Grocknir** [comment]
I encountered this issue as well, and it seems to be triggered by Windows' display scaling. I guess if you use any setting other than 100% the field will be empty, at least it was with 115% and 125%. With 100% scaling everything is fine.

**Comment by Jjagg** [comment]
Same issue here. I set display scaling to 125% and properties aren't displayed anymore. Switched back to 100% and everything is fine.

**Comment by vcrobe** [comment]
@Grocknir the problem is related to the display scaling as you mentioned. I'm using 125% changed it to 100% and now the properties are shown as expected.

**Then I tested all the scale values and the properties are shown with all of them but 125%**

So the issue arise only when the scaling is 125% (at least in my PC). Can anyone verify the issue with scales greater than 125% and see if it works?

**Comment by Grocknir** [comment]
I can confirm that scaling values of 100%, 150% and 175% display the properties properly.
With 115% (using the semi-hidden custom scaling) and 125% (using Windows 10's default scaling method) they're gone.
I'll see if I will find some time to test 200% and 225% as well as a few additional values using the custom scaling method tomorrow.

**Comment by tomspilman** [comment]
@cra0zy ?

**Comment by cra0zy** [comment]
Sounds like an issue in Eto.Forms, I'll take a look tomorrow.

**Comment by cra0zy** [comment]
I am unable to reproduce the issue on my system... one thing to note is that I am using an Insider Preview so this might also be a Windows bug?

**Comment by mrhelmut** [comment]
I'll give it a test on my Win10 by tomorrow.
Hi-DPI support in Win10 is quite messed up right now. Not that Win10 does anything wrong (it's doing it better that any OS), but software which support it are very rare and full of issues (recent games inc.).

**Comment by Grocknir** [comment]
@cra0zy Did you sign out and back in again after changing the scaling? The content pipeline does not respond to it until after you signed out, simply re-opening it is not enough.

**Comment by cra0zy** [comment]
@Grocknir Thanks, that caused it for me.
