### ISSUE TITLE
Develop branch v3.6.0.1089 play some sounds in the left speaker only (mono)

### ISSUE THREAD

**Issue by vcrobe** [MonoGame/MonoGame#5286]
When I play the game using the develop branch v3.6.0.1089 some sounds are played only in the left speaker only.

I don't know why some are played like that because all of them are .ogg files.

Also, you should test the songs too. In my case I only have one and it's played stereo but who knows having more than one.

Note: using the master branch this never happen.

I'm using Window 10 and DirectX.

**Comment by cra0zy** [comment]
Duplicate of #5054

**Comment by vcrobe** [comment]
I think so
