### ISSUE TITLE
Get content of project in MonoDevelop

### ISSUE THREAD

**Issue by legionlab** [MonoGame/MonoGame#5293]
I'm trying to insert a PNG image in my game, but I'm not getting, the image is in Content/alien.png with the code below:

```
Texture2D alien;
.
.
.
protected override void LoadContent ()
{
    spriteBatch = new SpriteBatch (GraphicsDevice);
    Content.RootDirectory = "Content";
    alien = Content.Load<Texture2D>(@"alien");
}
```

When I run the game pops up the error message:

> **Microsoft.Xna.Framework.Content.ContentLoadException: Could not load alien asset as a non-content file!** ---> Microsoft.Xna.Framework.Content.ContentLoadException: The directory was not found. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/leonardo/Documentos/Mono/MaisUM/MaisUM/bin/Debug/Content/alien.xnb". at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x001cf] in :0 at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in :0 at at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
> at System.IO.File.OpenRead (System.String path) [0x00000] in :0 at Microsoft.Xna.Framework.TitleContainer.OpenStream (System.String name) [0x00029] in :0 at Microsoft.Xna.Framework.Content.ContentManager.OpenStream (System.String assetName) [0x0002e] in :0 --- End of inner exception stack trace --- at Microsoft.Xna.Framework.Content.ContentManager.OpenStream (System.String assetName) [0x00053] in :0 at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T] (System.String assetName, System.Action1[T] recordDisposableObject)
>   [0x00073] in <c33f6c525d914593acc9b590397e7c2b>:0   --- End of inner
>   exception stack trace ---   at
>   Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T]
>   (System.String assetName, System.Action1[T] recordDisposableObject) [0x0012b] in :0 at Microsoft.Xna.Framework.Content.ContentManager.Load[T] (System.String assetName) [0x00068] in :0 at MaisUM.Game1.LoadContent () [0x0002e] in /home/leonardo/Documentos/Mono/MaisUM/MaisUM/Game1.cs:46 at Microsoft.Xna.Framework.Game.Initialize () [0x0004d] in :0 at MaisUM.Game1.Initialize () [0x00002] in /home/leonardo/Documentos/Mono/MaisUM/MaisUM/Game1.cs:35 at Microsoft.Xna.Framework.Game.DoInitialize () [0x00011] in :0 at Microsoft.Xna.Framework.Game.Run (Microsoft.Xna.Framework.GameRunBehavior runBehavior) [0x00033] in :0 at Microsoft.Xna.Framework.Game.Run () [0x0000c] in :0 at MaisUM.Program.RunGame () [0x00010] in /home/leonardo/Documentos/Mono/MaisUM/MaisUM/Program.cs:31 at MaisUM.Program.Main (System.String[] args) [0x00001] in /home/leonardo/Documentos/Mono/MaisUM/MaisUM/Program.cs:55

Probably the error is because he expects a xnb file, but I only have a .PNG because Linux does not found a way to convert. Could someone help me?

**Information:** Linux Elementary the Freya - MonoDevelop 5.10 - MonoGame 3.5

**Comment by KonajuGames** [comment]
The content pipeline imports and processes textures and sounds to XNB files.  The Pipeline Tool is a GUI for managing your content project, and MGCB is the application that does the processing.

**Comment by legionlab** [comment]
I can't find where to install the Pipeline on Linux, on the site of monogame says he comes along with the monogame-sdk.run, but I install it and does not appear anywhere, except in MonoDevelop, that allows you to create a Content Pipeline MonoGame solution Library. But I don't know how it works, could you help me?

**Comment by Jjagg** [comment]
The installer creates a .desktop file so the pipeline tool should be available from your application launcher if you have one. If the installation was succesfull the pipeline tool should start up when you try to open the .mgcb file. Alternatively try running monogame-pipelinetool (or maybe pipeline-tool, I'm not sure try autocomplete) in a terminal.

**Comment by legionlab** [comment]
I managed to run the Content. my solution mgcb, the Pipeline opened normally, I added a sprite, but when you build error is displayed:

> Build started 11/11/2016 16:53:52
> 
> /home/leonardo/Documentos/Mono/Ultimo/Ultimo/Content/alien.png
> /home/leonardo/Documentos/Mono/Ultimo/Ultimo/Content/alien.png: error: Importer 'TextureImporter' had unexpected failure!
> System.DllNotFoundException: libfreeimage-3.17.0.so
>   at (wrapper managed-to-native) FreeImageAPI.FreeImage:GetFileType (string,int)
>   at FreeImageAPI.FreeImage.LoadEx (System.String filename, FreeImageAPI.FREE_IMAGE_LOAD_FLAGS flags, FreeImageAPI.FREE_IMAGE_FORMAT& format) [0x00026] in <f706b8ca83a34e888e47eb199bbc0923>:0 
>   at Microsoft.Xna.Framework.Content.Pipeline.TextureImporter.Import (System.String filename, Microsoft.Xna.Framework.Content.Pipeline.ContentImporterContext context) [0x00033] in <279c948b8d624a51ba8f1bf6590afc0d>:0 
>   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1[T].Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import (System.String filename, Microsoft.Xna.Framework.Content.Pipeline.ContentImporterContext context) [0x00022] in <279c948b8d624a51ba8f1bf6590afc0d>:0 
>   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent (MonoGame.Framework.Content.Pipeline.Builder.PipelineBuildEvent pipelineEvent) [0x00081] in <279c948b8d624a51ba8f1bf6590afc0d>:0 
> 
> Build 0 succeeded, 1 failed.
> 
> Time elapsed 00:00:01.34.


What can be?

**Comment by legionlab** [comment]
Got it, installed the MonoGame 3.4, after that deleted it and installed 3.5, so it worked.
