### ISSUE TITLE
Make SortingFilteringCollection public

### ISSUE THREAD

**Issue by MontyHimself** [MonoGame/MonoGame#5295]
I wanted to modify the drawing behaviour for drawable game components in my project and stumbled upon this class while looking through the MonoGame source code. I think it would be a useful addition if one could make use of this to implement some custom behaviour for the Draw() and Update() methods regarding game components.

This is the class I am talking about, nested inside the Game class:
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Game.cs#L773

**Comment by Jjagg** [comment]
I'm rejecting this proposal. The `SortingFilteringCollection` is an implementation detail and exposing it means maintaining the API for general use. MG should not provide loose custom collection classes like this.
