### ISSUE TITLE
MonoGame stops responding opening "Content"

### ISSUE THREAD

**Issue by Deadbellza** [MonoGame/MonoGame#5298]
MonoGame pipeline crashes whenever i try to open either the content tool with in visual studios, i have all the system requirements that it is asked for and haven't been able to find any solutions on the internet?

**Comment by KonajuGames** [comment]
What error message do you get?  What version of Windows are you using?  32-bit or 64-bit Windows?  The MonoGame Content Pipeline requires Windows 64-bit.

**Comment by Horstj** [comment]
Same Problem: pipeline.exe crashes almost instantly (taskmanager showes the process for about a second in details) without any notification or error. CMD retuns errorlevel -532462766
It doesn't matter wether I double click content in VS or try to run pipeline.exe directly.

**Comment by cra0zy** [comment]
I'm guessing this got fixed a long time ago, in a galaxy far far away...
