### ISSUE TITLE
[UWP] Mouse input blocks/delays keyboard input

### ISSUE THREAD

**Issue by MuletTheGreat** [MonoGame/MonoGame#5300]
InputEvents.cs is where the keyboard/mouse events are attached to allow MonoGame to collect input.

If the mouse is moving/clicking then keyboard input is delayed until it stops. This includes key released states, so it effects first person game very badly.

Attaching to the CoreWindow's keyboard and mouse events shows this.
Attached to the CoreIndependentInputSource for the Mouse, with the keyboard coming from the CoreWindow (standard practice) also causes this.

This did not occur in Windows 8/8.1 and only occurs in Windows 10.

**Comment by tomspilman** [comment]
Fixed in #5520.
