### ISSUE TITLE
OpenTK - Failed to make context #(number) current. Error: 0 

### ISSUE THREAD

**Issue by Verser** [MonoGame/MonoGame#5330]
OpenTK.Graphics.GraphicsContextException was unhandled
Message: An unhandled exception of type 'OpenTK.Graphics.GraphicsContextException' occurred in OpenTK.dll
Additional information: Failed to make context 131072 current. Error: 0
Ive also received error 2004 once.

I am getting this error several minutes after the program has started running. I am not sure what is causing it. I've seen some other issues posted. But they were fairly different or were closed citing that newer versions should "fix" the problem. 

Similar to[ issue 741](https://github.com/MonoGame/MonoGame/issues/741), I am passing the spritefont to different objects. But I haven't had this issue in older versions of Monogame or XNA. 

I am noticing the GC is going nuts, but only to this project (on the newer version of MG).  I dont use dispose on any of the textures manually, as everything is being used for the whole game.

**Comment by Verser** [comment]
While I haven't fixed the OpenTK issue, I did go in and scale back the texture creation. Which has allowed the game to run for 15 minutes again no problem.

I made a huge mistake, by creating new procedural generated gib textures and outline of an object every time it was moused over. Saving gibs and outline/border textures for later use, and then realigning them with the objects as they more or get resized has definitely fixed cut my texture creation way down, though it uses more memory when idle, it's much less overall at run-time.

The next step is probably just creating a dispose for them so they can be cleared from memory when they are off screen or so much time has passed.

**Comment by cra0zy** [comment]
OpenTK has been replaced by SDL + Custom GL/AL wrappers in the develop branch, and this issue is probably already resolved in it.

**Comment by Verser** [comment]
Even better. I got exposed to my mistake in the engine code, and the texture issue will be fixed.

Thanks for the update @cra0zy 

@tomspilman, should we close this until I can test it in the new SDL based branch?

**Comment by tomspilman** [comment]
@Verser - Fine to leave this open for now...  just be sure to come back here and update it soon.

**Comment by cra0zy** [comment]
It doesn't make sence to leave this issue open considering we closed all other issues that have been fixed in develop branch.

**Comment by cra0zy** [comment]
@tomspilman This got fixed.
