### ISSUE TITLE
NuGet dev branch package search is case sensitive

### ISSUE THREAD

**Issue by GameKyuubi** [MonoGame/MonoGame#5343]
- Add the Monogame dev feed to NuGet package manager sources
- Select "All" sources in the source dropdown
- Check "Include Prerelease" by the search bar
- Search for "MonoGame"
- Note that 3.6 builds show up
- Search for "monogame" or "Monogame"
- Note that only 3.5 builds show up

I guess it's not a gigantic problem but it did waste 24 hours of my time before I figured it out and I imagine I'm not the only one who has had this problem.

**Comment by Apostolique** [comment]
I don't think this applies anymore. Most likely good to close.
