### ISSUE TITLE
monogame as application

### ISSUE THREAD

**Issue by mister-giga** [MonoGame/MonoGame#5344]
If I want to create a fully custom environment (controls like buttons, labels, textboxes...) for three platforms UWP, Android and iOS. Is this thing named MonoGame what I need to use? I mean I dont want to make games but I want to make applications just like any random app on any platform, will this platform help me to achieve this?

**Comment by dlnieves** [comment]
Hello. Monogame produces code that is intended to be executed "within" the graphics device(card), its api is inherently optimized for graphics and thus games and multimedia. Also, the intensive use of graphics resources has a cost regarding to execution. Well, you could build a custom UI api from scratch that resembles for example: WPF and there you go.

**Comment by mister-giga** [comment]
I want to do UI api that looks exactly like WPF but to be more modern for UWP, Android and iOS. So MonoGame is what I am looking for! Thanks!

**Comment by dlnieves** [comment]
OK

**Comment by KonajuGames** [comment]
You could have a look at the [Empty Keys UI Library](http://emptykeys.com/).  You build the UI in Visual Studio using XAML and it uses MonoGame to render it.

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
