### ISSUE TITLE
Texture DDS 24 bit - content build fail - Unsupported RGB exception

### ISSUE THREAD

**Issue by kvenkateshan** [MonoGame/MonoGame#5345]
24 bit RGB DDS textures don't build.

Here's the link to one of our 24 bit DDS textures for testing:
https://www.dropbox.com/s/n835ojlc8ej1zgo/Stadium_60001_Atlas0.rar?dl=0

**Comment by tomspilman** [comment]
@KonajuGames  - Looks like we didn't implement the 24bit case in here:
 https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/DdsLoader.cs#L133

Got time to address this?

**Comment by KonajuGames** [comment]
This shouldn't take long to implement and test.  Thanks for the test image, @kvenkateshan.

**Comment by kvenkateshan** [comment]
It looks like the case that is not handled is Ddpf.Rgb with no alpha pixels that is 32 bits (*not 24). Not sure what should be the bit mask and surface format for the case but I am able to build fine by using the below format and mask.

else if (pixelFormat.dwRgbBitCount == 32)
 {
    rbSwap = pixelFormat.dwBBitMask == 0xFF;
    return SurfaceFormat.Color;
 }

**Comment by kvenkateshan** [comment]
Using rbSwap = pixelFormat.dwBBitMask == 0xF0; gets me closer the xnb file size of PS4 binary.

**Comment by KonajuGames** [comment]
@kvenkateshan, this is now fixed in PR #5368.  Your test image now loads into the content pipeline and is processed correctly.

![image](https://cloud.githubusercontent.com/assets/694943/21392645/90f8b39a-c7dc-11e6-9153-a5194235316e.png)
