### ISSUE TITLE
Get an older version of monogame

### ISSUE THREAD

**Issue by gillesboisson** [MonoGame/MonoGame#5349]
Hello,

I tried to find a way to get an older version of monogame (3.6.0.121) with no success. I look on the teamcity.monogame.net platform but I didn't find a link between builds version and commits UID. Is there any way to find archives or commit of each version ?

Cheers

**Comment by Jjagg** [comment]
Build artifacts aren't stored forever, they get deleted after a while. You can build from source if you really want a specific version.

**Comment by gillesboisson** [comment]
Thanks, is there any way to clone repo and get back to the the commit of the specific version ( in my case 3.6.0.131 ) ? I didn't find in teamcity.monogame.net what was the commit (uid) was used for the version I want to compile

**Comment by tomspilman** [comment]
First 3.6.0.121 or 3.6.0.131?  You mentioned both.

TeamCity deletes the binaries of old builds, but still has the full history of all builds it has generated:

 http://teamcity.monogame.net/searchResults.html?query=3.6.0.121&guest=1

So looking at the changes for that build it looks to be from PR #4712 which was commit https://github.com/MonoGame/MonoGame/commit/72cad33ee8395ae73d9dad73d4c9786be0ff953e.

**Comment by gillesboisson** [comment]
cheers, I didn't got #4712 was PR. thanks for the quick reply.
