### ISSUE TITLE
Switching from OSX el Capitan to sierra

### ISSUE THREAD

**Issue by gillesboisson** [MonoGame/MonoGame#5363]
Hi,

I just did OSX update and had issues with monogame 3.5 (installed from pkg installer) and xamarin studio. Xamarin Addin seems to not work anymore (template not available), and old project (Crossplatform desktop) seems to compile but not exec (no exception thrown) and stop when loading mono drawing.dll. I tried with visual studio express (preview on mac) and everything works, visual studio use mono 4.8 and Xamarin studio use mono 4.6.2.
Is there any way to install / copy addin from xamarin to visual studio, or I need to recompile it ?  

Also tried with the 3.6 (addin available in xamarin beta channel) and I had issue explained here #5346 

Cheers

**Comment by mrhelmut** [comment]
Best route would be to have #5346 resolved and to switch to the 3.6 beta.

**Comment by gillesboisson** [comment]
Thanks, I'll do that.

**Comment by mrhelmut** [comment]
This should fixed now, @gillesboisson would you mind updating to latest develop and confirm?

**Comment by cra0zy** [comment]
This has been fixed by #6135
