### ISSUE TITLE
this.Window.AllowUserResizing = true; just got borked

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#5374]
Just downloaded the nightly. Last time i downloaded this was a couple weeks ago around the 4th i think and it was working fine. The maximize button is also not working. Im running win7 gl 

> An unhandled exception of type 'System.Exception' occurred in MonoGame.Framework.dll
> 
> Additional information: SDL 2.0.4 does not support changing resizable parameter of the window after it's already been created, please use a newer version of it.

^ this cant be right this is a basic thing too boot it wont even work in the constructor.  
Its basically stuck on false and cannot be resized first thing i saw. Ah god this is horrible lol.

This however now works like it did in xna within initialize.
> graphics.PreferredBackBufferWidth = 1000;
> graphics.PreferredBackBufferHeight = 800;
> graphics.ApplyChanges();

This is going to be like really annoying. Having to manually reset the window size constantly by typing in new numbers, i need that for my tests im running.

Edit.

Some where between the 4th version .0187 and the 10th it got busted. (i put back in 0187 this is going to be more difficult then just turning of the mouse). Unfortunately i wanted to use at least the version out on the 10th for the mouse garbage fix but its got the resize bug as well. I actually need both to work.

**Comment by mrhelmut** [comment]
Confirmed.

#5336 reverted the SDL 2.0.5 update in the dependencies repository ( @DDReaper ;-).

**Comment by KonajuGames** [comment]
I'll fix this later tonight if no-one pushes a PR beforehand.​

**Comment by KonajuGames** [comment]
PR #5375 is now up to fix this.
