### ISSUE TITLE
OpenAL initialization failing quite often

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5381]
Hello,

This is a problem that I never encountered locally, but our crash database is filled with these kind of crashes and we have several players complaining about it.

```OggStream``` ctor crashes at times, with ```External component has thrown an exception```, which makes it quite hard to understand remotely and would indicates that the native side of OpenAL-Soft is failing.

It happens on a simple ```Content.Load<Song>()```. No threading involved. Here's the full stack trace:

```
   at Microsoft.Xna.Framework.Audio.OpenALSoundController.ReserveSource()
   at Microsoft.Xna.Framework.Audio.OggStream..ctor(String filename, Action finishedAction, Int32 bufferCount)
   at Microsoft.Xna.Framework.Media.Song.PlatformInitialize(String fileName)
   at Microsoft.Xna.Framework.Media.Song..ctor(String fileName, Int32 durationMS)
   at Microsoft.Xna.Framework.Content.SongReader.Read(ContentReader input, Song existingInstance)
   at Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read(ContentReader input, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T](T existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
```

The thing is that ```OpenALSoundController.ReserveSource()``` doesn't make any call to OpenAL, so the problem may be elsewhere.

Note that by the time this code is reached, we already successfully initialized the device and loaded a few ```SoundEffect``` before loading the ```Song```, which indicates that the AL device and buffers initializations are doing fine until song loading.

If anyone has inputs regarding this issue, that would be very welcome. I haven't been able to reproduce it.

**Comment by tomspilman** [comment]
> the native side of OpenAL-Soft is failing

I see a few possibilities:

  1. 32bit vs 64bit game binary.
  2. The OpenAL-Soft binary depends on some missing Windows components.
  3. The OpenAL-Soft binary is missing all together.

2 is what I suspect the most here.

**Comment by mrhelmut** [comment]
2 Looks like a good candidate.

I have different exceptions occurring with 1 & 3, and these are most likely linked to corrupted installations.

We probably have too few Linux/Mac users to confirm this, but it looks like a Windows only problem.

**Comment by tomspilman** [comment]
Looking at soft_oal.dll in Dependency Walker I see it depends on MSVCRT.DLL.  My guess is that this library is missing on some systems causing this issue.

Our best bet is to rebuild soft_oal.dll to use the static lib version of the CRT runtime to avoid the problem.

However my guess is that if you install the correct CRT runtime on these systems it would fix the problem.

**Comment by mrhelmut** [comment]
Interesting, I'll take a look at this.

**Comment by mrhelmut** [comment]
I've built OpenAL-Soft using VS2012 with static linking and sent it to a few players with this issue. I'll let you know how it goes.

The binaries from kcat website are built with MinGW, which links to the legacy VC 6.0 runtime (which is supposed to be a system dll but can be easily corrupted by any installer compared to newer runtime).

This makes me notice that SDL2 is also built with MinGW and links to VC 6.0 runtime. Potential issue too is this is the correct problem.

**Comment by tomspilman** [comment]
> but can be easily corrupted by any installer compared to newer runtime

Yeah that is true.

>  SDL2 is also built with MinGW and links to VC 6.0 runtime

Yep...  I think we really should ensure all our native libs are static linked to the VC runtime.  Yes it does bloat up the binaries with some duplicate code, but it ensures things work correctly.

**Comment by mrhelmut** [comment]
Update: the OpenAL-Soft binaries build with static linking fail too.

**Comment by mrhelmut** [comment]
I'm trying to investigate this issue more but I'm running into a dead end.

It really is Windows-only, and is apparently not linked how OpenAL-Soft is built (VC runtime statically built or not). We have a few players who tested our statically built OpenAL version and it didn't prove useful.

So far, my best guess is that the target computers having this issue have some software installed which adds virtual sound devices (e.g. audio capture, audio routers, streaming software) and OpenAL-Soft tries to initialize the wrong device.

We should try initializing OpenAL differently, for example by enumerating all devices and sticking with the first working one. A plus would be to have some mechanism to allow users or developers to list sound devices and make interactive device selection (or config files).

Also, not related but it would help a lot, OpenAL initialization shouldn't be a critical failure. DesktopGL apps should be able to run without sound support. This requires some refactoring of the AL code.

**Comment by mrhelmut** [comment]
@endimilojkoski seems to have encountered this issue in #4539

Does it still happen? Do you have any way to investigate this issue?

This forum thread: http://community.monogame.net/t/how-to-ship-openal/8539/6

seems to indicate that it is a ```InstancePlayLimitException``` (which would mean that the device couldn't create any AL source), but also indicates that it could be a dll bitness problem. Maybe the 32bit dll failing, or the bitness detection.

**Comment by mrhelmut** [comment]
The problem seems to be coming from ```OpenALSoundController.OpenSoundController()```.

It looks like it can happen that the AL device and the AL context are both correctly initialized, but ```OpenSoundController``` somehow considers it to have failed, and therefore ```_bSoundAvailable``` is never set to ```true``` but the program continues with a valid AL device and context, ending up with an ```External component has thrown an exception``` on this exception: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/OpenALSoundController.cs#L423

This can be reproduce by adding ```return(false)``` after https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/OpenALSoundController.cs#L286

Still don't know how this can happen and how to make it more robust.

**Comment by mrhelmut** [comment]
After pushing #5547 to our public Steam build, we found that ```_device = Alc.OpenDevice(string.Empty);``` fails with the error code 40964 (ALC_INVALID_VALUE), which means that OpenAL is unable to find any compatible output.

There are 2 possibilities:
- OpenAL Soft is built with some missing backends (which seems unlikely, especially after rebuilding it myself with all backends in)
- The client computer doesn't have DirectSound support

Anyway, #5547 seems to have clean up a lot a false positive errors, and it returns correctly a ```NoAudioHarwareException``` upon all initialization errors, which is good.
