### ISSUE TITLE
SDL 2.0.5 not in dev build installer even though dependent code changes are

### ISSUE THREAD

**Issue by YugeshN** [MonoGame/MonoGame#5383]
@cra0zy This is specifically related to some changes you made.

I just updated my Monogame install to the latest dev build (specifically 3.6.0.1246) after a couple months (was running an old dev build).

When I tried running my game, I was getting an exception when trying to enable window resizing viz.             Window.AllowUserResizing = true;

The exception was: "SDL 2.0.4 does not support changing resizable parameter of the window after it's already been created".

It looks like this change was made by you ~2 months ago:

https://github.com/MonoGame/MonoGame/commit/e9368c49e7a2ec6aa3e29cb9f33247ecedfc8555

It seems that even though the code changes for this are in the latest dev installer, the actual SDL2.dll that is bundled is version 2.0.4 and not version 2.0.5.

I manually updated my DLL to 2.0.5 and that seems to have fixed the problem.

It would be great to get the updated DLL into the installer as well.

Thanks.

**Comment by cra0zy** [comment]
MonoGame only provides newer SDL if you generate a new project, your existing project won't get it updated automatically.

On the bright side if I ever get time, #5262 will fix it.

**Comment by YugeshN** [comment]
@cra0zy  I had copied the x64 and x32 folders from the monogame opengl install folder into my project (erasing the old ones first}.  I always do this when I install a new version of monogame to ensure I have the updated dlls and libs in my project. 

The SDL dll in the monogame installed folder  (windows default install folder I. E program files (x86) \monogame\...)  is the older 2.0.4 version and not the 2.0.5 version. 

Or is there another location that the dll is pulled from?

**Comment by YugeshN** [comment]
The SDL version seems to be fixed in the newer builds.
