### ISSUE TITLE
Update assimp

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#5397]
Assimp should be updated to get some bugfixes in. This will most likely fix #5395 and will fix #4769. The maintainers haven't released binaries for the last few version so we need to build from source.

**Comment by polsys** [comment]
Also required for #4967.

**Comment by Jjagg** [comment]
I can do Windows and Linux, but not Mac. @KonajuGames? The latest assimp release is 3.3.1 so that's the one we should get.

**Comment by AliciaRaven** [comment]
Also connected to issue https://github.com/MonoGame/MonoGame/issues/4769

**Comment by KonajuGames** [comment]
I've been working on the OS X native binary.  As with building anything native on OS X, it's a challenge.  They embed the library search paths in the binary, so I'm trying to fix those up so they're not specific to my machine.

**Comment by tomspilman** [comment]
Note...  i'm looking to add `FbxImporter` unit tests first in https://github.com/MonoGame/MonoGame/pull/6158.

Then i will get a new AssImp version update which we can now test.

**Comment by tomspilman** [comment]
Update... i merged FBXImporter fixes and the latest AssImp on Windows.  However i need to update Linux and Mac versions of AssImp.  Will be doing this soon.

**Comment by harry-cpp** [comment]
Assimp has been updated, so closing this.
