### ISSUE TITLE
Which version C# should we target when making pull requests?

### ISSUE THREAD

**Issue by evgenidb** [MonoGame/MonoGame#5404]
A quick question: should we only use old C# syntax and features or we can use more recent ones like `nameof()` or `??` `?.` operators that came with VS 2015?

If we should support older version how far back to go?

**Comment by Jjagg** [comment]
The Windows build bot uses C# 5.0, so you can use `??` but not the others you mentioned.

**Comment by Jjagg** [comment]
If you're doing something on MonoGame and are not sure if something is a C# 6.0 feature, you can set the language version to 5.0 by setting Properties of the project > Build > Advanced... > Language Version: C# 5.0.

**Comment by evgenidb** [comment]
Thanks. Any idea of when or if a switch to newer version will happen?

**Comment by tomspilman** [comment]
Not sure... but we usually lag behind one or two VS releases.  So maybe once VS 2017 has shipped or around that time.

**Comment by Jjagg** [comment]
Is that just for users using older VS versions?

**Comment by tomspilman** [comment]
> Is that just for users using older VS versions?

Yes and people using older versions of XS on Mac/Linux.

**Comment by KonajuGames** [comment]
Closing this issue.
