### ISSUE TITLE
Calling GetData on IndexBuffer returns with missing data

### ISSUE THREAD

**Issue by AliciaRaven** [MonoGame/MonoGame#5413]
Using DesktopGL profile and calling IndexBuffer.GetData returns a byte array of the correct length, but with missing data. The end is padded out with zeros. Tested with same model loaded in 3.4 which returns correct data and current dev code which does not.

**Comment by Jjagg** [comment]
It's really weird that this worked in 3.4 considering the fix I made in #4882... Are you 100% sure the fetched indices are correct?

Just a quick tip: you're better off storing the index data in a managed buffer instead of pulling it from the GPU. If you can't, make sure you only pull it once and keep it stored in RAM.

**Comment by AliciaRaven** [comment]
Yes, I keep model data in my own format to save space, so after importing a collada mesh to monogames model, i take the vertex and index data out then save it. When its loaded the models looked ok using 3.4 but now are broken when importing using dev code.

I narrowed down the issue to the index buffer data returned by dumping the bytes for both vertex and index buffers to a file. Then used git diff to compare. The difference is the index block while being the same size as the correct version, after about halfway all values are zero. The array is the same size because its my code that creates it, its just not filled up with all data.

My test code has not changed between tests, i just swapped monogame dlls

**Comment by Jjagg** [comment]
How are you calling GetData and how many indices do you have? It could be your code is wrong for the current because the implementation was previously wrong.

**Comment by AliciaRaven** [comment]
byte[] arrOutPut = new byte[(MeshPart.PrimitiveCount * 3) * 2];
MeshPart.IndexBuffer.GetData(MeshPart.StartIndex * 2, arrOutPut, 0, MeshPart.PrimitiveCount * 3);

**Comment by Jjagg** [comment]
The elementCount should actually be the number of T elemnts, so that's the number of bytes in your case. Try `MeshPart.PrimitiveCount * 3 * 2`.

**Comment by AliciaRaven** [comment]
Yes thats the problem, it says elementCount which is correct now but the previous version expected the byte count. Thanks Jjagg 👍

**Comment by Jjagg** [comment]
FYI when #5121 is metged an exception will be thrown if elementcount is wrong and the expected and actual values of elementcount are included in the error message.

**Comment by AliciaRaven** [comment]
I have found that the following methods can return different values, I assumed they would return the same number. Maybe I should open another report for this? The values match in almost all test models but one, which reports a much lower value for 3 of its parts when calling the first method which results in missing geometry when using that number later in code to read the vertex data.

```
ModelMeshPart.NumVertices
ModelMeshPart.VertexBuffer.VertexCount
```

These should always be the same right?

**Comment by Jjagg** [comment]
Yes, I think they should be the same, can you open a new issue for that? But they should return the number of distinct vertices. You shouldn't use these numbers for reading from an index buffer, use `ModelMeshPart.IndexBuffer.IndexCount` instead.

**Comment by AliciaRaven** [comment]
Ok thanks. I was using the vertex count to calculate the size of the vertex buffer to read vertext data.
