### ISSUE TITLE
ToggleFullScreen not working in latest dev build

### ISSUE THREAD

**Issue by pareklund** [MonoGame/MonoGame#5417]
[DISCLAIMER: I haven't been developing on the Windows/.NET platform for many years, so I apologize if I have missed something fairly obvious.]

Issue Description:
Calling graphics.ToggleFullScreen() causes a NullReferenceException to be thrown. 

Stacktrace:
"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()\r\n   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present()\r\n   at Microsoft.Xna.Framework.UAPGamePlatform.Present()\r\n   at Microsoft.Xna.Framework.Game.EndDraw()\r\n   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)\r\n   at Microsoft.Xna.Framework.Game.Tick()\r\n   at Microsoft.Xna.Framework.UAPGameWindow.Tick()\r\n   at Microsoft.Xna.Framewor"

Steps to Reproduce:
1. Create a MonoGamew Windows 10 Universal Project, targeting .NET Framework 4.6.1 and UWP 10.0.14393.0 (Target and Minimum). 
2. Build and run => Works
3: Add graphics.ToggleFullScreen() in game class constructor as follows:
        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            graphics.ToggleFullScreen();
            Content.RootDirectory = "Content";
        }
4. Rebuild and Run => NullReferenceException

Environment:
* Windows 10 and Xbox One (same behaviour regardless of deployment target)
* Visual Studio Community 2015 v14.0.25431.01 Update 3
* .NET Framework 4.6.01586 
* Latest MonoGame development build (3.6.0.1352)
* UWP 10.0.14393.0

**Comment by pareklund** [comment]
And I get the same error in MonoGame build 3.6.0.1363 (latest package built in TeamCity as of this writing).

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
