### ISSUE TITLE
Split MGCB into lib and CLI

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#5435]
Feature request! Or rather proposal because I'd implement this myself if this is accepted.

I'd like to split MGCB into a DLL and a CLI so users can easily use the lib in whatever they like to build on top of the MG build system. The Pipeline Tool could also use that rather than calling the MGCB executable, that would be much nicer IMO. We could call the class library MGCBlib and the CLI just MGCB so we don't actually change the name.

I got this idea when looking at the code a bit to check out issues @UncleThomy ran into. http://community.monogame.net/t/typical-working-command-line-inputs-for-mgcb/8655/3
That also revealed that the '/define' option is not actually implemented. I'd also generally like to make the CLI a bit more robust and smarter e.g. by allowing spaces in options (and trimming them). 

👍 or 👎?

**Comment by tomspilman** [comment]
> I'd like to split MGCB into a DLL and a CLI 

There isn't a reason to add another assembly here.

If you look at MGCB you'll see that there is very little code in that project at all:

  https://github.com/MonoGame/MonoGame/tree/develop/Tools/MGCB

All the real work for content building is done via the `PipelineManager` class which is a public class in MonoGame.Framework.Content.Pipeline.dll:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs

So the split you're looking for already exists IMO.  You can write a custom pipeline tool against `MonoGame.Framework.Content.Pipeline.dll` alone and generate whatever content you want or you can call `MGCB.exe` if you want a command line tool.

Could be we need to improve the API of `PipelineManager` as well as clearly document it.

> That also revealed that the '/define' option is not actually implemented.

That concept always seemed half baked to me.

The idea was to use a preprocessor like syntax to allow for conditional compile of content and/or modifying settings.  We would then use this feature to implement multi-platform support in a single .MGCB file with the Pipeline GUI tool.

I think that whole approach to multi-platform content has to be re-evaluated before we make any changes there.


> I'd also generally like to make the CLI a bit more robust and smarter e.g. by allowing spaces in options (and trimming them).

I'm happy to us make the command line for MGCB better as long as we stick to the core principle of using the same syntax on the command line as in the .MGCB file.  Also any change cannot break existing .MGCB files people are using.

**Comment by Jjagg** [comment]
> Could be we need to improve the API of PipelineManager as well as clearly document it.

Can we move the response file parsing to Content.Pipeline dll?

> That concept always seemed half baked to me.

@UncleThomy has a use case for it. It seems like a useful thing to have, not really through the Pipeline Tool or CLI, but when automating things or writing a flexible wrapper around the content build system. 

> We would then use this feature to implement multi-platform support in a single .MGCB file

Like include/exclude specific files based on platform rather than just building the same files, but passing a different platform parameter?

> I'm happy to us make the command line for MGCB better as long as we stick to the core principle of using the same syntax on the command line as in the .MGCB file. Also any change cannot break existing .MGCB files people are using.

Of course, nothing breaking.

**Comment by tomspilman** [comment]
> Can we move the response file parsing and building to Content.Pipeline dll?

I'd rather not.  The point of keeping the command line parsing in MGCB was that it was that MGCB was the command line interface.


> Like include/exclude specific files based on platform rather than just building the same files

Yeah basically these two main features:

   - Exclude/include content per-platform or per-configuration (like DEMO vs RETAIL)
   - Modify content build settings per-platform or per-configuration (like don't compress this content on some platforms/configs).

At the time we thought a preprocessor like system could allow us to do these things.  However there was never a design for how these things would be done from the Pipeline GUI tool.

Unfortunately in the last 5 years or so since I wrote the original pipeline code no one has taken on this task.

**Comment by Jjagg** [comment]
> I'd rather not. The point of keeping the command line parsing in MGCB was that it was that MGCB was the command line interface.

Not the argument parsing, but the response file, .mgcb files.

> At the time we thought a preprocessor like system could allow us to do these things. However there was never a design for how these things would be done from the Pipeline GUI tool.

Hmm, it's not that easy making good GUI's, huh? I'll think about this for a bit.

**Comment by KonajuGames** [comment]
> Not the argument parsing, but the response file, .mgcb files.

It's all just command-line arguments.  The response file is just another source of command-line arguments.

There's no need to create another project.  Since the .exe is itself an assembly, it can be referenced from another .NET assembly.  It may just need exposing some more of the `Main()` function as public classes.

**Comment by Jjagg** [comment]
> It's all just command-line arguments. The response file is just another source of command-line arguments.

Oh, right...

> There's no need to create another project. Since the .exe is itself an assembly, it can be referenced from another .NET assembly.

I didn't actually know that, oops. Exposing some more granular functions through the MGCB.exe API seems very reasonable.
