### ISSUE TITLE
SharpDX 3.x.x update

### ISSUE THREAD

**Issue by aienabled** [MonoGame/MonoGame#5436]
**UPD. The information below is wrong - the performance boost was not from SharpDX improvement but from switching MonoGame to RELEASE build from DEBUG.**

I've updated SharpDX to 3.1.0 and got about 300-400% better framerate in our game. Sweet!
Perhaps the improvement is so dramatic because there are a lot of drawcalls (it's too early to optimize this in our game yet).

I was needed to fix a few places in master branch of MonoGame for proper compatibility with it, also SharpDX.Mathematics.dll should be references now as it was separated from the SharpDL.dll.

There are a few drawbacks: starting from 3.0.0 SharpDX requires .NET 4.5. And a problem with MGFX - it seems when SharpDX 3.1.0 is used it tries to compile with D3DCompiler_47.dll which is available (and works) only at Windows 8.1/10 SDK, so Windows 7 is not supported. Perhaps we need to ask at SharpDX repository about this requirement as I didn't found anything related to this.

Regards!

**Comment by Jjagg** [comment]
Oh noes, I also have a branch were I upgraded SharpDX (to 3.1.1) but I forgot to set up a PR :/ 

> got about 300-400% better framerate in our game

What the... I thought SharpDX was just a thin wrapper, I don't get how changes in it can improve performance so much.

> also SharpDX.Mathematics.dll should be references now

This is actually not necessary. SharpDX 3.0 release notes state: 

> All Mathematics (Vector3, Vector4...) have been moved to a dedicated assembly. The reason behind this change is to put SharpDX on a diet, where higher level API (like Xenko, MonoGame...) are no longer forced to include this API. In order to support this, all SharpDX assemblies are now using interop types (RawVector3, RawVector4 from SharpDX.Mathematics.Interop namespace)

@aienabled Maybe we can cross-check our changes and see if either of us missed anything?

Comparing my branch to develop (ignore the OpenTK thing, I messed up a merge probably): 
https://github.com/Jjagg/MonoGame/compare/develop...Jjagg:dx31?expand=1

**Comment by aienabled** [comment]
@Jjagg,
> I thought SharpDX was just a thin wrapper, I don't get how changes in it can improve performance so much.
Checked on a two machines and the difference is indeed overwhelming (even higher than MonoGame DEBUG vs RELEASE build). Will try to fire up a profiler to see what's improved in our case.

> This is actually not necessary
You're right, I absolutely missed the point that SharpDX now provides RawVector* interop types. Thanks!

>  Maybe we can cross-check our changes and see if either of us missed anything?
Unfortunately my branch is based on master branch, there are a lot of customization for my integration needs and I push it to my local Git server... Anyway my changes to support SharpDX 3.1.0 are only limited to fixing type names: Bool->RawBool, Vector*->RawVector*, Color4->RawColor4, ViewportF->RawViewportF. My game don't have audio yet so I don't know if audio actually works.

I've checked comparison of the develop vs your branch and it looks good.

Regards!

**Comment by aienabled** [comment]
My bad. I've checked with the profiler and turns out that actually previously I was using Debug build of MonoGame instead of Release! And when updated SharpDX I've switched to Release build so the change was because of this.
There are no noticeable performance improvement from SharpDX upgrade.
Sorry for the misleading, guys!

**Comment by Jjagg** [comment]
Thanks for checking!
