### ISSUE TITLE
Pipeline tool process stays active after exiting

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5439]
Hello,

When closing the Pipeline tool (at least on Windows), the window closes correctly but the process remains active and takes 100% of a CPU core usage.

**Comment by KonajuGames** [comment]
This no longer occurs in current source.

**Comment by mrhelmut** [comment]
I've test a bit a more, you have to load a project for this to happen. If no project has been loaded, exiting works fine.
It may be related to console extensions, I'm going to verify this because it happens on latest develop branch.

**Comment by KonajuGames** [comment]
I tested it the same way, with and without a project loaded. Mine was in
the debugger though, which is where I saw this happening a short while
back. Maybe it's just outside the debugger now?

**Comment by mrhelmut** [comment]
It's outside of the debugger. I'll try to look more into this and provide more context.

**Comment by Jjagg** [comment]
I just ran into this too, in a release build. CPU usage was about constant and relatively low though.

**Comment by zigzag312** [comment]
This happens to me too.

I had to add System.Environment.Exit(0) call inside OnClosing in MainWindow to force exit, so I don't need to kill Pipeline.exe process via task manager all the time.

**Comment by mrhelmut** [comment]
I haven't been able to reproduce it on my end.

**Comment by zigzag312** [comment]
For me it happens in release build if project is opened

**Comment by zigzag312** [comment]
Update: Its not release build that causes this, but **Optimize code** build option.

Steps to reproduce:
- Build _Pipeline.Windows_ project with _**Optimize code**_ enabled
- Open mgcb project. Project must contain some files!
- Exit pipeline tool. (See task manager, Pipeline.exe should still be running.)

I think it's FileWatcher that is causing this. 
When I run with just my code disabled:
If _optimize code_ is disabled, I only get single `System.Threading.ThreadAbortException: 'Thread was being aborted.'` exception inside `ExistsThread()` method.
If _optimize code_ is enabled, I get endless `System.Threading.ThreadAbortException: 'Thread was being aborted.'` exceptions inside `ExistsThread()` method.
