### ISSUE TITLE
UWP project is broken in newer builds

### ISSUE THREAD

**Issue by YugeshN** [MonoGame/MonoGame#5462]
I was previously running a dev version of 3.6 with build # 1365. All was good with my UWP which ran on both Windows 10 and Xbox One.

I recently upgraded to build # 1499, and noticed that my UWP project is now broken. I get the following stack trace when trying to launch the game:

```    		e	{Windows.UI.Xaml.UnhandledExceptionEventArgs}	    Windows.UI.Xaml.UnhandledExceptionEventArgs
-		Exception	{System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present()
   at Microsoft.Xna.Framework.UAPGamePlatform.Present()
   at Microsoft.Xna.Framework.Game.EndDraw()
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.UAPGameWindow.Tick()
   at Microsoft.Xna.Framework.UAPGamePlatform.<>c.<StartRunLoop>b__12_0(Object o, Object a)}	System.Exception {System.NullReferenceException}
+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		HResult	-2147467261	int
		HelpLink	null	string
+		InnerException	null	System.Exception
		Message	"Object reference not set to an instance of an object."	string
		Source	"MonoGame.Framework"	string
		StackTrace	"   
		at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
		at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present()  
		at Microsoft.Xna.Framework.UAPGamePlatform.Present()   
		at Microsoft.Xna.Framework.Game.EndDraw()
		at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
		at Microsoft.Xna.Framework.Game.Tick()
		at Microsoft.Xna.Framework.UAPGameWindow.Tick()
		at Microsoft.Xna.Framework.UAPGamePlatform.<>c.<StartRunLoop>b__12_0(Object o, Object a)"	string
+		Static members		
+		Non-Public members		
		Handled	false	bool
		Message	"System.NullReferenceException: Object reference not set to an instance of an object.
		at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent()
		at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present()
		at Microsoft.Xna.Framework.UAPGamePlatform.Present()
		at Microsoft.Xna.Framework.Game.EndDraw()
		at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
		at Microsoft.Xna.Framework.Game.Tick()
		at Microsoft.Xna.Framework.UAPGameWindow.Tick()
		at Microsoft.Xna.Framewor"	string
		Native View	To inspect the native object, enable native code debugging.	
```

I went back to the earliest available Windows build which is # 1398 (from the 20th of January), and it's still broken. Note, this error occurs on both Windows 10 and Xbox One.

I *suspect* from looking at the history that this might be related to some changes introduced by @Jjagg on January 6th which looks like it involved a lot of cleanup / refactoring. However, I cannot confirm this since I can't seem to access builds beyond the 20th of January.

Thanks.

**Comment by tomspilman** [comment]
@Jjagg @KonajuGames It is critical to get this fixed ASAP.

**Comment by KonajuGames** [comment]
I'll have a look in a few hours if no-one else gets to it first.

**Comment by Jjagg** [comment]
Could be #5139 has something to do with this. Sorry, I can't check right now.

**Comment by nkast** [comment]
I can confirm. The Exception is thrown at https://github.com/MonoGame/MonoGame/blob/2eb6f36b459e2b51acc8af6e5b9e989a8d62284e/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L938 and _swapChain is null. 
The bug should be somewhere in the initialization code. 

I think `presentationParameters.SwapChainPanel` is never initialized.
I added the line `presentationParameters.SwapChainPanel = this.SwapChainPanel;` in  `GraphicsDeviceManager.PreparePresentationParameters(...)` (not sure this is the right place) and then I  got a SharpDX exception at line https://github.com/MonoGame/MonoGame/blob/2eb6f36b459e2b51acc8af6e5b9e989a8d62284e/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L488

```
HRESULT: [0x887A0001], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall], Message: The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect.
 ```

**Comment by KonajuGames** [comment]
I'm also looking at this now.  Not too sure how the initialization of the swapchain is supposed to happen yet.

**Comment by KonajuGames** [comment]
It's in GraphicsDeviceManager.Initialize.  It initializes a new instance of PresentationParameters with the SwapChain from the XAML, but then discards it.

**Comment by Jjagg** [comment]
The stuff that happens in [PlatformInitialize](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/GraphicsDeviceManager.WinRT.cs#L25) should be done in PrepareGraphicDeviceInformation: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/GraphicsDeviceManager.cs#L302

**Comment by KonajuGames** [comment]
Ok, got UWP working.  Added a `PlatformPreparePresentationParameters(PresentationParameters presentationParameters)` method and changed `PlatformInitialize` in GraphicsDeviceManager.WinRT.cs to `PlatformPreparePresentationParameters`.  Now checking Windows Store App...

**Comment by KonajuGames** [comment]
PR #5463 is up.

**Comment by tomspilman** [comment]
@YugeshN - Give the latest develop branch a try again if you can.  We believe to have merged the fix.

**Comment by nkast** [comment]
I tested UWP & W8.1 and the swapchain no longer resize, as if it doesn't respond to resize event.
On UWP it remains the same size. On W8.1 same thing but scales to fill the window.
@YugeshN - can you verify this?

**Comment by KonajuGames** [comment]
I didn't test resizing.  I'll have another look tonight (in about ten-twelve hours) unless someone gets to it before then.

**Comment by YugeshN** [comment]
@nkast @KonajuGames  Sorry, didn't get a chance to test this until my work day was over. There definitely seems to be some issues with resizing. On Win10, resizing events don't seem to be propagating. On Xbox One, the rendered image is  not correctly sized i.e. there are white bars on the right and bottom.

**Comment by KonajuGames** [comment]
I can't test Xbox One (don't have one), but I'll see what I can find about resizing on Windows 10.

**Comment by KonajuGames** [comment]
PR #5464 is now up.  The GraphicsDevice.Reset implementations for UWP and Store Apps were empty.

**Comment by YugeshN** [comment]
Tested this on both Win10 and Xbox and the problem appears to be fixed. Thanks @KonajuGames for resolving this so promptly!

**Comment by KonajuGames** [comment]
Thanks for testing, @YugeshN.  @tomspilman, #5464 is good to merge.
