### ISSUE TITLE
Pipeline Error on OSx - System.DllnotFoundException: libfreeimage.dylib

### ISSUE THREAD

**Issue by Preprocezzor** [MonoGame/MonoGame#5470]
I'm not able to add any content to my project via Content Pipeline.
I use the Xamarin Studio. I tried to install freeimage via Homebrew but it still doesn't work.

My Error looks like this: 

<img width="1238" alt="screen shot 2017-02-10 at 21 23 59" src="https://cloud.githubusercontent.com/assets/25663451/22842891/4c3a385a-efd7-11e6-956f-d51692957c8e.png">

What's the solution for this?

Thanks.

**Comment by Rydgel** [comment]
Same error.

**Comment by Dids** [comment]
I'd consider this a bug with the Pipeline project itself, as it should bundle `libfreeimage.dylib` with the rest of the frameworks, but it doesn't.

A workaround:
- Compile the Pipeline app from source to get it running on macOS (3.6 crashes on macOS, development version doesn't), then copy `Pipeline.app` to `/Applications`
- Copy the missing framework from `/Path/To/MonoGame/ThirdParty/Dependencies/FreeImage.NET/MacOS/libfreeimage.dylib` to `/Applications/Pipeline.app/Contents/MonoBundle/`

After that it should work fine, at least for textures.

**Comment by jvlppm** [comment]
The same is valid when using the dotnet core project template / nuget by @cra0zy 

I had to manually copy `libfreeimage.dylib` into `~/.nuget/packages/monogame.content.builder/3.7.0.4/build/MGCB/build`

After that it works fine.

**Comment by Jjagg** [comment]
@cra0zy I guess the native freeimage lib wasn't bundled with Pipeline Tool on Mac. This must have been fixed, right?

**Comment by cra0zy** [comment]
> @cra0zy I guess the native freeimage lib wasn't bundled with Pipeline Tool on Mac.

I think its not.

**Comment by kflu** [comment]
I concur. It appears that the builder package is shipped with a `libfreeimage-3.17.0.so` that's not loadable from mac OS:

    file libfreeimage-3.17.0.so
    libfreeimage-3.17.0.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=...., stripped

I fixed by `brew install freeimage` and `ln` the lib over. And the linked dylib looks like this:

    file libfreeimage.dylib 
    libfreeimage.dylib: Mach-O 64-bit dynamically linked shared library x86_64

**Comment by harry-cpp** [comment]
This has been fixed.
