### ISSUE TITLE
Texture2D.GetData<T> does not return the correct number of elements when  size of T is not the same as the pixel format. (OpenGL)

### ISSUE THREAD

**Issue by james0x0A** [MonoGame/MonoGame#5474]
This is the cause of #5473

**Comment by Jjagg** [comment]
I may have fixed this in https://github.com/MonoGame/MonoGame/pull/5429/commits/854ea8ae194c341bfad6e502daab9dec212094db
I'll get that building again so it can be merged.

**Comment by Jjagg** [comment]
Yeah, that fixed it :)
