### ISSUE TITLE
New or cloned skinned effect will not work

### ISSUE THREAD

**Issue by AliciaRaven** [MonoGame/MonoGame#5476]
Creating a new skinned effect or a clone of a skinned effect using existing effect from a model will not work, only the original effect created as part of the model will work.

I am trying to create a skinned effect at runtime so i dont have to include serialized effect data in all my models. These models use a custom model format. I can create new basic or alpha effects which work ok but when i try to create a new skinned effect it does not work.

Model renders black in a fixed location on the screen. Setting textures, lighting or animation does nothing. Even changing the view or world projects does not change the position on screen where the black model is rendered. I would expect a clone of a working effect to copy all parameters over but maybe some thing is missed out for skinned effects?

The original effect in the model works fine, but only one effect is created for all parts of the model meaning at draw time the textures have to be assigned for every frame drawn.

See also, http://community.monogame.net/t/creating-skinnedeffect-at-runtime-not-working/8744/2

**Comment by nkast** [comment]
>  Should the first method work or is the second way the expected way to do this? If the first way is just wrong then this issue can be closed.

I'd say to leave this open for a while to check a few things. I believe it shouldn't let you assign a new `ModelEffectCollection`. `ModelEffectCollection` is a readonly collection that enumerates all the effects used by the MeshParts.

**Comment by nkast** [comment]
OK, MonoGame has ModelEffectCollection as a [get;set; property](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/ModelMesh.cs#L48), while XNA [documentation](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.modelmesh.effects.aspx) 
defines it as a readonly property. It makes sense to mimic XNA behavior here.
