### ISSUE TITLE
[DANGEROUS] MGCB wiping out folders

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#5482]
Hello,

I know MGCB does not support linked files yet and that linked files are problematic, but I'm porting to Android and it seems the "new" android MG versions does not support textures with mipmapping compiled from old XNA XNBs, so I'm in need to use MGCB, and file linking is a must due to my folder structure.

But even with that in mind, I think this is an issue that should be urgently fixed 

I'm attaching a zip file with an structure of folders.

[folder1.zip](https://github.com/MonoGame/MonoGame/files/784454/folder1.zip)

Go through the folders to "project" and open the project with MGCB.

The project only has a file: assets/x.png . Unfortunately linking files does not work, so it's putting it in ../assets/x.png.

The problem is that if you try to delete the .. folder (as I did a few minutes ago), not only x.png appears to be deleted, but the WHOLE .. folder... and subfolders. It asks for confirmation, but one supposes that it should be only deleting the x.png file, so I skipped checking.

Luckily when I did that, all that deleted were my other platform project I had in that folder (which had been commited a moment ago into mercurial) but if I had had that folder in the root on my HD, it'd have wiped out the entire hard disk!

(in fact it even wipes out the very same mgcb file)

**Comment by tomspilman** [comment]
@cra0zy - Thoughts on this?

**Comment by cra0zy** [comment]
Sounds like it's deleting `../` directory.

**Comment by Jjagg** [comment]
Bump! Some other people running into this. 
http://community.monogame.net/t/content-issue-deleted-my-whole-desktop/9739

**Comment by cra0zy** [comment]
This got fixed a while back: #5820

**Comment by BasBloem** [comment]
Hello, I'm the guy who posted that on monogame.net from the above comment.
All I have to add is that this happened in 3.6.0.1625 of the Pipeline Tool.

**Comment by nkast** [comment]
How about 3.5.1.1679 ? is it safe to use?

**Comment by cra0zy** [comment]
> How about 3.5.1.1679 ? is it safe to use?

Probably not, the code for deleting hasn't been touch for a while.

**Comment by nkast** [comment]
That's probably reassuring. 👍

**Comment by nkast** [comment]
So, anything from 3.7.0.638 or later is ok.

**Comment by tomspilman** [comment]
@cra0zy - This is fixed correct?

**Comment by cra0zy** [comment]
Yup.
