### ISSUE TITLE
monogame-sdk.run outputs "OK" but build errors when building "error free" code

### ISSUE THREAD

**Issue by Sir-Ignis** [MonoGame/MonoGame#5483]
OS: **Leap 42.2**
{running}

    sudo ./monogame-sdk.run 

{output}

    Verifying archive integrity... All good.
    Uncompressing Monogame Pipeline Installer.....................................................................
    Please uninstall any previous versions of MonoGame SDK

[Code](http://pastebin.com/VpwDjvjU) being compiled...

Errors:

{line 147}
>Game1.cs(147,46): error CS1056: Unexpected character `“'

>Game1.cs(147,48): error CS1056: Unexpected character `\005c'

>Game1.cs(147,55): error CS1056: Unexpected character `”'

>Game1.cs(147,56): error CS1525: Unexpected symbol `,'

>Game1.cs(147,72): error CS1525: Unexpected symbol `)'

When line 147 is commented out then:

Errors appear on lines **182,188,194**:

>Game1.cs(182,4): error CS0103: The name `_spriteBatch' does not exist in the current context 

>Game1.cs(188,16): error CS0103: The name `_spriteBatch' does not exist in the current context

>Game1.cs(194,4): error CS0103: The name `_spriteBatch' does not exist in the current context

Also I'm not sure if this is significant but running the template code brings up a window, but I can't close the window by clicking on the 'X', I have to stop running the application to close it.

_I've_ been using MonoGame for < 1 day and my C# skills are not very good so please take that into account when _replying._

**Comment by Jjagg** [comment]
> Game1.cs(147,46): error CS1056: Unexpected character `“'

You're not using the right quotation marks here. Use " instead. How do you even type those?

> Game1.cs(182,4): error CS0103: The name `_spriteBatch' does not exist in the current context

Should be 'spriteBatch', not '_spriteBatch'.

These are not errors with MonoGame.

**Comment by Sir-Ignis** [comment]
Thanks for the help @Jjagg  . Again I apologies for the trivial mistakes I made here.

**Comment by Sir-Ignis** [comment]
I made the changes that you told me to @Jjagg but I got an error:

`Program.cs(30,18): error CS0246: The type or namespace name 'Game1' could not be found. Are you missing an assembly reference?`

The code for the program.cs is [here](http://pastebin.com/KhLZ8riH).

When I start a new project the program still compiles even though the **MonoGame.Framework, NVorbis and OpenTK are missing**. But when I search for these on my system I have all these dlls. I think the problem is deeper within how I installed MonoGame...

**Comment by Jjagg** [comment]
@Sir-Ignis Put Program in the same namespace as Game1 (looks like the namespace line is not included because of preprocessor directives) or import the Game1 namespace. I'm not sure what you mean about libs 'missing'. If things compile that means you reference them. Maybe the copy action of the references is set to don't copy?

This is not really the place for troubleshooting though. The issues here are for bugs in MG, so it'd be better if you migrated this to the community forums over at http://community.monogame.net/.

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
