### ISSUE TITLE
Black borders around glyphs when resizing spritefont-textures

### ISSUE THREAD

**Issue by guFalcon** [MonoGame/MonoGame#5491]
The current content pipeline code in the develop branch seems to have issues with separating the glyphs of a SpriteFont texture.

Here is an image of the resulting borders when resizing the fonts (making them bigger):
![image](https://cloud.githubusercontent.com/assets/7469819/23172423/0468adea-f856-11e6-94ff-7c90c393f459.png)
That's when the borders start showing up.

UPDATE:
Here's what happens when I change the pipeline-tool back to version  3.5.1.1679:
![image](https://cloud.githubusercontent.com/assets/7469819/23172343/c26d19da-f855-11e6-9ae7-35c066ae90e4.png)

The thing is that switching the MG releases didn't help because the CP that gets started when the build process starts is always the same, the one that is installed via the installer, e.g. 3.6.0.1488 in my case.

So the content pipeline seems to get the borders wrong when generating the XNB file.

UPDATE:
Upgraded to 3.6.0.1551 using the installer. Still no change/same problem.

Link to community.monogame.net thread:
http://community.monogame.net/t/black-borders-when-using-resized-font-textures/8755/12

Link to test-repo (where the images come from):
https://github.com/UnterrainerInformatik/MonoGame_fonts_black_borders

**Comment by nkast** [comment]
If it's any help, I draw the `SpriteFont.Texture`  with AlphaBlend, NonPremultiplied, Additive & Opaque.
![screenshot 17](https://cloud.githubusercontent.com/assets/3018589/23193457/c5182cf4-f8b1-11e6-9946-adc2827b778f.png)

Then changed the importer to PremultiplyAlpha=false 
![screenshot 18](https://cloud.githubusercontent.com/assets/3018589/23193493/f4951cc6-f8b1-11e6-9283-9a3fb3f477e5.png)

@guFalcon , can you try the same with the old XNB and the one from XNA?  
I think the black borders shouldn't be there.

**Comment by guFalcon** [comment]
Is this still debugging? Because if this is about finding a workaround, I don't really need it since the workaround is to NOT build the spriteFonts with the 3.6.0 pipeline, but with the 3.5.1 one.
If that's debugging, you won't get the lines when not sizing up above Vector2(1, 1).
The spritefont is in the board thread (2 of them).

If it's about debugging, of course I will try to help. Are the screenshots you inserted the spritefonts loaded as texture and drawn as a single rectangle? Because I'm not quite sure what I should do (sorry).

**Comment by willmotil** [comment]
I cant reproduce this with a regular spritefont at all i tried yesterday for a long while im thinking as well this is the importer.

**Comment by guFalcon** [comment]
> So even more strange is that you should be getting those lines at (1,1) scale as well and your not.

Yes. I've thought about that and the most obvious reason I could come up with is that it seems to be connected to the SamplerState.
It doesn't happen when the SamplerState is LinearClamp or PointClamp and the scale is ```new Vector2(1, 1)```, but it's visible when doing AnisotropicClamp even with scale set to 1.

**Comment by KonajuGames** [comment]
PR #5509 submitted.
