### ISSUE TITLE
[MGCB] Curve fails to build/import

### ISSUE THREAD

**Issue by zigzag312** [MonoGame/MonoGame#5492]
Curves stored in xml files, that were created using XNA Curve Editor fail to build with Monogame's Pipeline tool. Xml of the most simple `Curve `with only one `CurveKey `looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<XnaContent xmlns:Framework="Microsoft.Xna.Framework">
  <Asset Type="Framework:Curve">
    <PreLoop>Constant</PreLoop>
    <PostLoop>Constant</PostLoop>
    <Keys>0 1 0 0 Smooth</Keys>
  </Asset>
</XnaContent>
```
First problem is that `XmlImporter `in Monogame expects elements in different order. This issue is already described in #4792. I have started making a fix for this when I stumbled on a second problem: 
`CurveKeyCollection `is not getting deserialized from xml. 

Each `CurveKey `is represented by 5 values separated by space inside `<Keys>...</Keys>`. 
Order of values is: `Position`, `Value`, `TangentIn`, `TangentOut `and `Continuity`.
Each new CurveKey inside a collection is also separated by space. Two CurveKeys look like this: `<Keys>0 1 0 0 Smooth 0.5 0.5 0 0 Smooth</Keys>`

Debugging step-by-step I found the point where deserialization fails. `GenericCollectionHelper `doesn't read collection as it expects each `CurveKey `to be a separate xml element.
Here's the `Deserialize `method from `GenericCollectionHelper `:
```
 public void Deserialize(IntermediateReader input, object collection, ContentSerializerAttribute format)
        {
            var itemFormat = new ContentSerializerAttribute();
            itemFormat.ElementName = format.CollectionItemName;
            while (input.MoveToElement(format.CollectionItemName)) // this loop expect list of CurveKey elements!
                _addMethod.Invoke(collection, new[] { input.ReadObject<object>(itemFormat, _contentSerializer) });
        }
```
Does anyone know if there is another class in Monogame that would help to deserialize collection like this? And does anyone with more experience with deserialization have any idea how one would approach to solve this?

I have many curves in a project I want to migrate and changing all xml files might take me the same amount of time as fixing this code. Also there are [others ](http://community.monogame.net/t/importer-xmlimporter-had-unexpected-failure/7959)reporting the same issue.

**Comment by KonajuGames** [comment]
I had no idea XNA had a curve editor tool. I've never used these curves in
XNA.

It sounds like it needs a CurveConverter class to convert the Curve to and
from a string. This should be able to read and write the five
space-delimited values. At the moment the serialization is likely using the
default behaviour of the XML deserializer which is to read each property of
the Curve as a separate node.

**Comment by zigzag312** [comment]
> I had no idea XNA had a curve editor tool. I've never used these curves in
XNA.

It is quite basic utility that was released as one of the samples. You can find it [here](http://xbox.create.msdn.com/en-US/education/catalog/utility/curve_editor). 

> It sounds like it needs a CurveConverter class to convert the Curve to and
from a string. This should be able to read and write the five
space-delimited values. At the moment the serialization is likely using the
default behaviour of the XML deserializer which is to read each property of
the Curve as a separate node.

Yeah it is using `ReflectiveSerializer`. I just had an idea. If I leave it to still relay on `ReflectiveSerializer `to do most of the work and just create CurveKeyCollectionSerializer that would know how to deserialize this `Keys `string, would that be good way to do this?

**Comment by KonajuGames** [comment]
That could work. I can't look at the code now to check (on a train on the
way to work), but it sounds correct.

**Comment by zigzag312** [comment]
OK, then I'll try this and post new PR if all goes well :)

**Comment by zigzag312** [comment]
Closing this as fix has been already merged
