### ISSUE TITLE
A potential bug in Audio/Xact/Cue.cs

### ISSUE THREAD

**Issue by valhristov** [MonoGame/MonoGame#5493]
I found a potential bug with the SonarC# plugin for SonarQube - on the following line _curSound could be null (because you check for null on the line before that):
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/Xact/Cue.cs#L260

All the best,
Valeri

**Comment by tomspilman** [comment]
We noticed this the other day too... it is indeed a bug.

**Comment by tomspilman** [comment]
Fixed in https://github.com/MonoGame/MonoGame/pull/5709.
