### ISSUE TITLE
Add New Item in Mac Pipeline tool has an empty list

### ISSUE THREAD

**Issue by dellis1972** [MonoGame/MonoGame#5498]
The "Add New Item" menu which usually shows a list for SpriteFonts and shaders is current empty on the Mac Version of the Pipeline Tool

<img width="1440" alt="screen shot 2017-02-23 at 17 04 55" src="https://cloud.githubusercontent.com/assets/810617/23270022/54272ae2-f9ea-11e6-82b0-3b7552b11ec6.png">

**Comment by cra0zy** [comment]
There is a good chance that it's just looking in the wrong directory for templates.

**Comment by dellis1972** [comment]
PR up https://github.com/MonoGame/MonoGame/pull/5501
