### ISSUE TITLE
Add support for Gamepad AXIS_HAT_XY on Android 

### ISSUE THREAD

**Issue by YugeshN** [MonoGame/MonoGame#5519]
I am adding gamepad support to my game, and was testing it out on Android. I have an XBOX One S Controller (with bluetooth) that I connected to my Android tablet.

When testing the gamepad via a gamepad tester app from the app store, all buttons / keys worked except the the right trigger (which is an Android mapping issue and unrelated to Monogame). The app did show that the D-PAD actually generates AXIS_HAT_X and AXIS_HAT_Y events on Android, and not the DPAD_UP, DPAD_DOWN etc.

It does not look like Monogame currently supports the AXIS_HAT_XY events for Android (from looking at the code in https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Input/GamePad.Android.cs ).

It would be great to add support for this which should (mostly) allow the Xbox One S Controller to be usable on Monogame with little to no tweaking / changes.

Thanks.

**Comment by YugeshN** [comment]
Does anyone have any ideas how I could add support for this? I looked at the Monogame code for this, and it's a little tricky to find a clean way to add this without potentially breaking anything.

**Comment by YugeshN** [comment]
@cra0zy I noticed you are making changes to the gamepad support and cleaning things up. Is there any way you can address this? I looked at the code for this and don't know where to start in order to address this issue without potentially breaking something.

Thanks!

**Comment by cra0zy** [comment]
Oh, I didn't know there was an issue about this... I fixed it 4 days ago :D #5673

**Comment by YugeshN** [comment]
@cra0zy That's awesome! I didn't know it was fixed... I'll definitely be testing it out. Thanks for resolving this.
