### ISSUE TITLE
Project fails to run after latest OSX patch

### ISSUE THREAD

**Issue by csauers** [MonoGame/MonoGame#5524]
After I updated my mac this morning I haven't been able to run my DesktopGL project. After running my game "mono32" appears in my dock, but nothing besides that. No breakpoints are hit at any place in my application. I'm currently on the dev branch (3.6.0.1604-develop).

Also possibly related, I reimported monogame and now when I try to run my game I get a SDL2 DllNotFoundException.

**Comment by csauers** [comment]
Fixed by reimporting the dev branch of monogame, cleaning the project, setting the MonoGame.Framework.dll.config file's "copy to output directory" property to always copy, and then by overwriting the libSDL2-2.0.0.dylib file found [here](https://github.com/MonoGame/MonoGame.Dependencies/tree/master/SDL/MacOS/Universal)

**Comment by tomspilman** [comment]
Thanks for updating this @csauers !
