### ISSUE TITLE
Texture2Ds created at runtime are not always empty

### ISSUE THREAD

**Issue by zigzag312** [MonoGame/MonoGame#5527]
If Texture2D instance is created at runtime by a constructor, that instance is not always empty. By empty I mean, not all pixels are transparent black. In XNA I always get an empty texture (tested on Windows only). 

Now I am not sure if this is intended behavior and I was just lucky that my code worked in XNA as [in docs](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.texture2d.texture2d.aspx) it says: 

> Creates an **_uninitialized_** Texture2D resource of the specified dimensions.

So my question is: is this a correct behavior and if it is, what is the fastest way to clear a texture to transparent black (is there faster way than SetData())?

**Comment by willmotil** [comment]
That texture shouldn't normally be used until you set something to it anyways right.
Then you would set the data or and if used in a target clear that data. In either case you wouldn't depend on pixels being a certain defined color that you never defined.

Transparent black default texture ?
This was actually linked to a bug in xna3.1 that let me create a backbuffer that was transparent black were i could see thru the entire game window to the desktop in fullscreen or windowed, a virtual security hole in and of itself for the entire api.

**Comment by KonajuGames** [comment]
Never assume that textures are initialized to black. Always assume that you
must call SetData with some valid texture data to set the texture to a
known value. Yes, you may have gotten lucky with XNA. It would be a waste
of CPU time and memory for our code to initialize a texture to black when
in 99.9℅ of cases it will be immediately set to something else using
SetData anyway.

**Comment by zigzag312** [comment]
Thank you for clearing this up! Problem in my case is that not all pixels have data set, as texture is used as texture atlas. For now, I'll just call additional SetData with zeroed array after texture's constructor . If performance is going to be a problem, I'll try to remove SetData overdraw.
