### ISSUE TITLE
SpriteBatch AlphaBlend doesn't look the same on OpenGL vs DirectX

### ISSUE THREAD

**Issue by Thraka** [MonoGame/MonoGame#5529]
Using the new 3.6 nuget packages, alphablending sprite (that is a raw PNG file, not sent through the pipeline) calls doesn't look right. Here is my begin

    Global.SpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.DepthRead, RasterizerState.CullNone);

And here are the results.

![image](https://cloud.githubusercontent.com/assets/2672110/23485127/f18bad6e-fe8e-11e6-8948-cbb64d77145d.png)

To me it looks like on DirectX, it's figuring out the premultiply correctly while opengl doesn't see it and therefore doesn't use it.

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy @Jjagg - I suspect the png loading is doing something different on the DX platform vs. OGL.  Any ideas?

**Comment by Thraka** [comment]
For reference, that is two sprites, a yellow box and a purple circle drawn on top.

**Comment by willmotil** [comment]
With spritefonts on gl i can tell you premultiplied vs non-premultiplied set from graphics device does work even when the image is not set to pre-multiplied in the pipeline.

The final color on the right obviously has less blue and red intensity remember that alpha is transparency and transparency's ultimate effect for color itself of a object is to reduce it in the final result.
Where with pre-multiply there is no rgb reduction calculated as it has been pre-multplied by the alpha.
So while this appears to be the case are you sure it's not your settings i think you must prove this case with settings you have toggled and cases or a working example.

I normally don't use premultiplied at all its like taking away your ability to manipulate data you might need to thus giving yourself a headache.

**Comment by Thraka** [comment]
I'm not using any pipeline, i'm loading texture2d directly from a png. To make the difference in pictures I just remove the WindowsDX monogame nuget package and add the DesktopGL or WindowsGL package.

No code changes between them.

**Comment by KonajuGames** [comment]
There may be some platform-specific differences in the processing of the
PNG after it has been loaded. We need to make sure these are the same
across all platforms.
