### ISSUE TITLE
Problem with Graphics.PreferMultiSampling

### ISSUE THREAD

**Issue by aienabled** [MonoGame/MonoGame#5532]
Hi guys,

I've noticed that by default if `Graphics.PreferMultiSampling` is set to `true` you're using `32` constant value:
```C#
// always initialize MultiSampleCount to the maximum, if users want to overwrite
// this they have to respond to the PreparingDeviceSettingsEvent and modify
// args.GraphicsDeviceInformation.PresentationParameters.MultiSampleCount
presentationParameters.MultiSampleCount = GraphicsDevice != null
    ? GraphicsDevice.GraphicsCapabilities.MaxMultiSampleCount
    : 32;
```

The problem is that in most cases SharpDX will be unable to create the graphics device with `32` multisampling level (BTW, I have NVIDIA GPU, and it seems to work properly only with `8` max multisampling level). And the exception is very cryptic (as usual with SharpDX):
```SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.```

But that exception is catched by MonoGame and this one thrown instead:
```Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Failed to create graphics device!```

So it was a complete mystique to me and required debugging (with using MonoGame source compiled in debug mode) to determine what's going on. Of course I was able to fix this by subscribing to PreparingDeviceSettings and providing proper value to `GraphicsDeviceInformation.PresentationParameters.MultiSampleCount`. But that's not something I wish for other developers to repeat...

I would prefer to have a proper exception thrown instead of using default `32` value which in most cases will lead to these cryptic exceptions. I know it's not that easy because of current architecture, but we definitely need an improvement in that area.
Even using default value `1` for `MaxMultiSampleCount` will be a better option for now. This way no exception is thrown but developer could quite easily see that multisampling is not working and first thought in that case (at least for me) is that multisample count is set to 1.

Regards!

**Comment by zigzag312** [comment]
This is fixed in #5477

**Comment by aienabled** [comment]
Good to hear. Thanks!
I will close this issue when your commit will be merged - currently this issue report might be useful for other devs.

**Comment by tomspilman** [comment]
Closing this as the PR is merged now.
