### ISSUE TITLE
WinFormsGameWindow - no ClientSizeChanged event on window state change 

### ISSUE THREAD

**Issue by aienabled** [MonoGame/MonoGame#5533]
Hi guys,

I've noticed that in MonoGame 3.6 ClientSizeChanged (for WinFormsGameWindow) is not invoked anymore when window state changes (normal->maximized and vice versa). It worked properly for us at v3.5.

As a workaround for this issue I've changed (in WinFormsGameWindow.cs):
```C#
Form.ResizeEnd += OnResizeEnd;
```
to
```C#
Form.ResizeEnd += OnResizeEnd;
Form.SizeChanged += OnResizeEnd;
```

But that might lead to some side effects...
BTW, I'm using `GraphicsDeviceManager.HardwareModeSwitch = false;`.

Regards!

**Comment by mrhelmut** [comment]
@Jjagg may have some knowledge about this.

**Comment by Jjagg** [comment]
This should have been fixed in https://github.com/MonoGame/MonoGame/commit/2319d3b5bf00ec7383c46d547cc6476eb26d69cb. Let me investigate. @aienabled Your workaround will behave a bit different from when XNA would raise the event. XNA only raises when the user ends resizing and for full screen switches, while SizeChanged will also trigger during the frames when a user is resizing and when the size is changed through code (so by changing the back buffer size when not in full screen mode). If that's fine for what you're doing you can use the workaround :)

**Comment by aienabled** [comment]
@Jjagg, thanks!
I've debugged this a little more with looking on your commit and it seems that this commit cannot handle `GraphicsDeviceManager.HardwareModeSwitch=false` mode properly:
+ `OnPresentationChanged` is not called when window maximized
+ even if it will be called, it will not detect full screen mode change because  `Game.GraphicsDevice.PresentationParameters.IsFullScreen` will still be `false` (because `GraphicsDeviceManager.HardwareModeSwitch=false`).

Please note I'm not familiar with XNA but I will try to provide useful input for you.
Possible solution for this issue might include listening to form `SizeChanged ` event trigger and check if the window state changed - and trigger `OnResizeEnd` event handler in that case:
```C#
private FormWindowState lastWindowState;
private void SizeChanged(object sender, EventArgs e)
{
    if (Form.WindowState != lastWindowState)
    {
        // window state changed
        lastWindowState = Form.WindowState;
        OnResizeEnd(sender, e);
    }
}
```
I've tested this approach and it works perfect for us: MonoGame raises `ClientSizeChanged` event only when user-induced resizing is ended or when the window state is changed.

Regards!

**Comment by Jjagg** [comment]
@aienabled How are you maximizing the window? When HardwareModeSwitch is set to false you can just enable full screen as usual. I'm getting the ClientSizeChanged event fine like that. Are you accessing the form directly?

**Comment by aienabled** [comment]
@Jjagg, if the game is running in the regular windowed mode the user could press maximize/minimize buttons on the form. In MonoGame 3.5 it triggered the event, so we subscribed on it and in the event handler changed the backbuffer size to match the new client size. Now in 3.6 the event is never triggered in that case - only when the user is manually dragging a side of the (resizable) form the event is triggered.

**Comment by Jjagg** [comment]
Oh, right. I never tested that :( I never thought that would be handled different from resizing the window by dragging the edges. In that case your fix seems like a good idea.

**Comment by Jjagg** [comment]
I think I got the DX window stuff exactly matching XNA including the ClientSizeChanged event in my branch from #5522. I'll sort out the changes and separate them in nice commits later.

**Comment by aienabled** [comment]
@Jjagg, I cannot see WinFormsGameWindow modified in your commits. Does SDL form will be used for MonoGame for DirectX platform?

**Comment by Jjagg** [comment]
Like I said I didn't commit yet.
