### ISSUE TITLE
(DesktopGL) Process still running after window close

### ISSUE THREAD

**Issue by bogdanfedko** [MonoGame/MonoGame#5539]
Well, everything is working ok when starting a new project. But after upgrading an existing one to 3.6 process is still running after window close, also debugging process in VS2015 doesn't stop. Everything else is working alright. Platform is DesktopGL, running on Windows 10.

**Comment by CanopyOverseer** [comment]
I've got a _very_ similar issue with the previous release, intermittently.

My host is Windows 10 x64 / DX / AMD ATI drivers. After a period of time (could be 3 mins?) it closes down. 

- What previous version were you using?  
- It is intermittent like mine?

**Comment by bogdanfedko** [comment]
I was using 3.5. Also, there was another issue - SDL2.DLL not founded, but I have figured it out. What platform your project is?

**Comment by mrhelmut** [comment]
See #5531 for the SDL2.dll issue.

Regarding this issue, I'll take a look at it, it could be a migration problem as well.

**Comment by bogdanfedko** [comment]
Yeah, there was the same problem. Think I'll try DX version next, maybe this is not a DesktopGL issue

**Comment by bogdanfedko** [comment]
Working perfectly with SharpDX

**Comment by Thraka** [comment]
I think I noticed this when the 3.5 release came out, the process eventually closes, but it takes some time (30 seconds to a minute). This happens on DesktopDX for me.

**Comment by Jjagg** [comment]
I don't think this is still happening. @mrhelmut have you had any reports of this?

**Comment by mrhelmut** [comment]
I did notice a slight latency in stopping debugging when doing a normal process exit (which I believe is related to the unloading of assets / stopping of all threads), but it totally disappears on release builds and we never had any report regarding this.

**Comment by Jjagg** [comment]
Okay, thanks! Closing...
