### ISSUE TITLE
Generic usb gamepad

### ISSUE THREAD

**Issue by xnamahx** [MonoGame/MonoGame#5551]
Hi was trying to test gamepad events but my device is only recognized as Joystick
    Joystick.GetState(0).isConnected = true
    Gamepad.GetState(0).isConnected = false

The problem was that some buttons where not working. So looking on how SDL is doing this I ended up filling the gamecontrollerdb.txt file with the ID and mapping resulted from using http://www.generalarcade.com/gamepadtool/ and it works. But I needed to recompile all the framework to add it.

To test this quickly I expose some functions in GamePad.SDL.cs to InitDatabase from file so the mappings are loaded on execution, looking for the file in the Content folder.

Why so many useful functions in Sdl class are internal restricted? 
Sorry if breaking something im preety noob.

**Comment by Jjagg** [comment]
You can add the mapping to the file here https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/SDL/gamecontrollerdb.txt. MonoGame will pick it up. The reason SDL stuff is internal is because MG tries to hide as much platform-specific stuff and only expose the shared API.

**Comment by xnamahx** [comment]
Yeah is what I did. but then I need to recompile monogame, and put the new dll on my game project.

I want to make more easy to add mapping. Postponing the initdatabase for reading the file gamecontrollerdb.txt on execution time works.

This change is breaking some plataform specific ?

```
static partial class Joystick{
        public static void AddDevice(int deviceId)
```

    
```
static partial class GamePad{
        public static void InitDatabaseFromFile(Stream stream)
        {
            using (stream)
                if (stream != null)
                    using (var reader = new StreamReader(stream))
                    {
                        string line;
                        while ((line = reader.ReadLine()) != null)
                            if (!line.StartsWith("#") && !string.IsNullOrWhiteSpace(line))
                                Sdl.GameController.AddMapping(line);
                    }
        }
```

thanks for your time

**Comment by cra0zy** [comment]
@xnamahx If you want to add your custom mapping all you have to do is add the following code somewhere in your game:
```c#
[DllImport(NativeLibName, CallingConvention=CallingConvention.Cdecl)]
public static extern int SDL_GameControllerAddMapping(string mappingString);
```
and call it somewhere in the constructor. Tho if you are publishing your game on Steam you don't even need to bother with this because Steam has it's own SDL database which MonoGame should load (if the controller was setuped in Big Picture mode, it should work with the game).

**Comment by cra0zy** [comment]
@tomspilman This can be closed
