### ISSUE TITLE
Scale and Rotation properties in Matrix class return incorrect values

### ISSUE THREAD

**Issue by KrytenCoder** [MonoGame/MonoGame#5553]
When calling the Scale and Rotation properties on the Matrix class, the values returned are often incorrect. I have been struggling to get some code to work for some time and discovered that by replacing these calls with a single call to Matrix.Decompose the correct values are returned. For example, calling Scale seems to always return 1,0,0 but when using Decompose the correct value 1,1,1 is returned.

**Comment by Jjagg** [comment]
Yes, these values are only correct when only scale or rotation are applied. This is confusing and IMO these properties should either be removed in favor of the Decompose function or this should be clearly documented.

**Comment by KrytenCoder** [comment]
I agree, if they return garbage most of the time they should be removed. At the very leased there should be a summary tag over the method with a warning maybe. Ive lost hours thinking my math was wrong and now I'm wondering how many other places in code I've expected them to return what they claim and just given up on it and marked it as a todo.
Thanks @Jjagg if this is known issue should i close or leave open?

**Comment by tomspilman** [comment]
> I'm in favor of removing them myself, these properties are not available in XNA either.

Agreed... lets remove them.

**Comment by willmotil** [comment]
I think they were intended as convenience methods but only for world matrix's.
They are pretty useless though i can just go new Vector(m11,m22,33) for scale. 
r = m; r.Translation = Vector3.Zero; for rotation. 
After you multiply by world by view those are trashed. They should have been named WorldScale WorldRotation. 

What's more troubling is i just discovered Matrix.CreateScale  used on a world matrix. 
When passed to basic effect flips the projection and you need to negate the z component first.  
CreateScale(v.X , v.Y, **-v.Z**);

**Comment by Jjagg** [comment]
What does this have to do with World/View/Projection matrices? It's plain wrong for a generic transformation matrix to return Scale and Rotation like MG currently does. The values are wrong for any matrix containing both scale and rotation.

> What's more troubling is i just discovered Matrix.CreateScale used on a world matrix.
When passed to basic effect flips the projection closer vertices are drawn closer to the screen ackkk!!!.
You need to negate the z component first. CreateScale(v.X , v.Y, -v.Z);

I don't get what you mean by that.

**Comment by willmotil** [comment]
> 
> What does this have to do with World/View/Projection matrices?
> The values are wrong for any matrix containing both scale and rotation.

Well im not disagreeing in saying these aren't useless, 

Though technically the values are still usable after rotation as long as its not by the view matrix.

The values for m11 m22 m33 are the scaling part of the matrix.
Even after you mulitply the world by a regular rotation matrix they are still valid individually.
m11 is the x scale
m22 the y scale
m33 the z scale
Scale.Normalize will still evaluate to 1 and so it could be used for some obscure purpose.
The values are valid until you mulitply by the view matrix. 
The create look jumbles up the matrix to were you can even use that scalar after that anymore.
Same as trying to get the values out of a projected matrix without unprojecting first.
The rotation isn't even returning a matrix though.

> I don't get what you mean by that.
I drew a cube to the screen with basic effect using a world view fov projection matrixs.
I then repeat that process using Matrix.CreateScale(.5f) * world and then pass it to basic effect.
in the first case the farthest vertices are correctly displaced towards the focal point.
in the second case the closest vertices are incorrectly displaced towards the focal point.
