### ISSUE TITLE
Content Pipeline Extension project referencing error in Visual Studio 2017

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#5554]
Please be seated before reading this.

I've found what I suspect is a bug/change in VS2017 with the $(MSBuildExtensionsPath) variable we use in the Content Pipeline project.

in 2015 and before, this correctly resolves to the MSBUILD folder on the dev machine.

in 2017 however, this is resolving to the Windows 8 MonoGame folder???  so as the Content Pipeline project DLL is nto packages with / per platform, this reference fails.

So need to investigate further to see what's causing this and whether a template change is required or whether we await a Visual Studio fix.

*On a side note
I noticed we don't actually have a proper Content Pipeline DLL, only the PCL one.
Having a full CP NuGet and using that in the project reference may be another easy way to resolve the issue.

**Comment by tomspilman** [comment]
> in 2017 however, this is resolving to the Windows 8 MonoGame folder

That makes zero sense... can we get someone to verify this on another system?

If it indeed is happening I would say it is a VS2017 bug.

**Comment by trong8820** [comment]
Because $(MSBuildExtensionsPath) value is C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild

**Comment by Jjagg** [comment]
Haven't gotten any reports of this and it would occur with every template if it was a MG issue. This was most likely an installation issue.
