### ISSUE TITLE
Windows StoreApps PreferredBackBufferWidth/Height bug

### ISSUE THREAD

**Issue by nkast** [MonoGame/MonoGame#5555]
PreferredBackBufferWidth/Height is wrong at startup when Client Width<Height.

W8.1 / WP8.1 Screenshots

![w81](https://cloud.githubusercontent.com/assets/3018589/23714688/d98681f4-0432-11e7-8c41-6954d3f53170.png)
![wp81](https://cloud.githubusercontent.com/assets/3018589/23714691/db0b07b6-0432-11e7-8489-cc999331297d.png)

The cause of this is https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/GraphicsDeviceManager.cs#L69-L78
which I assume is an attempt to [Automatic Rotation](https://msdn.microsoft.com/en-us/library/ff966425.aspx).
 
On W10 the values are still wrong during Game.Initialize(). After initialization W10 receives a SizeChange event that restores the values.
Even if W8.1/WP8.1 got a resize event the same code is present in MetroGameWindow.cs (UAPGameWindow.cs doesn't swap Width/Height),
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Windows8/MetroGameWindow.cs#L157-L166

IMO it's best to remove this code entirely.

A proper implementation would be to change the Orientation when SupportedOrientations= Default and the game is fullscreen or runs in fullscreen environment (WP,Android,iOS).

Personally I think this behavior is confusing and goes a step too far. I found myself fighting against it in XNA in the past when trying to take advantage of the WP7 scaler.

**Comment by tomspilman** [comment]
> IMO it's best to remove this code entirely.

Yeah I think that would be the best approach.
