### ISSUE TITLE
Loading 3D Model on 3.6 iOS results in an Exception

### ISSUE THREAD

**Issue by dellis1972** [MonoGame/MonoGame#5557]
Unhandled Exception:

System.ArgumentException: elementCount is not the right size, elementCount * sizeof(T) is 32768, but data size is 65536.
Parameter name: elementCount occurred

@Jjagg any ideas?

**Comment by dellis1972** [comment]
Looks like its related to Texture Compression on iOS. Setting to Compressed results in the error, setting to Color works

 @KonajuGames

**Comment by dellis1972** [comment]
ok with Color set.. we get blank textures. Something weird is going on.

**Comment by tomspilman** [comment]
@dellis1972 - So first... who is throwing that `ArgumentException`?  My guess is `Texture2D.SetData()`?

If so maybe has something to do with https://github.com/MonoGame/MonoGame/pull/5512/files ?

**Comment by dellis1972** [comment]
well my guess is when using "Compressed" its creating a DXT texture not a
PVRTC texture... hence the problem. iOS only loads PVRTC.
With the Color setting it loads.. but the texture is either blank or not
quite right. I'll try and put a sample together over the weekend.

**Comment by tomspilman** [comment]
> well my guess is when using "Compressed" its creating a DXT texture not a
PVRTC texture... hence the problem

Yeah... that would be the first bug... we should never be creating DXT textures for iOS.

> With the Color setting it loads.. but the texture is either blank or not
quite right.

Bug number two then.  There is no reason for a color texture to not work on iOS.

**Comment by dellis1972** [comment]
So this is the end result.. 

DesktopGL
<img width="1680" alt="screen shot 2017-03-08 at 20 59 56" src="https://cloud.githubusercontent.com/assets/810617/23723728/345552c2-0442-11e7-9bfa-df97b74f31b2.png">

Android (and iOS).
<img width="1680" alt="screen shot 2017-03-08 at 20 58 33" src="https://cloud.githubusercontent.com/assets/810617/23723716/2087a6a0-0442-11e7-9cee-c872c7e89aff.png">

Same content settings. Both have the 3DModel TextureCompression set to Color. 
Setting to Compressed results in the exception in the comment 1

**Comment by dellis1972** [comment]
looking at the android screen shot, it looks like the lighting is not working.

**Comment by tomspilman** [comment]
> it looks like the lighting is not working.

Should be easy to disable lighting of the `Effect` and check.

**Comment by dellis1972** [comment]
its not the lighting. Loading the texture from the model manually results in a black texture. So this is a content pipeline issue.

**Comment by dellis1972** [comment]
looks like PVRTC compressed textures are bust :(
the Compressed options doesn't work either.

**Comment by tomspilman** [comment]
> looks like PVRTC compressed textures are bust :(
> the Compressed options doesn't work either.

Yeah...  we have a bunch of options there... `Compressed`, `DxtCompressed`, `PvrCompressed`, `Etc1Compressed`, and `AtcCompressed`... i still feel it is a mistake to have all of these IMO.

On the console ports I throw an exception if you select an incompatible format for the platform... like selecting `Etc1Compressed` or `PvrCompressed` on XB1 for instance.  This is just me protecting against people setting dumb settings that we allow because of the additional formats we added.  Also i automatically convert `DxtCompressed` to `Compressed` since IMO...  `DxtCompressed` is just incorrectly named and not really saying the user wants DXT regardless of platform (that would be stupid).  So in the end i just look at three options...  `Compressed`, `Color` or `Color16Bit` ... with `Compressed` meaning the best format for the current platform.

I can't say what is happening for iOS in the pipeline...  but it could be doing something dumb here with the complexity of the output formats we have.

**Comment by KonajuGames** [comment]
PVR textures have been previously verified to work by themselves on
Android. I haven't tested them when processed as part of a model though.

If you haven't got it sorted soon, I'll have a look when I finish the audio
fixes.

**Comment by KakCAT** [comment]
Could you check if the error disappears removing mipmapping? If so, I think this could be the same as this: 
https://github.com/MonoGame/MonoGame/issues/5490

At least, the error "elementCount is not the right size" is the same I was getting until I removed mip mapping.

**Comment by dellis1972** [comment]
@KakCAT turning off MipMapping makes no difference if the texture if Compressed. 
If its Color then it fixes the black texture issue.

**Comment by KakCAT** [comment]
It's the same issue then, I remember starting with compression and mipmapping and changing configuration until I found that no mipmapping and no compression worked well.

As I had to release it asap, so I ended using an August 2016 MG snapshot (it was working there)

**Comment by Jjagg** [comment]
> System.ArgumentException: elementCount is not the right size, elementCount * sizeof(T) is 32768, but data size is 65536.
Parameter name: elementCount occurred

I made SetData strictly check the elementCount again (like XNA). This was slightly looser first, but IMO it makes sense to specify the number of elements you expect since you're going to use that data for something. It helps catch errors in user code (and MG code!). So the code that throws the exception just computes the element count incorrectly.

**Comment by KakCAT** [comment]
Hello,

I've found a patch with Color + MipMap textures. In Texture2D.OpenGL.cs, there's a point where there's a code 

    GL.GenerateMipmap (TextureTarget.TextureCubeMap);

I think this is what makes the mipmap loading fail. Replacing the parameter for TextureTarget.Texture2D makes the failing sample at https://github.com/MonoGame/MonoGame/issues/5490 work.

Compressed textures still fail, but instead of failing in the texture loading phase it fails just after the GL.GenerateMipmap line, with an "Out of memory" exception, so I'm not positive the patch fixes anything at all. I just hope this gives some clues :)

**Comment by Jjagg** [comment]
Woops, that looks like a huge dumb copy-paste error on my part :/

**Comment by KakCAT** [comment]
Another problem...

                    if (glFormat == (PixelFormat)GLPixelFormat.CompressedTextureFormats)
                    {
                        GL.CompressedTexSubImage2D(TextureTarget.Texture2D, level, rect.X, rect.Y, rect.Width, rect.Height,
                            (PixelInternalFormat) glInternalFormat, elementCount * elementSizeInByte, dataPtr);


CompressedTexSubImage2D just fails when using ETC1 compressed textures with Android. Error returned is "InvalidEnum". 

Replacing the GL.CompressedTexSubimage2D with GL.CompressedTexImage2D (and changing parameters accordingly) makes my Compressed Textures work when using ETC1 without mipmaps. 


Also, GL.GenerateMipmap crashes no matter what I do. If I'm not wrong this documentation of GL ES 2.0 says to throw an error when an "intenral compression format" is used, but I have no idea if this refers to all compressions like ETC1 or a GL ES compression of its own.
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGenerateMipmap.xml

As usual, no idea if this are valid pointers as I have no clue about MG internals and haven't touched OpenGL in 15 years :)

**Comment by KonajuGames** [comment]
I definitely know that ETC1 (and all other compressed texture formats)
worked on Android when I was last in the texture processing code. So what
has changed to make it return an invalid enum error now?

**Comment by KonajuGames** [comment]
I'll look at this texture compression once I post the audio PR.

**Comment by tomspilman** [comment]
Any progress on this?  I have run into it as well on a project.

**Comment by tomspilman** [comment]
So this code here...

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.cs#L332

... and this code here...

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.cs#L353

Looks suspect to me.  I don't think that correctly works for formats that are less than 1 byte per pixel.

**Comment by tomspilman** [comment]
So my experimental fix is to change this line:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.cs#L347
```
dataByteSize = roundedWidth * roundedHeight * fSize / 16;
```

... to this line...

```
dataByteSize = (roundedWidth * roundedHeight * 8) / fSize;
```

This accounts for `fSize` being in bits per pixel instead of bytes per pixel.

**Comment by tomspilman** [comment]
Another question...  why didn't our unit tests catch this case?  Are we not testing any compressed formats on Windows even?  I would think a test on a DXT texture would even trigger this assert.

**Comment by tomspilman** [comment]
@Jjagg - So shouldn't there also be a `GraphicsExtensions.CheckGLError()` inside this `if (mipmaps)` branch to check the result of the mipmap generation?

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.OpenGL.cs#L125

**Comment by tomspilman** [comment]
So this...

```
GL.GenerateMipmap(TextureTarget.Texture2D);
```

Fails under PVRTC if you call `CheckGLError()`... because yeah it cannot automatically generate mips for compressed textures.  That command is literally... "make some mipmaps now"... which seems dumb to happen in texture construction before we have even set any data.

I don't know much about GL, but this sounds wrong to me.  There must be some other correct way to say "create a new empty texture with mipmaps" that doesn't involve trying to filter level 0 to generate mipmaps at runtime.

**Comment by KonajuGames** [comment]
Compressed textures are only loaded through the ContentManager, which means
they were processed by the content pipeline. If the dev wants mipmaps, they
should have been generated in the content pipeline and not at load time.

**Comment by tomspilman** [comment]
Ok... so calling `GL.GenerateMipmap(TextureTarget.Texture2D)` is utter bullshit from what I can tell.

The right thing is doing a loop and calling `GL.CompressedTexImage2D` for each level.  We should fix this and stop calling `GL.GenerateMipmap` when that isn't what we're trying to do.  It likely is costing us performance on texture creation for no reason at all... when it works at all.

**Comment by tomspilman** [comment]
> Compressed textures are only loaded through the ContentManager, which means
they were processed by the content pipeline. If the dev wants mipmaps, they
should have been generated in the content pipeline and not at load time.

Agreed... however we've been calling `GL.GenerateMipmap` in our texture constructors for years now.  I suspect this was someones "trick" to avoid writing the loop to correctly add mip levels to the texture.

**Comment by tomspilman** [comment]
So my findings....

 - `Texture2D.ValidateParams()` is broken for compressed formats.  It doesn't consider bits per pixel or that there is a min size for some mip levels.

 - We must purge `GL.GenerateMipmap` from our GL texture constructors and correctly construct textures with mip levels.  Both for compressed and non-compressed textures.  This would result in cleaner code with no mobile hacks actually.

**Comment by Jjagg** [comment]
> Texture2D.ValidateParams() is broken for compressed formats. It doesn't consider bits per pixel [...]

All compression formats are block compression with 4x4 blocks. So fSize is bytes per block. The size of the region to get/set in bytes is then 

```
var nrBlocks = width * height / 16; // all supported compression formats are 4x4 block compression schemes
var bytes = nrBlocks * fSize;
```

> [...] or that there is a min size for some mip levels

It does:
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.cs#L338-L344

> We must purge GL.GenerateMipmap from our GL texture constructors and correctly construct textures with mip levels. Both for compressed and non-compressed textures. This would result in cleaner code with no mobile hacks actually. See #5599.

Can't argue with this. The GL.GenerateMipmap call is plain wrong and I messed up here. I don't know how to tell GL a texture needs mipmaps without generating them though.

> This checkedRect stuff here should be removed. It doesn't account for compressed texture mip sizes and is likely more expensive. See #5600.

Why remove it? It's used to get the same behavior as XNA when Get/SetData is used on compressed textures. x, y, width and height of the Rectangle are all rounded to fit blocks. And as for compressed texture mip sizes, it does account for that like I said above. But I agree on not using the ValidateParam stuff for the simpler Get/SetData overloads that get/set the whole texture.

> Another question... why didn't our unit tests catch this case? Are we not testing any compressed formats on Windows even? I would think a test on a DXT texture would even trigger this assert.

All DXT tests passed last time I ran the tests, both on DesktopGL and WindowsDX. Tests are here:
https://github.com/MonoGame/MonoGame/blob/develop/Test/Framework/Graphics/Texture2DNonVisualTest.cs#L518

**Comment by KonajuGames** [comment]
I've been working on this tonight.  The call to `GL.GenerateMipmaps()` is removed and the desired number of mip levels is now set in `GenerateGLTextureIfRequired()`.  Also added a simpler `PlatformSetData()` overload that assumes the entire texture level.  Still more to finish though.

**Comment by tomspilman** [comment]
> All DXT tests passed last time I ran the tests

@Jjagg - I'm sure they did... my point was why did they pass when the code is clearly incorrect?  I am suggesting there is something wrong/missing in our tests.

**Comment by Jjagg** [comment]
The code - as far as I'm aware - is only incorrect for compressed formats that use blocks other sizes than 4x4.

**Comment by KonajuGames** [comment]
#5614 fixed loading of compressed textures.
