### ISSUE TITLE
Models to not render properly by default

### ISSUE THREAD

**Issue by dellis1972** [MonoGame/MonoGame#5558]
When loading and rendering a 3d model using the same code as XNA the model looks transparent / inside out. You have to add the following code before you draw the model to get it to work.

```GraphicsDevice.DepthStencilState = DepthStencilState.Default;```

**Comment by dellis1972** [comment]
We should probably set this by default (if possible)

**Comment by tomspilman** [comment]
> You have to add the following code before you draw the model to get it to work.

`DepthStencilState.Default` is the default state when the graphics device is initialized.

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.cs#L280

 So unless someone changes it before this point it would be set.

> We should probably set this by default (if possible)

By default where?

**Comment by dellis1972** [comment]
Looks like spriteBatch is messing this up. I'll check to see what happens
with the same code in XNA.

**Comment by Jjagg** [comment]
`SpriteBatch` modifies state. That is also the case in XNA. This is not a bug.
