### ISSUE TITLE
IOS SpriteFont data format problem on remote debug from visual studio

### ISSUE THREAD

**Issue by nebosite** [MonoGame/MonoGame#5561]
I'm using Visual Studio 2015 CE to remotely build and debug an IOS app.  When I build and run the app from Xamarin on my mac, it works fine, but when I try from my PC, the build works, but there is a runtime exception when loading a spritefont:

    System.ArgumentException: elementCount is not the right size, elementCount * sizeof(T) is 131072, but data size is 262144.
    Parameter name: elementCount

Note that the data size is exactly twice expected size.   I suspect this also happens on any texture, but I have not tested that.

Details:
- the font.otf file is incorperated directly in the Content/Fonts folder and is referenced directly from the sprintfont file.
- The "Perform all 32bit floating point operations as 64 bit" option is unchecked
- The IOS project is pretty vanilla.  I haven't altered any compiling options that I can think of.

**Comment by KonajuGames** [comment]
This will be the same issue as #5557.

**Comment by KonajuGames** [comment]
It will be fixed soon when one of us can look at it.

**Comment by KonajuGames** [comment]
Fixed with #5614.
