### ISSUE TITLE
Support for compressed SoundEffects

### ISSUE THREAD

**Issue by simoneddeland** [MonoGame/MonoGame#5564]
SoundEffects are processed with the Content Pipeline Tool to an uncompressed format which can make audio files take up a very large percentage of a games' total size. This is the way it was done in XNA (too increase loading speed?), but wouldn't it be good to support a way to build compressed SoundEffects with the Content Pipeline Tool? The trade off for a smaller .xnb size would be a longer loading time but it would be up to each developer to decide if they want to do this tradeoff or not via some setting in the pipeline tool.

**Comment by KonajuGames** [comment]
I think you're getting confused about what compressed sound really is.  Sounds are processed to PCM at the input sample rate when the `CompressionQuality` property is at the default value of `Best`.  At `Medium` compression quality it is processed to ADPCM (4 bits per sample) at 2/3 of the input sample rate, and at `Low` quality it is processed to ADPCM at half the input sample rate.  Each of these result in lower quality but smaller file size.  At runtime, they are not decompressed but are played as-is.  So they actually load quicker because there is less data to read, but at the cost of sound quality.

**Comment by KonajuGames** [comment]
Content compression (stored on disk compressed and decompressed at load time) is a different topic, and typically does not work well with audio because content compression works best with patterns of data, and audio data is mostly random values.

**Comment by simoneddeland** [comment]
@KonajuGames  Thank you for clarifying what the different quality levels mean.

I guess what I'm trying to ask is if it's possible to process the sounds to Vorbis, AAC or some other audio coding format and save that data in the .xnb files instead of processing to PCM. My thought was that this would achieve a higher sound quality level while keeping the file sizes smaller. Then the sound would be loaded into memory as as Vorbis or AAC and played as-is OR converted to PCM when the game wants to load them. My knowledge of how the audio system works is below this level however, what I want to achieve is smaller .xnb files for sound while still keeping a higher audio quality.

**Comment by KonajuGames** [comment]
We have Vorbis playback in the DesktopGL platforms, though it's aimed at streaming song playback at this stage. It could potentially be used for SoundEffect as well, but it would add a load of complexity to integrating it into the existing sound playback. It would create a DynamicSoundEffectInstance behind the scenes for each sound playing, and Vorbis decoding is not cheap. It would have a CPU and memory cost to realtime decode each concurrently playing Vorbis sound effect.

Vorbis typically compresses to 15-20% depending on quality. ADPCM is 4-bits per sample, giving you 25% of the original file size, and near zero CPU and memory cost during playback.

**Comment by simoneddeland** [comment]
@KonajuGames How would 4-bit ADPCM compare to Vorbis (at about the same bitrates) quality wise? Is 4-bit ADPCM (i.e. medium compression quality) enought for most sound effects in your opinion?

**Comment by KonajuGames** [comment]
A lot of games have already used ADPCM for years and you never knew.

**Comment by tomspilman** [comment]
We support compressed sound effects already.
