### ISSUE TITLE
Use NuGet packages for project templates

### ISSUE THREAD

**Issue by harry-cpp** [MonoGame/MonoGame#5565]
We should switch to using NuGet package for local project templates so we can update native libraries in the background.

Also the idea is to use local NuGet packages as the base for the templates, like what @dellis1972 did before for MonoDevelop addin.

CC. @dellis1972 @tomspilman

**Comment by dellis1972** [comment]
I think this should be put off until the new template creator is done. Then the user can have the choice of using local assemblies, nuget or the source. (If that is still the plan). 

To be honest the only reason I used Nuget for the MonoDevelop addin in the first place was because we had problems referencing the local assemblies. That was fixed.

**Comment by cra0zy** [comment]
My idea is to remove local assemblies completely, they literally have no up side.

**Comment by dellis1972** [comment]
I personally try to avoid using Nuget unless I absolutely have too. Mostly
for the reason I do a fair amount of development offline. So unless you
have the required packages downloaded already and cached you are stuffed if
you start a new project e.g on plane in the middle of the Atlantic. Having
no network access happens more often than I'd like to admit.

I have also been in a position where the Nuget servers are unavailable or
are under a DDOS attack. When that happened work at the company I was at
ground to a halt. After that we had to create and manage our own Nuget
server.

One thing that I personally find annoying about UWP development for example
is the need to download a ton of packages before you can even compile the
app and the first thing you see when creating a new project is a ton of
errors. Not a great UX I'm my opinion.

All that said I'm not saying we should not offer it as a choice, just
saying it shouldn't be the only one :)

**Comment by cra0zy** [comment]
By providing local versions of NuGet packages all the problems you face are gone.

The reason why I think we should not offer local assemblies is because we rely on some native libs and if we change them there is no way to auto update them for the end users.

**Comment by DDReaper** [comment]
If you switch from packages assemblies to NuGet only, then if you are on a train jam with no connectivity you are completely stuffed :S 
I agree they are the best and most current way of getting references and I do prefer them, but the lack of an offline backup option kinda makes it hard to justify with the templates.

I use them predominately in the MonoGame.Samples site, but that's on GIT and if you can't access that, you can't access the samples and so no issue.

The template creator could use the NuGet's as a primary and supply an offline "backup" for offline situations, which overall is the better solution.

**Comment by cra0zy** [comment]
@DDReaper

> Also the idea is to use local NuGet packages as the base for the templates, like what @dellis1972 did before for MonoDevelop addin.

**Comment by DDReaper** [comment]
@dellis1972 did some black magic with the MonoDevelop addin to make that happen. Not sure it's even possible with VS.
Which is why I say it could possibly done with a standalone template generator

**Comment by Jjagg** [comment]
Done!
