### ISSUE TITLE
Replacing System.Drawing for DesktopGL

### ISSUE THREAD

**Issue by cra0zy** [MonoGame/MonoGame#5567]
Most parts of System.Drawing are already gone, and now the last file that needs to be fixed would be: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.OpenGL.cs This needs to be done so we can get .Net Core supporting more easily when the time comes.

For replacing System.Drawing I would recommend going with either of these:
 - <a href="https://github.com/JimBobSquarePants/ImageSharp">ImageSharp</a> - it's fully managed so no need for any dependencies
 - ~~<a href="https://www.libsdl.org/projects/SDL_image/">SDL_image</a> - if we are going native we might as well pick a format that SDL understands~~
   - ~~bonus point: we get .ico format, useful for loading window icon~~

CC. @tomspilman @KonajuGames @dellis1972

**Comment by tomspilman** [comment]
Well first... what are we using `System.Drawing` for?  Seems like for `Texture2D.PlatformFromStream()` and `Texture2D.SaveAsPng/JPEG()` mainly...  is there more that we need that saving/loading image data?

I see a better alternative which would take a little work from us.

We already had @disportium contribute PNG reading/writing here:

 https://github.com/MonoGame/MonoGame/tree/develop/MonoGame.Framework/Utilities/Png

The performance is a bit poor on consoles/mobile because of the design (lots of little array allocations, no use of pointers, etc).  I would love to see that improved and used on all platforms as it gives us a cross-platform portable PNG encoding/decoding.

It would be ideal to do the same with JPEG as there are reference encoders/decoders out there to work from.

**Comment by cra0zy** [comment]
There is also: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Input/MouseCursor.SDL.cs#L40

And it needs to be a bmp format for SDL to be able to read it.

**Comment by cra0zy** [comment]
Also it would be nice if this piece of code could load .ico files: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/SDL/SDLGameWindow.cs#L127

**Comment by tomspilman** [comment]
> And it needs to be a bmp format for SDL to be able to read it.
> Also it would be nice if this piece of code could load .ico files: 

So this means we need:

  - Png reader/writer (done... but could use improvement)
  - Jpeg reader/writer
  - Bmp writer (and reader would be nice)
  - Ico reader.

Correct?

**Comment by KonajuGames** [comment]
I don't think there is anything that writes a BMP.

**Comment by willmotil** [comment]
Image sharp lists bmp as well as others it just dumps them to disk with filestream.


    ImageSharp Contains the Image classes, Colors, Primitives, Bootstrapper, IImageFormat interface, and other core functionality.
    ImageSharp.Formats.Jpeg The jpeg decoder/encoder (Auto registered)
    ImageSharp.Formats.Png The png decoder/encoder (Auto registered)
    ImageSharp.Formats.Gif The gif decoder/encoder (Auto registered)
    ImageSharp.Formats.Bmp The bmp decoder/encoder (Auto registered)
    ImageSharp.Processing Contains methods like Resize, Crop, Skew, Rotate - Anything that alters the dimensions of the image. Contains methods like Gaussian Blur, Pixelate, Edge Detection - Anything that maintains the original image dimensions.
    ImageSharp.Drawing Brushes and various drawing algorithms, including drawing Images
        ImageSharp.Drawing.Paths Various vector drawing methods for drawing paths, polygons etc.

**Comment by tomspilman** [comment]
> Image sharp lists bmp and jpeg as well as others.

We are aware ImageSharp supports the formats we need.  That isn't a question here.

The question is should we continue down the path we started with https://github.com/MonoGame/MonoGame/pull/3537 or change paths?

Using a native library has the normal binary issues plus extra work to build a version for each platform.  For me maintaining all the console ports it means porting each of these native libraries to the console.  Not an ideal situation. However the native library should be very fast.

Using a managed library means yet another assembly to ship along side `MonoGame.Framework.dll` and possibly one bloated up with a lot more "features" than we ever use.  However they can be easy to support on consoles if they don't call OS specific features.

Rolling our own is more work for us to develop and test, but it supports just the features we need at runtime in MG and has no other dependencies.  It is also fully portable to every platform.  This to me is the ideal situation.

**Comment by prollin** [comment]
If you guys go native, I would recommend to look at [TurboJPEG ](http://www.libjpeg-turbo.org/About/TurboJPEG) for fast jpeg decoding; been using this on Windows/iOS/Android without issues. Windows and iOS comes with prebuilt binaries, Android was a bit more work but nothing out of the ordinary when dealing with native libraries.

Sometime I wish there was a pure c# stb style library for common stuff like that :)

**Comment by tomspilman** [comment]
> Sometime I wish there was a pure c# stb style library for common stuff like that :)

Actually... you reminded me!  A MG community member has started porting STB to C#:

http://community.monogame.net/t/stbsharp-c-port-of-famous-c-framework/8715

@rds1983 - You around to talk about this?

**Comment by rds1983** [comment]
Sure.

**Comment by tomspilman** [comment]
Hey @rds1983.

How far have you gotten with performance since your last post about StbSharp?

Are you willing to or open to adding more performance improvements to it?

If we included the code directly into MonoGame via a submodule would you be ok with that?

**Comment by rds1983** [comment]
1. No, actually I didnt change anything since that last post.

2. I am willing and open. But as it is stated in the initial post, the StbSharp code isn't manual port, but it is the generated code: https://github.com/rds1983/StbSharp/blob/master/StbSharp/Image.Generated.cs. 
So I dont really know what is going in the code. 
Though I planned some changes(probably will do it this week) - I want to replace smaller classes(that dont have delegates as their members) with structs. Including ArrayPointer<T>. That'll make it work more like the original C version. Unsure though if it'll improve the performance.

3. Sure. Actually, personally I've included some of your code in my other project already: https://github.com/rds1983/Myra/blob/master/Myra/Utility/PngReader.cs
So have completely no problems with that :)

**Comment by cra0zy** [comment]
> So this means we need:
> 
> Png reader/writer (done... but could use improvement)
> Jpeg reader/writer
> Bmp writer (and reader would be nice)
> Ico reader.
> Correct?

We also need gif reader: https://msdn.microsoft.com/en-us/library/ff434103.aspx

SDL Image adds 1.5 MB and gets us all we need: http://jcatki.no-ip.org:8080/SDL_image/SDL_image_frame.html

**Comment by rds1983** [comment]
In support of the StbSharp, I want to add that it's parent STBI is proven to be stable and mature. Therefore it is used in another famous managed game framework libgdx: https://github.com/libgdx/libgdx/tree/master/gdx/jni/gdx2d
Though they seem to use jpgd for jpg decoding. Probably I'll port it eventually too.

The downsides of StbSharp is it's young and need to be seriously tested on thousands of images.
It can't load GIF yet, but it'll be added eventually. And it can't write too(and it wont be added, as STBI lacks that feature also).

**Comment by cra0zy** [comment]
Actually scratch my supporting of SDL Image, it only allows loading...

**Comment by rds1983** [comment]
Further research revealed, that STB has this lib: https://github.com/nothings/stb/blob/master/stb_image_write.h

I can run my converter over it and it'll generate PNG, BMP, TGA and HDR(what is it?) writers.

**Comment by KonajuGames** [comment]
HDR is a format that no-one uses.

JPEG is always the odd one out, though not surprised given the messy patent history it has.

**Comment by mrhelmut** [comment]
Definitely +1 for removing references to System.Drawing, no matter the alternative among the ones mentioned. It's a pain with Mono & MonoKickstart.

**Comment by willmotil** [comment]
Well it would be great if you wrote your own encoder decoders but that really is a bit of work.
The end result might end up being just as bloated as something like image-sharp. 

Though technically a graphical api should i think have its own image encoding decoding functions.
I think this is a also a question of manpower.

_I rewrote a decoder encoder a long while back for something called a .shp file a old out dated encoding which is surprisingly good for how simple the data stream itself was compared to others.  It was stored in a another table called a datup. It was quite a effort even with a clear format description and took a long time._

**Comment by rds1983** [comment]
I've ported ported stb_image_write.h. So now StbSharp can write images in BMP, TGA, HDR and PNG formats.
Also GIF loading has been ported. So now StbSharp can read images in JPG, PNG, BMP, TGA, PSD, PIC and GIF formats.

**Comment by tomspilman** [comment]
@rds1983 - So writing JPG would then be the only missing feature then.

Still concerned over getting the performance up with the converted STB code, but I am sure this is doable with some custom tweaks to the code.

**Comment by cra0zy** [comment]
@rds1983 Why not make StbSharp public domain? I ask this because you basically just run a C# converter on stb, and stb is public domain.

**Comment by rds1983** [comment]
@cra0zy Frankly I just didnt think and chose first license that went to my mind. Anyway, you made good point, thanks. So it's public domain now. :)

**Comment by rds1983** [comment]
I've run my converter over this lib: https://github.com/serge-rgb/TinyJPEG/
Which resulted in yet another port: https://github.com/rds1983/TinyJpegSharp

**Comment by rds1983** [comment]
Did some improvements on StbSharp to reduce amount of allocations: replaced most of classes with simple structs(fixed fields are used for arrays) and replaced most of local allocations with stackalloc.
Also I've finally written simple auto-tester:
https://github.com/rds1983/StbSharp/blob/master/StbSharp.Tests/Program.cs
It recursively traverses specified folder and for every found image does following:
1. Loads it with StbSharp.
2. Loads it with stb_image.h (which is called through C++/CLI wrapper).
3. Performs per-byte comparison of results acquired in step 1 and 2.
4. Encodes the image with StbSharp with every supported format(except for HDR, I'll explain the reason later).
5. Encodes it with stb_image_writer.h
6. Again performs the per-byte comparison.

Also it sums up overall time of StbSharp/stb_image.h loading and reports it.
For the testing reasons, I've took all images from [DigitalRune Engine](https://github.com/DigitalRune/DigitalRune) and put them in the separate repo: https://github.com/rds1983/DigitalRune-Images (I hope I didnt do anything inappropriate)

Then ran my tester over it. There aren't any discrepancies in the per-byte comparisons.
And there's report of the overall loading time:
Total StbSharp Loading Time: 8097 ms
Total Stb.Native Loading Time: 6561 ms
That is for about 750 different images.
Most importantly the StbSharp loading time is actually close to the stb_image.h

So overally I think that StbSharp is ready to be used.

Now the bad part is HDR writer is somewhat buggy. It randomly crashes the auto tester by hitting the unmanaged memory somewhere. But that's not gonna be an issue as HDR writing isn't gonna to be used.

**Comment by tomspilman** [comment]
Great work @rds1983 !

> Total StbSharp Loading Time: 8097 ms
> Total Stb.Native Loading Time: 6561 ms
> That is for about 750 different images.

Those numbers do look really good...  around a 2ms difference between managed and native image decoding (disk access is factored out in your tests).

Still the testing method has me a little concerned.

`DateTime.Now` is only accurate to around 30ms.  I suggest switching to `Stopwatch` which is more accurate and doing the decode step like 500 times then taking the average of the time.  This will make the test run much slower...  but should make your measurements much more accurate.


> Now the bad part is HDR writer is somewhat buggy. 

We would likely want to not even use HDR loading or saving at all.

Ideally we could omit formats we don't need from the code base to reduce binary size.  I know STB had this feature, but not sure if your translated version does too.

**Comment by rds1983** [comment]
Thanks for the feedback. My version doesnt have that feature yet. But it'll be added.

**Comment by rds1983** [comment]
I've made dedicated repo with versions of StbSharp & TinyJpegSharp suited for the MonoGame integration: https://github.com/rds1983/MonoGame.StbTinyJpegSharp
Unessecary formats had been removed. So it can read images from JPG, PNG, GIF, BMP and TGA formats. And write to BMP, TGA, JPG(TinyJpeg quality=2 is used for that) and PNG formats.
[This](https://github.com/rds1983/MonoGame.StbTinyJpegSharp/tree/master/MonoGame) contains all source files that would need to be included. All classes but [Texture2D](https://github.com/rds1983/MonoGame.StbTinyJpegSharp/blob/master/MonoGame/Texture2D.cs) are internal. Actually, Operations is also public, but it is required only for the autotesting app and wouldn't be required for actual MG integration.
This project has it's own [autotesting app](https://github.com/rds1983/MonoGame.StbTinyJpegSharp/tree/master/MonoGame.Tests)
Its working principles I'd described two posts earlier.
Though I've replaced DateTime.Now with Stopwatch. Also every image is loaded 100 times than the elapsed time is divided by 100.
I got following result this time:
Total StbSharp Loading From Stream Time: 7837 ms
Total Stb.Native Loading From Stream Time: 5673 ms

**Comment by cra0zy** [comment]
@rds1983 If you can submit a PR to MonoGame.

**Comment by rds1983** [comment]
I can. What backend(s) should I submit it for? Only DesktopGL?

**Comment by cra0zy** [comment]
For now only DesktopGL, it will be much easier to assess the PR.

**Comment by rds1983** [comment]
Ok.
