### ISSUE TITLE
Standalone template generator

### ISSUE THREAD

**Issue by cra0zy** [MonoGame/MonoGame#5571]
So it seems that a need for the standalone project template generator has risen, and I do have time to work on it right now... so I need you all to give me what you would like it to be able to do, and what you don't want it to do.

There is also an option of using Protobuild Managet for generating project templates, which I am not really a fan of.

CC. @tomspilman @KonajuGames @dellis1972 @DDReaper

**Comment by theZMan** [comment]
What are the practical reasons for not using Protobuild - if it doesn't do what we need lets make it work. Its open source after all.

Even if that's not possible there's well tested generators like this http://yeoman.io/ (SOlid enough that the VS Code team use it for their examples https://code.visualstudio.com/docs/tools/yocode) - making more code that we need to maintain going forward isn't usually a great idea.

**Comment by DDReaper** [comment]
Ultimately @cra0zy  it simply needs to provide the capability to:

- Generate a project / solution template similar to VS with templates for all platforms
- Bind to NuGet libs first and fall back to cache / nuget backup for references

Secondarily, it would be nice to be able to:

- Like protobuild, generate a multi-project solution
- Have a "Open Solution" method to open your editor of choice in the project folder (e.g. MD / VS or VSCode)
- Integrate with VS / MD to have a template option to launch the manager
- (really wishy) have a "news" / "Info" page section which feeds directly from MonoGame 💃 

I don't mind helping out but it seems the ProtoBuild template manager seems a good start as it has most things already. So I'd have to agree with @theZMan that if it doesn't do something we like, then OS the heck out of that sucker. (better to start with something working and make it better imho)

**Comment by cra0zy** [comment]
> Integrate with VS / MD to have a template option to launch the manager

I would avoid that at all costs.. MD changes APIs like socks and always breaks stuff :( Plus there is Rider IDE as well so if we provided templates for those 2 we need to provide templates for the 3rd one as well...

**Comment by DDReaper** [comment]
Ok, ignore MD, fine with that, lol :P

**Comment by jackmott** [comment]
Just a note that if you create this, it would be nice to also have it support F# projects. I'm happy to help with that if this gets going.

**Comment by Jjagg** [comment]
Once this is set up it should be easy to have the option to choose Game1.vb and Game1.fs files.

**Comment by tomspilman** [comment]
At this point my intention is to give https://github.com/MonoGame/MonoGame/pull/4295 a fair look before deciding on using anything else.  My concern is still that often @hach-que and i butt heads on what features we want as maintainers of MonoGame and what ProtoGame wants as a concerned user of MonoGame.

I'll get this worked out this week so we can finally move on with this template stuff.  This has become a pretty critical issue with as many version of VS we're supporting plus the rapid pace of Xamarin Studio changes.

**Comment by cra0zy** [comment]
> My concern is still that often @hach-que and i butt heads on what features we want as maintainers of MonoGame and what ProtoGame wants as a concerned user of MonoGame.

Yup, I see that exact problem happening, it has already happened several times with Protobuild...

**Comment by cra0zy** [comment]
Now that I think about it, maintaining Protobuild Manager is probably gonna be harder than maintaining our custom project template generator.. why? Well let's say we want to make Protobuild Manager support F#, than we need to fix Protobuild first, than Protobuild Manager, than update here in repo, and fixing each part is not easy, while on the other hand our custom project template generator just needs to copy over a few files to generate a project, so adding F# support to something like that is way quicker and easier.

**Comment by hach-que** [comment]
Not really, the Protobuild Manager just uses an overlay system so you can just copy F# `.proj` files into the template and it can generate them.

**Comment by cra0zy** [comment]
Oh, I did not realize that.

**Comment by cra0zy** [comment]
@tomspilman [Did / What did] you decide?

**Comment by cra0zy** [comment]
Closing since https://github.com/dotnet/templating exists.

**Comment by DDReaper** [comment]
Yeah but no GUI with that solution :S

**Comment by cra0zy** [comment]
Its on the roadmap, also vs and vs for mac integration is there as well.

**Comment by Jjagg** [comment]
@cra0zy You mean a standalone GUI?

**Comment by cra0zy** [comment]
> @cra0zy You mean a standalone GUI?

No, it will be command line based like `yo aspnet`...
