### ISSUE TITLE
Shader works on all platforms except for UWP

### ISSUE THREAD

**Issue by endimilojkoski** [MonoGame/MonoGame#5578]
I have a simple screen shader that works on DesktopGL and Android but don't work on UWP (Windows 10 and Xbox One).
I am attaching simple UWP project with the shader so anyone can take a look. I have heard that there might be some issue in UWP.

Here is the link, it is VS2015 solution:
https://drive.google.com/file/d/0B0Lsxplzc9IiUUFWTTU5dFM3XzQ/view?usp=sharing
It draws screenshot from the game and applies the shader on it.

This is how the game should look like with and without the shader:
![shaderissue](https://cloud.githubusercontent.com/assets/13436441/23878325/23228928-081d-11e7-9894-131413818a2c.png)

But in UWP I get all solid yellow-ish screen.

**Comment by DDReaper** [comment]
Confirmed issue, in fact for some reason on UWP it also inverts the screen for me, as shown below:
![image](https://cloud.githubusercontent.com/assets/1793042/23897418/ff857c2c-08a4-11e7-92a9-832303def460.png)

Checking the shader code, cannot see any particular reason for it:
```
// Parameter
float2 TextureSize : register(c0);
float Tint;

// Sampler
sampler TexSampler : register(s0);

// Shader
float4 main(float2 texCoord : TEXCOORD0) : COLOR 
{ 
   // Default color is fully transparent
   //float4 color = 0;
   float4 color = tex2D(TexSampler, texCoord);
   float a = color.a;
   color = color * Tint;
   color.a = a;
   
   // Scale to int texture size, add x and y
   float2 vpos = texCoord * TextureSize * 0.5f; 
   float vposSum = vpos.x + vpos.y;
 
   // Calc diff between rounded half and half to get 0 or 0.5
   float diff = round(vposSum) - vposSum;
   float diffSq = diff * diff;

   // Even or odd? Only even pixels are sampled
   if(diffSq < 0.1)
   {
      color = tex2D(TexSampler, texCoord);
   } 
   return color;
}

technique SCN
{
	pass P0
	{
#if SM4
		PixelShader = compile ps_4_0 main();
#else
		PixelShader = compile ps_3_0 main();
#endif
	}
}
```

Any thoughts @tomspilman @KonajuGames ?

**Comment by endimilojkoski** [comment]
Interesting result. I have never seen that on my side, I get all yellow-ish screen like this:
![image](https://cloud.githubusercontent.com/assets/13436441/23899538/e8dde48c-088b-11e7-85c8-d5d456e49e99.png)

Another guy that tested this also got a solid color.

BUT, in Android version I see very similar behavior with another scanlines shader.

**Comment by DDReaper** [comment]
OK, this issue is actually to do with SharpDX as the same happens on Windows DX.  
**NOT a UWP specific issue.**
So has anyone any ideas why this shader is now behaving differently fo DX over GL?

**Comment by DDReaper** [comment]
Also now tested with 3.5 and the issue still persists there, so it's not a new problem. Must have something to with the shader compilation for DX with this shader.  
Hmm, @tgjones  can you assist?

**Comment by NemoKradXNA** [comment]
It may be flipped on UWP as I think GL has a flipped y coord as opposed to DX (nice to have standards isn;t it :/), but would have thought MG would have sorted that for you.

As to the opening issue, not sure why it's doing what it's doing there, could be a card specific issue?

For that effect could you not go with a texture overlay, so, an alpha blended texture over the top of your screen rather than having post process to do that for you? I think it would be a less expensive render too.

I have not got the code and had a look, just reading this post, if I get time Ill grab it and take a look.

**Comment by dellis1972** [comment]
you want to look how the shaders are put together at [1]. They work on UWP/GL and DX.

[1] https://github.com/infinitespace-studios/VectorRumble/blob/master/Content/Effects/BloomExtract.fx

**Comment by KonajuGames** [comment]
Try converting the shader to use Macros.fxh as it clears up a lot of confusion between different platforms.

**Comment by Jjagg** [comment]
The texCoord argument isn't filled in correctly. Make sure you take the same arguments as the vertex shader you're using returns.

Changing the header to the following will fix the issue.

`float4 main(float4 position : POSITION0, float4 c : COLOR0, float2 texCoord : TEXCOORD0) : COLOR`

**Comment by Jjagg** [comment]
Full shader, also with a minor optimization:

```
// Parameter
float2 TextureSize : register(c0);
float Tint;

// Sampler
sampler TexSampler : register(s0);

// Shader
float4 main(float4 position : POSITION0, float4 c : COLOR0, float2 texCoord : TEXCOORD0) : COLOR 
{ 
   float4 color = tex2D(TexSampler, texCoord);
   
   // Scale to int texture size, add x and y
   float2 vpos = texCoord * TextureSize * 0.5f; 
   float vposSum = vpos.x + vpos.y;
 
   // Calc diff between rounded half and half to get 0 or 0.5
   float diff = round(vposSum) - vposSum;
   float diffSq = diff * diff;

   // Even or odd? Only even pixels are sampled
   if(diffSq >= 0.1)
     color = float4(color.rgb * Tint, color.a);

   return color;
}

technique SCN
{
  pass P0
  {
#ifdef SM4
    PixelShader = compile ps_4_0 main();
#else
    PixelShader = compile ps_2_0 main();
#endif
  }
}
```

**Comment by DDReaper** [comment]
Confirmed, that seems to resolve the issue.  Very wierd the different effects the same shader had between GL / DX.
But a good lesson in what to look out for @Jjagg 

Hope this helps you @endimilojkoski

**Comment by DDReaper** [comment]
Note from @Jjagg  for you @endimilojkoski 
Be sure to check out the shader writing tips here in the future.
http://www.monogame.net/documentation/?page=Custom_Effects

This kind of fix / style is covered in the MG docs

**Comment by endimilojkoski** [comment]
Awesome, it is working now! Thanks!
I will test it on Xbox One and confirm but I am sure it will be fine.

Now let me find space for you in Credits @Jjagg !
MonoGame, MonoGame team and some of you are already mentioned ;)

**Comment by DDReaper** [comment]
Ok @endimilojkoski , if you are up and running, be sure to close this issue.

**Comment by endimilojkoski** [comment]
OK @Jjagg and @DDReaper, thanks, will have that in mind!
I don't have experience with shader code and some mentioned it could be something in UWP so I opened an issue.
