### ISSUE TITLE
Remove GamerServices

### ISSUE THREAD

**Issue by cra0zy** [MonoGame/MonoGame#5582]
Most of the classes in GamerServices are meant for communication with Xbox Live API, and the classes we have made for it are just stubs, so why keep this in? 

CC. @tomspilman @KonajuGames @dellis1972

**Comment by dellis1972** [comment]
There is a plan to get these implemented :)
I have wrappers for GooglePlay services for Android and Game Centre for
iOS. Just not had the time to submit PRs

**Comment by cra0zy** [comment]
Oh, fancy, well that changes stuff, closing...

**Comment by DDReaper** [comment]
Sounds like a plan @dellis1972  / @cra0zy 
Keep me in the loop for testing these PR's 💃

**Comment by cra0zy** [comment]
Since I have access to Xbox Live Creators program, I think I can setup a chunk of this for it.

**Comment by KonajuGames** [comment]
Note that we cannot include code in the public repo that uses APIs that require a signed agreement to view or use.

**Comment by cra0zy** [comment]
Ah, thanks for the reminder, I probably would have made a mistake there.

**Comment by cra0zy** [comment]
Do any of you have a good example of GamerServices usage in XNA? I do know about API references <a href="https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.gamerservices.aspx">here</a>, but without a good example I'll probably make a mistake in implementation.

**Comment by DDReaper** [comment]
You can give this XNA sample a Try. It's a 16 player network sample with live signin support.
