### ISSUE TITLE
Error while trying to add a reference to another shared code project to Windows 10 project

### ISSUE THREAD

**Issue by esteban-filardi** [MonoGame/MonoGame#5586]
I'm new using MonoGame. I was testing with the example of Xamarin "WalkingGame".

Here's what I did basically:

1. Created a normal C# Class Library called WalkingGame.Shared
2. Added MonoGame.Framework.Portable nuget package
3. Wrote the game code on this project
4. Created the MonoGame Android project
5. Added WalkingGame.Shared project as a reference and adapt code to use it

Until here everything is ok, the Android version compiles using the shared project and it works.

6. Created the Windows 10 MonoGame project
7. Tried to add the WalkingGame.Shared as reference (same as Android)

Here's where I get the error 

> Unable to add reference to project "WalkingGame.Shared"

One more thing, the project that I've created with the shared code is a regular project, not a  Visual Studio "Shared Code" project.

Can someone advice me to make this work?

**Comment by dellis1972** [comment]
I don't think UWP can reference normal C# class libraries it has to use WinRT ones. If you want portable code you should be using either a) Portable Class Library or a b) Shared Project.

**Comment by esteban-filardi** [comment]
Ok thanks ! 
I've changed to a Xamarin PCL and it worked.
Which 
is the preferred way of doing a shared code project ? PCL or "Shared code project"?

Another unrelated question. In the Android application the "character" starts at the top left. In the Windows 10 the character starts at the top right o.O.
I'm guessing that windows uses a left coordinate system that puts the 0 at the top right.

Is there a standard way of handling this?

**Comment by dellis1972** [comment]
I use Shared Projects, but others use PCL. 

You shouldn't see any difference between Android/Windows 10. Can you post your code to gist.github,.com? someone can take a look then.

**Comment by esteban-filardi** [comment]
https://gist.github.com/esteban-filardi/28590a59558f0e3e6ff744d31ba45d2b

**Comment by esteban-filardi** [comment]
Ok, nevermind. It was an issue with the rotation of the screens. For some reason the Windows Phone starts in landscape only, and the android application starts portrait and that confused me. 
Thanks !

**Comment by dellis1972** [comment]
glad you got it working, Closing the issue :)
