### ISSUE TITLE
[DesktopGL] Xbox One S controller mapping missing

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5591]
Hello there,

It has come to our attention that Xbox One S controllers (which are different from the base and elite Xbox One controllers) have wrong mappings on Mac OS.

We managed to get the SDL mapping to add thanks to the help of our players and this tool: http://www.generalarcade.com/gamepadtool/

Here are the missing mapping: 

Wireless (Xbox One S controller are the first Xbox controller to have bluetooth support):
```
5e04000000000000e002000000000000,Xbox Wireless Controller,platform:Mac OS X,x:b2,a:b0,b:b1,y:b3,back:b6,guide:b10,start:b7,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,dpup:h0.1,leftshoulder:b4,lefttrigger:a2,rightshoulder:b5,righttrigger:a5,leftstick:b8,rightstick:b9,leftx:a0,lefty:a1,rightx:a3,righty:a4,
```
Wired:
```
5e04000000000000ea02000000000000,Xbox Wireless Controller,platform:Mac OS X,x:b2,a:b0,b:b1,y:b3,back:b9,guide:b10,start:b8,dpleft:b13,dpdown:b12,dpright:b14,dpup:b11,leftshoulder:b4,lefttrigger:a2,rightshoulder:b5,righttrigger:a5,leftstick:b6,rightstick:b7,leftx:a0,lefty:a1,rightx:a3,righty:a4,
```

I'm currently not able to setup a PR, so I'm just dropping this here as a reminder for futur me (if nobody updates this by then).

**Comment by Jjagg** [comment]
Maybe sync with https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt. Looks like there's a few more controllers added since MG pulled the file.

**Comment by mrhelmut** [comment]
Thanks for reminding me this, the Xbox One S controllers are in the latest database, so I'll pull those changes to MG.
