### ISSUE TITLE
Mouse.GetState() X1Button and X2Button values not updated on Windows

### ISSUE THREAD

**Issue by Metalfusion** [MonoGame/MonoGame#5593]
Having extra buttons is pretty common in mice nowadays, and XNA supported these.
Source of the problem seems to be that the method UpdateMouseState() in WinFormsGameWindow doesn't consider these buttons even though the state is available the same as the other buttons. Fixing this seems trivial, much more so than setting up to make a pull request myself.

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Windows/WinFormsGameWindow.cs#L243

**Comment by Jjagg** [comment]
Fixed in #6418.
