### ISSUE TITLE
Crash when calling Guide on windows universal app

### ISSUE THREAD

**Issue by Mattlekim** [MonoGame/MonoGame#5595]
the is a crash when calling any guide function in windows universal app running windows 10 due to an obsolete call var licenseInformation = CurrentApp.LicenseInformation;

**Comment by Mattlekim** [comment]
I have fixed this on my local branch here are my changes

`@@ -69,10 +69,13 @@ using System.Runtime.Remoting.Messaging;
 #if !(WINDOWS && DIRECTX)
 using Microsoft.Xna.Framework.Net;
 #endif
 #endif
 
+#if WINDOWS_UAP
+using Windows.Services.Store;
+#endif
 #endregion Using clause
 
 namespace Microsoft.Xna.Framework.GamerServices
 {
 
@@ -90,17 +93,24 @@ namespace Microsoft.Xna.Framework.GamerServices
 
         static Guide()
         {
 #if WINDOWS_STOREAPP || WINDOWS_UAP
             _dispatcher = Windows.ApplicationModel.Core.CoreApplication.MainView.CoreWindow.Dispatcher;
-
-
+#endif
+            //Windows UAP does not have currentapp.licenseinformation
+#if WINDOWS_STOREAPP
             var licenseInformation = CurrentApp.LicenseInformation;
             licenseInformation.LicenseChanged += () => isTrialMode = !licenseInformation.IsActive || licenseInformation.IsTrial;
-
-            isTrialMode = !licenseInformation.IsActive || licenseInformation.IsTrial;
+#elif WINDOWS_UAP
+            var contex = StoreContext.GetDefault(); //get contex
+            var task = Task.Run(async () =>
+            {
+                return await contex.GetAppLicenseAsync(); //run the get license task
+            });
+            StoreAppLicense licenseInformation = task.Result; //get the app license
 #endif
+            isTrialMode = !licenseInformation.IsActive || licenseInformation.IsTrial;
         }
 
 		delegate string ShowKeyboardInputDelegate(
          MGXna_Framework.PlayerIndex player,           
          string title,
`

**Comment by Halofreak1990** [comment]
Why hasn't this been fixed, yet? Aside from the redundant Task.Run(), the code looks fine
