### ISSUE TITLE
How to use Joystick on UWP

### ISSUE THREAD

**Issue by StarlightNL** [MonoGame/MonoGame#5597]
Hi all,

I am trying to make a UWP app for Windows 10 Desktop and IoT to controll a robot via a non-xbox and non-gamepad controller. How can I achive this. 
I tried it with the Joystick.GetState but it always returns the same things. Do I need to define the things in the gamepad db? I do want to avoid this because I want to control it using a custom controller build with a Arduino Micro as HID device.

**Comment by cra0zy** [comment]
Ah, sorry about that but Joystick is not implemented right now, reason being is that the API that needs to be used is currently in prerelease state: https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.rawgamecontroller

**Comment by StarlightNL** [comment]
Thanks for the answer. I just need to wait till it is released then.
