### ISSUE TITLE
Fix Texture2D.ValidateParams() for Compressed Formats

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5598]
The current implementation of `Texture2D.ValidateParams()` is broken for compressed formats (likely for all... but in particular PVRTC).  This is a critical issue that needs to be resolve ASAP as it makes MonoGame useless for most game development.

It doesn't consider bits per pixel or that there is a min size for some mip levels.  You can see my findings here:

https://github.com/MonoGame/MonoGame/issues/5557#issuecomment-287682593
https://github.com/MonoGame/MonoGame/issues/5557#issuecomment-287683524

We need to add some specific unit tests for setting/getting data on compressed formats including data on every mip level.

**Comment by tomspilman** [comment]
@Jjagg  @KonajuGames

**Comment by tomspilman** [comment]
Continuing a discussion with @Jjagg from https://github.com/MonoGame/MonoGame/issues/5557#issuecomment-287742618.

> All compression formats are block compression with 4x4 blocks. 

I don't believe that is true.  PVRTC 2bit mode I believe is 8x4.  Not to mention PVRTC has a min size of 8x8 for a mip level when under DXT it is 4x4.

Point is we cannot make assumptions that all compression formats are equal.

**Comment by Jjagg** [comment]
Ah, that explains the issues then.
