### ISSUE TITLE
Purge calls of GL.GenerateMipmap from Texture constructors

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5599]
In `Texture2D` in particular it calls `GL.GenerateMipmap` in some form to fill out the mip map chain.

This is wrong.

`GL.GenerateMipmap` literally means "generate mip maps from the level 0 data now".  It reads each pixel of the level 0 data and filters it down to generate mips.  Depending on the target platform on the CPU or the GPU.

It should be painfully obvious that doing this on a empty texture is a waste of time.

Also you cannot call `GL.GenerateMipmap` on compressed textures as GL will not auto generate mips for compressed formats.  It would require GL to compress the texture at runtime which it does not do.  So currently this fails for compressed formats.

Versions of MonoGame from just 6 months ago didn't call `GL.GenerateMipmap` at all:

https://github.com/MonoGame/MonoGame/blob/5e387fdd658d0f91276a9ac1311b4aff0b5f910e/MonoGame.Framework/Graphics/Texture2D.OpenGL.cs#L109

~~So either A:~~

  - ~~We stop calling `GL.GenerateMipmap` and do nothing for mipmaps on construction (which I don't know is correct).~~

Or B:

 - We correctly define mip levels on a texture by writing a loop and calling `GL.CompressedTexImage2D` or `GL.TexImage2D` for each level.

**Comment by tomspilman** [comment]
@Jjagg @KonajuGames

**Comment by tomspilman** [comment]
I'm actually fairly certain that B is the right path.  We need to be calling `GL.CompressedTexImage2D`/`GL.TexImage2D` for each level on construction.  This ensures a correct texture with the complete mipmap chain is created at construction like we have on all other platforms.

**Comment by KonajuGames** [comment]
Yes, that is correct. B is the right path.

**Comment by KakCAT** [comment]
I think the code to upload mipmaps as you say in 'B' is already working, and all that is needed is removing the Gl.GenerateMipmap call. 

A few days ago when I was trying the issue, removing the call made the mipmaps work, but I was out of time and I couldn't investigate further.

**Comment by tomspilman** [comment]
> I think the code to upload mipmaps as you say in 'B' is already working

No it isn't.  There is no loop in the `PlatformConstructor` code to generate all the mip levels.

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.OpenGL.cs#L74

This is required to correctly construct a texture with mips.

**Comment by KakCAT** [comment]
I just checked it... the code to read the mipmaps is not in the PlatformConstructor but in the Texture2DReader.cs file.

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Content/ContentReaders/Texture2DReader.cs#L72

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Content/ContentReaders/Texture2DReader.cs#L172


I'm talking about the assets read with the Content object. If you're talking about creating a new Texture2D() then you may be right, I haven't explored that path.

**Comment by tomspilman** [comment]
> the code to read the mipmaps is not in the PlatformConstructor but in the Texture2DReader.cs file.

Sure...  I am not speaking of the code to read the data for a mip map from disk and copy it to the texture.

> If you're talking about creating a new Texture2D() then you may be right,

Yes I am speaking of that.  Specifically...
```
// On DirectX correctly returns a blank texture with mipmaps!
// On OpenGL incorrectly returns a blank texture without mipmaps!
var tex = new Texture2D(device, 1024, 1024, true, SurfaceFormat.Color);
```

**Comment by tomspilman** [comment]
Continuing a discussion with @Jjagg from https://github.com/MonoGame/MonoGame/issues/5557#issuecomment-287742618.

> All compression formats are block compression with 4x4 blocks. 

I don't believe that is true.  PVRTC 2bit mode I believe is 8x4.  Not to mention PVRTC has a min size of 8x8 for a mip level when under DXT it is 4x4.

Point is we cannot make assumptions that all compression formats are equal.

**Comment by KonajuGames** [comment]
#5614 fixed this for Texture2D.  Texture3D has no support for mipmaps at this stage.  TextureCube still uses glGenerateMipmaps.  These could be added as separate issues.
