### ISSUE TITLE
[W10/CoreApplication] Game loop doesn't run.

### ISSUE THREAD

**Issue by nkast** [MonoGame/MonoGame#5612]
Probably the bug surface due to the new way of event processing on StoreApps but the root of the problem I believe it to be #2084. The app stays forever in IsActive=false and the game loop doesn't run. 

That's a break from XNA behavior.
Update/Draw should always be called and it's up to the game dev to check Game.IsActive and skip physics , pause the game or whatever.

I suppose we should revert #2084. If there are issues with Suspend and Store certification those should be handled independently of lost of focus & minimize.

**Comment by DDReaper** [comment]
I agree, should revert #2084 as I'm not sure that is resolving the issue what was reported and seems to have unintended consequences

**Comment by nkast** [comment]
closed by #5613
