### ISSUE TITLE
Maximize Windows

### ISSUE THREAD

**Issue by robert-wallis** [MonoGame/MonoGame#5618]
In my 'game' I want to have a maximized window, that is not full-screen.  SDL supports this with `SDL_MaximizeWindow` however the `Sdl` class is `internal` so my Game doesn't have access to it.

So I threaded the function call through GameWindow like this:
https://github.com/robert-wallis/MonoGame/commit/b8e4e06ee34f344bc18c3ec1437f11522ff24dae#diff-c36ddd5c033ea9ae2a05b30e38dfc0a6R159
By adding a new public Maximize(), Minimize() and Restore() function to GameWindow, SDLGameWindow, and the appropriate function pointers inside Sdl.Window.

* Is this something for which I should create a PR? (but finish it up by adding the functionality to the other desktop platforms) 
* Or would it be better to mark `Sdl` as `public` so my Game code can call it directly.

I also have another issue with Windows where a stylus doesn't register as down for a half second.  Which is infuriating. But can be turned off if you have the HWND through some special Win32 API magic.  
* So I had to add the `SDL_GetWindowWMInfo` function pointer, and then add a new HWND property since GameWindow.Handle and SDLGameWindow._handle point to the SDL_Window and not the HWND.  https://github.com/MonoGame/MonoGame/compare/develop...robert-wallis:HWND?expand=0
* Or if I made `Sdl` `public` then I wouldn't have to create the new property.

What kind of PR would you rather see?  I'm new to MonoGame so I'm not sure if it's better to abstract everything and thread functionality through the main classes, or provide a set of public APIs that you can optionally access if you want.

**Comment by cra0zy** [comment]
Sdl class in MG is an incomplete wrapper that is only meant to be used by internals of MonoGame framework. You don't need to even touch it to add a custom maximize function, all you have to do is make your own wrapper function, ie. add this to your Game1.cs and you'll be able to maximize the window:
```c#
private const string SDL = "SDL2.dll";

[DllImport(SDL, CallingConvention = CallingConvention.Cdecl]
public static extern void SDL_MaximizeWindow(IntPtr window);

private void MaximizeWindow()
{
    SDL_MaximizeWindow(Window.Handle);
}
```

> Is this something for which I should create a PR? (but finish it up by adding the functionality to the other desktop platforms)
> Or would it be better to mark Sdl as public so my Game code can call it directly.

Neither.

> So I had to add the SDL_GetWindowWMInfo function pointer, and then add a new HWND property since GameWindow.Handle and SDLGameWindow._handle point to the SDL_Window and not the HWND. https://github.com/MonoGame/MonoGame/compare/develop...robert-wallis:HWND?expand=0

It needs to be SDL handle, on Windows for example you are just translating that to 1 Windows handle, but for Linux for example you have multiple important handles: https://wiki.libsdl.org/SDL_SysWMinfo

**Comment by robert-wallis** [comment]
> Neither.
Ok.  So what is the MonoGame graphics layer, is it more like a collection of frameworks, or more like an abstraction?

Maybe the Windows Pen bug fix should be inside SDL.
