### ISSUE TITLE
Include a default LaunchScreen.storyboard in the iOS template

### ISSUE THREAD

**Issue by richkzad** [MonoGame/MonoGame#5640]
When adding a MonoGame iOS Application to a project, and you run your game on an iPhone 7 Plus (and likely other devices), it doesn't render fullscreen. It looks like the whole thing is being scaled up inappropriately.

A good fix is to add a storyboard to serve as a launch screen. Then iOS realizes the app supports the larger resolutions, and displays you in fullscreen as you likely intend.

It'd be great if MonoGame included one by default, or at least some default such that iOS will render the game fullscreen and the device's native resolution.

**Comment by ryancheung** [comment]
lol, every MG developer want to support iOS comes to this issue...

**Comment by harry-cpp** [comment]
Yea, what a weird iOS issue this is, I'll get it resolved soon.
