### ISSUE TITLE
FontDescriptionProcessor should also check user's local Fonts folder, on Mac

### ISSUE THREAD

**Issue by richkzad** [MonoGame/MonoGame#5644]
FontDescriptionProcessor currently won't pick up any fonts in `~/Library/Fonts`, but it does pick up fonts from `/Library/Fonts`.

When you install fonts on a Mac, I believe it defaults to your local folder, so it's a little confusing that the Content Pipeline doesn't pick it up.

**Comment by harry-cpp** [comment]
This has been fixed.
