### ISSUE TITLE
[Nuget] Keep old packages

### ISSUE THREAD

**Issue by Scellow** [MonoGame/MonoGame#5657]
Hello

Currently, the only version availaible is the latest, that means if you don't have local backup then it is impossible to revert to old version in case something is wrong

I think keeping old versions in the nuget repo is usefull

What do you think ?

**Comment by tomspilman** [comment]
> Currently, the only version availaible is the latest

What package are you looking at?  Looking at all our official nuget packages...

  https://www.nuget.org/profiles/MonoGame

I see older versions for all of them.

**Comment by cra0zy** [comment]
@tomspilman This should probable get closed.

**Comment by Scellow** [comment]
Oops my bad forgot about this issue

Looks like there was something wrong on my end, i can now see all the versions from NuGet
