### ISSUE TITLE
"This MGFX effect is for an older release of MonoGame and needs to be rebuilt" exception

### ISSUE THREAD

**Issue by TN-1** [MonoGame/MonoGame#5666]
So my situation is as follows:  
Code primarily on my desktop, VS2017 Community with MonoGame 3.6.0.1625. Everything builds and runs as expected.  
I am now trying to code on my laptop, Identical setup. VS2017 Community with MonoGame 3.6.0.1625. The code is pulled straight from github, compiled(With 0 errors) and then run, The exception is thrown before the game launches. The only difference is Windows version, My desktop has the creators update and my laptop doesnt. That shouldnt affect it though AFAIK.    
Any thoughts why this is happening and how I can fix it?

**Comment by nkast** [comment]
If you are using 3.6 from git, you also need to install the 3.6 pipeline tools and rebuild the effect.

**Comment by TN-1** [comment]
I installed using the installer from the website on both machines, no
building from source.

**Comment by nkast** [comment]
What code did you pull from github then? 
Did you rebuild the .fx file?

**Comment by TN-1** [comment]
My own code for my game.
Yep, multiple times.

**Comment by TN-1** [comment]
Ok, Allow me to clarify.  
Im using MonoGame 3.6 from the installer on both computers with VS2017 community. I am pulling my game's repo from github, compiling(Successfully) but it throws the above exception before the game launches. Everything(including the .fx files) are being built and rebuilt.

**Comment by TN-1** [comment]
Apologies, The exception was a MonoGame one but the root cause was another package in the solution. Ive got it all sorted now :)
