### ISSUE TITLE
SynchronizeWithVerticalRetrace does not work during game in OpenGL on Windows (ver. 3.6)

### ISSUE THREAD

**Issue by JPCZ44** [MonoGame/MonoGame#5695]
I switch our project to version 3.6 of Monogame (OpenGL on Windows) and i found that GraphicsDeviceManager.SynchronizeWithVerticalRetrace does not work anymore.

It works just on Initialization state - there I can set SynchronizeWithVerticalRetrace successfully, but when I am trying switch synchronisation during the game - nothing happened. I am calling GraphicsDeviceManager.ApplyChanges() but it stay unchanged.

In old version 3.5 it works properly.

**Comment by mrhelmut** [comment]
Do you happen to be on Windows 10?

There is known issue in the window composing of Windows 10 with OpenGL: it overrides VSync, no matter the setting (being borderless or real fullscreen mode) or the graphics driver configuration, VSync is always off. There's no known workaround.

If you're not on Windows 10, then it may be a MonoGame issue.

**Comment by JPCZ44** [comment]
I have Windows 10, but same behavior is on Windows 7 (tested on another computer). Previous version of MonoGame (3.5.1) hasn't this issue.  And when i set SynchronizeWithVerticalRetrace in Initialize() method it works, but I am unable to change it later in game... (It is needed because user wants to change it from Optionsmenu etc.)

**Comment by mrhelmut** [comment]
So, it's not that it doesn't work, it's that it works but cannot be changed at runtime?

Summoning @cra0zy. Isn't this a limitation about VSync support being linked to window creation with SDL?

**Comment by cra0zy** [comment]
> Isn't this a limitation about VSync support being linked to window creation with SDL?

I don't think it is, looking at the our source we either forgot to implement it or someone removed it (The needed wrapper is there: https://github.com/MonoGame/MonoGame/blob/1a7d0abf70b09449f507e474a5f87cc7a83ee37a/MonoGame.Framework/SDL/SDL2.cs#L482 but never called).

**Comment by JPCZ44** [comment]
So, guys - what is your advice? :) I can wait to your fix - no problem now (release date of Jets'n'Guns 2 is too far). But will be good to fix this issue, because it is necessary feature to be able switching vsync during the game. Thank you very much for your time!

**Comment by Jjagg** [comment]
@KonajuGames This was fixed in #5862 :)

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
