### ISSUE TITLE
Add a new label for beginning contributors

### ISSUE THREAD

**Issue by theweekendgeek** [MonoGame/MonoGame#5696]
I've seen this on other projects on gihub and I think it could help encourage contribution to the project. At least that is the case for me.
I would be interested in contributing to MonoGame but since my C#-Skills are still a bit limited and so is my time. It would be helpful if I could more easily identify issues that require less knowledge of MonoGame.

A label like "beginner friedly" or "for beginners" could very much help with that. As it stands now I woud have to scan through all the issues (at least the ones with "help wanted") and then start looking at the corresponding postitions in the code. If I'm lucky I might find something that I feel comfortable working on, if I'm not I have to start that process over. And all of that takes some time.

Working in issues that require less initial knowledge could also help increase my knowledge of C# and MonoGame in general so over time it would be possible to tackle bigger problems. 

edit: I should propbably add that I'm not really used to working with labels myself, so if this is actually a thing with the people creating issues then it would be nice if use of such a label, where appropriate, would be encouraged.

**Comment by Jjagg** [comment]
I agree. When I started contributing I had the same problem. I didn't really know where to start and had to put in effort to first find issues I could handle, which can discourage people to actually help. When you don't know about the codebase it can be hard to tell how difficult an issue is to solve. If we had labels for difficulty or just a 'beginner' label that would make it easier for people to identify the low-hanging fruit and start contributing.

**Comment by tomspilman** [comment]
The problem here is the time of myself and other project leads is limited as well.

Reviewing each issue and deciding if it is "for beginners" is tricky...  what is easy for me is not easy for others.  Most often we fix the really easy things ourselves when we see them.

Second I don't think we have all that much easy stuff to do.  Most of the stuff we have are technical issues that require some knowledge of the platforms and APIs we're working with.  If you don't have that knowledge and don't have the time to learn it... it will be difficult do make meaningful contributions.

Now maybe i'm setting the bar too low on what is easy here... but that is part of my point.

> I've seen this on other projects on gihub 

Can you point out a few for me so I can take a look?

**Comment by theweekendgeek** [comment]
> Can you point out a few for me so I can take a look?
I can not really remember where I saw it recently but I looked around and found a few:

https://github.com/elastic/elasticsearch/labels/low%20hanging%20fruit
https://github.com/moment/moment/labels/Up-For-Grabs
https://github.com/neovim/neovim/labels/entry-level
https://github.com/moby/moby/labels/exp%2Fbeginner
https://github.com/phpmyadmin/phpmyadmin/labels/newbie
https://github.com/python-babel/babel/labels/difficulty%2Flow

I got these from here, there are a lot more: 

https://github.com/MunGell/awesome-for-beginners

I surely know of limited time, thats the problem I have myself. And also that it would be difficult to decide what is easy, what isn't.
If it is so, that the easy stuff gets fixed quickly by the core maintainers then you are right, that to make meaningful contributions one would have to familiarize oneself more with the API's and platforms.
I'm not saying that I don't have the time to actually learn that. But I think it could make things easier if issues could be easier identified that might require less knowledge.

I am very well used to the "learning on the job" approach and I think I could do the same for contributions to MonoGame. I just think that a label identifying issues that require a bit less knowledge of the inner workings of MonoGame could speed these things up or at least make it more inviting to newcomers.
As it is right now, I will probably at some point start contributing the Project whether such a label exists or not. But I will probably need some more time, identifying issues I am able to fix or try a few, hit a brick wall, and repeat until I find something that I can solve.

I don't think the bar actually has to be that low. But for example, and I am guessing here, it could be easier to start on something that includes the content pipeline or it's UI instead of something that might include drivers etc. 
It could also be just something like documentation that needs updating and that you and others don't really find the time for.

**Comment by tomspilman** [comment]
>  I will probably need some more time, identifying issues I am able to fix or try a few, hit a brick wall, and repeat until I find something that I can solve.

I think regardless of a label this is the experience everyone has contributing to a new project.


> It could also be just something like documentation 

Actually that has proven to be the worst thing to have beginners do.  It results in completely useless documentation that parrots the function name rather than give insight into what the function does.  People writing docs...  like any other writing...  should have to have deep knowledge of the subject matter for it to be useful.

**Comment by theweekendgeek** [comment]
Ok I see. Well It's of course ok if you decide against such a label. 
I just thought I'd share why I thought it might be useful and I'd wish for something like that to exist. The way I see it you already, in a way, look at issues. So you might not need to review things completely to give an educated guess as to how hard it might be to fix or implement. I don't really think it would take much away, bit I might be wrong.
I totally get what you're saying with the docs, though.

**Comment by Jjagg** [comment]
We have the "Good First Issue" label, just need to get used to using it and add it to existing issues.
