### ISSUE TITLE
SharpDX.SharpDXException when loading SM4.0 (or higher) Effect with Reach-Profile

### ISSUE THREAD

**Issue by aharabada** [MonoGame/MonoGame#5699]
It seems like the default GraphicsProfile is set to Reach now instead of HiDef. Which is fine, but because I didn't know this I tried to load an SM5.0-Effect with the Reach-Profile and got the following exception:

> SharpDX.SharpDXException: "HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid > Arguments], Message: Falscher Parameter.
> 
> "

This exception is thrown in the "CreatePixelShader"-Function of the "Shader"-Class and because this exception isn't really helpful I think that:

- The Pipeline-Tool should throw an error if someone tries to compile an effect with SM4.0 (or higher) when the GraphicsProfile is set to Reach.
- MonoGame should throw an exception that tells the user to either use the HiDef-Profile or compile his effect with SM4.0-level 9.3

**Comment by tomspilman** [comment]
> The Pipeline-Tool should throw an error if someone tries to compile an effect with SM4.0 (or higher) when the GraphicsProfile is set to Reach.

That should be doable but would take a little effort passing the graphics profile down into the effect compiler code.

> MonoGame should throw an exception that tells the user to either use the HiDef-Profile or compile his effect with SM4.0-level 9.3

This should be doable as well.  Unfortunately we only get a generic `SharpDXException/E_INVALIDARG` error, so we will be taking a bit of a guess if that is the actual problem.  

Still any message we have will be better than what we have now.

**Comment by Jjagg** [comment]
Closing in favor of #5108.
