### ISSUE TITLE
iTunes Connect rejects Mac binary due to QTKit dependency

### ISSUE THREAD

**Issue by dtaylorus** [MonoGame/MonoGame#5701]
My Mac App Store submission was rejected with the following response from iTunes Connect:

> **Deprecated API Usage** - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs.

I don't have any references to QuickTime in my project, so I assume this comes from a MonoGame dependency?

I'm using the MonoGame DesktopGL framework with native references to sdl2 and openal.

If this is a MonoGame issue, some guidance as to how to build a game that can pass the Mac App Store submission criteria would be appreciated.

Thanks!
-David

**Comment by tomspilman** [comment]
@dellis1972 @mrhelmut @cra0zy ?

**Comment by cra0zy** [comment]
We are currently using `QTMovieView` instead of `AVPlayerView` to play videos on Mac. 

PS. I can't help with fixing this since the only macOS I have is in a VM, and it does not like working with GL stuff.

**Comment by tomspilman** [comment]
> We are currently using `QTMovieView` instead of `AVPlayerView` to play videos on Mac.

This seems like the possible culprit here.

@dtaylorus - Are you using the video player?  If not can you remove it from your project and see if the issue goes away?

**Comment by dtaylorus** [comment]
@tomspilman I'm not using the video player.

Just to clarify, are you saying I should do my own build of the MonoGame binaries and remove all of the QTKit references?

Or is there some way to remove these references without a custom build?

Thanks!

**Comment by dellis1972** [comment]
@dtaylorus are you using the Xamarin.Mac dll or the DesktopGL one? The DesktopGL should not contain any references to QTKit since its only the Xamarin.Mac video player that uses it. You can ship DesktopGL stuff on the Mac store because I have done that myself.

Also are you on MonoGame 3.6? 

No idea why but if I reply to this thread via email , they are not showing up :/

**Comment by cra0zy** [comment]
@dellis1972 Should we maybe completely drop the MonoMac/Xamarin.Mac platforms if DesktopGL works for store?

**Comment by dellis1972** [comment]
We can't really since users (and we) might want/need to be able to use Mac
specific features like Game centre etc via Xamarin.Mac. That said the
branch which removes OpenTK basically makes things allot better. So the
sooner we can get 3.6.1 out and get that merged and tested the better
things will get.

I'll look at unifying the Mac/iOS video players this week. In theory they
should be able to use the same code now.

**Comment by cra0zy** [comment]
> specific features like Game centre etc

Since I don't know too much about Mac, why couldn't it be used with DesktopGL?

**Comment by mrhelmut** [comment]
Aren't GameKit features out of the scope of MonoGame? (just asking, but I do understand well that having Xamarin.Mac support still is quite useful in that regard since Xamarin.Mac is the only option to access GameKit API because there is no open source binding for GameKit).

**Comment by dellis1972** [comment]
We currently use Game Centre stuff for GamerServices etc, plus the video
player needs Xamarin.Mac. I'd prefer to keep it about. The OpenTKRemoval
branch does unify DesktopGL and MacOS quite a bit. But still having a
project that is built against Xamarin.Mac is very useful.

Getting back on topic I'll try to take a look at this.

**Comment by dtaylorus** [comment]
@dellis1972 I'm using the DesktopGL version of MonoGame 3.6. Specifically, the binaries that come with the 3.6 installer, not the binaries from NuGet.

What are your compile settings? Specifically, what version of the .NET Framework, and what linker settings?

Good to know you've shipped in the Mac Store!

**Comment by iamthefaker** [comment]
I think this might help.

![image](https://cloud.githubusercontent.com/assets/4160801/26057843/2f6eb5ee-3973-11e7-9b69-7034f37254e4.png)

**Comment by dtaylorus** [comment]
@dellis1972 Can you please share the build settings you used to submit to the Mac Store?

I've tried every combination I can think of and there's still some QTKit reference I can't eliminate.

Also, I'm unable to link any assemblies. Even linking SDK assemblies only results in a build failure related to System.Drawing.

I sure would appreciate knowing your secret to shipping a MonoGame app in the Mac Store!

**Comment by dellis1972** [comment]
I didn't use the Xamarin.Mac project (which it looks like you are using). I
used a Cross Platform project (Desktop GL) then built the .app package from
that using Monokickstart.
I have a tool (in development) which might help you generate the .app
package for a DesktopGL project, but you will have to sign it etc yourself
manually using the Xcode tooling.

**Comment by dtaylorus** [comment]
@iamthefaker Thank you! I can confirm that with the --registrar:dynamic switch, the app passes Mac Store validation tests and with no other change, removing the switch causes validation to fail with the deprecated QTKit reference.

So as you said, it seems this is a Xamarin issue, not a MonoGame issue.

**Comment by iamthefaker** [comment]
--registrar:dynamic
doesn't seem to work anymore.
Now running VS for Mac and latest builds of Xamarin.mac and so on.
And the QTKit dependency rejection has come back, regardless of trying a number of different
mmp arguments.

As per:
https://forums.xamarin.com/discussion/101776/apple-no-longer-accepts-submissions-of-apps-that-use-quicktime-or-qtkit-apis

**Comment by dtaylorus** [comment]
I'm having the same problem. I cannot find any combination of build settings that will pass certification anymore. Also getting linker errors for any type of linking.

________________________________

**Comment by iamthefaker** [comment]
It looks like Chris Hamons' (from Xamarin) comment on 20th October may be the key here.
https://forums.xamarin.com/discussion/comment/302820/#Comment_302820
Quote:
- Fundamentally you are in a broken position, one of your dependencies is not fully loadable.
- The nature of the JIT is letting you get away with that, but it breaks all forms of linking.
- Xamarin.Mac has bindings to QTKit that we can't remove until the next API break (if it occurs)
- Linking is the way to remove the bindings you don't use
- Until you fix the dependency, either by recompiling it, removing it, or hiding it's usage, you can't link.

**Comment by dellis1972** [comment]
This was merged into develop a while back https://github.com/MonoGame/MonoGame/pull/5942

It removes our dependency on QTKit. So if you are using the 'development' version I have no idea where this QTKit dependency is coming from.

**Comment by dtaylorus** [comment]
The QTKit rejection problem is due to the fact that Xamarin.Mac has a dependency on QTKit that cannot be removed according to Xamarin, so that isn’t a MonoGame issue.

However, now that --register:dynamic no longer works, the only way to resolve the Xamarin QTKit issue is by linking, and the MonoGame.Framework.dll dependency causes the linker to fail, even if you choose “Link SDK assemblies only”.

So, it seems there is no way to get MonoGame into the Mac store anymore.

________________________________

**Comment by dellis1972** [comment]
@dtaylorus do you have a DesktopGL app? If so as long as you are not using any Xamarin.Mac API's you can ship that. Its just a question of packaging.

I have a nuget in alpha [1] which will generate a Mac .app package for you and use https://github.com/MonoGame/MonoKickstart.

To use Build your DesktopGL app in release mode then (on a Mac)

`msbuild <project> /p:Configuration=Release /t:BuildGamePackage /p:PackageTargetPlatforms=MacOS`

You should get a .app package in your output directory. 

Note it is still in development so if you have any unusual content stuff (i.e the content is not in a "Content" directory) it might no package everything. But please contact me on Gitter if you want help.
[1] https://www.nuget.org/packages/InfinitespaceStudios.MonoGame.Packaging/0.0.6-alpha

**Comment by dellis1972** [comment]
@dtaylorus you will need to manually sign the package and create a .pkg but that is documented on the apple developers site.

**Comment by dtaylorus** [comment]
Thanks, Dean! I'll give it a try.

________________________________
