### ISSUE TITLE
Android: restoration of an activity fails after Game.Exit (v 3.6.0.1625)

### ISSUE THREAD

**Issue by asyschikov** [MonoGame/MonoGame#5702]
I pulled the sample game https://github.com/MonoGame/MonoGame.Samples/tree/develop/Platformer2D

Updated Monogame to the latest (3.6.0.1625) and suddenly I noticed the nasty effect if I click Back (calls `Game.Exit`) and then click app icon, it can't restore the game. It seems to work in "3.4.0.359"

That's what application output is showing:
```
[AppTracker] App Event: start
[MonoGame] MonoGameAndroidGameView.SurfaceCreated: surfaceFrame = Rect(0, 0 - 1920, 1080)
[MonoGame] GraphicsDeviceManager.ResetClientBounds: newClientBounds={X:0 Y:0 Width:1920 Height:1080}
[MonoGame] MonoGameAndroidGameView.SurfaceChanged: format = Rgb565, width = 1920, height = 1080
[MonoGame] GraphicsDeviceManager.ResetClientBounds: newClientBounds={X:0 Y:0 Width:1920 Height:1080}
[AppTracker] App Event: stop
[MonoGame] MonoGameAndroidGameView.SurfaceDestroyed
```

My Android is 7.1.1

**Comment by nebosite** [comment]
I'm noticing the same problem:

1) Create a vanilla Android Project
2) Run on phone
3) Hit back button
4) Notice that the app still shows up as an active app.  (Expected: the app should be completely shut down and missing from this list.)
5) Try to re-activate the app
Result: app comes up and renders one frame, then Deactivates immediately.

**Comment by KonajuGames** [comment]
The first issue is that your expectation that apps should terminate is
incorrect. Apps on Android consist of two parts: the price and the
activity.  When you press the Back button, the activity is closed, but the
process remains.  It is the process that you see in the apps list.  This to
allow quick resuming of the app when the user switches to it again. This
involves the process being brought back to the foreground and the activity
being recreated.  It's the responsibility of the OS to
terminate processes when memory gets low.

The second issue is the activity appears to be crashing soon after it is
recreated. That is something to look into.

**Comment by asyschikov** [comment]
@KonajuGames not sure to whom you replied, me or nebosite, but I didn't imply that the process should be killed. On the opposite, the problem is that when the activity is closed, the process lives (as intended) but the activity fails to restore. I tried it on the emulator, with different projects (including the official sample) and the only determining factor is MonoGame version (3.6), the problem seems very consistent.

**Comment by KonajuGames** [comment]
About the process was in reply to @nebosite.  It would seem there is an activity restoration issue to be resolved here.

**Comment by AndreCL** [comment]
This is still an issue. See http://community.monogame.net/t/problem-with-resuming-after-back-button-from-android-device/9111/9 for a temporary solution

**Comment by Timmeey86** [comment]
Still relevant with MonoGame 3.7.1 / Android 8.1 / Visual Studio 2017, both for the Android emulator and a physical device (I haven't tested other combinations). I can confirm the workaround with `Game.Activity.MoveTaskToBack(true);` rather than `Exit()` works.
Would it maybe be a good idea to change the default Android example in the Visual Studio project templates at least until this is fixed (if ever)?

**Comment by ryancheung** [comment]
bump
