### ISSUE TITLE
Type.GetTypeInfo() is Net 4.5+

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5716]
I just noticed that ```Type.GetTypeInfo()``` is an extension method only present since .Net 4.5.

This change breaks the compatibility with .Net 4.0: https://github.com/MonoGame/MonoGame/commit/e3261f71c780c7b8294a42a9e3f36efd447f439d#diff-51a9663b2b82c89eb208960d5902e904R38

Having a .Net 4.0 compatibility is interesting for Windows XP support.

According to the Steam hardware survey, Windows XP still represents about 1% of players. http://store.steampowered.com/hwsurvey/

Is this something we should care about or should we move forward?

I would be fine with moving forward, since Microsoft doesn't support the OS anymore and that the OpenGL 3.0 requirement for DesktopGL represents a way bigger barrier (most XP machines don't even support it anyway).

@tomspilman @KonajuGames @cra0zy

**Comment by tomspilman** [comment]
> Is this something we should care about or should we move forward?

1% of players makes it seem very unimportant to me.  Still the fix to keep 4.0 compatibility isn't very hard.  In fact we have an few extension methods for dealing with this from the WinRT work:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Utilities/ReflectionHelpers.cs

Maybe we should fix this and keep 4.0 support for longer if it is easy like this.

Also maybe that code shouldn't be `#if WINRT` and instead something to do with the current .NET version.

**Comment by cra0zy** [comment]
I did submit a PR to move to GetTypeInfo: #5607, I did it since we need to use that part of the code on .net core.

That being said I don't think its worth supporting .Net 4.0, there really isn't a good up side to it.

**Comment by tomspilman** [comment]
> That being said I don't think its worth supporting .Net 4.0, there really isn't a good up side to it.

My only concern is disrupting work on consoles.  I need get some time to check that all our console platforms can support 4.5 fine and if not see about fixing that.

**Comment by cra0zy** [comment]
> My only concern is disrupting work on consoles. I need get some time to check that all our console platforms can support 4.5 fine and if not see about fixing that.

That is a valid concern, if they can't do mention in here and I'll update #5607 with `#if NET4` preprocessor params.

**Comment by tomspilman** [comment]
> if they can't do mention in here

I'm sure they can...  it is just a matter of fixing it which I have to find time to fit in.

IMO to immediately move forward with .NET Core and fix this issue for @mrhelmut is to move to `#if NET4` or maybe a partial class technique.

**Comment by cra0zy** [comment]
There are some other issues with .NET Core support (NVorbis, System.Drawing) so we don't need to rush with this until they are addressed.

**Comment by tomspilman** [comment]
> so we don't need to rush with this until they are addressed.

Ok... just be aware me finding time to test it fix this might mean 2 or 3 months.

**Comment by cra0zy** [comment]
Thats fine.

Side note, we will need to provide MGCB in nuget form as well for proper .net core support (vscode c# extension for example provides its own msbuild so it's not using system msbuild extensions, MonoDevelop on Linux from flatpak can't access system stuff, Rider also provides its own msbuild).

**Comment by mrhelmut** [comment]
Ah, consoles... better sticking to NET4 for now then.
There's no immediate rush I believe, the only direct concern is that DesktopGL has a 4.5 requirement, which in itself won't impact other platforms requirements.

**Comment by mrhelmut** [comment]
Is there anything I can do to help here?

**Comment by tomspilman** [comment]
@mrhelmut - If you wanted to fix our `GetTypeInfo` helper...

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Utilities/ReflectionHelpers.cs

To check for `#if NET4` I would be good with that.  The problem is that `NET4` isn't like something the compiler pre-defines... in fact the compiler just compiles against assemblies, it doesn't know what net version it is.

Or if you just want to #if the one problematic line of code i'm good with that too.

Just not sure how best to fix it.

**Comment by mrhelmut** [comment]
If protobuild supports it, we can add a custom constant such as this one in project files:

```
    <PropertyGroup>
        <DefineConstants Condition="$([System.Version]::Parse('$(TargetFrameworkVersion.Substring(1))').CompareTo($([System.Version]::Parse('4.0'))))   &gt;= 0">$(DefineConstants);NET4</DefineConstants>
    </PropertyGroup>
```

**Comment by mrhelmut** [comment]
Here it is #5732

I tried to apply these changes to #5607

Let me know what you think of this approach.
