### ISSUE TITLE
SoundEffect.DistanceScale does not work under OpenAL

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5717]
The `SoundEffect.DistanceScale` global is correctly set under XAudio platforms:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.XAudio.cs#L41

But it is totally unused under OpenAL:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.OpenAL.cs#L72

This breaks games causing sounds to be too loud or totally silent.

**Comment by tomspilman** [comment]
Looks like `SoundEffect.DopplerScale` is broken in the same way too.

**Comment by Jjagg** [comment]
I'm taking this!

Relevant X3DAUDIO docs: https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.x3daudio.x3daudio_emitter%28v=vs.85%29.aspx
OpenAL docs: https://www.openal.org/documentation/OpenAL_Programmers_Guide.pdf

I read those and it looks like we just need to set the DistanceModel to InverseDistanceClamped and set the ReferenceDistance to SoundEffect.DistanceScale. We might also need to set AL_MAX_DISTANCE if it's not infinite by default (docs don't mention it, but I think it is).
For the Doppler scale we can use alDopplerFactor. Easy!
