### ISSUE TITLE
Monogame.Framework.WindowsUniversal should not include SharpDX assembly binaries

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#5726]
I am having conflicts trying to use Monogame.Framework.WindowsUniversal, I'm getting this error:
```
Payload contains two or more files with the same destination path 'SharpDX.Direct3D11.dll'. Source files:
....MonoGame.Framework.WindowsUniversal\3.6.0.1625\lib\netcore\SharpDX.Direct3D11.dll
....SharpDX.Direct3D11\3.0.0\lib\portable-net45+netcore45+wpa81+MonoAndroid1+MonoTouch1\SharpDX.Direct3D11.dll
```
What I noticed is that `Monogame.Framework.WindowsUniversal` is including SharpDX binary assemblies directly!?

```
<files>
        <file src="WindowsUniversal\AnyCPU\Release\Themes\generic.xbf" target="lib\netcore\MonoGame.Framework\Themes\generic.xbf" />
        <file src="WindowsUniversal\AnyCPU\Release\MonoGame.Framework.dll" target="lib\netcore\MonoGame.Framework.dll" />
        <file src="WindowsUniversal\AnyCPU\Release\MonoGame.Framework.xml" target="lib\netcore\MonoGame.Framework.xml" />
        <file src="WindowsUniversal\AnyCPU\Release\MonoGame.Framework.pri" target="lib\netcore\MonoGame.Framework.pri" />
        <file src="WindowsUniversal\AnyCPU\Release\MonoGame.Framework.xr.xml" target="lib\netcore\MonoGame.Framework\MonoGame.Framework.xr.xml" />

        <!-- should remove these references -->
        <file src="WindowsUniversal\AnyCPU\Release\SharpDX.Direct2D1.dll" target="lib\netcore\SharpDX.Direct2D1.dll" />
        <file src="WindowsUniversal\AnyCPU\Release\SharpDX.Direct3D11.dll" target="lib\netcore\SharpDX.Direct3D11.dll" />
        <file src="WindowsUniversal\AnyCPU\Release\SharpDX.dll" target="lib\netcore\SharpDX.dll" />
        <file src="WindowsUniversal\AnyCPU\Release\SharpDX.DXGI.dll" target="lib\netcore\SharpDX.DXGI.dll" />
        <file src="WindowsUniversal\AnyCPU\Release\SharpDX.MediaFoundation.dll" target="lib\netcore\SharpDX.MediaFoundation.dll" />
        <file src="WindowsUniversal\AnyCPU\Release\SharpDX.XAudio2.dll" target="lib\netcore\SharpDX.XAudio2.dll" />

        <file src="..\..\NuGetPackages\readme\MonoGame.Framework\readme.txt" target="readme.txt" />
    </files>
```

This is wrong, when a nuget package has references to assemblies also available as NuGet packages, it should not include the assembly binaries. Instead, it should let NuGet resolve the references.

**Comment by DDReaper** [comment]
This was originally because MonoGame was tied to a specific version of SharpDX, which may no longer be the case.

Thoughts @tomspilman @dellis1972 @KonajuGames @tgjones . Should we start using the release version of SharpDX?

**Comment by tomspilman** [comment]
@DDReaper - I'm fine with using the latest SharpDX as long as things are compatible.

We could also see about updating the version of SharpDX we have in our dependencies:

https://github.com/MonoGame/MonoGame.Dependencies/tree/master/SharpDX

**Comment by vpenades** [comment]
Well, my point was not only about updating SharpDx to a newer version, but also to stop including the binaries explicitly. Instead it should reference the appropiate version of SharpDX nugets.

**Comment by tomspilman** [comment]
> Instead it should reference the appropiate version of SharpDX nugets.

If you mean our Windows installer package should depend on NuGet...  no we will never do that.

If you mean the GitHub repo and automated build process should depend on NuGet...  we won't ever do that either.

But our NuGet packages should certainly always depend on other NuGet packages and not bundle its own version of SharpDX.

**Comment by vpenades** [comment]
Yes, I mean the third option:

> But our NuGet packages should certainly always depend on other NuGet packages and not bundle its own version of SharpDX

 :smile:

**Comment by DDReaper** [comment]
In which case, I'll look to creating a pr to sort that then

**Comment by DDReaper** [comment]
Submitted #5748 to remove SharpDX dll's from NuGets and replaced with dependancies

**Comment by vpenades** [comment]
Just created a test project pulling MonoGame.Framework.WindowsDX 3.7.0.499-develop NuGet package.

It correctly pulls SharpDx 3.0.0.0 Nuget Packages.

But upon execution, it throws a FileLoadException on SharpDx , because it's still looking for 2.6.3.

It's not enough to replace SharpDx 2.6.3 with 3.0.0 at NuSpec level;  the Monogame.Framework project also needs to target SharpDX 3.0.0

**Comment by DDReaper** [comment]
I've tested these repeatedly on all 3 DX platforms and it runs here fine.

Did you remove the original MG references prior to adding the NuGet's.  Saying that though, I have installed Nuget over MG templates without issue.

AFAIK, There are no hard dependencies on any specific version of SharpDX.

I'll try uninstalling MG and try the old MSI releases and see if there is any old conflicts

**Comment by vpenades** [comment]
@DDReaper that's really weird... maybe what you're trying locally is not what's reaching the dev stream?

Yes, I've removed all MG references, and the only dependency is:

```
<ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX">
      <Version>3.7.0.499-develop</Version>
    </PackageReference>
  </ItemGroup>
```

It compiles, and in the binaries, I've verified SharpDx version is 3.0.0 and Monogame.Framework is 3.7.0.499, but when running, it still asks for SDX 2.6.3

**Comment by DDReaper** [comment]
I'm simply using a brand new project and then pulling the NuGet (499) from the MG dev NuGet stream.

**Comment by vpenades** [comment]
It seems same thing as what I did... 

I've just opened a private on gitter to discuss... if you can

**Comment by DDReaper** [comment]
Any further issues with SharpDX being downgraded for GL?
I've tested again with the latest and found no issues I can see.
