### ISSUE TITLE
Fails to load `Song` content on macOS (DataUnavailable)

### ISSUE THREAD

**Issue by darfink** [MonoGame/MonoGame#5730]
I've been having issues loading a `Song` resource on macOS, using the content pipeline. I have tried using several different source audio and types (`wav`, `ogg`, `mp3`), different qualities (`Low`, `Medium`, `Best`), different platforms (`DesktopGL`, `MacOSX`), and last but not least, different MonoGame versions (`3.6.0.1625` and develop branch `3.7.0.379`).

The issue stems from the [PlatformLoadAudioStream#L71-L94](https://github.com/MonoGame/MonoGame/blob/9b199ee849c3a2cc7f7c35ddbd27e302a1099cf6/MonoGame.Framework/Audio/SoundEffect.OpenAL.cs#L71-L94) method. The `audiodata` variable itself seems to contain the correct content, judging by its size and that it contains the magic cookie for `m4a` format (the converted file from the pipeline).

The `AudioFileStream` object though, is completely blank with only `LastError` set to `DataUnavailable`.

<img src="https://cloud.githubusercontent.com/assets/1612390/26342234/82dcef8c-3f97-11e7-886a-76f7c543f71c.png" align="left" width="200" >

When the properties from the `afs` object are used, the code throws a [`DivideByZeroException`](https://github.com/MonoGame/MonoGame/blob/9b199ee849c3a2cc7f7c35ddbd27e302a1099cf6/MonoGame.Framework/Audio/SoundEffect.OpenAL.cs#L87), since the sample rate, bits per channel, channels per frame etc are all set to `0` / `null`.

Further investigation shows that the `DataUnavailable` error is directly mapped to [`kAudioFileStreamError_DataUnavailable`](https://developer.apple.com/reference/audiotoolbox/kaudiofilestreamerror_dataunavailable), with the description:

> The amount of data provided to the parser was insufficient to produce any result.

This is where I got stuck, since the `audiodata` is correct from what I can tell (e.g the size is `973820`, same as the file on disk, it has the magic cookie etc). Is there anyone else experiencing this or can aid me in my debugging?

- Running on macOS 10.12.4, MonoGame `3.7.0.379`.
- The generated `m4a` file can be played with every media player I have tried.

**Comment by harry-cpp** [comment]
Mac platform has been replaced by DesktopGL, so this is technically fixed.
