### ISSUE TITLE
SoundEffectInstance doesn't play

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#5742]
I created a new MonoGame.Windows (SharpDx) project,  loaded "blast_mono.wav" into a SounfEffect, and when trying to play the sound, I only get silence.

Same example in WindowsGL works correctly.

After some research, I found that SharpDX.XAudio2 [constructor](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffect.XAudio.cs#L119) was throwing an exception with the following message:

`HRESULT: [0x80040154], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unregistered Class`

I tried to find a solution using the SharpDX currently used by monogame without success.

Then I followed the next steps:

I upgraded MonoGame.Framework.Windows to SharpDx 4.0
Upon compiling it gave 3 or 4 errors very easy to fix (RawBool instead of Bool and a missing argument in Reberb)
After compiling and running again, it gives more initialization exceptions, but this time in the [MasteringVoice](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffect.XAudio.cs#L134) , apparently, it doesn't like being passed a deviceID = 0
I removed the last three arguments, and left the constructor as `new MasteringVoice(Device);`

Compiled again, and it worked!, sound was playing!

So in order to fix the problem, it's a matter of upgrading to SharpDX 4.0  and adjusting the MasteringVoice constructor.

Btw, I tried removing deviceId argument from MasteringVolume with SharpDX 2.6.3 but it didn't work. Given that SharpDX 4.0 is a significant milestone and it seems there's no big hurdles upgrading monogame to SharpDX, I would ask to consider upgrading soon.

**Comment by Jjagg** [comment]
There's an open issue specifically for upgrading SharpDX #3794.

I have a branch that upgrades the SharpDX version to 3.1 (the latest version at the time), but I ran into issues with the D3D compiler so I didn't set up a PR back then. If someone implements the upgrade to 4.0 some of the fixes from that branch can probably be used. Branch is at https://github.com/Jjagg/MonoGame/tree/dx31

**Comment by vpenades** [comment]
which sort of D3D compiler issues you had? as far as I know, the compiler is only used in the pipeline processor, right?

**Comment by Jjagg** [comment]
Compilation just failed with some error that didn't help much. I don't really remember what error exactly. Yes, the compiler is only used by 2MGFX, the MonoGame effect compiler.

**Comment by Jjagg** [comment]
Woops, didn't mean to autoclose this. @vpenades Can you test that #5825 fixed your issue?

**Comment by vpenades** [comment]
Problem solved on MonoGame 3.7.0.647!

**Comment by hejoy91** [comment]
> Problem solved on MonoGame 3.7.0.647!

@vpenades vpenades  why my monogame3.7.1.189 for vs sdk still has this problem。load wav file wth soundeffect，and nothing happens，but xna gamestudio4.0 goes well。。

**Comment by vpenades** [comment]
@hejoy91 are you processing the audio effect through the content pipeline, or are you loading the wav directly?  without more detailed information I can't tell what the problem might be...

**Comment by hejoy91** [comment]
@vpenades yes i use  the content pipeline with xnb file，here is my code，
`protected override void LoadContent()
        {
            // Create a new SpriteBatch, which can be used to draw textures.
            spriteBatch = new SpriteBatch(GraphicsDevice);
            SoundEffect se = Content.Load<SoundEffect>("Thunder");
            se.Play();
            // TODO: use this.Content to load your game content here
        }`
this is the basic code，in monogame nothing happens，but xna gamestudio4.0 goes well。

**Comment by vpenades** [comment]
@hejoy91 I am not sure why this happens. I am using the same version and the audio works fine.

Maybe something you can try is to downsample the audio to 22050Hz mono, and see if it can play it.

**Comment by hejoy91** [comment]
sorry，i choose the 22050hz wav file，and load the xnb，but it still doesn't work。my monogame for vs version：3.7.1.189，and i send the wav file to you，can you help me to try it。：)



&nbsp;怀念夏天的味道。。
 &nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ——风


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Vicente Penades"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 下午4:18
收件人:&nbsp;"MonoGame/MonoGame"<MonoGame@noreply.github.com&gt;;
抄送:&nbsp;""<hejoy91@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MonoGame/MonoGame] SoundEffectInstance doesn't play (#5742)




@hejoy91 I am not sure why this happens. I am using the same version and the audio works fine.
 
Maybe something you can try is to downsample the audio to 22050Hz mono, and see if it can play it.

**Comment by hejoy91** [comment]
@vpenades sorry，i choose the 22050hz wav file，and load the xnb，but it still doesn't work。my monogame for vs version：3.7.1.189，and 3.6 version has the same problem, is it related to DirectX version？or  something with wav file？

**Comment by hejoy91** [comment]
@vpenades finally i solve it，it's the problem of DirectX version，i upgrade it  and everything is ok。thanks ！
