### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by TurboMaxGit** [MonoGame/MonoGame#5752]
I use MonoGame 3.6 with VS2015. Following code should work, but...silence...

   SoundEffect destroy;
   destroy = Content.Load<SoundEffect>(@"audio\zombie");
   destroy.Play();

The code is from one of the examples in the gameprogramming course on Coursera.
Is there a known bug in MG3.6/VS2015? Any advise welcome

**Comment by vpenades** [comment]
Maybe it's related to #5742 ?

**Comment by TurboMaxGit** [comment]
I read that too, and indeed after installing latest versions of everything it started working. :-)

**Comment by vpenades** [comment]
@TurboMaxGit what "latest versions" did you install?  I've just tried latest version of monogame.dev (20170605) and no luck
