### ISSUE TITLE
I have two GLSL shader, the target platform is Android, how to use the custom Effect in MonoGame, is it necessary to replace with HLSL implementation,

### ISSUE THREAD

**Issue by hadow** [MonoGame/MonoGame#5754]
Vertex Shader:
uniform vec3 Scroll;
uniform vec3 r1, r2;

attribute vec4 aVertexPosition;
attribute vec4 aVertexTexCoord;
attribute vec2 aVertexTexMetadata;
varying vec4 vTexCoord;
varying vec2 vTexMetadata;
varying vec4 vChannelMask;
varying vec4 vDepthMask;

vec4 DecodeChannelMask(float x)
{
	if (x > 0.7)
		return vec4(0,0,0,1);
	if (x > 0.5)
		return vec4(0,0,1,0);
	if (x > 0.3)
		return vec4(0,1,0,0);
	else
		return vec4(1,0,0,0);
}

void main()
{
	gl_Position = vec4((aVertexPosition.xyz - Scroll.xyz) * r1 + r2, 1);
	vTexCoord = aVertexTexCoord;
	vTexMetadata = aVertexTexMetadata;
	vChannelMask = DecodeChannelMask(abs(aVertexTexMetadata.t));
	if (aVertexTexMetadata.t < 0.0)
	{
		float x = -aVertexTexMetadata.t * 10.0;
		vDepthMask = DecodeChannelMask(x - floor(x));
	}
	else
		vDepthMask = vec4(0,0,0,0);
} 

Pixel Shader:
uniform sampler2D DiffuseTexture, Palette;

uniform bool EnableDepthPreview;
uniform float DepthTextureScale;

varying vec4 vTexCoord;
varying vec2 vTexMetadata;
varying vec4 vChannelMask;
varying vec4 vDepthMask;

float jet_r(float x)
{
	return x < 0.7 ? 4.0 * x - 1.5 : -4.0 * x + 4.5;
}

float jet_g(float x)
{
	return x < 0.5 ? 4.0 * x - 0.5 : -4.0 * x + 3.5;
}

float jet_b(float x)
{
	return x < 0.3 ? 4.0 * x + 0.5 : -4.0 * x + 2.5;
}

void main()
{
	vec4 x = texture2D(DiffuseTexture, vTexCoord.st);
	vec2 p = vec2(dot(x, vChannelMask), vTexMetadata.s);
	vec4 c = texture2D(Palette, p);

	// Discard any transparent fragments (both color and depth)
	if (c.a == 0.0)
		discard;

	float depth = gl_FragCoord.z;
	if (length(vDepthMask) > 0.0)
	{
		vec4 y = texture2D(DiffuseTexture, vTexCoord.pq);
		depth = depth + DepthTextureScale * dot(y, vDepthMask);
	}

	// Convert to window coords
	gl_FragDepth = 0.5 * depth + 0.5;

	if (EnableDepthPreview)
	{
		float x = 1.0 - gl_FragDepth;
		float r = clamp(jet_r(x), 0.0, 1.0);
		float g = clamp(jet_g(x), 0.0, 1.0);
		float b = clamp(jet_b(x), 0.0, 1.0);
		gl_FragColor = vec4(r, g, b, 1.0);
	}
	else
		gl_FragColor = c;
}

**Comment by Jjagg** [comment]
MonoGame currently only accepts HLSL shaders, so you'll have to Port your shaders.
 If you target Android the shaders will be automatically translated back to GLSL when you build the effect.
