### ISSUE TITLE
[DesktopGL] Texture2D.FromStream() performance on non Windows platforms

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5756]
I just stumbled upon this performance issue while deploying our debug tools on MacOS.

Loading textures with ```Texture2D.FromStream()``` is incredibly slow on non Windows platforms. While a simple 2048x2048 PNG loads in a few milliseconds on Windows, it litteraly takes up to 1m30 on MacOS.

I suspect ```RGBToBGR``` which is using ```System.Drawing```.

**Comment by KonajuGames** [comment]
We can be a bit smarter with that and use OpenGL functionality to map RGB to BGR during the glTexImage2D call.

**Comment by Jjagg** [comment]
Related: #5567 and #5630.
Maybe you can give 5630 a try @mrhelmut.

**Comment by tomspilman** [comment]
@mrhelmut - If you can take a few minutes and check performance with https://github.com/MonoGame/MonoGame/pull/5630 that would help a lot in us deciding to merge that.

**Comment by mrhelmut** [comment]
Good thing: #5630 works and is super fast (maybe even faster than on Windows ```System.Drawing```).

Bad thing: there's an issue with the alpha channel that I'm reporting on #5630

This confirms that the problem is ```System.Drawing```. I'll look into @KonajuGames suggestion as well, since ```Texture2D``` may not need this dependency at all.

**Comment by cra0zy** [comment]
I am totally not surprised by this issue... System.Drawing is so horribly implemented on the mono side of things. Technically this is a dup of #5630
