### ISSUE TITLE
VideoPlayer Resume() on DesktopGL throws error.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#5757]
The video player starts then stops then restarts fine.
I can pause it and then stop it, then, hit play again and it still works. 
However, i can't pause then, resume it, because it throws a error.

This on windows7 using the desktop gl solution.

> // An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll
>                     // Additional information: HRESULT: [0x80004003], Module: [General], ApiCode: [E_POINTER/Invalid pointer], Message: **Invalid pointer**

In addition it maybe leaking memory at least there are garbage collections occuring.
About 128 kb per second in my test run, with a heartbeat of about 8 kb's of garbage per second.

Here is my console output of a test run.

> clicked boxinbox_C0-(PlayVideo) No children, OnClick: Action will fire
> >PlayVideo< status StoppedVideo, State:: Stopped
> 
> clicked boxinbox_C1-(PauseVideo) No children, OnClick: Action will fire
> >PauseVideo< status PlayingVideo, State: Playing
> **-player.Pause();  result: Playing**
> 
> clicked boxinbox_C2-(StopVideo) No children, OnClick: Action will fire
> >PauseVideo< status PaudedVideo, State: Paused
> -player.Stop();  result: Stopped
> 
> clicked boxinbox_C0-(PlayVideo) No children, OnClick: Action will fire
> >PlayVideo< status StoppedVideo, State:: Stopped
> 
> clicked boxinbox_C1-(**PauseVideo**) No children, OnClick: Action will fire
> >PauseVideo< status PlayingVideo, State: Playing
> -player.Pause();  result: Paused
> 
> clicked boxinbox_C0-(**PlayVideo**) No children, OnClick: Action will fire
> >PlayVideo< **status PausedVideo, State:: Paused**

this last command is actually Play or Resume its Resume() in this case and it always throws the error.

```
        public static void PlayOrResumeVideo()
        {
            if (isPlayerInitialized == false)
            {
                videoFrameTexture = Gv.dotTexture;
                player = new VideoPlayer();
                isPlayerInitialized = true;
            }
            else
            {
                if (player.State == MediaState.Paused)
                {
                    Console.WriteLine(">PlayVideo< status PausedVideo, State:: " + player.State.ToString());
                    // could be null or its stopped
                    player.Resume(); 
                    // An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll
                    // Additional information: HRESULT: [0x80004003], Module: [General], ApiCode: [E_POINTER/Invalid pointer], Message: Invalid pointer
                }
                if (player.State == MediaState.Stopped)
                {
                    Console.WriteLine(">PlayVideo< status StoppedVideo, State:: " + player.State.ToString());
                    // could be null or its stopped
                    player.Play(video); // sometimes throws "cannot start video"
                }
                Console.WriteLine();
            }
        }
        public static void PauseVideo()
        {
            if (isPlayerInitialized)
            {
                if (player.State == MediaState.Playing)
                {
                    Console.WriteLine(">PauseVideo< status PlayingVideo, State: " + player.State.ToString());
                    player.Pause();
                    Console.WriteLine("-player.Pause();  result: " + player.State.ToString());
                    // State returns that it is playing
                }
                Console.WriteLine();
            }
        }
```

**Comment by cra0zy** [comment]
Video stuff never got implemented on the DesktopGL side, dup of: #3983

**Comment by Jjagg** [comment]
> // An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll

This is about Windows DX, @willmotil?

**Comment by KonajuGames** [comment]
I have a PR fixing a lot of behaviour in DirectX video playback (#5437) that I have to rebase.

**Comment by willmotil** [comment]
That error is called from a monogame crossplatform desktop project.

**Comment by KonajuGames** [comment]
SharpDX is only referenced by the Windows versions.  WindowsGL/DesktopGL does not have a video implementation as yet.

**Comment by willmotil** [comment]
Well someone probably just had the cross platform project pointing to SharpDx. So im guessing this would work on Dx the exact same though i didn't test that yet.

This is a cross platform project and the video does play in this monogame test app with the above class called from Game1.

**Comment by Jjagg** [comment]
> This is a cross platform project and the video does play in this monogame test app with the above class.

That's impossible, because there is no video player in DesktopGL, so your class above would fail to compile. https://github.com/MonoGame/MonoGame/blob/develop/Build/Projects/MonoGame.Framework.definition#L1149-L1151

**Comment by willmotil** [comment]
Well im looking at it right now in GL and Dx.

http://i936.photobucket.com/albums/ad207/xlightwavex/programing%20and%20concepts/testrunVideo_zpsfjl57gcv.gif

I understand your saying it shouldn't be in the .dll but the only thing i did was add a using statement to .Media and it worked.

The video player meta data path is here when i right click to goto the definition. 
-------\AppData\Local\Temp\4620$MonoGame.Framework.dll$v4.0.30319$NoDynamic\Microsoft.Xna.Framework.Media.VideoPlayer.cs

**Comment by Jjagg** [comment]
I just ran Protobuild and there's no video player in WindowsGL.

Anyway, we know it's an issue with the video player that uses SharpDX. We'll need to verify that pausing, then resuming works in #5437.

**Comment by KonajuGames** [comment]
I have just rebased #5437 and fixed the resuming.  An empty `Variant` needs to be passed to `MediaSession.Start` or it throws an invalid pointer error.

**Comment by willmotil** [comment]
Maybe an old dll is being referenced or something somehow maybe something didn't uninstall ?
Because it really is playing and i am using the nightly installer from a day ago.

So now im a bit interested in, how would i go about investigating how i am in fact able to use.
Microsoft.Xna.Framework.Media;

How would i approach tracking down were the videoplayer is being referenced from? 
In order to determine if it is in fact included in the downloaded nightly framework .dll

**Comment by Jjagg** [comment]
> Does the "monogame crossplatform project" when on windows now default to using sharpdx ?

No, then it wouldn't be cross platform anymore.

>  How would i go about starting to investigate how i am in fact able to use. Microsoft.Xna.Framework.Media;

Check the MonoGame.Framework.dll that your referencing. It's likely the DX version. Either check the full path or the description.

**Comment by willmotil** [comment]
the path says its in C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows\MonoGame.Framework.dll for the windows dx and the cross platform same one.

**Comment by KonajuGames** [comment]
Correct.  `VideoPlayer` is implemented in the DirectX version.  The DesktopGL cross-platform version has yet to get a `VideoPlayer` implementation.  The DesktopGL assembly is installed in C:\Program Files (x86)\MonoGame\v3.0\Assemblies\DesktopGL.
