### ISSUE TITLE
[OpenAL] No sounds playing

### ISSUE THREAD

**Issue by Osuology** [MonoGame/MonoGame#5760]
In all my projects that have been made in GL, they do not play sounds. I have ensured that the sounds are loading properly and they are. Even projects that used to work no longer work anymore, I'm not sure what to do anymore. My projects have OpenTK.dll in the project but no OpenAL32.dll or anything. I've reinstalled OpenAL as well as getting the latest OpenTK version by nuget and they did nothing to help. I've reinstalled mono as well and that changed nothing as well. Any ideas?

**Comment by Jjagg** [comment]
What MonoGame version are you using? The latest does not use openTK anymore.

**Comment by Osuology** [comment]
Not sure how to check but I did reinstall mono and then created a new project and it still had OpenTK.

**Comment by mrhelmut** [comment]
You're most probably on a previous version of MonoGame. Try updating to 3.6, it doesn't rely on OpenTK anymore and doesn't need OpenAL to be installed, every relevant dependencies should be embedded when you create a new project and should as-is everywhere.

**Comment by Osuology** [comment]
As of updating MonoGame and testing out a new project, OpenTK is gone and was replaced by libs of OpenAL and other stuff. Sound is now working, so thanks a lot! Sorry about the trouble over a pretty simple thing haha...
