### ISSUE TITLE
Missing Texture2D.FromFile ?

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#5761]
In upgrading the ZiggyWare blog posts, I came across the good old Texture2D.FromFile method.

I know this was a XNA 1 artifact but this seems a much easier function for users not using the content pipeline to use that the current Texture2D.FromStream

Any reasons why we couldn't add such a method ?

This would simply wrap the existing FromStream function to actually load the texture from a stream safely and return the resultant Texture2D.

**Comment by willmotil** [comment]
You can use different streams this way its less limiting.
I think in xna you could send the stream to the from file as well in a overload.
So all in all i suppose there isn't much difference.

Maybe just wrap a stream and add a from file as well. Then a user can do it either way.

**Comment by Jjagg** [comment]
IMO this isn't necessary, but there's no harm in adding the function I guess. To be consistent the same could be done for SoundEffects.

**Comment by mrhelmut** [comment]
I have mixed feelings about this when code as short as ```Texture2D.FromStream(File.Open(path))``` exist.
But I think there's no harm adding it.

**Comment by willmotil** [comment]
Well on the other hand i sort of worry about from stream for a new guy who doesn't flush and close a stream.

**Comment by PERECil** [comment]
Just one (maybe stupid) question: System.IO.File is not available in PCL. You won't be able to provide this method in the PCL version of MonoGame, do you?

**Comment by DDReaper** [comment]
MonoGames pcl implementation is based on the "bait and switch" model currently, so it only contains stub records.
The actual run time is performed on the platform with the real dll's, so this isn't an issue.

**Comment by Halofreak1990** [comment]
> Well on the other hand i sort of worry about from stream for a new guy who doesn't flush and close a stream properly so i guess it has a upside.

@willmotil I'm not sure why MonoGame should care about a user failing to properly flush/close the stream supplied to any of the FromStream methods.
