### ISSUE TITLE
Slowness in starting for Blank Page project 

### ISSUE THREAD

**Issue by yolan51** [MonoGame/MonoGame#5765]
I'm on Visual Studio 2017, AMD Phenom 2 x4 965 3,4Ghz , directX up to date , NetFramework up to date , Nvidia Geforce 750 Ti up to date. Windows Pro 64 bit.

A 4 year old computer but still it shouldn't mather for 2d graphics.

 I installed Monogame version 3.6. It take about 20 seconds for the window to appear. I compared with SFML which take about 3-4 seconds, and Windows forms 1 sec .... all blank page project.

I intend to load alots of content at startup so i don't like the 20 seconds wait for a blank page .

Good Luck.

**Comment by Jjagg** [comment]
@yolan51 Can you try profiling the application to see what's taking so long? Startup really shouldn't take that long.

Maybe you can give a 'Cross Platform Desktop Project' a try (that's referred to as DesktopGL most of the time).

**Comment by Pixelnicks** [comment]
My game starts immediately on my laptop, every time.

When I run it on my reasonably good work computer, it either loads immediately, takes 8 seconds to load, or takes 23 seconds to load. Perhaps a similar issue?

**Comment by mrhelmut** [comment]
> When I run it on my reasonably good work computer, it either loads immediately, takes 8 seconds to load, or takes 23 seconds to load. Perhaps a similar issue?

This can be linked to assets being built/rebuilt by the pipeline if they have been updated.

**Comment by Pixelnicks** [comment]
Just tested this again. This is a different issue  to yolan51. On my machine, the window is created and it hangs for either 8 or 23 seconds either during or just before loading content. I haven't tested this thoroughly. It only appears to be an issue when debugging from VS, standalone exe launch seems fine.

**Comment by mrhelmut** [comment]
What version of MonoGame are you using and what kind of project template? Would you happen to load textures from raw images (```Texture2D.FromFile```)? Are you using pipeline compression?
