### ISSUE TITLE
Sort Content in MGCB Files

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5767]
Currently the content of MGCB files is unsorted.  The content files appear in the file as they exist in memory.  New stuff is added at the end and the order from opening an existing file is preserved.

This seemed like a good idea when I first wrote the code, but it completely stinks for merging .mgcb files or when working with multiple people.

If we do a simple sort in `PipelineProjectParser.SaveProject`:
```
// Sort the items alphabetically to ensure a consistent output
// and better mergability of the resulting MGCB file.
var sortedItems = _project.ContentItems.OrderBy(c => c.OriginalPath, StringComparer.InvariantCulture);

foreach (var i in sortedItems)
{
```

This works at the content is always in a consistent order when saving, it reduces merge conflicts, and makes it easier to compare changes.

The bad part in the code above is that a simple `OrderBy` string sort for a file path produces weird results.  There is a .NET Fiddle example here:   https://dotnetfiddle.net/Odactj

If someone can come up with a good sort this would make for a great PR.

**Comment by PERECil** [comment]
My two cents; if the purpose is to reduce merge conflicts, any sort order will do fine. No need to over engineer this to a natural sort order.

**Comment by KonajuGames** [comment]
> any sort order will do fine.

It needs to be consistent across cultures too.  Different cultures can have different sorting rules.

@tomspilman What is weird about the sorting by file path?  It makes sense to me from looking at that example.

**Comment by Jjagg** [comment]
Sorting lexicographically will yield:
```
"content dir/asset.txt"
"content.dir/asset.txt"
"content/asset.txt"  // I'd prefer this one first
"content_dir/asset.txt"
"contentdir/asset.txt"
```
These are edge cases, but IMO it's preferable that dir seperator char is ordered before any other symbol (in this case 'space' and '.'). So with the above paths, the sort would result in:
```
"content/asset.txt"
"content dir/asset.txt"
"content.dir/asset.txt"
"content_dir/asset.txt"
"contentdir/asset.txt"
```
Doesn't matter all too much though IMO.

**Comment by KakCAT** [comment]
I had to do something similar in the past, check if it fits your needs

`
	List<string> list=new List<string>() {
	"content dir/asset.txt",
	"content.dir/asset.txt",
	"contentdir/folder2/assetzzz.txt",
	"test.txt",
	"content/asset.txt",
	"content_dir/asset.txt",
	"content.dir/secondFolder/ta.txt",
	"contentdir/zasset.txt",
	"contentdir/folder3/asset.txt",
	"contentdir/folder2/asset.txt",
	"content.txt",
	"content.dir/anotherasset.txt",
	};
	int i;

	// sort lexicographically path part per part first, then check shortests paths first.
	list.Sort ((p1,p2)=>
		{
			var sp1=p1.Split ('/','\\');
			var sp2=p2.Split ('/','\\');

			// check each path part
			for (i=0;i<sp1.Length;i++)
			{
				// we're at last part of sp2, and sp1 is longer: sp2 goes first
				if (i==sp2.Length-1) if (sp1.Length>sp2.Length) return 1;

				// we're at last part of sp1, and sp2 is longer: sp1 goes first
				if (i==sp1.Length-1) if (sp2.Length>sp1.Length) return -1;

				// sort lexicographically this part
				int compareResult=sp1[i].CompareTo (sp2[i]);
				if (compareResult!=0) return compareResult;
			}

			return 0;								// p1<p2 (this should only be reached if p1==p2)

		}
	);



results:

content.txt
test.txt
content/asset.txt
content dir/asset.txt
content.dir/anotherasset.txt
content.dir/asset.txt
content.dir/secondFolder/ta.txt
content_dir/asset.txt
contentdir/zasset.txt
contentdir/folder2/asset.txt
contentdir/folder2/assetzzz.txt
contentdir/folder3/asset.txt
`

**Comment by willmotil** [comment]
https://msdn.microsoft.com/en-us/library/system.stringcomparer.invariantculture(v=vs.110).aspx

**Comment by Jjagg** [comment]
Yes, the sort needs to be consistent across cultures.

**Comment by nkast** [comment]
I propose to change only the way new items are inserted in the list.
To Iterate items one-by-one from the top and insert the new item into the right place.

* No need to sort items on every load/save/insert.
* The order in existing files is preserved.  (=no headaches to update/merge projects)
* New files will be maintained in a sorted order.

**Comment by KonajuGames** [comment]
> I propose to change only the way new items are inserted in the list.

That won't be feasible.  The file cannot remember which items were in the list before the change and which ones were added after.

> The order in existing files is preserved. (=no headaches to update/merge projects)

It would be a one-time upgrade for older files, therefore a one-time resolve of any merges.  Moving on, it would make merges easier because you won't always be resolving conflicts at the end of the file.

> New files will be maintained in a sorted order. No need to sort items on every load/save.

The items would only be sorted when saved to file.  The treeview is already sorted by folder and by name within a folder.  No change there.

There is no need to create a complex sort that is pleasing to the eye.  It just needs to be consistent across cultures and platforms for the purpose of storing items in the file.  `StringComparison.InvariantCulture` provides that consistency in a reliable way.

**Comment by nkast** [comment]
> That won't be feasible. The file cannot remember which items were in the list before the change and which ones were added after.

I don't see why . It already preserves the order. 
The only change would be how we insert a new item. Instead of .Add() we would use .InsertAt() at the first right location.

> It would be a one-time upgrade for older files,

A one time work that it's unnecessary IMO, and quite frustrating. 

The code would be quite simple. Not as simple as a .Sort() of course but 2-3 lines more or less, it's just a for loop. As for the sorting method, I didn't mention anything about that, it will use the same StringComparer as the one by @KakCAT .

**Comment by willmotil** [comment]
Whats wrong with using culture invariant seems to me its a matter of simply choosing ignore case or not with that. Did you guys look at the examples in that link ?

https://msdn.microsoft.com/en-us/library/system.stringcomparer.invariantculture(v=vs.110).aspx

The best practices makes a good case for not rolling your own.

 We recommend that you select an overload that does not use default values, for the following reasons:

Some overloads with default parameters (those that search for a Char in the string instance) perform an ordinal comparison, whereas others (those that search for a string in the string instance) are culture-sensitive. It is difficult to remember which method uses which default value, and easy to confuse the overloads.

Hence what is the culture used in kats example ? >> the local culture << this will not be invariant and additions from a different hosting server with a different culture would have different ordering.

// sort lexicographically path part per part first, then check shortests paths first.
list.Sort ((p1,p2)=>
