### ISSUE TITLE
Can't create texture in iOS

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#5773]
Hi,

in iOS (tested in simulator and ipod 6 10.3.2) creating a texture with i.e.

`var tex=new Texture2D (GraphicsDevice,32,32)
`

generates 

`Microsoft.Xna.Framework.Graphics.MonoGameGLException: GL.GetError() returned InvalidEnum`

at

`GL.TexParameter(TextureTarget.Texture2D, (TextureParameterName)0x813C, 0);
`

Has anybody found the same problem since the #5614 update?

**Comment by Jjagg** [comment]
@KonajuGames Looks like GL_TEXTURE_BASE_LEVEL is not in the GL ES 2.0 spec.
I didn't really look in to it, so this may be dumb, but can't we just remove that line? 0 is the default value.

**Comment by KonajuGames** [comment]
I will look at that tomorrow.

**Comment by KonajuGames** [comment]
#5774 submitted.
