### ISSUE TITLE
Video player request and problem.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#5781]
The video player really needs a way to set position. 
It should have that, as it is standard functionality for a video player.

Additionally... 

It seems that some video's wouldn't play even after being processed thru the pipeline. Ill get a null texture returned over and over for some videos. 

However using ffmpeg thru the command line i have been testing re-encoding videos to get them to play. Pretty much most videos that i have re-encoded thru ffmpeg seem to work after the pipline processes them. (_Many that didn't prior to being re-encoded i.e. just built by the pipeline.)_

This is the ffmpeg re-encoding command that seems to work the best for preproccessing mp4s before adding them to the content pipeline. 

"ffmpeg -y -i" + " " + inputFilePath + " "
**"-c:v libx264 -profile:v main -level:v 3.0 -ab 128k -vf fps=30 -s 320x240 -c:a copy"** 
" " + outputFilePath

What the major criteria is for it to work or not i cant seem to pinpoint. Im thinking its the bitrate but i dunno.
If anyone  can shed some light on what the preferred encoding is for video's it would be much appreciated.

**Comment by Jjagg** [comment]
Opened a new issue for seeking: #6585. There's other open issues regarding video playback.
