### ISSUE TITLE
dpiAware for DestopGL does not work

### ISSUE THREAD

**Issue by JPCZ44** [MonoGame/MonoGame#5784]
I need to keep window size / resolution on computers where is enabled scaling of text and apps to more than 100% (in Windows display settings) - typical on 4K monitors. I was trying to use app.manifest with: 

```
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
	<dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</dpiAware>
   </windowsSettings>
</application>
```

Manifest is selected in project properties and solution is rebuilded, but nothing happens. It is same if I have there false or true/pm option. Game window is still resized by Windows.

**Comment by mrhelmut** [comment]
What version are you using? If you're on develop or 3.6+, the DesktopGL project template comes with a manifest that should enable DPI awareness for Windows (and compatibility modes). If the manifest is missing, you're most probably not on the correct version/template.

```
<?xml version="1.0" encoding="utf-8"?>
<asmv1:assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv1="urn:schemas-microsoft-com:asm.v1" xmlns:asmv2="urn:schemas-microsoft-com:asm.v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <assemblyIdentity version="1.0.0.0" name="YourProjectName"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="asInvoker" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- Windows Vista -->
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" />
      <!-- Windows 7 -->
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" />
      <!-- Windows 8 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" />
      <!-- Windows 8.1 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" />
      <!-- Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
    </application>
  </compatibility>
  <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
</asmv1:assembly>
```

Mind the ```assemblyIdentity``` element.

**Comment by JPCZ44** [comment]
I was trying it on MonoGame 3.6 and now on 3.7.0.512. I am using your template now but still no effect. 
I have resolution 1920 x 1080 and I have set 150% scale in Windows. Game Window is too big (is scaled). DisplayMode says that I have resolution 1280 x 720...

**Comment by mrhelmut** [comment]
It should be working if you're using this manifest. I don't know for sure, but there's maybe a manifest cache on Windows (like on some other OS) and you may need to wait for the cache to be updated. Try to make a full rebuild as well. The window shouldn't be scaled.

But the fact that your project didn't have the correct manifest is either because you didn't install the 3.6 template, or the template having a problem.
