### ISSUE TITLE
Monogame.Framework.Portable profile

### ISSUE THREAD

**Issue by impworks** [MonoGame/MonoGame#5794]
I can't upgrade my PCL library from MonoGame.Framework.Portable **v3.2.99.1-Beta** to latest **v3.6.0.1625**. Nuget Manager throws this error:

> You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259',
> but the package does not contain any assembly references or content files
> that are compatible with that framework. For more information, contact the package author.

Version 3.2.99.1-Beta supported the following profiles:
![image](https://user-images.githubusercontent.com/604496/27489319-c7dd5bf8-5842-11e7-9f98-6d0babe2a86e.png)

Version v3.6.0.1625 has a much smaller list:
![image](https://user-images.githubusercontent.com/604496/27489338-da77442c-5842-11e7-91ce-4cc53b623968.png)

Why did this happen?

**Comment by impworks** [comment]
@tomspilman Is this new expected behaviour or just a release blooper?

**Comment by DDReaper** [comment]
Likely because your project is using the older .Net 4 target, whereas MonoGame now uses .net4.5
Try updating your project to target .Net4.5 and it should work

**Comment by impworks** [comment]
@DDReaper it's 4.5 already, as the error message says:

> You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259',
> but the package does not contain any assembly references or content files
> that are compatible with that framework. For more information, contact the package author.

Here's the list of targets from the project:

![image](https://user-images.githubusercontent.com/604496/27860174-0f5d5ede-6184-11e7-8386-55a367f1f486.png)

**Comment by DDReaper** [comment]
OK, you'll need to remove WP Silverlight 8, as that is no longer a supported platform. Or try changing targets down to .net4.5 see if it works then add more.
Best also only add those targets you are actually using (or those defaulted in).

**Comment by impworks** [comment]
@DDReaper thanks! I was actually only targeting WP8.1, Android, and iOS. Deselecting all other options resolved the issue.
