### ISSUE TITLE
BasicEffect inconsistent behavior between CurrentTechnique and a loop on each technique

### ISSUE THREAD

**Issue by PERECil** [MonoGame/MonoGame#5796]
It seems, for some reason, that `BasicEffect` is behaving differently when looping on each `Techniques` and using the `CurrentTechnique` property. The following code shows the problem:

```
GraphicsDevice.Clear(Color.CornflowerBlue);

VertexPosition[] vertices = new VertexPosition[3];

vertices[0] = new VertexPosition(new Vector3(-0.5f, -0.25f, 0f));
vertices[1] = new VertexPosition(new Vector3(0.0f, (float)Math.Sqrt(0.75) - 0.25f, 0f));
vertices[2] = new VertexPosition(new Vector3(0.5f, -0.25f, 0f));

BasicEffect basicEffect = new BasicEffect(this.GraphicsDevice);

basicEffect.EmissiveColor = Color.White.ToVector3();
basicEffect.LightingEnabled = true;

basicEffect.Projection = Matrix.CreateOrthographic(this.GraphicsDevice.Viewport.Bounds.Width, this.GraphicsDevice.Viewport.Bounds.Height, -100, 100);
basicEffect.World = Matrix.CreateScale(100f);

// This renders the triangle white, as expected
foreach (EffectPass pass in basicEffect.CurrentTechnique.Passes)
{
	pass.Apply();

	GraphicsDevice.DrawUserPrimitives(PrimitiveType.TriangleList, vertices, 0, 1);
}
// */

/* This renders the triangle black
foreach (EffectTechnique technique in basicEffect.Techniques)
{
	foreach (EffectPass pass in technique.Passes)
	{
		pass.Apply();

		this.GraphicsDevice.DrawUserPrimitives(PrimitiveType.TriangleList, vertices, 0, 1);
	}
}
// */
```

Using `CurrentTechnique` is giving the expected result, but looping each `Techniques` renders the triangle black. What I find weird is that `BasicEffect` is just holding one technique, so the loop is only on one element, the technique named `"BasicEffect"`.

Am I missing something, or is it a bug?

**Comment by Jjagg** [comment]
BasicEffect actually has a bunch of techniques. See https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Effect/Resources/BasicEffect.fx#L456-L490

**Comment by PERECil** [comment]
OK, tested it again, and you were right. I was pretty sure that I saw only one technique in BasicEffect (maybe because I didn't wait for the loop to end and the first technique is the current technique).
