### ISSUE TITLE
SpriteFont.Measurestring() gives different values on Nvidia <--> AMD GPU

### ISSUE THREAD

**Issue by Jxlle** [MonoGame/MonoGame#5802]
I used to work on a computer running Microsoft Visual Studio 2015, but I recently made a new computer and installed Visual Studio 2017. 
I imported my MonoGame project, and the first thing I saw when I started the project, was that my font wasn't correctly displayed. The code gives different values for SpriteFont.Measurestring().Y.

I did some research on multiple computers and found this:

**computer 1:**

CPU: intel core i7-7700K, 4.20GHz
Memory: Gskill trident Z DDR4 4x8GB
Motherboard: Asus maximus ix formula
GPU: ZOTAC GTX 1080ti amp extreme (**Nvidia**)
resolution: 1920 x 1080
`SpriteFont.MeasureString(".").Y` : **44** 
`SpriteFont.MeasureString(".").X` : 8

**computer 2:**

CPU: intel core i7-4790S, 3.20GHz
Memory: Samsung DDR3 8GB
Motherboard: Hewlett-Packard 2AF7
GPU: **AMD** R7 240
resolution: 1920 x 1080
`SpriteFont.MeasureString(".").Y` : **32**
`SpriteFont.MeasureString(".").X` : 8

**computer 3:**

CPU: intel core i7-4770
Memory: Nanya DDR3 2x8GB
Motherboard: Medion MS-7848
GPU: **Nvidia** GTX 760
resolution: 1920 x 1080
`SpriteFont.MeasureString(".").Y` : **44**
`SpriteFont.MeasureString(".").X` : 8

Nvidia and AMD cards use a different font height. Computer 1 & 3 have Nvidia GPU's and they have the same font size. The computer with the AMD card does not.

My font: https://fontstruct.com/fontstructions/show/1294054/pixel-102 

**UPDATE**
I can't recreate this bug in a new project, but I have another project where the same bug is present.

simple project to test MeasureString (can't recreate problem here) : [SpriteFontTest.zip](https://github.com/MonoGame/MonoGame/files/1133669/SpriteFontTest.zip)

used font in my original project : [Pixel (1).zip](https://github.com/MonoGame/MonoGame/files/1133685/Pixel.1.zip)

**Comment by Jjagg** [comment]
> computer 3:
[...]
 used font size X: 4

Is that a typo?

Thanks for reporting!

**Comment by Jxlle** [comment]
Yes, that was a typo. The X value is the same on Nvidia/AMD cards

**Comment by nkast** [comment]
What's the .spriteFont file used for this one? 

Have you tried with other fonts or swapping the cards between the two computers?

The link requires login or something. It would be great if you could share a font file on dropbox, onedrive, etc or if you could replicate that with a font found on windows XP/2000/8/10.

**Comment by Jxlle** [comment]
I'm going to make a project, with a default font, and upload the files so you can test on your computer if the values are the same. 

I can't switch the cards because computer 1 and 2 are customer computers bought in a store. The case is a tight fit and you lose warranty if you open the case.

**Comment by Jxlle** [comment]
Hmm seems like a very weird bug in my project. The only place where the AMD card is wrong in font size is my project. I made a new project to see if the problem occurred again, but it's all good.

I don't know how it happens on my project, but it does **NOT** seem a general MonoGame issue..

**Comment by nkast** [comment]
Ok, I can test it on a AMD R7 270 if you'd like.

**Comment by Jxlle** [comment]
I added the project. You can always test with different fonts and stuff, but I can't reconstruct the problem so it's probably a very rare/weird glitch or something.

**Comment by KonajuGames** [comment]
I don't understand what you mean by "used font size Y".  Is that what you used in the .spritefont file or what was reported by `MeasureString` from the same .xnb?

**Comment by Jxlle** [comment]
Sorry for the confusion. I mean the` SpriteFont.MeasureString().Y` value when using a single character (example: ".")
I use a size of 15 in the .spritefont file.

**Comment by nkast** [comment]
I am getting {X:4 Y:18}

**Comment by Jxlle** [comment]
I'm also getting {X:4 Y:18}. The weird thing is, that I have another project and this project has the exact same bug with the SpriteFont size. I can't recreate the problem outside these projects.

**Comment by nkast** [comment]
Maybe you are seeing an older file. Is it possible that the font doesn't re-build for some reason?

**Comment by Jxlle** [comment]
That might be it! Maybe if I reinstall the font on the older computer..
I will try this asap.

**Comment by PERECil** [comment]
The measurement are stored in the `SpriteFont`'s `Glyph` that is built at compile time through the `MGCB` tool. Try to swap the `xnb` compiled font from one computer to another, and I think you should not have a difference in measurement anymore.

**Comment by Jxlle** [comment]
Yes that will work. Thanks for the information!
