### ISSUE TITLE
Expose keyDown / keyUp events in GameWindow class.

### ISSUE THREAD

**Issue by PERECil** [MonoGame/MonoGame#5806]
Currently the `GameWindow` class expose a `TextInput` event to allows the creation of text boxes and other similar UI events. However, this event only fires when characters are typed, **and common function buttons like backspace or delete don't trigger this event**.

To provide full functionality to a textbox like UI control, **we currently need to emulate the behavior** by checking the key state in the `Keyboard` class, in an `Update()` loop. However, this emulation is not perfect, because even if implement it to emulate the keyboard delays and repeat speed, if the user hit rapidly the backspace stroke (for example), as the update loop is running, by default, at 60hz, **we may miss some keystrokes**.

**This gives the end user a laggy experience**. I suggest to implement the `KeyDown` and `KeyUp` events as well (and from what I see in `OpenTKGameWindow`, they're already used, it's just a matter of exposing them) in the `GameWindow` so the user of the framework could have a finer grained control of the keyboard, and would not have to rely on sort of emulation to provide erasing capabilities to a text box.

**Comment by nkast** [comment]
I remember that TextInput was changed to include special characters (like tab, etc). #4878
Maybe it still ignores a few like backspace  & delete. On which platform are you seeing this?

**Comment by PERECil** [comment]
Windows, DesktopGL, but my keyboard and UI code is in a PCL using the latest MonoGame Portable Classes (3.6).

**Comment by nkast** [comment]
It should work then. Isn't SDLGameWindow the one used for DesktopGL? 
Have you tried to get Backspace/Delete from  TextInput with MG3.6?

**Comment by BaseCrosser** [comment]
Do you have some code somewhere that is filtering the characters that are not in the spritefont?
Something like this:
```
public EventHandler<TextInputEventArgs> TextInputEvent;

gameWindow.TextInput += OnTextInput;

void OnTextInput(object sender, TextInputEventArgs e)
{
    // Check if character is in spritefont based on the character region  in the spritefont file
    if (e.Character >= 32 && e.Character <= 126) // this iis the default character region range in a spritefont file
    {
        TextInputEvent?.Invoke(sender, e);
    {
}
```
If you do, remove the `if` statement and check what character you receive from the event when you press backspace, it should be `'\b'`. The special characters are out of the default range of the character region in the spritefont file.

I have done this previously and it worked but that was on Windows DX, I don't remember if I tested it on OpenGL.

**Comment by PERECil** [comment]
Nope, it's `OpenTKGameWindow`, not `SDLGameWindow` from what I'm seeing in the inspector in debug mode. I'm not filtering anything as I just put a breakpoint in the event handler from TextInput.

**Comment by mrhelmut** [comment]
It shouldn't be using OpenTK since 3.6, would you mind trying to clean your MonoGame binaries?

The ```SDLGameWindow.TextInput``` event should correctly report control keys now.

**Comment by PERECil** [comment]
OK, somehow, I was thinking that using the MonoGame 3.6 nuget package was the same as installing the MonoGame 3.6 SDK. While upgrading my project from 3.5 to 3.6 I encountered #5531, but this was easily fixable. 

Now the `Game.Window` is an instance of `SDLGameWindow` as expected and the backspace key is correctly detected. 

Thanks for the help!
