### ISSUE TITLE
Remove Windows Phone 8 / WinRT support

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#5807]
I've did a fork [here](https://github.com/vpenades/MonoGame) to upgrade monogame to SharpDX 4.0.1 #3794 , but it's failing to compile on Windows 8 project because SharpDX has removed support for it. So I pulled back my PR.

Prior trying to upgrade to SharpDX 4.0.1 , Windows 8 platform support needs to be removed. I guess this is a hairy issue, so I leave it here for people to decide what to do with this platform.

Notice that keeping Windows8 support implies not being able to upgrade to newer versions of SharpDX.

@tomspilman I think I would need assistence with this...

**Comment by DDReaper** [comment]
I know I brought up this discussion previously, but it seems even our partners are now dropping Windows 8.1 / Windows Phone 8.1 support.

So i feel this falls in the same pattern we have used for previously dropped platforms.  For 3.7 we should de-scope support for Windows 8.1 & Windows Phone 8.1.

Anyone still needing those platforms will need to use 3.6.

**Comment by KonajuGames** [comment]
> For 3.7 we should de-scope support for Windows 8.1 & Windows Phone 8.1.
> 
> Anyone still needing those platforms will need to use 3.6.

I'm happy with that.  The audience for Windows Phone 8.1 is almost zero.  For Windows 8.1, the Steam Hardware & Software Survey reports 8.1 64-bit at 6.86% and 8.1 32-bit at 0.20%.  Of that 7%, the number of people who use the Windows Store to buy games would be a tiny fraction of that.  Also remember this is a Steam survey, so they're using Steam for their games, not the Windows Store, and our Windows and DesktopGL platforms support that just fine.

**Comment by vpenades** [comment]
[How convenient](https://www.theverge.com/2017/7/11/15952654/microsoft-windows-phone-end-of-support)

**Comment by Jjagg** [comment]
The link says Microsoft ended WP8.1 support July 11 (yesterday at the time of writing).
Great timing I guess :D

**Comment by DDReaper** [comment]
Worst announcement of dissolving of support ever, so much for giving devs notice :D 
But it has almost no info on the future of Windows Mobile 10.  The MS train continues to it's eventual demise again :(

**Comment by Scellow** [comment]
i bet the future will be with CoreRT https://github.com/dotnet/corert

But that means MonoGame will be to be ported to .Net Core, wich should be now possible with upcoming release of .Net Core 2.0

**Comment by DDReaper** [comment]
Sadly that's mostly unlikely for the time being, even with NetCore2 as it still doesn't support graphical or audio elements.  @cra0zy does have a test repo for building MG in NetCore.  Still a heavily "work in progress" atm

**Comment by cra0zy** [comment]
> Sadly that's mostly unlikely for the time being, even with NetCore2 as it still doesn't support graphical or audio elements.

Well the default C# doesn't support that either and we still manage just fine... the only thing stopping me from submitting a PR for .Net Core to the main repo is the fact that Protobuild does not support .Net Core, and I don't want to have to write xsls files to add support for it.

**Comment by DDReaper** [comment]
Thanks for clarifying @cra0zy  just my bad misinterpretation of the core issues for not going NetCore :D

**Comment by vpenades** [comment]
The concept behind net.Core is to have true cross platform runtime that behaves exactly the same across all platforms. Ironically, the first one that broke this concept is Microsoft itself, because they could have chose to make Universal Platform a net.core platform, but instead they chose to move as far away from net.core as possible, to keep UWP closed and proprietary.

My conclusion is that net.core is an attempt to make a cross platform runtime, as long as the given platform is an **open** platform, which means windows desktop, linux, server environments, etc. Given the target audience of Monogame is gaming platforms which, in many cases, are proprietary and closed platforms, it's going to be highly unlikely these platforms will ever support net.core.

A completely different matter is net.standard, and I think monogame *should* support net.standard one way or another, because it would allow to write shared assemblies that could be referenced from platform specific backends

**Comment by DDReaper** [comment]
Win 8 / WP8 also being removed from the Microsoft DirectXTK repo 
https://github.com/Microsoft/DirectXTK/issues/47

**Comment by vpenades** [comment]
@DDReaper wow, it's like they gave order to erase it of existence as if never existed!

**Comment by DDReaper** [comment]
So @tomspilman / @KonajuGames what are your thoughts? Are we going to progress this and PR #5809 ?
@tgjones do you have any further thoughts?

**Comment by cra0zy** [comment]
The support for Windows 8.x platforms has been removed in: #5809
