### ISSUE TITLE
Cross Platform Project Mouse.SetCursor() alpha channel displays magenta

### ISSUE THREAD

**Issue by Pixelnicks** [MonoGame/MonoGame#5822]
```
Mouse.SetCursor(MouseCursor.FromTexture2D(cursorTexture,0,0));
IsMouseVisible = true;
```

Expected result on Cross Platform Project: Mouse cursor is changed to the Texture2D with transparency, this works as expected on a Windows project.

Actual result on Cross Platform Project: Mouse cursor is changed to the Texture2D, the transparent areas are filled with magenta.

**Comment by tomspilman** [comment]
@cra0zy @dellis1972 @KonajuGames ?

**Comment by KonajuGames** [comment]
I'll take a look now.

**Comment by cra0zy** [comment]
@Pixelnicks what version of MG are you using?

**Comment by Pixelnicks** [comment]
MonoGame 3.7.0.512

I can't provide the image as cursors are removed from Print Screen, Snipping tool and Fraps.

Here's a fake screenshot:
![image](https://user-images.githubusercontent.com/28794554/28426801-2dea1c7c-6d6c-11e7-8ae4-0b4848a68482.png)

**Comment by KonajuGames** [comment]
I have replicated this and am working on a fix now.

**Comment by KonajuGames** [comment]
PR #5829 fixes this issue.

**Comment by Pixelnicks** [comment]
Outstanding response, thanks @KonajuGames! It's working well now.

**Comment by KonajuGames** [comment]
I'll verify DX behaviour and then this should be good to go.
