### ISSUE TITLE
Weird shader behavior on Android

### ISSUE THREAD

**Issue by Paulloz** [MonoGame/MonoGame#5830]
Hi there, I'm having some trouble using `Effect` on some Android devices.  
I'll try to be understandable (feel free to ask stuff if I'm not).  

My tests are performed on two devices: Samsung Galaxy S4 (Android 5.0.1) and Samsung Galaxy Tab 2 (Android 6.0.1). I should note that I'm using other 6.0.1 devices without any issue.  
Galaxy S4 screenshots will be on the left and Galaxy Tab 2 on the right.

Everything is built through MonoGame Pipeline 3.5

---

**1rst test**: using a shader which outputs red pixels to draw on screen
```glsl
#if OPENGL
#define PS_SHADERMODEL ps_3_0
#else
#define PS_SHADERMODEL ps_4_0_level_9_1
#endif

float4 PixelShaderFunction(float2 pos : SV_POSITION, float4 color1 : COLOR0, float2 coords : TEXCOORD0) : COLOR0
{
	return float4(1, 0, 0, 1);
}

technique Technique1
{
	pass Pass1
	{
		PixelShader = compile PS_SHADERMODEL PixelShaderFunction();
	}
};
```

```cs
// ...
this.shader = this.Manager.Game.Content.Load<Effect>("shaders/credits");
// ...
this.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, null, null, null, this.shader);
this.spriteBatch.Draw(this.credits, this.creditsViewport, this.creditsSource, Color.White);
this.spriteBatch.End();
// ...
```
Everything is fine on both devices.
![screenshot_2017-07-21-15-05-18](https://user-images.githubusercontent.com/437025/28464951-73389540-6e27-11e7-9b0f-199bce5614bc.png)

---

**2nd test**: using a shader which outputs texture as-is to draw on screen (C# code is same as above)
```glsl
#if OPENGL
#define PS_SHADERMODEL ps_3_0
#else
#define PS_SHADERMODEL ps_4_0_level_9_1
#endif

sampler ColorSampler : register(s0);

float4 PixelShaderFunction(float2 pos : SV_POSITION, float4 color1 : COLOR0, float2 coords : TEXCOORD0) : COLOR0
{
	return tex2D(ColorSampler, coords);
}

technique Technique1
{
	pass Pass1
	{
		PixelShader = compile PS_SHADERMODEL PixelShaderFunction();
	}
};
```
Everything is fine on the Galaxy S4 but nothing is drawn on the Galaxy Tab 2.
![screen](https://user-images.githubusercontent.com/437025/28466074-6cf75be0-6e2b-11e7-83ba-5a643fdb6cf7.png)

---

**3rd test**: using the same shader as **2nd test** but on another `RenderTarget2D`
```cs
//...
Effect shader = this.Manager.Game.Content.Load<Effect>("shaders/credits");
SpriteBatch spriteBatch = new SpriteBatch(this.Manager.GraphicsDevice);

this.fade = new RenderTarget2D(this.Manager.GraphicsDevice, this.Manager.GraphicsDevice.Viewport.Width, this.Manager.GraphicsDevice.Viewport.Height);

this.Manager.Game.GraphicsDevice.SetRenderTarget(this.fade as RenderTarget2D);
this.Manager.Game.GraphicsDevice.Clear(Color.Transparent);
spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, null, null, null, shader);
spriteBatch.Draw(this.background[0].Texture, this.fade.Bounds, Color.White);
spriteBatch.End();
this.Manager.Game.GraphicsDevice.SetRenderTargets();
//...
```
From now on (and no matter if I do something with `this.fade` or not), here's what kind of stuff is drawn on the Galaxy Tab 2 screen (no issue on the other device).

![screenshot_20170721-154119](https://user-images.githubusercontent.com/437025/28466123-96079a4a-6e2b-11e7-9000-409b828bf22a.png)

And then, every single thing I draw on screen is broken (left picture is for comparison).
![screen](https://user-images.githubusercontent.com/437025/28466239-16f81eae-6e2c-11e7-966e-eae8e5cb4441.png)

---

I am not that experienced with shaders so... Am I doing everything wrong? Is this somehow understandable?  
Thanks!

**Comment by mrhelmut** [comment]
Looks very detailed to me, thanks.

@roponator  @dellis1972 @KonajuGames Would you happen to have any input?

**Comment by Jjagg** [comment]
@Paulloz can you try making the position parameter a float4?

**Comment by mrhelmut** [comment]
I'm now working with @Paulloz and can confirm that @Jjagg 's suggestion fixed the issue (as well as updating to the latest develop branch).

This can be closed.

**Comment by dellis1972** [comment]
@mrhelmut what was @Jjagg suggestion? Might be helpful for people getting the same issue?

**Comment by dellis1972** [comment]
never mind just saw it :)
