### ISSUE TITLE
Rectangle bugs

### ISSUE THREAD

**Issue by Exo-Mike** [MonoGame/MonoGame#5833]
*Rectangle.IsEmpty* and *Rectangle.Empty* should be corrected, as using either of these could lead to bugs via false negatives.

The current implementation is:
```
/// <summary>
/// Whether or not this <see cref="Rectangle"/> has a <see cref="Width"/> and
/// <see cref="Height"/> of 0, and a <see cref="Location"/> of (0, 0).
/// </summary>
public bool IsEmpty
{
    get
    {
        return ((((this.Width == 0) && (this.Height == 0)) && (this.X == 0)) && (this.Y == 0));
    }
}
```
According to this, for a *Rectangle* to be considered empty, both it's width *and* its height **must** equal 0 **and** both its X and Y positions **must** equal 0.

For a Rectangle to actually be empty, all that is required is that *either* its width **or** height equal 0. Its X or Y positions have no effect on this. A rectangle could have a height of *int.MaxValue* but if its width is 0, its still an empty triangle containing a no space. Essentially it would just be a line with no volume. It also doesn't matter if an empty Rectangle is located in the top-left of screen or the bottom-right; empty is still empty.

A correct implementation of *Rectangle.IsEmpty* would be:
```
public bool IsEmpty
{
    get { return Width == 0 || Height == 0; }
}
```
I realize this is legacy dragged along from XNA but regardless, its still incorrect and bugged against what should be expected behavior.

This also applies to the *Rectangle.Empty* constant which really shouldn't be labeled the definitive state of an empty Rectangle. As mentioned above, the X and Y positions have no context in whether it is empty and only a width **or** height of 0 indicate emptiness. Removing or renaming the *Rectangle.Empty* constant could be a breaking change to anyone compiled against it to determine emptiness in their code which sucks but if they're depending on this being the only form of an empty rectangle possible than their code is already bugged.

Any chance on a pull request to correct this or any thoughts against a PR for this?

**Comment by PERECil** [comment]
I would go for adding some kind of IsZero property and fix the behavior. And throw directly either Empty or IsEmpty, because both have the same behavior and is a bait for confusion.

**Comment by Halofreak1990** [comment]
@Exo-Mike Why, though? In XNA, `Rectangle.Empty` is defined as a Rectangle with all dimensions set to 0, and `Rectangle.IsEmpty`, IIRC, is defined as a simple comparison between the current Rectangle and `Rectangle.Empty`. I understand where you're coming from, but as it is in XNA, there is little room for error, to be honest.

**Comment by theZMan** [comment]
@Exo-Mike - your logic is sound but this would be such a breaking change its very unlikely to be accepted as a change.

In XNA 'empty' is really being used as an IsNull type flag - in that its a sentinel value for 'this rectangle has not been set/has been cleared'. 

I'd suggest adding an extension method called something like Is(Degenerate)[https://en.wikipedia.org/wiki/Degeneracy_(mathematics)] with your code. You might get that in as a PR if not it would be a useful addition to the (MonoGame.Extended) [https://github.com/craftworkgames/MonoGame.Extended]
