### ISSUE TITLE
PipelineTool - Not showing error line when output filtering on

### ISSUE THREAD

**Issue by MarcVador** [MonoGame/MonoGame#5846]
Hi !
I've noticed with the last build (as of 3.7.678) and maybe the previous one or 2, the line and position of the warnings/errors are no more available when using the filtered output.
I have to switch to "text mode" to find the line of the warning/error:
![image](https://user-images.githubusercontent.com/19704413/28669220-a4137238-72d3-11e7-94ad-0a29cceaeed2.png)

**Comment by nkast** [comment]
@MarcVador 
Can you please  test the package from PR #5849 ?
http://teamcity.monogame.net/viewLog.html?buildId=50475&buildTypeId=MonoGame_PackagingWindows&tab=artifacts

**Comment by nkast** [comment]
@MarcVador 
can you try the package from PR #5849 ?
http://teamcity.monogame.net/viewLog.html?buildId=50509&buildTypeId=MonoGame_PackagingWindows&tab=artifacts

**Comment by MarcVador** [comment]
It's ok with this ! Warnings and errors are back for me too. Nice ! Thank you.

**Comment by nkast** [comment]
Thanks for the verification @MarcVador.
