### ISSUE TITLE
UWP ARM runtime failure

### ISSUE THREAD

**Issue by rkusyapkulov** [MonoGame/MonoGame#5847]
Hello,

I have problem by building my UWP app using VS2015 SP3 and MonoGame 3.6.
 The compiler probably produce wrong code, if "Compile with .NET Native tool chain" is active.
 If I disable this feature, then all working fine.

It happened only, if I create a final windows store package.
 The DEBUG and RELEASE builds working fine, if I deploy and start app from debugger.
 But if I create a final windows store package with active "Compile with .NET Native tool chain" and manual install,
 then by start my app showing only SplashScreen and then app be terminated.

If I disable "Compile with .NET Native tool chain" and create a final windows store package,
 then my app working fine by manual install too.

The x86 and x64 packages working fine.
 It's looked that problem only under ARM.

My app using last MonoGame Framework version 3.6 .
 To reproduce problem enough to  create a default (empty) MonoGame Windows 10 Universal Project.
 Then activate "Compile with .NET Native tool chain" and create a final windows store package.
 After build, try to manual install ARM package to any windows phone.
 After start app - it show only SplashScreen and then app be terminated.
 If you disable "Compile with .NET Native tool chain" and create a final windows store package.
 Then by manual install all working fine.

I found similar issues:
https://github.com/aspnet/EntityFramework/issues/6253
https://github.com/aspnet/EntityFramework/issues/6027
https://stackoverflow.com/questions/43530071/how-to-fix-app-submission-error-of-1300

but no any solutions not help to resolve this problem.

My question is how I can resolve this problem ?

Did somebody successful generated a submitt any monogame app to MS and successful go thru submission?

thanks,

PS: I just tested with last developer build 3.7.0.678. It's same problem !

I asked help on MS forum: https://social.msdn.microsoft.com/Forums/Windowsapps/en-US/0e3dd982-8458-4dce-a513-b51847d8dddf/monogame-and-uwp?forum=wpdevelop
But they not can or not want to help us resolve this problem :-( ...

**Comment by rkusyapkulov** [comment]
Hello,

did you or MS developers have any News about my Problem?

I just built and tested again using latest Version 15.3.2 VS2017 and latest developer build of MonoGame 3.7.0.768.

(it used latest Microsoft.NET.Native.Framework.1.7).

This Problem exist until now !

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
