### ISSUE TITLE
MonoGame 3.6 UWP Template is broken for VB.NET

### ISSUE THREAD

**Issue by BrainSlugs83** [MonoGame/MonoGame#5855]
So, I recently re-imaged my dev. machine with the latest Windows 10 Creators Update -- so my machine is pretty raw/clean.

I've got Visual Studio 2015, Update 3 -- and I've just pulled down Monogame 3.6 from the official website / installer.

I immediately try to Create a new Monogame project -- and I accidentally selected the VB.NET version without realizing it (instead of C#) -- but I figured, what the heck, let's give this a try.

Upon build, it pulled down a bunch of NuGet packages, and then immediately failed with the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload file 'C:\Users\Mikey\.nuget\packages\MonoGame.Framework.WindowsUAP\3.4.0.459\lib\netcore\MonoGame.Framework\MonoGame.Framework.xr.xml' does not exist.	RenderSomething			
```

It seems to me like, maybe the vbproj file is referencing MonoGame 3.4? -- Maybe this might even work if I'd also had MonoGame 3.4 installed. -- But, I bet that might lead to some interesting issues on its own.

**Comment by DDReaper** [comment]
None of the MonoGame templates (to my knowledge) use any NuGet packages.  So this would be very odd.
The VB template as far as I know, is still the VS2015 package, so it's likely you'd need VS2015 installed to open it.  Not seen any requests to continue offering the VB package going forward (could be wrong :D)

**Comment by Jjagg** [comment]
We no longer have VB templates. Adding them is tracked in #4127.
