### ISSUE TITLE
compiled mp3: SharpDXException The system cannot find the file specified

### ISSUE THREAD

**Issue by JoshuaLamusga** [MonoGame/MonoGame#5857]
With MonoGame version 3.6, I get
`SharpDX.SharpDXException: 'HRESULT: [0x80070002], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: The system cannot find the file specified.`

In VS2017 using the _Monogame Windows Project_ template, with a properly-built Content.mgcb directory of files. The content pipeline has found the .xnb file associated with the song, but is throwing an exception for some other reason. Output contains both .wma and .xnb files for each song as expected.

**Comment by KonajuGames** [comment]
You should only get a .wma if you built for Windows, and the SharpDX exception indicates you are using the Windows platform.  A cross-platform project should get a .ogg file.  For a song, the .xnb contains the relative path to the song file that the content pipeline produced (.wma for Windows, .ogg for Windows/Mac/Linux OpenGL, .aac for iOS and Android).

**Comment by JoshuaLamusga** [comment]
You're right, I am using a Windows project (sorry!). Both the .wma and .xnb are in their original output folder together. .wav files compile to .xnb and work without hassle, if that's any help.

**Comment by KonajuGames** [comment]
Are you able to view the contents of the XNB file?  You should see the relative path to the .wma file in there.  Is the relative path correct?  Odd characters in the filename?  Are you running from a network drive perhaps?  Trying to guess what could make it fail.

**Comment by JoshuaLamusga** [comment]
Using GXView from (http://www.gruaz.net/projects/the-gametools-suite), I get this output:
> TargetPlatform: Windows
GraphicProfile: Reach
XNA Framework Version: 4
Error: End position does not match XNB header: unexpected amount of data was read.

If you suspect it cannot correctly read the file, I can take a recommendation for another tool to read the file, but it would probably be faster to view it yourself, so I've attached one. It has both the .wma and the .xnb associated, made in pipeline.
[both.zip](https://github.com/MonoGame/MonoGame/files/1197953/both.zip)

**Comment by Jjagg** [comment]
Tested and working 👍
