### ISSUE TITLE
Pipeline crashes when setting a boolean processor parameter for 2+ items with mixed values

### ISSUE THREAD

**Issue by JoshuaLamusga** [MonoGame/MonoGame#5858]
The MonoGame Pipeline (version 3.6.0.1625) reliably crashes when you select two or more items that have different values for the same processor parameter, then try to set that processor parameter for both simultaneously. It crashes with a NullReferenceException, but I can't get more information than that without digging into MonoGame (which I don't want to do right now).

**Steps to reproduce**
Make a new project.
Add 2 or more images.
Set *Color Key Enabled* to false for one (one is false and one is true).
Select both.
Try to set *Color Key Enabled* by clicking on it. The Pipeline should crash.

**Notes**
This bug exists for any boolean processor parameter.
![image](https://user-images.githubusercontent.com/30244654/28836683-d2f1a650-769e-11e7-9b94-43ff4b510935.png)

**Comment by tomspilman** [comment]
@cra0zy ?

**Comment by cra0zy** [comment]
On it.
