### ISSUE TITLE
SoundEffect not playing on a WPF and Winforms hosted game

### ISSUE THREAD

**Issue by dlnieves** [MonoGame/MonoGame#5861]
Hello. Sounds are not playing when your game is hosted on a WPF/Winforms control (using DirectX of course).
In a normal Monogame window it works perfectly.
Any ideas?

**Comment by mrhelmut** [comment]
Does a standalone DirectX project play sound?

If not, you are missing the June 2010 DirectX runtimes on your computer.
Here's a link: https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by dlnieves** [comment]
Oh, hello, thanks for answering. I made a game editor based on WPF, the scene viewport is a GraphicsDeviceControl which has been working since Monogame 3.4. Recently, when I switched to Monogame 3.6 none of the sounds worked, and yes: a standalone DirectX project plays sounds. 
The same scene code works perfectly in a standalone monogame game. Could it be an issue or conflict related to WPF and DirectX combination? I repeat: The problem is only for the Monogame 3.6 stable version.

**Comment by nkast** [comment]
I can confirm that. 
I fix it by calling FrameworkDispatcher.Update() before creating any sounds to initialize the sound engine and then again on every update/loop.

However that was not necesery before and neither was for XNA.

**Comment by dlnieves** [comment]
Oh, I will try that, but it still bothers me.

**Comment by KonajuGames** [comment]
> However that was not necesery before and neither was for XNA.

Calling `FrameworkDispatcher.Update()` was required in XNA to play sounds [when a `Game` object was not present](https://msdn.microsoft.com/en-us/library/ff842408.aspx), such as when it was embedded in a Windows Phone or WinForms application.

**Comment by DDReaper** [comment]
@KonajuGames is completely correct. For XNA Windows / Xbox it was not needed as the audio logic was built in to the subsystem loop.
However, In Windows Phone and now UWP/modern WPF, they separated it out in to its own runtime, hence you need to update the dispatcher manually.  Never really understood why but that's how it is now when you access the sound system directly.

**Comment by nkast** [comment]
Ok, I have seen what happened. 
FrameworkDispatcher.Update is required to update things like the SoundEffect pool, dynamic SoundEffects and the microphone.
So far I haven't noticed any bug because I always work with SoundEffectIncances. 
The difference is that previously (MG3.5 & XNA) the audio engine was initialized automatically whenever you create a sound while now you need to call fd.Update() once before any initialization.

However, that's how you are supposed to work with Frameworkdispather. even under XNA.

**Comment by dlnieves** [comment]
Hello. It works perfectly. You can **close this issue now**. Thanks to all.
