### ISSUE TITLE
TextureFormat Color16Bit does not render odd-width textures correctly (Cross Platform Desktop)

### ISSUE THREAD

**Issue by Pixelnicks** [MonoGame/MonoGame#5865]
Create a Cross Platform Desktop Project.
Create a texture with an odd number pixels width.
Set TextureFormat in Monogame Pipeline Tool to Color16Bit.
Draw the texture in Monogame and it offsets to create a diagonal slanted texture.

The image in the example is 257x256 pixels.

![image](https://user-images.githubusercontent.com/28794554/29240287-f9c41b0a-7f59-11e7-92fe-1a341676d5ab.png)

**Comment by KonajuGames** [comment]
That should be fairly easy to fix.  It will be an issue with the row pitch being 32-bit aligned.

**Comment by Jjagg** [comment]
Yeah, I already fixed it locally with a call to `glPixelStorei` to set `GL_UNPACK_ALIGNMENT`. Will do a PR after polishing it an adding tests.

**Comment by Jjagg** [comment]
Hmm, I built the texture with format set to `Color16Bit`, but runtime format is DXT3.

**Comment by KonajuGames** [comment]
That's odd.  Would have to trace through the TextureProcessor to see why.
