### ISSUE TITLE
monogame-sdk.run requires user intervention to install

### ISSUE THREAD

**Issue by ashes999** [MonoGame/MonoGame#5879]
I'm trying to build my MonoGame project on Travis (under Linux) and run my unit tests. I'm stuck on the step where I bootstrap MonoGame.

As of MonoGame 3.6 (I think 3.4 worked at some point), running `monogame-sdk.run` requires user intervention; after checking and listing pre-requisites, there's a prompt that says `Continue (Y, n):` and doesn't proceed unless there's a human present to enter input.

I tried piping input several ways, but nothing seems to work. I also looked for any command-line arguments that I can use (including editing the source shell script part) but didn't find anything.

Please provide some way for the installation to proceed without human intervention, and please also tell me if there's a work-around for this in the meanwhile. (I tried extracting the contents but the prompt comes from `postinstall.sh` and there doesn't seem to be a way around it.)

I tried opening a PR for this myself, but couldn't figure out how to check the command-line arguments properly. It looks like `makeshelf` sends in two parameters already, and I'm not clear how to build the `makeshelf` file to test my changes.

NB: I reported this issue forst on [makeshelf, here](https://github.com/megastep/makeself/issues/113) and through that, figured out that it really is the MonoGame installer script that's prompting for input.  This is also something of a duplicate of [my community post](http://community.monogame.net/t/running-monogame-sdk-run-on-linux-without-confirmation-travis-ci/9567), albeit I documented my work-around there (use a custom `postinstall.sh` that doesn't prompt for confirmation).

**Comment by persn** [comment]
It sounds like you just need to try out some bash magic rather than having an issue with MonoGame.  Does this work for you? `yes y | sudo ./monogame-sdk.run;`

[Full Travis script](https://github.com/persn/Hero6/blob/develop/feature/monogame-upgrade-2/.travis.yml)

**Comment by cra0zy** [comment]
Yea, @persn is totally right, there are no modifications that should be done on MG side.

**Comment by ashes999** [comment]
I'm pretty sure I tried that, as well as every combination of `echo`, piping, redirecting output, etc. to no avail. I'll try it again and report back.

**Comment by cra0zy** [comment]
`echo y | sudo ./monogame-sdk.run` works just fine, totally bypasses the prompt.

**Comment by ashes999** [comment]
Well, I guess we can close this.

Can someone please document this somewhere easily visible so that future searchers can find this information? (Admittedly, I'm not an expert on Linux or MonoGame.)

**Comment by ashes999** [comment]
Interestingly, Travis complains that `monogame-sdk.run` doesn't exist:

 > $ echo y | sudo ./monogame-sdk.run
> sudo: ./monogame-sdk.run: command not found
> The command "echo y | sudo ./monogame-sdk.run" failed and exited with 1 during .

Relevant build is [here](https://travis-ci.org/deengames-prototypes/eman-stories-v2/builds/265810561).

I confirmed that I spelled everything right, etc. and this should work.  Travis.yml looks like:

```
language: csharp
install:
  # MonoGame 3.6
  - sudo apt-get install gtk-sharp3
  - wget http://www.monogame.net/releases/v3.6/monogame-sdk.run  
  - echo y | sudo ./monogame-sdk.run
  - nuget restore
  # [...]
script:
  - msbuild
  - [...]
```

Please tell me I'm doing something wrong and this actually is supposed to work.

**Comment by cra0zy** [comment]
> Can someone please document this somewhere easily visible so that future searchers can find this information? (Admittedly, I'm not an expert on Linux or MonoGame.)

It's literally a basic Linux command...

> Interestingly, Travis complains that monogame-sdk.run doesn't exist:

On Linux you need to give files executable permission before executing them, do:
```
chmod +x monogame-sdk.run
```
