### ISSUE TITLE
MSBuild gets stuck when compiling a project with missing Content.mgcb

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#5883]
[This PR](https://github.com/MonoGame/MonoGame/pull/4997) has modified heavily MonoGame.Content.Builder.targets with an unexpected consequence:

When compiling a project with missing content.mgcb (because it's not needed) MSBuild gets stuck!, as if it's doing some sort of infinite loop.

Now I have multiple MonoGame utility assemblies that leave visual studio blocked forever when I try to compile them!

Steps to reproduce:

Create a new Monogame Windows Project
Delete content.mgcb
Compile

**Comment by KonajuGames** [comment]
I submitted a potential fix for this (#5886).  Try that branch or try the [installer](http://teamcity.monogame.net/viewLog.html?buildId=51930&tab=artifacts&buildTypeId=MonoGame_PackagingWindows) generated from it.  Let me know if it fixes the issue.

**Comment by vpenades** [comment]
@KonajuGames yes, just checked and it seems the problem has been solved.

Thanks!

**Comment by tomspilman** [comment]
Thanks for verifying the fix @vpenades !
