### ISSUE TITLE
Fullscreen + Alt Tab still an issue in latest MonoGame 3.7.0.753 Development build

### ISSUE THREAD

**Issue by AgisisTheCoder** [MonoGame/MonoGame#5885]
I put together a video that shows the issue is still persisting. I saw that the latest dev build had some fixes committed 4 days ago for this issue, but it appears to persist at least on my box. 

VIDEO: https://youtu.be/1hT_YOruTdk

Machine:
1) Windows 10, 64-bit, Latest Update Pack installed as of 8/19/2017
2) NVIDIA

Steps taken to reproduce :
1) Uninstalled Monogame v3.7.0.744
2) Installed Monogame v3.7.0.753
3) Cleaned the projects
4) Rebuilt
5) Run the game in FULLSCREEN mode
6) ALT-TAB out to the desktop

Result:
1) Game icon is not visible on the task bar.
2) The game is still running as a background process (interestingly enough, OBS was still able to capture it!)
3) Holding down ALT-TAB also shows that the game process is not accessible
4) I have to End Task from the task manager to shut the game down.

Thoughts?

**Comment by cra0zy** [comment]
WindowsDX or DesktopGL?

**Comment by AgisisTheCoder** [comment]
WindowsDX

**Comment by AgisisTheCoder** [comment]
Also, quick note that I pulled up a much simpler test project that just loads an FBX file and texture and was able to reproduce it there once I put it in full screen. I wanted to ensure we weren't doing something silly in our main game.

**Comment by KonajuGames** [comment]
I'll have a look at this now.  It may be related to a recent marge (#5585), so I'll start there.

**Comment by KonajuGames** [comment]
@AgisisTheCoder I have submitted a fix for this in #5887.  It would be great if you could give that version a go when you can.

**Comment by AgisisTheCoder** [comment]
I installed v3.7.0.759. It is not much better, but it is different. The result this time is that a white box stays in the middle of my screen after alt-tabbing out, but the application icon at the bottom is still missing and there is way back to the application by alt-tabbing. I have to end-task. Let me know if you want a video, but that pretty much sums it up.

**Comment by KonajuGames** [comment]
Those are the symptoms I was getting before my fix. Just make sure you got
the installer from the PR (available in the artifacts in the Windows
packaging build step), not the latest develop installer. It won't shear in
the latest develop installer until it the PR is merged.

**Comment by Jjagg** [comment]
@AgisisTheCoder You can get the installer from this page: http://teamcity.monogame.net/viewLog.html?buildId=51975&tab=artifacts&buildTypeId=MonoGame_PackagingWindows
That's v3.7.0.758 which is the one you need. I just checked and v3.7.0.759 is a build from the develop branch, which means it does not have the fix in.

**Comment by AgisisTheCoder** [comment]
I will test this evening!

**Comment by AgisisTheCoder** [comment]
Looks like it fixed it guys. Thanks so much. Monogame is great. If you are bored, look what we have wrought with Monogame! You can find out about our little game at www.tinyrts.com (the trailer is almost 7 months old so a LOT has improved since then). Newer videos are on Twitter at https://twitter.com/TinyRTS. It's a online multi-player 4x RTS space game. There are only two of us and we are two years into its construction. Still a ways to go before release though.

Monogame was PERFECT for our needs. I also just saw you have Monogame media files, so I will add the Monogame logo to our credits page in-game if that's OK. Thanks again.

Do you know when this will go out with the next dev build?

**Comment by tomspilman** [comment]
Thanks for testing this @AgisisTheCoder !

> You can find out about our little game 

Looks great...  i've linked your trailer to our YouTube playlists.

https://www.youtube.com/playlist?list=PLTWJSIs82sS3UqutUWD-GqKidN6cHHfzE

Is it ok to link to your other videos?  They were marked private which is why I ask.

If you throw a `#MonoGame` on your tweets the official MG twitter should see them and retweet them to get you more eyeballs.

> Monogame logo to our credits page in-game if that's OK

Sure... just grab what you need from:  https://github.com/MonoGame/MonoGame.Logo

> Do you know when this will go out with the next dev build?

I'll be merging it now... so should be in the develop build in the next 20 minutes.

**Comment by AgisisTheCoder** [comment]
Yes, feel free to deep link them. Mostly, those tweets are just updates as
we address issues and add new features. I figured it was time to get a
Twitter up and running as we get closer to the end.  I need to get a full
gameplay video recording done. We play our own game every single day for
fun and it's held up, so I think we are onto something. It's pretty intense
and stressful as far as multiplayer goes. We loved Galactic Conquest back
in the early 90's and always wanted to make our own, but with a modern
starcraft'ish interface and have it play very quickly.

I'll look into the media and will definitely add the hashtags going
forward.
Thanks so much for all you do. I'll keep an eye out for the build.

**Comment by mdrejhon** [comment]
# UPDATE: This bugfix breaks #6294
