### ISSUE TITLE
Monogame 3.6 Pipeline tool does not work with Visual Studio 2017

### ISSUE THREAD

**Issue by diliupg** [MonoGame/MonoGame#5889]
This is a problem which has been going on for some time with no solution still. All versions of monogame give the same error of freetype file

**Comment by cra0zy** [comment]
Install http://www.microsoft.com/en-NZ/download/details.aspx?id=30679, it should solve it.

Also this should be a duplicate of: #3556

**Comment by diliupg** [comment]
Thanks. All's well now.

**Comment by cra0zy** [comment]
Closing since this is a duplicate of: #3556
