### ISSUE TITLE
MGCB.exe workingdir arg is fragile

### ISSUE THREAD

**Issue by dazinator** [MonoGame/MonoGame#5891]
If you call `MGCB.exe` and supply a `/workingDir` argument, it only has an impact if it is early in the list of args.

For example - this fails because it looks like the importer tries to resolve source files, before the working dir is set:

```
"C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"C:\Users\darre\Source\Repos\MonoGame\Sample\Content\Content.mgcb" /platform:Windows /outputDir:"C:\Users\darre\Source\Repos\MonoGame\Sample\Content\bin\Windows\Content" /intermediateDir:"C:\Users\darre\Source\Repos\MonoGame\Sample\Content\obj\Windows\Content" /workingDir:"C:\Users\darre\Source\Repos\MonoGame\Sample\Content"
Build started 22/08/2017 22:38:53

C:/WINDOWS/system32/Test.fx
C:/WINDOWS/system32/Test.fx: error: The source file 'C:/WINDOWS/system32/Test.fx' does not exist!
```

Took me a while to figure out what was wrong here as was not initially obvious from command line usage. Supplying /workingDir as the first argument works as expected.

**Comment by cra0zy** [comment]
Not a bug, this is how mgcb works.
