### ISSUE TITLE
fix xbuild 

### ISSUE THREAD

**Issue by dazinator** [MonoGame/MonoGame#5892]
#4977 broke xbuild.

We need to either revert it, or get xbuild working. One day we can drop xbuild as will be replaced by msbuild, but that day isn't yet today apparantly.

**Comment by dazinator** [comment]
PR Submitted and needs feedback / refinement.

**Comment by dellis1972** [comment]
I worked around the `xbuild` issue in https://github.com/MonoGame/MonoGame/pull/5897

**Comment by dellis1972** [comment]
This is now fixed.
