### ISSUE TITLE
MG Content Builder targets - Path's format is not supported

### ISSUE THREAD

**Issue by monobeginner** [MonoGame/MonoGame#5895]
Hello,

Actually I got MG 3.7.0.759 and I have problem during build of Android project. Output from build:
`C:\Program Files (x86)\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets(73,5): error MSB3191: Unable to create directory "D:\Projects\Game\Game.Android\D:\Projects\Game\GameShared\Content\bin\Android\Content". The given path's format is not supported.`

It seems that path is constructed not properly.  I tried also build 756 - doesn't help. Issue does not exist on Monogame 3.5 - it builds without errors.

This is how looks my MGCB file's global properties section:
```
#----------------------------- Global Properties ----------------------------#
/outputDir:bin/$(Platform)
/intermediateDir:obj/$(Platform)
/platform:NativeClient
/config:
/profile:Reach
/compress:False
```

What kind of data can I give you to help localize of problem ? Maybe can I turn on some extra diagnostics debugger (verbose output log file ? ) ? Any workaround for this ?

MonoGame.Content.Builder.targets file can be found on github here: 
https://github.com/labnation/MonoGame/blob/master/MonoGame.Framework.Content.Pipeline/MonoGame.Content.Builder.targets

**Comment by KonajuGames** [comment]
From that output, am I correct in that you have two projects in your solution, one for Android and one shared, and the MGCB file is in the shared project?

**Comment by monobeginner** [comment]
Exacly, that's the case. I reference my Shared project within Android project and MGCB builds output for Android if this project is selected. Here is how I reference Shared project in Game.Android.csproj:
`<Import Project="..\GameShared\GameShared.projitems" Label="Shared" />`

Here is how my look my Shared project .shproj file:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Globals">
    <ProjectGuid>...</ProjectGuid>
    <MinimumVisualStudioVersion>14.0</MinimumVisualStudioVersion>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\CodeSharing\Microsoft.CodeSharing.Common.Default.props" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\CodeSharing\Microsoft.CodeSharing.Common.props" />
  <Import Project="GameShared.projitems" Label="Shared" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\CodeSharing\Microsoft.CodeSharing.CSharp.targets" />
  <Import Project="$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets" />
</Project>
```

Part of GameShared.projitems:
```
<ItemGroup>
    <MonoGameContentReference Include="$(MSBuildThisFileDirectory)Content\Content.mgcb">
      <SubType>Designer</SubType>
    </MonoGameContentReference>
  </ItemGroup>
```

As I mentioned before, project builds fine with MonoGame 3.5. Can I provide you some more information ?

**Comment by KonajuGames** [comment]
That should be enough information.  There was a change to the .targets file to help with multiple content projects, and that seems to have lead to this issue.  We'll get this fixed.

**Comment by monobeginner** [comment]
Tried newest build #3.7.0.790 - bug still exists. Please let me know when it will be fixed, so I will try and give feedback.

**Comment by monobeginner** [comment]
Any update on this ?

**Comment by Jjagg** [comment]
@dellis1972 #5897 should have fixed this, right?

**Comment by cra0zy** [comment]
@Jjagg read the PR description, it did not fix it.

**Comment by monobeginner** [comment]
Any update on this ? This is critical issue for me.

**Comment by cra0zy** [comment]
It should be fixed in devel, I tried it 3 days ago.

**Comment by tomspilman** [comment]
@monobeginner - Can you verify things are working now with the latest `develop` branch?

**Comment by monobeginner** [comment]
@tomspilman - Sure, I would like to. Is Windows Installer no longer available in artifacts from build server ? Could not find installer in artifacts http://teamcity.monogame.net/viewLog.html?buildId=55845&buildTypeId=MonoGame_DevelopWin&tab=artifacts

**Comment by monobeginner** [comment]
Verified with 3.7.0.960, builds without problem. But .. now my game has smaller screen on edges, about 5% on left and 5% on right edge (landscape). Something has changed ? Is it known issue ? Any ideas how to fix this ? This is how I fetch screen size:
```
graphics.GraphicsDevice.Viewport.TitleSafeArea.Width;
graphics.GraphicsDevice.Viewport.TitleSafeArea.Height;
```

**Comment by cra0zy** [comment]
Closing as the original issue got fixed.
