### ISSUE TITLE
[PipelineTool] / dev branch:  fails to build models with a custom modelprocessor with b.790

### ISSUE THREAD

**Issue by MarcVador** [MonoGame/MonoGame#5903]
Hi !
Tested the latest build when I encountered a problem.

When I build the content with the Build menu, on the first model using my modelprocessor, it throws
"MGCB has ceased working"
And 
![image](https://user-images.githubusercontent.com/19704413/29776367-b2b715f8-8c08-11e7-87f1-de8299d539c4.png)

but when i build it from the right click menu on the model, it works (at least it throws no error)

It used to work on previous builds (up to dev build 768 at least, 790 fails too), and I have not changed any path in my project since then.

**Comment by dellis1972** [comment]
This should be fixed by https://github.com/MonoGame/MonoGame/pull/5904

**Comment by MarcVador** [comment]
It builds now with the buid815 ;) thanks

**Comment by Jjagg** [comment]
@MarcVador Can you close this issue?

**Comment by MarcVador** [comment]
Sure, no problem. I thought this one done by the "fixer" ;)
