### ISSUE TITLE
Pipeline tool should add standard keyboard shortcuts to access the main menu items

### ISSUE THREAD

**Issue by dneelyep** [MonoGame/MonoGame#5916]
In the Pipeline tool, I can press "Alt" to highlight the main menu bar (with options File, Edit, View, Build, Help). Ideally, I could use the below shortcuts to immediately open menu options, rather than having to press Alt+Up/Down/Left/Right Arrow to navigate to the correct menu.

- [x] File: Alt+F
- [x] Edit: Alt+E
- [x] View: Alt+V
- [x] Build: Alt+B
- [x] Help: Alt+H

For an example, see the behavior of Visual Studio.

**Comment by dneelyep** [comment]
If this is accepted, I don't mind implementing it - should be pretty simple.

**Comment by Jjagg** [comment]
> If this is accepted, I don't mind implementing it

Awesome! :)

The Pipeline Tool uses [Eto.Forms](https://github.com/picoe/Eto), not WinForms directly. Maybe there are some differences in how this needs to be implemented. @cra0zy Do you know this part of the API? Anything @dneelyep needs to know?

**Comment by cra0zy** [comment]
Try adding:
```c#
menuFile.Shortcut = Application.Instance.AlternateModifier | Keys.F;
```
bellow: https://github.com/MonoGame/MonoGame/blob/develop/Tools/Pipeline/MainWindow.eto.cs#L259

If that doesn't work comment here and I'll explain how to directly interact with WPF.

**Comment by dneelyep** [comment]
@cra0zy I attempted the above method, but it ended up not working. No errors were thrown, but the above code resulted in nothing happening when the shortcut was pressed. Instead I ended up adding this, which works on my system (Win 10):

`menuEdit.Text = "&Edit"; `

I'm assuming this method works on Mac/Linux - haven't tested though.

**Comment by cra0zy** [comment]
Yup, works on Linux.
