### ISSUE TITLE
Dispose singleton when "Do not keep activities" option is selected

### ISSUE THREAD

**Issue by monobeginner** [MonoGame/MonoGame#5922]
Hello,

My Android game crashes when "Do not keep activites" option is selected in developer options. Steps to reproduce:

1. Select "Do not keep activities" in developer options
2. Launch game
3. Press home button
4. Resume game

Notice that activity is recreated and so on MonoGame framework will be reinitialized. Game.Intiialize() will be called for the second time, I have some singletons initialization there which were initialized on first Game.Intialize() call. Where should I dispose singletons in such case ? I think UnloadContent(..) callback is not called in this scenario.

Piece of code:
```
public static void Initialize()
        {
            if (INSTANCE != null)
            {
                throw new Exception("AppSettings instance is already initialized");
            }
            INSTANCE = new AppSettings();
        }
```

**Comment by mrhelmut** [comment]
```Game.UnloadContent()``` is called if the host activity gets destroyed. You can free stuff here.

You might also want to manage your singletons differently by using a singleton pattern:

```
class AppSettings
{
        private static AppSettings_instance = null;
        private AppSettings() { }

        public static AppSettings Instance
        { 
                get 
                {
                         if (_instance == null)
                                 _instance = new AppSettings();
                         return _instance;
                } 
        }
}
```

And then access your singleton through ```AppSettings.Instance```.

**Comment by KonajuGames** [comment]
Override the `Game.Dispose(bool)` method and destroy your singleton.

        protected override void Dispose(bool disposing)
        {
            // Destroy your singleton here
            // ...
            base.Dispose(disposing);
        }

The `Game` object is disposed on Android when the `Activity.OnDestroy()` method is called.

Note that singletons on Android are generally not the best approach as static data lives in the process, which outlives the activity.  This is why the singleton still appears allocated when the activity is recreated because the process remained.
