### ISSUE TITLE
 XMLImporter failure - Unable to load one or more of the requested types (Android)

### ISSUE THREAD

**Issue by littlebeast** [MonoGame/MonoGame#5924]
(still not really sure this is a bug, but)
I wrote a simple class, serialized it using the IntermediateSerializer, and then attempted to load it with the Content Pipeline tool.  But, every time I do, it gives the error
`EXEC : warning : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

I have a reference to my game's debug DLL, so it should be capable of finding that.  The class is really freakin' basic - literally two strings, a vector2 and a List of ints (plus a private List of its own type, but that doesn't get serialized) and yet it says it can't find one of the types.  I even tried adding the Monogame.Framework and System dlls as references to the pipeline, in case it was being stupid, but no dice.

More details on the [forum thread](http://community.monogame.net/t/xmlimporter-failure-unable-to-load-one-or-more-of-the-requested-types/9669) if you need them.

What the heck is going wrong??

**Comment by KonajuGames** [comment]
As noted in that forum thread, I tried to reproduce with your sample class and XML file, but it succeeded for me.

**Comment by littlebeast** [comment]
Well, my problem is solved now (porting it to a library worked, I just did it wrong before) but this may be an issue in the future for people targeting Android, so I'm not going to close the issue myself.  If you wish to investigate more, [this commit](https://github.com/littlebeast/WrathOfTheGods/tree/cba65e7f74b17b9f4e7ce447e67108df11af21e9) should still have the error.  If not, you can go ahead and close it.
