### ISSUE TITLE
Provide SHA-256 checksums for installers

### ISSUE THREAD

**Issue by remmah** [MonoGame/MonoGame#5929]
The macOS MonoGame installer is unsigned and has to be downloaded in the clear from monogame.net. Would it be possible to provide the SHA-256 digest for each installer on a TLS-enabled site? Perhaps in the notes for each release tag here on GitHub?

**Comment by tomspilman** [comment]
I can't say i know anything about doing this, but willing to do it as long as it can be 100% automated.

**Comment by remmah** [comment]
Probably the easiest way is to run `[sha256sum](https://help.ubuntu.com/community/HowToSHA256SUM)` on each installer after it's built and log the output to a place where whoever writes the release notes can securely access that output. I'm new to MonoGame so I'm not familiar with the build process and whether it offers an opportunity to run a script after the installers are built.

An alternative to providing SHA digests is to just make the installer downloads accessible via HTTPS (either on GitHub or another site with a valid TLS cert). Depending on how monogame.net is hosted, it may be possible to set up an automatically-renewing TLS cert from [Let'sEncrypt](https://letsencrypt.org/).

Either way, the concern is making sure that the bits people get when downloading the installers are the same as what the MonoGame team uploads, with nothing modified or corrupted in-transit.

**Comment by harry-cpp** [comment]
Installers have been replaced by templates/nugets.
