### ISSUE TITLE
[Android] Viewport size issues

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5935]
Since #5410, I am running into ```GraphicsDevice.Viewport``` issues when using fullscreen or immersive mode.

It seems that the viewport is too small and offset'd by the size of the action bar.

This is because the initial ```Viewport``` size is based on ```CurrentDisplayMode```, which uses ```AndroidGameView.GameView.Width``` / ```Height```, while ```PreferredBackbufferWidth``` / ```Height``` gets their value from ```ClientBounds``` (set from ```Context.Resources.DisplayMetrics```).

On my device, ```AndroidGameView.GameView``` is 600x1024 while ```Context.Resources.DisplayMetrics``` is 600x976.

I believe this is due to ```MonoAndroidGameView``` being created after the ```Context``` is queried for the display size and then returns values for non-fullscreen mode. Potential fix would be to initialize ```ClientBounds``` after the view is created and using its size instead of the display metrics.

Thoughts @dellis1972 @roponator ?

**Comment by dellis1972** [comment]
no sure what the best approach would be in this case. I'd have to look at the code again.

**Comment by dellis1972** [comment]
@mrhelmut I have a local change which creates the `_clientBounds` using the GameView values and don't see any bad effects in my testing so far.

**Comment by mrhelmut** [comment]
@dellis1972 Would you mind pointing me to this branch? I'll give it a try.  :)

**Comment by dellis1972** [comment]
@mrhelmut https://github.com/MonoGame/MonoGame/pull/5975

**Comment by dellis1972** [comment]
@mrhelmut how are you setting immersive mode? I can get the navigation bar to disappear but no matter what I do the Action bar is always present. and `ActionBar` on the activity is null.

**Comment by dellis1972** [comment]
@mrhelmut never mind. It was me lol

**Comment by ApmeM** [comment]
Hi, sorry for commenting to old issue.

Is there a workaround I can use for 3.6 version (As I can see this fix is not released).
On my Meizu m3s it hide almost half of screen.
And another problem here is that mouse is still full screen, only viewport is broken an it leads to mispointing when clicking on it.
