### ISSUE TITLE
[Android] Black screen after splash screen and before game

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5936]
Another one since #5410 :)

There is a black screen appearing after the splash screen and before the game runs.

I haven't looked into this one yet.

@dellis1972 @roponator

**Comment by roponator** [comment]
That is for Android? And by splash screen you mean the native android splashscreen shown at start?

Can you repro this with a simple project?

**Comment by mrhelmut** [comment]
Yes, between the native android splashscreen and the first draw from the game.

Let me check if I can come up with a minimal project, it happens on a full game.

**Comment by dellis1972** [comment]
@mrhelmut its possibly a Content Load exception. I've seen that before, but I thought we threw the exception on the main thread.

**Comment by dellis1972** [comment]
@mrhelmut any future info on this?

**Comment by mrhelmut** [comment]
I haven't looked more into this yet.

**Comment by roponator** [comment]
I won't be looking at this for ~14 days, have some more critical stuff first.
