### ISSUE TITLE
MonoGame.Build.Tasks.dll not put into the right folder at installation ?

### ISSUE THREAD

**Issue by MarcVador** [MonoGame/MonoGame#5939]
Got error when updated to monogame latest build (the problem started after one of the builds folowing the 828):
"Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4062	The "MonoGame.Build.Tasks.CollectContentReferences" task could not be loaded from the assembly C:\Program Files (x86)\MSBuild\MonoGame\v3.0\MonoGame.Build.Tasks.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\MSBuild\MonoGame\v3.0\MonoGame.Build.Tasks.dll' or one of its dependencies. Le fichier spécifié est introuvable. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask"

cf http://community.monogame.net/t/trouble-getting-started-with-monogame-monogame-build-tasks-collectcontentreferences-solved/9704

Solution seems to manually move the file to the parent folder.

When I do this, the error has vanished (that's now normal), but I seem to be getting the same problem as #5904 <- #5903, building a project takes ages. The only way for me to stop it is to kill MSbuild.exe in the taskmanager

Changes between the last build  i know working (828) vs the latest:
![image](https://user-images.githubusercontent.com/19704413/30428214-02bd8490-9953-11e7-864d-8a53583d06a8.png)

**Comment by dellis1972** [comment]
a PR is up for this issue https://github.com/MonoGame/MonoGame/pull/5940.

**Comment by MarcVador** [comment]
With the latest build (891), I still got the same problem: building a project without a mgcb file takes an infinite time to build
After 20minutes, still at the same point:
![image](https://user-images.githubusercontent.com/19704413/30477728-740c81c6-9a0e-11e7-9434-55c3da560e14.png)

**Comment by dellis1972** [comment]
@MarcVador I think I have repo'd your issue. I'll look at it over the weekend.

**Comment by dellis1972** [comment]
@MarcVador looks like the fix was fairly simple :) https://github.com/MonoGame/MonoGame/pull/5945

**Comment by MarcVador** [comment]
Well done :) Thanks a lot. I was about to add a "dummy" content file with no data to all my projects that don't have an mgcb, but this is no more needed.
