### ISSUE TITLE
MonoGame Pipeline Tool: Generate MipMaps

### ISSUE THREAD

**Issue by skyelord2015** [MonoGame/MonoGame#5946]
Turning this option on doesn't stay on sometimes (even if you save and build). Sometimes if you do it twice it works. Double clicking the "false/true" or using the checkbox doesn't seem to help.

Building then saving or saving then building doesn't help either.

This is an example texture I was having trouble with
![txcobblestonepaving](https://user-images.githubusercontent.com/25881489/30513784-27f55ad0-9b01-11e7-9545-04e5132954af.png)

**Comment by cra0zy** [comment]
I am unable to reproduce this. Are you sure that you are closing the cell after changing the value?

**Comment by skyelord2015** [comment]
Ah clicking to a different cell makes the value stay. Slightly odd behaviour but I can live with it. Happy to just close it.
