### ISSUE TITLE
ScissorRectangle + Viewport renders the wrong part of the screen.

### ISSUE THREAD

**Issue by vchelaru** [MonoGame/MonoGame#5947]
**Bug**
If GraphicsDevice.ScissorRectangle is combined with GraphicsDevice.Viewport, the resulting area of the screen which is drawn does not match the expected intersection. Furthermore, the portion of the screen does not match the portion of the screen drawn when the code is executed in Microsoft XNA 4.0 (PC).

**Code**
Here is code to reproduce the bug:

```
public class Game1 : Microsoft.Xna.Framework.Game
{
    GraphicsDeviceManager graphics;

    SpriteBatch spriteBatch;
    Texture2D textureFile;

    public Game1() : base ()
    {
        graphics = new GraphicsDeviceManager(this);

        graphics.PreferredBackBufferWidth = 400;
        graphics.PreferredBackBufferHeight = 400;
    }

    protected override void Initialize()
    {
        textureFile = Content.Load<Texture2D>("textureFile");
        spriteBatch = new SpriteBatch(graphics.GraphicsDevice);
        base.Initialize();
    }

    protected override void Draw(GameTime gameTime)
    {
        GraphicsDevice.Clear(Color.Black);
        graphics.GraphicsDevice.Viewport = new Viewport(100, 100, 200, 200);
        var scissorTestEnabled = new RasterizerState();
        scissorTestEnabled.CullMode = CullMode.None;
        scissorTestEnabled.ScissorTestEnable = true;

        graphics.GraphicsDevice.ScissorRectangle = new Rectangle(0, 0, 200, 200);

        spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, 
            SamplerState.PointClamp, DepthStencilState.Default, scissorTestEnabled);

        spriteBatch.Draw(textureFile, new Rectangle(0, 0, 400, 400), Color.White);
        spriteBatch.End();

        base.Draw(gameTime);
    }
}
```

**Results**
MonoGame Desktop GL (rendered red portion is too far down):
![image](https://i.imgur.com/GptY6dB.png)

XNA (correctly rendered):
![image](https://i.imgur.com/DR8Myuq.png)

Image Breakdown (XNA, correct rendering):
![image](https://i.imgur.com/hMsaeG0.png)

**Version Info**
This was tested on MonoGame Desktop GL 3.6 and 3.7 (build pulled at the beginning of August). Also, this was tested on Android 3.6.

**Comment by tomspilman** [comment]
My bet is that this doesn't occur under the Windows DirectX target platform.

@dellis1972 - Whatever the bug here ends up being.  We should expand or improve the [existing scissor unit tests](https://github.com/MonoGame/MonoGame/blob/develop/Test/Framework/Graphics/ScissorRectangleTest.cs) to expose the bug.

**Comment by dellis1972** [comment]
I have repo'd the issue. 
@vchelaru is it me or is the box a full box width lower than it should be.. i.e is it flipped?

**Comment by dellis1972** [comment]
OK the problem is the code on this line https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.OpenGL.cs#L1004

its currently

```sharp
scissorRect.Y = _viewport.Height - scissorRect.Y - scissorRect.Height;
```

I think it should be 
```csharp
scissorRect.Y = scissorRect.Y - scissorRect.Height;
```

**Comment by dellis1972** [comment]
Sorry 
```csharp
scissorRect.Y = scissorRect.Y + scissorRect.Height;
```

**Comment by dellis1972** [comment]
Nope that is wrong too. We need to take into account the height of the window in order to flip this correctly I think.. the problem is we are using the current _viewport... 
Orrrr. is it the fact that the viewport is not reset between Draw calls...

**Comment by dellis1972** [comment]
ok the problem is the Viewport is not reset to the window size after a frame. In XNA it gets reset each frame to the window size.

**Comment by dellis1972** [comment]
ok maybe not.. weird.. but we still need to use the Presentation Parameters I think

**Comment by vchelaru** [comment]
Sorry for not replying to this earlier, just saw the message.

The problem seems to be that the viewport's Y is added twice. I can hack
around the issue by subtracting the viewport Y from the scissor Y and it
*seems* to fix it in a few test cases.

--Victor Chelaru--
801 391 5271
hangouts: VicChelaru@gmail.com
skype: armysarj
www.flatredball.com

**Comment by dellis1972** [comment]
@vchelaru I don't think it is the `Y`. We need to flip the Y value for the scissor rect when not using a RenderTarget on OpenGL cos 0,0 is bottom left not top left.. We currently use the `_viewport.Height` to figure out what the total height of the window is.. but in your sample the viewport is changed to have a height of 200.. so we end up with a flipped Y value of 0, when it should have been 200. 

So in this case I think the code should be 

`scissorRect.Y = PresentationParameters.BackBufferHeight - (scissorRect.Y + scissorRect.Height);`

**Comment by dellis1972** [comment]
The Scissor rect seems to be dependent on the Window Size in XNA not the current viewport.

**Comment by vchelaru** [comment]
Right the scissor rect is based on the window, and the intersection of the
viewport (in my tests) is how it decides what actually shows up. So...maybe
the bug has nothing to do with the viewport? I'm not sure.

--Victor Chelaru--
801 391 5271
hangouts: VicChelaru@gmail.com
skype: armysarj
www.flatredball.com

**Comment by dellis1972** [comment]
@vchelaru I put a PR up #5977
