### ISSUE TITLE
Monogame is hanging when soft_oal.dll is in the folder

### ISSUE THREAD

**Issue by Thraka** [MonoGame/MonoGame#5966]
Trying to track down an [issue with my engine](https://www.reddit.com/r/sadconsole/comments/721x9i/sadconsole_linux_support/). A user was noting that the window fails to close on Linux and Windows. Through testing he can get the window to close if **soft_oal.dll** is removed on the windows machine. On linux, he cannot get it to close properly. 

Can anyone help investigate? Here is [his original project](https://bitbucket.org/Chris3606/sadcon-closebug) which seems more tuned for linux. I've tweaked it for windows [(download it here)](https://github.com/MonoGame/MonoGame/files/1335679/Chris3606-sadcon-closebug-1034adfa2c39.zip) if someone wants to try and debug in Visual Studio.

Originally I was able to run the exe without the debugger attached and the window would close. However, that doesn't seem to happen anymore and no matter what, I get a hang. If I delete soft_oal.dll the exe and debugger work as expected. (Although it takes too long for the window to close, it does in a few seconds)

**Comment by mrhelmut** [comment]
I have noticed the slight close time that #5850 introduced, but having to remove soft_oal.dll sounds weird. It shouldn't even work anymore.

Looking at your code, I believe this a problem with how https://github.com/Thraka/SadConsole handles the game loop.

**Comment by Thraka** [comment]
Can you point to the specific thing in the game loop you are talking about?

**Comment by mrhelmut** [comment]
This is an assumption because I don't have the time to really dig into your sample, but it would seem that SadConsole may have a different ```Game``` class lifecycle and usage. You might want to check if MonoGame systems are initialized and disposed correctly and in the same order as the default MG usage.

The thing about soft_oal.dll is really puzzling me though.

Have you tried to pause debug during the freeze to see where it's spinning?

**Comment by Thraka** [comment]
I did but nothing comes up. The code exits the `Game.Run` method and then exits `Program.Main`. I just did a test and didn't call anything related to SadConsole and I still get the hang.

```csharp
class Program
{

    class tempGame: Microsoft.Xna.Framework.Game
    {
        public tempGame()
        {
            new GraphicsDeviceManager(this);
        }
    }

    static void Main(string[] args)
    {
        tempGame game = new tempGame();
        game.Run();
    }
}

**Comment by Thraka** [comment]
I just added `game.Dispose();` and it closes instantly with no problems, with the dll or without. I think this is the source of the issue. Whoops

**Comment by tomspilman** [comment]
Yeah...  most MG mains look like this:

```
    static void Main(string[] args)
    {
        using(var game = new tempGame())
           game.Run();
    }
```

So that the game is `Disposed()` when `Run` returns.

**Comment by Thraka** [comment]
Been working in my own world so long I totally spaced the using.. Since it generally exited every time until someone put the dll in the folder, I assumed I was doing what I should have been. Whoops!

Thanks for investigating with me.
