### ISSUE TITLE
GamePadState.PacketNumber stays 0 even when input is working.

### ISSUE THREAD

**Issue by monkeyharhar** [MonoGame/MonoGame#5971]
Only issue I could find that might pertain is [https://github.com/MonoGame/MonoGame/issues/4002](#4002)

I've set up breakpoints on GamePadState.GetButtonPressed(Buttons.A) and it returns true but PacketNumber never updates.

**Comment by tomspilman** [comment]
@monkeyharhar - What platform are you running on?  If Windows then are you using DesktopGL or Windows DirectX?

**Comment by monkeyharhar** [comment]
Oops, sorry, I should have specified. I am running on DesktopGL.

**Comment by cra0zy** [comment]
Yea, I never got around to implementing this since SDL does not posses a similar property (we could technically just increase PacketNumber on any gamepad event).

**Comment by monkeyharhar** [comment]
@cra0zy Any fix would be great! I am currently trying to reference PacketNumber to detect any input changes from a GamePad and as an early out in my Player input management code.

**Comment by augustozanellato** [comment]
Still not working on DesktopGL, add this to the documentation or fix this please.

**Comment by Jjagg** [comment]
Fixed in #6760.
