### ISSUE TITLE
MonoGame Template not in Visual Studio on Mac

### ISSUE THREAD

**Issue by Tattomoosa** [MonoGame/MonoGame#5981]
I followed the instructions in the documentation for [Mac setup](http://www.monogame.net/documentation/?page=Setting_Up_MonoGame_Mac) but none of the MonoGame templates show up in Visual Studio for Mac.

Running macOS Sierra 10.12.6 on a 2010 Macbook Pro (it is too old to upgrade the OS, if that might be the issue)

**Comment by gingerbeardman** [comment]
+1

**Comment by gingerbeardman** [comment]
I just found the solution...

- File > Extensions... > Gallery > Manage Repositories > (tick to enable Alpha channel)
- IDE extensions > MonoDevelop.MonoGame.Template > Install
- enjoy!

ref: http://community.monogame.net/t/add-templates-for-visual-studio-mac/9027/2

![screen shot 2017-10-10 at 00 17 55](https://user-images.githubusercontent.com/49612/31362518-cf048272-ad50-11e7-8d1f-36ff27591236.png)

**Comment by Jjagg** [comment]
@dellis1972 You made this extension, right?

**Comment by dellis1972** [comment]
@Jjagg yes I did. Its still a work in progress I'm afraid.

**Comment by ytn3rd** [comment]
Had a few bees and just jumped on to update an old project (wanted to start from scratch and refactor all the old code) for fun but I hit this issue. Appears the best way to do this at the moment is create your own Xamarin.iOS, Xamarin.Android (+ Xamarin.Mac, UWP, etc) projects, get your Game.cs setup correctly and then copy across the initialisation code from the [samples](https://github.com/MonoGame/MonoGame.Samples).

**Comment by cra0zy** [comment]
Fixed in 3.7.
