### ISSUE TITLE
Valid usage of MonoGame Logo Media question

### ISSUE THREAD

**Issue by AgisisTheCoder** [MonoGame/MonoGame#5982]
Hey guys,
  To honor our use of the awesome MonoGame Engine, I coded out a MonoGame splash intro for our game Dominari. Before making it available to our playtesters, I wanted to ensure this will be OK with the MonoGame team to use as our intro. I could not find any policy regarding the usage of the logos, so I thought it best to ask permission.

You can view it here: 
https://youtu.be/KQu_K6FenVs

**Comment by cra0zy** [comment]
@tomspilman @KonajuGames

**Comment by AgisisTheCoder** [comment]
I think we can close this one. I cleared its usage with both Press and Biz via Email. Thanks guys, and this probably shouldn't have been opened as a support issue.
