### ISSUE TITLE
[Android] Pipeline failing to check format

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5983]
Hello,

When trying to compress textures for an Android target, I noticed that depending on the source image format, the pipeline doesn't check for the correct requirement.

Using ETC1 compression, and depending on the PNG encoding, a 1920x1080 texture may build fine, or fail with a "must be power of 2" error.

Either the pipeline fails to check the requirements, or the error message is misleading and something else happens while processing the source file.

Here are example files: https://www.dropbox.com/s/l7ly2vpcom7ebql/selfies.zip?dl=0

Both are PNG 24bit, one works, the other fails, the only difference being the internal DPI of the files.

**Comment by KonajuGames** [comment]
The ETC1 spec does indeed only require multiple of four for texture dimensions.  PowerVR chipsets however will fail to load a ETC1 texture if it is not a power of two.  This is most likely due to the hardware support for their own PVRTC format and its requirements for power-of-two dimensions which has somehow bled over into its ETC1 support.  We cannot determine at content build time which particular chipset the end user will have, so we have to go with the lowest common denominator.

ETC1 is only used for opaque images (no varying  or non-opaque alpha values), and BGRA4444 is used for any images with alpha values.  Since BGRA4444 does not have the same PoT requirement, even on PowerVR chipsets, there is no PoT checks for those textures.

**Comment by mrhelmut** [comment]
> This is most likely due to the hardware support for their own PVRTC format and its requirements for power-of-two dimensions which has somehow bled over into its ETC1 support.

That explains a lot why I've been running into GL errors when loading some compressed textures on PowerVR devices.

> ETC1 is only used for opaque images (no varying or non-opaque alpha values), and BGRA4444 is used for any images with alpha values. Since BGRA4444 does not have the same PoT requirement, even on PowerVR chipsets, there is no PoT checks for those textures.

Strange thing is that the first texture outputs 2 completely different files when using compression or color format. It then fails to load if compressed, so maybe the BGRA fallback isn't working?

**Comment by KonajuGames** [comment]
There could be a bug there somewhere.  I'm not on my usual dev machine at the moment, but it shouldn't be too difficult to figure out.

**Comment by mrhelmut** [comment]
Here's what happens depending on the source file:
- is POT and has no transparency: ETC1 compressed
- has transparency (size doesn't matter): is converted to BGRA4444 and builds fine
- has no transparency and is NPOT: fails to build

I believe that it is very misleading that some NPOT textures build and some don't. Moreover, for some reason, BGRA4444 works better with file compression than the Color format.

I think the pipeline should be converting any NPOT texture to BGRA4444 if compression is selected and display a notice that it was used as a fallback.

**Comment by dellis1972** [comment]
I always found that ETC1 compassion artifacts are pretty horrible.

**Comment by KonajuGames** [comment]
BGRA4444 has its own artifacts (banding), but they can be mitigated.

BGRA4444 is smaller than Color because each pixel is 16-bit (4 bits per
channel) rather than the 32-bit of Color.

We could certainly use BGRA4444 for NPOT textures. Easy to do, and does
make sense.

**Comment by mrhelmut** [comment]
More bearable than PVRTC. ^^

The game I'm working on is 200MB without ETC1 and 100MB with. I'd rather have slight artifacts than coding an APK extension support because of Google Play 100MB limitation...

**Comment by dellis1972** [comment]
the APK extension support is a pain, but I do have an old branch which does have that support [1]
There is a ton of stuff in there.. Leadboard implementation via Google Play etc. But the changes were too big to get in at once. Never had the time to split it up :(

[1] https://github.com/dellis1972/MonoGame/commits/androidrewrite

**Comment by mrhelmut** [comment]
Thanks for sharing it! That may come to be quite handy.

**Comment by KonajuGames** [comment]
Added PR #6003 to address this.
