### ISSUE TITLE
[Android] Wrong backbuffer size after lockscreen

### ISSUE THREAD

**Issue by Ragath** [MonoGame/MonoGame#5997]
MonoGame gets confused about the backbuffer size when the viewport changes and the screen locks/unlocks. This can be seen by the background still being cleared to cornflower blue across the edges, while drawing a texture at 0,0 does not make it go all the way into the topleft corner.

1.  bring up the navbar
2. lock the screen
3. unlock the screen

Now MonoGame thinks the backbuffer is the size of the viewport, but in reality it never changed size.

**Comment by Jjagg** [comment]
Fixed in #5975.
