### ISSUE TITLE
Fix Texture2D.FromStream support for 1bit PNGs

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#6001]
Ran across a 1bpp PNG image that our existing `Texture2D.FromStream` would not load.

We should add this format to the unit tests and ensure it works.

You can download this white 1bpp texture here:  

  https://user-images.githubusercontent.com/103522/31480817-aafc0bde-aee5-11e7-9cb5-77491b4d3ae2.png

**Comment by KonajuGames** [comment]
As raised back in #2424 and with @rds1983's [StbSharp](https://github.com/rds1983/StbSharp) library, I'll have a go at integrating the StbSharp code into MonoGame (to avoid the extra assembly).

**Comment by tomspilman** [comment]
> I'll have a go at integrating the StbSharp code into MonoGame (to avoid the extra assembly).

I suggest making StbSharp the default for all platform except consoles for now.

Then remove all our old image loading code.

**Comment by KonajuGames** [comment]
That's the plan.

**Comment by rds1983** [comment]
Maybe I misunderstood the discussion, but wanted to say that StbSharp is already integrated in the MG: https://github.com/MonoGame/MonoGame/tree/develop/MonoGame.Framework/Utilities/Imaging
It is used for Texture2D.FromStream only for the DesktopGL version. And it seems to load fine the image attached to this ticket.

**Comment by KonajuGames** [comment]
I did remember it had been done, but didn't find it.  Probably because of the Utilities/Imaging directory.  I'll extend the DesktopGL version of `Texture2D.FromStream` to all platforms.

**Comment by KonajuGames** [comment]
STB doesn't support TIF or DDS.  Do we consider that much a loss?  XNA supported PNG, JPG, GIF.  STB supports PNG, JPG, GIF, BMP, PSD, TGA plus others that never get used in the real world.

**Comment by KonajuGames** [comment]
Added PR #6008 to fix this and use StbSharp for all implementations of `Texture2D.FromStream(GraphicsDevice, Stream)`.  More details in the PR description.

**Comment by KonajuGames** [comment]
@rds1983 If you update your StbSharp library, we could use ImageWriter in for `Texture2D.SaveAsJpg()` and `Texture2D.SaveAsPng()` since [JPG support](https://github.com/nothings/stb/commit/721c788fdb56dc98ccbc7cc4b6434d1ca2d8cef3#diff-469d4cb48b9965801e6c8cb7b92e46fe) has been added to stb_image_write.h back in March.

**Comment by rds1983** [comment]
I think SaveAsPng already uses StbSharp, while SaveAsJpg uses TinyJpeg(DesktopGL version only): https://github.com/MonoGame/MonoGame/blob/f726fb6c3ff48fcffa017c811339c4926a4565f4/MonoGame.Framework/Graphics/Texture2D.OpenGL.cs#L459.

However I'll surely port latest stb_image_write.h as it'll allow to drop TinyJpeg.
