### ISSUE TITLE
Request to make the Sdl class public, instead of internal

### ISSUE THREAD

**Issue by FrostFlame64** [MonoGame/MonoGame#6015]
Hello,
I'm a hobbyist developer using the MonoGame framework, and the recent change to abandon OpenTK caused me some issues that took me a while to work out.

Basically, while developing in a "sandbox" type setup, I create some additional WinForm windows that position themselves around the Main game window. These additional windows display some debugging information for me in a way that keeps the main screen uncluttered.

In order to keep the additional windows "maintenance free", they were set up listen to some events from the main window (EX: Move, Resize, FocusedChanged, etc) to auto position themselves. When MonoGame still used OpenTK, I simply used some reflection to get the wrapping OpenTK.GameWindow, and setup delegates on its events.

But since MonoGame now uses SDL2 for this, I basically had to roll my own "Window" wrapper, that basically polls for the SDL events to detect for movement/resize/focus and raise custom event handlers.

Doing that works fine for me, but in order for me to do this, **I basically had to copy/replicate everything from MonoGame's "Sdl" class into my own "SDL" class. They are nearly identical, which why I'm requesting that MonoGame just makes its Sdl class public.** Being able to just use that directly would be much easier.

As the title suggests: this is just a request. I got it to work fine by replicating it almost entirely (so I'm able to move on, even if this request is denied). I just felt that giving my use case might convince you to make it public (or if someone would suggest a different way for me to do this without polling SDL events).

Thanks for your time!

**Comment by Jjagg** [comment]
Hmm, I don't know about this. MG is basically a hardware abstraction layer, meaning it offers a cross-platform API to low level services like graphics and audio. If it exposes the internal, platform-specific implementations it might make users write code that is not as portable (which is an important goal of MG). At this point most functionality is available completely cross-platform. Ideally the public MG API would offer everything you need for an extension like this. It might help if you could say concretely what functionality you can't access through the public API @FrostFlame64 (as in what method calls and events).

It would definitely be nicer to expand the cross-platform API than to expose platform-specific internals.

**Comment by tomspilman** [comment]
> Hmm, I don't know about this.

Same here.   I don't think we should expose the low level bits that could change in the future.

It would be better to look into adding the high level features you are needing officially so it can be supported on all platforms.

Or... you do have the full source code, just modify it how you need it.

**Comment by cra0zy** [comment]
The SDL class that we have is not a full wrapper for the SDL library, but only a partial one, it just includes stuff that MonoGame needs. As such it should definitely not be public.

However if somebody wants to interact with SDL without writing their own wrappers... well they should use an existing binding: https://github.com/flibitijibibo/SDL2-CS

**Comment by mrhelmut** [comment]
I'm not quite sure to understand why you need to access these internals, can't you use the existing high level MonoGame events and API to surface those events to WinForm?
Alternatively, you can use WinForm events and channel them to MonoGame.
I've done both ways for our game editors (which are using WinForm or WPF) and I haven't felt the need to go into SDL or OpenTK internals.

Beside my comment, I agree with the other comments, and I feel like this is a edge case scenario which is a bit out of the scope of the original MonoGame design and I believe that working from source code should do the trick if need be.

Yet, I would be totally fine if we can come up with a new set of features that integrates well in the existing MonoGame design to ease this process.

Could you elaborate on your specific needs and what you ended up doing?

**Comment by FrostFlame64** [comment]
Sorry for the late response, I was sick for the last few days.
Here is a gif demonstrating the functionality I was trying to describe: https://www.dropbox.com/s/e3pg33x0mlwm8q1/d9bd844b0d99f35193141e85517407d1.gif?dl=0

As I said in my original post, I basically have some additional windows (for debugging purposes only) that are setup to stay "snapped" to the sides of the main window. They display some debugging information for me, in a way that avoids me having to show the data on the main window (cluttering up the view). Again, this is ONLY for debugging purposes; I have no intention of having these snapping windows when developing an actual game. They're only useful as I play in a "sandbox" environment to write and test custom engine code.

When MonoGame still used OpenTK, this simple snippet is what I'd use:
```
/// <summary>
/// Gets the MonoGame wrapping form for the specified window.
/// </summary>
/// <param name="gameWindow">The window to get the wrapping form from.</param>
/// <returns>The MonoGame form wrapping this window, or null if it's not using MonoGame.</returns>
public static OpenTK.GameWindow GetForm(this GameWindow gameWindow)
{
    // Old Logic - MonoGame 3.5 and lower
    Type type = gameWindow.GetType();
    FieldInfo field = type.GetField("window", BindingFlags.NonPublic | BindingFlags.Instance);
    if (field == null)
    {
        return null;
    }
    else
    {
        return field.GetValue(gameWindow) as OpenTK.GameWindow;
    }
}
```
The OpenTK.GameWindow had the events I needed (Resize, Move, FocusChanged) to keep the additional windows snapped together.

But with the recent changes to abandon OpenTK, this is basically what I had to resort to in order to simulate the window events (Polling SDL events to fire C# events).
[SDLForm.txt](https://github.com/MonoGame/MonoGame/files/1414762/SDLForm.txt)

Which is why I requested making the Sdl class public, because my "SDL" class is basically identical.
If you guys have suggestions for an alternative approach for me to take (that would basically give me the Resize, Move, and FocusChanged events of the main window), I'm totally open for it.
But this was the approach I settled on, due to finding difficulties of doing it any other way.

**Comment by FrostFlame64** [comment]
I know this is old, but I believe I can narrow down my issue (for why I made this request and all of this extra work). The whole reason that I'm having to poll SDL events and such is because when developing with MonoGame's DesktopGL DLLs, this line won't work:

```var form = (System.Windows.Forms.Form)Control.FromHandle(gameWindow.Handle);```

When working with MonoGame's Windows DLLs (or even in the original XNA framework), this line will return the wrapping window that the application is running in. With that, I have access to the events I need (Move, Resize, Focus, etc). So my problem is that there's no real equivalent to doing this when MonoGame is using SDL for the wrapping window.

**Comment by cra0zy** [comment]
Just use SDL-CS and grab the native window handle.

**Comment by FrostFlame64** [comment]
So I tried the SDL2-CS package that you suggested, but I guess I'm still not understanding how I'd be able to get the Control.FromHandle() to work properly. This still returns null:
```var form = (System.Windows.Forms.Form)Control.FromHandle(SDL2.SDL.SDL_GL_GetCurrentWindow());```

Sorry, perhaps I'm just being dumb, but could you provide an example on how using SDL2-CS would help me get the native window?

**Comment by cra0zy** [comment]
https://wiki.libsdl.org/SDL_GetWindowWMInfo

https://wiki.libsdl.org/SDL_SysWMinfo

**Comment by FrostFlame64** [comment]
Alright, so calling SDL_SysWMInfo gets me the handle to the window, but that handle still doesn't work with Control.FromHandle.

As I mentioned, I'm trying to get the window's control so I can have access to the events I need (Move, Resize, Focus). And I currently don't see anything in SDL2-CS to support getting the actual control instance or events for the properties changing.

In fact, the only things I see are methods like SDL_GetWindowSize() which would get me the property values on demand, meaning I'd have to have a loop constantly pulling the property values and manually invoking custom events when the properties change. And if I have to do THAT, I might as well as stick with what I currently have (Polling SDL Events),

Alright, well thanks anyways. I'm not seeing a better solution than what I currently have, so I guess I'll have to live with it.

**Comment by tomspilman** [comment]
Going to go ahead and close this as we don't have plans to make our internal SDL wrappers public.
