### ISSUE TITLE
Cannot load SDL2.dll when changing folder path!

### ISSUE THREAD

**Issue by jellythedoge** [MonoGame/MonoGame#6017]
I have my project setup so all my dlls go like this

    MainClass
        API - x86 & x64 folders
        Game - All code not including MainClass
        Content - All assets

Now the problem is with the API path the exe doesnt see the DLLS, Could you please add support for custom dll paths?

**Comment by Jjagg** [comment]
It would be pretty easy to allow users to specify where MG should look for its dependencies.
@jellythedoge Why do you not just use the folders like MG set them up?

**Comment by cra0zy** [comment]
Gonna close this as with 3.7 you can just override PATH/LIB variables to search extra paths.
