### ISSUE TITLE
APK expansion support

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#6018]
On Google Play, Android APKs are limited to 100MB. If an application has to be bigger, one has to implement a support for side loading APK expansions (OBB files): https://developer.android.com/google/play/expansion-files.html

An OBB file a zip archive with the same internal structure as the APK and has to be located in a specific system folder.

I recently had to support this for loading assets through the content pipeline. Thanks to the help of @dellis1972 I ended up simply modifying the ```TitleContainer```: https://github.com/mrhelmut/MonoGame/commit/29f96cc6ef76ac9cab2c8687c07883ec1335a58f

Would it be worth to upstream this change? Is there any better way to handle this?

@KonajuGames ?

**Comment by dellis1972** [comment]
I'm in favour of including this change.

**Comment by tomspilman** [comment]
I don't know how any of that works, so i'm good with whatever @dellis1972 and @KonajuGames say.

**Comment by cra0zy** [comment]
Could we maybe make it so that each set of content files (each .mgcb) gets packed into its own .obb file in case of Android export? And of course use that as default for content loading.

**Comment by dellis1972** [comment]
you only need an .obb for stuff over 100meg. So it should not be the
default. Setting up an .obb requires accessing google play services and
other bits and pieces which for small games are over kill. So this should
be something that is supported but not the default.

That said some docs would be useful/

**Comment by mrhelmut** [comment]
The obb limitation is only specific to Google Play. I believe that the other Android market places like Amazon don't have this limit (and don't support .obb).

But I agree that this involve a specific build setup... I ended with two configurations to ship APKs for both kind of market places.

**Comment by mrhelmut** [comment]
Irrelevant nowadays.
