### ISSUE TITLE
GamePadState miss a public constructor. Breaks compatibility with XNA.

### ISSUE THREAD

**Issue by nkast** [MonoGame/MonoGame#6027]
The API was broken in PR #4970. 

`public GamePadState(Vector2, Vector2 , float , float , params Buttons[])`

**Comment by Jjagg** [comment]
Fixed in #6572.

**Comment by nkast** [comment]
![gamepadstate](https://user-images.githubusercontent.com/3018589/50505233-28023800-0a7b-11e9-9718-cbab730e2dfc.png)
