### ISSUE TITLE
GameWindow.ClientSizeChanged event not triggered when maximizing window

### ISSUE THREAD

**Issue by raizam** [MonoGame/MonoGame#6028]
When AllowUserResizing = true, ClientSizeChanged is triggered  as expected when user resize manually.
However, when pressing the maximize icon on the window's bar, it doesn't get triggered, and the presentation parameters don't get updated.
Is there something I'm missing?

edit: using windows 7/ dx

**Comment by raizam** [comment]
Here is a stackoverflow question describing the issue.
https://stackoverflow.com/questions/45362989/monogame-maximize-window-event

Current solution is checking manually Window.ClientBounds at each frame. not ideal

**Comment by zigzag312** [comment]
What version of MG are you using?

**Comment by Jjagg** [comment]
Should have been fixed in #5585

**Comment by raizam** [comment]
@zigzag312 I'm using default 3.6 indeed.
Glad this got fixed, thank you @Jjagg for your work.
I'm closing this then

**Comment by zigzag312** [comment]
@raizam you can add Monogame develop branch to your NuGet packed manager to get the latest development packages: http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/
