### ISSUE TITLE
ClientSizeChanged not called on maximizing the window.

### ISSUE THREAD

**Issue by perneky** [MonoGame/MonoGame#6030]
On Windows DirectX, when the game window gets maximized, ClientSizeChanged not called, even if AllowUserResizing set to true. Interesting that it called when you move the window to the top of the screen and maximize that way, but not when you click the maximize button of the window, or the restore button when maximized.

**Comment by Jjagg** [comment]
This is fixed in the develop version of MonoGame by #5585. Please check the existing issues or try the develop branch of MonoGame before posting a new issue.
