### ISSUE TITLE
XNA spritebatch+drawuserindexednormalprimitives help

### ISSUE THREAD

**Issue by gatinha96** [MonoGame/MonoGame#6035]
I'm trying to put a cursor on my program (where my actual cursor is), but that messes up my stuff in the background:
![training2 3d 25_10_2017 15_43_24](https://user-images.githubusercontent.com/25842096/32232666-77d93cd4-be50-11e7-8af7-38d7b73dd2ad.png)
(with spritebatch)
![training2 3d 25_10_2017 15_45_52](https://user-images.githubusercontent.com/25842096/32232708-8f2901a8-be50-11e7-91e5-e3b88ba3014b.png)
(without spritebatch, that's how the terrain should look)
Here's my main draw code:
`protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.White);

            Ground.Draw(GraphicsDevice,camera);

            spriteBatch.Begin();
            spriteBatch.Draw(cursor, cursorpos, Color.White);
            spriteBatch.End();

            base.Draw(gameTime);
        }`
"Ground" is my terrain, heres it's draw:
`public void Draw(GraphicsDevice device, ClsCamera view)
        {
            effect.Projection = Matrix.CreatePerspectiveFieldOfView(MathHelper.PiOver4, device.Viewport.AspectRatio, 1.0f, 300.0f);
            effect.TextureEnabled = true;
            effect.Texture = texture;
            effect.VertexColorEnabled = false;

            effect.World = worldMatrix;
            effect.View = view.view;

            effect.CurrentTechnique.Passes[0].Apply();
            device.DrawUserIndexedPrimitives<VertexPositionNormalTexture>(PrimitiveType.TriangleList, vertices, 0, vertices.Length, indices, 0, indices.Length / 3);
        }`
"effect" is initialized before any draw.

Any guesses on what went wrong? Thanks in advance.

P.S. I'm using Monogame for Visual Studios.

**Comment by Jjagg** [comment]
SpriteBatch does not reset the graphics state to what it was before it draws stuff and it has different defaults than what GraphicsDevice initializes to. Judging by the image the issue is sampler state. SpriteBatch sets the first sampler state to LinearClamp, but the default (what you're likely expecting) is LinearWrap. You might also want to reset the other graphics state.

**Comment by gatinha96** [comment]
Thank you, that was indeed the problem, resetting the values fixed it:
`
GraphicsDevice.SamplerStates[0] = SamplerState.LinearWrap;
            GraphicsDevice.BlendState = BlendState.Opaque;
            GraphicsDevice.DepthStencilState = DepthStencilState.Default;
`
