### ISSUE TITLE
[SharpDX] Problems with DXT render targets

### ISSUE THREAD

**Issue by Sizaar** [MonoGame/MonoGame#6036]
Creating a render target with SurfaceFormat.Dxt1/3/5 or SurfaceFormat.Dxt1/3/5SRgb results in an SharpDX exception "The parameter is incorrect", here is the stack trace:
```
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at Microsoft.Xna.Framework.Graphics.TextureCube.CreateTexture()
   at Microsoft.Xna.Framework.Graphics.TextureCube..ctor(GraphicsDevice graphicsDevice, Int32 size, 
Boolean mipMap, SurfaceFormat format, Boolean renderTarget)
   at Microsoft.Xna.Framework.Graphics.RenderTargetCube..ctor(GraphicsDevice graphicsDevice, Int32 size, 
Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage)
```

**Comment by tomspilman** [comment]
My guess is XNA doesn't allow this either, but likely throws a nicer exception when you do.

GPUs cannot render to a compressed format.  So the error is correct.

**Comment by Sizaar** [comment]
Actually XNA allows this, checked with a DXT1 Albedo buffer and it works.

**Comment by tomspilman** [comment]
We will have to setup a unit test against XNA and figure out how they are doing it.  GPUs don't render to block compressed formats.  All i can think of is XNA added some code under the hood to render to a regular surface the compress it.

**Comment by Jjagg** [comment]
I think XNA falls back to a supported format. The parameter is called `prefferedFormat`. XNA has other places where it uses 'preferred' as a prefix to mean that it will try to use the given setting but falls back to something else if needed (like in GraphicsDeviceManager).

**Comment by tomspilman** [comment]
> I think XNA falls back to a supported format. 

Interesting... thanks for that info @Jjagg .

We should probably setup a unit test for this and ensure we behave like XNA so that people are not surprised by an error here where XNA just works.

**Comment by vpenades** [comment]
Graphics Cards, in general, don't support DXT (or any other compression format) to be used as render targets.

I think the right solution would be to throw a "not supported exception" whenever you setup such render target.

**Comment by KonajuGames** [comment]
XNA allowed it, but the surface format of the created render target is not DXT.  It will usually be Color, as the parameter is **preferred**Format.  This allows the library to choose the closest supported format that allows the render target to be created and usable.  This si the same as the properties we set on the GraphicsDeviceManager in the Game constructor.  They are preferred properties, but may not be available so it falls back to supported values.  The [XNA doc](https://msdn.microsoft.com/en-us/library/ff433785.aspx) states 
> Preferred format for the surface data. This is the format preferred by the application, which may or may not be available from the hardware.
