### ISSUE TITLE
The Visual Studio installer has issues if the user is a "standard user" (not in the Administrators group)

### ISSUE THREAD

**Issue by fogbank** [MonoGame/MonoGame#6047]
I tried to install MonoGame for Visual Studio on Windows 10 from a "standard user", which means that, after asking for the Administrator's password, Windows runs it as the Administrator user.

When this happens, of course the start menu entries get saved into the Administrator's start menu and the VS templates are not saved anywhere because the installer looks for the VS directory in the user's Documents folder, and Administrator does not have that directory, so the VS installation is not detected. I've tried with VS 2017 (and yes, with the latest 3.7.0 dev package), don't know if it's the same with older versions.

So, it seems that the MonoGame installer requires to be run by a user who is in the Administrators group.

**Comment by fogbank** [comment]
If I may suggest, and assuming there are really no ways to know which user really launched the installer with such a setup, it would probably be better to save the start menu entries in c:\ProgramData, since the installer runs as elevated anyway, and, as for the VS templates, the proper solution would probably be to make a VSIX package and publish it as a VS extension.

**Comment by Moth-Tolias** [comment]
I suffered from this as well. it was very confusing and distressing until I figured out what was going on. fortunately I had installed visual studio 2017 on the administrator account  as well,  meaning that I could copy the templates to the more appropriate positions of the standard account.

**Comment by Jjagg** [comment]
This issue was brought up in #4838 and explained in [this comment](https://github.com/MonoGame/MonoGame/issues/4838#issuecomment-263760703).

>  We need administrator privileges to install MonoGame into Program Files, but this means authenticating as an admin user. The installer then runs under that admin user, so when we access the registry to find the location of the user's Visual Studio project templates folder, it is reading the registry for the admin user, not the standard user.

**Comment by Jjagg** [comment]
Installer doesn't use the registry keys anymore because it caused issues with VS2017. Closing in favor of #3808.
