### ISSUE TITLE
[WinDX] Window is not centred on startup

### ISSUE THREAD

**Issue by MichaelDePiazzi** [MonoGame/MonoGame#6051]
When using Windows DirectX, the game window is no longer centred on start up again. Windows GL still works correctly.

This was previously fixed by @Jjagg in PR #5576, but something must have broken it again since then... :/

I'm super busy at the moment, but I will try to investigate this further at some point if no one else can.

**Comment by Jjagg** [comment]
For me on Windows 10 Windows DX centers the window on the working area (area of the screen without the task bar), while the SDL code centers the window in the full screen. Are those the same results you're getting?

**Comment by MichaelDePiazzi** [comment]
@Jjagg If I use the default window size, it is centred in the working area as expected. If I use a larger size, it's not. Here's a screenshot showing a 1280x720 window size on a 1920x1080 desktop resolution:

![window_issue](https://user-images.githubusercontent.com/5249498/32877138-07c3f064-cadb-11e7-81a5-e14cbc66b307.png)

It seems to be using the default window size when working out the position.

(P.S. I am also using Windows 10 - v1703)

**Comment by MichaelDePiazzi** [comment]
(P.P.S. I only just noticed that the default window size was centred correctly, that's why I didn't mention it earlier)

**Comment by Jjagg** [comment]
Got it! I broke this myself, but the fix is easy :) See #6060.
