### ISSUE TITLE
[UWP]OnActivated bug?

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#6054]
Hi,

with the latest build where UWP is working (900), I create a new Monogame UWP project and add the following functions to Game1.cs:

```
		protected override void OnActivated(object sender, EventArgs args)
		{
			System.Diagnostics.Debug.WriteLine ("--->OnActivated");
			base.OnActivated(sender, args);
		}

		protected override void OnDeactivated(object sender, EventArgs args)
		{
			System.Diagnostics.Debug.WriteLine ("--->OnDeactivated");
			base.OnDeactivated(sender, args);
		}

		protected override void OnExiting(object sender, EventArgs args)
		{
			System.Diagnostics.Debug.WriteLine ("--->OnExiting");
			base.OnExiting(sender, args);
		}
```

Run the project with F5, wait until the window is opened, and then close it. The debug output shows this:

--->OnActivated
--->OnDeactivated
--->OnActivated

(not only OnActivated is called after deactivation and closing, but OnExiting is not being called)

edit: I'm aware OnExiting is complex in the UWP, but what is really killing me is the extra activation, as I'm deleting some tombstone files and then the 'game continue' is lost because there's never another deactivation.

**Comment by cra0zy** [comment]
When you press the close button on the window you are unfocusing it and focusing it back, this acts as expected... closing.

**Comment by KakCAT** [comment]
and the fact that OnExiting is not called ?
