### ISSUE TITLE
Assertion of Color throws Warning

### ISSUE THREAD

**Issue by Juhlinus** [MonoGame/MonoGame#6059]
I searched the issues and didn't find any issues created by the original author who reproduced this bug.

While writing a test trying to Assert colors the compiler throws a warning.

```
[TestMethod]
    public void PeronagemColorTest()
    {
        var color = new Color(255,255,255,255);

        var color2 = new Color(255, 255, 255, 255);

        if (!color.Equals(color2))
        {
            Assert.Fail();
        }
    }
```

Warning thrown is: 

> error CS0103: The name 'DebugDisplayString' does not exist in the current context

According to comment to said SO question it might be related to [this](https://github.com/MonoGame/MonoGame/blob/989dbe64ab1f629e92af25427c4b25c3895fe130/MonoGame.Framework/Color.cs#L16).

[Source](https://stackoverflow.com/questions/47223498/monogame-unit-test-color)

**Comment by Jjagg** [comment]
Are you working off modified source code? The DebugDisplayString function should be found in the Color class [here](https://github.com/MonoGame/MonoGame/blob/989dbe64ab1f629e92af25427c4b25c3895fe130/MonoGame.Framework/Color.cs#L1802).

**Comment by Juhlinus** [comment]
I am not able to try and reproduce the bug myself as of right now, rather I just wanted to bring it to your attention.

**Comment by KonajuGames** [comment]
> According to comment to said SO question it might be related to this.

The `DebugDisplayString` method the attribute links to is at line 1802 in that same file.  That SO page wasn't of any help.  That source file has not changed for over a year now, with no other reports of issues.

**Comment by Juhlinus** [comment]
I haven't been able to reproduce this problem, so it's probably something specific to that user. 

Closing.
