### ISSUE TITLE
Leveraging C# 7.2 'reference semantics with value types' in future?

### ISSUE THREAD

**Issue by dsaf** [MonoGame/MonoGame#6062]
Based on my shallow understanding it should be a good little performance booster? I was wondering if it's worth tracking this for some 4.x+ release. Obviously it would limit code to C# 7.2+ compilers.

https://docs.microsoft.com/en-gb/dotnet/csharp/reference-semantics-with-value-types

> An advantage to using value types is that they often avoid heap allocations. The corresponding disadvantage is that they are copied by value. This tradeoff makes it harder to optimize algorithms that operate on large amounts of data. New language features in C# 7.2 provide mechanisms that enable pass-by-reference semantics with value types. If you use these features wisely you can minimize both allocations and copy operations. This article explores those new features.

> These enhancements to the C# language are designed for performance critical algorithms where memory allocations can be critical to achieving the necessary performance. You may find that you don't often use these features in the code you write.

**Comment by KonajuGames** [comment]
> Obviously it would limit code to C# 7.2+ compilers.

That is the primary reason for not jumping into new C# features too soon.
We need the compilers on all platforms to have support for those features.
But we must also ensure it is a valid case for changing existing code and
that there are no side effects.

**Comment by cra0zy** [comment]
Gonna close this as this isn't a bug report or a feature request.
