### ISSUE TITLE
Can't build .xnb files with Monogame Core

### ISSUE THREAD

**Issue by Tenes** [MonoGame/MonoGame#6069]
Hello, i've been using monogame core since its release and when i set the images to "Build" and try to use the "dotnet run" command, there is an error with the mgcb.exe. So i set the images to "Copy" and it was missing the .xnb files.
The only fix i found was to build the .xnb files with the stable monogame on Visual Studio 2017 and then to move the .xnb it generates to the targeted directory.
Is there any way to have the .xnb without having to build them with the OG Monogame ?

**Comment by Velkow** [comment]
Yes, same problem here.

**Comment by Jjagg** [comment]
What do you mean exactly by "MonoGame Core"?

**Comment by Tenes** [comment]
The monogame version usable with the .net core 2.0. The one cra0zy forked (i couldn't post issue on the fork, so i came here instead).
https://github.com/cra0zy/MonoGame/tree/core

**Comment by mrhelmut** [comment]
This is a work in progress, and better ping @cra0zy then.

You might also be interested in following this discussion #5339 and make sure that your setup is correct.

**Comment by cra0zy** [comment]
@Tenes @Velkow One of you give me your csproj file (don't just copy paste in comments, use gist.github.com or something similar).

**Comment by Tenes** [comment]
Thanks for the reply ! Here it is : https://gist.github.com/Tenes/6d821fbb26cade78db8dd92810e1d39c

**Comment by cra0zy** [comment]
Give me your build log now.

**Comment by Tenes** [comment]
wait, i don't have the error anymore, it is really weird. I had the exact same error from this guy http://community.monogame.net/t/mgcb-exe-command-failing-during-compile/6410
Sorry for the trouble, i think i can close the issue right now since everything is working as intented.
