### ISSUE TITLE
Tom Spilmans beard function is not working

### ISSUE THREAD

**Issue by StealthKill** [MonoGame/MonoGame#6079]
```
public Beard
{
	float timer;
	float beardLength;

	public Beard()
	{
		beardLength = 0;
		timer = 1000f; //ms
	}

	public void SetBeardLength(float value)
	{
		beardLength = value;
	}
	
	public void Update(GameTime gameTime)
	{
		timer -= (float)gameTime.ElapsedGameTime.MilliSeconds;
		if(timer <= 0)
		{
			beardLength += 0.01f;
			timer = 1000f;
		}
		
		if(beardLength > 9000)
		{
			beardLength = 0; // NOT WORKING
		}
	}
}

```
Please shave, makes you look like a 80 year old Kung Fu Master.

**Comment by mrhelmut** [comment]
I'm against this proposition, he looks magnificent.

**Comment by MarcVador** [comment]
@mrhelmut You are not impartial enough :)

@StealthKill That era was the best one ! That's cool to look like a Kung Fu Master ! You cannot imagine all the work needed to achieve this...

**Comment by Juhlinus** [comment]
> you look like a 80 year old Kung Fu Master
That's... a bad thing...?

**Comment by DDReaper** [comment]
> That's... a bad thing...? 😄

Well, when his beard gets long enough to interfere with his keyboard we could run in to trouble with the random merge and clicking the wrong button :P 
Also if it objects to a grand new idea, it could threaten his life and throttle him red dwarf style 😄

**Comment by StealthKill** [comment]
I bet his beard is doing all the coding job.

**Comment by chaosnhatred** [comment]
🤣 nice.
