### ISSUE TITLE
[WinDX] Crash when using gamepads on Windows 7

### ISSUE THREAD

**Issue by MichaelDePiazzi** [MonoGame/MonoGame#6083]
The Windows DirectX build is now crashing when trying to use gamepads on Windows 7. The exception is a `DllNotFoundException` for `xinput1_4.dll`.

However, XInput 1.4 is only available for Windows 8 and higher. XInput 1.3 is the highest version supported on Windows 7.

I'm guessing this is similar to issue #5986 and was caused by PR #5949 when SharpDX was updated to v4.0.1.

@Jjagg, would you be able to take a look at this? If not, I'll try look into it later this week.

**Comment by Jjagg** [comment]
This is fixed by #6010. The dependencies were just merged, so it's just the submodule update in #6010 that needs to be merged now :)

**Comment by MichaelDePiazzi** [comment]
Oh, great! I will give this a test right now. Thanks again @Jjagg  :)

**Comment by MichaelDePiazzi** [comment]
Confirmed - PR #6010 fixes this

**Comment by MichaelDePiazzi** [comment]
Closed now that PR #6010 has been merged.
