### ISSUE TITLE
[OpenGL Win] A call to PInvoke function 'MonoGame.Framework!MonoGame.OpenGL.GL+RenderbufferStorageDelegate::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature.

### ISSUE THREAD

**Issue by Eversor** [MonoGame/MonoGame#6084]
Updating to the last version in the repository i foun this issue when creating rendertargets with multisample count set to 0 on Windows OpenGL.

**Comment by Jjagg** [comment]
Possibly incorrect calling convention? [RenderBufferStorage](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/OpenGL.cs#L840-L844) is one of the only 2 PInvoke functions that has a Cdecl calling convention. I never really understood that stuff though. 

cc @dellis1972 @mrhelmut

**Comment by Eversor** [comment]
The issue rises on the else branch of the 
void RenderbufferStorageMultisample(int samples, int internalFormat, int width, int height)
at line 80 of
C:\Repos\DoomAndDestiny3\Code\Libraries\MONOGAME\MonoGame.Framework\Graphics\GraphicsDevice.OpenGL.FramebufferHelper.cs
i tried to add an (int samples) parameter btw RenderbufferTarget and RenderbufferStorage but this changed the type of error without solving the issue :(

**Comment by Jjagg** [comment]
@Eversor Do you build from source? If so, could you try to delete [this line](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/OpenGL.cs#L842) and see if that fixes the issue.

I can't seem to reproduce the issue...

**Comment by mrhelmut** [comment]
Totally sounds like a calling convention issue, I believe Jjagg is right about removing the Cdecl line.

**Comment by Eversor** [comment]
Yes it works 🥇 thank you very much !

**Comment by dellis1972** [comment]
I think both of those Cdecl references should be removed.
