### ISSUE TITLE
UWP GamePage.xaml question/proposal

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#6089]
Hi,

each time I have to make an UWP app that has to navigate to another XAML page, when going back to the 'monogame' GamePage.xaml, it is created again (meaning that everything is initialized again, loaded again, ...) because the system 'kills' GamePage.xaml the moment it is navigated away.

Wouldn't it be better to keep the MonoGame page intact as default, so that when people navigate back, everything is as it was before?

According to https://docs.microsoft.com/en-us/windows/uwp/porting/getting-started-navigation , this would be achieved adding to the constructor of GamePage.xaml.cs ' template

````
NavigationCacheMode = Windows.UI.Xaml.Navigation.NavigationCacheMode.Enabled;
````

For people that wants the old behaviour, it's easier to delete a line than having to browse internet to find a solution.

**Comment by nkast** [comment]
```
To enable a page to be cached, set NavigationCacheMode to either Enabled or Required. The difference in behavior is that Enabled might not be cached if the frame's cache size limit (CacheSize ) is exceeded, whereas Required always generates an entry no matter the size limit.
```

IMO, `Required` is a better option, `Enabled` is unpredictable.

**Comment by DDReaper** [comment]
To be honest.  It's rare for most games to need the ability to navigate to another XAML page, so this is more of a fringe case (please feel free to shoot me down if you feel I'm wrong)

In which case, adding the note to the docs, highlighting that option would be better, instead of forcing all projects to use it.

**Comment by Jjagg** [comment]
If people don't switch anyway, this option doesn't matter, right? So it won't hurt either way to set it to Required. Or is there some downside to it?

**Comment by DDReaper** [comment]
Not sure if there is a downside, or the impact on running memory for the single page.
usually with UWP, you don't turn something on unless you need it.  Unsure what effect this would have on tombstoning / activation / etc for a single page,  could mean the game doesn't release it's memory while in the background?

**Comment by KakCAT** [comment]
> Not sure if there is a downside, or the impact on running memory for the single page.

No idea either. All I can say it that adding that line made no impact in my game in terms of memory (i.e. when minimizing), tombstoning and activation. I haven't received any bug report that can be assigned to this change either. But all of this is hardly a proof of anything, I just wanted to expose the issue in order for UWP experts to decide on it. (a note in the documentation, a comment in the template code, or leaving that line on, all seem good solutions to me)

>  It's rare for most games to need the ability to navigate to another XAML page

In my experience those have been the cases:

* Writing (complex) configuration pages in XAML instead of ingame code, just because it's easier.
* Writing a tool instead of a game (often lots of pages are used then)
* On Xbox, I need "RequiresPointer" to interact and close advertisments, so you have to create a new page to avoid the GamePage to have a dancing pointer while you're playing. (or in similar case, any library/plugin that requires you to use an extra page)


How common are those cases and do they justify the addition of the line? No idea :)

**Comment by nkast** [comment]
> Writing a tool instead of a game (often lots of pages are used then)

In that case it would be bad to have multiple MG pages cached. (assuming the developer copy-pasted the GamePage.xaml)

> Writing (complex) configuration pages in XAML instead of ingame code, just because it's easier.

It's not cross-platform and I think we should discourage people from navigating way from the GamePage. I don't even know if MG was supposed to support this scenario in the first place or if it still works. There are some major changes in the UWP from 3.6, have you tried with the latest Develop 3.7.* ? For example Does the game & input loop work correctly (with and without the cache)?

**Comment by DDReaper** [comment]
Ok, based on your feedback / testing @KakCAT , I would endorse adding that option for UWP, especially with your testing on Xbox.

@nkast true, it's not very multi-platform, as the approach would need separate implementations for each platform, however, that's obviously the developers choice in everything.  This suggestion simply makes it easier for UWP devs who do this, with (it seems) no obvious downsides to UWP devs.

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
