### ISSUE TITLE
Tuple deconstruction for common types?

### ISSUE THREAD

**Issue by portal-chan** [MonoGame/MonoGame#6094]
Apologies if this was already brought up/discussed already but I couldn't find anything relevant.

Could the `Deconstruct` method be implemented for common types in the framework to allow code like this?

```csharp
var (x, y) = vec2;
var (r, g, b) = color;
// etc.
```

**Comment by Juhlinus** [comment]
As of right now the common types are `structs`, which if I recall do not support deconstruction.

**Comment by portal-chan** [comment]
Well I'm not home and all online compilers apparently lost tuple support overnight so I can't check for certain but isn't `System.ValueTuple` THE main tuple `struct` which supports deconstruction? It even works as an extension method so I don't see why `struct`s wouldn't support it.

**Comment by Juhlinus** [comment]
Yeah, you're right, that was my bad. I've pushed an extension file on my fork of MonoGame.

**Comment by cra0zy** [comment]
This has been fixed in #6096, closing...
