### ISSUE TITLE
Cannot generate installer using NSIS for windows

### ISSUE THREAD

**Issue by msmshazan** [MonoGame/MonoGame#6095]
Cannot generate installer using NSIS for windows.
 Returns error 
```!define: "MUI_INSERT_NSISCONF"=""

Changing directory to: "E:\shazan\monogame\MonoGame\Installers\Windows"

Processing script file: "E:\shazan\monogame\MonoGame\Installers\Windows\MonoGame.nsi" (ACP)
SetCompressor: /FINAL /SOLID lzma
!include: could not find: "header.nsh"
Error in script "E:\shazan\monogame\MonoGame\Installers\Windows\MonoGame.nsi" on line 3 -- aborting creation process
``` 
OS: Windows 10 . IDE: Visual studio 2017. Also it would be helpful to provide intructions to build from source in the documentation.

**Comment by msmshazan** [comment]
![image](https://user-images.githubusercontent.com/20334207/33518187-ed7c7ce2-d7b6-11e7-8d8b-116bb2d12207.png)
Okay I figured out some stuff on my own still couldn't solve this error

**Comment by cra0zy** [comment]
You have to build the base default,build file, not the Installers one.

**Comment by msmshazan** [comment]
Okay thanks
