### ISSUE TITLE
SurfaceFormat.Color is Unsigned 32-bit RGBA pixel format for store 8 bits per channel? 

### ISSUE THREAD

**Issue by xvwvx** [MonoGame/MonoGame#6106]
SurfaceFormat.Color is Unsigned 32-bit RGBA pixel format for store 8 bits per channel?

**Comment by Jjagg** [comment]
From the [docs](http://www.monogame.net/documentation/?page=T_Microsoft_Xna_Framework_Graphics_SurfaceFormat):

> Unsigned 32-bit ARGB pixel format for store 8 bits per channel.
