### ISSUE TITLE
SdlGameWindow.Handle returns SDL Handle, instead of Win32 Handle as expected

### ISSUE THREAD

**Issue by moritzuehling** [MonoGame/MonoGame#6111]
In XNA as well as in the [`WinFormsGameForm`](https://github.com/MonoGame/MonoGame/blob/ed77ff8681a96c0a90f8344960c980b44e217a69/MonoGame.Framework/Windows/WinFormsGameForm.cs) [`GameWindow.Handle`](https://github.com/MonoGame/MonoGame/blob/ed77ff8681a96c0a90f8344960c980b44e217a69/MonoGame.Framework/GameWindow.cs#L36) returns the Win32-Handle of the window.

That can be cast to a `System.Windows.Forms.Control` (of course, that's impossible as we don't use WinForms), but also passed to Win32-APIs such as `ShowWindow(IntPtr hWnd, int nCmdShow)` in `user32.dll`, or the linux equivalents.

However, at the moment it [returns the SDL-Handle](https://github.com/MonoGame/MonoGame/blob/ed77ff8681a96c0a90f8344960c980b44e217a69/MonoGame.Framework/SDL/SDLGameWindow.cs#L155) which is quite useless at first glance, since one can only pass it to SDL-functions. 

Those SDL-Functions can't be used, since the [SDL Interface is not exposed](https://github.com/MonoGame/MonoGame/blob/ed77ff8681a96c0a90f8344960c980b44e217a69/MonoGame.Framework/SDL/SDL2.cs#L10). 

Proposal:

- Change `SdlGameWindow.Handle` to return a Win32-Handle by expected. This can be retrieved using [`SDL_GetWindowWMInfo`](https://wiki.libsdl.org/SDL_GetWindowWMInfo?highlight=%28%5CbCategoryAPI%5Cb%29%7C%28SDLFunctionTemplate%29), and create an explicit Property `SdlGameWindow.SdlHandle` where the old `_handle` will be returned. Problem: `SdlGameWindow` is (of course) marked internal, so a user wouldn't be able to access it without reflection.

- Give users a way to call SDL-functions such as [Sdl.Show()](https://github.com/MonoGame/MonoGame/blob/ed77ff8681a96c0a90f8344960c980b44e217a69/MonoGame.Framework/SDL/SDL2.cs#L381) so we one can use this property with copying the SDL2.cs to the game-project.

In my opionion, a mix of these approaches would be best (expose the Sdl2-Interface somehow, *and* add the extra `SdlHandle`-Property).

Just for reference:

```csharp
var win32Handle = Process.GetCurrentProcess().MainWindowHandle;  // 0x0000000000b50646
var sdlHandle = this.Window.Handle;                              // 0x0000025f1ba0ccc0
var windowType = this.Window.GetType().FullName;                 // "Microsoft.Xna.Framework.SdlGameWindow"
```

**Comment by Jjagg** [comment]
I think this is outside the scope of MonoGame. MonoGame is essentially a hardware abstraction layer. It aims to provide a unified API across multiple back ends. Exposing those back ends does not make a lot of sense given the goals of the project. It enables users to write platform-dependent code. You can P/Invoke into SDL yourself if you need it. (it's also against .NET best practices to expose native wrappers to clients)

**Comment by mrhelmut** [comment]
I agree that ```Window.Handle``` may be useless in a SDL context (and having the native handle would allow to better integrate MonoGame in tools), but I also agree with Jjagg on the design.

I believe that both handle should be accessible (something like ```Window.Handle``` for the native window handle and ```Window.PlatformHandle``` for the backend handle?), but exposing the backend should be up to the developer, not the library.

**Comment by moritzuehling** [comment]
That's makes sense, but intuitivly I still think Handle should return the native handle.

MonoGame seems to have [no special documentation](http://www.monogame.net/documentation/?page=P_Microsoft_Xna_Framework_GameWindow_Handle) for Handle, and the XNA documentation [describes it](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.gamewindow.handle.aspx) as 

> Gets the handle to the system window.

While it's debatable what "system window" means, I think that a native window-handle is a bit closer to what I'd expect. In the WinFormsGameWindow we return `Window.Handle` as well, and not `(IntPtr)(&Window)` (for example).

An alternative would be to add some documentation to MonoGame that explains that the return value might not be the system window, but something else entirely based on the platform.

**Comment by Jjagg** [comment]
> MonoGame seems to have no special documentation for Handle

Good point, that's an issue.

@mrhelmut Yeah, we could add an API for it. I don't really think it's necessary, but I'm not against it. If people think it would be useful that would be fine IMO.

**Comment by cra0zy** [comment]
Handle needs to return a SDL handle since unlike Windows, for Linux you need multiple params to hook up something to the window.

**Comment by cra0zy** [comment]
Gonna close this as API is working as expected.
