### ISSUE TITLE
MonoGame.Utilities's Operations.Malloc is not threadsafe, and so Texture2D.FromStream isn't

### ISSUE THREAD

**Issue by jbeshir** [MonoGame/MonoGame#6114]
Been suffering from random failures to load pictures into textures, which ultimately were tracked down to exceptions while trying to index the dictionary used by Operations.Malloc.

On inspecting https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Utilities/Imaging/Operations.cs it became clear that there isn't any protection against concurrent writes to the dictionary tracking allocations, and so this method would be unsafe to call from multiple threads at once, but Texture2D.FromStream assumes that the image loading can be done from any thread and doesn't dispatch to the UI thread until actually creating the texture, leading to multiple calls into malloc at once during texture loading. As a temporary fix I've modified my fork to do the image loading on the UI thread too- this is not ideal but prevents crashes.

Replication is somewhat difficult- you have to spawn multiple threads and try to load textures on them, and sometimes it will crash. I could put together a sample project if needed, although I think the problem is fairly visible to inspection- there's an object called "_lock" in Operations.cs, but nothing ever uses it, and in the absence of any locking concurrent writes to a dictionary are incorrect.

**Comment by rds1983** [comment]
I am author of that code. Unfortunately, I haven't tested it in the multi-threaded environment. That "_lock" is actually used here: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Utilities/Imaging/PinnedArray.cs

Maybe the issue could fixed by replacing Dictionary with ConcurrentDictionary?
