### ISSUE TITLE
Game not running/launching when using 3.6+

### ISSUE THREAD

**Issue by rafaelalmeidatk** [MonoGame/MonoGame#6115]
I deployed a game and sent to a couple of people so they could test. All of them was able to play the game with one exception. The game window wasn't opening, no error was being thrown. The process just starts then close. So I told him to send me the Error Viewer exception:

![](https://cdn.discordapp.com/attachments/285851488625098752/392458141348134912/unknown.png)

Then I utilized this code to generate a log file to know more about the problem:

    static void CatchUnhandledException
        (object sender, UnhandledExceptionEventArgs e)
    {
        StreamWriter sw;
        Exception ex;

        try
        {
            sw = new StreamWriter("crash.txt");
            ex = (Exception)e.ExceptionObject;

            sw.WriteLine("### Crash ###");
            sw.WriteLine(ex.Message + ex.StackTrace);
            sw.WriteLine("### Inner ###");
            sw.WriteLine(ex.InnerException);
            sw.WriteLine("### Source ###");
            sw.WriteLine(ex.Source);
            sw.WriteLine("### Data ###");
            sw.WriteLine(ex.Data);
            sw.Close();
        }
        finally
        {
        }
    }

And his results:

    ### Crash ###
    Failed to create graphics device!   em Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
       em Microsoft.Xna.Framework.Game.DoInitialize()
       em Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
       em GraphicsTest3._7.Program.Main() na c:\users\rafael\documents\visual studio 2017\Projects\GraphicsTest3.7\GraphicsTest3.7\Program.cs:linha 21
    ### Inner ###
    System.PlatformNotSupportedException: MonoGame requires either ARB_framebuffer_object or EXT_framebuffer_object.Try updating your graphics drivers.
       em Microsoft.Xna.Framework.Graphics.GraphicsDevice.FramebufferHelper.Create(GraphicsDevice gd)
       em Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformInitialize()
       em Microsoft.Xna.Framework.Graphics.GraphicsDevice.Initialize()
       em Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
       em Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi)
       em Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
    ### Source ###
    MonoGame.Framework
    ### Data ###
    System.Collections.ListDictionaryInternal

I've tested with several versions:

* Using MonoGame 3.6: Exception says MonoGame requires OpenGL 3.0+, but [he has 3.1](https://cdn.discordapp.com/attachments/285851488625098752/392448908384665601/unknown.png).
* Using MonoGame 3.7: Exception says MonoGame requires `EXT_framebuffer_object`, but [he has it](https://cdn.discordapp.com/attachments/285851488625098752/392486594474541076/unknown.png).
* Using MonoGame 3.5: **The game works**.

All the tests were done using the plain Class Platform Desktop Project, no changes, it still crashes.

**Comment by mrhelmut** [comment]
Hello,

Would you mind trying a new blank project using the template of 3.6 and 3.7? If it works, it's most likely because your project missed the new dependencies layout (please check how the new template manage sdl and openal dependencies).

**Comment by rafaelalmeidatk** [comment]
For all the tests I've done the following: Close VS, uninstall the last version, install the new version, create a new project with the templates. So I guess I am with the new dependencies.

**Comment by rafaelalmeidatk** [comment]
I did another test with DirectX and latest MonoGame 3.7, the game now works. The problem is with OpenGL. Maybe create a shared project with DirectX for Windows and OpenGL for the other platforms may be a good workaround for max compatibility?

**Comment by mrhelmut** [comment]
Could you break point this method line by line? https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/OpenGL.cs#L1371

From what I read of your logs, if it crashes within this method, your Windows OpenGL driver can't load the FBO extension, which would be a driver issue.
Alternatively, try to run your test with MonoGame's debug symbols (pdb file) so that your log contains the file lines in the stacktrace.

If it fails before that (most probably in the LoadEntryPoints method), the problem is elsewhere, but as-is it really looks like either a driver issue or a missing dll.

**Comment by rafaelalmeidatk** [comment]
He installed the MonoGame 3.6 and created a WindowGL project. When running the project with no changes, the game now works, but if I try to do the same and send to him, the game crashes like before. Maybe the fact that he is using Xamarin instead of Visual Studio (as I am doing) matters?

He ran the tests on the code you sent but the breakpoints never reach the inner `if`s because the condition `GL.RenderbufferStorageMultisample == null` [is false](https://cdn.discordapp.com/attachments/285851488625098752/400113939008192533/unknown.png).

**Comment by Jjagg** [comment]
Considering no one else has reported this issue, I'm gonna say this is a driver bug.
