### ISSUE TITLE
Enabling MSAA on RenderTargets on Windows breaks rendering after #5538

### ISSUE THREAD

**Issue by roy-t** [MonoGame/MonoGame#6124]
I know the official NuGet package does not yet support MSAA for render targets. But I found the following merged PR (https://github.com/MonoGame/MonoGame/pull/5538). So I decided to check it out.

I've checked out the latest develop of MonoGame, build a release version for Windows and referenced it from my project (that previously used the latest NuGet package). 

When creating a render target and setting preferredMultiSampleCount to 0 everything worked as before. However when I set preferredMultiSampleCount to 2 or higher everything goes wrong. Even separate render targets that do not use any data from the render target that has enabled multi-sampling seem to break down. 

**Reproduction:**

1. Clone and build the latest version of MonoGame/develop
2. Clone https://github.com/roy-t/MiniRTS/tree/feature/MSAA_RenderTargets
3. Open MiniRTS.sln
4. Fix the reference to MonoGame.Framework to the location you have it on your machine
5. Build and run MiniRTS

**Result:**
![capture](https://user-images.githubusercontent.com/623634/34409060-a7cf41dc-ebc7-11e7-9c23-2d86cc2c67c5.PNG)

**Expected:**
![capture2](https://user-images.githubusercontent.com/623634/34409078-bd3bc31a-ebc7-11e7-9270-8bf58e4e211b.PNG)

You can see how it should look by opening `RenderSystem.cs` and in the constructor change the `preferredMultiSampleCount` parameter of `this.ColorTarget` to 0.

**Tested on:**
Windows 10 1709, 64 bit
NVIDIA GeForce GTX 970 4GB

**Comment by zigzag312** [comment]
Hi Roy, Thanks for detailed bug report with sample project. I'll have a look at this, but only after 31. - I hope you are not in a hurry.

**Comment by roy-t** [comment]
@zigzag312 after 31 is fine, I can live a while without AA :). If you need any more data, let me know :).

**Comment by Jure-BB** [comment]
I only get solid color rectangles, even if I set ColorTarget's MS count to 0. Any idea why? Top-rightmost rectangle is changing color. 
![clipboard-20180103](https://user-images.githubusercontent.com/6940357/34504274-f6a7f5ba-f01d-11e7-9310-e4d75d34b2ef.png)

I have same 64bit OS build & GTX 660 Ti

**Comment by Jure-BB** [comment]
@roy-t do you have any idea why sample project isn't working with multisampling disabled?

**Comment by roy-t** [comment]
Sorry I didn't see the notification for you response on the 3rd of januari. I've checked out the branch again and rebuild it. And I still see the same behavior. 

```
this.ColorTarget  = new RenderTarget2D(device, width, height, false, SurfaceFormat.Color, DepthFormat.Depth24, 2, RenderTargetUsage.DiscardContents);
```
![aa](https://user-images.githubusercontent.com/623634/34921047-0f9a030c-f97d-11e7-9fb3-f1c98ea504fa.PNG)

```
this.ColorTarget  = new RenderTarget2D(device, width, height, false, SurfaceFormat.Color, DepthFormat.Depth24, 0, RenderTargetUsage.DiscardContents);
```
![no-aa](https://user-images.githubusercontent.com/623634/34921050-169ced04-f97d-11e7-98cf-87496fbc3ced.PNG)

**Comment by roy-t** [comment]
Argh, I was trying to create a more minimal test-case to see if that one would work on your PC and show the weird error. I still have no idea why your computer has trouble displaying anything when AA is off. But I've found the solution.

It seems that when you use `GraphicsDevice.SetRenderTargets(a, b, c)` a, b, and c all need to have the same AA level set. I'm not sure if this is documented somewhere, or if this should be the case. But setting the same AA level to all render targets I rendered to at the same time (MRT) fixed my issue. 

Still very weird that your PC wont render anything.

Do you want to keep this issue open to investigate further, or is this expected design?

**Comment by Jure-BB** [comment]
@roy-t you solved it by yourself. This is DirectX limitation:

> If render targets use multisample anti-aliasing, all bound render targets and depth buffer must be the same form of multisample resource (that is, the sample counts must be the same).

Source: https://msdn.microsoft.com/en-us/library/windows/desktop/ff476464%28v=vs.85%29.aspx

@tomspilman Maybe MG should throw descriptive exception, if user tries to set multiple render targets with different multisample count?

PS: I tired latest version of your sample project. Now the ship is successfully rendered on my machine (single ship, same as top-left in your screenshots).

**Comment by roy-t** [comment]
Closing this one because the error was on my side :)
