### ISSUE TITLE
Problem with android project

### ISSUE THREAD

**Issue by TheYoungGeek43** [MonoGame/MonoGame#6127]
Hello
For the beginning I keep the source code generate by MonoGame and I start with android of Visual Studio (7,5,4.4) and I have this error

![capture](https://user-images.githubusercontent.com/24993753/34468256-2f0c6504-ef05-11e7-8d3d-6c82c3bb9b90.PNG)

Thanks

**Comment by cra0zy** [comment]
You probably need to enable graphics hardware acceleration on the emulator.

**Comment by TheYoungGeek43** [comment]
Thanks ;) My bug is finish
