### ISSUE TITLE
[UWP] Wrong BackBuffer size

### ISSUE THREAD

**Issue by Jure-BB** [MonoGame/MonoGame#6129]
BackBufferWidth & BackBufferHeight don't always match real Window size in UWP. 

I think #5615 broke setting backbuffer sizes at startup (there is white are around rendered content). 

EDIT: Setting new preferred backbuffer sizes while in windowed mode wasn't working even before #5615 (windows size isn't changed, but backbuffer size is changed, resulting in white area around rendered content because of mismatch between window viewbounds size and backbuffer size). Also described here #5914

**Comment by McFizh** [comment]
I'm having similar problems with mg 3.7.1385 and uwp. The following code in initialize method:

```
graphics.PreferredBackBufferWidth = 960;
graphics.PreferredBackBufferHeight = 520;
graphics.ApplyChanges();
```

causes project to open in 500x800 window. Moving this code to constructor doesn't change the end result.

**Comment by Jure-BB** [comment]
Unfortunately UWP version of MG does not resize the window like it does on other platforms. Its not implemented (missing feature) in UWP. 

You can check some suggested workarounds here https://github.com/MonoGame/MonoGame/pull/5615#issuecomment-354855177

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
