### ISSUE TITLE
Support for "dotnet build"

### ISSUE THREAD

**Issue by persn** [MonoGame/MonoGame#6137]
Please note that this is not a request for MonoGame itself to build with .NET Core or .NET Standard.

I would simply like to be able to run the command ``dotnet build MySolution.sln`` and make it work. I have a solution with some MonoGame projects, and several library projects, I wanted to convert the library projects to .NET Standard 2.0, and then build on TeamCity by using the dotnet tools. However, when I try to build even a basic MonoGame project it aborts with errors. From what I can gather, it's looking for the .targets script in a place where it isn't installed.

Tested on MonoGame v.3.5.1 and Dev Build v3.7.0.1156

````
$ dotnet build TestMonoGameDotnet.sln
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet\TestMonoGameDotnet.csproj(109,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.2\MonoGame\v3.0\MonoGame.Content.Builder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet\TestMonoGameDotnet.csproj : warning NU1503: Skipping restore for project 'E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet\TestMonoGameDotnet.csproj'. The project file may be invalid or missing targets required for restore. [E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet.sln]
C:\Program Files\dotnet\sdk\2.1.2\NuGet.targets(103,5): warning : Unable to find a project to restore! [E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet.sln]
E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet\TestMonoGameDotnet.csproj(109,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.2\MonoGame\v3.0\MonoGame.Content.Builder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Build FAILED.

E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet\TestMonoGameDotnet.csproj : warning NU1503: Skipping restore for project 'E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet\TestMonoGameDotnet.csproj'. The project file may be invalid or missing targets required for restore. [E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet.sln]
C:\Program Files\dotnet\sdk\2.1.2\NuGet.targets(103,5): warning : Unable to find a project to restore! [E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet.sln]
E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet\TestMonoGameDotnet.csproj(109,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.2\MonoGame\v3.0\MonoGame.Content.Builder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
E:\Programming\TestMonoGameDotnet\TestMonoGameDotnet\TestMonoGameDotnet.csproj(109,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.2\MonoGame\v3.0\MonoGame.Content.Builder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    2 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.20

**Comment by cra0zy** [comment]
Yea, `dotnet build` uses `dotnet msbuild` which is separate from main `msbuild`. 
 - If you are using MonoGame 3.6, you should be able to just copy over the `Tools` from `msbuild` directory to `dotnet msbuild` one.
 - If you are using the newest MonoGame, things become a bit more complex since we added a new MSBuild task which does not currently work with `dotnet msbuild`
   - however you can use my nuget package for MGCB (it works on Windows and Linux): <a href="https://www.nuget.org/packages/MonoGame.Content.Builder/">MonoGame.Content.Builder</a>. I do plan on submitting them once the build server gets updated. Quick example: <a href="https://github.com/cra0zy/MonoGame/blob/core/ProjectTemplates/MonoGame.Template.CSharp/content/MonoGame.DesktopGL.CSharp/MGNamespace.csproj">link</a>

**Comment by persn** [comment]
I don't need it straight away, so I'd rather wait for an official release. It is reassuring to get confirmation that I wasn't doing something wrong.

**Comment by Jjagg** [comment]
Closing in favor of #4975

**Comment by cra0zy** [comment]
@Jjagg This is asking about being able to use dotnet build, not supporting .NET Core or PCL like .NET Standard, a very different thing.

**Comment by Jjagg** [comment]
`dotnet build` is supported where possible.
