### ISSUE TITLE
I want to make a gui framework for monogame, but encountered a problem, please help me

### ISSUE THREAD

**Issue by esengine** [MonoGame/MonoGame#6140]
I recently wanted to make a gui framework for monogame but encountered a difficulty when doing Textbox and then on windows I did not know how to make my textbox allow IME pops up and what should i do with textbox to pop IME and support multi-character enter? Can you help me solve this problem?

**Comment by cra0zy** [comment]
Issues are meant for bugs and feature requests, questions like these should be posted on the community forum: http://community.monogame.net/
