### ISSUE TITLE
Improve OpenAssetImporter

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#6157]
Currently the `OpenAssetImporter` is crippled to only expose features that the old XNA `FbxImporter` and `XImporter` supported.  So for example we only expose 4 different texture types in `MaterialContent`:

  - Texture (aka Diffuse)
  - Transparency
  - Specular
  - Bump

However AssImp supports like 12 different types of defined texture maps and even custom ones.

Same sort of thing exists for material properties where we only expose a few... but some useful ones like 'IsTwoSided` is not exposed.

I think we have two paths:

 A) Just add the extra stuff as `OpaqueData` and not worry.
 B) Set a `XnaCompatible` flag to `OpenAssetImporter` when called from the `FbxImporter`.

If you use the `OpenAssetImporter` or `FbxImporter` let me know what you think.

**Comment by tomspilman** [comment]
See https://github.com/MonoGame/MonoGame/pull/6158

**Comment by Jjagg** [comment]
We should also update assimp to the latest stable release (#5397). MG is very far behind.

**Comment by tomspilman** [comment]
> We should also update assimp to the latest stable release (#5397). MG is very far behind.

Agreed.  I tested with it, but waited to update it in the next PR.

The goal being to use this new `FbxImporter` unit tests to help detect any issues from changing it.

**Comment by vpenades** [comment]
@Jjagg I agree on updating Assimp to the latest version, but it seems they're not keeping the NET wrapper up to date; the last official NET wrapper is still the one for Assimp 3, and it's +4 years old. I heard from time to time there's a new NET wrapper in the works, but it's not even in their official repository.
