### ISSUE TITLE
Keyboard State Stuck in Fullscreen

### ISSUE THREAD

**Issue by PBarnard** [MonoGame/MonoGame#6159]
I'm having the same issue as that outlined in this thread:

http://community.monogame.net/t/when-starting-in-fullscreen-mode-the-keyboard-state-gets-stuck/10114

The pressed keys are getting "stuck" according to the IsKeyDown() when the application is running in fullscreen using "graphics.ToggleFullScreen();"

One of the answers says it is fixed in 3.7.0.1206-develop but I've tried that version and 3.7.0.1232-develop and it's still happening.

**Comment by Jjagg** [comment]
Can you try setting IsFullScreen to true instead of calling ToggleFullScreen? 
ToggleFullScreen calls ApplyChanges and I suspect that messes up initialization.

**Comment by cra0zy** [comment]
What platform WindowsDX or DesktopGL?

**Comment by Jjagg** [comment]
The forum topic is about UWP.

**Comment by PBarnard** [comment]
Hey Jjagg, thanks for the reply, doing:

this.graphics = new GraphicsDeviceManager(this)
{
    IsFullScreen = true
};

in the constructor has fixed the problem, cheers!

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
