### ISSUE TITLE
MonoGame 3.6: Direct3D Shader/Effect works on Windows 7 but not Windows 10

### ISSUE THREAD

**Issue by davidsummers** [MonoGame/MonoGame#6171]
I have a program that uses a custom Direct3D shader/effect that works fine on Window 7 for the last year.

I'm in the process of upgrading and testing on Windows 10.

For some reason this custom shader/effect works fine on Windows 7 but not on Windows 10.

It should show an earth model with continents and shaded with a day/night shader/effect.

On Windows 7 it works fine.  On Windows 10 it just shows a black ball.

What is the difference in Windows 7 and Windows 10 that might cause shaders/effects not to work the same?

I'm pretty new at shaders/effects so it might be something obvious to someone with more experience.

A minimal program that demonstrates this problem can be found at: https://github.com/davidsummers/mgtest

**Comment by davidsummers** [comment]
Here is an example of it working correctly on Windows 7:

![windows7good](https://user-images.githubusercontent.com/16345256/35692854-00f20dfe-0742-11e8-94ba-19babcb2f9ad.png)

**Comment by davidsummers** [comment]
Here is an example of it not working correctly on Windows 10:
![windows10bad](https://user-images.githubusercontent.com/16345256/35693197-07ca0036-0743-11e8-9309-d61a55c74d23.png)

**Comment by sourceskyboxer** [comment]
It reproduces a bug. I have Windows 10 Pro and it sees like last comment #3 last.
Same from me too:
![same_bug](https://user-images.githubusercontent.com/3496136/35703602-efcb3f22-079c-11e8-8228-743245aed80d.JPG)

Did you try OpenGL ( DesktopGL version )?

**Comment by davidsummers** [comment]
I have been trying to see if I could use the OpenGL version and have tried a *LOT* of stuff in the last several days but everything I try gives errors such as:
1. SD2.DLL not found 
2. Can't add project (Tried to add the MonoGame project to my Solution).
3. Asset does not appear to be a valid XNB file (Tried using 2MGFX, I got the effect to compile with OpenGL but then got this message when I tried to use it, I probably just don't know the right way to use 2MGFX).

I've tried a lot more things but I'm losing track of what I tried and what I didn't try.

If anyone has some instructions for how to either use an OpenGL effect or how to switch from Direct3D to OpenGL then I would greatly appreciate it.

There are lots of tutorials but they are mostly all old ones that don't seem to apply to the current MonoGame 3.6 or 3.7, they mostly seem to be either pre-3.6 or old XNA.

**Comment by davidsummers** [comment]
The main question with respect to this issue is: *SHOULD* a custom effect/shader that works with Direct3D 9 on Windows 7 work on Windows 10 without any changes?  

If not, what changes would need to be made to get it to work?

If it *should* work, why is *not* working?

**Comment by DaveCoper** [comment]
You have bug in your shader. You are passing different structure to pixel shader than you declared (PixelLightingVSOutputTx to PixelLightingPSInputTx). Your layout is currently using XY position as UV texture coordinates. Change ps input to correct structure (PixelLightingVSOutputTx) and you will see your earth texture again.

**Comment by davidsummers** [comment]
@DaveCoper That's *very* interesting.  I will definitely check this out and report back.  Thanks so much!

I wonder why it works on Windows 7?

**Comment by davidsummers** [comment]
@DaveCoper That fixed the problem!

Wow!

No bug in MonoGame, just a buggy shader that for some reason happened to work correctly on Windows 7.

I've simplified the NightDay.fx file and fixed the bug and committed to the mgtest project on github.

I spent a week trying different things and was just starting to look at simplifying the NightDay.fx to get rid of the dead code.

A million thanks!

**Comment by tomspilman** [comment]
Note this is specifically why we have in the docs:

![image](https://user-images.githubusercontent.com/103522/35822939-768ca694-0a73-11e8-89e1-2758c0b7904a.png)
http://www.monogame.net/documentation/?page=Custom_Effects

**Comment by davidsummers** [comment]
Good point. 

I am a newbie at effects/shaders and had not written the code to begin with.

It also was complicated by the fact that there was a lot dead code.
