### ISSUE TITLE
OpenGL project switches to full screen mode when fullscreen flag is  set to off / false

### ISSUE THREAD

**Issue by YTN0** [MonoGame/MonoGame#6176]
I am currently using MG 3.7.0.1245 (pretty recent dev build) for an OpenGL project on Windows 10 using VS 2017.

On my laptop, I am setting graphics mode 1920x1080 with fullscreen *off* (GraphicsDevice.IsFullScreen = false).

1920x1080 is my Windows 10 /  laptop screen resolution.

I previously had no app.manifest file (the project settings had Manifest set to "embed manifest with default settings), however, with that setting, I was having issues with the DPI scaling on my laptop and the screen size / backbuffer.

Without the project app.manifest, setting the mode to 1920x1080 with fullscreen *off* worked fine i.e. I would get a windowed output.

However, I have since created an app.manifest file which has the dpiAware = true entry. This fixes my DPI scaling problem, however now, when I set the mode to 1920x1080 and have fullscreen set to *off*, the app still launches in fullscreen. If I change the app mode to another resolution e.g. 800x600 (which is different from my screen resolution of 1920x1080), then it displays correctly in windowed mode.

So the issue seems to be setting a mode that matches the screen resolution (in this case 1920x1080) and having dpiAware = true. When those 2 things are aligned, the fullscreen flag seems to be ignored and it sets the app to fullscreen anyways.

Unless I am mistaken, the app should always be in windowed mode when the isFullScreen flag is set to false, even if the window size matches the screen resolution.

**Comment by YugeshN** [comment]
FYI.. I tested this on 2 different computers (with 2 different graphics cards) and this happens on both.

**Comment by cra0zy** [comment]
Can you write a small sample code that demonstrates the problem?

**Comment by YugeshN** [comment]
[FullScreenBug.zip](https://github.com/MonoGame/MonoGame/files/1783417/FullScreenBug.zip)

@cra0zy  I have attached a sample. It's basically just a brand new OpenGL project and all I did is set the backbuffer to match my screen resolution (in my case 1920 x 1080) and set fullscreen to false.

If you change the backbuffer to any other resolution that does *not* match your OS screen resolution, then windowed mode works fine. As soon as the backbuffer matches the screen resolution, it automatically goes to full screen even when the fullscreen flag is false.

FYI, if you're running a different resolution than 1920 x 1080, then change those values in the app.

**Comment by cra0zy** [comment]
It does not actually enter fullscreen, MGs code always centers the window, and in this case it just so happens that the client sizes are equal to the screen size.

You can add `Window.Position = new Point(100, 100);` and you'll see the Window border.

**Comment by YTN0** [comment]
@cra0zy Doh... Thanks! 

Didn't quite see that one. It looks completely different with the DPI aware flag off compared to with the flag on (as it worked in past builds), so I didn't see that it might actually still be windowed but just not be showing the frame.

I'll close this out.
