### ISSUE TITLE
Can't hide mouse cursor

### ISSUE THREAD

**Issue by mikea314** [MonoGame/MonoGame#6180]
Setting IsMouseVisible = false doesn't hide the mouse cursor

MonoGame.Framework.WindowsUniversal
3.7.0.1248-develop

**Comment by cra0zy** [comment]
Hmm, I can't seem to reproduce this one.

**Comment by mikea314** [comment]
Thanks for taking a look cra0zy.
It's still happening for me on the latest Dev build.
Initially, the mouse cursor is hidden, but the moment I move the mouse it re-appears.

**Comment by cra0zy** [comment]
Can you make a minimal example that reproduces the issue?

**Comment by mikea314** [comment]
Will do

**Comment by mikea314** [comment]
Here's a link to the download.
https://www.dropbox.com/s/ke3vgkh6zs0ch8n/MouseTest.MG.zip?dl=1

**Comment by cra0zy** [comment]
Oh, I see whats causing the bug...

**Comment by cra0zy** [comment]
I don't have time to dig into this right now, but the bug is getting caused by the Xaml template, however it is not getting caused by the Core template.

**Comment by mikea314** [comment]
No hassles, thanks for having a look

**Comment by Jjagg** [comment]
Fixed in #6180.
