### ISSUE TITLE
Updating SDL to 2.0.7 might be required

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#6186]
Hello there,

Our Linux players recently found out a bug with SDL 2.0.5 that is messing up with keyboard inputs (e.g. it registers repeating key presses while holding a key down).

Upgrading (or downgrading to 2.0.4) proved to fix this issue.

It might be worth updating MonoGame dependencies.

On a side note, OpenAL-Soft also got updated recently with quite a bunch of changes. I haven't tested any version more recent than 1.17.2, but it may also be interesting to investigate potential improvements.

**Comment by cra0zy** [comment]
https://github.com/MonoGame/MonoGame.Dependencies/pull/117

**Comment by mrhelmut** [comment]
Oh! Let's summon @KonajuGames or @dellis1972 then. :)
