### ISSUE TITLE
Possible bug: MouseState not always changing after calling Mouse.SetPosition

### ISSUE THREAD

**Issue by s-m-k** [MonoGame/MonoGame#6210]
I need to capture the mouse cursor within game's window area to prevent accidental clicks outside of it, which gamers find very annoying when that happens.

Unfortunately, I can't find any dedicated MonoGame's functionality for that (not letting the mouse to go outside of the game window / delta-based mouse input), so I came up with a solution involving setting the mouse position to the center of the window.

Unfortunately 2, there seems to be a rare bug that causes the position reported in the mouse state to be always different than the position I set (so my cursor is always "going somewhere" without me even touching the mouse, it resets when I move the mouse again).

My operating system is Windows 10. Not sure if it happened on older Windows versions.

Here's the screenshot from Visual Studio with the watches that show the values of variables used to compute the delta. I've set this up without touching the mouse not to spoil the result. The expected behavior is that the next time I hit the breakpoint, the X value in the mouse state should be changed to the mouseMidX's value and the deltas should be 0. It doesn't happen until I move the mouse slightly, then it returns to the expected behavior. So far, the bug appears to happen randomly.

https://i.imgur.com/Jq7wde8.png

I'm not aware of any other way to do it in MonoGame, which is a shame, because that kind of mouse control is absolutely essential for 2d aiming or FPP look.

**Comment by cra0zy** [comment]
What version of MonoGame and what platform? (WindowsDX / DesktopGL / WundowsUWP / etc.)

**Comment by tomspilman** [comment]
> I need to capture the mouse cursor within game's window area to prevent accidental clicks outside of it, 

Is this real fullscreen?  Borderless fullscreen?  Windowed mode?

**Comment by s-m-k** [comment]
> What version of MonoGame and what platform? (WindowsDX / DesktopGL / WundowsUWP / etc.)

Oh, forgot to mention that. MonoGame 3.7 and DesktopGL (the one with SDL backend I guess).

(yeah, I know 3.7 is not stable yet, but you probably still want to hear about any bugs haha)

> Is this real fullscreen? Borderless fullscreen? Windowed mode?

It happens in both fullscreen and windowed mode (the ``HardwareModeSwitch = true|false`` doesn't seem to make any difference, so this will be something for the next issue report, unless I don't get something). Happened both in Debug and Release mode. Also, I build x64 and x86 separately because it seems to be easier that way for me for now if that makes any difference.

**Comment by tomspilman** [comment]
As a refresher to all this.

`Mouse.SetPosition` is the way in XNA that you would do relative mouse movements and lock the mouse to your game window.   This was a tricky hack... but it worked.

The problem is/was that we support platforms where it was not possible to move the mouse position.  I think we should look into this again as we've dropped some old platforms and things might have changed.

The other solution we considered (but one implemented) is a new "mouse lock" type of API which is really what we're looking for.  Still the question was could we implement this successfully across all platforms.

I know Windows UWP had later added a "relative mouse" feature:  https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh994925(v=win.10)  Maybe this is more like what we need?

**Comment by s-m-k** [comment]
Using deltas instead of mouse position is surely a thing for the FPP look. For 2D aim, however, it's enough to just be able to clip the mouse to the window area (and unclip it in the pause menu or on window unfocus), which actually would be preferred because of less perceived input lag.

I'm not sure about being able to do it on all platforms (like mobile, consoles etc.). I think it should be at least possible on all desktop platforms, seems that there are the SDL functions that do it (I guess I could call them myself for DesktopGL builds if MonoGame uses SDL as well):

https://wiki.libsdl.org/SDL_SetWindowGrab - for grabbing the cursor inside the window
https://wiki.libsdl.org/SDL_SetRelativeMouseMode - for the delta mode
https://wiki.libsdl.org/SDL_MouseMotionEvent - the mouse motion events in both normal and delta mode

**Comment by cra0zy** [comment]
@s-m-k Can you make a small example of i toccuring?

> The other solution we considered (but one implemented) is a new "mouse lock" type of API which is really what we're looking for. Still the question was could we implement this successfully across all platforms.
> 
> I know Windows UWP had later added a "relative mouse" feature: https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh994925(v=win.10) Maybe this is more like what we need?

There actually is a way to call SetPosition for mouse under UWP without capturing the cursor. 

On a side note, XNAs input system is generally bad:
- events can be missed because input pulling is tied to the update loop
- keyboard keys are a mix of keycodes and scancodes
- keyboard does not provide textinput (tho there is that event we added to the window...)
- mouse setposition does not work on all platforms
- android physical back button is implemented as gamepad back...
- there are no events

**Comment by cra0zy** [comment]
PS. I did submit a PR to add mousecapture: https://github.com/MonoGame/MonoGame/pull/4989

Closed it a few days later because it turned out UWP does allow setposition.

**Comment by tomspilman** [comment]
> XNAs input system is generally bad:

That is another discussion for another thread... lets keep to the topic.


> There actually is a way to call SetPosition for mouse under UWP without capturing the cursor.

If that is true maybe we need to go fix that and support `Mouse.SetPosition` on all desktop platforms.

**Comment by cra0zy** [comment]
https://github.com/MonoGame/MonoGame/issues/5000

**Comment by s-m-k** [comment]
Actually, I'm still not sure whether it happens in MonoGame itself or because of something weird in my code. I'm reading the source and it really shouldn't happen, as the state is updated as soon as the position is set (unless the 3.7 version I use is too old and it was actually fixed).

Whatever the cause, I hate bugs like that :)

**Comment by s-m-k** [comment]
Could #6045 be possibly related?

**Comment by s-m-k** [comment]
OK, I seemed to have an outdated MonoGame build (still from Dec 2017). So instead of trying to isolate it, I'll just continue my dev work and see if the bug ever happens again. Because it really shouldn't, based on the current source code.

**Comment by cra0zy** [comment]
#6099 fixed getting position after calling setposition on the same frame.

**Comment by s-m-k** [comment]
So it would make sense. What it looked like when the bug happened on my side, was that the state didn't change and the program had no reason to update it (like the mouse move event was somehow missed or something). Now the code just changes the state every time I call SetPosition, so I think that the bug simply cannot happen anymore - the state is just updated immediately, no need to care whether it's updated later or not (unless it's somehow changed back to its old values at some point). In fact, I'll close the issue and re-open it if the bug magically happens again.
