### ISSUE TITLE
Shader compilation always uses shader model ps_2_0

### ISSUE THREAD

**Issue by roy-t** [MonoGame/MonoGame#6219]
I'm using the MonoGame Pipeline tool 3.6.0.1625 on Windows 10 to compile a shader and I got the following error message:

X5608: Compiled shader code uses too many arithmetic instruction slots (66). Max. allowed by the target (ps_2_0) is 64.

This is weird because I've defined my technique like this:

```
#if OPENGL
    #define SV_POSITION POSITION
    #define VS_SHADERMODEL vs_3_0
    #define PS_SHADERMODEL ps_3_0
#else
    #define VS_SHADERMODEL vs_4_0_level_9_1
    #define PS_SHADERMODEL ps_4_0_level_9_1
#endif

// <snip pixel shader and vertex shader code>

// This is the only technique in the file
technique DirectionalLightTechnique
{
    pass Pass0
    {
        VertexShader = compile VS_SHADERMODEL MainVS();
        PixelShader = compile PS_SHADERMODEL MainPS();
    }
}
```
See the full shader here: https://pastebin.com/4vMm1HB6

I've tried other pixel shader models (directly, without the macro), but it doesn't seem to have any effect. My mgcb file starts with this, which seems correct:

```
#----------------------------- Global Properties ----------------------------#

/outputDir:bin/$(Platform)
/intermediateDir:obj/$(Platform)
/platform:Windows
/config:
/profile:HiDef
/compress:False
```

And defines the build properties of the shader like this:

```
#begin ShadowCastingLight.fx
/importer:EffectImporter
/processor:EffectProcessor
/processorParam:DebugMode=Auto
/build:ShadowCastingLight.fx
```

How can I get the shader compiler/ pipeline tool to use a higher version shader model?

**Comment by Jjagg** [comment]
I assume this is a DX project?

This is not a bug. You're using `vs_4_0_level_9_1` which is a compatibility target that is pretty much equivalent to vs_2_0. You can use 4_0_level_9_3 which is equivalent with 3_0, or just 4_0 or 5_0 instead.

> I've tried other pixel shader models (directly, without the macro), but it doesn't seem to have any effect. 

What have you tried? All of the following should work for DX:
```
vs_4_0_level_9_1, ps_4_0_level_9_1
vs_4_0_level_9_3, ps_4_0_level_9_3
vs_4_0, ps_4_0
vs_4_1, ps_4_1
vs_5_0, ps_5_0
```

For completeness, for OpenGL the following should work:
```
vs_2_0, ps_2_0
vs_3_0, ps_3_0
```

There's a good explanation of it on some MSDN page, but I can't seem to find it right now. Here's the page with an overview of shader models: https://msdn.microsoft.com/en-us/library/windows/desktop/bb509626(v=vs.85).aspx

**Comment by roy-t** [comment]
@Jjagg its indeed a DirectX project. I tried vs_3_0, ps_3_0 and that gave me the exact same error message. So then I assumed something was wrong. Apparently  3_0 is not a valid value for DirectX projects (Probably because we're now using DirectX 11 instead of 9/10?). While if I remember correctly it was valid in XNA. But using 4_0 works perfectly! Thank you!

**Comment by Jjagg** [comment]
Yes, that's correct. vs_3_0 and ps_3_0 do not work for dx projects, 4_0_level_9_3 is what you wanna use to target 3_0 for dx. 
Anyway, I'm glad you got it working :)
