### ISSUE TITLE
AccessViolationException in MGCB.exe when trying to import simple model from Blender

### ISSUE THREAD

**Issue by andrekoehler** [MonoGame/MonoGame#6221]
I created a simple model in Blender 2.79a: Create cube; set simple material; subdivide one face into a 3x3 grid; extrude grid segment in the middle of it.

![blender](https://user-images.githubusercontent.com/22099714/36904623-7368ada6-1e31-11e8-939a-ed7e05b06380.PNG)

When I start the MonoGame Pipeline Tool, create a new MonoGame Content Build Project, add the Blender file with the Cube and press rebuild, it does NOT generate any output but does not show any error message either:
![screenshot](https://user-images.githubusercontent.com/22099714/36904279-93ba5222-1e30-11e8-97d1-0e729c1e3f2c.PNG)

When I create a new "MonoGame Cross Platform Desktop Project" in Visual Studio 2017, add the same Blender model file to the Content.mgcb file and Rebuild the C# project, I get the following build error:

> 1>------ Rebuild All started: Project: PipelineCrash, Configuration: Debug Any CPU ------
> 1>  C:/Users/Andre/Desktop/PipelineCrash/Content/Box.blend
> 1>  
**> 1>  Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.**
> 1>     at Assimp.Unmanaged.AssimpLibrary.ImportFile(String file, PostProcessSteps flags, IntPtr fileIO, IntPtr propStore)
> 1>     at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
> 1>     at Microsoft.Xna.Framework.Content.Pipeline.OpenAssetImporter.Import(String filename, ContentImporterContext context)
> 1>     at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
> 1>     at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)
> 1>     at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.BuildContent(PipelineBuildEvent pipelineEvent, PipelineBuildEvent cachedEvent, String eventFilepath)
> 1>     at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.BuildContent(String sourceFilepath, String outputFilepath, String importerName, String processorName, OpaqueDataDictionary processorParameters)
> 1>     at MGCB.BuildContent.Build(Int32& successCount, Int32& errorCount)
> 1>     at MGCB.Program.Main(String[] args)
> 1>C:\Program Files (x86)\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets(84,5): error MSB3073: The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"C:\Users\Andre\Desktop\PipelineCrash\Content\Content.mgcb" /platform:DesktopGL /quiet /outputDir:"bin\DesktopGL\Content" /intermediateDir:"obj\DesktopGL\Content"" exited with code -1073741819.
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
> 

Here is the download link for the Blender file that causes this issue: 
[Box.zip](https://github.com/MonoGame/MonoGame/files/1775480/Box.zip)

The issue can also be reproduced by starting Blender, subdivide one face of the cube that exists on start-up and then save. So we can rule out that the material or extrusion is the cause of the issue.

I noticed when I subdivide the top face instead of the right face I get a different exception:

> 1>------ Rebuild All started: Project: PipelineCrash, Configuration: Debug Any CPU ------
> 1>  C:/Users/Andre/Desktop/PipelineCrash/Content/untitled.blend
> 1>C:/Users/Andre/Desktop/PipelineCrash/Content/untitled.blend : error : Importer 'OpenAssetImporter' had unexpected failure!
**> 1>  Assimp.AssimpException: Error importing file: EdgeEvent - collinear points not supported**
> 1>     at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
> 1>     at Microsoft.Xna.Framework.Content.Pipeline.OpenAssetImporter.Import(String filename, ContentImporterContext context)
> 1>     at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
> 1>     at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)
> 1>C:\Program Files (x86)\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets(84,5): error MSB3073: The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"C:\Users\Andre\Desktop\PipelineCrash\Content\Content.mgcb" /platform:DesktopGL /quiet /outputDir:"bin\DesktopGL\Content" /intermediateDir:"obj\DesktopGL\Content"" exited with code 1.
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
> 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.6
- MonoGame 3.7.0.1352

#### What operating system are you using:
- Windows 10 Version 1709

#### What MonoGame platform are you using:
- DesktopGL

**Comment by tomspilman** [comment]
@andrekoehler - This sounds like the library we use for importing Blender models, [Assimp](https://github.com/assimp/assimp), is failing to import that Blender model.

Doing a test on your Blender model here.

@cra0zy - Can you investigate why the fancy build output view does not show this clear content building error?

**Comment by tomspilman** [comment]
@andrekoehler - It looks like using the latest Assimp fixes this.  I'll accelerate my efforts to updating us to the latest version of Assimp.  I had caught a bug in Assimp when run across our unit tests which leaves me no choice but to go fix Assimp before i can update it.

**Comment by tomspilman** [comment]
@andrekoehler - FYI...  https://github.com/MonoGame/MonoGame/issues/6221

**Comment by cra0zy** [comment]
It probably won't fix this bug (assimp is very bad with blender format, they even had whole rant on how bad it is on their old site).

**Comment by tomspilman** [comment]
> It probably won't fix this bug

I tested this by opening his blender file in Assimp's viewer using the latest master code.  So i am pretty confident it will work.

But i'll go a step further... i'll add his blender file to our unit tests and make sure it imports.

**Comment by tomspilman** [comment]
Yes it imports... going to put a few asserts in to catch future issues.

**Comment by tomspilman** [comment]
Unit test added and at least this one Blender file works correctly.

https://github.com/MonoGame/MonoGame/pull/6222/commits/d32dba56432d62b733070ccfee13f1c0d9ee74c0
