### ISSUE TITLE
3.7.0.1371 - VS for Mac Build Error

### ISSUE THREAD

**Issue by 8bitdna** [MonoGame/MonoGame#6227]
Thought I'd try out the latest dev build from teamcity but am having a little build issue when using the new DesktopGL templates for VS for Mac.  Setup as follows:

MonoGame - 3.7.0.1371
OSX 10.13.3 High Sierra
Mono 5.4.1.7
VS for Mac Community 7.3.3 (build 23)

Using the template 'MonoGame Cross Platform Desktop Application' and no changes made if I try and build I get:

/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Error: The OutputPath property is not set for project 'TestGLApp.Desktop.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform=''.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform. (TestGLApp.Desktop)

If I open the same solution in my install of the Rider IDE everything builds fine with no issues which is making me think theres something up with CS Project file, or the way the IDE's are handling it?  I've not touched any C# for 10 years so I don't know enough to help fix it (a LOT has changed, the learning curve is steep haha).  I did dabble with the CS Project file after a google around regarding the error but with no joy.

Just thought someone might know better?

**Comment by tomspilman** [comment]
Thanks for reporting this @8bitdna !

@dellis1972 ?

**Comment by dellis1972** [comment]
Looks like its because `Platform=''.` Where our template is expected `AnyCPU`. We should probably just update the template so the debug/release configurations only use `Configuration` for the conditions and not Platform. 

The weird thing is the `<Platform/>` element is denied in the template [1].

@8bitdna can you check the text of the .csproj and see if `<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>` is in there.
If not there might be a bug in the Nuget Template engine... @cra0zy have you seen this before?

[1] https://github.com/MonoGame/MonoGame/blob/develop/ProjectTemplates/DotNetTemplate/MonoGame.Templates.CSharp/content/BlankApp.DesktopGL/BlankApp.Desktop.csproj#L6

**Comment by dellis1972** [comment]
To be fair, its not the first time I've seen a bug in the template engine. It stripped out the 

`#if __IOS__`

code I had in the templates, so I had to remove it in the end :/

**Comment by dellis1972** [comment]
This might be a bug in VSForMac. 

A work around is to add 

`<Platform>AnyCPU</Platform>`

to your csproj.

**Comment by 8bitdna** [comment]
Cheers for looking into this @dellis1972 and no I don't see the line you are referring to in my .csproj.  If I add the missing line from the template file you referenced above i.e.

<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>

...it all builds fine.  I checked the Addins directory to see if I can check the templates manually before they are used in VS for Mac but they get packaged up (excuse my ignorance, still hugely coming up to speed with .NET after a 10 year break!) although I do see a correct 3.7.0.1371 version in the Addin folder (MonoDevelop.MonoGame_IDE_VisualStudioForMac.3.7.0.1371) so I assume I've not made any mistake somehow and got an older version.

Does indeed suggest a naughty VS for Mac.

**Comment by cra0zy** [comment]
This is a bug in MonoDevelop: https://github.com/mono/monodevelop/issues/4040

**Comment by Josephvb10** [comment]
Still no fix for this? Not even a workaround? I can't do anything related to Monogame on Linux.

**Comment by Jjagg** [comment]
@JosephTico According to mono/monodevelop#4040 this is fixed.
If you're on an old build of MD a workaround is mentioned above:

> A work around is to add

`<Platform>AnyCPU</Platform>`

> to your csproj.

**Comment by Topodic** [comment]
Still having this issue with both the latest version of MD and MG on Linux. The AnyCPU line doesn't fix it either.

**Comment by Jjagg** [comment]
@Topodic Do you get the exact same error message?

**Comment by Topodic** [comment]
Big oops on my bit, meant to post that on issue #6593, shouldn't be trying to resolve issues at 4 AM. I'll follow up on the community link posted there. Apologies.

**Comment by Jjagg** [comment]
No worries :)
