### ISSUE TITLE
3.7.0.1371 - VS 2017 Template not associating MGCB file/s to Pipeline Tool

### ISSUE THREAD

**Issue by 8bitdna** [MonoGame/MonoGame#6229]
When using the new DesktopGL templates for VS 2017 the MGCB files open as a text file and not the Pipeline Tool.  I worked around by just manually associating them but I thought someone who knows better want to know :)

MonoGame - 3.7.0.1371
Win 10 v1709
VS Community 2017 15.5.2

**Comment by Jjagg** [comment]
Not sure if we can do anything about this. Is this just a registry value we can edit or is it VS?

**Comment by tomspilman** [comment]
This is how we currently register the GUI Pipeline tool in the Windows installer to open when we double click the .mgcb from VS:

https://github.com/MonoGame/MonoGame/blob/develop/Installers/Windows/MonoGame.nsi#L95

It also might be worth looking again if there is a way to define the preferred editor for .mgcb file from the .vcproj or our .targets file.

**Comment by MarcVador** [comment]
Doesn't it work when, duner visual2017, right clicking the mgcb file > open with, selecting monogame pipeline tool, and setting it as default ?

**Comment by 8bitdna** [comment]
@MarcVador Yes it does work like that.  That's how I got it working but if you are new to the framework etc you may not understand what is going on...  I'm pretty new myself and it caused a few minutes of me wondering and googling first.  On VS for Mac it opened the pipeline tool by default without doing anything so was thinking it might be good to keep a similar experience?

**Comment by cra0zy** [comment]
Pipeline Tool does get registered as an editor, it just doesn't get set as the default one, and from what I can see there doesn't seem to be an option to automatically set it.
