### ISSUE TITLE
"Copy Asset Path" should be full path

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#6230]
In the GUI Pipeline Tool when you do "Copy Asset Path" you get the relative path to the root of the content project.  This should be the full path instead.

**Comment by cra0zy** [comment]
Can you give an example of the error, I feel a bit confused.

**Comment by tomspilman** [comment]
If that is correct... it should be changed to "Copy Asset Name" to match the documentation on `Content.Load<>(string assetName)`.

Separately we can decide if adding "Copy Full Path" is worth it (this matches VS terminology).
