### ISSUE TITLE
FileHelpers.cs does not use 'MonoGame.Utilities' namespace

### ISSUE THREAD

**Issue by flibitijibibo** [MonoGame/MonoGame#6268]
From the current `develop` revision:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Utilities/FileHelpers.cs#L9

This is [pretty easy to fix](https://github.com/FNA-XNA/FNA/commit/9f443bc5b11f8acf03a85cb847eb26a2e650d5b0), but requires touching a lot of different files in the source so I didn't want to put it in #6267 and risk breaking everything, since I don't know the codebase well enough...

Not a big deal but thought I'd bring it up while I was looking at it!

**Comment by davi19** [comment]
ok. I'm going make the substitutions. It's ok ?

**Comment by davi19** [comment]
every file that has the FileHelpers is to reference the MonoGame.Utilities?

**Comment by davi19** [comment]
it will be my pleasure to help. Thanks, i'm going make the substitutions like the example.

**Comment by davi19** [comment]
one question the code is in the folder  MonoGame.Framework ?

**Comment by KinsonDigital** [comment]
Has this already been done?  I guess I am asking, how do I find out if this has already started?

**Comment by davi19** [comment]
It's started, have a pull request open but. Not already pass, the pull request it's: Fix issues #6268

**Comment by KinsonDigital** [comment]
Ok thanks.
