### ISSUE TITLE
Project templates use the same guid

### ISSUE THREAD

**Issue by mrward** [MonoGame/MonoGame#6278]
The project templates use a hard coded guid instead of having a new one generated each time. This can cause [problems in Visual Studio for Mac](https://developercommunity.visualstudio.com/content/problem/231218/unable-to-add-multiple-projects-to-a-solution.html) when adding the same MonoGame project type to the same solution.

The [template.config file](https://github.com/MonoGame/MonoGame/blob/develop/ProjectTemplates/DotNetTemplate/MonoGame.Templates.CSharp/content/BlankApp.PCL/.template.config/template.json) should have a guids section that lists the guids used in the templates. The templating engine will then replace these with new guids when the templates are created.

```
"guids": [
        "98E19497-29A6-4B77-B773-BEC55F9B55DC", // Project 1
        "18013668-F025-46F7-AD60-72795F485D78", // Project 2
    ]
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1

#### What operating system are you using:
- Mac

**Comment by tomspilman** [comment]
@dellis1972 ?

**Comment by CartBlanche** [comment]
@tomspilman I've unassigned @dellis1972 as he says he'd not aware of what needs to be done.

**Comment by harry-cpp** [comment]
@CartBlanche I know what needs to be done. I've kept this in for 3.8 as its really a small change.
