### ISSUE TITLE
Windows Universal platform & Monogame

### ISSUE THREAD

**Issue by jlk678** [MonoGame/MonoGame#6287]
#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL
hello

I use Visual Studio 2017 community.

I can't run an universal windows 10 projet with Monogame.
following Messages : Microsoft.net.core.universalwindowplatform is not found.

of course all the package have been installed but can't be found.

help, help...

**Comment by Eversor** [comment]
AFAIK DesktopGL is not officially supported on Windows Universal, you should really use the MonoGame.Framework.WindowsUniversal version. It uses DirectX instead of OpenGL.

**Comment by cra0zy** [comment]
Closing this one as the original issue does not make sense:
DesktopGL platform does not support UWP.
UWP platform requires Windows 10 SDK installed.
