### ISSUE TITLE
UWP, XamlGame<T> construction

### ISSUE THREAD

**Issue by FrancescoBonizzi** [MonoGame/MonoGame#6288]
Hi!

I'd like to discuss another possible way to initialize a game object for a XAML UWP application.

Now there is a static initializer `MonoGame.Framework.XamlGame<T>.Create(...)` that takes care of the construction of the `Game` class. With this logic, it isn't possible to inject in a "clear" way some dependencies, since the default constructor is called: `var game = new T();`.

What I'd like to propose as a pull request, if you agree with me, is:
- Doing nothing to XamlGame<T>.Create(...), in avoid breaking everything and to keep projects templates as they are
- Add an overload to that Create method that takes a "gameConstructor Func<T>", to be called like this:
`var game = gameConstructor();` in the Create method.

In that way, the final user will initialize its UWP implementation of the game like this:
`var game = MonoGame.Framework.XamlGame<MyGameClass>.Create(launchArguments, Window.Current.CoreWindow, swapChainPanel, () => new MyGameClass(dep1, dep2...));`

_Side note:_
Considering that the class requires the `T : Game` to have a default constructor, by adding this overload I ask anyway to mantain a default constructor, although it couldn't be necessary.

**Why I need to inject dependencies in my game?**
Consider I have the same Game class for different platforms. My game class needs an `IStringsProvider`, an `IAchievementsManager`, an `IStoreGateway`: I would implement those differently for each platform. To me, each specific platform will have only need to construct a new game with its correct implementations. This is a real case, I have game published for Android and for UWP with this logic.

What do you think? (If you agree I could do the pull request)
Thanks.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsUWP

**Comment by SimonDarksideJ** [comment]
It's certainly an interesting thought.
However, wouldn't you be doing the same style initilization within your game class already? (as seems to the the usual pattern)

Is there really a need to raise the implementation higher to the Game Class itself.  

I can see the need when it affects internal constructs to MonoGame itself, such as Graphics, Content Loading, etc.  
But for the types of dependencies you are referring to, these are bespoke to each game and usually handled internally.

All you are effectively doing is proposing to move some DI intialization to the Program/Main class, instead of inside your game code.  Unless I'm missing something.

**Comment by FrancescoBonizzi** [comment]
You are right, the thing is that the `: Game` initialization is the "nearest link" with the platform, that could be the `MainActivity` on Android, the [MainPage.xaml](url) in UWP and so on: this the only place I could construct a platform dependent implementation.

Consider you have a structure like this:

- MyGame portable library, that references `MonoGame.Framework.Portable`. The entry point of this library that contains the whole game is the calls that inherits from `Game`.
- An UWP project that references MyGame and `MonoGame.Framwork.Universal`
- An Android project that references MyGame, `MonoGame.Framwork.Android` (and Xamarin...)

`MyGame` needs some dependencies such as an `ISettingsRepository` to get some values from each platform settings store. I would then implement an `AndroidSettingsRepository `and an `UwpSettingsRepository`. I **cannot** construct those dependencies in `MyGame` itself, **because they are platform dependent**, so I have (and it seems reasonable to me) to inject them into `MyGame` constructor.

For example, in a `MainActivity` on Android I would do:

```
_game = new MyGame(
                new AndroidTextFileImporter(Assets),
                new AndroidSettingsRepository(this));
```

In a MainPage.xaml on UWP - at this moment - i have to do:

```
 _game = MonoGame.Framework.XamlGame<MyGame>.Create(
                launchArguments, 
                Window.Current.CoreWindow, 
                swapChainPanel);

_game.InjectDependencies(
                new UWPTextFileImporter(),
                new UWPSettingsRepository());
```

To me is important to inject those dependencies directly into the `MyGame` constructor.

Let me know if I'm missing something.
Thanks.

**Comment by SimonDarksideJ** [comment]
I see, so this is something you can already do on the other platforms but are unable to do on UWP, that makes more sense.

Feel free to put together a PR with the changes you propose then and the team will review it.  If it levels the playing field between the platforms, I don't see any issue with it.

Just be aware, there is both a XAML initialiser and a CORE initialiser (no XAML) to contend with :D

**Comment by FrancescoBonizzi** [comment]
Perfect, thanks! I'll do it.

**Comment by dellis1972** [comment]
is this not what the `game.Services` is for?

for each platform you can run

`
var game = new Game ();
game.Services.AddService (new AndroidSettingsRepository(this));
`

etc.

**Comment by FrancescoBonizzi** [comment]
@dellis1972, there is a difference: if you inject some dependencies in the constructor you construct a `Game `class that is in a valid usable state in a single call, (the constructor has been defined for this); if you add your dependencies later, your `Game` class could be in an invalid state because it lacks some dependencies. This can occur when you dependencies aren't optional, but required.
