### ISSUE TITLE
Instanced geometry not supported on OpenGL ES 3.0 and higher

### ISSUE THREAD

**Issue by YTN0** [MonoGame/MonoGame#6292]
When trying to run my app which uses instancing on my Pixel C tablet, I get the following error:

`System.PlatformNotSupportedException: Instanced geometry drawing is not supported yet for GLES or MONOMAC.
`

However, according to these posts, instancing is supported on OpenGL ES 3.0 and higher (and 2.0, with the specific extensions).

https://android-developers.googleblog.com/2015/05/game-performance-geometry-instancing.html

https://software.intel.com/en-us/articles/opengl-es-30-instanced-rendering

The Pixel C supports OpenGL 3.2, so it should work there. 

I am assuming this means it's not enabled in Monogame.

cc @Jjagg @dellis1972  You guys seem to be the resident experts in OpenGL (and instancing), so giving you a heads up here...

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL
- Android

**Comment by dellis1972** [comment]
Try https://github.com/MonoGame/MonoGame/pull/6264 
I just added detection of `glVertexAttribDivisor` so it works on all the gl platforms not just desktop and removed some of the exceptions for runtime checks

**Comment by YTN0** [comment]
@dellis1972  Cool... seems to be working now.
