### ISSUE TITLE
Fix 2-monitor breakpoint debugging with .IsFullScreen = true (worked in 3.6, issue in 3.7)

### ISSUE THREAD

**Issue by mdrejhon** [MonoGame/MonoGame#6294]
I upgraded MonoGame 3.6 to the current MonoGame 3.7.0.1467 and lost a valuable debugging capability: The ability to flawlessly breakpoint/debug a running MonoGame running in exclusive full screen mode.  I use 2 monitors, one primary for MonoGame exclusive full screen mode.

I have a specific application (beam racing) that requires the mandatory use of VSYNC OFF.  So I cannot use windowed mode or borderless mode.  I must debug using exclusive fullscreen (VSYNC OFF tearlines) for this stuff.  And I liked the debugging I could do in 3.6.

In MonoGame 3.7 -- as soon as I change window focus away from the exclusive full screen app to a window on a 2nd monitor (e.g. Visual Studio), the MonoGame app freezes for 1 second, followed by loss of graphics.    

Had no problem in 3.6.  Exclusive full screen mode did not make a fuss if it lost focus, as long as I focussed to a window on a separate monitor (2nd monitor) -- the exclusive fullscreen graphics simply paused when a breakpoint was hit, and I could do my usual debugging (as long as I did not move any windows to the exclusive fullscreen display).  Not anymore in 3.7, debugging is now made impossible in exclusive fullscreen ....

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1467

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsDX
- GeForce 1080 Ti

**Comment by mdrejhon** [comment]
I just reinstalled Monogame 3.6 for Windows ... Works beautifully.  
I can debug/breakpoint fullscreen-exclusive apps with IDE on my secondary monitor.  

But I really want to stick to Monogame 3.7 because it allows me to develop for Mac using Visual Studio 2017 for MacOS.   

Allowing me one common development environment for both PC and Mac.

I may have to keep switching between 3.6 <-> 3.7 until bug is fixed.

I would be happy to put a $100 BountySource bounty on fixing this 3.7 this bug, contact me mark@blurbusters.com

**Comment by fatneko** [comment]
In the file _WinFormsGameWindow.cs_, on line 235 there's the event handler _OnDeactivate()_
```
private void OnDeactivate(object sender, EventArgs eventArgs)
{
	// If in exclusive mode full-screen, force it out of exclusive mode and minimize the window
	if( IsFullScreen && _platform.Game.GraphicsDevice.PresentationParameters.HardwareModeSwitch ) {
		MinimizeFullScreen();
	}
	_platform.IsActive = false;
	Keyboard.SetActive(false);
}
```

The following code was **not** present in 3.6
`// If in exclusive mode full-screen, force it out of exclusive mode and minimize the window
if( IsFullScreen && _platform.Game.GraphicsDevice.PresentationParameters.HardwareModeSwitch ) {
	MinimizeFullScreen();
}`

Try removing these lines, which results in:
```
private void OnDeactivate(object sender, EventArgs eventArgs)
{	
	_platform.IsActive = false;
	Keyboard.SetActive(false);
}
```

This is not necessarily a bug, just intended behavior. See if it solves your problem.

**Comment by mdrejhon** [comment]
# It Works!  But it breaks #5885.

Just installed MonoGame source, built, made mod, built, and.... It works!

I viewed git history and it appears Steve 'Sly' Williams <slygamer@gmail.com> made a commit 8/23/2017 that added this undesirable behaviour to fix #5885 

Now, the question begins, how to solve this problem for a multi-monitor system for the following use-cases that are now broken by this 5885 "bugfix".

Multimonitor use cases -- From common use case, to less common use case.

* Users displaying gaming walkthroughs, cheatsheets & webpages on a 2nd monitor (very common)
* Debuggers like me who need to do IDE debugging of exclusive full screen.
* Games that create two MonoGame instances (rare)

Thusly, I consider this a **BUG**. It's quacks like a bug, looks like a bug, so 😉

Little known, but past versions apparently works to create a 2nd instance for a HUD display, two-screen-play (Nintendo-DS style).  Basically intentionally creating two "Game" instances in the same MonoGame app.  That works successfully.  While not an intended use of MonoGame, this actually works with Monogame 3.6, creating two Game objects for use on two separate monitors -- one of them being exclusive full screen for low-input-lag operation -- and the other one of them being windowed on 2nd monitor to display info/HUD/inventoryselector/etc stuff.  Focus switching does not glitch under Monogame 3.6 but currently does under 3.7.

But deleting the code as you suggest, resurrects bug #5885.  

I'm open to options how to proceed with my $100 BountySource offer.

* Claim: I can put up a $100 BountySource pot. If you (fatneko) wants to make a commit that keeps #5885 fixed but does not break the above multi-monitor use-cases, let me know.   
* Yield: If you prefer, you can yield to someone else to fix the bug, I can try contacting others (e.g. Steve) to rework his #5885 bugfix, or find someone else.   
* Share: Alternatively, if you want to collaborate, I can split the reward ($50-$50) between two developers collaborating (you having confirmed where the bug is, and another developer fixing the said bug).

Cheers,
Mark Rejhon
Founder, BlurBusters.com & Inventor of TestUFO.com

**Comment by fatneko** [comment]
I am not interested in the reward, I was just trying to help :)

**Comment by mdrejhon** [comment]
> I am not interested in the reward, I was just trying to help :)

Thanks! You have made it easier for the next programmer, though -- because we know exactly what broke this.  The tricky part is fixing #6294 and #5885 simultaneously.

**Comment by mdrejhon** [comment]
##$100 BountySource Reward For This Fix##

Contact mark@blurbusters.com to claim.

**Comment by mdrejhon** [comment]
The pull request didn't make 3.7.1?
