### ISSUE TITLE
Where is 2MGFX Tool on Windows (MonoGame 3.6) ?

### ISSUE THREAD

**Issue by Ticoel** [MonoGame/MonoGame#6296]
Hello,

Where is 2MGFX Tool on Windows (MonoGame 3.6) ?
Because I not found in "C:\Program Files (x86)\MonoGame\v3.0".

**Comment by cra0zy** [comment]
2MGFX get installed in MSBuild dir inside Program Files: 
```
C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools
```

In future, do ask these questions on the [community site](http://community.monogame.net/) or [gitter chat](https://gitter.im/MonoGame/MonoGame) instead, GitHub issues are meant for bug reports and feature requests.

**Comment by Ticoel** [comment]
Thank you !
