### ISSUE TITLE
Error in BoundingBox.Contains(BoundingFrustum)

### ISSUE THREAD

**Issue by Apostolique** [MonoGame/MonoGame#6298]
https://github.com/MonoGame/MonoGame/blob/6f4e51030120913bc1d5b21b34b07493d2eeebff/MonoGame.Framework/BoundingBox.cs#L71

The function ```BoundingBox.Contains(BoundingFrustum)``` doesn't work properly. If I have a BoundingFrustum that is outside a BoundingBox, the returned value will be ```ContainmentType.Intersects```.

If I instead call the equivalent (?) function on the ```BoundingFrustum.Contains(BoundingBox)```, I get the right result, namely ```ContainmentType.Disjoint```.
https://github.com/MonoGame/MonoGame/blob/6f4e51030120913bc1d5b21b34b07493d2eeebff/MonoGame.Framework/BoundingFrustum.cs#L179

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL, WindowsDX, NetCore

**Comment by nkast** [comment]
The BoundingFrustum code is over complicated. 
The [construction says](https://github.com/MonoGame/MonoGame/blob/6f4e51030120913bc1d5b21b34b07493d2eeebff/MonoGame.Framework/BoundingFrustum.cs#L128) that it's defined as a View * Projection matrix.

Let's look at [Contains(Vector3 point)  ](https://github.com/MonoGame/MonoGame/blob/6f4e51030120913bc1d5b21b34b07493d2eeebff/MonoGame.Framework/BoundingFrustum.cs#L294-L306)
If you have a vector3 in world coordinates and you tranform it by ViewProj, you get this point in normalized device coordinates (NDC a.k.a. Clip coordinates).  You then check if the point is withing -1 to +1 (-1 to 0 for Z).

You can extract corners and planes the same way. Tranform the corner (1,1,0) from Clip coordinates with inverse ViewProj into world coordinates.
I bet you can simplify the transform by taking the matrix Left,right,Up,down, etc. (it's multiplying with 1 and 0 after all).

Same goes for Planes, Spheres, boxes. Tranform them with ViewProj and then check if it's inside the NDC.

**Comment by baudii** [comment]
Has anyone solved this yet? It was first mentioned 6 years ago and I see there isn't even a test case for this scenario.
