### ISSUE TITLE
My Pipeline doesn't seem to work

### ISSUE THREAD

**Issue by esengine** [MonoGame/MonoGame#6304]
An error occurred while compiling the spritefont file and I was unable to load the DLL "freetype6.dll". But I checked this file under the monogame installation directory. Why is this, can someone answer it for me?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.6

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by Juhlinus** [comment]
Possible duplicate of #4504

**Comment by esengine** [comment]
I succeeded! thank you very much
