### ISSUE TITLE
MonoGame download page does NOT list VS 2017 as a supported dev tool

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#6315]
On the MonoGame downloads page, it only lists:

MonoGame for Visual Studio (requires a 64bit version of Windows, VS2010, VS2012, VS2013 or VS2015, and the latest DirectX Runtime)

Pretty sure we stopped using 2010 - 2013 some time back.

But more importantly, it DOES NOT list Visual Studio 2017, which technically is supported in 3.6 and is the standard platform for 3.7.

Can we please get the Downloads page (and subsequent documentation) updated to include VS 2017 please!

**Comment by cra0zy** [comment]
cc. @tomspilman

**Comment by willmotil** [comment]
Ya it needs to be updated in fact i think the download link to the nightly build should be at the top.
Seems like that is a question that gets repeatedly asked.

**Comment by tomspilman** [comment]
@SimonDarksideJ - Check it now... does that work?

**Comment by tomspilman** [comment]
@willmotil - I hate the idea of moving the development build ahead of the stable builds.  I would like to figure out the actual problem here.

Is it just that they don't scroll down the page enough to see it?

Is it that "development build" should be "nightly build"?

Something else?

**Comment by SimonDarksideJ** [comment]
Yup, that looks good.
