### ISSUE TITLE
MGCB.exe builds into wrong paths, and crashes

### ISSUE THREAD

**Issue by pkmnfrk** [MonoGame/MonoGame#6317]
Following the getting started tutorial, I get an error during build after adding some content to the content bundle.

```
1>------ Build started: Project: ZeldaLike, Configuration: Debug Any CPU ------
1>  Skipping c:/projects/ZeldaLike/ZeldaLike/Content/../../../overworld.png
1>  
1>  Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\projects\ZeldaLike\ZeldaLike\Content\obj\DesktopGL\Content\.mgcontent'.
1>     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>     at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
1>     at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
1>     at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
1>     at MGCB.SourceFileCollection.Write(String filePath)
1>     at MGCB.BuildContent.Build(Int32& successCount, Int32& errorCount)
1>     at MGCB.Program.Main(String[] args)
1>C:\Program Files (x86)\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets(84,5): error MSB3073: The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"c:\projects\ZeldaLike\ZeldaLike\Content\Content.mgcb" /platform:DesktopGL /quiet /outputDir:"bin\DesktopGL\Content" /intermediateDir:"obj\DesktopGL\Content"" exited with code -532462766.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

It looks like it's trying to build the files into $(Project)/Content/bin/... rather than $(Project)/bin/..., etc. I'm not sure which folder is the intended behaviour.

I did some digging into the msbuild targets files, and it appears to:

1. Define the path as "bin/$Platform/Content"
2. Create that folder, relative to the project
3. Feed that specific path into MGCB.exe, who will then interpret it as relative to the Content folder.

I tried fixing this issue, but I broke everything, so I'm just going to roll back to 3.6 (I accidentally installed 3.7, but at least you got a bug report out of it!)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7 development

#### What operating system are you using:
- Windows 10 Pro x64

#### What MonoGame platform are you using:
- DesktopGL

**Comment by pkmnfrk** [comment]
(Replacing 3.7 with 3.6, the project builds straight off, and appears to create the bin, etc folders in the Content folder, but they're pretty empty, so idk)

**Comment by cra0zy** [comment]
There is a new linking system in 3.7, issues like these should not occur anymore.
