### ISSUE TITLE
Content Pipeline Tool GUI quirks

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#6322]
While using Pipeline Tool, I am experiencing quite often these issues:

- When switching from one asset to another, the properties become duplicated.
- If a subdirectory does not exist anymore, it signals both the parent and the subdirectory with a Warning icon, this is correct, because that way you can notice that something' wrong in a collapsed subdirectory. But when I remove the subdirectory, the parent directory remains signaled.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1519

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by cra0zy** [comment]
This should be fixed.
