### ISSUE TITLE
Xnb's are bloating some file sizes by a incredible amount.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#6326]
This is a critical issue.

Xnb's are creating a huge amount of bloat in file sizes.
This is a jpeg.

That is the raw file size 16.77 mb for this texture.
So its basically decompressing the jpeg from its normal storage to do whatever, but not recompressing it.

![redalertxnbsarebloating](https://user-images.githubusercontent.com/7495196/40749391-d6479b58-6431-11e8-9fc8-685621159b50.png)

This is basically the same as saving a 16 million length byte array on disk directly.
Pretty much looking thru my folders all my jpegs are uncompressed on disk atm as xnb's
There is basically no compression active at all not standard or anything i have old bit compression algorithm i wrote. That would compress this back better then to not at all. Im guessing this is just a bug though.

Dx12 caps

What version of MonoGame does the bug occur on:
MonoGame 3.7

What operating system are you using:
Windows 10 

What MonoGame platform are you using:
DesktopGL

**Comment by tomspilman** [comment]
> This is a jpeg.

You'll see the same thing in XNA.  My guess is your leaving the texture format as `Color` which is essentially uncompressed.  If you select `Compressed` on the texture you will get DXT or the appropriate lossy compression for your target platform.

If you set `Compresed` to true in the content project settings it will do a lossless compression on uncompressed formats like this texture.  It can help a ton on the size of the file on disk and read times, but it is at the expense of more CPU time decompressing the data.  This is why the default is to not compress these in MG or XNA.

**Comment by tomspilman** [comment]
> Does it automatically compress pngs or do you need a setting for them ?

if you set compression on individual textures... you need to decide if the texture still looks good after lossy compression.  In general most game textures you find in modern games are all lossy compressed.

However if you have a pixel art style game usually these are all uncompressed.  This is because lossy compression adds artifacts.

In that case you're better off leaving it as Color and setting the Compress flag on the content project.

**Comment by cra0zy** [comment]
Gonna close this as it is neither a bug not a feature request.
