### ISSUE TITLE
Teamcity does not respond

### ISSUE THREAD

**Issue by ollipekka** [MonoGame/MonoGame#6328]
Currently nuget based monogame builds fail because teamcity does not respons. I'm not able to download packages from the feed or visit the user interface. 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

**Comment by cra0zy** [comment]
https://twitter.com/MonoGameTeam/status/1001984848029011968

**Comment by orlleite** [comment]
Hi, I just first met this engine friday. But doing my working setup I have to download 3.7 version for mac. Is there a mirror? Or, not pressure, do you speculate when those servers are going back?

**Comment by tomspilman** [comment]
@orlleite - Sorry for the disruption.  It will still be a few more days before the build servers are back.  For now your best bet is to work from the code on the GitHub repo directly or from Nuget.

**Comment by ollipekka** [comment]
Works for me.

**Comment by ollipekka** [comment]
A bit too early, http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/ is not responding

**Comment by tomspilman** [comment]
Sorry... the last few weeks the connection it is on has been spotty.  It will be in its final new home that is much more reliable in the next week or so.

**Comment by orlleite** [comment]
It appears to work fine now.

**Comment by MattiKloepper** [comment]
Throughout the last week I had absolutely no problems to access the teamcity website. Seems to be solved. Thanks a lot!
