### ISSUE TITLE
Building MonoGame framework on mac got MonoGame.Tests.Audio error

### ISSUE THREAD

**Issue by orlleite** [MonoGame/MonoGame#6332]
I'd like to build monogame so I cloned this repo, installed some apps needed, like nant, and updated xcode to 9.4 version. I ran:
`mono /Users/orlandoleite/nant-master/build/Release/NAnt.exe -D:nuget3path="/usr/local/bin/"`

I got this error about `CFBundleIdentifier` not presented at Info.plist.
I edited `MonoGame/Test/Info.plist` to:

	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
	<dict>
		<key>CFBundleIdentifier</key>
		<string>com.MonoGame.MacOS</string>
	</dict>
	</plist>

_I don't think it is related to the main problem, I'm just putting here in case._

I ran again and it appears to get many files compiled but at Tests I got those errors.

     [exec] OneTimeSetUp: Fix me!
          [exec]
          [exec] Errors, Failures and Warnings
          [exec]
          [exec] 1) Failed : MonoGame.Tests.Audio.DynamicSoundEffectInstanceTest.BufferNeeded_MultipleConsumed
          [exec]   Expected: 3
          [exec]   But was:  1
          [exec]   at MonoGame.Tests.Audio.DynamicSoundEffectInstanceTest.BufferNeeded_MultipleConsumed () [0x00076] in <bb6a959011334e60a10a82a2859a1bb2>:0
          [exec]
          [exec] 2) Failed : MonoGame.Tests.Audio.DynamicSoundEffectInstanceTest.PendingBufferCount
          [exec]   Expected: 0
          [exec]   But was:  1
          [exec]   at MonoGame.Tests.Audio.DynamicSoundEffectInstanceTest.PendingBufferCount () [0x00099] in <bb6a959011334e60a10a82a2859a1bb2>:0
          [exec]
          [exec] 3) Error : MonoGame.Tests.Audio.DynamicSoundEffectInstanceTest.Playback
          [exec] System.InvalidOperationException :  (Reason: InvalidOperation)
          [exec]   at Microsoft.Xna.Framework.Audio.ALHelper.CheckError (System.String message, System.Object[] args) [0x0003e] in <1e8cd725069444549a2b5d5f6696121c>:0
          [exec]   at Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.PlatformSubmitBuffer (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00065] in <1e8cd725069444549a2b5d5f6696121c>:0
          [exec]   at Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.SubmitBuffer (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00086] in <1e8cd725069444549a2b5d5f6696121c>:0
          [exec]   at Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.SubmitBuffer (System.Byte[] buffer) [0x0003c] in <1e8cd725069444549a2b5d5f6696121c>:0
          [exec]   at MonoGame.Tests.Audio.DynamicSoundEffectInstanceTest.Playback () [0x0003b] in <bb6a959011334e60a10a82a2859a1bb2>:0
          [exec]   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
          [exec]   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <bb7b695b8c6246b3ac1646577aea7650>:0
          [exec]
          [exec] 4) Failed : MonoGame.Tests.Framework.FrameworkDispatcherTest.UpdatesSoundEffectInstancePool
          [exec]   Expected: 1
          [exec]   But was:  2
          [exec]   at MonoGame.Tests.Framework.FrameworkDispatcherTest.UpdatesSoundEffectInstancePool () [0x0002c] in <bb6a959011334e60a10a82a2859a1bb2>:0
          [exec]
          [exec] Run Settings
          [exec]     Number of Test Workers: 8
          [exec]     Work Directory: /Users/orlandoleite/MonoGame/Test/bin/Linux/AnyCPU/Debug
          [exec]     Internal Trace: Off
          [exec]     Display TeamCity Service Messages
          [exec]
          [exec] Test Run Summary
          [exec]   Overall result: Failed
          [exec]   Test Count: 1195, Passed: 1143, Failed: 4, Warnings: 0, Inconclusive: 0, Skipped: 48
          [exec]     Failed Tests - Failures: 3, Errors: 1, Invalid: 0
          [exec]     Skipped Tests - Ignored: 48, Explicit: 0, Other: 0
          [exec]   Start time: 2018-06-05 19:06:56Z
          [exec]     End time: 2018-06-05 19:09:03Z
          [exec]     Duration: 127.014 seconds
          [exec]
          [exec] Results (nunit3) saved as /Users/orlandoleite/MonoGame/Test/bin/Linux/AnyCPU/Debug/TestResult.xml

     BUILD FAILED - 0 non-fatal error(s), 396 warning(s)

     /Users/orlandoleite/MonoGame/default.build(225,8):
     External Program Failed: mono (return code was 4)

     Total time: 314.5 seconds.

I tried to compile target `build_mac`. **It works!** 
But I need to build the `MonoGame.pkg` installer.

MaOS 10.13.5
Mono JIT compiler version 5.10.1.47
Visual Studio Mac 7.5.2 (b40)

**Comment by jnoyola** [comment]
I got the same error and also got it working by editing the same Info.plist like that.

**Comment by harry-cpp** [comment]
The build system and protobuild have been replaced so this is no longer a valid issue.
