### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by tjulises** [MonoGame/MonoGame#6334]
Hi @monogame ,
My name is Ulises or TJ if you like,
i'm a graphic designer and I contribute to cool projects (open source) like this one!
if this is something that you're looking forward to, I'll gladly upload some logo proposals

I'll look forward for your reply, cheers!

TJ.

**Comment by cra0zy** [comment]
Hi! We are currently not looking for a new logo, however there are a few icons which are on our TODO list (#5187) in case you are interested in it.

**Comment by tjulises** [comment]
Sure, tell me which ones @cra0zy

**Comment by Jjagg** [comment]
@tjulises This is really cool :D What projects have you made logos for?

**Comment by tjulises** [comment]
this isn't my actual portfolio, this are some of the .png I had made before for some repos, for you to take a look at [google drive](https://drive.google.com/open?id=1DBM4sp91l8CDZsOm16o0ZrczawsmwoDU) the repo's I have worked with are visible on my profile :+1:  @Jjagg

**Comment by Apostolique** [comment]
Those are all really nice! @tjulises

**Comment by cra0zy** [comment]
Gonna close this as there is: #5187
