### ISSUE TITLE
Error with BoundingSphere.Intersects(BoundingBox)

### ISSUE THREAD

**Issue by delgadobosso** [MonoGame/MonoGame#6336]
Created a Sphere with `BoundingSphere Bound = new BoundingSphere(new Vector3(0, 5, 0), 1);`
and a Box with `BoundingBox BoxBound = new BoundingBox(-Vector3.One, Vector3.One);`.
When I decrease the Y-value of the Bound, `Bound.Intersects(BoxBound)` will never return True when the intersect.

`Bound.Contains(BoxBound) == ContainmentType.Intersects` on the otherhand will return true.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Apostolique** [comment]
It's likely that there are errors in the BoundingBox code.

Related issue(?): #6298

**Comment by willmotil** [comment]
I was just looking at this... that code is a spegettified nightmare in those classes.
What is the point of having a bool intersects when contains can return intersects contains or disjoint.
Then...
Sphere.Contains( box ) has a different implementation then Box.Contains( sphere ).
Sphere.Intersects( box ) calls box.Intersects(sphere) which is not the same code as in the box.contains(sphere) method that also checks for intersects, but does so like this 
if (dmin <= sphere.Radius * sphere.Radius)

There is also a todo method that isn't implemented in sphere.
Ya i wonder if thats really the same as xna or if these are just rough draft classes that were never straightened out.

**Comment by Halofreak1990** [comment]
> Ya i wonder if this is really similar to xna or if these are just rough draft classes that were never straightened out.

The latter, most likely.

**Comment by Apostolique** [comment]
Worth nothing that the code is the exact same in FNA.

https://github.com/FNA-XNA/FNA/blob/master/src/BoundingBox.cs

I wonder if FNA also has the same bugs, and if XNA was working that way too.

**Comment by tomspilman** [comment]
FNA is a fork of MonoGame so many issues we have found and fixed also existed there.  Ethan at times fixes FNA when we find issues.

**Comment by lithiumtoast** [comment]
@Apostolique suggested I take a look at this since I wrote the intersection (collision) code for many 2D primitives in MonoGame.Extended.

For reference:
- `BoundingBox` is a 3D axis-aligned-bounding-box using the min and max representation of two points.
- `BoundingSphere` is a 3D sphere using the only representation available; centre point and radius.

I use the following book, [Real-Time Collision Detection](https://www.amazon.com/Real-Time-Collision-Detection-Interactive-Technology/dp/1558607323), for academic reference and to derive all code.

Page 165, 5.2.5, Testing Sphere against AABB:

<img width="403" alt="screen shot 2019-02-10 at 6 37 32 pm" src="https://user-images.githubusercontent.com/519592/52544036-f4494c00-2d62-11e9-825b-f59d9313caeb.png">
<img width="367" alt="screen shot 2019-02-10 at 6 38 22 pm" src="https://user-images.githubusercontent.com/519592/52544047-104ced80-2d63-11e9-9b10-aef4dba658e4.png">

Existing code in MonoGame for reference:
```
// BoundingBox.cs
...
        public bool Intersects(BoundingSphere sphere)
        {
            if (sphere.Center.X - Min.X > sphere.Radius
                && sphere.Center.Y - Min.Y > sphere.Radius
                && sphere.Center.Z - Min.Z > sphere.Radius
                && Max.X - sphere.Center.X > sphere.Radius
                && Max.Y - sphere.Center.Y > sphere.Radius
                && Max.Z - sphere.Center.Z > sphere.Radius)
                return true;

            double dmin = 0;

            if (sphere.Center.X - Min.X <= sphere.Radius)
                dmin += (sphere.Center.X - Min.X) * (sphere.Center.X - Min.X);
            else if (Max.X - sphere.Center.X <= sphere.Radius)
                dmin += (sphere.Center.X - Max.X) * (sphere.Center.X - Max.X);

            if (sphere.Center.Y - Min.Y <= sphere.Radius)
                dmin += (sphere.Center.Y - Min.Y) * (sphere.Center.Y - Min.Y);
            else if (Max.Y - sphere.Center.Y <= sphere.Radius)
                dmin += (sphere.Center.Y - Max.Y) * (sphere.Center.Y - Max.Y);

            if (sphere.Center.Z - Min.Z <= sphere.Radius)
                dmin += (sphere.Center.Z - Min.Z) * (sphere.Center.Z - Min.Z);
            else if (Max.Z - sphere.Center.Z <= sphere.Radius)
                dmin += (sphere.Center.Z - Max.Z) * (sphere.Center.Z - Max.Z);

            if (dmin <= sphere.Radius * sphere.Radius)
                return true;

            return false;
        }
```

Suggested solution in C# from reference:
```
// BoundingBox.cs
...
public float SquareDistanceTo(Vector3 point)
{
    var squareDistance = 0.0f;
    if (point.X < Min.X) squareDistance += (Min.X - point.X) * (Min.X - point.X)
    if (point.X > Max.X) squareDistance += (point.X - Max.X) * (point.X - Max.X)
    if (point.Y < Min.Y) squareDistance += (Min.Y - point.Y) * (Min.Y - point.Y)
    if (point.Y > Max.Y) squareDistance += (point.Y - Max.Y) * (point.Y - Max.Y)
    if (point.Z < Min.Z) squareDistance += (Min.Z - point.Z) * (Min.Z - point.Z)
    if (point.Z > Max.Z) squareDistance += (point.Z - Max.Z) * (point.Z - Max.Z)
    return squareDistance;
}
...
public bool Intersects(BoundingSphere sphere)
{
    var squareDistance = SquareDistanceTo(sphere.Center);
    return squareDistance <= sphere.Radius * sphere.Radius;   
}
```

**Comment by Jjagg** [comment]
A pull request with these changes and the test case in the original post would be very much appreciated :)
