### ISSUE TITLE
XML doc request

### ISSUE THREAD

**Issue by stromkos** [MonoGame/MonoGame#6338]
Would it be possible to include XML schema in the MonoGame documentation for the serializable classes(including Reflection and Helpers)?

While the helper classes would need to be manually updated (include a comment to ensure changes are reflected in the documentation), the reflective serializer can utilize xsd.exe to generate the proper schema and wrap it with the appropriate tags.

I have concluded that attempting to solve #4792, the only solutions utilizing XmlReader.Create() instead of XmlTextReader, forces any solution that exists to be in exponential time.  

While I could mitigate the problems, by eliminating already read elements, I do not feel like my approach is the appropriate solution, given my solution only works for basic cases.
I am opting for option "B" to the original problem. Give the user the needed feedback to correct the situation. Instead of only informing the user the the expected element is missing;  Give the user the expected element AND a reference to the expected schema.
Even if the proper schema is not available; This would inform the user of the out-of-order elements and the opportunity to correct them, instead of only informing of the missing element.

I hope to provide a PR with this issue, to inform the user the element is out of order(already in the works), 
I also wish to return a reference the appropriate schema to be utilized when implementing the class(Hence the Issue).

**Comment by Jjagg** [comment]
I'm closing this. I don't think the bookmarking solution is a good approach instead we should reverse control as suggested in #4792 and look up fields/properties as the XML elements are parsed.
