### ISSUE TITLE
SDL2 and Raspberry Pi with Raspbian

### ISSUE THREAD

**Issue by Graveen** [MonoGame/MonoGame#6342]
I have installed mono-runtime and libopenal-dev under Linux Raspbian.
I have compiled the cross platform example with VS2017 / windows.
When i run the code on raspberry pi 3 Model B, i have an error message:

"Unhandled Exception:
Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Failed to create graphics device! ---> System.EntryPointNotFoundException: SDL_SetWindowResizable at (wrapper managed-to-native) Sdl/Window:SetResizable (intptr,bool)"

libSDL2.2.0.so0 is installed (in /usr/lib)

Latest Raspbian
Compiled on Windows with Monogame 3.6
Raspberry Pi 3 model B

#### What version of MonoGame does the bug occur on:
- MonoGame 3.6

#### What operating system are you using:
- Linux / Arm

#### What MonoGame platform are you using:

- DesktopGL

**Comment by cra0zy** [comment]
You need SDL 2.0.5 or newer in your system, or just use the ones pre packaged with the templates.

**Comment by Graveen** [comment]
Thank you for your answer. I'm not sure i see how to deploy 2.0.5 for ARM - iirc 2.2.0 is not compatible/suitable. I believe the templates are packaged with x86/x64 SDL versions ?

**Comment by Graveen** [comment]
With Raspbian Stretch and SDL 2.0.5 (the basic SDL provided with Raspbian 9) it works flawlessly.
Thank you @cra0zy
