### ISSUE TITLE
SoundEffect loopStart and loopLength do nothing

### ISSUE THREAD

**Issue by Jesuszilla** [MonoGame/MonoGame#6369]
I'm trying to loop a PCM stream (decoded from MP3 using MP3Sharp) and the loopStart and loopLength parameters do not loop the track after being decoded.

```
bgm = new SoundEffect(decoded.ToArray(), 0, (int)decoded.Count, mp3Dec.Frequency, (AudioChannels)mp3Dec.ChannelCount, loopStart, loopEnd - loopStart);
```

Instead, it just goes right past the loop point and plays the rest of the track. I know this because it gets to the end of the song, then loops around, rather than using the specified loop points.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by tdeeb** [comment]
OpenAL SoundEffects don't actually use these values for some reason. Most of them route to [PlatformInitializePcm](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffect.OpenAL.cs#L46), which ignores them completely. This contrasts to XAudio's constructors which call the [CreateBuffers](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffect.XAudio.cs#L245) method, which does look to utilize them in some form.

What would it take to fix this in OpenAL?

**Comment by Jesuszilla** [comment]
OpenAL does have alSourceQueueBuffers, which I believe is what DynamicSoundEffectInstance uses underneath. It could do what I do for my MP3/OGG looping (due to this not working) and split the PCM data on the sample boundaries and constantly feed it the loop region. It needs to clear the previously played buffers to prevent memory leaks, though.

**Comment by tomspilman** [comment]
There must be a OpenAL feature for this.   It really shouldn't require streaming of a sound asset.

**Comment by Jesuszilla** [comment]
The way I see it, there's three ways to go about it:

1. Set a timer to go off exactly at the loop start period, then start playing the loop portion (inaccurate; tried similar approach in C# and there were still early fires or delays, though maybe there's a more accurate, lower-level timer that can be used).
2. Constantly poll the state of the alSource. This would result in a busy loop, which is quite undesirable. May not be 100% accurate, either.

Perhaps the best approach on this layer would be a combination of both 1 and 2: set a timer to go off a little earlier than the loop portion, then do a busy poll to check if the source has stopped playing. I do not know how accurate this would be.

Short of feeding in a loop buffer similar to my DynamicSoundEffectInstance approach, this is the only way I can see it happening.

**Comment by tomspilman** [comment]
It seems like OpenAL Soft has an extension for loop points: `AL_LOOP_POINTS_SOFT`

https://github.com/kcat/openal-soft/commit/d9126eeb2c9e5b4d5d00027cd70aef0ae8900602

@dellis1972 - What if we move to use OpenAL Soft for all platforms where we use OpenAL?

**Comment by Jesuszilla** [comment]
Hello! It's been a while so I was just posting to ask if there has been any discussion or progress on this front?

Keep up the good work, guys!

**Comment by Jjagg** [comment]
Sorry for the lack of response @Jesuszilla. No progress has been made here.
I'm closing this as a duplicate of #5186.
