### ISSUE TITLE
Allow setting GameWindow minimum and maximum size

### ISSUE THREAD

**Issue by fatneko** [MonoGame/MonoGame#6373]
I know most games wouldn't benefit from this, but since there is property called `AllowUserResizing` in `GameWindow`, I believe it would make sense to expose a minimum and maximum window size property (for Desktop platforms).

**Comment by tdeeb** [comment]
It's possible to do this manually:

```
private int maxWidth = 900;

private void GameWindowSizeChanged(object sender, EventArgs e)
{
    if (Window.ClientBounds.Width > maxWidth)
    {
        graphics.PreferredBackBufferWidth = maxWidth;
    
        graphics.ApplyChanges();
    }
}
```

**Comment by cra0zy** [comment]
If you are using DesktopGL you can also call the SDL native methods:
- https://wiki.libsdl.org/SDL_SetWindowMinimumSize
- https://wiki.libsdl.org/SDL_SetWindowMaximumSize
