### ISSUE TITLE
Building Desktop-GL MonoGame Project in VS Mac 

### ISSUE THREAD

**Issue by Lus1t4nUm** [MonoGame/MonoGame#6375]
So here's what happens when I try to build via VS, the MonoGame Desktop Project on Mac. (Development rls) 

<img width="801" alt="screen shot 2018-07-20 at 15 08 33" src="https://user-images.githubusercontent.com/34067397/43007351-fb75eb2a-8c2f-11e8-9794-b4b38dc63e35.png">

Here's what happens when I try to build via VS, the MonoGame Desktop Project Mac; on this stage:

<img width="992" alt="screen shot 2018-07-20 at 15 10 07" src="https://user-images.githubusercontent.com/34067397/43007397-1f498908-8c30-11e8-8802-28c9e7369736.png">

<img width="796" alt="screen shot 2018-07-20 at 15 15 18" src="https://user-images.githubusercontent.com/34067397/43007430-36c95a5e-8c30-11e8-9f07-d47e23d1e701.png">

p.s. Idk if it's this stage the most precise in relation to the issue. But can help

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by cra0zy** [comment]
Looking at the log it seems that you are using MonoGame from source, however it also seems that you have not initialized all the submodules.

Run `git submodule init --update` in your MonoGame git directory.

**Comment by Lus1t4nUm** [comment]
I done it and the command let this output. I'm using native xcode Git. 
![printlis](https://user-images.githubusercontent.com/34067397/43014469-245c3b2a-8c44-11e8-9583-7ea986478f49.jpg)

**Comment by Lus1t4nUm** [comment]
I really missed that step. Thanks.
