### ISSUE TITLE
Inconsistent behavior of QueryRendertarget() and new RenderTarget2D()

### ISSUE THREAD

**Issue by MattiKloepper** [MonoGame/MonoGame#6384]
Just tried to create a RenderTarget2D with a SurfaceFormat of Vector4 in my android Project.
This works fine in my android Emulator (running with Oreo 8.0).

On an old Galaxy Tab with Jelly Bean 4.2 it fails  with a System.NotSupportedException ("The requested SurfaceFormat `Vector4` is not supported."). That could have been expected on such an old system.

What makes me wonder is that a call to "Graphics.Adapter.QueryRenderTargetFormat()" Returns TRUE for the same set of parameters (GraphicsProfile.HiDef, SurfaceFormat.Vector4, DepthFormat.None, 1). The out-Parameter for the selected SurfaceFormat is gets set to Vector4, too.

Shouldn't QueryRenderTargetFormat return false if the SurfaceFormat is not supported?

And I read the RenderTargets should fall back to the best alternative Format if a given Format is not supported. How should I check which SurfaceFormats are supported on my device?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1614

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Android

**Comment by MattiKloepper** [comment]
Looking at the code I discovered that QueryRenderTargetFormat does not really test the GraphicsAdapter for the requested Format but just check agains a hardcoded list of SurfaceFormats. 
Maybe I just misinterpreted the usecase of this function.

**Comment by nkast** [comment]
Are you working from your own branch/source code? then there are a couple of things you have to patch for this to work.

First you need to implement the `GraphicsAdapter.IsProfileSupported()`. #5953
(Probably there is a better way to do that by testing GL version and or some extensions)

Then you need a fallback strategy for the Profile in your Game class.  
https://github.com/MonoGame/MonoGame/pull/5312#issue-94659716
If have the profile set to Hidef without the fallback then the app will throw a profile-not- supported fail from the start on devices that don't support it.

For good measure you can also bring in #5451.
This will 
 * catch early on any errors when you try to use HiDef features instead of getting cryptic GL errors. 
 * let's you emulate and test the Galaxy Tab/Reach behavior right on your Desktop, by simply disabling the fallback code and set the profile to Reach.

**Comment by MattiKloepper** [comment]
I'm working with the Nuget packages from the development branch, Version 3.7.0.1614.
IsProfileSupported returns true for the HiDef profile on the Samsung tablet.

So how is the recommended behavior? Should IsProfileSupported return false for HiDef if float SurfaceFormats are not supported? Or are float formats an optional feature even in HiDef?

Interestingly the Samsung tablet seems to have an GLES 2.0 extension for float textures installed. I commented on this in #6264.

**Comment by MattiKloepper** [comment]
Just realized that "floating point textures" and "floating point rendertargets" are different capabilities most probably? Is there a minimum set of rendertarget-formats that HiDef ist guaranteed to support?

**Comment by nkast** [comment]
Yes, rendertargets are different than textures. One extreme example is the DXT1 compressed format which can't be compressed on the fly.

 XNA doesn't define which formats are supported as render targets.
https://blogs.msdn.microsoft.com/shawnhar/2010/07/09/rendertarget-formats-in-xna-game-studio-4-0/

* Well, I was wrong previously. Self detecting the profile is not enough, MG doesn't currently fallback from unsupported formats apart from some obvious ones (Compressed,etc). That's in #5451 *(https://github.com/MonoGame/MonoGame/pull/5451/commits/1e8621c42c400abf70f60731978e0e44fa30de7a).
In that some formats will fallback to `Color` when the profile is Reach. That's Based on tests on what XNA actually is doing. and also on what is and isn't supported on FL 9.1 and 9.3.
https://msdn.microsoft.com/library/windows/desktop/ff471324
Still there is no support for optional formats (BGR565 for example, but most of the formats should be supported in HiDef anyways).

Your only option I am afraid it to test the GL version yourself and fall back to a suitable format.

**Comment by MattiKloepper** [comment]
Ok, thanks. For now I'm just trying all formats at initialization and build up a list of supported ones.

**Comment by MattiKloepper** [comment]
No haste, this "problem" doesn't break anything.
I'd offer my help but I haven't looked into DirectX APIs for a lot of years and never into OpenGL. Don't even know if there is a way to query the supported Texture/Rendertarget formats 😑
