### ISSUE TITLE
Vector2 equality testing

### ISSUE THREAD

**Issue by spaaaaam** [MonoGame/MonoGame#6391]
Hi,

I'm probably missing something, but I have this weird behaviour with MG :
```
Vector2.Zero.Equals(new Vector2(0f, 0f))
```
returns false.

From https://github.com/ManojLakshan/monogame/blob/d5f9892d20bdca1168c5e5718c410d38bc4deeb9/MonoGame.Framework/Vector2.cs#L222 , it is as if it does object equality but not Vector equality.

If I test X & Y explicitly, it (obviously) works.

Is there another way to test Vector2 equality?

Thx

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1657-develop (nuget package)

#### What operating system are you using:
- Ubuntu 18.04 (x64)

#### What MonoGame platform are you using:

- DesktopGL

**Comment by cra0zy** [comment]
Vector2.Equals works just fine:
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Vector2.cs#L497
is calling
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Vector2.cs#L512

You can also just use `==` operator: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Vector2.cs#L236

Closing...

**Comment by spaaaaam** [comment]
Ok, something was broken on my side, I finally found a hint in the compiler outputs :

```
Target _HandlePackageFileConflicts:
    Encountered conflict between 'Reference:MonoGame.Framework' and 'Reference:MonoGame.Framework'.  Could not determine winner due to equal file and assembly versions.
```
I reinstalled the packages dependencies, and now it works as expected.

Thanks for your time!
