### ISSUE TITLE
Monogame installation failed from Visual Studio Mac extensions manager

### ISSUE THREAD

**Issue by Gamabunta57** [MonoGame/MonoGame#6399]
Hello !

I'm using a case sensitive disk partition on my mac and it causes troubles installing the visual studio mac extension for monogame. 
Actually the installer can't find 3 files due to the folder's name not matching. This is the error I got:

> /MonoDevelop.Docker/MonoDevelop.Docker.dll: The file '/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/docker/MonoDevelop.Docker/pt-BR/MonoDevelope.Docker.resources.dll' referenced in the manifest could not be found.
> /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/docker/MonoDevelop.Docker/MonoDevelop.Docker.dll: The file '/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/docker/MonoDevelop.Docker/zh-Hans/MonoDevelope.Docker.resources.dll' referenced in the manifest could not be found.
> /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/docker/MonoDevelop.Docker/MonoDevelop.Docker.dll: The file '/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/docker/MonoDevelop.Docker/zh-Hant/MonoDevelope.Docker.resources.dll' referenced in the manifest could not be found.

These files exist but those folders didn't use the same case on my computer:
- pt-BR => pt-br
- zh-Hans => zh-hans
- zh-Hant  => zh-hant

So I tried to rename those with capital letters, but I got the same kind of error. This was with the same folders, but instead with the other spelling. I think, somewhere in the package (I don't know how it works exactly) these folders are spelled with 2 spelling.

As a workaround I made symlinks between:
pt-BR => pt-br,
zh-Hans => zh-hans 
zh-Hant => zh-hant

This way it works for me.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Mac (with case sensitive partition)

**Comment by cra0zy** [comment]
When MonoDevelop is installing addins, it will complain if any other adding that you have installed has errors, in this case seems like MonoDevelop.Docker addin has errors.

SInce this has nothing to do with us, closing...
