### ISSUE TITLE
Idea: Add more features to the Quaternion struct

### ISSUE THREAD

**Issue by JulianAssmann** [MonoGame/MonoGame#6405]
I'd like to see the Quaternion struct expanded by some new helpful functions and properties, because I prefer to do certain things directly via quaternions. A few of my ideas:

- Normalized: The normalized quaternion
- Inversed: The quaternion inverse
- IsUnitQuaternion: Indicates whether the quaternion is a unit quaternion
- Vector3 ToYawPitchRoll(): converts the quaternion to (yaw-pitch-roll) angles
- Quaternion Pow(float power): pow operation for the quaternion
- Quaternion Sqrt(): square root of the quaternion
- Quaternion Log(float base): logarithm of the quaternion
- Vector3 RotateVector3(Vector3): Rotates a Vector3 by the rotation represented by the quaternion
- Matrix ToMatrix(): Converts the quaternion into a rotation matrix
etc.

I can provide the code, but is there any chance that this will make into MonoGame? If so, I would start to write the code.

**Comment by mrhelmut** [comment]
This kind of non-breaking additions are welcome. Feel free to setup a pull request for your code. I believe that the only requirement here would be that everything is correctly documented. The icing on the cake would be to have unit tests to bullet proof your proposition.

**Comment by tomspilman** [comment]
Hey @JulianAssmann !

First many of the things you are suggesting we already have.  So i am confused.

Normalize:
  https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Quaternion.cs#L956
Inverse:
  https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Quaternion.cs#L600
IsUnitQuaternion: 
  `Length` https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Quaternion.cs#L633
RotateVector3:
  https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Vector3.cs#L966
ToMatrix:
  https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Matrix.cs#L667

I think that most of your issues is not yet knowing the MonoGame library and not that we have much of anything missing.

> I believe that the only requirement here would be that everything is correctly documented.
> The icing on the cake would be to have unit tests to bullet proof your proposition.

Well to be very clear about this.  We REQUIRE documentation of new features and we REQUIRE unit tests.  New math will never be merged without them.

**Comment by JulianAssmann** [comment]
Hey @tomspilman!
Thanks for the response. I already knew about some of these functions (for example creating the matrix from a quaternion and so on) but thought, it would be nice for convinience to also have it in the Quaternion class. As I don't know how you guys think about that, I thought, I would suggest it and see.
For the other mistakes: I just wrote a Quaternion class for another purpose and obviously didn't look into the MonoGame Quaternion class well enough. I'm sorry for spamming this place.

**Comment by tomspilman** [comment]
> it would be nice for convinience to also have it in the Quaternion class.

I'm not convinced this is worth the confusion it would create with two methods that do the same thing.

> I'm sorry for spamming this place.

It wasn't spam at all... it is questions like this that often produce ideas/features.
