### ISSUE TITLE
Android game running fine with debugger attached if launched from IDE but really laggy otherwise

### ISSUE THREAD

**Issue by Doraku** [MonoGame/MonoGame#6408]
Hello there, first and foremost thank you for all this amazing work!

Allas not everything is sunshine as I find myself in a strange situation. As the title says my MonoGame android game runs fine if launched in debug (so no optimization) from my IDE (Visual Studio 2017 v15.7.6) on my phone (SONY Xperia z5 Compact E5823 Android 7.1 - API 25) but if I launch it manually from my phone (no debugger) it is super laggy, from stable 60fps to... 5? Same if launched in release (with optimization then) and obviously no debugger, completely unplayable. The emulator runs it fine.
Is there something I have completely missed? I thought having a debugger attached would made things slower, not the contrary! Are some things leveraged to my computer when debugging which make my phone appears to run my game smoothly hiding the fact that it's a mess in reality? I am pulling my hair over this.

I tried with both stable and preview last versions 3.6.0.1625 and 3.7.0.1681-develop, same thing. My project is built against Android 8.1 API 27 with the minimum android version 7.1 API 25.
Tried it on someone else Pixel 2 phone and apparently it runs fine, but unplayable on an other one android tablet (don't now which one).

This is my setup in the Game class
```
public DefaultGame(DisplayMetrics displayMetrics, AssetManager assets, Action moveTaskToBack)
{
    _assets = assets;
    _deviceManager = new GraphicsDeviceManager(this);
    _moveTaskToBack = moveTaskToBack;
    Content.RootDirectory = "Content";

    IsFixedTimeStep = true;
    _deviceManager.SynchronizeWithVerticalRetrace = false;
    _deviceManager.GraphicsProfile = GraphicsProfile.HiDef;
    _deviceManager.IsFullScreen = true;
    _deviceManager.PreferredBackBufferWidth = displayMetrics.WidthPixels;
    _deviceManager.PreferredBackBufferHeight = displayMetrics.HeightPixels;
    _deviceManager.SupportedOrientations = DisplayOrientation.LandscapeLeft | DisplayOrientation.LandscapeRight;
    _deviceManager.ApplyChanges();
}
```
My game is only using a SpriteBatch to draw around 650 sprites, all from the same sprite sheet so they are batched correctly together, although I am using the BackToFront mode so there is some sorting (not that changing it to Deferred made any difference...).
On .netcore MonoGame on my pc (not a beast i5-3570 cpu, 8Go ram, GeForce 660TI, Windows 10) I can push it to +48k for comparison before breaking from 60fps at 720p.
If that is important I am using C#7.0 features heavily with Span, ref return and all for my update logic if it is known to cause problem on android, not that I have found anything about that.

But yeah, it all boils down to: run fine on phone with debugger attached, unplayable otherwise :/ I don't have access to the android profiler with the community version of Visual Studio so I have no idea what is making it crap itself. Any magic checkbox I may have missed?

**Comment by nkast** [comment]
can you try with SynchronizeWithVerticalRetrace=true and or IsFixedTimeStep = false
and see if anything changes?

**Comment by Doraku** [comment]
Wow what the hell? At first I think it was true/true which had the same result and while searching for a reason I ended up somewhere recommending SynchronizeWithVerticalRetrace=false and IsFixedTimeStep = true because of some obscure reason with the vsync which is why I had it setup-ed like that. But trying true/false, it actually run smoothly now! I don't understand. Is there some problem with the IsFixedTimeStep on android (and especially when there's no debugger attached?!)?
Thank you this has really saved me :)

**Comment by nkast** [comment]
Maybe it's the problem with Thread.Sleep() in the gameloop but you need to re-build mg from source to verify it. It's the first time someone report this on android.

**Comment by Doraku** [comment]
I'll try to play with the develop branch if I have time when I get back from work.

**Comment by Doraku** [comment]
So I have been looking into it. Tried to change the wait mechanism but no luck there. Then just for the heck of it I tried to run at a lower fps (60 to 30)  and to my surprise things were running okay. My guess is that I overshoot ever so slightly my frame time at 60fps making it go into a weird update loop which, again, does not happen with a debugger attached...
Even if I reduced greatly the number of things in my scene I have this chopped behavior though so maybe it is something else :/ With 2600 sprites moving at 30fps it's ok but 130 sprites at 60fps and it is horrible (sub 10fps), it makes no sense!

This still bugs me but I will take the fixed 30fps for now (and I guess the phone batterie will be happy too) instead of being regulated with the vsync.

**Comment by nkast** [comment]
> stepCount is stable at... 20 :/

Does that mean that on each loop it's 20 frames behind?
And it's calling Update 20 times to catch up? (or put it in other words, skips 20 Draws)

So there's something else that's slowing down the loop. 
How about BeginDraw/draw/EndDraw(present)?  have you measured the time between those?

**Comment by nkast** [comment]
I found that android has a Game.Activity.RenderOnUIThread. 
I don't know much about it, some info can be founded [here](https://github.com/MonoGame/MonoGame/issues/3222). 

Maybe try to see if setting this to false changes anything...

**Comment by Doraku** [comment]
Yes that's what happening, I guess it max because of Game._maxElapsedTime. Game.RenderOnUIThread didn't have any impact. I disabled my draw and the debug info still showed a lot of update to catch up to. I can accept that my update is slow but it just doesn't make any sense for it to run perfectly with a debugger attached and to run like crap in release even way way less objects :/

**Comment by Doraku** [comment]
Ok so I just ran some tests. It seems my update time has actually a LOT of variation. It can be blazing fast or really slow (to do the exacte same thing) on my phone. And if I change it to run on a single cpu, then it's always blazing fast... so... my phone doesn't like multi threaded code it seems :/
Not an issue with MonoGame, just something inexplicable with my synchronization code that my phone does not like when there is no debugger around (does its presence change Environment.ProcessorCount by any chance as I am using that to create my threads?) >_> I'll look into that and close this issue.

I'm using a Barrier to synchronize my threads work if that rings any bell by the way, but thanks for helping me!
