### ISSUE TITLE
The 'pan' parameter in SoundEffect.Play is broken.

### ISSUE THREAD

**Issue by BrainSlugs83** [MonoGame/MonoGame#6409]
If you supply anything other than 0 to pan, it will move all sound to the right speaker.

I've tried with -1, 0, and +1;  0 works fine out of both speakers, but -1 and +1 both cause the sound to come out of the right speaker only.  (-1 should be the left speaker!)

I did some googling and it looks like other people have [run into this before](http://community.monogame.net/t/pan-stereo-does-not-work-at-all-for-soundinstances-or-soundeffects/7446/2), but I didn't see a bugs logged.

The suggested workaround in that forum post is to edit the sound file and bake the panning in, but that's just ridiculous, I should be able to specify a float for dynamic sound panning, and not need 100 versions of the same sound file.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.6.0.1625

#### What operating system are you using:
- Windows 10 (1803)

#### What MonoGame platform are you using:
- DesktopGL

**Comment by tdeeb** [comment]
Have you tested this on the latest develop build?

**Comment by cra0zy** [comment]
Should be fixed in 3.7, reopen if not.

**Comment by Toemsel** [comment]
Not fixed yet
