### ISSUE TITLE
[FX Compilation] Wrong parameter name for texture

### ISSUE THREAD

**Issue by elisee** [MonoGame/MonoGame#641]
When compiling a pretty basic FX file with a Texture parameter defined as:

```
uniform extern texture Texture;
```

and a texture sampler defined as:

```
sampler textureSampler = sampler_state
{
    Texture = <Texture>;
    mipfilter = POINT; 
    minfilter = POINT; 
    magfilter = POINT; 
};
```

XNA exposes an effect parameter named "Texture" whereas MonoGame exposes the same parameter as "textureSampler". This means I have to change my code from

```
Effect.Parameters["Texture"] = myTexture;
```

to

```
Effect.Parameters["textureSampler"] = myTexture;
```

**Comment by InanZen** [comment]
I'm still having the problem with parameter names.
When i compile for DirectX it works as intended (effect.Parameters["TextureName"] points to texture parameter), but when i compile for OpenGL the texture parameter names are SamplerName+TextureName (effect.Parameters["TextureName"] points to NULL, effect.Parameters["SamplerName+TextureName"] points to the texture parameter)

Here's my shader setup:
`Texture2D<float4> DiffuseTexture : register(t0);
Texture2D<float4> NormalTexture : register(t1);
Texture2D<float4> SpecularTexture : register(t2);
sampler LinearWrapSampler : register(s0);
`

**Comment by discosultan** [comment]
@InanZen Can confirm that this is still an issue with MonoGame 3.6

**Comment by InanZen** [comment]
@discosultan I've just pust an IF statement in my effect's parameter caching method.
```C#
texture_Diffuse = effect.Parameters["DiffuseTexture"];
if (texture_Diffuse == null)
    texture_Diffuse = effect.Parameters["LinearWrapSampler+DiffuseTexture"];

```

**Comment by discosultan** [comment]
@InanZen Yeah, luckily there are easy workarounds 👍 

I resorted to preprocessor directives:

```csharp
#if WINDOWSDX
    texture = effect.Parameters["Texture"];
#elif DESKTOPGL
    texture = effect.Parameters["TextureSampler+Texture"];
#endif
```

**Comment by Jjagg** [comment]
There's no way around that issue unfortunately. In DirectX samplers and textures are decoupled, while in OpenGL textures are part of the sampler state.
That means you can use 1 sampler to sample from two different textures in DirectX, but you'd need two samplers in OpenGL. When MojoShader generates the samplers it needs to generate 1 sampler for each sampler-texture combination used in the HLSL shader (e.g. 3 samplers, 3 textures in HLSL => 9 samplers in GLSL). It has to generate names for those samplers someway so it uses the name [Sampler]+[Texture].
