### ISSUE TITLE
Game loop running slowly in 3.7

### ISSUE THREAD

**Issue by CrimsonCastel** [MonoGame/MonoGame#6411]
Extremely slow performance of Application.DoEvents(); (which I understand is an OS call)

It is taking about 6ms per game loop to run the message loop on a high end fully up to date windows 10 machine.

Any idea why? This didn't seem to be an issue until I moved to 3.7 from 3.5 and it only happens when I move the mouse.

![image](https://user-images.githubusercontent.com/2770203/44071690-178e288e-9fce-11e8-9e4d-180a71cb8e8a.png)

Here is some basic profiling data, anything stand out to anyone?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopDX

**Comment by nkast** [comment]
DoEvents() was removed recently and replaced with Application.Run().
The reason was to reduce extensive garbage generated for Keyboard+Mouse events. 
Possibly what you see is a result of frequent GC. 

Can you update to the latest develop build and test it again?
The code still generates garbage but it's down to ~20%.

**Comment by Danthekilla** [comment]
Well that kinda fixed it...

So before I was getting 180 to 220fps (vsync off on a 240hz monitor) and when I moved my mouse (500 updates per second poll rate), the framerate dropped to a very choppy feeling 60-80fps but the timesteps were all over the place.

Now my framerate is around 100fps and only drops to 90fps when I move the mouse. And it is far more stable (not perfect, however)

I am about to run some memory profiling in both states and hopefully I will have more info.

**Comment by nkast** [comment]
Did you see it this is due to the GC or is it something else?
That would be the case especially if you have many small objects.
you could test a new project for example where the GC doesn't have much work to do.

It's possible to handle the WM_MOVE and other events directly so that WinForms won't generate new MouseEventArgs. But that will cripple things for those who use WinForms staff from within MonoGame as the WinForms will not know that a mouse event ever happen.

**Comment by nkast** [comment]
Here is the code in case you are interested for a custom build.

inside WinFormsGameForm WndProc() add the following:
```

            // TNC: handle those messages internally to avoid garbage from EventArgs
            switch (m.Msg)
            {
                case 0x0014: // WM_ERASEBKGND
                    return; // skip repaint of the control under the swapchain (PaintEventArgs)
                case 0x020A: // WM_MOUSEWHEEL
                    var delta = (short)(((ulong)m.WParam >> 16) & 0xffff);
                    _window.MouseState.ScrollWheelValue += delta;
                    return;
                case 0x020E: // WM_MOUSEHWHEEL
                    var deltaH = (short)(((ulong)m.WParam >> 16) & 0xffff);
                    _window.MouseState.ScrollWheelValue += deltaH;
                    return;
                case 0x0200: // WM_MOUSEMOVE
                    return;
```

**Comment by Danthekilla** [comment]
Do I need to remove any existing code or is this change it?

I will give it a go tomorrow and get back to you.

**Comment by nkast** [comment]
[Here](https://github.com/nkast/MonoGame/commit/d50362ee628ec7bc8aa07b383fd8f16e3c3fa36f) is the whole thing. You can merge it into the existing switch if you like, I keep it separate to avoid conflicts when rebasing with MG. 

You might also like to r[emove keyboard garbage](https://github.com/nkast/MonoGame/commit/d400ae0a5bc5ff6b0b9f72729c29fd3e41d5418c), even though those are not as frequent.

**Comment by Danthekilla** [comment]
I swapped out for that and now I get a rock stable 210 fps at my lower resolution and no drop when using the mouse which is fantastic.

However, no only 10% of mouse scroll events get received, any idea why I might be getting that or how I might avoid that?

Thanks heaps for your help nkast.

**Comment by nkast** [comment]
>> I swapped out for that and now I get a rock stable 210 fps at my lower resolution and no drop when using the mouse which is fantastic.

Good to know! 
ping @tomspilman , @Jjagg , Is it OK to have this low-level handling in the main repo? It might not play well for devs that mix WinForms controls with monogame.

>> However, no only 10% of mouse scroll events get received, any idea why I might be getting that or how I might avoid that?

What you mean by that? Are you still getting MouseScrollEventArgs or the scroll is losing event/not responding?
Also, I had a bug in the code: WM_MOUSEHWHEEL should increase the `HorizontalScrollWheelValue`.

**Comment by Jjagg** [comment]
> Is it OK to have this low-level handling in the main repo?

Yes, of course, if it solves this issue! But we need to make sure it's fully functional first.

**Comment by Danthekilla** [comment]
@nkast 
> What you mean by that? Are you still getting MouseScrollEventArgs or the scroll is losing event/not responding?

Yeah... I had a bug, I was setting ScrollWheelValue and HorizontalScrollWheelValue rather than adding to them.

It all works now and I get great performance with no apparent issues so far.

**Comment by cra0zy** [comment]
Closing as the last comment states that this is fixed.
