### ISSUE TITLE
OpenGL 3.1 error

### ISSUE THREAD

**Issue by Absolute-Code** [MonoGame/MonoGame#6414]
Hello !

I created a classic monogame window project and everything works fine :)

I create a monogamous project cross platform ... and here I am told: Opengl 3 required

I have a fairly old chipset (Intel HD Graphics 2000) but it supports OpenGL 3.1

How do I fix my problem?

**Comment by D4v1ks** [comment]
Yes, Intel HD Graphics 2000 is a old chip.
If you have the latest drivers installed, you could start by downloading a tool like "OpenGL Extensions Viewer", to see if your current drivers really supports OpenGL 3.1 before think in fixing it.

**Comment by Absolute-Code** [comment]
It is precisely from this tool that I come to you

![image](https://user-images.githubusercontent.com/40502530/44266625-7a109280-a22b-11e8-8c39-cdc0288d1774.png)

**Comment by D4v1ks** [comment]
It could be just the case of a particular extension missing, or an issue on the driver itself, which is no longer supported by intel.

**Comment by Absolute-Code** [comment]
Or a problem coming from monogamous

**Comment by Absolute-Code** [comment]
And .. for Window 8.1 ?

**Comment by Absolute-Code** [comment]
Because i see https://downloadcenter.intel.com/fr/download/24971/Pilote-pour-Graphiques-HD-Intel-pour-Windows-7-8-64-bits?_ga=2.137854128.1634816141.1535387990-187066553.1535387970 support for Window 8 ! And 8.1 ?

**Comment by mrhelmut** [comment]
Yes, it should be ok on 8 and 8.1. At least the 64bit systems.

**Comment by Absolute-Code** [comment]
in doubt I install Window 7

**Comment by Absolute-Code** [comment]
so thanks to this change of g system I could use Monogam without problem?

**Comment by mrhelmut** [comment]
Yes, it should work, providing that you install the latest drivers from Intel.

**Comment by Absolute-Code** [comment]
OK !
I installed Window 8.1 and successfully launched a game that runs on Monogame Cross Platform :)
However, I would like to know if you would have a project using push functions of Monogame ? To see if it really works, I really do not want to come across an error with opengl when I would like to make things a bit more complex.

Anything else, do you plan to upgrade to a newer version of opengl in the near future?

**Comment by Absolute-Code** [comment]
I would like to know how I can be sure that the Monogame cross platform version works on my computer?

Currently the basic project works but I would like to know if there is a way to know if my chipset will really hold ..

In fact, why on Window 10 the project "Windows" using DirectX worked?

A difference between DirectX and Opengl?

**Comment by mrhelmut** [comment]
I've already explained this:

> Intel has never provided a fully OpenGL 3 compliant driver for HD2000/HD3000 on Windows 10.

You can thank Intel for not issuing up-to-date OpenGL drivers on Windows 10 for their older processors.

Even though HD2000 and HD3000 are technically compatible with OpenGL 3 / Direct3D 10, Intel only shipped the Direct3D 10 driver on Windows 10 and slacked on the OpenGL one.

It is absolutely not a MonoGame issue, it's 100% an Intel driver problem.

**Comment by Absolute-Code** [comment]
I understand better so my chipset is compatible with Monogame as I remain under W 8.1 because of the drivers

**Comment by Absolute-Code** [comment]
As a matter of fact, if I install window 8.1 and the Intel driver and then I go to Window 10

Will it work? Or would I still have the problem of drivers

**Comment by mrhelmut** [comment]
You'll have the same problem. Drivers are bound to the version of Windows, and they'll get updated when upgrading to Win10.
It is impossible to take the Win8/7 driver and make it work on 10.

Intel has deprecated HD2000 and HD3000 on Windows 10, there's no way around it.

**Comment by Jjagg** [comment]
I'm closing this because it's a driver issue, but feel free to continue the discussion.
