### ISSUE TITLE
path is slightly wrong in MonoGame.Content.Builder.targets

### ISSUE THREAD

**Issue by qntf** [MonoGame/MonoGame#6417]
path is slightly wrong in MonoGame.Content.Builder.targets from https://www.nuget.org/packages/MonoGame.Content.Builder/, as of the current version 3.7.0.9.

on L74 it says:

`Command="$(MgcbCommand) /@:&quot;%(ContentReferences.FullPath)&quot; /platform:$(MonoGamePlatform) $(MgcbArguments) /outputDir:&quot;%(ContentReferences.ContentOutputDir)&quot; /intermediateDir:&quot;%(ContentReferences.ContentIntermediateOutputDir)&quot;"`

but it should be

`Command="&quot;$(MgcbCommand)&quot; /@:&quot;%(ContentReferences.FullPath)&quot; /platform:$(MonoGamePlatform) $(MgcbArguments) /outputDir:&quot;%(ContentReferences.ContentOutputDir)&quot; /intermediateDir:&quot;%(ContentReferences.ContentIntermediateOutputDir)&quot;"`

(Adding quotes around the `$(MgcbCommand)` because the path to MGCB might have spaces, like my username on Windows.

**Comment by qntf** [comment]
(Path is `monogame.content.builder.3.7.0.9\build\MonoGame.Content.Builder.targets`)

inside the `<Target Name="RunContentBuilder">`

**Comment by cra0zy** [comment]
PR updated, new nuget package will be published some time in the future.

https://github.com/MonoGame/MonoGame/pull/6295/commits/8d20aa3e9296c88dd82e657daedc5978d24d1692

**Comment by bjornenalfa** [comment]
This is still a problem in the current latest nuget package.
