### ISSUE TITLE
Add interfaces for high level objects like SpriteBatch and GraphicsDeviceManager

### ISSUE THREAD

**Issue by grofit** [MonoGame/MonoGame#6419]
## Problem

Currently it is very difficult to test code which depends on certain parts of Monogame, such as `SpriteBatch` as you cannot mock the object making your tests require actual instances of SpriteBatch (which in turn requires GraphicsDeviceManager instance etc), and while there are some test classes internally in MG source they are not really exposed externally.

Due to this the only way to get around it at the moment is to create your own inherited version which tries to counter the underlying behaviour from base classes, and also use some pragmas to switch between test code and real code which is VERY bad as my source code shouldn't need to know it is being tested, and would end up with some test specific code being bundled into my actual game source.

I am also wanting to make use of Dependency Injection which is far better when using interfaces as you are able to bind interfaces to implementations far easier than binding concrete classes to themselves.

There is also the problem that because of not using interfaces a lot of internal MG code is having to use partial classes or other tricks to have platform specific code run, i.e winRT, SDL related code for `GraphicsDeviceManager`. A lot of this could be avoided if interfaces were adopted for surface API contracts and then composition used within platform specific packages to bundle the specific optimizations/required.

## Solution

Wherever possible on the surface API (ones consumers often use) add interfaces which expose the public methods/properties and use that as the contract on exposed MG code.

For example if we had `ISpriteBatch` we could mock this within a test without needing any form of underlying graphics device etc, also this would mean that we could easily provide our own implementation if needed and, this would also mean that all code depending on this only cares about the surface API contract, not the underlying implementation behavior, so if you needed to make platform specific optimizations you can do so without effecting the consumer too much, as the contract doesnt change, just the underlying implementations. 

The only down side to adding interfaces and using them as the contract around the framework would be the impact on using interface methods (akin to virtual methods) vs direct calls, which depending on throughput can create an almost non existent performance difference.

Going forward this allows users to do more with the library in varying scenarios from testing, plugins, extensibility, dependency injection etc, and makes the framework easier to chunk up and move towards a more singular `MonoGame.Core` which could contain all truly shared functionality and interfaces, and just have platform specific implementations, ultimately making it more flexible going forward.

## Other info

If you have resharper this is not too difficult to do as you can literally extract interfaces quickly for most objects, then just find all usages of that concrete class and replace it wherever needed with an interface.

If there are any performance critical internal pieces by all means skip putting interfaces in, but for surface API there is virtually no downside other than the overhead of implementing it.

**Comment by cra0zy** [comment]
As I stated on Discord channel, I am against this idea, so I'm just gonna leave to the other maintainers to decide.

**Comment by vpenades** [comment]
As an alternative for helping testing internal objects, there's the option to tell monogame to be "friend" of the test assembly. That way, they test project can see the internal classes/object as public.

`[assembly:InternalsVisibleTo("monogame.test.framework")]`

**Comment by Jjagg** [comment]
IMO we could add interfaces for user convenience.

Though we will not use them internally and switch out our current solution with separate builds. Tom has mentioned before that he is against that. The biggest con (and a blocker by itself) is that we would have to change the API a lot (think of creating instances of classes with platform specific code).

**Comment by grofit** [comment]
I did have a quick stab at adding interfaces and was going to see how far I could go down the path, now for high level customer facing objects like `ISpriteBatch` and other such things its not too bad, but when you start trying to do `IGraphicsDeviceManager` (or whatever its called) things start getting iffy as beyond that point you have LOTS of internal methods which cannot easily be handled via the interfaces, unfortunately I am busy with releases on multiple other projects so will try and get back into it soon.

**Comment by vpenades** [comment]
@grofit How to deal with GraphicsDeviceManager is a recurring problem that me, and others have brought in the past.

[Here's](https://github.com/MonoGame/MonoGame/issues/6175#issuecomment-369856371) a (somewhat unrelated) thread that also discussed the topic.

**Comment by Jjagg** [comment]
> @Jjagg what is the problem with having different implementations for different platform specific code? I am all for code reuse wherever possible but sometimes it can become a false economy, I could see loads of internal and partial methods in place to work around this problem, but given the net core change coming up I assume you will be re-writing chunks anyway, so it may be worth investing some time in trying to move away from internals and partials for some of this stuff.

@grofit You misunderstand me. Of course MG itself needs platform-specific code, but we want to avoid forcing users to modify their code for each platform. If we switch to an interface system with implementations for all platforms users would need to create e.g. a Texture2D by calling `var tex = new Texture2DDesktopGL(gd, width, height)`, tying their implementation to the platform they target which is exactly what MG tries to prevent. Usually this is fixed with factory objects/methods, but that would require major changes to the MG API.

**Comment by qril** [comment]
making your own abstraction that encapsulates the MonoGame's SpriteBatch would be a more correct solution.

**Comment by Jjagg** [comment]
I'm closing this issue because MonoGame will not use interfaces internally and adding interfaces just so users can mock MG classes or switch out implementations IMO is not effective considering how specific the API is. As @qril suggested in his comment above, you can abstract over MG classes by wrapping them and delegating the required methods.

For a relevant discussion and arguments against the idea of moving away from the current conditional builds/partial classes solution see #6175.
