### ISSUE TITLE
Why do you write suspend my account under Monogam community?

### ISSUE THREAD

**Issue by sourceskyboxer** [MonoGame/MonoGame#6422]
ASSHOLE I HAVE TOLD YOU PLEASE REMOVE MY ACCOUNT FROM COMMUNITY IF YOU STAY THAN I WILL SHOW POLICE IN GERMANY IF YOUR EXTORTION HOLDS AS SUSPENSION 

1 year hahaha you forget i never come back. Cra0zy is bad hurter again my deafness 

I will tell police in Germany.  Muhaha you will get punishment.  I am right.

**Comment by tomspilman** [comment]
FYI.  I blocked this user for a month.

**Comment by tomspilman** [comment]
Actually... Changed my mind.  Blocked forever.

**Comment by tomspilman** [comment]
Leaving this issue up as a paper trail just in case we need it.  Do not delete.
