### ISSUE TITLE
3D Sound (Emitter/Listener) not working properly

### ISSUE THREAD

**Issue by svantechgit** [MonoGame/MonoGame#6426]
When running 3D sound the sound will not come from the correct direction.
The problem is that AudioEmitter and AudioListener is converted wrong to X3DAudio.
Forward vector is inverted instead of only the Z component.
Up vector is not adjusted at all but must also have the Z component inverted.

SoundEffectInstance.XAudio.cs adjust following in ToDXListener() and ToDXEmitter()
forward *= -1.0f;
To: 
forward.Z *= -1.0f;
up.Z *= -1.0f;

The problem also most likely exist in Windows8\SharpDXHelper.cs ToEmitter() and ToListener()

/Tommy

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:
- WindowsDX

**Comment by Yheeky** [comment]
3D sound isn't working for me since upgrading to 3.7 as well. Worked like a charm previously...please fix this

**Comment by squarebananas** [comment]
Looks like I made a duplicate issue of this here: #7388
Fixed: #7389
