### ISSUE TITLE
Mouse events still firing when a windowed Monogame app no longer has focus and is behind other windows

### ISSUE THREAD

**Issue by YTN0** [MonoGame/MonoGame#6428]
I have a windowed DirectX app. When my app is behind other windows (but not minimized) e.g. behind Visual Studio, Notepad++ etc, I still get mouse events firing when I click on other apps that are in front of it. The other apps function as normal (e.g. clicking on lines of code in the IDE in Visual Studio, but the Monogame app behind it also receives these mouse clicks and is triggering the game functionality.

I would expect the Monogame app not to receive mouse events when it no longer has focus.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1491

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

WindowsDX

**Comment by cra0zy** [comment]
This is actually how XNA worked, check `Game.IsActive` property to check if the window is in focus.
