### ISSUE TITLE
SharpDX library versions do not match what is referenced in source code.

### ISSUE THREAD

**Issue by KinsonDigital** [MonoGame/MonoGame#6431]
The version of the SharpDX libraries showing in the references section of the **MonoGame.Framework.WIndows** project are showing version **v4.0.1.0.**  The branches I checked the references under were **master** and **develop**.

This led me to believe that the version that is used in my project when creating a visual studio project would be the same version of **v4.0.1.0**.

I checked the version being pushed into my bin\debug folder and noticed that the versions are indeed **v2.6.3,** not **v4.0.1.0**.

Is this intentional?  I checked the installation directory where monogame for visual studio is installed and those binaries are indeed SharpDX libraries are **v2.6.3** as well.  This makes sense to me of course because I am sure that when a monogame project is built, this location is where the binaries are being pulled from when pushing into the bin\debug folder.

I was expecting the **master** branch to show **SharpDX v4.0.1.0** and the **develop** branch to possibly show a later version.  But this was not the case.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.6.0.1625

#### MonoGame Installation Assemblies Directory ####
C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:
- DesktopDX

**Comment by KinsonDigital** [comment]
I also tried to manually install the **SharpDX** nuget packages for version **v2.6.3** instead of **v4.0.1.0**.  This did not work.  Visual Studio gave me an error that **SharpDX** was not compatible with net **.NETFramework v4.0**.

How is this possible since the MonoGame project templates use **v2.6.3**?

#### Here are the errors I get. ####
![image](https://user-images.githubusercontent.com/4921022/45842369-8e442580-bcea-11e8-8587-48268a74db62.png)

#### .NET Framework version of project with issues ####
.NET Framework **v4.6.1**

**Comment by tomspilman** [comment]
> I checked the version being pushed into my bin\debug folder and noticed that the versions are indeed v2.6.3, not v4.0.1.0.

That is weird.  I just looked at my local copy and the versions on disk are clearly 

![image](https://user-images.githubusercontent.com/103522/45845088-b5e6be00-bce9-11e8-8229-2f9828c7896d.png)

Did you maybe forget to update the dependencies submodule?  I suspect you haven't and are using the dependencies from the master branch with the develop branch.

**Comment by KinsonDigital** [comment]
I am not having this issue while using the source project directly.  This is just a couple MG projects created with visual studio.

Is that what you mean?

**Comment by tomspilman** [comment]
> This is just a couple MG projects created with visual studio.

So you are working from the MonoGame installer and creating a new project from a template in VS?

**Comment by KinsonDigital** [comment]
Yes.  I am just working off of a MonoGame project that was created using Visual Studio.

If I create a blank project in Visual Studio 2017, and I hover over the produced output in the **x86\Debug** folder, I see this below.

![image](https://user-images.githubusercontent.com/4921022/45851114-26e89e80-bd07-11e8-89e3-b29e3ff41e93.png)

----------------------------------------------------------------------------------------------------

Below is the version of **SharpDX.dll** in the MonoGame installation directory.

![image](https://user-images.githubusercontent.com/4921022/45851157-631bff00-bd07-11e8-8827-0d5c7efd0045.png)

----------------------------------------------------------------------------------------------------

This is a screenshot of the version shown in the MonoGame source in Visual Studio in the properties window.  This is on the develop branch.  But as you can see at the bottom it will not let me build.  I only assume this is because I have to probably run **protobuild** every time I switch branches?

![image](https://user-images.githubusercontent.com/4921022/45851256-f9e8bb80-bd07-11e8-8f25-3a216d2c19b8.png)

----------------------------------------------------------------------------------------------------

This is a screenshot of the same thing as above, except its on the develop branch.

![image](https://user-images.githubusercontent.com/4921022/45851309-36b4b280-bd08-11e8-9c42-b4a89c46b07e.png)

----------------------------------------------------------------------------------------------------

And here is the screenshot of the **SharpDX** binary version in the output folder of the develop branch that Visual Studio produces.  This one does indeed show **v4.0.1.0**

![image](https://user-images.githubusercontent.com/4921022/45851348-69f74180-bd08-11e8-81ca-cf10eda84a58.png)

Maybe this is just simply the building process of the installation package?

Hope this helps!!  If you need anything else, let me know.

**Comment by tomspilman** [comment]
Try the develop branch installer and see if that solves it for you:

http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/latest.lastSuccessful/MonoGameSetup.exe?guest=1

**Comment by KinsonDigital** [comment]
Very awesome!! It worked!!  

So at this point we just wait until v3.7 is out.  Have any idea yet when that will be?

Actually, even more interesting to me, what is the status of moving to .NET Core.  If that is currently happening that is.

Thanks a bunch.  😄

**Comment by tomspilman** [comment]
> So at this point we just wait until v3.7 is out. Have any idea yet when that will be?

Well you don't have to wait... that installer works fine and is as stable as the release will be.

I'm the blocker... i will try to get it out in the next few days.

>  what is the status of moving to .NET Core. If that is currently happening that is.

We're working towards it.   We will support it in 3.8 i'm sure.

**Comment by KinsonDigital** [comment]
Whoo hoo!! Very cool.  Anything I can do to help to move the process along?  Simple stuff to start out with?
