### ISSUE TITLE
Drag and drop doesn't work in the Pipeline Tool

### ISSUE THREAD

**Issue by simoneddeland** [MonoGame/MonoGame#6436]
I installed MonoGame 3.7 and I can't drag and drop image files in the Content Pipeline Tool on Windows anymore. I uninstalled and reinstalled to see if something went wrong during the install but the problem persists. I can still add content with "Add -> Existing item" and building it also works.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by cra0zy** [comment]
Duplicate of #6248, closing...
