### ISSUE TITLE
The "Add file" window in the Pipeline Tool sometimes appear off-screen.

### ISSUE THREAD

**Issue by simoneddeland** [MonoGame/MonoGame#6437]
When adding content in the Pipeline Tool a window appears asking if I want to copy the file or add a link to it. Sometimes this window appears off the screen. Maybe it should always appear in the same place as the Content Pipeline Tool window?

FYI, I am running a desktop resolution of 3440x1440 (21:9 aspect ratio).

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by cra0zy** [comment]
Oh yea, I remember noticing something like this on Windows, but I forgot to take a look as it happened on Windows... I'm not very often on Windows as one might imagine.

**Comment by Jjagg** [comment]
Fixed in #6451!
