### ISSUE TITLE
MonoGame installer doesn't notify about/install Visual C++ redistributable package

### ISSUE THREAD

**Issue by AimedNuu** [MonoGame/MonoGame#6439]
Issue: MonoGame installer doesn't notify about/install Visual C++ redistributable package
This will cause MonoGame Content Builder to fail execution if there's no visual C++ installed.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL

**Comment by mrhelmut** [comment]
The installer has been deprecated.
