### ISSUE TITLE
MonoGame Content Builder exits with 9009 error code if solution path contains spaces

### ISSUE THREAD

**Issue by AimedNuu** [MonoGame/MonoGame#6440]
Issue: MonoGame Content Builder exits with 9009 error code if solution path contains spaces

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL

**Comment by cra0zy** [comment]
Duplicate of: #6417
