### ISSUE TITLE
MonoGame 3.7.0.1708: Multisampling fails on Windows® 10 UWP (XAML)

### ISSUE THREAD

**Issue by AdrianWenz** [MonoGame/MonoGame#6442]
The instruction 'Graphics.PreferMultiSampling = true;' still crashes the application as with previous releases of MonoGame.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1708

#### What operating system are you using:
- Windows 10 (17134.285)

#### What MonoGame platform are you using:

- WindowsUWP + XAML

**Comment by Jjagg** [comment]
More information in [this comment](https://github.com/MonoGame/MonoGame/issues/6178#issuecomment-376241755) from #6178.

**Comment by YTN0** [comment]
Ran into this problem recently.
From googling, I found the following article that might help whomever can fix this...

https://docs.microsoft.com/tr-tr/windows/uwp/gaming/multisampling--multi-sample-anti-aliasing--in-windows-store-apps

**Comment by cilliemalan** [comment]
Here is a possible workaround:

https://gist.github.com/cilliemalan/9e4bb05bf4bfbbb4ad011d36096e81e3

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
