### ISSUE TITLE
Sprite Effect files not being built via Pipeline Tool.

### ISSUE THREAD

**Issue by Safebox36** [MonoGame/MonoGame#6445]
Suddenly every Sprite Effect file won't build with the Pipeline Tool, even newly created ones.
Error given by Pipeline Tool:
![image](https://user-images.githubusercontent.com/28492621/46171101-801c7900-c297-11e8-9937-b9c0fbd7d4ad.png)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by cra0zy** [comment]
You are missing DirectX: https://github.com/MonoGame/MonoGame/issues/5436

Also a duplicate issue, so closing...
