### ISSUE TITLE
TextInputEventArgs.Keys is empty

### ISSUE THREAD

**Issue by live627** [MonoGame/MonoGame#6447]
TextInputEventArgs doesn't have the Keys property filled. This also affects both UAP and MacOS from looking at the codebase.

https://github.com/MonoGame/MonoGame/search?q=OnTextInput&unscoped_q=OnTextInput

https://github.com/MonoGame/MonoGame/blob/6ce62db0566114b5ed1adb655c7a13d9e1371bff/MonoGame.Framework/Windows/WinFormsGameWindow.cs#L328

Suggested code change:

```
using Keys = Microsoft.Xna.Framework.Input.Keys;

OnTextInput(sender, new TextInputEventArgs(e.KeyChar, (Keys)e.KeyChar));
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WinDX

**Comment by Jjagg** [comment]
This has been fixed for all desktop platforms! We had to do some work arounds for Windows DX and UWP, please open a new ticket if you run into any issues.
