### ISSUE TITLE
MonoGame pipeline tool crashes

### ISSUE THREAD

**Issue by Jack-Ji** [MonoGame/MonoGame#6448]
Right click root node Content and select add existing folder, click cancel button without
selecting directory, the pipeline tool will simple crash.

Here's call stack:

System.InvalidOperationException: File name not available - dialog was canceled.
   Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.CheckFileNamesAvailable()
   Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.get_FileName()
   MonoGame.Tools.Pipeline.MainWindow.ChooseContentFolder(String initialDirectory, String& folder)
   MonoGame.Tools.Pipeline.PipelineController.IncludeFolder()
   Eto.Forms.Command.OnExecuted(EventArgs e)
   Eto.Forms.Command.System.Windows.Input.ICommand.Execute(Object parameter)
   Eto.Forms.MenuItem.OnClick(EventArgs e)
   Eto.Forms.MenuItem.Callback.OnClick(MenuItem widget, EventArgs e)
   Eto.Wpf.Forms.Menu.MenuItemHandler`3.OnClick()
   System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   System.Windows.Threading.DispatcherOperation.InvokeImpl()
   System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   System.Windows.Threading.DispatcherOperation.Invoke()
   System.Windows.Threading.Dispatcher.ProcessQueue()
   System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   System.Windows.Application.RunDispatcher(Object ignore)
   System.Windows.Application.RunInternal(Window window)
   MonoGame.Tools.Pipeline.Program.Main(String[] args)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
 WindowsDX

**Comment by Jjagg** [comment]
Fixed in #6449!
