### ISSUE TITLE
Position of game screen is not correct on Xbox One

### ISSUE THREAD

**Issue by olivegamestudio** [MonoGame/MonoGame#6468]
Start up Windows Universal project with remote machine option for Xbox One.
Notice game screen is not positioned correctly on screen. e.g. off the top left and not filling the entire screen.
As a side the resolution is 1728 x 972 which seems odd.
See screenshot for more information.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Xbox One

#### What MonoGame platform are you using:
WindowsUWP

![img_0143](https://user-images.githubusercontent.com/11839289/46439792-6082c600-c759-11e8-8b41-b850f538b344.jpg)

**Comment by cra0zy** [comment]
MonoGame has 2 ways of handling fullscreen:
- Without hardwaremodeswitch, in which case scaling of the game screen is left to the developer
- With hardwaremodeswitch, not all platforms support this, for example UWP platform does now and as such you actually have to use the first method. This method tries to change the resolution of the screen to the desired one. This is how XNA acts, and in this day and age, games, at least on Linux, never change the host resolution.

I would recommend asking about handling screen scaling on the MonoGame community forum as I don't have enough time to go into this in full detail on this: http://community.monogame.net
