### ISSUE TITLE
Playing the video doesn't work anymore.

### ISSUE THREAD

**Issue by esengine** [MonoGame/MonoGame#6487]
When I use the MP4 file format for playback, only the sound has no picture. Is it wrong for me?

```C#
var video = Content.Load<Video> ("testVideo");
var videoPlayer = new VideoPlayer();
videoPlayer.Play(video);
```

What code is needed to make it appear?

#### What version of MonoGame does the bug occur on:
MonoGame 3.7
#### What operating system are you using:
- Windows
#### What MonoGame platform are you using:
- WindowsDX

**Comment by mrhelmut** [comment]
You have to draw the picture by retrieving the player texture handle with ```videoPlayer.GetTexture()```.

Unless there's a real issue, would you mind closing it and referring to the community forum for further help if need be?

**Comment by Jjagg** [comment]
Hey @esengine! Like @mrhelmut said, the [community forum](http://community.monogame.net/) is the place for questions. The issues here are for bugs and feature requests.
