### ISSUE TITLE
master branch and v3.7 tag are out of sync

### ISSUE THREAD

**Issue by bonimy** [MonoGame/MonoGame#6495]
# Issue
As far as I can understand, the [`master`](https://github.com/MonoGame/MonoGame/tree/master) branch is supposed to always point to the latest release tag. In this case, [`v3.7`](https://github.com/MonoGame/MonoGame/tree/v3.7). The current git log looks like this: 
```
$ git log --graph master v3.7
* commit 3d26a001c302ac30093fec5e28f2a1924ef7f894 (tag: v3.7)
| Author: Tom Spilman <tom@sickheadgames.com>
| Date:   Sun Sep 23 16:41:17 2018 -0500
|
|     Update changelog for 3.7 release.
|
| *   commit 0146cf60fe86e9cd092ee3e3840fa4bfc7aa2553 (HEAD -> master, upstream/master)
| |\  Merge: 1c09add4a 76cb3d64e
| | | Author: Tom Spilman <tom@sickheadgames.com>
| | | Date:   Sun Sep 23 16:53:34 2018 -0500
| | |
| | |     Merge pull request #6434 from SickheadGames/release_3_7
| | |
| | |     Release 3.7
| | |
| | * commit 76cb3d64ef86006aa6679645efbac1add26b5aa4
| |/  Author: Tom Spilman <tom@sickheadgames.com>
|/|   Date:   Sun Sep 23 16:41:17 2018 -0500
| |
| |       Update changelog for 3.7 release.
| |
* |   commit a97df67f947481b472cd4ba707f455e16d221183
| |  Merge: eace6bc53 220d70b8f
| | Author: Harry <cra0zy@gmail.com>
| | Date:   Sun Sep 23 09:25:30 2018 +0200
| |
| |     Merge pull request #6433 from SickheadGames/ios_avsession
| |
| |     Fixed audio interruption bug on iOS
| |
...
| *   commit 1c09add4a7407cf14690614d5ec36666d6c2a8ea (tag: v3.6, origin/master)
| | Merge: 071136f3c 27d269096
| | Author: Tom Spilman <tom@sickheadgames.com>
| | Date:   Wed Mar 1 07:03:21 2017 -0800
| |
| |     Merge pull request #5526 from SickheadGames/release_3_6
| |
| |     Release 3.6
| |
...
```
Where `upstream` remote is MonoGame and `origin` is my form. It appears that `master` pointed to `v3.6` while that one was the latest release.

It looks like 76cb3d64e and 3d26a001c both supplied the same changes (Update changelog for 3.7 release), and at the same time, but for some reason diverged the history.

## Proposed Resolution
`git diff master v3.7` produces no output so the code is at least identical. The only reasonable change I can think of (if any change at all should be done) would be to move the v3.7 tag from 3d26a001c to 0146cf60f. Looking at the previous releases, the tags were always assigned to master once it merged the latest release changes. So this is what should have happened at least.

That can obviously be a bad idea if anyone (foolishly) has added commits on their fork to the v3.7 tag.

I'm not sure how big of a deal this is, but I thought it would be worth bringing up.

**Comment by tomspilman** [comment]
@bonimy - Yeah not sure why i did it that way last time.

I've done it correctly in 3.7.1 and documenting the process better so i don't forget.

Also doing a merge of master back into develop as there are some old commits that have no changes, but were different between the branches.  See https://github.com/MonoGame/MonoGame/pull/6575
