### ISSUE TITLE
Runtime exception "Shader Compilation Failed" on iOS and Android, works on Windows

### ISSUE THREAD

**Issue by dtaylorus** [MonoGame/MonoGame#6499]
I am successfully using a shader on Windows and now trying to port it to iOS and Android.

The shader compiles just fine via the content pipeline for iOS and Android.

However, it fails with the following exception at runtime on iOS and Android:

> System.InvalidOperationException: Shader Compilation Failed occurred

The HLSL version of the shader is:

````
#if OPENGL
	#define SV_POSITION POSITION
	#define VS_SHADERMODEL vs_3_0
	#define PS_SHADERMODEL ps_3_0
#else
	#define VS_SHADERMODEL vs_4_0_level_9_3
	#define PS_SHADERMODEL ps_4_0_level_9_3
#endif

float2 TextureSize;
float PxRange;

sampler TextureSampler : register(s0);

float4 SamplePS(float4 Position : SV_POSITION, float4 Color : COLOR0, float2 TexCoord : TEXCOORD0) : SV_TARGET0
{
	float2 msdfUnit = PxRange / TextureSize;
	float3 samp = tex2D(TextureSampler, TexCoord).rgb;
	float sigDist = max(min(samp.r, samp.g), min(max(samp.r, samp.g), samp.b)) - 0.5f;
	sigDist *= dot(msdfUnit, 0.5f / fwidth(TexCoord));
	float opacity = clamp(sigDist + 0.5f, 0.0f, 1.0f);
	return Color * opacity;
}

technique Technique1
{
	pass Pass1
	{
		PixelShader = compile PS_SHADERMODEL SamplePS();		
	}
};
````

The GLSL created by the content pipeline is:

````
#ifdef GL_ES
precision mediump float;
precision mediump int;
#endif

uniform vec4 ps_uniforms_vec4[2];
const vec4 ps_c2 = vec4(-0.5, 0.5, 0.0, 0.0);
vec4 ps_r0;
vec4 ps_r1;
vec4 ps_r2;
#define ps_c0 ps_uniforms_vec4[0]
#define ps_c1 ps_uniforms_vec4[1]
uniform sampler2D ps_s0;
varying vec4 vFrontColor;
#define ps_v0 vFrontColor
#define ps_oC0 gl_FragColor
varying vec4 vTexCoord0;
#define ps_v1 vTexCoord0

void main()
{
	ps_r0.xy = dFdx(ps_v1.xy);
	ps_r0.zw = dFdy(ps_v1.xy);
	ps_r0.xy = abs(ps_r0.zw) + abs(ps_r0.xy);
	ps_r1.x = 1.0 / ps_r0.x;
	ps_r1.y = 1.0 / ps_r0.y;
	ps_r0.xy = ps_r1.xy * ps_c2.yy;
	ps_r1.x = 1.0 / ps_c0.x;
	ps_r1.y = 1.0 / ps_c0.y;
	ps_r0.zw = ps_r1.xy * ps_c1.xx;
	ps_r0.x = dot(ps_r0.zw, ps_r0.xy) + ps_c2.z;
	ps_r1 = texture2D(ps_s0, ps_v1.xy);
	ps_r0.y = -ps_r1.y + ps_r1.x;
	ps_r0.yz = ((ps_r0.y >= 0.0) ? ps_r1.yx : ps_r1.xy);
	ps_r2.x = min(ps_r1.z, ps_r0.z);
	ps_r1.x = max(ps_r0.y, ps_r2.x);
	ps_r0.y = ps_r1.x + ps_c2.x;
	ps_r0.x = clamp((ps_r0.y * ps_r0.x) + ps_c2.y, 0.0, 1.0);
	ps_oC0 = ps_r0.xxxx * ps_v0;
}
````

Is there any workaround?

**Comment by mrhelmut** [comment]
I don't see anything shady there and it should be working.

What are your iOS and Android devices and which system versions are you running?

**Comment by dtaylorus** [comment]
I've tried on an iPad running iOS 12 and a Kindle Fire, as well as emulators for both iOS and Android.

My guess is that this is the same thing identified in [this forum thread](http://community.monogame.net/t/solved-can-glsl-extensions-be-enabled-in-effects/9623).

To summarize the thread, the GLSL shader output is missing the following preprocessor extension, which is required to support `dFdx` and `dFdy`:

    #extension GL_OES_standard_derivatives : enable

This theory is supported by the fact that if I remove `fwidth` from the HLSL shader, the shader compiles properly at runtime (though it doesn't actually do what I want, of course).

I just haven't yet figured out how to edit the xnb file to verify this theory by adding this missing directive.

Or maybe there's some other way to enable support for `dFdx` and `dFdy`?

**Comment by mrhelmut** [comment]
Okay, thanks for the details.

It looks to be a limitation of MojoShader, the converter that is used to produce GLSL code.
MojoShader only knows plain GLSL 1.20 and doesn't support extensions.

This is probably something that should be discussed with the MonoGame team, because fixing the issue implies to create a patch for MojoShader (and then comes the debate about what should be done about GLSL extensions for future references).

@Jjagg @tomspilman thoughts?

**Comment by tomspilman** [comment]
Well i think we just have to move away from MojoShader for a better HLSL->GLSL cross compiling library.  Ideally one that works from HLSL source code to GLSL source code (or even SPIR-V) without the need for a HLSL compiler step first.  Also one that is in active development and supports HLSL SM 3/4/5/6 etc.

Pushing further with MojoShader i think is the wrong direction long term.

**Comment by tomspilman** [comment]
Hi @dtaylorus.

One hacky workaround for you could be to add something like this to the 2MGFX source after MojoShader runs:

https://github.com/MonoGame/MonoGame/blob/develop/Tools/2MGFX/ShaderData.mojo.cs#L183
```
if (glslCode.Contains("dFdx") || glslCode.Contains("dFdy"))
	glslCode = "#extension GL_OES_standard_derivatives : enable\r\n" + glslCode;
```
That might even be a good PR knowing that it should be better than not working at all.

**Comment by dtaylorus** [comment]
Thanks, @tomspilman ! I'll give that hack a shot and submit a PR if it works.

I was also wondering if there was a way to enable the extension (or even a higher level of GLSL) in code at runtime, i.e., before compiling the shader at runtime?

It seems to me that the `GL_OES_standard_derivatives` extension shouldn't even be required if the GLSL level is higher, but I don't know where that is set or how to change it.

**Comment by tomspilman** [comment]
> I was also wondering if there was a way to enable the extension (or even a higher level of GLSL) in code at runtime, i.e., before compiling the shader at runtime?

We don't have a real API for that other than maybe the existing XNA `HiDef` profile.

I'm not super well versed in GL, so i cannot say.

@Jjagg @cra0zy ?

**Comment by dtaylorus** [comment]
I verified in the debugger that I'm setting the HiDef profile, and I verified that I'm using the HiDef profile in the content builder as well.

The good news is that the hack works! I'll submit a PR, probably later tonight. It's so cool to have smooth MSDF font scaling on iOS and Android! Thank you so much!

**Comment by Jjagg** [comment]
> I was also wondering if there was a way to enable the extension (or even a higher level of GLSL) in code at runtime, i.e., before compiling the shader at runtime?

I think you have to have the extension in the shader code. I guess you could just prepend the extension text to the shader string, but not through the MG API of course.

Regarding GLSL version, MojoShader generates 110 or 120, but MG always sets it to 110. We could just replace that after letting MojoShader generate the GLSL, but I'm not sure if we could break anything by just upping the version number.

**Comment by mrhelmut** [comment]
Yeah, you can't set the GLSL version at runtime with the actual API, but we could add a feature that detects the runtime GL version and add the core GLSL directive when ```Effect``` are loaded.

For example, if the host supports OpenGL 3.0, it can't do any harm to add a ```#version 130``` directive at the beginning of each generated GLSL code when the content pipeline loads effects.

However, I don't know since which GLSL version ```GL_OES_standard_derivatives``` went core.

Core GLSL version table can be found here: https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)

**Comment by nkast** [comment]
I have a shader that uses fwidth for XNA and MG/DX. In XNA I had to set HiDef in the content project and use SM3. In MG it requires at least SM4_0_9_3 to build and at least a FeatureLevel 9.3 device.
It did compile for GL but I never tested it.


@dtaylorus I also have a fallback for Reach profile. The trick is to perform the same calculation for one texel to the right, and one texel to the top, and then get the ABS difference. Due to the inst limit I had to break it down to multiple passes. I have to say that the quality of the fallback is not as good as the fwidth version. 
More on this & link to the source:  http://community.monogame.net/t/grid-background-question/8836/10

**Comment by dtaylorus** [comment]
@nkast, I also was able to use fwidth on DX and compile with 2MGFX/MojoShader with no issues.

The problem is that your shader will fail to compile on GL platforms (including iOS and Android) _at runtime_, unless you apply my PR.

It works fine in the GL content pipeline as you noted.

**Comment by mrhelmut** [comment]
FYI, Microsoft has a new open source project about cross-compiling HLSL to GLSL/Spir-V/Metal: https://github.com/Microsoft/ShaderConductor

I haven't looked into it yet, but maybe something to consider to have a modern replacement of MojoShader?

**Comment by Jjagg** [comment]
Worked around in #6501
