### ISSUE TITLE
Content builder fails in new DesktopGL template 

### ISSUE THREAD

**Issue by wanton7** [MonoGame/MonoGame#6500]
Tried new template that was added in commit bf092060932afe2462021e4dc9f5219fccc279cb
Content builder seems to fail because I have space in my Windows user name.
`C:\Users\Removed Removed.Removed\.nuget\packages\monogame.content.builder\3.7.0.9\build\MonoGame.Content.Builder.targets(73,5): error MSB3073: The command "C:\Users\Removed Removed.Removed\.nuget\packages\monogame.content.builder\3.7.0.9\tasks\netstandard2.0\../../build\MGCB\build/MGCB.exe /@:"C:\Removed\Removed\Removed\Removed\Content\Content.mgcb" /platform:DesktopGL /quiet /outputDir:"bin\DesktopGL\Content" /intermediateDir:"obj\DesktopGL\Content"" exited with code 9009. [C:\Removed\Removed\Removed\Removed\Removed.csproj]`

It's missing quotes, it should look like this instead
`"C:\Users\Removed Removed.Removed\.nuget\packages\monogame.content.builder\3.7.0.9\tasks\netstandard2.0\../../build\MGCB\build/MGCB.exe" /@:"C:\Removed\Removed\Removed\Removed\Content\Content.mgcb" /platform:DesktopGL /quiet /outputDir:"bin\DesktopGL\Content" /intermediateDir:"obj\DesktopGL\Content"`

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7 develop

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

**Comment by cra0zy** [comment]
This is a duplicate issue, and it already got fixed on my fork. I'll get around to updating the nuget some time soon.
