### ISSUE TITLE
Qol its been needed for a long time.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#6511]
Minor Quality of life addition to the Rectangle class. This is a proposal for 3 Rectangle overloads, LocationVector, SizeVector and CenterVector that return Vector2's. These are supplemental to the existing location Property's that return Points of the same name without the word Vector appended at the end.

Motivation...

Today for the umpteenth time i drew a Rectangle.

_Rectangle r = new Rectangle(100,100, 200, 30);
spriteBatch.Draw(.., r ,,,);_

Then i drew some text in the rectangle.

_spriteBatch,DrawString( ......  r.Location  ,,,,); // This of course would error._

so...

_Vector2 v = new Vector2(r.X, r.Y);
spriteBatch,DrawString( ......  v  ,,,,);_

The reverse going from Vector2's to Rectangle.Location or Size is annoying and you have to type the cast (int) which i know is sort of a good thing sometimes but honestly in this case not really as it has to be done and will be done anyways,

.

With the proposed addition you would have instead.

_spriteBatch,DrawString( ......  r.LocationVector  ,,,,);_

.

Now you might say this isn't a big deal and you are right. 
I typically have as extension methods ToVector2() and ToPoint() lying around.
But ...
New people don't as well it gets annoying to always have to add them.
Further this amounts to a extra call or pass and typing every time it has to be done.

How many times have these extra lines been written since the begining of xna or monogame,

I submitted a pull request hopefully i did it right. https://github.com/MonoGame/MonoGame/pull/6510

I know there is cache hit concerns and i didn't try to test for them but i doubt those structs are that big,
If you guys approve i would also like to submit the following...
On the Vector2 a Point type Return getter. 
On the Point a Vector2 type Return getter.
Typically i name my extensions ToPoint and ToVector

It doesn't and probably shouldn't be a overload (because it should be a explicit method or property call) but something like a ToVector method or property in the point class, (ToPoint in the vector class) would allow many to get rid of extension methods for something that probably should of been added years ago in xna. 
If nothing else to avoid a extra parameter pass between these calls and to keep the code cleaner.

**Comment by Jjagg** [comment]
`Point.ToVector2()` and `Vector2.ToPoint()` exist. I'm against this proposal, it's pretty much useless.

**Comment by willmotil** [comment]
Humm i didn't know the ToVector2 and ToPoint were already added well never mind then.

But still
r.Location.ToVector2();
Point p = new Point( r.X, r.Y);
Vector2 v = new Vector2( p.X,p.Y);

Extra call every time.

I never really understood why xna just didn't make the Rectangle a floating point class then all this casting wouldn't be necessary at all.

**Comment by tomspilman** [comment]
> I never really understood why xna just didn't make the Rectangle a floating point struct

I think it is legacy.  `Rectangle` was there to sort of match `System.Drawing.Rectangle` as a integer bounds (same as `Point`).

Then they couldn't think of an elegant name for a floating point 2D rectangle... so they just left that to the user to figure out. :)

**Comment by Jjagg** [comment]
> And internally everything ends up as floating point.

This is false. It matters that ints are stored with more significant digits. 

> I never really understood why xna just didn't make the Rectangle a floating point struct

Definitely agree that this is an annoying part of the API. Another place this comes up often is in the SpriteBatch overloads that take a rectangle.

**Comment by willmotil** [comment]
I meant by converted internally that when it goes from SpriteBatch via set(...) to spriteBatcherItem that even though the cast isn't explicitly needed to be made on by the programmer. 
C# is still implicitly casting those ints to floats.

It may not seem like a lot until you think about that then take a look at one of those methods.

Worse if your keeping screen resolution by scaling everything which i ussually do. The easiest way is to store your data on your end in floats. Which if you are using spritebatch will need to be cast to int's to pass to spritebatch for any rectangle draws, which will then eventually call set on them. 

I have no idea how much this actually impacts performance on a small scale. But i would wager the more draw calls per frame the heavier the toll on frames per second from casting alone.

```
public void Set(float x, float y, float w, float h, Color color, Vector2 texCoordTL, Vector2 texCoordBR, float depth)
        {
            vertexTL.Position.X = x;
            vertexTL.Position.Y = y;
            vertexTL.Position.Z = depth;
            vertexTL.Color = color;
            vertexTL.TextureCoordinate.X = texCoordTL.X;
            vertexTL.TextureCoordinate.Y = texCoordTL.Y;

            vertexTR.Position.X = x + w;
            vertexTR.Position.Y = y;
            vertexTR.Position.Z = depth;
            vertexTR.Color = color;
            vertexTR.TextureCoordinate.X = texCoordBR.X;
            vertexTR.TextureCoordinate.Y = texCoordTL.Y;

            vertexBL.Position.X = x;
            vertexBL.Position.Y = y + h;
            vertexBL.Position.Z = depth;
            vertexBL.Color = color;
            vertexBL.TextureCoordinate.X = texCoordTL.X;
            vertexBL.TextureCoordinate.Y = texCoordBR.Y;

            vertexBR.Position.X = x + w;
            vertexBR.Position.Y = y + h;
            vertexBR.Position.Z = depth;
            vertexBR.Color = color;
            vertexBR.TextureCoordinate.X = texCoordBR.X;
            vertexBR.TextureCoordinate.Y = texCoordBR.Y;
} 
```

**Comment by Halofreak1990** [comment]
I'm not sure why having an integer Rectangle for bounds is weird. Ever seen a texture with a fractional width? I sure haven't. It's contextual, in my opinion. SpriteBatch would be best served by a RectangleF structure in its overloads, while things like Texture.Bounds make more sense with an integer Rectangle structure.

Note that the System.Drawing Rectangle implicitly converts to RectangleF, and Rectangle has .Ceiling() .Round() and .Truncate() methods to convert a RectangleF into a Rectangle.

**Comment by Jjagg** [comment]
Closing because there's conversion methods for `Point` <-> `Vector2`. If you care about the overhead of creating a `Point` and then a `Vector2` (which you shouldn't), you can still implement extension methods that use the `X` and `Y` properties.
