### ISSUE TITLE
MonoGame 3.7.0.1708: SwapChainPanel Repaint Issues on Windows® 10 UWP (XAML)

### ISSUE THREAD

**Issue by AdrianWenz** [MonoGame/MonoGame#6513]
When a 'SwapChainPanel' UIElement is placed inside a 'ScrollViewer' object and the visible area is scrolled to the left, the uncovered part of the swap chain panel is NOT drawn at all (see attached picture).
**The previous version of MonoGame (3.6.) handled this correctly.**

![monogame 3 7 0 1708 scroll issue](https://user-images.githubusercontent.com/19491407/47607985-9862ed80-da27-11e8-9246-39c4a9ad9c27.png)

Steps to reproduce this issue:
- Create a 'MonoGame Windows 10 Universal (XAML) Project'
- Change the file 'GamePage.xaml' to:
  `<ScrollViewer x:Name="AppContent"  VerticalScrollBarVisibility="Auto"   HorizontalScrollBarVisibility="Auto"  HorizontalScrollMode="Auto" VerticalScrollMode="Auto" ZoomMode="Enabled">`
   `<SwapChainPanel x:Name="swapChainPanel" MinWidth="768" MinHeight="640"/>`
   `</ScrollViewer>`
- Compile the project and launch it
- Resize the application windows to be less than 768 px in width and scroll to content to the left

The sample project is attached.
[Game1.zip](https://github.com/MonoGame/MonoGame/files/2522111/Game1.zip)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1708

#### What operating system are you using:
- Windows® 10 (17134.345)

#### What MonoGame platform are you using:

- WindowsUWP

**Comment by nkast** [comment]
I think what broke it was #5615. 
I changed the code from _swapChainPanel.SizeChanged to _coreWindow.SizeChanged because now the inputElement/SwapChainPanel could be null under an CoreApplication projects and I assumed that a SwapChainPanel will always be the same size as the window. 

The Phone case is a bit weird. I believe the cause of the bug is #5555, #5569.
However in 3.6, the _swapChainPanel would fire a SizeChanged right after startup and update the wrong Backbuffer size.

**Comment by AdrianWenz** [comment]
@nkast 
I've added some more pictures to illustrate the distorted aspect ratio on the mobile emulators:
After launching the application it looks as follows:

![monogame 3 7 0 1708 i](https://user-images.githubusercontent.com/19491407/47614271-82900f80-da9d-11e8-84b7-52e9e00fa494.png)


Turning the emulator into the horizontal orientation and then back to vertical:

![monogame 3 7 0 1708 ii](https://user-images.githubusercontent.com/19491407/47614281-aa7f7300-da9d-11e8-9334-37e18a5a9904.png)

I hope this additional information helps to fix the reported issue.

**Comment by nkast** [comment]
For the  distorted aspect ratio on phones apply the changes from #5569. I believe that will fix it.

As for the first issue with the SwapChainPanel in a ScrollViewer , I don't think MG can support it. When you change the backbuffer size for example, MG will also change the Window size to match that size. Therefore the SwapChainPanel must be the root element and fill the window without any borders/padding.  For scenarios like the one you describe you would need something like a SwapChainRenderTarget for UWP #4674.

**Comment by AdrianWenz** [comment]
@nkast 
I want to state again here that BOTH issues are handled correctly by MonoGame 3.6. i.e. **these bugs have been introduced by version 3.7.0.1708**.

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
