### ISSUE TITLE
Wrong index passed to DataStream.Create in DynamicSoundEffectInstance.cs

### ISSUE THREAD

**Issue by JoaoBaptMG** [MonoGame/MonoGame#6524]
As stated in pull request #6523, the parameter `index` (the fourth parameter) passed to the method `DataStream.Create` by the method `PlatformSubmitBuffer` of the class `DynamicSoundEffectInstance` using the XAudio back-end seems wrong. Since the buffer referred to by the method is `pooledBuffer`, and data is copied from the original buffer to this pooled buffer, the right value passed to the parameter might be `0` instead of `offset`.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by Jjagg** [comment]
Fixed in #6523.
