### ISSUE TITLE
Exception trying to use MediaPlayer on WindowsDX

### ISSUE THREAD

**Issue by dmanning23** [MonoGame/MonoGame#6525]
When trying to access the MediaPlayer on WindowsDX, an exception is thrown:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Xna.Framework.Media.MediaPlayer' threw an exception.
  Source=MonoGame.Framework
  StackTrace:
   at Microsoft.Xna.Framework.Media.MediaPlayer.get_State()
  ...

Inner Exception 1:
TypeLoadException: Method 'QueryInterface' in type 'Callback' from assembly 'MonoGame.Framework, Version=3.7.0.1708, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

I'm getting this whenever I try to access any property or method of the MediaPlayer object, which leads to believe it is something wrong in the `PlatformInitialize()` method for the WindowsDX platform.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by MichaelDePiazzi** [comment]
Do you have Windows Media Player installed on your system? Media Foundation requires it (or the Media Foundation Pack) to be installed for it to work.

There was some code posted here to check if it's installed or not: https://github.com/MonoGame/MonoGame/issues/4287#issuecomment-241204569

**Comment by Jjagg** [comment]
I think this happens because of a mismatch of the target and runtime version of SharpDX.
This is not a MonoGame issue.
