### ISSUE TITLE
SoundEffectInstance looping is not seamless

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#6541]
There is a very minor delay before SoundEffectInstances loop with `SoundEffectInstance.IsLooped` after they're done playing. This happens on both WindowsDX and DesktopGL on the latest develop version. I've verified that the songs themselves loop correctly by playing them in Adobe Audition.

Specs:
- Alienware 15 R3 laptop
- CPU: Intel(R) Core(TM) i7-7700 HQ
- GPU: NVIDIA GeForce GTX 1070
- Sound: Realtek Audio

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL
- WindowsDX

**Comment by mrhelmut** [comment]
Could you provide an example project? I've been using looped ```SoundEffectInstance``` a lot with DesktopGL with no audible issue.

**Comment by tdeeb** [comment]
[Here's an example project.](https://github.com/MonoGame/MonoGame/files/2588802/MonoGame.Looping.Example.Project.zip)

I'm on the latest develop version with no changes to MonoGame.

**Comment by mrhelmut** [comment]
Thank you.

I tested it and ```SoundEffectInstance``` loops correctly on the latest develop branch.
However the file you provided doesn't have a clean loop, it behaves the same in other players or sound authoring software such as Audacity where the loop doesn't quite work.

You can test how sounds loop with a tone sample: https://www.mediacollege.com/audio/tone/download/

**Comment by tdeeb** [comment]
You are correct; I tested the WAV tone samples and they loop perfectly in MonoGame.
