### ISSUE TITLE
SoundEffect panning does not split properly

### ISSUE THREAD

**Issue by indiemini** [MonoGame/MonoGame#6543]
From the forums: http://community.monogame.net/t/soundeffect-panning-does-not-split-properly/11092

The docs say that the pan value of `SoundEffect.Play` ranges from -1.0f to 1.0f, but audio is only playing out of the left speaker, right speaker, or both, equally. `pan = 0.1f` is being treated the same as `pan = 1.0f`. This behaved as expected when using the SharpDX library / XAudio, but not after we moved to OpenGL.

This is the function we wrote to play the audio.

```
public static void PlaySound(string name, float vol = 0.5f, float pan = 0.0f, bool jitter = false)
{
    bool ok = SFX.TryGetValue(name, out SoundEffect audio);
    if (ok)
    {
        float pitch = jitter ? ((float)Utils.Random.NextDouble() / 4.0f) : 0.0f;
        audio.Play(vol, pitch, pan);
    }
}
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows 10, macOS Mojave

#### What MonoGame platform are you using:

- DesktopGL (bug did not occur with WindowsDX)

**Comment by MiniguyBrendan** [comment]
Tried the workaround like this:

```
public static void PlaySound(string name, float vol = 0.5f, float pan = 0.0f, bool jitter = false)
{
    bool ok = SFX.TryGetValue(name, out SoundEffect audio);
    if (ok)
    {
        float pitch = jitter ? ((float)Utils.Random.NextDouble() / 4.0f) : 0.0f;
        SoundEffectInstance instance = audio.CreateInstance();
        instance.Play();
        instance.Pan = 0.2f;
        instance.Pitch = pitch;
        instance.Volume = vol;
    }
}
```

But this behaved the same as the first example with the `.Play(vol, pitch, pan)` function (the audio plays completely out of one speaker).

**Comment by Jjagg** [comment]
Damn, I thought that would work.  So we're probably messing up something else too.

OpenAL does not directly support panning, so we use the 3D audio support to implement it, which is not as straightforward as setting a panning value.

**Comment by Ghorthalon** [comment]
Since 3D is used to create the stereo panning effect, a workaround for OpenAL would be to raise the listener's Y position up by a few units. The closer the emitter is to the listener, the more pronounced the change will be. I've found that a Y value of 0.5f for the emitter will translate more or less OK for values between -1 and 1. I'm sure there's a better algorithm to come up with a much closer approximation, but this seems to work OK enough for most usecases. I see that in SoundEffectInstance.OpenAL.cs you already try this with a z value of 0.1f, but from playing around with it, that value is too small. Changing this value to 0.5f should workaround this issue a bit better. Not a perfect solution, but good enough.

**Comment by IgorFIE** [comment]
Is there any update on this issue? I'm on the latest version of monogame and I have this same problem.

**Comment by yyr57695** [comment]
I have the same issue too.  I use the Windows templates for most of my projects, but was considering migrating to DesktopGL to support Steam Deck as WMA audio doesn't work on it.  But sound panning doesn't work properly =\

The issue is the same in older versions of MonoGame 3.8.  It works properly under SharpDX but not DesktopGL.  I hope that this can be addressed at some point.

**Comment by Zarkonnen** [comment]
I've attempted to set the z value in PlatformSetPan to 0.5f and as high as 10f, and I still get the same panning bug where any pan is either 100% left, 100% right, or dead center.

**Comment by mrhelmut** [comment]
OpenAL is too limiting and can't properly mimic XAudio2. We should look into replacing OpenAL with FAudio to have a proper accuracy versus XAudio2 throughout all our targets.

In the meantime, I think it is worth looking into improving the OpenAL implementation.

**Comment by KenshirouLuke** [comment]
Hello, any update on this issue?
Thanks

**Comment by Zarkonnen** [comment]
AFAIK it's still broken. I've found that you can work around it with code that plays the sound effect twice at the same time, once on the left channel, and once on the right. Not a great solution, though.

**Comment by KenshirouLuke** [comment]
Thanks, but it will kinda sound the same, right? I mean, choosing between only -1, 0 and +1, and not other float values, maybe it will sound more "stereo", but still the same, without the possibility to choose the exact point?
I heard about a class related on 3D audio; it's a valid alternative?

**Comment by Zarkonnen** [comment]
All that OpenAL does when you pick a pan value is that it plays it at some volume out of the left channel and some other value out of the right channel. If you e.g play the sound at 0.5 volume at -1 and at 0.2 volume at 1, that's the same as playing it at a pan between -1 and 1 and some volume. You just have to redo the math that OpenAL is meant to handle for you.

**Comment by KenshirouLuke** [comment]
Thanks for the reply, are you suggesting that I should calculate both values, and then play two SoundEffectInstance at the same time, each one with its pan (-1 and 1) and its volume?

**Comment by macabrett** [comment]
I ran into this issue and the solution of creating two SoundEffectInstances worked for my needs.

> Thanks for the reply, are you suggesting that I should calculate both values, and then play two SoundEffectInstance at the same time, each one with its pan (-1 and 1) and its volume?

Yes, this is how I ended up handling it. I created a wrapper for SoundEffectInstance that contains two SoundEffectInstances. One of them has a Pan of -1f and the other has a Pan of 1f.

Here's the basic code I run when pan is adjusted on my wrapper class (_leftChannel and _rightChannel are both SoundEffectInstances):

```csharp
var rightChannelMultiplier = (this._pan + 1f) / 2f;
this._rightChannel.Volume = this.Volume * rightChannelMultiplier;

var leftChannelMultipler = 1f - rightChannelMultiplier;
this._leftChannel.Volume = this.Volume * leftChannelMultipler;
```

You'll have to store both volume and pan separately from the instances. This is working for me.
