### ISSUE TITLE
FullScreen mode does not defer screen edge gestures on iOS 11+

### ISSUE THREAD

**Issue by dtaylorus** [MonoGame/MonoGame#6553]
Touches near the edge of a full screen game on iOS 11+ immediately activate system gestures like Control Center and task switching, instead of deferring them as expected in iOS 10 and earlier.

The solution is to override `preferredScreenEdgesDeferringSystemGestures` in `iOSGameViewController` (see [Apple developer documentation](https://developer.apple.com/documentation/uikit/uiviewcontroller/2887512-preferredscreenedgesdeferringsys)), which is not possible without a fix in MonoGame.Framework.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- iOS

**Comment by Jjagg** [comment]
Fixed in #6501. Thanks @dtaylorus!
