### ISSUE TITLE
3DS as supported platform

### ISSUE THREAD

**Issue by bovacu** [MonoGame/MonoGame#6554]
#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

Hi, I recently posted a question about if the 3ds was supported as a monogame platform and one of your monogame developers answered me that if a was interested about getting this platform as a monogame supported one I should open a issue here, so here it is. It would be awesome if you could made it.

Thank you un advance.

**Comment by Jjagg** [comment]
cc @tomspilman Not sure if this ever came up before.

Anyone reading this that would also like to develop for Nintendo 3DS, please upvote the original post and/or reply here so we can gauge interest.
Anyone that would like to implement or help implement 3DS support, please reply to this topic or chat with us on the Gitter channel :)

**Comment by mrhelmut** [comment]
I guess that nobody ever attempted this because there was too little demand compared to the workload needed to get this done (its hardware is quite different from any other platform). Not to mention that it is uncertain that the 3DS will be powerful enough to run the current build pipeline and runtime for MonoGame (it runs correctly on the Vita, but we can feel that it's at its limit for decent performance), but we need to try to know!

Any help welcome! (it is required to be a Nintendo registered developer)

**Comment by HopefulToad** [comment]
I imagine that if this were to happen, it would probably be limited to the "New" 3DS family of systems, which have increased performance capabilities compared to the original 3DS family.

It would be cool to see this happen, but it also seems rather unlikely. Does Nintendo even accept new developers for the 3DS anymore?

**Comment by TyPhyter** [comment]
Upvoted, would love to see this happen. Optimized Unity builds can reportedly run on old 3DS hardware, so I feel like it's a possibility. Would be happy to help in any way I can.

And yes @HopefulToad , Nintendo's Developer program for 3DS is entirely open. Anyone can sign up.

**Comment by mrhelmut** [comment]
Anyone interested in helping is very welcome and should contact @tomspilman for private access to the console runtime.

Mind that this sounds like a very complicated task involving thousands of C/C++ lines. The 3DS is like no other hardware MonoGame has ever been ported to and its memory management is quite different.
It also only has an OpenGL 1.1 compliant GPU (with some extensions) with non programmable pixel shader stage, which means that BasicEffect and SpriteEffect will have to be partly "emulated" through fixed functions.

**Comment by cra0zy** [comment]
> Mind that this sounds like a very complicated task involving thousands of C/C++ lines. The 3DS is like no other hardware MonoGame has ever been ported to and its memory management is quite different.
> It also only has an OpenGL 1.1 compliant GPU (with some extensions) with non programmable pixel shader stage, which means that BasicEffect and SpriteEffect will have to be partly "emulated" through fixed functions.

Not sure if this sounds like fun or torture.

**Comment by Jjagg** [comment]
Closing this since 3DS is pretty much dead.
