### ISSUE TITLE
Manual building project

### ISSUE THREAD

**Issue by nanodesu88** [MonoGame/MonoGame#6557]
Manual creating a MonoGame project.

Hello everybody! Sorry for bad english, i am good with reading, but writing... I am trying to create a manual MonoGame project.
What did i do:
1) Creating a .net framework 4.6.1 console application
2) Copying MonoGame.Framework.dll and all libs to project, reference them etc.
3) Write a simple code:
```fsharp
let game = new Game()
let graphics = new GraphicsDeviceManager(game);

game.Run()
```
and take
```
D:/code/MonoGameFSharp/ConsoleApplication1/bin/Debug/ConsoleApplication1.exe
AL lib: (EE) SetChannelMap: Failed to match front-center channel (2) in channel map

System.AccessViolationException: You are attempting to read or write into the protected memory. Usually it indicates that other memories has been damaged.
   в Sdl.Window.Create(String title, Int32 x, Int32 y, Int32 w, Int32 h, Int32 flags)
   в Microsoft.Xna.Framework.SdlGameWindow.CreateWindow()
   в Microsoft.Xna.Framework.GraphicsDeviceManager.Initialize()
   в Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   в Microsoft.Xna.Framework.Game.DoInitialize()
   в Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   в Program.main(String[] argv)
```
What this means? How can i fix it? 
Basic MonoGame template works well, but i need F#

- Integrated VideoCard Intel HD630
- MonoGame 3.7.1708
- Win10 x64
- DesktopGL, WindowsDX, any other

**Comment by nanodesu88** [comment]
Problem fixed.

**Comment by Apostolique** [comment]
Maybe you should consider writing what it is that you did to fix this.

**Comment by nanodesu88** [comment]
It was a problem with videocard drivers
