### ISSUE TITLE
EXT_framebuffer No Longer Available

### ISSUE THREAD

**Issue by jcsnider** [MonoGame/MonoGame#6561]
I've been creating a mostly SpriteBatch 2d game using the DesktopGL template. After recently upgrading my game from MonoGame 3.6 to 3.7 I started receiving reports that players who could play my game using MonoGame 3.6 but could no longer play using MonoGame 3.7.

One of my players has an old Intel Core 2 Duo with integrated graphics. Framebuffer support was provided via the EXT_framebuffer object. As of this PR (#5993) his machine no longer loads the BindFramebufferDelegate, GenFramebufferDelegate, or any of the other EXT functions which eventually leads to a NoSuitableGraphicsDeviceException when trying to call those functions from PlatformApplyRenderTargets in GraphicsDevice.OpenGL.cs.

By bringing back the old EXT loading code, and code in the Framebufferhelper.cs file I was able to compile a MonoGame dll from the develop branch that he could use. Obviously [these changes](https://github.com/jcsnider/MonoGame/commit/b4c057571d7ef0c82c07d3dbed8e853c8aa0896a) are not suitable for a PR but I was able to prove to myself that these players can still use MonoGame 3.7+ with very minor modifications.

I guess I'm wondering if it was intended to drop support for computers that required the EXT functions (ie 'glBindFramebufferEXT') or if this is a valid issue. If it's valid I can devote more time and attempt to find a real solution for these players that won't break other devices.

Thanks!
JC

CPU: Intel Core 2 Duo 3.00ghz
Memory: 5gb
IGPU: Intel Q45/Q43 Express Chipset
OpenGL Version: 2.1 + EXT_Framebuffer

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows 7 x64

#### What MonoGame platform are you using:
- DesktopGL

**Comment by mrhelmut** [comment]
What you did in your branch is most likely to do the opposite on some systems: break frame buffer extension for OpenGL version where these extensions are core features.

I found the issue though, the problem is here: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/OpenGL.cs#L1388

The ```GL_EXT_framebuffer_object``` check and loading should be outside the ```if (GL.RenderbufferStorageMultisample == null)``` statement.
Right now, the framebuffer object extension gets loaded only if ```glRenderbufferStorageMultisample``` didn't get loaded.

I'm going to push a fix (and clean up a few things).

**Comment by jcsnider** [comment]
@mrhelmut we are SUPER close.  Your changes do indeed allow the EXT extensions to load correctly, so if the following should be in a separate issue please let me know.

There is [one more problem here with EXT loading.](https://github.com/MonoGame/MonoGame/pull/5993/commits/db6c1baa4c32f0687979e97ff8cfdb446418964b#diff-486713d6fefa46564f3ed52038e6a48cR76)

After that commit the RenderbufferStorageMultisample function checks the sample count. If the samples > 0 then it uses the GL.RenderbufferStorageMultisample delegate, but if the samples = 0 then it tries to use GL.RenderbufferStorage.

The problem is that GL.RenderbufferStorage is never loaded for EXT.  I am able to get your code working for my player just by adding the following line of code in LoadFrameBufferObjectEXTEntryPoints():

`RenderbufferStorage = LoadFunction<RenderbufferStorageDelegate>("glRenderbufferStorageEXT");`

Is that a valid solution? If so I can create a PR.

Thanks again!
JC

**Comment by Jjagg** [comment]
> Is that a valid solution? If so I can create a PR.

@jcsnider Yes, please do :)

**Comment by jcsnider** [comment]
No problem. It is also in that PR now.  Thanks guys!
