### ISSUE TITLE
Texture size limit

### ISSUE THREAD

**Issue by nanodesu88** [MonoGame/MonoGame#6565]
Is textures have a limit width/height?
I am created a sprite with 20353x178 sizes and when i am loading a texture i am getting a exception:

``
System.InvalidOperationException: This image format is not supported ---> SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments]
``

- MonoGame 3.7
- Windows
- WindowsDX

**Comment by KakCAT** [comment]
http://community.monogame.net/t/what-is-the-size-limit-for-texture2d-on-monogame/2266/3

**Comment by nanodesu88** [comment]
Thanks you!
