### ISSUE TITLE
Default Windows project throws NoSuitableGraphicsDeviceException

### ISSUE THREAD

**Issue by krishermans** [MonoGame/MonoGame#6568]
I'm just a newbie and asked this in the forum. They suggested to open an issue on Github. Please forgive me if I forgot any details.

When I create a new project using the standard templates (MonoGame Windows Project) and hit run. I get the following exception:

> Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: 'Adapter 'Intel(R) HD Graphics Family' does not support the Reach profile.'

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7
- Latest Development build
#### What operating system are you using:
- Windows 10
- Surface Pro 3
- Visual Studio 2017
- Graphics Card: Intel(R) HD Graphics Family

#### What MonoGame platform are you using:

- Standard Windows Project

**Comment by mrhelmut** [comment]
That seems pretty weird for a Surface Pro. I have no problem on mine, so you might want to check your Intel graphics drivers.

Would you mind debugging from source and break on this line to inspect ```highestSupportedLevel``` ? https://github.com/MonoGame/MonoGame/blob/3e92fc7bff7b4c32edf1314e143a4b7de4fab161/MonoGame.Framework/Graphics/GraphicsAdapter.DirectX.cs#L131

**Comment by Jjagg** [comment]
I'm closing this because it's not a MG issue, but feel free to continue the discussion.

**Comment by KakCAT** [comment]
I'd try MonoGame 3.6 to discard a problem with the new SharpDX.

**Comment by krishermans** [comment]
Nope, 3.6 gave the same exception. I’ll guess I will try to change the driver.

________________________________
Van: KakCAT <notifications@github.com>
Verzonden: Thursday, November 29, 2018 1:03:18 PM
Aan: MonoGame/MonoGame
CC: Kris Hermans; Author
Onderwerp: Re: [MonoGame/MonoGame] Default Windows project throws NoSuitableGraphicsDeviceException (#6568)


I'd try MonoGame 3.6 to discard a problem with the new SharpDX.

**Comment by krishermans** [comment]
Installed the latest Intel driver from their own website, still the same issue :-(

**Comment by mrhelmut** [comment]
That's really the weirdest thing, I have the same hardware and no issue. There's something preventing Direct3D from returning the feature level, which sounds quite bad from a system/driver perspective.

**Comment by krishermans** [comment]
And what's driver/version do you use?

Op 29 nov. 2018 3:03 p.m. schreef Thomas Altenburger <notifications@github.com>:

That's really the weirdest thing, I have the same hardware and no issue. There's something preventing Direct3D from returning the feature level, which sounds quite bad from a system/driver perspective.

**Comment by perpetualKid** [comment]
Just looking at the latest/current code, having similar issues if running the unit tests on SP3 device.
```
    Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException : Failed to create graphics device!
      ----> SharpDX.SharpDXException : HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: The specified device interface or feature level is not supported on this system.

```
In MonoGame.Tests.TestGameBase.ctor(), GraphicsAdapter.UseReferenceDevice is set to true. 
If changing to not use the ReferenceDevice implementation (UseReferenceDevice = false), everything seems to work fine. 


Intel HD Graphics 520
Driver version 26.20.100.7463 (11/06/2019)
DX 12 (FL 12.1)
