### ISSUE TITLE
Practical problem keyboard input. 

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#6570]
I have been doing quite a bit of text stuff lately and come up on a seemingly unsolvable situation.

First problem.  The monogame Keyboard class is all messed up big time. 
**Some keys are straight up missing in the keys enum common ones... Less than, More than, Hyphen, Forward slash ect...**

In the not so odd case were i want to press control and use that like a command shortcut with another key like w or m i can maybe get it to work with keyboardstate but if want to do this with a special character at all many of them such as a bracket { or ` < > / [ ] ' ; . 

**Keyboard state doesn't actually return a shifted case key properly or un-shifted keys right for that matter.** 

For example here is some test output were i hold shift in all presses 
notice i get ? instead of / and yet i get , . instead of  < >. 

while pressing the Shifted keys i should get  <> ?
Un-shifted the keys i should get are this   , . /

> key[0] LeftShift isCommand True isShift True isNumeric False isCharacter False isSpecialCharacter False
> key[1] OemComma isCommand False isShift False isNumeric False isCharacter True isSpecialCharacter True
> 
> key[0] LeftShift isCommand True isShift True isNumeric False isCharacter False isSpecialCharacter False
> key[1] OemPeriod isCommand False isShift False isNumeric False isCharacter True isSpecialCharacter False
> 
> key[0] LeftShift isCommand True isShift True isNumeric False isCharacter False isSpecialCharacter False
> key[1] OemQuestion isCommand False isShift False isNumeric False isCharacter True isSpecialCharacter True
> 

It returns the upper keys and lower keys without pressing anything else as well essentially whats returned in the array is unmodified by shift. The upper key or lower returned key seems random but constantly shift doesn't modify it at all.

**On the other hand.**

Text input cannot be used to determine a character pressed when something like the "control" key prevents the event from being raised. **Also when one presses shift and a letter the passed Arguments.Key evaluates to keys.None not Shift which is inconsistent with the other control keys that raise the event.** 

This leaves you with the only other option being Keyboard GetState.

The problem with GetState "Shift" it's borked big time.
**Which also means the enum for Keys has a bunch of codes that GetState never ever return.**
 
Can i know 100% the shift key characters are the same for the keys someone else presses on there keyboard even if the upper or lower case was consistently returned. Shift should be modifying which key is returned.

<img src= "https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Feasyprintable.files.wordpress.com%2F2015%2F10%2Fus-keyboard-microsoft.png&f=1" >

<img src= "http://www.smartkeyboardsolutions.com/images/Spanish_10071_zoom.gif" >

**This begs the questions,,,** 

This lead to... the user hard coding shifted control key characters to some crazy mapping ?
Which then begs the question should i expect every keyboard to have the same shift characters above the same keys ?

**The impossibility of these two scenarios then combines into something really frustrating...**

TextInput as is can't simply replace keyboard input nor can it be used in combination with it properly.

I cannot mix the textinput event with the polling as i cannot even see that shift is pressed in the raised event ... So i can't from the raised event method get the keystate to try to see that shift is the control key pressed that way.
Remember that the raised event argument for text input returns NONE as the argument when shift is pressed.

Conversely i can't poll to the raised method previously fired from my update method to get character keys from text input to hack in as a way to do short cut keys as they don't fire if i hit control, so in some game i can't reliably say control + any special key or control shift any key reliably with either. Even if it was just raised, calling into it is useless when its not raised on control or alt or many others. 
So no key character or argument will be good anyways other then shift and that actual isn't passed as a argument which means i have to fall back to Keyboard state to see if shift is pressed for any reason ?.
Also control arrows insert and many other control keys do not allow the raising of the the text input event at all. So any sort of short cut key via text input is not practically possible in any sort of simple to do way when trying to have a full and simple solution for input and is only semi reliable with keyboardstate.

Which leaves exactly no way to detect reliably that the user pressed something like control + / or >.

The general user will have to hope their keyboard layout is just like mine and i hard code it with some wacky unshift shift mapping for any kind of command keys i want to add like control * and the next programmer will too. 
Of course i know they wont all have the same layout.

Which im about to do in some limited way in a minute or in some really weird behaviorial way to get around it because i simply can see no other way. E.G. toggle on and off control alt and shift and function keys.

<img src= "https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.smartkeyboardsolutions.com%2Fimages%2FTurkish-10082-zoom.gif&f=1" >

Worse even if it was working perfectly with the keyboardstate you need something like this to convert keys to characters properly on different keyboards
```

using System;
using System.Text;
using Microsoft.Xna.Framework.Input;
using System.Runtime.InteropServices;

namespace GLMessageBoxProtoType
{

    /// <summary>
    /// using System.Runtime.InteropServices;
    /// called as such... char c = User32Interop.ToAscii(Keys.OemQuestion, Keys.ShiftKey); // = '?
    /// </summary>
    public static class User32Interop
    {
        public static char ToAscii(Keys key, Keys modifiers)
        {
            var outputBuilder = new StringBuilder(2);
            int result = ToAscii((uint)key, 0, GetKeyState(modifiers),
                                 outputBuilder, 0);
            if (result == 1)
                return outputBuilder[0];
            else
                throw new Exception("Invalid key");
        }

        private const byte HighBit = 0x80;
        private static byte[] GetKeyState(Keys modifiers)
        {
            var keyState = new byte[256];
            foreach (Keys key in Enum.GetValues(typeof(Keys)))
            {
                if ((modifiers & key) == key)
                {
                    keyState[(int)key] = HighBit;
                }
            }
            return keyState;
        }

        [DllImport("user32.dll")]
        private static extern int ToAscii(uint uVirtKey, uint uScanCode,
                                          byte[] lpKeyState,
                                          [Out] StringBuilder lpChar,
                                          uint uFlags);
    }
}
```

**Its crazy to have two separate keyboard input classes were neither fully work and they don't work with each other.**

Its ugly.  
The best solution i can see is to only rely on keyboard state for the simplest things it's not even good enough for control groups or special commands instead. Raise a separate event for text input when any key is pressed and let the user decide if he needs to do anything with keys he may not care about control alt or shift key function keys ect. If that is doable ?

Char itself in c# can tell you if a actual utf16 returned character is a control separator whitespace or what not on its own in any language.

God forbid if you really wanted to _press control shift /_ .
Try to write out the code to detect that on a us keyboard atm and you will see how frustrating this is currently. Because right now under monogame on my keyboard this is actually 100% impossible to do and i don't mean i don't know how i mean its impossible with the classes that monogame has.

If someone wants to educate me on what im missing id be quite abliged but so far this is all from running tests and the tests are telling me its really borked. I think it needs a bit of consideration.

**Comment by Jjagg** [comment]
> If someone wants to educate me on what im missing id be quite abliged but so far this is all from running tests and the tests are telling me its really borked. I think it needs a bit of consideration.

What you're missing is that the `Keys` enum members map to virtual keycodes, so they do not map to characters. `TextInput` maps the keys to characters, localized for the user input method. It is literally for text input. These are two different API's for different purposes, they technically don't overlap and are complementary.
For hotkeys you don't care what character is given, you care about what key is pressed (you also don't care about caps lock state). So you should use the `Keyboard` API. You shouldn't check for `Ctrl` + `/` (character), but `Ctrl` + `Shift` + `OemQuestion` (virtual key). This can be confusing because virtual keys are named after one of the characters that are on them. E.g. OemQuestion refers to `The OEM question mark key on a US standard keyboard.`

Here's a link with some more information: https://docs.microsoft.com/en-us/windows/desktop/inputdev/about-keyboard-input.

Since this issue stems from misunderstanding I'm closing it. If you have a specific issue after grasping how this all works, open a new issue. Walls of text like this are hard to digest and to find the actual alleged bug(s) in. So please be concise and have separate issues for each problem.

**Comment by willmotil** [comment]
> you care about what key is pressed.

So the enum defines physical key positions on the keyboards not actual key character groups.
Does the enum then map to the key number.
To say key number 32 space on my keyboard is key 32 on all keyboards provided they are not missing a space. So a missing key then is a dead key.


For control + OemQuestion number 226 on us keyboards. You would have to tell the Spanish guy its control comma on his keyboard as his OemQuestion is in a totally different physical place on the keyboard.

Isn't it confusing to even label the enums with a string like OemQuestion if they really are to refer to something like key number 226.

**Comment by Jjagg** [comment]
To refer to key numbers to identify a virtual key is a bit confusing. The Keys enum values are simply the values used by the Win32 VirtualKey enum. That's where the abstraction happens. A different platforms will have different values and perhaps different virtual keys (at least I don't think there's a standard, but I'm not a specialist). MonoGame translates these so they're the same across platforms and keys map to the MG Keys enum.

There are APIs to map virtual keys to characters in the active locale if you need them (not exposed by MG).

Yes, it is confusing to label virtual keys by the characters on them, but how else would you identify a key in a non device-specific way. Also, that's not a MG thing, it's how VKs everywhere work.
