### ISSUE TITLE
Document system requirements for SDK and runtime

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#6580]
We should really update the REQUIREMENTS.md file in the project root and share the page with the [System Requirements](http://www.monogame.net/documentation/?page=System_Requirements) doc (or just remove this REQUIREMENTS.md file altogether).

This comes up a lot and if we write a comprehensive page with all the information we can just point users to it instead of repeating over and over (and sometimes even searching for the right information ourselves, I know I always have to check for OpenGL requirements).

We need to explain the SDK requirements per platform (Linux, Windows, Mac) and the runtime requirements for each (public) project type. Maybe we should split those in 2 separate pages in the docs.

## MG SDK

- Linux:
   - GTK for the Pipeline Tool
   - #5866 
- Windows:
   - DirectX SDK for effects
   - Visual C++ runtimes 20xx (not sure which ones)
- Mac:
   - ???

## Lowest supported runtime requirements

- WindowsDX:
   - DirectX 9.0c+ GPU and driver
- UWP:
   - DirectX 9.0c+ GPU and driver
   - Windows 10 Kit (minimal version?)
- DesktopGL:
   - OpenGL 3.0+ or OpenGL 2.0+ and ARB_framebuffer_object extension
- Android:
  - Android SDK (minimal version?)
- iOS:
  - ???

## Runtime native dependencies

E.g. SDL, OpenAL Soft for DesktopGL 
+ explain bundling for publish (cc @mrhelmut #4430)

We should also explain that the runtime requirements can be higher to enable functionality and explain `GraphicsProfile` and `GraphicsCapabilities`.

cc @cra0zy @tomspilman @SimonDarksideJ to help complete this

**Comment by mrhelmut** [comment]
Windows DX requires the "DirectX June 2010 redist" to have gamepad and sound effects working (even on Windows 10).

There also this thing about "Windows N" versions (Windows without Media Player, therefore missing critical dll for song playback). For reference #4176

I really should get #4430 updated and moving forward.
