### ISSUE TITLE
MonoGame.Content.Builder.targets does not respect outputDir

### ISSUE THREAD

**Issue by EnemyArea** [MonoGame/MonoGame#6582]
If you make a new project with monogame and add one image to the Content.mgcb, the outputDir from it isnt used to move the compiled files. Lets assume the project is named "ContentGame", after compile you get that directory chaos:

ContentGame
-ContentGame
--bin
---Windows
----Content (empty)
----x86
-----Debug (game.exe)
------Content (with the image)
--Content
---bin
----Windows
-----Content (with the image too...)
---obj
----Windows
-----Content
--obj
---Windows
----Content (empty)
---x86
----Debug
--Properties
![grafik](https://user-images.githubusercontent.com/2128995/49704020-760ae500-fc0d-11e8-9efe-080b6d52073a.png)

Why are so many empty and wrong Content folders?
If I set the outputDir to C:\Projects\Game\Content\ it should be there. If you use the pipeline tool, it works.

EDIT:  I have looked how to fix it. There are two lines I changed to get rid of the extra content folders:
```
<MakeDir Directories="%(ContentReferences.ContentOutputDir)"/>
<MakeDir Directories="%(ContentReferences.ContentIntermediateOutputDir)"/>
```

AND if you remove the parameters from RunContentBuilder it used, as I expected, te settings. But it doesnt copy the files to the exe directory any more.. (I have no need, but maybe someone will ;))

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by harry-cpp** [comment]
Yup, mgcb output path is not something task should respect.
