### ISSUE TITLE
IntermediateSerializer does not serialize any objects

### ISSUE THREAD

**Issue by Talanin** [MonoGame/MonoGame#6591]
IntermediateSerializer(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate namespace) doesn't work properly. Everything is working fine while you're deserializing XML, but when you try to serialize something, nothing happens at all.

https://blogs.msdn.microsoft.com/shawnhar/2008/08/12/teaching-a-man-to-fish/
Code from there works with XNA library and doesn't work with one from MonoGame.

If you run this code with referenced MonoGame.Framework.Content.Pipeline.Portable.dll, it will cause an empty console:

    using System;
    using System.Xml;
    using Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate;

    namespace IntermediateSerializerTest
    {
        class MyTest
        {
            public int elf = 23;
            public string hello = "Hello World";
        }

        class Program
        {
            static void Main(string[] args)
            {
                MyTest testData = new MyTest();

                XmlWriterSettings settings = new XmlWriterSettings()
                {
                    Indent = true
                };

                using (XmlWriter writer = XmlWriter.Create(Console.Out, settings))
                {
                    IntermediateSerializer.Serialize(writer, testData, null);
                }

                Console.ReadKey(true);
            }
        }
    }

**Comment by Jjagg** [comment]
The Portable assembly is not meant for consumption and does not contain any implementation. It's only meant as a target for class libraries. At runtime a dll for a specific platform is always required. Please try using the Content Pipeline project that matches your platform.
