### ISSUE TITLE
MonoGame 3.7 stops iOS background music on startup with no workaround

### ISSUE THREAD

**Issue by dtaylorus** [MonoGame/MonoGame#6595]
MonoGame 3.7 has a regression from 3.6 where the iOS audio session category is incorrectly set to `AVAudioSessionCategory.SoloAmbient` in `OpenALSoundController.cs`.

This immediately stops background music and breaks the workaround in issue #735, which was to set the audio session category to `AVAudioSessionCategory.Ambient` in `FinishedLaunching`.

In my opinion, MonoGame should not override the audio category set by the developer, and this code should be deleted.

For one of my games (a party game where audio is essential) I want to use `AVAudioSessionCategory.Playback` with the option `AVAudioSessionCategoryOptions.MixWithOthers` and `SecondaryAudioShouldBeSilencedHint` in order to create an experience where my game sound effects always play (even if the ringer is muted) and my background music only plays if some other background music isn't already playing.

For another of my games (a puzzle game where audio is not essential), I want to use `Ambient` so my sound is silenced when the ringer is muted.

My point is that there isn't a single category that the MonoGame framework should dictate for every game. The framework should leave this setting up to the game developer.

Also note that MonoGame is not setting `AVAudioSessionCategory` when the application is resumed/activated, so I'm able to get the correct behavior if the user switches back to the music app, restarts the music, and switches back to my game. However, I don't consider this a viable workaround.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- iOS

#### What MonoGame platform are you using:

- iOS

**Comment by Jjagg** [comment]
Looks like this was changed in #6433. There's a comment that mentions that it interrupts other non-mixable audio, so Tom was aware of this behavior. I think we can simply remove the line that sets the audio session. The comment mentions that `SoloAmbient` is the default, so I think behavior won't change by default, but users would be able to override the category.

**Comment by dtaylorus** [comment]
I confirmed that commenting out the line that sets `SoloAmbient` does fix this issue.

**Comment by Jjagg** [comment]
@dtaylorus Can you also check that the issue mentioned in #6433 is still fixed after that change. I.e. don't override the audio category, switch away from the game, turn on audio, return to the game -> audio should still work.

**Comment by dtaylorus** [comment]
I removed my override of the audio category, started my game, verified that sound effects were working, started Siri, switched back to my game, and verified that sound effects were still working.

My background music didn't resume after returning from Siri, but that's the case whether I override the category or not. Also, if I turn the music off and back on from my game settings, it does start to play again. So I don't think that's related to #6433 as I read it.

So yes, I believe #6433 is still fixed after deleting the `SoloAmbient` line.

**Comment by Jjagg** [comment]
That sounds good, thanks :) Would you be able to set up a pull request to remove the line that sets the category @dtaylorus?

**Comment by dtaylorus** [comment]
Sure. I also investigated the music resume problem and it happens because `MediaPlayer.State == MediaState.Playing` even though the music has stopped after returning from Siri. So my code doesn't know it needs to be resumed. I'll follow up on that as a separate issue later.

**Comment by Jjagg** [comment]
Thanks!

**Comment by Jjagg** [comment]
Fixed in #6596.
