### ISSUE TITLE
Can't build content for DesktopGL

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#6598]
Hey there!

When using the MGCB from the installer (nightly build), I am unable to build content for ```DesktopGL``` platform. MGCB returns ```Invalid value 'DesktopGL' for option 'platform'``` (which is also a silent failure when using the Pipeline tool).

The weird part is that if I build MGCB locally, it works (and I don't seem to find where this issue is coming from).

It looks like the ```TargetPlaform``` enum conversion is failing at some point? Can this be related to a change within the build bot?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by tomspilman** [comment]
> which is also a silent failure when using the Pipeline tool

First thing...  we need to capture and ensure there are no silent failures.

Then let's fix the real bug.

>  MGCB returns Invalid value `'DesktopGL' for option 'platform'`

Yeah that is weird.  It has to be a build bot thing of some sort but i don't know what.

Did anything change there recently?  @cra0zy @Jjagg

**Comment by Jjagg** [comment]
> Did anything change there recently?

No, doesn't look like it.

The code that fails is here: https://github.com/MonoGame/MonoGame/blob/6f34eb393aa0ac005888d74c5c4c6ab5615fdc8c/Tools/MGCB/CommandLineParser.cs#L431-L471

The platform option is defined here: https://github.com/MonoGame/MonoGame/blob/6f34eb393aa0ac005888d74c5c4c6ab5615fdc8c/Tools/MGCB/BuildContent.cs#L92-L97

I don't have time to look at this in depth right now.
