### ISSUE TITLE
Feature request if possible GetState raised.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#6600]
Dunno how to close this myself but i guess it can be closed.

I don't know if this is possible but it would be nice.

Id like a way to register to a event that is raised on 
Any keys pressed or down ect... and that passes GameTime as a parameter. 

So that i can make a callback to bypass having to poll in update specifically im trying to make a keyboard class that only calls getstate when it needs to.
Much like how textinput is raised as a callback for character keys space enter backspace tab and insert.

So any time getstate would be populated the event or action or func would be raised.

Essentially i want to bypass polling Keyboard.GetState() every update. Atm i need to have a update method for my keyboard class, which isn't a big deal.
However, if i want to compartmentalize it without having to poll getstate every update that's not really possible and this would sort of make it possible to use keyboard like textinput and it would be kind of nice if there was a uniformed way to use them.

Which is what i was dabling with and why im asking.

Here is how my game1 looks currently in the update you can see below it would be nicer looking to just get rid of the KeyBoard.Update if there was a event raised for any key that passed gametime i could just poll getstate in my keyboard class.

```
using System;
using System.Text;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace TestNewKeyboardClasses
{

    public class Game1 : Game
    {
        GraphicsDeviceManager graphics;
        SpriteBatch spriteBatch;
        SpriteFont font;
        
        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
        }

        protected override void Initialize()
        {
            Gu.AddMethodToRaiseOnWindowReSizeEvent(OnResize);

            KeyBoardTextInput.Initialize(this.Window);
            KeyBoardTextInput.AddMethodsToRaiseOnKeyBoardActivity(OnTextInput, OnKeyboardShortCutsOrCommands);
            KeyBoardTextInput.KeyRepeatDelay = .01f;

            base.Initialize();
        }

        protected override void LoadContent()
        {
            Gu.SetUpLoad(this, graphics, Content, "MgFont");
            spriteBatch = Gu.spriteBatch;
            font = Gu.currentFont;
        }

        protected override void UnloadContent()
        { 
        }

        protected override void Update(GameTime gameTime)
        {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();

            Gu.Update(gameTime); // i could stick it in here to hide it but i don't want to always use a helper class.

            KeyBoardTextInput.Update(gameTime); // it would be nicer if i could just register to a Any KeyBoard Event or Action

            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);

            spriteBatch.Begin();
            Gu.Draw(gameTime);
            spriteBatch.End();

            base.Draw(gameTime);
        }

        public void OnResize()
        {
        }
        public void OnTextInput(StringBuilder s, Keys k)
        {
            //Console.WriteLine("OnCharacterKeys  raised");
        }
        public void OnKeyboardShortCutsOrCommands(Keys k1, Keys k2)
        {
            //Console.WriteLine("OnControlKeys raised");
        }
    }
}
```
Just in case anyone is curious i can post the rest of it or the project if you like there is a keyboard info class also with the keyboard class that i had to align with the keys enum. It basically just catagorizes keys in relation to text input not both as well as the kind of key pressed. As it is both events can end up fired sometimes if it makes sense to and can be ignored or not in one method or the other by the user.

**Comment by Jjagg** [comment]
> Id like a way to register to a event that is raised on
Any keys pressed or down ect... and that passes GameTime as a parameter.

This doesn't really add any functionality.

I'm against adding an event for when a key is pressed. It essentially duplicates API. It's just another way for users to detect that keys are down. We shouldn't add an API just because someone says it fits the style of their project better.

**Comment by willmotil** [comment]
I wouldn't say it just fits the style of my project better. 
Id say the current textinput and keyboard classes are confused about what style they want to be.

It looks sort of messed up for text input to be a event. 
Then the keyboard class to require polling update.

Especially since you have to use the both if you plan to make something as common as a game chatbox or a game with short cut keys or both in the same application.

C# is riddled with syntactic sugar just to make things easier or to make it more intuitive.
I figured it might be a trivial addition since sdl is raising a event on window text input anyways.

**Comment by Jjagg** [comment]
> I figured it might be a trivial addition since sdl is raising a event on window text input.

It **is** a trivial addition, but that in itself doesn't justify it. Adding the event makes our API more confusing. Now if we could replace the Keyboard API to be event based this discussion could be very different. But we have certain rules to stick by with regards to backwards compatibility.

**Comment by Apostolique** [comment]
Personally, I much prefer polling when it comes to keyboard input. And if you want events, it's easy to abstract that away in your game.

**Comment by willmotil** [comment]
Well i suppose it would make things more confusing.

I didn't mean replace the polling though just add the event so that you could still use either or both.
So for instance if there was a event that fired once per update when a key was pressed you could put that method in the template so it was clear.

For example in the previous code if it was part of the framework it would look like the below.

```
        protected override void Initialize()
        {
            base.Initialize();
        }
        protected override void Update(GameTime gameTime)
        {
            // do update stuff

            base.Update(gameTime);
        }
        public void OnKeyboardShortCutsOrCommands(Keys k1, Keys k2)
        {
                if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();
        }
```

It looks cleaner to me. I dunno maybe that would be more confusing and a little redundant.

**Comment by tamkcr** [comment]
What is lacking from just using GameWindow.TextInput?

**Comment by stromkos** [comment]
@willmotil, 
I cannot answer to the GameWindow.TextInput, but, traditional input can be polled once per update. If you need higher resolution you can hook into the native message-pump loop of the target OS.
I have found a use for this technique in touch mapping in Android, and mouse movements in Windows, but beyond that, I cannot fathom a need for this to be included in the framework.

**Comment by Jjagg** [comment]
Feature was added as `GameWindow.KeyDown` and `GameWindow.KeyUp` in #6762.
