### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [MonoGame/MonoGame#6608]
i've downloaded Version '3.7.1' but when selecting "Pipeline.app"  in the Finder and using 'Get Info' it claims to be Version '3.3'

**Comment by mrhelmut** [comment]
.plist metadata here should be updated: https://github.com/MonoGame/MonoGame/blob/develop/Tools/Pipeline/Info.plist#L25

Worth noting that MGCB could have more info in its own .plist: https://github.com/MonoGame/MonoGame/blob/develop/Tools/MGCB/Info.plist

**Comment by core-code** [comment]
i can provide you with current best-practice Info.plist template from Xcode if you need one

**Comment by Jjagg** [comment]
That would be great @core-code.

I wonder if we could insert the right version at build time somehow.

**Comment by core-code** [comment]
no problem, i've uploaded the Xcode 10.1 Info.plist template here:
https://gist.github.com/core-code/3f5ab40a5d85bc056228ce4f6fbac4e3

i'm sure there are various ways to automate setting of version numbers, but it all depends on your build environment so i can't give any definitive recommendation.
having a look at "PlistBuddy" is always a good idea though as it can manipulate the Info.plist file:

`/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $versionString" path/to/Info.plist`

personally i just search for the old version number and replace it manually in all 3 places with the new one prior to each release. because the uploadable ZIP filename gets generated from the version string in a later step, its impossible to forget this.

**Comment by harry-cpp** [comment]
This has been fixed.
