### ISSUE TITLE
Loading music with Content.Load<Song> fails, yet it works with Content.Load<SoundEffect>

### ISSUE THREAD

**Issue by egordorichev** [MonoGame/MonoGame#6609]
Hi. I'm trying to get music working in my game. I took a few .mp3 and .wav files, that work with other engines, and plugged them into Content Pipeline. 

![screenshot from 2018-12-29 13-18-57](https://user-images.githubusercontent.com/7851390/50537077-81965f80-0b6c-11e9-996a-9d845d010a66.png)

_Here is an example of settings._

Loading music with Content.Load<Song> fails, yet it works with Content.Load<SoundEffect>. Here is the exception:

```
System.IO.InvalidDataException: Could not determine container type!
  at NVorbis.VorbisReader..ctor (System.IO.Stream stream, System.Boolean closeStreamOnDispose) 
```

Content Pipeline creates 2 files in the `bin/Music` folder: `shop.wma` and `shop.xnb`. The original file is .mp3. I tried converting the file to other formats or exporting it using audacity, nothing helps.

Here is the code:

```c
Assets.Content.Load<Song>("bin/Music/shop");
```

It won't crash if I change the export type to Sound Effect in Content Pipeline and load it like:

```c
Assets.Content.Load<SoundEffect>("bin/Music/shop");
```

Thanks a bunch.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Linux (ubuntu 18.04 64 bit)

#### What MonoGame platform are you using:
- DesktopGL

**Comment by mrhelmut** [comment]
You should specify the Content Pipeline that the target platform is DesktopGL and rebuild your assets. Based on your feedback, it is wrongly set to Windows and MonoGame tries to load the wma while it is expecting an ogg file.
You should have both an xnb and an ogg file in your Music folder.

**Comment by egordorichev** [comment]
Oh, my bad :man_facepalming: I totally missed the export target platform settings, thanks a lot, it fixed it!
