### ISSUE TITLE
MonoGame WindowsDX is not compatible with SharpDX 4.2.0 yet

### ISSUE THREAD

**Issue by devedse** [MonoGame/MonoGame#6611]
The following issue pops up once you try to use SharpDX 4.2.0 together with MonoGame

![image](https://user-images.githubusercontent.com/2350015/50542685-b08bf000-0bc3-11e9-8679-de55902c17da.png)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by devedse** [comment]
Good question, was kinda in a rush when making this issue :).

Reason we would like to upgrade is because currently in SharpDX 4.0.1 there's an issue where the UWP apps you create can't be published to the Windows Store because they make use of some native calls (well they aren't actually used but they are included in the SharpDX DLL's). This pops up when you run the "Windows App Cert Kit" on them.

This was supposed to be fixed in SharpDX 4.2.0 however it apparently wasn't completely:
https://github.com/sharpdx/SharpDX/pull/1111

I fixed this in this pull request but then when testing it with the latest MonoGame version I ran into this issue.

**Comment by devedse** [comment]
Exactly :)

**Comment by mrhelmut** [comment]
Feel free to ping here when 4.2.1 is available. :)

**Comment by tomspilman** [comment]
@mrhelmut  @Jjagg @cra0zy - So looks like SharpDX 4.2.1 will never release officially, so to fix this we're going to have to build the latest SharpDX ourselves and resolve the issue.

We have a fork here where we should land our fixes/changes and build from:

 https://github.com/MonoGame/SharpDX

If someone can find the build instructions for the project i can set it up on our automated build process.

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
