### ISSUE TITLE
Wrong parameter order for MGCB.exe in .targets file

### ISSUE THREAD

**Issue by MOAMiner** [MonoGame/MonoGame#6645]
The parameter order in MonoGame.Content.Builder.targets for MGCB.exe seems to be wrong in concern of cross-platform projects. The /platform paramter should come after the /@ parameter in order to correctly overwrite the platform in order to have platform specific projects (with shared content) built their content correctly.

..in the current order the /platform parameter is always ignored when a .mgcb file is provided - which happens to be the case in cross-platform with shared project

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- not relevant

**Comment by Jjagg** [comment]
This got fixed.
