### ISSUE TITLE
No autocomplete/intellisense in shared project.

### ISSUE THREAD

**Issue by Emmsii** [MonoGame/MonoGame#6648]
**Autocomplete/intellisense does not work in a Monogame Shared project.**

Steps to reproduce:

1. Create a new Monogame Shared project.
2. Right click on the solution and create a new Monogame DX or OpenGL project.
3. Add the shared project as a reference to the DX/GL project.
    a. When I do this, the using statement in the shared project `using Microsoft.Xna.Framework.Storage;` throws an error: "The type or namespace 'Storage' does not exist in the namespace 'Monogame.XNA.Framework'." I'm not sure what's up with that.
4. Create a new class in the shared project.
5. Begin typing the 'prop' shortcut for creating a property. 
6. There is no autocomplete or intellisense. Pressing TAB does not trigger the prop shortcut. Also, I am unable to use the `;` character at all.

I'm only able to fix this by unloading and reloading the shared project, but I don't want to have to do that every time I make a new class.

I'm using Visual Studio Professional 2017 Version 15.9.4, as well as JetBrains ReSharper Ultimate 2018.3.1.

Example: https://imgur.com/iQ17oYQ

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1708

#### What operating system are you using:
- Windows 10 Pro Version: 1803 Build: 17164.523

#### What MonoGame platform are you using:

- Shared, DesktopGL, WindowsDX

**Comment by cra0zy** [comment]
This is not a MonoGame issue, this is just how shared projects work in Visual Studio, as such, closing...
