### ISSUE TITLE
Templates missing in MonoGame 3.7.1?

### ISSUE THREAD

**Issue by BrainSlugs83** [MonoGame/MonoGame#6662]
After installing MonoGame 3.7.1 for Visual Studio, from the [Official Release](http://community.monogame.net/t/monogame-3-7-1-release/11173), I do not have any new project templates in Visual Studio 2017 (Enterprise).  There were no errors during the install, and nothing particularly noteworthy in the "Application" or "Setup" sections of the system event logs.  Running the installer multiple times does not alleviate the situation.

#### What version of MonoGame does the bug occur on:
- The official release of MonoGame 3.7.1 (linked above) for Visual Studio.

#### What operating system are you using:
- Windows 10 (1709, but otherwise up-to-date)
- Visual Studio Enterprise 2017 (15.9.7)

#### What MonoGame platform are you using:
- None, all of the templates are missing (hence the bug).

#### Installer:
![image](https://user-images.githubusercontent.com/5217366/52891628-02231680-3141-11e9-84b3-f80d0b916c52.png)

#### Visual Studio 2017 -- New Project Dialog:
![image](https://user-images.githubusercontent.com/5217366/52891604-e455b180-3140-11e9-82b2-57cc1ee0a9d8.png)

**Comment by Jamezila** [comment]
Just encountered this problem, following.

**Comment by stromkos** [comment]
@BrainSlugs83,
Were you using the same user for both installation and running it?

**Comment by Jamezila** [comment]
I figured it out -- it was putting the templates in my OneDrive Documents folder. I manually moved them to my regular Documents folder and now they show up.

**Comment by mrhelmut** [comment]
The installer has retired, closing.
