### ISSUE TITLE
monogame-pipeline-tool 3.7.1

### ISSUE THREAD

**Issue by Rombersoft** [MonoGame/MonoGame#6665]
When I click right mouse button on source file that application crashes always.
#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Lubuntu 16.10

#### What MonoGame platform are you using:
- DesktopGL

Stack trace:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Gtk.Menu.PopupAtPointer (Gdk.Event trigger_event) [0x00014] in <f775ff7b2e4a42d992aca2c382879b7c>:0 
  at Gtk.Menu.Popup () [0x00000] in <f775ff7b2e4a42d992aca2c382879b7c>:0 
  at Eto.GtkSharp.Forms.Controls.GridHandler`2+GridConnector[TWidget,TCallback].HandleButtonPress (System.Object o, Gtk.ButtonPressEventArgs args) [0x000f7] in <3bbc1daff97142648cd48237c49932b3>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <2f83d2ff70e3444cb3582fe4e97bad63>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00051] in <2f83d2ff70e3444cb3582fe4e97bad63>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <2f83d2ff70e3444cb3582fe4e97bad63>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <2f83d2ff70e3444cb3582fe4e97bad63>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <2f83d2ff70e3444cb3582fe4e97bad63>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <2f83d2ff70e3444cb3582fe4e97bad63>:0 
  at GLib.Signal.ClosureInvokedCB (System.Object o, GLib.ClosureInvokedArgs args) [0x00034] in <902eeaa2a1d147909254a60264666525>:0 
  at GLib.SignalClosure.Invoke (GLib.ClosureInvokedArgs args) [0x00009] in <902eeaa2a1d147909254a60264666525>:0 
  at GLib.SignalClosure.MarshalCallback (System.IntPtr raw_closure, System.IntPtr return_val, System.UInt32 n_param_vals, System.IntPtr param_values, System.IntPtr invocation_hint, System.IntPtr marshal_data) [0x00136] in <902eeaa2a1d147909254a60264666525>:0 

Console output:
destructor@Toshiba-Satellite-C660:~$ monogame-pipeline-tool 
[WARNING] Function not found: gtk_normalise_detailed_action_name
[WARNING] Function not found: gtk_show_uri_on_window

** (Pipeline:18722): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[WARNING] Function not found: gdk_pixbuf_new_from_file_at_scale_utf8
[WARNING] Function not found: gdk_pixbuf_new_from_file_at_size_utf8
[WARNING] Function not found: gdk_pixbuf_new_from_file_utf8
[WARNING] Function not found: gdk_pixbuf_copy_options
[WARNING] Function not found: gdk_pixbuf_remove_option
[WARNING] Function not found: gdk_pixbuf_save_to_streamv
[WARNING] Function not found: gdk_pixbuf_save_to_streamv_async
[WARNING] Function not found: gdk_pixbuf_savev_utf8
[WARNING] Function not found: gtk_icon_theme_get_search_path_utf8
[WARNING] Function not found: gtk_icon_theme_set_search_path_utf8
[WARNING] Function not found: cairo_atsui_font_face_create_for_atsu_font_id
[WARNING] Function not found: cairo_glitz_surface_create
[WARNING] Function not found: cairo_quartz_surface_create
[WARNING] Function not found: cairo_directfb_surface_create
[WARNING] Function not found: cairo_win32_font_face_create_for_logfontw
[WARNING] Function not found: cairo_win32_scaled_font_done_font
[WARNING] Function not found: cairo_win32_scaled_font_get_metrics_factor
[WARNING] Function not found: cairo_win32_scaled_font_select_font
[WARNING] Function not found: cairo_win32_surface_create
[WARNING] Function not found: cairo_win32_surface_create_with_ddb
[WARNING] Function not found: gdk_cairo_get_drawing_context
[WARNING] Function not found: gtk_widget_get_focus_on_click
[WARNING] Function not found: gtk_widget_set_focus_on_click
[WARNING] Function not found: gtk_widget_get_allocated_size
[WARNING] Function not found: gtk_widget_queue_allocate
[WARNING] Function not found: gtk_clipboard_get_selection

(Pipeline:18722): GdkPixbuf-CRITICAL **: gdk_pixbuf_new: assertion 'bits_per_sample == 8' failed

(Pipeline:18722): GdkPixbuf-CRITICAL **: gdk_pixbuf_new: assertion 'bits_per_sample == 8' failed
[WARNING] Function not found: gtk_menu_place_on_monitor
[WARNING] Function not found: gtk_menu_popup_at_pointer
[WARNING] Function not found: gtk_menu_popup_at_rect
[WARNING] Function not found: gtk_menu_popup_at_widget

(Pipeline:18722): Gtk-CRITICAL **: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed

(Pipeline:18722): Gtk-CRITICAL **: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed

(Pipeline:18722): Gtk-CRITICAL **: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed
[WARNING] Function not found: gtk_style_context_to_string
[WARNING] Function not found: gtk_scrolled_window_get_max_content_width
[WARNING] Function not found: gtk_scrolled_window_set_max_content_width
[WARNING] Function not found: gtk_scrolled_window_get_max_content_height
[WARNING] Function not found: gtk_scrolled_window_set_max_content_height
[WARNING] Function not found: gtk_scrolled_window_get_propagate_natural_width
[WARNING] Function not found: gtk_scrolled_window_set_propagate_natural_width
[WARNING] Function not found: gtk_scrolled_window_get_propagate_natural_height
[WARNING] Function not found: gtk_scrolled_window_set_propagate_natural_height
[WARNING] Function not found: gtk_text_view_reset_cursor_blink
[WARNING] Function not found: g_source_get_type
Cairo.Context is leaking, programmer is missing a call to Dispose
Set MONO_CAIRO_DEBUG_DISPOSE to track allocation traces

(Pipeline:18722): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:18722): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:18722): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:18722): Gtk-CRITICAL **: gtk_widget_queue_draw_area: assertion 'width >= 0' failed
[WARNING] Function not found: gdk_window_begin_draw_frame
[WARNING] Function not found: gdk_window_end_draw_frame

(Pipeline:18722): Gtk-CRITICAL **: gtk_icon_set_unref: assertion 'icon_set != NULL' failed

(Pipeline:18722): Gtk-CRITICAL **: gtk_icon_set_unref: assertion 'icon_set != NULL' failed

(Pipeline:18722): Gtk-CRITICAL **: gtk_icon_set_unref: assertion 'icon_set != NULL' failed

(Pipeline:18722): Gtk-CRITICAL **: gtk_widget_queue_draw_area: assertion 'width >= 0' failed
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

[WARNING] Function not found: gtk_file_chooser_add_choice
[WARNING] Function not found: gtk_file_chooser_get_choice
[WARNING] Function not found: gtk_file_chooser_remove_choice
[WARNING] Function not found: gtk_file_chooser_set_choice
[WARNING] Function not found: gtk_file_filter_new_from_gvariant
[WARNING] Function not found: gtk_file_filter_to_gvariant

(Pipeline:18722): Gtk-CRITICAL **: gtk_tree_view_unref_tree_helper: assertion 'node != NULL' failed
[WARNING] Function not found: gtk_text_iter_starts_tag
Marshaling button-press-event signal

(Pipeline:18722): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:18722): Gtk-WARNING **: Toplevel size doesn't seem to directly depend on the size of the geometry widget from gtk_window_set_geometry_hints(). The geometry widget might not be in the window, or it might not be packed into the window appropriately
destructor@Toshiba-Satellite-C660:~$ monogame-pipeline-tool 
[WARNING] Function not found: gtk_normalise_detailed_action_name
[WARNING] Function not found: gtk_show_uri_on_window

** (Pipeline:19756): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[WARNING] Function not found: gdk_pixbuf_new_from_file_at_scale_utf8
[WARNING] Function not found: gdk_pixbuf_new_from_file_at_size_utf8
[WARNING] Function not found: gdk_pixbuf_new_from_file_utf8
[WARNING] Function not found: gdk_pixbuf_copy_options
[WARNING] Function not found: gdk_pixbuf_remove_option
[WARNING] Function not found: gdk_pixbuf_save_to_streamv
[WARNING] Function not found: gdk_pixbuf_save_to_streamv_async
[WARNING] Function not found: gdk_pixbuf_savev_utf8
[WARNING] Function not found: gtk_icon_theme_get_search_path_utf8
[WARNING] Function not found: gtk_icon_theme_set_search_path_utf8
[WARNING] Function not found: cairo_atsui_font_face_create_for_atsu_font_id
[WARNING] Function not found: cairo_glitz_surface_create
[WARNING] Function not found: cairo_quartz_surface_create
[WARNING] Function not found: cairo_directfb_surface_create
[WARNING] Function not found: cairo_win32_font_face_create_for_logfontw
[WARNING] Function not found: cairo_win32_scaled_font_done_font
[WARNING] Function not found: cairo_win32_scaled_font_get_metrics_factor
[WARNING] Function not found: cairo_win32_scaled_font_select_font
[WARNING] Function not found: cairo_win32_surface_create
[WARNING] Function not found: cairo_win32_surface_create_with_ddb
[WARNING] Function not found: gdk_cairo_get_drawing_context
[WARNING] Function not found: gtk_widget_get_focus_on_click
[WARNING] Function not found: gtk_widget_set_focus_on_click
[WARNING] Function not found: gtk_widget_get_allocated_size
[WARNING] Function not found: gtk_widget_queue_allocate
[WARNING] Function not found: gtk_clipboard_get_selection

(Pipeline:19756): GdkPixbuf-CRITICAL **: gdk_pixbuf_new: assertion 'bits_per_sample == 8' failed

(Pipeline:19756): GdkPixbuf-CRITICAL **: gdk_pixbuf_new: assertion 'bits_per_sample == 8' failed
[WARNING] Function not found: gtk_menu_place_on_monitor
[WARNING] Function not found: gtk_menu_popup_at_pointer
[WARNING] Function not found: gtk_menu_popup_at_rect
[WARNING] Function not found: gtk_menu_popup_at_widget

(Pipeline:19756): Gtk-CRITICAL **: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed

(Pipeline:19756): Gtk-CRITICAL **: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed

(Pipeline:19756): Gtk-CRITICAL **: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed
[WARNING] Function not found: gtk_style_context_to_string
[WARNING] Function not found: gtk_scrolled_window_get_max_content_width
[WARNING] Function not found: gtk_scrolled_window_set_max_content_width
[WARNING] Function not found: gtk_scrolled_window_get_max_content_height
[WARNING] Function not found: gtk_scrolled_window_set_max_content_height
[WARNING] Function not found: gtk_scrolled_window_get_propagate_natural_width
[WARNING] Function not found: gtk_scrolled_window_set_propagate_natural_width
[WARNING] Function not found: gtk_scrolled_window_get_propagate_natural_height
[WARNING] Function not found: gtk_scrolled_window_set_propagate_natural_height
[WARNING] Function not found: gtk_text_view_reset_cursor_blink
[WARNING] Function not found: g_source_get_type
Cairo.Context is leaking, programmer is missing a call to Dispose
Set MONO_CAIRO_DEBUG_DISPOSE to track allocation traces

(Pipeline:19756): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:19756): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:19756): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:19756): Gtk-CRITICAL **: gtk_widget_queue_draw_area: assertion 'width >= 0' failed
[WARNING] Function not found: gdk_window_begin_draw_frame
[WARNING] Function not found: gdk_window_end_draw_frame

(Pipeline:19756): Gtk-CRITICAL **: gtk_icon_set_unref: assertion 'icon_set != NULL' failed

(Pipeline:19756): Gtk-CRITICAL **: gtk_icon_set_unref: assertion 'icon_set != NULL' failed

(Pipeline:19756): Gtk-CRITICAL **: gtk_icon_set_unref: assertion 'icon_set != NULL' failed

(Pipeline:19756): Gtk-CRITICAL **: gtk_widget_queue_draw_area: assertion 'width >= 0' failed
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

(Pipeline:19756): Gtk-CRITICAL **: gtk_tree_view_unref_tree_helper: assertion 'node != NULL' failed
[WARNING] Function not found: gtk_text_iter_starts_tag
Marshaling button-press-event signal

(Pipeline:19756): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:19756): Gtk-WARNING **: Toplevel size doesn't seem to directly depend on the size of the geometry widget from gtk_window_set_geometry_hints(). The geometry widget might not be in the window, or it might not be packed into the window appropriately

(Pipeline:19756): Gtk-CRITICAL **: gtk_clipboard_set_with_data: assertion 'targets != NULL' failed

(Pipeline:19756): Gtk-CRITICAL **: gtk_clipboard_set_with_data: assertion 'targets != NULL' failed

**Comment by cra0zy** [comment]
Most likely we are using a function which requires a newer version of Gtk.

On a related note, I should probably create a snap or a flatpak package for the Pipeline Tool.

**Comment by Rombersoft** [comment]
What is GTK version required???

**Comment by Rombersoft** [comment]
this is output when I run it in terminal emulator:
```
[WARNING] Function not found: gtk_normalise_detailed_action_name
[WARNING] Function not found: gtk_show_uri_on_window

** (Pipeline:10117): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[WARNING] Function not found: gdk_pixbuf_new_from_file_at_scale_utf8
[WARNING] Function not found: gdk_pixbuf_new_from_file_at_size_utf8
[WARNING] Function not found: gdk_pixbuf_new_from_file_utf8
[WARNING] Function not found: gdk_pixbuf_copy_options
[WARNING] Function not found: gdk_pixbuf_remove_option
[WARNING] Function not found: gdk_pixbuf_save_to_streamv
[WARNING] Function not found: gdk_pixbuf_save_to_streamv_async
[WARNING] Function not found: gdk_pixbuf_savev_utf8
[WARNING] Function not found: gtk_icon_theme_get_search_path_utf8
[WARNING] Function not found: gtk_icon_theme_set_search_path_utf8
[WARNING] Function not found: cairo_atsui_font_face_create_for_atsu_font_id
[WARNING] Function not found: cairo_glitz_surface_create
[WARNING] Function not found: cairo_quartz_surface_create
[WARNING] Function not found: cairo_directfb_surface_create
[WARNING] Function not found: cairo_win32_font_face_create_for_logfontw
[WARNING] Function not found: cairo_win32_scaled_font_done_font
[WARNING] Function not found: cairo_win32_scaled_font_get_metrics_factor
[WARNING] Function not found: cairo_win32_scaled_font_select_font
[WARNING] Function not found: cairo_win32_surface_create
[WARNING] Function not found: cairo_win32_surface_create_with_ddb
[WARNING] Function not found: gdk_cairo_get_drawing_context
[WARNING] Function not found: gtk_widget_get_focus_on_click
[WARNING] Function not found: gtk_widget_set_focus_on_click
[WARNING] Function not found: gtk_widget_get_allocated_size
[WARNING] Function not found: gtk_widget_queue_allocate
[WARNING] Function not found: gtk_clipboard_get_selection

(Pipeline:10117): GdkPixbuf-CRITICAL **: gdk_pixbuf_new: assertion 'bits_per_sample == 8' failed

(Pipeline:10117): GdkPixbuf-CRITICAL **: gdk_pixbuf_new: assertion 'bits_per_sample == 8' failed
[WARNING] Function not found: gtk_menu_place_on_monitor
[WARNING] Function not found: gtk_menu_popup_at_pointer
[WARNING] Function not found: gtk_menu_popup_at_rect
[WARNING] Function not found: gtk_menu_popup_at_widget

(Pipeline:10117): Gtk-CRITICAL **: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed

(Pipeline:10117): Gtk-CRITICAL **: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed

(Pipeline:10117): Gtk-CRITICAL **: gtk_icon_set_new_from_pixbuf: assertion 'pixbuf != NULL' failed
[WARNING] Function not found: gtk_style_context_to_string
[WARNING] Function not found: gtk_scrolled_window_get_max_content_width
[WARNING] Function not found: gtk_scrolled_window_set_max_content_width
[WARNING] Function not found: gtk_scrolled_window_get_max_content_height
[WARNING] Function not found: gtk_scrolled_window_set_max_content_height
[WARNING] Function not found: gtk_scrolled_window_get_propagate_natural_width
[WARNING] Function not found: gtk_scrolled_window_set_propagate_natural_width
[WARNING] Function not found: gtk_scrolled_window_get_propagate_natural_height
[WARNING] Function not found: gtk_scrolled_window_set_propagate_natural_height
[WARNING] Function not found: gtk_text_view_reset_cursor_blink
[WARNING] Function not found: g_source_get_type
Cairo.Context is leaking, programmer is missing a call to Dispose
Set MONO_CAIRO_DEBUG_DISPOSE to track allocation traces

(Pipeline:10117): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:10117): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:10117): Gtk-CRITICAL **: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(Pipeline:10117): Gtk-CRITICAL **: gtk_widget_queue_draw_area: assertion 'width >= 0' failed
[WARNING] Function not found: gdk_window_begin_draw_frame
[WARNING] Function not found: gdk_window_end_draw_frame

(Pipeline:10117): Gtk-CRITICAL **: gtk_icon_set_unref: assertion 'icon_set != NULL' failed

(Pipeline:10117): Gtk-CRITICAL **: gtk_icon_set_unref: assertion 'icon_set != NULL' failed

(Pipeline:10117): Gtk-CRITICAL **: gtk_icon_set_unref: assertion 'icon_set != NULL' failed

(Pipeline:10117): Gtk-CRITICAL **: gtk_widget_queue_draw_area: assertion 'width >= 0' failed
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

**Comment by Rombersoft** [comment]
Pay attention for this line:
```
Cairo.Context is leaking, programmer is missing a call to Dispose
```

**Comment by Jjagg** [comment]
@harry-cpp assuming this is fixed?

**Comment by harry-cpp** [comment]
Lets assume its fixed.
