### ISSUE TITLE
Content.Load<Effect> DirectoryNotFoundException

### ISSUE THREAD

**Issue by rejurime** [MonoGame/MonoGame#6673]
When I try to load an FX file in my project, I got the next exception:
```c#
Microsoft.Xna.Framework.Content.ContentLoadException: 'The content file was not found.'
DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Mito\Documents\GitHub\tgc-mg\bin\Debug\netcoreapp2.2\Content\Effects\Ambient.xnb'. 
```
I don't know why the generated path is ...\netcoreapp2.2\Content\Effects... when the Pipeline tool make the following structure:
![captura](https://user-images.githubusercontent.com/7131403/53539841-eb41d400-3af1-11e9-946b-80570360451b.PNG)
![anotacion 2019-02-28 001542](https://user-images.githubusercontent.com/7131403/53539843-ed0b9780-3af1-11e9-9a70-4883ad19b317.jpg)

#### What version of MonoGame does the bug occur on:

* MonoGame 3.7.1
* Nuget - MonoGame.Content.Builder 3.7.0.9
* Nuget - MonoGame.Framework.DesktopGL.Core 3.7.0.7

#### What operating system are you using:

* Windows 10

#### What MonoGame platform are you using:

* DesktopGL

**Comment by Apostolique** [comment]
Your folder is `Effect` but you're using `Effects` inside your game.

**Comment by rejurime** [comment]
I'm such a newbie, my bad :disappointed:.
Instead of looking for the simple, I started looking for the complex :disappointed_relieved:.

**Comment by Apostolique** [comment]
Yeah, this is a common mistake. It's so easy to overlook.
