### ISSUE TITLE
SpriteBatcher performance issue on 8000+ `SpriteBatch.Draw` per second

### ISSUE THREAD

**Issue by ryancheung** [MonoGame/MonoGame#6674]
<s>`SpriteBatcher` class has a member `private VertexPositionColorTexture[] _vertexArray;`. When draw count per seconds goes to 150000-20000 per second. That array member size get increased heavely, and then cause high latency GC on next batch draw.</s>

<s>This may be the reason my game's draw lag, which can go to 300ms, and 80ms on average draw.</s>

EDIT: This is not that reason cause lag. I must be something in other place.

And it becomes more worse if you enable AlphaTestEffect on most of the batch draw.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL and DirectX

**Comment by ryancheung** [comment]
The game is migrated from windows only game with SharpDX, and in SharpDX with DirectD39, there's absolutely no the performance issue.

**Comment by ryancheung** [comment]
BTW, Im making a game like LegendOfMir 
![52908300-24867280-32ae-11e9-9a3d-ccc251a2657f](https://user-images.githubusercontent.com/240899/53652957-14df3480-3c85-11e9-9745-c026e99c568b.jpg)

**Comment by nkast** [comment]
>> That array member size get increased heavely, and then cause high latency GC on next batch draw.

This happens only once though. It will effect only the few frames that happen to increase the size of  
_vertexArray and it's increases in chucks so it will not happen frequently. 

You don't by way create a new SpriteBatch on each frame?

**Comment by ryancheung** [comment]
No, I dont' create a new SpriteBatch on each frame, I only use on SpriteBatch instance in whole game loop.

I put a stop watch to monitor the game update latency. Like this:
```csharp
       public static String GetMetrics()
        {
            return String.Format("ClearCount:{0}, DrawCount:{1}, PixelShaderCount:{2}, VeterxShaderCount:{3}, PrimitiveCount:{4}, SpriteCount:{5}, TargetCount:{6}, TextureCount:{7}",
                _graphicDevice.Metrics.ClearCount,
                _graphicDevice.Metrics.DrawCount,
                _graphicDevice.Metrics.PixelShaderCount,
                _graphicDevice.Metrics.VertexShaderCount,
                _graphicDevice.Metrics.PrimitiveCount,
                _graphicDevice.Metrics.SpriteCount,
                _graphicDevice.Metrics.TargetCount,
                _graphicDevice.Metrics.TextureCount);
        }

        protected override void Draw(GameTime gameTime)
        {
            Stopwatch watch = Stopwatch.StartNew();

            RenderGame();

            Console.WriteLine("====FrameLogStart====");
            watch.Stop();
            double time = watch.Elapsed.TotalMilliseconds;
            if (time > 10)
                Console.WriteLine(String.Format("{0} - Slow update: {1}", DateTime.Now.ToLocalTime().ToLongTimeString(), time));

            Console.WriteLine(String.Format("Metrics: {0}", GetMetrics()));
            Console.WriteLine("====FrameLogEnd====");

            base.Draw(gameTime);
        }
```

And the result: https://pastebin.com/raw/XHBGuv6F

The log shows two points:
1. When the draw metrics became larger (almost double than previous frame) of the next frame, the frame become a slow update frame, its latency may goes to 150~300ms.
2. Sometime even the next draw metrics is the same as previous frame, the update latency may goes to 30+ms.

**Comment by ryancheung** [comment]
After some debug, the ` _vertexArray = new VertexPositionColorTexture[4 * numBatchItems];` is actually get call only when the batch size need to increase for new batch capacity.

**Comment by ryancheung** [comment]
Most of the frame update latency  in one second is below 10ms, but one to three frames latency may goes to 20ms~100ms+, the update latency is random. 
Appreciate for anyone can help.

**Comment by ryancheung** [comment]
I tried remove all my hack and use the original v3.7.1 MonoGame version, issues are still present. :'(

**Comment by ryancheung** [comment]
GC is pretty high: 
![csharp-high-gc](https://user-images.githubusercontent.com/240899/53677129-112fca00-3ce6-11e9-9dbe-de6ad998143d.PNG)

**Comment by ryancheung** [comment]
GC is pretty high: 
![csharp-high-gc](https://user-images.githubusercontent.com/240899/53677129-112fca00-3ce6-11e9-9dbe-de6ad998143d.PNG)


GC frequency is also high, every ~0.7s per GC

**Comment by ryancheung** [comment]
Here is an example game to test MonoGame's Graphic Performance https://github.com/ryancheung/MonoGamePerofrmanceTest

**Comment by ryancheung** [comment]
Here is the performance test result: https://pastebin.com/raw/Y6BtiDcW

**Comment by ryancheung** [comment]
@nkast 's fork https://github.com/nkast/MonoGame may fix this issue, I'll take a look.

**Comment by ryancheung** [comment]
Performance get increased without creating new `BlendState` object on every  frame draw. https://github.com/ryancheung/MonoGamePerofrmanceTest/commits/no-blendstate-create-and-destroy-on-every-frame-draw

**Comment by nkast** [comment]
Indeed, creating states is expensive. You need to cache those.

**Comment by ryancheung** [comment]
After more debug, yes it is, create new Objects on every frame draw is the main reason cause lag.

**Comment by ryancheung** [comment]
Issue resolved by: https://github.com/ryancheung/MonoGame/commit/a32497dbf61ee2ec0e056e11d38323e22ddbd9f6

I can be sure that lag is caused by creating new BlendState on every frame draw, BlendState instance is big, and then it cause heavy GC.

**Comment by ryancheung** [comment]
BTW, MonoGame should change the SpriteBatch API, let it only use one BlendState instance, which won't cause performance issue. Even without my hack, just use the original MonoGame version, this issue also cause when some game need to change multiple times of BlendState on every frame draw.
