### ISSUE TITLE
Game freeze when TargetElapsedTime is greater than MaxElapsedTime

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#6679]
If `TargetElapsedTime` is set to a value greater than `MaxElapsedTime` when `IsFixedUpdate` is true, the game will freeze due to it not being able to run any updates. Here's the piece of code causing this:

```
// Do not allow any update to take longer than our maximum.
if (_accumulatedElapsedTime > _maxElapsedTime)
    _accumulatedElapsedTime = _maxElapsedTime;

if (IsFixedTimeStep)
{
    _gameTime.ElapsedGameTime = TargetElapsedTime;
    var stepCount = 0;

    // Perform as many full fixed length time steps as we can.
    while (_accumulatedElapsedTime >= TargetElapsedTime && !_shouldExit)
    {
        _gameTime.TotalGameTime += TargetElapsedTime;
        _accumulatedElapsedTime -= TargetElapsedTime;
        ++stepCount;

        DoUpdate(_gameTime);
    }
```

As shown here, `_accumulatedElapsedTime` will be clamped by `_maxElapsedTime` and thus never update if `TargetElapsedTime` is greater. There is an exception thrown when setting `MaxElapsedTime` to a value less than `TargetElapsedTime`, but setting `TargetElapsedTime` does not check for `MaxElapsedTime`.

This can be resolved by either clamping `TargetElapsedTime` by `MaxElapsedTime` or throwing an exception when `TargetElapsedTime` is set to a higher value than `MaxElapsedTime`. I feel either solution is better than the game freezing (even if it is caused by the developer).

To replicate this, set `MaxElapsedTime` to a value, then set `TargetElapsedTime` to a greater value. Doing the reverse will not work since it throws the exception. `IsFixedTimeStep` must also be true.

#### What version of MonoGame does the bug occur on:
- Latest develop

#### What operating system are you using:
- Windows 10 64-bit

#### What MonoGame platform are you using:

- DesktopGL, Windows. This may affect all platforms

**Comment by tomspilman** [comment]
Would be good to know what XNA did in this case.. but it seems like the max elapsed time should win IMO.

**Comment by Jjagg** [comment]
> There is an exception thrown when setting MaxElapsedTime to a value less than TargetElapsedTime, but setting TargetElapsedTime does not check for MaxElapsedTime.

> This can be resolved by either clamping TargetElapsedTime by MaxElapsedTime or throwing an exception when TargetElapsedTime is set to a higher value than MaxElapsedTime.

TargetElapsedTime should be clamped by MaxElapsedTime. Throwing is annoying in cases like this where devs might want to change both values, but change the wrong one first causing an exception due to temporary incompatibility even though the final configuration wouldn't be invalid.

**Comment by SAJenkin** [comment]
I have submitted a pull request for this issue, its my first time contributing on github so please let me know if I did anything wrong or could have done something better.
