### ISSUE TITLE
Moving mouse down in full screen gets crazy results.

### ISSUE THREAD

**Issue by Tricky1975** [MonoGame/MonoGame#6684]
I am currently writing my own map editor using MonoGame for two reasons. 
a> To master MonoGame, and 
b> To preserve this map system as the programming language I originally wrote it in is hardly maintained anymore ;)
I've been creating my own lay-out and stuff in it all to get the utmost out of myself.

However during test runs (in both debug and release builds) something odd happens.
When I start up, the app runs full screen in 1920x1080 screen mode, but when I move the mouse down, I suddenly get back into my Windows screens, but my application doesn't close, however when I click the icon again on the task bar I get back into my editor but now in 720x576 screen mode. 

Now the source code can be found [here](https://github.com/TrickyGameTools/TeddyBear), but if you need specific parts of the code, just tell me.

#### What version of MonoGame does the bug occur on:
- All I can find in version check is: runtime version v4.0.30319

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
Not quite sure to understand what you are describing, it would be nice to have a minimal example exposing the problem. Right now it's hard to figure out if it's a MonoGame issue.

**Comment by Tricky1975** [comment]
I currently have my hands full, so writing a small sample will have to wait (I may have more time for that in a few days), but what it comes down to is, 
- I run a monogame program, in full screen.
- Screen is now in 1920x1080
- I move the mouse pointer to the bottom of the screen (by just using the mouse)
- Windows flashes back to its own Windows desktop screen
- I click the icon of the monogame program in question on my task bar
- Screen is now in 720x576 mode (a lot smaller)
- Moving mouse to bottom of the screen no causes any issues, but the screen is smaller.

It's not a super big issue (since I always make my work adapt for multiple screen sizes (and this issue proved that part of my code at least worked), but it is annoying, and I've never seen this before in other programming tools).

If still needed I'll set up a sample program, likely next weekend.

**Comment by mrhelmut** [comment]
I never encountered such an issue, hence the details request. I believe there's more to just MonoGame to this issue.

Note that if you are using borderless fullscreen mode, it is expected from MonoGame to set the resolution to match the desktop resolution when going fullscreen.

**Comment by Tricky1975** [comment]
~~~c#
            graphics.PreferredBackBufferWidth = GraphicsDevice.DisplayMode.Width;
            graphics.PreferredBackBufferHeight = GraphicsDevice.DisplayMode.Height;
            graphics.IsFullScreen = true;
            graphics.ApplyChanges();
~~~
This is the code I found by googling on how to go full screen, and I just copied it and didn't modify it.
Of course, it's possible the code is outdated due to newer versions, and I do not remember where I found this....

**Comment by tdeeb** [comment]
To get full screen working should require only setting `IsFullScreen` to true; the back buffer width and height are not essential. Also check if setting GraphicsDeviceManager's `HardwareModeSwitch` to false helps fix the issue.

**Comment by Tricky1975** [comment]
Okay, I modified my code into this:
~~~c#
            //graphics.PreferredBackBufferWidth = GraphicsDevice.DisplayMode.Width;
            //graphics.PreferredBackBufferHeight = GraphicsDevice.DisplayMode.Height;
            graphics.HardwareModeSwitch = false;
            graphics.IsFullScreen = true;
            graphics.ApplyChanges();
~~~
And yes that appears to solve the issue, that a lot, @tdeeb ;)
