### ISSUE TITLE
Game loop capped to 45 FPS when game form not in focus

### ISSUE THREAD

**Issue by RendijsSmukulis** [MonoGame/MonoGame#6696]
The issue described is present in 3.7.1 and 3.8 latest dev build, and _not_ present in 3.7.0

After the MonoGame window loses focus (e.g. when I alt-tab to another window), the draw calls seem to be capped at around 45 FPS. 

Here's a FPS report from running an empty MonoGame project with VSync disabled:

```
FPS: 46.43, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 45.87, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 45.15, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 45.13, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 45.44, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 45.38, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 45.56, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 877.65, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 3950.02, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 3912.83, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 3930.43, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 3934.43, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 3866.05, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 3553.79, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 47.41, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 47.30, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 47.35, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
FPS: 47.20, VTrace on: False, Fixed timestep on:False, requested timestep: 2ms
```

The log starts off with the windowed game being in the foreground (~45 fps), I then switch to the game window (fps jumps to ~3900), and then switch to another app (fps drops back to 45). 

However, the issue is there when VSync is on and fixed timestep is on as well, but the drop is less dramatic, from 60fps to 45fps.

#### Repro steps ####

- Create a new project
- Add some way to measure FPS, e.g.
```
            this.frameCount++;
            if (this.stopWatch.ElapsedMilliseconds > 2500)
            {
                Debug.WriteLine($"FPS: {(double)this.frameCount * 1000 / this.stopWatch.ElapsedMilliseconds:F2}, " +
                                $"VTrace on: {this.graphics.SynchronizeWithVerticalRetrace}, " +
                                $"Fixed timestep on:{this.IsFixedTimeStep}, " +
                                $"requested timestep: {this.TargetElapsedTime.TotalMilliseconds}ms");

                this.stopWatch.Restart();
                this.frameCount = 0;
            }
```
- Run the game
- Observe the higher FPS
- Alt-tab to some other window
- Note the FPS drop.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1+

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:
- WindowsDX

**Comment by mrhelmut** [comment]
This is the expected behavior. When inactive, MonoGame sleeps for 20ms each update, hence the under 50 FPS.

If you want to tweak this behavior, you can change the waiting time through ```Game.InactiveSleepTime``` and set it to 0 if you'd like to to fully disable it (the actual threshold for disabling it is < 1ms).

Also note that, beyond this parameter, Windows 10 resource management may cook its own thing here and throttle your program no matter what MonoGame does.
