### ISSUE TITLE
Content Pipeline Tool should remember window size and sidebar width

### ISSUE THREAD

**Issue by AidanMcK** [MonoGame/MonoGame#6698]
The Content Pipeline Tool should remember the last window size and the width of the side panel - its a pain having to resize it each time.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by harry-cpp** [comment]
Duplicate of #6430
