### ISSUE TITLE
MonoGame.Android template missing AndroidManifest

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#6702]
When creating a new Monogame android project an error occurs because the AndroidManifest is missing.

This is not included with the standard project templates and causes errors on loading.

Ideally a default one should be included that the user can tailor, instead of causing confusion on load.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- Android

**Comment by Simon-Miller** [comment]
I'm totally with you, pal!

I've come across this too, and figured out the difference between a working and failing project.
If anyone reading is hitting the same issue and needs a work-around, then this is it:
In your Android project's "Properties" folder, there is a file called "AssemblyInfo.cs".  But there's a missing file called "AndroidManifest.xml".

Here's one I prepared earlier:
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="SpriteBatchTest.SpriteBatchTexturesDemo" android:versionCode="1" android:versionName="1.0">
	<uses-sdk android:targetSdkVersion="25" />
	<application android:label="AndroidTest3" android:icon="@drawable/Icon"></application>
</manifest>`

You'll probably want to change the names, such as "AndroidTest3", and "SpriteBatchTest.SpriteBatchTexturesDemo" - to whatever your project is.

Hope this helps.

**Comment by SimonDarksideJ** [comment]
I found it's possible (at least in 2017) to look at the properties of the Android project, click on the "Manifest" tab and there was a "regenerate" option if the manifest was missing or invalid.
That worked for me, it's just not well documented from what I could tell.

**Comment by Jjagg** [comment]
Fixed when we redid templates for dotnet templating engine.
