### ISSUE TITLE
[DesktopGL] OggStreamer doesn't get disposed after application is closed

### ISSUE THREAD

**Issue by AimedNuu** [MonoGame/MonoGame#6706]
* Create DesktopGL project on Windows. Debug or Release, doesn't matter.
* Start application and close it short after by pressing the X.
* Observe application hanging. Pause studio -> OggStreamer.EnsureBuffersFilled() is executing Thread.Sleep in a Worker Thread and preventing application from closing. Somehow OggStreamer.Dispose() never gets called and cancelled boolean never gets set to break the thread from blocking.

- MonoGame 3.7.1.189
- Windows
- DesktopGL

**Comment by tdeeb** [comment]
I'm not able to reproduce this. Does this require playing `Songs`? Are you able to provide a simple project reproducing the issue?

**Comment by AimedNuu** [comment]
No, I didn't play anything. In fact, I don't have any audio assets at this point. I'll provide an example project.

**Comment by AimedNuu** [comment]
> I'm not able to reproduce this. Does this require playing `Songs`? Are you able to provide a simple project reproducing the issue?
