### ISSUE TITLE
MonoGame 3.7.1 not working on Visual Studio Community 2017

### ISSUE THREAD

**Issue by ChalkX** [MonoGame/MonoGame#6711]
Hi all. I can't seem to get MonoGame 3.7.1 to work on Visual Studio Community 2017. Whenever I add a project, whether it's Shared Code, Windows, or Cross-Platform, the project adds successfully, then Visual Studio stops responding. When I close VS with my task manager and open the project again (either the .sln or the .csproj file), Visual Studio opens the project then immediately stops responding. Am I missing something obvious or is there an issue here?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Windows 10 64-bit

#### What MonoGame platform are you using:
- DesktopGL/WindowsDX

**Comment by SaculRennorb** [comment]
From my experience Win10 tends to be missing a lot of 'default' drivers / dlls etc, which you would expect to be there. I know its not very helpfull but for my installation it works fine. You might want to check out #6580 tho, a lot of the requred runtimes are listed there and there is talk about some required stuff missing 'even on Windows 10'.

**Comment by Jjagg** [comment]
Nothing extra needs to be installed to open at least DesktopGL and WindowsDX projects in visual studio. I haven't seen this reported before. Maybe it's an issue with the VS installation.

**Comment by mrhelmut** [comment]
You might want to try disabling every extensions or add-ons before trying to open a project. When VS doesn't start, it's almost always linked to a third party thing failing.

**Comment by mrhelmut** [comment]
You might want to try disabling every extensions or add-ons before trying to open a project. When VS doesn't start, it's almost always linked to a third party thing failing.

**Comment by Jjagg** [comment]
Gonna close this, because I'm pretty sure this isn't an issue with MG.
