### ISSUE TITLE
Pipeline Tool build infinitely long (in Debug Mode)

### ISSUE THREAD

**Issue by griseus** [MonoGame/MonoGame#6717]
Hello Monogame Community,

I think the pipeline tool is broken for Ubuntu. I try to build the following mgcb

```
#----------------------------- Global Properties ----------------------------#

/outputDir:bin
/intermediateDir:obj
/platform:Windows
/config:
/profile:Reach
/compress:False

#-------------------------------- References --------------------------------#


#---------------------------------- Content ---------------------------------#

#begin Bilder/Wallpapers/alpen.jpg
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:Bilder/Wallpapers/alpen.jpg
```

If i start the pipeline tool, it will run infinitely long. However, I can cancel the process, but no output was generated. I also run the pipeline tool in debug mode and from the console, but there is no stack trace or anything I can work with.

Maybe it's relevant: I added a custom Pipeline dll into the references in another session (mgcb). But this should not affect this file I think?

- MonoGame 3.7.1
- Ubuntu
- DesktopGL

**Comment by griseus** [comment]
Update: Strange, on my other Ubuntu machine the pipeline works like a charm. I will look into this, and let you know if I find the reason for this behaviour.

**Comment by griseus** [comment]
I succeeded in reproducing the bug. And you wont believe me, but it's only happening if I'm in debug mode. So this is just a minor problem, but maybe worth looking into.

**Comment by cra0zy** [comment]
> only happening if I'm in debug mode.

When the Pipeline Tool is in debug mode, it waits for a debugger to get attached before it continues building. You need to attach the debugger to `localhost:55555`

**Comment by Jjagg** [comment]
@cra0zy Maybe the Pipeline tool could display that information somewhere while waiting?

**Comment by cra0zy** [comment]
> @cra0zy Maybe the Pipeline tool could display that information somewhere while waiting?

It does in the text output, the filter output could be updated tho.
