### ISSUE TITLE
TextureProcessor overwrites existing mipmaps.

### ISSUE THREAD

**Issue by nkast** [MonoGame/MonoGame#6720]
I have a Processor to generate a sprite atlas that overrides TextureProcessor and generates mipmaps for individual sprites to avoid Color bleeding between sprites.

As soon as I call base.Process(), it will overwrite/replace my mipmaps.
This is different than what XNA does. As a workaround I had to do this in MG:

```
            if (MipmapsPerSprite && GenerateMipmaps)
            {
                GenerateMipmaps = false;
                base.Process(output, context);
                GenerateMipmaps = true;
            }
            else
            {
                base.Process(output, context);
            }
```

Here is the code of my Processor:
https://github.com/tainicom/Aether.Extras/blob/22a7bb37db141a297302f4f91db698a7b2e98469/Content.Pipeline/AtlasImporter/Processors/TextureAtlasProcessor.cs

That's the line in TextureProcessor that generates Mipmaps.
It should call GenerateMipmaps(bool overwriteExistingMipmaps) with false.
https://github.com/MonoGame/MonoGame/blob/6f34eb393aa0ac005888d74c5c4c6ab5615fdc8c/MonoGame.Framework.Content.Pipeline/Processors/TextureProcessor.cs#L64

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7 & 3.8-Develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Any

**Comment by tomspilman** [comment]
>  it will overwrite/replace my mipmaps.

Yeah it shouldn't be replacing existing mipmaps... it should assume mipmaps that exits already are correct and what was intended to be used.

**Comment by nkast** [comment]
Should I push a PR to change `GenerateMipmaps(true)` to `GenerateMipmaps(false)` and see how this goes?

**Comment by tomspilman** [comment]
I don't know the details to say how the implementation should be.

I do know we don't want to break existing processing for textures without mipmaps.

If the results for textures with mipmaps is a little different than before i think that is acceptable.

Also we would want to be sure we have a test case.  A DDS with different colors in each mip level is a good way to test that they are being passed thru and not modified.

**Comment by Halofreak1990** [comment]
Am I missing something, here? Looking at the linked code of the TextureProcessor, it only calls GenerateMipmaps with true when the GenerateMipmaps property is also true. The code is somewhat weird, though, as it should probably pass the GenerateMipmaps property as a parameter to that function, instead.
