### ISSUE TITLE
TextInputEventArgs should be made available in all platforms

### ISSUE THREAD

**Issue by Apostolique** [MonoGame/MonoGame#6721]
Right now, the TextInputEventArgs isn't available in platforms like Android. The conditional is set here:
https://github.com/MonoGame/MonoGame/blob/develop/Build/Projects/MonoGame.Framework.definition#L300

Making the API different in different platforms makes it much harder to develop cross-platform libraries for MonoGame.

There are also some conditionals here:
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/GameWindow.cs#L92

Those should be exposed in all platforms even if they aren't used behind the scenes.

**Comment by Apostolique** [comment]
Looks like this will get fixed with this pull request: #6712

**Comment by Jjagg** [comment]
Fixed with new project structure. TextInputEventArgs is shared for all runtimes.

**Comment by Apostolique** [comment]
This should be reopened. There's still a conditional that prevents TextInput from being available on all platforms:

https://github.com/MonoGame/MonoGame/blob/7dc8aa037d88c650a3551f89c8e8103a21ec8f5e/MonoGame.Framework/GameWindow.cs#L131-L156

This means that accessing `Windows.TextInput` in a library for example would crash on the user side in platforms like Android.
