### ISSUE TITLE
Feature DirectoryInfo slash FileInfo helper class.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#6725]
This is a suggestion to add a Helper class that is crossplatform to perform basic querys for files and folders.

Some possible examples:

FileExists( string filePath)
GetFileNameWithoutExtension(...)
GetFileNameWithExtension(...)
DirectoryExists(...)
GetDocumentsFolder()
GetCurrentAppDomainDirectory();

ect...

**Comment by Halofreak1990** [comment]
Correct me if I'm wrong, but aren't `GetFileNameWithoutExtension` and `GetFileNameWithExtension` already provided by the Path class, and cross-platform?

**Comment by willmotil** [comment]
Well its part of system which should work the same way everywhere but from what i have been reading there are some platforms were some calls in the same classes don't work in a standard way or might not work at all on some platforms. 

here is one example but it seems there are others here and there.
http://community.monogame.net/t/solved-get-all-files-in-the-content-directory/8213

Im not sure what the extent is to it maybe these calls should be tested first on all the platforms i just can't do it myself because i don't have access to all of them. I was just about to use file.exists and was remembering some posts i read about directory and file class problems on different platforms.

**Comment by tdeeb** [comment]
At least in my experience on Windows, macOS, and Linux, I've found the `Path` fields/methods (`Path.Combine`, `Path.DirectorySeparatorChar`, etc.) to be very consistent. I can't vouch for `System.Environment.GetFolderPath`, but considering it takes in special folders that non-Windows OSes may not have, I wouldn't expect it to work across all platforms.

**Comment by Jjagg** [comment]
.NET handles these pretty well. I don't think MG should take responsibility for these methods, so I'm closing this.

**Comment by willmotil** [comment]
well i suppose your right.
