### ISSUE TITLE
Andoid refusing to load PNG in Texture2D

### ISSUE THREAD

**Issue by Simon-Miller** [MonoGame/MonoGame#6727]
Issue 651 sounds like the same problem, but that ticket was closed.
I'm using MonoGame 3.7.1.189 (NuGet package).

I get the following error:
System.InvalidOperationException: This image format is not supported occurred

Let me explain a little deeper.

`
using (var mem = new MemoryStream(rawPng))
            {
                this.texture1 = Texture2D.FromStream(this.GraphicsDevice, mem);
            }
`
I've tried to isolate the issue as much as possible, to the point where I've a byte[] in source code, and are trying to load that.  In fact, I've multiple files in source!  There's one I call "Ordained by God", because it is blessed with the power to load and work!  Yes, a PNG that loads!

All the other PNGs I have are variations.  I've tried saving a PNG from Cosmigo's Promotion (the working file, and also failing files) as well as loading the failing PNG into GIMP, and re-saving as a PNG again.  I've tried re-saving as a 24bit file too.  I've even resorted to try saving the PNG from Microsoft Paint, - and they ALL generate PNGs that work in Windows, but under Android, they all refuse to load, except the one ordained by God.  (Bub and Bob from BubbleBobble, as it happens).

Lastly, out of desperation, I also tried generating a 300k byte[] that's a BMP file, not PNG.
I thought that might work - but it didn't. 

I'm happy to share my isolated project.
[SpriteBatchTexturesDemo.zip](https://github.com/MonoGame/MonoGame/files/3136019/SpriteBatchTexturesDemo.zip)

Pretty please, I'd love to get to the bottom of this one.
Is there something I need to know, or are missing?

at the top of the Game1.cs file I've a region:

`
 #region data to convert back into a byte[] to load into a Texture2d.
`

In which you can comment out the binaries you are not concerned with.
Note that the first one ("bub n bob") actually works!

We're trying to establish why the others don't.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1.189

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- Android

**Comment by tdeeb** [comment]
Unfortunately I can't run your Android project since I don't have the tools installed, but can you find out which format it thinks your data is?

**Comment by Simon-Miller** [comment]
`{System.InvalidOperationException: This image format is not supported ---> System.InvalidOperationException: unknown image type
  at MonoGame.Utilities.ImageReader.Read (System.IO.Stream stream, System.Int32& x, System.Int32& y, System.Int32& comp, System.Int32 req_comp) [0x00092] in <14285e7be6444bda94a4048e3cb68e5b>:0 
  at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformFromStream (Microsoft.Xna.Framework.Graphics.GraphicsDevice graphicsDevice, System.IO.Stream stream) [0x00000] in <14285e7be6444bda94a4048e3cb68e5b>:0 
  at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream (Microsoft.Xna.Framework.Graphics.GraphicsDevice graphicsDevice, System.IO.Stream stream) [0x0001c] in <14285e7be6444bda94a4048e3cb68e5b>:0 
   --- End of inner exception stack trace ---
  at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream (Microsoft.Xna.Framework.Graphics.GraphicsDevice graphicsDevice, System.IO.Stream stream) [0x00032] in <14285e7be6444bda94a4048e3cb68e5b>:0 
  at SpriteBatchTexturesDemo.Game1.LoadContent () [0x00011] in C:\Users\Simon Miller\Documents\Visual Studio 2017\Projects\MonoGameTest1\SpriteBatchTexturesDemo\Game1.cs:83 }`

That's all it says.  No inner exception.  No exception data.

Is there a better way to extract error information?  All I could do to get this, was to wrap the failing code in a try/catch block, because all the output to the output[debug] window says is `System.InvalidOperationException: This image format is not supported
`

**Comment by tdeeb** [comment]
Is it possible for you to test this on a debug build from MonoGame source?

**Comment by rds1983** [comment]
Hi,
Can you share original PNGs that refuse to load?
I've tried to extract it from the provided code by adding following line into LoadContent:
```c#
File.WriteAllBytes("d:\\temp\\test.png", rawPng);
```

However, `d:\temp\test.png` can't be opened in the MSPaint.

**Comment by Simon-Miller** [comment]
That's interesting.  If I take the byte stream, and write it out, they do work.  But regardless, here's the originals, as you asked.  You might notice I like white boxes around each sprite.  I've a tool that I've made (and used for years) that cuts out all the sprites by findind all the boxes.  I call is "Sprite Catcher".  It creates a collection of rectangles that are the sprites to be cut from the graphic.  I think you can see where this is going.  the PNG is added into a single file along with the rectangles, and a header of its own. So the PNG is never processed in any way from the original file.  
I've a binary importer for the content pipeline, and therefore at runtime need to extract the PNG which serves as a sprite sheet.  I want to load that into a Texture2D.  So to focus on the issue, I came up with the previously attached code that isolates the data (which works if I run a Monogame Windows Direct X project.  But not Android.  

So back to the images, here they are.


![BubnBob](https://user-images.githubusercontent.com/43334205/57176008-bbdd7980-6e4a-11e9-96a6-a57eb556f8d7.png)


![C64Font](https://user-images.githubusercontent.com/43334205/57176042-f9da9d80-6e4a-11e9-9102-75031a178557.png)

**Comment by rds1983** [comment]
Hi,
I've made a small MG android project that loads and renders first image. Image is stored as android asset and loaded using following code:
```c#
			using (var stream = TitleContainer.OpenStream("image.png"))
			{
				_texture = Texture2D.FromStream(GraphicsDevice, stream);
			}
```
It runs fine for me:
![image](https://user-images.githubusercontent.com/1057289/57176357-4d67de00-6e81-11e9-9bb8-f47e3f76cf0b.png)

I am attaching the project. It is required to have latest MG installed to open it:
[MGAndroidGame.zip](https://github.com/MonoGame/MonoGame/files/3144153/MGAndroidGame.zip)

btw, what is your development environment? Mine is win7x64, vs2017.

**Comment by Simon-Miller** [comment]
Yeah, this is exactly the kind of result I get.
it's the C64 Font that won't load.  That's why I described the different methods I attempted, believing it may just be something to do with how a particular application saves a PNG that Andriod might not be happy about.  Again, this is why I refer to Bub and Bob as ordained by God!  They somehow seems to be blessed with a magic PNG that works on Android.

**Comment by rds1983** [comment]
I've tried 2nd image and it works as well:
![image](https://user-images.githubusercontent.com/1057289/57184169-656f4a00-6ee1-11e9-97d1-51d4ce86aeaa.png)

**Comment by Simon-Miller** [comment]
Just to close the door a little on "magic png's" - I've added both to the Content pipeline, and used Content.Load<Texture2D>("name"); Both appear on screen in this way.  But this defeats the purpose of what I'm trying to do by loading a PNG with actual data.  
As you've seen for yourself, Bub n Bob load up, but it's a mystery as to why the other png (C64 Font) won't.  That's the bug I'm reporting.

**Comment by Simon-Miller** [comment]
Interesting that you've got a stream from an Android Asset - I've tried your code, and get the same result.  So I've tried going a step further, and read the data into a byte[].  (for the C64 font).
I've made a memory stream from it, and tried loading the texture from that, since it most closely resembles what's going on in my project, and interestingly, it is working.

I'm going to extract the byte stream and turn it back into source (again).
I'll then compare the binaries - there should not be any difference.  If there is, then the fault is with me.  I'll keep you informed.  Thanks for your thoughts and efforts.  Very much appreciated.

**Comment by Simon-Miller** [comment]
Calling it a night, I think. - I'm confused.
The byte[] from my sprite loading routine is an exact match to the byte[] extracted from the Android Asset.

Hence, I can load the image, as desired! 
What's killing me now, is what happens from that point.
Before I go into that, I'll just say that I dont understand why I've got different data than yesterday.
The byte[] of 1881 bytes doesn't match any of my revious attempts that I've saved.  It's likely I didn't keep the original, and instead over-written it, which might explain why my data is different.
But I wouldn't have opened a ticket if I hadn't already struggled for a few evenings trying to get my code working.
Again, shared code - that works in an MG Windows deskop project, but not on Android.
Yet here I am proving to myself, as you also have - that the image can load into a Texture2D.

I'm hesitant to want to say we should close this ticket, given the issues I had.  Given the project posted definitely didn't work, and they should all be valid PNG files in the source.

It certainly feels like it's leaning towards bad data in the source - but I can't explain how that could be the case.  I'll sleep on it.

**Comment by Simon-Miller** [comment]
ok, happy to close this ticket.  False alarm!
However, I do have a genuine problem with Texture2D. 
Perhaps move the following to another thread, if you can confirm the issue?

As we've discovered, we can indeed load a PNG file using a byte[] as source.
We both can confirm that the images appear on an Android.  In your case, via emulation, and in my case, with my phone physically attached with USB.

But the part missing from loading a texture in this way, is that with the MG Content Pipeline, you get to choose a transparent colour, and it will automatically turn that colour within the PNG to transparent.

I, on the other hand, after loading the C64Font png, need to iterate over the pixels and set the designated pixel colour as transparent.  My code works fine in Windows (I'm sounding like a broken record) but not with Android.

In fact, I don't even need to manipulate any pixels at all.  Just the act of copying the data from the texture is enough to kill it.
I isolated it down to just pulling a texture from the content pipeline.


`
protected override void LoadContent()
        {
            this.texture1 = Content.Load<Texture2D>("BubnBob");
            this.texture2 = Content.Load<Texture2D>("C64Font");

            // let's fudge up the texture now.  All I have to do, is read its data!
            var colorData = new Color[texture2.Height * texture2.Width];
            this.texture2.GetData<Color>(colorData);

            // now try drawing texture2.  it won't appear!
        }
`

If you comment out the line 'this.texture2.GetData<Color>(colorData);', and try displaying both textures, they'll both appear on screen.

Obviously, to manipulate the texture, I need to pull out its Color[ ] data.
This seems like enough to kill the source texture.

Is there something I'm missing here, or have I found the real bug?  You can see why I thought it was the texture failing to load though, because I see nothing on screen, and don't get an error. 

Please confirm.

**Comment by rds1983** [comment]
#6506

**Comment by Jjagg** [comment]
Okay, closing this for #6506. Thanks for the research guys!
