### ISSUE TITLE
Exposing the DrawInstancedPrimitives() instance base index

### ISSUE THREAD

**Issue by YTN0** [MonoGame/MonoGame#6732]
Does anyone have any objections to exposing (as an optional parameter) the instance base index in the call:

`DrawInstancedPrimitives(PrimitiveType primitiveType, int baseVertex, int startIndex, int primitiveCount, int instanceCount)`

Currently the instance base index is hardcoded to 0 inside of the private method `PlatformDrawInstancedPrimitives.`

My proposal is to modify DrawInstancedPrimitives to have the following signature:

`DrawInstancedPrimitives(PrimitiveType primitiveType, int baseVertex, int startIndex, int primitiveCount, int instanceCount, int instanceIndex = 0)`

This will preserve existing usage and behavior but allow you to optionally set a different base index for the instances.

Reason being is that I have a circular buffer of instance data and I want to draw different sections of it without having to also have separate and multiple SetData calls. With this change I can set the data once and have separate draw calls drawing from different sections of the set instance data.

#### What version of MonoGame does the bug occur on:
- All

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL, WindowsDX

**Comment by willmotil** [comment]
Yes.

The question is though is why was it hardcoded to zero was that just done because in a hurry then forgotten ? or was it done for a reason ?

**Comment by YTN0** [comment]
@willmotil  FYI, the hardcoded 0 base was only on the DirectX side of things. I am not sure the original reasoning.... but based on what I learnt from making the code changes, I would speculate that it's because the DirectX API allowed you to set a base instance index, but OpenGL had a separate API for that, and that API is only available from 4.2 and above.

Because earlier versions of the API didn't support setting the base instance index, it was probably simpler to just hardcode it to 0 for DirectX.
