### ISSUE TITLE
Xbox One Wireless Controller is not detected as gamepad on OSX

### ISSUE THREAD

**Issue by luizribeiro** [MonoGame/MonoGame#6736]
I've been trying to get my Xbox One Wireless controller (`030000005e040000fd02000003090000`, according to SDL2 Gamepad Tool) to work with Monogame.

Monogame does not seem to find the Gamepad, as `GamePad.GetCapabilities(PlayerIndex.One).IsConnected` always returns `false`. I'm currently using the controller through Bluetooth. The controller works fine on Steam.

I did notice that the controller is detected as a joystick by Monogame. However, the identifier of the joystick shows up as `0000045e-0000-0000-fd02-000000000000` on Monogame if read `Joystick.GetCapabilities(0).Identifier`, which strikes as a bit odd to me.

Any idea what's up?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.7

#### What operating system are you using:
- macOS 10.14.5

#### What MonoGame platform are you using:

- DesktopGL

**Comment by luizribeiro** [comment]
I was able to get around this and make the controller work.

Copying my own `libSDL2-2.0.0.dylib` from SDL 2.0.9 over the `libSDL2-2.dylib` that is MonoGame's Nuget distribution fixed it for me.

Is there any way to prioritize using a local DLL so I don't have to replace the DLL myself?

**Comment by harry-cpp** [comment]
SDL on develop is 2.0.10 so this should be fixed.

There is a way, you'd just have to add a action post MG .targets action for .NET Framework, not the most elegant of solutions tho.
