### ISSUE TITLE
SpriteFont Proposed change to cut out the middle man.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#6745]
Currently sprite font has 2 ways to get at the glyphs and both are round about functionally or optimally.

GetGlyphs() which returns a dictionary but its useless unless you cache that or you will get tons of garbage. 

Caching it isn't a real option because spriteBatch drawString can't use your cached dictionary.
SpriteFont is also sealed so you can't just encapsulate it if you want to add functionality to your own custom methods. 

Then 

There is glyphs[] which is readonly and thats fine but whats not fine is that it is an array instead of a dictionary which is like ok... now you can direct access it, but its now the Wrong Type.

With a fat ugly slow method to search for a glyph actually being in the array that is executed in the inner loop of each drawstring. Instead of a dictionary and direct access to it.

Further this call is not accessible **internal int GetGlyphIndexOrDefault(char c)** which sort of makes getting a array even more pointless because the user can't use pointers to access the underlying calls himself from his project. In order to duplicate any speed mitigation the pointer method might give to make up for not having a dictionary.

So in other words whats going on fundamentally is two different ideas are in play and both have the opposite problem and both are basically just acting as middle men (frustration) to what really should be the correct answer to getting at the glyphs.

**public dictionary glyphs;** // or even read only doesn't matter

**what is needed is glyphs to be a dictionary and direct access to it** 

(read the very bottom for why its both a speed hit and flexibility problem for extending functionality the way it is now.)

but.. since its not 
and changing it now **would break it**.

I would like to make the suggestion that one of the two non breaking changes be made to the spritefont class or the better breaking change be made.

**1)** (the superior breaking change) 
Make glyphs a public dictionary and readonly if necessary, 
set it in the constructor using GetGlyphs() 
removing that huge ugly indexing method that checks for a key.
replacing it with containsKey.
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/SpriteFont.cs#L263 
this would effect all the lines from 263 to 314 essentially removing all but  a couple of them and replacing code in the method GetGlyphOrIndex(char c)
with something like akin to this.

```
                if (glyphs.ContainsKey(c))
                    currentGlyph = glyphs[c];
                else
                if (!tsf.DefaultCharacter.HasValue)
                    throw new ArgumentException("Text Contains a Unresolvable Character: "+c.ToString("x"));
                else
                    currentGlyph = defaultGlyph;
```

in the constructor glyphs = GetGlyphs();  at the end to set it;
in the class declaration as Dictionary<char, Glyph>glyphs; // readonly if requisite

**2)** (the inferior change)
Same as the above but make it a addition to the class. leaving the list in also. Then the same steps as discussed above just name it something else.  glyphsDictionary or something.
Thats double the memory for the glyphs struct as it's two copys, still better then the list.
You can still eliminate all that indexing code.
... i would never use the list version given the choice it is inferior and can cause real slow downs when writing a lot of text and it gets much worse as the font size increases comparatively.

**3)** (the semi inferior or possibly the most inferior change) 
unmark the spritefont class as a final class.
public class SpriteFont{ 
.
This option could be slightly better then (2) as one can possibly just new over the class. Essentially mock it up on load to do (1) in roundabout way im not 100% this is possible though. 
Or 
You can encapsulate spritefont and wrap the load method and every font that comes in as well as include the additional required dictionary. This is a lot of work that will need repeated in each project and then monogame wont really be changed for it. This will only work on a users custom methods but at least it wont roadblock you at every turn.

Its always been a annoyance every time i write a method or mess with anything that has to do with text and the spritefont class. Well today i was streamlining old methods so i don't have to cache and found it is basically impossible to get around this without deoptimizing spritebatch or caching via a wrapper... and a wrapper wouldn't be the right thing to do. Encapsulating it would be but the damn class is marked final probably for like a .01% speed boost. Which won't mean anything at all if i have to use a array and search that array were i should have a way to directly search a dictionary in the spritefont.

Just in case anyone doesn't get what im saying, a huge font with thousands of characters having to search in a loop that draws those characters on each iteration a character array with thousands of indices takes a shitload longer then just a few hops thru a dictionary and the more characters the worse the situation gets its basically a n^2 situation - random * n  vs a dictionary which is basically linear like a  log(n) or something basically some linear value * n in time basically its way way less looping the bigger the character array gets.

**Comment by Jjagg** [comment]
#5874 made the change from dictionary to regions + arrays and binary search. It is actually **a lot** faster. Please do some benchmarks to back up your claims.

It is unclear to me what you want to address exactly with your suggestions. You talk about extending SpriteFont functionality in user code, but also using SpriteBatch.DrawString (which is just for SpriteFont). I don't see the problem with getting a dictionary from SpriteFont once and keeping it around. Either way how fonts are represented internally should not matter to end users. 

Regarding your last paragraph, dictionary lookups are constant time, so O(1) (assuming no collisions) while the region/array method is O(log(#regions)) due to binary search for a region, however typically the number of regions is very small and big O just tells you how things scale, not how performant they are. Just look at the benchmark in #5874, it shows that while regions doesn't scale as well as a dictionary, it takes a looot of regions to get performance below that of a dictionary.

**Comment by willmotil** [comment]
Great but that method is marked internal.

1) if someone is accessing the glyphs they are most likely making a function to do something that spritebatch.DrawString wont do.
2) With a dictionary they still need to call ContainsKey() 
So if that function you wrote is comparable fine but with a list, 
They wont be using that function because it is marked internal.

So now you just guided the user down a path to write his own indexing search function. 

If he decides to use the array, so he doesn't have to copy glyph data out using GetGlyphs (which of course has the pitfall of generating garbage unless you cache it) then.

He can't access the Function you wrote because its internal. 
He can't use ContainsKey() on a array.
If he then decides to use GetGlyphs() then what was the point of adding glyphs as a array ?

What is he going to do well by this time lets hope he didn't start with the dictionary cause then hes going to goto the array then he might just write his own regular loop which will be brute force probably.
Or he has to make his own fork of monogame to access it internally.
Which at this point is probably the best choice.

I mean a 1% speed boost internally is fine but whats the cost here?

This is a path out there for people to follow that leads them to write there own equivalent of ContainsKey on a array which is a god awful idea they can't access what your accessing externally with pointers. 

You need to remember that not everyone is forking monogame. 
Expecting every user to do so is also a terrible idea.

I just don't see how this is a good idea ideologically.

btw

I don't see what Regions have to do with anything after they get imported in, Regions aren't special at all they are just used by xna and mono game. Is so you can specify a chunk of offsets to grab out of a ttf that are defined so you don't have to remember the numbers. https://unicode-table.com/en/blocks/control-character/

You realize that its possible to have like however many regions there are in the first 64 k character set and that is just for A single character not The unicode 4 byte high low surrogate range. 

Besides that isn't what that those test show at all and the fact that regions had a noticable effect just goes to show what dictionary has been refined to deal with over a long period of time.
Its about the actual code value of the characters and how well the spacial algorithm handles wacky ass distributions you can have.  You would have to do tons and tons of tests to prove much with all sorts of distributions of characters over the the entire 64 k plane one or two limited tests isn't really convincing.

**Comment by willmotil** [comment]
Here sure maybe this isn't the best example as this is based off a precomputed function but say i was just word wrapping on letters i wouldn't need to insert and then i might do something like this at runtime.
Actually i could probably use this at runtime as it is.

```
using System;
using System.Text;
using System.Collections.Generic;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace BetterTextBounder
{
    public static class TextWrapping
    {
        private static string newline = Environment.NewLine;
        private static MgStringBuilder text = new MgStringBuilder();
        private static Dictionary<int, SpriteFontItem> spriteFonts = new Dictionary<int, SpriteFontItem>();
        private static SpriteFontItem lastSpriteFontItem;
        private static int lastHashCode = -1;

        private class SpriteFontItem
        {
            public SpriteFont tsf;
            public Dictionary<char, SpriteFont.Glyph> _glyphs;
            public SpriteFont.Glyph defaultGlyph;
            public char defaultfontchar = ' ';
            public float Spacing = 0f;
            public int LineSpacing = 10;
            public string newline = Environment.NewLine;


            public void SetSpriteFont(SpriteFont s)
            {
                tsf = s;
                _glyphs = tsf.GetGlyphs();
                defaultGlyph = new SpriteFont.Glyph();
                Spacing = tsf.Spacing;
                LineSpacing = tsf.LineSpacing;
                if (tsf.DefaultCharacter.HasValue)
                {
                    defaultfontchar = (char)(tsf.DefaultCharacter.Value);
                    defaultGlyph = _glyphs[defaultfontchar];
                }
            }

            public static SpriteFontItem PrepFont(SpriteFont sf)
            {
                var hcode = sf.GetHashCode();
                if (hcode != lastHashCode)
                {
                    if (spriteFonts.ContainsKey(hcode) == false)
                    {
                        SpriteFontItem nval = new SpriteFontItem();
                        nval.SetSpriteFont(sf);
                        spriteFonts.Add(hcode, nval);
                    }
                    lastSpriteFontItem = spriteFonts[hcode];
                }
                return lastSpriteFontItem;
            }
        }

        /// <summary>
        /// This is the primary working method the others only will generate garbage during runtime.
        /// That may or may not be a problem depending on if you are just pre-calculating.
        /// </summary>
        public static void WordWrapTextWithinBounds(SpriteBatch sb, SpriteFont sf, MgStringBuilder stringText, Vector2 scale, Rectangle boundRect, Color color)
        {
            var sfc = SpriteFontItem.PrepFont(sf);
            text.Clear();
            text.Append(stringText);
            var _glyphs = sfc._glyphs;
            var Spacing = sfc.Spacing;
            var lineHeight = sfc.LineSpacing * scale.Y;
            Vector2 offset = Vector2.Zero;
            float yextent = offset.Y + lineHeight;
            Vector2 redrawOffset = Vector2.Zero;
            Rectangle dest = new Rectangle();
            var currentGlyph = SpriteFont.Glyph.Empty;
            var firstGlyphOfLine = true;

            int lastWordBreakCharPos = 0;
            bool firstwordonline = true;
            Vector2 rewindOffset = Vector2.Zero;

            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];

                if (c == '\r')
                    continue;
                if (c == '\n')
                {
                    offset.X = 0;
                    offset.Y += lineHeight;
                    yextent = offset.Y + lineHeight;
                    firstGlyphOfLine = true;
                    firstwordonline = true;
                    continue;
                }

                if (_glyphs.ContainsKey(c))
                    currentGlyph = _glyphs[c];
                else
                if (! sfc.tsf.DefaultCharacter.HasValue)
                    throw new ArgumentException("Text Contains a Unresolvable Character");
                else
                    currentGlyph = sfc.defaultGlyph;

                // Solves the problem- the first character on a line with a negative left side bearing.
                if (firstGlyphOfLine)
                {
                    offset.X = Math.Max(currentGlyph.LeftSideBearing, 0);
                    firstGlyphOfLine = false;
                }
                else
                    offset.X += Spacing + currentGlyph.LeftSideBearing;

                // matrix calculations unrolled rotation is excluded for this version
                var m = offset;
                m.X += currentGlyph.Cropping.X;
                m.Y += currentGlyph.Cropping.Y;

                dest = new Rectangle(
                    (int)(m.X * scale.X),
                    (int)(m.Y * scale.Y),
                    (int)(currentGlyph.BoundsInTexture.Width * scale.X),
                    (int)(currentGlyph.BoundsInTexture.Height * scale.Y)
                    );

                // Begin word wrapping operations.
                // if char is a word break character e.g. white space
                if (c == ' ')
                {
                    lastWordBreakCharPos = i;
                    rewindOffset = offset;
                    if (firstwordonline)
                        firstwordonline = false;
                }
                // word wrapping calculations.
                if (yextent >= boundRect.Height)
                {
                    // this essentially is function termination due to height boundry
                    text.Length = i;
                    i = text.Length;
                }
                else
                {
                    if (dest.Right > boundRect.Width)
                    {
                        if (text.Length > (i + 1))
                        {
                            if (firstwordonline == false)
                            {
                                if (text[lastWordBreakCharPos + 1] != '\n')
                                {
                                    // i also pulled the +1 here which is i think inserting a improperly positioned like break using append at.
                                    text.AppendAt(lastWordBreakCharPos + 1, '\n'); // !!!  insert here is a gcollection problem... fixed
                                    if (text[lastWordBreakCharPos + 1] != ' ')
                                    {
                                        offset = rewindOffset;
                                        i = lastWordBreakCharPos;
                                    }
                                }
                            }
                            else // first word on the line true
                            {
                                if (text[i + 1] != '\n') // if its not already a new line char
                                {
                                    text.AppendAt(i + 1, '\n'); // !!!  insert here is a gcollection problem... fixed
                                }
                            }
                        }
                    }
                }
                offset.X += currentGlyph.Width + currentGlyph.RightSideBearing;
            }
            sb.DrawString(sfc.tsf ,text, boundRect.Location.ToVector2(), color);
        }
    }
}
```

**Comment by Jjagg** [comment]
You're right that the GetGlyphIndex method needs to be public for the array to be useful. We just never planned to expose the glyphs array, it was done in a bigger pull request and we missed it.
IMO we should either remove the glyph array accessor or actually make it useful so users can benefit from its speed boost. We can do that by exposing the GetGlyphIndex method and providing a way to enumerate characters (expose the regions or provide an enumerator).

Regarding the dictionary, I don't see what the issue is in your example.
