### ISSUE TITLE
GL ClearOptions.Target on a RenderTarget, Ignores Clear Color RGB values but not Alpha.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#6750]
* Do not see another issue for this, it maybe a recent bug.
* Win 10 new Video Card max Caps
* DesktopGL  (i did not test for this on dx or other platforms it may exist there or not)
* Occured using a nightly build from a few days ago. This bug was observed in relation to a separate bug i was testing for.
* image attached at the bottom.

ClearOptions.Target on a RenderTarget, Ignores Clear Color RGB values but not the Alpha Component. The clear color RGB portion of the clear color is hardcoded to Black 0,0,0,

**Amendment**  
the **Green Blue** components of the color **are ignored** the **Red and Alpha** components **are applied**.

The test was run using a rendertarget and a vertice primitive model the render target was drawn using spritebatch. Under the following basic procedure to observe the behavior.

The rendertarget can be seen under this test as i increase the alpha to the maximum to turn the render target drawn area black. While the alpha for the clear color varys at no time is green ever added.
```

        int displace = 0;

        /// <summary>
        /// This is called when the game should draw itself.
        /// </summary>
        /// <param name="gameTime">Provides a snapshot of timing values.</param>
        protected override void Draw(GameTime gameTime)
        {
            // motion variable to visibly ensure the clear is occuring.
            displace += 1;
            if (displace > 255)
                displace = 0;

            // set the render target
            GraphicsDevice.SetRenderTarget(renderTarget);
            // clear the render target to green
            GraphicsDevice.Clear(ClearOptions.Target, new Color(0,255,0, displace), 1f, 0); // target is ignoring clear color ... and is hard coded to black.

            // draw to the render target first with spritebatch.
            DrawSpriteBatchItem();
            // draw to the render target next with a vertice primitive.
            sphere.Draw(GraphicsDevice, triangleEffect);

            // set the backbuffer
            GraphicsDevice.SetRenderTarget(null);
            // clear the backbuffer to blue
            GraphicsDevice.Clear(Color.CornflowerBlue);

            // draw the render target to almost the whole screen.
            // we leave a space at the right and bottom to see the back buffer color underneath the rendertarget drawn.
            DrawRenderTargetWithSpriteBatch();


            base.Draw(gameTime);
        }

        public void DrawSpriteBatchItem()
        {
            spriteBatch.Begin();
            spriteBatch.Draw(BasicTextures.grid, new Rectangle(displace *2, 0, 100, 100), Color.Red);
            spriteBatch.End();
        }
        public void DrawRenderTargetWithSpriteBatch()
        {
            spriteBatch.Begin();
            spriteBatch.Draw(renderTarget, new Rectangle(0, 0, GraphicsDevice.Viewport.Width -100, GraphicsDevice.Viewport.Height -100), Color.Red);
            spriteBatch.End();
        }
```

The visual output.

![RtClearApiBugTest](https://user-images.githubusercontent.com/7495196/58570477-0d88e200-8206-11e9-9609-779f7d8815fc.png)

**Comment by nkast** [comment]
why are you drawing the rendertarget with Red tint?
 `spriteBatch.Draw(renderTarget, new Rectangle(0, 0, GraphicsDevice.Viewport.Width -100, GraphicsDevice.Viewport.Height -100), Color.Red);`

**Comment by willmotil** [comment]
Ah i was having a weird bug in my other project and was testing i copy pasted some of the code over.
Ill withdraw the issue.
