### ISSUE TITLE
MGCB.exe exited with code -1

### ISSUE THREAD

**Issue by Lautenschlager-id** [MonoGame/MonoGame#6751]
Spent a few hours of the day trying to fix something, but I can't really find the problem

My console says
```
The command ""C:\Program Files\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /quiet /platform:DesktopGL /@:"C:\Users\Lautenschlager\Desktop\x\x\Content\Content.mgcb" /outputDir:"bin\DesktopGL\Content" /intermediateDir:"obj\DesktopGL\Content"" exited with code -1.
```
when I try to build/run the game (i just created the folder, nothing was written there yet)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Windows 7 x86

#### What MonoGame platform are you using:
- DesktopGL

**Comment by Jjagg** [comment]
If you open the .mgcb file with the Pipeline Tool and try to build you'll get a better error message.

**Comment by Lautenschlager-id** [comment]
> If you open the .mgcb file with the Pipeline Tool and try to build you'll get a better error message.

Oh ok, will do!
---
![image](https://user-images.githubusercontent.com/26045253/58641309-58236080-82d1-11e9-8ff8-217d40e38137.png)
Just in case, I changed the logs to Diagnostic to see where it is. That's it :thinking:

**Comment by Lautenschlager-id** [comment]
@Jjagg 
Where am I supposed to see the logs? I just rebuilt the project and nothing has appeared there
![image](https://user-images.githubusercontent.com/26045253/58641931-966d4f80-82d2-11e9-833a-03fb65ecfbde.png)

**Comment by tdeeb** [comment]
The Build Output window should be showing information. Click **View > Build Output** and make sure everything is checked, then try building again.

**Comment by Lautenschlager-id** [comment]
See, nothing happens when I build it. I tried building in the project also.. nothing.
https://i.gyazo.com/57cad4bacf2190f25c961ffcd6d4d66c.mp4

It's all checked (even tho gyazo didn't captured it :thinking:)

**Comment by tdeeb** [comment]
I noticed that your first comment shows you're running MGCB with the `/quiet` flag. Can you check if the executable (with default installation, found in `C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools`) is being run with the flag?

**Comment by Jjagg** [comment]
When running MGCB as a build step with the .targets file used in MG templates it uses the quiet flag.

**Comment by Lautenschlager-id** [comment]
Ouch, found the problem. Thanks tde
![image](https://user-images.githubusercontent.com/26045253/59046413-58cf7000-8858-11e9-8271-6b92c583b093.png)

However I have the 32 bits version of monogame. :thinking: What now?

**Comment by Jjagg** [comment]
MonoGame runs on 32-bit, but the Pipeline tool does not :/
 Win32 is just the name of the windows API, it's not really related to bitness.

**Comment by Lautenschlager-id** [comment]
Oooh... :| Duh

Is there any way that I could build the content as in XNA so it can work on this machine?

**Comment by cra0zy** [comment]
The content building does not work from a 32 bit machine, however once the content is built it can be loaded from a 32 bit machine.

Closing as this is not an issue.

**Comment by nablabla** [comment]
hi, i seem to have the same issue, i am not on a 32bit machine thou.
i get no output whatsoever from the tool

**Comment by frpeters** [comment]
Same problem here, can't start any project and I'm in a 64 bit machine.

**Comment by johanolofsson** [comment]
Got this problem when I missed to include the .config folder in my repo. Worked fine on the machine where it was created but not on others that pulled the repo due to the .config folder being .gitignored.
