### ISSUE TITLE
SpriteBatch artifacts when drawing 500+ sprites

### ISSUE THREAD

**Issue by Nalsmoth** [MonoGame/MonoGame#6752]
I noticed that when I queue 500 or more sprites with a single Begin() / End() block in a SpriteBatch that the very last sprite appears to be drawn with incorrect texture coordinates.  See the attached screenshot; both grassy squares ought to be identical, but bottom-right corner of the 2nd sprite appears corrupted.

![corrupt](https://user-images.githubusercontent.com/19171532/58717951-07277100-8392-11e9-8d73-7abdb1ea0e85.png)

When drawing more than 500 sprites, only the last quad appears to be affected. In other words, if I queue up 525 sprites, only # 524 has issues. The size of the sprite doesn't seem to matter. I can work around the problem by calling End() early and restarting the batch, but that might not be an option for users who are using the sorting feature.

The problem is easily reproduced in a brand new project.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by tdeeb** [comment]
Can you provide a simple project replicating the issue?

**Comment by Nalsmoth** [comment]
This project demonstrates the issue. It draws 500 identical 32x32 sprites, and the last one is corrupted / has artifacts.
[sprite500.zip](https://github.com/MonoGame/MonoGame/files/3242390/sprite500.zip)

**Comment by tdeeb** [comment]
I downloaded and ran the project, and I'm not seeing this issue on my machine. This is what I see:
https://imgur.com/a/ELVQv4O

**Comment by Nalsmoth** [comment]
@tdeeb Your output looks the same as mine except for the last sprite. I've been working on a Dell Optiplex 745 running Windows 10 (ancient, I know). It's an old Intel processor without a dedicated graphics card.

I will try it on a different machine when I get home tonight.

**Comment by Nalsmoth** [comment]
@tdeeb I've confirmed that the issue does not occur on my other (more modern) machine at home. It could just be a driver issue. Sorry for wasting your time if that's the case.

**Comment by Jjagg** [comment]
Oof, yes that's very old. I'm gonna close this as a driver issue. Thanks for looking into it @tdeeb and @Nalsmoth :)
