### ISSUE TITLE
Linux/SDL: IsKeyDown() is reporting in a key repeat pattern, not like on Windows

### ISSUE THREAD

**Issue by soulblaze1** [MonoGame/MonoGame#6758]
When I check IsKeyDown() I get a sporadic report of keypresses which doesn't work as it does in XNA/Windows. What you get is something like you'd expect while writing in Word if you hold a key down, where the key event fires are coming in a line of text being typed slowly every so often. But we don't want that of course.

This issue is still present, basically: http://community.monogame.net/t/iskeydown-is-not-working-on-linux/9308

I tried the fix here but I can't figure out how to update the .dylib's in my game folder, it didn't work for me: http://community.monogame.net/t/iskeydown-is-not-working-on-linux/9308/7

Ubuntu 16.04 TLS 64-bit
MonoGame 3.6.0.1625
DesktopGL

It's annoying but I found a cool workaround: just poll the key states independently and less often, and it can function quite well, not as responsive but workable and without jitteriness:

>				//player input
>				isAdownTimer = new System.Timers.Timer();
>				isAdownTimer.Interval = 90;
>				isAdownTimer.Elapsed += (sender, e) => { _isAdown = false; };
>				isAdownTimer.Start();
>
>			        System.Timers.Timer isAdownTimer;
>			        bool _isAdown;
>
in Update()
>			        if(Keys.A.down()) { _isAdown = true; isAdownTimer.Stop(); isAdownTimer.Start(); }
>
>			        if(_isAdown)
>				{
>			        //...

**Comment by tdeeb** [comment]
This is a problem with an older version of SDL that has been fixed in develop. Is it possible for you to test on the latest?

**Comment by cra0zy** [comment]
Gonna close this as its fixed in 3.7.1 I believe.
