### ISSUE TITLE
Make MG not dependent on VS version.

### ISSUE THREAD

**Issue by VictorRabotko** [MonoGame/MonoGame#6764]
Is it possible to Make MG not dependent on the Visual Studio version? 

A new VS 2019 is out. And MG templates are missing for vs2019. Again. Same has happened when a vs2015 and vs2010 was out.

Is it possible to create an online visual studio extension template and publish it to marketplace.visualstudio.com ? It can solve the main problem: when new Visual Studio is out no need to wait for the next MonoGame release, it just needs to upgrade the online visual studio extension template to get support new VS/

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL, WindowsDX, WindowsUWP, Android

**Comment by Jjagg** [comment]
Yeah, that would be nice.

**Comment by ironpower** [comment]
The best choice i think, his to have in the monogame folder all the template directely, And we must just copy them in the visual studio x version,

**Comment by willmotil** [comment]
One little thing with that is that there are quite a few versions so the path needs to stored for each i don't mean vs 2015 2017 2019 there is community, pro ect... if i remember right the template folder paths  weren't always the same.

**Comment by Jjagg** [comment]
@willmotip Visual Studio extensions don't have this issue. They are the solution for us.

**Comment by harry-cpp** [comment]
We are moving away from the installer, and to a simple, just install mg templates extension and everything will work approach, so gonna close this as there are other issues tracking it.
