### ISSUE TITLE
VB project creation error.

### ISSUE THREAD

**Issue by tclancey** [MonoGame/MonoGame#6767]
Just installed the Visual Studio development branch from the website, install goes fine.  Selected 2017 as that's what I have and all looks good.  I can create new projects in C# easily, but get an error with VB.

The project file
'C\Users\Me\AppData\Local\Temp\iocuhrt1.vr4\Temp\MonoGame Windows 10 Universal Project1\vbproj' cannot be opened.

There is a missing project subtype.
Subtype: '[A5A43C5b-DE2A-4C0C-9213-0A381AF9435A]' is unsupported by this installation.

Can you please send me/post a link to a working file?  I really, really want to get this up and running, I have legacy VB code I need to work with, I am not converting to C#.

Many thanks.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
We no longer have VB templates. Adding them is tracked in #4127.
