### ISSUE TITLE
Replace nant scripts with CAKE scripts

### ISSUE THREAD

**Issue by harry-cpp** [MonoGame/MonoGame#6773]
CAKE is literally made with C# project compilation in mind, as such its much easier to call stuff like `dotnet restore` or `msbuild pack` without having to worry if you properly setuped the location of where the stuff is found on each platform.

CAKE scripts are just C# scripts with some predefined methods, any C# function can be called from them because of this. Its also much easier to read the build script logic as its just C# code.

https://cakebuild.net

CC. @tomspilman @Jjagg @dellis1972 @KonajuGames

**Comment by Jjagg** [comment]
IMO the biggest benefit is that Cake can be installed as a .NET Core global tool: 
- global tools doc page: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools
- Cake tool nuget: https://www.nuget.org/packages/Cake.Tool/

So it's easy to run the build scripts anywhere.
Installation is as simple as running `dotnet tool install -g Cake.Tool`.

**Comment by cra0zy** [comment]
Actually CAKE is self contained, it will automatically download itself from the build scripts and place itself into tools folder. You literally just need to have C# runtime installed.

**Comment by hazevich** [comment]
@Jjagg you don't even need `dotnet tool` just run it through powershell and it will install relevant packages itself

**Comment by tomspilman** [comment]
I'm good with all this... NANT is ancient.

As long as the new script breaks up the build in a similar way to how we had it in NANT we can fix up the build server to use it instead.

I assume i will have to install a Cake binary on the build box to make this work or find a Cake Runner for TeamCity.

**Comment by Jjagg** [comment]
Cake can be installed by running the bootstrap scripts that are included already or by installing it as a dotnet global tool:

Run the bootstrap scripts (downloads CAKE and runs the build script):
```
./build.sh # Unix
build.ps1 # Windows
```

dotnet global tool:
```
$ dotnet tool install -g Cake.Tool
$ dotnet cake
```

**Comment by cra0zy** [comment]
> I assume i will have to install a Cake binary on the build box to make this work or find a Cake Runner for TeamCity.

No need, just make it run the bootstrap script.

**Comment by cra0zy** [comment]
We do need build bot C# stuff updated tho for the new projects.

**Comment by tomspilman** [comment]
@cra0zy  @Jjagg @mrhelmut 

So how should we proceed with this?

I don't want to break the automated build for weeks... but we need a way to test automated builds using Cake.

Any ideas?

**Comment by cra0zy** [comment]
We could create a PR that fully drops Protobuild and Nant, than once its ready we move to build bot fixes to properly execute script / pick up artifacts.

**Comment by tomspilman** [comment]
Yeah i don't see a way to have the build bot support both Nant and Cake at once.  We just have to switch over once the Cake script is working.

As long as it has to same basic breakup into targets for:

 - Build Windows stuff.
 - Build Mac stuff.
 - Run Windows tests.
 - Run Mac tests.
 - Do doc generation.
 - Build Windows installers and stuff .
 - Build Mac and Linux installers and stuff.
 - NuGet building/packaging.
 - NuGet publishing.

We seperate build from test and from installers/packaging here so that we can skip steps if the builds fail.  As long as we keep that core concept it should be easy to swap in a Cake script kickoff.

**Comment by harry-cpp** [comment]
This has been done, so closing.
