### ISSUE TITLE
[Question/Proposal] Make DiscardColor writable.

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#6803]
Is there any reason ( other than the bug patch here: https://github.com/MonoGame/MonoGame/pull/2124 ) because DiscardColor is different in Debug/Release?

I'm usually working with the Release version but I had to switch back to Debug for some GPU leaks I'm searching and some of my RTs became 'purple-tinted'. Right now when using MG in Debug mode and Release mode may give different results because of that patch. Personally I think both versions should give always the same results, but that's just a personal preference.

Anyways, I think that if there's no ulterior motive DiscardColor should be writable. Right now to get the same results on Debug/Release I have to either:
* clear the render target myself to black with an #ifdef DEBUG (which is ugly considering that MG should be multiplatform, yet doesn't get the same results even with a debug/release change)
* clear the RT to black without the ifdef (clearing twice, losing performance)
* use PreserveContents and clear always (dangerous and prone to errors)

making DiscardColor writable to your desired clear color would result in cleaner code and performant.

**Comment by tomspilman** [comment]
> DiscardColor is different in Debug/Release?

This is a debug feature that existed since XNA.  The reason for it was to make it easier to detect if you accidently didn't clear a buffer by seeing a purple color.  We use black in release as a performance optimization.

We could make it writable, but it should default to the current colors.
