### ISSUE TITLE
MonoGame Default Android App Not Resuming

### ISSUE THREAD

**Issue by matx2** [MonoGame/MonoGame#6804]
The out-of-the-box default MonoGame Android app - which just gives you a cornflower blue screen - cannot be resumed after exiting it with the back arrow. It just flashes for an instant and exits immediately. The app has to be manually killed and then cold started to make it work - but resuming doesn't work.

Every time I try to resume the app, this is what's logged to the debug output:

07-02 20:31:39.984 D/ViewRootImpl@da8bb5cActivity1: mHardwareRenderer.destroy()#1
07-02 20:31:39.992 D/ViewRootImpl@da8bb5cActivity1: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
07-02 20:31:40.008 D/SensorManager(26166): registerListener :: 0, 66667, 0,
07-02 20:31:40.029 D/SurfaceView(26166): Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x7 surface={Surface(name=null)/@0x6fe473a isValid=true -2030430208}
07-02 20:31:40.054 D/ViewRootImpl@da8bb5cActivity1: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x7 surface={isValid=true -2028197888} surfaceGenerationChanged=true
07-02 20:31:40.054 D/ViewRootImpl@da8bb5cActivity1: mHardwareRenderer.initialize() mSurface={isValid=true -2028197888} hwInitialized=true
07-02 20:31:40.062 D/MonoGame(26166): GraphicsDeviceManager.ResetClientBounds: newClientBounds={X:0 Y:40 Width:720 Height:1200}
07-02 20:31:40.064 D/ViewRootImpl@da8bb5cActivity1: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
07-02 20:31:40.064 D/ViewRootImpl@da8bb5cActivity1: MSG_WINDOW_FOCUS_CHANGED 1
07-02 20:31:40.065 D/ViewRootImpl@da8bb5cActivity1: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -2028197888}
07-02 20:31:40.065 V/InputMethodManager(26166): Starting input: tba=android.view.inputmethod.EditorInfo@72c43ea nm : BlindFindAndroid.BlindFindAndroid ic=null
07-02 20:31:40.065 I/InputMethodManager(26166): startInputInner - mService.startInputOrWindowGainedFocus
07-02 20:31:40.069 D/InputTransport(26166): Input channel constructed: fd=71
07-02 20:31:40.213 D/ViewRootImpl@da8bb5cActivity1: MSG_RESIZED: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
07-02 20:31:40.218 D/SensorManager(26166): unregisterListener ::
07-02 20:31:40.226 I/AudioTrack(26166): Skip ramp
07-02 20:31:40.257 D/SurfaceView(26166): Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x5 surface={Surface(name=null)/@0x6fe473a isValid=false 0}
07-02 20:31:40.317 D/ViewRootImpl@da8bb5cActivity1: mHardwareRenderer.destroy()#1
07-02 20:31:40.345 D/ViewRootImpl@da8bb5cActivity1: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
07-02 20:31:40.347 D/ViewRootImpl@da8bb5cActivity1: MSG_WINDOW_FOCUS_CHANGED 0
07-02 20:31:40.374 D/InputTransport(26166): Input channel destroyed: fd=71

This issue has originally been brought up here, where you can find a workaround for it as well:
http://community.monogame.net/t/monogame-android-app-not-resuming/11693

The default app should just work flawlessly at the press of a button.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1.189

#### What operating system are you using:
- Windows + Visual Studio 2017

#### What MonoGame platform are you using:

- Android, 7.1 Nougat with USB debugging on a Samsung Galaxy J5
- On the emulator as well: Android_Accelerated_x86_Oreo, 8.1 API 27

**Comment by Jjagg** [comment]
This is fixed in #6739. Please try a development build! We'll push out another release when we finish .NET Core migration.
