### ISSUE TITLE
Color.TransparentBlack

### ISSUE THREAD

**Issue by nkast** [MonoGame/MonoGame#6805]
XNA 3.0 had two transparent values,  TransparentBlack & TransparentWhite. When XNA 4.0 switch to use premultiplied colors by default, they drop both properties and replaced them with Color.Transparent. 

MG still defines Color.TransparentBlack which has the same value as Color.Transparent. 
I propose to mark TransparentBlack as 'Obsolete' for now and then remove it on a later version.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7,.1 3.8 (dev)

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX, WindowsUWP, Android

**Comment by willmotil** [comment]
Just to point out that will be a breaking change for anyone using transparenblack.
I always pick transparent black :(

Fun fact in xna 3.0 there was a bug i found were you could use transparent white to see the desktop thru the game window.

**Comment by Jjagg** [comment]
That's why the current transparent colors will stay, but be marked as obsolete.

I would accept a PR for this :)

**Comment by RUSshy** [comment]
> Just to point out that will be a breaking change for anyone using transparenblack.

Then they'll fix their code, there is no reason to keep that kind of stuff just to please lazy developers

Existing games will still work since everyone ship their own DLL, if they update, they fix, simple

That makes everything bloated, no reason to have to fields with same value but different name, it causes confusions

**Comment by Halofreak1990** [comment]
I'm with @RUSshy. Also, wasn't the goal of Monogame to eventually match XNA 4.0? If so, why are we keeping 3.x compat around?
