### ISSUE TITLE
英国大学文凭办理www.diplomaclub.net

### ISSUE THREAD

**Issue by hrye8rghzsdf** [MonoGame/MonoGame#6808]
#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL
英国大学文凭办理[www.diplomaclub.net](www.diplomaclub.net)办理英国大学文凭

**Comment by Jjagg** [comment]
@tomspilman Can you delete this? Only MG owners can delete issues.

**Comment by tomspilman** [comment]
Don't see any way to delete the post...  all i can do is edit it.

Also blocked the user for 30 days and reported it to GitHub.

**Comment by Jjagg** [comment]
Ah, deleting issues needs to be explicitly enabled: https://help.github.com/en/articles/allowing-people-to-delete-issues-in-your-organization
