### ISSUE TITLE
Drop macOS-specific DesktopGL platform

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#6811]
The macOS project is identical to DesktopGL, but it has a working VideoPlayer implementation specifically for Mac. If we add a cross-platform VideoPlayer to DesktopGL (#3983) we can drop the macOS project. Considering building the project requires a Mac, dropping the project would be very convenient.

**Comment by mrhelmut** [comment]
I agree. It's also misleading to have 2 targets for the same thing.

**Comment by Jjagg** [comment]
Closing this because the Mac specific project is gone. Still don't have a video player for DGL though.
