### ISSUE TITLE
OpenALSoundController doesn't clear available sources that were paused during their lifetime

### ISSUE THREAD

**Issue by Owlzy** [MonoGame/MonoGame#6814]
It seems that any looping SoundEffectInstances that have been paused at any point, after being stopped, will never be cleared from the list availableSourcesCollection in OpenALSoundController.cs , causing a InstancePlayLimitException after some time.  I managed to reduce it down to a test case, if you comment out the pausing it will no longer crash.  This means we are unable to pause sound effect instances. 

```
public void AudioLeakTest()
        {
            if (loop1 != null)
            {
                loop1.Stop(true);
                loop1.Dispose();
                loop1 = null;
            }

            if (loop2 != null)
            {
                loop2.Stop(true);
                loop2.Dispose();
                loop2 = null;
            }

            if (stop)
            {
                return;
            }

            loop1 = Audio.PlaySound("sfx_boulder_launch_00", true);
            loop1.Pause();
            loop1.Play();

            loop2 = Audio.PlaySound("sfx_boulder_launch_00", true);
            loop2.Pause();
            loop2.Play();

            Utils.Delay(0.5f, () =>
            {

                if (loop1 != null)
                {
                    loop1.Stop(true);
                    loop1.Dispose();
                    loop1 = null;
                }

                if (loop2 != null)
                {
                    loop2.Stop(true);
                    loop2.Dispose();
                    loop2 = null;
                }

                loop1 = Audio.PlaySound("sfx_boulder_launch_00", true);
                loop1.Pause();
                loop1.Play();

                loop2 = Audio.PlaySound("sfx_boulder_launch_00", true);
                loop2.Pause();
                loop2.Play();

                Utils.Delay(0.5f, () =>
                {
                    AudioLeakTest();
                });
            });

        }
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows, Android, iOS

#### What MonoGame platform are you using:
- DesktopGL, Android, iOS

**Comment by tdeeb** [comment]
The problem looks to be in [`PlatformPlay`](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Audio/SoundEffectInstance.OpenAL.cs#L107). It reserves a new source even if the existing one is in use when paused.

**Comment by Owlzy** [comment]
Awesome, thanks for helping track that down.  I added this condition and its no longer crashing. Does this look okay to you?  If so I can put in a PR.

```
if(SoundState != SoundState.Paused)
{
    SourceId = 0;
    HasSourceId = false;
    SourceId = controller.ReserveSource();
    HasSourceId = true;
}
```

**Comment by Jjagg** [comment]
I think we should let [SoundEffectInstance.Play()](https://github.com/MonoGame/MonoGame/blob/3e223ada704c8fbbe4f38613f456c515c20394fb/MonoGame.Framework/Audio/SoundEffectInstance.cs#L141) call Resume if the instance is paused.

**Comment by Owlzy** [comment]
just to confirm @Jjagg I tested your fix and it works, thanks!

**Comment by Ellpeck** [comment]
This issue also seems to occur when trying to play a `SoundEffectInstance` again after it has ended (for example, by checking if the state is `Stopped`), as long as it's not explicitly stopped using the `Stop` method before playing it again. This seems to occur because of the same reason that @tdeep described.
