### ISSUE TITLE
MSBuild properties to build DesktopGL for a specific platform

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#6819]
This is a proposal to simplify publishing for DesktopGL.

When building a DesktopGL game, dependencies for Mac, Linux and Windows are included. It would be nice to have MSBuild properties that users can set to remove native dependencies except for the target platform. E.g. the following properties: `MGTargetWin64`, `MGTargetWin32`, `MGTargetMac`, `MGTargetLinux64`, `MGTargetLinux32`, `MGTargetWin` and `MGTargetLinux` (last two to include both 32- and 64-bit).

When publishing with dotnet CLI we can check the RID (runtime identifier, e.g. win-x64) to figure out what dependencies are necessary.  

cc @cra0zy @mrhelmut

**Comment by mrhelmut** [comment]
I think it would be best to ship Linux and Windows as ```AnyCPU``` so that they work in both 32 and 64bit contexts with one single package. I guess that all we need is a switch to tell if the target is Windows, macOS, or Linux.

Side note: dotnet core has a requirement of El Capitan 10.11 on macOS, which is a 64bit OS only (since 10.9), so it should be pretty safe to just scrap 32bit support from all mac builds and dependencies (MonoKickstart too since it requires 10.9).

**Comment by cra0zy** [comment]
> When publishing with dotnet CLI we can check the RID (runtime identifier, e.g. win-x64) to figure out what dependencies are necessary.

I'm already doing that for the most part xD. The only thing I left is to check if the current compilation target is normal .NET Framework, and only in that case to execute the following targets file: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/MonoGame.Framework.DesktopGL.targets

.NET Core will take the proper win-x64 folder deps that are included in the nuget, for example.

**Comment by Jjagg** [comment]
Oh, that's cool. I didn't know that :)

**Comment by Jjagg** [comment]
Bit of an issue here. We can't directly have deps in `runtime/<rid>/native` get copied to a subfolder of the output folder because they subfolders get flattened. See dotnet/cli#9794.
Suggested workaround is to create a package with native deps, which seems overkill for this. Maybe we should just rename the libs to disambiguate version of different bitness, e.g. rename SDL2.dll to SDL2_64.dll and SDL2_32.dll for the respective targets. Then they could exist in the root output folder together.

**Comment by cra0zy** [comment]
When publishing there are separate RIDs for win-x64 and win-x86.

**Comment by Jjagg** [comment]
I missed that we load the library at the output root in case loading in x64/x86 fails.

**Comment by Jjagg** [comment]
We merged #6852, so this is fixed for .NET Core. If you specify an RID only required libs are copied over. 

Should we add these options for .NET Framework? I think it would be pretty easy to do, by putting conditions on the copy operations in the DesktopGL.targets file.

**Comment by cra0zy** [comment]
Nah, you only get cool stuff with .NET Core :P

**Comment by Jjagg** [comment]
The thing is if you use a DesktopGL build for Windows, you'll want to target .NET Framework 4.5 or something. So it would be nice for consistency when publishing. I'm gonna try and implement this.

**Comment by Jjagg** [comment]
I came up with the following system and wrote the implementation in MSBuild:
Users can set the following boolean properties:

- MGTargetWin
- MGTargetWin86
- MGTargetWin64
- MGTargetLinux
- MGTargetOSX

If any of those are set, only the libs for platforms that have their property set to true are copied.

Additionally I added the following flags that only do something when none of the above flags have been set:
- MGTargetCurrentOS: copy libs for the current OS; for Windows copies both x86 and x64
- MGTargetCurrentOSPlatform: same, but for Windows only copies x86 or x64 if you don't build for AnyCPU

If none of the flags are set, libs for all platforms are copied over.

- Do we need the last two? Are they useful? I added them, assuming people often compile from the target OS. If they do, they can set either of those properties in their csproj and don't have to worry about it. 
- Are the names good?
 
cc @mrhelmut @cra0zy for feedback

**Comment by cra0zy** [comment]
How about:
```
<MGNativeLibs>win-x86;win-x64;linux-x64<MGNativeLibs>
```

**Comment by Jjagg** [comment]
We could also only support Windows and push to use .NET Core on Mac/Linux. I don't think there's any good reason to still use Mono, is there? 

@cra0zy I'm fine with that approach as well.

**Comment by cra0zy** [comment]
> We could also only support Windows and push to use .NET Core on Mac/Linux. I don't think there's any good reason to still use Mono, is there?

Don't do that, there is no point in not supporting mono.

**Comment by Jjagg** [comment]
Just to clarify, I meant we could only support these properties on Windows.

**Comment by Jjagg** [comment]
Since this is not an issue in .NET Core and NETFX is getting phased out, I'm not gonna pursue this further.
