### ISSUE TITLE
Joystick.GetState generates lots of garbage

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#6820]
[`Joystick.GetState`](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Input/Joystick.SDL.cs#L78) allocates new arrays for each `JoystickState`, which can lead to lots of garbage over time considering input is usually obtained multiple times a frame for controllers. I can think of a few options for improving this:
* Add a cached default state that is simply returned when we need to return a [default JoystickState](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Input/Joystick.SDL.cs#L80). This avoids allocating multiple zero-length arrays.
* Add some type of garbage-less overload that takes in user-defined arrays to fill the information with. The user can get the `JoystickCapabilities` first to see how many axes, buttons, and hats the joystick has - the existing code already does this, as a matter of fact. One thing to consider would be how to cleanly present this API.

#### What version of MonoGame does the bug occur on:
- Develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by nkast** [comment]
>> Add a cached default state that is simply returned when we need to return a default JoystickState. This avoids allocating multiple zero-length arrays.

We have done the same thing for TouchPanelState #2902

>> Add some type of garbage-less overload that takes in user-defined arrays 
Here's [another idea](https://github.com/MonoGame/MonoGame/issues/2876#issuecomment-51115871). 
As a matter of fact I had implemented a garbage free touch collection for use in Windows phone and I am still using the same code on Android. It uses a fixed array for up to 4 touch positions. For more that 4 it fallback to an array.

**Comment by tdeeb** [comment]
More garbage/performance improvements:

- Reduce a dictionary lookup in [`PlatformGetCapabilities`](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Input/Joystick.SDL.cs#L55) via `TryGetValue`.
- Replace [`HasFlag` checks](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Input/Joystick.SDL.cs#L107) with a direct bitwise check to avoid boxing and various security checks. For example: `(hatstate & Sdl.Joystick.Hat.Up) != 0`

**Comment by tdeeb** [comment]
I looked into a new overload: `PlatformGetState(int index, int[] axes, ButtonState[] buttons, JoystickHat[] hats)`. This would fill the supplied arrays and assign them to the JoystickState, but I quickly found out that it's useless since modifying the arrays will modify the JoystickStates created via this method. Is there some alternative to how we do things now to reduce the amount of memory allocated with each JoystickState?

**Comment by Jjagg** [comment]
We could let users pass a JoystickState ref that we fill in. Users only need as many instances as supported joysticks and array lengths only grow a couple times.

**Comment by tdeeb** [comment]
I like that idea. What should it do if the array lengths change or a completely different controller is in that index now? For example:
1. Index 0 has a Joystick with 8 buttons
2. Joystick at index 0 is disconnected
3. Joystick at index 0 now has 10 buttons
4. The JoystickState associated with index 0 has a button array of length 8

Should we resize the arrays, or is this something we expect users to manage?

**Comment by Jjagg** [comment]
I would let MG manage array size, otherwise it complicates things. We'd need API for users to query required size and it adds boilerplate for any user consuming the Joystick API.

MG should create larger arrays if necessary, but never make them smaller to avoid allocations if things change a lot. Users should be able to avoid MG resizing the arrays by precreating the arrays with some size that is large enough for any joystick.

**Comment by tdeeb** [comment]
Closing this due to https://github.com/MonoGame/MonoGame/pull/6829 and https://github.com/MonoGame/MonoGame/pull/6834 being merged.
