### ISSUE TITLE
PipelineController catches only NotSupportedException upon initialization of encoding

### ISSUE THREAD

**Issue by tchanturia** [MonoGame/MonoGame#6825]
Currently `PipelineController` upon `DoBuild` tries to set `encoding` within a `try/catch` clause. The clause only catches `NotSupportedException` and initializes `encoding` with `UTF8` in case of the exception.
https://github.com/MonoGame/MonoGame/blob/56694bbb9f0b92a5d85014982d9e423b63267049/Tools/Pipeline/Common/PipelineController.cs#L501-L506

According to msdn `Encoding.GetEncoding` may also throw `ArgumentException` which means that provided `codepage` is not supported too. Not catching this exception leads to the pipeline tool sometimes being unresponsive on build/rebuild/clean actions:

![pipelinebug](https://user-images.githubusercontent.com/35450004/61712255-35a04780-ad56-11e9-8669-6a1afb7a6261.gif)

#### What version of MonoGame does the bug occur on:
- latest develop build

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by Jjagg** [comment]
Fixed in #2826.
