### ISSUE TITLE
Switching between Song objects in the MediaPlayer causes them to be played at a reduced volume

### ISSUE THREAD

**Issue by SuperPokeunicorn** [MonoGame/MonoGame#6828]
I'm trying to implement music in my game using the MediaPlayer and Song classes, but I'm running into an issue. The first Song I play will play at the desired volume, no matter how many times I play it. However, as soon as I try playing a different Song, the volume is significantly reduced, even though MediaPlayer.Volume is still set to 1. Even if I try switching back to the original Song, the volume is usually reduced as well. Sometimes the first song will still be at the desired volume after switching back to it, but this seems to occur at random and the volume reduction will eventually occur after calling play on it a few more times. The volume reduction seems to be permanent until I close out and start the game again. 

I have tried both MP3 and WAV files, but both run into this issue. This issue does not affect the volume of SoundEffect objects, just Song objects. I tried posting to the forums for a solution, but I was told that this is probably an issue with MonoGame itself and that I should post about it here.

After some experimenting, I found that the problem seems to be related to the ContentManager. Removing all SoundEffect loads from my code fixes the issue, but loading even a single SoundEffect using the ContentManager causes the issue to occur. I'm loading my SoundEffect objects from MP3 files if that's important. 

However, this issue occurred even before adding SoundEffect objects to my project, so I'm not sure why removing them now solved the issue. Anyway, SoundEffect objects may or may not be the only source of the issue, but loading SoundEffect objects is the only consistent way of reproducing the issue that I've found.

Here's a simple example where the issue occurs. I've added the following code to a default Windows project. Pressing A or S will cause the song to play at full volume, but then pressing the other button will cause the other song to play at a reduced volume:

```
        Song s1, s2;
        protected override void LoadContent()
        {
            s1 = Content.Load<Song>("exampleSong1");
            s2 = Content.Load<Song>("exampleSong2");

            Content.Load<SoundEffect>("exampleSFX");
        }

        protected override void Update(GameTime gameTime)
        {
            if (Keyboard.GetState().IsKeyDown(Keys.A))
                MediaPlayer.Play(s1);
            if (Keyboard.GetState().IsKeyDown(Keys.S))
                MediaPlayer.Play(s2);

            base.Update(gameTime);
        }
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.626

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsDX

**Comment by tdeeb** [comment]
I'm not too knowledgable on MediaPlayer, but I think it might have to do with [disposing the `_volumeController`](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Media/MediaPlayer.WMS.cs#L220) in `StartNewSong`.

**Comment by SuperPokeunicorn** [comment]
Thanks for looking into this. To clarify, the MediaPlayer.Volume variable itself is not changing, but the volume the Song plays at is. Trying to change the volume variable after switching songs does not seem to solve the issue. Whatever level I set MediaPlayer.Volume to, the actual audio is played lower than that. Hope this helps.

**Comment by SuperPokeunicorn** [comment]
I've recently noticed that if my game crashes due to an error, the volume returns to normal. Hope this info helps.

**Comment by SuperPokeunicorn** [comment]
I recently got a new PC and found that this issue was fixed when I tried running the project on the new one. Since this means that the issue is likely on my end and is being caused by my old PC, I'll go ahead and close the issue.
