### ISSUE TITLE
Joystick usage sample

### ISSUE THREAD

**Issue by tclancey** [MonoGame/MonoGame#6830]
Could we please have some working Joystick examples?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by diwashbiswa** [comment]
Here's the code you would use for adding gamepad capabilities. This one moves the sprite based on the left joystick input.

// Inside Update method
// Gamepad
GamePadCapabilities capabilities = GamePad.GetCapabilities(PlayerIndex.One);

// handle for controller
if (capabilities.IsConnected)
{
    GamePadState gamePadState = GamePad.GetState(PlayerIndex.One);

    if (capabilities.HasLeftXThumbStick)
    {
        if (gamePadState.ThumbSticks.Left.X < -0.5f)
        {
            position.X -= 10.0f;
        }
        if (gamePadState.ThumbSticks.Left.X > 0.5f)
        {
            position.X += 10.0f;
        }
        if (gamePadState.ThumbSticks.Left.Y < -0.5f)
        {
            position.Y += 10.0f;
        }
        if (gamePadState.ThumbSticks.Left.Y > 0.5)
        {
            position.Y -= 10.0f;
        }
    }
    if (capabilities.GamePadType == GamePadType.GamePad)
    {
        if (gamePadState.IsButtonDown(Buttons.B))
        {
            Exit();
        }
    }
}

Attached is a simple working example.
[Joystick Example.zip](https://github.com/MonoGame/MonoGame/files/7406459/Joystick.Example.zip)

**Comment by samercer2002** [comment]
Hello, I was wondering if this was available to be worked on. If so, I would like to work on it.
