### ISSUE TITLE
Cake, MSBuild and Visual Studio

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#6835]
I've been reading about the new Cake build scripting being adopted by monogame to replace Protogame...

Reading the code I've noticed there's tricks and hacks to determine which is the current version of MSBuild to use, specially when running concurrently with Visual Studio.

I've had a similar issue recently, and I'm not the only one, so Microsoft has recently released this new nuget package: [Microsoft.Build.Locator](https://www.nuget.org/packages/Microsoft.Build.Locator/)

This package is intended to be used for exactly that purpose; it identifies which is the appropiate MSBuild instance to use in your project, so you don't need to worry about which version is installed, or looking into different directories, that package does it four you.

Usage example can be located [here](https://docs.microsoft.com/es-es/visualstudio/msbuild/updating-an-existing-application?view=vs-2019#use-microsoftbuildlocator). 

I've dropped this here in case it can be useful... close the issue at will 😄 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.*

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
We use [vswhere](https://github.com/microsoft/vswhere). It has good integration with CAKE.
