### ISSUE TITLE
OggStreamer create non background thread, Consequently application can't close on exit

### ISSUE THREAD

**Issue by theR4K** [MonoGame/MonoGame#6847]
When I played with dynamicSoundEffectInstaince I find that when I create Instance my app don't close after end of main thread ...
I opened Monogame src and find that, when OggStreamer constructor were called it's create new thread, but for this thread not setted proterty "IsBackground". And this thread been created as main and app wait it to close.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
Thanks for the bug report! I've set up a pull request that correctly sets the thread to run as a background thread :)
