### ISSUE TITLE
Documentation does not show "ref" in method signatures

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#6849]
The documentation on the website doesn't show the `ref` keyword in method signatures. For example, compare the documentation pages for [this](http://www.monogame.net/documentation/?page=M_Microsoft_Xna_Framework_Input_Joystick_GetState_1) and [this](http://www.monogame.net/documentation/?page=M_Microsoft_Xna_Framework_Rectangle_Intersect) with the actual signatures [here](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Input/Joystick.cs#L57) and [here](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Rectangle.cs#L425).

#### What version of MonoGame does the bug occur on:
- Develop

#### What operating system are you using:
- N/A

#### What MonoGame platform are you using:

- N/A

**Comment by Jjagg** [comment]
Will be fixed when we switch to docfx #5559.
