### ISSUE TITLE
Why is there no "FillMode.Point"?

### ISSUE THREAD

**Issue by NET-D3v3l0p3r** [MonoGame/MonoGame#6866]
Is there a reason FillMode.Point is not implemented?

Best wishes.

**Comment by Jjagg** [comment]
It was not in XNA and is not supported by Direct3D.

**Comment by NET-D3v3l0p3r** [comment]
"not supported by Direct3D"
Hm, this is not correct at all, I guess: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb322859(v%3Dvs.85)

**Comment by Jjagg** [comment]
Those are the D3D9 docs. MonoGame uses Direct3D 11 which no longer has the point fillmode: https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_fill_mode
