### ISSUE TITLE
Windows DirectX version for .NET Core 3.0

### ISSUE THREAD

**Issue by johanolofsson** [MonoGame/MonoGame#6874]
Integrating MonoGame with WPF creates a pretty nice environment for building tools and editors.
 
However, as C# 8 is only available with .NET Core (and Standard 2.1) this causes a bit of an issue. 

WPF is now fully supported by .NET Core 3.0. 

It would be really nice with a build for .NET Core or Standard for use in a .NET Core 3.0 WPF application.

**Comment by cra0zy** [comment]
You can reference .NET Framework libraries from .NET Core, and as such, I'm gonna close this issue as there is nothing for us to do here.

**Comment by Jjagg** [comment]
I think we should multitarget once .NET Core 3.0 is out with the SDK-style WindowsDX project.

**Comment by cra0zy** [comment]
Of course.

**Comment by johanolofsson** [comment]
Why wait?

I find it unlikely for there to be any major changes to .NET 3.0 that will make a MonoGame WindowsDX .NET Core build incompatible.

**Comment by Jjagg** [comment]
I'm fine with adding .NET Core 3.0 as a target right now. We don't publish nugets yet for the SDK style projects, so users will still have to build from source for now.

**Comment by cra0zy** [comment]
But 3.0 is not out yet, I'm against adding it right now, once its out we'll add it.

**Comment by johanolofsson** [comment]
It will be released in September so I guess I can wait :)

If possible it would be even nicer if it was .NET Standard. 

I do have a few concerns on how to actually structure a solution with support for both WPF integration and builds for various platforms without having to deal with "Shared Projects" but I'll create another thread for that.
