### ISSUE TITLE
OpenXR support

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#6875]
One of the missing big features of monogame is VR support; this is something that has been discussed many times in the past, and the consensus has always been that it would be very difficult to support given monogame's architecture, and the state of VR APIs.

Khronos has just released OpenXR, which aims to provide a common API for all VR headsets.

My proposal would be for monogame to support OpenXR and only OpenXR as an in built solution for VR.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
Yes, we should most definitely support OpenXR!

**Comment by SimonDarksideJ** [comment]
The main issue I've found in the past is that MonoGame can only support VR rendering where there is a single render texture supplied to the headset, where two separate display textures are needed (usually referred to as two separate graphics displays), then we run in to an issue as MG at its core only supports a single graphical display (at lease as far as I've been able to work with).

It's not clear if OpenXR goes to this level, but something to take into consideration.

**Comment by Jjagg** [comment]
I haven't encountered that issue at all. I've written an application with MG for SteamVR and it accepted native DX or GL textures, so I could simply retrieve the native handle from a MG RenderTarget2D and submit that. If we expose the native handle VR integration will probably be very simple for a MG game.

**Comment by vpenades** [comment]
@SimonDarksideJ I can see two different approaches to solve this:

1- Sequential rendering: Somehow, let the current Graphics display API expose one backbuffer as now, but add a method to "switch" backbuffer eyes, so the game can render one eye after another

2- the graphics display will be right eye by default, the left eye will be always hidden under the hood of monogame. Then, all rendering calls must be redirected to each backbuffer, the monogame visible one, and the hidden one. I suspect this would require a lot of work.

My feeling is that XNA/Monogame has always been a good engine to serve as a sort of _introductory_ framework for game development, and its API philosophy has always been to hide the underlaying complexities of handling graphics devices, resources, etc.

Ideally, any 3D monogame application would simply require to use a "bool VRHeadsetDisplay" to switch from desktop rendering to VR rendering.

**Comment by SimonDarksideJ** [comment]
@Jjagg different platforms have different requirements and SteamVR is closely aligned with OpenVR, hence a single texture for both eye's, like Cardboard.

I Like your idea @vpenades hiding the rendering complexity for each platform behind MG. I initially looked at updating the graphics class to accept different graphics devices, but your approach is more akin to MG's goals.

@demonixis any thoughts?

**Comment by demonixis** [comment]
@SimonDarksideJ OpenVR requires two textures, [one per eye](https://github.com/demonixis/C3DE/blob/develop/C3DE/VR/OpenVR/OpenVRService.cs#L163).
The main issue with a native integration is that you've to handle a lot of different cases. What about:
- In engine optimizations?  (Singlepass, etc...)
- How the developer can change the behaviour of the defaut rendering engine?

I think that it's a great idea to expose everything needed by developers to make their own integration (a pointer to the native resource, today [we've to use reflection](https://github.com/demonixis/C3DE/blob/develop/C3DE/VR/OpenVR/OpenVRService.cs#L84). Maybe providing a sample with a naive implementation.

Finally OpenXR is not only VR, it's also AR!

**Comment by vpenades** [comment]
Considering monogame infrastructure, and how VR works, I would implement VR in monogame like this:

Monogame has two main methods: Update and Draw.

For VR, I would extend this by adding DrawLeftEye and DrawRightEye.

So the rendering order would be this:

1- DrawLeftEye(EyeMatrices left)
2- DrawRightEye(EyeMatrices right)
3- Draw()

Notice that Draw is still called after drawing both eyes; this can be used to set the mirror image from one of the two previously rendered eyes, or to render a custom view.

**Comment by BenMcLean** [comment]
If MonoGame ever came to support OpenXR then that would get me to switch from Godot to MonoGame.

**Comment by Apostolique** [comment]
I don't know if it helps, but there's this repo with an example setup: <https://github.com/cpt-max/OculusRift4MonoGame>.

**Comment by BenMcLean** [comment]
> I don't know if it helps, but there's this repo with an example setup: https://github.com/cpt-max/OculusRift4MonoGame.

Thanks for the info. Glad to know this exists.
However, I don't want to switch to the Oculus SDK. I really want OpenXR so that I don't have to agree to anything owned or controlled by Facebook.

**Comment by BenMcLean** [comment]
Apostolique's reply made me do some searches on this and I found [StereoKit](https://github.com/maluoi/StereoKit). Someone even [posted about it on the forums back in February](https://community.monogame.net/t/should-monogame-and-stereokit-team-up/15084). Maybe MonoGame could sort of copy what they did?

**Comment by Apostolique** [comment]
Looks like there's more discussions here: https://github.com/maluoi/StereoKit/discussions/131

**Comment by vpenades** [comment]
@BenMcLean @Apostolique I've been asking for VR support on MonoGame for some years now... and I've came to the realization that there's no real interest.

So given the current pace at which MonoGame merges PRs... don't expect VR anytime soon. I am looking for alternatives too.

**Comment by SimonDarksideJ** [comment]
I wonder if @demonixis would like to pitch in, considering they have VR working in MonoGame :D

**Comment by SimonDarksideJ** [comment]
> So given the current pace at which MonoGame merges PRs... don't expect VR anytime soon. I am looking for alternatives too.

TO be honest, following MonoGames past, this would likely be more the work of an Extension, like MonoGame.Extended or FNA, rather than rely on the internal team.  As this wasn't a native XNA implementation, extending MonoGame has always been done externally. 

But anyone is free to submit a PR with options to make implementing VR/AR easier.

**Comment by demonixis** [comment]
Well, the main problem with VR integration is that you need to update shaders if you want to make an optimized implementation and not just a multipass one. That means using the old Basic Effect.
I think that it's easier for developers to use something like a plugin to use VR in MonoGame because MonoGame is not an engine, but a framework.

My VR integration into C3DE (that is powered by MonoGame) is simple, but it's an engine integration, not a framework one.
If you want something between the engine and the Framework, take a look at the great StereoKit engine. It's VR first and contains everything you need for that.

**Comment by vpenades** [comment]
As I said many times in the past, that kind of integration was valid for old VR SDKs that simply expected you to render every eye to a render target surface and you were ready to go. Modern VR SDKs require a much deeper integration with the graphics engine to take advantage of newer features. This deeper integration mean exposing some private monogame classes, and in some cases, making some methods virtual so you can hook into them...  And I am aware that MonoGame doesn't want to go in that direction.

@demonixis I agree that, StereoKit or maybe Veldrid are the way to go for VR

**Comment by mrhelmut** [comment]
If anyone wants to make a proposal and work on it, the team will likely consider it. Please mind that as-is, there is a lack of VR contributors and interest to make anything in that regard to move forward. Also, MonoGame is not an engine, so I don't know if we should expect a deep integration with its own target and template. IMO it should be about exposing what might be useful to implement your own support in any target, and that would pretty much be it.

**Comment by vpenades** [comment]
@mrhelmut Sorry, but expecting others to implement VR with minimal or no support from the leads is unrealistic.

All things considered, I don't think MonoGame will ever have VR support, and maybe it should not, and it needs to stay the way it is so it can keep doing what it does best: 2D games.

I opened this issue +2 years ago when there were no alternatives to do VR in c# besides Unity. Now we have Godot, Veldrid, SteroKit, Stride... so, that's the answer to my own issue.

**Comment by demonixis** [comment]
IMO the best way is to make an OpenXR C# wrapper with a plugin for MonoGame. That way developers can use the plugin in their engine with the optimizations they want. It's still possible to integrate a multipass implementation, but it'll requires work from the developper in any cases because MonoGame doesn't contains a camera system. It's in my plans, but before that, I'm waiting for the merge of the Shader Conductor PR.
