### ISSUE TITLE
SoundEffect pan property not working

### ISSUE THREAD

**Issue by Toemsel** [MonoGame/MonoGame#6876]
Since the Apply3D isn't working at all, I tried to build a workaround with "pan". But setting pan from -1f to 1f doesn't change anything. SoundEffect appears on both speakers. WAV file is in stereo format.

```
            using (var effectInstance = soundEffectBuffer[effect].CreateInstance())
            {
                effectInstance.Volume = volume;
                effectInstance.Pitch = pitch;
                effectInstance.Pan = pan;
                effectInstance.Play();
            }
```

Also did try the suggested solution #6543

```
            using (var effectInstance = soundEffectBuffer[effect].CreateInstance())
            {
                effectInstance.Play();
                effectInstance.Volume = volume;
                effectInstance.Pitch = pitch;
                effectInstance.Pan = pan;
            }
```

without any difference.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1.189

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL

**Comment by Jjagg** [comment]
> Since the Apply3D isn't working at all

Could you expand on this? Are you calling Apply3D on playing soundeffects?

**Comment by Toemsel** [comment]
Yes. And the output didn't differ. Also I read here on GitHub (or MonoGame forum) that the Apply3D is buggy and has some issues. Thus I tried to stick to the pan/volumne solution above.

Both of them do not work. Due to the completeness

                AudioEmitter emitter = new AudioEmitter() { Position = X };
                AudioListener listener = new AudioListener() { Position = Y };
                effectInstance.Apply3D(listener, emitter);

X equals the entitie's transform and Y the cameras transform component. Sound gets equaly emitted. (Both channels max volumne) No matter how I do transform the camera's transform component.

**Comment by JamDoggie** [comment]
Panning still does not seem to work on the DesktopGL branch as of 2.21.2020

**Comment by julcreutz** [comment]
Confirmed. Pan does not work on DesktopGL on 3.8.0.1444-develop

**Comment by JRC-BitBull** [comment]
Hi - just wondering whether this is likely to be fixed in the near future so I can plan around it? I'm currently running an old build of MG (which is working fine otherwise) but getting this issue resolved could be worth the potential pain of updating...

**Comment by absoluteAquarian** [comment]
I managed to get sound panning to work as on 27Oct2022 by making sure that the sound file was using the Mono channels setting instead of Stereo.

**Comment by Halofreak1990** [comment]
> I managed to get sound panning to work as of 27Oct2022 by making sure that the sound file was using the Mono channels setting instead of Stereo.

That's weird, this sounds like a 3D buffer issue, given that 3D buffers are supposed to contain mono audio in order for them to work properly. But there really shouldn't be any 3D processing going on unless one uses Apply3D and related 3D audio methods.
