### ISSUE TITLE
SpriteFont loading causes ContentLoadException on .NET Core 3.0

### ISSUE THREAD

**Issue by suleyth** [MonoGame/MonoGame#6889]
Hello, I'm just making a normal game (.NET Core 3.0) and everything works fine on the debug and release build. However, when I publish the project as a single executable (trimmed) and copy the Content folder I get this exception:
```
Microsoft.Xna.Framework.Content.ContentLoadException: Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name
```
I'm pretty sure there's nothing wrong with .NET Core 3.0 or single file executables because nothing was thrown when I loaded textures. I can confirm the exception is thrown when loading the font because not loading it works just fine. I've tried cleaning and rebuilding, copying the Content folder from all other directories, but it still throws the error when it loads the font.

The `.spritefont` file is the default. I didn't change anything, it's just Arial. And like I said, it loads and renders fine when debugging.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.7

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:
- DesktopGL

**Comment by mrhelmut** [comment]
Hi!

It can be because of the trimming. When you publish with the ```PublishSingleFile``` flag, .net core is trimming unused IL code, which may make reflected types to be missing (and I assumed that the debug mode is avoiding trimming).

You must add any missing types to your ```csproj``` for the trimming to make them available for reflection, e.g.:

```
<ItemGroup>
  <TrimmerRootAssembly Include="Microsoft.Xna.Framework.Content.ContentTypeReader" />
</ItemGroup>
```

Or alternatively disable the trimming with the ```PublishTrimmed``` set to ```false``` (this will however increase the footprint of the output a lot).

@cra0zy @Jjagg We should add the most common reflected types of MonoGame in the templates, I guess.

**Comment by cra0zy** [comment]
Hmm, there is https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Content/ContentTypeReaderManager.cs#L50 , I guess it does not work in case of .NET Core.

**Comment by Jjagg** [comment]
We can exclude the type readers from trimming with a wildcard in the templates.

Is there maybe an attribute we can use to keep things from being trimmed? That'd be nicer and we could recommend that for pipeline extensions.

**Comment by suleyth** [comment]
First, thanks a lot for answering so quickly. Adding that code to my `.csproj` causes the publishing to fail.
Here's the log:

```tmp
02/10/2019 16:04:27
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__202.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

System.Exception: Publishing failed.

===================

```

Here's my file if I typed anything wrong: https://hastebin.com/nagabeyutu.xml

**Comment by mrhelmut** [comment]
> Hmm, there is https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Content/ContentTypeReaderManager.cs#L50 , I guess it does not work in case of .NET Core.

Yeah I guess the linker detects unused instances, but the Mono AOT doesn't.

**Comment by suleyth** [comment]
I can now confirm it's the trimming, publishing without it shows no error.

**Comment by harry-cpp** [comment]
The templates have been updated so closing this.

**Comment by KelsamGames** [comment]
Wanted to post this here in case someone comes across this in the future: https://community.monogame.net/t/trimming-linker-breaks-spritefont-loading/18296

**Comment by Crustbrns** [comment]
Works, thanks a lot
