### ISSUE TITLE
Missing template that covers all the supported platforms

### ISSUE THREAD

**Issue by SuperJMN** [MonoGame/MonoGame#6894]
# Problem
As today, the available "dotnet" templates create platform specific projects.

# What we want
As a developer, I considered that it would be quite handy to have a template that creates a solution with the appropriate projects for each supported platform and a special project that should hold all the shared code (either a .NET Standard Library or a Shared Library, whatever it fits better).

Also, it the Content files (.mgcb) should be shared among the projects. Is this possible already?

**Comment by mrhelmut** [comment]
You can have one .mgcb for all platforms, it'll automatically build assets for the target you're building for as long as it is added to a project.

**Comment by SuperJMN** [comment]
@mrhelmut OK, what I want is to have a single one that is shared among the different targeted projects so every resource is centralized and to save time managing them. Is it possible? If so, how is it done? I tried to put my .mgcb file in a .NET Standard project and it didn't compile at all :(

**Comment by Apostolique** [comment]
I updated [Apos.Framework](https://github.com/Apostolique/Apos.Framework) so you can see how it's done. There's now a DirectX project in platforms. It uses the same mgcb file as the Core project. Check the csproj files to understand better.

**Comment by cra0zy** [comment]
> Also, it the Content files (.mgcb) should be shared among the projects. Is this possible already?

Yes, check out the mg shared project template to see how to set it up: https://github.com/MonoGame/MonoGame/tree/develop/ProjectTemplates/DotNetTemplate/MonoGame.Templates.CSharp/content/MonoGame.Library.Shared.CSharp

> As a developer, I considered that it would be quite handy to have a template that creates a solution with the appropriate projects for each supported platform and a special project that should hold all the shared code

The template for that already exists: https://github.com/MonoGame/MonoGame/tree/develop/ProjectTemplates/DotNetTemplate/MonoGame.Templates.CSharp/content/BlankApp
