### ISSUE TITLE
Use dotnet tools during build

### ISSUE THREAD

**Issue by jnoyola** [MonoGame/MonoGame#6898]
This is a question about the design and usage of the recent dotnet tools: 2MGFX and MGCB. I haven't found much discussion of this, but please point me in the right direction if I missed a thread. Apologies for the verbosity.

#### Question

Do we expect users to manually install dotnet tools before being able to build their game, or should they get the functionality automatically from the template or a PackageReference?

I'm under the impression that MonoGame is moving toward a model where a dev can clone a game repo and build without requiring any manual installation.

#### Problem

Dotnet tools seem to be intended more as manual helpers, rather than for use in automated build steps, for the following reasons:

1. Dotnet tools are not automatically restored on build. `dotnet restore` is run on build, but still not `dotnet tool restore`. This means tools need to be manually and explicitly installed or restored.
2. Dotnet tools cannot be transitive dependencies, by design, as opposed to package references.  You won't be able to reference a MonoGame.Content.Builder package that in turn references the MGCB tool. This means that any project intending to use MGCB will either need the tool installed globally, or listed in a manifest for local tool restore.

#### Solutions

Given those constraints, I see the following options:

1. Publish a MonoGame.Content.Builder package that expects the MGCB tool to be present.
    - The user can then choose to install the tool globally, or check in a local tool manifest and manually restore from it.
    - **Concern:** The user must manually install or restore the tool.
2. Publish a MonoGame.Content.Builder package that depends on the MGCB tool, but automatically runs `dotnet tool restore`.
    - The user can still choose to install the tool globally or check in a local tool manifest. In the case of a local manifest, though, it will be automatically restored as part of build. I'm not sure if this has perf implications or why it's not already automatic.
    - **Concern:** The repo must contain a local manifest, or the user must manually install the tool.
3. Keep MonoGame.Content.Builder as is.
    - The package has full control over the MGCB dependency, requiring no manual action.
    - **Concern:** This is somewhat non-standard and doesn't use the dotnet tools at all.

**Comment by Jjagg** [comment]
I think the best way to go is to have the MSBuild task that's run by MonoGame.Content.Builder try to find an installed mgcb and install it if no installed version is found. I'm thinking it should try things in the following order:
- Check for MSBuild property `MGCBCommand` to override the command that's used to invoke mgcb (can be used to specify local executable or for additional build steps)
- Try locally installed mgcb tool, check for manifest if a local version can be restored
- Try globally installed mgcb tool
- Install mgcb tool locally and use that, creating a manifest if it doesn't exist

**Comment by jnoyola** [comment]
I like that. I didn't think about creating the manifest for them. So in more detail, something like this:

1. Check for `MGCBCommand` (e.g. `C:\path\to\mgcb.exe`)
2. Check `dotnet tool list --local` for `mgcb` command. (Searching for the command instead of the package would allow someone to swap out their MGCB tool without needing a custom build of this task.)
    a. Run `dotnet tool restore` and set `MGCBCommand = "dotnet tool run mgcb"`
    b. Is doesn't seem possible to know if the package is already restored or not, so we should always restore. Even if it were possible, we wouldn't know if the version matched that in the manifest, so another reason to always restore.
3. Check `dotnet tool list --global` for `mgcb` command.
    a. Run `mgcb` under the assumption that global tools are correctly in the PATH.
4. If no local or global tool is present, add with the following:
    a. `dotnet new tool-manifest` -- make sure this is in the solution root?
    b. `dotnet tool install dotnet-mgcb`

I can take a whack at this later.

**Comment by Jjagg** [comment]
> make sure this is in the solution root?

I think we should put the manifest next to the project file. We shouldn't really be trying to find the solution file, there's so many difficult cases to handle if we want to do it right. It'll be easier to invoke as well if it's next to the project file. Local tools are still installed in the global package cache anyway, so duplicate manifests aren't an issue at all.

I'm starting to think that we might even just skip the global tool stuff and always use a local tool unless `MGCBCommand` is set. That'll let us do proper versioning, tying the version of the Content.Builder package to the MGCB version, instead of having users set the version in the local tool manifest.

**Comment by jnoyola** [comment]
> That'll let us do proper versioning, tying the version of the Content.Builder package to the MGCB version

Do you mean the task can also automatically update the manifest to use the correct version of MGCB? Maybe only upgrade to the correct version but never downgrade? The `dotnet tool update` command doesn't allow you to specify the version -- it just picks up the latest. Is that ok and we assume they're always backwards compatible, or should we manually parse and update the manifest?

**Comment by Jjagg** [comment]
> we could uninstall and install to pick the right version.

Great, IMO that's the way to go then!

> the global and local tool caches are different

That makes sense because global installation only has one version. We don't want to touch the global installation, so this isn't an issue.

**Comment by jnoyola** [comment]
> we could uninstall and install to pick the right version.

The only side-effect I found was if
- There's a root manifest (`C:\repo\.config\dotnet-tools.json`) with MGCB installed
- There's a separate sub-manifest (`C:\repo\project\.config\dotnet-tools.json`)

Then uninstalling and reinstalling may cause the tool to be uninstalled from the root and reinstalled in the sub-manifest.

If this is an edge case worth solving, we could get the path of the correct manifest when checking the version from `dotnet tool list` and `cd` to the correct directory before installing.

**Comment by Jjagg** [comment]
We don't want to uninstall a local tool if it's not installed in the current directory.

> we could get the path of the correct manifest when checking the version from dotnet tool list and cd to the correct directory before installing.

Listing local tools also gives us the manifest path, we should that the manifest is contained in our project folder. If it isn't, we create a manifest (which will fail if it already exists, but that's ok) and install the tool, it'll install in the subfolder manifest. Only the deepest manifest installation of the tool will be listed, so if I have a folder and subfolder with a manifest with mgcb installed and do `dotnet tool list` in the subfolder, only the installation in the subfolder manifest will be listed.

So if we have `/.config/dotnet-tools.json` with MGCB installed and someone has a project in `/project/` which uses MonoGame.Content.Builder, we'll do:
- working directory must be project folder `/project/`
- `dotnet tool list`
```
Package Id      Version      Commands      Manifest
---------------------------------------------------------------------------------------
dotnet-mgcb     3.7          mgcb          /.config/dotnet-tools.json
```
- Manifest root path `/` does not match project path `/project/` so either manifest at project folder does not exist or mgcb is not installed in it
- `dotnet new tool-manifest`
- `dotnet install mgcb --version {Version}`

**Comment by jnoyola** [comment]
> We don't want to uninstall a local tool if it's not installed in the current directory.

Good point. I was already using the manifest path to make sure we reinstall in the same location, but your idea is better.

I think it's in a decent state now. I'll have to do some testing later.

**Comment by Jjagg** [comment]
Awesome, looking forward to it :)

**Comment by Jjagg** [comment]
> I don't imagine xbuild can make use of this package and the dotnet tools anyway.

Yeah, dotnet CLI comes with portable MSBuild, so we only have to support that :)

**Comment by jnoyola** [comment]
#6905 resolved this thread for the Content Builder. #6922 is a separate thread to track the Pipeline tool.
