### ISSUE TITLE
[WindowsDX] SharpDX missing from nupkg

### ISSUE THREAD

**Issue by jnoyola** [MonoGame/MonoGame#6912]
I built the WindowsDX nuget package from the develop branch.
When I run a game, I get this error when MonoGame.Framework.dll tries to load SharpDX:
```Could not load file or assembly 'SharpDX, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' or one of its dependencies. The system cannot find the file specified.```

When I look inside the nuget package (both from cake's `build.ps1` and `dotnet pack`), the SharpDX DLLs are indeed missing. They're present in the MonoGame.Framework WindowsDX build output, but don't get pulled into the nuget, presumably because of the type of `Reference`. Do we still need the local DLLs instead of using `PackageReference`s like WindowsUniversal does? If so, we need to fix this by packing them into the nupkg, right?

#### What version of MonoGame does the bug occur on:
- develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by Jjagg** [comment]
We should switch it to use PackageReference.
