### ISSUE TITLE
Using IsFixedTimeStep causes max CPU usage on Mac OS X.

### ISSUE THREAD

**Issue by AidanMcK** [MonoGame/MonoGame#6925]
Due to the changes made doing issue [6535](https://github.com/MonoGame/MonoGame/pull/6535), the following lines of code in Game.cs were changed from (code comments removed):

```
if (IsFixedTimeStep && _accumulatedElapsedTime < TargetElapsedTime)
{
   var sleepTime = (int)(TargetElapsedTime - _accumulatedElapsedTime).TotalMilliseconds;

#if WINDOWS_UAP
   Task.Delay(sleepTime).Wait();
#else
   System.Threading.Thread.Sleep(sleepTime);
#endif
   goto RetryTick;
}
```

to:

```
if (IsFixedTimeStep && _accumulatedElapsedTime < TargetElapsedTime)
{
   var sleepTime = (int)(TargetElapsedTime - _accumulatedElapsedTime).TotalMilliseconds;

#if WINDOWS
   var sleepTime = (TargetElapsedTime - _accumulatedElapsedTime).TotalMilliseconds;
   Utilities.TimerHelper.SleepForNoMoreThan(sleepTime);
#endif
   goto RetryTick;
}
```

This may be a great solution for Windows, but MonoGame is more than Windows, and these changes result in a 100% CPU hog when using IsFixedTimeStep on Mac OS X, and probably other platforms.

Suggest putting the code back for non-Windows platforms, or implementing SleepForNoMoreThan() for the other platforms.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Mac OS X

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
This was actually done on purpose, for accuracy. The idea of a flag to sleep instead of spinning came up in the PR. But of course a SleepForNoMoreThan implementation would be better.

**Comment by AidanMcK** [comment]
Accuracy is good. 100% cpu usage overhearing laptops/phones and draining batteries is not. Got a lot of customer complaints due to this problem.

**Comment by meniku** [comment]
I second that, I wonder if there isn't some better way than 100% spinning the CPU, for example sleeping in small steps.

**Comment by Jjagg** [comment]
@mrhelmut What's your experience here?

**Comment by mrhelmut** [comment]
We should probably use the ```WINDOWS``` code path on DesktopGL and detect the OS at runtime to use another system timer when running on Linux or macOS (or default to the standard C# one as a workaround, even if it's less accurate).

**Comment by AidanMcK** [comment]
I added the original "System.Threading.Thread.Sleep(sleepTime);" to the non-windows code and seems to work fine for Macs:

```
#if WINDOWS_UAP
Task.Delay(sleepTime).Wait();
#else
System.Threading.Thread.Sleep(sleepTime);
#endif
```

This may not be the best solution, but its better than the existing situation. I only do this on Mac releases, it does not seem necessary for Android, and have not checked iOS yet.

**Comment by nkast** [comment]
@AidanMcK Have you disabled V-Sync in your game?

**Comment by AidanMcK** [comment]
Yep: SynchronizeWithVerticalRetrace = false

**Comment by mrhelmut** [comment]
(On a personal note, we never used fixed time steps on our games. We either allow players to Vsync or play uncapped. Though I understand that some use cases require fixed time steps; I'll look into this.)

**Comment by Apostolique** [comment]
> (On a personal note, we never used fixed time steps on our games. We either allow players to Vsync or play uncapped. Though I understand that some use cases require fixed time steps; I'll look into this.)

I found one good use for fixed time step, but maybe it's because my streaming setup is bad. When I play my game with uncapped frames, OBS shows my game stuttering even though it looks smooth locally. With fixed time steps, the game looks smooth on stream too.

**Comment by mrhelmut** [comment]
I remember a very big streamer saying that if a game doesn't have an option to tweak precisely the framerate, he would simply not play it because streaming hardware and software are so damn sensitive to it.
So yeah, I hear you out loud on that.

I'll try to look into this.

There's apparently a flaw in the current Windows path too: the timer may not be set to its most precise setting by default, and ```NtSetTimerResolution``` may be required.

**Comment by Apostolique** [comment]
There's actually a bug here I think: https://github.com/MonoGame/MonoGame/blob/fb9946ca6db364f32c64cb3cf05200c0be62f4eb/MonoGame.Framework/Game.cs#L51

The number should be 166666. It's been rounded up instead of down.

**Comment by mrhelmut** [comment]
I don't think that a 0.1 nano second makes a difference.

I'm working on a PR.

**Comment by mrhelmut** [comment]
I've setup #6941 

It's basically a fallback to the previous behavior on non-Windows platforms to avoid maxing the CPU.

It most likely reintroduces #4202 on non-Windows platforms.

A proper fix would be to look into what is the timer of ```Thread.Sleep``` on Mono platforms and find a way to know the actual precision. It looks like a very hairy per-platform problem to figure out and requires a deep knowledge of both Mono and Unix systems.

I can't do much more than this.

**Comment by AidanMcK** [comment]
So you've confirmed it to use full CPU on Android? I ran some CPU monitoring program on Android and did not notice high CPU usage when I tested it.

**Comment by mrhelmut** [comment]
Check if Android enforces Vsync on a system level (most devices do and ignore OpenGL settings).
This issue will not be exposed if the app is GPU bound.

Does your monitoring show a per core usage or total usage spread across all cores?

**Comment by MichaelDePiazzi** [comment]
I was afraid this would be an issue. I did originally keep the sleeps in place for other platforms, but it was decided that accuracy was more important. So I suggested adding an option to enable the less accurate timing and keep the previous behaviour, but it was decided to hold off on that to see if it would be an issue first 😅

@mrhelmut Thanks for addressing this! I'll post some suggestions in your PR shortly based on my previous work. I found it is actually possible to get the frame timings a little more accurate while still keeping sleep in place.

**Comment by MichaelDePiazzi** [comment]
Oh, almost forgot -- After my PR (#6535) was merged, there was some additional discussion regarding some potential further improvements to fixed time step in issue #6540.

**Comment by mrhelmut** [comment]
I'll look into this. Ideally we should avoid relying on Windows specific system calls.

**Comment by mrhelmut** [comment]
From what I read about ```Thread.Sleep()```, it's the most unreliable thing to use if we need sub 16ms accuracy (and we shouldn't expect a fixed frame time to work at all if it goes above 64 FPS). We _could_ have some control over its precision with system calls, but then again Windows thread scheduler doesn't guarantee accuracy at all (and it'd be a Windows only solution).
Everything that involves ```Thread.Sleep()``` seems to be a dead end.

Dunno if ```SpinWait``` can do better. It seems to be perfect to solve the accuracy issue, but has a chance to be as CPU intensive as active polling. I'll give it a spin.

**Comment by mrhelmut** [comment]
I made some measurements. Targeting a 17ms frame time:
- ```Thread.Sleep()``` ± 0.75ms max accuracy
- Brute force ± 0.10ms max accuracy (and 100% CPU)
- ```SpinWait.Once()``` ± 1.10ms max accuracy (but does free up CPU usage quite comparably to Sleep)

My guess is that ```SpinWait``` is not doing better because it potentially yields the thread back to the scheduler multiple times per frame (instead of just once in the case of ```Thread.Sleep()```).

I don't believe that we'll find a cross-platform compromise in between brute force and ```Thread.Sleep()```.

**Comment by mrhelmut** [comment]
I made some more tests and posted my thoughts on #6941
