### ISSUE TITLE
[UWP] GamePad vibration are set to triggers on Xbox One controllers

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#6929]
Hey there!

We're currently porting our game to UWP and I noticed that vibrations on a Xbox One controller make the triggers to vibrate instead of the handles (Xbox One controllers have 4 different vibration actuators: 2 in handles, 2 in triggers).

For consistency, vibration should be applied to handles and not to triggers.

I haven't checked if this affects the standard DirectX target.

Cheers!

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Windows UWP

**Comment by cra0zy** [comment]
Hmm, I set both the handle and the triggers to vibrate when setting left/right vibration param. The fix is pretty easy tho:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Input/GamePad.UWP.cs#L161

**Comment by cra0zy** [comment]
On a related note, that can totally be optimized by using a local variable as to skip pointless allocation.

**Comment by mrhelmut** [comment]
Ah cool, thanks for pointing it out.

I'll try to take a look at this to remove the allocation.

Do you think we should add an overload to set independently the 4 actuators?

**Comment by tomspilman** [comment]
> Do you think we should add an overload to set independently the 4 actuators?

We could add some methods as long as they are properly documented to only work on XB1 controllers.  No other controllers i can think of have trigger rumble.

**Comment by cra0zy** [comment]
How about adding a method that accepts `float[]` in cases a controller has more than 2 vibration motors? Maybe also adding a VibrationMotorCount to the caps side?

**Comment by tomspilman** [comment]
@cra0zy 

I think we either go with a simple `GamePad.SetTriggerVibration()` or we have to have another overload `GamePad.SetVibration(PlayerIndex playerIndex, float leftMotor, float rightMotor, float leftTrigger, float rightTrigger)`.  Or we add a `struct VibrationState` with all the different named vibration inputs with documentation on how each work and when they work.

There is no magical device at the moment that has anything more than these 4 vibration features and if there were more we would have to define what they are very specifically.  I don't think a nameless `float[]` is enough.

Heck in most cases a single float isn't enough to define the full vibration effect possible.  Take Switch vibration effects that don't work with a single float per "motor" as it is.

Anything beyond that would need alot more careful design to make it useful.

**Comment by mrhelmut** [comment]
Alright, I'll try to address and document this properly.
