### ISSUE TITLE
Switch access

### ISSUE THREAD

**Issue by Velocity-** [MonoGame/MonoGame#6945]
I've tried to apply to the Switch port of Monogame but haven't heard anything back. Perhaps Tom isn't here, but is there anyone else who could get me the access?

**Comment by Jjagg** [comment]
AFAIK Tom is the only one. cc @mrhelmut

**Comment by Velocity-** [comment]
That's unfortunate, I'd love to get started. I'll just wait for Tom, in that case :)

**Comment by cra0zy** [comment]
Yes, you need to wait for @tomspilman to approve you.

**Comment by tomspilman** [comment]
@Velocity- hey Bart.... just replied to your request.
