### ISSUE TITLE
DesktopGL doesn't run on 32bit .Net Core / dropping 32bit support?

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#6962]
Hello there,

Just noticed that DesktopGL projects don't run with ```win-x86``` identifier on .Net Core (tested on 3.0 and 3.1). It results in an access violation on a native level.

As far as it goes, it seems related to SDL.

The exact same project works perfectly on .Net 4.5 while using "prefer 32bit" targeting.

This makes me think that it's an issue on the .Net Core side. Possibly linked to how the native functions are marshalled.

**The real question is**: should we drop 32bit targets once and for all?

Few arguments:
- ```MonoGame.Framework.Content.Pipeline``` is already 64bit only
- .Net Core is 64bit only on macOS and Linux
- As of November 2019, Steam players using 32bit systems represent 0.96% (and declining)
- It could simplify the repository quite a bit

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by KakCAT** [comment]
I think the last @s-m-k  messages in gitter talk about this

https://gitter.im/MonoGame/MonoGame
