### ISSUE TITLE
GraphicsDevice.OpenGL: MaxTextureSlots is incorrectly determined

### ISSUE THREAD

**Issue by bartwe** [MonoGame/MonoGame#6969]
in GraphicsDevice.OpenGL.cs PlatformSetup()

MaxTextureSlots is determined using

       GL.GetInteger(GetPName.MaxTextureImageUnits, out MaxTextureSlots);

and later used by TextureCollection

in TextureCollection.OpenGL.cs PlatformSetTextures

the range used with GL.ActiveTexture(TextureUnit.Texture0 + i) is bound by MaxTextureSlots value.

However the documentation of GL.ActiveTexture() says the limit is GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS -1

which in my test setup (Ubuntu 18.04 in virtualbox) is reporting 8 instead of 32 for MaxTextureImageUnits which is causing glerror 1282

#### What version of MonoGame does the bug occur on:
- Head

#### What operating system are you using:
- Linux

#### What MonoGame platform are you using:
- DesktopGL

**Comment by Jjagg** [comment]
Fixed in #6970.
