### ISSUE TITLE
Update monogame.net

### ISSUE THREAD

**Issue by matale** [MonoGame/MonoGame#6979]
I was checking out the website and I thought this project was abandoned because the latest news if from 2017.

**Comment by harry-cpp** [comment]
@tomspilman We should really remove the news section since we are not using it.

**Comment by tomspilman** [comment]
I'll see if i can look into it.  I've wanted to link the Discourse latest threads there, but haven't gotten it to look good so i stopped.

@Jjagg - You can see that code in `front-page.php` in the MG theme.  You can see me pulling from `http://community.monogame.net/latest.json` .  Let me know if you want to take a crack at it.

**Comment by Jjagg** [comment]
I'm really busy for a couple weeks, but if you don't get around to it I'll handle it when I do the other website stuff.

**Comment by tomspilman** [comment]
@Jjagg - FYI. Taking a tab at the news thing again today for the next few hours.

**Comment by tomspilman** [comment]
Ok.... things are better now...

http://www.monogame.net/

![image](https://user-images.githubusercontent.com/103522/72672188-2c99e580-3a1c-11ea-9700-e31f6abd1385.png)

If i get some more time i'll jump in there and add the user icons from the posters on Discourse as well.

**Comment by tomspilman** [comment]
Also removed the header link to "News"...

![image](https://user-images.githubusercontent.com/103522/72672535-ff036b00-3a20-11ea-9f59-2451077c5c2c.png)

... thinking maybe i could add it back later and point it at http://community.monogame.net/c/news .

Thoughts?
