### ISSUE TITLE
AvaloniaUI. OneUI. Support Development

### ISSUE THREAD

**Issue by ParadiseFallen** [MonoGame/MonoGame#6990]
Hello.  there is such a beautiful thing as AvaloniaUI.  This is a UI for all platforms.  you need to add support for this framework.  It is necessary to implement some interfaces and provide access to the window for AvaloniaUI.  I think it will not be difficult for you to do this, because you know the whole architecture of the project.  Need a function that will provide a DataClass for AvaloniaUI so that it can work.  In the code, the person himself will decide whether to connect it from the outside or not.  Well, the interfaces can be sent by AvaloniaUI in PR themselves.  This issue https://github.com/AvaloniaUI/Avalonia/issues/1969.  And git repo https://github.com/AvaloniaUI

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Windows
But must work at any platform
#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
This is not a job for MonoGame devs.

**Comment by damian-666** [comment]
7 days ago :     https://github.com/AvaloniaInside/AvaloniaInside.MonoGame      works somewhat ok.     similar to the craftwork one a bit slower , uses writeable bitmap
