### ISSUE TITLE
KeyboardState missing GetPressedKeyCount method

### ISSUE THREAD

**Issue by yunfeizhengcoder** [MonoGame/MonoGame#6997]
According to the Monogame documentation on monogame.net, the KeyboardState structure should have the GetPressedKeyCount method. However, when I tried to use it in my program, it said that "KeyboardState does not contain a definition" for that method. I then looked at the KeyboardState definition in the metadata and it doesn't contain a definition for GetPressedKeyCount.
![2020-01-21](https://user-images.githubusercontent.com/57196644/72852786-a67cd980-3c7d-11ea-8590-54cf107e76da.png)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
`GetPressedKeyCount` was added after the last release. The docs are built from the develop version of MonoGame so they do have the method.
