### ISSUE TITLE
CS1729 Error at new ModelMeshPart();

### ISSUE THREAD

**Issue by ivanlog-git** [MonoGame/MonoGame#7006]
When i try do something like that:
ModelMeshPart meshPart = new ModelMeshPart();

I catch CS1729 C# ModelMeshPart does not contain a constructor that takes 0 arguments.
This problem exist in MonoGame.Framework.DesktopGL.Core 3.8.0.1-3.8.0.2
In 3.7.0.7 - work nornal.

Microsoft Visual Studio Community 2019 16.4.3

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by willmotil** [comment]
I believe this line disallowed the default constructor to be used.
I don't know if the default constructor in xna was public.
https://github.com/MonoGame/MonoGame/commit/2d7c0e17515340ad7f03eda2a6d1b7926660fa51#diff-d8057156161dee8e77ae3ea07a3b8b9cR67

**Comment by limbusdev** [comment]
There is a commit and issue doing this change. It broke my code as well. Currently I have no idea how to fix this without replicating the old version.

**Comment by limbusdev** [comment]
This has been solved by [PR 7198](https://github.com/MonoGame/MonoGame/pull/7198) for now. The constructor is public again but marked as "obsolete".
