### ISSUE TITLE
Wrong lighting when LightingEnabled = true on BasicEffect

### ISSUE THREAD

**Issue by BMarques** [MonoGame/MonoGame#7007]
When using the BasicEffect, using the EnableDefaultLighting() seems to be lighting the objects properly, but if using only LightingEnabled = true, the DirectionalLight0 is not being set properly. According to the book XNA Game Studio 4.0 Programming, the DirectionalLight0 DiffuseColor and Direction should have the following defaults.

effect.DirectionalLight0.DiffuseColor = Vector3.One; 
effect.DirectionalLight0.Direction = Vector3.Down; 

Small sample code.

```
model = Content.Load<Model>("box");
effect = new BasicEffect(GraphicsDevice)
            {
                Projection = Matrix.CreatePerspectiveFieldOfView(MathHelper.PiOver4, GraphicsDevice.Viewport.AspectRatio, 1f, 100f),
                View = Matrix.CreateLookAt(new Vector3(2, 3, 2), Vector3.Zero, Vector3.Up),
                LightingEnabled = true
            };

// Setting LightingEnabled is not defaulting the DirectionalLight0 properly.
effect.DirectionalLight0.DiffuseColor = Vector3.One; // Is set to Vector3.Zero initially in Monogame
effect.DirectionalLight0.Direction = Vector3.Down; // Is set to Vector3.Zero initially in Monogame
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1018

#### What operating system are you using:
- Windows
- Xbox One via UWP

#### What MonoGame platform are you using:

- WindowsDX
- WindowsUWP

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
