### ISSUE TITLE
PlatformClear inconsistent accesability level

### ISSUE THREAD

**Issue by bjornenalfa** [MonoGame/MonoGame#7024]
GraphicsDevice.PlatformClear and GraphicsDevice.PlatformPresent are public when targeting OpenGL or Web but private when targeting DirectX. This can lead to errors when switching platforms or potentially cause a System.MethodAccessException when using assemblies built for a different platform.

#### What version of MonoGame does the bug occur on:
- Develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL, WindowsDX

**Comment by tomspilman** [comment]
Thanks for reporting this @bjornenalfa ....  `PlatformXXXX` shouldn't be public at all on any platform.  Those should all be internal/private APIs.

If someone gets a chance to fix this please submit a PR.

**Comment by moolicc** [comment]
Alright, I've got a free minute or two. May as well take a stab.

**Comment by nkast** [comment]
The same fix is needed for GraphicsDevice.Web.cs

Additionally there's a public Mouse.PlatformSetCursor(...) 
in Mouse.Default.cs  and Mouse.Windows.cs

**Comment by harry-cpp** [comment]
The web backend is just stubs, its not even getting compiled by the build bot, the real one lives in my fork.

**Comment by tomspilman** [comment]
@harry-cpp - Still the docs show any public APIs like that.  So it would be good to fix it just to avoid it appearing in the docs.
