### ISSUE TITLE
SharpDX missing from WindowsUniversal assemblies directory on latest's development branches

### ISSUE THREAD

**Issue by BMarques** [MonoGame/MonoGame#7028]
UWP project isn't starting up properly because the SharpDX assemblies are not included within C:\Program Files (x86)\MonoGame\v3.0\Assemblies\WindowsUniversal.

It was fine with the 3.7.1 release. I managed to fix it by copying the SharpDX assemblies from the Windows Directory to the WindowsUniversal directory and rebuilding the UWP project.

Not relevant.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1053

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsUWP

**Comment by mrhelmut** [comment]
Hey there,

How are you building/referencing MonoGame?

No issue on my end using the build.ps1 script and referencing the nuget produced (which is the expected future distribution paradigm of MonoGame; this nuget is not yet online).

**Comment by BMarques** [comment]
I meant to say build, not branch, sorry for misleading. http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/latest.lastSuccessful/MonoGameSetup.exe?guest=1. If you uninstall all previously installed SDK, and install this one alone, you should have the issue.

**Comment by mrhelmut** [comment]
Okay!

The installer will retire soon, so it's likely not going to get fixed. The new consumption method of MonoGame will be entirely nuget based.
In the meantime, I would recommend to build from source and reference the local nuget if you need the latest develop version.

**Comment by BMarques** [comment]
Thanks, I'll do that.
