### ISSUE TITLE
Coordinate system completely different than XNA?

### ISSUE THREAD

**Issue by paulb39** [MonoGame/MonoGame#7039]
Does monogame draw models completely differently than XNA? 

As a learning exercise I am trying to convert this XNA chess game to monogame: https://sourceforge.net/p/xna3dchess/code/HEAD/tree/

You can just copy their game class in a monogame project and it'll compile - only thing I had to change was :
```
            GraphicsDevice.RenderState.AlphaBlendEnable = false;
            GraphicsDevice.RenderState.DepthBufferEnable = true;
```
to
```
            GraphicsDevice.BlendState = BlendState.Opaque;
            GraphicsDevice.DepthStencilState = DepthStencilState.Default;
```

The issue I am having is everything is displayed wrong, I am using the exact same code, literal copy and paste - see screenshots:

[XNA](https://imgur.com/a/kTuCViz)

[Monogame](https://imgur.com/a/JkcLzGC)

The only other thing I had to do was - when I added the model FBX files, the pipeline tool failed with:
`Imported FbxImporter had unexpected failure!
Error importing file: FBX-DOM unsupported, old format version, supported are only FBX 2011, FBX 2012 and FBX 2013`

I opened the file in visual studio 2017, and did save as FBX, and that made the models compile. That wouldn't affect how they would get drawn, would it?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL
-DesktopUWP
-Android

**Comment by KakCAT** [comment]
I've ported several of my 3D games from XNA to MonoGame and there's no coordinate changes.

My bet is that either VS2017 'broke' the FBX when resaving them, altering the rotations, or that MGCB (converts the fbx to xnb) was the one who broke them.

You can try to open both the original file and the converted file with Blender, 3ds max, or any DCC program to see if the rotations are the same. (don't trust VS2017 as it's the one that maybe is introducing the problem)... If they're not, culprit is probably the VS2017 save, otherwise a MGCB problem.

**Comment by paulb39** [comment]
@KakCAT thanks for the reply. Is there a guide to exporting the file with blender? I used visual studio because I originally tried using blender but the model would never load to the monogame scene when I used that file.

**Comment by paulb39** [comment]
Used [autodesk FBX converter](https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives) to convert to 2013 FBX, models load in monogame but still with the odd rotation. Manually rotated the object in VS and saved it, models load the right direction now, but as you can see from the screenshot, the spacing is wrong (I guess scaling gets screwed in the conversion as well?)

Also the models .Tag is null so collision doesn't work (guess that gets stripped in the conversion as well?)

Pulled from source to use the latest pipeline tool to see if it would compile the FBX files differently, same issue. Giving up, closing since this isn't technically a bug with monogame.
