### ISSUE TITLE
Content Pipeline support for arbitrary text config files (including JSON, YAML, etc.)

### ISSUE THREAD

**Issue by mcmillen** [MonoGame/MonoGame#7053]
This is a feature request / design review for functionality that I'm happy to implement & contribute as long as the MonoGame devs approve of the concept. Comments / suggestions welcome!

# Proposal

Right now, the MonoGame content pipeline has the ability to import XML files via `XmlImporter`, but many folks would rather keep metadata & config files in a different format, such as JSON, Windows INI / .cfg files, YAML, etc.

Rather than implementing separate processors for every possible plain-text file format, I propose adding a generic `TextImporter` to the content pipeline, which simply reads the associated file and presents it to the user as a C# string. The user can then parse it with their favorite JSON / YAML (etc) parser; for example:

```csharp
string json = content.Load<string>("path/to/some/config.json")
JObject config = Newtonsoft.Json.Linq.JObject.Parse(json);
```

This would be implemented as a straightforward `ContentImporter` that reads the input file and returns a `string` result, defaulting to the `PassThroughProcessor`, since it's expected that the user will do their own processing within their game logic.

# Alternatives

One obvious alternative would be to simply read the file directly, with `System.IO.File.ReadAllText()` or a similar API. My assumption is that a lot of people would rather keep all their content files & content-loading code in one place within the MonoGame framework. Providing them an easy way to load arbitrary config files would lead to simpler & more-orthogonal business logic.

Another alternative would be for each developer to implement their own custom content importer, for example [as described in this blog post](http://blog.dylanwilson.net/posts/2015/creating-custom-content-importers-for-the-monogame-pipeline/). Unfortunately, that's a bit of an laborious process if all you want to do is load a couple simple text files and parse them from within your game. 

MonoGame.Extended includes [JSON support](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Source/MonoGame.Extended.Content.Pipeline/Json), but including all of MonoGame.Extended feels like a lot just to load some JSON files -- and it only supports JSON specifically, not any other text-file formats that someone might want to use. It's also described in the code as "very nearly fully working", which does not instill confidence.

Finally, there's the approach I've actually taken in my game for now: include a JSON string inside an XML file and use XmlImporter, like so:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<XnaContent>
  <Asset Type="System.String">
<![CDATA[
JSON goes here
]]>
  </Asset>
</XnaContent>
```
This *works*, but I'm not proud of it. It feels slightly cursed.

# Questions

* How do we handle the encoding of the input text files? My preference would be to only support UTF-8 files, or perhaps to make two separate importers `Utf8Importer` and `Utf16Importer` for the two most-common Unicode formats.

# Expected limitations

* We will not handle legacy non-Unicode file encodings such as Windows code pages, Shift-JIS, and so on.

* The text file will be loaded into a single string in memory. A user who wants to load a file that's too big to fit in memory should probably implement their own streaming loading system instead of trying to use the proposed `TextImporter`.

**Comment by tomspilman** [comment]
I don't see an issue supporting more text file types if others agree.

However having the pipeline just pass thru text to the game and then parsing the XML, JSON, YAML, etc at runtime is sort of the opposite of what the pipeline was intended for.  I would for sure try not to encourage it too much as it just leads to abuse and problems for these devs.

I've dealt with enough games now ported to consoles that have slow saves, slow loads, etc because of abusing XML like it is some optimal format for runtime use.  It isn't much better with JSON or YAML.  All these formats are usually huge and 100x slower to process than just a little binary data.

> Finally, there's the approach I've actually taken in my game for now: 

 To me a simpler approach.  Include the .json file and mark it as a pass thru file which then is just copied across without changes.  Then do:
```
string json = File.ReadAllText("content/path/to/some/config.json");
```

Or if you want to get fancy...
```
using (var reader = new StreamReader(TitleContainer.OpenStream("content/path/to/some/config.json")))
    string json = streamReader.ReadToEnd();
```
Is there something wrong with this approach?

> `content.Load<string>("path/to/some/config.json")`

I don't see a problem having a special case for `ContentManager.Load<string>` that reads the file as raw string data.

**Comment by mcmillen** [comment]
Ah! I wasn't aware that it was allowed to just copy across a file without running it through some Importer, since the Pipeline Tool displays "Invalid / Missing Importer" in this case. But it seems I can just ignore that message as long as I change the build action from Build to Copy.

Having a special-case for `ContentManager.Load<string>` sounds grand to me.

If you wanted to make it easy to load binary data as well, I'd propose a similar `ContentManager.Load<byte[]>` so that people could also load custom binary formats through the ContentManager without writing a lot of boilerplate.

**Comment by tomspilman** [comment]
>  I wasn't aware that it was allowed to just copy across a file without running it through some Importer, since the Pipeline Tool displays "Invalid / Missing Importer" in this case. 

@harry-cpp - Note this has been a bug there for a while... it is really confusing.


> If you wanted to make it easy to load binary data as well, I'd propose a similar `ContentManager.Load<byte[]>`

There have been various proposals for this in the past.

The blocker has always been that the main feature of the content manager is caching... that it loads the data once and keeps it in memory for fast access.  If you're just loading the `string` or `byte[]` to parse and generate some other resource...  then you likely don't want this caching.

So the idea of this always seemed out of place in content manager.

**Comment by mcmillen** [comment]
Thanks for the explanations. I'll go ahead and close this, since it seems like there's easier ways of doing this than what I was envisioning.
