### ISSUE TITLE
Pipeline Tool Crashing 3.8.0.1082

### ISSUE THREAD

**Issue by Shidesu** [MonoGame/MonoGame#7057]
Hi,
I've recently updated to MonoGame 3.8.0.1082 and now the Pipeline Tool is not opening anymore. I tried to run it from a cmd to see if there was any error message. I managed to get this one: 
System.InvalidOperationException: Platform not found. Are you missing the platform assembly?
▒ Eto.Platform.Get(String platformType, Boolean allowNull)
▒ Eto.Forms.Application..ctor(String platformType)
▒ MonoGame.Tools.Pipeline.Program.Main(String[] args)

I rolled back to another version of MonoGame and no problem. So the problem is definitely linked to that version.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1082

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
Should work fine on develop branch (no pipeline tool installer for it unfortunately since the Protobuild removal).
