### ISSUE TITLE
`GraphicsDevice.DrawUserPrimitives` in version 3.8.0.2 behaves differently than in version 3.7.0.7

### ISSUE THREAD

**Issue by ryancheung** [MonoGame/MonoGame#7060]
When drawing a simple rectangle of (0, 0, 100, 100) with `GraphicsDevice.DrawUserPrimitives`, in version MonoGame.Framework.DesktopGL.Core **3.7.0.7**, it works without any problem, but in version 3.8.0.2, the left border of the rectangle doest not show up, it seems off-screen.

#### How to reproduce

1. Run the shape demo provided by MonoGame.Extended project
https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Tutorials/Demos/ShapesDemo.cs
2. Draw a rectangle like ` _primitiveDrawing.DrawRectangle(new Vector2(0, 0), 100, 100, Color.Yellow);`
3. Run the demo you'll see no problem, since the default MonoGame package referenced by the demo is 3.7.0.7
4. Upgrade demo reference of MonoGame to 3.8.0.2
5. You'll get the problem.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.2

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by ryancheung** [comment]
Just found it's not an issue, it is just that version `3.7.0.7` set `GraphicsDevice.UseHalfPixelOffset` true by default. 
After https://github.com/MonoGame/MonoGame/pull/6780 , `GraphicsDevice.UseHalfPixelOffset` was set to false by default.

By enabling `GraphicsDevice.UseHalfPixelOffset` this  issue should be fixed.

**Comment by Jjagg** [comment]
@tomspilman @harry-cpp Good reminder we should feature this change when we release.
