### ISSUE TITLE
New version `3.8.0.12` of `MonoGame.Framework.DesktopGL.Core` is toxic!

### ISSUE THREAD

**Issue by ryancheung** [MonoGame/MonoGame#7067]
I have a library that reference the netstandard package `MonoGame.Framework.DesktopGL.Core`, then i reference my library in a WindowsDX core monogame project.

it just raises `Could not load file or assembly 'MonoGame.Framework, Version=3.8.0.12, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference.`

Then i tried with the old version `3.8.0.2` and it works fine.

It seems version `3.8.0.12` of `MonoGame.Framework.DesktopGL.Core`  make `PrivateAssets=All` used in `PackageReference`  effectless. 

This is just werid. 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.12

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by ryancheung** [comment]
This is not related to the package itself, but it's version number after some tests I  found.
The version `3.8.0.12` of `MonoGame.Framework.DesktopGL.Core` is greater than the version `3.8.0.3` of `MonoGame.Framework.WindowsDX.Core`, this seems break the `PrivateAssets=All` rule and force the running exe trying to find the newer version of `MonoGame.Framework.dll`.

This is still werid, no documentation found in msbuild official docs site about this.

**Comment by ryancheung** [comment]
It is also weird that this rule does not apply to xamarin.ios and xamarin.android.

**Comment by tomspilman** [comment]
@harry-cpp - What are these `.Core` nugets for?

https://www.nuget.org/packages/MonoGame.Framework.WindowsDX.Core/
https://www.nuget.org/packages/MonoGame.Framework.DesktopGL.Core/

Can we not publish these officially?

**Comment by harry-cpp** [comment]
Just current builds of WindowsDX and DesktopGL builds, the DesktopGL one was originally uploaded when I did the DesktopGL .NET Core version. They are not official, I should probably edit the metadata.

That being said, they will be killed off once 3.8 is out, I use them, as well as other people use them, because 3.7 does not support .NET Core.
