### ISSUE TITLE
[DesktopGL] Target framework check does not seem to work

### ISSUE THREAD

**Issue by harry-cpp** [MonoGame/MonoGame#7068]
For some reason the target framework check does not seem to work, adding this here so I don't forget to check why:
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/MonoGame.Framework.DesktopGL.targets

**Comment by ryancheung** [comment]
I think it's the filename name `MonoGame.Framework.DesktopGL.targets`, the filename should be equal with the nuget package name. The package name may be `MonoGame.Framework.DesktopGL.Core`.

**Comment by ryancheung** [comment]
In advance, There's a condition check `Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">`.

**Comment by harry-cpp** [comment]
@ryancheung Oh yea, I forgot to rename it, thanks for pointing it out @ryancheung XD
