### ISSUE TITLE
Is it possible to instance a very large group of vectors or matrices?

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#7072]
So im thinking about how to instance a bunch of geometry for a model. 
But its not just geometry and instance data but animation information in addition that im thinking of.

The thing is to really make it work i would need to put the animation data quaternions positions and scale vectors on the shader then create the bone matrices on it. There would be a lot of them or could be a lot of them per model some models have over 1000 keys per animation. 
Now if i could put them on the shader i might be able to just do the calculations per bone on the shader per instance based on animation time. But im not sure about the data limitations and this on the cpu is precalculated so im not sure its possible to upload these form the matrices and then use them for each instance of the geometry on the gpu.

I really have no clue how to even approach this yet but im thinking about the bone matrix limit that xna had placed on matrices and im wondering how realistic this thought is as the way im doing it now is just uploading the bones per mesh to the shader but the bone animations are calculated cpu side.

Since im in the dark on how to approach this or if its even possible? 
Any information or thoughts would be welcome.
More so if anyone has experience doing something similar already.

win 10 mg 3.7 DesktopGL, WindowsDX

**Comment by Jjagg** [comment]
Please ask questions on the forum. The issue tracker is for bugs and feature requests.

community.monogame.net
