### ISSUE TITLE
SDL_Init() call causes a Keystroke Receiving popup on Mac OS X Catalina resulting in Mac App Store rejection.

### ISSUE THREAD

**Issue by AidanMcK** [MonoGame/MonoGame#7074]
On Mac OS X Catalina, the call to SDL_Init() triggers a Keystroke Receiving popup - the app "would like to receive keystrokes from any application":

![image](https://user-images.githubusercontent.com/19970935/77568448-8907fe00-6ec0-11ea-9718-3654bae45a28.png)

This causes rejection in the Mac App Store review process:

> Guideline 2.4.5(v) - Performance
> Your app requests admin access from the user during operation.

and after requesting more info from the Apple reviewer:

> To resolve this issue, it would be appropriate to confirm that you are using:
> - NSEvent.addLocalMonitor
> rather than
> - CGEvent.TapCreate.
>
> In addition, it would be appropriate to remove
> IOHIDCheckAccess(kIOHIDRequestTypeListenEvent) for accessing the user’s keystroke under
> Privacy, as apps with this feature are not appropriate for the App Store.

The popup appears within the call to SDL_Init() in the SdlGamePlatform constructor in SdlGamePlatform.cs:

```
Sdl.Init((int)(
                Sdl.InitFlags.Video |
                Sdl.InitFlags.Joystick |
                Sdl.InitFlags.GameController |
                Sdl.InitFlags.Haptic
            ));
```

If one passes 0 to the Sdl.Init() call instead of the flags above, the popup does not appear, but instead it appears later on in the creation of SdlGameWindow in  the call to SDL_CreateWindow(), so I cannot see anyway around this.

Also, calling Sdl.Init(0) followed by Sdl.InitSubSystem((int)Sdl.InitFlags.Video), the popup is indeed called during the SDL video subsystem initialisation. (Note: Sdl.InitSubSystem() is not present in MonoGame - I added it locally for testing).

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Mac OS X

#### What MonoGame platform are you using:
- DesktopGL

**Comment by harry-cpp** [comment]
Try updating the sdl dylib to a newer version. I don't get that permission request with MonoGame 3.8.

**Comment by AidanMcK** [comment]
3.8? Where is that? I only see 3.7.1 releases mentioned. Or do you mean the latest dev branch?

**Comment by harry-cpp** [comment]
I do indeed mean the dev branch.

**Comment by AidanMcK** [comment]
Yep that works, thanks.

The 3.7 SDL version is 2.0.5, and the current dev one is 2.0.10 which does not show the popup.

File in 3.7: ThirdParty/Dependencies/SDL/MacOS/Universal/libSDL2-2.0.0.dylib
now located in:  MonoGame.Dependencies/SDL/MacOS/Universal/libSDL2-2.0.0.dylib

**Comment by harry-cpp** [comment]
Great, thanks for reporting back! Closing as this is fixed in the develop branch.
