### ISSUE TITLE
Path errors on macOS 10.15 Catalina preventing loading SDL or content

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#7078]
I'm cross-compiling my game built in Windows with .NET Framework 4.7.2 to macOS using `mkbundle` with the mono 5.18.0 runtime for macOS 10.9 (64-bit). When double-clicking to run the game, the paths do not point to the actual executable, which is in `home/Desktop/Folder`:

- `AppDomain.CurrentDomain.BaseDirectory` reports the home folder
- `typeof(Microsoft.Xna.Framework.Color).Assembly.Location` - reports the home folder

This prevents the game from loading native libraries [such as SDL](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Utilities/FuncLoader.Desktop.cs#L41) and [loading content](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/TitleContainer.Desktop.cs#L23) because MonoGame internally uses these properties. Things work fine on Windows and Linux and if I run the game through the terminal. This prevents me from making an app bundle.

My current workaround for native library loading is to set `Environment.CurrentDirectory` to the application directory, which is retrieved through the native `proc_pidpath` function on macOS using the id of the current process. However, all content fails to load because it's still looking in the wrong location. I've tried later Mono runtimes and they still fail.

I've searched far and wide, and I can't find much about this issue. One option is to default to these paths and allow the developer to change them.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7+ (exact commit a854b98d1832a22cf3e7f61bd88c90e7bf93ef97)

#### What operating system are you using:
- macOS 10.15 Catalina

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
You can use MonoKickstart or dotnet publish to create a .app bundle for your game. `mkbundle` really is not a good option for doing so.
