### ISSUE TITLE
CSharp Templates issues

### ISSUE THREAD

**Issue by MattiKloepper** [MonoGame/MonoGame#7079]
I am experiencing slight issues with the current CSharp Templates from NuGet in Visual Studio (2019). I have installed the current templates (MonoGame.Templates.CSharp:3.8.0.1176-develop)
  - via `dotnet new MonoGame.Templates.CSharp:3.8.0.1176-develop` as well as
  - via the Visual Studio Extension `MonoGame project templates` Version 1.0.0.

The templates get installed without issues and even show up in the Visual Studio New Project Wizard if they are installed via the Visual Studio Extension.

If I than create a new project from the template `MonoGame Windows Desktop Application (Windows DirectX)' there are two NuGet packages listed in the project:
  - MonoGame.Content.Builder (3.8.*)
  - MonoGame.Framework.WindowsDX (3.8.*)

These packages can not be restored by Visual Studio. A couple of problems occur here:
- The Monogame NuGet feed (http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/) lists V3.8.0.1103 as the latest stable version but this version does not seem to be available for download. (Visual Studio will only use the latest stable version if you reference packages with wildcards.)
- The public NuGet Repository only has MonoGame 3.7.* packages available.
- The package `MonoGame.Content.Builder` is not listed at all.
- Updating the package `Monogame.Framework.WindowsDX` in Visual Studio to the latest preview build (3.8.0.1176-develop) does not work because it complains that the listed latest stable build (3.8.0.1103) is not available.
- Uninstalling the package `MonoGame.Framework.WindowsDX` in Visual Studio does not work because it complains that the listed latest stable build (3.8.0.1103) is not available.

To resolve this issue you will have to manually remove the packages from the Solution Explorer and than install the latest preview build of `MonoGame.Framework.WindowsDX` via NuGet Package Manager.

How to install `MonoGame.Content.Builder` I have no clue. Is that necessary at all?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1176

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by Jjagg** [comment]
MonoGame 3.8 has not yet been released and published to NuGet so the templates in the latest develop version that are also available as a Visual Studio extension do not work. The templates in the VS marketplace are a test, I forgot to unpublish them.

You can fix this issue by opening the csproj file and editing the MonoGame NuGet versions, or as you did with the NuGet Package Manager.

**Comment by MattiKloepper** [comment]
Thanks fpr the answer. Good to know that this will be fixed with the 3.8 release. Im fine with fixing it manually in the development-build.

Could you give me a hint on `MonoGame.Content.Builder`? What it is for? How to get a current development version? Or the current replacement if there is any? Thanks again.

**Comment by Jjagg** [comment]
`MonoGame.Content.Builder` is used to automatically build your game content. It picks up any `*.mgcb` files, builds them and copies the output to your bin folder. NuGet has a 3.7 version of that as well: https://www.nuget.org/packages/MonoGame.Content.Builder/, so you can use the same fix and change its version.

**Comment by MattiKloepper** [comment]
So you advice to install the MonoGame.Content-Builder in V3.7? I just wondered that there is no V3.8.* available. If that does not produce any issues I will use V3.7 for the Builder of course.

**Comment by harry-cpp** [comment]
`MonoGame.Content.Builder` was renamed to `MonoGame.Content.Builder.Task`, we should fix the templates.

**Comment by MattiKloepper** [comment]
Thanks for the clarification!

**Comment by MattiKloepper** [comment]
Created PR #7081 to reflect the renaming in the templates.
