### ISSUE TITLE
Pipeline tool will not open on Windows 10 (MG build 3.8.0.1082)

### ISSUE THREAD

**Issue by Brett208** [MonoGame/MonoGame#7092]
I could no longer open the MonoGame content pipeline executable after updating to the most recent development build of MonoGame.

Using Windows 10.

Steps to reproduce:

- Download MonoGame build 3.8.0.1082 installer and installer
- Attempt to open the MonoGame pipeline tool. Blue circle spins for fraction of second and nothing else occurs. Restart doesn't help. Uninstalling and reinstalling MonoGame does not help.
- Download MonoGame 3.7.1 (last official release)
- MonoGame pipeline tool runs properly again

I'm willing to pull extra system details if useful in investigation. Fortunately, anyone can just revert to the last official release to continue working.

**Comment by Brett208** [comment]
It looks like downloading the following link pulls a build from approx. 26 Feb 2020. 

http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/latest.lastSuccessful/MonoGameSetup.exe?guest=1

I'm gathering the new way to install development branches of MonoGame is via Nuget. I'm unsure how you pull the newest version of the pipeline tool (I think maybe renamed to MGCB) post build 3.8.0.1082? Is there a specific nuget package that can be downloaded that would include the newest Pipeline tool?

I suspect this issue may be resolved in builds of MonoGame more current than build 3.8.0.1082, but I'm unsure how to download the Content Pipeline tool since the development build is no longer being posted as an installer at https://www.monogame.net/downloads/.

**Comment by mrhelmut** [comment]
Hey there,

As you noticed, MonoGame is undergoing some heavy refactors in preparation of the public 3.8 release.

The installer has been deprecated and will be retiring soon. The new distribution model will be 100% nuget based (and the templates should be grabbed from dotnet CLI or a VS Extension). Presently, those nugets are not yet entirely public (we're still a few days/weeks until release).

So your best chance at working with the latest distribution is to build everything from source. For that you will need .Net Core 3.1 SDK and then to install Cake as a global tool with ```dotnet tool install --global Cake.Tool```.
Then you'll be able to run the automated build with the ```dotnet cake``` command from the repository's folder.

**Comment by Brett208** [comment]
@mrhelmut, thanks for the tip.

I downloaded cake and ran the script. It ran okay until the BuildTools where I get the following error:

```
========================================
BuildTools
========================================
  Restore completed in 34.74 ms for \MonoGame\Tools\MonoGame.Effect.Compiler\MonoGame.Effect.Compiler.csproj.
  MonoGame.Effect.Compiler -> \MonoGame\Artifacts\MonoGame.Effect.Compiler\Debug\mgfxc.dll
  Restore completed in 37.75 ms for \MonoGame\Tools\MonoGame.Content.Builder\MonoGame.Content.Builder.csproj.
  Restore completed in 37.42 ms for \MonoGame\MonoGame.Framework\MonoGame.Framework.DesktopGL.csproj.
  Restore completed in 37.43 ms for \MonoGame\MonoGame.Framework.Content.Pipeline\MonoGame.Framework.Content.Pipeline.csproj.
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.1.512\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [\MonoGame\Tools\MonoGame.Content.Builder\MonoGame.Content.Builder.csproj]
An error occurred when executing task 'BuildTools'.
Error: One or more errors occurred. (MSBuild: Process returned an error (exit code 1).)
        MSBuild: Process returned an error (exit code 1).
```

Interesting that the script is looking in the 2.1.512 SDK folder. I checked and there is also a 3.1.201 folder. I uninstalled a bunch of the 2.1.X versions of the SDK from my computer, and then it ran properly.

After finishing the script, I was able to open the file at the following location: `\MonoGame\Artifacts\MonoGame.Content.Builder.Editor\Launcher\Release\mgcb-editor-wpf.exe`. There seemed to be several different variations of mgcb.exe. I think this issue can be closed though unless there is something else I should check.

**Comment by mrhelmut** [comment]
I would have been curious as to know which dotnet version ```dotnet --version``` was returning. My guess is that despite your multiple installs, the default SDK in your environment was still set to 2.1.

Pinging @harry-cpp just in case there may be something more than the default SDK going on (maybe we should check ```dotnet``` versions, or maybe detect if there are multiple installs and use the latest one? or inviting to default to a newer version if it's older than 3.1?).

**Comment by harry-cpp** [comment]
Ah, I think I know what the problem is, `GetMSBuildWith` overrides the tool path, but does not restore it for the subsequent solutions.

**Comment by Jjagg** [comment]
@harry-cpp `GetMSBuildWith` only returns full MSBuild installations, not dotnet SDK installations. Btw what was the bug with packing with `dotnet` on Linux/Mac again? Is that still an issue?

**Comment by harry-cpp** [comment]
It is, you can't compile .NET Framework targeting assemblies with `dotnet msbuild`

**Comment by Brett208** [comment]
Thanks for the help. Both problems discussed in this issue sheet are now resolved.
