### ISSUE TITLE
MonoGame hide window only works on Windows platforms

### ISSUE THREAD

**Issue by VictorJL** [MonoGame/MonoGame#7104]
Hi. 

I'm building a level editor for our game, in which we take advantage of the Update and Draw methods of the Game class, being integrated with Eto.Forms it is not possible to update / draw from the main thread at this moment. 

The thing is that we create 2 windows, and one of them which is the Game window, must be hidden or opacity set to 0, I've seen that the Window has an implementation of a SDL2Window, which led me to conclusion that maybe using reflection we can set the game window to a hidden state. 

It would be nice that the Hide function could be cross-platform so other users can benefit from it.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- MacOs

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
You can use `Game.Window.Handle` to get the SDL window handle (this will not be set until the window is shown). You can call SDL functions with that handle to manipulate the window. 

I don't think this is something we want to support in our public API. Most users really don't need stuff like this. For a regular game at least this does not seem useful at all.
cc @tomspilman @harry-cpp 

Would destroying and recreating the game not work for your use-case?

**Comment by VictorJL** [comment]
I managed to hide the window by modifying the develop branch, also tried to call SDL functions by the method used by MonoGame using the FuncLoader class

````
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void d_sdl_setwindowhidden(IntPtr window);
        public static d_sdl_setwindowhidden SetHidden = FuncLoader.LoadFunction<d_sdl_setwindowhidden>(NativeLibrary, "SDL_HideWindow");
`````

**Comment by Jjagg** [comment]
What went wrong trying to call SDL from your code? It would be preferable if users do not have to change the source code.

**Comment by VictorJL** [comment]
A lot, to start with I was trying to share the NSApplicationDelegate so that two applications could run at the same time and ended implementing an NSWindowDelegate to make Eto.Forms run at the same time with the native SDL Application being created., 

In the end I wrote a virtual method on the main Window class to be overridden by the SDLWindow class

```
        public override void Hide()
        {
            base.Hide();
            Sdl.Window.SetHidden(_handle);
            _hidden = true;
        }
```

Lately I tried hiding the window from inside EndScreenDeviceChange

````

            // If this window is resizable, there is a bug in SDL 2.0.4 where
            // after the window gets resized, window position information
            // becomes wrong (for me it always returned 10 8). Solution is
            // to not try and set the window position because it will be wrong.
            if ((Sdl.Patch > 4 || !AllowUserResizing) && !_wasMoved)
                Sdl.Window.SetPosition(Handle, centerX, centerY);

            if (IsFullScreen != _willBeFullScreen)
                OnClientSizeChanged();

            IsFullScreen = _willBeFullScreen;

            _supressMoved = true;

            if (_hidden)
            {
                Hide();
            }
````

But that stopped the application from running the Update and Draw methods, which got solved somehow afterwards without really noticing it (there were some mixed netstandard2.0 and net461 assemblies conflicting) and even though the window wasn't hiding. 

Then and finally, inside the Game class Update method I had to put code like this:

````
            protected override void Update(GameTime gameTime)
            {
                base.Update(gameTime);

                OnUpdate?.Invoke();

                this.Window.Hide();
            }

````

I will open source the tools we're using at some point, they're not quite ready yet. Some rendering performance related issues and aesthetics left over.

**Comment by VictorJL** [comment]
The involved code is available at [ROTF](https://github.com/VictorJL/ROTF)
