### ISSUE TITLE
gitignore not hiding some generated files

### ISSUE THREAD

**Issue by Brett208** [MonoGame/MonoGame#7110]
When running `dotnet cake` on Windows 10 from, the following files are generated and not blocked by gitignore:

Tools/NUnit.ConsoleRunner.3.4.0/.signature.p7s
Tools/NUnit.ConsoleRunner.3.4.0/CHANGES.txt
Tools/NUnit.ConsoleRunner.3.4.0/LICENSE.txt
Tools/NUnit.ConsoleRunner.3.4.0/NOTICES.txt
Tools/NUnit.ConsoleRunner.3.4.0/NUnit.ConsoleRunner.nuspec
Tools/NUnit.ConsoleRunner.3.4.0/tools/Mono.Cecil.dll
Tools/NUnit.ConsoleRunner.3.4.0/tools/nunit-agent-x86.exe.config
Tools/NUnit.ConsoleRunner.3.4.0/tools/nunit-agent.exe.config
Tools/NUnit.ConsoleRunner.3.4.0/tools/nunit.engine.api.dll
Tools/NUnit.ConsoleRunner.3.4.0/tools/nunit.engine.api.xml
Tools/NUnit.ConsoleRunner.3.4.0/tools/nunit.engine.dll
Tools/NUnit.ConsoleRunner.3.4.0/tools/nunit3-console.exe.config

Tools/vswhere.2.6.7/.signature.p7s
Tools/vswhere.2.6.7/build/vswhere.props
Tools/vswhere.2.6.7/tools/LICENSE.txt
Tools/vswhere.2.6.7/tools/VERIFICATION.txt
Tools/vswhere.2.6.7/vswhere.nuspec 

Maybe the following directories should be added to the gitignore: 
 - Tools/NUnit.ConsoleRunner.X.X.X
 - Tools/vswhere.X.X.X 

I wasn't sure where to add them, maybe just below the cake section in gitignore?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8 (Commit Can't hide mouse cursor #6180 (#6908))

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
WindowsUWP, Android

**Comment by Jjagg** [comment]
Ah, we previously configured the tools path in the cake bootstrap scripts, but we removed those and that doesn't work when you directly execute the cake script anyway. Fix incoming!

**Comment by harry-cpp** [comment]
@Jjagg I figured it out, if you add a Fixes #XXXX in a PR description it auto closes with a much nicer message! Right?

**Comment by Jjagg** [comment]
Yes, then the PR closes it instead of the commit :)
