### ISSUE TITLE
MediaPlayer.Pause() bad behavior in UWP apps

### ISSUE THREAD

**Issue by diegohcanepa** [MonoGame/MonoGame#7113]
After resuming MediaPlayer from a pause state by calling MediaPlayer.Resume(), MediaPlayer.Pause() no longer works again. As indicated below, this bad behavior is happening in my UWP version of the project. The windows desktop / DX version works fine.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1082

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:
- WindowsUWP

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
