### ISSUE TITLE
How come I see mgcontent rather than .XNB files?

### ISSUE THREAD

**Issue by elguoshiy** [MonoGame/MonoGame#7122]
After building my png and spritefont how come I see mgcontent rather than .XNB files?

![2020-04-19 (2)](https://user-images.githubusercontent.com/61806028/79687036-5ee5f980-823c-11ea-9f3f-82350e4531ad.png)

**Comment by Apostolique** [comment]
You're looking into the `obj` folder. Try the `bin` one instead.

**Comment by elguoshiy** [comment]
Ok

**Comment by elguoshiy** [comment]
Yeah it worked thx man
