### ISSUE TITLE
Can't install the Install-Package Monogame.Extended

### ISSUE THREAD

**Issue by elguoshiy** [MonoGame/MonoGame#7126]
![2020-04-22 (2)](https://user-images.githubusercontent.com/61806028/80018693-560c5680-84ce-11ea-8bb5-366503f9288a.png)
I don't know what it means. Please help.

**Comment by harry-cpp** [comment]
MonoGame.Extended has nothing to do with us (except its a library that works on top of MonoGame), please complain about it on their repository: https://github.com/craftworkgames/MonoGame.Extended
