### ISSUE TITLE
[DesktopGL] Upgrading to SDL 2.0.12

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7128]
Hey there,

Just a to do note about upgrading to SDL 2.0.12 which has been released recently.
It might be needed to build it from source to make sure that it links to the VS runtime statically.

Cheers!

**Comment by Jjagg** [comment]
We could fork https://github.com/spurious/SDL-mirror/tree/release-2.0.12 and customize the build to statically link, same as we do for some other deps. That would make upgrading easier in the future.
