### ISSUE TITLE
GamePad.GetState() null exception

### ISSUE THREAD

**Issue by diegohcanepa** [MonoGame/MonoGame#7135]
I’m using monogame (.1082) with UWP, but this bug happened to me with previous versions, too.

It happens “rarely” when the game has started and the controller is disconnected. When you turn the controller on an “Object not set to an instance of an object” is thrown. It happens in the the Update() method when calling GamePad.GetState(). Unfortunately, I cannot reproduce it. I think it is a race condition or something like this, because as I said, it happens "rarely".

" at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)\r\n at Microsoft.Xna.Framework.Input.GamePad.PlatformGetState(Int32 index, GamePadDeadZone leftDeadZoneMode, GamePadDeadZone rightDeadZoneMode)\r\n at Microsoft.Xna.Framework.Input.GamePad.GetState(Int32 index, GamePadDeadZone leftDeadZoneMode, GamePadDeadZone rightDeadZoneMode)\r\n at Microsoft.Xna.Framework.Input.GamePad.GetState(Int32 index)\r\n at

In addition, it also occurs in the  Windows Desktop DX version. Here is the exception:
en SharpDX.Result.CheckError()
en SharpDX.XInput.Controller.GetCapabilities(DeviceQueryType deviceQueryType)
en Microsoft.Xna.Framework.Input.GamePad.PlatformGetCapabilities(Int32 index)
en Microsoft.Xna.Framework.Input.GamePad.GetCapabilities(Int32 index)
en NineWitches.Input.InputHandlerHelper.CalculateDirectionUsingGamePad(PlayerIndex playerIndex, GamePadStick stick) en C:\Users\DIEGO\Documents\nine-witches-family-disruption\Project\Shared\NineWitches\Input\InputHandlerHelper.cs:línea 21
en NineWitches.Input.PlayerCharacterInputHandler`1.OnHandleInput(GameTime gameTime) en C:\Users\DIEGO\Documents\nine-witches-family-disruption\Project\Shared\NineWitches\Input\PlayerCharacterInputHandler.cs:línea 97
en NineWitches.Input.ProfessorSoulInputHandler.OnHandleInput(GameTime gameTime) en C:\Users\DIEGO\Documents\nine-witches-family-disruption\Project\Shared\NineWitches\Input\ProfessorSoulInputHandler.cs:línea 33
en NineWitches.NWSession.OnHandleInput(GameTime gameTime) en C:\Users\DIEGO\Documents\nine-witches-family-disruption\Project\Shared\NineWitches\NWSession.cs:línea 304
en TinyEngine.Scene.HandleInput(GameTime gameTime) en C:\Users\DIEGO\Documents\nine-witches-family-disruption\Project\Shared\TinyEngine\Scene.cs:línea 99
en TinyEngine.TinyGame.Update(GameTime gameTime) en C:\Users\DIEGO\Documents\nine-witches-family-disruption\Project\Shared\TinyEngine\TinyGame.cs:línea 145
en NineWitches.NWGame.Update(GameTime gameTime) en C:\Users\DIEGO\Documents\nine-witches-family-disruption\Project\Shared\NineWitches\NWGame.cs:línea 335
en NineWitches.PlatformNWGame.Update(GameTime gameTime) en C:\Users\DIEGO\Documents\nine-witches-family-disruption\Project\NineWitchesWindowsDesktop\PlatformNWGame.cs:línea 67
en Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
en Microsoft.Xna.Framework.Game.Tick()
en MonoGame.Framework.WinFormsGameW

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1082

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:
- UWP
- Desktop DX

**Comment by diegohcanepa** [comment]
I suspect that one possible cause is that I was updating my input logic before calling base.Update(), so this might be a possible reason, because when you connect the controller, there are chances to hit the Update() call and this might cause the exception as monogame internally has some uninitialized stuff. Not sure, but has sense.

**Comment by mrhelmut** [comment]
It's likely not related to ```base.Update()```. The only thing that it does is updating ```Components```, which are not linked to inputs (unless you made your own input manager as a GameComponent and added to the game instance).

**Comment by diegohcanepa** [comment]
Thanks Thomas. My input manager is not a GameComponente. So, I think I fix nothing.

**Comment by mrhelmut** [comment]
Your issue makes me think of #7015.
It doesn't look related, but it seems to confirm that DirectInput might return invalid values under unforeseeable circumstances.

**Comment by diegohcanepa** [comment]
BTW, I'm using an XBox 360 wireless controller.

**Comment by squarebananas** [comment]
This might be because WGI.Gamepad.GamepadAdded and WGI.Gamepad.GamepadRemoved are possibly adding and removing gamepads from a different thread to the game tick where PlatformGetState is likely to be called. If the timing was right a gamepad could be removed from the dictionary while also accessing it for GetState/GetCapabilities.

It's difficult to prove but it might be worthwhile putting a lock statement around all references to the gamepads dictionary.

**Comment by nkast** [comment]
The race condition in GetState() for UWP has already been fixed by #7655.
