### ISSUE TITLE
.wav sound file not able to build on MonoGame 3.8

### ISSUE THREAD

**Issue by ryancheung** [MonoGame/MonoGame#7136]
Sound files (*.wav) are not able to build in MonoGame 3.8(develop branch). It raises build errors as the following:
```
You can invoke the tool from this directory using the following commands: 'dotnet tool run mgcb' or 'dotnet mgcb'.
Tool 'dotnet-mgcb' (version '3.7.200-develop') was successfully installed. Entry is added to the manifest file /Users/Ryan/monogame/Pong/Pong.DesktopGL/.config/dotnet-tools.json.
/Users/Ryan/monogame/Pong/Pong.DesktopGL/Content/Sound/1.wav
Failed to open file 1. Ensure the file is a valid audio file and is not DRM protected.
/Users/Ryan/.nuget/packages/monogame.content.builder.task/3.7.200-develop/build/MonoGame.Content.Builder.Task.targets(269,5): error MSB3073: The command "dotnet tool run mgcb /quiet /@:"/Users/Ryan/monogame/Pong/Pong.DesktopGL/Content/Content.mgcb" /platform:DesktopGL /outputDir:"/Users/Ryan/monogame/Pong/Pong.DesktopGL/Content/bin/DesktopGL/Content" /intermediateDir:"/Users/Ryan/monogame/Pong/Pong.DesktopGL/Content/obj/DesktopGL/Content" /workingDir:"/Users/Ryan/monogame/Pong/Pong.DesktopGL/Content/"" exited with code 1. [/Users/Ryan/monogame/Pong/Pong.DesktopGL/Pong.DesktopGL.csproj]
```
The build error: **Failed to open file 1. Ensure the file is a valid audio file and is not DRM protected.**

Test project: https://github.com/ryancheung/Pong

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8 (develop branch)

#### What operating system are you using:
- MacOS

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
Can confirm, it seems ffmpeg stuff don't get correct permissions:
```
chmod: changing permissions of '/usr/bin/ffprobe': Operation not permitted
chmod: changing permissions of '/usr/bin/ffmpeg': Operation not permitted
chmod: changing permissions of '/usr/bin/ffprobe': Operation not permitted
```

**Comment by ryancheung** [comment]
I saw that `ffmpeg` binaries are bundled into `dotnet-mgcb-editor`, why need to find them in `/user/bin` directory.

**Comment by ryancheung** [comment]
I just fixed this by `brew install ffmpeg`, but the `ffmpeg` brew package seems having infinite dependencies. It should be better to just use the bundled version.

**Comment by harry-cpp** [comment]
Feel blind for not looking at what the ffmpeg path was XD
