### ISSUE TITLE
Using MonoGame built from source on .NET Core

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#7145]
I'm having trouble building MonoGame from source and using it in a new .NET Core project. It's not clear to me what I need to do. Here's what I've done:

- Pulled the latest from develop.
- Run `dotnet build` on `MonoGame.Framework.DesktopGL.sln` and `MonoGame.Tools.Linux`.
- Installed the templates with `dotnet new -i Templates` while in the base repo folder.
- Created a new project with `dotnet new mgdesktopgl`.
- Build the project with `dotnet build` and get the following error:
```
MGEngine.csproj : error NU1102: Unable to find package MonoGame.Framework.DesktopGL with version (>= 3.8.0)
MGEngine.csproj : error NU1102:   - Found 6 version(s) in nuget.org [ Nearest version: 3.7.1.189 ]
MGEngine.csproj : error NU1101: Unable to find package MonoGame.Content.Builder.Task. No packages exist with this id in source(s): nuget.org
```
It looks like it doesn't have the MG nuget package installed, but I'm not sure how to install and use the one I've built from source. It looks like there's also a similar issue with the pipeline tool. What do I need to do to resolve this?

#### What version of MonoGame does the bug occur on:
- develop

#### What operating system are you using:
- Linux Mint 19.3 Tricia

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
When building from source you are supposed to reference local projects and not use nuget packages.

**Comment by tdeeb** [comment]
Can you provide an example or lead me in the right direction regarding this? For example, how can I get it set up to work nicely like the nuget package, including having content build with `dotnet build`? There's a lot of information out there for simply using the nuget packages but nothing from source.

**Comment by harry-cpp** [comment]
Add MG .csproj to your solution inside MonoGame.Framework folder, reference the project from another project.
