### ISSUE TITLE
Monogame Shared Library Project doesn't work

### ISSUE THREAD

**Issue by bootzin** [MonoGame/MonoGame#7152]
So.. I'm trying to make use of MonoGame's cross platform capabilities in VS2019, and I've seen a few tutorials about using a Shared Project to share code, and the issues regarding Content management for this.. That's when I saw the "MonoGame Shared Library Project" template.

It's description says it can be used to share code and content between projects, but how do I do that? I mean, even though the project comes with it's own Game1.cs and Content folder, you can't access them from within Visual Studio. You also can't add classes and folders to the project, nor can you add a reference to it from other projects (It doesn't even appear). I've also tried checking the properties and the .shproj file, but nothing seemed to make it work..

So my question is: how do I use it? Is there an issue regarding this template in VS2019, or am I doing it the wrong way? Should I stick to the normal C# shared project for this?

P.S.: I haven't checked if it works with VS2017, but I also don't have enough disk space on C: to install it, so I'd rather avoid this.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL, WindowsDX, Android

**Comment by harry-cpp** [comment]
GitHub Issues are meant for bug tracking/feature requests, use community.monogame.net for questions/discussions: https://community.monogame.net/

As for the actual question, this should be able to help you get your project properly set up:
https://github.com/harry-cpp/MonoGame/blob/newprojdocs/Documentation/setting_up_project/setting_up_project.md
