### ISSUE TITLE
Rectangle<T> class

### ISSUE THREAD

**Issue by awest03** [MonoGame/MonoGame#7153]
The current `Microsoft.Xna.Framework.Rectangle` class only provides option for integer values, this limits its usage to rendering and other low precision tasks. Which is fine regarding it's use cases.

What I am proposing is that we have a new `Rectangle<T>` class, so that it can store floats, doubles, etc. This will broaden the usage of the `Rectangle` class so that it can be used in precise calculations, such as physics engines, etc. And in order to keep compatability with the API we create a `Rectangle` class which inherits from `Rectangle<int>`. That way SpriteBatch and other functionalities would not need modification.

````csharp
public class Rectangle : Rectangle<int>
{
    // ...
}
`````

Or would it be more appropriate to create an interface for Rectangle<T>?

**Comment by mrhelmut** [comment]
Hello there!

```Rectangle``` is a ```struct```, not a ```class```, and that's by design. Rectangles are extremely frequently used types that is mandatory to be allocated on the stack, and not the heap to avoid garbage.

So anything like class or generics for this kind of types are to be avoided.

If you are looking into things like ```RectangleF```, you can check ```MonoGame.Extended``` which implements it (as a ```struct```).

**Comment by harry-cpp** [comment]
Structs can have a T specifier, haven't really played around with it, but: https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector-1?view=netcore-3.1

**Comment by awest03** [comment]
Just as a followup for future onlookers, I have since done significant research into the topic of Maths with Generics in C#. And I have created a little library to somewhat handle the Rectangle<T> concept. I’ll probably release it on nuget in the near future,
Thank you to everyone for responding to my issue so fast.
