### ISSUE TITLE
Can I upload directly .fx file?

### ISSUE THREAD

**Issue by j303-27** [MonoGame/MonoGame#7154]
For example:

Effect e = new Effect(GraphicsDevice, "file.fx");

//file.fx
float4x4 world_matrix; 
float4x4 view_matrix;  
float4x4 proj_matrix;
...
...
...

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by ryancheung** [comment]
No, you have to compile it to directX or openGL shader bytecode first.

**Comment by j303-27** [comment]
And compilation can be done on the fly? Without 2mgfx...

**Comment by ryancheung** [comment]
No, It can't, I belive. Even if it can, it is just not necessary, unless you want to change the shader source code while your game running.

**Comment by Jjagg** [comment]
@j303-27 you'll need MGFXC (we renamed 2MGFX) to compile a shader. You can include it in your game to build shaders on the fly and enable hot reload.
Gonna close this since it's not an issue, but feel free to continue the discussion.

**Comment by willmotil** [comment]
maybe this will help its old it used to work dunno if it still will.

https://community.monogame.net/t/solved-is-it-possible-to-directly-load-a-effect-from-a-class-files-string/10486
