### ISSUE TITLE
Rebuild on project root does not rebuild

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#7158]
If you right click and hit "Rebuild" on the root of the project in the MGCB Editor it does not rebuild the project:

![image](https://user-images.githubusercontent.com/103522/82759190-4f188280-9db1-11ea-809b-a374b36419b2.png)

However if i do it from the Build menu it does work....

![image](https://user-images.githubusercontent.com/103522/82759210-7a9b6d00-9db1-11ea-9895-f3d51f924fa2.png)

Both commands should have the same result of cleaning and rebuilding the entire project.

**Comment by margorski** [comment]
Hello, I've created pull request for that issue. Sorry for not mentioning that I'm working on that bug but it was so easy to fix that I fixed it during problem investigation.
