### ISSUE TITLE
Darken message text in filtered build output

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#7160]
The text in the filtered build output in the MGCB Editor is very hard to read...

![image](https://user-images.githubusercontent.com/103522/82759562-dcf56d00-9db3-11ea-997e-99c874424ac9.png)

We should darken this text or just make it the default text color.  The text is generally well formatted so color of the text could likely be normal.

**Comment by jojotrujillo** [comment]
Hey, @tomspilman! Could I take a crack at this? I've overviewed the Contributing file and I think I could handle this issue with my skillset. :smile:

**Comment by harry-cpp** [comment]
Why of course, go right ahead :)

**Comment by jojotrujillo** [comment]
I forgot to use one of those keywords to automatically close an issue. For future reference, do y'all prefer to close issues manually, or is it okay to automatically close an issue on merge?

**Comment by tomspilman** [comment]
@jojotrujillo - if you use the magic `Fixed #number` that works for us.

Going to close this now.
