### ISSUE TITLE
[Android] Content not packed into Apk after the first project build and debugging.

### ISSUE THREAD

**Issue by ryancheung** [MonoGame/MonoGame#7162]
Content only get packed into Apk at the first project build, or clean build then build. When you change some game code and Press F5 and let VS rebuild your project and repack Apk, the resulting Apk would not contain Contents. Then you have to clean the android project and then build it manually. This is kinda annoying on debugging.

Test project: https://github.com/ryancheung/Pong.Test
For fast testing, android fast deploy mode should be disabled to ensure changing game code and then F5 to run would do Apk repacking and upload it to android device, or you have to unplug your android device and plug it back.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1365-develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Android

**Comment by craigvt** [comment]
Just curious if any workarounds/updates have been discovered on this topic? Thanks.

**Comment by harry-cpp** [comment]
This has been fixed in the 3.8 stable.
