### ISSUE TITLE
Loading content fails when '#' is in the file name

### ISSUE THREAD

**Issue by Jure-BB** [MonoGame/MonoGame#7167]
Example: `var test = Content.Load<Texture2D>("tes#t");`

'#' character is lost in this method, by the Uri class:
https://github.com/MonoGame/MonoGame/blob/3e92fc7bff7b4c32edf1314e143a4b7de4fab161/MonoGame.Framework/TitleContainer.cs#L66 

MonoGame 3.8 (pre-release, build from source)
Platform: WindowsDX
OS: Windows 10

EDIT: `%20` character sequence also causes problems with Uri.

**Comment by tomspilman** [comment]
Interesting...  we used `Uri` as it is normally recommended for this sort of thing, but it seems like it disallows some characters that are allowed in file names on Windows.

It would be nice to have a proper implementation here and not depend on `Uri`.  But not sure what that would look like.

**Comment by Jjagg** [comment]
We've fixed the same issue in another part of the codebase in #5583.

**Comment by Jure-BB** [comment]
Changing `var uri = new Uri("file:///" + name);` to
`var uri = new Uri("file:///" + FileHelpers.UrlEncode(name));`
in the `NormalizeRelativePath` method fixes the issue, but I'm not sure it can never lead to double escaping the file name.

**Comment by Jjagg** [comment]
I don't know if there's a good reason to go through Uri. Not sure what it's supposed to do here since we still replace the directory separators afterwards. The following implementation should do the trick (including normalizing separators).

```
internal static string NormalizeRelativePath(string name)
{
    var uri = new Uri(System.IO.GetFullPath(name));
    return uri.LocalPath;
}
```

**Comment by Jure-BB** [comment]
@Jjagg It doesn't work, if "%20" is in the name. Also, it may be problematic for Unix-based systems: https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netframework-4.7.2#implicit-file-path-support

It seems that Uri class has many issues with local file system paths: https://stackoverflow.com/questions/1546419/convert-file-path-to-a-file-uri/35734486#35734486

Escaping name with FileHelpers.UrlEncode before passing in to Uri works for both # and %20. But I wonder, if using Uri class even makes sense.

**Comment by Jjagg** [comment]
Yeah, we shouldn't use Uri here IMO. We really only need to normalize directory separators I think.

**Comment by goosenoises** [comment]
@Jjagg In that case, is the intent here to just remove the Uri object? E.g. something like:

```
        internal static string NormalizeRelativePath(string name)
        {
            return name.Replace(FileHelpers.NotSeparator, FileHelpers.Separator);
        }
```

**Comment by Jjagg** [comment]
Yes, I believe that would be correct.

**Comment by tomspilman** [comment]
I think actually it does more than that.  I think the intent is to fix things like `"..\..\sub\folder\file"`.

**Comment by tomspilman** [comment]
Actually @goosenoises @Jjagg @Jure-BB ....

We have this other `FileHelpers.ResolveRelativePath`:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Utilities/FileHelpers.cs#L41

Which has unit tests that clearly accoung for `#`....

https://github.com/MonoGame/MonoGame/blob/develop/Tests/Framework/UtilitiesTest.cs#L46

While these helpers serve different purposes i think it shows how to fix the `Uri` call if we wanted to.

Also maybe some of this code could be shared?

**Comment by Jure-BB** [comment]
Adding FileHelpers.UrlEncode fixes it for me, but I have only tested it on Windows. 
```
internal static string NormalizeRelativePath(string name)
{
    var uri = new Uri("file:///" + FileHelpers.UrlEncode(name));
    var path = uri.LocalPath;
    path = path.Substring(1);
    return path.Replace(FileHelpers.NotSeparator, FileHelpers.Separator);
}
```
I can make a PR, if this looks good to you.

**Comment by goosenoises** [comment]
That makes sense. I think there are some parallels between this issue and one that's to be fixed in .NET 5: https://github.com/dotnet/runtime/issues/2162

I realize .NET 5 (and MG using .NET 5) are still a ways off, but want to check if my understanding is correct?

**Comment by Jure-BB** [comment]
@goosenoises It seem so me it serves the same purpose as NormalizeRelativePath method in MG. It's nice to see it's going to be added to the official API.
