### ISSUE TITLE
Publish error when using the PublishTrimmed flag

### ISSUE THREAD

**Issue by Emmsii** [MonoGame/MonoGame#7177]
An error occurs when publishing a MonoGame DirectX dotnet core project using the PublishTrimmed flag.

I created a new monogame project using the following command:
`dotnet new mgwindowsdx -o DirectX`

Then published the project with the following command:
`dotnet publish -r win-x86 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true`

This results in the following error:

`C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(83,5): error MSB6006: "dotnet.exe" exited with code -1073741819. [C:\Users\Matt\Documents\Code\mgcore\Test\DirectX\DirectX.csproj]`

The same error occurs when the PublishSingleFile flag is removed.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8 PreRelease

#### What operating system are you using:
- Windows 10 Pro - 1909

#### What MonoGame platform are you using:

- DirectX

**Comment by mrhelmut** [comment]
Hello,

If the error happens during ```publish``` this is very likely a .NET Core issue. ```PublishTrimmed``` and its associated trimmer (```Microsoft.NET.ILLink```) are still kind of experimental.

We have it working on full projects successfully, so we know that it's not related to MonoGame itself.

You might want to open an issue on the .NET Core repository.

**Comment by harry-cpp** [comment]
I'm gonna close this as there is literally nothing for us to do here.
