### ISSUE TITLE
app.manifest not configuring DPI scaling [3.8/DesktopGL/.NET Core 3.1].

### ISSUE THREAD

**Issue by goosenoises** [MonoGame/MonoGame#7181]
Running into an issue with a fresh DesktopGL project using .NET Core 3.1.

Currently on a 3000x2000 display with 200% scaling. This problem occurs regardless of how I run the project - whether it's `dotnet run`, or launching the .exe directly. I did see #7004 and #5784, but am still unable to get this working.

Using the [templates found on Nuget.](https://www.nuget.org/packages/MonoGame.Templates.CSharp/) In my app.manifest file, I have the following:

```
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity version="1.0.0.0" name="MgDpiTest.csproj"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel  level="asInvoker" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>

  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- A list of the Windows versions that this application has been tested on and is
           is designed to work with. Uncomment the appropriate elements and Windows will 
           automatically selected the most compatible environment. -->

      <!-- Windows Vista -->
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" />

      <!-- Windows 7 -->
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" />

      <!-- Windows 8 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" />

      <!-- Windows 8.1 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" />

      <!-- Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />

    </application>
  </compatibility>

  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">permonitorv2,permonitor</dpiAwareness>
    </windowsSettings>
  </application>

</assembly>
```

#### What version of MonoGame does the bug occur on:
- 3.8.0.1375-develop. Had the same issue with .NET Core 3.0 and MonoGame v3.7.

#### What operating system are you using:
- Windows 10, version 1903

#### What MonoGame platform are you using:

- DesktopGL

Any help is greatly appreciated. Thank you!

**Comment by mrhelmut** [comment]
What do you mean by "problem" ? Please describe what's happening and you would expect.

From my perspective, everything is working as intended and the manifest is properly attached to the template and activated at runtime by leaving DPI handling to the application.

**Comment by goosenoises** [comment]
Expected behavior is that the application would scale 200%, which is the behavior I had with previous versions (I believe I was using 3.6) of MonoGame. So for example, a 800x600 window would appear as 1600x1200 on my laptop (3000x2000 screen res with DPI scaling at 200%), but be 800x600 on my desktop (1920x1080 screen res with DPI scaling at 100%).

It's entirely possible I'm just not understanding what "expected" behavior is here; could you elaborate on the correct way DPI scaling is supposed to be handled, or point me to resources that go into detail?

**Comment by mrhelmut** [comment]
MonoGame now defaults to not scaling to the DPI and leaving DPI handling to the user. That is how most players expect their games to behave and is recommended. That's what is called "DPI Awareness".

If you wish that your game to not be DPI Aware and to scale with the Windows DPI, remove this from the manifest:
```
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">permonitorv2,permonitor</dpiAwareness>
    </windowsSettings>
  </application>
```

Please note that removing DPI awareness will likely produce blurred output (and possibly wrong mouse coordinates).

**Comment by goosenoises** [comment]
Got it, I misunderstood what those meant. You are correct, removing that did produce the behavior I was expecting. Thank you so much for taking the time to clarify! I can close the issue.
