### ISSUE TITLE
The "GetMGCBTask" task failed unexpectedly

### ISSUE THREAD

**Issue by aodendaal** [MonoGame/MonoGame#7189]
- Downloaded and installed MonoGame 3.7.1
- Created a new directory for a game
- Ran `dotnet new --install MonoGame.Template.CSharp`
- Ran `dotnet new mgdesktopgl`
- Ran `dotnet run`

**Expected:**
a window with the default background for MonoGame

**Actual**
`The "GetMGCBTask" task failed unexpectedly.`

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
There are no dotnet templates for 3.7, also MonoGame.Template.CSharp should not be used.

Instead you can use 3.8 dev templates: https://www.nuget.org/packages/MonoGame.Templates.CSharp/3.8.0.1375-develop
