### ISSUE TITLE
Calling DrawIndexedPrimitives and DrawInstancedPrimitives in succession causes problems.

### ISSUE THREAD

**Issue by OpenPachinko** [MonoGame/MonoGame#7193]
It may not occur depending on the calling sequence.
The behavior seems to be different between Android and DesktopGL.

I made a program to reproduce the problem.
https://github.com/OpenPachinko/MonogameCompareBehaviors

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1375-develop

#### What operating system are you using:
- MacOS
- Android

#### What MonoGame platform are you using:

- DesktopGL
- Android

**Comment by OpenPachinko** [comment]
After drawing, I tried saving it to a file with RenderTarget2D.SaveAsPng().
I did not notice it visually, but the first frame is normal.
The problem seems to occur from the second frame.

I used ObjectDumper.NET to get a dump of GraphicsDevice for the first and second frames and compared them, but there was no difference.

**Comment by OpenPachinko** [comment]
I modified GraphicsDevice.OpenGL.cs a little.
DesktopGL has improved a lot.
Android is still useless.

My main platform is Android,
Android is troubled because it cannot be solved by brute force...
```
        private void ApplyAttribs(Shader shader, int baseVertex)
        {
            var programHash = ShaderProgramHash;
            var bindingsChanged = false;

            for (var slot = 0; slot < _vertexBuffers.Count; slot++)
            {
                var vertexBufferBinding = _vertexBuffers.Get(slot);
                var vertexDeclaration = vertexBufferBinding.VertexBuffer.VertexDeclaration;
                var attrInfo = vertexDeclaration.GetAttributeInfo(shader, programHash);

                var vertexStride = vertexDeclaration.VertexStride;
                var offset = (IntPtr)(vertexDeclaration.VertexStride * (baseVertex + vertexBufferBinding.VertexOffset));

                //if (!_attribsDirty)
                //    if (_bufferBindingInfos[slot].VertexOffset == offset)
                //        if (ReferenceEquals(_bufferBindingInfos[slot].AttributeInfo, attrInfo))
                //            if (_bufferBindingInfos[slot].InstanceFrequency == vertexBufferBinding.InstanceFrequency)
                //                if (_bufferBindingInfos[slot].Vbo == vertexBufferBinding.VertexBuffer.vbo)
                //                    continue;
            

                bindingsChanged = true;

                GL.BindBuffer(BufferTarget.ArrayBuffer, vertexBufferBinding.VertexBuffer.vbo);
                GraphicsExtensions.CheckGLError();

                // If instancing is not supported, but InstanceFrequency of the buffer is not zero, throw an exception
                if (!GraphicsCapabilities.SupportsInstancing && vertexBufferBinding.InstanceFrequency > 0)
                    throw new PlatformNotSupportedException("Instanced geometry drawing requires at least OpenGL 3.2 or GLES 3.2. Try upgrading your graphics drivers.");

                foreach (var element in attrInfo.Elements)
                {
                    GL.VertexAttribPointer(element.AttributeLocation,
                        element.NumberOfElements,
                        element.VertexAttribPointerType,
                        element.Normalized,
                        vertexStride,
                        (IntPtr)(offset.ToInt64() + element.Offset));

                    // only set the divisor if instancing is supported
                    if (GraphicsCapabilities.SupportsInstancing) 
                        GL.VertexAttribDivisor(element.AttributeLocation, vertexBufferBinding.InstanceFrequency);

                    GraphicsExtensions.CheckGLError();
                }

                _bufferBindingInfos[slot].VertexOffset = offset;
                _bufferBindingInfos[slot].AttributeInfo = attrInfo;
                _bufferBindingInfos[slot].InstanceFrequency = vertexBufferBinding.InstanceFrequency;
                _bufferBindingInfos[slot].Vbo = vertexBufferBinding.VertexBuffer.vbo;
            }

            _attribsDirty = false;

            if (bindingsChanged)
            {
                Array.Clear(_newEnabledVertexAttributes, 0, _newEnabledVertexAttributes.Length);
                for (var slot = 0; slot < _vertexBuffers.Count; slot++)
                {
                    foreach (var element in _bufferBindingInfos[slot].AttributeInfo.Elements)
                        _newEnabledVertexAttributes[element.AttributeLocation] = true;
                }
            }
            SetVertexAttributeArray(_newEnabledVertexAttributes);
        }
```

**Comment by nkast** [comment]
This has been reported before, https://github.com/MonoGame/MonoGame/issues/6710#issuecomment-482672897

That is my one-line fix https://github.com/nkast/MonoGame/commit/dfb4efc60f418dbf47ea87cf31cc800148475062
although that's a quick hack, one should step-in the code and determine what actual flags/states need cleaning instead of mark them all for clearing...

**Comment by OpenPachinko** [comment]
Even on Android it was rendered unless I used GraphicsDevice.SetRenderTarget.
On Android, it seems to break if a RenderTarget other than null is specified.
By the way, with DesktopGL it looks like everything is fine.

**Comment by RonenNess** [comment]
@Jjagg @squarebananas are you guys sure this bug is fixed? I'm using latest stable MonoGame (from Nuget) with .net 5.0 and if I mix DrawIndexedPrimitives and DrawInstancedPrimitives in the same frame, the instanced rendering get messed up (looks like the transformation matrices are not copied properly?).

To verify its indeed due to the mix I tried commenting out just the 'DrawIndexedPrimitives' line and it fixes the issues with the instanced drawing, so its not related to the setup or my code - its the very call to DrawIndexedPrimitives that mess up future DrawInstancedPrimitives.

Is there an easy way to see if its the same issue, or any fix I can apply from my end?

Thanks,

**Comment by Apostolique** [comment]
The fix isn't yet released. You can install a development build if you want. https://learn-monogame.github.io/how-to/install-develop/

**Comment by RonenNess** [comment]
Ah sorry I mixed the opening date and the closing date and thought it was closed before the version release :)

Thanks for the info!
