### ISSUE TITLE
MGCB Editor does not add link to the start menu

### ISSUE THREAD

**Issue by harry-cpp** [MonoGame/MonoGame#7202]
On Windows, running `mgcb-editor --register` will not add a link to the start menu.

CC. @jnoyola

**Comment by jnoyola** [comment]
Sorry I guess I missed that! Based on the discussion in #6922, I didn’t realize that was a requirement. It sounded like registering was only supposed to associate the file extension.

> I wonder if we could have some sort of pipeline.exe /register or something that you can do to have it self register as the default handler for MG files.
