### ISSUE TITLE
Missing Menus in the Pipeline Tool

### ISSUE THREAD

**Issue by Rohan-Bansal** [MonoGame/MonoGame#7205]
I do not have the edit option menu or toolbar in the MonoGame Pipeline Tool (Linux). I cloned a sample DesktopGL project and opened `Content.mgcb` under the Content folder. This is what I see:

![mgpt](https://user-images.githubusercontent.com/36248672/84603677-0ea6a480-ae45-11ea-8169-9d9c0bd2775c.png)

I'm pretty sure this is what I'm supposed to be seeing (taken from [this](https://docs.monogame.net/articles/getting_started/3_adding_content.html) article): 

![Screenshot from 2020-06-14 13-47-36](https://user-images.githubusercontent.com/36248672/84603747-a0161680-ae45-11ea-9ad5-5d9de319664d.png)

#### Version of MonoGame the bug occurs on:
- MonoGame 3.7

#### What operating system I am using:
- Linux

#### What MonoGame platform I am using:

- DesktopGL

**Comment by harry-cpp** [comment]
That is how the MGCB Editor (aka. Pipeline Tool) looks on Linux now, totally normal.

**Comment by hsandt** [comment]
For those coming from https://docs.monogame.net/articles/getting_started/4_adding_content.html

> * Add Existing Item toolbar button
> * Edit > Add > Existing Item... menu button
> * right-click > Add > Existing Item... context menu

It means only the last option is available now (right-click). Too bad we don't have a shortcut button, but at least all the top-menu/toolbar menu items have an equivalent in some contextual menu item (Add Item/Folder), top bar icon (Build/Rebuild/Clean/New/Open) or Hamburger menu (Save As, Undo/Redo, Help, About, Quit).
