### ISSUE TITLE
Relative paths for references in MGCB doesn't work when building the .mgcb file from another folder

### ISSUE THREAD

**Issue by OAguinagalde** [MonoGame/MonoGame#7208]
When using the flag `/reference` with a relative path, if you build the .mgcb file from a different folder than the location it's in, it won't find the assemblies. This doesn't happen with other kind of contents, just with references. I think this is the reason.

```c#
[CommandLineParameter(
    Name = "build",
    Flag = "b",
    ValueName = "sourceFile",
    Description = "Build the content source file using the previously set switches and options. Optional destination path may be specified with \"sourceFile;destFile\" if you wish to change the output filepath.")
]
public void OnBuild(string sourceFile)
{
    // Make sure the source file is absolute.
    if (!Path.IsPathRooted(sourceFile))
        sourceFile = Path.Combine(Directory.GetCurrentDirectory(), sourceFile);
}
```

As shown in the snippet above, in the `OnBuild` function, **the full path of the resource is calculated and stored**. Later in the execution, when all the command/configuration has been parsed and the paths full paths have been generated, a loop goes through all the content generating the output files. The same thing happens on the `OnCopy` function.

It makes sense to do it, because if we are building files from different paths, then by the time the actual Build or Copy happens, there is no need to worry about the current directory, as the full paths have been generated in the initial parsing.

The problem comes when referencing an extern assembly by using the `/reference` flag. Contrary to what happens with Build and Copy content, the references full path is never calculated in the parsing phase, so when the times comes to actually load the assemblies, if the place where you are calling mgcb is different from the place where the .mgcb file is, then it won't find the assemblies (unless of course the references path are already a full path).

In this snippet it can be seen that the assembly references are just added as is, and no full path is generated

```c#
[CommandLineParameter(
    Name = "reference",
    Flag = "f",
    ValueName = "assembly",
    Description = "Adds an assembly reference for resolving content importers, processors, and writers.")
]

public readonly List<string> References = new List<string>();

bool SetOption(MemberInfo member, string value)
{
    {. . .}
    if (IsList(member))
    {
        // Append this value to a list of options.
        GetList(member).Add(ChangeType(value, ListElementType(member)));
    }
    {. . .}
}
```

For the sake of consistency, both content and references should have the same treatment and be able to added as relative paths.

#### What version of MonoGame does the bug occur on:
- MonoGame branch develop on May 28th (e7bd560)

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by harry-cpp** [comment]
You need to pass `/workingDir` argument to mgcb and specify what folder to use for building content.

**Comment by OAguinagalde** [comment]
I was actually doing that but it kept on failing. Apparently if the /w flag is issued before the content file it ignores the flag without error.

The help for mgcb reads like this and never mentions the order of commands.

```
MonoGame Content Builder
Builds optimized game content for MonoGame projects.

Usage: mgcb <Options>

Options:
  /w, /workingDir:<directoryPath>   The working directory where all source content is located.
```
When it's written like this, the build happens but it fails to locate the references (the other content is generated properly)

```ps1
> .\mgcb\mgcb.exe /workingDir:$workingDirectory .\Game\Content\Content.mgcb
```
The same command with the working directory at the end like this works.

```ps1
>.\mgcb\mgcb.exe .\Game\Content\Content.mgcb /workingDir:$workingDirectory
```

I guess it's fixed now, but I still think it would be better to calculate the full path  for references the same way as it's done with the other content, just for consistency.

In any case, thanks for the quick reply! 👍

**Comment by harry-cpp** [comment]
Ah, yes, /@ basically just gets replaced with all the commands in the .mgcb file, like if you were typing in more arguments.
