### ISSUE TITLE
ContentLoader looking in the wrong directory

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [MonoGame/MonoGame#7212]
Hi there,
I updated to MonoGame 3.8.0.1375-develop for `MonoGame.Framework.WindowsDX` and `MonoGame.Framework.Content.Pipeline`. Now during the build I get the following error:

```
"C:\Program Files\JetBrains\JetBrains Rider 2019.2.3\plugins\dpa\DotFiles\JetBrains.DPA.Runner.exe" --handle=8300 --backend-pid=6200 --detach-event-name=dpa.detach.8300 "C:\Program Files\dotnet\dotnet.exe" C:/Users/.../bin/Release/netcoreapp3.1/PiX.dll
Unhandled exception. Microsoft.Xna.Framework.Content.ContentLoadException: The content file was not found.
 ---> System.IO.FileNotFoundException: Content\font.xnb
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\...\bin\Release\netcoreapp3.1\Content\font.xnb'.

...
```

The content loader is looking for the content in `bin/Release/netcore3.1/` but the builder packs all into `bin/Windows/`. I can't set platform to `netcore3.1`. So what is the right thing to do here?

Thanks for your great work,
Cheers,
Georg

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1375-develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX with .NET Core 3.1

**Comment by jnoyola** [comment]
When you build the content on its own it will place it in `bin/Windows/`, but when you build a game it expects it to be copied into the game's output folder (`bin/Release/netcore3.1/`).

Are you using the `MonoGame.Content.Builder.Task` nuget package? That should handle it for you.

**Comment by georg-eckert-zeiss** [comment]
I use `<PackageReference Include="MonoGame.Content.Builder" Version="3.7.0.9" />`. Is that wrong?

**Comment by georg-eckert-zeiss** [comment]
I use `<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.0.1375-develop" />` - but it is still looking in that netcore3.1 directory.

**Comment by georg-eckert-zeiss** [comment]
I upgraded to `<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.0.1375-develop" />` and it seems to work. Thank you : )

**Comment by georg-eckert-zeiss** [comment]
Yeah. That worked. Thank you : )
