### ISSUE TITLE
Window.TextInput : Could not load type if the project is referenced by another project

### ISSUE THREAD

**Issue by damarindra** [MonoGame/MonoGame#7213]
The hierarchy of the project

- LibGame

    - MonoGame.Framework.Portable

- Game_DesktopGL 

    - referenced to LibGame

    - MonoGame.Framework.DesktopGL

Whenever you access Window.TextInput in LibGame, it will throws an error `System.TypeLoadException: Could not load type 'Microsoft.Xna.Framework.TextInputEventArgs' from assembly 'LibGame, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' due to value type mismatch.`.

**Why I need this?**

I'm currently creating extension that support editor function, I'm using ImGUI.Net. So, right now, I need to call this code manually inside the main Game_DesktopGL project. 
```
Window.TextInput += (sender, args) =>
{
	if (args.Character == '\t') return;
				
	ImGuiRenderer.GetIOPtr.AddInputCharacter(args.Character);
};
```

So, any solution, or this is a bug?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL
- Portable

**Comment by Jjagg** [comment]
MonoGame.Framework.Portable is deprecated. Currently you can reference the DesktopGL library in a shared project and reference the right platform library in the game project. 

For some discussion on this topic see #7086. Feel free to weigh in. Going to close this for now.
