### ISSUE TITLE
Update MonoGame UWP SDK target

### ISSUE THREAD

**Issue by BMarques** [MonoGame/MonoGame#7220]
On Visual Studio 2019, Windows SDK 18362 is the default that is installed by the Visual Studio Installer. MonoGame is still targeting Windows SDK 17763 though... Is there any specific reason for that?

![image](https://user-images.githubusercontent.com/5073823/85939370-bf647780-b90c-11ea-8263-43f9ae2bbf04.png)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1365

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsUWP

**Comment by BMarques** [comment]
@Jjagg, if it's ok with you, I can give this one a try :)

**Comment by Jjagg** [comment]
Sure, thanks!

**Comment by BMarques** [comment]
From what I see, what needs to be updated to target sdk 18362 is:

- MonoGame.Framework.WindowsUniversal.csproj 
- MGNamespace.csproj (In the templates folder)

Anything else?

Sadly I don't know how to build a vsix to test the updated template locally, any documentation that I can follow?

**Comment by harry-cpp** [comment]
You can submit a PR and pick up artifacts from the build bot, just mark the PR as WIP.

**Comment by BMarques** [comment]
@harry-cpp How can I mark it as WIP?

**Comment by harry-cpp** [comment]
I've done it for you.
