### ISSUE TITLE
Assimp64 not found

### ISSUE THREAD

**Issue by jnoyola** [MonoGame/MonoGame#7229]
See [this forum post](https://community.monogame.net/t/problem-with-fbximporter-in-3-8-0-1375-develop-build/12777).

I haven't experienced this myself, but it looks like there are issues loading the Assimp64 lib on Windows and Linux with the new MGCB.Task and this should probably be fixed for 3.8.

I believe it's related to the working directory changing in the new task, and maybe caused by Assimp loading native libraries based on working directory instead of relative path, since copying Assimp64.dll to the MGCB working directory fixed this on Windows.

#### What version of MonoGame does the bug occur on:
- 3.8.0.1375-develop

#### What operating system are you using:
- Windows, Linux

#### What MonoGame platform are you using:

- all? looks like at least WindowsUWP and DesktopGL based on forum post

**Comment by harry-cpp** [comment]
Should be fixed by https://github.com/MonoGame/MonoGame/pull/7184
