### ISSUE TITLE
prerequisites for building from source

### ISSUE THREAD

**Issue by cpt-max** [MonoGame/MonoGame#7235]
If you build a fresh clone of MonoGame in Visual Studio, without .Net Core installed, you get build errors. I think this should be mentioned in the Requirements link in README.md. Currently it only mentiones Linux requirements:

https://github.com/MonoGame/MonoGame/blob/develop/REQUIREMENTS.md

But then there is this page from the documentation that does mention it:

https://github.com/MonoGame/MonoGame/blob/2a83a3b94c131d962bacb9833080b2f5b03c2b40/Documentation/articles/introduction/requirements.md

Merge those two pages into one?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by Jjagg** [comment]
We should remove the requirements.md file here and point to build documentation in the repo readme, maybe with a short version in the readme itself.

**Comment by RicoGuerra** [comment]
I am on this issue now. There is just one little obstacle. The requirements.md file doesn't exist in my forked repo so I am not able to delete it.
![Bild_2021-03-26_130749](https://user-images.githubusercontent.com/77100998/112629192-4448d700-8e34-11eb-986c-0801f2455a5a.png)
