### ISSUE TITLE
Unable to start the Pipeline tool (3.8)

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7236]
I installed 3.8 and now I'm unable to start the Pipeline tool, I've tried:

* From VS
* Doble clicking mgcb file
* Manually from Start menu
* As administrator
* From command prompt

The window simply fails to open (does appear to try and run but fails)

Are there any logs or command-line overrides that can be used to get more details as to why it's not starting?

I uninstalled 3.8 and reinstalled the latest 3.7.1 and confirmed that build does indeed run.

P.S. Will try from source later.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1082

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- N/A

**Comment by harry-cpp** [comment]
3.8.1082 is like 10 months old release. Installers have been dropped, the Downloads page needs a bit of updating. You can install the newest development build using nuget.

**Comment by SimonDarksideJ** [comment]
If that's the case they they do need updating in short order :D  even I wasn't aware we had completely changed to NuGet.

**Comment by SimonDarksideJ** [comment]
Help me out here @harry-cpp , where is the new pipeline tool then?  I've installed the new extension, which includes the latest Platform + Content-Builder packages.  But no pipeline tool is available?

How is the new pipeline tool installed?

**Comment by harry-cpp** [comment]
https://docs.monogame.net/articles/tools/pipeline.html

Also gonna close this.

**Comment by SimonDarksideJ** [comment]
You beat me to closing it @harry-cpp , but we definitely need a task created to urgently update the website and avoid simple issues like this 🗡️ 

I know it's been a while since I was fully MonoGaming, but even I was caught out :D
