### ISSUE TITLE
"MonoGame Windows Desktop Application (Windows DirectX)" template raises warning on new project

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7238]
After creating a new "MonoGame Windows Desktop Application (Windows DirectX)" project using the latest extension, the following warning appears:

> Microsoft.NET.Sdk.WindowsDesktop requires 'UseWpf' or 'UseWindowsForms' to be set to 'true'	MonoGame Windows Desktop Application (Windows DirectX)	C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.NET.Sdk.WindowsDesktop.targets	96	

Seems there is an issue in the .targets file for the template

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsDX

**Comment by roy-t** [comment]
I was able to get rid of this warning by adding `  <UseWPF>true</UseWPF>` to a propertygroup in my csproj file. I guess this is needed if we really need to include the WindowsDesktop target.

**Comment by Jjagg** [comment]
Should be UseWindowsForms, PR most welcome :)

**Comment by SimonDarksideJ** [comment]
Needs to reopen as the fix didn't replicate through to the actual templates, as such, the issue still exists.
@harry-cpp / @tomspilman can you reopen please.
