### ISSUE TITLE
MonoGame 3.8 WindowsDX package does not work with netstandard projects

### ISSUE THREAD

**Issue by roy-t** [MonoGame/MonoGame#7241]
I've got an extremely simple netstandard2.0 project referencing the latest `MonoGame.Framework.WindowsDX` package

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.0.1375-develop" />
  </ItemGroup>
</Project>
```

In this case I cannot use any of the MonoGame/XNA classes:

`The type or namespace name 'Xna' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)`

I can fix this by either:
- Using the GL version of the package
- Using target framework netcoreapp3.1

So far I have been unable to figure out why this happens.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1375-develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- WindowsDX

**Comment by harry-cpp** [comment]
WindowsDX targets .netcoreapp, this is normal.

If you wish to make a .NET Standard library, check out the `mgnetstandard` template.

**Comment by roy-t** [comment]
This leaves me completely puzzled, the reason for .netstandard is to share code between .net core and .net framework. If I use the DX version in my .net framework app/libraries, I can't use a .netstandard library that references the GL version, right? 

I must be completely missing something :)

I also looked at the templates and it seems right now there is no WindowsDX library project template so its hard to discover this issue.

**Comment by harry-cpp** [comment]
The MG .NET Standard library template is using bait and switch approach.
