### ISSUE TITLE
mgcb no longer detects changes to files included in a shader

### ISSUE THREAD

**Issue by roy-t** [MonoGame/MonoGame#7243]
I use the following set-up to keep my shaders manageable.

shader.fx:
```
// some stuff

#include "shaderpart.hlsl"
```

Only shader.fx is included in my content.mgcb file.

On MonoGame 3.7 whenever I make changes to shaderpart.hlsl the content pipeline automatically builds shader.fx on the next build. However on MonoGame 3.8.0.1469-develop this does not happen. And I have to make a change to shader.fx before it will build again. 

I guess the content processor for fx files no longer adds an `ExternalReference` for external files included in shaders?

Edit: I think I found the commit that broke this. In https://github.com/MonoGame/MonoGame/commit/4e48966a00a4833d802d284ff395c6b54417a605#diff-e31429c4281a413276a0b823cdf19e38 the following few lines of code have been removed/replaced in `EffectProcessor.cs`

```
            // Parse the MGFX file expanding includes, macros, and returning the techniques.	
            ShaderResult shaderResult;	
            try	
            {	
                shaderResult = ShaderResult.FromFile(options.SourceFile, options, 	
                    new ContentPipelineEffectCompilerOutput(context));	

                // Add the include dependencies so that if they change	
                // it will trigger a rebuild of this effect.	
                foreach (var dep in shaderResult.Dependencies)	
                    context.AddDependency(dep);	
            }
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1469-develop

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- WindowsDX

**Comment by tomspilman** [comment]
> Edit: I think I found the commit that broke this. 

@roy-t - Yep you are right.

Specifically this code was removed...
```
                // Add the include dependencies so that if they change
                // it will trigger a rebuild of this effect.
                foreach (var dep in shaderResult.Dependencies)
                    context.AddDependency(dep);
```

@harry-cpp how should this be fixed now?

**Comment by harry-cpp** [comment]
I'm not sure, effectprocessor no longer has any information about the effect that is being processed, instead it just calls the effect compiler.

Maybe just a fast regex parsing of `#include` is enough so it knows which content to watch?

**Comment by tomspilman** [comment]
> Maybe just a fast regex parsing of `#include` is enough so it knows which content to watch?

That could work...  we just have to recursively open all the includes too.  As an include can have other includes in it.

Another option is to have MGFXC.exe dump out a second file with dependency info we can read and use.  Would also be a good solution for other teams that may want to plug in MGFXC into their own custom pipelines.

**Comment by roy-t** [comment]
I came to the same conclusion when trying to see if I could create a merge request with a fix.  For now  I've created a custom EffectProcessor that works well enough for my own project. 

I'm not sure if it captures all possible syntaxes for including a file. So I would not consider it production proof yet. It does handle recursive includes (which my project also has) nicely. Theoretically there could be a cycle of includes but if I recall correctly the fx compiler won't like that either :).


```
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Microsoft.Xna.Framework.Content.Pipeline;
using Microsoft.Xna.Framework.Content.Pipeline.Graphics;
using Microsoft.Xna.Framework.Content.Pipeline.Processors;

namespace MiniEngine.ContentProcessors
{
    [ContentProcessor(DisplayName = "MiniEngine :: Multi File Effect Processor")]
    public sealed class MultiFileEffectProcessor : EffectProcessor
    {
        private static Regex IncludeRegex = new Regex("^#include\\s\"(?<file>.*)\"", RegexOptions.Multiline);

        public override CompiledEffectContent Process(EffectContent input, ContentProcessorContext context)
        {
            var depencencies = ProcessFile(Path.GetDirectoryName(input.Identity.SourceFilename), input.EffectCode);

            foreach (var depencency in depencencies)
            {
                context.AddDependency(depencency);
            }

            return base.Process(input, context);
        }


        private static List<string> ProcessFile(string effectDirectory, string effectCode)
        {
            var dependencies = new List<string>();
            var includes = IncludeRegex.Matches(effectCode).Select(m => m.Groups["file"].Value);

            foreach (var include in includes)
            {
                var path = Path.GetFullPath(Path.Combine(effectDirectory, include));
                dependencies.Add(path);
                dependencies.AddRange(ProcessFile(Path.GetDirectoryName(path), File.ReadAllText(path)));
            }

            return dependencies;
        }
    }
}
```
(Code is part of my engine at https://github.com/roy-t/MiniRTS which is MIT licensed, feel free to use or adapt it)

**Comment by harry-cpp** [comment]
You missed an infinity loop XD

**Comment by roy-t** [comment]
Ha you're right. I was thinking about cycles but ofc this code runs before the fx compiler. I've updated the code in the above comment.

**Comment by harry-cpp** [comment]
https://github.com/MonoGame/MonoGame/pull/7244 should fix this.

**Comment by roy-t** [comment]
Sweet, that was quick. Looks good to me!
