### ISSUE TITLE
Cannot completely uninstall Mono/MonoGame/MonoDevelop

### ISSUE THREAD

**Issue by JansthcirlU** [MonoGame/MonoGame#7248]
I have recently given MonoGame and MonoDevelop a try for game development, but I decided to uninstall. I managed to uninstall MonoGame and MonoDevelop, but for some reason the MonoGame Pipeline Tool icon still persists. When I right-click to Show Details about the icon, the Ubuntu software manager says it doesn't exist. Typing `whereis mono` yields `mono: /usr/lib/mono /etc/mono` and sudo rm -rf'ing doesn't seem to do the trick. How can I completely uninstall and clear all mono-related files and folders?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Ubuntu 18.04 LTS

#### What MonoGame platform are you using:
- MonoGame for Linux
- MonoGame Pipeline Tool

**Comment by harry-cpp** [comment]
Run the uninstall command in terminal, `monogame-uninstall`.

**Comment by JansthcirlU** [comment]
I don't think you understand, I managed to uninstall everything BUT the Pipelines tool, therefore trying to run yields a `monogame-uninstall: command not found` error.

**Comment by harry-cpp** [comment]
Give me the output of the following stuff:

```
which monogame-pipeline-tool
```

```
cat /usr/share/applications/MonogamePipeline.desktop
```

```
ls /opt/MonoGameSDK
```

**Comment by JansthcirlU** [comment]
Here you go:

```
which monogame-pipeline-tool
/usr/bin/monogame-pipeline-tool
```
```
cat /usr/share/applications/MonoGamePipeline.desktop
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=MonoGame Pipeline Tool
GenericName=MonoGame Pipeline Tool
Comment=Creates platform specific content files.
Exec=monogame-pipeline-tool %F
TryExec=monogame-pipeline-tool
Icon=monogame
StartupNotify=true
Terminal=false
Type=Application
MimeType=text/x-mgcb;
Categories=Development;
StartupWMClass=Pipeline
```
```
ls -l /opt/MonoGameSDK
lrwxrwxrwx 1 root root 34 mei  7 21:09 /opt/MonoGameSDK -> /usr/lib/mono/xbuild/MonoGame/v3.0
```
(That's 7 May 9:09 PM Belgian time)

**Comment by harry-cpp** [comment]
Try:

```
cd /opt/MonoGameSDK
sudo ./uninstall.sh
```

**Comment by harry-cpp** [comment]
Also `ls -l /opt/MonoGameSDK/` if that does not work, I forgot a slash at the end XD

**Comment by JansthcirlU** [comment]
Strangely, I cannot navigate to `/opt/MonoGameSDK`:

```
cd /opt/MonoGameSDK
bash: cd: /opt/MonoGameSDK: No such file or directory
```
Adding a slash doesn't work either:
```
cd /opt/MonoGameSDK/
bash: cd: /opt/MonoGameSDK/: No such file or directory
```

**Comment by harry-cpp** [comment]
I assume you deleted the mono directory manually?

**Comment by JansthcirlU** [comment]
I think so, yeah.

**Comment by harry-cpp** [comment]
Well, thats the problem, never do that with Linux system files, always let the package manager / uninstall script handle that for you.

Download the following script with sudo, and you should get everything removed properly: https://github.com/MonoGame/MonoGame/blob/v3.7.1/Installers/Linux/RUN/uninstall.sh

**Comment by JansthcirlU** [comment]
Sorry, I'm still a linux newbie, could you run me through the steps to do that?

**Comment by JansthcirlU** [comment]
Sorry, I think I figured it out. However, I get the following error:

```
touch: cannot touch '/opt/MonoGameSDK/x-mgcb.xml': No such file or directory
xdg-mime: file '/opt/MonoGameSDK/x-mgcb.xml' does not exist
```

**Comment by harry-cpp** [comment]
Delete the following stuff:
```
sudo rm -f /usr/bin/monogame-pipeline-tool
sudo rm -f /usr/bin/monogame-uninstall
sudo rm -f /usr/bin/mgcb
sudo rm -f /etc/bash_completion.d/mgcb
sudo rm -rf /usr/share/icons/gnome/scalable/mimetypes/monogame.svg
sudo rm -rf /usr/share/applications/Monogame\ Pipeline.desktop
sudo rm -rf /usr/lib/mono/xbuild/MonoGame
sudo rm -rf /opt/MonoGameSDK
```

**Comment by harry-cpp** [comment]
> Sorry, I think I figured it out. However, I get the following error:

Ah, yea, you broke the symlink and the original file, just comment out lines 22 and 23.

**Comment by JansthcirlU** [comment]
Thanks! That worked! Next time I'll make sure to read the docs before doing anything rash!
