### ISSUE TITLE
Two conflicting Utility API namespaces within MonoGame namespace

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7254]
Whilst reviewing the API documentation, there seems to be two conflicting/overlapping namespaces in the MonoGame codebase, which could lead to confusion:

MonoGame.Framework.Utilities
MonoGame.Utilities

IMHO, there should only be a single MonoGame Utilities namespace to avoid confusion
(There is also a MonoGame.Utilities.Deflate namespace that will need aligning)

Given the breaking nature of MonoGame 3.8, it would be advisable to align these for the 3.8 release.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8 Development

**Comment by SimonDarksideJ** [comment]
@tomspilman / @Jjagg 
If you want to pick which namespace should live and which should be updated, let me know and I'll do a PR (while I wait for the docs PR to build)

**Comment by Jjagg** [comment]
This should probably all be in the Mg.Framework.Utilities namespace since the public classes are in that ns (except the BinaryReader/WriterEx which should be moved).

**Comment by SimonDarksideJ** [comment]
OK, I'll update what is there to 

> MonoGame.Framework.Utilities

Not sure about the BinaryReader/WriterEx, that should probably be its own PR
