### ISSUE TITLE
Fix missing nuget package descriptions

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#7259]
A few of the new package descriptions on NuGet are blank...

![image](https://user-images.githubusercontent.com/103522/88603701-43f50380-d03b-11ea-9595-946e360101d3.png)

Specifically dotnet-mgcb , MonoGame.Content.Builder.Task, dotnet-mgfxc,

**Comment by Jjagg** [comment]
Relevant .csproj files need a `Description` property added.

**Comment by SimonDarksideJ** [comment]
I'll take a look at it @Jjagg / @tomspilman
