### ISSUE TITLE
Updating MonoGame.Samples for 3.8

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7270]
Starting a discussion to get a heads of agreement on a plan to update the samples to 3.8

My initial thoughts are as follows:

* Review and close-out existing PR's for 3.7
* Commit current examples to a 3.7 branch
* Update develop branch samples to 3.8
* Create an updated sample template using 3.8 pattern
* Review new samples for 3.8

Weigh in below (before we start)

**Comment by SimonDarksideJ** [comment]
Thoughts @tomspilman / @Jjagg / @harry-cpp ?

**Comment by harry-cpp** [comment]
Can you move this issue to the samples repo?

**Comment by SimonDarksideJ** [comment]
moving discussion to 
https://github.com/MonoGame/MonoGame.Samples/issues/50
