### ISSUE TITLE
Adding a mgwindowsdx dotnet core project to a solution fails on Linux

### ISSUE THREAD

**Issue by Kwyrky** [MonoGame/MonoGame#7274]
#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1375-develop

#### What operating system are you using:
- Linux Mint 19.3 Tricia / Windows 10

#### What MonoGame platform are you using:

- WindowsDX (mgwindowsdx dotnet core template) 

I installed the templates with
`dotnet new --install MonoGame.Templates.CSharp`

When using the following commands to create a new solution and a new project using the dotnet core mgwindowsdx template it works but when adding the project to the solution it fails with a error message.

```
dotnet new sln -n ProjectMGDC
dotnet new mgwindowsdx -n ProjectMGDC.Windows
dotnet sln add ProjectMGDC.Windows/ProjectMGDC.Windows.csproj
```

```
Invalid project `/home/kwyrky/Desktop/ProjectMGDC.Windows/ProjectMGDC.Windows.csproj`. The imported project "/usr/share/dotnet/sdk/3.1.302/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.WinFX.props" was not found. Confirm that the expression in the Import declaration "Microsoft.WinFX.props" is correct, and that the file exists on disk.  /usr/share/dotnet/sdk/3.1.302/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props.
```

**Comment by harry-cpp** [comment]
Nothing for us to do here, thats how dotnet tool works, you can't add projects to solutions which you don't have the needed targets for installed (ie. xamarin ios, xamarin android, uwp).

Probably gonna get better with .NET 5 and 6.

**Comment by Kwyrky** [comment]
Oh OK good to know. That's why the same commands work on windows but not on Linux. I assumed I could build the project and then run it later on windows. I guess then I will start using the cross platform project which is based on OpenGL or if I use the mgwindowsdx project from Linux to just add the project to the solution later. Thank you for the info!
