### ISSUE TITLE
Adding IEffectBones interface to the collection of Effect interfaces

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#7286]
In order to simplify Effects management, there's a number of interfaces that abstract the way effects are setup, these include: IEffectMatrices, IEffectFog, etc.

I would like to add yet another interface for the collection, with this definition:

```c#
public interface IEffectBones
    {
        int MaxBones { get; }
        void SetBoneTransforms(Matrix[] boneTransforms);
    }
```

This interface would be implemented by SkinnedEffect.

It's a trivial addition, so if there's agreement I can do the pull request myself.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
I'm fine with this.
@tomspilman @harry-cpp

**Comment by vpenades** [comment]
Additionally, and planning in advance, another interface for morph targets would be desirable:

```c#
Interface IEffectMorphing
{
int MaxWeights { get; }
void SetMorphWeights(float[] weights);
}
```

**Comment by vpenades** [comment]
Added a PR for IEffectBones: #7344

There's no point adding an IEffectMorphing interface right now because, as discussed in #7341, morphing animation support in MonoGame is currently not possible.
