### ISSUE TITLE
In 3.8, PreferredBackBufferWidth/Height no longer works

### ISSUE THREAD

**Issue by 01yakiek** [MonoGame/MonoGame#7298]
The options PreferredBackBufferWidth and PreferredBackBufferHeight appears to be no longer working after upgrading to 3.8. I tried this on a new project. Was there some kind of change or is there another way to change window size?

`public Game1() {
    // not working
    _graphics = new GraphicsDeviceManager( this ) {
        PreferredBackBufferWidth = 512
        , PreferredBackBufferHeight = 512
    };
    Content.RootDirectory = "Content";
    IsMouseVisible = true;

    // not working either
    this._graphics.PreferredBackBufferWidth = 512;
    this._graphics.PreferredBackBufferHeight = 512;
    this._graphics.ApplyChanges( );
}`

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
Set it in `Initialize` and call `ApplyState`.
