### ISSUE TITLE
Documentation inconsistancy.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#7300]
Applys to all platforms all systems.

The issue is a point of confusion for new people and for reference potentially leading to a failed registration of the pipeline tool.

Under getting started.

found here.
https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_windows.html

At the bottom of the page marked Optional which (should be marked Recommended).
Seen before the more detailed instructions with cavets for installing and registering the pipeline tool later on.

> 
> To register the MGCB Editor tool with Windows and Visual Studio 2019, run the following from the Command-Prompt.
> 
> dotnet tool install --global dotnet-mgcb-editor
> mgcb-editor --register

Doesn't match the more detailed instructions.

Found at the bottom here.
https://docs.monogame.net/articles/tools/mgcb_editor.html

> The MGCB Editor is published as a .NET Core tool, Make sure you have the .NET Core SDK installed if you wish to install the editor. You can download it here.
> 
> In a command prompt/terminal window, run the following command to install the MGCB Editor:
> 
> dotnet tool install -g dotnet-mgcb-editor
> 
>     For development branches, you will need to ensure you have the dev channel NuGet registered and include the version number in the command, for example:
> 
>     dotnet nuget add source -n MonoGame http://teamcity.monogame.net/guestAuth/app/nuget/feed/_Root/default/v3/index.json
> 
>     dotnet tool install --global dotnet-mgcb-editor --version 3.8.0.1476-develop
> 
> After installing mgcb-editor run the following to register the MGCB Editor as the default app for mgcb files.
> 
> mgcb-editor --register

People using the new version and 2019 are going to use the first set of instructions which can fail.
They may not read further to the segment titled tools editor when it doesn't work for the next step after getting started in sequence.

1) Their should **only** be one area for installation instructions for any specific thing listing all possible configurations and cavets.
2) Other places where there is a required awareness of these instructions should linked to that location.
3) If the majority of use cases apply to a specific topic or a link.
Then that item should **not** be marked _optional_ but instead either Suggested, Recommended, Standard, or Requisite reading.   

Something that implys that you should now click to here to ensure you have set everything up for your platform.

**Comment by harry-cpp** [comment]
> People using the new version and 2019 are going to use the first set of instructions which can fail.

It can't fail. And those are the exact same instruction for stable release, except the mgcb-editor tool page, unlike the getting started page, tells you a bit more.

**Comment by harry-cpp** [comment]
Also getting started section is special, you don't want to drag a person through a thousand pages, just go over that one page and you are done with your dev setup.

**Comment by willmotil** [comment]
That's exactly my point **the bit more** should be earlier rather then later ... 
and it failed for me i posted the screen shots to you of it failing when i followed those instructions with out adding the dev version.

**Comment by harry-cpp** [comment]
You wrote 2 walls of text, but you have yet to explain your issue properly. Just explain your issue properly, in one sentence, ie:

```
dotnet tool install --global dotnet-mgcb-editor did not work
```

**Comment by willmotil** [comment]
argg i thought i was defending my point.

**Comment by jnoyola** [comment]
> It failed for me i posted the screen shots to you of it failing on discord, when i followed those instructions with out adding the dev version part listed later on in the second link.

Small note: if I remember correctly, I believe this was because the full release was not yet available, so the only way to install this tool was using the teamcity feed for the prerelease version. That type failure shouldn't ever be possible anymore, and it makes sense to want to hide these prerelease steps in the more detailed page.

But I don't want to get into whether we should maintain two sets of similar instructions for different purposes.

**Comment by willmotil** [comment]
The real point is to avoid confusion such as in this post.
the guy here actually thought the pipeline tool doesn't come with the new version of monogame.

https://community.monogame.net/t/monogame-3-8-prerelease-packages-are-up-on-nuget/12708/131

**Comment by jnoyola** [comment]
> The guy here actually thought the pipeline tool doesn't come with the new version of monogame.

I'm not sure I follow. In fact, I don't understand your statement in the forum:

> When you download the newer versions of the monogame nuget the pipeline tool comes with it.
It will replace the old one.

I don't think this is true. The MonoGame.Framework.DesktopGL package is separate from the dotnet-mgcb-editor package. I wouldn't say it comes with it, and I wouldn't say it replaces the old one. I _would_ say that it's a separate tool that you should install and use instead of the old one. Are we talking about different things, or just explaining the same thing with different words?

___

> Has this been verified on a brand new install

I think the 480 downloads according to nuget.org are good evidence that people are successfully getting this to work.

**Comment by willmotil** [comment]
> 
> 
>     When you download the newer versions of the monogame nuget the pipeline tool comes with it.
>     It will replace the old one.
> 
> I don't think this is true. The MonoGame.Framework.DesktopGL package is separate from the dotnet-mgcb-editor package. I wouldn't say it comes with it, and I wouldn't say it replaces the old one. I would say that it's a separate tool that you should install and use instead of the old one. Are we talking about different things, or just explaining the same thing with different words?

Yes your right that is a incorrect statement the old one is still in there, i got that mixed up a bit.

Not that it matters much as there is only one default tool / editor that is registered to windows to open a text file with a .mgcb extension though.  I had used the template extensions at the time as per the getting started page i have no idea if that maybe failed because i still had vs 2017 in but this Editor is the one that has the crashing bug though i can't remember were the heck it is in the file system.

**Comment by jnoyola** [comment]
I think the extra step you needed to get it to work was adding that teamcity nuget feed. But now that the full release is available on nuget.org, I think it really is that simple.

P.S. Harry also moved up the MGCB Editor instructions on the Getting Started page so it's no longer marked as optional.
