### ISSUE TITLE
RenderTarget2D.GetSharedHandle();  null reference exception

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#7305]
After upgrading from 3.8.0.1375-develop to 3.8.0.1641, RenderTarget2D.GetSharedHandle(); throws a null reference exception.

It was working fine with the develop version.

#### What version of MonoGame does the bug occur on:
- MonoGame.Framework.WindowsDX 3.8.0.1641

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by harry-cpp** [comment]
> What version of MonoGame does the bug occur on:
>
> MonoGame.Framework.WindowsDX 3.8.0.1641
>
> What MonoGame platform are you using:
>
> DesktopGL

Those are some contradictory information there XD

**Comment by vpenades** [comment]
> Those are some contradictory information there XD

Endeed, fixed

**Comment by harry-cpp** [comment]
@nkast @Jjagg Ping

**Comment by Jjagg** [comment]
Ah, I think the native resource is only created on demand since nkast's last PR in this area. GetSharedHandle should create the texture first if it isn't created yet.

I didn't know we had this API :o

**Comment by nkast** [comment]
@Jjagg do you think we need to override this method for MSAA rendertargets?

**Comment by nkast** [comment]
@vpenades Can you check the #3.8.0.1667-develop ?

**Comment by vpenades** [comment]
@nkast Sorry, I can't check it right now, but the code that uses the GetSharedHandle method is based on this:

https://github.com/craftworkgames/MonoGame.WpfCore

**Comment by Jjagg** [comment]
> @Jjagg do you think we need to override this method for MSAA rendertargets?

I don't know why anyone would need it, so IMO we should hold off until someone requests it with an actual use case.
