### ISSUE TITLE
Need access to ResetRenderTargets() on WindowsUWP

### ISSUE THREAD

**Issue by AidanMcK** [MonoGame/MonoGame#7308]
For Windows, Mac, Linux, iOS and Android (and possibly others), a call to GraphicsDevice.Present() allows for rendering something and presenting it to the screen manually.
e.g.
```
1) render a "please wait..." message
2) call GraphicsDevice.Present()
3) do some time consuming stuff
```
The "please wait..." message will get shown on the platforms mentioned above before the time consuming stuff happens.

This does not work on Windows Universal (UWP) for some reason (just get a blank screen). However this works:
```
1) call GraphicsDevice.ResetRenderTargets()
2) render a "please wait..." message
3) call GraphicsDevice.Present()
4) do some time consuming stuff
```
The problem is that GraphicsDevice.ResetRenderTargets() is not accessible.

So it would be nice to have access to that function, or some other way to achieve this.

UAPPlatform.BeforeDraw() also would suffice, as is it just calls GraphicsDevice.ResetRenderTargets(), but it does not seem to be accessible either. That function has the following comment: "For a UAP app we need to re-apply the render target before every draw." 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- WindowsUWP

**Comment by mrhelmut** [comment]
I'm going to investigate but exposing a private API doesn't sounds quite right to me. I'd rather look into why ```Present()``` might not work properly (though I have my guess: UWP has a forced Vsync and that may mess things up).

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
