### ISSUE TITLE
Target netcoreapp3.1 in addition to netstandard2.0

### ISSUE THREAD

**Issue by kerams** [MonoGame/MonoGame#7310]
This will allow for the conditional use of new .NET Core APIs that are not included in .NET Standard. The most interesting are probably `System.Buffers.ArrayPool` (superseding `MonoGame.Framework.Utilities.ByteBufferPool`) and many new method overloads in the BCL with `Span` parameters, which might be handy for reducing allocations in some hot paths (I'm guessing as I don't know the internals of MonoGame).

**Comment by harry-cpp** [comment]
Switching to a newer target framework would not be helpful:
- The only public platforms which are netstandard2.0 is DestkopGL
- BRUTE requires older C# version to port your games to consoles
- netcoreapp3.1 is a bad request in general, netcoreapp3.1 is a target framework, not a C# version, meaning .netstandard 2.1 has all those features you are requesting
- Fragmentation of code for specific platforms without any performance benefits, actually fragmentation of code between the same platform for different frameworks, that would be a nightmare to maintain
- etc. Its morning :)

**Comment by kerams** [comment]
> The only public platforms which are netstandard2.0 is DestkopGL

WindowsDX already targets .NET Core 3.1, so were you to conditionally compile optimized code for that runtime, consumers of the package would reap the benefits immediately (if they're compiling for .NET Core 3.1, that is), but those of DesktopGL wouldn't.

> BRUTE requires older C# version to port your games to consoles

If it doesn't use code compiled for the .NET Core runtime (which is where the optimizations would be - `Span` is in C# 7.2), then there's no problem.

> netcoreapp3.1 is a bad request in general, netcoreapp3.1 is a target framework, not a C# version, meaning .netstandard 2.1 has all those features you are requesting

Did I say it was? `netstandard2.1` is not a C# version either for that matter.

> Fragmentation of code for specific platforms without any performance benefits

The whole point of doing this would be potential performance benefits and as I've said, you'd generally 'fragment' small parts of a method in hot paths - there'd be no large codebase split to speak of. Nedless to say, if it isn't possible to identify places where the extra APIs would provide a meaningful optimization, then sure, adding adding the TFM is useless.

protobuf-net is making good use of this concept for instance. [This part of csproj](https://github.com/protobuf-net/protobuf-net/blob/01c00be3e12eca861715f9313f2ffb06e46e2868/src/protobuf-net.Core/protobuf-net.Core.csproj#L26-L28) defines constants for specific features of .NET Core 3.1, which then get used for [small-scale, focused optimizations](https://github.com/protobuf-net/protobuf-net/blob/e645160c7c78a224d06de25f22a33e634a56291a/src/protobuf-net.Core/ProtoWriter.State.cs#L107-L127) when compiling for that runtime.

**Comment by mrhelmut** [comment]
It's not as simple as a language version. Some of the newer features are not just syntactic sugars and rely internally on BCL types that are simply not present in older BCLs. IL code may be portable, but the BCL in itself isn't. Console versions of MonoGame support any IL/compiler but are bound to the .Net 4.5 BCL.
We could allow higher language versions and manually checking every PR if it uses .Net 4.5+ types but this is not a manageable scenario and could lead to human errors breaking consoles. Limiting the language features is a convenient way that we can automate in the tests to make 100% sure that the BCL limits are endorsed in every PR.

It is planned to upgrade the console BCL (and therefore lift these limits) but this is quite a giant work, so it is a very slow process with no due date.

**Comment by kerams** [comment]
That makes it a little more clearer, but I still don't understand one thing. If consoles only support .NET 4.5 BCL, doesn't it mean that they use a version of MonoGame built for the "legacy" .NET? Then if anyone tries to use a feature that is incompatible with that framework, the version of MonoGame for the corresponding target would not compile in the first place, no?

**Comment by mrhelmut** [comment]
Yes, we could for instance have a "dummy" ```net452``` target just for the tests to check if it compiles and would ensure that those limitations are within checks.
