### ISSUE TITLE
Is WindowsDX supported in new MG3.8 netstandard2.0 project?

### ISSUE THREAD

**Issue by discosultan** [MonoGame/MonoGame#7315]
I noticed I'm unable to build a MonoGame 3.8 netstandard2.0 project when targeting WindowsDX. Steps to reproduce:

1. Run:

```sh
dotnet new mgnetstandard
```

2. In .csproj, change from:

```xml
<PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.0.1641">
  <PrivateAssets>All</PrivateAssets>
</PackageReference>
```

to

```xml
<PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.0.1641">
  <PrivateAssets>All</PrivateAssets>
</PackageReference>
```

3. Run:

```sh
dotnet build
```

The build will fail as it's unable to find any of the MonoGame types.

Is this a known limitation? Should I use `netcoreapp3.1` instead?

**Comment by Jjagg** [comment]
We reference WinForms, so the MG.F.WindowsDX project can't target netstandard2.0. Instead we multitarget netcoreapp3.1 and net452. Neither of those is compatible with .NET Standard 2.0.

Libraries can target the DesktopGL runtime however and things will work out when consuming projects reference the WindowsDX runtime. At runtime the WindowsDX lib will be used. 

We've had discussions about designing this so it isn't as confusing as it is right now in #7086. See specifically https://github.com/MonoGame/MonoGame/pull/7086#issuecomment-609095046 for two alternatives to the current situation. Feel free to weigh in with what would work best for you as well.

**Comment by discosultan** [comment]
Thank you for a prompt reply @Jjagg!

I'm glad that targeting a DesktopGL library from a WindowsDX application works the way you described. In my case, my library also includes monogame content assets (embedded into the dll) built specifically for target platform. Therefore, instead of getting rid of the WindowsDX library project (and only keeping a DesktopGL one), I will resort to targeting netcoreapp3.1 from my WindwosDX project instead.
