### ISSUE TITLE
NetStandard Library includes content files but is missing a MonoGame.Content.Builder.Task reference

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7318]
When creating a new shared NetStandard project it includes a default Content file.  However, as the NetStandard project does not have a reference to the MonoGame.Content.Builder.Task package, this Content file cannot be built

Either:

* The default Content file/folder needs removing from the template - or
* The MonoGame.Content.Builder.Task reference needs adding to the NetStandard template

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
This is just a warning. It's been there for a long time, to catch cases where the content reference is not set up properly. With the warning people can catch the error at build time, rather than getting a `ContentLoadException` at runtime.

**Comment by SimonDarksideJ** [comment]
Fair enough, but seems Content can't be accessed via the shared project either. Unless I've done something completely stupid :D

**Comment by SimonDarksideJ** [comment]
Issue update following discussion on Content file use/availability in NetStandard Libraries.  Likely the same affects the Xamarin shared project template too.

**Comment by roy-t** [comment]
I ran into this today. Adding these two lines to the project file seems to do the trick.
```
<MonoGameContentReference Include="Content\Content.mgcb" />
<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.0.1641" />
```

After that the content in the library project was built correctly, and when this project was referenced by another project the copy was copied to the correct output directory.

**Comment by SimonDarksideJ** [comment]
Yes, that was the point @roy-t , it needs adding to the NetStandard library project definition.

**Comment by harry-cpp** [comment]
How would .NET Standard library task know which platform the content is meant for? I thought the point was to reference Content.mgcb from the main project.

**Comment by SimonDarksideJ** [comment]
Check the updated Samples branch, where the content is contained within the shared project, which then builds it for whichever platform is being built at the time
https://github.com/MonoGame/MonoGame.Samples/tree/3_8_upg/Platformer2D

**Comment by harry-cpp** [comment]
I'm gonna have to test that out... not sure how its building it for the correct platform and not always for DesktopGL.

**Comment by SimonDarksideJ** [comment]
Well, in testing. Everything seems to build and run fine.

**Comment by SimonDarksideJ** [comment]
Retracting after a lengthy discussion. Library projects should NOT be used for building content.
Certainly, host the files and .mgcb in the library project folder and use a relational reference in platform projects
