### ISSUE TITLE
Setting buffer size doesn't work in Game's constructor

### ISSUE THREAD

**Issue by Bxil** [MonoGame/MonoGame#7319]
When PreferredBackBufferHeight or PreferredBackBufferWidth is set in Game's constructor it will not perform the resize on DesktopGL even when ApplyChanges is called. It works with DX.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL, WindowsDX

**Comment by AliciaRaven** [comment]
I also came across this issue when upgrading to 3.8. I found an acceptable work around is to simply move that code to the Initialize method instead and there is no noticeable difference in behaviour

**Comment by Jjagg** [comment]
Duplicate of #7298.
Fixed in #7299. This will be in the 3.8.1 release.

Please check existing issues before opening a new one.
