### ISSUE TITLE
Glitches when starting mgcb from VS2019

### ISSUE THREAD

**Issue by pirota-pirozou** [MonoGame/MonoGame#7331]
After installing MonoGame 3.8, when I created an empty Game project on WindowsDX, (or DesktopGL) , I found out that
I saw a yellow caution mark on the package dependencies and it seems the package is not installed correctly.

Those packages are two of the following:
 MonoGame.Content.Buider.Task (3.8.0.1641)
 MonoGame.Framework.WindowsDX (3.8.0.1641)

The cases I've encountered seem to be rare, and most people seem to be working correctly, and I didn't find anyone writing about the same problem. I checked the activity log for error output.
When running mgcb, I got the error “The MonoGame content tools only work on a 64-bit OS.”
But my OS is Windows 10 Pro (64bit).
I thought dotnet.exe was suspicious and looked at my PATH and found it in C:\Program Files (x86)\dotnet.
I removed that directory from my PATH and made sure my PATH was in the 64bit dotnet.exe file, and then I found the created When I opened the project, I was able to build it with no errors!

I would like to see a fix so that when VS2019 starts mgcb via dotnet.exe, the 64-bit version of dotnet.exe does start correctly and no cause problems.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX
- DeskTopGL

**Comment by harry-cpp** [comment]
We don't support 32 bit dotnet sdk with the mgcb tool.

**Comment by leeviana** [comment]
Thank you for finding and posting this! I had the exact same repro with the same setup, where I got that mgcb error on a 64-bit OS. I removed the C:\Program Files (x86)\dotnet from my system PATH to fix the issue. :)
