### ISSUE TITLE
MGCB-Editor about page needs some love

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7332]
A minor niggle, but the title on the MGCB-Editor about page should be more friendly.

![image](https://user-images.githubusercontent.com/1793042/91238159-4d55b680-e734-11ea-9059-be6efa84634f.png)

The text layout also needs formatting.

Might also be good to add a link to the MGCB-Editor documentation guide.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

**Comment by harry-cpp** [comment]
Duplicate of #6242
