### ISSUE TITLE
Issue with DrawIndexedPrimitives NOT rendering data

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7346]
Finishing off Riemers first 3D series, where the tutorial walks through the use of Index and Vertex buffers (instead of arrays)

When using the old XNA DrawIndexedPrimitives function below, everything works fine:

```csharp
_device.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, 0, _vertices.Length, 0, _indices.Length / 3);
```

However, as the above method is marked as obsolete, it recommends using the shorter version below.  BUT THIS DOES NOT WORK?

```csharp
_device.DrawIndexedPrimitives(PrimitiveType.TriangleList, _vertices.Length, 0, _indices.Length / 3);
```

Am I missing something, as it would appear the new function is just a shorter version of its older counterpart, but it doesn't seem to work or something else is needed (apart from setting the buffers) to make it work?

Ideas?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by peon501** [comment]
Try this one
_device.DrawUserIndexedPrimitives(PrimitiveType.TriangleList, vertsData, 0, noVertices/3, vertsIndicesData, 0, noTriangles / 3, VertexPositionNormalTexture.VertexDeclaration);

**Comment by rejurime** [comment]
When you use ```DrawIndexedPrimitives``` you previously need to do ```_device.SetVertexBuffer(_vertices);```
I leave you an example where we draw a cube using vertex and index, there are several examples we are working on.
https://github.com/tgc-utn/tgc-monogame-samples/blob/develop/TGC.MonoGame.Samples/Samples/Tutorials/Tutorial2.cs

**Comment by SimonDarksideJ** [comment]
The code IS setting the vertex / index buffers as you can see here:

https://github.com/SimonDarksideJ/XNAGameStudio/blob/a590b6bd193c98e2a6076c6fb65b5b4cc820b91f/MonoGameSamples/Riemers/Series_1_Terrain/Game1.cs#L247

But if I switch that line from :

```
_device.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, 0, _vertices.Length, 0, _indices.Length / 3);
```

To

```
_device.DrawIndexedPrimitives(PrimitiveType.TriangleList, _vertices.Length, 0, _indices.Length / 3);
```

It does not work.

But I'll check your example for reference @rejurime

Feel free to grab that sample and try it yourself :D

**Comment by SimonDarksideJ** [comment]
In looking at your code @rejurime , you aren't passing the Vertex buffer size, in the parameters, instead you are specifying 0
```
GraphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, 0, NumberOfIndices / 3);
```
Will have to try that

**Comment by SimonDarksideJ** [comment]
Thanks @rejurime , your sample did help solve it, I was simply using the wrong value for BaseVertex and incorrectly read it as VertextBuffer size and not offset/begin.

**Comment by peon501** [comment]
I had problem with IndexElementSize
`bufferIndex  = new IndexBuffer(device, IndexElementSize.SixteenBits, indices.Length, BufferUsage.WriteOnly);`
fixed with:
`bufferIndex  = new IndexBuffer(device, IndexElementSize.ThirtyTwoBits, indices.Length, BufferUsage.WriteOnly);`

**Comment by SimonDarksideJ** [comment]
Yeah, that is due to the Reach / HiDef profiles.  Reach is a maximum 16 bits, Hidef is 32. (Difference between Singles and floats too in buffers)
