### ISSUE TITLE
iOS - User music is interrupted when application launches

### ISSUE THREAD

**Issue by Nezz** [MonoGame/MonoGame#735]
In any MonoGame project, the user music is interrupted when the application is started. This should not be happening and does not happen for standard MonoTouch projects.
Happens when Alc.MakeContextCurrent (_context); is called on the OpenALSoundController.

**Comment by danzel** [comment]
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Sound.html
Check "Scenario 3", I think we should just need to change the AVAudioSessionCategory before initialising OpenAL.

Also ref https://developer.apple.com/library/ios/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionBasics/AudioSessionBasics.html#//apple_ref/doc/uid/TP40007875-CH3-SW1

**Comment by Andreyul** [comment]
Game developer can call `AVAudioSession.SharedInstance().SetCategory(AVAudioSessionCategory.Ambient);` in `UIApplicationDelegate.FinishedLaunching()`. `SoloAmbient` is the default.

**Comment by hrkm** [comment]
This is still an open issue, but applying Andreyul suggestion I was able to have my app to play sound effects alongside the background music played from iTunes. I think this can be closed now.

**Comment by tomspilman** [comment]
@dellis1972 @KonajuGames - Can someone look into this for 3.6?

**Comment by tomspilman** [comment]
This is fixed and the work around is for the developer to change the category as described in...

https://github.com/MonoGame/MonoGame/issues/735#issuecomment-179740858
