### ISSUE TITLE
dotnet add reference and dotnet run not working for mgandroid project

### ISSUE THREAD

**Issue by Kwyrky** [MonoGame/MonoGame#7350]
Using dotnet / .NET Core CLI with the commands to generate an Android the project can't be build or added to a solution, also no reference can be added because the targets file is missing.

Everything is working when creating a solution in Visual Studio 2019 and adding the generated project there. I can then build and run / deploy the android app to an android emulator.

```
$ dotnet new mgandroid -o MyGame
The template "MonoGame Android Application" was created successfully.
$ cd MyGame/
$ dotnet run
C:\Program Files\dotnet\sdk\3.1.401\Xamarin\Android\Xamarin.Android.CSharp.targets(51,5): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.401\Xamarin\Android\Xamarin.Android.Common.targets" was not found. Confirm that the expression in the Import declaration "Xamarin.Android.Common.targets" is correct, and that the file exists on disk. [C:\Users\<user>\MyGame\MyGame.csproj]
The build failed. Fix the build errors and run again.
```

- MonoGame 3.8
- Windows 10
- Android

**Comment by harry-cpp** [comment]
Not a bug, you have to use msbuild to build Xamarin.Android projects.

With .NET 6 you'll be able to work with Xamarin.Android projects from dotnet CLI.

**Comment by Kwyrky** [comment]
Oh I see. The schedule for .NET 6 is November 2021... So that will take a while.
