### ISSUE TITLE
Built games not working inside Windows 7 vm.

### ISSUE THREAD

**Issue by gameunite** [MonoGame/MonoGame#7355]
I tried to build and run it inside my windows 7 vm and nothing happens. No error, no window appeared, nothing. 

On my windows 10 vm, dx and gl versions works fine but it runs around 30-40 fps. My dx11 program runs over 60fps. So maybe there's a problem with dx11 implementation?

I tried making an empty scene in unity and runs in both of my vm and it works perfectly. Stable at 60fps in vsync on.

i7 4690k
32GB RAM
GTX 1060

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8
and also in
- develop branch

#### What operating system are you using:
- Windows 7 64bit and Windows 10 64 bit

#### What MonoGame platform are you using:

- WindowsDX, DesktopGL

**Comment by harry-cpp** [comment]
Not a bug or featue request, ask these questions on the forum: https://community.monogame.net

**Comment by gameunite** [comment]
Can you explain to me why this is not an issue here? I've been working as a developer for over 20 years and this seems like an issue to me. Even the xenko build is working perfectly inside the vm.

Celeste which looks like running in monogame doesn't work too.

**Comment by harry-cpp** [comment]
Your issue is probably gonna be either missing dx stuff, bad vm drivers, or something similar, easiest solution is to ask on the forums.

Also Celeste does not use MonoGame on Windows.
