### ISSUE TITLE
Effect compilation fails via Wine on Linux Mint 20

### ISSUE THREAD

**Issue by kimimaru4000** [MonoGame/MonoGame#7360]
I followed all instructions from [the documentation](https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_ubuntu.html#optional-set-up-wine-for-effect-compilation) on setting up Wine for effect compilation, but it's not working and gives me no error messages. Here's an image of the output I see:

![MGCB Linux Effect Error](https://user-images.githubusercontent.com/1388037/94316336-abfc9300-ff73-11ea-97ae-6cee5c8f82c2.png)

Even if I run it in debug mode or through a terminal, I don't see an error message to indicate what fails. I've quadruple checked the `MGFXC_WINE_PATH` in both **~/.profile** and **~/.zprofile** and they're correct.

#### What version of MonoGame does the bug occur on:
- develop

#### What operating system are you using:
- Linux Mint 20 Ulyana

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
Disable the output filtering by clicking on the gear in the top right corner on build output, and unchecking filter output, and tell give me the error message.

**Comment by tdeeb** [comment]
This is what I get:
```
Build started (redacted)

(redacted)/Desktop/Test/Test/Content/File.fx
(redacted)/Desktop/Test/Test/Content/File.fx: 

Build 0 succeeded, 1 failed.

Time elapsed 00:00:03.82.
```
File.fx is a newly generated Effect file from the pipeline tool.

**Comment by Apostolique** [comment]
I don't if that helps but this pipeline sets up wine to compile shaders: <https://github.com/Apostolique/Texo/blob/master/.github/workflows/release.yml>.

**Comment by hsandt** [comment]
Following @Apostolique 's answer, here is the part that may interest you for a local setup:

$ wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/develop/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | bash

The documentation, unfortunately, only mentions the process for the master branch. If you use the develop branch, you must run the equivalent setup script on the develop branch. I think this should be indicated on both https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_ubuntu.html and https://www.monogame.net/downloads/ > Development Builds as it's easy to forget.

If you only use master script, as of today, only netcore 3 will be installed and you'll end up with an error when running mgfxc:

> It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
>  - The following frameworks were found:
	  3.1.3 at [C:\windows\system32\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
>  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win7-x64

(and if you don't pay attention to the C:\ path it's very weird as you don't understand it's using Wine, and NET 5 should already be installed on Linux at this point)

with the develop script, you'll get net 5 on your Wine install as expected.
