### ISSUE TITLE
 Pipeline Extension cant reslove external assambly.

### ISSUE THREAD

**Issue by gronken** [MonoGame/MonoGame#7368]
I have a nuget Newtonsoft.Json included in my Pipeline Extension project. Between my pypeline extension project and my DesktopGL project i have a NetStandard Library. Everything compiles fine but when i try to use my pipeline to content lode a file it fails as the nuget json library cant be found. 

`System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The file can not be found.`

If i manualy copy the Newtonsoft.Json.dll from my .nuget location to the build folder of my pypeline extension it all works fine.

I have tested this on 3 different computers one with a clean install of everything.

**as stated by persn in this problemsolving thread** https://community.monogame.net/t/pipeline-extension-3-8-not-finding-nuget-files/13808/3
_I’m guessing it doesn’t resolve the assembly because the Pipeline editor probably loads your assembly by reflection and then it can’t correctly resolve dependencies or somethings. It’s possible that this can be resolved, I urge you to open a issue on the GitHub repo about it._

#### What version of MonoGame does the bug occur on:
MonoGame 3.8.0.1641

#### What operating system are you using:
Windows 10

#### What MonoGame platform are you using:

Pipeline Extension, NetStandard Library or DesktopGL

**Comment by jrunestone** [comment]
I think this is one of many reports related to #6942

**Comment by gronken** [comment]
> I think this is one of many reports related to #6942

Maybe but this issue did not exsist for me in MonoGame 3.7.1 and before.

**Comment by SimonDarksideJ** [comment]
Thoughts @harry-cpp / @Jjagg , we seem to have a regression issue with MGCB with regards to pipeline references

**Comment by harry-cpp** [comment]
It's not a regression, its just that .NET Core does not copy nuget references to output folder by default.

**Comment by gronken** [comment]
> It's not a regression, its just that .NET Core does not copy nuget references to output folder by default.

Well i kinda had a feeling i did something wrong! 
Im sorry i bothered all of you.

As this issue is the intended default behavior .NET Core ill close this.

**Comment by supermoosefgc** [comment]
In case anybody runs into this post via googling for this issue (as there seems to be quite a few) this is the quick way to fix this (if its the wrong way please feel free to correct me ;)

First, edit the csproj file of your pipeline extension project manually with a text editor and add this line to the <PropertyGroup>...</PropertyGroup> block:

<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

Rebuild your project

Then in the MGCB Tool add the 3rd party DLLs as references like so (they should be in the same ...\Debug folder as your main library DLL after rebuilding)

![image](https://user-images.githubusercontent.com/1892207/97132661-e2f5ce00-1704-11eb-9f95-a554f8d921e4.png)

**Comment by persn** [comment]
Maybe `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` should be added to the project template?

**Comment by SolarIceMedia** [comment]
supermoosefgc paranoid much ? not like paths to directories on your computer is useable by anyone other than you.
