### ISSUE TITLE
Bug in SoundEffectInstance.Pause on Windows 

### ISSUE THREAD

**Issue by nillkitty** [MonoGame/MonoGame#7372]
If you Pause() a SoundEffectInstance, and then Stop() it while it's paused,  you can never pause it again.   

If you look at the code in SoundEffectInstance.OpenAL.cs you'll see that neither `PlatformStop()` nor `PlatformPlay()` reset the `pauseCount` and a `pauseCount` > 0 will prevent you from actually pausing the sound again in `PlatformPause()`, no matter how many times you stop or restart it.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
DesktopGL

**Comment by KelsamGames** [comment]
Also seeing this in MonoGame 3.8

Simple code to reproduce: [https://community.monogame.net/t/sound-effect-instance-pause-breaks-down/13904](https://community.monogame.net/t/sound-effect-instance-pause-breaks-down/13904)

Out of curiosity, what is actually the point of the counter? Why would we want the Play/Pause to ever fail even if the code had called Pause repeatedly and Resume only once or what have you (which is what the counter appears to be for).

**Comment by tevenson** [comment]
I'm using 3.7.1.189 and the .Play() and then .Stop() doesn't work for me.
