### ISSUE TITLE
[MGCB] dotnet mgcb resolves relative path for reference assemblies incorrectly

### ISSUE THREAD

**Issue by persn** [MonoGame/MonoGame#7377]
My .mgcb file uses relative paths to find the pipeline extensions assembly, which works fine when I build from the mgcb-editor or through the csproj task builder.
`/reference:..\Hero6.MonoGame.Pipeline\bin\$(Config)\netstandard2.0\Hero6.MonoGame.Pipeline.dll`

However, attempting to build manually from the command line using `dotnet mgcb` then it can't find my pipeline extensions assembly anymore because it resolves the path incorrectly.
`dotnet mgcb /@:src/Hero6.Content/Hero6.Content.mgcb /config:Debug /platform:DesktopGL`

Because of the `..\` in the path, it will navigate up one step from where `dotnet mgcb` was invoked and use that as the base of the relative paths.

**What is happening:** It uses the disk location where `dotnet mgcb` was invoked from the command line as the root of the relative path.

**What I expect to happen:** It should use the location of the .mgcb file as the root of the relative path.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL

**Comment by harry-cpp** [comment]
You need to specify /workingDir argument.
