### ISSUE TITLE
Math to MathF

### ISSUE THREAD

**Issue by aXu-AP** [MonoGame/MonoGame#7382]
Suggestion to change calls to Math to MathF. Saves extra casts and is likely more performant.
For example from Matrix.cs:
`float num = (float) Math.Cos((double) angle);`
Could be changed to:
`float num = MathF.Cos(angle);`

Or does Monogame still need to have .Net Framework support? MathF is in Core, Standard and 5.

**Comment by TechnologicalPizza** [comment]
There could be a fake MathF class that's only included on platforms without the real MathF.

Honestly, there is plenty of room for modernization in MonoGame and there should realistically be a whole to-do list of modernization tasks, especially now when MonoGame is starting to embrace .NET Core.

**Comment by initram** [comment]
None of the current target frameworks support MathF. Monogame currently target .net framework and netstandard2.0.

But I guess a new target framework could be added, maybe dot net 5 as that will be released soon.

**Comment by TechnologicalPizza** [comment]
WindowsDX seems to be the only one on Core3.1 actually. Unsure why DesktopGL is on Standard2.0 and not Core.

**Comment by initram** [comment]
This issue should be reopened again i think. I would like to give it another try. If a pull request that does not lower precision would be accepted.

**Comment by tomspilman** [comment]
> This issue should be reopened again i think. I would like to give it another try. If a pull request that does not lower precision would be accepted.

@initram i would be good with that.  @mrhelmut  @nkast  ?
