### ISSUE TITLE
How to assign textures to a Texture2D array?

### ISSUE THREAD

**Issue by NET-D3v3l0p3r** [MonoGame/MonoGame#7383]
Hello,

I am trying to pass an array of textures to the shader - but how excactly am I supposed to assign the individual textures to the texture array?

I know, Texture2D offers a constructor that allows me to specify the array size, but how exactly do I set the values?
I tried using "Texture2D.SetData<Texture2D>(new Texture2D[]{a, b, c, ...});" but this doesn't work, because T must be non-nullable. 

Best regards,

**Comment by minimalism** [comment]
Use the SetData overload that accepts an index parameter, like so:
```List<byte[]> bytesList = Foo.GetRawBytesForEachArraySlice();
Texture2D = new Texture2D(device, Width, Height, false, SurfaceFormat.Color, bytesList.Count);
for (int i = 0; i < bytesList.Count; i++) {
    Texture2D.SetData(0, i, null, bytesList[i], 0, bytesList[i].Length);
}```

**Comment by NET-D3v3l0p3r** [comment]
Yes,

my solution:

`// - 1 -
    public class TextureArray : Texture2D
    {
        public TextureArray(GraphicsDevice graphicsDevice, int width, int height, int arraySize) : 
            base(graphicsDevice, width, height, true, SurfaceFormat.Color, SurfaceType.Texture, false, arraySize)
        {

        }
        public void Add(int index, Texture2D texture)
        {
            for (int i = 0; i < texture.LevelCount; i++)
            {

                float divisor = 1.0f / (1 << i);
                int[] pixelData = new int[(int)(texture.Width * texture.Height * divisor * divisor)];

                texture.GetData<int>(
                    i, 
                    0, 
                    new Rectangle(0, 0, (int)(texture.Width * divisor), (int)(texture.Height * divisor)), 
                    pixelData, 
                    0, 
                    pixelData.Length);

                this.SetData<int>(
                    i, 
                    index, 
                    new Rectangle(0, 0, (int)(texture.Width * divisor), (int)(texture.Height * divisor)),
                    pixelData, 
                    0, 
                    pixelData.Length);
            }
        }

        public static TextureArray LoadFromContentFolder(GraphicsDevice graphicsDevice, int widthPerTex, int heightPerTex, string path)
        {
            var paths = Directory.GetFiles(Environment.CurrentDirectory + @"\Content\" + path);

            TextureArray pTexArray = new TextureArray(graphicsDevice, widthPerTex, heightPerTex, paths.Length);

            int index = 0;

            foreach (var file in paths)
                pTexArray.Add(index++, GlobalRessources.Content.Load<Texture2D>(path + @"\" + Path.GetFileNameWithoutExtension(file)));

            return pTexArray;
        }
       
    }`
