### ISSUE TITLE
Maximum number of techniques reached in a mgfxo file

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#7391]
So far I've been able to compile and consume shaders with lots of techniques... up to today, I've was able to load MGFXO files with 128 techniques

Today I've pushed to 256 techniques on a MGFXO and when loading the bytecode into an Effect, it threw this exception:

    System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

    at Microsoft.Xna.Framework.Graphics.Effect.ReadEffect(BinaryReaderEx reader)
    at Microsoft.Xna.Framework.Graphics.Effect..ctor(GraphicsDevice graphicsDevice, Byte[] effectCode, Int32 index, Int32 count)
    at Microsoft.Xna.Framework.Graphics.Effect..ctor(GraphicsDevice graphicsDevice, Byte[] effectCode)
    at Microsoft.Xna.Framework.Graphics.AnimatedEffect..ctor(GraphicsDevice device, Byte[] effectCode) in D:\Github(Owned)(LIBS)\git.MonoGame.AnimAndPBR\src\MonoGame.Framework.Graphics.PBR\Effects\AnimatedEffect.cs:line 19
    at Microsoft.Xna.Framework.Graphics.PBREffect..ctor(GraphicsDevice device, Byte[] effectCode) in D:\Github(Owned)(LIBS)\git.MonoGame.AnimAndPBR\src\MonoGame.Framework.Graphics.PBR\Effects\PBREffect.cs:line 13

So I've guess I've hit some sort of limit in the file format.

The MGFXO that fails to load can be retrieved [__here__](https://github.com/vpenades/MonoGame.AnimAndPBR/blob/master/src/MonoGame.Framework.Graphics.PBR/Effects/Shaders/Resources2/MetallicRoughnessEffect.ogl.mgfxo)

After discussing with @Jjagg it seems there's some limits in-built in the format that need to be pushed up, which would require bumping the version number of the mgfxo format.

... 

Digging into the code:
https://github.com/Jjagg/MonoGame/blob/cb24746589835f0d4e2b7c041b6b0c8659979737/Tools/2MGFX/EffectObject.writer.cs#L49

Is clamping the number of techniques to 255.... but I see plenty of (Byte) casts....  all these should be replaced by encoded7 or shorts at the very least

I would suggest having subclasses for loading different versions for backwards compatibility (if desired)

Like:

internal static class EffectReaderVer9 { ... }
internal static class EffectLoaderVer10 { ... }

so based on the version header, it could use the old and the new reader.

#### What version of MonoGame does the bug occur on:
- MonoGame  3.8.0.1641

#### What operating system are you using:
- All 

#### What MonoGame platform are you using:

- All

**Comment by tomspilman** [comment]
> Is clamping the number of techniques to 255

Yeah i did that.  I wrote that code thinking "why would we ever need more than 256 techniques?".

We  just need to extend that format to support `(ushort)` number of techniques.

Ideally we fix it to pass the file version number thru to the reader and read the right size.  This way old effect files still work with the current code.  I wouldn't want to duplicate all the code for a single read change.

> but I see plenty of (Byte) casts.... all these should be replaced by encoded7 or shorts at the very least

I would just fix the techniques count, constant buffer count, and the shader count.  The rest should all be fine.

**Comment by vpenades** [comment]
I would simply go for 32bit ints as this the easiest value to read and write... if there's some concern about file size, I would go for enconded ints.

Also, although 65536 techniques is probably too many, from the point of view of how techniques are built, it might be misledading... I mean:

Typically, the number of techniques is based on the number of permutation bits.... so 8 bits yield 256 techniques.

I am planning to use probably 10 to 12 bits,  which means betwen 1024 and 4096 techniques.

But in the future, maybe someone is crazy enough to add even more permutation bits... _and it's not that difficult to go from 12 booleans to 17 booleans.

I don't mean we should support 17 (or even 15) permutation bits....  in fact I would add this:

- If the current shader code generates more 16384 or more techniques (14 permutation bits) issue a warning at compile time.
- If the current shader code generates more 32768 or more techniques (15 permutation bits) issue an error at compile time.

**Comment by tomspilman** [comment]
> I would simply go for 32bit ints as this the easiest value to read and write

Sure.... if you want to make it 32bits for techniques to allow the most possible bits for permutations that is fine.

No need to encode it or anything complex.

**Comment by vpenades** [comment]
Pull request is up: #7397
