### ISSUE TITLE
Add comment to CONTRIBUTING.md about limit on C# version

### ISSUE THREAD

**Issue by initram** [MonoGame/MonoGame#7393]
Currently the version of C# to use for compiling monogame is set til C# 5. I think it would be a good idea to add a section to CONTRIBUTING.md about this, and also a reason for this limit.

As I understand it the reasons I have found searching through cases and asking on Discord, is that the "BRUTE" tool used to compile for consoles do not support a newer version of C# for some reason. But this is not really documented anywhere.

If games that use a C# version higher than C# 5 are not supported on consoles, then I think that should also be added to the official documentation. If that is not the case, then why is monogame framework limited, but not the actual games?

**Comment by mrhelmut** [comment]
Public documentation is limited because the involved runtimes are under non-disclosure agreements.

I submitted #7394 to clarify a bit, but we can't go much further into the specifics publicly.

**Comment by initram** [comment]
Just a comment that says something like: "If you plan on shipping on consoles, you will have to limit your project to C# 5 and .Net framework 4.5.2.". If that is the case, otherwise users including me would think that I could write a game using C# 8 and .net core 3.1 and still be able to target consoles (because monogame supports those consoles). So I would just like an asterix in the documentation and a small text stating the limitations, no in-depth explanations required.
