### ISSUE TITLE
Project Unsupported error when creating a new MonoGame project in Visual Studio 2019

### ISSUE THREAD

**Issue by Jixxis** [MonoGame/MonoGame#7398]
After installing Visual Studio 2019 and following the MonoGame documentation for installing MonoGame for Visual Studio 2019, Visual Studio fails to properly create a MonoGame Cross-Platform Desktop Application (OpenGL) Project with the error that the project is not supported with Visual Studio 2019.

![image](https://user-images.githubusercontent.com/36606285/98509069-93e48880-222e-11eb-9e2b-970eba806619.png)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- MonoGame Cross-Platform Desktop Application (OpenGL)

**Comment by Jjagg** [comment]
You'll need to install the .NET Core component in the VS Installer to open Cross-Platform Desktop (DesktopGL) projects.
If you do have that component installed, please post a copy of the migration report.
