### ISSUE TITLE
Showcase not easily found on website

### ISSUE THREAD

**Issue by dsychin** [MonoGame/MonoGame#7407]
Why is the showcase at https://www.monogame.net/showcase/ not linked anywhere in the homepage?
When I first visited the website I thought there was no showcase.
I only found out about it through a link on Microsoft.
https://dotnet.microsoft.com/apps/games/engines

#### What version of MonoGame does the bug occur on:
- N/A

#### What operating system are you using:
- N/A

#### What MonoGame platform are you using:

- N/A

**Comment by harry-cpp** [comment]
@tomspilman @Jjagg Get on this XD

**Comment by Jjagg** [comment]
Added it to the top bar navigation :) 

![image](https://user-images.githubusercontent.com/14875382/105375778-4c548280-5c09-11eb-8145-5e19d3d41bf2.png)

**Comment by harry-cpp** [comment]
https://community.monogame.net

You lied to me @Jjagg XD

**Comment by Jjagg** [comment]
Woops, that page is maintained separately. Fixed it!
