### ISSUE TITLE
Add readonly modifier to struct methods that do not change state

### ISSUE THREAD

**Issue by LokiMidgard** [MonoGame/MonoGame#7408]
Methods of structs that do not modify the instance could be marked with `readonly`. This makes it easier to distinguish  methods with side effects from methods without.

It could also prevent defensive copies if the the struct is used with a method as `in` parameter.

I may be wrong but I think this would not be a breaking change. Through the C# LangVersion would need to be at least 8.0.

If this would be done it would also be possible to change `ref` modifier in many methods to `in` reflecting that the parameter is actually not modified. But this would be a breaking change, so probably not before 5.0. So it should probably be a separate issue.

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by initram** [comment]
As mentioned here https://www.github.com/MonoGame/MonoGame/tree/develop/CONTRIBUTING.md

Monogame source is currently limited to c#5. So this change request is not possible before being able to upgrade to a new version of c#.

**Comment by harry-cpp** [comment]
Yup, not gonna happen before 5.0, gonna close this as there are separate threads for 5.0 already.

**Comment by LokiMidgard** [comment]
sorry I haven't seen that in the contributing md.

**Comment by harry-cpp** [comment]
Don't worry about it, its always good to ask about useful stuff like these.
