### ISSUE TITLE
MonoGame.Content.Builder.Task fails when target framework multitargeting

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#7409]
I tried to make one of my projects to multitarget NetCore3.1 and Net471, and when compiling it fails with this exception:

    Error MSB3073:
    The command "dotnet C:\Users\CurrentUser\.nuget\packages\monogame.content.builder.task\3.8.0.1641\build\\..\tools\netcoreapp3.1\any\mgcb.dll
    /quiet /@:"D:\Projects\Game2\Content\Content.mgcb" /platform:DesktopGL
    /outputDir:"D:/Projects/Game2/Content/bin/DesktopGL/Content"
    /intermediateDir:"D:/Projects/Game2/Content/obj/DesktopGL/Content"
    /workingDir:"D:/Projects/Game2/Content/"" exited with code -532462766.
    Game2	C:\Users\CurrentUser\.nuget\packages\monogame.content.builder.task\3.8.0.1641\build\MonoGame.Content.Builder.Task.targets	138	

Steps to reproduce:
- Create a Windows DesktopGL game project.
- Edit project file and replace: `<TargetFramework>netcoreapp3.1</TargetFramework>` with `<TargetFrameworks>netcoreapp3.1;net471</TargetFrameworks>`
- Recompile (sometimes it requires two recompiles to kick in)

Epilogue:
Why do I need multitargeting?  we used to compile against Net471 and we're in the process of moving towards NetCore3.1. Unfortunately, we're compiling against some closed drivers for which only Net4x drivers are available, and we still require to do so to keep servicing our customers. Meanwhile, other devices we support are moving towards NetCore, so we're forced to publish two versions of our software: One for NetCore and one for NetFx

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
I don't think this is failing due to multitargeting frameworks, mgcb task does not really care about what target framework you are on, it just cares about MonoGamePlatform property really.

Try executing the command you have in the error in cmd or powershell, it should give you what the actual error from it is.

**Comment by vpenades** [comment]
@harry-cpp In the output window I found the stack dump:

    Unhandled exception. System.IO.IOException: The process cannot access the file 'D:\Github\_KK\Game2\Content\obj\DesktopGL\Content\.mgstats' because it is being used by another process.
    1>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
    1>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
    1>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    1>   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
    1>   at Microsoft.Xna.Framework.Content.Pipeline.ContentStatsCollection.Write(String outputPath) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\ContentStatsCollection.cs:line 202
    1>   at MonoGame.Content.Builder.BuildContent.Build(Int32& successCount, Int32& errorCount) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder\BuildContent.cs:line 502
    1>   at MonoGame.Content.Builder.Program.Main(String[] args) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder\Program.cs:line 59

Maybe this is because, when multitargeting, VisualStudio launches the tasks for every target _simultaneously_ ?

In that case, I guess the root of the problem is MGCB trying to access `.mgstats` from two executions at the same time.

Possible solutions: maybe the file should be named per platform, like:  `.net471.mgstats` and `netcore3.1.mgstats` , or maybe instead of storing it in the contents path, it should be stored in OBJ/Somewhere?

**Comment by harry-cpp** [comment]
Ahhh, yes, that would do it, the fix for this is simple tho, we just need to append target framework to obj/bin paths.

**Comment by vpenades** [comment]
Yes, I think it's the same solution used by VS to determine the binaries output...

So, instead of:

'D:\Projects\Game2\Content\obj\DesktopGL\Content\.mgstats'

It should be:

'D:\Projects\Game2\Content\obj\Net471\DesktopGL\Content\.mgstats'
'D:\Projects\Game2\Content\obj\NetCore3.1\DesktopGL\Content\.mgstats'
