### ISSUE TITLE
[CoreRT,macOS] Game crash when runing in app bundle but works in command line

### ISSUE THREAD

**Issue by ryancheung** [MonoGame/MonoGame#7414]
Blank game cannot run in macOS app bundle. 

Test project: https://github.com/ryancheung/GameFoo

Steps to reproduce:
1. Clone the test project
2. Run `dotnet publish -c Release -r osx-x64 -t:BundleApp` to get a app bundle in `bin/Release/netcoreapp3.1/osx-x64/publish/`
3. Run the generated `Foo.app`
4. You'll see the crash similar with  https://gist.github.com/ryancheung/694f75e42649bbe95c30e5048527970e

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- macOS

#### What MonoGame platform are you using:

- DesktopGL

**Comment by ryancheung** [comment]
After some debugging it shows `https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/SDL/SDLGamePlatform.cs#L37` game crash on this line, which means SDL native library searching may have problems in macOS bundled app.

**Comment by Jjagg** [comment]
Thanks for reporting this, Ryan :)
