### ISSUE TITLE
Setting the MacOS About Box Text

### ISSUE THREAD

**Issue by nillkitty** [MonoGame/MonoGame#7420]
I'm using MonoGame 3.8 and I can't seem to find anything in the library or documentation about how I would set the contents of the About Box when running a game under MacOS.  Currently the About Box is just the name of the executable.  I'd like to either remove the option or be able to control what's displayed.

**Comment by harry-cpp** [comment]
Those things are read from Info.plist once you package up your game for macOS in a .app, keys: "CFBundleName", "CFBundleShortVersionString", "NSHumanReadableCopyright".

**Comment by nillkitty** [comment]
Oh awesome.  Is there any monogame-specific guide on the packaging process?  I know it's pretty basic but just curious that other plist properties I might want to change. 
 Coming from a non-mac person going working a beta tester.
