### ISSUE TITLE
Point and Rectangle interoperability with System.Drawing.Primitives

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#7422]
Similar to #7417 , I would like to discuss whether it's worth to add interoperability between Monogame's Point and Rectangle, and [System.Drawing.Primitives](https://www.nuget.org/packages/System.Drawing.Primitives/).

A bit of history:

The evolution of the System.Drawing namespace from the old Net Framework to the current System.Drawing.Common nuget package has been, to say the least... _bumpy_. Unlike System.Drawing.Vectors, which is a mostly pure math code, System.Drawing.Common has a lot of OS dependant stuff (bitmaps, fonts, brushes) mixed with some other pure structures, like Points and Rects.

At some point, Microsoft decided to _split_ the namespace into two packages:

- [System.Drawing.Primitives](https://www.nuget.org/packages/System.Drawing.Primitives/) which is a pure NetStandard library containing only the pure code structs like `System.Drawing.Point`, `System.Drawing.Size` and `System.Drawing.Rectangle`
- [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Primitives/) which contains the OS dependant stuff like bitmaps, brushes, pens, fonts, etc.

This means that it is possible to add System.Drawing.* primitive types to a project without incorporating the ugly, OS dependant bits.

The implicit conversion mapping would be limited to Point and Rectangle.

About the usefulness of this proposal, I am not 100% sure; that's why I wanted to leave it for discussion here. From time to time I've found myself needing to convert from Drawing.Rectangle to Monogame.Rectangle, not as often as with System.Numerics, but it's a scenario I've found myself in. Given that Microsoft has provided System.Drawing.Primitives, I thought it might be possible to explore this possibility.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.x

#### What operating system are you using:
- All

#### What MonoGame platform are you using:

- All

**Comment by Jjagg** [comment]
What's your use case for using MG and System.Drawing together?

I don't really like the idea of adding these conversions. It made a lot of sense for System.Numerics because those types are intended to be the canonical ones for vector and matrix operations. And they're a part of the .NET API.

Neither of those things are true for System.Drawing.

**Comment by vpenades** [comment]
Lately I'm doing lots of stuff with OpenCV, TensorFlow and other AI engines, using MonoGame as a frontend of sorts. As it happens, many of the c# bindings to OpenCV & co happen to use System.Drawing Rectangle and Point extensively.

> I don't really like the idea of adding these conversions. It made a lot of sense for System.Numerics because those types are intended to be the canonical ones for vector and matrix operations. And they're a part of the .NET API.

Yeah, I have mixed feelings myself, but also I've noticed everybody is ending doing its own implementation of Rectangle and Point. Which is awkward since there's a system implementation. 

> Neither of those things are true for System.Drawing.

I agree that System.Drawing.Primitives might not be intended to be the canonicar Rect and Point of c#, but after the split, I've began seeing them with different eyes.

Anyway, unless there's some interest on this, I'm not going to push this myself. The really important ones, as you said, were the Numerics types.

**Comment by Jjagg** [comment]
I'm digging into this a bit more, and it seems like System.Drawing.Primitives structs _are_ intended to be the canonical .NET structs for geometric primitives ([issue](https://github.com/dotnet/runtime/issues/14503)) and, in fact, that was the purpose of splitting off the primitives.

But they aren't used that way 😔
And that's more important for this decision, so I still think we shouldn't add these conversions.

Really sucks that there's no widespread standard geometric structs. The System.Drawing stuff's API is far from ideal due to its history and there's no API for working with System.Numerics. I wonder if there's a chance of getting new primitives in the Systems.Numerics namespace...

**Comment by lithiumtoast** [comment]
> Lately I'm doing lots of stuff with OpenCV, TensorFlow and other AI engines, using MonoGame as a frontend of sorts. As it happens, many of the c# bindings to OpenCV & co happen to use System.Drawing Rectangle and Point extensively.

Could you post a link to these bindings? It seems to me these bindings are pulling in `Rectangle` and `Point` when they should probably use their own types for `CVRectangle` and `CVPoint` or something along those lines. As long as the bit representation is the same for the structs you can always typecast to MonoGame's types using a number of techniques.

**Comment by vpenades** [comment]
@lithiumtoast As far as I remember, I've found System.Drawing usage in these neural network packages:
- Emgu.CV has overloads for its own CVRectangle type, and also for System.Drawing.Rectangle for interoperability.
- Microsoft.ML architecture also uses System.Drawing quite extensively for its image based types (not only the primitives, but also the bitmap types)
- Accord framework (now archived) also uses System.Drawing types as its main and only imaging and primitive types.

**Comment by lithiumtoast** [comment]
> but I also believe that whenever System.* provides a type for a given task, it must be used in favour of a custom type, not the opposite.

@vpenades Unfortunately, the tasks involved for `System.Drawing` are outdated and mostly artifacts of old technology of rendering with the GDI+ for .NET applications in a timeline where Microsoft killed off XNA. Sometimes `System.*` choices are not always the best ;)

**Comment by vpenades** [comment]
> Unfortunately, the tasks involved for `System.Drawing` are outdated and mostly artifacts of old technology of rendering with the GDI+ for .NET applications in a timeline where Microsoft killed off XNA. Sometimes `System.*` choices are not always the best ;)

You might be right, specially when talking about the GDI+ objects like brush and bitmaps, where have some kind of hardware support tied to windows OS.

But then, why microsoft split the GDI support into two libreries, where System.Drawing.Primitives contains the neutral types and System.Drawing.Common contains the OS dependant types. It's almost as if Microsoft wanted to salvage some of the types that could live beyond GDI+.

**Comment by amerkoleci** [comment]
Xamarin Essentials has conversion from/to drawing types and numerics as well https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/Types/PlatformExtensions

**Comment by harry-cpp** [comment]
I'm pretty much in agreement with @Jjagg so closing this.
