### ISSUE TITLE
Build Error or Unable to open MGCB project on brand new project on Catalina

### ISSUE THREAD

**Issue by arnavb** [MonoGame/MonoGame#7423]
When I create a new project on the command line (using `dotnet new mgdesktopgl`) and run it (`dotnet run`), everything works fine. The app opens with the cornflower blue screen.

However, when I try to open the `Content/Content.mgcb` file via the command line (using `mgcb-editor Content/Content.mgcb`), I get the following error (the error popup shows up 2 times and then closes the window):

![MGCB project loading failed due to unknown error](https://user-images.githubusercontent.com/30810402/103321761-2ae8e800-4a09-11eb-9440-4d7a8983d4a6.png)

If, instead, I try to open the file directly from Finder, it loads properly and I'm able to add assets. Unfortunately, when I try to build the project, I get this error:

![Unable to build error: No such file or directory](https://user-images.githubusercontent.com/30810402/103321812-6a173900-4a09-11eb-836c-1c2acf877bdb.png)

<details>
<summary>For reference, here is my <code>csproj</code> file:</summary>

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Icon.ico" />
    <None Remove="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Icon.ico" />
    <EmbeddedResource Include="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>
  <ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.Xna.Framework.Content.ContentTypeReader" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.0.1641" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.0.1641" />
  </ItemGroup>
</Project>
```

</details>

I initially asked this question on Discord but was advised to create an issue instead.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- MacOS 10.15.6 Catalina

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
> However, when I try to open the `Content/Content.mgcb` file via the command line (using `mgcb-editor Content/Content.mgcb`), I get the following error (the error popup shows up 2 times and then closes the window):

You can't open up .mgcb files like that from macOS.




> If, instead, I try to open the file directly from Finder, it loads properly and I'm able to add assets. Unfortunately, when I try to build the project, I get this error:

Give us your full path to .mgcb file and the contents of it.

**Comment by arnavb** [comment]
@harry-cpp 

Project structure:

```bash
workspace/csharp/MonogameTwo via .NET 3.1.100
[I] ➜ tree -L 2
.
├── Content
│   ├── Content.mgcb
│   ├── TrexSpritesheet.png
│   ├── bin
│   │   └── DesktopGL
│   │       └── Content
│   ├── button-press.mp3
│   ├── hit.mp3
│   ├── obj
│   │   └── DesktopGL
│   │       └── Content
│   └── score-reached.mp3
├── Game1.cs
├── Icon.bmp
├── Icon.ico
├── MonogameTwo.csproj
├── Program.cs
├── app.manifest
```

For reference, the assets are from [here](https://github.com/Yeti47/TrexGame/tree/master/Resources).

Contents of `.mgcb` file:

<details>

<summary><code>Content.mgcb</code></summary>

```

#----------------------------- Global Properties ----------------------------#

/outputDir:bin/$(Platform)
/intermediateDir:obj/$(Platform)
/platform:DesktopGL
/config:
/profile:Reach
/compress:False

#-------------------------------- References --------------------------------#


#---------------------------------- Content ---------------------------------#

#begin button-press.mp3
/importer:Mp3Importer
/processor:SongProcessor
/processorParam:Quality=Best
/build:button-press.mp3

#begin hit.mp3
/importer:Mp3Importer
/processor:SongProcessor
/processorParam:Quality=Best
/build:hit.mp3

#begin score-reached.mp3
/importer:Mp3Importer
/processor:SongProcessor
/processorParam:Quality=Best
/build:score-reached.mp3

#begin TrexSpritesheet.png
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:TrexSpritesheet.png

```

</details>

Attempting to click the Build button after loading the assets still leads to "Build failed: No such file or directory".

**Comment by arnavb** [comment]
Ok another update. I don't know which commit fixed this, but building the latest version from source works perfectly. I'm closing this issue as I don't think there's any more action that can be done for this (other than maybe updating the version publicly available?)

**Comment by ThomasFOG** [comment]
> I would expect the dotnet tool to be able to handle relative paths though.

See #8786
