### ISSUE TITLE
Content Builder cannot find nuget libraries

### ISSUE THREAD

**Issue by Setakat** [MonoGame/MonoGame#7424]
I've recently tried updating one of my 3.7 projects to 3.8, and I've had a bit of a problem with a custom JSON importer for importing TexturePacker sprite sheets. It looks as if the content builder in 3.8 is unable to locate nuget binaries within the custom content pipeline project, and any attempt to use the the custom TexturePacker importer fails.
The custom content pipeline also references a common project that contains a collection of various model/util classes, and other custom importers are able to reference the objects within the common library, so its just a issue with the content builder being unable to locate the nuget sourced json library.

```
1>C:/Users/setakat/source/repos/SnakebiteEngineDemo.NetCore/SnakebiteEngineDemo.NetCore/Content/Sprites/10400001/10400001.json : error : Importer 'TexturePackerJsonImporter' had unexpected failure!
1>System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
1>File name: 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
1>   at Malachite.Monogame.Content.Pipeline.TexturePacker.TexturePackerJsonImporter.Import(String filename, ContentImporterContext context)
1>   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\ContentImporter.cs:line 45
1>   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\MonoGame.Framework.Content.Pipeline\Builder\PipelineManager.cs:line 669
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL, WindowsDX (to make sure it wasn't solely a DesktopGL issue)

**Comment by Apostolique** [comment]
The solution is here: https://github.com/MonoGame/MonoGame/issues/7368#issuecomment-716289198

In your extension project, add `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` to the csproj. Then build it. That will give you the `System.Text.Json.dll` next to your extension dll in the build output. In the content pipeline, you can add that dll along with your extension dll.

**Comment by Setakat** [comment]
Thanks - that did the trick. My Google-fu has failed me as I somehow did not manage to find that article.
