### ISSUE TITLE
MGCB Editor Help goes to a broken link:

### ISSUE THREAD

**Issue by rtargosz** [MonoGame/MonoGame#7428]
The Help->View Help (F1) option in MGCB Editor version 3.8.0.1641 goes to a broken link: https://docs.monogame.net/articles/tools/pipeline.html

404 Not Found
nginx/1.14.0 (Ubuntu)

Also, you should always use a custom 404 page; having it fail to the default nginx 404 page is a security risk: you've now told hackers what OS, application server and version you are using, so they can immediately take advantage of any CVEs like this: https://www.cvedetails.com/vulnerability-list/vendor_id-10048/product_id-17956/version_id-267430/Nginx-Nginx-1.14.0.html

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- All

**Comment by Jjagg** [comment]
Thanks for reporting this!
