### ISSUE TITLE
dotnet cli: Update for template pack always available

### ISSUE THREAD

**Issue by galexandreg** [MonoGame/MonoGame#7429]
I feel like there is something really simple that I'm not seeing here... I'm new with the whole .NET world and I guess I could be doing something wrong...

I can't update the MonoGame templates using the command line.
This is very similar to this issue: dotnet/templating/issues/2362, but I am using the correct MonoGame.Templates.CSharp.

`dotnet new --install MonoGame.Templates.CSharp::3.8.0.1641` works fine.

But when I create a project:
`dotnet new mgdesktopgl -o testmg`
I get the following message:
```
An update for template pack MonoGame.Templates.CSharp::3.8.0.1641 is available.
    install command: dotnet new -i MonoGame.Templates.CSharp::3.8.0.1641
```
If I run the update command, it seems to work, but I still get the "update available" message.

`dotnet new --update-check` shows the update available (and others)
`dotnet new --update-apply` works fine
`dotnet new --update-check` shows the available Monogame update, but the others are gone.

So it seems I can't update Monogame.Templates.CSHarp, but the others work just fine.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- MacOS

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
This isn't bug on our side, complain about it on the dotnet templating repo.

**Comment by andylatham82** [comment]
> This isn't bug on our side, open an issue about it on the dotnet templating repo.

Is there a link to this issue? I have the same problem.

**Comment by galexandreg** [comment]
I think that @harry-cpp was suggesting that I open an issue myself in the templating repo.
I still haven't done it and I wanted to do a bit more tests before opening the issue.
I may get to it in the next days, but if you have the time and want to do it before I do, that's fine 😃

**Comment by hsandt** [comment]
Any news on this? I could open a bug but I don't know where the "dotnet templating repo" is (I see nothing such under the GitHub user MonoGame).

**Comment by hsandt** [comment]
In fact, it seems that the templates are part of this repo: https://github.com/MonoGame/MonoGame/tree/develop/Templates/MonoGame.Templates.CSharp

but in fact you were talking about the templating engine itself, which I finally found at https://github.com/dotnet/templating. I'll rewrite this issue there soon.
