### ISSUE TITLE
MGCB Couldn't Find Importer

### ISSUE THREAD

**Issue by manbeardgames** [MonoGame/MonoGame#7431]
I'm the developer of the [MonoGame.Aseprite](https://github.com/manbeardgames/monogame-aseprite) library and recently had an [issue opened](https://github.com/manbeardgames/monogame-aseprite/issues/18) where the MGCB Editor was unable to find the importer.    After doing some tests, I was able to confirm that this is only happening if the **Content.mgcb** file for the project is located in a directory lower than  `\Users\` directory in Windows.  

For instance
*  `C:\MonoGameAsepriteTest\Content\Content.mgcb` fails to load the dll reference correctly
* `C:\Users\[username]\MonoGameAsepriteTest\Content` loads the dll reference as expected.

To test this, here are the steps I performed:

1. Open command line and navigate to the C: root with `cd c:`
2. Create a new MonoGame Project with the following command `dotnet new mgdesktopgl -o MonoGameAsepriteTest`
3. Navigate into the new project directory with `cd MonoGameAsepriteTest`
4. Add the latest **MonoGame.Aseprite** package with `dotnet add package MonoGame.Aseprite --version 2.0.3.3`
5. Open the MGCB Editor
6. In the MGCB Editor, open the **Content.mgcb** file located at `C:\MonoGameAsepriteTest\Content\Content.mgcb`
7. Add a reference to the **MonoGame.Aseprite.ContentPipeline.dll** located at `%userprofile%\.nuget\packages\monogame.aseprite\2.0.3.3\contentFiles\netstandard2.0\MonoGame.Aseprite.ContentPipeline.dll`
8. Add an Aseprite file to the content project.  I have attached one that can be used to this issue called **aseprite-test.aseprite**
9. The Importer and Processor for the file show the correct **Aseprite Document Importer** and **Aseprite Document Processor** but clicking build shows the error following error

```
Build started 1/11/2021 8:14:08 PM

/reference:../../Users/Dart/.nuget/packages/monogame.aseprite/2.0.3.3/contentFiles/netstandard2.0/MonoGame.Aseprite.ContentPipeline.dll: error: Couldn't find a default importer for '/reference:../../Users/Dart/.nuget/packages/monogame.aseprite/2.0.3.3/contentFiles/netstandard2.0/MonoGame.Aseprite.ContentPipeline.dll'!
C:/MonoGameAsepriteTest/Content/aseprite-test.aseprite: error: Couldn't find a default importer for 'C:/MonoGameAsepriteTest/Content/aseprite-test.aseprite'!

Build 0 succeeded, 2 failed.

Time elapsed 00:00:00.12.

```

![image](https://user-images.githubusercontent.com/7365893/104257400-56c58e00-544b-11eb-9075-3f547d6dc481.png)

The above shows the error that occurs.  As a comparison, if you perform the same exact steps below, then there is no error. The only difference in the steps below versus those above is the project directory is at minimum inside the `C:\Users\[username]` directory.

1. Open command line and navigate your user directory with `cd C:\Users\[username]` where `[username]` is your user name.
2. Create a new MonoGame Project with the following command `dotnet new mgdesktopgl -o MonoGameAsepriteTest`
3. Navigate into the new project directory with `cd MonoGameAsepriteTest`
4. Add the latest **MonoGame.Aseprite** package with `dotnet add package MonoGame.Aseprite --version 2.0.3.3`
5. Open the MGCB Editor
6. In the MGCB Editor, open the **Content.mgcb** file located at `C:\MonoGameAsepriteTest\Content\Content.mgcb`
7. Add a reference to the **MonoGame.Aseprite.ContentPipeline.dll** located at `%userprofile%\.nuget\packages\monogame.aseprite\2.0.3.3\contentFiles\netstandard2.0\MonoGame.Aseprite.ContentPipeline.dll`
8. Add the Aseprite file to the content project. 
9. The Importer and Processor for the file show the correct **Aseprite Document Importer** and **Aseprite Document Processor** and clicking build will build successfully.

![image](https://user-images.githubusercontent.com/7365893/104257591-cd628b80-544b-11eb-8bed-b64111dda896.png)

With .NET Core and NuGet packages, the packages are installed by default to the `%userprofile%\.nuget\packages\` directory.  It looks like if a user is managing their project directories directly at the C: root in Windows, then it is unable to resolve the reference properly since they reside behind the `%userprofile%` directory.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641
- MGCB Editor 3.8.0.1641

#### What operating system are you using:
- Windows 10 Home 64-bit (10.0 Build 18363)

#### What MonoGame platform are you using:
- DesktopGL

#### Attached Files
[aseprite-test-file.zip](https://github.com/MonoGame/MonoGame/files/5799250/aseprite-test-file.zip)

**Comment by harry-cpp** [comment]
Some folders require admin privileges, namely stuff bellow Users folder, I assume running the MGCB Editor as admin would make it work as expected so closing this.
