### ISSUE TITLE
DesktopGL: Mouse state has inconsistencies when mouse leaves the window while a mouse button is pressed

### ISSUE THREAD

**Issue by Apostolique** [MonoGame/MonoGame#7434]
OpenGL:

https://user-images.githubusercontent.com/2766423/104387832-efb8df80-5505-11eb-9093-f695370d7a18.mp4

In the video above, I press the left mouse button, then I drag my mouse outside the window. 2 cases can happen:

1. The mouse's position updates but the button's state stays pressed until the mouse is back in the window.
2. The mouse's position doesn't update but the button's state is updated instantly when released. The mouse position restarts updating right away when the button is released.

What I would expect:

The mouse's position updates and the button's state is updated instantly when released.

WindowsDX:

https://user-images.githubusercontent.com/2766423/104388293-e8de9c80-5506-11eb-96bd-94bca58b6b18.mp4

There are no issues in WindowsDX.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by TechnologicalPizza** [comment]
Interestingly enough a Sdl2 window that pumps events stops receiving mouse updates when the mouse is not inside the window. MonoGame uses [SDL_GetGlobalMouseState](https://wiki.libsdl.org/SDL_GetGlobalMouseState) for every `Mouse.GetState()` so this seems like an SDL bug.

**Comment by harry-cpp** [comment]
So https://github.com/MonoGame/MonoGame/pull/7440 will fix your issue, but I still need to test it under few Linux environments before merge.

Iirc we had issue with getting incorrect mouse position on some Linux DEs, maybe newer SDL got it all sorted by now.
