### ISSUE TITLE
MGCB requires .NET Core 3.1 despite having .NET 5 runtime

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7446]
Hello there,

I just noticed that MGCB has an hard requirement on .NET Core 3.1. It is required to have the 3.1 runtime installed, no matter if we have any more recent runtime like .NET 5 installed.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Tested on all OS

#### What MonoGame platform are you using:

- All targets

**Comment by harry-cpp** [comment]
https://github.com/MonoGame/MonoGame/pull/7437
