### ISSUE TITLE
Android not resuming to app after using Exit(); via backbutton

### ISSUE THREAD

**Issue by 7unk10** [MonoGame/MonoGame#7458]
I investigated it and found that in AndroidGameActivity.cs if that EventHandlers.Raise is commented out, I can resume like expected. See https://community.monogame.net/t/resume-android-app-running-in-the-background/14894/23
I don't understand it any further..

#### What version of MonoGame does the bug occur on:
-monogame 3.8.0.1641

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Android

**Comment by mrhelmut** [comment]
As per Android life cycle management, it is not recommended to call ```Exit()```.
