### ISSUE TITLE
Matrix.CreateBillboard inverts model over the Y axis

### ISSUE THREAD

**Issue by roy-t** [MonoGame/MonoGame#7461]
Whenever I apply MonoGame's Matrix.CreateBillboard(...) matrix to a model, the model is incorrectly flipped over the Y axis. This means that the model is culled when the `CullMode` is set to `CounterClockwise`. When culling is disabled the model shows up but the texture is inverted.

```
var position = particle.StartPosition + (particle.Velocity * particle.Age);
particle.Transform = Matrix.CreateScale(particle.Scale)
   * Matrix.CreateBillboard(position, camera.Position, Vector3.Up, camera.Forward);
```
![image](https://user-images.githubusercontent.com/623634/107120849-a010ce00-688f-11eb-9304-64a806ffedf6.png)

Not applying the Billboard matrix, but a regular translation matrix shows that the inversion happens due to the billboard matrix.

```
var position = particle.StartPosition + (particle.Velocity * particle.Age);
particle.Transform = Matrix.CreateScale(particle.Scale)
   * Matrix.CreateTranslation(position);
```
![image](https://user-images.githubusercontent.com/623634/107120951-00077480-6890-11eb-801f-c32a87262095.png)

I've looked at the source code, but I don't see where the bug is coming from. But I'm also not sure if the CreateBillboard function is doing exactly what its supposed to be doing. As you can see in the first image the billboard matrix does not perfectly align the sprite with the view. 

For a personal project I've been using a different function to create billboards:
(source: https://swiftcoder.wordpress.com/2008/11/25/constructing-a-billboard-matrix/)
```
public static Matrix CreateBillboard(Vector3 position, Matrix view)
{
    var result = Matrix.Identity;
    result.Translation = position;
    result.M11 = view.M11;
    result.M12 = view.M21;
    result.M13 = view.M31;

    result.M21 = view.M12;
    result.M22 = view.M22;
    result.M23 = view.M32;

    result.M31 = view.M13;
    result.M32 = view.M23;
    result.M33 = view.M33;

    return result;
}
```        
![image](https://user-images.githubusercontent.com/623634/107121019-7d32e980-6890-11eb-8284-060524fac908.png)

Unfortunately it has a completely different signature and probably does not mimic what XNA used to do. Any thoughts what we could do?

- Fix the inversion over the Y axis bug in the original matrix function
- Add the function above to the matrix class, but how to call it?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by nkast** [comment]
It's the model the one that is flipped in Y.  
The '.Forward' vector of the Billboard matrix correctly points towards the camera.

**Comment by roy-t** [comment]
I'm not sure if I follow. The 'model' in this case is defined as such:

```
var vertices = new[]
{
    new VertexPosition(new Vector3(-0.5f, -0.5f, 0)),
    new VertexPosition(new Vector3(-0.5f, 0.5f, 0)),
    new VertexPosition(new Vector3(0.5f, 0.5f, 0)),
    new VertexPosition(new Vector3(0.5f, -0.5f, 0))
};

var indices = new short[]{ 0, 1, 2,    2, 3, 0};
```

So its basically just a quad facing towards the user. So the 'front' of a regular 2 sided model. I would expect that if the model is at {0, 0, 0} and the camera is at Vector3.Backward the matrix provided by Matrix.CreateBillboard would be the identity matrix. But it instead produces a matrix that rotates the model 180 degrees around the Y axis.

Other methods that I found online do provide the correct matrix. So I'm quite puzzled why this behavior is different. I would expect a billboard to always point the front towards the camera, not the back.

**Comment by nkast** [comment]
>> So its basically just a quad facing towards the user. 

That's the problem. Your quad has a hard-coded rotation to face the camera.
That's optimal for drawing 2D but to use it in a 3D environment you have to create it in such a way that it faces forward and apply the the model transformation later.

Try this alternative configuration, place the camera at Vector3.Forward, looking Vector3.Backward at the model.
Now the billboard matrix would be Identity as it should be, and facing forward at the camera (billboardMtx.Forward == Vector3.Forward). If the quad looks flipped it's because it is.

**Comment by roy-t** [comment]
Ah now I get it, I guess in other libraries they were coming more from a 2D perspective when it comes to billboards. Thanks for the detailed explanation!
