### ISSUE TITLE
BlockOnUIThread crashing on low end hardware

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7471]
Hello there,

#7384 introduced ```MaxWaitForUIThread``` to the ```Threading``` class.

https://github.com/TechnologicalPizza/MonoGame/blob/6176b242eb799e9b876ca7e107779a3897c202a6/MonoGame.Framework/Platform/Threading.cs#L22

We didn't see any problem in this at first because we likely run on machines which are powerful enough to not hit this wall, but after publishing this to our players, we immediately started to run into those _very_ frequently on calls as simple as loading a small texture.

I believe that we should entirely get rid of both of this limit since increasing it will likely just hide things and still be hit on some machines. Maybe we should just use them to display a warning to developers, but it should not crash.

I'll try to work on a PR for this.

cc'ing @TechnologicalPizza @roeyskoe 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- All systems

#### What MonoGame platform are you using:

- DesktopGL

**Comment by KakCAT** [comment]
Could you post an example of low end hardware where this problem appears? Are you talking mobile, or also PC/Mac?

**Comment by mrhelmut** [comment]
All GL platforms: PC, Mac, Linux and mobiles.

I don't have a specs threshold, it seems bound to how loaded a machine is. Anyway, the current maximum time that a GPU operation can take is 1 second, and loading a 4MB texture can easily take longer on some hardware.

I believe that we should simply wait indefinitely, which is what MonoGame was doing before this update.

**Comment by roeyskoe** [comment]
The crash was not limited to only low end hardware, I originally found this on a i7-5820k and GTX970.

My crash was happening due to garbage collection trying to remove RenderTexture2D, but UI thread was busy doing something else at the same time.
