### ISSUE TITLE
Getting Started documentation missing .Net Core SDK dependancies on Windows

### ISSUE THREAD

**Issue by nbourre** [MonoGame/MonoGame#7480]
I've just installed MonoGame to play around with the framework. I've followed the [Getting started](https://docs.monogame.net/articles/getting_started/0_getting_started.html) page on the official Website

When I tried to compile the blank project, it failed. I noticed that some dependencies were not working. After googling a bit, I've found that MG was dependent of .Net Core SDK.

After installing it, everything worked fine.

It might be a good idea to include this in the documentation for beginners.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows 10 20H2

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
The first image on the [Getting started page for Windows](https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_windows.html) shows you that you have to install .NET Core SDK. And the first bullet point tells it as well.

> .NET Core cross-platform development - For Desktop OpenGL and DirectX platforms

**Comment by nbourre** [comment]
I already had VS 2019 installed. So I skipped this part. Dummy me!
