### ISSUE TITLE
Requirement for Linux development (monodevelop) is no longer open source and unmaintained

### ISSUE THREAD

**Issue by Ruin0x11** [MonoGame/MonoGame#7481]
I tried to install the latest monodevelop on my Arch Linux machine, but the compilation failed. Then I learned that monodevelop is no longer open source, and the latest version only builds on Mac: https://github.com/mono/monodevelop/issues/8006

But the build requirements say that monodevelop is necessary. So as I was unable to install it, and the version available in my package manager is years out of date and unmaintained, I'm not sure what to do. Is monodevelop actually necessary to develop with MonoGame on Linux? Or should the instructions be updated to use dotdevelop (the community fork of monodevelop)?

**Comment by harry-cpp** [comment]
> But the build requirements say that monodevelop is necessary.

What build requirements are you following?

> I'm not sure what to do. Is monodevelop actually necessary to develop with MonoGame on Linux?

There is getting started guide for Linux (well Ubuntu, but you can pretty much follow it easily on any distro):
https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_ubuntu.html

You can use either Visual Studio Code or Rider IDE for developing C# applications from Linux.

**Comment by Ruin0x11** [comment]
These requirements that were linked from the readme: https://github.com/MonoGame/MonoGame/blob/develop/REQUIREMENTS.md#linux-requirements

What I meant to say is that if monodevelop isn't strictly necessary to use MonoGame, then it should say "a C# IDE like monodevelop or Rider" instead of "monodevelop" there. It was a bit confusing since I've never done any .NET development on Linux.
