### ISSUE TITLE
Proposal: Provide ways to write your own Tick function.

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#7483]
Hi, I'm working in a game where some of the features are locked to 60Hz. However people with higher refresh rates may want to play the game at higher framerates. After some thinking I realized that the only way I could manage that without changing tons of code was rewriting the Monogame Tick function.

I think MonoGame should provide a good enough Tick function, but still allow users to write their own without recompiling.

At first I thought of taking advantage of SupressDraw. However doing a quick exit from a Update with a SupressDraw generates a ton and a half of garbage, either from UpdateWindows() or PeekMessage(), I don't know which.

Then I slightly modified MonoGame to add a "DoRetryTick" function, mimicking SupressDraw, which just gotos to RetryTick after exiting from Update (in non fixed timestep) if it has been called. This way you are kept in the loop, avoids the garbage, and virtually allows you to write your own Tick function.

This would allow users to mostly bypass the whole MonoGame tick, allowing them to do their own tick if they want, or even choose between different tick functions created by the community, and the changes to the Tick function (which is a very controversial one) are minimal.

Another option would be making Game.Tick overridable, but that should need several other changes (like making several variables and functions protected, and moving the exit function out of the Game.Tick function) and it's easier to mess up.

**Comment by harry-cpp** [comment]
Nope, that sounds like a horrible idea, if you tied some of your game code to have to be executed up to X times, you can pretty easily either check timer in Update/Draw methods and call it if 1/60 time passed or make your own thread for executing it.

**Comment by KakCAT** [comment]
You're right, it's not needed. Found a way to write the tick management function without needing the DoRetryTick.
