### ISSUE TITLE
Spritefont XNB backwards compatibility.

### ISSUE THREAD

**Issue by stromkos** [MonoGame/MonoGame#7489]
The switch to netcore has broken the SpriteFont XNB compatibility with previous versions of Monogame and XNA. 

This issue was brought up in #7174 and fixed in the reader in #7199. 

The problem, as I see it, is the difference in the XNB files depending on whether the file was built in netcore or not.

I realize that backward compatibility is not major design goal. 

However, it should not be hard to fix this in the writer. Replace all "System.Private.CoreLib" with "mscorlib" prior to writing the type to the type dictionary in the XNB file.

Any thoughts?

#### What version of MonoGame does the bug occur on:
- MonoGame 3..8

#### What operating system are you using:
- Any

#### What MonoGame platform are you using:

- Any

**Comment by harry-cpp** [comment]
What would be the issue you are trying to solve by doing that?

**Comment by harry-cpp** [comment]
I am gonna close this as no response was given to the previous comment.

If anybody has any reason for which they would like this compatibility added, feel free to comment down bellow.

**Comment by stromkos** [comment]
Version compatibility and consistency across builds.

This was brought up in another issue: https://github.com/MonoGame/MonoGame/issues/7476#issuecomment-795687624

Here is one of my reasoning screnarios:
Imagine I have a game fully tested and ready to ship using Monogame 3.7.1.  I hear about the new font packing speed-up feature in Develop?, and I decide to include CJK translations using the localized font processor, since the build times are reasonable.
I take and place that file into the 3.7.1 project... Crash.

It seems weird that a "data"(I know there is more to it than that) file would change depending on the target that the mgcb.exe was built against. 

For me, my issue stems from the need to go back and forth between 3.8 and 3.7.

**Comment by harry-cpp** [comment]
You always need to compile content with the same version of MGCB as the MonoGame.Framework assembly.

That being said, even if we did replace all System.Private.CoreLib with mscorlib, whats being saved inside .xnb file is a full type name, meaning that if you were to try to use an older version of MonoGame with something like .NET 5, it would actually crash as mscorlib would not be a valid type name in that case.

**Comment by stromkos** [comment]
> You always need to compile content with the same version of MGCB as the MonoGame.Framework assembly you use.

If that were the case, Monogame would have emoji support.  

Since the design was based on XNA compatibility, AFAIK, there have been no breaking changes to the xnb format until 3.8. 
For simple games, I have been able to go back and forth between Monogame 3.6 - 3.7 and XNA 4 with the XNB files.


> ... older version of MonoGame with something like .NET 5, it would actually crash as mscorlib would not be a valid type name in that case.

You have already addressed that with the current solution. 
Anyone compiling an older version against .net 5 or core would need to implement #7199. I am not purposing to remove that PR.

However, rather than focusing on crashes for people who choose to recompile an older version to a future target(3.7 will always run on the 4.5 - 4.8 runtime), I am concerned about the crashes for existing builds.

---

There is no drawback, no negative to this change. In fact, it saves a few bytes in every XNB file produced at the cost of a text replacement operation(or two).

---

The other point is binary version control in Perforce.  The file can change depending on the configuration of the person building it.
The "same" file can switch for each commit, leading to large change logs and repositories.

**Comment by harry-cpp** [comment]
> Since the design was based on XNA compatibility, AFAIK, there have been no breaking changes to the xnb format until 3.8.
> For simple games, I have been able to go back and forth between Monogame 3.6 - 3.7 and XNA 4 with the XNB files.

You should not do that. Maybe it worked for something more basic like textures, but sound effects, songs, shaders, videos, all of those have very specific xnb files and they are very much not the same between platforms.

Also stuff like shaders pretty much break backwards compatibility with each release of MonoGame.

And to repeat myself: You always need to compile content with the same version of MGCB as the MonoGame.Framework assembly you use.

> The other point is binary version control in Perforce. The file can change depending on the configuration of the person building it.
> The "same" file can switch for each commit, leading to large change logs and repositories.

No it cannot, mgcb is strictly a dotnet tool now, it will always write System.Private.CoreLib as the type.

Also not sure why you are committing .xnb files to perforce, that seems very redundant.
