### ISSUE TITLE
MGCB editor is crashing on Arch linux

### ISSUE THREAD

**Issue by vfrz** [MonoGame/MonoGame#7491]
When I open MGCB, it crashes with this exception message:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)`

The issue has already been reported in the Eto repository here: https://github.com/picoe/Eto/issues/1914 and seems to be a compatibility problem with the newer version of `glib2` 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Manjaro (Linux 5.10.28-1)

#### What MonoGame platform are you using:

- DesktopGL

**Comment by peon501** [comment]
Arch lmao

**Comment by Emobe** [comment]
I'm still getting this exact error on arch still using v3.8.0.1641

**Comment by vfrz** [comment]
> I'm still getting this exact error on arch still using v3.8.0.1641

The 3.8.0.1641 has been released on August 10 of 2020 so you'll have to wait for the next release to get the fix or compile it by yourself.

**Comment by Emobe** [comment]
Thanks for the info! Managed to get it running my building it myself

**Comment by Alumniminium** [comment]
needs to be re-opened, issue re-appeared

**Comment by kaiytech** [comment]
can confirm the issue re-appeared, this time on popOS

**Comment by xslendix** [comment]
Can confim, I have this issue myself too.

**Comment by LordChildConsumer** [comment]
Can also confirm. I'm on EndeavourOS/Arch.

**Comment by Beyley** [comment]
> Can also confirm. I'm on EndeavourOS/Arch.



> Can confim, I have this issue myself too.



> can confirm the issue re-appeared, this time on popOS



> needs to be re-opened, issue re-appeared

are you on master? or are you using the dotnet tool?

**Comment by xslendix** [comment]
I personally used the dotnet tool, I don't know how to build it from master

**Comment by LordChildConsumer** [comment]
**FOR ANYONE ON ARCH/MANJARO/ENDEAVOUR/ETC**
The [AUR version](https://aur.archlinux.org/packages/mgcb-editor-git) works.

**Comment by Beyley** [comment]
> **FOR ANYONE ON ARCH/MANJARO/ENDEAVOUR/ETC** The [AUR version](https://aur.archlinux.org/packages/mgcb-editor-git) works.

manjaro devs reccomend against AUR, as it can cause breakages, i wouldnt be pointing manjaro users to it

**Comment by Lioncat2002** [comment]
Facing same issue on Kali Linux(which is well just Ubuntu)

**Comment by Beyley** [comment]
> Facing same issue on Kali Linux(which is well just Ubuntu)

just build from source, its already fixed
