### ISSUE TITLE
3rd party NVorbis submodule no longer available

### ISSUE THREAD

**Issue by Bodwad** [MonoGame/MonoGame#7494]
It looks like the link to the https://github.com/MrHelmut/NVorbis.git submodule is no longer available.

Error occurs when setting up a new Monogame clone and trying to run the git commands

'git submodule init' and 'git submodule update'

**Comment by Jjagg** [comment]
@mrhelmut

**Comment by mrhelmut** [comment]
Woopsy, I deleted that assuming it was no longer in use. I have a local backup, I propose that we host it in the MonoGame org so that don't happen again.

**Comment by mrhelmut** [comment]
I switched to https://github.com/NVorbis/NVorbis with #7495 
I had to point to an old release (the same as we originally pointed to) because more recent versions of NVorbis are heavy on the newest C# language features we can't use.
