### ISSUE TITLE
MGCB editor is opening and closing non-stop

### ISSUE THREAD

**Issue by ayousuf23** [MonoGame/MonoGame#7499]
The MGCB editor is opening and closing. The app closes and reopens instantly or at least that's what it looks like. 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8 develop branch

#### What operating system are you using:
- macOS Big Sur

#### What MonoGame platform are you using:

- DesktopGL

**Comment by novitix** [comment]
Having the same issue on macOS 11.3.1

**Comment by harry-cpp** [comment]
I am able to reproduce this, it seems compiling the MGCB Editor from Windows is causing some issues.

A way to kill of the app for me was to execute the following command in the terminal:
```
killall mgcb-editor-mac
```

**Comment by ChrisChou-freeman** [comment]
+1

**Comment by mrhelmut** [comment]
@harry-cpp Can we assume this to be fixed for 3.8.1 / .net 6 ?
