### ISSUE TITLE
Spritesheet animation jittery/shaky on iOS

### ISSUE THREAD

**Issue by dtaylorus** [MonoGame/MonoGame#7516]
My spritesheet animations are rock solid and steady on Windows and Android, but on iOS they have a terrible shake/jitter that makes them unusable. I've tried tweaking every setting I know to no avail.

See the attached video for an example. The feet should be steady but they're shaking all around. With this exact same spritesheet and code the feet are steady on Android and Windows. I've only seen this problem on iOS devices.

Any ideas for a fix/workaround?

https://user-images.githubusercontent.com/2476671/120045953-1bcd8c80-bfdf-11eb-94ff-629728b8e26f.mp4

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- MacOS

#### What MonoGame platform are you using:

- iOS

**Comment by dtaylorus** [comment]
As a data point, the jitter seems to be less noticeable when I reduce the texture size, but I don't think it ever completely goes away.

Could these be a floating point accuracy issue? But why only on iOS?

**Comment by mrhelmut** [comment]
Sounds like you're using the ```Vector2``` overload of ```SpriteBatch.Draw()```. You might want to round the position because the hardware will do it for you if you don't, and there's no guarantee in regard to how each platform might do the rounding.

**Comment by dtaylorus** [comment]
Thanks, but even if I use Vector2.Zero as the position the problem persists. I've also verified that the sprite sheet contains all integer offsets used for the origin and sourceRect parameters.

Is there something about this that explains why iOS would behave differently, or why a larger texture seems to make the problem worse?

Could this be a floating point precision issue, and if so, is there some way to increase the precision?

**Comment by dtaylorus** [comment]
There is a world transform matrix applied to the SpriteBatch, but I forced that to all integer values and the animation was still jittery. I cannot think of another parameter to convert to an integer at this point.

However, I did narrow the problem down quite a bit.

If I force all the sprites in the sprite sheet to be the same size, the jitter goes away. This translates to making the SpriteBatch.Draw `origin` and `sourceRectangle` parameters constant.

Of course, this makes my spritesheet texture much bigger and full of unnecessary transparent pixels, so I'd still like to resolve this issue.

Any workarounds for the iOS version of the SpriteBatch.Draw method having some precision issues with the `origin` and `sourceRectangle` parameters as used to draw a trimmed sprite from a sprite sheet?

Even guesses as to where to start looking would be helpful.

**Comment by bjornenalfa** [comment]
Is the size of your spritesheet an power of 2? What is your sampling mode?

**Comment by dtaylorus** [comment]
My spritesheet size was not a power of 2, and I don't explicitly set SamplerState (not sure of the default value, either).

I changed TexturePacker to output a power of 2 size and the problem does appear to be resolved. I changed some other parameters as well (Extrude 0 => 1 and Shape Padding 0 => 2), so I'll need to experiment to figure out which setting made the difference.

Thank you for pointing me in the right direction!

What sampling mode do you recommend, and do you recommend all my spritesheet sizes be a power of 2 to accommodate iOS?

**Comment by dtaylorus** [comment]
Confirmed the fix was the power of 2 texture size. The other changes to the texture packing were irrelevant.

I'm not sure of the memory impact of using power of 2 sizes with a lot of empty space in them.

Is there an alternative setting to make non-power of 2 texture sizes work without the jitter?

**Comment by bjornenalfa** [comment]
It is always a good idea to have textures be powers of 2 to prevent issues with floating point precision regardless of platform. It can also speed up the rendering. I think modern graphics drivers will resize your textures to powers of 2 anyway, but apparently that might not be the case on iOS.

Unless you end up with extreme amounts of empty space I don't think it is worth worrying about unnecessary memory usage.

If you are not scaling your sprites then using nearest neighbour sampling can fix small jittering, but then you'll want to keep at least 1 transparent pixel padding between your sprites to avoid sampling another sprite at the edges.

**Comment by dtaylorus** [comment]
Awesome. Thank you so much @bjornenalfa!
