### ISSUE TITLE
Error: MGCG Editor, Error in building  png files 

### ISSUE THREAD

**Issue by BoolPurist** [MonoGame/MonoGame#7518]
Hello,

**Problem:**

I am not able to import png files with MGCG Editor for a Monogame project. 

**Things I tried:**

According to a related [forum post](https://community.monogame.net/t/solved-freeimage-dll-not-found/8221/10) in regards of the failure with TextureImpoter and the not found dll FreeImage. 
I tried to install [Visual C++ Redistributable Packages for Visual Studio 2013 ](https://www.microsoft.com/en-us/download/details.aspx?id=40784). Unfortunately when I tried to install it, the following error message comes up "This app can't run on your PC" 

Here is Image of the error occurring.
![image](https://user-images.githubusercontent.com/57603453/120089401-2f214a80-c0fa-11eb-9d43-a5bed23d9de8.png)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641
- mgcb-editor-wpf 3.8.0.1641

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
The FreeImage dll that is shipped with MonoGame doesn't need a VC++ redistributable anymore.

Do you happen to be running a 32bit Windows? Support for 32bit systems has been dropped for the tools.

**Comment by BoolPurist** [comment]
> Do you happen to be running a 32bit Windows? 

No I am runnning a 64 bit Winows.

**Comment by BoolPurist** [comment]
Problem solved via trail and error.
Now I can build png files without throwing an error with TextImporter in the mgcb-editor-wpf.

Solution:
I had to repair "Microsoft Visual c++ 2015-2019 Redistributable (x64) 14.29.30037" under Apps & Features.
