### ISSUE TITLE
Assembly On MonoGame for Advanced Learning Development

### ISSUE THREAD

**Issue by abakasam** [MonoGame/MonoGame#7519]
I need help with making something for the Game Boy... I am programming in C and Z80... Sooooo, I need Cfront for assembly? Okay.

C++ > C > Cfront > Assembly > Z80 (no ARM, maybe on Android not here)

I need compilation support. I do not want to rewrite C++ or C and go to Z80 with Cfront. Z80 is the goal. If I wanted C++ or C I would have a PSP, laughing... and I already do just rushing to the devkit before it has to be hidden like the Cell stuff from IBM when you have a PS4 with Pro hopefully because if not all I will be buying is a PS3 or 2 for the emotion.

First rule, Stay a plumber.
Second rule, Stay with mother teresa.
Third rule, Do not get angry without enough electrolytes.

I need compilation support. I do not want to rewrite C++ or C and go to Z80 with Cfront. Z80 is the goal.
C++ > C > Cfront > Assembly > Z80 (no ARM, maybe on Android not here)

- MonoGame 4
- Windows
- Game Boy

**Comment by abakasam** [comment]
Thanks. I saw LeBoy.

Also, with MonoGame 4, was compilation kept for PSP, including its emulator without the SDK.

Sam

**Comment by mrhelmut** [comment]
PSP never was supported and PS Vita has been deprecated.

For further discussion, please refer to the community forums: https://community.monogame.net/

Github is meant for issue tracking.
