### ISSUE TITLE
iOS `Texture2D` constructor from bgthread hangs

### ISSUE THREAD

**Issue by Mindfulplays** [MonoGame/MonoGame#7520]
Calling `new Texture2D` or `Texture2D.SetData` from background thread queues up a workitem in `Threading.BlockOnUIThread` however, the workitem never gets invoked.

I found out that [unlike Android/SDL platforms](https://github.com/MonoGame/MonoGame/search?q=threading.run), `Threading.Run` is not invoked in iOS (and possibly other platforms?) in [`iOSGameWindow`](https://github.com/MonoGame/MonoGame/blob/a9e5ae6befc40d7c86320ffdcfcd9d9b66f786a8/MonoGame.Framework/Platform/iOS/iOSGameWindow.cs).

I worked around this by moving the call to the UI thread.
At a high-level, is there anything that prevents moving the texture loading to happen from a worker thread as opposed to the main UI thread? This will avoid any jank even if there is a loading screen being presented.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- MacOS

#### What MonoGame platform are you using:
iOS/OpenGL

**Comment by TechnologicalPizza** [comment]
OpenGL only allows operations from the main thread, so there must be some synchronization.
But this iOS issue seems like a missed bug.

**Comment by Mindfulplays** [comment]
Got it, I figured as much but my knowledge is from a decade ago so was hoping things changed😄

Happy to send a fix later if this is considered an actual bug.

**Comment by mrhelmut** [comment]
Yeah, trying to load OpenGL textures from a thread on iOS is extremely prone to corrupting textures or eventually generating errors.
```Threading.Run()``` missing is an oversight. If anyone has the time to setup a PR for this, that would be very welcome.

**Comment by Mindfulplays** [comment]
This is my first time contributing, could you please let me know if I have done anything foolish with my PR process?
Thank you.
