### ISSUE TITLE
Dotnet command failure in `MonoGame.Content.Builder.Task.targets`

### ISSUE THREAD

**Issue by Oberon-Zheng** [MonoGame/MonoGame#7538]
I tried to create a project with MonoGame project templates extension. But I found that I got some problems in dependencies.
Error log shows that error occurred due to command failure at line 138 in `MonoGame.Content.Builder.Task.targets` :
```
    <Exec
      Condition="'%(ContentReference.FullPath)' != ''"
      Command="$(DotnetCommand) $(MGCBPath) $(MonoGameMGCBAdditionalArguments) /@:&quot;%(ContentReference.FullPath)&quot; /platform:$(MonoGamePlatform) /outputDir:&quot;%(ContentReference.ContentOutputDir)&quot; /intermediateDir:&quot;%(ContentReference.ContentIntermediateOutputDir)&quot; /workingDir:&quot;%(ContentReference.FullDir)&quot;"
      WorkingDirectory="$(MSBuildProjectDirectory)" />
```

I finally got the reason is that my username contains **a space character** which made cmd couldn't identify the `dotnet C:\XXX XXX\...\mgcb.dll` command hence failed. This failure causes namespace `Microsoft.Xna` could not be found.

I solved this by modifying this line with `$(MGCBPath)` embraced with quotes :
```
    <Exec
      Condition="'%(ContentReference.FullPath)' != ''"
      Command="$(DotnetCommand) &quot;$(MGCBPath)&quot; $(MonoGameMGCBAdditionalArguments) /@:&quot;%(ContentReference.FullPath)&quot; /platform:$(MonoGamePlatform) /outputDir:&quot;%(ContentReference.ContentOutputDir)&quot; /intermediateDir:&quot;%(ContentReference.ContentIntermediateOutputDir)&quot; /workingDir:&quot;%(ContentReference.FullDir)&quot;"
      WorkingDirectory="$(MSBuildProjectDirectory)" />
```
and saved the target file.

This problem is not so severe nor hard to fix but I think the project template should take this in consideration and prevent users from modifying those underlying files.

-----

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL
- or maybe other platforms either.

##

**Comment by Apostolique** [comment]
This was already fixed in #7304 for the develop branch. It just hasn't been released yet. (will be fixed in MonoGame 3.8.1.*)
