### ISSUE TITLE
Window.Handle is not the real handle of GameWindow 

### ISSUE THREAD

**Issue by Garneg** [MonoGame/MonoGame#7539]
After some failed interactions with Window.Handle and user32.dll (Well, you know, this lib requires a handle to do stuff) i decided to check handle 
via FindWindow(user32.dll function) and compared it with Window.Handle and they were not the same.  I think maybe SDL2 gives us invalid handle.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8,0

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Apostolique** [comment]
What were you trying to do that didn't work? I have this example project that uses the window handle without any issues. <https://github.com/Apostolique/MonoGameContinuousUpdate/blob/main/Game/GameRoot.cs#L24>

**Comment by TechnologicalPizza** [comment]
user32 takes the OS handle, while MonoGame only exposes the SDL2 window handle.
You would need to call into SDL2 to get the underlying OS window handle.
