### ISSUE TITLE
Audio does not work after headphones connection

### ISSUE THREAD

**Issue by Garneg** [MonoGame/MonoGame#7542]
If you will connect headphones while game is running, all audio will stop working. The same thing happens when you disconnect headphones, that was connected before game start.

MonoGame version: MonoGame 3.8

 OS: Windows 10

 MonoGame platform: DesktopGL

**Comment by mrhelmut** [comment]
This is not quite a "bug" but a limitation of both the Windows mixing and OpenAL. If you plug/unplug something while an application is running on DesktopGL, the app can't be aware of it and can't switch devices for yourself. You have to manually switch the output in your Windows output mix.
