### ISSUE TITLE
Template  build error

### ISSUE THREAD

**Issue by ZhiZe-ZG** [MonoGame/MonoGame#7545]
I create a game by

```
dotnet new mgdesktopgl -o GuessNumber
```

then build it

```
cd GuessNumber
dotnet build
```

and I get

```
CSC : error CS7065: Error building Win32 resources -- Unable to read beyond the end of the stream. [D:\GuessNumber\GuessNumber.csproj]

Build FAILED.
```

I'm using visual studio 2022 preview and dotnet 6.0 but I have installed the dotnet core 3.1(mgcb-editor  and MonoGame.Templates.CSharp as well).

 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

**Comment by ZhiZe-ZG** [comment]
I fix this by delete 

```
<ApplicationIcon>Icon.ico</ApplicationIcon>
```
in my GuessNumber.csproj 

But I don't know why.

**Comment by Apostolique** [comment]
I ran into this issue the other day. I wonder if the icon in the NuGet package got corrupted somehow? You should be able to replace the one in your project with this one; <https://github.com/MonoGame/MonoGame/blob/develop/Templates/MonoGame.Templates.CSharp/content/MonoGame.Application.DesktopGL.CSharp/Icon.ico>.

**Comment by ZhiZe-ZG** [comment]
@Apostolique  Thanks, it works. But I create the project from template. I'm curious how this happend. (Now I can create normal new project.)

**Comment by BlueElectivire** [comment]
I tried replicating bug this and failed (The project was built successfully). 
Any specific steps to replicate this not mentioned in the original issue?
Perhaps some bug with the preview versions of VS2022 that was taken care of in the full release.
This seems to be working ok now.

**Comment by Jjagg** [comment]
I'm going to close this under the assumption it was an issue with a VS or .NET preview release. Please reopen if you still run into this issue.
