### ISSUE TITLE
KeyboardInput.Show not working in UWP on Xbox

### ISSUE THREAD

**Issue by tomcashman** [MonoGame/MonoGame#7552]
Receive the following error when calling the API.

```
Exception thrown: '<unknown>' in System.Private.Interop.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.dll
EETypeRva:0x00514F28
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Xbox

#### What MonoGame platform are you using:
- UWP

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
