### ISSUE TITLE
Publishing for linux with pipeline included targets wrong name for Freeimage library

### ISSUE THREAD

**Issue by AliciaRaven** [MonoGame/MonoGame#7556]
When publishing my game, i have to include Pipeline to import models and textures at runtime. When publishing for Linux x64, my linux tester is reporting that texture imports are crashing because monogame tries to find "libFreeImage.so" but the file that is packaged is "libfreeimage-3.17.0.so"

Similar to #5470 but that issue has been marked fixed and closed by @harry-cpp

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Developing with Windows. Issue shows when publishing for Linux x64 and running on that platform.

#### What MonoGame platform are you using:
- DesktopGL

**Comment by harry-cpp** [comment]
When we are packaging libraries into a nuget, they don't use the name of the link parameter:
- https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/MonoGame.Framework.Content.Pipeline.csproj#L104

**Comment by AliciaRaven** [comment]
so this is a confirmed bug and not something im missing? Thanks for fast response @harry-cpp

**Comment by AliciaRaven** [comment]
Will packages be updated or will we have to wait for next release?
