### ISSUE TITLE
.net 6 iOS FillTouchCollection crash.

### ISSUE THREAD

**Issue by Dokug** [MonoGame/MonoGame#7614]
Hello, 
I experimented with updating the MonoGame projects to .Net 6 and noticed that the iOS project crashes when a touch is registered. The result is that "An arithmetic operation resulted in an overflow".

This happens in MonoGame.Framework.iOS/Platform/iOS/iOSGameView_touch.cs/FillTouchCollection(NSSet touches).
https://github.com/MonoGame/MonoGame/blob/71b25eece3d1b92d6c9f3f32cb51dc054e099133/MonoGame.Framework/Platform/iOS/iOSGameView_Touch.cs#L127

The problem seems to be that the Event id is using `touch.Handle.ToInt32()`.
However, `touch.Handle` seems to be a 64 bit integer/pointer under "net6.0-ios".

For myself, I currently worked around the problem with this code block, replacing line 127 in the above mentioned file:
`int id;
if (IntPtr.Size == 8) id = i; /*64 bit process*/
else id = touch.Handle.ToInt32 ();`

If there is interest in my MonoGame net6.0 port I'm of course happy to provide a PR, however the majority of the work is just changing the target framework and commenting out some lines in the .csproj files.

Best regards,
Dokug

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8 develop

#### What operating system are you using:
- macOS

#### What MonoGame platform are you using:

- DesktopGL/iOS

**Comment by ayousuf23** [comment]
I think this is necessary to fix because .NET 6 is a LTS release and .NET 6 is the future of Xamarin. @harry-cpp would you accept a PR (that @Dokug would provide) for this issue?

**Comment by mrhelmut** [comment]
Fixed in #7688
