### ISSUE TITLE
Geometric shape hash methods depend on mutable properties

### ISSUE THREAD

**Issue by JacksonDorsett** [MonoGame/MonoGame#7619]
While looking through the gethashcode methods for some of the classes i noticed that many classes such as the Point class calculate the hash value depending on mutable properties.
here is the current implementation:

```c#
/// <summary>
        /// Gets the hash code of this <see cref="Point"/>.
        /// </summary>
        /// <returns>Hash code of this <see cref="Point"/>.</returns>
        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = hash * 23 + X.GetHashCode();
                hash = hash * 23 + Y.GetHashCode();
                return hash;
            }

        }
```
the current implementation would cause a bug if we were storing points in an dictionary and decided to change the points values then look up the value in the dictionary since the calculation would be different. Below is an example of the bug.

```c#
Point p = new Point(10,10);
Dictionary<Point, String> playerLocation= new HashSet<Point>();
playerLocation.add(p, 'Aurthor');
Assert.Contains(p,playerLocation.Keys); //Will succeed
p.X = 20;
Assert.Contains(p,playerLocation.Keys); //Will fail because the values used to calculate the hashcode will be different
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by bjornenalfa** [comment]
There is no bug in your example. Point is a struct, not a class.
