### ISSUE TITLE
.NET 6 Support

### ISSUE THREAD

**Issue by yhl1219** [MonoGame/MonoGame#7632]
# .NET 6 Support

Is there any plan to move alone to .NET 6 since it is another LTS version? It seems this may not be a big problem and now most up-to-date `dotnet` toolchain already set sdk version 6 by default.

Maybe I could try to build it with .NET 6 first or so.

**Comment by yhl1219** [comment]
It seems ok with .NET 6 (although I don't have Android SDK with the proper version so I couldn't build that Android support)

**Comment by Dokug** [comment]
Any net6.0-ios app crashes currently.
See: https://github.com/MonoGame/MonoGame/issues/7614

**Comment by lechgu** [comment]
the desktop (mac+windows opengl) seems to work with .net 6 without much trouble.
I don't use the content pipeline though.

**Comment by damian-666** [comment]
i have a shared public test rig  using netstandard core,  thin .net 6 launchers, with shared content building also, on windows w vs2022  targeting droid, console dx, console Gl...     u might need netcore 3.1 installed tho for content to build... so if i touch a shader, build , run , all works ..  i'm waiting before i try android w xamarin  on net6 tho... i think its gonna happen and or xamarin will change significantly soon so ill wait on that.. also windows might support droid apps, , ARM apps, and partial emulation,  soon , that might be when the best approach emerges, since emulator is terribly slow, 
 and completely broken on win 11.   https://github.com/damian-666/MGShadersXPlatform

**Comment by stromkos** [comment]
@mrhelmut, What is the official status of .Net 6(LTS) support? 

Apple has released their silicon Mac's and Microsoft has chosen not to port `netcoreapp3.1` to the ARM Mac platform.

**Comment by Beyley** [comment]
> @mrhelmut, What is the official status of .Net 6(LTS) support? 
> 
> Apple has released their silicon Mac's and Microsoft has chosen not to port `netcoreapp3.1` to the ARM Mac platform.
> 
> 
> 
> 

it should just work on .net 6

**Comment by mrhelmut** [comment]
It should just work, but for good measure there's a few maintenance updates to make sure that both the pipeline and building works with net6 (so far the pipeline might still need a net5 install, but building and running games should just work with net6).

**Comment by theparticleman** [comment]
FWIW, I installed both .NET 5 and .NET 6 installed. I changed my csproj to target `net6.0`. If I do a `dotnet build` I get errors from `MonoGame.Content.Builder.Task.targets` referring to `netcoreapp3.1` paths. If I then install .NET 3.1 the errors are resolved. So even though compiling the code seems to work fine just by switching to `net6.0`, there are things in the content pipeline that appear to still require .NET 3.1.

**Comment by damian-666** [comment]
thast true but once u do all that is works fine so noone bother to submit a PR to fix it.    bugt i agree too many people complain but don't help to fix theres like only a few with time to submit PRs.    also for mutlplatform u should use teh resource editor once it will set a target... erase that , then it will compile for whatever target, and then start to edit the content file by copy paste. you dont need the UI to work perfectly these are free tools.  its worth it to use vs 2022 and .net6 beleivev me .   jump the hoops .  i did show a rig that builds 3 plafroms plus shaders and content all shared.    no repeat code.   https://github.com/damian-666/MGShadersXPlatform     it works on vs 2022 after all those net3.1 5, and 6 installed.. then vscode i think might even install it for u , dont remember butg it sucks so use vs2022

**Comment by damian-666** [comment]
https://github.com/MonoGame/MonoGame/issues/7614    i didnt add ios tho.. but its can be worked around if u need itr... ARM adn xamarin are not enjoying the full bnenet of net 6 tho msft is working on it i think..  ome of there Surface use ARM and the intel ones blow hot air..

**Comment by mrhelmut** [comment]
Yes, the MonoGame.Content.Builder does require netcore 3.1, but that's only for building content. The actual game assemblies can be built and run with either NET 5, 6, or 7. netcore 3.1 should never be a requirement at runtime.

Actually making MonoGame.Content.Builder NET 5/6 compatible is the only thing preventing us from releasing a 3.8.1 MG. Our target is to make 3.8.1 compatible with NET6 and VS2022.

**Comment by evilkomododragon** [comment]
So as I understand correctly, the MonoGame.Content.Builder code is the most work in all of the code to be compatible with NET6 and VS2022?
