### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [MonoGame/MonoGame#7633]
Hey there!

I belong to an open source security research community, and a member (@dwisiswant0) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mrhelmut** [comment]
Security concerns will gladly be received through contact at the bottom of the about page: https://www.monogame.net/about/

**Comment by JamieSlome** [comment]
@mrhelmut - it looks like we sent a couple of e-mails to your `admin@...` address, but haven't received any response.

If more helpful, you can view the report directly here:
https://huntr.dev/bounties/5bc48008-da9c-415e-9a02-49453a0297f9

It is currently private and only accessible to maintainers with repository write permissions 👍
