### ISSUE TITLE
Suggestion: Add Buttons.None, to match Keys.None

### ISSUE THREAD

**Issue by JamesC01** [MonoGame/MonoGame#7634]
I'll preface this by saying that this may just be me being naive, and this might not fit with the framework, so sorry if that's the case.

I'm trying to write a re-usable input class, which has Actions, which represent the inputs.

public class Action
{
    public Keys key { get; set; } = Keys.None;
    public Buttons button { get; set; } = Buttons.None;
    public MouseButtons mousebutton { get; set; } = MouseButtons.None;
}
In some cases, you might want a keyboard only, or mouse only action. The problem is, Buttons.None doesn't exist. (MouseButtons was simple enough to make, though, so that's not a problem.) I could make Buttons nullable, and I think that would work, but doesn't feel like the most consistent choice.

I read in another issue that when polling for controller input, you'll never get the value None, which is a problem, I suppose. Adding it just for some edge cases may not be the best choice, but it also seems fairly consistent. Why would their only be Keys.None, and not Buttons.None.

**Comment by JamesC01** [comment]
I'm reading my code back again, and I'm thinking that making all of them nullable might be the better choice anyway. All I'm doing is checking if the key isn't none, and then returning the state of the key. I may be wrong, but nullable feels like it would be a cleaner choice there instead. Not sure.

**Comment by Apostolique** [comment]
What are you trying to do? I have this library, maybe it helps you with inputs? <https://apostolique.github.io/Apos.Input/>

**Comment by JamesC01** [comment]
@Apostolique Yeah, basically exactly what I'm trying to do. I'm mainly doing this as practice, though, so I'm trying to do it myself. I've figured out a fairly clean way by making the enums nullable, though.

**Comment by mrhelmut** [comment]
```Buttons``` is a flag, so you can use it to do something like this: ```public Buttons button { get; set; } = (Buttons)0; // no button set```

It's not elegant, but it works.

If you feel like it, contributing a ```Buttons.None = 0``` is straightforward and I'd be happy to merge it.
