### ISSUE TITLE
Monogame game window takes whole screen width and height

### ISSUE THREAD

**Issue by Moon422** [MonoGame/MonoGame#7636]
I am using MonoGame 3.8 (Desktopgl project template) on a Linux Mint 20.2 machine. I have Dotnet Core 3.1 and Dotnet 6 installed and I am using wine to compile shaders. I am facing a strange issue where the game window takes up the whole screen width and height. "_graphics.PreferredBackBufferWidth", "_graphics.PreferredBackBufferHeight" and "_graphics.IsFullScreen" is set to 800, 840 and false. The window appears in windowed mode as the settings are set, but the width and height takes up whole space. I have used Monogame (DesktopDX project template) on windows machine, but I have not faced such issue earlier. Also, I have used Monogame 3.7 on both windows and linux, it did not have any issue.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Linux (linux mint)

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Apostolique** [comment]
If you set
```csharp
Window.AllowUserResizing = true;
```
Are you able to resize the window?

**Comment by Moon422** [comment]
> If you set
> 
> ```cs
> Window.AllowUserResizing = true;
> ```
> 
> Are you able to resize the window?

Yes, the window is resizable after setting the property. By the way, does everyone who is using Linux as his or her platform of development face the same issue, or is it just me? Or is it a distro (linux mint 20.2) specific problem?

**Comment by Apostolique** [comment]
You can try my app to see if it has the same issue: <https://apos.itch.io/mitten>.

**Comment by Beyley** [comment]
> > If you set
> > ```cs
> > Window.AllowUserResizing = true;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Are you able to resize the window?
> 
> Yes, the window is resizable after setting the property. By the way, does everyone who is using Linux as his or her platform of development face the same issue, or is it just me? Or is it a distro (linux mint 20.2) specific problem?

I dont have that issue, im running Arch Linux with nvidia drivers and i3wm

**Comment by pherbeas** [comment]
I have the same issue with new projects on Linux Mint 19.3. However, I can change the settings successfully.  Are you doing:

_graphics.ApplyChanges());

after you change the settings?

**Comment by gingeneer** [comment]
I'm having the same issue on arch linux, with intel graphics and kde plasma. I'm doing the following in the Game constructor:
```
_graphics.PreferredBackBufferWidth = 800;
_graphics.PreferredBackBufferHeight = 480; 
_graphics.IsFullScreen = false;
_graphics.ApplyChanges();
```
The window still takes up the whole screen.

**Comment by ohtrobinson** [comment]
Try it in the `Initialize()` method, I don't believe it works correctly in the constructor.

**Comment by gingeneer** [comment]
Moving it to the initialize method worked, thanks :)

**Comment by Apostolique** [comment]
It's supposed to work in the constructor but the current released version is bugged. It's fixed in the develop branch already.

**Comment by Moon422** [comment]
Probably that's the reason monogame 3.7 worked...
