### ISSUE TITLE
Include SDL2 for M1 Mac

### ISSUE THREAD

**Issue by ayousuf23** [MonoGame/MonoGame#7638]
Running MonoGame on M1 Mac will result in an error due to a mismatch between .NET and SDL2 architecture. The SDL2 dylib file should support both x64 and arm64.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- macOS

#### What MonoGame platform are you using:

- DesktopGL

**Comment by ayousuf23** [comment]
@harry-cpp Let me know what I can do to fix this issue.

**Comment by NoFr1ends** [comment]
I guess that would require to update the dylib here: https://github.com/MonoGame/MonoGame.Dependencies/tree/master/SDL/MacOS/Universal

And for full M1 support there are even more dependencies which have to get compiled for arm64

**Comment by galexandreg** [comment]
I unfortunately don't really know how I could help with this, but I had to change my mac recently and it really broke monogame development using the latest release version. The content builder task needs a .net3 runtime, but the dotnet command on arm doesn't find x64 versions, so building with dotnet build doesn't work. You have to manually install and set the path for the x64 version of dotnet for everything to work. But even then, OmniSharp only supports native versions, so it's looks impossible to properly use the tools in VS to build and debug...

In the end, it's possible to make everything work, but it's a bit messy. 🤔 Or I may be missing something...
I hope there is not too much other stuff to fix to make this work natively on new macs. 😄

**Comment by mrhelmut** [comment]
I'll look into the PR but we'll also be needing OpenAL-Soft to be built for ARM64.

As noted by @NoFr1ends in their PR, this would only allow games to run natively without rosetta on M1, but the content pipeline requires much more dependencies to be updated.

**Comment by mrhelmut** [comment]
Fixed by #7690
