### ISSUE TITLE
MonoGame / SDL2 2.0.14 detects keyboard as controller and wreaks havok

### ISSUE THREAD

**Issue by hollunder** [MonoGame/MonoGame#7646]
I ran into this issue with Stardew Valley and it took me a long time to narrow it down.
What happened since Stardew Valley 1.5.6 (probably since 1.5.5, which I never had) was that on startup my keyboard became unusable and the XBox 360 controller was also not detected. My keyboard remained unusable until replugged. All device nodes in /dev/input relating to the keyboard were gone.

Stardew Valley switched to MonoGame 3.8 starting with version 1.5.5. MonoGame 3.8 uses libSDL2 2.0.14.
My keyboard is rather special, a Wooting Two, which can act as a XBox controller on top of being a keyboard. 
Naturally I looked into all things related to the keyboard. However, whether that functionality is disabled or not does not matter, the behavior of the game is always the same. Whatever I tried, and I tried a lot, it did not change the outcome.

Eventually I tried something rather simple, renaming the shipped libSDL2-2.0.so.0. The game then used the systems libSDL2-2.0.so.0 and worked like a charm again.
I wrote a little program to find the version of the shipped libSDL2-2.0.so.0. 2.0.14, which matches the version MonoGame dependencies. My systems SDL2 version is 2.0.20. So whatever causes this issue either has to do with SDL 2.0.14 or its use in Monogame.

What I did not yet try:
Determine the version of SDL2 Stardew 1.5.4 used (which still worked).
Determine whether SDL2 2.0.15 to 2.0.19 work.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8 as used by Stardew Valley 1.5.6

#### What operating system are you using:
- Linux

#### What MonoGame platform are you using:
- DesktopGL

**Comment by mrhelmut** [comment]
We'll be bumping the SDL version at some point. It is not related to MonoGame, it is likely the game controller driver of SDL doing that. In the meantime, the Stardew Valley team can update their own SDL independently of what MonoGame does.
