### ISSUE TITLE
DesktopGL project has broken dependencies

### ISSUE THREAD

**Issue by Ombrezz** [MonoGame/MonoGame#7651]
When making a DesktopGL project with `dotnet new mgdesktopgl`, the project generates but OmniSharp nor the .NET Compiler can detect any dependencies, not even Microsoft.NETCore.App.

OmniSharp Log: https://pastebin.com/zaxmeGej
.NET Compiler Log: https://pastebin.com/rLBVBuEk

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

**Comment by bjornenalfa** [comment]
You do not have dotnet 3.1 installed
