### ISSUE TITLE
[DesktopGL] Memory leak on static variable (GL.Extensions)

### ISSUE THREAD

**Issue by felaugmar** [MonoGame/MonoGame#7665]
[`List<String> [Static variable MonoGame.OpenGL.GL.Extensions]`](https://github.com/MonoGame/MonoGame/blob/v3.8/MonoGame.Framework/Platform/Graphics/OpenGL.cs#L1428)

This ^ variable is used to store 'OpenGL extensions', but it is never cleared and grows forever.
I noticed that it increases when the game runs.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
Could you provide more context regarding your use case of MG? The only reason I would see for this collection to grow would be that you are creating several GraphicalContext.

**Comment by felaugmar** [comment]
> Could you provide more context regarding your use case of MG? The only reason I would see for this collection to grow would be that you are creating several GraphicalContext.

Yes, I'm disposing and recreating the `Game` instance every time there is an unhandled exception, probably recreating the `GraphicalContext` as you pointed.

**Comment by mrhelmut** [comment]
While the fix should be straightforward, I'd like to note that this isn't a use case within the scope of MonoGame. Restarting your game because it crashed doesn't sound like a good practice.
