### ISSUE TITLE
monogame extension

### ISSUE THREAD

**Issue by lonely-unicorn** [MonoGame/MonoGame#7666]
Hi

The monogame extension is not found in visual studio 2022 community

https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_windows.html

So we can't install it!

**Comment by lonely-unicorn** [comment]
Also this doesn't work: https://docs.monogame.net/articles/getting_started/2_creating_a_new_project_netcore.html

I get this error:

`
dotnet new mgdesktopgl -o MyGame

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.201

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
No templates found matching: 'mgdesktopgl'.

To list installed templates, run:
   dotnet new --list
To search for the templates on NuGet.org, run:
   dotnet new mgdesktopgl --search
`

When I want to install a new template, it's not in there:

`dotnet new --list
These templates matched your input:

Template Name                                 Short Name           Language    Tags
--------------------------------------------  -------------------  ----------  --------------------------
ASP.NET Core Empty                            web                  [C#],F#     Web/Empty
ASP.NET Core gRPC Service                     grpc                 [C#]        Web/gRPC
ASP.NET Core Web API                          webapi               [C#],F#     Web/WebAPI
ASP.NET Core Web App                          webapp,razor         [C#]        Web/MVC/Razor Pages
ASP.NET Core Web App (Model-View-Controller)  mvc                  [C#],F#     Web/MVC
ASP.NET Core with Angular                     angular              [C#]        Web/MVC/SPA
ASP.NET Core with React.js                    react                [C#]        Web/MVC/SPA
ASP.NET Core with React.js and Redux          reactredux           [C#]        Web/MVC/SPA
Blazor Server App                             blazorserver         [C#]        Web/Blazor
Blazor WebAssembly App                        blazorwasm           [C#]        Web/Blazor/WebAssembly/PWA
Class Library                                 classlib             [C#],F#,VB  Common/Library
Console App                                   console              [C#],F#,VB  Common/Console
dotnet gitignore file                         gitignore                        Config
Dotnet local tool manifest file               tool-manifest                    Config
EditorConfig file                             editorconfig                     Config
global.json file                              globaljson                       Config
MSTest Test Project                           mstest               [C#],F#,VB  Test/MSTest
MVC ViewImports                               viewimports          [C#]        Web/ASP.NET
MVC ViewStart                                 viewstart            [C#]        Web/ASP.NET
NuGet Config                                  nugetconfig                      Config
NUnit 3 Test Item                             nunit-test           [C#],F#,VB  Test/NUnit
NUnit 3 Test Project                          nunit                [C#],F#,VB  Test/NUnit
Protocol Buffer File                          proto                            Web/gRPC
Razor Class Library                           razorclasslib        [C#]        Web/Razor/Library
Razor Component                               razorcomponent       [C#]        Web/ASP.NET
Razor Page                                    page                 [C#]        Web/ASP.NET
Solution File                                 sln                              Solution
Web Config                                    webconfig                        Config
Windows Forms App                             winforms             [C#],VB     Common/WinForms
Windows Forms Class Library                   winformslib          [C#],VB     Common/WinForms
Windows Forms Control Library                 winformscontrollib   [C#],VB     Common/WinForms
Worker Service                                worker               [C#],F#     Common/Worker/Web
WPF Application                               wpf                  [C#],VB     Common/WPF
WPF Class Library                             wpflib               [C#],VB     Common/WPF
WPF Custom Control Library                    wpfcustomcontrollib  [C#],VB     Common/WPF
WPF User Control Library                      wpfusercontrollib    [C#],VB     Common/WPF
xUnit Test Project                            xunit                [C#],F#,VB  Test/xUnit
`

So how to use monogame with visual studio 2022 if nothing works???

**Comment by Apostolique** [comment]
You can do:

Install
```
dotnet new --install MonoGame.Templates.CSharp
```

Get the MonoGame Content Pipeline
```
dotnet tool install --global dotnet-mgcb-editor
mgcb-editor --register
```

Create a new game and run it
```
dotnet new mgdesktopgl -o MyGame
cd MyGame
dotnet run
```

Publish
```
dotnet publish -c Release -r win-x64 -o artifacts/windows
dotnet publish -c Release -r osx-x64 -o artifacts/osx
dotnet publish -c Release -r linux-x64 -o artifacts/linux
```

**Comment by lonely-unicorn** [comment]
But I want to work with visual studio. How can I do this?
I never use command line

Why is the monogame extension not found in visual studio 2022?

**Comment by Beyley** [comment]
> But I want to work with visual studio. How can I do this?
> I never use command line
> 
> Why is the monogame extension not found in visual studio 2022?

because it's not published in VS2022

**Comment by lonely-unicorn** [comment]
Ok I see
But this simple issue is holding back many many beginners who can't even install monogame and eventually will give up.
I now finally installed it using CLI (after some days of learning) but I really hope this extension is published as soon as possible!
