### ISSUE TITLE
Feature Request: Publish a Visual Studio 2022 extension to the VS2022 marketplace

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7669]
With Visual Studio 2022 now nearing GA (and frankly everyone is using it), the Visual Studio 2019 extension needs updating and publishing to the Visual Studio 2022 marketplace.

This will also likely need an update for the Mac extension as well.

This should then be publicised on the MonoGame News site once released.

## Linked issues:

* https://github.com/MonoGame/MonoGame/issues/7616
* https://github.com/MonoGame/MonoGame/issues/7666

**Comment by lonely-unicorn** [comment]
yes please!!!
Highly needed for beginners who want an easy way to install MonoGame.
Using CLI to install is sometimes too much for beginners (I first had troubles too with it).

**Comment by simoneddeland** [comment]
This would be a greatly appreciated to make it easier for my students to install MonoGame.

**Comment by mrhelmut** [comment]
The 3.8.1 extensions are now live on the [marketplace](https://marketplace.visualstudio.com/items?itemName=MonoGame.MonoGame-Templates-VSExtension) (VS2022) and the [github release](https://github.com/MonoGame/MonoGame/releases/tag/v3.8.1) (VS2022 for mac).

Please note that at the time of posting, every packages and documentation might not be fully uploaded yet.
