### ISSUE TITLE
Content Builder Editor for Mac won't build: "NuGet MSBuild targets are missing"

### ISSUE THREAD

**Issue by tadashibashi** [MonoGame/MonoGame#7686]
Hi, when I try to build the MonoGame content editor for Mac, I keep receiving the error "NuGet packages need to be restored before building. NuGet MSBuild targets are missing and are needed for building. The NuGet MSBuild targets are generated when the NuGet packages are restored. (MonoGame.Content.Builder.Editor.Mac)"

This happens even after apparently successfully restoring and updating the packages in Visual Studio for Mac (8.10.21).

(As a side, there is also a problem with the content builder app from dotnet where it immediately crashes, so I don't have any way to use the GUI on Mac. The pipeline tool is working though.)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- MacOS 12.3.1

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
Pretty sure there was an issue open about that but I can't find it.

This is different issue than this one. The reason why MGCB doesn't run without Rosetta is because MGCB dependencies are not built with M1 support. Here the libraries that would need to be rebuilt with arm64+x64 support are:
- FreeImage
- NVTT
- libPVRTexLibWrapper
- freetype 6
- libpng16
- ffmpeg
- ffprobe

**Comment by rosingrind** [comment]
> Assuming it be fixed for the upcoming 3.8.1 release. Feel free to reopen if it persists on 3.8.1.

**Solution:** MonoGame.Tools.Mac
**MonoGame Version:** 3.8.1
**OS:** MacOS Ventura 13.2 (M1)

NuGet Package Restore doesn't help, freshly cloned 3.8.1 tag produces following errors when building:

> Error: NuGet packages need to be restored before building. NuGet MSBuild targets are missing and are needed for building. The NuGet MSBuild targets are generated when the NuGet packages are restored. (MonoGame.Content.Builder.Editor.Mac)
> 
> Error: NuGet packages need to be restored before building. NuGet MSBuild targets are missing and are needed for building. The NuGet MSBuild targets are generated when the NuGet packages are restored. (MonoGame.Content.Builder.Editor.Launcher.Mac)
