### ISSUE TITLE
request: add monogame.extended?

### ISSUE THREAD

**Issue by evilkomododragon** [MonoGame/MonoGame#7700]
Hi

Since the developer of monogame.extended is now working on katabasis and maybe monogame.extended is not actively updated anymore, would it maybe be a good idea to let monogame absorb monogame.extended?
There are content importers for Tiled maps, ... and many usefull features that blend with monogame like magic :)

What do you think?

**Comment by lithiumtoast** [comment]
Hey, `MonoGame.Extended` will be updated when MonoGame is updated. Progress in being directed towards Katabasis otherwise for now.

**Comment by mrhelmut** [comment]
MonoGame's scope will likely stay as it is: a bare-bone "bring your own tools" framework that guarantees that things run everywhere, including consoles.

It is already very demanding to maintain and expanding that scope doesn't sound desirable in the foreseeable future (it's not set, but I prefer to not give false promises here).
MonoGame.Extended and Nez do indeed a great job at providing additional features and keeping things maintainable for everyone. MonoGame isn't introducing breaking changes, so I guess those projects will be easy to keep up-to-date and likely to stay around.
