### ISSUE TITLE
Compile OpenAL-Soft for macOS with x64+ARM binaries and back-compat to older macOS

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7701]
In order to properly support M1 Apple silicon, we need a build of [OpenAL-Soft](https://github.com/kcat/openal-soft) built with backward compatibility down to macOS 10.9 and with both ARM64 and x86_64 binaries into a universal dylib.

This should be straightforward for whoever is used to build native stuff on mac with CMake.

**Comment by lithiumtoast** [comment]
I already build SDL2 for macOS M1 using CMake but it should be similar for any other C library using CMake. The trick is to use `CMAKE_OSX_ARCHITECTURES` flag. I like to use `CMAKE_OSX_ARCHITECTURES=x86_64;arm64` to get a single "universal" `.dylib`. The consequence is that compile times are longer and the file size is larger, but you don't have to worry about whether it is x64 or arm64 for P/Invoke which is nice.

**Comment by mrhelmut** [comment]
The CMake config of OpenAL-Soft doesn't seem to set backward compatibility for macOS (it seems to be doing it only for iOS).

To make a proper build for MonoGame, we should add this the CMakeLists.txt:
```set(CMAKE_OSX_DEPLOYMENT_TARGET "10.9" CACHE STRING "Minimum OS X deployment version")```

**Comment by harry-cpp** [comment]
net6.0 doesn't support macOS version lower than 10.15: https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md

**Comment by mrhelmut** [comment]
Yes, I've read that recently, and it would make sense to follow that requirement for the dependencies.
