### ISSUE TITLE
bug?: GamePad (HORI Fighting Stick MINI) buttons switched

### ISSUE THREAD

**Issue by evilkomododragon** [MonoGame/MonoGame#7704]
Hi

I'm trying to read the input from my game controller. Here I can read xbox controllers are supported, but are other USB controllers also supported?

http://rbwhitaker.wikidot.com/monogame-xbox-controller-input

For example, I'm using an arcade stick connected with USB connection: https://stores.horiusa.com/fighting-stick-mini-for-nintendo-switch/
See attached manual, it's XInput controller.

[[NSW-149U] Fighting Stick Mini.pdf](https://github.com/MonoGame/MonoGame/files/8550044/NSW-149U.Fighting.Stick.Mini.pdf)

When I read up, down,left, right of the stick, all values are read correctly.
However when I want to read the button A, B, X and Y, the values are switched.

The following code is triggered when pressing Y (not X) so X and Y are switched. The same happens for A and B.

`if(gamePadState.Buttons.X == ButtonState.Pressed)
{
    // do something
}`

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8, .NET 6.0

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:
- DesktopGL

**Comment by evilkomododragon** [comment]
Anybody who can tell me how to read the R, L, ZR and ZL buttons or is this not supported?

![afbeelding](https://user-images.githubusercontent.com/103590956/164985136-3edede2a-9f59-4bfb-ac11-ea028b60e0e7.png)

**Comment by mrhelmut** [comment]
Actually what you describe is perfectly correct in regard to API design.

MonoGame follows XInput wiring convention, with A placed south and Y placed north (which became an industry standard in regard to PC API design).
This Hori controller follows the Nintendo naming convention, which has A/B and X/Y inverted, but in regard to XInput, they are wired the same (i.e. Nintendo gamepad aren't wired differently, it's only the visual label that is swapped).

**Comment by evilkomododragon** [comment]
And why would somebody want to invert buttons like Nintendo does???
So if I buy an xbox controller, the names are not inverted?
