### ISSUE TITLE
installer for 3.8?

### ISSUE THREAD

**Issue by hellphreak** [MonoGame/MonoGame#7766]
Hi

In the past I used monogame 3.7 with an installer and now I just returned to monogame.
I see now the installer is gone in 3.8...

Why is that and what are the reasons for this?
I liked the option to be able to install templates for different visual studio versions as included in the installer.

How are things organised now in order to use vs2019 or vs2022 considering the template extensions?

I couldn't find anything about this :(

**Comment by Hedmun395** [comment]
Hi hellphreak. Glad to see you back! 

> In the past I used monogame 3.7 with an installer and now I just returned to monogame.
> I see now the installer is gone in 3.8...

In the past you mean 2 days ago when you filled this repository with annoying messages as evilkomododragon?
Or you mean 4 days ago when you filled this repository with annoying messages as lovely-unicorn?

Please consider getting help, really. And I don't mean MonoGame help.

**Comment by hellphreak** [comment]
Can you help me with my question?

I didn't use MG since 3.7 so please stop harassing me or I report you to github...

**Comment by mrhelmut** [comment]
Hello, github is not the place to ask questions. Please refer to the [documentation](https://docs.monogame.net/articles/getting_started/0_getting_started.html) or the [forums](https://community.monogame.net/).

**Comment by Hedmun395** [comment]
> Can you help me with my question?

Sure, use the forums as you've been told like 5 times already.

> I didn't use MG since 3.7 so please stop harassing me or I report you to github...

I didn't know you could report users to github, thanks for the tip! :)

**Comment by mrhelmut** [comment]
As a matter of fact, we do know every accounts of lonely-unicorn (as well as the people they've been emailing or trying to reach through discord), even the newly created (and style disguised) accounts. And at this point github knows them too, next time is likely to be an IP-ban of all their IPs.

**Comment by hellphreak** [comment]
You guys ban what you want, I already said I don't know what you are talking about...

**Comment by hellphreak** [comment]
ARE YOU GOING TO ANSWER MY QUESTION???

**Comment by rejurime** [comment]
You can read [Migrating from 3.7](https://docs.monogame.net/articles/migrate_37.html). This entry is in the link that @mrhelmut gave you.

**Comment by hellphreak** [comment]
ok sorry :)
