### ISSUE TITLE
Git submodule ThirdParty/NVorbis points to a private repo

### ISSUE THREAD

**Issue by johankson** [MonoGame/MonoGame#7774]
In the master branch,

the Git submodule NVorbis points to `https://github.com/MrHelmut/NVorbis.git` which seems to be a private repos. Perhaps change to the official `https://github.com/NVorbis/NVorbis.git` or make the private repo public if there are changes then are needed.

I've tried changing it locally and it works for me as far as I can tell but I haven't done any in-depth analysis since my project works as expected or in the case that this is already under the radar of the MonoGame team.

The submodule in the Develop branch also seems to point to the private repo.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- MacOS

#### What MonoGame platform are you using:
- DesktopGL

**Comment by BlueElectivire** [comment]
I opened it from the develop branch and it seems to point to NVorbis/NVorbis. It does give a 404 when you try to open it from the master branch, but I assume that that would just be fixed the next time develop is merged into master.

**Comment by johankson** [comment]
Sweet! I somehow missed that. Closing the issue myself then.

**Comment by avengerx** [comment]
Tag v3.8 has this issue :)
Thanks for logging this!
