### ISSUE TITLE
IsKeyDown keeps reading?

### ISSUE THREAD

**Issue by monogamegirl** [MonoGame/MonoGame#7778]
Hi

When I want to read IsKeyDown in the Update function, this function keeps reading the keyboard in a loop.
How can I read if a key has been pressed ONCE?

**Comment by mrhelmut** [comment]
Hi Jess/Lisa,

Github is not meant to ask for support or documentation questions about how to use MonoGame. Please ask this question [on the forums](https://community.monogame.net/).

Github is meant to report bugs or discuss future improvements. If you are not sure if your question is about a bug or how things should work, please ask on the forums _first_.

Support questions on github make our work harder and slower.
