### ISSUE TITLE
MGCB Editor Doesn't Find Importer/Process From Extension Project

### ISSUE THREAD

**Issue by AristurtleDev** [MonoGame/MonoGame#7802]
# The Issue
When creating a MonoGame Content Pipeline extension project, if additional classes are added to the project that are not the `[ContentImporter]`/`ContentImporter<T>` and `[ContentProcessor]`/`ContentProcessor<Tinput, TOutput>` then then MGCB Editor fails to locate the importer and processor.

## Recreating the Issue
The following are steps that can be taken to reproduce this issue.
1. Created a new solution file `dotnet new sln -n ContentPipelineIssue`
2. Created a new MonoGame Desktop GL project `dotnet new mgdesktopgl -n ContentPipelineIssue`
3. Create a new MonoGame Content Pipeline Extension project `dotnet new mgpipeline -n ContentPipelineExtension`
4. Added projects to the sln
    * `dotnet sln add ./ContentPipelineIssue/ContentPipelineIssue.csproj`
    * `dotnet sln add ./ContentPipelineExtension/ContentPipelineExtension.csproj`
5.  Add a dummy text file to **ContentPipelineIssue** directory `echo "" > ./ContentPipelineIssue/Content/dummy.txt`
6. Build projects `dotnet build`
7. Launch MGCB Editor `mgcb-editor`
8. Open the **ContentPipelineIssue/Content/Content.mgcb** file within the editor and add a reference to **ContentPipelineExtension/bin/Debug/netstandard2.0/ContentPipelineExtension.dll**
9. Choose to add an existing item and choose the **ContentPipelineIssue/Content/dummy.txt** file that was created.  When doing this, the correct Importer and Processor are choosen as **Importer1** and **Processor1**
10. Close the MGCB Editor, **do not save**.
11. Add a new class file to **ContentPipelineExtension** called **FakeClass.cs** and add the following code to the file

```cs
namespace ContentPipelineExtension
{
    public class FakeClass
    {
        
    }
}
```

12. Perform a clean and then a build. `dotnet clean && dotnet build`

13. Repeat steps 7, 8, and 9 to open the Content.mgcb file, add the dll reference, then add the dummy.txt file.  **Only this time, the Importer and Process are not found**

At this point, if you remove the **FakeClass.cs** and rebuild, the do the steps for the mgcb-editor, the Importer and Processor will show back up.  So it would appear that adding any class that is not directly the Importer and/or Processor to the extension project prevents it from loading properly in the mgcb-editor.  By Importer and Processor I mean class with the `[ContentImporter]` and `[ContentProcessor]` attributes and inheritences. 

# Example Project
I have created a repository containing an example project created that replicates the steps above.  It can be found at  https://github.com/AristurtleDev/content-pipeline-issue

# Video Explanation
This is 100% overkill but I also uploaded a video that steps through the issue.
https://www.youtube.com/watch?v=vfhjHSQlt0I

# System Stats

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- MacOS Mojave 10.14.6

#### What MonoGame platform are you using:
* DesktopGL (created with `dotnet new mgdesktopgl`)
* Content Pipeline Extension (created with `dotnet new mgpipeline`)

**Comment by AristurtleDev** [comment]
Was able to test this on my Windows desktop and this problem does not exist there.  Not sure if this is isolated to just Mac or not.

**Comment by AristurtleDev** [comment]
> Unless you have a specific reason to stay, I would suggest installing a newer framework version on your Mac. `netstandard2.0` was replaced by `netstandard2.1` the last version, and then superseded by `netcore3.1`, and now `net6.0`(yes, I skipped some versions.)
> 
> I could not say if the version is the cause, but it is worth mentioning. This could be a bug in the Mac implementation of Reflection in that version?
> 
> The simple workaround is to externalize the extra classes and structs. If the mirror assumption stands, then they will be needed for decoding anyway.
> 
> Please update this post, if any one of my suggestions helped, or not. I do not have a Mac to test this.

`netstandard2.0` is the recommended one to use to support all platforms for code libraries https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

I'm also the developer of the MonoGame.Aseprite library which is used by some who still use MonoGame 3.7 on .net4x.

The `mgpipeline` template also defaults on `netstandard2.0`, which is what was used in all testing scenarios posted above so I don't think it would be the cause, since it's very specifically from the dll built on MacOS then used specifically in thr MacOs mgcb-editor

**Comment by AristurtleDev** [comment]
> I could not say if the version is the cause, but it is worth mentioning. This could be a bug in the Mac implementation of Reflection in that version?

Wouldn't a reflection issue still cause the compiled dll on a windows OS that is then used in the Mac mgcb-editor to exhibit the same issue? 

> The simple workaround is to externalize the extra classes and structs. If the mirror assumption stands, then they will be needed for decoding anyway.

This just adds a layer of complexity that isn't needed. Ultimately I can just switch to my windows desktop to develop and test, but not everyone has that option. Having to add an addition project to reference that only supports decoding that is only used by the pipeline extension vs keeping all of it in one logical project

**Comment by stromkos** [comment]
> From your page: [No new versions of .NET Standard will be released](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/), but .NET 5, .NET 6, and all future versions will continue to support .NET Standard 2.1 and earlier.

Please note that at least 17 approved updates have occurred since its original publication.

.Net Standard is completely dead unless you created your own runtime; Mono, Xamerin have all moved on.

Problems from the same [page](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#net-standard-problems)

> Wouldn't a reflection issue still cause the compiled dll on a windows OS that is then used in the Mac mgcb-editor to exhibit the same issue?

No, each runtime and compiler implementation is platform specific. The MSIL code generated should be the same, but it is not at that version level. This was the primary reason for combining the code-bases starting in .Net5 (do not attempt to use), and completed in .Net6 (recommended).

>I'm also the developer of the MonoGame.Aseprite library which is used by some who still use MonoGame 3.7 on .net4x.

The MonoGame code is restricted to C# 5, meaning the code will build against .Net Framework 4.5 natively. Grab a 3.7 .sln file and project files (update for any added/removed files and build), and create a 3.8 .Net Framework 4.x dll.

**Comment by AristurtleDev** [comment]
Just did a build of the current 3.8.1.1-develop and the problem does not exist in the current develop version of the mgcb-editor for mac. This was using both `netstandard2.0` and `net6.0` for the pipeline extension build.  Since this seems resolved in the upcoming release, I'll self close the issue.

For now, I can just move the extension development to my Windows PC since the dll built there doesn't exhibit the issues between OSs.

Thanks for the information @stromkos and @mrhelmut. 

As a side note, I also tested the current mgcb-editor 3.8.0.1641 release with a pipeline extension build against `net6.0` and the problem still existed.

**Comment by stromkos** [comment]
>This just adds a layer of complexity that isn't needed. 

I agree, but there are very few people still using the unsupported .Net Standard (both Microsoft and MonoGame dropped support years ago).

So yes, "everyone has the option" to use supported versions, whether you choose it or not is your choice.

So without a confirmation via .Net6, I am forced to conclude that you are asking here for a correction to the Mac version of the .Net Standard 2.0 runtime. I would suggest contacting Microsoft on that point.

I have two final points:

  1. The only bad question is one not asked.
  2. My opinions are mine alone, and should not be construed to represent any entity.
