### ISSUE TITLE
[ContentBuilder] Allow users to configure external tools used (dotnet, ffmpeg, etc.)

### ISSUE THREAD

**Issue by Lancelotbronner** [MonoGame/MonoGame#7803]
## My Issue

I was trying to use `mgcb` (CLI) on my m1 Mac, on which we have to use a separate dotnet installation because there are no arm binaries for netcoreapp3.1, and I would get the following error:

```
/path/to/shaders/shader.fx: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' (arm64) was not found.
```

## The Cause

This was caused by the following line in `Monogame.Framework.Content.Pipeline/Processors/EffectProcessor.cs` (line 65):

```c#
var success = ExternalTool.Run("dotnet", arguments, out stdout, out stderr) == 0;
```

Which was calling the arm dotnet which indeed has no *netcoreapp3.1*.

It would have needed to use the alternate dotnet binary. I though it might be a good idea to have an easy way to allow users to configure the external tools that `mgcb` is using (shell, dotnet, ffprobe, ffmpeg).

## My Solution

I have two solutions but I wanted an opinion before opening a pull request.

I have added a new option to the tool: `--tools=TOOL:PATH`, this can be used as follows: `mgcb --tools=dotnet:/path/to/dotnet64`.

I made a `PipelineServices` class which would allow access to those configured paths, allowing us to do `ExternalTool.Run(services.Dotnet, /* arguments */)` but requires those services passed everywhere which is a pain. This would require modifications to the test projects as a couple of abstract classes saw their members receive that new `services` parameter. I have the beginning of a solution on [my fork](https://github.com/Lancelotbronner/MonoGame/tree/feature/configurable-external-tools-instance), it compiles `mgcb` and works but I haven't modified the test projects.

This much hassle has lead me to implement a simpler solution also on [my fork](https://github.com/Lancelotbronner/MonoGame/tree/feature/configurable-external-tool-global) which we can use like such: `ExternalTool.Run(ExternalTool.Dotnet, /* arguments */)`, it works and requires no further modifications.

I'd appreciate some feedback!

#### What version of MonoGame does the bug occur on:
- `mgcb` has no version option?

#### What operating system are you using:
- macOS

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
The real problem is related to all the native MGCB dependencies not having arm64 binaries. The solution would be to compile all the native dependencies with arm64+x64 support. This would solve this issue without the need to install different .NET SDK nor having to choose a tool.

This will be half-solved for 3.8.1. MGCB will work without issue providing that you have .NET 6 x64 installed (hence running through Rosetta).

Native arm64 support will be fixed for a later release.

**Comment by Lancelotbronner** [comment]
I do have dotnet x64 installed and I ran mgcb built from source (develop branch). Was it supposed to be fixed?

**Comment by mrhelmut** [comment]
There must be something off with your source or build, because there is no reason for ```develop``` to ask for dotnet core 3.1. Only dotnet 6 should be required and mgcb should run on net 6.

**Comment by Lancelotbronner** [comment]
Perfect! Then I just gotta figure what I did wrong. Thanks a lot!
