### ISSUE TITLE
Game crashes on second launch when loading content

### ISSUE THREAD

**Issue by PetrVobornik** [MonoGame/MonoGame#7816]
When I launch the Monogame game in the Xamarin application from the XAML menu, everything works correctly. Then I exit the game (game.Content.Unload(); Content.Dispose(); game.Exit();) and return to the XAML menu. But when I want to start the game again from it (new Game()) without resetting the whole application, everything gets stuck while loading the content. 
In the Android Xamarin app, I get a NullReferenceException when I try to load the SoundEffect. When I skip these loadings of sounds, game works fine (without sound).
In the UWP Xamarin app, the sounds load fine, but I end up trying to load Texture2D.
Yet on both platforms, the first launch of the game and loading all the content went fine. Resetting the whole app to restart the game is not very user friendly though. 

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- Windows 10 (UWP) and Android 8.1 and 12

#### What MonoGame platform are you using:

- DesktopGL, WindwosUniversal, Android, Content.Builder.Task

**Comment by mrhelmut** [comment]
Could you share more context in regard to why you need to kill and restart instances of ```Game```? Monogame isn't designed for this and the mobile/UWP use cases intended aren't either. Just trying to check if it's just a misuse or something out of scope.

**Comment by PetrVobornik** [comment]
I'm trying to combine the power of Xamairn (Forms) and Monogame. Xamarin will provide the start menu, game setup form, campaign level overview, score table, tutorial and project information, etc. The app/game also includes the map editor and configurator, which is much easier and more efficient to create in Xamarin.Forms than in Monogame. To debug a map, it's a good idea to run the game with the map, test it, and then go right back to editing and tweaking it. These maps could then be shared between users (which could also have server support) and for their individual versions, users could compete for higher scores.
But ToDe (Tower Defense) is mainly an educational project, its development is streamed as a "let's program" (in Czech language) and open to all interested parties ([GitHub](https://github.com/PetrVobornik/ToDe), [YouTube](https://www.youtube.com/playlist?list=PLxTqV9i8bnb_BN9k_-W_CjXfumNzqiPEe), Twitch, Discord...). 
It's a great pity when Monogame fails like this with only a few minor bugs that could certainly be easily (maybe) solved, such as reloading content, or the ability to reuse already loaded content in a new game. Being able to link the game part to a classic multiplatform application (everything in C#) would expand its use many times over.
Currently, for linking Monogame with Xamarin.Forms in UWP works better, when I use a custom PageRenderer that embeds SwapChainPanel and XamlGame into the page. 
For Android, on the other hand, it's better to pass control to a native Android part (project) that starts a new activity (AndroidGameActivity) and returns to the MainActivity and exits the game (Exit) when the back button is pressed. 
It might also be a solution to just put the game to sleep, keep an instance of it in the background, and come back to it again. But in Android this is hardwired to an activity that must be terminated (Finish) to switch back to Xamarin.Forms, and in UWP its XamlGame instance is linked to a SwapChainPanel on a specific page.
Anyway, incorrectly releasing the loaded content or reloading it seems to be a bug.

**Comment by mrhelmut** [comment]
This really is very specific and not the intended use of MonoGame. I am not sure if we should support/encourage to instantiate a Game object per GUI view. The intended lifecycle of the Game object is that it remains alive for the whole duration of the app and once it's disposed, the app is closed. It is not meant to recover after a ```Dispose()``` or ```Exit()``` (which calls ```Dispose()```), and is intended that you render your own GUI within it.

I would recommend to keep the Game object living and just loading/unloading your game content when it gets displayed without disposing or killing the Game object.
Alternatively, I would look into having a permanent view with the Game displayed and Xamarin.Forms/UWP controls on top that you show/hide.

**Comment by PetrVobornik** [comment]
Thank you. Keeping the game object alive is the second option to handle such an application. In that case, however, support for temporarily suspending it would be useful, i.e. completely disabling the Update and Draw calls, perhaps stopping the internal timer. For example, via Suspend/UnSuspend methods. 
This would probably be possible to use in UWP, where you are just switching pages. In an Android app it's more complicated, because Xamarin.Forms needs to run its own main activity (FormsAppCompatActivity), and Monogame does too (inherited from AndroidGameActivity). And the only way to return from the Monogame activity to the main XF activity is to terminate the MG activity (Finish). I don't know how it is on iOS.
A solution could be, for example, a special type of page for Xamarin.Forms, which would take control and run the Monogame game when switched to it (either automatically in OnAppearing or via Run/UnSuspend method), but suspend the game after leaving that page (automatically in OnDisappearing or via Suspend method). In Xamarin.Forms you can store page objects, put them in the navigation stack or switch between them well, so it could work great this way. Only on Android would the activity model have to be tweaked a bit.
However, Xamarin.Forms is already a thing of the past, it would be better to focus straight on support in .NET MAUI. So we would wait with these considerations for the completion of a version supporting .NET 6 (3.8.1?), and then try to design some currently solution (like the new NuGet, e.g. Monogame.MAUI) directly for MAUI.

**Comment by mrhelmut** [comment]
Closing this issue for the time being since it relates to an intended use case. Feel free to comment, we will re-evaluate the demand if need be.

**Comment by damian-666** [comment]
You might get an idea from the monogame.wpf core project... https://github.com/craftworkgames/MonoGame.WpfCore   someone submitted a.PR  unmerged, that release improves the monogame view model and .that supports two windows .. I aslo submit a net6 sample..  
   This method goesnt use a game class, and his PR it fixed my issue...I don't use game components or call update..I just call draw using a shared device texture from the device service.   It's how that view model is designed..there is also demand for a way that works without sharp dx bit it's would be thr same idea...it's highly valuable so I can leverage framework like wpf that has a rich ui for level and shapes edit..not have to make a crappy ingame editor with all my own ui...  Our PRs isn't merge but if u can get a  way to get a shared texture from sdl. Or make itworking in a gl exe....look at Monogame graphics device serivce.   They was big demand for something works on avalonia...I'm just targeting windows...it's.basivally the swap chain,shared.back buffer..redner target idea but without tjr direct3d device and instead using SDL...the old sharrpdx and interop is like2 years abandoned so I'm lucky mine works again.   I did too try.maui but I couldn't get far with it.. a general device service sample with tabbed windows support and client count would  would be greatly valuable to the community
