### ISSUE TITLE
DynamicSoundEffectInstance PlatformStop not working correctly.

### ISSUE THREAD

**Issue by CidVonHighwind** [MonoGame/MonoGame#7819]
I found a problem with the DynamicSoundEffectInstance on WindowsDX. Is is really specific and I only found out because sometimes my audio breaks on my game boy sound system player after changing the track.

**Cause of the problem (DynamicSoundEffectInstance.XAudio.cs):**
We have the _queuedBuffers variable containing the buffers that are being played by _voice (SourceVoice).
When we add a buffer it will be added to _queuedBuffers and to _voice. Whenever _voice finished playing a buffer the OnBufferEnd function is called. This will remove the buffer from _queuedBuffers while _voice will itself removes the buffer internally.
So when OnBufferEnd is called the buffer that just finished playing will be removed from _queuedBuffers.

If PlatformStop is called for DynamicSoundEffectInstance there are three things happening:
1. _voice.Stop() is called
2. _voice.FlushSourceBuffers() is called
3. _queuedBuffers is cleared

The problem is that FlushSourceBuffers does not directly remove all buffers in _voice but the _queuedBuffers will always be cleared.
So after calling PlatformStop and directly PlatformSubmitBuffer after that it is possible for _voice to contain more buffers than _queuedBuffers. If this is the case OnBufferEnd will "free" buffers that are currently played. Now when the buffers get filled with new data while at the same time being played the audio breaks.

**Solution:**
In PlatformStop we do not need to clear _queuedBuffers because for every buffer in _voice the OnBufferEnd function will get called (["For every buffer removed, an OnBufferEnd callback will be made, but none of the other per-buffer callbacks (OnBufferStart, OnStreamEnd or OnLoopEnd) will be made."](https://docs.microsoft.com/en-us/windows/win32/api/xaudio2/nf-xaudio2-ixaudio2sourcevoice-flushsourcebuffers)). So _queuedBuffers will get cleared at the same time as _voice. So we never run into the situation where _voice contains more buffers than _queuedBuffers.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- WindowsDX

**Comment by mrhelmut** [comment]
Can you confirm that this is in regard to WindowsDX, and not DesktopGL? (or vice versa)
Because you're mentioning DesktopGL twice, but the file and implementation you're pointing to are the XAudio WindowsDX implementation, not DesktopGL (and this will have no effect on DesktopGL).

**Comment by CidVonHighwind** [comment]
Yes sorry I meant WindowsDX. I just updated the text.
