### ISSUE TITLE
UWP and VSync bugs

### ISSUE THREAD

**Issue by vrgamestudio** [MonoGame/MonoGame#7821]
Hi guys,

I've run into this issue with VSync and Monogame UWP in that it basically has several big problems.

I've written about this previously on the forums but have no replies so here I am again.
https://community.monogame.net/t/presentationinterval-presentationinterval-two-in-uwp/17622
https://community.monogame.net/t/problems-with-vsync-in-uwp/17574

First of all, this code results in a presentation interval of One instead of the expected Two:

```
...
graphics.PreparingDeviceSettings += Graphics_PreparingDeviceSettings;
...
private void Graphics_PreparingDeviceSettings(object sender, PreparingDeviceSettingsEventArgs e)
{
    // This will not be applied correctly in UWP, Only interval One, not Two.
    e.GraphicsDeviceInformation.PresentationParameters.PresentationInterval = PresentInterval.Two;
}
```

Second of all, in Monogame 3.7, in the Game constructor, setting graphics.SynchronizeWithVerticalRetrace = false used to cause an exception to be thrown from SharpDX, such as this:

```
// Exception thrown: 'SharpDX.SharpDXException' in SharpDX.dll
// Exception thrown: 'Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException' in MonoGame.Framework.dll
this.IsFixedTimeStep = false;
graphics.SynchronizeWithVerticalRetrace = false;
```
No problem though as that is fixed in Monogame 3.8, thank you. 

However...in 3.8 a SharpDX exception is now thrown if this value is ever changed at runtime:

So lets say in constructor it is like this (true or false it doesn't matter):

`graphics.SynchronizeWithVerticalRetrace = false;`

Then in Update we have something like this:

```
protected override void Update(GameTime gameTime)
{
    KeyboardState keyState = Keyboard.GetState();
    if (_lastKeyState.IsKeyUp(Keys.Space) && keyState.IsKeyDown(Keys.Space))
    {
        Debug.WriteLine("Space pressed");
        graphics.SynchronizeWithVerticalRetrace = !graphics.SynchronizeWithVerticalRetrace;
        graphics.ApplyChanges();
    }
            
    base.Update(gameTime);

    _lastKeyState = keyState;
}
```
We again get the dreaded SharpDX exception and game crash, like this:

```
Space pressed
Preparing Device SettingsException thrown: 'SharpDX.SharpDXException' in SharpDX.dll
The program '[20884] MG38Test.exe' has exited with code 1 (0x1).
```

I hope this is all clear enough but don't hesitate to ask if you need any further information.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7, 3.8

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsUWP

**Comment by squarebananas** [comment]
With issue 1 it seems within the GraphicsDevice.DirectX PlatformPresent code the swapChain.Present syncInterval argument is set to 1 instead of using the PresentationInterval value.

If you're building from source see if changing this line (https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Graphics/GraphicsDevice.DirectX.cs#L1052) from
`_swapChain.Present(1, PresentFlags.None);`
to
`_swapChain.Present(Math.Max(1, PresentationParameters.PresentationInterval.GetSyncInterval()), PresentFlags.None);`
fixes your issue.

With issue 2 I can change VSync at runtime without issue. Have you applied PR #7463 as it may have been broken before that fix.

**Comment by mrhelmut** [comment]
As far as I can tell, the Vsync code of the UWP implementation was done back in the days when UWP didn't have support for explicit VSync support. So there's likely improvements to be made. It might even be possible that the standard Windows code path just works on UWP by now.

**Comment by vrgamestudio** [comment]
Thank you both for the responses. 

I'm not building from source but was pulling in the latest Monogame.Framework.Universal Nuget package from here:

http://teamcity.monogame.net/guestAuth/app/nuget/feed/_Root/default/v3/index.json

which gave me version 3.8.0.1641. I don't know if that includes PR #7463 ? 

From what @squarebananas has said, the example code fix looks very much like it would at least fix the VSync Two problem. Perhaps PR #7463 will fix the VSync change issue. I'll attempt to build from source and try it out, no promises I'll be able to do it though as I'm not experienced with this.

While I'm here:
A) You don't know a way to get the current screen refresh rate in UWP do you?
B) Can I suggest a PresentInterval.Three and PresentInterval.Four also?

**Comment by vrgamestudio** [comment]
No sorry I wasn't able to build from source AND test in an app. 

I mean could build the Monogame.Framework.WindowsUniversal solution after adding a couple extra Nuget packages "StbImageSharp" and "StbImageWriteSharp" but it would either not build or error / crash when I tried to reference the built Monogame.Framework.dll and run a test UWP program.

Perhaps there is a tutorial that would walk me through the process?

**Comment by mrhelmut** [comment]
You didn't pulled the git submodules. No other dependency should be needed to build MonoGame.

Even though the teamcity nugets are outdated, the one you referenced to does include #7463

**Comment by vrgamestudio** [comment]
> You didn't pulled the git submodules. No other dependency should be needed to build MonoGame.

I downloaded the zip file containing the project, extracted it and then opened MonoGame.Framework.WindowsUniversal.sln and proceeded to try to get that to build a dll for Release and Debug (into the "Artifacts" folder). Like I say, I'm sorry to be so thick but maybe a tutorial to explain it to me like I'm a 5 year old would be useful.

> Even though the teamcity nugets are outdated, the one you referenced to does include #7463

In that case then perhaps there is still a bug in there somewhere as this is my output from the test I gave above using the Nuget package version 3.8.0.1641 from that teamcity source:

```
Space pressed
Preparing Device SettingsException thrown: 'SharpDX.SharpDXException' in SharpDX.dll
The program '[20048] MG38Test.exe' has exited with code 1 (0x1).
```
It's every single time and it doesn't matter if graphics.HardwareModeSwitch is true or false.

**Comment by squarebananas** [comment]
The commands to run to clone the source and update the submodules are shown on the readme file viewed at https://github.com/MonoGame/MonoGame

I personally use GitHub Desktop and use the Clone Repository option through that as it does these steps automatically.

**Comment by vrgamestudio** [comment]
> The commands to run to clone the source and update the submodules are shown on the readme file viewed at https://github.com/MonoGame/MonoGame
> 
> I personally use GitHub Desktop and use the Clone Repository option through that as it does these steps automatically.
> 
> Also I add the MonoGame project to my solution and then add a project reference directly so that I can step through / add breakpoints to the MonoGame code as well as see where exactly exceptions occur.

That looks useful thank you I'll give it a go.

**Comment by vrgamestudio** [comment]
So I've run the test for issue 2 (Change VSync at runtime) and can confirm it now works as expected!

This is great but I wonder why this wasn't working with the Nuget package from teamcity. A theory I have is maybe because my project had a lower min version for UAP, I simply wasn't offered the more up to date Nuget package that actually contained PR #7463 ?

**Comment by vrgamestudio** [comment]
Ok fantastic it seems that @squarebananas suggestion does indeed work perfectly, thank you so much! 

I put this at Line 1052:

```
int interval = Math.Max(1, PresentationParameters.PresentationInterval.GetSyncInterval());
_swapChain.Present(interval, PresentFlags.None);
```

and it solves the issue.

Just an extra thought though, I found both these worked too and gave expected results:

`_swapChain.Present(3, PresentFlags.None);`

Gives 40Hz VSynced on my 120Hz laptop, as desired.

`_swapChain.Present(4, PresentFlags.None);`

Gives 30Hz VSynced on my 120Hz laptop, as desired.

 So three questions:

1) Can I/how do I add this back to the source code, maybe solving/closing this issue thread? Remember I'm "5 years old" and never done this before.

2) What about if we could add Three and Four as PresentationIntervals (amending the GetSyncInterval extension method to return 3 or 4 in those cases?

3) Can we get and expose the current Screen Refresh Rate (like Xna used to prior to V4.0) to enable games to be able to set these things as reasonable default values, aiding maximum smoothness and performance out of the box?

**Comment by squarebananas** [comment]
> 1. Can I/how do I add this back to the source code, maybe solving/closing this issue thread? Remember I'm "5 years old" and never done this before.

There is a contributing document in the same folder as the readme file. The document contains links to "how to create a fork" and "how to submit a pull request" which may be a good place to start.
https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md

Originally I was going to submit a PR for that one line if it worked for you but I'll let you try if you like. Generally I've only been submitting PRs for bug fixes so someone else will have to answer your other questions regarding feature requests.

**Comment by vrgamestudio** [comment]
> There is a contributing document in the same folder as the readme file. The document contains links to "how to create a fork" and "how to submit a pull request" which may be a good place to start. https://github.com/MonoGame/MonoGame/blob/develop/CONTRIBUTING.md
> 
> Originally I was going to submit a PR for that one line if it worked for you but I'll let you try if you like. Generally I've only been submitting PRs for bug fixes so someone else will have to answer your other questions regarding feature requests.

Once again that's very helpful thank you and also kind of you to allow me to try it for myself so thank you again. 

I'll have a go with the document and the process and see how I get on.

**Comment by vrgamestudio** [comment]
Oh my goodness, what a pain that was made all the worse because I don't want to mess anything up for anyone so I'm literally scared to press anything or do anything! 

Not being funny though, although the MonoGame documentation for "cloning the code" was OK (not quite perfect), the documentation for submitting code back was more or less non existent, beyond "Know how to use Git" so basically RTFM.

> The MonoGame project follows standard [GitHub flow](https://guides.github.com/introduction/flow/index.html). You should learn and be familiar with how to [use Git](https://help.github.com/articles/set-up-git/), how to [create a fork of MonoGame](https://help.github.com/articles/fork-a-repo/), and how to [submit a Pull Request](https://help.github.com/articles/using-pull-requests/).
> 
> After you submit a PR, the [MonoGame build server](http://teamcity.monogame.net/?guest=1) will build your changes and verify that all tests pass. Project maintainers and contributors will review your changes and provide constructive feedback to improve your submission.
> 
> Once we are satisfied that your changes are good for MonoGame, we will merge your PR.

Really I needed a first timer, idiot's guide. I tried my best to piece it together. From the information that is there, it's all over the place, assuming you know stuff, some are using web, some desktop, some command line etc (none used visual studio though).

We have command line Git, Git bash (WTH?) Desktop Git, Web Git, Git via Visual Studio and so on and so forth.

I just wanted a simple guide for a simple thing and preferably all using the same f@*king tool if possible. I ended up using the web, CLI, Visual Studio and finally web again! What an ugly mess that felt like.

After creating a fork (via the web interface), cloning to my desktop (via the CLI), updating the submodules (CLI again) and making my changes (Visual Studio) & checking them I was honestly about ready to give up pushing it all back!

Eventually I decided to just try to wing it, I used Visual Studio to Commit the code (there was a nicely labelled BUTTON for that, thanks Visual Studio!) back to my repository and from there just clicked on whatever looked good back on on the Web interface again to do the thing that seemed to need doing (request that the code from my forked repository be merged back into the MonoGame repository my fork came from via this Pull Request PR thing). 

It was all over the place and surely shouldn't be this difficult or messy!

What I really wanted, as a newbie was a coherent guide from start to finish using, say, only one interface if possible and not merely the catch all, "RTFM".

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
