### ISSUE TITLE
Game.Activity should use Android.App.Activity instead of AndroidGameActivity

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#7831]
On Android, class Game has an Activity property which exposes an AndroidGameActivity.

The problem is that this is severely limiting the Activity types we can use in an android project.

An example of this problem is #7191

In my case, I need to use the new AndroidX.AppCompatActivity

Solution: Game.Activity should be more flexible and simply accept Android.App.Activity

For AndroidGameActivity features, it could be possible to create an interface IAndroidGameActivity,
implemented by all monogame based Activities

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0

#### What operating system are you using:
- Android

**Comment by CartBlanche** [comment]
@vpenades As you closed your PR, I'm going to assume you may no longer require this functionality.

**Comment by vpenades** [comment]
> @vpenades As you closed your PR, I'm going to assume you may no longer require this functionality.

Indeed, we needed a solution that supported the new AndroidX lifecycle, we ultimately found an alternate solution and went with it.
