### ISSUE TITLE
Suggestion: Showcase of engines and/or utilities made with MonoGame

### ISSUE THREAD

**Issue by eosxf** [MonoGame/MonoGame#7836]
For most non-trivial projects, the features offered by MonoGame alone are insufficient. Some developers may feel like an engine like Unity is too much, but a framework like MG is too little, albeit still interested in what MG has to offer. I think it would be beneficial to add a showcase of sorts for engines/utilities on the MG website. Some that come to mind are:

https://github.com/prime31/Nez - Engine

https://github.com/Martenfur/Monofoxe - Engine

https://github.com/RonenNess/GeonBit.UI - UI Framework

Though if we do go along with this, we should respect the authors by getting permission first.

**Comment by Apostolique** [comment]
It sounds like you're looking for this: https://github.com/aloisdeniel/awesome-monogame

**Comment by eosxf** [comment]
Something like that is mostly what I'm looking for. I still think it would be very beneficial to add a more up-to-date list directly on the MG website though.
