### ISSUE TITLE
List PS5 Support on MonoGame.net

### ISSUE THREAD

**Issue by eosxf** [MonoGame/MonoGame#7839]
Someone on the forums asked about the progress on PS5 support which I later found out isn't listed as a supported platform [on the website docs](https://docs.monogame.net/articles/platforms/0_platforms.html)

**Comment by mrhelmut** [comment]
Already fixed in [develop](https://github.com/MonoGame/MonoGame/blob/develop/Documentation/articles/platforms.md), it will be updated with the 3.8.1 release.
