### ISSUE TITLE
mgcb-editor crashes upon launch

### ISSUE THREAD

**Issue by Ninjastorm380** [MonoGame/MonoGame#7840]
when attempting to launch the MonoGame content editor, it immediately crashes with an error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)
```
![Screenshot from 2022-07-17 17-29-25](https://user-images.githubusercontent.com/40574927/179425452-3d3c7191-6599-46cc-a878-d13380721df7.png)
#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- EndeavourOS (ArchLinux Rolling)

#### What MonoGame platform are you using:
- DesktopGL

**Comment by mukhinid** [comment]
Duplicate #7689 #7491 
Known issue on all Arch-based distros, fixed in current develop branch. As long as the fix is not published, you can build mgcb-editor from source.

**Comment by mrhelmut** [comment]
I'll be closing it for now. Feel free to re-open the issue if when 3.8.1 is available it still happens.

**Comment by Ninjastorm380** [comment]
thanks!
