### ISSUE TITLE
Remove global usings from 3.8.1 nuget packages.

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#7848]
I've just tested the new 3.8.1 nugets, and I've found they have in built global usings for all monogame namespaces.

```csproj
<Project>

  <PropertyGroup>
    <MonoGamePlatform>DesktopGL</MonoGamePlatform>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Microsoft.Xna.Framework.Audio" />
    <Using Include="Microsoft.Xna.Framework" />
    <Using Include="Microsoft.Xna.Framework.Content" />
    <Using Include="Microsoft.Xna.Framework.Graphics" />
    <Using Include="Microsoft.Xna.Framework.Media" />
    <Using Include="Microsoft.Xna.Framework.Input" />
    <Using Include="Microsoft.Xna.Framework.Input.Touch" />
    <Using Include="MonoGame.Framework.Utilities" />
  </ItemGroup>

</Project>

```

This might look like a great idea for beginners and simple projects, but for already existing, or complex projects that might require using multiple third party libraries, it prevents managing namespaces correctly.

Consider this use case: A project using MonoGame AND BepuPhysics, which uses System.Numeric.Vectors by default.

Since Monogame has Vector3 type, and System.Numerics also has Vector3 type, And Monogame is aplying a "global using" on their types project wide. It forces a developer to type System.Numerics.Vector3 with the full name to prevent a collision with monogame's Vector3.

In any case, developers must be able to decide whether to use global usings or not, and by forcing these global usings into the developers, it makes much more difficult to resolve complex type collision scenarios.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
It might be best to remove those implicit usings. If anyone wishes to contribute, it is likely a good first contribution.

In the mean time, if anyone runs into type collisions due to this, I'd suggest disabling implicit usings by adding this to your project csproj: ```<ImplicitUsings>disable</ImplicitUsings>```

**Comment by vpenades** [comment]
I can give a try with a PR
