### ISSUE TITLE
Add MGCB .config/dotnet-tool.json to migration guide from 3.8.0 to the documentation

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7851]
The [documentation to migrate to 3.8.1](https://docs.monogame.net/articles/migrate_38.html) is missing information on how the MGCB is now accessed.

The **MGCB Editor is no more designed as a .NET global tool** (and doesn't need to be registered). It is now a project tool defined project templates (please make sure that you have a ```.config/dotnet-tools.json``` properly configured) which will be installed automatically. You can access it either via the CLI (```dotnet mgcb-editor``` from within the project/solution folder) or by double-clicking a .mgcb file when the [Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=MonoGame.MonoGame-Templates-VSExtension) is installed (the mac extension need to be installed from downloading the mpack [here](https://github.com/MonoGame/MonoGame/releases/tag/v3.8.1)).

```.config/dotnet-tools.json``` should be placed in the project folder, and look like so:

```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-mgcb": {
      "version": "3.8.1.*",
      "commands": [
        "mgcb"
      ]
    },
    "dotnet-mgcb-editor": {
      "version": "3.8.1.*",
      "commands": [
        "mgcb-editor"
      ]
    },
    "dotnet-mgcb-editor-linux": {
      "version": "3.8.1.*",
      "commands": [
        "mgcb-editor-linux"
      ]
    },
    "dotnet-mgcb-editor-windows": {
      "version": "3.8.1.*",
      "commands": [
        "mgcb-editor-windows"
      ]
    },
    "dotnet-mgcb-editor-mac": {
      "version": "3.8.1.*",
      "commands": [
        "mgcb-editor-mac"
      ]
    }
  }
}
```

The package reference should also have the minor version wildcard:

```xml
<PackageReference Include="MonoGame.Framework.{Platform}" Version="3.8.1.*" />
<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.*" />
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by damian-666** [comment]
copying this to my netstandard project did work but i cant resolve any monogame references in a netstandard 2.0 dll.    its this no longer supported?

I had to do this manually for a project that has all the monogame code in a NetStandard core.. I dont see any better way to share my code and target android and desktops with shared code.   this fixes the issues with the content builder for the core   ive spend hours and i cant the XNA references to resolve in the netstandard project.   Sure i can build one platform but not with monogame code in a netstandard 2.0 dll..  has this been tested w 3.8.1 ?   the samples setup i have beenn sharing and using   2 years old.     https://github.com/MonoGame/MonoGame.Samples

I had to do this manually for a project that has all the monogame code in a NetStandard core.. I dont see any better way to share my code and target android and desktops with shared code.   this fixes the issues with the content ( but i dont need to build content in the core thats just where i put it )    ive spend hours and i cant the XNA references to resolve for mayh game core.. its the same as the

**Comment by seclerp** [comment]
Do you folks maybe have some background regarding this change? And I'm also wondering if this breaking change was done in a patch 3.8.1 release and not somewhere in 3.9.

Yes, it doesn't break anything from a framework usage point of view but affects tooling.
