### ISSUE TITLE
WindowsDX Could not load file or assembly 'System.Windows.Forms'

### ISSUE THREAD

**Issue by Apostolique** [MonoGame/MonoGame#7866]
Started from a new project:

```
dotnet new --install MonoGame.Templates.CSharp
dotnet new mgwindowsdx -o MyGameDX
cd MyGameDX
```

Change output type from WinExe to Exe in MyGameDX.csproj to get the error output in the console.

```
dotnet run
```

I get the following error:

> Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at MonoGame.Framework.WinFormsGamePlatform..ctor(Game game)
   at Microsoft.Xna.Framework.Game..ctor()
   at MyGameDX.Game1..ctor() in F:\MyGameDX\Game1.cs:line 12
   at Program.\<Main>$(String[] args) in F:\MyGameDX\Program.cs:line 2

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by mrhelmut** [comment]
Make sure that you're running on .NET 6 ```dotnet --version``` and that you don't have a previous .NET installation that is still active on the CLI.

**Comment by Apostolique** [comment]
I had .NET 6.0.100 installed which failed. Redownload the SDK and with .NET 6.0.302 the issue is resolved.
