### ISSUE TITLE
Migration missing uninstallation

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7869]
The migration guide should recommend to uninstall 3.8.0 global tools, otherwise users will run in MGCB version mismatch when using 3.8.1.

It might also be worth mentioning this in the "what's new" doc.

If you're migrating from 3.8.0, please run:
```
dotnet tool uninstall dotnet-mgcb -g
dotnet tool uninstall dotnet-2mgfx -g
dotnet tool uninstall dotnet-mgcb-editor -g
```

And never run ```dotnet tool install``` on 3.8.1, it would break 3.8.1.

**Comment by rocketpowergirl** [comment]
Is it also possible to make docs on how to upgrade an existing 3.8.1.X project to 3.8.1.Y project? (where X and Y are subversions of 3.8.1)

As I understand, it's not enough to update the nuget packages but we need to update the extension and recreate the project and then copy all source code files into this new project?

**Comment by JakeLegendXIII** [comment]
I have created PR [#3](https://github.com/MonoGame/docs.monogame.github.io/pull/3) over on the docs.monogame.github.io repo to update these documents.

**Comment by SimonDarksideJ** [comment]
REsolved by https://github.com/MonoGame/docs.monogame.github.io/pull/3
