### ISSUE TITLE
request: primitives drawing

### ISSUE THREAD

**Issue by rocketpowergirl** [MonoGame/MonoGame#7874]
Hi

I woumd like to request functions for drawing a line, circle and rectangle with parameters color, line thickness.
It's seems not possible ?

**Comment by bjornenalfa** [comment]
This is not built into MonoGame but you can find such functionality in libraries like https://github.com/Apostolique/Apos.Shapes or https://github.com/craftworkgames/MonoGame.Extended

**Comment by rocketpowergirl** [comment]
What is the logic behind the decision not to include primitives in monogame?
This is something essential I think and for gamedev you can use it everywhere.

**Comment by Kekwleon** [comment]
My guess would be, its Monogames "bare bones" approach, and leave it to the dev to implement.
There are plenty of libraries, to choose from , take what you like/need. 
Or just do it yourself.

Yes even as simple as primitives, are not "essential", its up to you where to draw the line.(And how)

**Comment by rocketpowergirl** [comment]
I don't really understand. What's the most elementary primitive being able to draw by MonoGame which needs to be used for drawing other primitives?
Is it 1 pixel?

**Comment by bjornenalfa** [comment]
The basic primitive is a triangle, with it you can draw all other things. You have full access to upload triangles to the GPU and draw them with whatever shader you want. It is a bit of work and requires learning how a 3D pipeline works. If you just want to draw 2D shapes on the screen, go with one of the libraries I linked above.

**Comment by eosxff** [comment]
This is delving into more lower level graphics programming, but it's triangles for (what I know to be) two reasons:

1. a triangle is always guaranteed to have a flat surface (plane). this may seem small, but it actually allows dedicated hardware to do a lot of optimisations, for reasons that I can't seem to recall right now
2. all other primitives can be represented as a series of triangles, but not the other way around

Therefore, driver vendors always guarantee that triangle primitives are supported, and what MonoGame chooses to support

**Comment by rocketpowergirl** [comment]
it's PATHETIC a framework using opengl or directx which can draw primitives DIRECTLY does not support it.
So you tell me I need a fucking shader and triangles to draw a line?

Here is opengl code to draw a line

glBegin(GL_LINES);
    glVertex2f(10, 10);
    glVertex2f(20, 20);
glEnd();

You make things HARDER, not EASIER

FUCKING RETARDS

**Comment by Beyley** [comment]
> it's PATHETIC a framework using opengl or directx which can draw primitives DIRECTLY does not support it. So you tell me I need a fucking shader and triangles to draw a line?
> 
> Here is opengl code to draw a line
> 
> glBegin(GL_LINES); glVertex2f(10, 10); glVertex2f(20, 20); glEnd();
> 
> You make things HARDER, not EASIER
> 
> FUCKING RETARDS

Actually that opengl draw code will not work on OpenGL 3.2+ without a compatibility context, and will not support arbitrary line widths of any size, as most drivers cap out at widths of 5-10, may i suggest using a rotated quad or a geometry shader to draw lines?
