### ISSUE TITLE
Can't use a NetStandard 2.0  dll as a core wth 3.81 after quite a few hours..

### ISSUE THREAD

**Issue by damian-666** [MonoGame/MonoGame#7875]
Is this now anymore a supported way to share code.. I use a touch PC and put all my game code in a netstandard2.0 DLL, like Nez does and I thought most people did.

it has android and it has netcore windows and netcore desktopGL..

i dont see a cleaner way to this without any special maintenance.  it worked beautifullwith whith netcore 6 before.  i already unstilled net 3.1 

i got the technicque from ths.. sure individual templates work buts i use a touch pc to develop android and desktop..    

https://github.com/MonoGame/MonoGame.Samples/issues/59

**Comment by Beyley** [comment]
.net standard 2.0 is not listed as supported in the [project files](https://github.com/MonoGame/MonoGame/blob/574fd7f870a90d4c85ea6776acda359b08874d2a/MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj#L4)
The solution is to use a .net 6 library instead

**Comment by rocketpowergirl** [comment]
According to Microsoft's website, .NET 6.0 supports ANY .NET Standard version...

https://dotnet.microsoft.com/en-us/platform/dotnet-standard

**Comment by damian-666** [comment]
welll im getting through it..  looks like net core 6 libs maybe is the new netstandard...  https://www.techtarget.com/searchapparchitecture/tip/Will-NET-6-features-bridge-the-gap-between-NET-frameworks.   


but to update a multiplatfrom project targeting mobile and desktop, 
you can't just added the extensioins, update the nugets, remove old net 5 , netcore 3.1,  and go.   i created new net6 game lib dlls as advised, to replace the netstandard,  compare the projects,  cleanout old MSFT junk ... then just tweak the new ones beasue they are so much cleaner.       then  as I have put all the game code in one GameCore like DLL, a bit  like Nez, and the content in there and "add as Link" just the content.mgcb file to each exe.    im usng vs 2022 latest preview and has a great  new settngs and feature search and ts stable.


Triming has and would be an issue if anything uses reflection to load plugins its will be trimmed out on droid, so the shutting off idea is best.

 i did need to copy   .config folders, [MonoGame/MonoGame] Add MGCB .config/dotnet-tool.json to migration guide from 3.8.0 to the documentation (Issue #7851)


i still see some xamarin stuff.. i still thnk its slow to build and archive.. but i can debug via usb and on the emulation and its MUCH better.  byut MSFT has a bit more to do with this.  


 ill update my sample and maybe the other ones if i got time.   they work, android and desktop on one solution one linked mgcb file with , shaders building, render targets .    havent tried dx yet..  content builds..   the globals usings are fine.    
 
 my scary issue is im using a custom wpf  level edtior with a mono game window in the canvas render buffer.. based on the https://github.com/craftworkgames/MonoGame.WpfCore  one  , then  tried Microsofts command line wpf :  net 48 to net 6 converter and it got through 99% compabilble.   i was getting a SDL issue getting the window handle tho.  so that isnt Net6 wpf yet but lll try to figure it out.  those havent been maintained in a while.     BUT.. supposedly, a net 4.8 wpf app will run with netcore 6 libs, if i cant go all the way with this to net 6 on wpf,  i should be ok using net6 instead of netstandard... along with net4,8...

its actaully much easier now , worth it i think it may full day those to do this update but u end up with less junk ..

**Comment by damian-666** [comment]
and im editing manually the project file, doing 	the suggestion for the Wildcard * on the minor version as i dont know how hotfixes are going in via nuget or what , but they seem like ones that might prevent people spending hours cluelessly hacking ..   

 <ItemGroup>
		<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.*" />
		<PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.1.*." />

**Comment by rocketpowergirl** [comment]
I SUGGEST YOU TO USE A FRAMEWORK THAT IS GOING SOMEWHERE
UNITY OR UNREAL ENGINE
MONOGAME IS THE BIGGEST PIECE OF SHIT I HAVE SEEN 
NO DOCS
THEY CHANGE THE INSTALLATION METHOD ON EACH RELEASE
ITS GOING NOWHERE 
THERE ARE NO CONTRIBUTORS

THE *ONLY* REASON IT EXISTS IS TOM SPILMAN AND THAT BEARD LOSER MAKING MONEY OF IT FOR THEIR COMPANY

SO STOP WASTING YOUR TIME WITH IT!!!!!!!!!
