### ISSUE TITLE
`mgfxc_wine_setup.sh` downloads the x86 dotnet exectuable instead of the x64 exectuable

### ISSUE THREAD

**Issue by Tacodude7729** [MonoGame/MonoGame#7898]
Currently `mgfxc_wine_setup.sh` creates a 64-bit wine prefix than installs the 32-bit version of dotnet into `system32`. This is incorrect. The 32-bit executable should be in the `syswow64` folder, so wine freaks out when trying to execute a 32-bit executable from `system32`. MGFXC requires being on a 64-bit computer to run, so the 64-bit version of dotnet should be downloaded and installed instead. 

Before 3.8.1, the 64-bit version of dotnet 5 was installed then PR #7790 changed it from dotnet 5.0 x64 to dotnet 6.0 x86.

Likely the cause of:
 - #7865 
 - [Game build fails when shaders are used](https://community.monogame.net/t/game-build-fails-when-shaders-are-used/17817)
 - [MGFXC 8.3.1 / Wine](https://community.monogame.net/t/mgfxc-8-3-1-wine/17809)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

**Comment by Miredly** [comment]
The macos installation instructions page still links to the old broken version of this file: https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_macos.html

**Comment by Des-Nerger** [comment]
Please anyone also fix the `mgfxc_wine_setup.sh` link in there:

https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_macos.html
https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_ubuntu.html

They point to the `master` branch, which doesn't have this fix merged.
I was tripped by that.
