### ISSUE TITLE
3d game white washed and laggy after 3.8.1 upgrade

### ISSUE THREAD

**Issue by devedse** [MonoGame/MonoGame#7914]
I've just upgraded my 3d maze game to the latest 3.8.1.303 MonoGame but this resulted in some strange issues:

First of all all colors are way lighter now, original:
![image](https://user-images.githubusercontent.com/2350015/185747010-71196770-3274-4072-b3d3-1db3d9d28bc2.png)

new:
![image](https://user-images.githubusercontent.com/2350015/185747018-830d99ac-8141-4b7d-bce2-0e2dbece9509.png)

Secondly my game feels way more stuttery and laggy after the upgrade.

Here's the sourcecode:
https://github.com/devedse/DeveMazeGeneratorCore/tree/f72e6f36d1fe2220a0be69966cd96d36b01e6aba

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1.303

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by damian-666** [comment]
i get this regresson as well on my Desktop GL build... Windows DX is fine.


Another issue is on my surface if i set the refresh to 120 hz, its drawing vsync at 30 fps.. also the draw time i measure is around 30 fps.. so either Vsync is broken or its slower.. at 60 fps is ok, just the lighter colors.  Im not sure if it happens on droid but some screens are 120hz or so when you are touching them.  i use a bk thread, , no locks, and draw the last frame when i get a draw call.

**Comment by devedse** [comment]
I got a reaction on this from @nkast :
![Screenshot_20220826-092246~2](https://user-images.githubusercontent.com/2350015/186846172-d41ceff1-c3a7-4c86-8414-b06485b83bd0.png)

So you have to turn graphics.MultiSampling off for now

**Comment by espinosaluis** [comment]
@devedse Did that property fix the lagging issues for you? It still happens to me.

**Comment by devedse** [comment]
I'm not exactly sure where you're seeing that I'm doing invokes. If it is within the maze generation algorithm itself then there's no problem for the following reasons:
1. The maze is only getting generated when starting the application (once). Or when the character has finished it's run (basically like loading a new level)
2. The invokes are no Action.Invoke calls, they are simply calls on a generic method
3. The way I have implemented invokes actually get removed by the compiler. The compiler will compile a new instance of the `GenerateMaze` call based on what the generic type is. If TAction is of type NoAction. It sees that it's invoke call is supposed to be inclined (AggressiveInlining) and as the method is empty the IL for doing the invoke will actually be completely ommited.

Maybe I've gone a bit far in explaining the internals of C#/JITting but I hope it clears some confusions on your side.

**Comment by SimonDarksideJ** [comment]
@devedse are you still seeing this effect, as in several local tests we've been unable to replicate the issue in the latest version of `develop`

Can you please confirm this is still an issue?

**Comment by CartBlanche** [comment]
@devedse I'm going to close the issue for now. Re-open it if this is still and issue for you once you've tested it with 3.8.2

**Comment by squarebananas** [comment]
### 3.7
![image](https://github.com/user-attachments/assets/ea215d10-e95a-4b12-8520-f45d29e5229b)

### 3.8.2.1105
:![image](https://github.com/user-attachments/assets/ff5c0352-c9b8-4b2d-8d20-f646f3847873)

### 3.9
Maybe `Color.CornflowerWhite`.

---

### Issue
Most likely connected with: https://github.com/MonoGame/MonoGame/pull/8087

### Workaround
Force the `MultiSampleCount` to a lower value via subscribing to `PreparingDeviceSettings` in the game constructor:
```
_graphics = new GraphicsDeviceManager(this) { PreferMultiSampling = true };
_graphics.PreparingDeviceSettings += (s, e) => e.GraphicsDeviceInformation.PresentationParameters.MultiSampleCount = 4;
```
