### ISSUE TITLE
VS 2022 Mac - MG 3.8.1 extensions always install as disabled

### ISSUE THREAD

**Issue by carcharo** [MonoGame/MonoGame#7918]
The Monogame template extensions for MacOS always install as disabled. Templates do appear but then missing when next opening Visual Studio. 

<img width="634" alt="Screenshot 2022-08-22 at 19 24 07" src="https://user-images.githubusercontent.com/6247358/186021233-52ba6099-dd17-43ba-ad3c-5a858c3ef481.png">

Have tried on both Intel and Apple Silicon and the Intel Mac Mini is a fresh install of OS and Visual Studio 2022.

On Intel while the templates are listed, able to create a project and successfully build the project with content. On reopening VS & project, the association to the MGCB editor is missing but able to right click on the content file and open with editor from the solution explorer.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1.303

#### What operating system are you using:
- MacOS 12.5.1
- Visual Studio 2022 Mac v17.3.1

**Comment by harry-cpp** [comment]
That would be a bug with Visual Studio for Mac, the extension is actually enabled and works just fine :D

**Comment by ethandpowers** [comment]
I'm having the exact same issue.  I am also unable to use the MGCB editor.  I've installed the new version (3.8.1.303) with a fresh install of VS 2022.  I'm on M1 Macbook Pro.

**Comment by damian-666** [comment]
All I can say is
Look for local cache files the.vs.2022 puts in ur user account with recent
dates..erase...there's ton of junothat can screw.up ur installationand
tools..   And try the command line , manually build
..update ur ms build, try continuous CI tools.like Nuke that the dot net
team uses internally..try installing vs preview and install it on that..now
one one my vs 2022 is so corrupt I can't even uninstall it.    It's
probably not a MG issue if it works for someone..  I get weird isue reboot
often.. but they update the.preview liek every month I take updates
recklessly and it's stable for me for now .  Also monogame discord is good
for general crying out for help.


Actually  We aren't supposed to comment on closed bugs  in GitHub if really
closed,u nless we have solid proof it's not fixed properly
