### ISSUE TITLE
Problem mgcb-editor-mac for IOS project

### ISSUE THREAD

**Issue by GameGuess** [MonoGame/MonoGame#7921]
Problem with mgcb-editor-mac for IOS project
the construction is done well the .xnb files are created but when I try to load in the LoadContent...
I have a content not found error

- Apparently I'm not the only one with this problem.

- have you planned hotfix for mgcb in this realease?

remark:
mgcb-editor-mac works fine with android project

thanks in advance

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1.303

#### What operating system are you using:
- MacOS(Intel)

#### What MonoGame platform are you using:

- IOS

**Comment by impworks** [comment]
I'm having the same problem, here's a temporary solution that works for me:
https://github.com/MonoGame/MonoGame/issues/7897#issuecomment-1236777913

**Comment by GameGuess** [comment]
resolved

**Comment by GameGuess** [comment]
Thank you
