### ISSUE TITLE
SDL version check needs to be updated

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7922]
SDL changed its version naming convention. It no longer follows the ```2.0.x``` convention. ```2.0.22``` is the last release with this convention. It changed to ```2.x``` (with possible "patch" versions like ```2.x.y```). The current latest is ```2.24```.

This breaks this check:
https://github.com/MonoGame/MonoGame/blob/a9e5ae6befc40d7c86320ffdcfcd9d9b66f786a8/MonoGame.Framework/Platform/SDL/SDLGameWindow.cs#L21

We need to update this check to work with both naming conventions.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by blouflashdb** [comment]
I would like to work on this.

**Comment by Brett208** [comment]
@blouflashdb sorry I was mostly done with a fix before seeing your plan to work on it.
