### ISSUE TITLE
Windows build from linux is missing .exe icon, and launches with a terminal open

### ISSUE THREAD

**Issue by bwiklund** [MonoGame/MonoGame#7926]
I'm setting up our project for build automation, (on linux, with a windows build target), and everything works great! except:
- the game's .exe has no icon (also it's smaller by ~ the same number of kb as the Icon.ico file) (the icon works when built on windows)
- the .exe launches with a terminal window open, while the build made on windows does not

The relevant bits are, i'm grabbing the Wine setup here for the automated build:
```
wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/master/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh
```

And building like this on both platforms
```
dotnet publish -r win-x64 -c Release -p:PublishReadyToRun=false -p:TieredCompilation=false -p:PublishSingleFile=true --self-contained --output artifacts/windows
```

- MonoGame 3.8.1.303
- Windows / Linux
- DesktopGL

**Comment by mrhelmut** [comment]
Could you share your csproj? This doesn't sound like a MonoGame issue at all. It is more likely a .NET / VS Code / project configuration issue.

**Comment by Apostolique** [comment]
This is a general dotnet issue. More info here: https://github.com/dotnet/runtime/issues/3828

I did this as a temporary fix in my projects: https://github.com/Apostolique/Mitten/compare/0a4a37b%5E%5E..0a4a37b

**Comment by bwiklund** [comment]
> I did this as a temporary fix in my projects: https://github.com/Apostolique/Mitten/compare/0a4a37b%5E%5E..0a4a37b

Ah, nice. Any idea about the terminal opening itself on windows when built from linux? Does yours do that?

**Comment by Apostolique** [comment]
I'm not sure, I don't have a computer to test for the foreseeable future but you can try my builds here: <https://apos.itch.io/mitten>.

I had been running the app using the itch.io launcher. It's possible that it hides the terminal so I wouldn't see it.
