### ISSUE TITLE
Windows UWP template is missing "Content.mgcb" reference in the solution

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7941]
The Windows UWP template, while having a Content file in the project is missing the relevant entries in the csproj file to reference it.

Replication:
* Create a new MonoGame UWP project
* Observe no Content.mgcb reference or content folder in the VS solution
* Check project folder, files exist

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsUWP

**Comment by Apostolique** [comment]
I haven't checked myself but if the content builder task package is there it could automatically reference Content.mgcb. Not sure if that's what's happening, don't have a computer to check right now.

**Comment by SimonDarksideJ** [comment]
No worries, planning to submit a PR myself to sort out these template issues :D

**Comment by ancientpharaoh** [comment]
Same here

When is something fixed here?!?
There are a ton of problems everywhere and nothing is being fixed here.
On the forum many questions about the latest version and nobody answers.
Is this project still alive?????

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
