### ISSUE TITLE
VSMac Extension disables on every startup

### ISSUE THREAD

**Issue by PaulMDemers** [MonoGame/MonoGame#7944]
Using Visual Studio for Mac 2022, I have installed the MonoGame Extension. When installed, it works properly on first launch, however upon relaunching Visual Studio the MonoGame templates disappear.

I open the Extensions menu, the extension shows as disabled. I then click Disable, then Enable, it still shows as disabled however the templates now show again until the next relaunch of VS.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- macOS

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
Closing since VS for Mac is set to retire later this year. We won't be supporting it anymore. It is suggested to switch to VS Code.
