### ISSUE TITLE
mgcb-editor: documentation about standalone installation could be improved

### ISSUE THREAD

**Issue by novak-as** [MonoGame/MonoGame#7951]
As per documentation [here](https://docs.monogame.net/articles/tools/mgcb_editor.html) installation of `mgcb-editor` relies on some monogame templates. In my case, I have a relatively old project with existent automation, so I was looking for some standalone installation to minimize the amount of additional work. I really don't remember how it was installed previously, but I've noticed that I can not use rebuilt shaders because of a version mismatch. I googled a bit and found multiple "how to install standalone mgcb-editor" threads on reddit/stackoverflow. Some of them refer back to the official documentation, and some of them recommend rebuilding everything from sources or installing mgcb-editor as a standalone tool using `dotnet tool`. 

Usually, the recommended option is to do something like `dotnet tool install -g dotnet-mgcb-editor`, but I found that this is not enough.

```
> dotnet --version
6.0.401
> dotnet tool list -g
Package Id        Version        Commands
-----------------------------------------
dotnet-mgcb       3.8.1.303      mgcb
dotnet-mgfxc      3.8.1.303      mgfxc

> dotnet tool install -g dotnet-mgcb-editor
You can invoke the tool using the following command: mgcb-editor
Tool 'dotnet-mgcb-editor' (version '3.8.1.303') was successfully installed.

>mgcb-editor
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-mgcb-editor-windows does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

> dotnet tool list -g
Package Id              Version        Commands
--------------------------------------------------
aws-role                2.0.7          aws-role
dotnet-mgcb             3.8.1.303      mgcb
dotnet-mgcb-editor      3.8.1.303      mgcb-editor
dotnet-mgfxc            3.8.1.303      mgfxc

> dotnet tool install -g dotnet-mgcb-editor-windows
You can invoke the tool using the following command: mgcb-editor-windows
Tool 'dotnet-mgcb-editor-windows' (version '3.8.1.303') was successfully installed.

>mgcb-editor
 Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-mgcb-editor-windows does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

> dotnet tool list -g
Package Id                      Version        Commands
------------------------------------------------------------------
aws-role                        2.0.7          aws-role
dotnet-mgcb                     3.8.1.303      mgcb
dotnet-mgcb-editor              3.8.1.303      mgcb-editor
dotnet-mgcb-editor-windows      3.8.1.303      mgcb-editor-windows
dotnet-mgfxc                    3.8.1.303      mgfxc

> mgcb-editor-windows

UI has opened 
```

it looks that either `mgcb-editor` should have a platform-specific dependency(`mgcb-editor-windows` in my case), or `mgcb-editor-windows` should be just installed instead. **upd**: unfortunately "I can open UI and see all my resources" != "I can rebuild them". There is no reaction for "build" action, so am I doing something completely wrong?  

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL

**Comment by Apostolique** [comment]
There's a migration guide here: https://github.com/MonoGame/MonoGame/blob/develop/Documentation/articles/migrate_38.md

Look at the `.config/dotnet-tools.json` file.

**Comment by novak-as** [comment]
Oh, great. Thanks a lot @Apostolique

**Comment by gktval** [comment]
I tried the suggestion above and changed the config file. I also uninstalled mgcb and reinstalled it. When I open the mgcb-editor and click About, It still says version 3.8.0.1641. How can I update this to version 3.81.303?
