### ISSUE TITLE
🧊 [FEATURE] FBX Model Proccesor Texture Path!

### ISSUE THREAD

**Issue by MrScautHD** [MonoGame/MonoGame#7964]
Hello!
Today i tried to add a FBX Model in my Game and i saw i can not do 2 different folders for my model and texture.

I would request a Path line in the model file that allows you to set the texture for the model.

Example:
models/street_light.fbx
Processor Parameters:
Texture path: "texture/street_light"

textures/street_light.png

Screenshot how it could looks:
![Unbenasdfasdfannt](https://user-images.githubusercontent.com/65916181/204082671-6416dc43-a9b3-4cd7-82c2-993091f03353.png)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL

**Comment by stromkos** [comment]
I believe this concept is a good idea(the rebasing of texture paths and files), but it is very hard to implement.

The editor has no awareness of the files beyond the type, the properties displayed are generic to the resource type.
FBX files already contain the names and paths(relative or absolute) for the textures in an array.

---

The model processor only handles the built-in textures by default.
You can change the textures on the fly in the shader parameters when drawn.

---

The obvious solution is to modify or fix, the textures in the original FBX file and save multiple copies of the FBX for the different textures. This solution is the same as your original request:

> FBX Models and Textures should not be in 1 Folder! 

This location is where you put them when the FBX file was created. Once compiled into an XNB file, locations are irrelevant.

**Comment by MrScautHD** [comment]
ok, yea thats a way to but it would maybe a cool feature if it possible

**Comment by ohtrobinson** [comment]
> but it is very hard to implement.

This is key. You would need to physically edit the fbx file itself just to change the path. It's pretty much a pointless task. Yes, it can be annoying, but that's how it is for any model file like this. The paths are relative, and most of the time its expected that the textures are in the same directory as the model itself.

Have you considered adding this feature yourself?

**Comment by MrScautHD** [comment]
Mh yea you right
