### ISSUE TITLE
🧊 Bug! Game Icon does not change!

### ISSUE THREAD

**Issue by MrScautHD** [MonoGame/MonoGame#7975]
Hey!
I tried to Change the Icon of my Game Looked allot of Tutorials and Forums and it looks like it is a bug.
![grafik](https://user-images.githubusercontent.com/65916181/210184813-1a841c04-306f-4e32-bad6-f847564e2249.png)

![grafik](https://user-images.githubusercontent.com/65916181/210184844-a6dad866-f7d1-4484-80e8-0bb83aa92ddd.png)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- Cross Platform

**Comment by ohtrobinson** [comment]
Did you remember to change `Icon.bmp` too? This is not a bug. Changing the application icon in your project settings like that does not change the icon used in the application itself, only the one you see in the output directory.

**Comment by MrScautHD** [comment]
> Did you remember to change `Icon.bmp` too? This is not a bug. Changing the application icon in your project settings like that does not change the icon used in the application itself, only the one you see in
 the output directory.

![Unasfdasfasdfbenannt](https://user-images.githubusercontent.com/65916181/210184914-b4162f11-5859-4af1-9098-57c11bb853f5.png)

**Comment by ohtrobinson** [comment]
Make sure the `Icon.bmp` in your output folder is the icon you have set it to there. If you can't find it, then you need to set the bmp to copy to the output directory.

**Comment by MrScautHD** [comment]
witch output folder?

**Comment by MrScautHD** [comment]
`
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
        <Authors>MrScautHD</Authors>
        <ApplicationIcon>logo.ico</ApplicationIcon>
        <Title>Project-Future</Title>
        <LangVersion>11</LangVersion>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>
    <ItemGroup>
        <None Remove="Icon.ico" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
        <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="csharp\renderer\entity" />
      <Folder Include="csharp\renderer\gui" />
      <Folder Include="csharp\renderer\sky" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Future.Common\Future.Common.csproj" />
    </ItemGroup>
    <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
        <Message Text="Restoring dotnet tools" Importance="High" />
        <Exec Command="dotnet tool restore" />
    </Target>
</Project>
`

**Comment by MrScautHD** [comment]
```cs
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
        <Authors>MrScautHD</Authors>
        <ApplicationIcon>logo.ico</ApplicationIcon>
        <Title>Project-Future</Title>
        <LangVersion>11</LangVersion>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>
    <ItemGroup>
        <None Remove="Icon.ico" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
        <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="csharp\renderer\entity" />
      <Folder Include="csharp\renderer\gui" />
      <Folder Include="csharp\renderer\sky" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Future.Common\Future.Common.csproj" />
    </ItemGroup>
    <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
        <Message Text="Restoring dotnet tools" Importance="High" />
        <Exec Command="dotnet tool restore" />
    </Target>
</Project>
```

**Comment by MrScautHD** [comment]
i fixed it
```cs
  <ItemGroup>
    <EmbeddedResource Include="Icon.bmp">
      <LogicalName>Icon.bmp</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Icon.ico">
      <LogicalName>Icon.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  ```
this get not generated

**Comment by shin1m** [comment]
@MrScautHD 
Is this resolved?
If not and your Program.cs uses top-level statements, a workaround would be to use the old style entry point class with the same namespace as the assembly name.

The top-level statements generates a entry point class with no namespace, with which the code below fails to load `"<namespace of the entry point class>.Icon.bmp"`.

https://github.com/MonoGame/MonoGame/blob/2fa596123f834f322be19811d97fe6c20616d570/MonoGame.Framework/Platform/SDL/SDLGameWindow.cs#L115

**Comment by Amasuri** [comment]
> i fixed it
> 
> ```cs
>   <ItemGroup>
>     <EmbeddedResource Include="Icon.bmp">
>       <LogicalName>Icon.bmp</LogicalName>
>     </EmbeddedResource>
>     <EmbeddedResource Include="Icon.ico">
>       <LogicalName>Icon.ico</LogicalName>
>     </EmbeddedResource>
>   </ItemGroup>
> ```
> 
> this get not generated

Can confirm, had the same issue, then putting this fixed it. Obviously already had .bmp & .ico.

Worth noting that in my case it did get generated, but without the `<LogicalName>Icon.ico</LogicalName>` and `<LogicalName>Icon.bmp</LogicalName>` bits. Just the "Embedded source" thing. So the fix was like that:

![image](https://github.com/MonoGame/MonoGame/assets/30713150/7d43864d-c0f0-4dd8-9b69-e5d8aefb875d)
