### ISSUE TITLE
MGCB Shader build error.

### ISSUE THREAD

**Issue by TMworldTM** [MonoGame/MonoGame#7978]
If I start building the project, then MGCB gives an error code 1 in console.
```hlsl
// Global variable
int num = 2;

// Example
int Func()
{
  int result = 0;

  // Loop
  for (int i = 0; i < num; i++)
  {
    result += 10;
  }
  return result;
}
```

When specifying a number in the loop, the error disappears.

The same thing happens when using global variables in a loop.

```hlsl
// Global variable
int num = 2;

// Example
int Func()
{
  int result = 0;

  // Loop
  for (int i = 0; i < 2; i++)
  {
    result += num;
  }
  return result;
}
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
 - WindowsDX

**Comment by bjornenalfa** [comment]
By default loops are unrolled, which is not possible if the length is determined by a variable. Mark the loop with `[loop]` to tell the compiler you don't want it unrolled.

**Comment by TMworldTM** [comment]
> By default loops are unrolled, which is not possible if the length is determined by a variable. Mark the loop with `[loop]` to tell the compiler you don't want it unrolled.

Nothing changed.

**Comment by TMworldTM** [comment]
If I use MGCB Editor, everything compiles without problems, but when I compile using the automatic compiler, an error occurs.

**Comment by bjornenalfa** [comment]
They are the same. Make sure that the platform and profile in your .mgcb file are correct. Is there no description of the error in the build output?

**Comment by TMworldTM** [comment]
> They are the same. Make sure that the platform and profile in your .mgcb file are correct. Is there no description of the error in the build output?

I created a new project and transferred all files except Content.mgcb and everything works, thanks!
