### ISSUE TITLE
Line artifact when using sourceRectangle.

### ISSUE THREAD

**Issue by TMworldTM** [MonoGame/MonoGame#7981]
(`Sorry in advance for bad English, I use a translator`)

I have a `SpriteSheet` with tile sprites, but when I draw them using `sourceRectangle` in `<SpriteBatch>.Draw(...)`, artifacts appear when changing the matrix (camera position).
The problem is using float in matrix position, but in my case it is necessary. Is there a way to fix this?

(A transparent pixels is shown here, as there is padding between the sprites.)
![Nabe_zpuHrZa1Am](https://user-images.githubusercontent.com/67167019/214827751-1c09ed47-0a0f-4029-a1c9-c46bdc00ce9c.png)

I tried: 

1. Change `SamplerState` in `<SpriteBatch>.Begin(...)` (I am using `PointClamp`).
2. Use custom shader.
3. Turn on anti-aliasing.

No effect.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by Apostolique** [comment]
You will want to extend the edges if your sprites outside the source rectangle for 1 pixel. For example if you have these two tiles in the atlas: 
![image](https://user-images.githubusercontent.com/2766423/214936684-6ce1b0ce-a611-47e1-9946-9b5e419e490c.png)

You want to duplicated the edge pixels 1 pixel further: 
![image](https://user-images.githubusercontent.com/2766423/214937060-aff20265-9550-40cb-bf52-7ad7fb6ecb55.png)

Your source rectangle should stay the same. This allows your rendering pipeline to interpolate the edge pixels with the same color so you end up with the right result iirc.

**Comment by TMworldTM** [comment]
I wrote my SpriteBatch and solved the problem.

**Comment by Apostolique** [comment]
What do you mean and what was the solution?
