### ISSUE TITLE
Vector2 Normalize returns 'NaN', expecting (0,0)

### ISSUE THREAD

**Issue by JohnRudy** [MonoGame/MonoGame#8002]
Vector2.Normalize() returns 'NaN' for given X or Y component when value is zero. 

Example 
```cs
Vector2 zero = new Vector2 ( 0 , 0 );
zero.Normalize ( );
Console.Write(zero.ToString() );
``` 
Returns; 
```
{X:NaN Y:NaN}
```

Expected:
```
{X:0 Y:0}
```

Looking at the source code for these there seemed to be no NaN checks in place. Is this intentional design?

- MonoGame 3.8.1
- Windows
- DesktopGL

Edit: 
Seems like this is a hostile environment when basic math is an issue. Fine. It's not then an issue for 0 times 0 to return NaN and not 0. I guess I have to look into this new math then.

**Comment by Apostolique** [comment]
I don't think it's an obvious fix. There are discussions online for example: <https://stackoverflow.com/questions/722073/how-do-you-normalize-a-zero-vector>.

Personally in my games I make sure I don't have a (0, 0) vector before normalizing. It allows me to skip a lot of logic that would depend on the normalization.

For example I normalize my gamepad ThumbSticks for my movement system so a (0, 0) would actually mean the ThumbSticks is in the resting position which allows me to skip all the movement code.

**Comment by Ravendarke8** [comment]
If framework intended for game development forces branching for vector normalization then it has no right to exist.

**Comment by NicusorN5** [comment]
Do you even know how vector nomalization works? Division by zero is mathematically undefined, therefore NaNs are returned.

Before normalizing, you have to check yourself if your vector has it's length 0.

**Comment by NicusorN5** [comment]
> If framework intended for game development forces branching for vector normalization then it has no right to exist.

What if I write a framework that throws an exception if normalizing a null vector? Does it deserve to exist?

**Comment by Ravendarke8** [comment]
> Do you even know how vector nomalization works? Division by zero is mathematically undefined, therefore NaNs are returned.
> 
> Before normalizing, you have to check yourself if your vector has it's length 0.
> 
> > If framework intended for game development forces branching for vector normalization then it has no right to exist.
> 
> What if I write normalization functions that throw exceptions when normalizing a null vector. Does my framework deserve to exist then?

Like you try catch Normalize? Nope, time for ion cannon treatment.
