### ISSUE TITLE
Windows UWP CoreApp (no XAML) template is missing entirely.

### ISSUE THREAD

**Issue by vrgamestudio** [MonoGame/MonoGame#8017]
The Windows UWP CoreApp (no Xaml) template is missing entirely.

The Xaml one can be easily converted by deleting the App and Page Xaml files then creating a Program.cs file with contents such as:

var factory = new MonoGame.Framework.GameFrameworkViewSource<Game1>();
Windows.ApplicationModel.Core.CoreApplication.Run(factory);

Also, the Xaml template is missing a project reference to Content.mgcb but there is already an Issue created for that.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1.303

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopUWP

**Comment by mrhelmut** [comment]
Cleaning this as UWP is getting deprecated #8406
