### ISSUE TITLE
Couldn't install MonoGame from command prompt

### ISSUE THREAD

**Issue by biophonism** [MonoGame/MonoGame#8025]
I get the following error when trying to execute "dotnet new --install MonoGame.Templates.CSharp" in the command prompt:

```
The following template packages will be installed:
   MonoGame.Templates.CSharp

Error: No NuGet sources are defined or enabled.
MonoGame.Templates.CSharp could not be installed, no NuGet feeds are configured or they are invalid.
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows 11

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Apostolique** [comment]
Have you tried adding a source? For example

```
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
```

**Comment by biophonism** [comment]
Thanks, that worked!
