### ISSUE TITLE
Microphone Recording and Playback Stutters in MonoGame But Not XNA

### ISSUE THREAD

**Issue by AristurtleDev** [MonoGame/MonoGame#8058]
## Description
Recorded audio from `Microphone` instance is choppy and stutters when played back through a `SoundEffect`.  

## Recreation
While being a relatively simple application, a step-by-step recreation would be hard to explain. Instead, I have created a GitHub repository which contains the MonoGame 3.8.1.303 version as well as an XNA Game Studio 4.0 version for comparison.  This repository can be found at: 

https://github.com/AristurtleDev/monogame-mic-record-issue

Both programs are identical, it is a literal copy + paste of the XNA Game Studio 4.0 version into the MonoGame version.  The only change made was the removal of the `using Microsoft.Xna.Framework.GamerServices;` statement in the MonoGame version as this namespace doesn't exist in MonoGame.

The game program itself is simple. When you run it, press the `Left Mouse Button` to begin recording of the microphone set as the default microphone on the system.  While recording, `Microphone.OnBufferReady` event triggers will add the microphone data into a `MemroyStream`.  Pressing the `Right Mouse Button` will stop the recording.  Finally, pressing the `Middle Mouse Button` will create a new `SoundEffect` using the `MemoryStream`, then create a `SoundEffectInstance` and finally play the instance.

## Expected Result
The expected result is that the microphone audio is recorded and when played back using the `SoundEffectInstance`, the audio that was recorded is played back correctly.

## Actual Result
In MonoGame, the audio that is played back is choppy and stuttering.

## XNA vs MonoGame
As mentioned above, I have tested the same exact code in XNA Game Studio 4.0 using Visual Studio 2010.  When testing with XNA Game Studio, the audio is recorded and played back crystal clear as expected. No stuttering or choppiness.

## Reference
This issue was originally found and opened due to a community forum post at https://community.monogame.net/t/cant-get-microphone-to-work-properly-in-monogame-3-8-1/19332/5

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1.303

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by nkast** [comment]
The code from the original issue is the following,
```
microphone.GetData(buffer);
stream.Write(buffer, 0, buffer.Length);
```
I think it should be 
```
int actualSizeOfWavData = microphone.GetData(buffer);
stream.Write(buffer, 0, actualSizeOfWavData);
```

I don't know why the Xna sample works (if it really does).
MonoGame fires the event as soon as there are samples available,
and BufferDuration is the size of the internal buffer.
Maybe in XNA the framework dispatcher is fired every 100ms or 
that is detail of XAudio. Or maybe it fires events 
on every BufferDuration samples while internally it has a larger buffer.
But then what happens on the last sample after .Stop()?
The documentation doesn't say much on the matter, 
but that doesn't change anything. We should always use the returned
value of .GetData().

 
![BufferDuration](https://github.com/MonoGame/MonoGame/assets/3018589/c8fba0c1-3cbc-4739-bcc3-dc1ee705fb44)

**Comment by nkast** [comment]
I've made some tests to see what GetData() returns.

in XNA we get:
_lastDataSize: 8820
_lastDataSize: 8820
...
_lastDataSize: 8820

in MG we get:
_lastDataSize: 2648
_lastDataSize: 884
_lastDataSize: 882
_lastDataSize: 882
_lastDataSize: 1766
 
in Xna the return buffer is always the size of _mic.GetSampleSizeInBytes(_mic.BufferDuration) even on the last event, if the provided buffer is of the same size.
If we provide a smaller or larger buffer in the GetData() then we get variable results. Smaller or larger that 8820.
The buffer is never filled entirely, but it looks like it's multiple of some value. At one time I got a returned dataSize of 0.
Apparently BufferDuration determine the size of some internal buffer, and the implementation swaps between buffers.

OpenAL has a single ring buffer, and the way MG is implemented the size of that buffer is set by BufferDuration.
What that means, is that if the user set BufferDuration = 100ms, you need to read the buffer at least every 50ms.
As a precaution we could set the OpenAL ring buffer to hold double that of BufferDuration.

**Comment by SimonDarksideJ** [comment]
Confirmed and updating the MonoGame docs with this correction.
