### ISSUE TITLE
Visual Studio for Mac is Retiring, Should Templates Be Removed?

### ISSUE THREAD

**Issue by AristurtleDev** [MonoGame/MonoGame#8060]
Visual Studio for Mac is retiring on August 31st, 2024.  With this news, I wanted to open discussion about the Mac VS templates and if they should be removed for future releases?

https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/

This would mean removal of the templates as well as the Mac VS template build part of the cake build script.

#### What version of MonoGame does the bug occur on:
- MonoGam Future

#### What operating system are you using:
- Mac OS

**Comment by kiddkaffeine** [comment]
Can these templates be used in Rider?

**Comment by AristurtleDev** [comment]
> Can these templates be used in Rider?

These are the Visual Studio for Mac specific templates.  Rider setup on all systems is done through the dotnet cli using the `dotnet new install MonoGame.Templates.CSharp` command

**Comment by SimonDarksideJ** [comment]
Visual Studio for Mac is being retired but it is not going away.  I'd say we keep the templates if they work currently.  No need to remove something that works as there will still be plenty of people still using it.

**Comment by AristurtleDev** [comment]
> Visual Studio for Mac is being retired but it is not going away. I'd say we keep the templates if they work currently. No need to remove something that works as there will still be plenty of people still using it.

The problem is going to be when the retirement date hits (August 31st, 2024) the next LTS .NET 8 will have already been released, which is coming this November.  As of right now, MonoGame templates target .NET 6, but Visual Studio for Mac will only have rudimentary support for .NET 8

Quote from article:
> While not officially supported, we’ve also enabled rudimentary support for .NET 8 in Visual Studio for Mac for building and debugging applications.

Along with this, after the retirement date, Visual Studio for Mac will no longer be available for download as normal

Quote from article:
> Visual Studio for Mac will no longer be supported starting August 31st, 2024. On that date, Visual Studio for Mac will be available as a legacy installation only via my.visualstudio.com for users with Visual Studio subscriptions but will no longer be serviced or maintained.

For the majority of users, they are not going to have Visual Studio subscriptions to download the legacy installation.

I think keeping the VS for Mac templates in the current version of MonoGame (3.8.1.303) is fine, and any future releases between now and the retirement date is fine.  This allows current and future users (until retirement date) to continue using VS for Mac with the templates, but after the retirement date, there is no reason to continue supporting the VS templates for Mac since the application is retired, no longer supported, has limited support for the current LTS .NET, and new users will need a subscription to even download it.

However, Microsoft is pushing for non-windows (Mac specifically in this instance) to switch to VSCode using the new C# Dev Kit extension.  If future MonoGame releases (3.9+) switch to what will be the current LTS (.NET 8), then even legacy VS for Mac will not fully support.  

At that point it just becomes a technical debt to maintain for future releases for an IDE that is retired and will no longer receive support.

**Comment by harry-cpp** [comment]
VS for Mac templates have been removed in: https://github.com/MonoGame/MonoGame/pull/8066

> +1 Million for the next update for MonoGame to support .net8 and VScode as a primary on both Windows, Mac and Linux

We already fully support it, the only thing missing really is a nice way to launch MGCB Editor from VS Code without using the `mgcb-editor` command.

**Comment by AristurtleDev** [comment]
> VS for Mac templates have been removed in: #8066
> 
> > +1 Million for the next update for MonoGame to support .net8 and VScode as a primary on both Windows, Mac and Linux
> 
> We already fully support it, the only thing missing really is a nice way to launch MGCB Editor from VS Code without using the `mgcb-editor` command.

This is something I've been working on in my free time since I primarily use vscode.  I'd be happy to contribute it to the repo once finished. I can open a draft PR as I continue working on it
