### ISSUE TITLE
Rectangle has incorrect bounds

### ISSUE THREAD

**Issue by wogaaerky** [MonoGame/MonoGame#8068]
Right is (this.X + this.Width) when it should be (this.X + this.Width - 1)
Bottom is (this.Y + this.Height) when it should be (this.Y + this.Height - 1)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by nkast** [comment]
Stop thinking in 'pixels' for a moment.
.Right is the coordinates of the right edge.

**Comment by DennisGruendig** [comment]
This topic can get confusing very quickly but maybe this helps:
`0 -> 1 -> 2 -> 3 -> 4 -> 5` x = 0, right = 5
`| p1 | p2 | p3 | p4 | p5 |` number of pixels = 5 / width = 5

Another example:
`5 -> 6 -> 7 -> 8 -> 9` x = 5, right = 9
`| p1 | p2 | p3 | p4 |` number of pixels = 4 / width = 4 (right - x)

**Comment by mrhelmut** [comment]
This is by design as per XNA specifications. If you need something different, I would suggest writing a Rectangle extension that does what you need.
