### ISSUE TITLE
Encountered this issue as well, found it occured with only a single monitor plugged in at 3840x2160,  when the scaling was not set to 100% / was set to 150% caused this problem

### ISSUE THREAD

**Issue by nbulgarides42** [MonoGame/MonoGame#8070]
Encountered this issue as well, found it occured with only a single monitor plugged in at 3840x2160,  when the scaling was not set to 100% / was set to 150% caused this problem

_Originally posted by @nbulgarides42 in https://github.com/MonoGame/MonoGame/issues/7844#issuecomment-1722141732_

**Comment by stromkos** [comment]
This is not a new issue and should be closed. This is an SDL issue.
