### ISSUE TITLE
DesktopGL: GraphicsDevice.ScissorRectangle is set only once and isn't updated if the window gets resized

### ISSUE THREAD

**Issue by rds1983** [MonoGame/MonoGame#8084]
### Prerequisites

- [X] I have verified this issue is not present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame 3.8.1.303

### Which MonoGame platform are you using?

MonoGame Cross-Platform Desktop Application (mgdesktopgl)

### Operating System

Windows

### Description

GraphicsDevice.ScissorRectangle is set to wrong value if GraphicsDevice.Clear is called.
Initially ScissorRectangle is set to the window size on the initialization: https://github.com/MonoGame/MonoGame/blob/a91dcc70b681d0230e960ec8eeaec4f9ff94b605/MonoGame.Framework/Graphics/GraphicsDevice.cs#L385

And seems that it never gets updated.

### Steps to Reproduce

1. Unpack the attached sample, open in the IDE and run.
2. Resize the window.
3. Notice that the image gets cut. That happens because of the wrong Graphics.ScissorRectangle.

### Expected Behavior

GraphicsRectangle should be synchronized with the ViewPort. That's how it works for MonoGame.WindowsDX.

### Resulting Behavior

https://github.com/MonoGame/MonoGame/assets/1057289/8d2513e6-3c71-4a39-85d3-5e7365eb3a3f

### Files
[MGScissorResize.zip](https://github.com/MonoGame/MonoGame/files/13066244/MGScissorResize.zip)

**Comment by Mindfulplays** [comment]
When the viewport gets [resized, doesn't it update both `Viewport` and `ScissorRectangle`](https://github.com/MonoGame/MonoGame/blob/a91dcc70b681d0230e960ec8eeaec4f9ff94b605/MonoGame.Framework/Graphics/GraphicsDevice.cs#L900) ?

**Comment by rds1983** [comment]
Well, check the sample. It's quite simple and shouldn't be cut. But it is cut.

**Comment by samercer2002** [comment]
Hello, as this issue seems to still be present, is it open for me to take a look at? I'd like to work on it.
