### ISSUE TITLE
Update MonoGame Copyright

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#8101]
Most of the existing code has the following header or something like it:

```
// MonoGame - Copyright (C) The MonoGame Team
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.
```

With the new foundation we should update the copyright to something like:

```
MonoGame - Copyright (C) MonoGame Foundation, Inc
```

The questions are:

  - Should we wait to do this?
  - Is this what we want it to say?
  - How best do we do this... one complete commit or piece at a time?

**Comment by AristurtleDev** [comment]
> * How best do we do this... one complete commit or piece at a time?

I think doing it as one commit is fine as long as the only change across all files is the statement change from Team to Foundation.  

If you did it one piece at a time, the commits would be squashed anyway into a single commit message
