### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by Lurler** [MonoGame/MonoGame#8102]
### Intent

There have already been discussions about potential support for WebAssembly with MonoGame, however in the past couple of years there doesn't seem to be any new information regarding it. In fact, even the web demo on the MonoGame website has been removed.

So, can we get an official statement if this is something that is being worked on or is WebAssembly support has been completely scrapped and won't be officially supported?

### Motivation

More and more projects are choosing to use WebAssembly as an easy way to get cross platform support automatically and out of the box everywhere, not to mention the ability to run your projects directly in the browser with no additional tricks. So having WebAssembly would definitely be something that a lot of people are looking for and for us it is currently the main thing that forces us to look at other solutions than MonoGame.

**Comment by Apostolique** [comment]
Check <https://github.com/kniengine/kni>. It's a MonoGame fork with web as a supported platform.

**Comment by SimonDarksideJ** [comment]
For instructions on consuming the KNI engine, check out this article
https://darkgenesis.zenithmoon.com/monogame-on-the-web-No-really!.html

If this is ok, please close this issue for now as a Web target is not in the immediate future for MonoGame 3.9
