### ISSUE TITLE
dotnet 8 requires libuv runtime identifier

### ISSUE THREAD

**Issue by Mindfulplays** [MonoGame/MonoGame#8107]
### Prerequisites

- [X] I have verified this issue is present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame develop (Dec 19, 2023)

### Which MonoGame platform are you using?

MonoGame Cross-Platform Desktop Application (mgdesktopgl)

### Operating System

Windows and Mac

### Description

Seeing this error:

```bash
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206
: Found version-specific or distribution-specific runtime identifier(s): debian-x64, fedora-x64, opensuse-x64, rhel-x64
, win7-arm, win7-x64, win7-x86. Affected libraries: Libuv. In .NET 8.0 and higher, assets for version-specific and dist
ribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details. [MonoGame\MonoGame.Framework.Content.Pipeline\MonoGame.Framework.Content.Pipeline.csproj]

```

### Steps to Reproduce

Build latest MonoGame desktopgl in a dummy project

### Expected Behavior

No warnings are present

### Resulting Behavior

Warning is present

**Comment by mrhelmut** [comment]
Could you share the content of your .csproj and/or the ```dotnet build``` arguments that you used? It seems that this is due to the RID of the project you're trying to build.

**Comment by Mindfulplays** [comment]
I couldn't repro in a clean dummy project, so I think it's the way my project is setup; thanks for the pointer!

**Comment by Akarinnnnn** [comment]
> I couldn't repro in a clean dummy project, so I think it's the way my project is setup; thanks for the pointer!

Hi, you may forget setting `TargetFramework` to `net8.0`. Empry new projects with `net6.0` don't trigger this warning.
And I think `libuv` is introduced by metapackage `Microsoft.NETCore.App`, some old dependencies like `SharpDX` in WindowsDX projects referenced it.
