### ISSUE TITLE
Possibility of using WinUI 3

### ISSUE THREAD

**Issue by Natriss** [MonoGame/MonoGame#8113]
### Intent

A newer version of WindowsUniversal that would replace UWP (if possible) with WinUI 3.

### Motivation

Since UWP isn't supported anymore and the hype is WinUI 3

**Comment by mrhelmut** [comment]
The UWP target is going to be deprecated and replaced by the upcoming GDK (D3D12) implementation. This will be the standard route to publish games to the Microsoft Store on both Xbox and Windows.

If we're talking about GUI toolkit integrations, the current mood is toward encouraging the use of [ImGUI](https://github.com/ocornut/imgui), which is the industry standard for building game editors. The [ImGUI.NET wrapper](https://github.com/ImGuiNET/ImGui.NET) has [an integration example with MonoGame](https://github.com/ImGuiNET/ImGui.NET/tree/master/src/ImGui.NET.SampleProgram.XNA).

**Comment by yesseruser** [comment]
Is the public Windows GDK planned to be supported alongside the NDA'd GDK?

**Comment by mrhelmut** [comment]
Yes. The public GDK implementation is expected to replace both WindowsDX and UWP, while GDKX will be used for Xbox (actually there isn't much differences between the two and 99% of the code will be shared across those platforms and made public).

**Comment by yesseruser** [comment]
Is it possible to publish public GDK games to Microsoft Store? I'm kinda worried I'll not be able to do that afterwards and I'm not part of ID@Xbox

**Comment by mrhelmut** [comment]
As of now, an ID@Xbox registration is required to publish GDK games (.msixvc packages) on the Microsoft Store (for both Windows and Xbox). Microsoft is expecting games to move away from UWP and toward GDK if they are willing to be published on the store. We can likely expect an update on that topic by the next GDC.

UWP is not going to disappear, it's just going to be deprecated as a MonoGame target in future releases (and isn't yet, as of now). But current versions of MonoGame are still usable if anyone needs to target UWP to publish an app without an ID@Xbox registration.

I understand that this previous statement might sound worrying to current UWP users, but we are hopeful to be able to discuss more about this transition in the months to come and that all concerns will be addressed. In the meantime, nothing's changing.

**Comment by Natriss** [comment]
@mrhelmut Can I close this ticket?

**Comment by mrhelmut** [comment]
Sure, it's yours.
