### ISSUE TITLE
Xbox digital cursor showing in UWP

### ISSUE THREAD

**Issue by yesseruser** [MonoGame/MonoGame#8115]
### Prerequisites

- [x] I have verified this issue is present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

3.8.1.303

### Which MonoGame platform are you using?

MonoGame Windows Universal XAML Application (mguwpxaml)

### Operating System

Xbox Series X (built on Windows 11)

### Description

When using the Windows UWP XAML app template, the digital cursor on Xbox is not hidden by default. I have to hide it manually.

### Steps to Reproduce

1. Create new MonoGame Windows Universal XAML Application using the template
2. Debug on Xbox
3. Observe the issue.

### Minimal Example Repo

https://github.com/yesseruser/XboxCursorShowingMinimalExample

### Expected Behavior

The Xbox digital cursor should be hidden by default.

### Resulting Behavior

The cursor is shown by default on Xbox.

**Comment by yesseruser** [comment]
One solution would be to change the template to include the following code in `App.xaml.cs`:
```cs
public App()
{
    this.InitializeComponent();

    // Disable Xbox pointer mode (https://learn.microsoft.com/en-us/windows/uwp/xbox-apps/how-to-disable-mouse-mode)
    this.RequiresPointerMode = ApplicationRequiresPointerMode.WhenRequested;

    this.Suspending += OnSuspending;
}
```

**Comment by mrhelmut** [comment]
Running UWP apps on Xbox is a use-case that we are deprecating (in favor of a new upcoming GDK target). In this context, the documentation that you posted seems sufficient. Thanks!
