### ISSUE TITLE
Windows 8 - Issue with SoundEffectInstance

### ISSUE THREAD

**Issue by jonathanpeppers** [MonoGame/MonoGame#812]
In XNA, if you call Play() on a SoundEffectInstance while it's playing--it does nothing.

In MonoGame/Windows 8, it stops the sound and starts it over.  Which causes some weird issues with sound in our game.  It is possible we are using sounds in an unexpected manner, though.

I have created a repro here: https://github.com/jonathanpeppers/SoundEffectInstanceRepro

There are two solutions: plain XNA as well as MonoGame/Windows 8.

**Comment by tomspilman** [comment]
We need to test this across all platforms and apply any fixes needed.

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy - I'm pretty sure this has already been fixed, but we need to test it.

If one of you could test this on the OpenAL backend i'll test it on the DirectX backend tomorrow and we can close this out.

**Comment by tomspilman** [comment]
Yeah looking at the code this is fixed.
