### ISSUE TITLE
Project Template Type Table Documentation URLs need to be updated

### ISSUE THREAD

**Issue by EskayMarutania** [MonoGame/MonoGame#8190]
FYI: The tables in the discussion below contain links to dead pages.

### Discussed in https://github.com/MonoGame/MonoGame/discussions/8131

<div type='discussions-op-text'>

<sup>Originally posted by **AristurtleDev** January 24, 2024</sup>
# Setting Up VSCode Development Environment For MonoGame

**Project Type Table**
| Name | Short Name | Documentation |
|---|---|---|
| MonoGame Android Application | `mgandroid` | https://monogame.net/articles/platforms/#android |
| MonoGame Content Pipeline Extension | `mgpipeline`  | https://monogame.net/articles/platforms/#content-pipeline-extension|
| MonoGame Cross-Platform Desktop Application | `mgdesktopgl` | https://monogame.net/articles/platforms/#desktopgl |
| MonoGame Game Library | `mglib` | https://monogame.net/articles/platforms/#net-standard-library |
| MonoGame iOS Application | `mgios` | https://monogame.net/articles/platforms/#ios|
| MonoGame Shared Library Project | `mgshared` | https://monogame.net/articles/platforms/#shared-project |
| MonoGame Windows Desktop Application | `mgwindowsdx` | https://monogame.net/articles/platforms/#windowsdx|
| MonoGame Windows Universal XAML Application | `mguwpxaml` | https://monogame.net/articles/platforms/#windowsuniversal |

**Comment by AristurtleDev** [comment]
Thanks @EskayMarutania,

I've updated the links in the discussion post, this issue can be closed.

**Comment by EskayMarutania** [comment]
Thank you @AristurtleDev! Closing issue
