### ISSUE TITLE
PathHelper.GetRelativePath potential bugs

### ISSUE THREAD

**Issue by gameoflord012** [MonoGame/MonoGame#8208]
### Prerequisites

- [X] I have verified this issue is present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame 3.8.1

### Which MonoGame platform are you using?

MonoGame DesktopGL

### Operating System

WIndows

### Description
The problem reside in function **GetRelativePath(string basePath, string path)** in file **MonoGame.Framework.Content.Pipeline/Builder/PathHelper.cs**
```c#
public static string GetRelativePath(string basePath, string path)
{
    Uri uri;
    if (!Uri.TryCreate(path, UriKind.Absolute, out uri))
        return path;

    uri = new Uri(basePath).MakeRelativeUri(uri);
    var str = Uri.UnescapeDataString(uri.ToString());

    return Normalize(str);
}
```
The issue is the return result of **PathHelper.GetRelativePath()** is relative path without the dot as the first char
- The true result should be **./bin/pathtomycontent.xnb**
- But instead **/bin/pathtomycontent.xnb** without the '.'

As we understand, path without the first dot is treated as an rooted path by .NET

This is where the piece of code calling **PathHelper.GetRelativePath()** bug appears, 
the function in **MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs** file which retrieve infomation of cached .mgcontent file
```c#
private PipelineBuildEvent LoadBuildEvent(string destFile, out string eventFilepath)
{
    var contentPath = Path.ChangeExtension(PathHelper.GetRelativePath(OutputDirectory, destFile), PipelineBuildEvent.Extension);
    eventFilepath = Path.Combine(IntermediateDirectory, contentPath); // This is where we messed up
    return PipelineBuildEvent.Load(eventFilepath);
}
```
**Path.Combine()** will only process the latter argument because **contentPath** is rooted and ignore **IntermediateDirectory**

### Steps to Reproduce

The problem can be reproduced by calling the function with **destFile** is a full subpath of OutputDirectory. 

For example calling **LoadBuildEvent("D:\\MyMonoGameProject\\Content\\out\\MyGameImage.xnb", out string eventFilepath)** with **OutputDirectory** is **"D:\\MyMonoGameProject\\Content\\out\\"**

### Expected Behavior

The out parameter **eventFilepath** should be **"D:\\MyMonoGameProject\\Content\\obj\\MyGameImage.mgcontent"** if the value of **IntermediateDirectory** is **D:\\MyMonoGameProject\\Content\\obj\\**

### Resulting Behavior

But instead the result of **eventFilepath** be **\MyGameImage.mgcontent** because **PathHelper.GetRelativePath()** return a rooted path

**Comment by samercer2002** [comment]
Hey, I am a first time contributor to MonoGame and I would like to work on this issue.

**Comment by samercer2002** [comment]
Hey again. Walked through the steps to replicate the issue and couldn't seem to replicate the issue at all. Currently I am using .NET 8 as my .NET version. When using console output, the GetRelativePath function returned a value without a '.' or a './' in front of it. For an example, my file I was loading was under ProjectDir\Content\bin\ball.xnb and when calling LoadBuildEvent with that file, it gave me an event file path as expected under the Intermediate directory. 

When looking at the documentation for Uri, it also shows that it should be returning a path without a '.' or './' in front of it as I was able to get.

Could @gameoflord012 replicate the issue and post a screenshot or video? That'd be much appreciated if this is an issue that is persisting.

**Comment by stromkos** [comment]
> As we understand, path without the first dot is treated as an rooted path by .NET

That is correct.  But the `GetRelativePath`  is destined to be combined with another path. The use of `.`, the current directory, would break build calls where the call was made outside of the directory tree.
