### ISSUE TITLE
[PAID BOUNTY][LOCKED] A shared base for public and console repos

### ISSUE THREAD

**Issue by harry-cpp** [MonoGame/MonoGame#8242]
_MonoGame needs a new base that can be used between public and private console repos._

📃**Full details**

MonoGame provides console ports of itself in private repos, all you need to do to access it is to be a registered developer for the correct platform. They are in private repos because of the console NDAs.

In order to make the work between the public and private repos less separate, we wanted to move MonoGame to a new system where there will be one C# **MonoGame.Framework.dll** assembly that can be used for both. It would containt only the C# wrapper calls to our custom **monogameframework** native library, then we could switch out the native library depending on the platform you are targeting.

🔒 Bounty status

Locked for @tomspilman to complete. 🔒

💰 **Bounty**

$1200,00 USD (One thousand and two hundred US dollars).

✋ **Requirements to apply**

_Standard requirements from [our generic bounty requirements](https://monogame.net/bounties/#requirements) as well as knowlage on C++, C++ build systems, Vulkan and SDL._

📦 **Expected delivery content**

- **MonoGame.Frameowk.Native** C# project
  - All C# Stubs need to be fully filled with wrapper calls to **monogameframework**
  - A generator needs to be writted to export all the wrappers to header files that need to be filled using reflection
  - Needs to be hooked up to the tests and passing non graphics / audio tests
- **monogameframework** native library
  - This library needs to contain exposed methods for all the platform call MonoGame does
  - All platform calls need to be fully implemented (Windowing + Input, using SDL)
  - Vulkan code needs to be moved from the private MonoGame repo
    - All graphics calls need to be fully hooked up, it does not need to be fully working
  - No audio call should be implemented, we are planing on using FAudio and a relavent bounty for it will be released at future time
- Both projects need to be fully hooked up to the CAKE Frosting build system

📅 **Delivery timeline**

As soon as possible.

**Comment by tomspilman** [comment]
FYI.  As part of this i will move the sharable bits of the DX12 work @Togimaro did for https://github.com/MonoGame/MonoGame/issues/8195 into the public MG repo under this new native API.

**Comment by tomspilman** [comment]
This bounty is completed.
