### ISSUE TITLE
Variable rate shading

### ISSUE THREAD

**Issue by BitKovin** [MonoGame/MonoGame#8256]
### Intent

Variable rate shading is pretty good technique that might help a lot with optimization. It allows to change rate of shading based on different areas of the screen. It improves performance by reducing GPU workload in areas where high number of details are less noticeable.

### Motivation

It would allow developers to optimize their game's performance. By allowing for different shading rates across the screen, less demanding areas can be rendered with lower quality, freeing up curtail GPU time.

**Comment by stromkos** [comment]
Variable rate shading would not improve the performance of most of the common graphics limiting factors:

 *  Draw Call counts
 *  PCIE transfers of Vertices, Textures and Parameters

It is only helpful in pixel shaders with complex calculations such as  in procedural generators, particles, large numbers of texture lookups...

The main drawback is the loss of stencil mask precision, most notably in the depth (Z) buffer making it unsuitable for many of the common shadow algorithms.

VRS is only available on DirectX 12 and Vulkan neither of which is generally implemented as of 3.8.1, greatly increasing the cross-platform complexity and non-parity.

Alternative
---

You could simply render your game to a `RenderTarget` a 1/2 resolution on each axis and  then draw it scaled to fit the screen.

**Comment by mrhelmut** [comment]
VRS is an advanced rendering technique that is very unlikely to be of use to more than 0.1% of MG's user base. I don't think that we've ever seen a game made with MG that has this level of requirements.

Also, this is more within the scope of an engine, which MG isn't. MG is more about providing the building blocks to implement your own techniques than providing an actual advanced renderer.
