### ISSUE TITLE
tu-clausthal link does not exists

### ISSUE THREAD

**Issue by lucaspalomodevelop** [MonoGame/MonoGame#8262]
this link does not exists

https://github.com/MonoGame/MonoGame/blob/40452a45c261a4a32c63e1c6c35e5f2676c1dfc2/MonoGame.Framework/BoundingBox.cs#L669-L670

**Comment by AristurtleDev** [comment]
Is available on wayback https://web.archive.org/web/20160321050150/http://zach.in.tu-clausthal.de/teaching/cg_literatur/lighthouse3d_view_frustum_culling/index.html

**Comment by AristurtleDev** [comment]
Found it, new location for the url is https://cgvr.informatik.uni-bremen.de/teaching/cg_literatur/lighthouse3d_view_frustum_culling/index.html
