### ISSUE TITLE
Getting started page is not working

### ISSUE THREAD

**Issue by henkehedstrom** [MonoGame/MonoGame#8277]
### Prerequisites

- [X] I have verified this issue is present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

Any

### Which MonoGame platform are you using?

N/A

### Operating System

Windows

### Description

The link for getting started (https://docs.monogame.net/articles/getting_started/0_getting_started.html) from your website shows me a 404 error. Both on my pc and mobile phone. Not sure if this is the correct place to report. 
![image](https://github.com/MonoGame/MonoGame/assets/36405465/cb516776-c3dd-4a23-9919-0c10ec81d774)

### Steps to Reproduce

Click on getting started on https://monogame.net/ 

### Expected Behavior

A working webpage should be shown 

### Resulting Behavior

A 404 file not found page is shown (see image in description)

**Comment by Kubrix** [comment]
I thought avout posting here but that did not sound like an issue so I posted in discussion
https://github.com/MonoGame/MonoGame/discussions/8273

**Comment by BlueElectivire** [comment]
This seems to have been solved - the URL changed to https://docs.monogame.net/articles/getting_started/index.html (which might be the thing that caused the issue), but the link on the front page has been updated accordingly.
