### ISSUE TITLE
Separate interfaces and platform-specific realizations

### ISSUE THREAD

**Issue by k4G17eYWI** [MonoGame/MonoGame#8303]
### Intent

It would be great to make interfaces to MonoGame objects (IGraphicDevice, ITexture2D, IContent, etc.) and separate them into a platform-independent Nuget package. Also all data-structures like vectors, matrices, colors, etc. should be put into it.

### Motivation

Thus it will be possible to create platform-independent projects instead of using shader-project.

Moreover, this functionality will not break backward compatibility, but will expand the possibilities of creating projects.

**Comment by mrhelmut** [comment]
Covered by #8242

**Comment by k4G17eYWI** [comment]
Got it! Naming got me confused a bit.
