### ISSUE TITLE
Deprecation of the UWP platform/target

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#8406]
### Intent

UWP is no longer a targetted/supported platform with Microsoft, and UWP submissions are no longer accepted on the Xbox Creators program for Xbox.

As per the roadmap, UWP is due to be deprecated for the 3.8.2 release.

### Motivation

Detailed above

**Comment by mrhelmut** [comment]
Just noting that once UWP will be deprecated and replaced by the Direct3D 12 version of MonoGame, a few things will change in regard to publishing games on Xbox or the Microsoft Store:
- It will no longer be possible to run MonoGame apps on retail Xbox consoles using the dev mode
- It will no longer be possible to self-publish MonoGame apps on the Microsoft Store with just the Creators Program
- An ID@Xbox license will be required to publish games on the Microsoft Store (including on PC)
