### ISSUE TITLE
Cleaning unused stuff

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#8412]
There are some unused stuff in the repository that we should remove:
- [Lidgren](https://github.com/MonoGame/MonoGame/tree/develop/ThirdParty/Lidgren.Network) and [references to it](https://github.com/search?q=repo%3AMonoGame%2FMonoGame%20lidgren&type=code)
- [GamepadConfig](https://github.com/MonoGame/MonoGame/tree/develop/ThirdParty/GamepadConfig)
- [ThirdParty/ThirdParty.iOS.sln](https://github.com/MonoGame/MonoGame/blob/develop/ThirdParty/ThirdParty.iOS.sln)

**Comment by JakeLegendXIII** [comment]
I have removed these 3 over in PR #8414 . Let me know if there are any questions or concerns!
