### ISSUE TITLE
[PAID BOUNTY] Upgrade MonoGame to use BasisUniversal for cross platform Texture Compression

### ISSUE THREAD

**Issue by dellis1972** [MonoGame/MonoGame#8419]
MonoGame's texture compression needs to be updated to support arm based machines.

📃**Full details**

MonoGame currently uses many native libraries to handle texture compression (nvtt, libpvr). Unfortunately these libraries are out of date and are tied to the x86/x86_64 CPU's because they use SIMD. As a result these libraries do not work on arm based chipsets like the Apple M1/M2. 

In order to fix the developer experience we need to switch out the texture compression code to use [Basis Universal](https://github.com/BinomialLLC/basis_universal). Which is a cross platform texture compression tool. The MonoGame build of this library is [here](https://github.com/MonoGame/MonoGame.Tool.BasisUniversal).

This new tooling is a command line tool. It will generate an intermediate file from which the compressed formats can be created. We will also need to shell out to the new `basisu` tool twice. Once to generate the intermediate file for the source image and once to generate the compressed data. Note the intermediate file can be used to generate many different compression types so it might not need to be called twiece every time.

This bounty is important as it will improve the stability and usability of the content pipeline on Mac and Linux. 

🔒 Bounty status

Assigned to @cdhanna
In Progress https://github.com/MonoGame/MonoGame/pull/8456/

💰 **Bounty**

$2000,00 USD (Two thousand US dollars).

✋ **Requirements to apply**

Standard requirements from [our generic bounty requirements](https://monogame.net/bounties/#requirements).
Having access to a Mac and Linux machines to aide testing is important.

📦 **Expected delivery content**

- Update MonoGame.Framework.Content.Pipeline
   - Remove all references to Nvidia.TextureTools.dll, libnv*.so/dll/dylib
   - Remove all References to ATI.TextureConverter.dll
   - Remove all Reference to PVRTexLibNET.dll and libPVRTexLibWrapper.so
   - Add references to the new MonoGame.Tool.BasisUniversal and make sure the `basisu` tool is being deployed along side the content pipeline assembly. Similar to how ffmpeg works.
   -  Create a central utility class through which the `basisu` tool can be called to generated the compressed textures. Note this should make use of the existing `ExternalTool.Run` method.
   - Add a utility class to create .ktx files and extract the compress texture data, which the above utility class will use. See https://registry.khronos.org/KTX/specs/1.0/ktxspec.v1.html. This class does not need to be feature complete. It just needs to be able to read the .ktx and extract the compressed texture data for the various mipmaps.
   - Update the various `BitmapContent` derived classes to call into the new Utility class to get the data
       - AtcBitmapContent
       - DxtBitmapContent
       - PvrtcBitmapContent
       - Etc1BitmapContent
   - Update unit tests to take into account the new compression methods (the test data might change with the new compressor).
   - Make sure the content pipeline works on Mac/Linux and Windows.
   - Add Support for the following Texture Compression Formats
      - Etc2
      - Atsc
   - Building compressed textures on Mac/Linux and Windows should *Just work* 😄 

📅 **Delivery timeline**

This bounty is urgent as it is holding up the 3.8.2 release.

**Comment by mrhelmut** [comment]
If that may be an additional incentive to take on this bounty: this is the one last bit that is holding 3.8.2's release back.

**Comment by tomspilman** [comment]
> If that may be an additional incentive to take on this bounty: this is the one last bit that is holding 3.8.2's release back.

IMO.  If no one takes this up soon, we should release 3.8.2 as is with broken Linux/Mac content building support.

We can always release a 3.8.3 with it fixed if someone does take it up later.

My issue is holding up a release for the 99% of Windows users for 1% Mac/Linux users.

**Comment by Brett208** [comment]
Would you mind clarifying what might be broken in 3.8.2 if this issue isn't tackled? Is it that the content pipeline when using Linux or Mac as a dev environment would not function or is it that when using Windows for the dev environment, we would be unable to prepare content for iOS and Linux builds? I think the answer is the former but wasn't sure when reading. 

Thank you,
Brett

**Comment by dellis1972** [comment]
@Brett208 The Content Pipeline does not work out of the box on Arm based machines for Linux /Mac. Windows builds are unaffected. A Work around is documented at https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_vscode.html?tabs=macos#apple-silicon-known-issues

**Comment by dellis1972** [comment]
Bounty payout updated to $2000

**Comment by NitroPlum** [comment]
Is there somewhere we can actively track the status of this? I believe I am capable of the work and have the machines available. The only thing I'm missing is the current self-employment status but I could remedy that if no one comes along.

**Comment by dellis1972** [comment]
This bounty has been assigned to @cdhanna and is now closed for applications. Thank you to all who applied we look forward to your future contributions to MonoGame.

**Comment by cdhanna** [comment]
I've opened up a PR to include the basisu binaries in the Monogame.Dependencies submodule, https://github.com/MonoGame/MonoGame.Dependencies/pull/167 

I've also opened an in-progress PR on my own fork of Monogame to show where I'm at,
https://github.com/cdhanna/MonoGame/pull/1 

I'll try and keep the PR on the fork up to date with commentary, and I'll open up a PR back into the main repo in Draft form when its at least feature complete.

**Comment by dellis1972** [comment]
@harry-cpp  can we get some guidance on how we are going to use the new MonoGame.Tools.* Repo's in this repo please.

**Comment by harry-cpp** [comment]
In case of tool repos, you should expect to invoke them from content pupeline project like so: "dotnet mgcb-ffmpeg"

You can test it by restoring the dotnet tool next to the mgcb file you are testing with.

**Comment by cdhanna** [comment]
For this task regarding `basisu`, the goal is to invoke `basisu` from within the `.cs` source code. We could rely on `dotnet` to invoke the tool; but that would require introducing a `dotnet-tools.json` manifest on the user's machine. Technically, most projects already have one since `mgcb` is a listed dotnet tool anyway. Are you suggesting that we should include `basisu` as a local dotnet tool installation alongside `mgcb`, and then invoke it from `.cs` files using Process invocation via `dotnet run mgcb-basisu` ? 

It seems like the way that other third party binaries are invoked is by bundling those binaries within the `Dependencies` git submodule, and then including those binaries from the `csproj` file of the monogame content pipeline project. This is the way I had been planning on moving forward, but I am happy to pivot. I just don't see any existing examples for the tool flow, although I could very well be looking in the wrong spot :)

**Comment by dellis1972** [comment]
@harry-cpp I was more thinking of will we still be using the ThirdParty submodule? Or referencing the new tools via Nuget or refereing the projects via a direct submodule or somehting else?

Regading how we execute it `basisu` is a native binary so there is no `mgcb-basisu`. Unless I'm missing something?

**Comment by harry-cpp** [comment]
> For this task regarding basisu, the goal is to invoke basisu from within the .cs source code. We could rely on dotnet to invoke the tool; but that would require introducing a dotnet-tools.json manifest on the user's machine. Technically, most projects already have one since mgcb is a listed dotnet tool anyway. Are you suggesting that we should include basisu as a local dotnet tool installation alongside mgcb, and then invoke it from .cs files using Process invocation via dotnet run mgcb-basisu ?

Exactly. We'll just need to add the new dotnet tool to the restore list in templates:
<https://github.com/MonoGame/MonoGame/blob/develop/Templates/MonoGame.Templates.CSharp/content/MonoGame.Application.DesktopGL.CSharp/.config/dotnet-tools.json>

You don't have to worry about if `dotnet basisu` is restored or dotnet-tools.json is present, just think of it as always available  while testing.

> @harry-cpp I was more thinking of will we still be using the ThirdParty submodule? Or referencing the new tools via Nuget or refereing the projects via a direct submodule or somehting else?
> 
> Regading how we execute it basisu is a native binary so there is no mgcb-basisu. Unless I'm missing something?

The MonoGame.Tool.X repos are dotnet tools, its using the same setup we have for mgcb and mgcb-editor.

**Comment by dellis1972** [comment]
@harry-cpp have any of these tool packages been published yet?

**Comment by harry-cpp** [comment]
ffmpeg and ffprobe ones:
- https://www.nuget.org/packages/mgcb-ffmpeg
- https://www.nuget.org/packages/mgcb-ffprobe

Sample usage can be found in commit in my wip branch:
- https://github.com/harry-cpp/MonoGame/commit/dfe0bedbeca45117a8ecfcd7ee76e8a66418cf21

**Comment by dellis1972** [comment]
I've just done a tag (1.16.4) for basisu. Hopefully that will end up on nuget.

**Comment by dellis1972** [comment]
It ran, https://github.com/MonoGame/MonoGame.Tool.BasisUniversal/actions/runs/10176143547/job/28144995093. Not sure if it wentt o nuget though.

**Comment by harry-cpp** [comment]
A couple of notes:
- Bump buildscripts, there was a bug with passing arguments, the built package needs to be rebuilt with the fix
- Always tag with 4 numbers, ie. `1.16.4.1`, the first 3 numbers represent the tool version, the last number represents our build version
- Once tagged, it uploads the nuget to https://github.com/MonoGame/MonoGame.Tool.BasisUniversal/pkgs/nuget/mgcb-basisu and makes a new release, thus far we are never directly uploading anything to nuget.org. You can manually upload the built package if you are happy with it, just remember to add it to the MG org

**Comment by cdhanna** [comment]
A few thoughts from me
1. I see that the `ffmpeg` (https://www.nuget.org/packages/mgcb-ffmpeg) sample referenced is only built to `net8.0`, but the MonoGame framework (https://www.nuget.org/packages/MonoGame.Framework.DesktopGL#supportedframeworks-body-tab) is built for `net6.0`. I would suggest that we should keep the target framework at net6, and add a `<RollForward>LatestMajor</RollForward>` entry to each tool's `csproj`. 
2. As for using the tool, I understand that for testing, I could just install the tool globally from own fork :+1: But when the users create a new project with `dotnet new`, we'd need to update the templates, here https://nuget.info/packages/MonoGame.Templates.CSharp/3.8.1.303 . However, beyond that, what is the plan for _existing_ monogame projects? I think I just haven't seen or heard anyone mention how the `mgcb` tool would make sure that `mgcb-basisu` existed in the the user's `dotnet-tools.json` file. I hope that mg users wouldn't need to manually update that file. 
3. I would advise a modicum of caution about tools invoking tools. Unless the tool is installed as a standalone-app (with dotnet pre-bundled into it), there is an interesting `dotnet` versioning issue that shows up on edge-cases. To be clear, I don't think Monogame is at this point, but if the invocation of the tool depends on a `dotnet` version, then when a user selects a specific version of `dotnet` to invoke the first tool in a chain of tool invocations, it would be good (but is hard) to forward their dotnet selection onto the later calls in the chain. Put differently, if I specifically use `net7` to invoke `mgcb` for some reason, but that tool makes a process call to `dotnet mgcb-basisu`, then the `dotnet` being used is ... which? `net7`, or perhaps the system default, `net8` ?

**Comment by harry-cpp** [comment]
> I see that the ffmpeg (https://www.nuget.org/packages/mgcb-ffmpeg) sample referenced is only built to net8.0, but the MonoGame framework (https://www.nuget.org/packages/MonoGame.Framework.DesktopGL#supportedframeworks-body-tab) is built for net6.0. I would suggest that we should keep the target framework at net6, and add a <RollForward>LatestMajor</RollForward> entry to each tool's csproj.

MonoGame internally already switched to net8.0. Our plan going forward is to require the latest dotnet SDK to be installed with each release. If you need to use an older dotnet, then you can use the older version of MonoGame.

> As for using the tool, I understand that for testing, I could just install the tool globally from own fork 👍 But when the users create a new project with dotnet new, we'd need to update the templates, here https://nuget.info/packages/MonoGame.Templates.CSharp/3.8.1.303 . However, beyond that, what is the plan for existing monogame projects? I think I just haven't seen or heard anyone mention how the mgcb tool would make sure that mgcb-basisu existed in the the user's dotnet-tools.json file. I hope that mg users wouldn't need to manually update that file.

I gave a simplified version of how to look at it, the way it will work is mgcb will check for installed tool in the users project directory, then if it fails to find it it will invoked the tool from its own directory that contains the needed tooling manifest. The only thing needed for this to work is to just pass absolute paths when calling ffmpeg/ffprobe/etc, which is just good practice in general 😄 

> I would advise a modicum of caution about tools invoking tools. Unless the tool is installed as a standalone-app (with dotnet pre-bundled into it), there is an interesting dotnet versioning issue that shows up on edge-cases. To be clear, I don't think Monogame is at this point, but if the invocation of the tool depends on a dotnet version, then when a user selects a specific version of dotnet to invoke the first tool in a chain of tool invocations, it would be good (but is hard) to forward their dotnet selection onto the later calls in the chain. Put differently, if I specifically use net7 to invoke mgcb for some reason, but that tool makes a process call to dotnet mgcb-basisu, then the dotnet being used is ... which? net7, or perhaps the system default, net8 ?

Different project can require different version of mgcb to compile the content, so we must avoid using global tools.

mgcb-ffmpeg, mgcb-ffprobe, mgcb-basisu contain only the passthrough C# wrapper (just passthrough for arguments to the correct executable), it does not matter what net they get invoked with, as they will never contain any actual logic.

**Comment by cdhanna** [comment]
>so we must avoid using global tools. 

Yep, totally agree :+1: And yeah, just as long as the tool wrappers don't do really _anything_ other than invoke the packaged binary, then I retract my concern. In my own career, we use a lot of `msbuild` tooling through dotnet tools, and you can get into trouble. 

>then if it fails to find it it will invoked the tool from its own directory that contains the needed tooling manifest. 

I think I need to go explore the ffmpeg example a bit more. You mentioned that was wip on a branch somewhere? 

>MonoGame internally already switched to net8.0. 

Ah ha, then that solves that concern. :+1:

**Comment by harry-cpp** [comment]
> I think I need to go explore the ffmpeg example a bit more. You mentioned that was wip on a branch somewhere?

https://github.com/harry-cpp/MonoGame/commit/dfe0bedbeca45117a8ecfcd7ee76e8a66418cf21

Just run `dotnet mgcb-basis` and don't worry about anything else :D

**Comment by cdhanna** [comment]
@harry-cpp , sorry for the long delay in getting back to you.

I just wanted to follow up and say that the tool stuff is pretty cool! I have a critical bug, but otherwise, its working (in that I can invoke the tool)
Just to recap, I did the following steps...
1. I authenticated my local machine with the Monogame nuget repo, 
2. I ran this, `dotnet tool install  mgcb-basisu --create-manifest-if-needed` in the root directory of the Monogame repo. Now I have a `.config/dotnet-tools.json` file, and I can execute `dotnet mgcb-basisu` from the command-line. 
3. I modified my code to invoke the `dotnet` process and set the first argument to be `mgcb-basisu`. :+1: 

A sample of a command I might run...

```
mgcb-basisu -file /Users/chrishanna/Documents/Github/MonoGame/Artifacts/Tests/Tools/Debug/test/d0123396-dc23-471d-86a7-a6a3ef5324a7/tempImage_dc5868dc-c5ac-407b-89ce-b9b4df97404b.png -uastc -ktx2 -output_file test/d0123396-dc23-471d-86a7-a6a3ef5324a7/tempImage_dc5868dc-c5ac-407b-89ce-b9b4df97404b.png.ktx
```
However, when I run that (using `dotnet` as the process), I get this error, 

```
ERROR: Unrecognized command line option: -file /Users/chrishanna/Documents/Github/MonoGame/Artifacts/Tests/Tools/Debug/test/d0123396-dc23-471d-86a7-a6a3ef5324a7/tempImage_dc5868dc-c5ac-407b-89ce-b9b4df97404b.png -uastc -ktx2 -output_file test/d0123396-dc23-471d-86a7-a6a3ef5324a7/tempImage_dc5868dc-c5ac-407b-89ce-b9b4df97404b.png.ktx
```

Unfortunately, if I just go to my prebuilt basisu tool and invoke it by hand, it works.

Is there something I'm missing about arg passing to the tool? 

Also, it seems like the error-code isn't being forwarded correctly? If the sub-invocation of `basisu` fails, I get an error reported, but the exit code of the process is `0`, indicating success. 
I think here, https://github.com/MonoGame/MonoGame.Tool.BuildScripts/blob/f123c5529154d688fc5ce959f7c31d3fe5ef7de1/Resources/Program.txt#L47, if the script returned with the `process.ExitCode`, that would fix that problem.

**Comment by cdhanna** [comment]
Oh my gosh, I'm sorry, I completely forgot to re-read the post and I saw your earlier message, 
>Bump buildscripts, there was a bug with passing arguments, the built package needs to be rebuilt with the fix

Sorry about the wall of text for a known issue.

**Comment by dellis1972** [comment]
An update. Work on this bounty is progressing nicely. Things we need to do 

- [ ] Publish MonoGame.Tool.BasisUniversal
- [ ] Publish MonoGame.Tool.Crunch
- [ ] Get the main PR at https://github.com/cdhanna/MonoGame/pull/1 up for the main repo and start the review process once its above tasks have been completed.

**Comment by cdhanna** [comment]
@harry-cpp , I'd like to follow up on this, 
>the way it will work is mgcb will check for installed tool in the users project directory, then if it fails to find it it will invoked the tool from its own directory that contains the needed tooling manifest. The only thing needed for this to work is to just pass absolute paths when calling ffmpeg/ffprobe/etc, which is just good practice in general 😄

My brain would benefit from some additional context about how to ensure the dotnet tools (mgcb-basisu, and now also mgcb-crunch) are actually available in a user's project. I see two possible pathways, 
1. the user starts a brand new monogame project, 
2. the user upgrades their existing monogame project to a release that relies on these tools

In the first case, my intuition is that the monogame templates would include new references in the `.config/dotnet-tools.json` file. 

In the second case, is the expectation that users will be required to manually update their `.config/dotnet-tools.json` files? Or are you imagining (or have already designed/built) a system that automatically installs the tools? I could envision something that checks the `.config/dotnet-tools.json` (or runs `dotnet tool list --local`) and runs some `dotnet tool install` or `dotnet tool update` commands before the processor really kicks off. Is that what you're thinking? 

Specifically about this section,
>The only thing needed for this to work is to just pass absolute paths when calling ffmpeg/ffprobe/etc

are you suggesting that anytime we invoke a dotnet tool, we catch a specific failure case where the dotnet tool doesn't exist, and run the auto-install then? Does monogame have an internally bundled version number that would signal which versions of the tools to download?

**Comment by harry-cpp** [comment]
Its neither, the tool manifest will be moved inside mgcb and mgcb task nuget and will no longer live inside the project directory.

**Comment by dellis1972** [comment]
@harry-cpp any ETA on when the other library work will be done? (FreeImage, Assimp etc). We are getting to the point where we will need it for this Bounty to be merged.

**Comment by cdhanna** [comment]
>Its neither, the tool manifest will be moved inside mgcb and mgcb task nuget and will no longer live inside the project directory.
@harry-cpp , again, sorry for the delayed follow up.

I'm still trying to wrap my head around the vision for the future of the mgcb/task.
Does this part, "mgcb task nuget and will no longer live inside the project ", imply that the user's project won't have a direct reference to the `<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />` anymore? 
I know that given that the user is referencing _some_ `MonoGame.Framework`, (like, `<PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />`), that package has an opportunity to inject custom `.props` and `.targets` files; but those files cannot affect nuget package resolution; so I'm unclear how the project would reference the `MonoGame.Content.Builder.Task`. 
Perhaps that is not what you meant by the comment at all.

And this part, "the tool manifest will be moved inside mgcb"... Are you saying that there would be a `.config/dotnet-tools.json` file at the MonoGame repo path, `Tools/MonoGame.Content.Builder/.config/dotnet-tools.json` ? If so, how would that file get used correctly by a user's machine? Would the dotnet tool invocations somehow be able to reference that manifest, even though its buried in a nuget cache somewhere? Perhaps there is a custom `.targets` file in the `MonoGame.Content.Builder` nuget package that copies the local manifest into the user's project? Again, perhaps I'm totally   misunderstanding this. 

I would love to have a better understanding.

**Comment by dellis1972** [comment]
This bounty is now complete. 🥳 

Thanks for @cdhanna for all his hard work and research on this item 👍
