### ISSUE TITLE
Window.AllowAltF4 = false; Don't works on OpenGL

### ISSUE THREAD

**Issue by PaologGithub** [MonoGame/MonoGame#8437]
### Prerequisites

- [x] I have verified this issue is present in the `develop` branch
- [x] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

MonoGame 3.8.1.303

### Which MonoGame platform are you using?

MonoGame Cross-Platform Desktop Application (mgdesktopgl)

### Operating System

Windows

### Description

I tried to put `Window.AllowAltF4 = False;` code in the `Initialize` function

The AllowUserResizing and Title works on OpenGL, but the AllowAltF4 doesn't work.
On DirectX, it works well

### Steps to Reproduce

````cs
public class MyGame : Game 
{
// Code
    protected override void Initialize() {
        Window.AllowAltF4 = false;
    }
}
```

### Minimal Example Repo

_No response_

### Expected Behavior

I except that the game doesn't close, like on DirectX

### Resulting Behavior

The game closes.

### Files

_No response_

**Comment by SimonDarksideJ** [comment]
Tested in MonoGame `3.8.2` and works as expected, the above code prevents Alt-F4 in a desktop gl build.
