### ISSUE TITLE
Monogame in DevExpress

### ISSUE THREAD

**Issue by fomines** [MonoGame/MonoGame#8446]
Hi!
I'm using a standalone monogame and wanted to embed it in devExpress. How can I do this in the simplest way? Thanks for your help.

**Comment by SimonDarksideJ** [comment]
"devExpress" is not one of MonoGame's primary recommended development IDE's ([See here](https://docs.monogame.net/articles/getting_started/index.html))

Ideally, the same pattern than is used for VSCode and Rider should work for devexpress, but it is not clear from their documentation their support for pure dotnet projects.

But as it stands, we have no plans to support DevExpress at this time directly
