### ISSUE TITLE
The physical keyboard is detected as a gamepad

### ISSUE THREAD

**Issue by Demoleitor2000** [MonoGame/MonoGame#8463]
### Prerequisites

- [X] I have verified this issue is present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

3.8.1 - 3.8.2

### Which MonoGame platform are you using?

MonoGame Android Application (mgandroid)

### Operating System

Android 12

### Description

The physical keyboard is detected and act as a gamepad
This issue was Discussed in Discord
https://discord.com/channels/355231098122272778/1277883586162200687

### Steps to Reproduce

```
int movingter = 0;
            if (Keyboard.GetState().IsKeyDown(Keys.B))
            {

                movingter = 2;
            }else
            {
                movingter = 3;
            }
```

### Expected Behavior

I expect if i press some key on the keyboard in the game perform an action.

### Resulting Behavior

Nothing happpened when i press any key... only with the arrows because monogame detects the arrows as a gamepad d-pad... 
The next message i received with all keyboards i tried...
[MonoGame] Found new controller [0] Name of the keyboard.

**Comment by dellis1972** [comment]
@Demoleitor2000 thanks for the bug report. Can you try this when you get a moment and see if it works https://github.com/MonoGame/MonoGame/pull/8465.
