### ISSUE TITLE
Building on Ubuntu 23 fails

### ISSUE THREAD

**Issue by brentharts** [MonoGame/MonoGame#8477]
### Prerequisites

- [X] I have verified this issue is present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

git sep 5, 2024

### Which MonoGame platform are you using?

MonoGame Cross-Platform Desktop Application (mgdesktopgl)

### Operating System

Ubuntu

### Description

/home/rap/HolyBlender/MonoGame/MonoGame.Framework/Graphics/Vertices/VertexBuffer.cs(79,65): warning CS1573: Parameter 'type' has no matching param tag in the XML comment for 'VertexBuffer.VertexBuffer(GraphicsDevice, Type, int, BufferUsage)' (but other parameters do) [/home/rap/HolyBlender/MonoGame/MonoGame.Framework/MonoGame.Framework.Native.csproj]
/home/rap/HolyBlender/MonoGame/MonoGame.Framework/TextInputEventArgs.cs(11,46): warning CS1574: XML comment has cref attribute 'TextInput' that could not be resolved [/home/rap/HolyBlender/MonoGame/MonoGame.Framework/MonoGame.Framework.Native.csproj]
  MonoGame.Framework.Native -> /home/rap/HolyBlender/MonoGame/Artifacts/MonoGame.Framework/Native/Release/MonoGame.Framework.dll
  The package MonoGame.Framework.Native.1.0.0.1-develop is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are important.
  Successfully created package '/home/rap/HolyBlender/MonoGame/artifacts/NuGet/MonoGame.Framework.Native.1.0.0.1-develop.nupkg'.

========================================
Build DesktopGL
========================================
  Determining projects to restore...
  Restored /home/rap/HolyBlender/MonoGame/MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj (in 18.18 sec).
/home/rap/HolyBlender/MonoGame/MonoGame.Framework/Platform/Graphics/Texture2D.StbSharp.cs(5,7): error CS0246: The type or namespace name 'StbImageSharp' could not be found (are you missing a using directive or an assembly reference?) [/home/rap/HolyBlender/MonoGame/MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj]
/home/rap/HolyBlender/MonoGame/MonoGame.Framework/Platform/Graphics/Texture2D.StbSharp.cs(6,7): error CS0246: The type or namespace name 'StbImageWriteSharp' could not be found (are you missing a using directive or an assembly reference?) [/home/rap/HolyBlender/MonoGame/MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj]
An error occurred when executing task 'Build DesktopGL'.
Error: .NET CLI: Process returned an error (exit code 1).

### Steps to Reproduce

cd MonoGame
./build.sh

### Expected Behavior

compile native opengl exe

### Resulting Behavior

build failed

**Comment by JakeLegendXIII** [comment]
Hey @brentharts it looks like an issue with having the submodules. Did you run this command prior to building the source?

git submodule update --init

**Comment by stromkos** [comment]
**The Ubuntu builds are working fine.**

Your attempt to create a usable custom Nuget package from source failed,  as @JakeLegendXIII pointed out.

You must ensure all prerequisites are met prior to packaging and more importantly on the destination computers.

---

Not every computer running Blender has a Monogame compatible .Net framework installed. 


---

Your quest of noble intention requires much more attention to the details, such as using a fixed version. 

Using the ever-changing Master branch source as a base makes troubleshooting impossible. 

Use version or branch ids for consistency.

Here is corrected Python code for line 208+.
```
   cmd = 'git clone https://github.com/MonoGame/MonoGame.git'  # PLEASE select a version here
   cmd1 = 'git submodule update --init'
   print(cmd)
   subprocess.check_call(cmd)
   print(cmd)
   subprocess.check_call(cmd.1split())
```

**Comment by brentharts** [comment]
i updated my code to call `git submodule update --init`
but i still get this error:
```
  MonoGame.Framework.Native -> /home/rap/Net-Ghost-SE/MonoGame/Artifacts/MonoGame.Framework/Native/Release/MonoGame.Framework.dll
  The package MonoGame.Framework.Native.1.0.0.1-develop is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are important.
  Successfully created package '/home/rap/Net-Ghost-SE/MonoGame/artifacts/NuGet/MonoGame.Framework.Native.1.0.0.1-develop.nupkg'.

========================================
Build DesktopGL
========================================
  Determining projects to restore...
  Restored /home/rap/Net-Ghost-SE/MonoGame/MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj (in 24.16 sec).
/home/rap/Net-Ghost-SE/MonoGame/MonoGame.Framework/Platform/Graphics/Texture2D.StbSharp.cs(5,7): error CS0246: The type or namespace name 'StbImageSharp' could not be found (are you missing a using directive or an assembly reference?) [/home/rap/Net-Ghost-SE/MonoGame/MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj]
An error occurred when executing task 'Build DesktopGL'.
Error: .NET CLI: Process returned an error (exit code 1).
```

is there a way to build a minimal version of MonoGame on Ubuntu without so many external deps?
