### ISSUE TITLE
Remove useless dll when building release version

### ISSUE THREAD

**Issue by SteveSuv** [MonoGame/MonoGame#8499]
### Intent

when I run building command:
```sh
dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained
```

the publish dir will contains entire System dll. most of them are useless. so  why not remove useless items.

![image](https://github.com/user-attachments/assets/7b417681-ef91-4733-bbab-ca0c30b27f46)

### Motivation

it will reduce publish dir size at least 10MB, and make app launch faster.

**Comment by itsBuggingMe** [comment]
This isn't a thing that Monogame can control. The dlls are included because it is published self contained - so it will include the dotnet standard library.

**Comment by mrhelmut** [comment]
Please refer to the dotnet publish documentation: https://learn.microsoft.com/en-us/dotnet/core/deploying/
