### ISSUE TITLE
MGCB Editor will not build when referencing .net 8

### ISSUE THREAD

**Issue by GMoney132** [MonoGame/MonoGame#8501]
## Discussed in https://github.com/MonoGame/MonoGame/discussions/8497

<div type='discussions-op-text'>

<sup>Originally posted by **GMoney132** September 23, 2024</sup>
I have been pulling my hair out trying to get the MGCB editor to build with a very simple XML file I created using the Intermediate Serializer.

Simple class:
```c#
namespace TestLibrary
{
	public class Class1
	{
		public int Junk { get; set; } = 5;
		public string Stuff { get; set; } = "Yes.";
	}
}
```

Generated XML file:
```html
<?xml version="1.0" encoding="utf-8"?>
<XnaContent xmlns:TestLibrary="TestLibrary">
  <Asset Type="TestLibrary:Class1">
    <Junk>5</Junk>
    <Stuff>Yes.</Stuff>
  </Asset>
</XnaContent>
```

In the main project, I have added TestLibrary as a reference in the project and in the MGCB Editor.  When I build the editor, I get the error in the screenshot:
![Capture](https://github.com/user-attachments/assets/6ab30e24-49a7-4daf-b3e1-3ba22f6d764e)

I'm able to build with XML files that have only primitive types.  I can't seem to find anything to do with this error anywhere.  Any and all help is appreciated.</div>

This happens when the project targets .NET 8.

**Comment by dellis1972** [comment]
Have you upgraded the versions in the `.config/dotnet-tools.json`? You should be using version `3.8.2.1105` of the tools as it supports .net 8. The older versions are .net 6 only.

**Comment by dellis1972** [comment]
Also see https://docs.monogame.net/articles/migration/updating_versions.html#update-mgcb-editor.

**Comment by GMoney132** [comment]
Thank you for the link.  Manually updating the version number of the MGCB Editor fixed it.  I probably never would have found that.
