### ISSUE TITLE
MacOS: using Vulkan, remove DirectX and license change

### ISSUE THREAD

**Issue by ghost** [MonoGame/MonoGame#8529]
### Intent

How can I set monogame to use Vulkan on MacOS?

Why is DirectX needed in a CROSS-platform library? It's NOT cross-platform if it's needed. I was forced to install Wine on my Mac which I don't want. I also don't want to use proprietary DirectX code...

I also want to ask to remove DirectX dependency and make Monogame a true free open source software, which it is not currently. I depends on proprietary DirectX code

Monogame  should be published under GPLv3 license as FREE software without any non-free dependencies like DirextX removed.

https://www.gnu.org/philosophy/free-sw.html.en

https://www.gnu.org/licenses/gpl-3.0.html.en

### Motivation

The GPLv3 makes sure the future of Monogame is guaranteed. Current way of working (and license) is not.
It's not free software as defined by the FSF (https://www.fsf.org/), neither is the license!

https://www.gnu.org/philosophy/free-sw.html.en

**Comment by Apostolique** [comment]
Have you tried using the DesktopGL platform to release on the MacOS or Linux? I use it for all my games and it works fine. WindowsDX is a platform for releasing on Windows.

Currently the Vulkan platform isn't released as a package so you have to build it yourself from source.
