### ISSUE TITLE
Game window shifting randomly

### ISSUE THREAD

**Issue by Hardycore** [MonoGame/MonoGame#879]
Having a strange problem that I cannot figure out.
Whenever I launch my game, its random whether it displays properly or not. (see pics)

Some things of note:  1. I use the gamestatemanagementsample as the base for my game, originally developed for winphone and xbox/pc.
1. I implemented the scaling code in screenmanager found in the tutorials section.  Is this needed? 
   http://infinitespace-studios.co.uk/2012/07/19/handling-multiple-screen-resolutions-in-monogame-for-android-part-1/
2. This is all in a 800x480 emulator, running 4.0.4, have not tested on real devices.
3.  Should i be doing something to detect the native resolution of the device?  

I'm trying to finish off this port. so any help is greatly appreciated.

![](http://s10.postimage.org/mid0njis9/cutoff.jpg)
![](http://s9.postimage.org/fwb2puu4v/normal.jpg)

**Comment by cra0zy** [comment]
OpenTK related thing so closing...
