### ISSUE TITLE
GraphicsDevice.DrawInstancedPrimitives API not yet implemented in GL.

### ISSUE THREAD

**Issue by CartBlanche** [MonoGame/MonoGame#913]
As Per subject line. Just adding this here so we know it needs implementing.

**Comment by gruntbatch** [comment]
Out of curiosity, should this issue be marked as closed? It looks like #4195 may have solved both this issue and #914

**Comment by mgarstenauer** [comment]
#4195 only provides the DirectX implementation. OpenGL implementation is still missing. 
(--> We can remove the DirectX label.)

**Comment by tomspilman** [comment]
@mgarstenauer - Done and edited the title.
