### ISSUE TITLE
[Windows 8] Reference SplashScreen and SettingsPane

### ISSUE THREAD

**Issue by Nezz** [MonoGame/MonoGame#933]
Currently there is no way to access the SplashScreen from the game class. It involves a little bit of hacking, as we only receive its reference in the XAML's LaunchedEventArgs.
This is important because if we want correct loading behaviour, we need the Dismissed event of the SplashScreen. I think there should be a universal way to access it.
SettingsPane could also be referenced somewhere, but it is less of an issue as it can be accessed from CoreWindow.

**Comment by tomspilman** [comment]
We've removed Win8/8.1 support in https://github.com/MonoGame/MonoGame/pull/5809.
