### ISSUE TITLE
Songs not loading on Windows (Compressed or not)

### ISSUE THREAD

**Issue by WaaghMan** [MonoGame/MonoGame#948]
Loading a song the way it would load on XNA, throws an NotSupportedException "Specified stream is not a wave file.";

The content folder contains what XNA usually builds, a small .xnb file and a .wma song.

Song tries to load the file as a plain WAV file, but it is a .wma and crashes.

I know compressed songs are not supported yet, but until now, maybe the content processor should create a plain wave file that could be read. My inputs are WAV files anyway ( We use a XACT project on XBLIG games ).

**Comment by tgjones** [comment]
Think this is outdated? I haven't tried it, but MG must support songs on Windows now?

**Comment by MGZero** [comment]
No, it does not.  This is still an issue.  See the following:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/AudioLoader.cs#L36

**Comment by mrhelmut** [comment]
This code path is only relevant to OpenGL projects and loading files through ```SoundEffect.FromStream()```, which is only meant to work with WAV.

DirectX projects are working fine and manage WMA correctly now.

Can be closed, @tomspilman @KonajuGames

**Comment by MGZero** [comment]
Hold on a minute, I still receive this exception even on the development build by calling content.load() on a Song.  If it's not working in OpenGL, that's still an issue.  That said, AudioLoader is the only place in the code that exception is referenced, so it must be stemming from there.  Line 22 of Song.default.cs is calling SoundEffect.FromStream(), which would line up with what you're saying.

https://github.com/mono/MonoGame/blob/0b25f56e861fb602db884c40267b99ea947bae15/MonoGame.Framework/Media/Song.Default.cs#L22

**Comment by dellis1972** [comment]
@MGZero can you post a repo project? (along with the .xnb in question) then someone else can try to repo and then fix the issue.

**Comment by MGZero** [comment]
Of course, I'll get you something when I get home from work later!

**Comment by mrhelmut** [comment]
@MGZero What type of project are trying to create? ```Song.Default.cs``` is only used in Angle projects, any other OpenGL-based project types rely on ```Song.NVorbis.cs``` or platform specific API.
There must be something wrong with your project definition if it triggers this code path.

Did you run protobuild.exe and used the generated project files for the platform you're targeting?

**Comment by MGZero** [comment]
As it turns out, the monogame DLLs linked to my project were out of date.  Updated them to their correct versions and the wma files are loading correctly.
